### ISSUE TITLE
Prevent user from entering bad characters in input (e.g. no ',' in object names) (Bugzilla #647)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#100]
On 2012-03-30 11:07:52, @macumber wrote:

> Don't know if we want to handle at the gui or data layer, maybe we need escape characters?

**Comment by DavidGoldwasser** [comment]
Recently there was a bug with slash #1354 and we also have had issues with names longer than what EnergyPlus can have. I'll keep this open but add feature label. Instead of just being about comma's we should make sure name are valid, and will still be valid in E+. I'll make minor low frequency.

**Comment by jmarrec** [comment]
Still true in OS 2.2.1. I can put a "," in a construction name.
Yet I'm pretty sure these get knocked off during forward translation. the GUI might have been a better choice, but I'd say this is probably closable.

**Comment by DavidGoldwasser** [comment]
I'm fine closing this if @macumber and @asparke2 are ok. I still like being more strict up front, don't want to create issues with server later on because of odd characters in names, even if E+ will run.

**Comment by asparke2** [comment]
I'm fine to close
