### ISSUE TITLE
Coil Cooling/Heating Water to Air HP wrappers are empty in UI

### ISSUE THREAD

**Issue by muh182** [NREL/OpenStudio#1005]
@kbenne 
I checked 1.3.2, the Coil Heating Water To Air HP and Coil Cooling Water to Air HP wrappers are empty in the UI.

![capture2](https://cloud.githubusercontent.com/assets/2249257/2792424/3e21c520-cbd2-11e3-8674-f079d86fd65a.PNG)

**Comment by asparke2** [comment]
Coil Cooling/Heating Water to Air HP can only be used inside of unitary and zoneHVAC equipment, therefore, it should not be a library category.

**Comment by kbenne** [comment]
I don't have the specific commit on hand, but I just checked and this was fixed somewhere along the line. I think I probably threw in a fix with something else. I'm going to go ahead and close.
