### ISSUE TITLE
Phantom BCL measure showing up in "BCL Measures" window

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1013]
@macumber I can't really explain this. I see "Standard Reports" in the "BCL Measures" tab even after repeatably throwing away my BCL directory. As shown it is empty. I'm seeing this on 1.3.1 windows install and also on Develop, but the behavior varies a bit. On 1.3.1 if I try to use this measure it just doesn't come into the project. On my developer build (release) that same action crashes OS app. Haven't tried in PAT.

Note: that this measure shows in GUI without BCL flag. I confirmed that when I really download measures from BCL I do see the tag.

**Comment by asparke2** [comment]
Closing because I haven't seen this at all in 1.6.0.  We can reopen if we see it again.
