### ISSUE TITLE
OpenStudio App GUI doesn't include DesignSpecificationOA for Controller:MechanicalVentilation

### ISSUE THREAD

**Issue by mostaphaRoudsari** [NREL/OpenStudio#1018]
@kbenne I imported an idf file and assigned VAV system from the template to zones. When I generate the idf file/run the analysis it leaves Design Specification Outdoor Air Object Name empty in Controller:MechanicalVentilation. I have already generated DesignSpecification: OutdoorAir in the idf file.

I've noticed that if I model everything in OpenStudio SketchUp and then bring it to OS app the field will be filled with the right OutdoorAir object name. How should I generate the idf file to make this also happen for my file? Is there any specific object that you are looking for in the idf file?

Here is the original idf file: https://dl.dropboxusercontent.com/u/16228160/OpenStudioFiles/010.idf
the osm file with systems assigned to zones: https://dl.dropboxusercontent.com/u/16228160/OpenStudioFiles/010.osm
and the exported idf file: https://dl.dropboxusercontent.com/u/16228160/OpenStudioFiles/in.idf

**Comment by asparke2** [comment]
Closed because not working on ReverseTranslator anymore.

**Comment by macumber** [comment]
@asparke2 what do you mean by "not working on ReverseTranslator anymore."?

@kbenne
