### ISSUE TITLE
ZoneLists are not translated IDF->OSM

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1019]
https://github.com/NREL/OpenStudio/blame/develop/openstudiocore/src/energyplus/ReverseTranslator.cpp#L854

@DavidGoldwasser @mostaphaRoudsari

**Comment by asparke2** [comment]
Closed because we aren't working on the ReverseTranslator any more.

**Comment by mostaphaRoudsari** [comment]
Ah! Does it mean that OpenStudio is not intended to support idf import anymore? I think it will make it really hard for many of the users to change to OpenStudio from EP specially for advanced EP users who already have they workflows built in EP. :disappointed:

**Comment by macumber** [comment]
@mostaphaRoudsari we aren't planning on deprecating any of the IDF->OSM translation that we already have, we are just not expanding the scope to include translation of more things (specifically HVAC).

This one strikes me as something we should be translating but are just not doing correctly.  I would consider re-opening, @asparke2 what do you think?

**Comment by jmarrec** [comment]
@macumber can you please look at your 4 year-old comment above and assess whether it really should stay open or not? At least I'd label this as "Enhancement request"

**Comment by macumber** [comment]
@mostaphaRoudsari is this an important feature for you?

**Comment by jmarrec** [comment]
@mostaphaRoudsari ping! Is this an important feature for you?

**Comment by jmarrec** [comment]
There seems to be a couple of mixups that could potentially be fixed easily.

Here, this should call `translateZoneList` instead:

https://github.com/NREL/OpenStudio/blob/b849d913172a961ce3cd8a1b5734e7cd1f44a8cf/openstudiocore/src/energyplus/ReverseTranslator.cpp#L1058:L1062

Here is should be ZoneList:

https://github.com/NREL/OpenStudio/blob/b849d913172a961ce3cd8a1b5734e7cd1f44a8cf/openstudiocore/src/energyplus/ReverseTranslator/ReverseTranslateZoneList.cpp#L51

**Comment by mostaphaRoudsari** [comment]
@jmarrec, thanks. we don't really use it for out workflows currently but if this import will do something like importing the ZoneList as a space type it will useful. From what I understand it is not critical to us right now.

@chriswmackey, any thoughts on this?

**Comment by jmarrec** [comment]
I can do the changes I listed. Note that this is coarse though, it will create a space type for each zonelist it finds, but if a zone is referenced by multiple zonelists, its spaces will end up with a spacetype correaponding to the last zonelist it found that references it. You'll get a warning that the previous spacetype was overwritten though

**Comment by chriswmackey** [comment]
I agree this is a very low priority for us and I have yet to encounter IDFs in my own work that make use of the ZoneList. Still, it seems like it's something important to support in order to say that OpenStudio supports the importing of basic Zone geometry from IDF. Whatever implementation you end up going with is fine by me, whether its importing each ZoneList as a SpaceType or just ignoring the ZoneList altogether and importing each zone as an individual contained unit (with duplicated versions of the properties shared across the ZoneList).

**Comment by jmarrec** [comment]
Fixed via #3776 in develop3
