### ISSUE TITLE
Run Tab - Progress bar hangs out at 75% most of the time (Bugzilla #654)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#102]
On 2012-04-06 08:31:54, @DavidGoldwasser wrote:

> would be nice if it showed some progress as EnergyPlus goes through the annual simulation.

**Comment by DavidGoldwasser** [comment]
I agree, would be nice to improve this but would need to get access to standard output to do so. With 8.2 we are not even getting that, which is what users have used to gauge progress instead of our progress bar.
