### ISSUE TITLE
gbXML import does not support all length units

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1031]
https://openstudio.nrel.gov/forums/openstudio-plug-sketchup/help-desk/error-could-not-translate-surface-gbxml#comment-3581

OpenStudio does not currently accept the following length units "Kilometers", "Centimeters", "Millimeters", or "Yards".

**Comment by macumber** [comment]
Also does not check units on material properties

**Comment by jasondegraw** [comment]
I'm going to close this because the top level issue has been addressed. Will add a separate issue for the materials units.
