### ISSUE TITLE
measure runner attributes not the right type

### ISSUE THREAD

**Issue by nllong** [NREL/OpenStudio#1032]
@macumber, I thought i would start the thread here so that I can share what I am seeing.

If i do this in a ruby script

```
result = runner.result
result.attributes.each { |att| @output_attributes << att }"
```

then try to look at @output_attributes... they show up as.

```
[
  {"__swigtype__":"_p_openstudio__Attribute"},
  {"__swigtype__":"_p_openstudio__Attribute"},
  {"__swigtype__":"_p_openstudio__Attribute"}
]
```

I have added these methods

```
  @model.getFacility
  @model.getBuilding
```

**Comment by asparke2** [comment]
@macumber @nllong is this still valid?
