### ISSUE TITLE
MS Visual C++ 2010 Express does not respect dependency hierarchy or number of processors.

### ISSUE THREAD

**Issue by elainethale** [NREL/OpenStudio#1033]
When I tried to build openstudio_analysis, after only having built openstudio_utilities_tests, both with and without "BUILD_WITH_MULTIPLE_PROCESSES" enabled, VS 2010 Express started trying to build all the missing projects in the chain AT THE SAME TIME, even though max processes was set to 4 and this does not respect dependencies. Application lock-up and build failures due to missing libraries of course ensue. I should be able to work around this by building piecemeal. (I'll try ALL_BUILD too, to see if it behaves better for some reason.)

**Comment by asparke2** [comment]
Closed since we have moved to VS 2012.  The only people who would hit this now are...?
