### ISSUE TITLE
Unhandled Exception Causes Open Studio to crash at the end of simulation

### ISSUE THREAD

**Issue by CUEBoxer** [NREL/OpenStudio#1036]
![image](https://cloud.githubusercontent.com/assets/6518490/2933043/e58e3d50-d7b9-11e3-95fd-9069ece80917.png)

This error causes OS to crash after a simulation is complete, and possibly during writing the sql file.

**Comment by asparke2** [comment]
Closing as invalid.  This is a generic crash dialog, not enough info to reproduce this crash.
