### ISSUE TITLE
Surfaces incorrectly matched after extrude and intersect of matched surface

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1039]
If you match surfaces in two spaces, then pull roof up in one space you get large wall matched to smaller one.  If you run intersect it breaks the surface into two pieces that are matched to the smaller wall.  Should be a way to unmatch those surfaces and rerun surface matching.

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/32
