### ISSUE TITLE
Error on cut/paste/cut of space (Bugzilla #661)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#104]
On 2012-04-13 15:55:15, @macumber wrote:

> Draw a space, cut it, paste it, cut again will generate an error

On 2012-05-24 15:47:23, @DavidGoldwasser wrote:

> Dan, I can't reproduce this? Can you try it again on your machine?
> Tested with trunk on 052212

**Comment by DavidGoldwasser** [comment]
Related to observers.
