### ISSUE TITLE
Copying measures by hand creates issues

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1047]
If you copy a measure in my measures directory by hand then update this will cause two measures with the same uuid.  This will cause problems in PAT, need to warn the user when this is detected.

**Comment by asparke2** [comment]
This seems like something that measure manager would be responsible for.

**Comment by macumber** [comment]
Measure manager can detect this, but we aren't passing it on to PAT or OS App for them to display to the user

**Comment by macumber** [comment]
This came up when we were testing simuwatt (and many more times past that).  No matter how many times we tell people to use the apps to copy measures, they will still copy and paste measures in their my measures directory.

**Comment by jmarrec** [comment]
I cannot see a valid way to go around that. That is a user problem really.

Changing the UUID upon detection of a duplicate is ill-advised (how do you determine which one to change? Reminding that the BCL uses that UUID for updating to new version etc).

the console would already pop up warning messages (in the OSApp at least). I'm closing, but happy to reproduce if someone has a good idea on a specific change.
