### ISSUE TITLE
Using Project Loose Geometry on a large model is very slow (many sub surfaces make files slow for many tasks) (Bugzilla #663)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#106]
On 2012-04-16 12:52:54, @DavidGoldwasser wrote:

> Created an attachment (id=159)
> File made in support of Stantec
> 
> Attached is OSM model I made for Stantec of Walmart project. It has 20 spaces, 154 base surfaces and 277 sub surfaces (mostly skylights).
> 
> When I open this file and draw six rectangles for loose geoemtry (on a single space), it takes about 35 seconds for the windows to show up and another 70 seconds for the processor to slow down.
> 
> In this test I check the box to project loose geometry vs. all geometry, however in this case it should not make a difference, There wasn't any other non-OS geometry.

On 2012-04-16 13:05:27, @DavidGoldwasser wrote:

> Ran similar test with base drawing imported (as a group) with 150 edges in it. Minimal impact on times reported in first test.
> 
> But here is the interesting thing. I have an earlier version of this mode (a vs. e) that has same spaces, but no sub-surfaces yet. Running this same test on that produces times of 3.5 seconds to create the six windows, and then another 2.5 for the processor to slow down.
> 
> So the question is why does having all of the additional sub-surfaces in the model have an impact here. Only 7 of the skylights were in the zone where I was adding new surfaces (and none of them shared the same base surface with the skylights, so there shouldn't have been any reason to check if they overlap).

On 2012-04-16 13:13:20, @DavidGoldwasser wrote:

> Created an attachment (id=160)
> Source file prior to adding skylights
> 
> Another question to ask could be why the "a" file opens quickly and the "e" file opens slowly.
> 
> File A (opens in 3.5 seconds, processor recovers in additional 4.5 seconds)
> 
> File B (opens in 105 seconds, processor recovers in additional 4.5 seconds)
> 
> We had issues long ago in legacy with subsurfaces. Maybe they are all checking both if they are contained by their base surface and if they are in plane with their base surface? and that is causing the slowdown. If so I'd be fine moving that testing into the diagnostic script and not having it as part of the basic workflow. This would have the added benefit of support for files with offset sub-surfaces (although would be little odd in SketchUp since not hosted by base surface). I know long term plan is window as SketchUp component vs. loose geometry

On 2012-05-04 09:43:04, @DavidGoldwasser wrote:

> <Batch Comment 05/04/12 - Bug added to Pivotal>

On 2012-05-10 16:41:56, @DavidGoldwasser wrote:

> I need to do more testing on this tomorrow.

On 2012-05-10 16:42:44, @DavidGoldwasser wrote:

> <batch change - re-validated with OpenStudio 0.7.3>

On 2012-05-24 09:34:21, @DavidGoldwasser wrote:

> Saw some odd behavior with this fixed. See attached screenshot. A surface in space that did not have windows added became un-responsive to render mode changes. If the file was re-opened things were fine, but seemed risky. Will push this back to 0.9 vs. 0.8 release. Hopefully we can get much more dramatic speed improvements. this fix was just 3x faster for projecting and same speed for opening.

On 2012-05-24 09:36:05, @DavidGoldwasser wrote:

> Created an attachment (id=172)
> Ver e file updated to 0.7.4 (prior to projecting new geometry)

On 2012-05-24 09:38:12, @DavidGoldwasser wrote:

> Created an attachment (id=173)
> Screenshot of rendering issue after projecting loose surfaces

On 2012-05-24 15:24:35, @DavidGoldwasser wrote:

> <re-validated with OpenStudio Trunk 052212>

On 2012-09-10 00:40:09, @DavidGoldwasser wrote:

> The issue on model is not the model being large, but having a large number of sub-surfaces hosted by a single base surface. Look at 0.8.x performance testing to see impacts in other areas (open, matching, intersection)

On 2012-09-10 08:16:34, @DavidGoldwasser wrote:

> <changed status of bugs in Pivotal to Assigned>

Original attachments:
* 4_13e.osm (ID 159)
* 4_13a.osm (ID 160)
* 05_23e_075.osm (ID 172)
* 0524_bug663.png (ID 173)

Keywords: Performance

**Comment by DavidGoldwasser** [comment]
Dan did some work to address sub-surface performance issues.
