### ISSUE TITLE
Schedule translator not working (Bugzilla #668)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#108]
On 2012-04-20 07:54:45, @macumber wrote:

> https://openstudio.nrel.gov/forums/openstudio-plug-google-sketchup/help-desk/importing-schedules#comment-1224

On 2012-05-10 16:05:34, @DavidGoldwasser wrote:

> Well I can't get the same error as the user, but I also can't import schedules form IDF files (either form E+ example file or from IDF files made by OpenStudio.
> 
> Here is what I see:
> 
> C:/EnergyPlusV7-0-0/ExampleFiles/4ZoneWithShading_Simple_1.idf is not valid to draft strictness 
>  The collection is INVALID at strictness level 'Draft', because of the errors:
> Object     level data error of type NoIdd             .
> Error pertains to an object of type 'Catchall', named ''.
> Additional information about the error type: input data definition is missing or empty.

On 2012-05-10 16:42:44, @DavidGoldwasser wrote:

> <batch change - re-validated with OpenStudio 0.7.3>

**Comment by DavidGoldwasser** [comment]
Not enough information to reproduce.
