### ISSUE TITLE
New checksum is much slower

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1099]
Looks like this implementation is less than ideal, much more time is spent in checksumIgnore than in actually computing the checksum.  I suggest we don't fix until after release.

Time    Time with Children  Hit Count   Routine Name
37.6740804332664    37.6740804332664    165974025   openstudio::detail::checksumIgnore
1.22908011713125    1.22908011713125    162388  boost::crc_optimal<32,79764919,4294967295,4294967295,1,1>::process_block
0.00020417962693176 0.000274598018018454    500 boost::detail::crc_table_t<32,79764919,1>::init_table
0.000218893496515676    0.000218893496515676    500 boost::detail::reflector<32>::reflect

**Comment by asparke2** [comment]
Changing to minor.  Haven't noticed any lag when syncing measures with project, even when I'm in the NREL-measures directory.
