### ISSUE TITLE
Imported gbXML file gets triangulated sub surface (Bugzilla #672)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#111]
On 2012-04-24 09:23:23, @macumber wrote:

> Created an attachment (id=163)
> Problem file
> 
> https://openstudio.nrel.gov/forums/openstudio-plug-google-sketchup/help-desk/gbxml-import-errors
> 
> Note, level data does not come in because buildingStoryId attribute of space elements is not set, instead vasari appends level name to space name

On 2012-05-10 14:41:52, @DavidGoldwasser wrote:

> Created an attachment (id=168)
> screenshot of model
> 
> Looks like this is limited to a single surface named aim41963. Wonder if it is some tolerance issue with it being out of Plane and it is being altered in SketchUp.

On 2012-05-10 16:42:45, @DavidGoldwasser wrote:

> <batch change - re-validated with OpenStudio 0.7.3>

Original attachments:
* ExampleGBXLMfromVasari2.xml (ID 163)
* bug672_screenshot.png (ID 168)

**Comment by DavidGoldwasser** [comment]
I think Dan has done some work to surfaces that can in as invalid. That may have also addressed this. If new reports come in I'll re-open or make a new issue.
