### ISSUE TITLE
When  you add a new script the dirty flag doesn't show up unless you load arguments (Bugzilla #684)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#112]
On 2012-05-03 13:56:27, @DavidGoldwasser wrote:

> As a result you can accidentally close a file without being warned to save it.

On 2012-05-10 16:42:47, @DavidGoldwasser wrote:

> <batch change - re-validated with OpenStudio 0.7.3>

**Comment by DavidGoldwasser** [comment]
I'm going to assign to me to re-confirm if this happens.
