### ISSUE TITLE
Simulation fails if ground preprocessor boundary conditions are used

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1127]
Should ideally run slab/basement like this measure https://github.com/NREL/OpenStudio-measures/tree/develop/NREL%20working%20measures/AedgK12SlabAndBasement

**Comment by asparke2** [comment]
We should look at the GroundDomain objects added in E+ 8.2 instead of the slab/basement preprocessors.

**Comment by macumber** [comment]
With introduction of Kiva objects by @joseph-robertson should we remove these slab and basement objects?  Are we actively using them @DavidGoldwasser @asparke2 ?

**Comment by DavidGoldwasser** [comment]
We are actively using GroundDomain:Slab objects, but not slab and basement pre-processor. I'd like to switch everything over to Kiva as soon as I can instead of GroundDomain.

**Comment by macumber** [comment]
@joseph-robertson can we close this?  Are we moving over to Kiva?  I wonder if we have to remove these options from OS:Surface?

**Comment by jmarrec** [comment]
ping @joseph-robertson
