### ISSUE TITLE
OpenStudio::SqlFile.execAndReturnVectorOfDouble does not work (Bugzilla #685)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#113]
On 2012-05-04 08:36:25, Eric Bonnema wrote:

> The 'get' method does not work on what is returned by called this method. See attached zip file for simulation files and example script, bug.rb. OpenStudio::SqlFile.execAndReturnVectorOfString works however.

On 2012-05-04 08:38:56, Eric Bonnema wrote:

> Created an attachment (id=166)
> All files needed to reproduce the bug. Removed E+ executable (Windows-64 7.0.0.036) because of size limitations.

On 2012-05-04 08:52:30, @macumber wrote:

> May just need to swig the template type optional, vector, double

Original attachments:
* EnergyPlus.zip (ID 166)

**Comment by DavidGoldwasser** [comment]
This is used a lot now by reporting measures, so issue must have been resolved.
