### ISSUE TITLE
Failed to compute arguments for measure: code converter not found (UTF-16LE to UTF-8)

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1132]
Trying to test the Space Type and Construction Set Wizard in 1.4.1, and I get this error when I drag it into OpenStudio App measures tab.

This is the only measure I have that uses a JSON file. It runs in Ngrid spreadsheet workflow. In 1.4.0 GUI I get a different error.

"Failed to compute arguments for measure: . . . . ruby\1.8/rubygems/custom_require.rb:31in 'gem_original_require': no such file to load --json"

cc: @axelstudios

**Comment by asparke2** [comment]
Closing.  Since we've switched to ruby 2.0.0, this isn't an issue.
