### ISSUE TITLE
File made in 0.7.0 crashes on open in 0.7.3 (Bugzilla #691)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#115]
On 2012-05-09 08:53:34, @DavidGoldwasser wrote:

> Created an attachment (id=167)
> File I made in 0.7.0
> 
> I made the attached filein 0.7.0. It still opens fine in the 0.7.3 SketchUp pluin, doesn't shown any validity errors on open, and the diagnostic script doesn't catch anything. Yet when I open it in the 0.7.3 OpenStudio app it crashes.

On 2012-05-10 16:42:48, @DavidGoldwasser wrote:

> <batch change - re-validated with OpenStudio 0.7.3>

Original attachments:
* school_demo_02.osm (ID 167)

**Comment by DavidGoldwasser** [comment]
This may have been related to objects with duplicate name which resulted in no errors, but a file that appeared to be empty.
