### ISSUE TITLE
Can't identify simulation error in 1.4.x PAT run

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1159]
This is clean model built up with measures. Nice the 95k E+ errors. There is no error shown, seems like odd failure.

@macumber I'm not assigning it to anyone now, because I don't really know what is going wrong.

![8-7-2014 10-29-51 am](https://cloud.githubusercontent.com/assets/4857055/3845249/9a36563e-1e50-11e4-8a1a-f907e27cc03e.png)

**Comment by asparke2** [comment]
@DavidGoldwasser do you have a PAT project to reproduce this?

**Comment by DavidGoldwasser** [comment]
Stale, issue.
