### ISSUE TITLE
Loops Tab - Supply side and design side graphic can get out of sync (Bugzilla #697)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#116]
On 2012-05-15 08:43:08, @DavidGoldwasser wrote:

> Created an attachment (id=170)
> screenshot of graphic glitch on loop
> 
> To duplicate what is shown on the attached image create an air loop and then add 2 or more zones to it (need more then one so splitter/mixer shows up) Then delete a component from the supply side of the loop. The right side of the loop should now be broken.

On 2012-05-21 08:58:11, @DavidGoldwasser wrote:

> <batch converting unconfirmed bugs to new, 5 bugs>

On 2012-09-06 23:27:16, @DavidGoldwasser wrote:

> While minor a number of people (internal and external) have hit this and pointed it out. Should be low risk fix?

Original attachments:
* 0514_loop_graphic_glitch.PNG (ID 170)

**Comment by DavidGoldwasser** [comment]
I haven't seen this in a long time.
