### ISSUE TITLE
Non repeatable cloud error.

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1160]
This loos like it started a server but not workers. I had to manually terminate them. When I tried to re-start cloud it worked fine. I wanted to document here anyway in case others see it. This was using 1.4.0 installer on windows 7.

![8-7-2014 11-07-51 am](https://cloud.githubusercontent.com/assets/4857055/3845935/9d060c68-1e57-11e4-8e45-762cf7916aeb.png)

**Comment by asparke2** [comment]
Closing.  We can reopen if we hear about this happening again.
