### ISSUE TITLE
Info Messages not showing on cloud run

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1161]
This sounds like an old bug. Not sure if it wasn't fixed or was fixed and came back. As shown, the local run job shows this, but not the cloud run. All measures and datapoints had similar outcome.

![pat0814_cloud_wherearemessages](https://cloud.githubusercontent.com/assets/4857055/3846075/1d17a3ac-1e59-11e4-98ea-8d571a21e02b.png)

![pat0814_cloud_wherearemessageslocalrun](https://cloud.githubusercontent.com/assets/4857055/3846077/26cd377c-1e59-11e4-9de2-4a093d838d89.png)

**Comment by DavidGoldwasser** [comment]
@DavidGoldwasser should re-verify

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
