### ISSUE TITLE
Scripts Tab - ImportIdfFile.rb has error, below is updated text that Dan fixed (Bugzilla #698)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#117]
On 2012-05-15 15:17:28, @DavidGoldwasser wrote:

> I don't currently have SVN checked out, so couldn't commit this.
> 
> 
> 
> ######################################################################
> #  Copyright (c) 2008-2010, Alliance for Sustainable Energy.  
> #  All rights reserved.
> #  
> #  This library is free software; you can redistribute it and/or
> #  modify it under the terms of the GNU Lesser General Public
> #  License as published by the Free Software Foundation; either
> #  version 2.1 of the License, or (at your option) any later version.
> #  
> #  This library is distributed in the hope that it will be useful,
> #  but WITHOUT ANY WARRANTY; without even the implied warranty of
> #  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
> #  Lesser General Public License for more details.
> #  
> #  You should have received a copy of the GNU Lesser General Public
> #  License along with this library; if not, write to the Free Software
> #  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
> ######################################################################
> 
> require 'openstudio'
> 
> class ImportIdfFile < OpenStudio::Ruleset::WorkspaceUserScript
> 
>   def name
>     return "Import Idf File"
>   end
>   
>   def arguments(workspace)
>     result = OpenStudio::Ruleset::UserScriptArgumentVector.new
>     
>     idf_file_path = OpenStudio::Ruleset::UserScriptArgument::makePathArgument("idf_file_path",true,"idf")
>     idf_file_path.setDisplayName("Idf File Path")
>     result << idf_file_path
>     
>     return result;  
>   end
>   
>   def run(workspace, runner, arguments)
>     idf_file_path = arguments["idf_file_path"]
>     
>     if not idf_file_path or not idf_file_path.hasValue
>       raise "The IDF file path must be defined."
>     end
>        
>     idfFile = OpenStudio::IdfFile::load(idf_file_path.valueAsPath)
>     if idfFile.empty?
>       raise "Unable to load IdfFile from " + idf_file_path.valueAsPath.to_s + "."
>     end
>     
>     idfFile = idfFile.get
>     objects = idfFile.objects
>     wsObjects = workspace.addObjects(objects)
>     if wsObjects.size < objects.size
>       warn "Only added #{wsObjects.size} of the #{objects.size} objects in the IDF file " + idf_file_path.valueAsPath.to_s + "."
>     end
>   end
> 
> end
> 
> ImportIdfFile.new

On 2012-05-21 08:58:12, @DavidGoldwasser wrote:

> <batch converting unconfirmed bugs to new, 5 bugs>

**Comment by DavidGoldwasser** [comment]
deprecated
