### ISSUE TITLE
SpaceTypeAndConstructionSetWizard should warn user if data is missing

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1170]
This is related to #1169 in which part of the expected data set is missing. The measure and its similar implementation in the SketchUp Plugin is someone graceful in that there is no ruby error and it does make the objects it can. But it should also issue a warning to the user. It is a bit tricky since the script doesn't know how many space types to expect, but it should never be 0. The same is true for construction sets.

**Comment by asparke2** [comment]
Changing to feature request since it works as designed, but this is would still be a good thing to add.

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/31
