### ISSUE TITLE
Issue in model with mixed air setpoint managers in model made in original 1.4.0 installer.

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1171]
The issue showed up as a crash when looking at the control tab with affected air loop selected. The original 1.4.0 was fine but the newer 1.4.0 installer was affected, as is the current develop branch.

The was able to confirm this was the issue be removing the mixed air setpoint managers on a copy o the model. Scheduled or outdoor air reset setpoint managers didn't seem to be affected.

**Comment by asparke2** [comment]
@DavidGoldwasser do you have the model to reproduce this with?

**Comment by kbenne** [comment]
@DavidGoldwasser Is this bug still alive?  I have it in my Pivotal queue, but I am not able to reproduce.

**Comment by DavidGoldwasser** [comment]
Sorry, for some reason file didn't make it into repo. I just forward it the file and user email to both of you. You can check it it in current build and close if it isn't an issue anymore.
