### ISSUE TITLE
When in "Schecules" sub tab of "Schedules 

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1179]
See attached screenshot. When I'm in the "Schedule Sets" sub tab I can see ruleset schedules. When I'm in the "Schedules" sub tab I only see "Schedule Ruleset"Objects.Seems to be an old but that I just happened to notice now when I was trying to bring in a schedule from a library vs. a schedule set.

![8-29-2014 8-29-08 am](https://cloud.githubusercontent.com/assets/4857055/4091506/3cec4e30-2f89-11e4-9abc-62b6c70d9aa6.png)
.

**Comment by asparke2** [comment]
Closing.  This is by-design (since this tab can only edit schedule-rulesets, only those types of schedules are available to be dropped in here).
