### ISSUE TITLE
Deleting Construction Set object leaves sub-set objects behind (Bugzilla #704)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#118]
On 2012-05-24 15:43:08, @DavidGoldwasser wrote:

> Similar to 689 and 662 and the delete thermal zone issue, we are orphaning objects when we delete a construction set. The 4 sub set objects that underlying it are left behind.
> 
> <re-validated with OpenStudio Trunk 052212>

**Comment by DavidGoldwasser** [comment]
May still be issue, but minor and low frequency issue. The purge unused and orphan objects I wrote may address this, but may still be something we should do in code, it would have to check that the object isn't used by other construction sets.

**Comment by jmarrec** [comment]
Still true today. But perhaps that is the expected behavior, and the purge button can be an option

**Comment by evanweaver** [comment]
Previously fixed. Tested with 2.4.0.
