### ISSUE TITLE
openStudioVersion in OpenStudio.hxx is difficult to configure correctly (Bugzilla #707)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#119]
On 2012-05-29 11:40:58, @macumber wrote:

> Currently, programmer must change version identifier in their cmake cache manually for version translator to work, this is an easy step to miss.

On 2012-06-06 10:41:10, @macumber wrote:

> Also, the version is set in both the Idd and the configured file.  If a developer does not configure correctly you can end up out of synch.  It appears that idd version is used when writing a file but configured version is used when opening, this can lead to situation where app can write files that it cannot read.  
> 
> Can we just use the idd version and remove the configured file?

**Comment by DavidGoldwasser** [comment]
Super build addresses this.
