### ISSUE TITLE
Loops Tab - OpenStudio lets you add fan to plant loop (Bugzilla #711)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#120]
On 2012-05-31 12:36:40, @DavidGoldwasser wrote:

> When on air loop you are protected from doing things like adding boiler. Plant loop doesn't seem to have that. This is true in ruby as well, not just app.

On 2012-09-06 23:24:03, @DavidGoldwasser wrote:

> *** Bug 845 has been marked as a duplicate of this bug. ***

On 2012-09-06 23:25:00, @DavidGoldwasser wrote:

> GUI will also let me drop Evap Cooler on demand side of air loop

**Comment by DavidGoldwasser** [comment]
I'm going to close this, It may have been fixed, but if not could be part of wider feature to tighten up component placement, or do pre-flight.
