### ISSUE TITLE
App Opening Delayed When Offline

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1203]
I've noticed in 1.2 - 1.4 the OS app takes much longer to open when not connected to the internet. Our My Measure path points to a network drive so I suspect this may be the cause of the issue.

**Comment by macumber** [comment]
@MatthewSteen this should be fixed in 1.5.5 can you confirm?

**Comment by MatthewSteen** [comment]
@macumber - will try this tonight from home.

**Comment by MatthewSteen** [comment]
@macumber - here are the messages I get when opening a new model and when opening a 1.5.0 model respectively.

![v1 6_error_open1](https://cloud.githubusercontent.com/assets/8397034/5781759/989f2df4-9d72-11e4-9764-d539842d0542.png)

![v1 6_error_open2](https://cloud.githubusercontent.com/assets/8397034/5781762/9c16811c-9d72-11e4-8490-bdfd0d5f0803.png)

**Comment by macumber** [comment]
Thanks @MatthewSteen, when you got this 1) was your My Measures directory set to a network location, 2) was that network location available, 3) did your OSM have any measures in it?

**Comment by MatthewSteen** [comment]
@macumber - yes to all. Also note that this was at work when connected to our net drives.

**Comment by asparke2** [comment]
Made this normal priority since many consulting firms are using network drives to share measures.

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
