### ISSUE TITLE
QWebkit seems to be slower parsing large objects in Javascript 

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1211]
Seems to have gotten worse after Qt 5:

http://qt-project.org/forums/viewthread/41682

http://stackoverflow.com/questions/25299253/javascript-in-qt-5-3-webkit-qwebview-is-too-slow-and-hang-the-mainwindow-on-win#comment40751450_25299253

http://blog.qt.digia.com/blog/2013/09/12/introducing-the-qt-webengine/

Fix may be to move over to QWebEngine in the future

**Comment by asparke2** [comment]
Changing to feature request because it currently works (albeit slowly), which is inherent to the QWebkit.  @axelstudios will update to QWebEngine at some point.

**Comment by macumber** [comment]
@axelstudios Looks like Qt 5.5 is released, maybe we should see if this fixes things?  http://blog.qt.io/blog/2015/07/01/qt-5-5-released/

**Comment by axelstudios** [comment]
About time - looks like a pretty good update.  I'll try it out

**Comment by evanweaver** [comment]
Closed due to updates.
