### ISSUE TITLE
Confusing message when installing just the legacy plugin (Bugzilla #714)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#122]
On 2012-05-31 13:46:34, @macumber wrote nothing.

On 2012-05-31 13:47:00, @macumber wrote:

> Created an attachment (id=174)
> Screenshot from Linda

Original attachments:
* Doc2.docx (ID 174)

**Comment by DavidGoldwasser** [comment]
Stale, will close this.
