### ISSUE TITLE
Measure's incorrectly show as broken in app

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1232]
@asparke2 was seeing this in apply measures now dialog, I think the measure was one of the BarAspectRatio measures in the measures repo

**Comment by MatthewSteen** [comment]
@macumber - I'm noticing this in 1.5.0 with a My Measure that previously displayed as unbroken. It changed to broken after I altered/saved the XML file.

**Comment by macumber** [comment]
Can you upload the measure to dropbox or something and provide a link?

**Comment by macumber** [comment]
I believe this is fixed by https://github.com/NREL/OpenStudio/commit/fbe2aacc2f6f5d5720739eaeabeb3fe6c3b9d164
