### ISSUE TITLE
SPM "Magic" doesn't work right if there are multiple fans on the supply side of AirLoopHVAC

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#1241]
In scenarios with return fans, there are SPM clones where there should be mixed air set point managers.

Around here: https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVAC.cpp#L98  the proposed solution is to use fans.back to retrieve the last fan instead of the first.  

The current work around is to place SPMs manually thus preventing OS from trying to do fancy set point manager logic for you.

**Comment by macumber** [comment]
@kbenne can you prioritize and add to pivotal if needed?
