### ISSUE TITLE
Clone measure adds space in front of name and "A" to class)

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1242]
This is kind of odd, I confirmed it didn't happen in 1.4 I'm using one of the 1.5 installer right now. If I delete the lading space in the display name the "A" goes away from the class name

![10-14-2014 11-59-17 am](https://cloud.githubusercontent.com/assets/4857055/4634894/70d140c4-53d4-11e4-906d-763ed1cfcd82.png)

**Comment by macumber** [comment]
@DavidGoldwasser A class name can't start with a space that is why the A is added

**Comment by DavidGoldwasser** [comment]
I didn't intend to put a space in the front, the original measure didn't have a space. At any rate, this doesn't seem to happen anymore, so I'll close this.
