### ISSUE TITLE
library objects can be dropped into drop downs

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1246]
The GUI allows the user to drop a library object into an editable drop down menu which results in the text from the object being entered and an immediate failure in 1.4.0 (still allowed in 1.5.0).

![tag drop1](https://cloud.githubusercontent.com/assets/8397034/4696231/552ad1c4-57d9-11e4-80eb-edb0147c312d.jpg)
![tag drop2](https://cloud.githubusercontent.com/assets/8397034/4696232/588d0e90-57d9-11e4-8bc0-aed93e33fb27.jpg)

**Comment by macumber** [comment]
@evanweaver I do not see this anymore, did you fix this bug?

**Comment by evanweaver** [comment]
@macumber I fixed the behavior mentioned in this bug, but I wasn't aware of this bug specifically.
