### ISSUE TITLE
Long path problems (Bugzilla #726)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#126]
On 2012-06-07 14:52:58, @macumber wrote:

> Windows paths are limited to 260 characters, functions that save or load files to paths longer than this may fail.  Qt seems to have handled this and the following workaround was used in openstudio app:
> 
> http://stackoverflow.com/questions/341550/on-windows-when-should-you-use-the-filename-prefix
> 
> Need to get consistent about how we work with paths to avoid this.

**Comment by DavidGoldwasser** [comment]
I assume work around fixed specific issue.
