### ISSUE TITLE
PAT cloud can get stuck

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1261]
If running data point and it does not return a correctly formed pat_data_point value in the datapoint json, PAT will not correctly determine that an undefined error occured (I'm not sure if there is a state for this).  We need to handle this case in OSServer_Impl::processDataPointJSON/

Also, when PAT gets into this state if you hit stop analysis, choose yes to stop analysis, and no to stop cloud PAT will not switch to the not running but cloud connected state.

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
