### ISSUE TITLE
apply measure now resets always run measure choice arg to empty

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1273]
Noticed that when I apply a My Measure (set vav zone minimum air flow method) to a 1.5.0 OSM that the choice arg is reset to empty in an always run BCL Measure (Add Daylight Sensor at Center of Spaces with a Specified Space Type Assigned) causing the sim to fail.

**Comment by macumber** [comment]
I bet this has to do with the model being reloaded after applying the measure, thanks for the report

**Comment by macumber** [comment]
@MatthewSteen I can't reproduce this either

**Comment by MatthewSteen** [comment]
@macumber, @DavidGoldwasser  - this seems to be isolated to [this measure](https://bcl.nrel.gov/node/37859), here are the steps to reproduce in 1.5.0:

1. create space in SU, set all attributes
2. open in OS, assign space to thermal zone
3. add Packaged Rooftop VAV with Reheat, add zone to it
4. add allways run BCL measure "Add Daylight Sensor at Center of Spaces...", select space type for required choice arg
5. save osm
6. apply another measure now (tested on both BCL and My measures) and accept changes

When the model reopens after accepting changes the required choice arg for space type in the daylight always run measure will be reset to blank as in the images above.

**Comment by macumber** [comment]
@MatthewSteen thanks a lot, I can reproduce this.  I'll look into it.
