### ISSUE TITLE
Cloning ScheduleRule results in odd behavior

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1279]
Need to add some tests around this

**Comment by asparke2** [comment]
@macumber is this only an issue when cloning a rule independently of cloning a schedule?  If so, please change severity to Normal.  If it affects cloning a schedule, keep at Major because it will show up in 1.7.0 when schedule copying is enabled in GUI.

**Comment by jmarrec** [comment]
I'm going to close this for lack of information to reproduce. (I suspect the behavior is that if you clone a scheduleRule and then try to assign it to another scheduleruleset, then it is cloned a second time)
