### ISSUE TITLE
Changing Units can show wrong data in currently selected object (Bugzilla #731)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#128]
On 2012-06-11 08:59:38, @DavidGoldwasser wrote:

> This can occur under the following conditions.
> 1. The users is in an object that is affected by unit switiching
> 2. The users has edited a value (affected by units) and has not yet switched away from this when they switch units.
> 
> Example is to type 10 or 10.1 for m2/person and convert units before and after switching away from object.
> 
> Was going to make this minor thinking it was only display issue, but can change values, so I left it as normal. I'll target it at 0.9.0 unless someone wants to do it sooner. So I wont' make a pivotal ticket.

On 2012-06-11 10:38:33, @DavidGoldwasser wrote:

> So I can't reproduce the error where data is incorrect. All I'm seeing now is the rounded value vs. an incorrect value. I'll keep testing and see if I can reproduce it. Don't commit anything to this for 0.8.0. Steps to reproduce this remain the same.

**Comment by DavidGoldwasser** [comment]
I'll assign this to myself to re-test, but I think this has been addressed.
