### ISSUE TITLE
Hard-sized entry of 0 reverts to Autosized

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1286]
This may have already been reported but I couldn't find the issue I was looking for related to strange IP-SI conversion/rounding behavior. This happened in the Controller:OutdoorAir object while I was trying to hard size the minimum OA to 0 for an unoccupied zone with its own air loop. When returning to the field after the sim, my hard sized entry of 0 was replaced with Autosized. I hard-entered a value of 0 into the IDF and ran it through E+ instead with no errors.

**Comment by macumber** [comment]
@kbenne Can you prioritize this?  Put it in pivotal if needed

**Comment by kbenne** [comment]
https://www.pivotaltracker.com/story/show/85606174

**Comment by kbenne** [comment]
@MatthewSteen are we talking about this field?

![screen shot 2015-01-12 at 1 51 20 pm](https://cloud.githubusercontent.com/assets/707488/5709816/6cc91ba8-9a62-11e4-89b6-9cc83e353623.png)

I wan't able to reproduce the error you describe on this particular field, but I was on other fields.  Like for instance CoilCoolingDXSingleSpeed::RatedTotalCoolingCapacity.  The reason it happens there is because the idd has a  \minimum> 0 code for that field.  I don't know if E+ will let this case slide, but the E+ idd is intentionally requiring numbers greater than 0, and this was carried over to the OS Model idd.  What is confusing is that you won't know the value was rejected until you leave and come back.  Perhaps that is the bug I should be going after?

**Comment by macumber** [comment]
@MatthewSteen is this an OK fix (you can now enter 0.01 but typing 0.0 will not be accepted) or do we need to change our IDD to allow for 0 as an acceptable value?  Do you have a use case that requires setting this to 0?

**Comment by macumber** [comment]
Looks like there are no bounds on OS:Controller:OutdoorAir - Minimum Outdoor Air Flow Rate, @MatthewSteen can you confirm if this was the field that exhibited this behavior?

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/resources/model/OpenStudio.idd#L12904

**Comment by kbenne** [comment]
@macumber yeah.  thats what I was saying and makes me surprised that @MatthewSteen found this issue on that field.

**Comment by macumber** [comment]
@kbenne hmm, I was able to verify this.  I made a new airloop, clicked on the oa controller, clicked hardsize on both min and max oa.  0 appeared in the hardsize box but I did not manually enter it as a value or hit return.  I changed vertical tabs then went back and the fields were autosized again.

**Comment by macumber** [comment]
If I manually typed in 0 then hit return and clicked around a few fields then the value stuck

**Comment by kbenne** [comment]
Ah yes.  Clicking on hard size but not touching the field is something different.  I bet that is what @MatthewSteen actually hit.  I'll see what I can do about that too.  

I believe one return should be enough.  No clicking around necessary.  Or have you found evidence to the contrary?

**Comment by macumber** [comment]
It is hard for me to actually tell when it accepts it so I usually do a combination of return and clicking around to be sure :-/

**Comment by macumber** [comment]
When I click hard size I see a number, but the model does not seem to change (based on model changed indicator in app menu bar) until I click in to the value field then click on something else

**Comment by kbenne** [comment]
or i believe click on the value field and press return.  I believe this is something I can fix.

**Comment by MatthewSteen** [comment]
@kbenne - yes, that's the field where I encountered the issue. I was able to duplicate in 1.5.0 with basically the same steps mentioned above: 

1. add ControllerOutdoorAir to air loop and go to edit
2. click Hard Sized bullet but don't click in field
3. click on another object in the same loop
4. go back to ControllerOutdoorAir which will be returned to Autosized

If the user instead clicks into the field before moving to another object the default hard sized value of 0 will stick. 

@macumber - I don't have a specific use case other than being able to force the OA damper closed. In my case I think this might have been an data/elec room and I eventually just removed the OA connection altogether. 

On a slightly related topic, OA priority is still a bit of a mystery to me. For proposed models I've had mixed success with hard sizing the Design Outdoor Air Flow Rate in the SizingSystem object so that it matches the mechanical schedule (with ControllerOutdoorAir autosized). In general the HTML output will match my entries but occasionally it doesn't. May be related to @kbenne's [EnergyPlus #4633](https://github.com/NREL/EnergyPlus/issues/4633) issue.

**Comment by MatthewSteen** [comment]
I've noticed a related but separate issue in the fields for Electric Equipment. If the user pastes in a calculated value from an Excel cell to the Design Level W field the value will have a space at the end. If the user doesn't delete the space and navigates to another definition the value will be changed to 0.

**Comment by DavidGoldwasser** [comment]
@kbenne this seems to have broken. I'm wondering if it is related to the newer #1476 that @MatthewSteen identified. It almost seems like clicking on the field naem isntead of the "Hard Sized" radio button is activating the hard sized value field.

I have confirmed this, brought to my attention by unmet hours post.
https://unmethours.com/question/4610/outdoor-air-flow-rate-of-vrf-systems/?answer=4611#post-id-4611

**Comment by MatthewSteen** [comment]
In 1.7.5 this behavior is present in ZoneHVAC equipment fields such as the SA and OA flow rates for PTACs and WSHPs. 

If the user want to hard size the flow rates to 0, it requires and extra click into the value box, not simply clicking the Hard Sized bullet which automatically enters a zero value by default.

**Comment by MatthewSteen** [comment]
I still see this behavior in 1.10.4 for the OutdoorAirController. Clicking the hardsize bullet and then clicking in the field saves the zero value (top), but only clicking the autosize bullet does not (bottom).

![image](https://cloud.githubusercontent.com/assets/8397034/13322986/91b2a62c-db94-11e5-941e-c87d1f16ab51.png)

**Comment by eringold** [comment]
Still relevant as of v2.1.2.

**Comment by MatthewSteen** [comment]
And 2.3.1.

**Comment by macumber** [comment]
@jmarrec is this something you are interested in?

**Comment by jmarrec** [comment]
@macumber I looked into it. I'm not 100% sure I understand every implication, but I found that if you change this line [IGLineEdit.cpp#L242](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model_editor/IGLineEdit.cpp#L242) from:

     emit textEdited(val);

To:

    emit newValue(val);

Then it works as expected.

I didn't see anything that broke when I did this, but I'd like to ask @kbenne or @evanweaver if they see a potential problem?

**Comment by evanweaver** [comment]
@MatthewSteen please verify Julian's fix. Thanks.

**Comment by MatthewSteen** [comment]
Tested the following objects mentioned above in 2.4.0:

* `ControllerOutdoorAir`
* `ZoneHVACPackagedTerminalAirConditioner`
* `CoilCoolingWater`
* `FanVariableVolume`
