### ISSUE TITLE
Performance improvements to unit parsing (Bugzilla #734)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#129]
On 2012-06-12 10:25:28, @macumber wrote:

> 50s out of 65s of the sdd unit tests are spent in unit parsing:
> 
> Time	Time with Children	Hit Count	Routine Name
> 0.0165733200521473	18.5787155632116	112706	openstudio::isUnit
> 0.507523457483081	11.9848461422919	112706	openstudio::decomposeCompoundUnitString
> 0.178052554925835	9.35114054874115	122576	openstudio::decomposeAtomicUnitString
> 0.0166793067175179	9.34026606350756	112706	openstudio::isScaledUnit
> 0.0557912250223552	0.379721364298379	112706	openstudio::Unit::Unit
> 0.0214148517743473	0.291492192505697	122576	openstudio::Unit::setBaseUnitExponent
> 0.0183347307672803	0.187838030712598	122576	openstudio::Unit::isBaseUnit

On 2012-06-13 08:29:29, @macumber wrote:

> This also affects the gbXML translator

**Comment by DavidGoldwasser** [comment]
Looks like work was done towards performance improvements.
