### ISSUE TITLE
Exterior lights crash on tranlastion to idf

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1297]
IDF translator for exterior lights crash if there is no schedule set.  Schedules are optional since lights can be controlled by astronomical clock

**Comment by kbenne** [comment]
@macumber well the model requires the schedule so I think the bug is upstream of the translator.  https://github.com/NREL/OpenStudio/blob/v1.6.0/openstudiocore/src/model/ExteriorLights.hpp#L72 

There are two constructors one that requires a schedule and the other that default constructs an always on schedule.  https://github.com/NREL/OpenStudio/blob/v1.6.0/openstudiocore/src/model/ExteriorLights.cpp#L234

From IO Documentation if a schedule is present and the AstronomicalClock option is chosen the schedule will be ignored.

"The ‘AstronomicalClock’ mode dictates that despite what the schedule indicates, the exterior lights will not run when the sun is up."  <-- IO Ref.

Recommend closing with no action.

**Comment by macumber** [comment]
This line still feels too harsh:
https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateExteriorLights.cpp#L46

If the schedule is missing we could log an error and fail the translation but this shouldn't be a program abort.

**Comment by macumber** [comment]
Also this:

https://github.com/NREL/OpenStudio/blob/v1.6.0/openstudiocore/src/model/ExteriorLights.cpp#L234

Should use the model alwaysOnDiscreteSchedule if possible:

https://github.com/NREL/OpenStudio/blob/v1.6.0/openstudiocore/src/model/Model.hpp#L115

**Comment by macumber** [comment]
@DavidGoldwasser , @kbenne does have a point.  Do you recall how the object that was causing this crash was being created?  I assume it was a measure, do you have a copy of that?

**Comment by kbenne** [comment]
It should use always on discrete.  I assumed this was written before we had that.

I feel like the error is to late in translator.  The model returns Schedule not boost::optional<Schedule> so if you want to do some error processing model seems like the correct location.  You could catch in the translator but if you start up that pattern for everything that the model claims is true where do stop?

**Comment by macumber** [comment]
Oh I see, I thought the model returned an optional schedule.  Ok, well then yeah there is nothing to do I guess?

**Comment by kbenne** [comment]
Perhaps figure out the origin of the model to see how it got in this condition.

**Comment by macumber** [comment]
Well here is one way that we don't defend against now:

schedule = exteriorLights.schedule
schedule.remove

I guess we could reject the remove of the schedule?

**Comment by kbenne** [comment]
@macumber How would you like to proceed?  One option might be create a schedule in ExteriorLights::schedule if one is missing.  I don't know if that is a great precedent or not.

**Comment by macumber** [comment]
@kbenne I'm not 100% sure, let's just chat about it offline for a bit

**Comment by macumber** [comment]
@kbenne I believe the resolution for this was to change the ExteriorLights object API to return an optional schedule, use the building's default always on schedule in the ctor for astronomical clock, set the schedule to default always on schedule in E+ translation if not set (because E+ requires this), then document the API change in the change log that @axelstudios is creating.  Is that correct?

@DavidGoldwasser @asparke2 any thoughts?

**Comment by kbenne** [comment]
yeah that's what I got in my chat log from our conversation.  I just haven't done it yet with distraction on grid styling.
