### ISSUE TITLE
Matched surface error if one space is not translated

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1299]
https://unmethours.com/question/1767/outside-boundary-conditionsurface-must-be-non-blank/?answer=1792#post-id-1792

**Comment by asparke2** [comment]
@macumber I assume that this would only be an issue if you were intentionally drawing extra spaces and then not putting them into thermal zones?

**Comment by macumber** [comment]
Mostly comes up if users forget to take the extra step of assigning thermal zones to spaces, not sure if this should be major, it is classified as such because this causes E+ to not run

**Comment by macumber** [comment]
Note sure what the resolution should be?  Make the surface adiabatic so simulation proceeds?  Log an error?

**Comment by asparke2** [comment]
Probably make the surface adiabatic and throw a warning.

**Comment by asparke2** [comment]
Confirmed with 1.7.0 build
