### ISSUE TITLE
This user file has a number of surfaces that didn't match on their own (Bugzilla #735)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#130]
On 2012-06-12 12:03:18, @DavidGoldwasser wrote:

> To test this, unmatch all surfaces and then rematch. One major floor won't be matched, and then a number of air walls near the roof wont' match. To check the air walls I ran a search for base surfaces with air wall construction and outdoor boundary condition.
> 
> I just thought this would be a good test case for surface matching. I would think 0.9.0 would be good time to use OpenStudio methods that don't rely on SketchUp, or  ruby code in SketchUp Plugin.
> 
> This is an updated version of the user file from bug 733.

Keywords: UserFile

**Comment by DavidGoldwasser** [comment]
We have any know test models that don't intersect or match correctly. Any fix for this would be outside of the plugin.
