### ISSUE TITLE
grid view doesn't update when you change load definitions

### ISSUE THREAD

**Issue by mleach-noresco** [NREL/OpenStudio#1306]
In the OS GUI, if you want to change the definition for a load rather than delete it and add a new definition, it works except that the definition that you select in the drop down list for the load does not update in the GUI until you leave the loads tab and come back.

**Comment by macumber** [comment]
@mleach-noresco @evanweaver I don't think this is valid anymore, how can you change the definition for a load in gridview?  I don't see a drop zone in 1.5.5

**Comment by asparke2** [comment]
This is still valid:
1. Go to the space type grid view and create a space type with loads assigned 
2. Click a load instance to edit
3. It will show up in the inspector
4. Use the inspector to change the definition
5. The definition in the grid doesn't update until you navigate away from that grid tab and back to it.  See screenshot below (red things are different).

![image](https://cloud.githubusercontent.com/assets/2009290/5989740/40f300de-a94e-11e4-9ea7-35cb80da6771.png)

**Comment by jmarrec** [comment]
Still true OS 2.2.1

**Comment by jmarrec** [comment]
Still true OS 2.7.1

**Comment by jmarrec** [comment]
I think this is going to be super tough to implement, since the Inspector Gadget is meant to be agnostic regarding what it's displaying. Here we'd have to connect a change in the IG back to the GridView... It's probably not worth it. I guess that's the downside of the high level of abstraction the IG provides.

**Comment by jmarrec** [comment]
We could add a policy to hide the "People Definition Name" in the OS:People object, but that means you'd have to delete your entire People object (where you might have renamed, set a multiplier, or assigned work/clothing/air velocity schedules) just to change the Load Definition associated with it, so I think that'd be a loss of functionality.

Closing as Won't fix after discussing it with Kyle
