### ISSUE TITLE
QSslSocket: cannot resolve TLSv1_1_client_method

### ISSUE THREAD

**Issue by muh182** [NREL/OpenStudio#1315]
Requiring OpenStudio in the Windows command line creates these warnings: 

QSslSocket: cannot resolve TLSv1_1_client_method
QSslSocket: cannot resolve TLSv1_2_client_method
QSslSocket: cannot resolve TLSv1_1_server_method
QSslSocket: cannot resolve TLSv1_2_server_method
QSslSocket: cannot resolve SSL_select_next_proto
QSslSocket: cannot resolve SSL_CTX_set_next_proto_select_cb
QSslSocket: cannot resolve SSL_get0_next_proto_negotiated

I am using ruby 2.0.0p598 and OpenStudio 1.5.1.

**Comment by asparke2** [comment]
Lowered severity because while these warnings are annoying, they don't indicate a problem and can totally be ignored.
