### ISSUE TITLE
Constructions drop zone looks bad

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1316]
These settings are no longer appropriate after recent changes to support grid view:

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/openstudio_lib/ConstructionInspectorView.cpp#L150

Other drop zones might also be affected.

**Comment by asparke2** [comment]
@macumber reopen if I'm looking at the wrong thing, but I see this and it looks fine to me:

![image](https://cloud.githubusercontent.com/assets/2009290/5989567/c6f03a44-a949-11e4-80cd-df794e590d19.png)
