### ISSUE TITLE
Save and Save As in SU removes EP measures but not OS measures from OSM

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1319]
Noticed this while testing geometry for errors in 1.5.0. I typically run the OSM periodically to check for errors while I'm building geometry in SU. I use one OS measure and one EP measure to do this (Ideal Air Loads and Add Output Diagnostics). After making changes to the OSM in SU and saving or saving as a new model the OS measure was preserved but the EP measure was removed. May be related to [#754](https://github.com/NREL/OpenStudio/issues/754).

**Comment by macumber** [comment]
Reported by several users

**Comment by macumber** [comment]
@MatthewSteen I cannot replicate this in 1.5.5.  Here are my exact steps:

1) Create new OSM in SketchUp
2) Save OSM in SketchUp
3) Open OSM in OS App by pressing button in SketchUp
4) Add measures in OS App
5) Save OSM in OS App
6) Switch back to SketchUp
7) Re-open OSM in SketchUp (you will not be prompted to reload OSM if all you did was edit measures in OS App)
8) Save or Save As OSM in SketchUp
9) Close OS App 
10) Open OSM in OS App by pressing button in SketchUp

**Comment by macumber** [comment]
I have a few ideas of what might be happening.  If you forget to reload the OSM when you switch back to SketchUp (you don't get a prompt) and then save you will lose the changes you made in OS App.

If you have the OSM open in OS App and you save it in SketchUp you don't get prompted to reload the OSM in OS App.  If you keep working in OS App you will lose changes you made in SketchUp.

Do either of those sound likely?  Can you reproduce this bug if you are careful to close each app and only work in one at a time?

**Comment by macumber** [comment]
It is also possible that if you have some file open (e.g. E+ results, etc) when you press save that the save may not work correctly

**Comment by MatthewSteen** [comment]
@macumber - I tried and couldn't replicate this either (1.5.0), closing this phantom issue.
