### ISSUE TITLE
Make link to BCL Key instructions clickable (Bugzilla #748)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#132]
On 2012-06-18 13:17:46, @DavidGoldwasser wrote:

> Not critical but would be nice to have.

On 2012-06-28 13:52:12, @DavidGoldwasser wrote:

> So this link clickable in the OS app now, but it isn't clickable in SketchUp. but I don't like the current workflow where the dialog (in app and plugin) only comes up after the user enters a bad key. Most users would dig around online looking for instructions rather than typing a bad code and hitting enter to bring up the link to the instructions.
> 
> While not critical for 0.8.0 I would like to fix it for 0.8.1

**Comment by DavidGoldwasser** [comment]
deprecated in plugin.
