### ISSUE TITLE
Measure Applicability of NA returns a half changed model

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1320]
Users was seeing odd results, it turned out when the measure was NA it was returning the half altered model vs. the original model. I thought it was designed to just return the original file.

I found the bug in the measure, I used an "or" where I should have used an "and", but I do have a return true to end. If I did a return false it would stop the workflow which isn't what we want.

cc: @nllong 

```ruby

    if sensor_count == 0 or costs_requested == false
      runner.registerAsNotApplicable("No spaces that currently don't have sensor required a new sensor, and no lifecycle costs objects were requested.")
      return true
    end
```

**Comment by DavidGoldwasser** [comment]
If we leave the behavior the way it is, measure writers just need to be sure that that "NA" status is triggered before any alterations occur to the model. Most may be written that way now, but I'm not 100% sure, it is likely in some cases that some stray resources get added that are not used, but probably doesn't cause any issues.

**Comment by macumber** [comment]
@DavidGoldwasser can we close this as won't fix?

**Comment by DavidGoldwasser** [comment]
Sure, but it could come back up at some point.
