### ISSUE TITLE
OpenStudio::Model.intersectSurfaces(spaces) fails on user model

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1322]
The model had a few orphan sub-surfaces, and also a surface that looked like duplicate of another.

![12-31-2014 10-51-19 am](https://cloud.githubusercontent.com/assets/4857055/5589516/d3b3b3b6-90dd-11e4-8d4b-39e6d2ce2509.png)

![12-31-2014 10-53-14 am](https://cloud.githubusercontent.com/assets/4857055/5589517/e05dfd2e-90dd-11e4-8672-640420f3e26d.png)

I'm currently testing to see if removing the orphan and duplicate surfaces solves the issue. I'll post example files and update this with link.
## Here is the full Advanced output.

QSslSocket: cannot resolve TLSv1_1_client_method
QSslSocket: cannot resolve TLSv1_2_client_method
QSslSocket: cannot resolve TLSv1_1_server_method
QSslSocket: cannot resolve TLSv1_2_server_method
QSslSocket: cannot resolve SSL_select_next_proto
QSslSocket: cannot resolve SSL_CTX_set_next_proto_select_cb
QSslSocket: cannot resolve SSL_get0_next_proto_negotiated
C:/Users/dgoldwas/AppData/Local/Temp/1/OpenStudio.V10272/ApplyMeasureNow/UserScript/user_script.rb:65: [BUG] Segmentation fault
ruby 2.0.0p594 (2014-10-27) [x64-mingw32]

-- Control frame information -----------------------------------------------
c:0004 p:---- s:0046 e:000045 CFUNC  :intersectSurfaces
c:0003 p:0136 s:0042 e:000041 METHOD C:/Users/dgoldwas/AppData/Local/Temp/1/OpenStudio.V10272/ApplyMeasureNow/UserScript/user_script.rb:65
c:0002 p:1466 s:0031 E:001e60 EVAL   in.rb:325 [FINISH]
c:0001 p:0000 s:0002 E:0000d8 TOP    [FINISH]

in.rb:325:in `<main>'
C:/Users/dgoldwas/AppData/Local/Temp/1/OpenStudio.V10272/ApplyMeasureNow/UserScript/user_script.rb:65:in`run'
C:/Users/dgoldwas/AppData/Local/Temp/1/OpenStudio.V10272/ApplyMeasureNow/UserScript/user_script.rb:65:in `intersectSurfaces'

-- C level backtrace information -------------------------------------------
 [0x00000000771412FA]
 [0x000007FEFCF510DC]
 [0x000000006F287B0D]

-- Other runtime information -----------------------------------------------
- Loaded script: in.rb
- Loaded features:
  
  0 enumerator.so
  1 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/x64-mingw32/enc/encdb.so
  2 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/x64-mingw32/enc/iso_8859_1.so
  3 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/x64-mingw32/enc/trans/transdb.so
  4 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/x64-mingw32/rbconfig.rb
  5 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/rubygems/compatibility.rb
  6 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/rubygems/defaults.rb
  7 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/rubygems/deprecate.rb
  8 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/rubygems/errors.rb
  9 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/rubygems/version.rb
  10 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/rubygems/requirement.rb
  11 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/rubygems/platform.rb
  12 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/rubygems/specification.rb
  13 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/rubygems/exceptions.rb
  14 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/rubygems/defaults/operating_system.rb
  15 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/x64-mingw32/enc/utf_16le.so
  16 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/x64-mingw32/enc/trans/utf_16_32.so
  17 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb
  18 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/thread.rb
  19 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/monitor.rb
  20 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb
  21 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/rubygems.rb
  22 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/ruby/Release/config.rb
  23 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/x64-mingw32/pathname.so
  24 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/pathname.rb
  25 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/x64-mingw32/enc/trans/single_byte.so
  26 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioutilitiescore.so
  27 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioutilitieseconomics.so
  28 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioutilitiestime.so
  29 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioutilitiesdata.so
  30 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioutilitiesplot.so
  31 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioutilitiesgeometry.so
  32 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioutilitiessql.so
  33 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioutilitiesbcl.so
  34 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioutilitiescloud.so
  35 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioutilitiesunits.so
  36 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioutilitiesidd.so
  37 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioutilitiesidf.so
  38 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioutilitiesfiletypes.so
  39 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioutilities.so
  40 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudiomodel.so
  41 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudiomodelcore.so
  42 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudiomodelsimulation.so
  43 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudiomodelresources.so
  44 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudiomodelgeometry.so
  45 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudiomodelhvac.so
  46 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudiomodelrefrigeration.so
  47 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioenergyplus.so
  48 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioradiance.so
  49 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudiogbxml.so
  50 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioairflow.so
  51 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioosversion.so
  52 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioruleset.so
  53 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudiorunmanager.so
  54 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioproject.so
  55 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioanalysisdriver.so
  56 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudiomodeleditor.so
  57 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioanalysis.so
  58 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudiolib.so
  59 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudioisomodel.so
  60 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/Products/ruby/Release/openstudiosdd.so
  61 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/OSCore-prefix/src/OSCore-build/ruby/Release/openstudio.rb
  62 C:/Users/dgoldwas/Documents/GitHub/OpenStudio/build/Ruby-prefix/src/Ruby/lib/ruby/2.0.0/optparse.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

[utilities.geometry.removeHoles] <1> Failed to partition polygon
[utilities.geometry.removeHoles] <1> Failed to partition polygon
[utilities.geometry.removeHoles] <1> Failed to partition polygon

**Comment by DavidGoldwasser** [comment]
@macumber on the repo I made over christmas, which started as the experimental workflow pulled into a stand alone plugin I added merge arguments to do intersection and surface match.
https://github.com/DavidGoldwasser/osm2su

To see the intersection you need to re-load the model. I also added space attribute render modes, and set it up to use the native paint/eye-dropper tool to apply space attributes (in place of needed to implement a space attributes tool). Thought about adding the gbXML and IDF import as well, merge to those formats will take some thought.

**Comment by macumber** [comment]
It looks like you are using native SketchUp intersect, https://github.com/DavidGoldwasser/osm2su/blob/7bd62ac1c138295d1d38090908157669cf73e69f/su2osm/geometry.rb#L198, is that right?

**Comment by macumber** [comment]
Why would you need to re-load the model to see the intersection?

**Comment by DavidGoldwasser** [comment]
Think of it a bit like apply measures now in OS app. If I want to use OpenStudio API, it is don'e external to the SketchUp model. I'm doing it is part of the merge to external OSM process. Prior to this the surfaces in SketchUp aren't even being classified at all (although I would like to address that at some point, but I started with spaces). I could auto-reload on a merge to OSM, but I'm not currently doing that.

**Comment by DavidGoldwasser** [comment]
Issue #1683 seems related to this

**Comment by DavidGoldwasser** [comment]
@macumber here is a new use file. For me in 1.11.3 the measure appeared ok, but then OpenStudio crashed when I accepted changes.

![screenshot 2016-05-26 08 57 05](https://cloud.githubusercontent.com/assets/4857055/15579149/9a1cf172-2320-11e6-9b76-ca9f44073fc4.png)

In 1.11.0 the user gets a measure error as described here.
https://unmethours.com/question/17625/problem-with-surface-matching-measure/?comment=17652#post-id-17652

**Comment by DavidGoldwasser** [comment]
So, this is a bit odd. I ran the measure three times on the model above and had three different outcomes. All run in 1.11.3 mac in Apply Measures Now.

- First time, it looked like it worked and then crashed.
- Second time it really did work (I'll add the intersected file to the directory for the issue)
- The third time I saw something more like the user did, see screenshot below.

![screenshot 2016-05-26 09 12 24](https://cloud.githubusercontent.com/assets/4857055/15579518/3f0e37da-2322-11e6-8703-f93e98daeeb8.png)

**Comment by DavidGoldwasser** [comment]
Linking to another UH post on this. Post has link to file
https://unmethours.com/question/21626/i-am-receving-error-in-surface-match-using-surface-measure-from-bcl-and-also-using-surface-match-tool-in-sketch-up-images-and-file-attached/

**Comment by DavidGoldwasser** [comment]
@macumber I made custom version of Surface Matching measure that only looked at one pair of spaces at a time, so I could identify the problem surface to alert the user. To my surprise, there were no errors when only looked at pair by pair. Of course it was much slower, but I was surprised at different outcome. Here is the code I used.

`    # looping through vector of each space
    model.getSpaces.sort.each do |space_a|
      model.getSpaces.sort.each do |space|
        runner.registerInfo("Intersecting and matching surfaces between #{space_a.name} and #{space.name}")
        puts "Intersecting and matching surfaces between #{space_a.name} and #{space.name}"
        spaces = OpenStudio::Model::SpaceVector.new
        spaces << space_a
        spaces << space
        OpenStudio::Model.intersectSurfaces(spaces)
        OpenStudio::Model.matchSurfaces(spaces)
      end
    end`

For 400 space model measure took about a minute to run in command line, longer in GUI. Any thoughts on why it didn't fail this way but did with all spaces at once? If this proves reliable I could always share with users when they hit this,or have an extra (diagnostic) argument in the main measure that defaults to "false. But I hate to mess with the main measure.

**Comment by jmarrec** [comment]
Using https://github.com/NREL/OpenStudio-files/blob/master/Git%20Issue%20Files/issue1322/810%20OS%20Space%20Plans-N12Z.osm, with 3.2.0, I can run the SurfaceMatching_Test.rb (from the official NREL measure), then reload the generated test.osm. CLosing.
