### ISSUE TITLE
delete space from Space Types tab causes app to close

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1324]
Noticed this while creating a OSM library for a model in 1.5.0. I created several space types to load into a model but hadn't added any loads to them. When I tried to delete one by clicking on the space type name and then using the red delete button the app unexpectedly closed. This happens when the user has clicked inside the space type name field rather than clicking on the entire space type row. Also noticed that deleting the space type using the library sidebar didn't work. 

![deletespacetypes](https://cloud.githubusercontent.com/assets/8397034/5647344/4c2a5462-9642-11e4-8968-d8139f2d0845.png)

**Comment by macumber** [comment]
@MatthewSteen I can't reproduce this in 1.5.5, have you tried that version can you still reproduce?  

Also, I am not sure what you mean by "deleting the space type using the library sidebar didn't work".  What did you try to do there?

**Comment by MatthewSteen** [comment]
I haven't tried 1.5.5 and just reproduced in a complete non-library model (see updated image). It seems to be related to the name of the space type and where the cursor is. If the user has named a space type starting with a number - e.g. "1br" - and has the cursor in the name field but another row selected to delete, the app will close. 

I also tried deleting using the **X** in the edit tab (inspector?) but it didn't work so not sure if that's the intended purpose.

**Comment by macumber** [comment]
Looks like this was fixed between 1.5.0 and 1.5.5

**Comment by MatthewSteen** [comment]
@macumber - FYI just had this happen in the Thermal Zone tab in 1.5.0. Happened when the cursor was in the name field and the row was also highlighted.

![issue_deletethermalzone](https://cloud.githubusercontent.com/assets/8397034/5725571/3cb6f764-9b11-11e4-88f4-7d2cae1c4955.png)

**Comment by evanweaver** [comment]
@MatthewSteen, thanks for the catch. Inspecting the Thermal Zone in Inspector Gadget on the right was never intended and was an implementation mistake in the Thermal Zone Grid View instance.  This has now been fixed, and the bug you listed here has been fixed and will appear in our next build.

**Comment by MatthewSteen** [comment]
@evanweaver - this actually happened independent of the IG using the red x. Just wanted to let you know in case this fix didn't cover the Thermal Zones tab in 1.5.5.

**Comment by evanweaver** [comment]
@MatthewSteen From your screen shot, I assumed that you used the red X, and that the Thermal Zone was also incorrectly displaying the thermal zone.  If this was the case. when the red X was clicked, model removed the thermal zone and broadcast a signal that interested GUI elements should update. IG thought that it was still holding a valid thermal zone object, and tried to do an update with it, and bang.

If I missed the gist of your report, just let me know.  Thanks again in advance.
