### ISSUE TITLE
SpaceType GridView improvements

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1325]
These are specific to SpaceType, we need to look at the other tabs as well.

1) Create a new space type, add a load definition, click on the load instance name, the load is selected in the inspector (this is correct).  Now click on the space type name, the inspector should be cleared, currently it keeps the last inspectable object selected.

2) Create a new space type, add a load definition, add a schedule to the load instance, click on the schedule, the schedule is selected in the inspector (this is correct).  Now click on the load instance multiplier (the multiplier is associated with the instance), the inspector should show the load instance, currently it keeps the schedule.

3) Create a new space type, add a load definition, add a schedule to the load instance, click on the load instance, use the inspector to clear the schedule, the grid GUI does not update until you go to another grid tab.

4) Create a new space type, add a load definition, click on the load instance, use the inspector to set the schedule, the grid GUI does not update until you go to another grid tab.

5) Create a new space type, add a load definition, click on the load definition, the delete X in the inspector should be disabled but it is not (you cannot clear the definition associated with a load instance)

6) The name fields and other text fields should have a minimum width set, it is weird they get so small if you name the space type "A"

7) Create a new space type, set a default schedule set, add a load definition, the schedule should appear in green because it is inherited (currently inheritance is not indicated).  Now click on the schedule name, the schedule should appear in the inspector but the delete X button should be disabled (you cannot clear an inherited schedule)

**Comment by macumber** [comment]
@evanweaver you still working on this for 1.7.0?

@axelstudios FYI

**Comment by macumber** [comment]
@evanweaver this is listed as closed in pivotal, if so can you please close here?  otherwise if this is not in 1.7.0 let's move to 1.8.0 milestone

**Comment by evanweaver** [comment]
@macumber I broke this ticket into 2 pivotal tickets, the first closed, and the second being https://www.pivotaltracker.com/n/projects/134010/stories/90606578, which I still need to work on.

**Comment by macumber** [comment]
@evanweaver @DavidGoldwasser is this closed?

**Comment by evanweaver** [comment]
@macumber, I can't find the Pivotal ticket listed above. I think that the above were fixed, but some line items may remain. I'd suggest we close this as it is stale, and open individual bugs as they present themselves. @DavidGoldwasser, thoughts?

**Comment by DavidGoldwasser** [comment]
I'm not familiar with these but unless @asparke2 is aware of EDAPT users having issues related to this I assume we won't be fixing them in near term. I'd be fine closing.

**Comment by DavidGoldwasser** [comment]
@evanweaver I found closed pivotal ticket that refers to this, it was closed in March 2015, so I'll close this.
https://www.pivotaltracker.com/story/show/85627656
