### ISSUE TITLE
BCL constructions rename when moved from library into my model (Bugzilla #749)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#133]
On 2012-06-18 16:13:59, @DavidGoldwasser wrote:

> I have a BLC construction object that shows in my library as âASHRAE STD 189 7A Exterior Wall Massâ. When brought into my model is shows as âMass_R-20 ci_Ext-wallâ
> 
> Seems really odd. Does the underlying OSM object not have the same name as the component? I assume any fix for this would be on BCL and not in our code. Looks like name is maybe from Insulation Minimum R-Value attribute (not sure just found out on already downloaded objects can't view attributes in BCL window). But many constructions have this same R value attribute, so the name would not be unique. The component name is unique, I always that that would be the object name in the model.

On 2012-09-06 23:10:26, @DavidGoldwasser wrote:

> Confirmed, with 0.8.4, still kind of bothers me. What shows in the library should be the name that you see in the model. Later on it is hard to map this back to the BCL object it came from.

**Comment by DavidGoldwasser** [comment]
I think this has been fixed, but if not it is really an issue for BCL content, not OpenStudio.  It is about the model object name vs. component name.
