### ISSUE TITLE
Space Type and Construction Set Wizard stopped working post 1.5.0

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1332]
I just tried to use this.
https://bcl.nrel.gov/node/82266

It works fine with 1.5.0 installer, but can't load arguments in 1.5.3 or in my current build version. I expect maybe broke with change to 64bit? it is unique as the only measure using a JSON file. Not sure if the fix is a change in how the measure is written or if there should be a C++ change.

By the way the ruby test runs fine, so this is jsut affecting the GUI. Something to consider when we create our testing framework. This isn't the first time issues are isolated to the GUI.
https://github.com/NREL/OpenStudio-measures/blob/develop/NREL%20working%20measures/SpaceTypeAndConstructionSetWizard/tests/SpaceTypeAndConstructionSetWizard_Test.rb

cc: @asparke2 @axelstudios 

![1-12-2015 8-46-46 am](https://cloud.githubusercontent.com/assets/4857055/5705738/cd500538-9a38-11e4-868b-c590985ae178.png)
Screenshot from 1.5.0

![1-12-2015 8-47-57 am](https://cloud.githubusercontent.com/assets/4857055/5705721/b309c880-9a38-11e4-8e7e-e65864640f69.png)
Screenshot from 1.5.3

**Comment by DavidGoldwasser** [comment]
One current test whole is that the test doesn't care about the measure.xml at all, while the GUI depends on it.

**Comment by DavidGoldwasser** [comment]
Sounds like ruby version and not the xml may be the issue. We could make sure tests use the OpenStudio vs. system installed ruby to make it more consistent with user workflow.

**Comment by DavidGoldwasser** [comment]
Use of wizard from within plugin doesn't suffer from this, but it is using SketchUp 2015's ruby version.

**Comment by macumber** [comment]
Fixed by https://github.com/NREL/OpenStudio/commit/5b4f372d1fc3242fd239b7efca089dd190db2a3b
