### ISSUE TITLE
Measure inspector not correctly restored after apply measure now

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1334]
If you are on the measures tab and run apply measure now the measure inspector is blank when the model reloads.  Switching to another tab and back restores the inspector.

**Comment by macumber** [comment]
Might be related to https://github.com/NREL/OpenStudio/issues/1273

**Comment by jmarrec** [comment]
Still true in OS 2.2.1

**Comment by jmarrec** [comment]
Can't reproduce it with current develop (9edf6e6, 2.6.0 basically) on Ubuntu 16.04

**Comment by jmarrec** [comment]
Can't reproduce either on OpenStudio 2.7.1 on Windows 10.
