### ISSUE TITLE
When use use BCL Weather Script the weather file isn't moved into project (Bugzilla #752)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#134]
On 2012-06-19 11:51:40, @DavidGoldwasser wrote:

> Here is what shows in the file
> 
> OS:WeatherFile,
>   {9b3a5702-ceac-498b-80ee-827b0fdacc49},  ! Handle
>   Denver Intl Ap,           ! City
>   CO,                       ! State Province Region
>   USA,                      ! Country
>   TMY3,                     ! Data Source
>   725650,                   ! WMO Number
>   39.83,                    ! Latitude {deg}
>   -104.65,                  ! Longitude {deg}
>   -7,                       ! Time Zone {hr}
>   1650,                     ! Elevation {m}
>   file:///C:/Users/dgoldwas/BCL/f5edd170-ae85-012d-6615-00ff10a04904/f5eee2f0-ae85-012d-6617-00ff10a04904/denver intl ap co [725650 TMY3]/files/USA_CO_Denver.Intl.AP_TMY3.epw,  ! Url
>   B6A78029;                 ! Checksum
> 
> Oddly, when you re-open the file the path that shows in run simulation dialog is
> files/USA_CO_Denver.Intl.AP_TMY3.epw
> 
> But the file really isn't there yet. When I save or run the simulation at this point the file is then copied over to match the new local path.
> 
> When I I browse in the sketchUp plugin to manually choose a weather file it creates the weather file in files directory as soon as I make the file.
> 
> Since things run fine now this isn't something we need to fix to 0.8.0 but I think we need to fix it soon, because if this was zipped up and someone distributed the file they would be missing the weather file in the BCL weather workflow, but not the manually browse workflow.

**Comment by DavidGoldwasser** [comment]
depricated in plugin.
