### ISSUE TITLE
Opening a previously run PAT project in a new OS version deletes all of the results

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1340]
To reproduce:

1. Run some PAT runs in 1.5.0 (make sure it shows results on the results tab)
2. Open the same project in 1.5.+ (any higher version)
3. Look at the results tab.  The results have been deleted.

This is probably triggered by the seed model updating from 1.5.0 to 1.5.+.  The results are thrown away because they don't technically correspond to the exact setup you have.  However, users don't seem to want to be so strict about knowing that the results are absolutely 100% in sync with the files as they currently exist on your computer.

Suggested fix:

When an existing project is opened, update the model and give a dialog that allows users to decide whether to clear results or not (not being the default selected button).

**Comment by macumber** [comment]
I tried to implement this solution earlier but ran into some issues, it was not as simple as it sounds
