### ISSUE TITLE
Update web-assets for 1.6.0 package

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1347]
I have been working on tuning up the reporting measures that PSD made and it looks like it's time to update the web assets we are packaging.

- Update [bootstrap css](http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/css/bootstrap.min.css)
- Add [bootstrap.js](http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js)
- Add [dygraphs](http://cdnjs.cloudflare.com/ajax/libs/dygraph/1.0.1/dygraph-combined.js)
- Maybe d3?

**Comment by axelstudios** [comment]
We can definitely add/update these.  We just have to be sure that the default reporting measures are updated for compatibilitty

**Comment by axelstudios** [comment]
@asparke2 David updated the dependencies a couple months ago:
- Bootstrap v3.2.0 (with javascript)
- D3 v3.4.8
- Dimple v2.1.2

Is that enough to close this ticket?

**Comment by asparke2** [comment]
Closed per @axelstudios  comment
