### ISSUE TITLE
Arguments for E+ measures gets empty workspace in app

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1348]
Works in PAT, reported by @mleachNREL

**Comment by DavidGoldwasser** [comment]
@macumber is this related to issue #1303

**Comment by kbenne** [comment]
Is this specific to OS App or does PAT suffer the same problem?

**Comment by macumber** [comment]
@kbenne I am not sure, it might well be.  My understanding was that both apps should cache an E+ translated version of the model that they would use to update measures.  This is expensive in the OS app because that translation would have to occur every time you switch to the measures tab.  Pat can just cache the translated model when it sets the baseline.

**Comment by kbenne** [comment]
Yeah that expense is what I'm concerned about.  I'm fairly certain this impacts PAT too, but like you say the expense is less because the Model and therefore translated Workspace is not changing, thus requiring update.  I should have more details soon.

**Comment by macumber** [comment]
Yeah this is making me suspect that this is being done in PAT but not in OS App.  Now that we have tab switching I guess the best thing to do now is do that translation on switching to the measure tab

**Comment by macumber** [comment]
@kbenne seems like this might be a good use for a future.  When you switch the to the tab you might start another process when you switch to the tab, update all the model measures, then block on the future when you go to update energyplus measures

**Comment by kbenne** [comment]
I'm about to make a commit that will highlight and fix (at least part of) the issue.  It will block on the translation, we can work from there.  Perhaps introducing a new process.

**Comment by kbenne** [comment]
@DavidGoldwasser @macumber can one of you point me to a measure that has some workspace supplied arguments? For testing.

**Comment by macumber** [comment]
@kbenne I'm pretty sure the one you create with new measure has an argument

**Comment by DavidGoldwasser** [comment]
@macumber the new measure just has a string value. While I have never gotten this to work, I assume it would look something like this. But it doesn't populate arguments for me in OS app.

```ruby
    # get all thermal zones in the starting model
    zone_names = OpenStudio::StringVector.new
    zones = workspace.getObjectsByType("Zone".to_IddObjectType)
    zones.each do |test|
      zone_names << test.getString(0)
    end
    test = OpenStudio::Ruleset::OSArgument::makeChoiceArgument("test",zone_names,true)
    test.setDisplayName("Pick A zone name, I can use this in the measure")
    args << test
```

If I put the code below into the arguments section and run test via ruby, it does get the zone names.
```ruby
    zones = workspace.getObjectsByType("Zone".to_IddObjectType)
    zones.each do |test|
      puts "found a zone named #{test.getString(0)}"
    end
```

**Comment by macumber** [comment]
@kbenne I never saw the progress bar on model translation but I didn't try this with any huge models

**Comment by kbenne** [comment]
I know, me either.  I tried it on baseline 07 test file and even that is very fast.  So I'm not positive it is there, but I think it is.

**Comment by macumber** [comment]
I think this will be a good kick in the pants to keep our idf translation times down
