### ISSUE TITLE
Measure Groups Rename on Reorder

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1349]
Tested with 1.6.0:

1. Create a PAT project
2. Create 2 measure groups (model measures)
3. Rename the measure groups
4. Reorder the measure groups.
Result:
The names you entered got lost

**Comment by macumber** [comment]
I am not able to reproduce in 1.8.0, @asparke2 can you try and close if you cannot

**Comment by asparke2** [comment]
@macumber I can still reproduce this with both 1.8.0 and the External File branch.

**Comment by elainethale** [comment]
I am seeing something like this just when going to the "Select Measures and Create Design Alternatives" tab and then back to the first tab. Version 1.10.0.
