### ISSUE TITLE
Tried to use "Write Space Type Report" from SketchUp in OpenStudio App Scripts tab (Bugzilla #754)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#135]
On 2012-06-19 15:58:34, @DavidGoldwasser wrote:

> So had two issues. First was that the user argument in the OpenStudio App showed an open dialog vs. a save dialog. So I could only set path by pointing to an existing file vs. entering a new name.
> 
> The next issue is that the script didn't seem to run. It didn't prevent the simulation from running but didn't create a report. Any thoughts on why this wouldn't work.

**Comment by DavidGoldwasser** [comment]
I'll look into this when I have a chance, but if it doesn't work ,I'm more likely to replace it with a measure for OS app than to fix it in the plugin user scripts.
