### ISSUE TITLE
SPM Mixed Air doesn't show on AirLoop diagram when added via Measure

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1358]
Working on a measure to get around issue 1357, I noticed that although the SPM Mixed Airs were added to the model successfully, the yellow flag doesn't show up on the HVAC diagram.  However, when you click on the node or inspect the .osm, you can see its properties.

Notice that I've clicked on a node with "nothing" but the inspector shows otherwise.

![image](https://cloud.githubusercontent.com/assets/2009290/5888520/f297a302-a3be-11e4-8c9f-183a906aa6f9.png)

**Comment by kbenne** [comment]
Anyone know if this is still a thing? I'm pretty sure this is/was not specific to adding via measure.

**Comment by kbenne** [comment]
It looks ok to me, but I admit I did this through the UI. 
![screen shot 2015-09-14 at 2 22 48 pm](https://cloud.githubusercontent.com/assets/707488/9859414/2544c5fc-5aec-11e5-9079-26a88e06c1e8.png)

**Comment by asparke2** [comment]
@kbenne Still a thing.  1.8.5.  It seems to be specific to Mixed Air SPMs (your example uses a single zone reheat) on the OA system nodes.

![image](https://cloud.githubusercontent.com/assets/2009290/9861059/5044945c-5aed-11e5-8cff-ee8fa249eade.png)

**Comment by kbenne** [comment]
Ah yes. In that case I think I know what is going on.

**Comment by jmarrec** [comment]
Is that still relevant today?

**Comment by jmarrec** [comment]
I did this in 2.6.0 in the GUI directly, but seems to be working.

![image](https://user-images.githubusercontent.com/5479063/42700910-6c330426-86c5-11e8-9099-8d3858fced34.png)

@asparke2 was this only a problem in measures? Or GUI too? Can we close?

**Comment by jmarrec** [comment]
Tried with OpenStudio 2.7.0 on windows. You **can** add a SPM mixed air on the outside OA nodes (the OA inlet and OA Relief nodes) **but they don't show** on the diagram.

But with 2.7.1 it is no longer a problem, because I have restricted the placement of SPMs and they aren't allowed on the outside air nodes anymore. Closing then.
