### ISSUE TITLE
EnergyPlus does not update standard output during run

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1359]
This changed in E+ 8.2

**Comment by macumber** [comment]
Could use this instead:

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/public/EnergyPlusPgm.hh#L26

**Comment by eringold** [comment]
fixed in EnergyPlus with https://github.com/NREL/EnergyPlus/pull/5289
