### ISSUE TITLE
1.6.0 PAT crash when switching to results tab

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1363]
1. Ran ~12 simulations
2. Switched to results tab while runs were going
3. Some runs appeared to have failed
4. Tried to switch to run tab
5. Crash

It is repeatable by opening [this PAT project](https://www.dropbox.com/s/s2dcaqllmh0e2er/QTR%20Small%20Office%202A.zip?dl=0) and switching to the run tab.

Here is the PAT info:
![pat version](https://cloud.githubusercontent.com/assets/2009290/5941801/7faa5532-a6d0-11e4-911f-6b5dcff51aa0.PNG)

**Comment by asparke2** [comment]
I've noticed that after PAT crashes and I reopen the project, it takes several (~5) minutes to switch to the run tab, and PAT is using a full processor the whole time.

**Comment by macumber** [comment]
Crash may have been related to #1372 

I will do some profiling on the speed, it is pretty slow

**Comment by asparke2** [comment]
Confirmed fixed with 1.6.3
