### ISSUE TITLE
1.6.0 PAT crash when run then cancel a simulation

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1364]
1. Create a new PAT project
2. Set [this model](https://www.dropbox.com/s/iazmrjvuc43kobp/empty_model.osm?dl=0) as the seed model
3. Go to the run tab and start the simulation, then stop simulation and confirm
4. Crash

Here is the PAT info (using the installer from the OS website):
![patcrash2](https://cloud.githubusercontent.com/assets/2009290/5943007/81285eec-a6d8-11e4-887e-6eaf41802faf.PNG)

**Comment by MatthewSteen** [comment]
I also experience this issue with one of my models.

**Comment by macumber** [comment]
@asparke2 I can't reproduce this on develop, I think this might have been fixed by https://github.com/NREL/OpenStudio/commit/f5e08476527cc0be1adc02f034b8dd9be9911d55

**Comment by asparke2** [comment]
@macumber tested and confirmed fixed in 1.6.3
