### ISSUE TITLE
Design Flow Air Rate in CoilCoolingWater object uses fluid vs. air units

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1365]
User saw this in four pipe fan coil, I also confirmed it with coil on air loop. Units in IP are gal/min and SI are m^3/s. These are the same units used for Design Water Flow Rate.

![1-28-2015 12-30-07 pm](https://cloud.githubusercontent.com/assets/4857055/5945181/e9dd1f8e-a6e9-11e4-90a9-0555a38c634d.png)

**Comment by MatthewSteen** [comment]
FYI - changed in EnergyPlus from 8.1 to 8.2 ([#4316](https://github.com/NREL/EnergyPlus/issues/4316))
