### ISSUE TITLE
Change which OS version EXE opens OSM files by default

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1373]
After installing 1.5.0 after 1.6.0 I was unable to set version 1.6.0 as the default program for OSM files through the Control Panel in Windows 7. To fix I had to reinstall 1.6.0. Possible feature request.

**Comment by macumber** [comment]
@MatthewSteen have you tried right clicking on OSM, "Choose Default Program", then browse to the actual OpenStudio.exe location you want (e.g. 'C:\Program Files\OpenStudio 1.6.0\bin\OpenStudio.exe')?

**Comment by MatthewSteen** [comment]
No, but I arrived at the same dialog using Control Panel > All Control Panel Items > Default Programs > Set Associations.

**Comment by macumber** [comment]
DId that work for you?  I believe you can associate OSM files with any version of OpenStudio provided you browse to the actual location that the EXE is installed at.

**Comment by MatthewSteen** [comment]
No, I just tried setting the default version back to 1.5 from 1.6 via a right click. Double clicking on an OSM still opens it in 1.6.

**Comment by jmarrec** [comment]
@MatthewSteen do you still have this problem?

**Comment by MatthewSteen** [comment]
Yes and no. I successfully changed the default version to 2.3.0 in Windows 7, which opened when I clicked on an existing 1.14.0 model. However, the instance of 2.3.0 that opens is an empty model.

**Comment by eringold** [comment]
Could be related to this, then: https://github.com/NREL/OpenStudio/issues/1353
