### ISSUE TITLE
CSV export from OpenStudio

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1375]
We have had several requests for timeseries CSV output from OpenStudio similar to ReadVarsESO.  However, I am unsure about the best implementation.  

We could do this with a reporting measure with a boolean checkbox to report each variable or meter, would that be acceptable?  Should we separate output into multiple CSV files, one for each reporting frequency?

Another option is to add CSV output from ResultsViewer.  This could allow more control of outputs but is less automated.

**Comment by macumber** [comment]
We will likely not add this feature to ResultsViewer which leaves a measure implementation.  I would think that the scope of reporting a variable for all keys is appropriate.  If we need a second measure to report a variable for particular keys we can do that as well.  We should implement this as an html measure which shows the data in tabular form with a link to download the raw CSV.  We do not need to use ReadVarsESO directly.

**Comment by MatthewSteen** [comment]
+1

**Comment by jmarrec** [comment]
+1

**Comment by shorowit** [comment]
If/when OpenStudio switches from ResultsViewer to DView, this can be closed as DView has a right-click menu option to 'Save data to CSV'.

**Comment by jmarrec** [comment]
Switch to DView is live. This can be closed

**Comment by macumber** [comment]
@MatthewSteen do you agree with closing this now that DView is included?

**Comment by MatthewSteen** [comment]
Yes, sounds good.

**Comment by aaron-boranian** [comment]
Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9098479)

**Comment by Maharshi-Pathak** [comment]
how can I run the readvarESO or equivalent to convert this .eso file to csv if I am running the command line interface on linux based systems? Is it already possible in the OSW?

**Comment by jmarrec** [comment]
@Maharshi-Pathak Use the OutputControlFiles object

```ruby
m = Model.new
o = m.getOutputControlFiles()
o.setOutputCSV(true)
```

**Comment by Maharshi-Pathak** [comment]
Amazing. Thanks @jmarrec

**Comment by govertsenk** [comment]
I turned @Maharshi-Pathak's question and @jmarrec's answer into a measure for others to use. Posted on my GitHub [here](https://github.com/govertsenk/myphddissertation/tree/main/Template/measures/OutputToCSV).
