### ISSUE TITLE
Crash when running user file

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1378]
File sent in by Taylor Roberts, in issues repo

**Comment by MatthewSteen** [comment]
@macumber any details? I'm experiencing one when trying to disconnect a CoilHeatingWater.

**Comment by kbenne** [comment]
@MatthewSteen "disconnect" CoilHeatingWater?  That sounds like something I should be concerned about.  How do you mean disconnect?  In the application, or a measure using some particular part of the API?

**Comment by MatthewSteen** [comment]
@kbenne I was using the app trying to manually disconnect some newly created coils by unchecking the loop connection. I was able to get around it by simply deleting the HW loop they were connected to. Is this still a known issue? If not, and different from this one, I'll submit a new one with more detail.

**Comment by kbenne** [comment]
@MatthewSteen I can't 100% confirm that there is not an issue for something like that, but it is not known inside my brain.  And a quick search through issues for keywords like water coil comes up empty.  I say add it.

**Comment by kbenne** [comment]
Duplicate of https://github.com/NREL/OpenStudio/issues/1380 which was fixed here https://github.com/NREL/OpenStudio/commit/875df593050b9976fd9826e628ee042fbe8d5ad7.  If the issue unexpectedly persists then please reopen.
