### ISSUE TITLE
Opening an osm with weather file object but file missing on disk, app should clear weather file object (Bugzilla #764)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#138]
On 2012-06-22 11:38:21, @macumber wrote nothing.

On 2012-09-06 22:44:51, @DavidGoldwasser wrote:

> This happens whenever someone sends me the file without the project folder

On 2013-03-12 12:24:05, @elainethale wrote:

> **\* Bug 1114 has been marked as a duplicate of this bug. ***

**Comment by DavidGoldwasser** [comment]
This is still valid, the GUI should be smart enough to clear out the path to a file that doesn't exist. Also still confusing got users why dry path is gone. I don't even think a path optio should show for DDY file, should just expose the objects in the model. But that is kind of a feature. I'll label as such.

**Comment by macumber** [comment]
@evanweaver I believe you are working on this

**Comment by evanweaver** [comment]
Fixed.
