### ISSUE TITLE
crash when manually disconnecting CoilHeatingWater from loop

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1380]
Steps to reproduce:

1. open new model
2. create new `Packaged DX Rooftop VAV with Reheat` using Add HVAC System wizard
3. click on the CoilHeatingWater
4. uncheck connection to HW loop

Workaround is to instead delete entire HW loop.

**Comment by mbadams5** [comment]
This crashes due to bad access...

https://github.com/NREL/OpenStudio/blob/6394835fde8599b228624b67087e07a7d16b165a/openstudiocore/src/openstudio_lib/LoopChooserView.cpp#L87

@kbenne @evanweaver

**Comment by kbenne** [comment]
I'm working on this now.  Another workaround I discovered while troubleshooting is to use the remove button "X" on the component itself.  If you do that while viewing the air system the water coil will be removed from the air side, but remain on the water side.  Conversely if you click on the remove button while viewing the component from the plant side, it will be removed from the plant, but remain on the air system.  I'm not yet sure if this is a problem in the GUI layer or if it is a more fundamental problem with the API.  The bad access that @mbadams5 points out might be a symptom of the API doing bad things and leaving the Model with a dangling connection, or it might be that the GUI is racing to redraw before the model changes are complete.
