### ISSUE TITLE
Support holidays in schedule GUI

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1382]

**Comment by DavidGoldwasser** [comment]
Wanted to refer to this post on unmet hours
https://unmethours.com/question/10029/set-holidays-in-os/

I noticed that there is API access to setUserWeatherFileHolidays in the RunPeriod object, but there isn't API access for a ScheduleRule object to setApplyHoliday.

@macumber did we disable that to prevent people from getting into trouble. I was trying to recommend some work around since it it taking us a while to get to this. Has been gone since 0.6.0 or so when we added in ScheduleRuleset.

**Comment by jmarrec** [comment]
I ran into this "pickle" two days ago, when defining occupancy and hvac schedule for an office. I want it to be ON for weekdays 8-18, and off for weekends and holidays. This would be a very useful feature

**Comment by DavidGoldwasser** [comment]
@jmarrec while I still prefer that a holiday profile in GUI looks kind of like design days, there is a schduleRule.addSpecificDate method and a scheduleRule.specificDates method to see them. But this isn't editable in GUI, and only inspectable annual calendar at right.

**Comment by jmarrec** [comment]
I think it should just be a new button like for Apply Holiday in a schedule rule, no?

![screen shot 2017-10-03 at 11 31 14 am](https://user-images.githubusercontent.com/5479063/31118661-7b50180c-a82e-11e7-8539-a44240af187e.png)

**Comment by DavidGoldwasser** [comment]
@jmarrec That would be fine. I assume you your example it applies to all holidays, not just holidays holidays for specific time of year or day of week. Also would have to be careful if someone checked "Holidays" for more than one profile. If you don't want to reuse a Sunday schedule for holidays, then I suppose you would just leave every day of the week un-checked.

**Comment by aaron-boranian** [comment]
Problem: It is not possible to describe holidays from within the schedule GUI

Solution: Add support for holidays from within the schedule editor in the GUI

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9097861)

**Comment by anchapin** [comment]
Is there any progress on this? Expected timetable for implementing this in the GUI? Thanks

**Comment by macumber** [comment]
Unfortunately we don't have plans to implement this feature in the GUI at this time.

**Comment by anchapin** [comment]
Who sets the priorities? It seems like the SDK gets all of the attention and the GUI gets the scraps that are left over. Having the ability to include holidays without writing a custom measure isn't asking a lot. Most people probably would assume that this feature is included.
