### ISSUE TITLE
Clean up StandardReport measure

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1389]
Add entries for total_source, total_source_eui, total_site_eui, unmet_heating_hours, unmet_cooling_hours, unmet_total_hours to StandardReport.  Can be machine readable only no need for html

Add entries for all outputs from StandardReport measure in unified taxonomy

**Comment by macumber** [comment]
@DavidGoldwasser is this complete?  Where these new attributes to support @brianlball ?

**Comment by DavidGoldwasser** [comment]
@axelstudios is helping me wit this now. Brian's attributes are needed for the updates to the calibration measure. I wasn't going to try and squeeze the calibration measure into 1.9.0.
