### ISSUE TITLE
Duplicate building rotation warnings in IDF->OSM translator

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1390]
User should only need to see this warning once.  Might implement a repeated warning filter in the translator?

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/GeometryTranslator.cpp#L252

**Comment by macumber** [comment]
@kbenne FYI

**Comment by jmarrec** [comment]
Permalink where Dan linked to: https://github.com/NREL/OpenStudio/blob/5d1aadadeaf4e9c69cf5b392f187aefcfd41a757/openstudiocore/src/energyplus/GeometryTranslator.cpp#L252

Nowadays at 3.2.0 alpha: https://github.com/NREL/OpenStudio/blob/a007b7801e3bb05731f012f585facdd814ef31fb/src/energyplus/GeometryTranslator.cpp#L340

**Comment by jmarrec** [comment]
This is in the RT, and the user can choose to add a Building to suppress this, so closing as working as expected
