### ISSUE TITLE
Implement measure testing framework

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1391]
There was a ticker for this in Pivotal, no detail under it, but know we want to do this, so thought I'd start and issue wand we can extend it.

cc: @macumber @kbenne @lefticus

**Comment by macumber** [comment]
I know that @ljbrackney is aware of this and that it is on his radar.  Removing low frequency and replacing with High Demand

**Comment by macumber** [comment]
We want a system that will work for us as well as regular users.  Potentially something built into BCL that runs when users submit measures would be ideal

**Comment by macumber** [comment]
Relates to https://github.com/NREL/OpenStudio/issues/500

**Comment by macumber** [comment]
Is this done @evanweaver @DavidGoldwasser ?  This is what the CI will run for measure repo right?

**Comment by evanweaver** [comment]
@macumber I think that this refers to work that @kflemin was going to do, but I really don't know.

**Comment by aaron-boranian** [comment]
Problem: Some measures submitted contain bugs.

Solution: Something built into the BCL that runs when users submit measures.

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9094969)

**Comment by ljbrackney** [comment]
A measure dashboard is in progress, but will only work as well as the provided unit tests.  If a measure contains few or no tests, the dashboard will only report on syntactical and stylistic errors.

**Comment by jmarrec** [comment]
@DavidGoldwasser Isn't this operational now?

**Comment by DavidGoldwasser** [comment]
Yes, this can be closed.
