### ISSUE TITLE
Scripts Tab - Bug in error reporting on importidf script (Bugzilla #769)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#140]
On 2012-06-25 15:37:35, @DavidGoldwasser wrote:

> [utilities.idf.WorkspaceObject] <0> ZONE 1 Ventl 1, an object of type ZoneVentilation:WindandStackOpenArea, points to an object named OS:ThermalZone 1 from field 1, but that object cannot be located.
> [utilities.idf.WorkspaceObject] <0> ZONE 1 Ventl 1, an object of type ZoneVentilation:WindandStackOpenArea, points to an object named Always_On from field 3, but that object cannot be located.
> [utilities.idf.WorkspaceObject] <0> ZONE 2 Ventl 1, an object of type ZoneVentilation:WindandStackOpenArea, points to an object named OS:ThermalZone 2 from field 1, but that object cannot be located.
> [utilities.idf.WorkspaceObject] <0> ZONE 2 Ventl 1, an object of type ZoneVentilation:WindandStackOpenArea, points to an object named Always_On from field 3, but that object cannot be located.
> [utilities.idf.WorkspaceObject] <0> ZONE 2 Ventl 2, an object of type ZoneVentilation:WindandStackOpenArea, points to an object named OS:ThermalZone 2 from field 1, but that object cannot be located.
> [utilities.idf.WorkspaceObject] <0> ZONE 2 Ventl 2, an object of type ZoneVentilation:WindandStackOpenArea, points to an object named Always_On from field 3, but that object cannot be located.

**Comment by DavidGoldwasser** [comment]
May have been issue with measure referring to object that had been deleted.
