### ISSUE TITLE
Add ZoneHVAC:OutdoorAirUnit

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1400]
Garage heating system type: systems like unit heaters & make up air units need to be implemented.  Unit Heaters are being added under another ticket.

**Comment by asparke2** [comment]
Unit heaters are already done.

**Comment by eringold** [comment]
@DavidGoldwasser why was this closed? OpenStudio does not have ZoneHVAC:OutdoorAirUnits
