### ISSUE TITLE
Standard and calibration reports do not show all non-zero fuel types.

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1408]

**Comment by macumber** [comment]
https://unmethours.com/question/13849/openstudio-calibration-not-working/?comment=13900#post-id-13900

**Comment by DavidGoldwasser** [comment]
In my test it does fail if you use district heating or cooling utility bill, vs, just not showing those fuels. I'll try to add the an updated test model into the repo, but test still wont' run until it also loads AMY vs. TMY file.

Ideally test should issue warning for other fuel utility bills.

**Comment by jmarrec** [comment]
related to #3381. Not sure if still an issue since the measures may have worked-around it.
