### ISSUE TITLE
StdError and StdOut not working correctly in apply measures now

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1410]
This feature isn't showing the stderr messages. I routinely still hit the "ruby failed with exit code of 1" message, and then when I click "Advanced Output" I only see stdout messages, not stderr messages, forcing me to go into the temp directory to find the actual stderr file.

https://github.com/NREL/OpenStudio/commit/b4fe664443beb03757da167253abce6b4a2ce039

Run the Measure a second time without making any changes to measure.rb and you’ll get the error message from stderr correctly. I believe the second time you run, it is actually getting the stderr from the first time you ran.

```
Andrew
```

**Comment by jmarrec** [comment]
@macumber thoughts on the comment above?

**Comment by macumber** [comment]
As long as you can see the info I think it is ok
