### ISSUE TITLE
Changing a Space Type definition's load in IG does not update in gridview

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1412]

**Comment by macumber** [comment]
@evanweaver you still working on this for 1.7.0?

@axelstudios FYI

**Comment by macumber** [comment]
@evanweaver if not going in 1.7.0 can you please move to 1.8.0 milestone here and in pivotal

**Comment by macumber** [comment]
@evanweaver is this still valid?  I am going to move to 1.9.0 milestone. If that won't be possible please remove the milestone

**Comment by jmarrec** [comment]
I think it's fixed in OS 2.2.1. If I edit the name of a load and press ENTER it changes in the grid

**Comment by evanweaver** [comment]
Fixed as tested in 2.3.0.
