### ISSUE TITLE
Update Model mainpage.hpp

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1416]
This is way out of of date and confusing to people trying to use the SDK docs

https://s3.amazonaws.com/openstudio-sdk-documentation/cpp/OpenStudio-1.6.0-doc/model/html/index.html

**Comment by jmarrec** [comment]
Seems like 3.1.0 is pretty much the same at 1.6.0 https://s3.amazonaws.com/openstudio-sdk-documentation/cpp/OpenStudio-3.1.0-doc/model/html/index.html

**Comment by jmarrec** [comment]
Superseeded by https://github.com/NREL/OpenStudio/issues/3519
