### ISSUE TITLE
Add -werror on Mac and Linux

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#1417]
I think we need some code cleanup before this is possible.

**Comment by axelstudios** [comment]
There are *very* few clang warnings now -- I cleaned up as many as I could right before 1.8.0.  What's left:

##### Ruby bindings
- ~20 warnings about usage of calls to OS_DEPRECATED functions
- 3 AnalysisDriver ruby warnings (ruby_OpenStudioAnalysisDriver_wrap.cxx:6506:1: warning: control may reach end of non-void function [-Wreturn-type])

##### 3rd-party
- openstudiocore sqlite has 1 warning
- litesql sqlite has 2 warnings
- litesql has 4 warnings

**Comment by mbadams5** [comment]
I thought I suppressed those OS_DEPRECATED warnings in the Ruby bindings... humm

**Comment by mbadams5** [comment]
@axelstudios You probably just need to move [this](https://github.com/NREL/OpenStudio/blob/e0af434eb0cd130c5da1cd9a922d91b54cd3f89d/openstudiocore/ProjectMacros.cmake#L349) to [here](https://github.com/NREL/OpenStudio/blob/e0af434eb0cd130c5da1cd9a922d91b54cd3f89d/openstudiocore/ProjectMacros.cmake#L343) and then get rid of [this entirely](https://github.com/NREL/OpenStudio/blob/e0af434eb0cd130c5da1cd9a922d91b54cd3f89d/openstudiocore/ProjectMacros.cmake#L347-350). At least that is my guess.

**Comment by mbadams5** [comment]
Or vice versa. That clang needs the -Wno-deprecated-declarations

**Comment by axelstudios** [comment]
Gotcha - I think 0082bc4f665650058f48d95ed47746d4e492b53b should do it

**Comment by jmarrec** [comment]
I suppressed a lot of warnings in https://github.com/NREL/OpenStudio/pull/2700
Perhaps time to revisit this?

**Comment by jmarrec** [comment]
This is on develop3, fixed by https://github.com/NREL/OpenStudio/pull/3396
