### ISSUE TITLE
Publish Radiance BSDFs to BCL

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1419]

**Comment by macumber** [comment]
@asparke2 can you clarify what this feature request is about? @rpg777 FYI

**Comment by rpg777** [comment]
The new Radiance model format and shade handling routines only require a small handful of BSDF files, so I propose including them with OpenStudio (we are doing so in the resources now, on a dev branch).

**Comment by asparke2** [comment]
@macumber I have no idea what this is anymore...I think it was originally to help Rob get the BSDFs uploaded?  I'm closing it.
