### ISSUE TITLE
Allow access to private BCL content

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1421]

**Comment by macumber** [comment]
What new user facing features will this provide?

**Comment by ljbrackney** [comment]
The ability to pull down content that is private to a group is the most immediate benefit.  Right now such content has to be shared via email or LAN and loses the BCL provenance and versioning capability.

**Comment by aaron-boranian** [comment]
Problem: There is currently no convenient way to pull down content private to a specific group.

Rationale: Private content can be shared via email or LAN but loses the provenance and versioning capability of BCL

Solution: Allow access to private BCL content

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9099733)
