### ISSUE TITLE
Skylights not properly translated from E+ (Bugzilla #777)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#143]
On 2012-07-05 09:56:50, @macumber wrote:

> Skylights don't have their own sub surface type in E+, need to check for windows on roofs or normal up on import and convert to skylight

**Comment by DavidGoldwasser** [comment]
I'm going to close this. It would be a feature request, but since this isn't something everyone needs, could be handled on as needed basis by measure that re-classifies sub-surfaces to be skylights.

@macumber are you ok with this being closed? If not we can re-open it.
