### ISSUE TITLE
Create Measures for 90.1 Appendix G System Types

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1432]

**Comment by MatthewSteen** [comment]
Would be nice to have these create the baseline model from the proposed by removing the HVAC systems.

**Comment by jmarrec** [comment]
Can this be closed now that openstudio-standards ships with OpenStudio? Or were you talking about using measures for the proposed system too?

**Comment by aaron-boranian** [comment]
Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9099355)
