### ISSUE TITLE
Add 90.1-2013 to OpenStudio Standards Spreadsheet

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1433]

**Comment by jmarrec** [comment]
Any update on this?

**Comment by asparke2** [comment]
@jmarrec Yeah, this is almost done.  The raw OpenStudio-standards.xlsx spreadsheet will be pushed up to the [OpenStudio-Prototype-Buildings repo](https://github.com/NREL/OpenStudio-Prototype-Buildings/tree/master/create_DOE_prototype_building/resources) once it's ready.  The templates won't be updated in OS installers until 1.9.2 or so.

**Comment by jmarrec** [comment]
As well as the OpenStudio_Standards_....json files? (Mark told me the prototype building for MidRiseApartment wouldn't be ready until much later, so I'm trying to get a head start on you :))

**Comment by ljbrackney** [comment]
I understand that all of the building types except for hospital and outpatient healthcare have at least been stubbed out within the measure.  So if you select mid rise, you will get a model.  It has not been debugged or validated against the IDF prototype though - that's work that is likely to happen in Oct-Dec.

**Comment by asparke2** [comment]
@jmarrec Yes, the .JSON files too.  We enter the data in the spreadsheet because it's easier to work with, but then export the spreadsheet to JSON because the diffs are nicer and it's easy to work with in Ruby.

**Comment by jmarrec** [comment]
Thanks for the answers, guys.

@ljbrackney  I'm going through the prototype stuff right now. Though you can't select Midrise, I see it's been indeed mostly "stubbed out". It's mostly there though a bunch of stuff hasn't been set, like the cooling sch and heating sch are zero for now, and it's absent from the prototype inputs.

**Comment by asparke2** [comment]
If you're interested in helping with that building type, I can give you write access.  Also, give you access to the google spreadsheet that we use to edit the OpenStudio_standards file.  Will you be coming to Atlanta for ASHRAE next week?  If so, we could meet up and I can get you started.  Or at least we could grab a beer/.

**Comment by jmarrec** [comment]
I think I am interested yes. I intend to built most of it anyways. (I'm not interested in creating the DOE prototype per se but something very similar - different goals, same path).

I'll be in Atlanta indeed, I'm game for a beer!

**Comment by asparke2** [comment]
Cool, sounds good!  It's not a big conference so I'm sure we'll run into each other pretty quickly.

**Comment by asparke2** [comment]
Closing.  This is long-resolved.

**Comment by aaron-boranian** [comment]
Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9099637)
