### ISSUE TITLE
User Script - Make scenes from stories script makes scenes out of order (Bugzilla #779)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#144]
On 2012-07-11 08:29:47, @DavidGoldwasser wrote:

> This used to work, but looks like we don't sort stories before we run this anymore. Also on user model from Doug Sharpe it is really slow. As we are not changing any model object I would expect it to be quicker.
> 
> David

On 2012-09-05 11:50:32, @DavidGoldwasser wrote:

> Hmm, this seems to work now, mabye this was just related to bug 880 (we don't sorts spaces when making story objects with "Assign Building Stories" script.
> 
> But now I see a new issue with "Scenes from Stories" the two first scenes that should save the current camera and the plan camera are not made. I may take a quick look at this and 880

On 2012-09-05 11:54:16, @DavidGoldwasser wrote:

> Never, mind, it does make those scenes, so this can be closed.

On 2012-09-14 15:06:36, @DavidGoldwasser wrote:

> So this wasn't really fixed. It seems to work when I use space diagram, but not other times, even if I make stories in the right order.
> 
> Also I found that the scenes are saving layer and section cut visibility. I'd like to un-check both of those when Is ave the scene.
> 
> I'll fix this post 0.9.0

**Comment by DavidGoldwasser** [comment]
I think it takes stories in the order they are in the OSM, which may or may not be alphabetical. This is rarely used use script. I don't plan to update it.
