### ISSUE TITLE
Integrate openstudio-aws-gem into openstudio

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1440]
Current version is here: https://github.com/NREL/OpenStudio-aws-gem .

The methods listed in the tasks need to be implemented in the openstudio_aws_wrapper.rb https://github.com/NREL/OpenStudio-aws-gem/blob/master/lib/openstudio/lib/openstudio_aws_wrapper.rb

**Comment by macumber** [comment]
@axelstudios can you close this once merged?

**Comment by axelstudios** [comment]
Done.
