### ISSUE TITLE
Easily set weather file in PAT

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1444]
Could be implemented as a measure

**Comment by DavidGoldwasser** [comment]
@macumber we have a measure like this in coffee. It of course has the possible weather files in resources folder vs. having the user browse for it. I have a feature request in to allow path arguments in measures that support cloud runs (when you set the argument the file needs to be brought into the project.

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
