### ISSUE TITLE
Update OS App run tab to look like PAT's

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1446]

**Comment by macumber** [comment]
Maybe needs to wait until we move to workflow gem?

**Comment by aaron-boranian** [comment]
Problem: There is a lack of design coherence between OS App’s run tab and PAT‘s run tab.

Solution: Update OS App run tab to look like PAT‘s

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9098725)

**Comment by ljbrackney** [comment]
I don't understand this issue.  The OS App and PAT have very different requirements for run management and diagnostics.
