### ISSUE TITLE
Create OSM to OSM diff report measure

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1450]

**Comment by DavidGoldwasser** [comment]
@macumber you already made this, unless you had enhancements you wanted to add to it.

**Comment by DavidGoldwasser** [comment]
@macumber just wanted to ping you again on this t see if this was to enhance the one you already made?

**Comment by macumber** [comment]
I think that is this one, https://github.com/NREL/OpenStudio-measures/tree/develop/NREL%20working%20measures/ReportModelChanges

I can never find it, we should probably rename it to have diff in the title.
