### ISSUE TITLE
Deprecate attributes from Model

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1452]
Requires replacing all GUI components built on attributes

**Comment by evanweaver** [comment]
@macumber is this still valid?

**Comment by macumber** [comment]
Yes but not an app thing

**Comment by macumber** [comment]
Replacing the code might require updates to the app, but this is not an app issue.  Remove all of these attribute methods:

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/ModelObject.hpp#L133

If possible, also want to remove the Attribute class:

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/utilities/data/Attribute.hpp

**Comment by jmarrec** [comment]
This was done as part of the move to 3.0.0

**Comment by jmarrec** [comment]
Well, actually it seems that the Facility class still has a couple.

```
Facility.cpp:1351:  boost::optional<Attribute> Facility_Impl::endUsesAttribute() const
Facility.cpp:1353:    boost::optional<Attribute> result;
Facility.cpp:1391:  boost::optional<Attribute> Facility_Impl::calibrationResultAttribute() const
Facility.cpp:1393:    boost::optional<Attribute> result;
Facility.cpp:2008:boost::optional<Attribute> Facility::endUsesAttribute() const
Facility.cpp:2010:  return getImpl<detail::Facility_Impl>()->endUsesAttribute();
Facility.cpp:2018:boost::optional<Attribute> Facility::calibrationResultAttribute() const
Facility.cpp:2020:  return getImpl<detail::Facility_Impl>()->calibrationResultAttribute();
```
