### ISSUE TITLE
Allow rearranging material layers in construction GUI

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1454]

**Comment by MatthewSteen** [comment]
Maybe overwrite by dropping a new material on top of old layer too.

**Comment by jmarrec** [comment]
+1

**Comment by MatthewSteen** [comment]
https://openstudio.uservoice.com/forums/308629-openstudio/suggestions/9099592-allow-rearranging-material-layers-in-construction

**Comment by aaron-boranian** [comment]
Problem: It is difficult to manipulate/edit material layers in the construction GUI

Solution: Allow rearranging material layers in construction GUI

Context: ported from GitHub: https://github.com/NREL/OpenStudio/issues/1454

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9099592)

**Comment by jmarrec** [comment]
#2964 would be a good reference if someone wants to implement this, since I similarly implemented reordering the AVMs within the AVM list on plant loop "Controls" subtab.

**Comment by jmarrec** [comment]
I opened as PR to fix this at https://github.com/NREL/OpenStudioApplication/pull/47
