### ISSUE TITLE
Ruby bindings to EpwFile are not very useful

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1458]

**Comment by macumber** [comment]
Reported by @stephen-frank and @henryHorsey the Ruby bindings to the EpwFile class are not very useful, I think mostly due to needing to import more of the other utilities sub projects (such as data and time)

**Comment by macumber** [comment]
require 'openstudio'

epw = OpenStudio::EpwFile::load('C:\EnergyPlusV8-2-0\WeatherData\USA_CO_Golden-NREL.724666_TMY3.epw').get
puts epw

startDate = epw.startDate.public_methods
puts startDate.is_a? OpenStudio::Date
puts OpenStudio::Date.new.is_a? OpenStudio::Date

# This would work but we need to export std::vector<EpwDataPoint>
#data = epw.data
#data.each do |d|
#  puts "#{d.date}, #{d.time}"
#end

# This would work but we need to export boost::optional<TimeSeries> before reading EpwFile
timeseries = epw.getTimeSeries('DryBulbTemperature')
puts timeseries.is_a? OpenStudio::OptionalTimeSeries
puts OpenStudio::OptionalTimeSeries.new.is_a? OpenStudio::OptionalTimeSeries

**Comment by macumber** [comment]
We need to add a ruby test that uses all this functionality

**Comment by macumber** [comment]
While we are at it I recommend removing the setters from EpwDataPoint, if you need to make these you can set then in the ctor.  @jasondegraw we probably already discussed this, do you remember the reason to keep these public?

**Comment by jasondegraw** [comment]
It also appears that the data period parser is not accepting dates with years, which it should:

![weather-tbl14-pg45](https://cloud.githubusercontent.com/assets/4623433/6758908/7565a4e2-cf01-11e4-86bc-c3457a92c00e.png)

@macumber @nllong What should the policy be? Start date and end date both have a year or both do not?

**Comment by macumber** [comment]
@jasondegraw what do you mean by start and end date?  are these entries in the header?

**Comment by jasondegraw** [comment]
@macumber The problematic data period line looks like this:

    DATA PERIODS,1,1,weather,Sunday,1/1/2008,12/31/2011

It occurred to me that someone might put in

    DATA PERIODS,1,1,weather,Sunday,1/1/2008,12/31

or

    DATA PERIODS,1,1,weather,Sunday,1/1,12/31/2011

I tend to think that we should accept the first one above, but neither of the others. But maybe need to see what E+ will take.

**Comment by macumber** [comment]
Ok, I get it now and agree with your assessment

**Comment by jasondegraw** [comment]
@macumber It turns out that E+ will take all of the variations in my earlier comment under the "right" circumstances... so I think we need to try to accept all of them. Could we do something with an optional year, or do we just need to have the bigger discussion about multi-year simulations?

(also, @nllong)

**Comment by macumber** [comment]
@jasondegraw can this be closed for now?  multi-year simulations are another topic

**Comment by jasondegraw** [comment]
@macumber Yes, I think this can safely be closed. So, closed.
