### ISSUE TITLE
LowTemperatureRadiant system input 'Radiant Surface Type' translates unexpected surfaces to SurfaceGroup

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#1459]
Tested in OpenStudio 1.6.0 Window x64, for Variable Flow, Constant Flow, and Electric Low Temperature Radiant Systems: 
1. Create space and apply internal source construction to all surfaces, create and assign thermal zone to space.
2. Apply LowTemperatureRadiant:VarFlow/ConstFlow/Electric, change 'Radiant Surface Type' in edit pane.
3. Run, examine 'in.idf' from \5-EnergyPlus-0.

Results:
- If Radiant Surface Type = 'Ceilings', ZoneHVAC:LowTemperatureRadiant:SurfaceGroup contains ceiling and floor surfaces (unexpected).
- If Radiant Surface Type = 'Floors', ZoneHVAC:LowTemperatureRadiant:SurfaceGroup contains floors only(expected).
- If Radiant Surface Type = 'CeilingsAndFloors', ZoneHVAC:LowTemperatureRadiant:SurfaceGroup contains floors only (unexpected).
- If Radiant Surface Type = 'AllSurfaces', ZoneHVAC:LowTemperatureRadiant:SurfaceGroup contains all surfaces (expected).

**Comment by eringold** [comment]
This issue continues to trip people up (e.g.: https://unmethours.com/question/19016/radiant-ceiling-and-floor/, https://unmethours.com/question/14676/radiant-ceiling-system/), and though it's been a good karma factory for me, I suppose I should be part of the solution.

Best I can tell, the problem is probably related to [this line](https://github.com/NREL/OpenStudio/blob/8296251db964cfdac272468381950d6327b42500/openstudiocore/src/model/ZoneHVACLowTempRadiantVarFlow.cpp#L257), where `(istringEqual("Ceiling", surfaceType)` should read: `(istringEqual("RoofCeiling", surfaceType)`. There might be more; I can't really understand why that bad conditional would result in the first observation above, e.g. Radiant Surface Type = 'Ceilings' returning ceilings and floors. 

@kbenne @macumber if you could confirm that's the problem, I'll volunteer to do the heavy legwork to fix it! :smile:

**Comment by eringold** [comment]
Also here (constant flow): https://github.com/NREL/OpenStudio/blob/8296251db964cfdac272468381950d6327b42500/openstudiocore/src/model/ZoneHVACLowTempRadiantConstFlow.cpp#L230

And here (electric): https://github.com/NREL/OpenStudio/blob/8296251db964cfdac272468381950d6327b42500/openstudiocore/src/model/ZoneHVACLowTemperatureRadiantElectric.cpp#L188

**Comment by macumber** [comment]
This line:
`
else if(istringEqual("Floor", surfaceType) || (istringEqual("Ceiling", surfaceType) && istringEqual("CeilingsandFloors",surfGrpName))){`

should be 

`else if((istringEqual("Floor", surfaceType) || (istringEqual("Ceiling", surfaceType)) && istringEqual("CeilingsandFloors",surfGrpName)){`

@eringold you want to try making the change?

**Comment by macumber** [comment]
The issue was the grouping of the logical tests

**Comment by eringold** [comment]
Ah, that's it. 

...but it should also be `(istringEqual("RoofCeiling", surfaceType)`  too, right?

**Comment by macumber** [comment]
Yes, good catch!

**Comment by eringold** [comment]
Thanks Dan! :+1:
