### ISSUE TITLE
onPercentageUpdated can be called with negative percentage when importing ddy file (Bugzilla #787)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#146]
On 2012-07-16 12:28:19, @macumber wrote nothing.

On 2012-07-23 16:53:52, @DavidGoldwasser wrote:

> <batch change bugs from unconfirmed to new>

**Comment by DavidGoldwasser** [comment]
@axelstudios and @macumber, do either of you know if this is still an issue. Seems like odd case so I'll show as low frequency minor, but feel free to close if not valid anymore.
