### ISSUE TITLE
Inherited Default Construction and Schedule Sets Not Displayed in Facility Tab

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1460]
If there's a default construction or schedule set assigned at the building level it doesn't show up as an inherited attribute with green text at the space type level.

![openstudio_issue1460-1](https://cloud.githubusercontent.com/assets/8397034/6136359/523b2182-b12d-11e4-9b02-cd3c66cf5a15.png)

![openstudio_issue1460-2](https://cloud.githubusercontent.com/assets/8397034/6136360/55588fd0-b12d-11e4-9df5-513125da3673.png)

![openstudio_issue1460-3](https://cloud.githubusercontent.com/assets/8397034/6136405/9f4de46e-b12d-11e4-9149-3578ced27b3e.png)

**Comment by MatthewSteen** [comment]
Possibly related to Feature Request #1449 - Show Source for All Inherited Values.

**Comment by macumber** [comment]
@MatthewSteen #1449 is a feature request to have a mouseover or something show you where the inherited value is coming from (e.g. inherited from building, from space type, etc).  This issue #1460 is just a bug and should stay.

**Comment by evanweaver** [comment]
To be fixed under the following:
Implement inheritance across all girdviews #1946
https://github.com/NREL/OpenStudio/issues/1946
