### ISSUE TITLE
Sql.annualTotalUtilityCost and .annualTotalCost methods incorrect when dist htg or dist clg

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1461]
The [sql.annualTotalUtilityCost method](https://github.com/NREL/OpenStudio/blob/0d1320b512a04a867f2a5614316ef44ac6725f47/openstudiocore/src/utilities/sql/SqlFile_Impl.cpp#L1060) works by calling [sql.annualTotalCost](https://github.com/NREL/OpenStudio/blob/0d1320b512a04a867f2a5614316ef44ac6725f47/openstudiocore/src/utilities/sql/SqlFile_Impl.cpp#L1008) with each of the different fuels and adding up the results to become the annual total.  However, the table only has entries for Electricity, Gas, and Other (see below).  This means if you have utility rates for DistrictHeating, DistrictCooling, Water, or the other fuels, they don't get returned properly by these two methods.

![image](https://cloud.githubusercontent.com/assets/2009290/6137194/371955a2-b134-11e4-8246-0edb4e4b9382.png)

You can circumvent this bug by writing your own sql query, but that is not ideal.

Here is the workaround query:

`SELECT Value from tabulardatawithstrings where (reportname = 'Economics Results Summary Report') and (ReportForString = 'Entire Facility') and (TableName = 'Annual Cost') and (ColumnName ='Total') and (((RowName = 'Cost') and (Units = '~~$~~')) or (RowName = 'Cost (~~$~~)'))`

**Comment by asparke2** [comment]
This affects the PAT results tab.

**Comment by macumber** [comment]
@asparke2 you still working on this for 1.7.0?

@axelstudios FYI

**Comment by asparke2** [comment]
Yeah, just finished up the tests.

Andrew Parker
Staff Engineer
NREL Commercial Buildings Group
W:  303-275-4568
C:  252-626-8842
andrew.parker@nrel.gov
