### ISSUE TITLE
SizingPlant Units and Conversion Appear Incorrect

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1462]
@kbenne - the `Loop Design Temperature Difference` field is labeled  as "K" but should be "C" according to the EP documentation. The unit conversion also appears to be incorrect...

**Code:**
>  hot_water_plant = OpenStudio::Model::PlantLoop.new(model)
    hot_water_plant.setName("Plant Loop HHW")
    sizing_plant = hot_water_plant.sizingPlant
    sizing_plant.setLoopType("Heating")
    sizing_plant.setDesignLoopExitTemperature(OpenStudio.convert(180,"F","C").get)
    sizing_plant.setLoopDesignTemperatureDifference(OpenStudio.convert(32,"F","C").get) #bug?

**Result:**
![openstudio_issue1462](https://cloud.githubusercontent.com/assets/8397034/6159617/30bd3890-b215-11e4-96be-21ab1488cbcb.png)

**Comment by kbenne** [comment]
@MatthewSteen this field as a delta T so wouldn't Rankine and Kelvin be appropriate scales?  And in the example code don't you want to convert from Delta F to Delta C which would be equivalent to converting from R to K?  i.e. OpenStudio.convert(32,"R","K").get which is 32 * 5/ 9 ~= 17.8.

**Comment by kbenne** [comment]
Hey @MatthewSteen what do you think, am I off base here or can I close this with no action?

**Comment by MatthewSteen** [comment]
@kbenne it did work for me with the conversion set to R and K. I had tried other combinations such as R to C expecting that OS wanted R and EP wanted C like in the IO Ref which gave strange results. Case closed.

**Comment by kbenne** [comment]
@MatthewSteen I would say the IO Ref is just a little imprecise.  They really mean delta C.  Thanks for following up.
