### ISSUE TITLE
Change peak flow rate in water use equipment definitions from cfm to gal/min

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1468]
![image](https://cloud.githubusercontent.com/assets/2009290/6196052/b29caa3a-b391-11e4-9619-ec7410115f55.png)

**Comment by MatthewSteen** [comment]
@asparke2 this came up today in one of our projects, do you happen to know if OS is correctly converting/translating this value to EP?

**Comment by asparke2** [comment]
@MatthewSteen yeah, OS is correctly changing from cfm to m^3/s.  You can also see the conversion by toggling IP to SI units.

**Comment by kbenne** [comment]
@MatthewSteen you want to verify this yourself or can I close this based on the work I did on the other issue?

**Comment by MatthewSteen** [comment]
@kbenne no, I was just pointing out the duplication and it seems like an easy fix.
