### ISSUE TITLE
ScheduleEditor issues

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1469]
These are issues not addressed by https://github.com/NREL/OpenStudio/pull/1463

When purging multiple schedules, the schedule editor may show an empty page, it should find the next non-removed schedule

When you first go to the schedules tab, the default profile page shows for the first schedule, but the line isn't plotted. This only happens when you open the model, and before you've clicked on any schedule. After you click any schedule, the line shows up. Not a huge deal.

**Comment by evanweaver** [comment]
Fixed.
