### ISSUE TITLE
Translation of objects to EnergyPlus should happen in sorted order (Bugzilla #788)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#147]
On 2012-07-16 12:29:07, @macumber wrote:

> Same thing with importing ddy, constructions, etc in plug-in, SDD translator, etc

On 2012-07-23 16:53:53, @DavidGoldwasser wrote:

> <batch change bugs from unconfirmed to new>

Keywords: BadSimResults

**Comment by DavidGoldwasser** [comment]
@macumber Do we now sort this? But I still remember an issue with them not being in the same order as how it would be from IDF editor, and that resulting in slightly different simulation results form the same model. I'll lower priority but leave it open for now.
