### ISSUE TITLE
SQL files containing illuminance maps are very large

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1471]
The schema of our illuminance map data matches that in E+, this allows ResultsViewer to open datasets from E+ or radiance runs. However, these SQL files are very large.  Possible that database structure could be improved in E+ and matched in OS.

**Comment by macumber** [comment]
Currently daylightmaphourlyreports has a separate time index for each map, can we reuse the time table for report variables?

**Comment by macumber** [comment]
daylightmaphourlydata has x and y point for each illuminance map point, possible that this could be reduced

**Comment by macumber** [comment]
@mbadams5 have you taken a look at these tables?

**Comment by macumber** [comment]
Would be best to store all the illuminance map values for each map as an array inside a single cell for each timestep, This would cut down size by a factor of 4 at least.

http://www.experts-exchange.com/Database/Miscellaneous/Q_27114435.html

**Comment by mbadams5** [comment]
@macumber I'd be curious about the size difference between 8.2.0 and current develop. I removed an index on DaylightMapHourlyData which should dramatically reduce the database file size.
