### ISSUE TITLE
SimulationControl choices not translating to E+

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1472]
Looks like the choices from SimulationControl aren't being translated to E+ correctly (ref: [UnmetHours](https://unmethours.com/question/3054/disable-zoneplantsystem-sizing/)).

![openstudio_issue1472-1b](https://cloud.githubusercontent.com/assets/8397034/6237638/c01c1100-b6b1-11e4-836d-2dd69e6a9621.png)
![openstudio_issue1472-2b](https://cloud.githubusercontent.com/assets/8397034/6237647/d1826458-b6b1-11e4-9f50-08fc99de6122.png)

![openstudio_issue1p](https://cloud.githubusercontent.com/assets/8397034/6237174/d1a41728-b6ad-11e4-89e2-171a72827a31.png)
![openstudio_issue2p](https://cloud.githubusercontent.com/assets/8397034/6237177/daae25b6-b6ad-11e4-876d-4f753031592f.png)

**Comment by kbenne** [comment]
@MatthewSteen Well there are some overrides in the translator to make sure simulations don't crash.  This is a great example of OpenStudio trying to thread a needle between usability and full EnergyPlus power.  Did we miss the mark?

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateSimulationControl.cpp#L59

**Comment by kbenne** [comment]
@MatthewSteen maybe I should be more explicit. If you said no to zone sizing (and there are zones and design days) your simulation would fail anyway.  It has been a while since I have been in these dark corners, but I'm pretty sure it has to do with how we define ventilation.  Maybe other things too.

**Comment by kbenne** [comment]
OK.  I reviewed the Unmet Hours post.  I see LSurf points has a valid scenario where zone sizing could be off and OpenStudio is not allowing it.  Seems like a valid complaint.  Maybe that override logic should just go away.  OS default zone sizing on, allow it to be turned off manually and respect that choice potential E+ failure or not.

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio/blob/c018cb6316372cb77b33a4f62f22452908320bc9/src/energyplus/ForwardTranslator/ForwardTranslateSimulationControl.cpp#L63-L87

@kbenne how about:

```
    if (modelObject.doZoneSizingCalculation()) {
      simCon.setString(openstudio::SimulationControlFields::DoZoneSizingCalculation, "Yes");
-    } else if ((numSizingPeriods > 0) && (modelObject.model().getConcreteModelObjects<ThermalZone>().size() > 0)) {
+  } else if (modelObject.isDoZoneSizingCalculationDefaulted() &&
                 (numSizingPeriods > 0) && (modelObject.model().getConcreteModelObjects<ThermalZone>().size() > 0)) {
      simCon.setString(openstudio::SimulationControlFields::DoZoneSizingCalculation, "Yes");
    } else {
      simCon.setString(openstudio::SimulationControlFields::DoZoneSizingCalculation, "No");
    }
```

**Comment by jmarrec** [comment]
Or maybe even better:

```c++
    auto hasZoneEquipment = [](const Model& m) {
      auto zones = m.getConcreteModelObjects<ThermalZone>();
      return std::any_of(zones.cbegin(), zones.cend(), [](const auto& z){ return !z.equipment().empty(); });
    };

    if (modelObject.doZoneSizingCalculation()) {
      simCon.setString(openstudio::SimulationControlFields::DoZoneSizingCalculation, "Yes");
    } else if ((numSizingPeriods > 0) && hasZoneEquipment(modelObject.model())) {
      if (modelObject.isDoZoneSizingCalculationDefaulted()) {
        LOG(Info, "You have zonal equipment and design days, and SimulationControl::DoZoneSizingCalculation is defaulted: turning on Do Zone Sizing Calculation");
        simCon.setString(openstudio::SimulationControlFields::DoZoneSizingCalculation, "Yes");
      } else {
        LOG(Info, "You have zonal equipment and design days, it's possible you should enable SimulationControl::DoZoneSizingCalculation");
      }
    } else {
      simCon.setString(openstudio::SimulationControlFields::DoZoneSizingCalculation, "No");
    }
```

**Comment by kbenne** [comment]
@jmarrec What is the value of DoZoneSizingCalculation for a new model. If is isn't "Yes" then won't there always be some logging noise unless the user deliberately sets "Yes"?

**Comment by kbenne** [comment]
Well assuming there is zone equipment...

**Comment by jmarrec** [comment]
DoZoneSizingCalculation is useful if you have a zone with zonal equipment that is actually autosized. We don't have a handy way of checking if an equipment is autosized (we have a way to autosize() only), so that's just trying to be more precise.

As far as logging goes, we can remove the case where we default it to Yes. I doubt many people read Info log levels anyways.

**Comment by jmarrec** [comment]
@kbenne ping.

**Comment by jmarrec** [comment]
@kbenne pong.

**Comment by jmarrec** [comment]
@kbenne ping.

**Comment by jmarrec** [comment]
@kbenne PONG.

Related to https://github.com/openstudiocoalition/OpenStudioApplication/issues/693 where I realized that it'd be better is that logic would be in the model namespace rather than the ForwardTranslator.
