### ISSUE TITLE
IG Hard Sized / Autosized Behavior 

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1476]
To reproduce:

1. Add ZoneHVAC equipment to zone
2. Click the blank space in the sizing section leaving the Autosized bullet selected. A ghost cursor will appear in the Hard Sized field
3. Click anywhere in the IG which will add a ghost 0 or 2.2204460492503e-16 value to the Hard Sized field
4. Run the model which should fail because the hard sized ghost values are used even though Autosized is selected

![openstudio_issue1476](https://cloud.githubusercontent.com/assets/8397034/6287609/0529a256-b8d0-11e4-902c-6acd7757bc42.png)

**Comment by DavidGoldwasser** [comment]
Good catch @MatthewSteen. @kbenne I just confirmed this on my machine as well. It took a little testing, but it appears that clicking anywhere on the name of the field title will do this. This same behavior happens on components in the HVAC tab as well, not just zone equipment on the Thermal Zone tab.

**Comment by kbenne** [comment]
Yep.  I see it now.  Not when i click in the field, but when i click on the field names label.  Strange...
