### ISSUE TITLE
URL links in measure description are not clickable 

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1477]
We are using html formatting so <a href=''>link</a> looks like a link in OS app and PAT but it is not clickable, would be useful for measure writers to link for more information

**Comment by kbenne** [comment]
@macumber I think [this](http://qt-project.org/doc/qt-4.8/qlabel.html#openExternalLinks-prop) is the answer.

**Comment by macumber** [comment]
Yeah, probably something like that, I think the fields are actually line edits

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
