### ISSUE TITLE
Allow measures to require gems

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1483]
Would allow users to specify gems to use in their measures.  Would have to allow users that download the measure to get the gem as well as on upload to the cloud.

**Comment by MKSahm** [comment]
Thank you, this would b every useful

**Comment by macumber** [comment]
Current thinking is that we will package a fixed set of gems with OpenStudio, these will be available to all users.  There is a process for developers to install their own set of gems to use before a gem is added to OpenStudio.  @axelstudios can you elaborate on this?

**Comment by axelstudios** [comment]
Packaged gems get added [here](https://github.com/NREL/OpenStudio/blob/develop/dependencies/ruby/Gemfile)

Packaged gems can be made available to everyone by adding them [here (prod)](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/ruby/openstudio.rb#L154) and [here (dev)](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/ruby/openstudio_dev.rb#L128), or they can be required on a case by case basis.

If you're a developer, you can simply modify the Gemfile, run CMake, and build the Ruby target to update Gemfile.lock and install the gem.

If you're a user and you want to try out a custom gem, you can install that gem in OpenStudio's ruby directory or your own and then require 'openstudio'.  If you use your own ruby, any gems you have installed that are also packaged with OpenStudio will override the packaged gems.

**Comment by asparke2** [comment]
This now works.  You can require the (few) gems that  are included with OS:

```Ruby

gem 'openstudio-workflow', '= 1.2.2' 
gem 'openstudio-standards', '= 0.1.13' 
gem 'rspec', '= 3.5.0'
gem 'test-unit-minitest', '= 0.9.1'
gem 'parallel', '= 1.10.0'
gem 'bundler', '= 1.14.4'
```
