### ISSUE TITLE
Enable build of OpenStudio without QWebKit

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1485]
This should be fairly straightforward and would support work on peregrine

**Comment by kbenne** [comment]
@macumber yes but build options can get numerous and intertwined.  How about focusing on carving out some big targets.  I keep trying to push three. Utilities, Model, Apps.  QWebKit would fall under Apps.

**Comment by macumber** [comment]
Even better, I was just trying to carve down the scope to something that would be feasible to get done quickly.  Here is what I get when building on peregrine:

The WebKit build was disabled for the following reasons:
    * ICU is required. To build QtWebKit with Qt 5 you need to build Qt 5 with libICU support. Check for ICU support being mentioned in qtbase/config.summary.
    * Missing gperf from PATH

I guess I could just try to get those dependencies loaded, kill this request, and hope that some day we will have time to tackle the big fish

**Comment by axelstudios** [comment]
QtWebEngine similarly has a [long list of dependencies](http://qt-project.org/wiki/QtWebEngineHowToTry)
