### ISSUE TITLE
Need to use Q_DECL_EXPORT and Q_DECL_IMPORT macros (Bugzilla #791)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#149]
On 2012-07-17 15:19:55, @macumber wrote:

> http://qt-project.org/doc/qt-4.8/sharedlibrary.html
> 
> Scott Criswell had trouble using OpenStudio shared libraries due to linker errors:
> 
> 1>OS_Wrap.obj : error LNK2001: unresolved external symbol "public: static struct QMetaObject const openstudio::detail::IdfObject_Impl::staticMetaObject" (?staticMetaObject@IdfObject_Impl@detail@openstudio@@2UQMetaObject@@B)
> 1>OS_Wrap.obj : error LNK2001: unresolved external symbol "public: static struct QMetaObject const openstudio::detail::WorkspaceObject_Impl::staticMetaObject" (?staticMetaObject@WorkspaceObject_Impl@detail@openstudio@@2UQMetaObject@@B)
> 
> Think we need to use Qt's version of dll export and import in our API headers instead

On 2012-07-23 16:53:53, @DavidGoldwasser wrote:

> <batch change bugs from unconfirmed to new>

**Comment by DavidGoldwasser** [comment]
Seems stale. Since we have switched versions of QT a few times since this I'm going to close. We can re-open if needed.
