### ISSUE TITLE
OS App incorrectly indicates unsaved changes with *

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1491]
Sometime the OS App inexplicably shows model.osm\* in the top bar, indicating that you have unsaved changes, even if you haven't made any changes to the model.

This happens:
1.  Whenever you go to the Site tab
   osm changes from:
   `file:files/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw, !- Url`
   to:
   `file:///C:/Users/aparker/Desktop/Testing/GridView MultiEdit/Office with Many HVAC System Types/files/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw, !- Url`
   the first time, but every time thereafter it gets marked as changed even if nothing was actually changed.
2.  Whenever you go to the Simulation Settings tab
   No change to the .osm upon save.
3. Sometimes when you go to the Constructions tab (if you have Materials in the model)
   osm has this added:
   `OS:StandardsInformation:Material,
   {6dc7d5fa-3c48-44c9-b17b-9da54810131c}, !- Handle
   {798ca11c-1b7b-4a20-8175-a6957c7183e1}; !- Material Name`

My suggestion is to fix up all of this junk when the file is first opened and save it for the user.  Then, make it stop re-doing this stuff whenever you switch tabs.

A few users have asked about this, and are worried that they have inadvertently changed things without meaning to.

**Comment by macumber** [comment]
Kristin hit this and was concerned about it too, lowers confidence in the software.

**Comment by macumber** [comment]
Certain tabs create unique objects the first time you open them (e.g. settings tab).  So clicking on the tab really does change the model.  These objects should be initialized either on open or in the model ctor.  Doing in the ctor is not great because we do have the idea of model as a component.  Maybe model could initialize everything but component would not?

This issue is worse now that we are doing the one tab in memory thing.  You can get different results running the same osm depending on which tabs you visit, not good.

**Comment by macumber** [comment]
@kbenne @evanweaver FYI

**Comment by macumber** [comment]
I think this can be closed now, any objections @asparke2 @DavidGoldwasser ?

**Comment by asparke2** [comment]
It would be better to initialize the default objects when a new file is created so that this weird behavior doesn't happen.

**Comment by macumber** [comment]
Is it still happening?  I got some of these things but not sure if all

**Comment by asparke2** [comment]
I tested it with a model I created via the standards gem.  Maybe it is fixed for models created with the App?

**Comment by macumber** [comment]
Yeah, it doesn't apply to all Models because that would mess up components.  You can call this method if you want to create all those objects:

https://github.com/NREL/OpenStudio/blob/553516614161dda1c9117f671e9584e24675bf28/openstudiocore/src/model/FileOperations.hpp#L82

**Comment by jmarrec** [comment]
Should we close this now?

**Comment by jmarrec** [comment]
Closing now, can always reopen if you voice a strong opinion.
