### ISSUE TITLE
Installer puts 64 bit E+ in 32 bit OS installer.

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#1496]
Probably need to reconfigure the build machine and watch out for this in the future, as there is no programatic catch for this in the cmake finder.  On that note consider adding guards against this in the finder.

https://unmethours.com/question/3110/openstudio-160-unable-to-run-energyplus-82/

**Comment by axelstudios** [comment]
Since both architectures of E+ install to `C:\EnergyPlusV8-2-0`, is there any possibility for using `Program Files` and `Program Files (x86)` as the default locations?

**Comment by kbenne** [comment]
oh yuck.  There isn't a good way to determine architecture in the finder is there?  EnergyPlus has a long history of C:\ I believe I tried to move to Program Files once in the past and met resistance.  I think the near term solution is to just make sure the build machines are configured with the right flavor and then for E+ release maybe I should add a ticket to provide some kind of signal for which flavor it is.  

Maybe energyplus --version should tell you something?  Right now it gives 

```
energyplus --version
EnergyPlus, Version 8.2.9-aa1e951b5c
```

**Comment by axelstudios** [comment]
Those cli arguments aren't in 8.2.0, right?  Maybe just a `energyplus --arch` so that it's machine parsable

**Comment by kbenne** [comment]
They are not, but will be in the coming 8.3.0.

**Comment by macumber** [comment]
Program Files would likely be a non starter, agree with the command line interface (see ruby's it tells you arch) and maybe a file too

**Comment by kbenne** [comment]
@macumber this sounds like what you are working on. Can it be assigned to you?
