### ISSUE TITLE
Undo delete space doesn't work (Bugzilla #797)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#150]
On 2012-07-27 10:48:54, @DavidGoldwasser wrote nothing.

On 2012-09-05 11:33:04, @DavidGoldwasser wrote:

> <re-validated with OpenStudio 0.8.4>
> 
> Sometimes work, sometimes doesn't, sometimes it looks like it works, but is out of sync when you re-open the file.

On 2012-09-10 08:16:35, @DavidGoldwasser wrote:

> <changed status of bugs in Pivotal to Assigned>

Keywords: SyncWithSU

**Comment by DavidGoldwasser** [comment]
Related to observers.
