### ISSUE TITLE
modelToGbxml method produces incomplete gbXML file (C#)

### ISSUE THREAD

**Issue by alnjxn** [NREL/OpenStudio#1502]
I am working with a well formed OpenStudio model. This model produces no errors in the OpenStudio GUI and can be run w/o issue. Exporting to gbXML via the GUI produces a complete gbXML file. Exporting the same model programmatically through the C# libraries produces an incomplete XML file. The XML shows only Zones where as the GUI version has Spaces, Zones, Surfaces, etc.

Openstudio Version: v1.6.0
Platform: Windows 8 x64

GUI Export 

```xml
<gbXML xmlns:xhtml="http://www.w3.org/1999/xhtml" volumeUnit="CubicMeters" areaUnit="SquareMeters" useSIUnitsForResults="true" xmlns:xsd="http://www.w3.org/2001/XMLSchema" temperatureUnit="C" xmlns="http://www.gbxml.org/schema" version="0.37" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gbxml.org/schema http://www.gbxml.org/schema/0-37/GreenBuildingXML.xsd" lengthUnit="Meters">
  <Campus id="Facility">
    <Name>Facility</Name>
    <Building id="Project_Name" buildingType="Unknown">
      <Name>Project Name</Name>
      <Area>4819.37</Area>
      <Space id="Instruction_221" zoneIdRef="Instruction_221">
        <Name>Instruction 221</Name>
        <Area>43.3277</Area>
        <Volume>164.645</Volume>
      </Space>
      <Space id="Conference_123" zoneIdRef="Conference_123">
        <Name>Conference 123</Name>
        <Area>44.032</Area>
        <Volume>167.322</Volume>
      </Space>
...
```

modelToGbxml Method Export

```xml
<gbXML areaUnit="SquareMeters" useSIUnitsForResults="true" volumeUnit="CubicMeters" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.gbxml.org/schema" xsi:schemaLocation="http://www.gbxml.org/schema http://www.gbxml.org/schema/0-37/GreenBuildingXML.xsd" temperatureUnit="C" version="0.37" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" lengthUnit="Meters">
  <Zone id="Administration_322">
    <Name>Administration 322</Name>
  </Zone>
  <Zone id="Electrical_227">
    <Name>Electrical 227</Name>
  </Zone>
  <Zone id="Stair_201">
    <Name>Stair 201</Name>
  </Zone>
  <Zone id="Instruction_205">
    <Name>Instruction 205</Name>
  </Zone>
...
```

C# Method

```csharp
//Save GBXML
OpenStudio.Path gbxmlpath = new OpenStudio.Path(path);
OpenStudio.GbXMLForwardTranslator gbxmlout = new OpenStudio.GbXMLForwardTranslator();
gbxmlout.modelToGbXML(_model, gbxmlpath);
```

**Comment by macumber** [comment]
@alnjxn that is very strange, I can't think of any reason that would be.  Is there anyway you could send me a link to your program that you are using to do this?  I should be able to load debug version of OpenStudio binaries and take a look.

**Comment by macumber** [comment]
Also, any chance you could send me the OSM?

**Comment by alnjxn** [comment]
Here is a link the the OSM file.
http://cl.ly/1n3N3s1Z0421/TestModel.osm

I would love to send you the entire application but it has dependencies on Autodesk Revit and Dynamo applications. Not sure how helpful it would be, but let me know.

**Comment by macumber** [comment]
@alnjxn thanks, is it possible to run with just Dynamo?  When looking at issues in Ladybug I can use a demo version of Rhino (nice that it does not expire) and Grasshopper is free.

**Comment by macumber** [comment]
@alnjxn is it possible to get the Vasari demo version to use with dynamo?

**Comment by macumber** [comment]
(I'm also curious to check out your work ;-)

**Comment by alnjxn** [comment]
@macumber Because the creation of the OSM model is dependent on Revit Levels and Rooms existing I don't think Vasari will work because it does not contain a room object. See below on how we build the OpenStudio Spaces, Building Stories, Thermal Zones etc. Maybe we can have a GoTo?

![2015-03-06 at 12 30 pm](https://cloud.githubusercontent.com/assets/1423708/6530174/a0ed657e-c3fc-11e4-9e73-de6ecfec12c7.png)

Also as a side note, the IDF export works as expected, so I am struggling with the idea that it is an issue with the way I am forming the model object.

**Comment by macumber** [comment]
@alnjxn would it be possible for you to create a small standalone command line C# app that reproduces the issue?

**Comment by macumber** [comment]
Hey Alan, can you make sure to instantiate a Facility object in your model?  This line of code might not write out the campus if you don't have one:

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/gbxml/ForwardTranslator.cpp#L150

**Comment by alnjxn** [comment]
@macumber Ahhhhh. You win.

```csharp
// Initialize the facility
Facility facility = _model.getFacility();
```

**Comment by macumber** [comment]
@alnjxn I thought you might find this link interesting.  It is a web viewer for OSM files I am working on, I used this model as a test case :-)

http://rawgit.com/macumber/openstudio-vA3C/master/doc/Issue1502.html

**Comment by alnjxn** [comment]
@macumber this is amazing! Would really love to help as more of this work gets moved to the web. very exciting.

**Comment by mostaphaRoudsari** [comment]
@macumber woohoo! We should have a load local file somewhere there. :tada:

**Comment by macumber** [comment]
Thanks :-)  We are going to be releasing this as a measure once I get the render by data working, eventually we want to integrate it into the app so you can click on surfaces in the web frame and have them get selected in the app.  The repo for this is here in case you are interested:

https://github.com/macumber/openstudio-vA3C

**Comment by mostaphaRoudsari** [comment]
This is awesome! We should find a way to have an exporter from Honeybee OpenStudio component to this viewer. We had an issue at the time to load measures but I haven't tried it recently. Thanks for the link.

**Comment by arif-hanif** [comment]
@alnjxn Alan hope things are going well at WeWork, was wondering if you were still doing this type of work. Any chance in you collaborating on an opensource project we will start out of unmethours to produce a utility for dynamo to OS.

**Comment by alnjxn** [comment]
@arif-hanif yes that would be great! I think between myself and Nate Miller we probably have some good basis for this as we prototyped in the past. Lets all sync up.
