### ISSUE TITLE
Add End Use Subcategory Fields

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1504]
The End Use Subcategory fields are missing from the following loads. This would be a nice feature to submeter certain process loads (e.g. elevators, kitchens, etc.).

* ElectricEquipment
* GasEquipment
* SteamEquipment

**Comment by macumber** [comment]
@MatthewSteen Maybe you are looking at the definition objects, these fields are available on the instances:

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/ElectricEquipment.hpp#L88

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/GasEquipment.hpp#L87

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/SteamEquipment.hpp#L87

**Comment by macumber** [comment]
I think we can close this as invalid

**Comment by MatthewSteen** [comment]
@macumber I was looking at the definitions. Where can this be specified in the GUI for these objects? I didn't see it in the Loads, Space Types, or Facility tabs. Thanks.

**Comment by macumber** [comment]
Currently this is only available to edit in the SketchUp plugin's inspector, you can view it if you drill all the way down to the load instances in the app

**Comment by MatthewSteen** [comment]
Ok, I see it now under the Load Name in Space Types tab. Assuming this field will be unlocked in a post 1.6.0 release.

**Comment by MatthewSteen** [comment]
https://openstudio.uservoice.com/forums/308629-openstudio/suggestions/11146404-end-use-subcategory

**Comment by jmarrec** [comment]
I vote to reopen this, and make this field editable by default in OS instead of being the classic "purple" (blue) locked-by-default field.

**Comment by aaron-boranian** [comment]
Make end-use subcategory editable for all equipment, fan, etc. 

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/11146404)
