### ISSUE TITLE
Deleting object from supply side of air loop messes up inlet nodes of mixed air setpoint managers (Bugzilla #799)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#151]
On 2012-07-27 13:42:54, @DavidGoldwasser wrote:

> I was trying to delete a fan and add new on other side. Deleting the fan seems to messes up the inlet node of all of the mixed air setpoint managers. If I delete the set point managers and add a new one they then hook up correctly.
> 
> Related to this when I add a new object in the node doesn't get a mixed air setpoint manager. Is there a way we can predict based on the object on each side of the node, which one is appropriate and add it in for the user?

On 2012-09-10 08:16:36, @DavidGoldwasser wrote:

> <changed status of bugs in Pivotal to Assigned>

On 2012-09-20 10:53:00, @DavidGoldwasser wrote:

> This is still valid, but I found out only happens if I delete the fan, or delete an object to the left of the fan that shares the fan's inlet node.
> 
> It would seem this is happening because the inlet node is being deleted, and the nodes don't re-ware to what now becomes the inlet node.

**Comment by DavidGoldwasser** [comment]
This has been addressed by feature added to automatically place mixed air stepping managers when the user doesn't
