### ISSUE TITLE
Run measures from inside SketchUp plugin

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1514]
We should allow users to run measures in my measures directory from inside the SketchUp plugin.  This will allow us to eventually deprecate the user scripts in favor of measures

**Comment by macumber** [comment]
Related to #164

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/29
