### ISSUE TITLE
ResultsViewer bugs from QWT update

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1518]
Found a few issues after the QWT update, I know illuminance maps have issues, not sure what else might be in there

**Comment by macumber** [comment]
@DavidGoldwasser @asparke2 @axelstudios  can you guys do some testing with the 1.6.3 package?

**Comment by macumber** [comment]
@axelstudios could you check out Linux and @kbenne could you check out Mac?

**Comment by rpg777** [comment]
The two issues I know about with this are:
(1) Nighttime illuminance map data displays all white, instead of blue (which is the color that is supposed to represent zero values): ![Nighttime Data in RV 1.6.3](https://cloud.githubusercontent.com/assets/3161332/6644322/7a22cda4-c978-11e4-9094-edcbeff491d2.png)

(2) Stepping through timestep data causes RV to crash. I can pretty reliably reproduce this by going forward a few hours, then back a couple (using the up/down arrow toggle). Typical core dump looks like this: 
```
Process:         ResultsViewer [1628]
Path:            /Users/USER/*/ResultsViewer.app/Contents/MacOS/ResultsViewer
Identifier:      gov.nrel.openstudio.58cd57aac2.resultsviewer
Version:         1.6.3 (58cd57aac2)
Code Type:       X86-64 (Native)
Parent Process:  launchd [430]
Responsible:     ResultsViewer [1628]
User ID:         1852480870

Date/Time:       2015-03-13 12:02:58.242 -0600
OS Version:      Mac OS X 10.9.5 (13F34)
Report Version:  11
Anonymous UUID:  E032A787-21E9-9B01-43E3-3D03CE69C463

Sleep/Wake UUID: D36B07F8-03B9-41AB-8F01-6CEDA781789E

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called
*** error for object 0x7fd703f02750: pointer being freed was not allocated
 

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff97752866 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff9323935c pthread_kill + 92
2   libsystem_c.dylib             	0x00007fff8ef24b1a abort + 125
3   libsystem_malloc.dylib        	0x00007fff94b5b07f free + 411
4   gov.nrel.openstudio.58cd57aac2.resultsviewer	0x000000010fe43b26 boost::numeric::ublas::unbounded_array<double, std::__1::allocator<double> >::~unbounded_array() + 70
5   gov.nrel.openstudio.58cd57aac2.resultsviewer	0x000000010fe43a85 boost::numeric::ublas::unbounded_array<double, std::__1::allocator<double> >::~unbounded_array() + 21
<snip>
```
I also think the daylight data (where present) is being plotted incorrectly, but I need to test that some more.

**Comment by macumber** [comment]
I have fixed the crash but still seem white pages when doing flood plots of data that is all 0's

Also the app is much slower but I don't need to look at that

**Comment by DavidGoldwasser** [comment]
@macumber I was seeing crash on my machine with E+ run. I'll build with your commit and try again.

One other minor thing I see. When I first load the map, the timescale slider is at the left, but the displayed day is 7/21. If I move the time up and down with arrows the slider stays at the left. As soon as I use the up/down on the date, the slider jumps to the middle of the year.

![3-17-2015 2-26-32 pm](https://cloud.githubusercontent.com/assets/4857055/6696889/21adb9f8-ccb2-11e4-98ec-a371ff13809b.png)

**Comment by macumber** [comment]
Filed https://github.com/NREL/OpenStudio/issues/1535 for the center and span issue
