### ISSUE TITLE
People Def can have values for multiple unit types, other loads can't

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1519]
I thought for all internal loads that at least the GUI (if not the API) only allowed you to enter a value for one of the unit types. This is true for other load types, but for some reason not for people. @macumber I assume this is an un-intentinal oversight vs. a design. Not clear what would happen on forward translation if you have multiple values. See screenshot below

![3-13-2015 11-34-05 am](https://cloud.githubusercontent.com/assets/4857055/6643870/5b633ed8-c975-11e4-8ee9-abcadd5d1404.png)

Note, that outdoor air does by design allow you to enter multiple values, and then uses a choice option to choose method handle the value. Infiltration is similar but the choice method in the end just picks one value. While not the subject of this bug it may be cleaner if it also just excepted one value so there is not confusion.

![3-13-2015 11-41-48 am](https://cloud.githubusercontent.com/assets/4857055/6643954/f6d7769a-c975-11e4-9562-b181db125fe7.png)

**Comment by DavidGoldwasser** [comment]
This came up in training recently, and caused some confusion. It only affects people load defs.

**Comment by macumber** [comment]
You are right @DavidGoldwasser this seems to be a GUI only bug, the model objects blank out the other fields, https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/PeopleDefinition.cpp#L179

**Comment by asparke2** [comment]
@macumber This commit doesn't appear to have broken the line edits, and does appear to have fixed the issue with the people definition.  The line edits are better in that they generally now start with the front of the word, and expand when the word exceeds the size.  This is great the first time you make an edit.  However, when you re-open the model the columns are back to their original (non-expanded) sizes and you see the end of the words.
