### ISSUE TITLE
We are not adjusting input value precision when it is first drawn on a page, as a result really long numbers (Bugzilla #800)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#152]
On 2012-07-27 13:45:32, @DavidGoldwasser wrote:

> It corrects it self when you enter and then leave the field but that shouldn't be necessary.

On 2012-09-10 08:16:36, @DavidGoldwasser wrote:

> <changed status of bugs in Pivotal to Assigned>

**Comment by DavidGoldwasser** [comment]
This is still valid, and very annoying both in the GUI, and when writing info messages in measures.

**Comment by evanweaver** [comment]
Closed. Will rely on more specific bugs to drive fixes in specific areas.
