### ISSUE TITLE
Floor/Ceiling Constructions creating issues with construction.getNetArea method

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1526]
When I call this method in a new model I hit it for every matched floor/ceiling surface, and since I loop through all constructions I hit this 527 on a single measure. As the images and text below show they are exact opposite constructions of each other. They are the constructions made with space type and construction set generator, and the plugin.

```
[openstudio.model.ConstructionBase] <1> Could not resolve matched surface construction conflicts between surfaces '1', and '1', area calculation may be incorrect
```

```
OS:Construction,
  {24f7753e-d747-406b-b867-62235a51db0b}, !- Handle
  Interior Ceiling,                       !- Name
  {980a6a9b-9c8d-4d19-b318-f97c3c73eb9c}, !- Surface Rendering Name
  {299a1cfb-327a-4427-83cc-862fee148597}, !- Layer 1
  {25c2915d-cf3f-4f68-8c90-eccbd9baeaae}, !- Layer 2
  {528df285-b758-4ff5-a376-88fe04c5c192}; !- Layer 3
```

```
OS:Construction,
  {7a9fb545-9100-4dec-a667-de4f0e4c7d03}, !- Handle
  Interior Floor,                         !- Name
  {b83371c3-657c-49ec-ba54-8c9421c27809}, !- Surface Rendering Name
  {528df285-b758-4ff5-a376-88fe04c5c192}, !- Layer 1
  {25c2915d-cf3f-4f68-8c90-eccbd9baeaae}, !- Layer 2
  {299a1cfb-327a-4427-83cc-862fee148597}; !- Layer 3
```

![3-16-2015 2-35-37 pm](https://cloud.githubusercontent.com/assets/4857055/6675929/d6ac8182-cbe9-11e4-8561-587f3dfcbd97.png)

![3-16-2015 2-28-54 pm](https://cloud.githubusercontent.com/assets/4857055/6675935/db834614-cbe9-11e4-89ba-ccf5c35652b0.png)

![3-16-2015 2-28-04 pm](https://cloud.githubusercontent.com/assets/4857055/6675937/dd9fd6a6-cbe9-11e4-9bb8-a3b5d201d658.png)

I added this to one of the AEDG measures, but anything that does this with constructions hits it. It still runs, but the errors slow things down a lot.
https://github.com/NREL/OpenStudio-measures/tree/develop/NREL%20working%20measures/AedgK12ExteriorWallConstruction/tests

secondary_school_space_attributes.osm is the new file that hits these errors. The content above is from this file.

0209_SimpleSchool_c123_dev.osm is an old file that doesn't have this issue, however it only has one pair of matched floor/ceiling surfaces, but still, doesn't even hit it for that. I'll try to investigate the difference. It has a symmetrical attic floor override the default interior ceiling of the space below.

**Comment by DavidGoldwasser** [comment]
I updated the test to use a new version of the old test model where I changed the attic to a typical space. It then hits the same error as the new model. It seems like mirrored matched constructions are falsely triggering the warning. Note: there are no surfaces named "1" in the model.

**Comment by DavidGoldwasser** [comment]
OK, so it seems like any time matched surfaces don't refer to the exact same construction this is triggered. So it isn't triggered on typical internal walls where we use the same construction for both sides, but it is triggered for floor/ceiling where we have mirrored constructions.

For this particular error message it doesn't seem to matter if the construction you pick is symmetrical or not, but of course not having a symmetrical or mirrored construction will fail later on when E+ has it.

The fix seems like it should be to recognize mirrored constructions correctly. We used to do this, I think in the past if there was a pair of surfaces that were each 10'x10', that we would count that as 50ft^2 of each of the two constructions (so we don't double count matched surfaces).

**Comment by macumber** [comment]
Here is an image to help explain the issue here.  Basically when floor/ceilings reference constructions that are reversed from each other it is difficult to assign an area to each construction without over counting the total area.  As far as I can tell, EnergyPlus does not report total area of each construction, either in the EIO (using Output:Constructions,Constructions) or in the html (Envelope Summary).  The only way I can think of to get this would be to add a dummy cost to each construction, I am not sure how EnergyPlus would handle matched surfaces (I suspect it might double count costs).  In the end, I wonder if we might deprecate construction.getNetArea and replace it with easier to compute and more relevant methods like construction.getExteriorSurfaceArea?  There are several measures using getNetArea, we would have to look at updating those.

![1526](https://cloud.githubusercontent.com/assets/1327850/10612607/b6cd4d3a-770e-11e5-96e4-6de839009130.jpg)

**Comment by macumber** [comment]
@asparke2 @DavidGoldwasser can you weigh in on this?

**Comment by macumber** [comment]
Finally, there are cases where the conflict resolution in the [ForwardTranslator](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator.cpp#L3037) is different than in the [Surface::construction method](https://github.com/NREL/OpenStudio/blame/develop/openstudiocore/src/model/Surface.cpp#L153).  This is because calling surface.construction will not change the model by adding new constructions or assigning constructions to surfaces, however these things do happen in the ForwardTranslator.  The less magic we have to do behind the scenes the better.

**Comment by DavidGoldwasser** [comment]
At some point I thought worked without an error. If surface was matched it counted as half of the area. There was logic added to pre-determine some of the mirrored constructions like what would happen for an attic floor at Forward translation. This gave better pre-translation numbers and also better render modes. Maybe that is when the errors came in?

Also used in the plugin, and in some jsonworkflowtest in runmananger. I'm sure it can be removed from there, but it is a shame we can't ask a construction how much it is used.
https://github.com/NREL/OpenStudio/search?l=ruby&q=getNetArea&utf8=%E2%9C%93

It is used 27 times in measures, but in many cases as a test to see if there are any surfaces using it vs. needed to know the area (looking for non-zero value). I can't just see if the construction is used, because it may be used in a construction set, but no surfaces in that construction set. It could be nice to have a method construction.getPlanarSurfaces that returns an array. 

If we do add method for exterior boundary condition, then I would also want to add these.
construction.getGroundSurfaceArea
construction.getAdiabaticSurfaceArea
construction.getSourfaceSurfaceArea (nothing funny, it could double count, then measure writer could divide in half if desired)

Users might want to alter the area for adiabatic as well depending upon if it is being used as floor/ceiling for zone with multiplier, a complex plenum, or a party wall.

**Comment by macumber** [comment]
@DavidGoldwasser how many of the use cases in measures are in reporting measures and could use data from output?  How many need to know the actual area used vs just if it is used at all?  I saw some code like if 'construction.getNetArea > 0'

**Comment by macumber** [comment]
I just confirmed that if you use E+ to cost the constructions in the example above you will double count the roof and ceiling (they are counted separate) but it does not double count the wall construction.  This appears to be an E+ bug according to the documentation for [ComponentCost:LineItem](http://bigladdersoftware.com/epx/docs/8-3/input-output-reference/cost-estimating.html#componentcostlineitem) which says:

> If the model includes duplicate surfaces, as for interior partitions or floors, these will be detected and not double-counted.

**Comment by macumber** [comment]
Scratch that, we are converting cost per area of construction to hard costs so this is our bad :-)

**Comment by DavidGoldwasser** [comment]
@macumber I think it is only used where I nee the value in a handful of places, which includes our standard report. I would like it to work from input vs. output so it can be run as an apply measure now, but I could just loop through all planer surfaces, and create a hash of constructions adding to the hash value for that key each time I see a surface using a specific construction.

EnergyPlus lists all surfaces, for our report I just list total for each construction. If I did use output I would probably consolidate it back to constructions.

**Comment by macumber** [comment]
If you loop over the surfaces like that you are going to double count the construction area of interior surfaces

**Comment by macumber** [comment]
Looks like the main thing this would affect in OpenStudio core is the translation of construction costs to total costs

**Comment by macumber** [comment]
@DavidGoldwasser I can think of two other solutions instead of removing this method.  

The first is to simply double count area for interior surfaces (e.g. count area of front and back sides).  This would support costing floors and ceilings (typically you would cost only one or the other of these) but you would over cost interior walls.

The second is to avoid double counting area if both surfaces use the same construction but allow double counting if they use different constructions.  This would support costing interior walls, floors, and ceilings in a way that would make sense.

**Comment by DavidGoldwasser** [comment]
@macumber just to take things back a bit to the original warning. I always thought this was an inadvertent warning. It should just be checking if the two constructions are mirrors of each other. (which they are in our model). and if they are it should leave them alone. How is area even getting into this check?

[openstudio.model.ConstructionBase] <1> Could not resolve matched surface construction conflicts between surfaces '1', and '1', area calculation may be incorrect

**Comment by macumber** [comment]
Well that is not the issue though @DavidGoldwasser.  This is from calling getNetArea in the reporting measure.  If there is a floor construction and a ceiling construction and they are mirrored copies of each other, what should getNetArea return for both?

**Comment by DavidGoldwasser** [comment]
@macumber what do we do for interior walls where the same construction is used on both sides? No warnings are thrown for the walls. Do we double count the matched walls or divide the calculated area for the two surfaces in half?

**Comment by macumber** [comment]
Re-opened, waiting for @DavidGoldwasser to accept in Pivotal.

**Comment by DavidGoldwasser** [comment]
@macumber I'll build and test in the morning. If the warnings are gone, I'm happy with any area calculation approach.

**Comment by macumber** [comment]
@DavidGoldwasser can you close if this is fixed?
