### ISSUE TITLE
Adding a daylighting control point in mac takes like 10 secodns (Bugzilla #802)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#153]
On 2012-07-27 15:16:12, @DavidGoldwasser wrote:

> Rob, is that normal? I did this on the model for the training. Basic 8 space hotel.

On 2012-09-10 08:16:36, @DavidGoldwasser wrote:

> <changed status of bugs in Pivotal to Assigned>

**Comment by DavidGoldwasser** [comment]
Going to close, will create new or reopen if I can re-confirm it.
