### ISSUE TITLE
setMinimumHotWaterOrStreamFlowRate (should be steam instead of stream)

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1536]
User reported typo in method name. 

https://github.com/NREL/OpenStudio/search?utf8=%E2%9C%93&q=setMinimumHotWaterOrStreamFlowRate

@kbenne @asparke2 and @macumber. Is anyone using this yet, or can we fix it and drop support for the current name. My guess is nobody is using steam yet or we would have seen this.

**Comment by kbenne** [comment]
I'll fix this right away, but I can guarantee you that nobody is doing steam systems because we don't have all of the component they need.  Plus E+ developers claim it is flat out broken, so.... I guess someone could be doing heavy idf measures to put together a steam system, but very doubtful.

**Comment by kbenne** [comment]
@DavidGoldwasser actually I see now that this is in AirTerminalSingleDuctVAVReheat.  That is a majorly common object.  I don't think changing the method name is a good idea.  I could add a synonym, but really I'd prefer to just to nothing.

**Comment by DavidGoldwasser** [comment]
@kbenne someone is going to use that object, that's how they saw this issue, I assume we want it matching the IDF object field which I assume is "steam" and not "stream". I'm much happer with synonym approach vs. doing nothing. Could the documentation point to the synonym vs. the original object?

**Comment by asparke2** [comment]
Closing this issue.  Haven't heard of it being an issue for anyone since opened.
