### ISSUE TITLE
Change default idd file type for Workspace.new

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1538]
Apparently I have been living under a rock or something but I thought that Workspace.new made an EnergyPlus workspace.  It actually makes an OpenStudio one and has for some time:

https://github.com/NREL/OpenStudio/blame/develop/openstudiocore/src/utilities/idf/Workspace.cpp#L2672

I think that most people calling Workspace.new want an EnergyPlus workspace, if they wanted an OpenStudio one they would make a model?

@DavidGoldwasser @asparke2 @kbenne you guys have thoughts?

**Comment by macumber** [comment]
Found this while testing, had to change the IDF measure tests in this commit https://github.com/NREL/OpenStudio/commit/9a8e5317b58f89c823df95a7efc923d2c8744a66

If we fix this issue we can change the tests back to Workspace.new (so people dont have to worry about what strictness or iddfiletype are)

**Comment by kbenne** [comment]
I guess I was living under the same rock.  It sure seems like the implications could be major for this.  Like not accessing the fields you think you are when writing an IDF Measure.  If that is true then surely we would have encountered this by now?  And what about validation?  Is the default strictness simply weak enough to let it go through?

**Comment by macumber** [comment]
I think so, I ended up with an idf file that had an OS:Version object and a Zone one

**Comment by kbenne** [comment]
I guess most idf measure work would use integer field keys so I can imagine this sliding by.  But then there is the object list tracking... are you sure the workflow isn't specifying the IDD on Workspace creation for IDF Measure?

**Comment by kbenne** [comment]
certainly the translator is doing the right thing.

https://github.com/NREL/OpenStudio/blob/9a8e5317b58f89c823df95a7efc923d2c8744a66/openstudiocore/src/energyplus/ForwardTranslator.cpp#L374

but that probably doesn't guarantee other parts of the workflow.

**Comment by macumber** [comment]
@kbenne when you run ModelToIDF in the app you get out a correct workspace, that is passed in to you measure.  This is specifically about calling Workspace.new which we were doing in some IDF measure tests, the defaults are wonky.

I had to change our default tests to now do:

    OpenStudio::Workspace.new("Draft".to_StrictnessLevel, "EnergyPlus".to_IddFileType)

which is just ugly

**Comment by kbenne** [comment]
good.  That is defiantly key.  That you get the correct type of workspace passed to you in idf measure.  Seems this issue is not as alarming as I originally read it to be.

**Comment by jmarrec** [comment]
Seems like a non issue in the end no?

**Comment by macumber** [comment]
I think it's still valid, the default for Workspace should be EnergyPlus

**Comment by jmarrec** [comment]
Addressed in #2873 (building right now, I'll check the Gtest to make sure there aren't unintended consequences)
