### ISSUE TITLE
Workflow for setting up thermostats for heating only or cooling only systems - e.g. type 9 and 10 (Bugzilla #817)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#154]
On 2012-08-03 10:58:16, @DavidGoldwasser wrote:

> This is kind of minor, but thought while you were thinking about thermostats this would be good. If you are using a heating only system it seems you still have to assign a cooling schedule. And if you don't put a real one (that doesn't overlap the heating schedule) energy plus will fail.
> 
> If we just want to have user workflow to add a dummy cooling schedule then we can mark this as invalid. Otherwise maybe we can make a dummy cooling schedule on translation if one is needed, or not use dual setpoint thermostat object?

On 2012-09-10 08:16:36, @DavidGoldwasser wrote:

> <changed status of bugs in Pivotal to Assigned>

**Comment by DavidGoldwasser** [comment]
I added feature request issue. Users who make heating only or cooling only systems hit issues trying to figure it out.

**Comment by jmarrec** [comment]
Implemented Heating/Cooling only tstats in #2813 (with hotfix in #3134).

Can close.
