### ISSUE TITLE
Move BCL Measures to GitHub

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1542]
Unfortunately I haven't seen a lot of community interaction on the BCL and I think moving development here may facilitate more involvement from the larger BEM community. Not sure if this strays from the larger vision for BCL Measures, but I will close this feature request if it does.

**Comment by macumber** [comment]
@MatthewSteen we already use github for our measure repository however the repo is currently private.  The long term plan is for this to be public but we need to do some cleanup and housekeeping before we are ready for that.  @DavidGoldwasser can grant you access in the meantime

**Comment by MatthewSteen** [comment]
Closing and happy to help out @DavidGoldwasser.
