### ISSUE TITLE
Seeing "Autocalculate" in Maximum Air Flow Rate for termial object

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1543]
@kbenne is this normal, I would expect the "Autosized" radio button to be checked. 

![3-20-2015 9-16-19 am](https://cloud.githubusercontent.com/assets/4857055/6754418/07b257f2-cee2-11e4-90bb-b8c1e71b51a1.png)

**Comment by kbenne** [comment]
Not normal.  Or at least not desired.  The IG doesn't know how to distinguish autocalculate and autosize.  I think we just need to mark it autosize in our IDD for IGs benefit.  Or perhaps enhance IG.
