### ISSUE TITLE
Apply to Selected - issue on larger models (Selecting affect zones/ space types)

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1546]
When you select a row in the column with checkbox for (Apply to Selected) on a longer model that doesn't fit on the screen, the display jumps back to the top, so you have to scroll down again to get back to the zone/space type you were just looking at. It would be good if it could maintain it's position. When you want to check 5/6 zones you need to keep scrolling back down each time.

Again, I think this could be a known issue for now. On the SpaceTypes tab you can filter to minimize how long your display is, making scrolling not as necessary.

**Comment by jmarrec** [comment]
Don't have this problem in OS 2.2.1
