### ISSUE TITLE
SpaceType Tab - Load filter should function on infiltration objects

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1547]
This may be more feature than bug, as infiltration objects are a different animal than the other internal loads. There are two parts to this issue. The more important issue is having infiltration objects not show up when you filter by a specific load type. In the attached screenshot it would be nice to be able to select all to quickly delete all people objects from space types. The second part would be adding infiltration objects to the filter list, so you can filter just for them.

The two infiltration object types affected are:
SpaceInfiltrationDesignFlowRate
SpaceInfiltrationEffectiveLeakageArea (this isn't used much but the other is in every space type)

Also, kind of trivial but, when in Custom View the filter pulldown should be grayed out, much like it is in general view. I don't think any of this has to be fixed for this release, can come later.

![3-20-2015 9-51-56 am](https://cloud.githubusercontent.com/assets/4857055/6755287/8ddca1ca-cee7-11e4-9623-ee84eae69c3d.png)

**Comment by evanweaver** [comment]
Fixed via https://www.pivotaltracker.com/n/projects/134010/stories/102491628
