### ISSUE TITLE
Coordinate fine/coarse Sky Subdivision Params in idd

### ISSUE THREAD

**Issue by rpg777** [NREL/OpenStudio#1549]
"coarse" Radiance settings should use 146 divs (145 sky + 1 ground); "fine" should use 2306 ((144sky * 16) + 1zenith + 1ground)

See:

https://github.com/NREL/OpenStudio/blob/3b37505da2004880ffd80bc448a6ece2333cf243/openstudiocore/src/radiance/ForwardTranslator.cpp#L353

https://github.com/NREL/OpenStudio/blob/0774a1a564ca869fcb097bb2a4645386abd3ca4e/openstudiocore/src/osversion/VersionTranslator.cpp#L1527

https://github.com/NREL/OpenStudio/blob/0774a1a564ca869fcb097bb2a4645386abd3ca4e/openstudiocore/src/osversion/VersionTranslator.cpp#L2159

**Comment by macumber** [comment]
There seems to be some flip flopping about whether the "medium" level should be 578 or 581.  @rpg777 do we even need a medium setting?

**Comment by rpg777** [comment]
Yeah, it's 578, and I included the "medium" discretization out of convention. I think most people use the fine, and sometimes the coarse for testing. What really should do is change the thing to a simple INT subdivision parameter, since that's how Radiance interprets it anyway. Users can specify as many subdivisions of the Tregenza as they wish, really.

**Comment by macumber** [comment]
Making it an int is great and does not require futzing with the version translator.  Can Radiance really support any number?  I would think there might be only so many ways you can subdivide the sky evenly?

**Comment by rpg777** [comment]
It can; more specifically, the .cal files that use this subdivision support it, but tools downstream can choke on higher resolutions. The subdivisions work with any integer because that number is applied in the x,y dimensions of the baseline 144 Tregenza patches that define the hemisphere _excluding the zenith patch_. At some point Patch#145 (the zenith) gets disproportionately larger than the others, but the sun is only ever in that region near the equator anyhow. In the end, I think it's cleaner to just specify and pass around the integer value. The GUI may still want to display the total patches as a helpful reminder, but we can put that in the NiceToHave bucket.

**Comment by evanweaver** [comment]
Implemented with applyCoarseSettings() and applyFineSettings().
