### ISSUE TITLE
No daylighting output variables available (Bugzilla #820)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#155]
On 2012-08-06 08:08:36, @macumber wrote nothing.

On 2012-09-10 08:16:37, @DavidGoldwasser wrote:

> <changed status of bugs in Pivotal to Assigned>

**Comment by DavidGoldwasser** [comment]
Model may have been missing proper objects. I'm sure this will be re-exercised with upcoming Radiance work and will fix if seems to be an issue then.
