### ISSUE TITLE
Thermal Zone tab Library disappears

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1550]
I haven't found the steps to reproduce this yet, but will update or close if I haven't identified it.

While working on a large model (175 zones) all the options in the Thermal Zone Library disappear (eg FanZoneExhaust, PTAC, etc).

**Comment by MatthewSteen** [comment]
This happens in the Facility tab in 1.7.0 after applying a measure and accepting changes.

![openstudio_issue1550-1](https://cloud.githubusercontent.com/assets/8397034/7071182/e272c58e-dea0-11e4-9cdc-2a767cfb38d5.png)

**Comment by jmarrec** [comment]
Probably stale as well.

**Comment by MatthewSteen** [comment]
Thermal zones are no longer visible from the Facility tab.
