### ISSUE TITLE
Remove scan for tools

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1553]
We are now shipping most tools needed for simulation, we should begin shipping radiance and remove the scan for tools functionality

The scan for tools dialog is confusing to users (what is default idf directory for?  are you supposed to pick the e+ version? etc)

Would be better to just have methods like energyplusDir and radianceDir that work for all installs

**Comment by macumber** [comment]
Potentially kill all these issues in one fell swoop https://github.com/NREL/OpenStudio/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+scan+for+tools

**Comment by macumber** [comment]
Depends on https://github.com/NREL/OpenStudio/issues/1441

**Comment by asparke2** [comment]
Fixed with 2.X

**Comment by aaron-boranian** [comment]
Problem: The “Scan for Tools” feature is confusing, has issues, and is potentially not needed anymore

Rationale: We are now shipping most tools needed for simulation, we should begin shipping radiance and remove the scan for tools functionality

Solution: Remove the “Scan for Tools” feature and package dependencies such as radiance together with OpenStudio

Depends on: 
http://openstudio.uservoice.com/forums/308629-openstudio/suggestions/9099670-ship-radiance-with-openstudio

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9097990)
