### ISSUE TITLE
BCL Components can't be purged from model

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1559]
After adding components from the BCL to a 1.6.3 model they can't be purged from Constructions or Materials and must be deleted individually. Probably a minor, low frequency bug. 

Steps to reproduce:
1. add components from BCL to model
2. try to purge from Constructions or Materials

**Comment by macumber** [comment]
@MatthewSteen I know what this is about, thanks for reporting

@kbenne FYI

**Comment by MatthewSteen** [comment]
Still valid in 1.10.4.

**Comment by jmarrec** [comment]
Still valid in 2.2.1

**Comment by macumber** [comment]
Root cause is https://github.com/NREL/OpenStudio/issues/125
