### ISSUE TITLE
Cancelling simulation can result in boost filesystem exists error (Bugzilla #827)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#156]
On 2012-08-06 08:16:38, @macumber wrote nothing.

On 2012-09-10 08:16:37, @DavidGoldwasser wrote:

> <changed status of bugs in Pivotal to Assigned>

On 2012-09-19 14:31:59, @DavidGoldwasser wrote:

> Dan, not sure where you first saw this, but rob just reported a beach ball of death if he cancels a simulation via the OS app. May be same as this.
> 
> David

**Comment by DavidGoldwasser** [comment]
I'm going to close this unless, it is reported again.
