### ISSUE TITLE
Diagnostic script does not remove orphan surfaces 

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1560]
https://unmethours.com/question/3888/how-to-fix-openstudio-input-file-errors-and-warnings/?comment=3930#comment-3930

**Comment by macumber** [comment]
Might also want to consider windows with area larger than base surface? https://unmethours.com/question/3908/openstudio-error-sub-surface-is-not-contained-by-its-base-surface/

**Comment by DavidGoldwasser** [comment]
@macumber the user script doesn't currently attempt to do this. 
https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/ruby/openstudio/sketchup_plugin/user_scripts/Reports/OSM_Diagnostic_Script.rb

It only checks for very small surfaces, or for more than one surface with the same geometry (or more than one sub-surface with the same geometry). Is the error triggered in the plugin on opening a model using an OpenStudio method? If so the we should be able to add it. There are many things we should add, but I already started a measure to remove orphan and un-used objects.
https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/ruby/openstudio/sketchup_plugin/user_scripts/Reports/OSM_Diagnostic_Script.rb

I was hoping that this measure (with some user options) or a collection of measures would take the place of the diagnostic script. Loosely related to this would be a pre-flight measure to check for things we know will make simulation fail.

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/28
