### ISSUE TITLE
Temporary run directories not removed

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1561]
https://unmethours.com/question/3408/os-does-not-delete-temporary-folders/

**Comment by kbenne** [comment]
I do believe this is something we might want to cleanup, but at the same time isn't a temporary location the operating system's responsibility to clean up.  Isn't that the whole idea of tmp?  @lefticus ?

**Comment by macumber** [comment]
Recently I had to delete all the kruft in my tmp directory on Windows, some was OpenStudio but most was not, it had accumulated to like 10 GB!  Nothing seemed to break when I did that so I guess it was ok but Windows was not cleaning these up on it's own

**Comment by lefticus** [comment]
@kbenne on Unix, yes. A reboot almost always cleans up tmp. I don't think that Windows has ever done that though. IMO, it's a good idea to clean up as much in the tmp if you can, but if you crash and leave something behind, that's not the end of the world.

**Comment by MatthewSteen** [comment]
I recently noticed this as well on my Windows machine. Running OS sims every day had created a lot of wasted space so I scheduled `disk cleanup` to run once a week as a fix.

**Comment by jmarrec** [comment]
Do windows user still have this problem with the new 2.x series?

**Comment by evanweaver** [comment]
Pre-2.0 issue.
