### ISSUE TITLE
Diagnostic script does not remove subsurfaces not contained by its base surface

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#1563]
https://unmethours.com/question/3908/openstudio-error-sub-surface-is-not-contained-by-its-base-surface/

To expand further, I created geometry in Rhino (badly apparently), and I'm processing it and exporting it to osm with honeybee, hence the problematic subsurfaces.

I am using:
Sketchup Make 2015
OpenStudio 1.6.0.1229eac298
E+  8.2.0

The diagnostic script doesn't remove any object. When I close and reload the file, some of the surfaces end up appearing and I can delete them.

Thanks,
Julien
PS: Is it customary to attach a link the culprit osm file? (first time user of this issue tracker)

**Comment by macumber** [comment]
Thanks @jmarrec, yes please post a link to your file.  We have another place where we store files related to issues so we can dig them up when we go to fix bugs

**Comment by jmarrec** [comment]
One guilty model here: http://we.tl/FUFjX5I1qE (there so much more wrong in it too!)

**Comment by macumber** [comment]
@DavidGoldwasser is the diagnostic script now a measure or still just in SketchUp?

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/27
