### ISSUE TITLE
ptac default view in the inspector is not consistent with other zone hvac objects

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1566]
In the Thermal Zones tab when selecting a `ZoneHVACPackagedTerminalAirConditioner` object to edit in the Inspector I've noticed the following behaviors in 1.6.0 and 1.7.0:
1. When changing the name of the PTAC in the Inspector and moving to another field, the view is reset to the default connections subtab (loses focus?).
2. The default view in the Inspector is the connection subtab which differs from other ZoneHVAC objects and is less frequently in need of editing once it's set which adds a step. 

(2) could be a separate issue as I've seen inconsistencies in which view is the default for zone equipment (PTACs, FCUs, VAVs, etc.). I can add another one if that's the case.

**Comment by MatthewSteen** [comment]
Still valid in 1.10.4. The default view for the PTAC object is the connections sub-tab instead of edit unlike all the other zone HVAC objects.

**Comment by jmarrec** [comment]
Still true OS 2.2.1, default is the chain icon subtab for PTAC. I'd add the "Minor Bug" tag...
