### ISSUE TITLE
Results summary not aggregating energy use in monthly bins

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/OpenStudio#1567]
The results summary in OpenStudio is not aggregating the results correctly. 

As an example, here is the gas consumption over the course of a year, which is reasonable: 
![results_viewer](https://cloud.githubusercontent.com/assets/2249271/6944021/a784863e-d85f-11e4-91c0-ac4a08c57677.png)
This is what the results summary shows: 
![results_summary](https://cloud.githubusercontent.com/assets/2249271/6944022/a784a916-d85f-11e4-9ae8-b8143c5a738a.png)
It is aggregating all heating into June and July, and improperly allocating electricity consumption as well.  This is occurring for several different models, including ones built and run correctly in previous OS versions.

**Comment by macumber** [comment]
Thanks @mdahlhausen

Possibly related to https://github.com/NREL/OpenStudio/issues/1568

**Comment by macumber** [comment]
@mdahlhausen can you provide an OSM to reproduce this? What is your RunPeriod? Are you attempting to match an actual year or just use TMY file?

**Comment by mdahlhausen** [comment]
Hi Dan,

Here is the OSM file.
RunPeriod is a full year, using a TMY file.
Windows 7 Enterprise, 64 bit

We were able to replicate the problem with OS 1.6.3, and on another machine
running Windows 7 with OS 1.6.3 and OS 1.7.  The problem did NOT show up in
OS 1.6.3 on a Mac.

**Comment by macumber** [comment]
@mdahlhausen can you attach a link to your file?  I don't think email attachments come through

**Comment by mdahlhausen** [comment]
let's try google drive [link](https://drive.google.com/file/d/0B20gWa-PODz5em1WZS1sZWZqOUk/view?usp=sharing)

**Comment by macumber** [comment]
Hmm, I am not seeing this:

![4-1-2015 1-53-45 pm](https://cloud.githubusercontent.com/assets/1327850/6950313/44d0b090-d877-11e4-8dbe-09b59f2c0970.jpg)

Can you go into your model's companion directory and find the report.html file, for me this is in E:\test\Issue1568\run\6-UserScript-0\.  Can you open that html file in a web browser (preferably Chrome or Firefox) and see if it renders?

**Comment by macumber** [comment]
I wonder if you are somehow looking at stale results?

**Comment by muh182** [comment]
@macumber I do receive the same error as @mdahlhausen mentioned it. Here is my screenshots from the app and html file.

![capture](https://cloud.githubusercontent.com/assets/2249257/6951870/5e282e28-d88c-11e4-9466-092690a21316.PNG)

![capture1](https://cloud.githubusercontent.com/assets/2249257/6951871/6094a7cc-d88c-11e4-9b97-4264230e5ab6.PNG)

May be we are missing some dependencies.

**Comment by mdahlhausen** [comment]
It renders, but gives the same error.  [here is the folder]( 
https://drive.google.com/folderview?id=0B20gWa-PODz5fjdZZVZHRzQ4MDh5UEJnQlBuTWFXblgtUHgyOC1OdzBFTnZ3SGliMFNUSzg&usp=sharing)

**Comment by macumber** [comment]
I am simulating with EnergyPlus, Version 8.2.0-8397c2e30b and you seem to be simulating with EnergyPlus, Version 8.2.0-e53a815bb2.  This should not be possible but I guess it is.  Can you try running scan for tools and then re-run your simulation?

**Comment by mdahlhausen** [comment]
I tried with both EnergyPlus versions and both had the same issue.  It shows up in the results viewer, so I don't think it is an issue with the EnergyPlus run.  any other ideas?

**Comment by macumber** [comment]
How did you get OpenStudio to use a different version of EnergyPlus than Version 8.2.0-8397c2e30b

**Comment by mdahlhausen** [comment]
I'm not sure; maybe I had version 8.2.0-e53a815bb2.before version 8.2.0-8397c2e30b?.  @muh182 is having the same issue with version 8.2.0-8397c2e30b.  We can demo it tomorrow in our call with @muh182  and @nmattise.

**Comment by macumber** [comment]
I am guessing that this might be due to use of the wrong EnergyPlus version, see this post https://unmethours.com/question/2660/energyplus-sql-query-returns-incorrect-value/

Let's talk tomorrow with @kbenne

**Comment by macumber** [comment]
Determined that the issue was OpenStudio incorrectly using EnergyPlus 8.2.0 instead of EnergyPlus 8.2.0-Update 1 even after running scan for tools.  After removing EnergyPlus 8.2.0 and installing [v8.2.0-Update-1](https://github.com/NREL/EnergyPlus/releases/tag/v8.2.0-Update-1.2) then running scan for tools, the issue was resolved.  All users should update their 8.2.0 installs to 8.2.0 Update 1.
