### ISSUE TITLE
Blank Results Viewer in OpenStudio 1.7

### ISSUE THREAD

**Issue by lukedorna** [NREL/OpenStudio#1568]
I just installed OpenStudio 1.7 and ran through the simulation of a simple office model. It's a central chilled/hot water plant, hot water reheat terminals, for a three story office building in CZ3. 

Sadly, the OpenStudio results viewer shows no results, just a blank screen. I have not seen any instructions or indications about needing to enable the results viewer. 

![image](https://cloud.githubusercontent.com/assets/11756861/6945235/3e0a99a8-d866-11e4-88ab-f7de13ddf2fd.png)

**Comment by macumber** [comment]
Thanks @lukedorna, we will look into this

Possibly related to https://github.com/NREL/OpenStudio/issues/1567

**Comment by macumber** [comment]
@lukedorna can you provide an OSM to reproduce this?  What is your RunPeriod? Are you attempting to match an actual year or just use TMY file?

**Comment by lukedorna** [comment]
OSM attached. Simple tmy annual run peroid.

**Comment by lukedorna** [comment]
I have the same issue as #1567 as well.

**Comment by macumber** [comment]
@lukedorna can you attach a link to your file? I don't think email attachments come through

**Comment by lukedorna** [comment]
@macumber  At the risk of sounding ridiculous, I have no clue how to attach a file in github. I just discovered you guys moved your support to this platform, which appears to be geared toward developers, not simple users like me. 

Can you tell me how to get a file to you?

**Comment by macumber** [comment]
No its not your problem, its ours.  You can either upload it to something like dropbox and then send a link or you can email openstudio@nrel.gov

**Comment by lukedorna** [comment]
@macumber File sent to openstudio@nrel.gov with subject "OSM for issue #1568"

**Comment by macumber** [comment]
excellent thanks!

**Comment by macumber** [comment]
Hmm, I am not seeing this:

![4-1-2015 2-09-39 pm](https://cloud.githubusercontent.com/assets/1327850/6951526/43617468-d879-11e4-850f-07812325b82f.jpg)

Can you go into your model's companion directory and find the report.html file, for me this is in E:\test\Issue1568\run\6-UserScript-0. Can you open that html file in a web browser (preferably Chrome or Firefox) and see if it renders there?

**Comment by macumber** [comment]
What operating system are you on (Windows 7?) and are you using 32 or 64 bit OpenStudio?

**Comment by lukedorna** [comment]
![image](https://cloud.githubusercontent.com/assets/11756861/6951613/82d125ba-d88a-11e4-93a9-15a16e54e33d.png)

This is what I see when I navigate to the file you directed, which is similar to the other issue. 

Also, I am using Windows 7, 64 bit, with 64 bit OpenStudio.

**Comment by macumber** [comment]
@asparke2 the only thing I can think of (besides Webkit problems) would be changes to the sql queries

@lukedorna if you save your model as different files and run this multiple times do you get different results html files?

**Comment by lukedorna** [comment]
@macumber 
![image](https://cloud.githubusercontent.com/assets/11756861/6952050/3c39d266-d88d-11e4-8d86-7fb7ba79b24f.png)

Nope. The resaved file provides the same results. Note that the results are actually correct in the energyplus output file. It's just the OS results viwer that has the weird values.

**Comment by macumber** [comment]
I am simulating with EnergyPlus, Version 8.2.0-8397c2e30b, can you check what version you are running by looking at the eplusout.err file or the eplustbl.htm file?

If you have something different can you try running scan for tools and then re-run your simulation?

**Comment by asparke2** [comment]
@macumber I wonder if fixing the sql query here: https://github.com/NREL/OpenStudio/pull/1534 could have done something?  I added unit tests, but maybe messed something up?

**Comment by macumber** [comment]
@asparke2 maybe, I have not been able to reproduce this yet

**Comment by macumber** [comment]
@lukedorna can you check if the resolution to https://github.com/NREL/OpenStudio/issues/1567 works for you?

Remove EnergyPlus 8.2.0, install [EnergyPlus v8.2.0-Update-1](https://github.com/NREL/EnergyPlus/releases/tag/v8.2.0-Update-1.2), then running scan for tools

**Comment by DavidGoldwasser** [comment]
Likely due to EnergyPlus SQL query bug
