### ISSUE TITLE
Cannot plot two variables with different units (Bugzilla #830)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#157]
On 2012-08-06 08:17:59, @macumber wrote nothing.

On 2012-09-10 08:16:37, @DavidGoldwasser wrote:

> <changed status of bugs in Pivotal to Assigned>

**Comment by DavidGoldwasser** [comment]
I don't think we have to support this, but I think it used to crash. Will have to re-test to see if that still happens.
