### ISSUE TITLE
New building.clone breaks space surface matching

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1571]
I made a quick measure to test this out. Found a similar issue to what I see if I loop through spaces in an external model and clone them over one by one. The surface matching breaks.

Here is the test measure
https://github.com/NREL/OpenStudio-measures/blob/develop/NREL%20working%20measures/clone_building_from_external_model/measure.rb

Here is a screenshot in SketchUp
![4-1-2015 3-09-19 pm](https://cloud.githubusercontent.com/assets/4857055/6952862/beb3b6c2-d882-11e4-88ec-f95c84fa44c7.png)

OS app as well for reference.
![4-1-2015 3-21-39 pm](https://cloud.githubusercontent.com/assets/4857055/6952878/e75ed5a2-d882-11e4-8970-b3a09cba54db.png)

@macumber any ideas? I gave this a major flag because we have a lot of different ways people are faking a (change seed model) measure. I was hoping to setup a clean example for others to use.

**Comment by DavidGoldwasser** [comment]
![4-1-2015 3-24-39 pm](https://cloud.githubusercontent.com/assets/4857055/6953007/b3be7968-d883-11e4-8437-15c277fd721b.png)

I'm pretty certain, that the handles changing on objects as they clone plays a role in the issue; it isn't the surface names that match to each other, it is the handles. @kbenne this seemingly would also create issues re-linking to space types, thermal zones and stores, but you have got those working. Is there a similar solution for surfaces.In my merge user script in the plugin I have to rely on names to since I can't rely on the handle, so I make a temporary hash before the clone and use it after the clone to re-wire everything back together.

**Comment by macumber** [comment]
Oh gross, ok

**Comment by macumber** [comment]
@DavidGoldwasser I'm not sure that cloning spaces one by one should preserve surface matching.  If you clone the entire building at once is it preserved?  Or if you clone an entire story is surface matching preserved within the story?

**Comment by DavidGoldwasser** [comment]
@macumber surface matching isn't preserved using building.clone. The screenshots in the original post are the results of the measure I created that uses building.clone with 1.7.0.

**Comment by DavidGoldwasser** [comment]
@macumber I hit this again on best test. I thought the code below would fix it, but it didn't change things. It is also odd that it now exports in forward translator as "Adiabatic" , vs. "Outdoors"

`      # surface match to fix issue with clone building
      #put all of the spaces in the model into a vector
      spaces = OpenStudio::Model::SpaceVector.new
      model.getSpaces.each do |space|
        spaces << space
      end

      #match surfaces for each space in the vector
      OpenStudio::Model.unmatchSurfaces(spaces)
      OpenStudio::Model.matchSurfaces(spaces)`

In the end, this is what worked.

`surface_a.setAdjacentSurface (surface_b)`

**Comment by jmarrec** [comment]
I can reproduce using 3.2.0 with the following ruby code

```ruby
include OpenStudio::Model
[1] m = exampleModel()
[2] energyplus(main)> m.getSurfaces.select{|s| s.adjacentSurface.is_initialized()}.size()
=> 8
[3] energyplus(main)> b = m.getBuilding
[4] energyplus(main)> m2 = Model.new
[5] energyplus(main)> b2 = b.clone(m2)
[6] energyplus(main)> m.getSurfaces.select{|s| s.adjacentSurface.is_initialized()}.size()
=> 8
[7] energyplus(main)> m2.getSurfaces.select{|s| s.adjacentSurface.is_initialized()}.size()
=> 0
```
