### ISSUE TITLE
Some RefrigerationCase defrost options are not supported

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#1573]
The problem is that you don't have access to the supporting curve in the app.

https://unmethours.com/question/4096/defrost-correction-curve/

**Comment by asparke2** [comment]
Alisa from Seventhwave reported that the defrost type is missing in the GUI.  Can we add these to the GUI to make this more usable?

**Comment by jmarrec** [comment]
Still true OS 2.2.1. http://bigladdersoftware.com/epx/docs/8-7/input-output-reference/group-refrigeration.html#field-case-defrost-type is missing.

**Comment by jmarrec** [comment]
Need to try in GUI to see if it's available there (it is available in Model API), to know whether this can be closed or not. Relabeling as Enhancement.

**Comment by jmarrec** [comment]
Tested in OS App 2.7.1: 

![image](https://user-images.githubusercontent.com/5479063/53479890-5354d380-3a7a-11e9-8e97-1507575aff55.png)
