### ISSUE TITLE
Weather files with non-epw extensions (e.g. amy)

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1574]
The app should allow you to select the _._ filter for opening weather files with other extensions

**Comment by macumber** [comment]
Also, if you set an amy file, save your osm, then set another weather file, the previous amy file remains in the files dir.  I think the code to clean up weather files must only be looking for epw files.  It should also look for the name of the file referenced by the current model

**Comment by macumber** [comment]
@evanweaver I believe you are working on this

**Comment by evanweaver** [comment]
Verified that non-epw extension files are deleted.
