### ISSUE TITLE
Add per-column precision to gridview

### ISSUE THREAD

**Issue by evanweaver** [NREL/OpenStudio#1578]

**Comment by evanweaver** [comment]
I added this long ago because someone thought it was needed. I am guessing that @asparke2 or @DavidGoldwasser was the actual originator of this feature request. Is this still a valid feature request? If so, @kbenne I'd like to discuss my GUI design idea, as well as persistence.

**Comment by evanweaver** [comment]
After review and discussion with @asparke2 this feature will now focus on removing trailing zeros which don't impart any additional information or accuracy to the user.

**Comment by aaron-boranian** [comment]
Problem: TBD

Solution: Add per-column precision to gridview

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9098851)
