### ISSUE TITLE
Sensible Heat Fraction Incorrect Inheritance Tag

### ISSUE THREAD

**Issue by dstuder** [NREL/OpenStudio#1579]
Looks like the Sensible Heat Fraction field in the People Definition object is incorrectly assuming that it has been inherited from another object, since it's displayed in green. Observed in OS 1.7 on a Windows machine.

![image](https://cloud.githubusercontent.com/assets/6117383/7027921/71904d5e-dd20-11e4-84a3-2c75a2f2aa86.png)

**Comment by dstuder** [comment]
Looks like this may also be occurring for the "North Axis" parameter on the "Facility" tab. At least I don't think this field is being inherited.

![image](https://cloud.githubusercontent.com/assets/6117383/7095919/73968f54-df9c-11e4-80fe-e78f114f56e6.png)

**Comment by macumber** [comment]
There is a technical difference between defaulted (which building north axis is) and inherited.  I'd leave it to Marj to decide how (or if) she wants to differentiate between those

**Comment by dstuder** [comment]
@macumber I was under the impression that OS did not treat default values. Is that incorrect? If OS does display defaulted values in green, what rule set is used to determine if a value is a "default?"

**Comment by macumber** [comment]
Default corresponds to no value in the OSM file, the default value comes from the IDD or somewhere in the code.  Inheritance is a special (more complicated) case of default.

**Comment by dstuder** [comment]
@macumber Oh, well in that case, I guess neither of these are bugs.

@asparke2

**Comment by evanweaver** [comment]
@dstuder it's good GitHub form to close your own tickets when you realize they are chaff.
