### ISSUE TITLE
Increase Header Emphasis 

### ISSUE THREAD

**Issue by dstuder** [NREL/OpenStudio#1582]
It would be awesome if the text identifying which tab a user has navigated to was larger/emphasized. This same comment applies to tab titles as well.

![header emphasis](https://cloud.githubusercontent.com/assets/6117383/7054291/8bf2bca6-de09-11e4-87ac-6495eda96fbb.png)

**Comment by marj-schott** [comment]
These are smaller in order to avoid taking up too much space in the interface. There will be times when there are more tabs and we will need the room. Because of the strong affordances of the tabs I think we are OK in assuming that these will be understood as headers because they are in the tabs.

**Comment by dstuder** [comment]
@marj-schott Planning ahead?!? Nice! But what about the white text that tells you what page you're on ("Site" in this case)? Would it take up too much screen real estate to make it a bit larger/bold? Also, delaying the start of the first tab (for pages with tabs) could also help to un-crowd that space and make it easier to identify which page the user is on.
