### ISSUE TITLE
Wrap Tab Boundary Around Whole Viewing Pane

### ISSUE THREAD

**Issue by dstuder** [NREL/OpenStudio#1583]
I've noticed that while the top and left tab boundaries are bounded by blue, the right and bottom tab boundaries are not (see screenshot). To me, this makes it look like the page content bleeds to the right and down off the page even when there is no additional content (granted, sometimes there is more content, but this is indicated by scroll bars). In future releases, I think it would be great if the same blue boundary extended around the entire main viewing window. I think that would provide a more finished look to the UI, and would help indicate to users that they were viewing the entirety of the window’s content.

![os tab boundary](https://cloud.githubusercontent.com/assets/6117383/7054327/cb91f61a-de09-11e4-9d85-9cf2c3c4bc00.png)

**Comment by marj-schott** [comment]
I think this is one that we should wait and see if we get additional feedback indicating that this is confusing. I would hate to give up any additional content space if we don't have to and I think this would take a quite a bit of custom GUI work to implement.

**Comment by macumber** [comment]
I kind of prefer it the way it is.  I think if this is just a matter of competing preferences Marj should make the final call

**Comment by dstuder** [comment]
Definitely a preference thing. I agree with @marj-schott's suggestion to take a wait and see approach, with the default to leave as-is.

**Comment by asparke2** [comment]
Declaring the wait-and-see period closed and closing this issue.
