### ISSUE TITLE
Expand Arrow Trigger Area

### ISSUE THREAD

**Issue by dstuder** [NREL/OpenStudio#1584]
I’ve noticed that the arrows that expand sections (in this specific instance, I was defining schedules) seem to only operate if you click to the left of the arrow, and won’t work if you click the arrow itself. I was puzzled by this for a long time thinking that my computer was not being responsive. If there’s a way to move the trigger point so that it overlays the arrows, or becomes larger such that it encompasses them, I think it would be an improvement.

**Comment by marj-schott** [comment]
I am having some difficulty reproducing this, could you send a screenshot?

**Comment by marj-schott** [comment]
@evanweaver and @kbenne  Could you respond to this?

**Comment by dstuder** [comment]
@evanweaver and @kbenne this appears to only be an issue on the "Schedules" tab of the "Schedules" page.

**Comment by jmarrec** [comment]
Still true in OS 2.2.1 (very minor inconvenience though)
