### ISSUE TITLE
Thermal Zones Tab Rectangular Button Revision Request

### ISSUE THREAD

**Issue by dstuder** [NREL/OpenStudio#1585]
It was recently pointed out to me that you can click the dark gray rectangles at the top of columns in the “Thermal Zones” tab to add them to the “Custom” view. It’s a pretty neat feature, but I doubt I would have ever figured that out on my own. Just my two cents, but I feel like turning those into actual buttons would be helpful to users. One solution would be to add a button that said “Add to Custom” similar to how the “Apply to Selected”
![rectangular button request](https://cloud.githubusercontent.com/assets/6117383/7055152/5eb0cfca-de0f-11e4-9844-c81a0dd54a4c.png)
 is implemented.

**Comment by marj-schott** [comment]
This would have to be a toggle button that then said "Remove from Custom". I think we should talk with Andrew to see if he thought this change would solve this problem and also with Evan to see how hard that would be to do.

**Comment by marj-schott** [comment]
It sounds like Kyle, Dan, Larry, Andrew, and others have had issues with the custom select. So we should all come to some idea that pleases everyone.

**Comment by kbenne** [comment]
I think that a traditional button is too much visual clutter and importance for this feature, but the current look is certainly obfuscated.  But what is the alternative?  A button that says "Click here to add this column to the custom view" !  You're know best @marj-schott so I defer.

**Comment by marj-schott** [comment]
It does feel really heavy handed. I will work on some alternatives @kbenne and @evanweaver

**Comment by marj-schott** [comment]
What about this idea? It works sort of like favorites so I am using that style of icon. It would go on the column and on the custom button to help clarify. @dstuder , @kbenne , @evanweaver , @ljbrackney

**Comment by evanweaver** [comment]
I think it is a simple, additional visual queue, which utilizes a currently common paradigm.  I like it, and like Kyle, I defer to you so you have my proxy vote too.

**Comment by marj-schott** [comment]
@kbenne , @evanweaver : here are the files for the heart button. I think it is the most intuitive solution.
![custom_on](https://cloud.githubusercontent.com/assets/8094932/7139153/ea0918ae-e281-11e4-95a9-f74cbffe8113.png)
![custom_off](https://cloud.githubusercontent.com/assets/8094932/7139163/ef85827c-e281-11e4-98f5-d8388f7b33a1.png)
![custom_over](https://cloud.githubusercontent.com/assets/8094932/7139166/f3ff9090-e281-11e4-9869-07ef20448000.png)

**Comment by asparke2** [comment]
@marj-schott  I like it, such a sweet fix (and it's universally understandable)!

**Comment by jmarrec** [comment]
The visual icons (please don't use actual hearts ;) ) never made it in, but there is an hover that says "Check to add this column to Custom". Is that enough?

**Comment by jmarrec** [comment]
Thoughts anyone? It's been hanging open for a long time. Unless someone says this is really needed, I'd say let's just close it.

**Comment by dstuder** [comment]
Sure, that's certainly better than what was there before!
