### ISSUE TITLE
1.7.0 OSM library files not updated

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1588]
The building type OSMs are still in version 1.6.0 so after loading the update version dialog shows up. The HVAC library is version 1.6.1.

**Comment by macumber** [comment]
This doesn't really cause you any issues other than seeing the dialog right?  Possibly some extra time to version translate these?

**Comment by MatthewSteen** [comment]
Yeah, not a big deal, just an extra mouse click.
