### ISSUE TITLE
Launch OS button doesn't work for OSM files on network drives

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1589]
Possibly searching for OS 1.6.0 which I don't have installed.

Plugin/OS build = 1.7.0.c5bad04b2c

**Comment by macumber** [comment]
What version do you see in the plugin's about menu?  Can you open the ruby console and then press this button?  Do you see any output?

**Comment by MatthewSteen** [comment]
See above for version. The console does show that it's accessing 1.7.0.

>start "" "C:/Program Files/OpenStudio 1.7.0/Ruby/../bin/OpenStudio" "//aesvr02/shared/PROJECTS/15023 1709 Chestnut Place/ENERGY/5 SD Analysis/Simulations/15023_Model02.osm"

**Comment by macumber** [comment]
My guess is that the issue is the file path which appears to be a network location

**Comment by MatthewSteen** [comment]
In previous versions I've been able to use the button for network locations.

**Comment by MatthewSteen** [comment]
@macumber I confirmed that it's because of the network location, button works for local paths.

**Comment by MatthewSteen** [comment]
Not valid in 1.10.4.
