### ISSUE TITLE
Filtering on BCL component attribute doesn't work for measures in OS app

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1591]
I made test measure and added in filtering by attribute to create more specific search results than a basic search. It works fine in ruby measure test, but the app breaks in arguments section. The offending code is highlighted link below.
https://github.com/NREL/OpenStudio-measures/blob/develop/NREL%20working%20measures/get_weather_file_from_building_component_library/measure.rb#L61-67

Error I see "Failed to compute arguments for measure: undefined method 'name' for #"

**Comment by DavidGoldwasser** [comment]
I should point out the ChangeBuildingLocation measure works fine on server using spreadsheet or scripted workflow. So only issue I'm aware of is running in PAT. There does appear to be an issue in Apply measures now, but the file fixes itself the next time you open the file by copying the weather file with the "Files directory"  I have not tried changing via Apply Measures Now, and then running right away?

**Comment by macumber** [comment]
Hovering over the error gave additional information pointing to the OpenStudio Attribute class

**Comment by macumber** [comment]
Looks like we need to load openstudioutilitiesdata here:

https://github.com/NREL/OpenStudio/blob/9eb5f1f4a27a9fe5376d0967b369e2da6ed6a800/openstudiocore/src/openstudio_app/main.cpp#L76

**Comment by macumber** [comment]
Related to the ongoing question of which subset of the ruby modules are available for measures mentioned here:

https://github.com/NREL/OpenStudio/issues/1383
