### ISSUE TITLE
If file requested by OS:WeatherFile can't be found no simulation should be run.

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1592]
This is related to issue #1590, but is a bit more specific so I filed it by itself.

The screenshot below shows an OSM file on the left that is the result of the ChangeBuildingLocation measure setting the weather file (EPW and DDY) to Chicago. The baseline model was set for Denver. The Denver weather file is in the "files" directory" and the Chicago weather file is in the EnegyPlus install. This was run as design alternative in PAT along with another design alternative using new test BCL measure (which had similar results). The model was run with the Chicago design day files, but with the Denver EPW file, despite the fact that the OS:WeatherFile object points to a Chicago EPW file.

@macumber is runManager just using whatever EPW it finds in the "Files" directory? I know by the time you jsut have an IDF, there is no longer a way to check what weather file is required. Maybe there is no checking. Another question, there isn't a "Files" directory for every datapoint, so if the weather file is copied somewhere for use in PAT, where would it be? I think at one point we had copies of the either file everywhere, but may have streamlined that to save space? 

![4-9-2015 3-21-33 pm](https://cloud.githubusercontent.com/assets/4857055/7077341/4857c864-decd-11e4-938f-1363408d6ad3.png)

**Comment by macumber** [comment]
No each datapoint does not currently get it's own resources directory which is why there is confusion

**Comment by DavidGoldwasser** [comment]
Wanted to link to same measure that get BCL site object which includes design day, water main temp, site object, and weather file.

When I add the main component, it results in path shown to epw in a temp zip folder
``ruby
new_site_object = componentData.get.primaryComponentObject.to_Site.get
``
https://github.com/NREL/OpenStudio-measures/blob/develop/NREL%20working%20measures/get_site_from_building_component_library/measure.rb#L200

When I add this line it updates the path to location within the local BCL database.
``ruby
OpenStudio::Model::WeatherFile::setWeatherFile(model, epw_file)
``
https://github.com/NREL/OpenStudio-measures/blob/develop/NREL%20working%20measures/get_site_from_building_component_library/measure.rb#L227-230

**Comment by DavidGoldwasser** [comment]
@macumber this same behavior exists in 2.x OpenStudio application. I assume we won't fix this for 1.14 so I'll flag for 1.15.0.

I'm also not sure how this will work in PAT 2.x Maybe in future version it should be updated to have site component vs. just epw so it can handle design days and water main temps. Also with support for Path argument I don't think PAT has a way to upload resource files like the analysis spreadsheet can.

**Comment by asparke2** [comment]
@DavidGoldwasser Can you confirm or close this bug while you are testing the BCL lookup measure?

**Comment by DavidGoldwasser** [comment]
@asparke2 I can test this, but may just be relevant for OS app now since PAT (and OSW) allows you to have a seed without a weather file set.
