### ISSUE TITLE
RadianceParameters gtest failures

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1594]
ModelFixture.RadianceParameters_AmbientBouncesVMX (Failed)
ModelFixture.RadianceParameters_AmbientDivisionsVMX (Failed)
ModelFixture.RadianceParameters_KlemsSamplingDensity_Quantity (Failed)

I think these are probably related to the recent GUI work?

**Comment by evanweaver** [comment]
@macumber originally, the default values for the radiance were neither "coarse" or "fine", but a mix of the 2.  The gtest values now match the coarse settings which are now consistently applied.

**Comment by macumber** [comment]
Closed by https://github.com/NREL/OpenStudio/pull/1600
