### ISSUE TITLE
measure Set Exterior Roof Assembly to User Input U Value references walls

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1596]
Several lines reference Wall instead of RoofCeiling. Email with changes to measure.rb file inbound.

Line 154
Line 323
Line 337
Line 344

![openstudio_issue1596-2](https://cloud.githubusercontent.com/assets/8397034/7119392/7f258244-e1c2-11e4-96b9-2468eb7badf7.png)

**Comment by MatthewSteen** [comment]
@DavidGoldwasser happy to help fix if needed.

**Comment by DavidGoldwasser** [comment]
@MatthewSteen thanks for pointing this out, I think I had quickly incorporated your log message changes but didn't realize there were other issues in the measure.

**Comment by MatthewSteen** [comment]
Sorry, I didn't bother to test the changes I suggested above. I did a quick diff with the complimentary wall measure and nothing appeared to be out of place which is strange because that one works.

**Comment by MatthewSteen** [comment]
@DavidGoldwasser to clarify my comment above, I had made the changes to my copy of the measure but it doesn't appear to fix it. Looks like the current BCL measure still references walls.

**Comment by MatthewSteen** [comment]
The 4 line changes I originally suggested above will fix the measure. I've made those changes and replaced all wall references with roof in the comments and variable names. 

Also, I suggest using `U-factor` instead of U-value to follow the ASHRAE convention in this measure and the `Set Exterior Wall Assembly to User Input U Value`.

**Comment by DavidGoldwasser** [comment]
@MatthewSteen Thanks for your help, just posted update to BCL.
