### ISSUE TITLE
dynamic generated argument choice values in measure.xml

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1598]
Looking at the test BCL measure I see that measure.xml populates measure argument choice values.
https://github.com/NREL/OpenStudio-measures/blob/develop/NREL%20working%20measures/get_weather_file_from_building_component_library/measure.xml

I'm not sure if this is the desired behavior? This may be dynamic for a number of reasons. New objects added, old objects may be removed, and private content could impact what is shown. What uses the choice data in the XML? 

I assume if the choice arguments were model dependent (e.g. if I look at what kind of exterior wall is used in the model to add attributes to my search? would the choice list not be populated in the XML?

cc: @nllong

**Comment by macumber** [comment]
@DavidGoldwasser I don't think this is the right thing to do.  However, I think we can just do this correctly in the new measure manager for PAT/OS App
