### ISSUE TITLE
PAT ruby script path not set

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1601]
User reported this issue: https://unmethours.com/question/4404/primary-ruby-script-path-not-set-for-passed-in-measure/

**Comment by macumber** [comment]
Link to error message in code https://github.com/NREL/OpenStudio/blob/3aaa0984dbc185867261bde6305b141deb118d5e/openstudiocore/src/runmanager/lib/RubyJobUtils.cpp#L1212

**Comment by DavidGoldwasser** [comment]
Closed with 1601.
