### ISSUE TITLE
Make IP reporting measure

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1611]
Should contain everything in the eplusout.html file but in IP

@asparke2 @DavidGoldwasser can one of you assign yourself if you are already working on this?

**Comment by macumber** [comment]
Need to fix https://github.com/NREL/OpenStudio/issues/283 once this is complete

**Comment by jmarrec** [comment]
+1

**Comment by asparke2** [comment]
I'll take the lead on this, but will work with @DavidGoldwasser to build on the coffee work he's done.

**Comment by DavidGoldwasser** [comment]
Is this making an IP version of the eplusout.htm

I updated the annual end use summary to pull in additional data from the tabular energy plus results. Should that be the starting point for this? This builds on work done for COFEE with table of contents and modular methods for table and graph generation. Currently this version just writes html, but once we support gems it can write Excel as well, although it is very ugly Excel for the moment.
https://bcl.nrel.gov/node/39418

YouTube video on it
https://www.youtube.com/watch?v=umQR8XoORZc

@macumber is this independant of having the OS app or PAT pass the preferred units to the measure. Ideally measures should be written to provide either IP or SI units, vs. keeping duplicate copies of measures.

**Comment by macumber** [comment]
@DavidGoldwasser is this complete?
