### ISSUE TITLE
Ability to copy log messages from measures

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1626]
This would include copying out of the apply measures now dialog. Ideally it would be nice to do this in PAT run tab as well, but isn't as critical there since the log data is saved to disk (but not always easy to find).

**Comment by jmarrec** [comment]
You cna copy out of the Advanced Console. Perhaps an easy workaround is to also output the main window "Final Condition"  etc to the advanced console. It may have been the intent at some point, there's an empty "run.log" section at the end of the advanced console.

Here's an example

```
Standard Output: (Note: this is stuff where I used "puts" statement)
Renamed 'ChW Loop Supply Inlet Node' to 'ChW Loop Supply Inlet Node'
Renamed 'ChW Loop Supply Outlet Node' to 'ChW Loop Supply Outlet Node'
Renamed 'ChW Loop Demand Inlet Node' to 'ChW Loop Demand Inlet Node'
Renamed 'ChW Loop Demand Outlet Node' to 'ChW Loop Demand Outlet Node'
Renamed ChW Loop Supply Splitter to ChW Loop Supply Splitter
Renamed ChW Loop Supply Mixer to ChW Loop Supply Mixer

Standard Error:

run.log:
```

**Comment by DavidGoldwasser** [comment]
Advanced console and OSW addressees this
