### ISSUE TITLE
HVAC Tab - Low Temp Radient components come in without any names

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1627]
I assume this can be fixed by giving the components in the library names. This happens two Electric, Variable Flow and Constant Flow. Even if Library objects are not named, the GUI and even the API normally forces a name if you don't have one. @macumber any thoughts why this ins't doing that? Maybe it gives new objects name even if you don't set it, but cloning an object may not?

Note in attached screenshot that there is a piece of zone equipment but it doesn't have a name. You can add a name so there is a work around. I don't know the implications of leaving the name blank on how forward translation happens.

![4-20-2015 1-06-18 pm](https://cloud.githubusercontent.com/assets/4857055/7238569/805b2c7e-e760-11e4-9a05-9c6d367793aa.png)

**Comment by kbenne** [comment]
@DavidGoldwasser I actually noticed this when I did ZoneVentilationDesignFlowRate. I made a fix that got lumped in with that work. You can see it [here](https://github.com/NREL/OpenStudio/commit/364738434801ef9515af01b62599f66534aa76e1#diff-61f9cf5b4a22f70a3f283a0468b08219R92).

**Comment by kbenne** [comment]
In other words please verify and close.
