### ISSUE TITLE
Incorrect results in OpenStudio App.

### ISSUE THREAD

**Issue by germolinal** [NREL/OpenStudio#1632]
Hello everyone, I want to report the following issue.

 **When running a model from the OpenStudio applications, the monthly results shown within the application are different from those seen in EnergyPlus files** (i.e. Results Summary tab, when choosing EnergyPlus results and OpenStudio results). My model only has Lighting as loads.

**Comment by macumber** [comment]
Thanks @germolinal could you break this into two issues?  For the second issue, with differences in monthly results, it would be helpful to provide more description on what differences you are seeing.

**Comment by germolinal** [comment]
Divided, @macumber.

I have a weekly schedule for lighting, working the whole year. EnergyPlus results (through OpenStudio application) show similar electricity consumption along the year (modulated by the number of days in the month). However, the OpenStudio results only show electricity consumption during January and February.

**Comment by macumber** [comment]
Hmm that is odd, any chance you can send the OSM file over?

**Comment by germolinal** [comment]
sent!

**Comment by macumber** [comment]
Added file to the files repo

**Comment by DavidGoldwasser** [comment]
This model was made with OpenStudio 1.7.0, looking at the code this pre-dates our current OpenStudio results measures, so any bug that may have existed then isn't in the code anymore
https://github.com/NREL/OpenStudio/blob/v1.7.0/openstudiocore/src/pat_app/Measures/StandardReports/measure.rb
