### ISSUE TITLE
Measure Names entered for new measure doesn't make it in as typed to BCL

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1633]
cc: @macumber @nllong @kflemin 

This may need to be addressed both in OpenStudio and BCL.

When I make a new measure in the OpenStudio app called "Schedule Profile Report" this is what the start of the XML looks like

```
<measure>
  <schema_version>3.0</schema_version>
  <name>schedule_profile_report</name>
  <uid>1d3d64b2-5588-4815-ad58-c0340678222d</uid>
  <version_id>74a2957e-9507-4246-84d7-e846a963dc15</version_id>
  <xml_checksum>557BF06F</xml_checksum>
  <class_name>ScheduleProfileReport</class_name>
  <display_name> Schedule Profile Report</display_name>
  <description>Create stepped plots of each ruleset schedule, with a line for the default profile, each rule, and the summer and winter design day.</description>
```

When I post this to BCL what the user see's seems to be "name" vs. "display_name"
https://bcl.nrel.gov/node/82784

The OS GUI's also use the "name" vs. "display_name" so the GUI shows the snake case version.

**Comment by macumber** [comment]
Which places in the OpenStudio GUIs use name instead of display name?  @kflemin scoped the change to use display name on BCL but we had to hold off for now.

**Comment by DavidGoldwasser** [comment]
@macumber The XML in the measures you download only have "name" field even though what I uploaded had "name" and "display_name". The library in the APP and PAT seem to fall back on "name" if it can't find "display_name". 

measure.rb knows what should be shown. Can the App use this to generate "display_name" and ideally alter the XML file (or is altering data in the database a bad idea?)

**Comment by macumber** [comment]
Probably not  a good idea as this would invalidate the checksum from BCL.  We should just wait until we can do the BCL fixes.

**Comment by jmarrec** [comment]
Does this still belong on this repo or is there another better place for BCL changes?
