### ISSUE TITLE
Output Control Reporting Tolerance units default to SI despite app unit preference

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#1636]
In OS App v1.7.0, Windows 64-bit: if app unit preferences are set to I-P or SI, upon entering the Simulation Settings tab the Output Control Reporting Tolerance units will be SI (K). 

While within the tab, cycling the unit preference to SI and back to I-P will change the tolerance units to I-P (R). Exiting and reentering the tab (with unit preference set to I-P) will reset the tolerance units back to K.

**Comment by DavidGoldwasser** [comment]
Thanks, good catch. Below are additional fields affected in simulation settings

-Temperature Convergence Tolerance Value in the Simulation Control section.
- Min and Max Surface Convection fields in Heat Balance Algorithm.

Their is one field with units that wasn't affected by this issue. Surface Temperature Upper Limit in Heat Balance Algorithm.

**Comment by evanweaver** [comment]
Fixed via https://www.pivotaltracker.com/n/projects/134010/stories/102621426
