### ISSUE TITLE
Add Space Infiltration Effective Leakage Area object to library files

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1642]
Currently it is very hard in the GUI  to make a new object of this type, and soon it will be impossible (once facility tab has grid view). We should add an object of this type to all the library files we make for OS app. Don't change template by hand update the script that makes them to add this, otherwise we may loose it next time an update is made.

**Comment by dstuder** [comment]
@DavidGoldwasser I agree that this should be added; it is now (as of 1.8.4) impossible to add this object to a model. It would be great if this could be added for the 1.9.0 release.

**Comment by DavidGoldwasser** [comment]
@dstuder would like this in. @macumber and @asparke2 the preferred way to do this would be to add it into code that we have to generate the template OSM's however that is on the way to being deprecated for the prototype work @asparke2 has been doing. The other way to do this is just to manually edit the OSM's to add this object, which is probably the most straight forward. 

There is also an issue #256 filed about not seeing infiltration objects in the "My Model tab".

**Comment by macumber** [comment]
Could this be done with a measure?

**Comment by asparke2** [comment]
It could be done with a measure, but we should have one object of this type in the library .osm file.  People shouldn't have to write a measure to access a basic type of object.

**Comment by dstuder** [comment]
Sure, but that defeats the purpose of the grid view implementation, which is to allow the modeler to easily see what's going on in their model. In my opinion, this needs to be added to the library (even a blank object that someone could drag into their model and then fill in).

**Comment by macumber** [comment]
So we put one object of this type in every space type osm or we could put it in the hvac library.

**Comment by DavidGoldwasser** [comment]
@macumber I don't think we need it in every space type, we just need an un-assigned one in the 16 osm's that people typically use as a library from the OS app. It doesn't need to be part of a space type in the library. I don't think putting it in the HVAC library would work? But maybe it would? I've never tried putting an internal load in it.

**Comment by DavidGoldwasser** [comment]
I updated the template files used as default directory in load library for OS app. This was important because changes to facility tab took away the work around that had bypassed the issue.

**Comment by macumber** [comment]
@DavidGoldwasser Is there a commit that implements this change?

**Comment by DavidGoldwasser** [comment]
Yep, I just did it in develop, but I did build and test it before I synced the commit.
