### ISSUE TITLE
Sometimes get crash when pasting text into string argument value in measures tab

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1645]
This doesn't always happen, but has happened to me three times in last two days.
1. Load completed model
2. add in View data measure
3. Run simulation (simulation is successful)
4. Load rdd file
5. copy choice from rdd file into clipboard
6. return to OS app and past into string field.

When I re-launch and paste the exact same thing in, there is no crash. I didn't even re-copy, was still in my clipboard.

**Comment by DavidGoldwasser** [comment]
Removed low frequency. Seems to be pretty easy to reproduce.

**Comment by DavidGoldwasser** [comment]
It also crashes if I go in and copy the text from the measure argument after sim run. Not just pasting into the field

**Comment by evanweaver** [comment]
Pre-2.0 issue
