### ISSUE TITLE
HVACComponent::addToNode derived implementations have inconsistent behavior

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#1649]
::addToNode is not consistent between StraightComponent, WaterToAirComponent, WaterToWaterComponent and AirToAirComponent.  StraightComponent will fail (return false) if ::addToNode is called on a component already attached to a system.  The other derived class of HVACComponent will first detach and then reattach to the new system.  Update all classes to be like StraightComponent failing when there is an existing attached loop.

**Comment by jmarrec** [comment]
@kbenne Would you like to revisit this statement now that this has been the API we have for 6 years? 

Hyrum's Law applies here, I think it's fair to say that people depend on this behavior. 

I'm closing, but feel free to reopen if you think this is really needed

**Comment by kbenne** [comment]
yeah agreed. way too late to change it.
