### ISSUE TITLE
Results Tab Crash Bug

### ISSUE THREAD

**Issue by evanweaver** [NREL/OpenStudio#1650]
Steps to reproduce:
1) Start OpenStudio,
2) Navigate to the Results Summary tab,
3) Navigate to the Run Simulation tab.

![image](https://cloud.githubusercontent.com/assets/4974134/7550464/0c7dbd92-f621-11e4-9c1e-9272ce22f6d2.png)

**Comment by evanweaver** [comment]
@macumber  @axelstudios  I think that this was introduced recently; any ideas on app development which may have caused it?

**Comment by axelstudios** [comment]
I'm not seeing that on v1.7.3 - Dan?

**Comment by macumber** [comment]
If this only happens in debug mode it is likely due to the debug console that I enabled

**Comment by evanweaver** [comment]
@axelstudios is this still valid and open?
