### ISSUE TITLE
Convert method units documentation

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1651]
Some of the units listed for the built in convert method are displaying incorrectly on the [Measure Code Examples](http://nrel.github.io/OpenStudio-user-documentation/reference/measure_code_examples/) page. Looks like a markdown issue where units are displayed in italics instead of with a `*` separator. For example power is displayed as **ft_lb_f_/s** instead of **ft*lb_f/s**. Could be confusing for someone unfamiliar with markdown.

**Comment by jmarrec** [comment]
Still true today. ft*lb_f*s
