### ISSUE TITLE
Facility Tab - Seems PTHP and PTAC shouldn't show under Library (Bugzilla #850)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#166]
On 2012-08-09 14:23:59, @DavidGoldwasser wrote:

> I haven't checked to see if this shows up elsewhere. Seems should only be in thermal zone tab.

On 2012-09-06 22:05:14, @DavidGoldwasser wrote:

> Also in HVAC loop view hot and cold water coil objects show under "my model" but not fans.

**Comment by jmarrec** [comment]
irrelevant due to GUI refactor
