### ISSUE TITLE
OpenStudio OS X Packages are broken

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#1665]
libopenstudio_radiance.dylib is getting built, but the Radiance libraries aren't making it into the package.  To reproduce, install OpenStudio v1.7.3 or v1.7.4 and attempt to launch the OpenStudio app.

**Comment by macumber** [comment]
Can we reassign this to @kbenne ?  I'm guessing that we somehow need to tell CMake's dependency finder that there is a dependency here.

**Comment by kbenne** [comment]
Gee thanks :) I'm switching to Windows...
