### ISSUE TITLE
WaterHeater:Mixed not forward translated when not on loop

### ISSUE THREAD

**Issue by mbadams5** [NREL/OpenStudio#1675]
If a WaterHeater:Mixed is not on a SWH PlantLoop then it is not forward translated. 

A water heater can be standalone when PeakUseFlowRate and UseFlowRateFractionSchedule are set.

I came across this in a few prototype buildings where this is used.

This iddobjectype just need to be added to [here](https://github.com/NREL/OpenStudio/blob/8e67be624fef6e4182f66df4782f45195422cf25/openstudiocore/src/energyplus/ForwardTranslator.cpp#L1997)

One option around this is to create a plantloop with a pump that has basically zero head pressure and a water use equipment that is the same as the PeakUseFlowRate and has a schedule the same as UseFlowRateFractionSchedule.

fyi @kbenne

**Comment by jmarrec** [comment]
Agreed that this should be supported. 

Once thing I dislike about is that the "Peak Use Flow Rate", which is the condition to check if the WH isn't hooked to a PlantLoop to see if it is *really* meant standalone, was made required-field and is default-initialized in the ctor to 0.1 m3/s.

That basically means ANY WaterHeaterMixed in your model will be translated no matter what. That could be confusing and could be hard to tell that it is actually happening. Perhaps that's ok though. 

@kbenne thoughts please?

**Comment by kbenne** [comment]
Given that Peak Use Flow Rate is required, it seems like we don't have the option to selectively translate this type anymore. My feeling is that we should just accept that it is always translated, and therefore do what @mbadams5 suggests and just add it to the list of always translated types. 

I'm assuming that making Peak Use Flow Rate optional would be a breaking api change, and I wouldn't changing the API.
