### ISSUE TITLE
Failure in intersectSurfaces method in some cases

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1683]
Error below from user model when running surface matching measure with intersect turned on.

DL is deprecated, please use Fiddle

QSslSocket: cannot resolve TLSv1_1_client_method

QSslSocket: cannot resolve TLSv1_2_client_method

QSslSocket: cannot resolve TLSv1_1_server_method

QSslSocket: cannot resolve TLSv1_2_server_method

QSslSocket: cannot resolve SSL_select_next_proto

QSslSocket: cannot resolve SSL_CTX_set_next_proto_select_cb

QSslSocket: cannot resolve SSL_get0_next_proto_negotiated

C:/Users/Matt/AppData/Local/Temp/OpenStudio.RS8784/ApplyMeasureNow/UserScript/user_script.rb:56: [BUG] Segmentation fault

ruby 2.0.0p594 (2014-10-27) [x64-mingw32]

-- Control frame information -----------------------------------------------

c:0008 p:---- s:0058 e:000057 CFUNC  :intersectSurfaces

c:0007 p:0047 s:0054 e:000053 BLOCK  C:/Users/Matt/AppData/Local/Temp/OpenStudio.RS8784/ApplyMeasureNow/UserScript/user_script.rb:56 [FINISH]

c:0006 p:---- s:0051 e:000050 CFUNC  :each

c:0005 p:0017 s:0048 e:000047 BLOCK  C:/Users/Matt/AppData/Local/Temp/OpenStudio.RS8784/ApplyMeasureNow/UserScript/user_script.rb:54 [FINISH]

c:0004 p:---- s:0045 e:000044 CFUNC  :each

c:0003 p:0132 s:0042 e:000041 METHOD C:/Users/Matt/AppData/Local/Temp/OpenStudio.RS8784/ApplyMeasureNow/UserScript/user_script.rb:53

c:0002 p:1466 s:0031 E:000920 EVAL   in.rb:325 [FINISH]

c:0001 p:0000 s:0002 E:0002d8 TOP    [FINISH]

in.rb:325:in `<main>'

C:/Users/Matt/AppData/Local/Temp/OpenStudio.RS8784/ApplyMeasureNow/UserScript/user_script.rb:53:in `run'

C:/Users/Matt/AppData/Local/Temp/OpenStudio.RS8784/ApplyMeasureNow/UserScript/user_script.rb:53:in `each'

C:/Users/Matt/AppData/Local/Temp/OpenStudio.RS8784/ApplyMeasureNow/UserScript/user_script.rb:54:in `block in run'

C:/Users/Matt/AppData/Local/Temp/OpenStudio.RS8784/ApplyMeasureNow/UserScript/user_script.rb:54:in `each'

C:/Users/Matt/AppData/Local/Temp/OpenStudio.RS8784/ApplyMeasureNow/UserScript/user_script.rb:56:in `block (2 levels) in run'

C:/Users/Matt/AppData/Local/Temp/OpenStudio.RS8784/ApplyMeasureNow/UserScript/user_script.rb:56:in `intersectSurfaces'

-- C level backtrace information -------------------------------------------

C:\Windows\SYSTEM32\ntdll.dll(NtWaitForSingleObject+0xa) [0x0000000076D8DBFA]

C:\Windows\system32\KERNELBASE.dll(WaitForSingleObjectEx+0x9c) [0x000007FEFCDF10DC]

C:\Program Files\OpenStudio 1.7.5\ruby-install\ruby\bin\x64-msvcrt-ruby200.dll(rb_vm_bugreport+0x9d) [0x000000006F287B0D]

C:\Program Files\OpenStudio 1.7.5\ruby-install\ruby\bin\x64-msvcrt-ruby200.dll(rb_name_err_mesg_new+0x838) [0x000000006F142828]

C:\Program Files\OpenStudio 1.7.5\ruby-install\ruby\bin\x64-msvcrt-ruby200.dll(rb_bug+0x45) [0x000000006F1435D5]

C:\Program Files\OpenStudio 1.7.5\ruby-install\ruby\bin\x64-msvcrt-ruby200.dll(rb_check_safe_str+0x3e1) [0x000000006F20C051]

 [0x0000000000401A85]

C:\Windows\SYSTEM32\ntdll.dll(_C_specific_handler+0x9c) [0x0000000076D57FA8]

C:\Windows\SYSTEM32\ntdll.dll(RtlDecodePointer+0xad) [0x0000000076D691AD]

C:\Windows\SYSTEM32\ntdll.dll(RtlUnwindEx+0xbbf) [0x0000000076D58BAF]

C:\Windows\SYSTEM32\ntdll.dll(KiUserExceptionDispatcher+0x2e) [0x0000000076D8DB38]

C:\Program Files\OpenStudio 1.7.5\Ruby\openstudio\openstudio_utilities.dll(openstudio::reverse+0x2614b) [0x000007FED4E46F7B]

C:\Program Files\OpenStudio 1.7.5\Ruby\openstudio\openstudio_utilities.dll(openstudio::subtract+0x975) [0x000007FED4E5E235]

C:\Program Files\OpenStudio 1.7.5\Ruby\openstudio\openstudio_utilities.dll(openstudio::intersect+0x70a) [0x000007FED4E5770A]

C:\Program Files\OpenStudio 1.7.5\Ruby\openstudio\openstudio_model.dll(openstudio::model::detail::Surface_Impl::computeIntersection+0x7a6) [0x000007FED3555F76]

C:\Program Files\OpenStudio 1.7.5\Ruby\openstudio\openstudio_model.dll(openstudio::model::Surface::computeIntersection+0x40) [0x000007FED3555790]

C:\Program Files\OpenStudio 1.7.5\Ruby\openstudio\openstudio_model.dll(openstudio::model::detail::Space_Impl::intersectSurfaces+0xf7f) [0x000007FED34F50AF]

C:\Program Files\OpenStudio 1.7.5\Ruby\openstudio\openstudio_model.dll(openstudio::model::Space::intersectSurfaces+0x2d) [0x000007FED34F40FD]

 [0x000007FED204CBAA]

C:\Program Files\OpenStudio 1.7.5\ruby-install\ruby\bin\x64-msvcrt-ruby200.dll(rb_error_arity+0x125) [0x000000006F2726A5]

C:\Program Files\OpenStudio 1.7.5\ruby-install\ruby\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x1cf8) [0x000000006F276DC8]

C:\Program Files\OpenStudio 1.7.5\ruby-install\ruby\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x5cb9) [0x000000006F27AD89]

C:\Program Files\OpenStudio 1.7.5\ruby-install\ruby\bin\x64-msvcrt-ruby200.dll(rb_yield+0x178) [0x000000006F284618]

C:\Program Files\OpenStudio 1.7.5\ruby-install\ruby\bin\x64-msvcrt-ruby200.dll(rb_reset_random_seed+0x1b80) [0x000000006F1D2220]

C:\Program Files\OpenStudio 1.7.5\ruby-install\ruby\bin\x64-msvcrt-ruby200.dll(rb_error_arity+0x125) [0x000000006F2726A5]

C:\Program Files\OpenStudio 1.7.5\ruby-install\ruby\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x1c91) [0x000000006F276D61]

C:\Program Files\OpenStudio 1.7.5\ruby-install\ruby\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x5cb9) [0x000000006F27AD89]

C:\Program Files\OpenStudio 1.7.5\ruby-install\ruby\bin\x64-msvcrt-ruby200.dll(rb_yield+0x178) [0x000000006F284618]

C:\Program Files\OpenStudio 1.7.5\ruby-install\ruby\bin\x64-msvcrt-ruby200.dll(rb_reset_random_seed+0x1b80) [0x000000006F1D2220]

C:\Program Files\OpenStudio 1.7.5\ruby-install\ruby\bin\x64-msvcrt-ruby200.dll(rb_error_arity+0x125) [0x000000006F2726A5]

C:\Program Files\OpenStudio 1.7.5\ruby-install\ruby\bin\x64-msvcrt-ruby200.dll(rb_f_send+0x5a1) [0x000000006F2814C1]

C:\Program Files\OpenStudio 1.7.5\ruby-install\ruby\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x1c91) [0x000000006F276D61]

C:\Program Files\OpenStudio 1.7.5\ruby-install\ruby\bin\x64-msvcrt-ruby200.dll(rb_vm_localjump_error+0x5cb9) [0x000000006F27AD89]

C:\Program Files\OpenStudio 1.7.5\ruby-install\ruby\bin\x64-msvcrt-ruby200.dll(rb_iseq_eval_main+0x1e0) [0x000000006F284C80]

C:\Program Files\OpenStudio 1.7.5\ruby-install\ruby\bin\x64-msvcrt-ruby200.dll(rb_check_copyable+0x3287) [0x000000006F148597]

C:\Program Files\OpenStudio 1.7.5\ruby-install\ruby\bin\x64-msvcrt-ruby200.dll(ruby_run_node+0x51) [0x000000006F14AE11]

 [0x0000000000402D14]

 [0x00000000004013D7]

 [0x00000000004014F8]

C:\Windows\system32\kernel32.dll(BaseThreadInitThunk+0xd) [0x0000000076C359CD]

-- Other runtime information -----------------------------------------------
- Loaded script: in.rb
- Loaded features:
  
  0 enumerator.so
  
  1 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/x64-mingw32/enc/encdb.so
  
  2 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/x64-mingw32/enc/iso_8859_1.so
  
  3 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/x64-mingw32/enc/trans/transdb.so
  
  4 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/x64-mingw32/rbconfig.rb
  
  5 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/rubygems/compatibility.rb
  
  6 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/rubygems/defaults.rb
  
  7 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/rubygems/deprecate.rb
  
  8 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/rubygems/errors.rb
  
  9 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/rubygems/version.rb
  
  10 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/rubygems/requirement.rb
  
  11 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/rubygems/platform.rb
  
  12 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/rubygems/specification.rb
  
  13 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/rubygems/exceptions.rb
  
  14 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/rubygems/defaults/operating_system.rb
  
  15 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/x64-mingw32/enc/utf_16le.so
  
  16 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/x64-mingw32/enc/trans/utf_16_32.so
  
  17 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb
  
  18 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/thread.rb
  
  19 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/monitor.rb
  
  20 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb
  
  21 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/rubygems.rb
  
  22 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/x64-mingw32/pathname.so
  
  23 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/pathname.rb
  
  24 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/x64-mingw32/enc/trans/single_byte.so
  
  25 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/x64-mingw32/dl.so
  
  26 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/x64-mingw32/fiddle.so
  
  27 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/fiddle/function.rb
  
  28 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/fiddle/closure.rb
  
  29 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/fiddle.rb
  
  30 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/dl.rb
  
  31 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/Win32API.rb
  
  32 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioutilitiescore.so
  
  33 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioutilitiestime.so
  
  34 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioutilitiesdata.so
  
  35 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioutilitiesplot.so
  
  36 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioutilitiesgeometry.so
  
  37 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioutilitiessql.so
  
  38 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioutilitiesbcl.so
  
  39 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioutilitiescloud.so
  
  40 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioutilitiesunits.so
  
  41 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioutilitiesidd.so
  
  42 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioutilitiesidf.so
  
  43 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioutilitiesfiletypes.so
  
  44 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioutilities.so
  
  45 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudiomodel.so
  
  46 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudiomodelcore.so
  
  47 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudiomodelsimulation.so
  
  48 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudiomodelresources.so
  
  49 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudiomodelgeometry.so
  
  50 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudiomodelhvac.so
  
  51 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudiomodelrefrigeration.so
  
  52 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioenergyplus.so
  
  53 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioradiance.so
  
  54 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudiogbxml.so
  
  55 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioairflow.so
  
  56 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioosversion.so
  
  57 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioruleset.so
  
  58 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudiorunmanager.so
  
  59 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioproject.so
  
  60 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioanalysisdriver.so
  
  61 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudiomodeleditor.so
  
  62 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioanalysis.so
  
  63 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudiolib.so
  
  64 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudioisomodel.so
  
  65 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio/openstudiosdd.so
  
  66 C:/Program Files/OpenStudio 1.7.5/Ruby/openstudio.rb
  
  67 C:/Program Files/OpenStudio 1.7.5/ruby-install/ruby/lib/ruby/2.0.0/optparse.rb

[NOTE]

You may have encountered a bug in the Ruby interpreter or extension libraries.

Bug reports are welcome.

For details: http://www.ruby-lang.org/bugreport.html

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

[utilities.geometry.removeHoles] <1> Failed to partition polygon
[utilities.geometry.removeHoles] <1> Failed to partition polygon

**Comment by MatthewSteen** [comment]
+1

**Comment by DavidGoldwasser** [comment]
Thanks for  finding it MattewSteen, I have file on private repo
https://github.com/NREL/OpenStudio-files/tree/master/Git%20Issue%20Files/Issue1683

**Comment by MatthewSteen** [comment]
As a "workaround" I was able to use the plugin surface matching script without any errors.

**Comment by MatthewSteen** [comment]
I hit this again on a similar model as above, high rise residential tower with below grade parking garage. I was again able to use the plugin surface matching script, but ended up using David's [surface_matching_diagnostic](https://github.com/UnmetHours/openstudio-measures/tree/master/surface_matching_diagnostic) test script.

**Comment by jmarrec** [comment]
Unclear why this is categorized as "OS App"?

**Comment by DavidGoldwasser** [comment]
@jmarrec you're right doesn't seem like right component. May have picked that because it was locking up or crashing the app. I'm not sure if measure is really the right choice either, I thought we had a "code" or API tag, which is really the issue. The measure locks up making an API call. What is the right tag now for model API issues.

**Comment by jmarrec** [comment]
The user file was actually added as a test in #4221 : https://github.com/NREL/OpenStudio/blob/develop/src/model/test/Space_GTest.cpp#L2842 It passes but was disabled because it's a bit too long.
