### ISSUE TITLE
the min. cfm/sf value in the zone:sizing object is being converted from IP to SI wrong in OS 1.7.0

### ISSUE THREAD

**Issue by lincolnharmer** [NREL/OpenStudio#1695]
This may have been resolved in a recent iteration release but I didn't find any related issues documented here. When the value is entered in the GUI in IP units the value is not properly translated to SI units for simulation. This only happens in the gridview. When clicking on the zone sizing settings on the HVAC tab the conversion works properly. This is one of the most critical inputs for a typical VAV w/ reheat model and can cause models to drastically overestimate energy usage.

**Comment by evanweaver** [comment]
This bug will be fixed via https://www.pivotaltracker.com/n/projects/134010/stories/101286352 and is also mentioned in https://github.com/NREL/OpenStudio/issues/1778.

**Comment by evanweaver** [comment]
This bug fix also accepted in Pivotal Aug 24.
