### ISSUE TITLE
Add inheritance to grid view

### ISSUE THREAD

**Issue by evanweaver** [NREL/OpenStudio#1696]
Create a new space type, set a default schedule set, add a load definition, the schedule should appear in green because it is inherited (currently inheritance is not indicated). Now click on the schedule name, the schedule should appear in the inspector but the delete X button should be disabled (you cannot clear an inherited schedule)

**Comment by macumber** [comment]
This request was converted to more concrete bugs for individual tabs:

https://github.com/NREL/OpenStudio/issues/1946
