### ISSUE TITLE
Loads Tab - Change CO2 units for people in OS app (Bugzilla #863)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#170]
On 2012-08-23 16:04:11, @DavidGoldwasser wrote:

> Check with Danny on units.

**Comment by evanweaver** [comment]
@DavidGoldwasser @asparke2 Do we want to change the above-mentioned units, and if so, to what. Is this an actual bug?

**Comment by macumber** [comment]
Current app SI units are 'L/s*W', EnergyPlus IDD has 'm3/s-W' for SI (it is possibly confusing that SI units differ from the input file units)

Current app IP units are 'ft^3*hr/min*Btu', EnergyPlus IDD has 'cfm/met/person' for IP

I'd say this is still valid, ask Danny Studer or @asparke2 for correct units

**Comment by evanweaver** [comment]
@asparke2 thoughts?

**Comment by evanweaver** [comment]
@jasondegraw Dan has acknowledged your excellence, and recommended I tap you for the answer  :)

**Comment by jmarrec** [comment]
Current E+ IDD is:

```
People:Definition,
   [...]
  N6 , \field Carbon Dioxide Generation Rate
       \note CO2 generation rate per unit of activity level.
       \type real
       \units m3/s-W
       \default 3.82E-8
       \minimum 0.0
       \maximum 3.82E-7
       \note The default value is obtained from ASHRAE Std 62.1 at 0.0084 cfm/met/person over
       \note the general adult population.
```

OS 

```
OS:People:Definition,
   [...]
  N6, \field Carbon Dioxide Generation Rate
       \note CO2 generation rate per unit of activity level.
       \note The default value is obtained from ASHRAE Std 62.1 at 0.0084 cfm/met/person over
       \note the general adult population.
       \type real
       \units m3/s-W
       \minimum 0
       \maximum 3.82e-07
       \default 3.82E-8
```

**Comment by DavidGoldwasser** [comment]
@jmarrec I'm fine this this being closed, I don't have a strong opinion on the units.
