### ISSUE TITLE
Deleting plant equipment with setpoint schedule on outlet node orphans setpoint schedule

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1701]
Occurred in 1.7.5 when deleting a boiler with a setpoint manager on the outlet node. Deleting the setpoint manager from the OSM file in a text editor fixed the error.

**Comment by MatthewSteen** [comment]
@kbenne this happened with a boiler and cooling tower in series on a condenser loop. Each has a scheduled SPM on the outlet node as produced by the WSHP measures on the BCL. 

In addition to happening when the boiler was deleted before its LWT SPM, this also occurred when deleting the cooling tower before its LWT SPM.

**Comment by kbenne** [comment]
Schedules derive from ResourceObject which I think means this is normal behavior.  That is we allow resources to float around in the model like islands.  I think @macumber is a little better with the resource semantics so maybe he can comment.

**Comment by macumber** [comment]
When a object that uses a resource is deleted then it should not delete the resource.  If you deleted the schedule explicitly then this would cause problems.  Deleting the setpoint manager should not delete the schedule.
