### ISSUE TITLE
Can't open PAT project on one of our repo's that previously worked.

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1702]
https://github.com/NREL/OpenStudio-Beopt/tree/master/Slab_FINAL

When I try to open it I see this
![6-25-2015 1-23-01 pm](https://cloud.githubusercontent.com/assets/4857055/8363623/594be8ec-1b3d-11e5-84d1-4d9380fbf78b.png)

Then this
![6-25-2015 1-23-12 pm](https://cloud.githubusercontent.com/assets/4857055/8363626/5d331a02-1b3d-11e5-8656-2b1a165bb869.png)

**Comment by DavidGoldwasser** [comment]
I get the same error as above using 1.7.0 vs. 1.7.5. The file does open in 1.6.0 but with errors about scripts it doesn't think it can find (but that really are there)

![6-25-2015 1-29-47 pm](https://cloud.githubusercontent.com/assets/4857055/8363761/73ae1376-1b3e-11e5-89f1-2d48d12a3fb9.png)

**Comment by DavidGoldwasser** [comment]
There are 5 other directories named (pat*) that have PAT projects
https://github.com/NREL/OpenStudio-Beopt

4 of the 5 also fail to open in 1.7.5. The one that does open gives errors about missing measures similar to what the original file did when opened in 1.6.0

![6-25-2015 1-43-05 pm](https://cloud.githubusercontent.com/assets/4857055/8364037/5998ac74-1b40-11e5-9688-377942d96bf9.png)

**Comment by macumber** [comment]
Sounds like @DavidGoldwasser will recreate these PAT projects in the BeOpt repo using either OS 1.7.0 or 1.8.0.  Not sure if I still need to look at what went wrong with the original PAT projects?

**Comment by macumber** [comment]
Downgrading to normal

**Comment by DavidGoldwasser** [comment]
So, in testing another file @axelstudios see's a crash, but it opens fine for me
https://github.com/NREL/OpenStudio-training/tree/master/Exercises/Basic%20Workflow/Models/Section%2012%20-%20PAT

**Comment by DavidGoldwasser** [comment]
since 1x files not important anymore.
