### ISSUE TITLE
Radiance simulation does not use the EnergyPlus installed with OpenStudio

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1703]
https://unmethours.com/question/8510/clear-the-approach-to-use-radiance-in-openstudio-without-getting-run-modeltorad-error/?answer=8676#post-id-8676

**Comment by macumber** [comment]
@rpg777 FYI

**Comment by rpg777** [comment]
Any way we can bundle this with the "install Radiance with OpenStudio" task?

**Comment by macumber** [comment]
This should be easier than installing radiance with OpenStudio but it wouldn't hurt to include both in 1.9.0

**Comment by DavidGoldwasser** [comment]
related to issue #1577
