### ISSUE TITLE
Chiller:Electric:EIR missing outdoor air node

### ISSUE THREAD

**Issue by muh182** [NREL/OpenStudio#1704]
@kbenne this is the E+ warning for the Chiller:Electric:EIR about the missing OutdoorAir:Node:

 *\* Warning *\* GetElectricEIRChillerInput: Chiller:Electric:EIR="CHILLER ELECTRIC EIR 1"
 *\*   ~~~   *\* Adding OutdoorAir:Node=CHILLER ELECTRIC EIR 1 INLET NODE FOR CONDENSER

E+ automatically adds the node.

**Comment by jmarrec** [comment]
Still true in OS 2.2.1:

```
   ** Warning ** GetElectricEIRChillerInput: Chiller:Electric:EIR="CHILLER - AIR COOLED"
   **   ~~~   ** Adding OutdoorAir:Node=CHILLER - AIR COOLED INLET NODE FOR CONDENSER
```
