### ISSUE TITLE
Zones with FanZoneExhaust require thermostat schedules

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1706]
For zones with only a FanZoneExaust OS requires thermostat schedules to run successfully whereas EP does not. I think the problem is that when the cooling and heating setpoints are deleted from a zone with only an exhaust fan the ThermostatSchedule:DualSetpoint objects are being deleted but the ZoneControl:Thermostat object that reference the setpoint schedules is not until the FanZoneExhaust is deleted.

@kbenne suggested this may be a grid view bug where the old On/Off tstat switch functionality is not completely implemented. This is a low frequency bug that only occurs with FanZoneExhaust zones since the other ZoneHVAC objects provide conditioning and need tstats to run.

FYI @evanweaver

**Comment by DavidGoldwasser** [comment]
Thanks @MatthewSteen nice catch

**Comment by MatthewSteen** [comment]
This may also affect CBECC-Com users and require them to assign tstat schedules.

**Comment by DavidGoldwasser** [comment]
@kbenne please assign to 1.9.0 milestone if you think it is needed for that release.

**Comment by kbenne** [comment]
@MatthewSteen I'd like to follow my favorite new way of verifying bug fixes and send you an installer package to test. What do you think, is this something you could do for me?

**Comment by MatthewSteen** [comment]
Sure, fire away.

**Comment by kbenne** [comment]
also @MatthewSteen and @evanweaver read my commit log for the details, but basically yes this problem has been agitated by grid view, but my solution is actually in the translator. I don't think the grid view behavior is all that bad.

@evanweaver for what it is worth the alternative solution in grid view would be to remove the thermostat on the last schedule reset [here](https://github.com/NREL/OpenStudio/blob/4232247615e8d84312a37afe08bf47d19731757c/openstudiocore/src/openstudio_lib/ThermalZonesGridView.cpp#L483).

**Comment by MatthewSteen** [comment]
@kbenne I'm actually at your office today if you want to put it on a 5.25" :floppy_disk:

**Comment by evanweaver** [comment]
Ha, our technical prowess has been recognized.

**Comment by kbenne** [comment]
@MatthewSteen I emailed a link to you.

**Comment by MatthewSteen** [comment]
@kbenne received, tested against 1.8.2, and **works**.
