### ISSUE TITLE
Error exporting PAT project to analysis spreadsheet

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1708]
I made a fresh PAT project in 1.7.5 to recreate an old one I couldn't open. project ran fine. There are 28 always run measure, and no measure groups, so just a baseline run. I get an error that export failed, although the measures and two csv files do export. Not sure what else I should have, does it normally also export the weather file and seed model? See screenshot below.

![7-1-2015 1-13-03 pm](https://cloud.githubusercontent.com/assets/4857055/8464170/6ac7853a-1ffd-11e5-810b-3a87feb35d66.png)

I don't know if this is an isolated issue or more widespread.

**Comment by macumber** [comment]
Also, when exporting the spreadsheet need to fix the following things identified by @brianlball 

Download the project template xlsx file from the spreadsheet develop branch.

Copy the analysis_spreadsheet_export dir to the spreadsheet directory and change the measure path in the spreadsheet to match that directory

Copy the seed file in the seeds directory and update the path in the spreadsheet

Check the weather file path in the spreadsheet

Copy only the highlighted portion of the spreadsheet_outputs_export.csv into the highlighted portion of the variables tab in the spreadsheet

Copy only the highlighted portion of the spreadsheet_variables_export.csv into the highlighted portion of the outputs tab in the spreadsheet.

![paste_here_out](https://cloud.githubusercontent.com/assets/1327850/8779666/b0ceb6de-2ec1-11e5-98ef-100999f2e502.png)
![paste_here_vars](https://cloud.githubusercontent.com/assets/1327850/8779665/b0cd90ec-2ec1-11e5-89d2-ae3297ac7ebb.png)
![varialbes](https://cloud.githubusercontent.com/assets/1327850/8779667/b0cff9b8-2ec1-11e5-89f3-50ed9ba1d938.png)
![change_measure_path](https://cloud.githubusercontent.com/assets/1327850/8779668/b0d81c10-2ec1-11e5-941a-e9cc88f0af1e.png)
![change_weather_and_seed](https://cloud.githubusercontent.com/assets/1327850/8779669/b0dea224-2ec1-11e5-9bf0-33d34612c860.png)
![dirs](https://cloud.githubusercontent.com/assets/1327850/8779670/b0e1f118-2ec1-11e5-9344-e8271ce89a2b.png)
![outputs](https://cloud.githubusercontent.com/assets/1327850/8779671/b0e8a904-2ec1-11e5-9256-38718a4d5eb8.png)

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
