### ISSUE TITLE
Export to spreadsheet when argument is choice list from model static value shows UUID vs. string

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1710]
Dan, not sure how man people hit this, but this is what it looks like in the test I did yesterday.

Choice      {a57e9a2b-e5fd-41c9-9b62-f35844eeaed6}  |attic spacetype,garage spacetype,living spacetype|

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
