### ISSUE TITLE
open studio not working on windows 8.1

### ISSUE THREAD

**Issue by saberian** [NREL/OpenStudio#1713]
I installed openstudio 1.7 on my windows 8.1 laptop. However, every time I open a file browser, e.g. file > open, the windows says that it encounters an error and closes the openstudio. I also checked with version 1.75 and it has the same problem. The same error occurs when I try to open openstudio plug-in inside SketchUp and ResultViewer.

Thanks

**Comment by macumber** [comment]
https://unmethours.com/question/13399/openstudio-crash-in-window-81/

**Comment by macumber** [comment]
Here is the call stack and some screenshots from dependency walker

With Autodesk 360:
[OpenStudio-Debug.txt](https://github.com/NREL/OpenStudio/files/89392/OpenStudio-Debug.txt)

![afterfiledialog-withautodesk](https://cloud.githubusercontent.com/assets/1327850/12305451/202c82de-b9f2-11e5-80a5-c5990e0ea95d.jpg)

After removing Autodesk 360:
![afterfiledialog-withoutautodesk](https://cloud.githubusercontent.com/assets/1327850/12305455/27b81f86-b9f2-11e5-8966-19c14ecef2b5.jpg)

![afterfiledialog-withoutautodesk-other](https://cloud.githubusercontent.com/assets/1327850/12305456/29f38c04-b9f2-11e5-860e-7fec789ea9bc.jpg)

![afterfiledialog-withoutautodesk-other2](https://cloud.githubusercontent.com/assets/1327850/12305479/3ffe0d26-b9f2-11e5-8f56-6248f279d361.jpg)

**Comment by macumber** [comment]
Noticed that AdSyncNamespace.dll seemed to be loading Qt4 dlls, this was suspicious.  Also saw this post https://forum.qt.io/topic/28608/solved-strange-error-while-opening-file/6

However, removing Autodesk 360 did not resolve the crash

**Comment by macumber** [comment]
Call stack of crash appears to be in C:\Program Files (x86)\Dell Backup and Recovery\Components\Shell\DBROverlayIconBackuped.dll
