### ISSUE TITLE
measure testing issue on mac

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1714]
@macumber I updated new reporting measure to use the newest testing standards. The measure tests works on windows, but for some reason it fails on my mac? Didn't know if it works for you on mac. This only affects the test, not use of measure elsewhere.

Here is the specific problem code
'''assert(!@@co.getDefaultEPWLocation.to_s.empty?)'''

Here is a link to it in use
https://github.com/NREL/OpenStudio-measures/blob/develop/NREL%20working%20measures/AnnualEndUseBreakdown/tests/AnnualEndUseBreakdown_Test.rb#L20

**Comment by jmarrec** [comment]
@DavidGoldwasser do you still have this problem? I'd hope you've been able to test it since then...
