### ISSUE TITLE
Thermal Zone Grid View won't accept decimals for zone multiplier

### ISSUE THREAD

**Issue by lincolnharmer** [NREL/OpenStudio#1715]
This feature is useless without the ability to use a decimal point. If the value is hard entered in the raw OSM file it is still not translated correctly. Found in v1.7.0

**Comment by evanweaver** [comment]
@lincolnharmer In the IDD, the Multiplier field is defined as an integer.

**Comment by lincolnharmer** [comment]
Gotchya @evanweaver . I wish EnergyPlus would allow for floating-point values for this field...

**Comment by macumber** [comment]
@lincolnharmer you might ask this as a question at unmethours, I'm interested in your use case.

**Comment by lincolnharmer** [comment]
@macumber I just was hoping to use this to quickly scale the area of my model. I don't know of an other way because this isn't allowed in Skecthup....is it?

**Comment by eringold** [comment]
@lincolnharmer it can be done with a [measure](https://unmethours.com/question/3566/scaling-commercial-reference-buildings/?answer=3579#post-id-3579).
