### ISSUE TITLE
Direction of fan in outdoor air supply

### ISSUE THREAD

**Issue by muh182** [NREL/OpenStudio#1717]
@kbenne Direction of the fan in the outdoor air supply should be reversed

![capture](https://cloud.githubusercontent.com/assets/2249257/8622347/ff5e7f80-26f8-11e5-81da-9ba0d70e4be9.PNG)

**Comment by jmarrec** [comment]
+1 (I noticed it [here](https://unmethours.com/question/12973/variable-speed-fan-ahu/?comment=12991#post-id-12991))

**Comment by jmarrec** [comment]
Still true in OS 2.2.1

![screen shot 2017-09-29 at 11 20 01 am](https://user-images.githubusercontent.com/5479063/31009554-2ae09cd0-a508-11e7-9584-df2bf4f27c94.png)
