### ISSUE TITLE
Warn user if they try to run a model with high poly windows (Bugzilla #870)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#172]
On 2012-08-29 14:21:26, @DavidGoldwasser wrote:

> This has come up in the past. In fact at one point we didn't even let the user add a 5th point to a window but that created crashes in SketchUp and also made it tough for people to make complex windows (by first drawing one and then splitting it up).
> 
> We could warn the user when the export this, similar to a space not in the model, or mis-matched construction. But for Radiance maybe want to support this?
> 
> We could get fancier and auto-split the window for them, or with a warning convert it to a rectangular window following some logic, but that opens up a big can of worms.
> 
> Or we do nothing, and have them dig through the EnergyPlus errors after they try to run it?
> 
> This was related to forum post.
> https://openstudio.nrel.gov/forums/openstudio-plug-google-sketchup/bug-reports-and-feature-requests/issue-windows-more-4-sides

Keywords: ForwardTranslation

**Comment by jmarrec** [comment]
I think it's fine to leave E+ provide information in eplusout.err
