### ISSUE TITLE
Improve scaling on high-DPI displays

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#1721]
Probably a low frequency (and low priority) feature request.. While OpenStudio (and PAT) are not terrible at high DPI, they still contain a good amount of text that's either tiny or too big for the field, and panes that need to be manually re-sized to see all content.

**Comment by DaveInCaz** [comment]
Referenced here: https://unmethours.com/question/37125/openstudio-user-interface-scaling-problems-very-small-buttons/

**Comment by JShultz89** [comment]
The scaling issue was more readily solved by finding the application shortcut > properties > compatibility > change DPI settings > override. See image below

![DPI Settings](https://user-images.githubusercontent.com/3712065/54789003-7e5cbe00-4c07-11e9-94d3-1ff53757c74b.png)

**Comment by jmarrec** [comment]
I also added automatic detection of High dpi screen for scaling. You can then customize with the environment variable , eg QT_SCALE_FACTOR=1.5 ./OpenStudioApp if you want
