### ISSUE TITLE
CoilSystemCoolingWaterHeatExchangerAssisted is not translated correctly

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#1722]
For one there needs to be an inner SPM on a node which is not described until translation time.  For two it seems the forward translator is just not handling this type correctly.  It seems to show up on the branch but the object itself is not translated.

**Comment by macumber** [comment]
@kbenne @DavidGoldwasser can you verify if this is fixed?  Marked as accepted in pivotal https://www.pivotaltracker.com/story/show/101286058

**Comment by DavidGoldwasser** [comment]
@kbenne it looks like I tested on a branch, but not sure if that made it into installer? I guess you owe $50 if it isn't fixed in the 2.x branch :)
https://www.pivotaltracker.com/n/projects/134010/stories/111232880

**Comment by macumber** [comment]
@kbenne can you verify?  There is $50 at stake...

**Comment by jmarrec** [comment]
Bump!

**Comment by jmarrec** [comment]
Ok, so I did some digging.

For sure, we need to add a SPM:MixedAir on the Cooling Coil Outlet Node or E+ will fatal out. I've already taken care of that, but here's a potential additional todo list:

* I think we should modify `CoilCoolingWater::addToNode` and `HeatExchangerAirToAirSensibleAndLatent::addToNode` to not allow connection if the coil is contained inside a `CoilSystemCoolingWaterHeatExchangerAssisted` object.
* Current `ForwardTranslateAirLoopHVAC` will add a SPM:MixedAir on the `HX Supply Air Outlet - Cooling Inlet Node` which I don't think is needed. Not sure if that's necessarily a bad thing though...
