### ISSUE TITLE
Runmanager loads models against wrong version of idd 

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#1726]
When creating a new job with OpenStudio's RunManager, calling Workflow::create to create a new job causes the model (osm) to be loaded into a workspace.  This happens immediately, before the job is queued up and running.  RunManger does this to "normalize" url fields before queueing up the job.  (in part to find weather files it seems)  This action happens [here](https://github.com/NREL/OpenStudio/blob/13ec115b00aa6a2af1426ceb26446f05014c8c8d/openstudiocore/src/runmanager/lib/NormalizeURLs.cpp#L52). The issue is that the osm may be of a prior version and the workspace is loading against current idd scheme. The referenced code is happening before os version translation has happened. The workspace is loaded with no strictness so the ill consequences seem to be rare, but they are certainly looming. Note that version translation normally happens in the ModelToIdf job, which happens after the job is queued up.  This issue does not present itself in the application because the app updates the model before anything else happens.  The issue is demonstrated when running the regression tests such as [this](https://github.com/NREL/OpenStudio-resources/blob/develop/model_tests/ModelSimulation_GTest.cpp#L100) code is doing.

**Comment by ljbrackney** [comment]
RunManager deprecated
