### ISSUE TITLE
Add method for creating non-ribbon windows

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1729]
The built in `setWindowToWallRatio` method is great for early design and quick model creation. However, it would be nice to have a complementary method to create normal windows for late design models, especially those with shading structures. This would facilitate a measure to add windows based on window dimensions, height offset, spacing, etc.

**Comment by DavidGoldwasser** [comment]
@MatthewSteen we have talked about this before, one question that comes up is that there could be a lot of ways to model the discrete windows, and should that be done in a measure (where users can make their own variations) or hard coded in C++.

One approach would be to set a target wwr, but also provide a window size and sill height, along some constraints on how close the window can be to an edge and to another window. This would then add the allowable number of windows equally spaced to get as close as possible to the target ratio. Or do you allow the width of the window to change to hit the exact ratio.

Another approach would be to import a 2d or 3d dxf to use for fenestration. This has been demonstrated in the plugin with manual workflow, but could be turned into a measure.

As shown with the AEDG fenestration measure there may also be the need for view and daylight windows with different properties and shading strategies. @macumber did a lot of work to support skylights grids. It is possible that some of that could be leveraged for windows.

If we did encourage/enable people to more easily model discrete windows then I would also want to make a measure that simplifies windows. The idea would be to use this when you wanted a really quick run, but you wouldn't' apply it to your base model (only in workflow for specific run). I have already played around with a measure to simplify a building geometry to a rectangle with similar aspect ratio to the full geometry.

**Comment by MatthewSteen** [comment]
>@MatthewSteen we have talked about this before, one question that comes up is that there could be a lot of ways to model the discrete windows, and should that be done in a measure (where users can make their own variations) or hard coded in C++.

I think having one built in method available through the Ruby bindings (and a measure) would be very useful to most users.

>One approach would be to set a target wwr, but also provide a window size and sill height, along some constraints on how close the window can be to an edge and to another window. This would then add the allowable number of windows equally spaced to get as close as possible to the target ratio. Or do you allow the width of the window to change to hit the exact ratio.

Yeah, lots of way to do it, but I think a measure using only an `addDiscreteWindows` method could accommodate many of them. Here are some of the ways IES VE handles windows: 

**Add Window**
![ve_windows-1](https://cloud.githubusercontent.com/assets/8397034/9010483/672b624c-3764-11e5-89b0-e60700120273.png)

![ve_windows-2](https://cloud.githubusercontent.com/assets/8397034/9010501/7649ebf4-3764-11e5-8bac-d8e5042a4d0a.png)

**Place In Plan**
![ve_windows-3](https://cloud.githubusercontent.com/assets/8397034/9010519/92e5e394-3764-11e5-8c3a-118a28af6223.png)

**Edit Openings**
![ve_windows-4](https://cloud.githubusercontent.com/assets/8397034/9010526/9b371946-3764-11e5-923f-59ce23885176.png)

>Another approach would be to import a 2d or 3d dxf to use for fenestration. This has been demonstrated in the plugin with manual workflow, but could be turned into a measure.

I've seen the tutorial on using CAD elevations to draw windows, but haven't used it yet. A measure would be preferable for new construction.

>As shown with the AEDG fenestration measure there may also be the need for view and daylight windows with different properties and shading strategies. @macumber did a lot of work to support skylights grids. It is possible that some of that could be leveraged for windows.

A built in method would allow for a very useful measure chain that would allow a user to create RSF/ESIF fenestration (minus the vertical shading devices) which is what the AEDG measure looks like it does.

1. Add Remove Or Replace Discrete *View* Windows
2. [Add Remove Or Replace Window Overhangs](https://bcl.nrel.gov/node/82837)
3. Add Remove Or Replace Discrete *Daylight* Windows

>If we did encourage/enable people to more easily model discrete windows then I would also want to make a measure that simplifies windows. The idea would be to use this when you wanted a really quick run, but you wouldn't' apply it to your base model (only in workflow for specific run). I have already played around with a measure to simplify a building geometry to a rectangle with similar aspect ratio to the full geometry.

No comment

**Comment by muh182** [comment]
@DavidGoldwasser  @MatthewSteen We have developed a SketchUp plugin a while ago to create individual windows. We just did not get a chance to finalize the plugin/measure and upload it on BCL. I spoke with @macumber last week about the plugin, and Dan mentioned it would be a good time to publicize the plugin.

The SketchUp plugin is accessible [here](https://github.com/buildsci/openstudio_measures/blob/master/individualWindows/SetIndividualWindows.rb)

I have put some descriptions about the algorithm [here](https://github.com/buildsci/openstudio_measures/blob/master/individualWindows/individualWindows.md). I'll try to clear the code and descriptions this coming week.

Besides cleaning the code, we know one problem with the code that needs to be fixed. The code works well when the surface is not tilted. However, when the surface is titled, the plugin does not draw the windows correctly. The following images show how the plugin works for straight and titled surfaces.

![1](https://cloud.githubusercontent.com/assets/2249257/9029230/acce2154-395d-11e5-87ce-c315830f3da7.png)
![2](https://cloud.githubusercontent.com/assets/2249257/9029231/ae0b46f0-395d-11e5-9a62-49c5b17f073c.png)
![3](https://cloud.githubusercontent.com/assets/2249257/9029233/b0e97b76-395d-11e5-9200-7de2f205084d.png)
![4](https://cloud.githubusercontent.com/assets/2249257/9029235/b470e950-395d-11e5-8de8-3d074ba0ca61.png)

Please, place the plugin in your `Ruby\openstudio\sketchup_plugin\user_scripts\Alter or Add Model Elements` folder of your OpenStudio folder and try the plugin. We will be happy to revise the plugin based on your feedback and create a BCL measure.

**Comment by MatthewSteen** [comment]
Will do @muh182, thanks!

**Comment by MatthewSteen** [comment]
Will do @muh182, thanks!

**Comment by macumber** [comment]
Hey @MatthewSteen have you and Eric had a chance to check this out?

**Comment by macumber** [comment]
@DavidGoldwasser and @asparke2 you guys might want to try this as well, the plugin user script is at https://github.com/buildsci/openstudio_measures/tree/master/individualWindows

**Comment by MatthewSteen** [comment]
@macumber only briefly, we're starting several OS models so will do more testing. Feel free to close if you're cleaning up the issues backlog.

**Comment by macumber** [comment]
No pressure to close, @muh182 was just looking for some feedback

**Comment by aaron-boranian** [comment]
Add method for creating non-ribbon windows

Problem: Users cannot (auto) create windows in the manner they would like; especially considering shading structures.

Solution: Add method with more capabilities during automated window creation

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9098830)
