### ISSUE TITLE
Crash on open file due to missing attributes (Bugzilla #871)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#173]
On 2012-08-30 12:53:44, @macumber wrote:

> Looks like some attributes are still missing, causes app to crash when opening attached file.  Use a debug build to reproduce, asserts might not trigger in release mode.

On 2012-08-30 12:54:04, @macumber wrote:

> Created an attachment (id=201)
> Test file

On 2012-08-30 13:00:11, @macumber wrote:

> Here is the call stack:
> 
> >	openstudio_lib.dll!openstudio::OSQuantityEdit::bind(openstudio::model::ModelObject & modelObject={...}, const char * property=0x596419b8, bool isIP=false, const boost::optional<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > & isDefaultedProperty={...}, const boost::optional<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > & isAutosizedProperty={...}, const boost::optional<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > & isAutocalculatedProperty={...})  Line 80 + 0x106 bytes	C++
>  	openstudio_lib.dll!openstudio::MaterialInspectorView::attach(openstudio::model::Material & masslessOpaqueMaterial={...})  Line 186 + 0x63 bytes	C++
>  	openstudio_lib.dll!openstudio::MaterialInspectorView::onSelectModelObject(const openstudio::model::ModelObject & modelObject={...})  Line 173	C++
>  	openstudio_lib.dll!openstudio::ModelObjectInspectorView::selectModelObject(const openstudio::model::ModelObject & modelObject={...})  Line 75 + 0x1e bytes	C++
>  	openstudio_lib.dll!openstudio::MaterialsInspectorView::showMaterialInspectorView(const openstudio::model::ModelObject & modelObject={...})  Line 234	C++
>  	openstudio_lib.dll!openstudio::MaterialsInspectorView::onSelectModelObject(const openstudio::model::ModelObject & modelObject={...})  Line 133	C++
>  	openstudio_lib.dll!openstudio::ModelObjectInspectorView::selectModelObject(const openstudio::model::ModelObject & modelObject={...})  Line 75 + 0x1e bytes	C++
>  	openstudio_lib.dll!openstudio::ModelObjectInspectorView::onSelectItem(openstudio::OSItem * item=0x19cfacb8)  Line 91 + 0x28 bytes	C++
>  	openstudio_lib.dll!openstudio::OSInspectorView::selectItem(openstudio::OSItem * item=0x19cfacb8)  Line 81 + 0x16 bytes	C++
>  	openstudio_lib.dll!openstudio::SubTabController::onSelectItem(openstudio::OSItem * item=0x19cfacb8)  Line 105	C++
>  	openstudio_lib.dll!openstudio::SubTabController::selectItem(openstudio::OSItem * item=0x19cfacb8)  Line 120 + 0x13 bytes	C++
>  	openstudio_lib.dll!openstudio::SubTabController::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=2, void * * _a=0x00d3920c)  Line 94 + 0x11 bytes	C++
>  	openstudio_lib.dll!openstudio::ModelSubTabController::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=8, void * * _a=0x00d3920c)  Line 71 + 0x14 bytes	C++
>  	openstudio_lib.dll!openstudio::MaterialsController::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=8, void * * _a=0x00d3920c)  Line 64 + 0x14 bytes	C++
>  	QtCored4.dll!QMetaObject::metacall(QObject * object=0x06888788, QMetaObject::Call cl=InvokeMetaMethod, int idx=8, void * * argv=0x00d3920c)  Line 238	C++
>  	QtCored4.dll!QMetaObject::activate(QObject * sender=0x068888b0, const QMetaObject * m=0x59be68a4, int local_signal_index=0, void * * argv=0x00d3920c)  Line 3286 + 0x27 bytes	C++
>  	openstudio_lib.dll!openstudio::SubTabView::itemSelected(openstudio::OSItem * _t1=0x19cfacb8)  Line 114 + 0x17 bytes	C++
>  	openstudio_lib.dll!openstudio::SubTabView::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=0, void * * _a=0x00d3935c)  Line 91 + 0x11 bytes	C++
>  	openstudio_lib.dll!openstudio::ModelSubTabView::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=28, void * * _a=0x00d3935c)  Line 75 + 0x14 bytes	C++
>  	openstudio_lib.dll!openstudio::MaterialsView::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=28, void * * _a=0x00d3935c)  Line 64 + 0x14 bytes	C++
>  	QtCored4.dll!QMetaObject::metacall(QObject * object=0x068888b0, QMetaObject::Call cl=InvokeMetaMethod, int idx=28, void * * argv=0x00d3935c)  Line 238	C++
>  	QtCored4.dll!QMetaObject::activate(QObject * sender=0x06caeb48, const QMetaObject * m=0x59be5efc, int local_signal_index=0, void * * argv=0x00d3935c)  Line 3286 + 0x27 bytes	C++
>  	openstudio_lib.dll!openstudio::OSItemSelector::itemSelected(openstudio::OSItem * _t1=0x19cfacb8)  Line 94 + 0x17 bytes	C++
>  	openstudio_lib.dll!openstudio::OSItemSelector::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=0, void * * _a=0x00d394ac)  Line 79 + 0x11 bytes	C++
>  	openstudio_lib.dll!openstudio::OSCollapsibleItemList::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=27, void * * _a=0x00d394ac)  Line 74 + 0x14 bytes	C++
>  	openstudio_lib.dll!openstudio::ModelObjectTypeListView::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=27, void * * _a=0x00d394ac)  Line 64 + 0x14 bytes	C++
>  	QtCored4.dll!QMetaObject::metacall(QObject * object=0x06caeb48, QMetaObject::Call cl=InvokeMetaMethod, int idx=27, void * * argv=0x00d394ac)  Line 238	C++
>  	QtCored4.dll!QMetaObject::activate(QObject * sender=0x0542a540, const QMetaObject * m=0x59be5d90, int local_signal_index=1, void * * argv=0x00d394ac)  Line 3286 + 0x27 bytes	C++
>  	openstudio_lib.dll!openstudio::OSCollapsibleItem::itemSelected(openstudio::OSItem * _t1=0x19cfacb8)  Line 120 + 0x17 bytes	C++
>  	openstudio_lib.dll!openstudio::OSCollapsibleItem::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=1, void * * _a=0x00d395e0)  Line 93 + 0x11 bytes	C++
>  	openstudio_lib.dll!openstudio::ModelObjectTypeItem::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=28, void * * _a=0x00d395e0)  Line 64 + 0x14 bytes	C++
>  	QtCored4.dll!QMetaObject::metacall(QObject * object=0x0542a540, QMetaObject::Call cl=InvokeMetaMethod, int idx=28, void * * argv=0x00d395e0)  Line 238	C++
>  	QtCored4.dll!QMetaObject::activate(QObject * sender=0x06ca5940, const QMetaObject * m=0x59be5efc, int local_signal_index=0, void * * argv=0x00d395e0)  Line 3286 + 0x27 bytes	C++
>  	openstudio_lib.dll!openstudio::OSItemSelector::itemSelected(openstudio::OSItem * _t1=0x19cfacb8)  Line 94 + 0x17 bytes	C++
>  	openstudio_lib.dll!openstudio::OSItemList::selectItem(openstudio::OSItem * selectItem=0x19cfacb8)  Line 301	C++
>  	openstudio_lib.dll!openstudio::OSItemList::setItemIds(const std::vector<openstudio::OSItemId,std::allocator<openstudio::OSItemId> > & itemIds=[12]({BCL_SOURCE_ID={...} m_itemId={...} m_sourceId={...} ...},{BCL_SOURCE_ID={...} m_itemId={...} m_sourceId={...} ...},{BCL_SOURCE_ID={...} m_itemId={...} m_sourceId={...} ...},{BCL_SOURCE_ID={...} m_itemId={...} m_sourceId={...} ...},{BCL_SOURCE_ID={...} m_itemId={...} m_sourceId={...} ...},{BCL_SOURCE_ID={...} m_itemId={...} m_sourceId={...} ...},{BCL_SOURCE_ID={...} m_itemId={...} m_sourceId=,...))  Line 220	C++
>  	openstudio_lib.dll!openstudio::OSItemList::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=5, void * * _a=0x00d398a0)  Line 90 + 0xf bytes	C++
>  	openstudio_lib.dll!openstudio::ModelObjectListView::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=36, void * * _a=0x00d398a0)  Line 130 + 0x14 bytes	C++
>  	QtCored4.dll!QMetaObject::metacall(QObject * object=0x06ca5940, QMetaObject::Call cl=InvokeMetaMethod, int idx=36, void * * argv=0x00d398a0)  Line 238	C++
>  	QtCored4.dll!QMetaObject::activate(QObject * sender=0x06ca5a18, const QMetaObject * m=0x59be6010, int local_signal_index=0, void * * argv=0x00d398a0)  Line 3286 + 0x27 bytes	C++
>  	openstudio_lib.dll!openstudio::OSVectorController::itemIds(const std::vector<openstudio::OSItemId,std::allocator<openstudio::OSItemId> > & _t1=[12]({BCL_SOURCE_ID={...} m_itemId={...} m_sourceId={...} ...},{BCL_SOURCE_ID={...} m_itemId={...} m_sourceId={...} ...},{BCL_SOURCE_ID={...} m_itemId={...} m_sourceId={...} ...},{BCL_SOURCE_ID={...} m_itemId={...} m_sourceId={...} ...},{BCL_SOURCE_ID={...} m_itemId={...} m_sourceId={...} ...},{BCL_SOURCE_ID={...} m_itemId={...} m_sourceId={...} ...},{BCL_SOURCE_ID={...} m_itemId={...} m_sourceId=,...))  Line 101 + 0x17 bytes	C++
>  	openstudio_lib.dll!openstudio::OSVectorController::reportItems()  Line 32 + 0x36 bytes	C++
>  	openstudio_lib.dll!openstudio::OSVectorController::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=1, void * * _a=0x00d399dc)  Line 85 + 0x8 bytes	C++
>  	openstudio_lib.dll!openstudio::ModelObjectListController::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=5, void * * _a=0x00d399dc)  Line 73 + 0x14 bytes	C++
>  	QtCored4.dll!QMetaObject::metacall(QObject * object=0x06ca5a18, QMetaObject::Call cl=InvokeMetaMethod, int idx=5, void * * argv=0x00d399dc)  Line 238	C++
>  	QtCored4.dll!QMetaObject::activate(QObject * sender=0x05429fb8, const QMetaObject * m=0x672eb8f0, int local_signal_index=0, void * * argv=0x00000000)  Line 3286 + 0x27 bytes	C++
>  	QtCored4.dll!QSingleShotTimer::timeout()  Line 82 + 0x12 bytes	C++
>  	QtCored4.dll!QSingleShotTimer::timerEvent(QTimerEvent * __formal=0x00d3a170)  Line 313	C++
>  	QtCored4.dll!QObject::event(QEvent * e=0x00d3a170)  Line 1217	C++
>  	QtGuid4.dll!QApplicationPrivate::notify_helper(QObject * receiver=0x05429fb8, QEvent * e=0x00d3a170)  Line 4242 + 0x11 bytes	C++
>  	QtGuid4.dll!QApplication::notify(QObject * receiver=0x05429fb8, QEvent * e=0x00d3a170)  Line 3661 + 0x10 bytes	C++
>  	OpenStudio.exe!openstudio::OpenStudioApp::notify(QObject * receiver=0x05429fb8, QEvent * event=0x00d3a170)  Line 710 + 0x13 bytes	C++
>  	QtCored4.dll!QCoreApplication::notifyInternal(QObject * receiver=0x05429fb8, QEvent * event=0x00d3a170)  Line 704 + 0x15 bytes	C++
>  	QtCored4.dll!QCoreApplication::sendEvent(QObject * receiver=0x05429fb8, QEvent * event=0x00d3a170)  Line 215 + 0x39 bytes	C++
>  	QtCored4.dll!QEventDispatcherWin32::event(QEvent * e=0x0542a460)  Line 1073 + 0x10 bytes	C++
>  	QtGuid4.dll!QApplicationPrivate::notify_helper(QObject * receiver=0x046b0428, QEvent * e=0x0542a460)  Line 4242 + 0x11 bytes	C++
>  	QtGuid4.dll!QApplication::notify(QObject * receiver=0x046b0428, QEvent * e=0x0542a460)  Line 3661 + 0x10 bytes	C++
>  	OpenStudio.exe!openstudio::OpenStudioApp::notify(QObject * receiver=0x046b0428, QEvent * event=0x0542a460)  Line 710 + 0x13 bytes	C++
>  	QtCored4.dll!QCoreApplication::notifyInternal(QObject * receiver=0x046b0428, QEvent * event=0x0542a460)  Line 704 + 0x15 bytes	C++
>  	QtCored4.dll!QCoreApplication::sendEvent(QObject * receiver=0x046b0428, QEvent * event=0x0542a460)  Line 215 + 0x39 bytes	C++
>  	QtCored4.dll!QCoreApplicationPrivate::sendPostedEvents(QObject * receiver=0x00000000, int event_type=0, QThreadData * data=0x046b0120)  Line 1345 + 0xd bytes	C++
>  	QtCored4.dll!qt_internal_proc(HWND__ * hwnd=0x00041354, unsigned int message=1025, unsigned int wp=0, long lp=0)  Line 507 + 0x10 bytes	C++
>  	user32.dll!_InternalCallWinProc@20()  + 0x23 bytes	
>  	user32.dll!_UserCallWinProcCheckWow@32()  + 0xb7 bytes	
>  	user32.dll!_DispatchMessageWorker@8()  + 0xed bytes	
>  	user32.dll!_DispatchMessageW@4()  + 0xf bytes	
>  	user32.dll!_DialogBox2@16()  + 0x1c0 bytes	
>  	user32.dll!_InternalDialogBox@24()  + 0xc9 bytes	
>  	user32.dll!_SoftModalMessageBox@4()  + 0x757 bytes	
>  	user32.dll!_MessageBoxWorker@4()  + 0x269 bytes	
>  	user32.dll!_MessageBoxTimeoutW@24()  + 0x52 bytes	
>  	user32.dll!_MessageBoxExW@20()  + 0x1b bytes	
>  	user32.dll!_MessageBoxW@16()  + 0x18 bytes	
>  	msvcr90d.dll!___crtMessageBoxW()  + 0x216 bytes	
>  	msvcr90d.dll!__wassert()  + 0xb38 bytes	
>  	openstudio_lib.dll!openstudio::OSQuantityEdit::bind(openstudio::model::ModelObject & modelObject={...}, const char * property=0x597052d8, bool isIP=false, const boost::optional<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > & isDefaultedProperty={...}, const boost::optional<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > & isAutosizedProperty={...}, const boost::optional<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > & isAutocalculatedProperty={...})  Line 80 + 0x106 bytes	C++
>  	openstudio_lib.dll!openstudio::WindowMaterialGlazingInspectorView::attach(openstudio::model::Glazing & glazing={...})  Line 257 + 0x75 bytes	C++
>  	openstudio_lib.dll!openstudio::WindowMaterialGlazingInspectorView::onSelectModelObject(const openstudio::model::ModelObject & modelObject={...})  Line 241	C++
>  	openstudio_lib.dll!openstudio::ModelObjectInspectorView::selectModelObject(const openstudio::model::ModelObject & modelObject={...})  Line 75 + 0x1e bytes	C++
>  	openstudio_lib.dll!openstudio::MaterialsInspectorView::showWindowMaterialGlazingInspectorView(const openstudio::model::ModelObject & modelObject={...})  Line 332	C++
>  	openstudio_lib.dll!openstudio::MaterialsInspectorView::onSelectModelObject(const openstudio::model::ModelObject & modelObject={...})  Line 160	C++
>  	openstudio_lib.dll!openstudio::ModelObjectInspectorView::selectModelObject(const openstudio::model::ModelObject & modelObject={...})  Line 75 + 0x1e bytes	C++
>  	openstudio_lib.dll!openstudio::ModelObjectInspectorView::onSelectItem(openstudio::OSItem * item=0x19bf7c20)  Line 91 + 0x28 bytes	C++
>  	openstudio_lib.dll!openstudio::OSInspectorView::selectItem(openstudio::OSItem * item=0x19bf7c20)  Line 81 + 0x16 bytes	C++
>  	openstudio_lib.dll!openstudio::SubTabController::onSelectItem(openstudio::OSItem * item=0x19bf7c20)  Line 105	C++
>  	openstudio_lib.dll!openstudio::SubTabController::selectItem(openstudio::OSItem * item=0x19bf7c20)  Line 120 + 0x13 bytes	C++
>  	openstudio_lib.dll!openstudio::SubTabController::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=2, void * * _a=0x00d3c41c)  Line 94 + 0x11 bytes	C++
>  	openstudio_lib.dll!openstudio::ModelSubTabController::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=8, void * * _a=0x00d3c41c)  Line 71 + 0x14 bytes	C++
>  	openstudio_lib.dll!openstudio::MaterialsController::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=8, void * * _a=0x00d3c41c)  Line 64 + 0x14 bytes	C++
>  	QtCored4.dll!QMetaObject::metacall(QObject * object=0x06888788, QMetaObject::Call cl=InvokeMetaMethod, int idx=8, void * * argv=0x00d3c41c)  Line 238	C++
>  	QtCored4.dll!QMetaObject::activate(QObject * sender=0x068888b0, const QMetaObject * m=0x59be68a4, int local_signal_index=0, void * * argv=0x00d3c41c)  Line 3286 + 0x27 bytes	C++
>  	openstudio_lib.dll!openstudio::SubTabView::itemSelected(openstudio::OSItem * _t1=0x19bf7c20)  Line 114 + 0x17 bytes	C++
>  	openstudio_lib.dll!openstudio::SubTabView::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=0, void * * _a=0x00d3c56c)  Line 91 + 0x11 bytes	C++
>  	openstudio_lib.dll!openstudio::ModelSubTabView::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=28, void * * _a=0x00d3c56c)  Line 75 + 0x14 bytes	C++
>  	openstudio_lib.dll!openstudio::MaterialsView::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=28, void * * _a=0x00d3c56c)  Line 64 + 0x14 bytes	C++
>  	QtCored4.dll!QMetaObject::metacall(QObject * object=0x068888b0, QMetaObject::Call cl=InvokeMetaMethod, int idx=28, void * * argv=0x00d3c56c)  Line 238	C++
>  	QtCored4.dll!QMetaObject::activate(QObject * sender=0x06caeb48, const QMetaObject * m=0x59be5efc, int local_signal_index=0, void * * argv=0x00d3c56c)  Line 3286 + 0x27 bytes	C++
>  	openstudio_lib.dll!openstudio::OSItemSelector::itemSelected(openstudio::OSItem * _t1=0x19bf7c20)  Line 94 + 0x17 bytes	C++
>  	openstudio_lib.dll!openstudio::OSItemSelector::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=0, void * * _a=0x00d3c6bc)  Line 79 + 0x11 bytes	C++
>  	openstudio_lib.dll!openstudio::OSCollapsibleItemList::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=27, void * * _a=0x00d3c6bc)  Line 74 + 0x14 bytes	C++
>  	openstudio_lib.dll!openstudio::ModelObjectTypeListView::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=27, void * * _a=0x00d3c6bc)  Line 64 + 0x14 bytes	C++
>  	QtCored4.dll!QMetaObject::metacall(QObject * object=0x06caeb48, QMetaObject::Call cl=InvokeMetaMethod, int idx=27, void * * argv=0x00d3c6bc)  Line 238	C++
>  	QtCored4.dll!QMetaObject::activate(QObject * sender=0x08ee2b18, const QMetaObject * m=0x59be5d90, int local_signal_index=1, void * * argv=0x00d3c6bc)  Line 3286 + 0x27 bytes	C++
>  	openstudio_lib.dll!openstudio::OSCollapsibleItem::itemSelected(openstudio::OSItem * _t1=0x19bf7c20)  Line 120 + 0x17 bytes	C++
>  	openstudio_lib.dll!openstudio::OSCollapsibleItem::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=1, void * * _a=0x00d3c7f0)  Line 93 + 0x11 bytes	C++
>  	openstudio_lib.dll!openstudio::ModelObjectTypeItem::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=28, void * * _a=0x00d3c7f0)  Line 64 + 0x14 bytes	C++
>  	QtCored4.dll!QMetaObject::metacall(QObject * object=0x08ee2b18, QMetaObject::Call cl=InvokeMetaMethod, int idx=28, void * * argv=0x00d3c7f0)  Line 238	C++
>  	QtCored4.dll!QMetaObject::activate(QObject * sender=0x08f34da8, const QMetaObject * m=0x59be5efc, int local_signal_index=0, void * * argv=0x00d3c7f0)  Line 3286 + 0x27 bytes	C++
>  	openstudio_lib.dll!openstudio::OSItemSelector::itemSelected(openstudio::OSItem * _t1=0x19bf7c20)  Line 94 + 0x17 bytes	C++
>  	openstudio_lib.dll!openstudio::OSItemList::selectItem(openstudio::OSItem * selectItem=0x19bf7c20)  Line 301	C++
>  	openstudio_lib.dll!openstudio::OSItemList::setItemIds(const std::vector<openstudio::OSItemId,std::allocator<openstudio::OSItemId> > & itemIds=[2]({BCL_SOURCE_ID={...} m_itemId={...} m_sourceId={...} ...},{BCL_SOURCE_ID={...} m_itemId={...} m_sourceId={...} ...}))  Line 220	C++
>  	openstudio_lib.dll!openstudio::OSItemList::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=5, void * * _a=0x00d3cab0)  Line 90 + 0xf bytes	C++
>  	openstudio_lib.dll!openstudio::ModelObjectListView::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=36, void * * _a=0x00d3cab0)  Line 130 + 0x14 bytes	C++
>  	QtCored4.dll!QMetaObject::metacall(QObject * object=0x08f34da8, QMetaObject::Call cl=InvokeMetaMethod, int idx=36, void * * argv=0x00d3cab0)  Line 238	C++
>  	QtCored4.dll!QMetaObject::activate(QObject * sender=0x08f34e80, const QMetaObject * m=0x59be6010, int local_signal_index=0, void * * argv=0x00d3cab0)  Line 3286 + 0x27 bytes	C++
>  	openstudio_lib.dll!openstudio::OSVectorController::itemIds(const std::vector<openstudio::OSItemId,std::allocator<openstudio::OSItemId> > & _t1=[2]({BCL_SOURCE_ID={...} m_itemId={...} m_sourceId={...} ...},{BCL_SOURCE_ID={...} m_itemId={...} m_sourceId={...} ...}))  Line 101 + 0x17 bytes	C++
>  	openstudio_lib.dll!openstudio::OSVectorController::reportItems()  Line 32 + 0x36 bytes	C++
>  	openstudio_lib.dll!openstudio::OSVectorController::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=1, void * * _a=0x00d3cbec)  Line 85 + 0x8 bytes	C++
>  	openstudio_lib.dll!openstudio::ModelObjectListController::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=5, void * * _a=0x00d3cbec)  Line 73 + 0x14 bytes	C++
>  	QtCored4.dll!QMetaObject::metacall(QObject * object=0x08f34e80, QMetaObject::Call cl=InvokeMetaMethod, int idx=5, void * * argv=0x00d3cbec)  Line 238	C++
>  	QtCored4.dll!QMetaObject::activate(QObject * sender=0x08ee26f8, const QMetaObject * m=0x672eb8f0, int local_signal_index=0, void * * argv=0x00000000)  Line 3286 + 0x27 bytes	C++
>  	QtCored4.dll!QSingleShotTimer::timeout()  Line 82 + 0x12 bytes	C++
>  	QtCored4.dll!QSingleShotTimer::timerEvent(QTimerEvent * __formal=0x00d3d380)  Line 313	C++
>  	QtCored4.dll!QObject::event(QEvent * e=0x00d3d380)  Line 1217	C++
>  	QtGuid4.dll!QApplicationPrivate::notify_helper(QObject * receiver=0x08ee26f8, QEvent * e=0x00d3d380)  Line 4242 + 0x11 bytes	C++
>  	QtGuid4.dll!QApplication::notify(QObject * receiver=0x08ee26f8, QEvent * e=0x00d3d380)  Line 3661 + 0x10 bytes	C++
>  	OpenStudio.exe!openstudio::OpenStudioApp::notify(QObject * receiver=0x08ee26f8, QEvent * event=0x00d3d380)  Line 710 + 0x13 bytes	C++
>  	QtCored4.dll!QCoreApplication::notifyInternal(QObject * receiver=0x08ee26f8, QEvent * event=0x00d3d380)  Line 704 + 0x15 bytes	C++
>  	QtCored4.dll!QCoreApplication::sendEvent(QObject * receiver=0x08ee26f8, QEvent * event=0x00d3d380)  Line 215 + 0x39 bytes	C++
>  	QtCored4.dll!QEventDispatcherWin32::event(QEvent * e=0x08ee2a38)  Line 1073 + 0x10 bytes	C++
>  	QtGuid4.dll!QApplicationPrivate::notify_helper(QObject * receiver=0x046b0428, QEvent * e=0x08ee2a38)  Line 4242 + 0x11 bytes	C++
>  	QtGuid4.dll!QApplication::notify(QObject * receiver=0x046b0428, QEvent * e=0x08ee2a38)  Line 3661 + 0x10 bytes	C++
>  	OpenStudio.exe!openstudio::OpenStudioApp::notify(QObject * receiver=0x046b0428, QEvent * event=0x08ee2a38)  Line 710 + 0x13 bytes	C++
>  	QtCored4.dll!QCoreApplication::notifyInternal(QObject * receiver=0x046b0428, QEvent * event=0x08ee2a38)  Line 704 + 0x15 bytes	C++
>  	QtCored4.dll!QCoreApplication::sendEvent(QObject * receiver=0x046b0428, QEvent * event=0x08ee2a38)  Line 215 + 0x39 bytes	C++
>  	QtCored4.dll!QCoreApplicationPrivate::sendPostedEvents(QObject * receiver=0x00000000, int event_type=0, QThreadData * data=0x046b0120)  Line 1345 + 0xd bytes	C++
>  	QtCored4.dll!qt_internal_proc(HWND__ * hwnd=0x00041354, unsigned int message=1025, unsigned int wp=0, long lp=0)  Line 507 + 0x10 bytes	C++
>  	user32.dll!_InternalCallWinProc@20()  + 0x23 bytes	
>  	user32.dll!_UserCallWinProcCheckWow@32()  + 0xb7 bytes	
>  	user32.dll!_DispatchMessageWorker@8()  + 0xed bytes	
>  	user32.dll!_DispatchMessageW@4()  + 0xf bytes	
>  	QtCored4.dll!QEventDispatcherWin32::processEvents(QFlags<enum QEventLoop::ProcessEventsFlag> flags={...})  Line 753	C++
>  	QtGuid4.dll!QGuiEventDispatcherWin32::processEvents(QFlags<enum QEventLoop::ProcessEventsFlag> flags={...})  Line 1133 + 0x15 bytes	C++
>  	QtCored4.dll!QEventLoop::processEvents(QFlags<enum QEventLoop::ProcessEventsFlag> flags={...})  Line 150	C++
>  	QtCored4.dll!QEventLoop::exec(QFlags<enum QEventLoop::ProcessEventsFlag> flags={...})  Line 201 + 0x2d bytes	C++
>  	QtCored4.dll!QCoreApplication::exec()  Line 981 + 0x15 bytes	C++
>  	QtGuid4.dll!QApplication::exec()  Line 3571	C++
>  	OpenStudio.exe!main(int argc=1, char * * argv=0x046ad370)  Line 96 + 0x8 bytes	C++
>  	OpenStudio.exe!WinMain(HINSTANCE__ * instance=0x002c0000, HINSTANCE__ * prevInstance=0x00000000, char * __formal=0x00e37198, int cmdShow=1)  Line 131 + 0x12 bytes	C++
>  	OpenStudio.exe!__tmainCRTStartup()  Line 574 + 0x35 bytes	C
>  	OpenStudio.exe!WinMainCRTStartup()  Line 399	C
>  	kernel32.dll!@BaseThreadInitThunk@12()  + 0x12 bytes	
>  	ntdll.dll!___RtlUserThreadStart@8()  + 0x27 bytes	
>  	ntdll.dll!__RtlUserThreadStart@8()  + 0x1b bytes

On 2012-11-01 10:53:36, @DavidGoldwasser wrote:

> Re-test with current installer to see if still crashes.

Original attachments:
* RadianceTest.osm (ID 201)

Keywords: Crash, EdgeCase

**Comment by DavidGoldwasser** [comment]
Stale
