### ISSUE TITLE
ModelObjects not translated to E+

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1730]
Several model objects are not being translated to E+, https://github.com/NREL/OpenStudio/commit/2ccd1315eeb05d0a9eddc0277842fc12b18b6ff0.  I have not done a full audit, suspect there may be others.

**Comment by DavidGoldwasser** [comment]
We can constrain this to just simulation settings for now, but we need to do a full audit that every model object is being translated.

**Comment by macumber** [comment]
The following objects do not have translate functions in the ForwardTranslator, emphasis on ones that are a problem (@kbenne @mbadams5 can you edit to include HVAC ones that are an issue?):

AirTerminalDualDuctVAV
AirTerminalSingleDuctConstantVolumeCooledBeam
BuildingStory - ok, no E+ counterpart
ClimateZones - ok, no E+ counterpart
CoilCoolingCooledBeam
CoilCoolingDXMultiSpeedStageData
CoilCoolingLowTempRadiantConstFlow
CoilCoolingLowTempRadiantVarFlow
CoilCoolingDXVariableSpeedSpeedData
CoilCoolingWaterToAirHeatPumpVariableSpeedEquationFitSpeedData
CoilHeatingDXMultiSpeedStageData
CoilHeatingGasMultiStageStageData
CoilHeatingLowTempRadiantConstFlow
CoilHeatingLowTempRadiantVarFlow
CoilHeatingDXVariableSpeedSpeedData
CoilHeatingWaterToAirHeatPumpVariableSpeedEquationFitSpeedData
CoilHeatingWaterBaseboard
*ComponentCostAdjustments*
ComponentData - ok, no E+ counterpart
Connection
ConnectorMixer
ConnectorSplitter
DefaultConstructionSet - ok, included in other translation
DefaultScheduleSet - ok, included in other translation
DefaultSubSurfaceConstructions - ok, included in other translation
DefaultSurfaceConstructions - ok, included in other translation
*DesignSpecificationZoneAirDistribution*
ElectricEquipmentDefinition - ok, included in other translation
ExteriorLightsDefinition - ok, included in other translation
Facility - ok, no E+ counterpart
GasEquipmentDefinition - ok, included in other translation
GenericModelObject - ok, no E+ counterpart
*GlareSensor*
HotWaterEquipmentDefinition - ok, included in other translation
InternalMassDefinition - ok, included in other translation
*LifeCycleCostUsePriceEscalation*
LightingDesignDay - ok, no E+ counterpart
LightingSimulationControl - ok, no E+ counterpart
LightingSimulationZone - ok, no E+ counterpart
LightsDefinition - ok, included in other translation
LuminaireDefinition - ok, included in other translation
ModelObjectList
OtherEquipmentDefinition - ok, included in other translation
PeopleDefinition - ok, included in other translation
*ProgramControl*
RadianceParameters - ok, no E+ counterpart
RefrigerationDefrostCycleParameters
RefrigerationWalkInZoneBoundary
RenderingColor - ok, no E+ counterpart
ScheduleRule - ok, included in other translation
StandardsInformationConstruction - ok, no E+ counterpart
StandardsInformationMaterial - ok, no E+ counterpart
SteamEquipmentDefinition - ok, included in other translation
*ThermochromicGlazing*
UtilityBill - ok, model objects not really implemented, should be removed
UtilityCost_Charge_Block - ok, model objects not really implemented, should be removed
UtilityCost_Charge_Simple - ok, model objects not really implemented, should be removed
UtilityCost_Computation - ok, model objects not really implemented, should be removed
UtilityCost_Qualify - ok, model objects not really implemented, should be removed
UtilityCost_Ratchet - ok, model objects not really implemented, should be removed
UtilityCost_Tariff - ok, model objects not really implemented, should be removed
UtilityCost_Variable - ok, model objects not really implemented, should be removed
WaterUseEquipmentDefinition - ok, included in other translation
WeatherFile - ok, no E+ counterpart
*WeatherFileConditionType*
*WeatherFileDays*
*WindowDataFile*
YearDescription - ok, no E+ counterpart
*ZoneAirContaminantBalance*
*ZoneCapacitanceMultiplierResearchSpecial*

**Comment by kbenne** [comment]
I'd say these many or most of these are translated, but not registered in the objects to translate function.

**Comment by macumber** [comment]
I think we need to do better at documenting the translator, not sure if any of this stuff needs to be documented?  I was also thinking we should have a case statement for each IDD object type where we explicitly say "// this object will be translated with AirLoop" or whatever

**Comment by macumber** [comment]
The ones I've highlighted are just plain being missed, you could add them to your osm in a measure and they would simply not show up in the idf

**Comment by macumber** [comment]
For the Utility objects, my feeling is we should remove them from the model.  Then when we get to utility rates we can add those back in.  Thoughts on that?

**Comment by kbenne** [comment]
Lets talk about this one on Monday.

**Comment by macumber** [comment]
Cool, for 1.9.0 I think I will just issue a warning for UtilityBill objects

**Comment by macumber** [comment]
@DavidGoldwasser maybe we should issue a warning for RunPeriodControlSpecialDays not being translated

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator.cpp#L257

**Comment by macumber** [comment]
@kbenne what are you thoughts on all this?

**Comment by kbenne** [comment]
@macumber wanna give me a call?

**Comment by macumber** [comment]
To recap the call @kbenne and I just had:

* ForwardTranslator::translateModelObject is not particularly useful and might be deprecated
* We are in favor of registering every ModelObject with a translate function, ideally in a way that is testable
* Simulation tests should be merged with the proposed measure testing framework

**Comment by macumber** [comment]
And we are ok to merge this

**Comment by asparke2** [comment]
It appears that this issue is back based on [this unmethours post from Tiejun Wu](https://unmethours.com/question/15137/cannot-enable-co2-concentration-calculation-in-openstudio/).  I confirmed the issue in 1.10.0.  The OS:ZoneAirContaminantBalance object shows up in the .osm, but not in the exported IDF.  Also, for this particular object, the string input field is no go; should really be a dropdown.

**Comment by asparke2** [comment]
@kbenne @macumber FYI

**Comment by macumber** [comment]
Let's reopen a new issue for that
