### ISSUE TITLE
Ubuntu 15.04 error: 'LoadError: libQt5Sensors.so.5: cannot open shared object file'

### ISSUE THREAD

**Issue by germolinal** [NREL/OpenStudio#1731]
The title pretty much summarizes my issue. When I write the following in the Ruby Console (and/or in a script)

```
require 'openstudio'
```

I get the following error 

```
LoadError: libQt5Sensors.so.5: cannot open shared object file: No such file or directory - /usr/local/lib/openstudio-1.8.1/ruby/2.0/openstudioutilitiescore.so
```

I am not sure if this is an OpenStudio error, or maybe I need to install something else. So I decided to post it here.

I have recently upgraded to Ubuntu 15.04, which I regret now, because my scripts used to work wonderfully.

If you could help me, I would appreciate it.

THANKS

**Comment by jmarrec** [comment]
I have no problem in 16.04 currently.
