### ISSUE TITLE
Weather file location 1.8.1

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1734]
The `Change Weather File` and `Import From DDY` buttons do not link to the wx file location in the Preferences menu. Tested for both local and network paths.

FYI @evanweaver

**Comment by MatthewSteen** [comment]
Fixed by closing and reopening OS. This change was immediate in previous versions.

**Comment by evanweaver** [comment]
Hey @MatthewSteen, did you also run "scan for tools"?  Also, is wx file location like a default file location?

**Comment by MatthewSteen** [comment]
I hadn't yet, but just did. Even though the wx path in `Show Tools` now has the default location...

C:/Program Files/OpenStudio 1.8.1/share/openstudio/EnergyPlusV8-3-0/WeatherData

...when I use the `Set Weather File` button it points at the network path I had set during a previous session.

**Comment by macumber** [comment]
The RunManager tools dialog is going to be deprecated in the next year so I think we should just close this as won't fix
