### ISSUE TITLE
PAT shows EnergyPlus Error but keeps running

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1736]
I think we have seen this before. EnergyPlus has an error, but it isn't a fatal error. As a result in PAT it looks like the datapoint failed, but when you go to the results page it ran just fine.

cc: @evanweaver @macumber @kbenne 

@kbenne the specific EnergyPlus error looks like it is about an air loop that has an outdoor air object, but no thermal zones on the air loop have any outdoor air requirements. There was a time the modeler had to add in a dummy outdoor air object with value of 0 or remove the outdoor air object from the air loop to get the simulation to run, but I thought we addressed that now in forward translation? Maybe this error has always shown and I just see it now because of PAT. In OS app there is no indication of a problem (of course I'm not manually digging in the eplusout.err file by hand). 

Screenshots for reference.

![7-23-2015 9-18-11 am](https://cloud.githubusercontent.com/assets/4857055/8854526/865f45cc-311d-11e5-9972-47713716324b.png)

![7-23-2015 9-18-22 am](https://cloud.githubusercontent.com/assets/4857055/8854518/7d28e6c0-311d-11e5-9a9d-b413b65c4c7e.png)

**Comment by DavidGoldwasser** [comment]
Strange, I hit this again today, but in this case the results tab looks empty. As a result I increased the severity. This is with develop build (maybe a week old?)

![8-11-2015 11-43-56 am](https://cloud.githubusercontent.com/assets/4857055/9205540/fed71e7e-401f-11e5-8475-3a99494056be.png)

![Uploading 8-11-2015 11-45-50 AM.png…]()

![Uploading 8-11-2015 11-44-09 AM.png…]()

**Comment by macumber** [comment]
Does the EnergyPlus simulation complete?  Could this be related to this E+ issue, https://github.com/NREL/EnergyPlus/issues/4838 ?

**Comment by macumber** [comment]
Also, @DavidGoldwasser your second set of screenshots seem to be indicating a different issue than the first set of screenshots.  In the first you have results, in the second you do not.

**Comment by DavidGoldwasser** [comment]
@macumber I do have results in the second one, but I guess this the second issue is really user error. The second PAT project I didn't have a working baseline model. That is why all of the results are blank. 

Also we currently don't stop PAT for E+ error unless it is fatal error, so that makes me think the whole issue here is invalid.
