### ISSUE TITLE
Cant get runner.lastEpwFilePath to work on OpenStudio server

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1737]
Testing AEDG slab/basement measure using OpenStudio server in preparation for custom version for Danny Studer, and I haven't gotten it to run yet. Runs fine locally in OS app and PAT.
https://www.pivotaltracker.com/story/show/99644162

I know there are already a few epw related issues filed, sorry if this is a duplicate but I couldn't find one that looked like it matched this specific issue.
Here is the problematic code in an E+ measure

``` ruby
    # check for epw file
    lastEpwFilePath = nil
    if not runner.lastEpwFilePath.empty?
      lastEpwFilePath = runner.lastEpwFilePath.get
      runner.registerInfo("Using lastEpwFilePath specified by runner")
    elsif File.exists?("#{File.dirname(__FILE__)}/in.epw")
      lastEpwFilePath = OpenStudio::Path.new("#{File.dirname(__FILE__)}/in.epw")
      runner.registerInfo("Using EpwFile found in directory")
    else
      runner.registerError("Cannot locate EPW file to use for calculating ground temperatures")
      return false
    end
```

It is used here 

``` ruby
      co = OpenStudio::Runmanager::ConfigOptions.new(true)
      co.findTools(false, true, false, true)
      wf = OpenStudio::Runmanager::Workflow.new("expandobjects->slab")
      wf.add(co.getTools())
      puts "slab: runDir: #{runDir}, idfPath: #{idfPath}, lastEpwFilePath: #{lastEpwFilePath}"
      job = wf.create(runDir, idfPath, lastEpwFilePath)
```

**Comment by DavidGoldwasser** [comment]
@macumber I'm hitting this on the BEopt measures as well. I got a running PAT project, but can't get a spreadsheet to run. They access the weather file in another way to come up with proper constructions.

**Comment by macumber** [comment]
I'm not sure if runner.lastEpwFilePath is implemented on the server, @nllong would know

**Comment by brianlball** [comment]
if its a path issue, you might need to do something like this:

ems_path = '../AdvancedRTUControls/ems_advanced_rtu_controls.ems'
    json_path = '../AdvancedRTUControls/ems_results.json'
    if File.exist? ems_path
      ems_string = File.read(ems_path)
      if File.exist? json_path
        json = JSON.parse(File.read(json_path))
      end
    else
      ems_path2 = Dir.glob('../../**/ems_advanced_rtu_controls.ems')
      ems_path1 = ems_path2[0]
      json_path2 = Dir.glob('../../**/ems_results.json')
      json_path1 = json_path2[0]

**Comment by DavidGoldwasser** [comment]
I'll follow up with Nick. Also digging into the BEopt measure code, they seem to have made their own "WeatherProcess". Don't know if you know any of the history on that? Screenshot below walks through it. The BEopt is not time critical and we can wait to discuss until you get back.

![7-23-2015 11-22-47 am](https://cloud.githubusercontent.com/assets/4857055/8857314/2269eff2-312e-11e5-8db5-0c32e83368e6.png)

**Comment by DavidGoldwasser** [comment]
@nllong @henryHorsey This should be moved to the workflow gem repo. Doesn't affect OpenStudio code.

**Comment by macumber** [comment]
@henryHorsey this is fixed right?  Can we close it?

**Comment by macumber** [comment]
Is this valid @DavidGoldwasser @rHorsey ?

**Comment by jmarrec** [comment]
Is this valid @DavidGoldwasser @rHorsey ?
