### ISSUE TITLE
Web asset path in Calibration Report is hard-coded

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1738]
In the report.html file, the web asset is hard-coded, and it should not be.  This results in the report not ever rendering when offline.  This could be fixed by using the code from the Standard Report to populate this path.

```
<script type="text/javascript" src="file:///C:/openstudio_git/OpenStudio/openstudiocore/resources/web_assets/jquery.min.js"></script>
```

[Here is a link to the file](https://github.com/NREL/OpenStudio/blob/bf5f68c76b79a69deaff25aae05cbb8a798b31b1/openstudiocore/src/pat_app/Measures/CalibrationReports/resources/report.html.in#L59)

**Comment by macumber** [comment]
@asparke2 @DavidGoldwasser my suggestion would be to provide a method to the installer path for any web assets we are shipping, the measure can call that.  Are we shipping any web libraries?  Should we be?
