### ISSUE TITLE
User can lockup Plugin by grouping and then exploding a group of surfaces in a space (Bugzilla #875)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#174]
On 2012-08-31 10:33:35, @DavidGoldwasser wrote:

> Don't see an error when you first group the, but see this error when it is exploded. CPU is working hard on something. But oddly it doesn't always lockup, sometimes I just get there app but can keep working. But selecting the exploded surfaces doesn't show the surface in the inspector, even though it appears to be there. If you pick it in the inspector it does however pick it in SketchUp.
> 
> Users can really get things out of sync here if they aren't watching the ruby console (which nobody does).
> 
> Error: #<RuntimeError: entity.entityID == old_entity.entityID is true>
> C:/Program Files (x86)/OpenStudio 0.8.4/Ruby/openstudio/sketchup_plugin/lib/interfaces/DrawingUtils.rb:121:in `swapped_face_on_divide?'
> C:/Program Files (x86)/OpenStudio 0.8.4/Ruby/openstudio/sketchup_plugin/lib/observers/SurfaceGroupEntitiesObserver.rb:134:in `onElementAdded'
> C:/Program Files (x86)/OpenStudio 0.8.4/Ruby/openstudio/sketchup_plugin/lib/PluginManager.rb:199:in `call'
> C:/Program Files (x86)/OpenStudio 0.8.4/Ruby/openstudio/sketchup_plugin/lib/PluginManager.rb:199:in `process_events'
> C:/Program Files (x86)/OpenStudio 0.8.4/Ruby/openstudio/sketchup_plugin/lib/PluginManager.rb:192:in `each'
> C:/Program Files (x86)/OpenStudio 0.8.4/Ruby/openstudio/sketchup_plugin/lib/PluginManager.rb:192:in `process_events'
> C:/Program Files (x86)/OpenStudio 0.8.4/Ruby/openstudio/sketchup_plugin/lib/PluginManager.rb:244:in `start_event_processing'

On 2012-09-07 09:05:51, @DavidGoldwasser wrote:

> Absolutely don't want to touch this for 0.9.0

Keywords: CornerCase, Crash, SyncWithSU

**Comment by macumber** [comment]
Don't do this
