### ISSUE TITLE
detached drop downs 

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1740]
To reproduce in 1.8.1:

1. Edit an object and click on a drop down field
2. Move the cursor off the drop down
3. Scroll away from the drop down

Tested in the Thermal Zones and HVAC Systems tabs for PTACs, AirLoopHVAC, and PlantLoop objects.

![openstudio_issue1740](https://cloud.githubusercontent.com/assets/8397034/8885587/6c57a078-321e-11e5-8359-c5b5bb01eeb5.png)

**Comment by macumber** [comment]
@MatthewSteen what problems does this end up causing?  Can you not interact with other parts of the GUI?  Is there a model corruption problem?

**Comment by MatthewSteen** [comment]
@macumber just aesthetics. I was still able to make a selection. The image above is from a fresh Untitled.osm so no corruption problem.
