### ISSUE TITLE
OpenStudio 1.8.0 does not work with installed E+

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1746]
Users have reported they have to delete the copy installed with OS and install E+ 8.3 on their own:

https://unmethours.com/question/9286/openstudio-180-unable-to-run-energyplus-83/

**Comment by macumber** [comment]
Might be related to https://github.com/NREL/OpenStudio/issues/1577 and https://github.com/NREL/OpenStudio/issues/1496

**Comment by macumber** [comment]
@axelstudios @evanweaver it sounds like this issue was actually because we were bundling 64 bit EnergyPlus with out 32 bit builds.  Users on 32 bit platforms could not use this.  Has this issue been fixed?  Do we make 64bit and 32bit OpenStudio builds on the same machine? Do we have any way to test this?  Do we have a 32 bit VM we can use?

**Comment by macumber** [comment]
Duplicate of https://github.com/NREL/OpenStudio/issues/1496

**Comment by macumber** [comment]
@axelstudios I found out that the cheapest version of Windows 7 (Starter) is 32 bit only, this might be why there are people using 32 bit Windows 7 machines?

**Comment by evanweaver** [comment]
We'll work on a solution for the next iteration build.

**Comment by macumber** [comment]
Just confirmed that this is still an issue with the current posted 1.8.4 32 bit builds

**Comment by macumber** [comment]
Also there is something fishy going on in the Radiance install with the 32 bit build.  The version of Radiance installed with 32 bit OS is 32 bit.  However, there are 64 bit Qt dlls in the Radiance package.  Aside from the horror that we are distributing Qt twice in our installer (!) they are 64 bit Qt dlls in the 32 bit Radiance package.

**Comment by macumber** [comment]
Probably the only safe way to avoid this problem is to build all of our 32 bit packages on a 32 bit machine.  That way there are no 64 bit binaries floating around.

**Comment by evanweaver** [comment]
Or roll with @rpg777's 32 bit solution.

**Comment by macumber** [comment]
What is @rpg777 's 32 bit solution?

**Comment by rpg777** [comment]
yeah, what's all that, then?

**Comment by rpg777** [comment]
OK I remade a Win32 Radiance package -- following my copious AlexNotes for making 32 on a 64 --  if anyone wants to check it for fish.

**Comment by axelstudios** [comment]
Makes sense.  We're definitely bundling 64-bit EnergyPlus with 32-bit OpenStudio packages.  It really sucks that both architectures of EnergyPlus install to the same location.  My recommendation would be to zip up the separate EnergyPlus installs, put them on S3, and add a step to the package builds that downloads the exact one that's necessary for packaging.

**Comment by rpg777** [comment]
=/

**Comment by macumber** [comment]
We also need to ensure that we only package 32 bit Ruby in the 32 bit packages

**Comment by axelstudios** [comment]
Ruby is already taken care of: https://github.com/NREL/OpenStudio/blob/develop/CMakeLists.txt#L544
