### ISSUE TITLE
SetpointManager:Scheduled crash

### ISSUE THREAD

**Issue by mbadams5** [NREL/OpenStudio#1747]
This crash was discussed on [unmethours](https://unmethours.com/question/9815/os-180-crashes-over-incomplete-setpoint-manager-specification/).

This happens when updating an OSM from OS 1.4.0 to OS 1.8.0. For some reason, a blank controlVariable was allowed as a valid option in OS 1.4.0. Looking back at the code, nothing stands out that would allow this. 

OS 1.8.0 does not allow this anymore and requires a (valid) controlVariable. This is causing a crash when loading the translated OSM.

Workaround: Manually edit OSM and put "Temperature" in for Control Variable. This should allow the updated OSM to load into the OS App.

**Comment by kbenne** [comment]
@mbadams5 your move.. What do you think about my solution?
