### ISSUE TITLE
Schedule Sets sub tab "My Model" doesn't populate at first

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1757]
This first screenshot shows what I see when I open a model and click on the "Schedules Tab"
![8-7-2015 9-11-38 am](https://cloud.githubusercontent.com/assets/4857055/9139063/08679506-3ce5-11e5-9d1f-232c88c105f3.png)

Clicking on other schedules sets still doesn't populate "My Model" with schedules from my model.. The "Library" tab is fine, but switching to that and back to "My Model" doesn't' fix the issue.

I have to go into the "Schedules" sub-tab and then back to "Schedule Sets" and then it is populated as shown below.
![8-7-2015 9-13-11 am](https://cloud.githubusercontent.com/assets/4857055/9139096/3818f178-3ce5-11e5-8844-6db6a4ac7169.png)
I'm using a recent develop build. Seems to happen with any model.

Some additional notes:
1. Another way to get it to pouplate seems to be to switich out of the schedules tab and then back in it. Sometimes when it comes back it has switched it to the "Schedules" sub-tab on its own instead of showing "Schedule Sets" the left most tab. In this case when I then switch to "Schedule Sets" it is populated.
2. In most cases when after fixing this when first launching, if I go to another tab and then back to Schedules, I have to repeat the task of going ot the schedules sub-tab and then back to the schedule sets sub-tab. So this isn't just something that has to be done when I first open the model. 
3. I don't see any behavior like this in the Constructions tab.

@kbenne or @evanweaver do one of you want this, While not critical it is a bit odd, and hopefully is an easy low risk fix. Not sure when it snuck in?

**Comment by DavidGoldwasser** [comment]
Ok, so didn't happen in 1.8.0. My guess is that it is tied to the removal of the "Year Settings" tab which used to be the landing sub-tab when you went to "Schedules" tab. There seems to be some glitches in which tab is the landing tab now, and making sure that that tab renders.

**Comment by evanweaver** [comment]
Fixed via https://www.pivotaltracker.com/n/projects/134010/stories/101285900
