### ISSUE TITLE
Hard Crash Opening 1.5.3 CBECC-Com OSM in 1.8.3

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1767]
![image](https://cloud.githubusercontent.com/assets/8397034/9278517/93139c48-426e-11e5-88b4-4606040fe604.png)

![image](https://cloud.githubusercontent.com/assets/8397034/9278523/97523fe4-426e-11e5-9305-16843e58afb6.png)

**Comment by evanweaver** [comment]
@MatthewSteen I'm unsure of this file's location, could you help out? Thanks

**Comment by MatthewSteen** [comment]
@evanweaver I don't have access to the file repo, so I just emailed it to you.

**Comment by MatthewSteen** [comment]
Emailed. This one has a sorted history...

IES VE > CBECC-Com v3 XML > opened and run in CBECC-Com v3c > OS 1.5.3 > OS 1.8.3

**Comment by MatthewSteen** [comment]
@evanweaver more info...

![image](https://cloud.githubusercontent.com/assets/8397034/9284409/cc160b0a-4298-11e5-8334-e723f12f4a3d.png)

![image](https://cloud.githubusercontent.com/assets/8397034/9284411/d37f7ef8-4298-11e5-8d0a-f0633dbb6fde.png)

**Comment by evanweaver** [comment]
Hey @MatthewSteen, you sent me 14095_Kilroy_T24 - ap.osm.  Is this the correct file?  I opened and navigated it with no problems.

![image](https://cloud.githubusercontent.com/assets/4974134/9285994/07ec0c5a-42a9-11e5-93dd-79adb4e49945.png)

**Comment by MatthewSteen** [comment]
Hmmm, I just did an uninstall/reinstall of the Win64 version of 1.8.3 with no change. Went back to 1.8.2 and it opens so it seems to be a 1.8.3 issue at least on my machine.

**Comment by evanweaver** [comment]
Thanks @MatthewSteen.  Initially I looked at this in debug, once I tried a release build it crashed.

**Comment by macumber** [comment]
Possibly require code in an assert statement is not getting executed in Release?

**Comment by evanweaver** [comment]
Or something like #if _DEBUG

**Comment by evanweaver** [comment]
Fixed with commit 3afb112b5ec80e791583c51be16121405eaff99b: Do not access uninitialized objects' data members.

**Comment by evanweaver** [comment]
@MatthewSteen, this fix will be available this Friday.

**Comment by axelstudios** [comment]
Fixed in 3afb112b5ec80e791583c51be16121405eaff99b
