### ISSUE TITLE
Facility tab grid view crash

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1770]
@macumber determined that this isn't due to corrupt or orphaned sizing:zones and has a different call stack/  He is going to upload the model to the OpenStudio-files repo.  The issue doesn't seem to happen with 1.8.0, just 1.8.3.

To reproduce:
1. Open the model
2. Click the facility tab
3. Crash

**Comment by macumber** [comment]
Appears to be column 3 of the Shading Surface Group grid:

    msvcr120d.dll!_wassert(const wchar_t * expr, const wchar_t * filename, unsigned int lineno) Line 369	C
    openstudio_lib.dll!`openstudio::ConceptProxy::cast<openstudio::model::ModelObject>'::`1'::catch$1() Line 296	C++
    openstudio_lib.dll!openstudio::ConceptProxy::cast<openstudio::model::ModelObject>() Line 287	C++
    openstudio_lib.dll!openstudio::OSGridController::widgetAt(int row, int column) Line 1237	C++
    openstudio_lib.dll!openstudio::OSGridView::addWidget(int row, int column) Line 406	C++
    openstudio_lib.dll!openstudio::OSGridView::refreshAll() Line 366	C++
    openstudio_lib.dll!openstudio::OSGridView::doRefresh() Line 348	C++

**Comment by evanweaver** [comment]
Fixed.  See https://www.pivotaltracker.com/n/projects/134010/stories/101543198
