### ISSUE TITLE
Can't add schedule to ZoneControlHumidistat

### ISSUE THREAD

**Issue by lincolnharmer** [NREL/OpenStudio#1772]
Schedules can't be add to this object in the GUI or via measure rendering it useless. This may have something to do with the fact that OpenStudio doesn't support schedules with unit type 'Humidity'

**Comment by mbadams5** [comment]
@lincolnharmer You need to make sure the schedule has a ScheduleTypeLimits that has Units of "Percent". 

In the GUI you do this when defining a new schedule...
![screen shot 2015-08-16 at 9 50 28 am](https://cloud.githubusercontent.com/assets/2001544/9293572/4ee20c58-43fe-11e5-81d6-c245dde5cec5.png)

When using ZoneControlHumidistat through a measure you need to build the ScheduleTypeLimits yourself. Here is example code to add a ScheduleRuleset to ZoneControlHumidistat.
```ruby
m = OpenStudio::Model::Model.new

percent_type_limits = OpenStudio::Model::ScheduleTypeLimits.new( m )
percent_type_limits.setLowerLimitValue( 0.0 )
percent_type_limits.setUpperLimitValue( 100.0 )
percent_type_limits.setNumericType( "Continuous" )
percent_type_limits.setUnitType( "Percent" )

sch_ruleset = OpenStudio::Model::ScheduleRuleset.new( m, 50 )
sch_ruleset.setScheduleTypeLimits( percent_type_limits )

zone_control = OpenStudio::Model::ZoneControlHumidistat.new( m )
zone_control.setHumidifyingRelativeHumiditySetpointSchedule( sch_ruleset )
zone_control.setDehumidifyingRelativeHumiditySetpointSchedule( sch_ruleset )
```

**Comment by lincolnharmer** [comment]
@mbadams5 That does the trick. Thanks!
