### ISSUE TITLE
Array bounds error with Controller:MechanicalVentilation and no DesignSpecification:OutdoorAir objects

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#1775]
Best way to describe this is to go to the corresponding E+ issue. OS should not be producing these mal formed idf files. The only reason it is an E+ bug is because E+ is crashing. 

https://github.com/NREL/EnergyPlus/issues/5112#issuecomment-131943130

**Comment by jmarrec** [comment]
OpenStudio still produces the "mal formed" Controller:MechanicalVentilation but E+ no longer crashes on that and issues a warning. As a result I'm not sure whether it's worth addressing or not @kbenne. 

In particular, I can't really see what behavior you'd want to put in place. The fact that E+ gives me a warning is actually a good thing, and probably better than if OpenStudio was the one issuing a warning while removing the extensible group `[Zone, DSOA, Design Specification Zone Air Distribution]` for zones without a DSOA. 

In the current state of OS App, the OS generated warnings are hard to find and easy to overlook. The E+ warning is a more sure thing to me.

```
Controller:MechanicalVentilation,
  CAVwReheat Controller Mechanical Ventilation, !- Name
  Always On Discrete,                     !- Availability Schedule Name
  No,                                     !- Demand Controlled Ventilation
  ZoneSum,                                !- System Outdoor Air Method
  ,                                       !- Zone Maximum Outdoor Air Fraction {dimensionless}
  Zone1,                                  !- Zone Name 1
  ,                                       !- Design Specification Outdoor Air Object Name 1
  Zone1 Design Spec Zone Air Dist,        !- Design Specification Zone Air Distribution Object Name 1
  Zone2,                                  !- Zone Name 2
  ,                                       !- Design Specification Outdoor Air Object Name 2
  Zone2 Design Spec Zone Air Dist;        !- Design Specification Zone Air Distribution Object Name 2
```
