### ISSUE TITLE
Incorrect SI to IP unit conversion in sizing:zone gridview

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1778]
See [this unmet hours question](https://unmethours.com/question/10384/minimum-air-flow-per-zone-floor-area/). The heating and cooling minimum airflow per zone floor area columns in the Thermal Zones grid view do not convert correctly to IP:

  `m^3 of air/s*m^2 of zone floor area`

to 

  `cfm air/min* ft^2 zone floor area`

I'm guessing this is because the units represent different quantities.  If you look at this same field in the inspector, it shows is showing the wrong units, but seems to be doing the conversion correctly.  You can see the the inspector behavior in the HVAC tab once you add a thermal zone to the loop and look in the sizing:zone object.

It would be good to check if other columns in the gridviews use this same conversion.

**Comment by evanweaver** [comment]
This bug will be fixed via https://www.pivotaltracker.com/n/projects/134010/stories/101286352 and is partially represented by https://github.com/NREL/OpenStudio/issues/1695.

**Comment by evanweaver** [comment]
Bug fix accepted in Pivotal Aug 24.
