### ISSUE TITLE
Can't Delete the First OS:WaterHeater:Stratified object Added to Plant Loop Using Measure

### ISSUE THREAD

**Issue by dstuder** [NREL/OpenStudio#1779]
When viewing a DHW plant loop in the HVAC Systems tab, where an OS:WaterHeater:Stratified object has been added via measure, there is no way to delete the OS:WaterHeater:Stratified object. Subsequent tanks (mixed or stratified) added via the GUI are able to be deleted.

**Comment by dstuder** [comment]
@kbenne Is this just a consequence of the manner in which the measure adds the object?

**Comment by kbenne** [comment]
No. this is because the stratified tank is (I assume in your case) is inside a hpwh. The tank has a method ::containingHVACComponent that signals to the GUI that it is contained by something else and therefore don't allow it to be removed. We are going to have to do some work to iron this all out in the UI.

**Comment by dstuder** [comment]
Ok, thanks. Just wanted to document the behavior since it seemed unusual.

**Comment by kbenne** [comment]
@dstuder can we close this one too? I admit it would be nice if the gui gave you some feedback about why you can't remove, but I don't think that is on the table at this point. If we do it here, it needs to be applied consistently to the many other objects that encounter this situation. 

From the API there is a method WaterToWaterComponent::removePlantLoop that will let you remove the object from the plant without completely removing it from the model.  In the GUI you can use the HPWH inspector to remove from plant.
