### ISSUE TITLE
HVAC Tab - Fields with Autosize/Hardsize are right justified (Bugzilla #892)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#178]
On 2012-09-09 21:08:40, @DavidGoldwasser wrote:

> This results in seeing a lot of decimals, and not seeing the left most part of your value (left of the decimal).

On 2012-12-12 10:50:14, @DavidGoldwasser wrote:

> Bug 926 has similar issue with material for specific heat, and Dan noticed this on multiplier field of loads in facility tab. May occur in other places as well.

**Comment by jmarrec** [comment]
cannot reproduce in OS 2.2.1
