### ISSUE TITLE
WaterHeating:AirToWaterHeatPump Rated Condenser Inlet Water Temperature Forcing Random Value

### ISSUE THREAD

**Issue by dstuder** [NREL/OpenStudio#1780]
When attempting to input a value for the "Rated Condenser Inlet Water Temperature" in the "WaterHeating:AirToWaterHeatPump" object, OpenStudio is forcing it to 55.72 C (the EnergyPlus default is 57.5 C). While OpenStudio appears to take the value when in Inspector, navigating away and coming back shows that the value did not persist. Hitting "enter" does not change the behavior.

@kbenne So far this is the only field I've seen this occur in. Because of that I suspect that this may be a one-off issue related to the recent HPWH addition.

**Comment by DavidGoldwasser** [comment]
I thought this might be related to be issue #656, but if that were the case then "57.5" you are typing would have to be an invalid EnergyPlus value. @kbenne, @asparke2 or @macumber any ideas?

**Comment by kbenne** [comment]
I can't reproduce this. I know that the inspector can be twitchy. The "commit action" doesn't happen until you press return or leave focus from the input field. Leaving focus normally happens however you leave the IG, but like I said twitchy. Can you double check that this is actually a thing?

**Comment by dstuder** [comment]
I can no longer reproduce this. Guess we can close it.
