### ISSUE TITLE
Crash When Deleting HPWH

### ISSUE THREAD

**Issue by dstuder** [NREL/OpenStudio#1784]
When deleting a HPWH system (by deleting the HPWH from the Zone Equipment list in the "Thermal Zones" tab by clicking the "X" icon in Inspector), OpenStudio will crash and exit the program if you try to navigate to the hot water plant loop on the "HVAC Systems" tab (the loop that previously contained the WaterHeater:Mixed or WaterHeater:Stratified object that was associated with the HPWH).

OpenStudio will also crash when trying to delete the HPWH from the Zone Equipment list in the "Thermal Zones" tab if you have navigated directly from the hot water plant loop on the "HVAC Systems" tab to the "Thermal Zones" tab.

**Comment by dstuder** [comment]
@kbenne OpenStudio also crashes after deleting the HPWH from the Zone Equipment list and then navigating to the "Measures" tab.

**Comment by kbenne** [comment]
@DavidGoldwasser and @dstuder can you two collectively verify that this is the right fix?

**Comment by kbenne** [comment]
ping @dstuder
