### ISSUE TITLE
Orphaned connections when deleting Air-to-Air HX from outdoor air system with other outdoor air equipment

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#1787]
Deleting the Air-to-Air HX from this configuration in the GUI will result in two orphaned connection objects:
![outdoorairequip](https://cloud.githubusercontent.com/assets/10799524/9394252/b35550c0-4744-11e5-9a54-7be812c4f451.png)

![connection](https://cloud.githubusercontent.com/assets/10799524/9394383/6dcf4604-4745-11e5-8963-654d7f42e5ca.png)

Causes EnergyPlus simulation failure at start of annual simulation. Workaround: delete these objects in a text editor. 
Tested in OS v1.8.0 and v1.8.2, Windows 64-bit

**Comment by DavidGoldwasser** [comment]
@kbenne and @asparke2 just wanted you to be familiar with this to look at for 1.9.0.

**Comment by kbenne** [comment]
@eringold if i send you an installer can you verify this fix?

**Comment by eringold** [comment]
Yes sir.

**Comment by kbenne** [comment]
@eringold take a look and see what you think. https://drive.google.com/file/d/0B6AYyX2ggNyBLXZHdFBHQmhMZFE/view?usp=sharing

**Comment by eringold** [comment]
@kbenne  With that build I was able to delete the HX from the Outdoor Air System and run the simulation without error. Thanks!

**Comment by kbenne** [comment]
Appreciate the testing.
