### ISSUE TITLE
Any reason not to hide "Apply to Selected" for Outside Boundary Condition Object 

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1795]
I can't think of a use case to batch change the outside condition object on either the surface or sub-surface sub-tabs. They should always be unique or empty. In the case of being empty changing the "Outside Boundary Condition" from "Surface" to something else will clear out the boundary objects for both surfaces and sub-surfaces.

@macumber, @evanweaver and @asparke2 any thoughts on this?

Another minor thing. You can't choose "Surface" from the pulldown list (which is correct). You can only set it to surface by picking an outside boundary object, then it changes to "Surface" automatically. This is a point of confusion in the plugin, people thing it is broken because they can't set surface. Wondering if we should hide "Surface" from the pick list (which may be problematic) or if we could pop up some alert if they try to set to "Surface" that says "Please assign an Outside Boundary Condition Object" to change the boundary condition to "Surface".

**Comment by evanweaver** [comment]
@asparke2, I'd like a quorum of at least 2.  Do you agree?

**Comment by asparke2** [comment]
I agree with David, I can't think of a situation where you'd need to bulk-apply an outside boundary condition object to multiple surfaces or subsurfaces

**Comment by evanweaver** [comment]
To be complete, this appears in SpacesSurfacesGridView, SpacesSubtabGridView, SpacesSubsurfacesGridView.  I am assuming that all of these instances should have the Apply To button hidden.  Correct?

**Comment by evanweaver** [comment]
Fixed via https://www.pivotaltracker.com/n/projects/134010/stories/101795128

**Comment by macumber** [comment]
@evanweaver can you close this if it is fixed?

**Comment by evanweaver** [comment]
@DavidGoldwasser, what say you?
