### ISSUE TITLE
"Shading" Sub-tab on building tab, pull down list shouldn't show "Space" as option

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1797]
Space shading groups are shown in the space tab under the appropriate space. This tab looks like it is intended only for building and site shading. The pulldown list under the "Type" menu shows Building, Site, and Space. It doesn't let you choose space, which is correct, but it should be hidden.

By the way, interesting that this sub-tab lets you make a surface group with the green "+" button and also has a drop zone. I'm wondering if that was a mistake? We don't have that enabled for any other kind of surface group (spaces, space shading, interior partitions). We also don't let you delete the groups once they have been made.

The story tab and exterior equipment tab (also on building) does have "+" enabled and it should, I'm wondering if "Shading was just copied from this.

**Comment by DavidGoldwasser** [comment]
As an update with screenshot. I noticed it will let me change a shading surface group fro "Space" to "Building" or "Site' and then it doesn't let you change it back to "Space". 

![9-3-2015 4-18-26 pm](https://cloud.githubusercontent.com/assets/4857055/9672432/d5300104-5257-11e5-97db-0b6fbc5e36ea.png)

**Comment by jmarrec** [comment]
OS 2.2.1 I don't see "Space" as an option in the right column when on the Shading Tab. @DavidGoldwasser

**Comment by macumber** [comment]
I think the answer is to create a new function that only returns valid keys for this tab.  Actually might even be easier that that: https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/openstudio_lib/FacilityShadingGridView.cpp#L153
