### ISSUE TITLE
HeatPump:WaterHeater Inlet Air Zone Name Not Exposed

### ISSUE THREAD

**Issue by dstuder** [NREL/OpenStudio#1801]
@kbenne I am writing a measure to modify whether the WaterHeater:HeatPump is ducted or uses zone air as the inlet to the evaporator, but realized when trying to reference the "Inlet Air Zone Name" parameter that it doesn't look like that specific parameter was wrapped/accessible. Am I missing something?

**Comment by kbenne** [comment]
I intend to give the HPWH a going over during this bug fix period. I know it certainly needs it.  But off the cuff, I think this one might not actually be an issue. The HPWH is zone equipment, meaning it has the ::addToThermalZone method like all other ZoneHVACComponents. Use this method to apply the water heater to a zone and inlet air zone name should be taken care of for you. OpenStudio is trying to weed out redundancies.

**Comment by dstuder** [comment]
I worked with @asparke2 to include this into a measure that @brianlball wrote to originally modify the zone to which the WaterHeater:Stratified object was assigned to. The measure works like a charm, in that the HeatPump:WaterHeater object now displays in the proper zone in the "Thermal Zones" tab. However, for some reason, the HeatPump:WaterHeater never actually turns on in the simulation, and the backup resistance heaters act as the primary heating source.

The HeatPump:WaterHeater object was observed working properly prior to the move. Moving it back to the original zone does not fix the issue (I was wondering if it was some sort of lockout due to zone temps, but it doesn't appear to be). Earlier this morning I had observed the same behavior when I had attempted to move the HeatPump:WaterHeater object by hand in a text editor. I had assumed I must have missed something, but now I'm thinking this is a deeper issue. Any thoughts?

**Comment by dstuder** [comment]
In an interesting addendum to this, if I open the model, make a HeatPump:WaterHeater zone assignment (using the drop down list of zone options that is part of the measure), and run the model, I encounter no issues. But if I then go back to the "Measures" tab and attempt to assign the HeatPump:WaterHeater to a new zone (by again selecting from the drop down list), I get an "OpenStudio has stopped working" error message and I am forced to close the program.

**Comment by dstuder** [comment]
I'm still working on this, but this may actually be an EnergyPlus and not OpenStudio issue (except the crash thing). I'm running into interesting behavior regarding control of the supplemental heaters. I'll investigate more tomorrow.

**Comment by kbenne** [comment]
@dstuder did you ever get to the bottom of this? One thought is that the HPWH does not have to be assigned to a zone from the E+ perspective. As I recall the ambient conditions can come from a variety of sources such as outdoor conditions, zone, or a schedule.

**Comment by dstuder** [comment]
@kbenne I did not get to the bottom of it, but it now appears to be working. I cannot replicate the OS crash, and the HPWH behavior is as expected. Closing OS and reopening the file seemed to fix the issue.

**Comment by kbenne** [comment]
@dstuder can we close this?

**Comment by dstuder** [comment]
I don't think so. I was just able to replicate the OpenStudio has stopped working error.

**Comment by kbenne** [comment]
oh this part...

"In an interesting addendum to this, if I open the model, make a WaterHeater:HeatPump zone assignment (using the drop down list of zone options that is part of the measure), and run the model, I encounter no issues. But if I then go back to the "Measures" tab and attempt to assign the WaterHeater:HeatPump to a new zone (by again selecting from the drop down list), I get an "OpenStudio has stopped working" error message and I am forced to close the program."

I forgot about that part. I'll take a look.

**Comment by kbenne** [comment]
@dstuder can you send me the measure and possibly the seed model? This is possibly unrelated to HPWH implementation.

**Comment by macumber** [comment]
@kbenne can you tag this with 1.10.0 if you want to include it?

**Comment by kbenne** [comment]
ping @dstuder 

Measure?

**Comment by kbenne** [comment]
@dstuder  I think this is related. https://github.com/NREL/OpenStudio/commit/e71f36fe299d976f236723f94718125f04826746 I noticed it while working on the wrapped condenser variation of HPWH.

**Comment by dstuder** [comment]
@kbenne Nice. I plan to spin this project back up as soon as the wrapped condenser stuff is live. I'll let you know if I run into any more trouble.

**Comment by macumber** [comment]
This ticket was closed in pivotal, is it still valid or can it be closed?

**Comment by evanweaver** [comment]
@dstuder we need this measure to test if this bug is still valid, otherwise we will close this issue.

**Comment by dstuder** [comment]
@evanweaver I believe this was the measure in question.


[change_water_heater_zone.zip](https://github.com/NREL/OpenStudio/files/1639996/change_water_heater_zone.zip)

**Comment by evanweaver** [comment]
Thanks @dstuder :)

**Comment by jmarrec** [comment]
is this still a thing?

**Comment by dstuder** [comment]
Unknown. Maybe a question for @kbenne?

**Comment by asparke2** [comment]
This does not appear to be an issue anymore, the field is populated once you call water_heater.addToThermalZone()
