### ISSUE TITLE
Effective Air Leakage Area Units Incorrect

### ISSUE THREAD

**Issue by dstuder** [NREL/OpenStudio#1808]
In the OS:SpaceInfiltration:EffectiveLeakageArea object, m2 is the listed unit for the "Effective Air Leakage Area" parameter. However, EnergyPlus expects (per the IDD) this to be in units of cm2. I checked the output from my model, and OS is not making this conversion. Seems like the easiest thing to do would be to just relabel this parameter as "cm2".

**Comment by macumber** [comment]
Duplicate of https://github.com/NREL/OpenStudio/pull/1575
