### ISSUE TITLE
EnergyPlus ForwardTranslator errors do not appear in the RunManager GUI elements (Bugzilla #897)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#181]
On 2012-09-11 10:56:19, @elainethale wrote:

> Created an attachment (id=213)
> Test file that produces ForwardTranslator errors.
> 
> I fixed a ForwardTranslator crash with the attached file. The fix includes logging an error. The error shows up if you run the file through developer/ruby/DebugScripts/DebugForwardTranslator.rb, but for some reason it does not show up under Errors/Warnings in the OpenStudio Application view of RunManager. I see in ModelToIdfJob.cpp that those translator warnings should be being pulled into RunManager, but they must be getting lost somewhere ... ?

Original attachments:
- PeopleTest_c.osm (ID 213)

**Comment by ljbrackney** [comment]
RunManager deprecated
