### ISSUE TITLE
Install Radiance with OpenStudio

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1815]
We get the message "Radiance was found but it is not the NREL version" when we install radiance with OpenStudio

**Comment by rpg777** [comment]
We never really parsed the NREL Radiance version file very well. Now that we're including it, we should.

**Comment by macumber** [comment]
Problem is that text file is not being included in the radiance install that we are including

**Comment by macumber** [comment]
Looks like this is just a configuration thing.  @axelstudios and @evanweaver when we build with radiance package can we just set RADIANCE_LOCATION to the directory containing the full install, e.g. 'C:\Program Files\Radiance'?  Right now it looks like that was configured to just install the bin directory, e.g. 'C:\Program Files\Radiance\bin'

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/CMakeLists.txt#L1049

**Comment by rpg777** [comment]
Honestly I think a better way to do it would be to get the version from the version string off of one of the critical executables. I've started embedding a breadcrumb in there, e.g.:

``` 
$ rcontrib -version
RADIANCE 5.0a (NREL ver 5.0.a.4) created Fri Aug 21 15:39:00 MDT 2015 by googs on rgugliel-25367s```

**Comment by macumber** [comment]
That is nice.  However, right now we are just installing the bin dir, we are not installing the lib dir.  That won't work right?

**Comment by macumber** [comment]
And @rpg777 I meant that is nice sincerely :-)

**Comment by rpg777** [comment]
Yeah, no, that definitely won't work, LOL. Need both the ./bin and the ./lib dirs, and they need to be in the same parent directory. From there the measure (should) take care of setting the RAYPATH and getting radiance/bin into the search path.

**Comment by axelstudios** [comment]
@macumber Which build platform has this problem?  In all cases we were setting `RADIANCE_LOCATION` to the root Radiance directory rather than the bin directory.

**Comment by macumber** [comment]
Looks like Windows 64 bit 1.8.4 install is correct, the 32 bit 1.8.4 installer I tested had this issue.
