### ISSUE TITLE
Material in templates is missing roughness and causes failed simulation

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1819]
This material seems to come from CEC work. This material is missing roughness in osm file. GUI shows it as VeryRough. If you just change the material roughness then it should export to the IDF file fine. It is in all of our template files and used in a number of CEC constructions.

OS:Material,
  {065acb20-8e01-4415-81ba-78a9157df073}, !- Handle
  Air - Metal Wall Framing - 16 or 24 in. OC, !- Name
  ,                                       !- Roughness
  0.1397,                                 !- Thickness {m}
  1.22016793979183,                       !- Conductivity {W/m-K}
  1.28147706991681,                       !- Density {kg/m3}
  1004.832,                               !- Specific Heat {J/kg-K}
  ,                                       !- Thermal Absorptance
  0,                                      !- Solar Absorptance
  0;                                      !- Visible Absorptance

OS:StandardsInformation:Material,
  {30b5ff7c-f776-4b80-b1df-f8fb55cc3caa}, !- Handle
  {065acb20-8e01-4415-81ba-78a9157df073}, !- Material Name
  CEC Title24-2013,                       !- Material Standard
  ,                                       !- Material Standard Source
  Air,                                    !- Standards Category
  Air - Metal Wall Framing - 16 or 24 in. OC, !- Standards Identifier
  ,                                       !- Composite Framing Material
  ,                                       !- Composite Framing Configuration
  ,                                       !- Composite Framing Depth
  ,                                       !- Composite Framing Size
  ;                                       !- Composite Cavity Insulation

I was able to reproduce this issue by adding a construction into my project that uses this material. When I manually assigned roughness in the GUI and re-ran it worked. We should be able to fix this for 1.9.0. (FYI - it isn't unique to hotel, happens in other templates as well.)

OS:Construction,
  {503c54c6-a289-4501-a03f-db07c3636a1b}, !- Handle
  MassHeavyWallU160,                      !- Name
  ,                                       !- Surface Rendering Name
  {86deda7d-73ae-42bb-ab57-8c9c9b934f0b}, !- Layer 1
  {c6a15ba6-81ba-401b-be0d-d1f1a9e0308d}, !- Layer 2
  {065acb20-8e01-4415-81ba-78a9157df073}, !- Layer 3
  {c148a8ba-54fd-4b13-9da8-e982f6c897a8}; !- Layer 4

**Comment by DavidGoldwasser** [comment]
CC: @macumber @asparke2 

If this is all we want to change in the templates then hand fixing with text editor is probably easier than updating standards spreadsheet and re-generating templates.One material to change in each template.

Can't remember if CEC work is in space type and construction set wizard, but I don't think it is. 

Another fix we may want to consider is addressing the GUI showing "VeryRough" when there is an empty roughness value. Maybe we have a default value. FYI - the material in question is always used on inside of a construction.

**Comment by macumber** [comment]
@DavidGoldwasser the constructor is actually correctly asking for this value, however if you pass in a bad value it wont set, this will be silent in a release build.  I guess the ctor should throw in that case?

@kbenne @mbadams5 what do you guys do in this case?

**Comment by macumber** [comment]
@DavidGoldwasser I am fine fixing in text editor for now

**Comment by DavidGoldwasser** [comment]
@macumber while most of the templates just had one material like this. The CECTemplate.osm had 18 air materials like this. Will have to remember to go back and fix those in the source later on.

I set everything to Smooth which is what the default roughness is when you make a new material. All of these materials are intended for use within a wall, so roughness shouldn't impact much.

Do you want to review this and then close? 
https://github.com/NREL/OpenStudio/commit/da2b604fa9e2574491c97a2c8f877d9c47b33997
