### ISSUE TITLE
Web Documentation points to files that are not in installer (Bugzilla #900)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#183]
On 2012-09-13 11:37:41, @DavidGoldwasser wrote:

> Not sure if we need to change the documentation or add files. Here is user forum post link
> https://openstudio.nrel.gov/forums/resultsviewer/help-desk/daylightingoffice#comment-1738
> 
> And here is the page he is talking about
> http://openstudio.nrel.gov/using-table-view-generate-illuminance-map-difference-plot
> 
> I'll have to test what he is talking about with the idf file not running. I can see it not importing to osm and running, but should run through EP launch.

Keywords: ForumPost

**Comment by asparke2** [comment]
Obsolete, references openstudio.nrel.gov
