### ISSUE TITLE
Select All in GridView should only select all rows/sub-rows that are currently visible (i.e. unfiltered)

### ISSUE THREAD

**Issue by evanweaver** [NREL/OpenStudio#1831]

**Comment by macumber** [comment]
@evanweaver is this possible to add for 1.10?  This seems pretty important

**Comment by evanweaver** [comment]
@DavidGoldwasser @asparke2 @macumber I believe I know your collective answer, but just to be sure, does "deselecting all" then only deselect those rows/sub rows that are currently visible (i.e those rows selected, but filtered out of view, would not be affected).

**Comment by evanweaver** [comment]
OK, I talked with Marj and have my marching orders.

**Comment by macumber** [comment]
What was the decision?

**Comment by evanweaver** [comment]
Mirrored behavior -- only deselect what is currently visible..

**Comment by macumber** [comment]
@evanweaver this looks good, the only thing I saw was that the All checkbox stays checked/unchecked in some non-intuitive (to me) ways.  For example:

1. Select all, All box is checked
2. Uncheck on row, All box remains checked (I thought it would get unchecked)

or 

1. Deselect all
2. Filter list
3. Select all, All is checked
4.  Unfilter list, All remains checked

You might revisit this with Marj but I'll close the ticket and merge for release
