### ISSUE TITLE
PAT - Amazon EC2 - Unable to update uuid with mismatches child job type

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#1842]
Openstudio PAT is crashing when I run on the cloud. Gives me the following dialogbox

![pat error-amazon ec2-unhandled exception](https://cloud.githubusercontent.com/assets/5479063/9734815/682da18c-5636-11e5-8953-3d04625330bf.jpg)

It will do it repeatedly. When I close and reopen up the project, I get the error right away. I have to go kill the cloud from the AWS console.

The cloud seems to have stalled as well while I have PAT open. When I close it, I see simulation finished, but there seems to be some fishy stuff

---

Version: 1.8.0
Build Number: 97b69c8a8d

**Comment by jmarrec** [comment]
That's what I thought, all of the runs actually failed. Simulation is complete, but they failed. I thought the time to run was way to short

I'm not quite sure what to put in terms of error log, so here's the entire page for one of the datapoints that I have opened before shutting the server down.

https://drive.google.com/file/d/0B6iX99bTtTWxdUVWR2R1THNRVjQ/view?usp=sharing

**Comment by macumber** [comment]
@axelstudios @evanweaver have you guys tested the cloud option in 1.8.5?

**Comment by macumber** [comment]
@nllong @henryHorsey  FYI

**Comment by jmarrec** [comment]
The measure you use, do they HAVE to be uploaded on BCL or can you use local measures?

**Comment by macumber** [comment]
You can use local measures, they are all uploaded to the EC2 computers when you start the cloud.

**Comment by jmarrec** [comment]
Hum. I set up a dumdum building (4 zones), a new PAT project and used very simple measures (rotate building, etc.).

This actually ran on EC2 fine... No idea what's wrong with my other project

**Comment by jmarrec** [comment]
Hum. But even with the above I keep getting "Detailed Results will be Downloaded when ready" even after 45min after the runs have completed...

**Comment by axelstudios** [comment]
Yep, there's currently a bug with downloading detailed results: #1723

The workaround until it's fixed is to copy the OpenStudio-server public DNS address from the AWS console (e.g. http://ec2-xxx-xxx-xxx-xxx.compute-1.amazonaws.com) and download the detailed results manually from there.

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
