### ISSUE TITLE
Space Tab - Subsurfaces sub-tab in lets you make new spaces with green "+"

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1843]
I assume the intent is to have this disabled?
@asparke2 or @macumber any thoughts on this. 

![9-8-2015 11-32-41 am](https://cloud.githubusercontent.com/assets/4857055/9743352/17e96e12-5623-11e5-89aa-5c5313e4d43c.png)

**Comment by asparke2** [comment]
Yeah, you shouldn't be able to create surfaces or subsurfaces.  I remember Marj talking about it, but not sure if it is specified in the design or not.  Basically, it is too difficult to create them accurately without a 3D view.

**Comment by macumber** [comment]
Making spaces is ok I guess, but I would prefer to have it disabled

**Comment by marj-schott** [comment]
Disabled is what I had in the document in the write up part but in the outline it is a question mark so that explains the confusion. Here are the things I listed in the text part of the Facility Tab document as not yet editable.
"The user can’t add, copy, or delete:
Spaces
Surfaces
Subsurfaces
Shading Surfaces
Interior Partitions"

**Comment by DavidGoldwasser** [comment]
Link to related issue. It shows that the shading group section of facility tab lets you add shading groups (site or building, not space). It also lets you lets you change site/building to space which is bad.
https://github.com/NREL/OpenStudio/issues/1797

I would also put Interior Partition Group on this list (which I think is the current behavior). It is probably also a bad idea for THE GUI to move any surfaces or sub surfaces to from one surface group to another.

**Comment by evanweaver** [comment]
@DavidGoldwasser please state explicitly what you want to accomplish with this bug.  Your most recent comment above appears to commingle 2 other issues which are dissimilar to "Please disable green + button on SpacesSurfacesGridView and SpacesSubsurfacesGridView" (which is what I believe you initially wanted).

**Comment by DavidGoldwasser** [comment]
@evanweaver I don't want the green "+" to make a new space. I didn't know if the intent was to have this disabled, or if it was supposed to be enabled, but to make a shading control object, frame and divider object, or light shelf, depending upon the current view. My reference to the other issue is related to the list of things @marj-schott says we should not be able to make until the next part of the facility tab.

Hearing Marj's comment, it sounds like the green "+" should be disabled throughout the space tab. Additionally issue #1797 mentions that the facility tab also allows new shading surface groups to be made and also has a drop zone for shading surface groups. I assume both of those should be disabled/removed as well?
