### ISSUE TITLE
Space Tab - Shading Controls sub-tab 

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1844]
@asparke2 and @macumber @evanweaver another one that may need some thought.

OpenStudio 1.8.5 lets you see and edit shading control objects. Everything has an "Apply to Selected" except for the Shading Control object. OS:ShadingControl is a shared resource. If you change the Shading Type or Schedule in one area it already changes everywhere else that shading control is used, even without the "Apply to Selected"  If you try to use "Apply to Selected it may not give the expected results (it will over apply it to any shading instances using that definition; to borrow term from internal loads).

Could just show the shading control object as drop zone, and we can provide a shading control object in our template. Then then user can drag it into their model and alter it with the edit pane. This would remove the requirement of using SketchUp to create these and also editing the construction or blind material (is there a reason that is hidden now?). Seems like main goal of this sub tab would be to apply or remove shading control assignment to existing geometry.

![9-8-2015 12-21-22 pm](https://cloud.githubusercontent.com/assets/4857055/9743918/1a289ace-5626-11e5-8317-9178152f05c7.png)

This is not critical and there is a way to do this in SketchUp, but since this is a new tab, the question is do we want to release it as is, hide it (only shading controls) until it does what we want, or release it as is and then enhance it later. I don't have a strong opinion. I was just testing it to see how a user might make use of it.

**Comment by macumber** [comment]
I'm not sure I understand what the issue is here?  Applying a shading control to all selected subsurfaces would make those subsurfaces use the shading control.  Editing the shading control in the inspector would affect all subsurfaces that use that shading control.  Is that what it does?

**Comment by macumber** [comment]
@rpg777 FYI

**Comment by DavidGoldwasser** [comment]
@macumber and @rpg777 currently you can't apply a new shading control to a sub-surface. You can only alter the shading surface properties (globally) for any shading surfaces that using that shading control.

So if I have 2 different shading controls used for 20 sub-surfaces. If a specific sub-surface used shading control "A" and I either wanted to change it to use shading control "B" or to make a new shading control, I can't do that in the App. I can only redefine shading control "A" and "B".

**Comment by DavidGoldwasser** [comment]
Fixed with this ticket
https://www.pivotaltracker.com/story/show/103031006
