### ISSUE TITLE
Space Tab - Daylighting Shelves

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1846]
We have drop zones for inside and outside shelf name, but the interior partition surfaces in "MyModel". To allow any editing of the objects we should allow users to re-assign or clear out the inside or outside shelf. Ideally we should also allow users to use this interface to make light shelves in the first place. currently this has to be done via a measure. Again not critical for 1.9.0, just wondering if the intent of the sub-tab is jsut for inspect vs. creating or editing objects.

cc: @asparke2 @macumber and @evanweaver 

![9-8-2015 11-40-19 am](https://cloud.githubusercontent.com/assets/4857055/9744211/b5770b68-5627-11e5-95e4-3a30d8c34d76.png)

**Comment by macumber** [comment]
Would this be solved by adding Interior Partition Surfaces to the My Model list?

**Comment by marj-schott** [comment]
We were not going to have interior partitions editable until we have some 3D view for them. Not sure I totally understand this issue so maybe we should discuss sometime.

**Comment by DavidGoldwasser** [comment]
@macumber yes, that fixes half of the issue (I only want it in MyModel and not in Library. The other half is making a new light shelf object.

@marj-schott I don't wan to add or alter the geometry itself, just want to associate it with a light shelf object, ideally would have the ability to make a new light shelf vs. just alter one made by a measure.

**Comment by macumber** [comment]
I don't think you should be able to make a new light shelf in OS app at this point, it's too geometry focused.  Associating an existing object is fine.

**Comment by DavidGoldwasser** [comment]
We were able to add library objects to 1.9 to create shading controls and frame and divider objects, but not daylighting shelves. This is because a new daylighting shelf has to be associated with a subSurface and there is no setSubSurface method. The preferred solution to this seems to be to change the API to behave more like shading control and frame and divider.

This could jsut be adding a setSubSurface method and allowing them to be constructioned withotu a subSurface. Then we can add stub object to library. A more dramatic change would be instead to add field to SubSurface to identify which daylighting shelf object it should refer to. This last approach would follow same logic as shading controls and frame and divider but has the potential to break older models unless version translation can clean up the files for this change.

@macumber I'll assign this to you, but it isn't anything to touch for release. Once this is done we will also need to change the "Daylighting Shelf Name" column in the Space > SubSurfaces sub-tab to a drop zone and then add a stub object into our templates.

**Comment by evanweaver** [comment]
There are a number of "what ifs" mentioned in this ticket, but I think that the true intent agreed upon by all is "Add Interior Partition Surfaces to My Model list", which has now been done.

**Comment by DavidGoldwasser** [comment]
@evanweaver that is what we agreed upon to get 1.9.0 out, but we talked about an API change to allow setSubSurface for a light shelf. Without that or some other change in the GUI you can't make a light shelf or associate an interior partition surface already in your model with a light shelf object.

**Comment by evanweaver** [comment]
@macumber thoughts?

**Comment by macumber** [comment]
Well part of what @DavidGoldwasser said is not right.  You *can* make a light shelf (have to pass in a SubSurface to the ctor) and you *can* associate an InteriorPartitionSurface with the light shelf using setInsideShelf.  

But David is right that there is no setSubSurface method so you can't move a light shelf from one window to another.  You also can't create an orphan light shelf and then assign it to a subsurface later.  If I understand correctly, David would like to have a light shelf in the library, then you could drag this in to a surface.  As long as we had a SubSurface and LightShelf in the library and we implemented light shelf.setSubSurface then I think this would work, is that what you mean @DavidGoldwasser ?

**Comment by DavidGoldwasser** [comment]
@macumber what  I meant is someone can't make a light shelf in the GUI. The API can do it, and it is used in measures and in SketchUp. The suggestion of adding the setSubSurface method and allowing me to make a light shelf object without any surfaces associated to put in the library seems like the most straight forward solution.

An alteration solution we discussed if we didn't want to touch the API, was to have an empty drop zones in the light shelf columns. Users could drag in an interior partition surface from "MyModel" and then it would make a light shelf object on the fly, and hook it up to the surface that was dragged in.

I was also find just hiding the Daylighting Shelves view of SubSurfaces. I think Shading Controls and Frame and Divider were adding in, in support of Radiance, but I don't think Radiance uses the light shelf object, however it does use the interior partition surfaces on their own.

**Comment by macumber** [comment]
I don't see any value in putting light shelves in the library since they don't have any real data in them (unless we also included the shelves but that is too window specific).  Here's the punch list for no API changes

- [ ] When window has a light shelf, no change, this works now
- [ ] When window has no light shelf, show empty drop zones for inside and outside shelf name
- [ ] When someone drops inside or outside shelf, if there is a light shelf then use that, if not create a light shelf for the window
- [ ] There should only be one light shelf per window, log a warning if that is violated

**Comment by evanweaver** [comment]
Thanks @macumber, perfect marching orders.

**Comment by rpg777** [comment]
I agree with @macumber. I also think this is a lot of hand wringing and time spent over an object that is fairly useless in real daylighting practice. Lightshelves rarely provide full cutoff throughout the entire year (unless the thing is ridiculously deep or you're at the equator), nor do they project light very far into the interior, particularly as far as EnergyPlus can predict. What are we *doing*, here?

**Comment by evanweaver** [comment]
With that in mind, is this something we try to put into 1.10? I think Luigi would grimace.

**Comment by rpg777** [comment]
LOL

**Comment by Altaiar** [comment]
can we make Light shelves in GUI right now? or how can i do it with api (should i do it in Sketchup ruby Console Right?)

**Comment by macumber** [comment]
@Altaiar you should file this as an issue in https://github.com/openstudiocoalition/OpenStudioApplication/issues or https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues since the maintenance of those applications transferred from NREL to the OpenStudio Coalition.
