### ISSUE TITLE
Space Tab - Shading sub tab is mising Shading Surface Name column

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1847]
Look like Shading Surface Name column is missing. If you have multiple shading surfaces in a space you won't be able to identify them from each other. Mainly important if you want to assign construction or transmittance schedule.

![9-8-2015 11-54-12 am](https://cloud.githubusercontent.com/assets/4857055/9744268/0fcffdfe-5628-11e5-8ff7-d77c93e7fbba.png)

**Comment by macumber** [comment]
Agree
