### ISSUE TITLE
Number of WaterHeater:Stratified Nodes Fixed at One

### ISSUE THREAD

**Issue by dstuder** [NREL/OpenStudio#1853]
It appears that the number of nodes is fixed at one for the WaterHeater:Stratified object. While the parameter can be manipulated in the OS App, the resulting .idf seems to always fix the number of nodes to 1.

I noticed this in a model where I indicated that the water heater had six nodes (via the OS App), but the .idf object has the "Number of Nodes" value set to "1".

**Comment by dstuder** [comment]
Am I missing something here, or is this a real (@mbadams5 or @kbenne?) issue?

**Comment by mbadams5** [comment]
@dstuder no, there is a subtle bug in the forward translator I see now.
