### ISSUE TITLE
Default BoilerHotWater::BoilerFlowMode

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#1861]
The HVAC library has the boiler flow mode set to LeavingSetpointModulated and the default constructor sets the value to ConstantFlow. LeavingSetpointModulated requires a SPM on the outlet node. The HVAC templates are using the default "ConstantFlow". I don't think either is good. 

I think the library should be "NotModulated". LeavingSetpointModulated is hazardous because you have to know what you're doing and add a SPM on the outlet node.

Changing the ctor default to NotModulated is probably in order, but such a change should be made carefully because it will change the behavior of the templates.

**Comment by kbenne** [comment]
Before making any changes it is important to confirm behavior with analysis of time series data. Show some graphs about what is going on.

**Comment by kbenne** [comment]
I changed the hvac library here

https://github.com/NREL/OpenStudio/commit/ed494eb1e00045c2a5440ca11e02181b90586df8

**Comment by macumber** [comment]
@kbenne is this complete?
