### ISSUE TITLE
PAT 1.8.5 hanging when running multiple simulations

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#1868]
I've got an issue in PAT 1.8.5.

When I run all of my measures, only the Baseline finishes, the rest keeps hanging.

Weirdly enough, I tried removing all of my measures, and created only one. Both the baseline and this measure ran.

I tried adding again the other measures, and running only 3 of them at a time... Same problem, it keeps hanging, never finishes. (doesn't appear to even get to E+ running, that's still 'idle')

The measures run fine when I apply them in OS App, and some of them I definitely tested successfully in OS PAT 1.8.0

**Comment by jmarrec** [comment]
I've narrowed it down...
Basically, I went through the trouble of applying each measure in openstudio successively.

It turns out I have one measure that appears to be guitly, that applies a PSZ-HP system to each zone, and deletes the air loop and chiller loops and condenser loops if they end up empty.

 I believe it's something similar to this https://unmethours.com/question/11162/os-hang-up-when-deleting-hot-water-loop/

**Comment by ljbrackney** [comment]
I'm curious if Kyle's fix for that issue will also fix this problem.

**Comment by jmarrec** [comment]
@ljbrackney: it does fail in "Apply now" also right now, so maybe it would fix it too.



I just uploaded a measure, a unit test file, and an example model, in case you want to play with it:

https://github.com/jmarrec/OpenStudioMeasures/tree/master/Add%20PSZ-HP%20to%20all%20Zones

**Comment by kbenne** [comment]
It does



On Sep 15, 2015, at 12:21 PM, L J Brackney <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm curious if Kyle's fix for that issue will also fix this problem.

**Comment by jmarrec** [comment]
Can I integrate the fix right now or should I just revert back to using 1.8.0 until the next release?

(Can you downgrade a model from 1.8.5 to 1.8.0 aside from manually changing the OS:Version in the text editor?)

**Comment by macumber** [comment]
If I understand correctly, this is fixed by @kbenne's commit and will be in the 1.9.0 Release Candidate builds available at the end of the week, right?

**Comment by kbenne** [comment]
My fix is merged to the develop branch so yes whenever that RC comes out we should have confirmation that this is taken care of.

**Comment by macumber** [comment]
@jmarrec can you confirm if this is fixed in 1.9.0 RC1?

**Comment by jmarrec** [comment]
Running it right now... will let you know in a minute

**Comment by jmarrec** [comment]
Confirmed, works as expected in both PAT and OS App's "Apply now"
