### ISSUE TITLE
When we warn users that we flipped surface we give UUID vs. name (Bugzilla #909)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#187]
On 2012-09-14 14:11:17, @DavidGoldwasser wrote:

> Warning:  {e002b28d-3c4b-429a-859f-3dbb9c3e965b}
> This Roof or Ceiling surface is upside-down.
> It has been automatically fixed.

**Comment by jmarrec** [comment]
Pretty sure that's not true anymore.
