### ISSUE TITLE
PAT 1.8.0 - An unhandled exception has occured - AnalysisDriver.cpp - Invalid Results

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#1870]
I'm trying to change one measure, it's telling me it will clear results, and then crashes. If I click on "clear results" before I change the measure, it crashes just the same

![2015-09-16 11_06_30-pat](https://cloud.githubusercontent.com/assets/5479063/9900743/0e1e0f1e-5c63-11e5-95ae-df1e663ee07c.jpg)

By the way, my openstudio is not installed in `C:\Openstudio1.8.0` like the picture says

**Comment by macumber** [comment]
That 'C:\Openstudio1.8.0' path is hanging around from the person that built that release.  Where did you get this installer from?  Is it the main 1.8.0 installer?

**Comment by macumber** [comment]
@jmarrec can you post a project somewhere so i can reproduce?

**Comment by jmarrec** [comment]
This is the main 1.8.0 installer.
I'm pretty sure I ended up trashing this project and recreating from scratch...
