### ISSUE TITLE
BCL categories for components missing

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#1871]
On the BCL website, there are a lot more of categories and subcategories than within OS App 1.8.0 "Find component".

![2015-09-16 16_34_55-online bcl-missing boilers etc](https://cloud.githubusercontent.com/assets/5479063/9907873/724f076c-5c91-11e5-90bd-8e9992c0b0b3.jpg)

All the components appear to be here though. For example, I cannot see the "Boiler" category under "HVAC" but I can still find the boilers...

**Comment by jmarrec** [comment]
I guess it's because they don't have an OSM file associated? 
https://unmethours.com/question/8133/how-do-you-download-hvac-equipmentcomponents-from-bcl-and-import-into-the-openstudio-application/

**Comment by DavidGoldwasser** [comment]
The type of components you can add using OpenStudio app from BCL is very constrained. Providing full support for BCL components from App would be good item for UserVoice.
