### ISSUE TITLE
Edit tab for many zone objects have an extra non-functional iink sub-tab

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1877]
I confirmed this on Water to Air HP, Unit Ventilator and Unit Heater.

![2015-09-17 09_49_24-os-1 9 0-3 links](https://cloud.githubusercontent.com/assets/4857055/9937021/fef6a5be-5d1b-11e5-921a-41c53fec1838.jpg)
screenshot from @jmarrec

**Comment by DavidGoldwasser** [comment]
It sounds like if any objects of a class of objects could have a water connection (or two) then all objects in that class have the link space even if they use gas instead of water. This could be cleaned up, but that explains the behavior.

**Comment by jmarrec** [comment]
Still true as of 2.2.1. I guess we don't care that much though...
