### ISSUE TITLE
OS App creates simulation settings objects different from E+ defaults

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1879]
When you create a model is the OS app, the model does not have simulation settings objects.  When you go to the simulation settings tab, these missing objects get created.  The issue is that the settings in these objects don't match the E+ defaults for what happens if the objects are missing.

The symptom is that you can get very different results in a model without (knowingly) editing anything.

Below shows a diff of a fresh model created before and after navigating to sim settings tab:
![image](https://cloud.githubusercontent.com/assets/2009290/9940968/e50229b2-5d2f-11e5-86f9-c8a481a0077f.png)

Two of the objects are populated differently than E+ defaults:

ShadowCalculation:
 - Calculation Frequency (IDD default is 20, OS uses 7)

ZoneAirHeatBalanceAlgorithm
  - Algorithm (E+ default and IDD default is ThirdOrderBackwardDifference, OS uses AnalyticalSolution)

Suggest either populating these objects on new file creation, or minimally changing the constructors to use the E+ default values so simulation results won't change.

**Comment by DavidGoldwasser** [comment]
Going to that tab adds this to my model

OS:RadianceParameters,
  {7155eeb0-4b8f-408e-ae78-a387c05ea188}, !- Handle
  1,                                      !- Accumulated Rays per Record
  0,                                      !- Direct Threshold
  1,                                      !- Direct Certainty
  1,                                      !- Direct Jitter
  1,                                      !- Direct Pretest
  6,                                      !- Ambient Bounces VMX
  2,                                      !- Ambient Bounces DMX
  4050,                                   !- Ambient Divisions VMX
  512,                                    !- Ambient Divisions DMX
  256,                                    !- Ambient Supersamples
  0.001,                                  !- Limit Weight VMX
  0.001,                                  !- Limit Weight DMX
  500,                                    !- Klems Sampling Density
  146;                                    !- Sky Discretization Resolution

OS:SimulationControl,
  {5416f735-0f7b-4cd7-a6ad-da0301e35762}; !- Handle

OS:Sizing:Parameters,
  {fb7533d9-b9e8-45fc-82fe-e1303665b6ed}, !- Handle
  1.25,                                   !- Heating Sizing Factor
  1.15;                                   !- Cooling Sizing Factor

OS:ProgramControl,
  {d904c14d-38b4-4952-8d33-b64eaf7968ea}; !- Handle

OS:Timestep,
  {db9786c4-4452-41c1-95d6-f124bd4c1c3c}, !- Handle
  6;                                      !- Number of Timesteps per Hour

OS:OutputControl:ReportingTolerances,
  {c6312d31-609f-436f-862a-225cdd7f471b}; !- Handle

OS:ConvergenceLimits,
  {193f4d45-a985-4ff6-b637-fe1300002e05}, !- Handle
  1;                                      !- Minimum System Timestep {minutes}

OS:ShadowCalculation,
  {31c1c535-8697-48e2-912b-54d40ab3ed74}, !- Handle
  20,                                     !- Calculation Frequency
  15000;                                  !- Maximum Figures in Shadow Overlap Calculations

OS:SurfaceConvectionAlgorithm:Inside,
  {8d654335-7d2e-47c5-9a8a-d165b4199f48}, !- Handle
  TARP;                                   !- Algorithm

OS:SurfaceConvectionAlgorithm:Outside,
  {9bba2dcb-81a6-41e7-b86e-66a3a324648a}, !- Handle
  DOE-2;                                  !- Algorithm

OS:HeatBalanceAlgorithm,
  {ab5c3473-4fd3-415e-8330-f9cc7478b745}, !- Handle
  ConductionTransferFunction,             !- Algorithm
  200;                                    !- Surface Temperature Upper Limit {C}

OS:ZoneAirHeatBalanceAlgorithm,
  {08bf009e-8bbf-4842-8204-197b77c27655}, !- Handle
  ThirdOrderBackwardDifference;           !- Algorithm

OS:ZoneAirContaminantBalance,
  {a4b22c15-fe1d-4102-aaf4-ab1a1e1ab211}; !- Handle

OS:ZoneCapacitanceMultiplier:ResearchSpecial,
  {8e14106f-4769-4efc-80e8-039c772c0f4f}, !- Handle
  ,                                       !- Temperature Capacity Multiplier
  ,                                       !- Humidity Capacity Multiplier
  ;                                       !- Carbon Dioxide Capacity Multiplier

OS:RunPeriod,
  {a3c73aef-1549-4ecb-ab50-a940d2130b98}, !- Handle
  Run Period 1,                           !- Name
  1,                                      !- Begin Month
  1,                                      !- Begin Day of Month
  12,                                     !- End Month
  31,                                     !- End Day of Month
  ,                                       !- Use Weather File Holidays and Special Days
  ,                                       !- Use Weather File Daylight Saving Period
  ,                                       !- Apply Weekend Holiday Rule
  ,                                       !- Use Weather File Rain Indicators
  ,                                       !- Use Weather File Snow Indicators
  ;                                       !- Number of Times Runperiod to be Repeated

**Comment by DavidGoldwasser** [comment]
IDF's made from this are almost exactly the same (except fro order and a few UUID's) except for the following objects.

This object is in the newer IDF after going to the tab, but not in the first IDF at all, but based on Andrew's initial comment we now seem to be using the E+ result. Does EnergyPlus add this object on the fly if needed (if user has never gone to sim settings in OS) 
ZoneAirHeatBalanceAlgorithm,
  ThirdOrderBackwardDifference;           !- Algorithm

More objects only in the newer IDF.I don't know for sure if these match the E+ defaults

ConvergenceLimits,
  1;    

HeatBalanceAlgorithm,
  ConductionTransferFunction,             !- Algorithm
  200;     

ShadowCalculation,
  AverageOverDaysInFrequency,             !- Calculation Method
  20,                                     !- Calculation Frequency
  15000;  

SurfaceConvectionAlgorithm:Inside,
  TARP;                                   !- Algorithm

SurfaceConvectionAlgorithm:Outside,
  DOE-2;  

Timestep,
  6;   

OutputControl:ReportingTolerances,
  0.2,                                    !- Tolerance for Time Heating Setpoint Not Met {deltaC}
  0.2;  

These all seem to be in line with E+ Results
