### ISSUE TITLE
Default constructor for PlantEquipmentOperation:OutdoorDryBulb has temp limits reversed

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1881]
After creating a PlantEquipmentOperation:OutdoorDryBulb, it looks like this:

```
OS:PlantEquipmentOperation:OutdoorDryBulb,
  {d944aebd-fcf2-4239-9329-21e43c4ba12b}, !- Handle
  Operate Chiller Above 13C,              !- Name
  70,                                     !- Dry-Bulb Temperature Range Lower Limit 1 {C}
  -70,                                    !- Dry-Bulb Temperature Range Upper Limit 1 {C}
  {db799e58-12cc-485a-beec-f0b6a5a9cf3b}; !- Range Equipment List Name 1
```
Notice that the upper and lower limits are flipped.  

Fix by changing these numbers:

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/PlantEquipmentOperationOutdoorDryBulb.cpp#L61

**Comment by asparke2** [comment]
@mbadams5 I think this is a super easy fix

**Comment by mbadams5** [comment]
@asparke2 I think there is more to this than it seems. Some of the other PlantEquipmentOperations have the same pattern... [OutdoorDewpoint](https://github.com/NREL/OpenStudio/blob/88f177befc849b26d384b3f95a49b9bee9e564cd/openstudiocore/src/model/PlantEquipmentOperationOutdoorDewpoint.cpp#L67), [OutdoorRelativeHumidity](https://github.com/NREL/OpenStudio/blob/88f177befc849b26d384b3f95a49b9bee9e564cd/openstudiocore/src/model/PlantEquipmentOperationOutdoorRelativeHumidity.cpp#L67). But then [OutdoorWetBulb](https://github.com/NREL/OpenStudio/blob/88f177befc849b26d384b3f95a49b9bee9e564cd/openstudiocore/src/model/PlantEquipmentOperationOutdoorWetBulb.cpp#L67) fits what you'd think...

**Comment by asparke2** [comment]
Hmm ok...I think set .addLoadRange method keys off of these initial values, so it matters if the initial constructors are.

**Comment by kbenne** [comment]
https://github.com/NREL/OpenStudio/commit/a3972f0cd7338278b3d2bb2a859d6fcf5933302e
