### ISSUE TITLE
PTACs have different characteristics between library and OpenStudio::Model::addSystemType1

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#1884]
I've looked at PTAC with DX cooling and Hot Water Coils, using `1.8.0`

Three choices:
1. `Cycling PTAC DX Clg HW Htg` from the HVAC Library
2. `PTAC DX Clg HW Htg` from the  HVAC Library
3.  PTAC created using the API `OpenStudio::Model::addSystemType1(model, zones)`

I wanted to see the differences, and some I can't explain:
- (3.) has a fan with 500 Pa whereas the two others have 250 Pa.
- (1.) has a different set of curves than the other two.

Why?

See [this excel file](https://slack-files.com/T0ADXQFF0-F0B4N6X98-3675001282) for more info.

**Comment by jmarrec** [comment]
For the fan pressure rise it's hard set [here](https://github.com/NREL/OpenStudio/blob/89455bdd81f894a02f4f81dead44a000fc27cc64/openstudiocore/src/model/HVACTemplates.cpp#L195).

**Comment by kbenne** [comment]
I don't think there is a good answer beyond the fact that these have been added at different points in time with not enough scrutiny. @jmarrec don't you think this is one more reason to base the HVAC library on Measure?

**Comment by kbenne** [comment]
I'm confident @jmarrec knows this but for other people who may be following along, note that fan pressure can be changed to your own value from the OS App or from a Measure.

**Comment by jmarrec** [comment]
@kbenne : I kinda had a brief conversation on the side with @mbadams5, about what should be the default value for library equipment. In my mind, unless specified, it should be the current ASHRAE standard enforced by the majority of states but I realize this is ever changing and confusing, or better it would ask which standard you want to use.

I've been looking at the Prototype Building stuff (it's brilliant, but hard to wrap your head around right now, tons of files!), and I think this will really change the game... I think eventually it'd be great to have the OS App 'add HVAC system' being replaced with the prototype stuff for baseline systems, and hardsetting values that are changing based on capacity after a sizing run (this is something I've wanted in E+ for ages, and now it's finally there in OS! that's awesome). For example, for PTAC you'd hardset the cooling COP based on Total Rated Capacity after sizing run.

I think keeping the library components in the App but having them being a measure adds some welcomed flexibility. Ideally I could picture having a dynamic window or a pre-selection screen (once/if this is implemented) poping up, asking if you want to define the characteristics of the system yourself or using baseline value from a user specified standard (pulling from the Openstudio_standards...json file)

**Comment by kbenne** [comment]
I just read the Slack conversation today. I think you guys echoed my thoughts pretty well. I have resisted advertising the fact the OS App "add HVAC System" almost follow ASHRAE standards, because as you are finding out now, they are not exactly compliant. Now that standards capability is coming along it is definitely time to reconsider how some of this works.

**Comment by jmarrec** [comment]
I'm closing this, as I think it's really a non-issue, especially now that the addSystemType1 is only left in the API.

If you want to implement ASHRAE compliant systems in the API, you'd use openstudio-standards nowadays.

The only thing to keep in mind is that the hvac_library might benefit from using the openstudio-standards directly to create ASHRAE systems for every vintage where applicable (that could be automated during build).
