### ISSUE TITLE
Running paegent seems to interfere with PAT cloud

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1885]

**Comment by macumber** [comment]
I remember seeing this before, @axelstudios does this ring a bell?  I turned off paegent and this worked again.

**Comment by macumber** [comment]
![9-22-2015 4-02-11 pm](https://cloud.githubusercontent.com/assets/1327850/10033036/128545f0-6144-11e5-8b11-e53c47ee6ccd.jpg)

**Comment by axelstudios** [comment]
I've never used pageant, so this isn't something I've run into

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
