### ISSUE TITLE
Thermal Zone Floor Area isn't exposed in API

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1890]
We do expose thermal zone volume, but not thermal zone floor area. This would allow a work around for issue #561 related to stacked spaces

**Comment by macumber** [comment]
We also need to update the ThermalZone::floorArea method to respect this field.  Finally, we need to also handle Space::isPartOfTotalFloorArea.  My thought is if any space is not part of the floor area then we need to write the floor area field on translation to E+.

**Comment by macumber** [comment]
We also need to make sure to convert all loads to total watts before combining floors.  Otherwise you could have 1 w/ft^2 upstairs and 2 w/ft^2 downstairs, those would not work well if you multiplied them by the total area.

**Comment by macumber** [comment]
Would be good if we can only set this field in E+ and not in OpenStudio, can this all be done in translation?

**Comment by macumber** [comment]
For the record, I think OpenStudio is pretty good at calculating floor area.  We have more problems in computing volume which is why the setVolume method is available.

**Comment by evanweaver** [comment]
@macumber, if you would elaborate on "respect", I'll take a look at implementation.

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio/blob/eadff9598068b16479b1f5a223ee0611458d2fc6/src/model/ThermalZone.cpp#L799-L805


https://github.com/NREL/OpenStudio/blob/eadff9598068b16479b1f5a223ee0611458d2fc6/src/model/Building.cpp#L650-L659

**Comment by shorowit** [comment]
If this is ever implemented, it'd be nice to offer the same for an OS:Space. EnergyPlus allow floor areas to be entered for either the thermal zone or the space. cc @eringold

**Comment by jmarrec** [comment]
Space::setFloorArea exist. So I think this is fine.
