### ISSUE TITLE
Application is freezing when trying to remove plantloop from model

### ISSUE THREAD

**Issue by lincolnharmer** [NREL/OpenStudio#1891]
This is happening regardless of whether the plantloop has components attached to it or not. This is resulting in the AEDG HVAC measures hanging up also. I'm using v1.8.5

**Comment by kbenne** [comment]
Unless you are running into something else, your problem has been fixed [here](https://github.com/NREL/OpenStudio/commit/6da27c12ea4a541b40afeab0df793c12c868a700). I believe the latest 1.9.0 candidates include this fix. 

[Mac](https://openstudio-builds.s3.amazonaws.com/1.9.0/OpenStudio-1.9.0.043ddbb575-Darwin.dmg)

[Linux](https://openstudio-builds.s3.amazonaws.com/1.9.0/OpenStudio-1.9.0.043ddbb575-Linux.deb)

[Win64](https://openstudio-builds.s3.amazonaws.com/1.9.0/OpenStudio-1.9.0.043ddbb575-Win64.exe)

[Win32](https://openstudio-builds.s3.amazonaws.com/1.9.0/OpenStudio-1.9.0.043ddbb575-Windows.exe)

**Comment by lincolnharmer** [comment]
thanks. let me check

**Comment by lincolnharmer** [comment]
did the trick

**Comment by DavidGoldwasser** [comment]
Great, I was having issues with SWH and HVAC AEDG measures when run on top of the prototype buildings. I didn't have a chance yet to investigate where the issue was, I had assumed it was related to the measures, but they run now in 1.9 :)
