### ISSUE TITLE
1.9.0 Space tab: do not see inherited properties

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#1893]
I've got a very simple setup: one space type (open office, created from your templates).

I've got one space: 

![2015-09-25 09_44_56-space](https://cloud.githubusercontent.com/assets/5479063/10095484/70c94ba2-636a-11e5-88a0-b37e5a4d2ebd.jpg)

First, I didn't specify the space type, it's inherited from the building level, so I'd like to see this in green as it used to be.

If I move to the load, it's completely empty, not showing any of the inherited loads from space type open office.

![2015-09-25 09_45_57-space loads](https://cloud.githubusercontent.com/assets/5479063/10095479/68915236-636a-11e5-8549-567062bea766.jpg)

I'd like to see those in green too...

As far as the other tabs, there is no longer any way to see what's defaulted and what's hard assigned, and to me this is a problem, especially for the Surfaces > Constructions.

**Comment by MatthewSteen** [comment]
Related to #1460.

**Comment by evanweaver** [comment]
To be fixed under the following:
Implement inheritance across all girdviews #1946
https://github.com/NREL/OpenStudio/issues/1946
