### ISSUE TITLE
Biquadratic curve min/max value edits not retained

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#1897]
@kbenne because I believe you work on HVAC.

In OS 1.9 (Windows x64): edits to the min/max values of x/y in the Curve:Biquadratic object attached to OS:Boiler:HotWater (also OS:CoolingTower:VariableSpeed, but those are the ones I checked) appear editable, but are reset to 0/1 when leaving the edit pane.

**Comment by macumber** [comment]
@kbenne please tag this for 1.10.0 if you would like to fix it for the release

**Comment by kbenne** [comment]
@eringold I couldn't reproduce this in 1.9.5. Would you mind double checking that it is still an issue? I tested on Mac.

**Comment by eringold** [comment]
Yeah, I'm still seeing it with 1.9.5 (windows x64). Edits to the coefficients stick around, but the min/max values always return to 0 and 1.

**Comment by jmarrec** [comment]
+1 still relevant today in 1.10.1

**Comment by eringold** [comment]
Looks like it only happens when app unit preference is IP.
