### ISSUE TITLE
When you copy a measure, the resulting measure has inadvertent space in display name.

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1898]
This doesn't happen when you make a new measure, only when you copy an existing measure. It looks fine in the "Name" input of the "Copy Measure" dialog. It only affects the resulting measure.rb and measure.xml.

Making a new measure doesn't suffer this.

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
