### ISSUE TITLE
Crash when viewing plant loop on user model

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1899]
I confirmed this on 1.9.1
https://unmethours.com/question/11836/crash-when-trying-to-view-hot-water-loop/

File is in unmethours post.

**Comment by DavidGoldwasser** [comment]
User has reported that re-build model doesn't crash. I have asked him to post that model as a comparison.

**Comment by DavidGoldwasser** [comment]
I have a crash in K12 modeling I'm working on using some new HVAC objects. It crashes in heat pump loop. Not when you first go to it, but when you scroll down. It is fine for teh first six coils on demand side, but crashes before the 7th.

For the first 6 coils I can click and edit them without any issues. file is in.osm in this directory.
https://github.com/NREL/OpenStudio-files/tree/master/Git%20Issue%20Files/Issue%201899

**Comment by asparke2** [comment]
@kbenne another report of this bug from G14.  "Model crashing HW loop.osm" in the folder David referenced above.

**Comment by kbenne** [comment]
Oh yeah. Definitely need to get this fixed. Let me get the 8.4 update out...
