### ISSUE TITLE
Fix Radiance translator's reporting behavior

### ISSUE THREAD

**Issue by rpg777** [NREL/OpenStudio#1901]
When the RadFwdTranslator has a problem with a subsurface (e.g. cannot discern the transmittance), it merely reports a warning, fails to translate the object, and moves on (leads to mildly annoying -- to severely problematic -- Radiance simulation errors down the line). Translator should report the issue as an error, and throw an exception.

**Comment by macumber** [comment]
@rpg777 please tag this for 1.10.0 if you would like to fix it for the release

**Comment by rpg777** [comment]
<a href="https://github.com/NREL/OpenStudio/commit/12f1a39431c4f83bc68f14225db0885e9381fc1c">fixed.</a>
