### ISSUE TITLE
Bad URL comes up on first launch of SketchUp plugin

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1903]
http://nrel.github.io/OpenStudio-user-documentation/next_steps/sketchup_plugin_interface/

**Comment by DavidGoldwasser** [comment]
Looks like the url is in 2 html and 2 .rb files in the plugin
https://github.com/NREL/OpenStudio/search?utf8=%E2%9C%93&q=http%3A%2F%2Fnrel.github.io%2FOpenStudio-user-documentation%2Fnext_steps%2Fsketchup_plugin_interface&type=Code

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/25
