### ISSUE TITLE
Linux installer: use less restrictive dependencies for the ruby runtime and library (available in current repos)

### ISSUE THREAD

**Issue by pachi** [NREL/OpenStudio#1904]
The current OpenStudio 1.9.1 installer needs additional dependencies but for current Ubuntu (15.4) one of them (Ruby2.0) is not available without requiring a backport (current release has Ruby2.1).
Could it be possible to set that dependency (and others in general) as accepting other micro-releases? So this would mean that, instead of requiring ruby2.0 it would require ruby2.x?

**Comment by macumber** [comment]
@nllong @axelstudios any thoughts?

**Comment by nllong** [comment]
it is caused by this [line](https://github.com/NREL/OpenStudio/blob/develop/OpenStudioCPack.cmake#L35). I would like to find a way to relax the requirement because I experienced similar issues when running a newer openstudio on Ubuntu 12. Not sure that I have an answer right now. Maybe a suggestion would be to have this be conditional based on linux flavor?

**Comment by pachi** [comment]
The problem is restricting to libruby2.0 and ruby2.0 as they are only used by somewhat old Fedora releases (19 and 20), while most other distros, and specially the .deb based ones use now ruby 2.1.

Given that Ruby versions in the 2.x series should be backwards compatible, and that ruby.org tags 2.0, 2.1 and 2.2 as "old stable", "previous stable" and "current stable", allowing any Ruby 2.x runtime and library would be available in any reasonably recent distro.

The following list shows the ruby version used in some popular linux distros for their most recent releases:

Debian 7 (wheezy): Ruby 1.8
Debian 8 (jessie): Ruby 2.1
Ubuntu 14.04 LTS (trusty): Ruby 1.9
Ubuntu 14.10 (utopic): Ruby 2.1
Ubuntu 15.04 (vivid): Ruby 2.1
Ubuntu 15.10 (wily): Ruby 2.1
Fedora 19: Ruby 2.0
Fedora 20: Ruby 2.0
Fedora 21: Ruby 2.1
Fedora 22: Ruby 2.2

I think that changing the pointed to CMAKE line to this would work:

    set(CPACK_DEBIAN_PACKAGE_DEPENDS "libboost-thread1.55.0, libboost-system1.55.0, libboost-regex1.55.0, libboost-filesystem1.55.0, libboost-date-time1.55.0, libboost-program-options1.55.0, libboost-log1.55.0, libqt5sql5, libqt5network5, libqt5sql5-sqlite, libqt5gui5, libqt5xml5, libqt5webkit5, libqt5concurrent5, libqt5location5, libqt5printsupport5, libruby2.0 | libruby2.1 | libruby2.2, ruby2.0 | ruby2.1 | ruby2.2")

This change is in pull request: https://github.com/NREL/OpenStudio/pull/1908

I can't currently build the package with this change, but I'm eager to try the new package.

**Comment by pachi** [comment]
Trying to find how the other dependencies fit in different distros I've found the "whohas" package very useful. You can ask it for any package name (with or without version) and it shows which distributions have it. For instance:

    pachi@PACHI-DEBIAN:~$ whohas libboost-thread1.55.0

shows:

    Ubuntu      libboost-thread1.55.0                  1.55.0-1           26K             all                       http://packages.ubuntu.com/trusty/libboost-thread1.55.0
    Ubuntu      libboost-thread1.55.0                  1.55.0+dfsg-1ubunt 26K             all                       http://packages.ubuntu.com/utopic/libboost-thread1.55.0
    Ubuntu      libboost-thread1.55.0                  1.55.0+dfsg-3ubunt 31K             all                       http://packages.ubuntu.com/vivid/libboost-thread1.55.0
    Tried fetching "http://dl.fedoraproject.org/pub/fedora/linux/releases/20/Everything/i386/os/Packages/l/" five times. Giving up.
    Debian      libboost-thread1.55.0                  1.55.0+dfsg-3      53K             all                       http://packages.debian.org/jessie/libboost-thread1.55.0
    Debian      libboost-thread1.55.0                  1.55.0+dfsg-4+b1   53K             all                       http://packages.debian.org/sid/libboost-thread1.55.0

so we can see that (besides failing to fetch Fedora data), that dependency works for Ubuntu: trusty, utopic and vivid, and Debian jessie (current stable) and sid (unstable). 

With that tool and some web search I've found that the libqt5 packages are widely available in many distros, but the libboost libraries are only available (with those names and versions) in Ubuntu trusty, Ubuntu utopic, Ubuntu vivid, Debian jessie and Debian sid, so these are,  in fact, the supported releases.

These releases also use ruby2.1 and libruby2.1 (and don't have ruby2.0 and libruby2.0), so I find reasonable that the packages at least depend on the 2.1 version of ruby and libruby.

Given that

**Comment by axelstudios** [comment]
@macumber It may be possible to remove those two Ruby dependencies entirely.  Now that we package Ruby 2.0 for linux, we might be able remove those and have the toolfinder default to our version rather than /usr/bin/ruby2.0 and /usr/bin/ruby.  I can't remember if we had a good reason to continue using the system versions...

**Comment by macumber** [comment]
I think I was confused, I thought we were talking about build time dependencies, are we talking about install time dependencies?  @pachi you are hitting issues when you try to install the OpenStudio debian package?  If that is the only case then I think it would be ok to remove the installer dependencies, would be interesting to test if the system Ruby 2.1 is compatible with our binaries.

**Comment by macumber** [comment]
Rather than add additional versions of Ruby I'd think we want to just remove any dependency on system Ruby right?

**Comment by macumber** [comment]
We may have been defaulted to system Ruby so @nllong could access gems that he installed?

**Comment by pachi** [comment]
Yes, I was talking about install time dependencies, as ruby20 and libruby20 is not available in any recent ubuntu or debian systems.

**Comment by pachi** [comment]
Could it be possible to bundle all those dependencies, excepting the libqt5 ones, with the distributed packages? The Boost and Ruby packages are not very big and bundling them would make easier installing the openstudio .deb package in almost any linux distro (the alien tool probably could convert it to RPM for Red Hat derived distros). 
Projects like LibreOffice bundle the interpreters they use (Python) to avoid this kind of problems

**Comment by pachi** [comment]
Recently released distros (ubuntu wily or debian sid) have also migrated from libboost1.55 to libboost 1.58, so removing this install-time dependency would make things smoother for them too.

**Comment by macumber** [comment]
@axelstudios and I discussed this and both of us lean towards static linking boost on Ubuntu (the only platform we don't do this on).  That way OpenStudio would not care what version of boost was on the system. However, @lefticus always recommended we do not do this, he knows a lot more about Linux than I do, maybe he can chime in?

PS: @axelstudios has played with this a bit and I think he ran into a few confusing problems.

**Comment by pachi** [comment]
IMHO, building libboost as a static library is not the solution, as maybe it's not designed to work that way. Instead, the path to the runtime libraries should be set, either using LD_LIBRARY_PATH or, better, using rpath and building the application with the LD_RUN_PATH variable set (e.g. LD_RUN_PATH='$ORIGIN/lib' and bundling these .so libraries in lib/). See this post for further information http://www.aimlesslygoingforward.com/2014/01/19/bundling-shared-libraries-on-linux/

**Comment by kbenne** [comment]
As of 2.0 I don't think this applies. I'm going to close, but please reopen if someone finds that it is still valid.

**Comment by macumber** [comment]
Did you make a change to the debian installer?  We should be able to relax the boost and maybe qt dependencies as well.
