### ISSUE TITLE
Crash when clicking on Solar Flat Plat Collector in Plant Loop

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/OpenStudio#1905]
I'm trying to create a simple model to test water-to-water heat exchangers connecting heat transfer from a solar thermal loop to a water tank. If I model an ICS plate, I can click on the object and edit inputs fine. If I model a flat plate, when I try to click on the object the OS app crashes.

I've tried attaching the models as *.osm and *.txt files, but apparently I need "write" access to do so.

**Comment by macumber** [comment]
Thanks @aaron-boranian , can you post a link to a file via dropbox or something?

**Comment by aaron-boranian** [comment]
... probably should have thought of that sooner :)

@macumber , you can find a Google Drive link to the files [HERE](https://drive.google.com/folderview?id=0B_SyIwm6jC9Mc1JSQTNtaUsxY0E&usp=sharing)

**Comment by macumber** [comment]
Great, I'll put these in our testing repo, thanks!

**Comment by macumber** [comment]
@aaron-boranian I can't reproduce this in 1.9.0 or 1.9.4, do you have any ideas on how to reproduce the crash?

![11-16-2015 3-49-16 pm](https://cloud.githubusercontent.com/assets/1327850/11197277/ae5d8de2-8c79-11e5-8e35-ddf4e168f205.jpg)

**Comment by macumber** [comment]
Am I clicking on the right thing?

**Comment by macumber** [comment]
@kbenne any gremlins you know of?  Maybe the clicking fast thing?

**Comment by aaron-boranian** [comment]
Hmm, would it matter that you're using 64-bit and I'm using 32-bit? Again, I can drag-and-drop the flat plate collector into a loop, but once I click on it's icon for editing, the app crashes.

![screen shot 2015-11-16 at 1 17 50 pm](https://cloud.githubusercontent.com/assets/15160917/11197888/912cb1d6-8c64-11e5-9cc4-686bbf4be814.png)

**Comment by macumber** [comment]
I downloaded the latest published 1.9.0 release in both 32 and 64 bits.  The 32 bit version does crash for me but the 64 bit installer does not so something is going on with that.  We'll look into it.

**Comment by aaron-boranian** [comment]
Weird. Glad that we could narrow it down to that at least.

**Comment by macumber** [comment]
I couldn't reproduce this with my own 32 bit build but I did confirm this still happens in the 32 bit 1.9.4 build.

**Comment by macumber** [comment]
Finally got a call stack on this with a RelWDebug build:

m_numNormalFields is being initialized to some crazy number

>	openstudio_model.dll!openstudio::model::AccessPolicy::getAccess(unsigned int index) Line 247	C++
 	openstudio_modeleditor.dll!InspectorGadget::layoutItems(QVBoxLayout * masterLayout, QWidget * parent, bool hideChildren) Line 316	C++
 	openstudio_modeleditor.dll!InspectorGadget::layoutModelObj(openstudio::WorkspaceObject & workspaceObj, bool force, bool recursive, bool locked, bool hideChildren) Line 233	C++
 	openstudio_modeleditor.dll!InspectorGadget::InspectorGadget(openstudio::WorkspaceObject & workspaceObj, int indent, ComboHighlightBridge * bridge, int precision, InspectorGadget::FLOAT_DISPLAY style, bool showComments, bool showAllFields, bool recursive, bool locked) Line 154	C++
 	openstudio_modeleditor.dll!InspectorGadget::layoutItems(QVBoxLayout * masterLayout, QWidget * parent, bool hideChildren) Line 408	C++
 	openstudio_modeleditor.dll!InspectorGadget::layoutModelObj(openstudio::WorkspaceObject & workspaceObj, bool force, bool recursive, bool locked, bool hideChildren) Line 233	C++
 	openstudio_lib.dll!openstudio::GenericInspectorView::layoutModelObject(openstudio::model::ModelObject & modelObject, bool readOnly, bool displayIP) Line 811	C++
 	openstudio_lib.dll!openstudio::InspectorView::layoutModelObject(boost::optional<openstudio::model::ModelObject> & modelObject, bool readOnly, bool displayIP) Line 692	C++
 	openstudio_lib.dll!openstudio::InspectorController::layoutModelObject(boost::optional<openstudio::model::ModelObject> & modelObject, bool readOnly) Line 117	C++
 	openstudio_lib.dll!openstudio::MainRightColumnController::inspectModelObject(boost::optional<openstudio::model::ModelObject> & modelObject, bool readOnly) Line 148	C++
 	openstudio_lib.dll!openstudio::HVACLayoutController::onModelObjectSelected(boost::optional<openstudio::model::ModelObject> & modelObject, bool readOnly) Line 847	C++
 	openstudio_lib.dll!QtPrivate::QSlotObject<void (__thiscall openstudio::HVACLayoutController::*)(boost::optional<openstudio::model::ModelObject> &,bool),QtPrivate::List<boost::optional<openstudio::model::ModelObject> &,bool>,void>::impl(int which, QtPrivate::QSlotObjectBase * this_, QObject * r, void * * a, bool * ret) Line 158	C++
