### ISSUE TITLE
Standard Report fails on model with zones with apostrophes in name

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1906]
1. Create a model
2. Put a ' in the name of the zone
3. Fails on performing a sql query

This may be true of other characters as well...probably should escape the queries somehow.

**Comment by mbadams5** [comment]
@asparke2 Do you know if this is specific to OS? If you manually run the query outside of OS App (or measure) does it work?

**Comment by asparke2** [comment]
@mbadams5 The raw sql query fails too (I loaded eplusout.sql file into SQLite manager and tested).

**Comment by DavidGoldwasser** [comment]
Is there way to alter the sql query to have this work with just change in OS? or does there need to be a change in E+.

**Comment by mbadams5** [comment]
@DavidGoldwasser This seems specific to OS. We need to escape the apostrophe when querying with it. Instead of string literals ('') we could use double quotes ("") which should avoid this issue or you can escape an apostrophe by putting another (') in front of it. So it would be `'it''s'` instead of `'it's'`.

**Comment by asparke2** [comment]
It would be ideal if the methods like sql::execAndReturnFirstDouble(query_string) would escape the query_string for you before running the query so that every person who writes a query doesn't have to re-create this in Ruby or whatever.  In some languages, there are built-in methods to do this, not sure if our C++ library has one or not.

**Comment by macumber** [comment]
Some queries do this for you when they are building a query and know which parts of it are the zone name.  It gets to be a pain because you may also have to capitalize names, I could see blindly escaping a user query but not capitalizing it for them

**Comment by macumber** [comment]
Is this really going to be fixed for 1.10? Sounds like there is not resolution on the fix yet.

**Comment by DavidGoldwasser** [comment]
@macumber and @asparke2 is it ok for now to just have this fail the specific table/section, or leave a blank value if feasible) but run the measure nicely. It seems the best place to fix the query is in C++ vs. the measure?

**Comment by DavidGoldwasser** [comment]
pull request will isolate this to problem section. Rest of report other than Zone Conditions will be generated.
https://github.com/NREL/OpenStudio/pull/1975

**Comment by DavidGoldwasser** [comment]
Looks like this isn't just about zone names but other objects. Below is link to post about design day objects.
https://unmethours.com/question/12533/simulation-fail-with-ddy-file/?answer=13166#post-id-13166

I don't think every query in a measure should have to check for this and correct the query. I think either core OpenStudio should address this (by fixing query for you or not allowing apostrophes in object names) or native to EnergyPlus.

I did test this with updated standard report, and it does trap this gracefully, but lose the entire model summary section vs, just the design day table (was much less code to change to trap section than to trap each table.)

**Comment by DavidGoldwasser** [comment]
@macumber let me know if you want this to be assigned to someone else.
