### ISSUE TITLE
HVAC Tab - Users may get lost in Water Use Connection object (Bugzilla #917)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#191]
On 2012-09-18 09:06:54, @DavidGoldwasser wrote:

> The Water Use Connection is kind of odd compared with the rest of the loop views in the HVAC systems tab. In every other situation you have access to the pulldown list to view any loop, and to the +/- to add or delete a loop.
> 
> I guess the reason for this is, maybe it isn't really a loop, but I still think maybe it could act like one, and be accessible in the pull down list. If we don't go that approach then maybe it could look like a pop up window (with a border and an "x" in the top right corner to close it). Ideally you would still see (maybe greyed out) typical interface with the pulldown showing the name of service water loop.
> 
> As it is now, until you start dragging your mouse around and stumble on the mouse over text, you don't know how to go back to main editor. Maybe a stop-gab solution is to write on the screen below the objects "click to go back to main editor" much like you do for the drop zone where you say "Drag Water Use Equipment form Library". By the way, another note, that text is very small.

On 2012-09-18 09:22:51, @kbenne wrote:

> Suggest having a discussion with Andrew about alternative designs.  I was originally thinking of having a sub tab for service water connections.  So then inside the hvac tab there would be sub tabs for "HVAC Loops" and "Service Water".  I do not think this is a bug but a request for design change and should find a better home then bugzilla.

**Comment by evanweaver** [comment]
Closed due to lack of demand.
