### ISSUE TITLE
Open Studio does not provide an error message when running VRF systems without cooling or heating schedules.

### ISSUE THREAD

**Issue by EnergyExpert** [NREL/OpenStudio#1916]
When performing a simple 5 zone VRF job in Open Studio I noticed that the job ran but that the cooling and heating kwh and the zone sizing reports were all providing unusual results.  As I began to investigate I discovered that the job had run even without an assigned heating and cooling setpoint schedule.  This error should be caught during runtime.

**Comment by DavidGoldwasser** [comment]
@asparke2 and @kbenne do you think this is more related to pre-flight check  or QAQC report vs. something we should catch at run time.

**Comment by macumber** [comment]
@kbenne please tag this for 1.10.0 if you would like to fix it for the release

**Comment by kbenne** [comment]
Not sure what to do here. It seems like the only mechanism we really have is QAQC report. Exposing the translator logs would be an option, but I don't feel like those are in a condition to expose to an end user.

**Comment by asparke2** [comment]
This seems like it should be bumped to the E+ issues

**Comment by kbenne** [comment]
Ok then I recommend that we close and suggest that @EnergyExpert file this on E+.
