### ISSUE TITLE
ZoneVentilation:DesignFlowRate won't work on zones without any zone equipment.

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1919]
Currently If using on building without HVAC (or with Ideal Air Loads) I need to add in a dummy exhaust fan with CFM = 0 to avoid these errors.

Severe IP: IDF line~1632 Object=ZONEHVAC:EQUIPMENTLIST, name=STORY 2 CORE ZONE EQUIPMENT LIST, Required Field=[Zone Equipment 1 Object Type] was blank.
Severe IP: IDF line~1632 Object=ZONEHVAC:EQUIPMENTLIST, name=STORY 2 CORE ZONE EQUIPMENT LIST, Required Field=[Zone Equipment 1 Name] was blank.
Severe IP: IDF line~1632 Object=ZONEHVAC:EQUIPMENTLIST, name=STORY 2 CORE ZONE EQUIPMENT LIST, Required Field=[Zone Equipment 1 Cooling Sequence] was blank.
Severe IP: IDF line~1632 Object=ZONEHVAC:EQUIPMENTLIST, name=STORY 2 CORE ZONE EQUIPMENT LIST, Required Field=[Zone Equipment 1 Heating or No-Load Sequence] was blank.

**Comment by DavidGoldwasser** [comment]
Just to add some detail. Instead of having the user manually add exhaust to seed model I added code to add exhaust object to the measure I'm working on. If the exhaust is added after ZoneVentilation it still fails. If I associate the exhaust with the zone first and then the zone ventilation, it runs. I assume it should run with either configuration, as well as with zone ventilation only.

**Comment by macumber** [comment]
@kbenne please tag this for 1.10.0 if you would like to fix it for the release
