### ISSUE TITLE
SketchUp Plugin doors default to "glass door" vs. door

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1924]
As a user pointed out, this causes issue because we don't have a glass door in our construction set, but it also changes the solar gain vs. a opaque door.
https://unmethours.com/question/12334/glass-door-as-the-default-door-but-with-problem/

@macumber I don't think we have messed with this code in a while.

**Comment by macumber** [comment]
I bet the change is related to any changes in construction->isFenestration:

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/SubSurface.cpp#L756
