### ISSUE TITLE
GBXML Export Uses wrong Coordinate Geometry

### ISSUE THREAD

**Issue by AWintersmith** [NREL/OpenStudio#1925]
I’m using Open Studio v1.9.

When exporting as GBXML is appears Open Studio does NOT comply with the published GBXML Schema, in particular the Coordinate Geometry. The official schema calls for a Decimal format and not floating point. In reviewing the GXML is is ovbious that floating point has been used and this violates the schema.

This prevents the GBXML file from importing to Energy Pro v6.6.

Example from the larger file:
<
Coordinate>58.5881</Coordinate
>
<
Coordinate>10.0787</Coordinate
>
<
Coordinate>1.32848e-13</Coordinate
>
 
Note the third item specification.

I have attached the complete XML file EXCEPT I CHANGED THE FILE EXTENSION TO TXT INSTEAD OF XML so that it could be attached.
Aaron W.

**Comment by macumber** [comment]
Thanks @AWintersmith, I was unaware of this issue.  @chiensiTB FYI

**Comment by AWintersmith** [comment]
It appears to occur when the coordinate is very close to zero. 
My manual fix to date has been to override these values to zero. Perhaps this is the appropriate fix for the software as well.
