### ISSUE TITLE
PAT XML Export is missing cash flow results in 1.9

### ISSUE THREAD

**Issue by andrulis** [NREL/OpenStudio#1932]
It seems the upgrade to Energy Plus included with OS 1.9 has broken the Xcel EDA Reporting and QAQC measures reporting of the life-cycle costs.  When examining the Results.xml file generated from PAT,  the cash flows are all 0 even though the PAT UI is showing non-zero results.

**Comment by asparke2** [comment]
@andrulis Can you clear the results and send me a .zip of the PAT project directory?

**Comment by chrisbalbach** [comment]
Andrew / Rich:

You both should have received a dropbox link to a zip file of what was requested below.

Let me know if you have issues.

Thanks,

_Chris

**Comment by asparke2** [comment]
@andrulis @chrisbalbach This issue is happening because you are using quite an old version of the "Xcel EDA Reporting and QAQC Measure" which didn't export the cash flows.  Download a newer version from the BCL, then click "Sync Measures with Library" in PAT to update this PAT project.
