### ISSUE TITLE
Standard Report fails on models with Schedule:Year objects used in the thermostat

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1933]
If you have a thermostat with a schedule:year used, the measure fails.  This isn't likely to happen via the GUI.  The model that exhibits this issue is from CBECC-Com.

I think the solution is to change this line:
https://github.com/NREL/OpenStudio/blob/5c16ad12b27e371c869d52ba73848c09953c5b27/openstudiocore/src/pat_app/Measures/StandardReports/resources/os_lib_schedules.rb#L89

from:
 
result = nil
 
to:
 
result = { 'min' => nil, 'max' => nil }

Not sure of all the places os_lib_schedules is used.

**Comment by DavidGoldwasser** [comment]
Solution for this will be to make the reporting measure leave blank values for thermostat temperature range if users don't use ruleset schedule vs. failing which is what happens now. This way the measure measure will run, but the table will just have a few blank cells.

We could use API to get min-max range for other schedule types, but I'd like to avoid that.

**Comment by DavidGoldwasser** [comment]
With pull request it will show message that it can't calculate temp range if not all schedules are ruleset.
https://github.com/NREL/OpenStudio/pull/1975
