### ISSUE TITLE
Controller:WaterCoil node references not cleaned up on airloop edit

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1936]
Issue came from the latest comment to the answer in [this Unmet Hours Post](https://unmethours.com/question/1566/severe-error-caused-by-controller-mechanical-ventilation-openstudio-150/)

1. Create a model with a template PVAV
2. Delete the Fan:VariableVolume
3. Add a Fan:ConstantVolume in the same place
4. Fails with error:

    ** Severe  ** HVACControllers: Missing temperature setpoint for controller type=Controller:WaterCoil    Name="CONTROLLER WATER COIL 1"
   **   ~~~   ** Node Referenced (by Controller)=NODE 15

I think what's happening is that when you delete the fan, you are deleting it's outlet node.  However, the water coil controller keeps referencing the old outlet node (which doesn't exist anymore) instead of getting hooked to the new node.

**Comment by asparke2** [comment]
Files have been added to [OpenStudio-files](https://github.com/NREL/OpenStudio-files/tree/master/Git%20Issue%20Files/Issue%201936).  `Template HVAC.osm` is the model saved after step 1 above, `Template HVAC VAV to CAV.osm` is the model saved after step 3.

**Comment by asparke2** [comment]
## Temporary Workaround

1. Determine the correct name of the water coil outlet node

![step1](https://cloud.githubusercontent.com/assets/2009290/10954918/a0d928c2-830d-11e5-9b90-f24ca514fb80.png)

2. Set the water coil controller to reference this node

![step2](https://cloud.githubusercontent.com/assets/2009290/10954924/a59311d4-830d-11e5-9cf2-dd29ef952722.png)

**Comment by kbenne** [comment]
@people I think the best answer is leaving the control nodes unset by default in the model. If they are still blank on translation then set them to the appropriate default. If they have a value, (from user presumably) then respect that at all costs and assuming whoever set that knew what they were doing. This is consistent with other OS defaulting around SPMs. Thoughts? 

I think there is one implementation wrinkle is that the controllers are only associated with their coils through nodes. I'm not yet sure what exactly I have to do to work around that but it might require a new field to directly refer to the associated coil, and thus a data transition. In any case I think this is the correct course of action.

**Comment by asparke2** [comment]
That logic works for me.

**Comment by kbenne** [comment]
@asparke2 one thing I noticed working on this is that when you drop a coil we are defaulting CoilHeatingWater to "normal" action, and CoilCoolingWater to "reverse". I recall some oscillation on this, perhaps motivated by asset score, I can't remember, but it seems like maybe we should be consistent. Care to comment?

**Comment by asparke2** [comment]
@kbenne We should keep the defaults the way they are. IMO this is a dumb field in E+.  It means "does the air heat up when the valve opens (normal) or does the air cool down when the valve opens (reverse)."  This is something that E+ should be able to infer based on what type of coil the controller is controlling so that users don't have a way to mess it up.  It isn't the same as the reverse/normal in VAV dampers, where either option is actually valid.

**Comment by kbenne** [comment]
So it is. I think my brain got mangled on thinking about about damper action on terminals which uses the same terms, but something different.

**Comment by asparke2** [comment]
I knew exactly what you were thinking as soon as I read the comment :)

**Comment by kbenne** [comment]
in any case i think this is a good change. It should really improve the robustness of the relationship between controller and coil. Just need to keep an eye out for errors in transitions, but I have scrutinized the simulation tests and they look good.

**Comment by MatthewSteen** [comment]
Just found this :gift: under the 1.10.0 :christmas_tree:
