### ISSUE TITLE
Calibration queries do not work without variable request workaround

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1939]
The following code will fail to return a value for the modelConsumption unless the last 5 output variables are present in the issue file, these are related to the [workaround code](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/runmanager/lib/EnergyPlusPreProcessJob.cpp) that was added to address #1699

```
require 'openstudio'
model = OpenStudio::Model::Model.load('in.osm').get
sqlFile = OpenStudio::SqlFile.new('eplusout.sql')
model.setSqlFile(sqlFile)
puts model.getUtilityBills[0].CVRMSE.to_i
puts model.getUtilityBills[1].billingPeriods[0].consumption.to_i
puts model.getUtilityBills[1].billingPeriods[0].modelConsumption.to_i
```

**Comment by macumber** [comment]
@mbadams5 FYI

**Comment by macumber** [comment]
I can see timeseries in resultsviewer in both cases so I am not sure if this is an E+ issue or an OpenStudio one.

**Comment by brianlball** [comment]
@nllong @henryHorsey Should the workflow-gem run this E+preprocess code now?

**Comment by nllong** [comment]
i can add this. @macumber, you are talking about this right (https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/runmanager/lib/EnergyPlusPreProcessJob.cpp#L276-L525 <https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/runmanager/lib/EnergyPlusPreProcessJob.cpp#L276-L525>)?

Thanks

**Comment by macumber** [comment]
It's more 150-240 and 502-519 but ideally the whole thing should be duplicated

**Comment by mbadams5** [comment]
I'm curious why the workaround is still needed when using E+ 8.4. It should be fixed.

**Comment by rHorsey** [comment]
If it's not a problem that would be great, but otherwise I can add it into the workflow gem, if Nick hasn't already.

**Comment by nllong** [comment]
okay, i think we fixed this issue now. it was more than what is in the EnergyPlusPreProcessJob.cpp. After adding in these (https://github.com/NREL/OpenStudio-workflow-gem/commit/323cfd27a07c4f5cff14016b76c02f95a5fb41f1), the report seemed to show up.

**Comment by nllong** [comment]
And it appears that I only fixed it for EnergyPlus 8.3. EnergyPlus 8.4 on the server is still not working right.

**Comment by brianlball** [comment]
@macumber, what did you add to the seed model to get it to work on the server before?

**Comment by macumber** [comment]
I just added those report variables in my email:

    OS:Output:Variable, {393572af-306b-4e1f-9b96-0e550ef1a764}, Output 1, *, Site Outdoor Air Drybulb Temperature, monthly;

    OS:Output:Variable, {4ff41263-e911-46a0-853f-2101863bfee3}, Output 2, *, Zone Air Temperature, hourly;

    OS:Output:Variable, {de58eb6f-cbe0-46cb-a991-4b56c2965416}, Output 3, *, Zone Air Relative Humidity, hourly;

    OS:Output:Variable, {914fbe02-f6bf-47f4-8971-52c55a4a442c}, Output 4, *, Site Outdoor Air Drybulb Temperature, timestep;

    OS:Output:Variable, {fbdffbb9-e96a-468d-bd17-4a2f3d1a799d}, Output 5, *, Site Outdoor Air Drybulb Temperature, daily;

**Comment by rHorsey** [comment]
@macumber I'm keeping the #1699 workaround in the updated WFG, correct?

**Comment by macumber** [comment]
Yes

**Comment by ljbrackney** [comment]
Is this still an issue as of 2.1.0?

**Comment by rHorsey** [comment]
My memory is that this is fixed. It may now be fixed in two places. the #1699 workaround is still in the WFG - see https://github.com/NREL/OpenStudio-workflow-gem/blob/develop/lib/openstudio/workflow/util/energyplus.rb#L201-L210

This can be closed.
