### ISSUE TITLE
Can't surface match entire model from within a space (Bugzilla #921)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#194]
On 2012-09-18 13:56:42, @DavidGoldwasser wrote:

> If I remember when you surface match entire model, the script does a select all, because you are within a SketchUp group, SketchUp doesn't select everything else, this could be fixed by not relying on the the SketchUp Selection.
> 
> This is pretty minor and work around is to back out of space, but just wanted to document it.

**Comment by jmarrec** [comment]
Moved to https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/71
