### ISSUE TITLE
OSM templates are 1.5.0

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1944]
These are pretty old, takes time at start up, we should update these for release

**Comment by mostaphaRoudsari** [comment]
Oh! So did I just replaced an old version with an older version of template here https://github.com/mostaphaRoudsari/Honeybee/issues/126. The link wasn't working so I just assumed the version which comes with OpenStudio is the latest. oops.

**Comment by macumber** [comment]
No I am talking about the OSM files shipped to support the SketchUp plugin, not the JSON file.  We need to remake the OSM files based on the current JSON.

**Comment by mostaphaRoudsari** [comment]
Ah! Great to know. Thanks.

**Comment by DavidGoldwasser** [comment]
@macumber once we update the space type and construction set wizard to use the new standards gem, could we make the OSM's as part of the OpenStudio build process vs. keeping static OSM's in the code base? Then it would always be new.

**Comment by macumber** [comment]
These are the files to update:

openstudio\openstudiocore\ruby\openstudio\sketchup_plugin\resources\templates

openstudio\openstudiocore\src\openstudio_app\Resources
