### ISSUE TITLE
OS 1.9 loses space loads when converting v1.8 model

### ISSUE THREAD

**Issue by CUEBoxer** [NREL/OpenStudio#1948]
When a version 1,8 model is opened in OS 1.9, it seems that all space loads (lights, people, equipment) are erased.

**Comment by ljbrackney** [comment]
If you're looking at the loads sub tab under the spaces tab and not seeing them, they are still there just not displayed. You will see them correctly displayed under the space type definitions tab.

This was an incomplete portion of grid view in 1.9.0 - inherited data was not displayed. The feature was completed in 1.9.1 or 1.9.2 - can't recall which. This was also addressed in an Unmet Hours question.

On Nov 12, 2015, at 6:27 AM, CUEBoxer <notifications@github.com<mailto:notifications@github.com>> wrote:


When a version 1,8 model is opened in OS 1.9, it seems that all space loads (lights, people, equipment) are erased.

-
