### ISSUE TITLE
PAT and ResultsViewer 1.9.3 won't launch

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#1949]
Using windows, I can't launch either PAT or ResultsViewer, whether from the OS App or directly. Rebooting had no effect.
Both of them suffer from the same behavior: I can see the instance(s) (usually several...) in the Task manager, but I can't successfully terminate them (it says success but they are not removed from the list of tasks) using the task manager or an elevator cmd with taskill.
They have a little bit over 100K of memory use, and 0% CPU.

**Comment by evanweaver** [comment]
@jmarrec, what version of Windows are you using, and with what version of OpenStudio did you first notice the issue? Have you tried to rollback to the last version of OpenStudio which worked successfully for you, and does it still work now?

**Comment by jmarrec** [comment]
@evanweaver : Win 7 x64 SP1.
I have both 192 and 193 installed. 192 works fine.
193 only the OS App works.

The un-installation program of 193 exhibits the same behavior as well...

I'm the only one who has this problem apparently, I asked several people to check (including @macumber, @kbenne  and @mbadams5) and it worked fine for them.

**Comment by evanweaver** [comment]
Thanks for the detective work @jmarrec. I installed v1.9.3 on a clean Windows VM, and had no problems. I did post v1.9.4 this morning, if you'd like to try it.

**Comment by jmarrec** [comment]
First I need to figure out how to uninstall this 1.9.3... :)

**Comment by jmarrec** [comment]
Waaaaaw. I installed OpenStudio 1.9.4 and even the OS App won't work now. I smell a clean install of windows... :(

**Comment by jmarrec** [comment]
Just as an FYI, I wiped my computer clean and no longer experience this problem
