### ISSUE TITLE
Merge spaces from external model isn't robust enough to handle daylighting objects (Bugzilla #924)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#195]
On 2012-09-18 16:01:06, @DavidGoldwasser wrote:

> When I first tested this I used a model with spaces hooked up to HVAC, and no child loads.
> 
> Testing today in model with daylighting objects it failed. This model also had water equipment associated with a space, so that may also have been an issue. I expect this will be fixed post 0.9.0.

On 2012-09-18 16:18:39, @DavidGoldwasser wrote:

> Created an attachment (id=222)
> Model A

On 2012-09-18 16:19:03, @DavidGoldwasser wrote:

> Created an attachment (id=223)
> Model C
> 
> Merge A to C or C to A

Original attachments:
- HotelSouthWindows_a.osm (ID 222)
- HotelSouthWindows_c.osm (ID 223)

**Comment by jmarrec** [comment]
Moved to https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/72
