### ISSUE TITLE
OS App 1.9.4 crashes in Apply Now when changing selected measure

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#1956]
In `1.9.4` if I go to "Apply Now", then select a measure, it goes fine.

But If I try to go an select another measure after I clicked on the first one, OS App crashes.

I'm on Win-x64 10

**Comment by macumber** [comment]
I've been able to reproduce this in Windows 10 but not Windows 7.  @axelstudios @evanweaver could one of you make a debug or release with debug build on Windows 10 and see if we can get a call stack?

**Comment by macumber** [comment]
This was possibly fixed by https://github.com/NREL/OpenStudio/commit/12bee679aa4890e5cc5192bd6a80efdba1f1046a

Need to confirm the fix in 1.9.5 build

@evanweaver @axelstudios FYI

**Comment by evanweaver** [comment]
Fixed in v1.9.5, as noted above by Dan.

**Comment by macumber** [comment]
@evanweaver did you test using a 1.9.5 build?

**Comment by evanweaver** [comment]
No, v1.9.0.

**Comment by evanweaver** [comment]
Yes, of course :)

**Comment by jmarrec** [comment]
(When is 1.9.5 due out of curiosity? A link to a schedule of dev and official releases would be welcomed if that exists!)

**Comment by evanweaver** [comment]
It will be available tomorrow, unless @macumber @kbenne or @DavidGoldwasser want to push other code changes in. Then, due to a long Thanksgiving weekend, 1.9.5 will not be available until late next week.

**Comment by DavidGoldwasser** [comment]
@evanweaver my changes can wait until next iteration.

**Comment by jmarrec** [comment]
Do you plan to do a 1.9.6 before 1.10.0 aka "the holiday gift (tm)" then?

Envoyé de mon iPhone

**Comment by evanweaver** [comment]
Potentially, but I need to review this with Luigi before I can comment with certainty.

**Comment by ljbrackney** [comment]
I believe the next scheduled iteration build will be 1.10.0

On Nov 24, 2015, at 1:27 PM, evanweaver <notifications@github.com<mailto:notifications@github.com>> wrote:


Potentially, but I need to review this with Luigi before I can comment with certainty.

-
