### ISSUE TITLE
Building of OpenStudio no Mac doesn't find EnergyPlus or Radiance

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1959]
Setting up fresh build on Mac, when launching GUI scan for tools doesn't find EnergyPlus or Radiance. I didn't manually installer either EnergyPlus or Radiance.

**Comment by muh182** [comment]
I had a fresh build (v 1.9.4) about 10 days ago on my new mac. I also did not manually installed E+. The app was able to find EnergyPlus in the build directory. I did not try Radiance.

**Comment by DavidGoldwasser** [comment]
Thanks, that's good to know, may be something unique to my machine.

**Comment by DavidGoldwasser** [comment]
Just tried to run with 1.10.1 on my development build, and it works now. So I'll close this.
