### ISSUE TITLE
Construction Tab - View doesn't always refresh on deleting material (Bugzilla #925)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#196]
On 2012-09-18 16:48:53, @DavidGoldwasser wrote:

> Typical when I delete a material (middle or end) it disappears when I click the "x", but in some cases I need to change to another object and back to see it refresh.
> 
> Steps to repeat
> - Launch OS App
> - Go to Constructions sub tab
> - From library drag in "ASHRAE_189.1-2009_ExtRoof_IEAD_ClimateZone 2-5"
> - Delete the Metal Decking layer (if like my machine you won't see it disappear
> - Make a new material and then go back to the previous one and the "Metal Decking" will be gone.
> 
> - Now drag the same exterior construction over again, and delete the material from the new copy. It works now (so seems to be more about sequence of events than which object it is.
> - But now try to delete Roof insulation. It doesn't work.
> - Go to the original one and delete Roof insulation. For me it didn't work, but if I keep trying it will work again and then break, can't figure out a pattern or logic. I can see this on new constructions and on constructions brought in from library.
> - It does seem to only occur on an inside material, and not on a middle or outside material. For example on a new file bring in the exterior wall again and start deleting from the outside layer. the first to materials delete, but when just one left it didn't (rather it didn't refresh)
> 
> FYI - my testing is based on build made last night.

On 2012-09-18 16:52:13, @DavidGoldwasser wrote:

> While not a crash bug since it relates to new feature think it should be in 0.9.0

**Comment by evanweaver** [comment]
@DavidGoldwasser @macumber Following David's steps, works for me.
