### ISSUE TITLE
Render by surface type leaaves some surfaces transparent

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1963]
Reported here, https://unmethours.com/question/12853/set-render-by-surfacetype-colour-in-openstudio/

File in issues repo

**Comment by macumber** [comment]
Probably being misclassified as air walls

**Comment by DavidGoldwasser** [comment]
Could be good corner test case for view_model measure as well.

**Comment by macumber** [comment]
Looks like this has been the behavior for some time, there is even a test around it:

https://github.com/NREL/OpenStudio/blame/develop/openstudiocore/src/model/test/Surface_GTest.cpp#L443

I am open to changing this but I wonder if that will cause other issues?

@DavidGoldwasser @asparke2 @rpg777 any thoughts on changing the behavior so surfaces with empty constructions are not classified as air walls?

**Comment by macumber** [comment]
https://github.com/NREL/OpenStudio/blame/develop/openstudiocore/src/model/PlanarSurface.cpp#L230

**Comment by rpg777** [comment]
Seems like a gross assumption to me, anyway. The OpenStudio/Radiance docs state that if you want a surface to go away you need to explicitly set that surface's construction to air wall.

**Comment by DavidGoldwasser** [comment]
I think a surface with an empty construction should just fail when you run EnergyPlus, ideally we issue a warning on forward translation to IDF. Render by Construction could just render it as white, which is similar to what would be done to a space if it doesn't have a thermal zone assigned.
