### ISSUE TITLE
OpenStudio plugin does not import shading:site

### ISSUE THREAD

**Issue by FarhangTahmasebi** [NREL/OpenStudio#1966]
OpenStudio plugin 1.9.0.7514aa6d3b does not import shading:site:detailed and shading:site objects from a EnergyPlus model. The EnergyPlus model I tested is 8.4.0 and not 8.3.0, but I doubt that this is the reason.

**Comment by macumber** [comment]
OpenStudio only works with one version of EnergyPlus at a time so this might well be the issue.  Could you try either importing your E+ 8.4 model into the current [iteration build of OpenStudio](https://www.openstudio.net/developers) which is updated to E+ 8.4 or try importing an 8.3 version of your file into OpenStudio 1.9.0?

**Comment by FarhangTahmasebi** [comment]
I tried the current iteration build (1.9.4). It was also not able to show the shading:site object when importing the IDF file.

**Comment by DavidGoldwasser** [comment]
Hmm, this worked on mac with some of the test E+ files. Maybe there is something unique about the IDF file you are importing. Try importing 4ZoneWithShading_Simple_1.idf and see if that works. If it does and the other file you have doesn't, then email the file to OpenStudio@nrel.gov

**Comment by FarhangTahmasebi** [comment]
Thanks David.
With that example it works. With my file not. I will email my file to the address.

**Comment by macumber** [comment]
Added file to user files
