### ISSUE TITLE
Using "x2" in app on thermal zone removes thermostat from other zones that used it.

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1969]
When you use the "x2" button on a thermal zone the end result is that the newly made zone has the thermostat assigned, but it is un-assigned from the source zone for the "x2" action. Additionally any other zones that might have shared that thermostat also loose it.

This happens to thermostats assigned in The SketchUp plugin and thermostats created in OS app (or presumably measures). See screenshots below of before and after "x2" action.

![screen shot 2015-11-24 at 12 39 04 pm](https://cloud.githubusercontent.com/assets/4857055/11378557/0f6168f4-92a9-11e5-9295-1dd53fa0d41d.png)
before x2

![screen shot 2015-11-24 at 12 39 29 pm](https://cloud.githubusercontent.com/assets/4857055/11378569/17fc869c-92a9-11e5-938c-696ce65cadff.png)
after x2

If you try this on Thermal Zone 3 you get similar behavior. FYI - I don't think tons of people clone thermal zones in the GUI, so not a lot of people hit this (I have not seen a report of it before) so not critical for 1.10 if there are other things to work on instead.

**Comment by DavidGoldwasser** [comment]
related to issue #123 and issue #985

**Comment by DavidGoldwasser** [comment]
@kbenne and @macumber should we do something to fix this when cloning a zone in OS app? Should it also clone the thermostat

**Comment by kbenne** [comment]
I think this bug is obsolete. See code [here](https://github.com/NREL/OpenStudio/blob/a9a4fa38a748dba2d8e4a9582a13a851361ecf15/openstudiocore/src/model/ThermalZone.cpp#L1943) and tests [here](https://github.com/NREL/OpenStudio/blob/a9a4fa38a748dba2d8e4a9582a13a851361ecf15/openstudiocore/src/model/test/ThermalZone_GTest.cpp#L569).

**Comment by kbenne** [comment]
@DavidGoldwasser

**Comment by macumber** [comment]
@DavidGoldwasser can you test this and close?

**Comment by DavidGoldwasser** [comment]
Looks good, just tested in OS app.
