### ISSUE TITLE
Add missing dual duct terminal types.

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#1973]
We currently only have AirTerminalDualDuctVAV

**Comment by DavidGoldwasser** [comment]
@kbenne I assume this still needed for 1.12.0 I'll put as Major severity if that is the case, to make sure we don't filter it out.

**Comment by kbenne** [comment]
TODO

* Add AirTerminal:DualDuct:VAV:OutdoorAir
* Add AirTerminal:DualDuct:ConstantVolume
