### ISSUE TITLE
View_data Measure Doesn't Rotate Shading Surfaces when North Axis is Rotated

### ISSUE THREAD

**Issue by pflaumingo** [NREL/OpenStudio#1984]
When using the view_data measure the report.html file doesn't rotate the ShadingSurfaces with the geometry as the image below shows. In this example the North Axis was rotated 90 degrees.
![viewdata90degreerotation](https://cloud.githubusercontent.com/assets/15233892/11545084/2df75f92-98fa-11e5-8b02-e97c8a2789e3.PNG)

OpenStudio v1.9.5 was used for this simulation.

**Comment by macumber** [comment]
Moving to https://github.com/macumber/openstudio-vA3C/issues/37
