### ISSUE TITLE
Infiltration objects with no schedule produce no infiltration

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1998]
VirtualPulse team reported that if you have infiltration objects with no schedule the simulation will run but will not produce infiltration.  I thought that other load types (e.g. lights) would error out with no schedule, surprising to hear that infiltration does not do the same.  Need to check all the loads, maybe error out at translation to E+ instead of simulation time?

**Comment by macumber** [comment]
Default in OS App is blank schedule, this can be supplied by the schedule set if that is present.

**Comment by jmarrec** [comment]
Not true anymore, E+ throws on it, which I'm perfectly fine with

```
   ** Severe  ** <root>[ZoneInfiltration:DesignFlowRate][Space Infiltration Design Flow Rate 1] - Missing required property 'schedule_name'.
   ** Severe  ** <root>[ZoneInfiltration:EffectiveLeakageArea][Space Infiltration Effective Leakage Area 1] - Missing required property 'schedule_name'.
   ** Severe  ** <root>[ZoneInfiltration:FlowCoefficient][Space Infiltration Flow Coefficient 1] - Missing required property 'schedule_name'.

```
