### ISSUE TITLE
Copying a measure produces invalid measure if "ended" is in description string (probably also issue in name and modeler description)

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2001]
Reported by @DavidGoldwasser when copying this measure https://bcl.nrel.gov/node/83274

**Comment by DavidGoldwasser** [comment]
@macumber there is something else going on here. I have the same issue on a copy of the measure where I added 'return' to the front of the name, description, and modeler description.
https://github.com/NREL/OpenStudio-files/tree/master/Git%20Issue%20Files/Issue%202001/example_report

Fan Assist Night Ventilation which has return also exhibits this issue.
https://github.com/NREL/OpenStudio-measures/blob/develop/NREL%20working%20measures/fan_assist_night_ventilation/measure.rb

Yet the standard results measure (what is in Core and this copy on measures repo) doesn't have the 'return' at the beginning of the measure but clones fine.
https://github.com/NREL/OpenStudio-measures/tree/develop/NREL%20working%20measures/openstudio_results.

@macumber can I piggy back the lack of test files in cloned measure with this, or should that be a different issue.

For reference below are pre and post clone images. These are before adding "return" but results are similar.

<img width="1440" alt="screen shot 2015-12-11 at 3 33 28 pm" src="https://cloud.githubusercontent.com/assets/4857055/11760128/473ebc40-a04b-11e5-8ba8-0a915ce3bd97.png">

<img width="1440" alt="screen shot 2015-12-11 at 3 34 15 pm" src="https://cloud.githubusercontent.com/assets/4857055/11760129/4c77e24a-a04b-11e5-8dfc-3df8807b910f.png">

**Comment by DavidGoldwasser** [comment]
@macumber remove "intended" from the description and things work fine. My guess is somehow having "ended" in the string upsets it, even as part of another work. Fan assisted Night ventilation does the same thing. I guess I should stop saying "This measure is intended to be used to ..." :)

**Comment by DavidGoldwasser** [comment]
FYI - back to test tests. When we did clone the tests directory the test was broken because it referred to the class of the old measure and not the new one.

```ruby
    # create an instance of the measure
    measure = AddRooftopPV.new
```

**Comment by DavidGoldwasser** [comment]
@macumber seems the tests not being copied is a bit of an edge case. If I have a measure named "My Measure" and I clone it the default name of the new measure is "My Measure Copy". If I don't change that name tests don't clone. Even changing the name to "xMy Measure Copy" still doesn't have tests, but if I re-name it "Some New Name" then the tests get copied over fine.

**Comment by DavidGoldwasser** [comment]
Thanks Hal, looks good.
