### ISSUE TITLE
GUI Configuration Failure - OS 1.9.0 and 1.9.5 for Load Profile Plant Object 

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/OpenStudio#2003]
The OS App GUI for this object will not accept a schedule change for the flow rate fraction schedule name object. The default value "Always ON Discrete 1" cannot be changed. 

Tested in both OS 1.9.0 and 1.9.5 using Win64 bit installations. Failure in both.

**Comment by kbenne** [comment]
I just tested this on Mac and Windows 7, with OS 1.9.0. It looked OK to me. The key is to use a fractional schedule.

<img width="1554" alt="screen shot 2015-12-15 at 10 51 34 am" src="https://cloud.githubusercontent.com/assets/707488/11817294/ecee5e2c-a319-11e5-9f69-cd195337b35a.png">

<img width="1554" alt="screen shot 2015-12-15 at 10 39 05 am" src="https://cloud.githubusercontent.com/assets/707488/11817349/2647a1ec-a31a-11e5-8067-3b1c2bde4e32.png">

**Comment by kbenne** [comment]
@chrisbalbach I also exported the Model to idf, which checked out.

**Comment by chrisbalbach** [comment]
Thanks Kyle – I’m moving tooo fast..

_Chris

**Comment by kbenne** [comment]
I will close, but you are welcome to reopen if something is still lurking.
