### ISSUE TITLE
64 bit C# bindings have a 32 bit dll

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#2004]
Everything that I have checked in the 64 bit Windows OpenStudio package is 64 bit as expected. But in trying to run a test program I ran into trouble and determined that one DLL in particular was of the wrong architecture (32 bit). This is the DLL located in the installation at CSharp\openstudio\OpenStudio.dll. This prevents the 64 bit C# bindings from working. 

I used the following to determine architecture. 

```dumpbin /headers C:\path\to\dll | findstr machine```

**Comment by kbenne** [comment]
ping @evanweaver and @axelstudios

**Comment by axelstudios** [comment]
I'm seeing that with v1.9.4 at least.  Any idea when this began?

**Comment by axelstudios** [comment]
I guess a better question is what problem is this causing and how are you reproducing it?  Just checked v1.8.0, and that one is also 32-bit.

**Comment by macumber** [comment]
I would think this would trip up @mostaphaRoudsari in grasshopper?

**Comment by macumber** [comment]
@kbenne did you try building in 64 bit mode and running using the 64 bit openstudio binaries?

**Comment by kbenne** [comment]
There are test VS projects in CSharp\examples that demonstrate the C# bindings. These will not compile in the 64 bit package. 

@macumber yes.

**Comment by kbenne** [comment]
can't load that 32 bit DLL into my 64 bit app.

**Comment by kbenne** [comment]
uh oh i might have to backtrack. I see now that my 64 bit app goes to a different directory. bin\x64. It seems to be working... ducking... 

however this does seems a little concerning. The fact remains that 32 bit library is still floating around in there.

**Comment by kbenne** [comment]
closing... But don't say I didn't warn you if this turns out to be a problem down the road!
