### ISSUE TITLE
Envelope section of standard report gives error if air wall used on exterior walls

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2006]
![screen shot 2015-12-17 at 3 13 09 pm](https://cloud.githubusercontent.com/assets/4857055/11883576/2a569fdc-a4d1-11e5-9914-a7c7ebefd934.png)

![screen shot 2015-12-17 at 3 19 04 pm](https://cloud.githubusercontent.com/assets/4857055/11883626/8a1b9300-a4d1-11e5-91a5-7d9168049e54.png)

If this happens I can either skip just this construction and add a warning, or skip the entire section more gracefully than the error shown above. Unless there is some way for me to get the air wall thermal conductance out of the air wall.

Bad optional is happening in loop of base surfaces here
https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/pat_app/Measures/StandardReports/resources/os_lib_reporting.rb#L1608

**Comment by DavidGoldwasser** [comment]
@macumber I assume you don't want to touch anything about this in C++. It is interesting that the construction has same name in E+ as OS,

**Comment by macumber** [comment]
Well if it's a bug then we should fix it, what is the c++ fix?

**Comment by DavidGoldwasser** [comment]
construction.thermalConductance.get should return a value even when that construction happens to be an air wall. It is unique from other constructions in that it has a single layer of an "Air Wall" material. I believe forward translation replaces that with a specific standard opaque material. In this process it seems the final construction in EnergyPlus looses its link back to the OpenStudio construction? Is a UUID being used to link them vs. the display name?

**Comment by jmarrec** [comment]
This is probably outdated now that ConstructionAirBoundary has been implemented.
