### ISSUE TITLE
alphabetize HVAC Systems list

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2007]
...like the HVAC Systems library is now.

**Comment by kbenne** [comment]
I'm not opposed to alphabetizing, but did you know that the systems roughly correspond to Appendix G system types?

**Comment by eringold** [comment]
I think @MatthewSteen is talking about the HVAC drop-down list, rather than the 'Add HVAC System' window list (which IMO is fine).

**Comment by MatthewSteen** [comment]
what @eringold said.

**Comment by kbenne** [comment]
Doh! Ok. That can be arranged.

The whole interface needs some rethinking, but this kind of stuff is quick and easy so I'm all for it.

**Comment by MatthewSteen** [comment]
@kbenne agreed, especially the SHW, VRF, Rx. alphabetizing throughout the app would be a nice thing to have done for each major release.
