### ISSUE TITLE
1.10.0 closes when changing Results Summary Report

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2013]
This has happened a few times in a medium sized model (225 zones, 190,000 ft2). The app will close when changing to the Results Summary tab and then quickly trying to change the report from the default OpenStudio Results report.

**Comment by DavidGoldwasser** [comment]
@MatthewSteen is "Results Summary tab" the EnergyPlus results?

**Comment by MatthewSteen** [comment]
No, the main OS tab, left side. So click main tab > quickly click drop down. Haven't hit it recently.

**Comment by jmarrec** [comment]
This is old (and seemed intermittent at the time anyways) and can probably be closed

**Comment by MatthewSteen** [comment]
Haven't had this happen in a while.
