### ISSUE TITLE
Openstudio application 1.10

### ISSUE THREAD

**Issue by cvazquezpe** [NREL/OpenStudio#2014]
The Opensutdio 1.10 
![daily range c](https://cloud.githubusercontent.com/assets/16490249/12052183/bc23067e-aee2-11e5-9620-9b01588a225d.JPG)
![daily range f](https://cloud.githubusercontent.com/assets/16490249/12052184/bc23b29a-aee2-11e5-811a-15682ae026c4.JPG)

application is wrong converting degrees celsius to fahrenheit in the design day climate data. This is happening in the case of daily ranges temperatures. The field is a "range of temperature" so the convertion factor shall be (Degrees F = 1.8 * Degrees C) and not (Degrees F = 1.8 * Degrees C + 32). So the daily range field is showing 32 degrees more when converting celsius to farenheit. Look like this is not having further consequences with the design load calculations. However, I think it shall be an easy to fix issue.

**Comment by macumber** [comment]
Hmm this should be working correctly already, the units in the IDD are deltaC which is correct:

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/resources/model/OpenStudio.idd#L1004

**Comment by cvazquezpe** [comment]
Yes it is correct in SI units. But when I-P units are chosen within the preferences menu, then the conversion is incorrect.

**Comment by evanweaver** [comment]
Understood. This is now a known bug, and we are addressing it. Thanks for the catch @cvazquezpe.

**Comment by evanweaver** [comment]
Currently, OpenStudio converts the idd's "deltaC" to "K". Kelvin and Rankine then are the currencies used in OpenStudio's QuantityConverter class to express temperature deltas. Users may prefer in the future to have temperature deltas expressed in C and F, but for now, this fix is technically correct and adheres to the current OpenStudio paradigm to express temperature deltas.
