### ISSUE TITLE
PAT's "Sync Project Measures with Library" only updates 10 measures

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2017]
I searched for a bug on this but didn't find one.

When there are a lot of measures to update via the "Sync Project Measures with Library" button in PAT, the screen shows the total number of measures to update, paginated with 10 measures per page. If you go to the other pages, all measures are checked by default. But when you click Update, only the first 10 measures (or perhaps, only the measures on the selected page?) are updated. 

This is unexpected behavior and very confusing until the user realizes not all measures were updated. Worse, there is no way for the user to update all measures in the app without syncing multiple times.

Screenshots:

![pat_update](https://cloud.githubusercontent.com/assets/5861765/12099010/f20c9292-b2e2-11e5-8dda-160e495a7a62.png)

![pat_update2](https://cloud.githubusercontent.com/assets/5861765/12099065/5f16aa1c-b2e3-11e5-88e6-879e29e016b9.png)

**Comment by DavidGoldwasser** [comment]
@marj-schott will address this in Pat 2.0 due out at end of September.

Currently Sync project measures only synchronizes between your local BCL database and your currently open project. It doesn't look at the BCL website for updates.

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
