### ISSUE TITLE
ZoneVentilationDesignFlowRate problem

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#2020]
When ZoneVentilationDesignFlowRate is assigned to a zone with other equipment, the simulation will fail unless zone ventilation is the last component in priority. This is because on export to idf the zone hvac assigned to the zone receives the incorrect heating/cooling priority. The software logic counts the zone ventilation as zone equipment which it is not, so there is an off by +1 error.

**Comment by jmarrec** [comment]
+1, I just ran into this

**Comment by kbenne** [comment]
https://github.com/NREL/OpenStudio/commit/442115c3982d4c3758f6aa32d78660a5f12aed71
