### ISSUE TITLE
Cannot use RubyJobBuilder for Reporting measures

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2021]
Reported by Iain McDonald, lack of input and output file types cause an error in this code

```
measure = OpenStudio::BCLMeasure::load('C:/Files/Devel/OpenStudioMeasures/Measures/StandardReports').get 
ruby_job = OpenStudio::Runmanager::RubyJobBuilder.new(measure) 
```

**Comment by macumber** [comment]
This code might be useful for figuring out a workaround: https://github.com/NREL/OpenStudio/blob/8296251db964cfdac272468381950d6327b42500/openstudiocore/src/analysis/RubyMeasure.cpp#L151

**Comment by asparke2** [comment]
RunManager has been deprecated in OS 2.X.
