### ISSUE TITLE
.osm files disappear from computer, possibly caused by uninstalling and reinstalling OpenStudio and Sketchup applications

### ISSUE THREAD

**Issue by edixon16** [NREL/OpenStudio#2024]
I noticed that all of the .osm files I had saved on my Windows 7 work computer had disappeared about a week ago (except for the .osm files that OS automatically creates in the sub-directory when saving a new file, possibly scripts or measures or libraries). They were a bunch of old projects I had worked on in November and saved in My Documents folder. There was a period of one month that these files could have disappeared without me noticing. I had written this off as an unlucky mistake I had made while trying to clear up space on my C drive and thanked god I had a backup saved on the server. It happened to me again today on my Windows 10 personal laptop to files I had saved in my Download folder just last night. I went to open the file I was working on yesterday and it, along with the rest of the .osm files on my computer (except for the .osm files that OS automatically creates in the sub-directory when saving a new file) had disappeared.

This is all that changed on my personal laptop from when I was working on the files yesterday to when I noticed they were gone today: I was successfully working in the OS v1.10.0 application yesterday. Today I uninstalled an expired trial of sketchup pro 2015 and then OS v1.10.0. I then installed sketchup make 2016 and then OS v1.10.1. I opened OS v1.10.1 and tried to open the .osm file I was working on last night and found that it, along with the rest of the .osm files I had saved on my laptop were gone. 

For my work computer, I had created the files on with OS v1.9.0 and a licensed version of sketchup pro 2015. OS v1.10.0 was recently installed on the computer (I don't know if it was before or after I noticed the .osm files had disappeared). OS v1.9.0 and sketchup pro 2015 were never removed and are still in use.

**Comment by macumber** [comment]
As far as I know nothing in the OpenStudio installer/uninstaller would remove OSM files.  Is it possible something else removed the files?

**Comment by DavidGoldwasser** [comment]
@macumber can we close this?
