### ISSUE TITLE
PAT is breaking 1.9.0 files when opening with 1.10

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2026]
Reported by Elizabeth Gilmore

**Comment by macumber** [comment]
I can reproduce this trying to open an empty 1.9.0 project

**Comment by macumber** [comment]
Useful script for debugging

[print_pat.rb.txt](https://github.com/NREL/OpenStudio/files/92537/print_pat.rb.txt)

**Comment by macumber** [comment]
@DavidGoldwasser @asparke2 can you help me test this out? Once this checks out, @evanweaver can patch it to the 1.10.0 release and roll installers for further testing

**Comment by macumber** [comment]
If you open a 1.9.0 file, you will end up running both versions of the standard report measure (the 1.9.0 version output looks really similar to the 1.10 version output which confused me at first).  Neither reporting measure will show in the PAT interface because they are "WorkItems" and not "Variables", this also confused me

**Comment by evanweaver** [comment]
I'm on deck. Let me know the testing results.

**Comment by macumber** [comment]
On second thought, @evanweaver it's probably best if you can roll this commit into some new 1.10.0 packages.  That way @DavidGoldwasser @asparke2 and @ljbrackney can test using installers.  I'll be out Monday, the commit that should go in is here 

https://github.com/NREL/OpenStudio/commit/5e36f2ea94b60c1bc449a6a8fc85d63a343aeeba

I still need to write a unit test on that branch to prevent this from happening in the future, but the 1.10.0 patch can go out without it.
