### ISSUE TITLE
Forward Translation error when multiple spaces of same space type in a zone when load type is design load

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2028]
Steps to reproduce.
1. Create electric equipment definition with design level value (watts vs. watts per are or per person)
2. Add this load to a space type
3. Add the space type to two or more spaces
4. Add the spaces from step 3 into a new thermal zone
5. export to IDF.

If the load in step 1 was 100W and you had three spaces, then there should be 300W in the resulting thermal zone in an exported IDF, but it has just 1 load object with a value of 100W.

cc: @asparke2

**Comment by macumber** [comment]
The proposed fix does not allow combined spaces to share a space type that has absolute loads.  This is consistent with the model api.  However, it is probably bad practice to apply absolute loads to a space type because the total load will be very sensitive to the space geometry (i.e. different configurations will have different total loads even if they have the same floor area)

**Comment by macumber** [comment]
@shorowit @joseph-robertson FYI

**Comment by DavidGoldwasser** [comment]
Looks good. Here is what I see now in the IDF file where two spaces use a common space type with a 65W refrigerator. Not sure why the second is 3 vs. 2 but not concerned with naming as long as results are as expected.

```
ElectricEquipment,
  residential refrigerator 1,             !- Name
  living zone,                            !- Zone or ZoneList Name
  residential refrigerator_annual_schedule, !- Schedule Name
  EquipmentLevel,                         !- Design Level Calculation Method
  65.0889336192958,                       !- Design Level {W}
  ,                                       !- Watts per Zone Floor Area {W/m2}
  ,                                       !- Watts per Person {W/person}
  0,                                      !- Fraction Latent
  0,                                      !- Fraction Radiant
  0;                                      !- Fraction Lost

ElectricEquipment,
  residential refrigerator 3,             !- Name
  living zone,                            !- Zone or ZoneList Name
  residential refrigerator_annual_schedule, !- Schedule Name
  EquipmentLevel,                         !- Design Level Calculation Method
  65.0889336192958,                       !- Design Level {W}
  ,                                       !- Watts per Zone Floor Area {W/m2}
  ,                                       !- Watts per Person {W/person}
  0,                                      !- Fraction Latent
  0,                                      !- Fraction Radiant
  0;                                      !- Fraction Lost
```

**Comment by shorowit** [comment]
@macumber Thanks for resolving this issue so quickly!
