### ISSUE TITLE
PAT 1.10.0 run time depends on number of External File User Defined Measures

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2030]
I'm running a small model through PAT for an EDA FEA report with a single design alternative created from an external file. The baseline model has an OS measure, an EP measure, and a Reporting measure brought in as fixed measures and the external file does not have any measures. The design alternative has 10 User Defined Measures included in the model, which takes significantly longer to run than the baseline unless the number of User Defined Measures is reduced. 

@asparke2, @macumber project inbound via email and I'll give anyone who finds the [easter egg](https://en.wikipedia.org/wiki/Easter_egg_(media)) a prize.

----

**7 User Defined Measures = 5 minutes**

![image](https://cloud.githubusercontent.com/assets/8397034/12399013/b58ad0b6-bdd4-11e5-8118-4beb06551db6.png)

**10 User Defined Measures = 40+ minutes (lost patience and cancelled sim)**

![image](https://cloud.githubusercontent.com/assets/8397034/12400368/c5b4280e-bddc-11e5-90ce-45dbee91ee0c.png)

**Comment by MatthewSteen** [comment]
Disregard, working now.

**Comment by macumber** [comment]
This can depend on the measure.  Are you sure it's not any measure in particular that is slowing things down?

**Comment by MatthewSteen** [comment]
It always stalls on the first OS measure, in this case 90.1-2010 Daylighting, but that one is attached to the baseline model as a fixed measure. There are no measures attached to the External File. Run time simply depends on how many User Defined Measures the External File is tagged with.

**Comment by ljbrackney** [comment]
That's odd.  The project I usually test with has 3 or 4 measures attached to the baseline, and then I pile on another 4 or 5 to create design alternatives.  When I was testing the 1.10.0 bug fix build yesterday I didn't notice anything out of the ordinary.  I wonder if it's specific to the daylighting measure?

**Comment by eringold** [comment]
I also experienced a severe PAT lag when running a design alternative (created from external file) with around ten User Defined Measures, and had the issue go away once I pruned the UDMs down to 5 or 6. I sent the project file to @asparke2 last week; I can send it to @macumber if you need another example.

**Comment by MatthewSteen** [comment]
I just tested that theory by deleting the OS measure and run time is still too long with the external file tagged with ~10 UDMs. In this case it stalls during the first step while processing the alternate model instead of the second step processing the first OS measure. The baseline took ~3 minutes and the alternate has taken >10.

![image](https://cloud.githubusercontent.com/assets/8397034/12425690/36be39d4-be93-11e5-9fb8-caed1f55b1e1.png)

**Comment by eringold** [comment]
Yep, that was the exact behavior I saw @MatthewSteen, though with mine I didn't have the patience to get past the first step (no movement after like 25 minutes).

**Comment by macumber** [comment]
File added to files repo

**Comment by MatthewSteen** [comment]
Workaround was to reduce the number of User Defined Measures so that the model runs in a tolerable amount of time (in my case 9 UDMs), and then edit the `results.xml` to add the remaining UDM(s) for EDAPT, which requires generating a UUID. 

    <measure>
          <name>Central Utility Plant (CUP) Proposed Design Phase 1 - 50% SD</name>
          <id>{b347f69a-9b68-4034-a42b-f109781a97f5}</id>
          <category>HVAC.Whole System</category>
          <description>description</description>
          <initial_condition></initial_condition>
          <final_condition></final_condition>
    </measure>

**Comment by macumber** [comment]
@eringold were you using the same measures as Matt?  Also, you were both running 7 jobs at a time on an 8-core machine?

**Comment by eringold** [comment]
@macumber I think we had the same always run measures in our projects. Both projects had only a couple 'always run' measures applied to the baseline and alternative(s). Each alternative was brought in from an external file, with 'user-defined measures' described to account for all the changes in those external files. I did this so that the XML would register those runs as 'design_alternative' runs, and populate the correct tables in eda-pt. The issue seems to result from the number of 'user-defined measures' added to a single alternative, since the baseline run would always proceed normally, and the simulation hang on the alternative runs.

**Comment by macumber** [comment]
@MatthewSteen @eringold you guys still hitting this?

**Comment by MatthewSteen** [comment]
i'm not working on any PAT projects currently and haven't checked 1.10.4 since downloading it. i'll run a test this week.

**Comment by MatthewSteen** [comment]
@macumber I just ran a large EDA project in 1.10.4 and didn't encounter this issue. The project had four Design Alternatives created from external files each with 8-9 User Defined Measures. For comparison I ran the same project with only one UDM per DA and it took the same amount of time. 

PS my easter egg offer is still open in case you, @asparke2, @DavidGoldwasser, @ljbrackney, or @evanweaver are coming with @kbenne to meet with Eric and I Thursday evening.

**Comment by macumber** [comment]
Ludicrous boiler efficiency?  I've got something better planned for April 1 ;-)

**Comment by macumber** [comment]
Plus that's a [real thing](https://www.youtube.com/watch?v=ygE01sOhzz0) anyway

**Comment by macumber** [comment]
PS: thanks for looking into this and trying to verify!

**Comment by MatthewSteen** [comment]
:beers:

**Comment by MatthewSteen** [comment]
For those still running 1.14.0, I'm still seeing this.
