### ISSUE TITLE
AirTerminalSingleDuctConstantVolumeFourPipeInduction does not always connect properly

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#2033]
If you have an AirLoopHVAC instance with a single demand branch that contains only an AirTerminalSingleDuctConstantVolumeFourPipeInduction (no zone), then add a zone, the terminal will not be connected properly. The recirculation loop between the zone exhaust node and the terminal's secondary air inlet will not be hooked up. This is almost certainly true for other terminals that have secondary air inlet (i.e. PIUs). The reason for this is that terminals depend on their ::addToNode to make these connections, but adding a thermal zone when the terminal already exists bypasses the terminal addToNode logic. The cleanest solution that does not duplicate code (consolidates on the sometimes complex logic of addToNode), is to remove the terminal from the loop, add the zone, then re-add the terminal.

**Comment by jmarrec** [comment]
@jugonzal reported the same on slack a few days ago, on the SeriesPIU.

Code to reproduce. This works:

```
[18] OpenStudio-PAT(main)> m = Model.new; z = ThermalZone.new(m); a = AirLoopHVAC.new(m); c = CoilHeatingElectric.new(m); fan = FanConstantVolume.new(m); atu = AirTerminalSingleDuctSeriesPIUReheat.new(m, fan, c);
[19] OpenStudio-PAT(main)> a.multiAddBranchForZone(z, atu)
=> true
[21] OpenStudio-PAT(main)> puts atu
OS:AirTerminal:SingleDuct:SeriesPIU:Reheat,
  {b5c222b7-ca79-41c7-8521-3f524e131e93}, !- Handle
  Air Terminal Single Duct Series PIU Reheat 1, !- Name
  ,                                       !- Availability Schedule Name
  autosize,                               !- Maximum Air Flow Rate {m3/s}
  autosize,                               !- Maximum Primary Air Flow Rate {m3/s}
  autosize,                               !- Minimum Primary Air Flow Fraction
  {cd4e2d2f-3b79-4df3-8891-68f67d55c5ab}, !- Supply Air Inlet Node
  {c9e506f7-f556-4c32-869a-8ca153044dbc}, !- Secondary Air Inlet Node
  {d361476e-9149-439e-b96f-708cc63df0e8}, !- Outlet Node
  ,                                       !- Reheat Coil Air Inlet Node
  ,                                       !- Zone Mixer Name
  {fc792d34-967a-45a2-84d4-723347679657}, !- Fan Name
  {c25187dc-a753-4f97-a78c-ee26673b8efa}, !- Reheat Coil Name
  autosize,                               !- Maximum Hot Water or Steam Flow Rate {m3/s}
  0,                                      !- Minimum Hot Water or Steam Flow Rate {m3/s}
  0.001;                                  !- Convergence Tolerance
```

If you do it like this, add a branch for the ATU then the zone, then the secondary inlet insn't set indeed
```
[31] OpenStudio-PAT(main)> a.addBranchForHVACComponent(atu)
[32] OpenStudio-PAT(main)> a.addBranchForZone(z)
```

Happens around here: https://github.com/NREL/OpenStudio/blob/8ae4d883ed1a6ba704aa8b60003646de69a00f39/src/model/AirTerminalSingleDuctSeriesPIUReheat.cpp#L383-L402

A special case should probably be added around here or something like that: https://github.com/NREL/OpenStudio/blob/8ae4d883ed1a6ba704aa8b60003646de69a00f39/src/model/AirLoopHVAC.cpp#L405
