### ISSUE TITLE
Decimal separator disable in construction material values fields

### ISSUE THREAD

**Issue by Pampipampupampa** [NREL/OpenStudio#2038]
Cannot write decimal separator `.` in a value field for a material information (`Constructions/Materials`)

See: https://unmethours.com/question/12233/creating-new-construction-materials/ 

**The proposed solution works but affect others softwares on the platform:**
"A quick fix (tested in W7 64-bit) : 'Control Panel' > 'Clock, Language, and Region' > 'Formats Tab' and change comma separator into point." 

**Informations:**
- Platform: Windows 7 Professionnal 64bit and Linux Mint 17.2 64bit
- State: France
- Decimal separator: `,`
- Open Studio version: 1.10.0

**Comment by DavidGoldwasser** [comment]
@axelstudios and @macumber anything for us to do on our end, or is this just user configuration for non-US machines.

**Comment by jmarrec** [comment]
Were you actually trying to use the numeric keypad "." key next to the 0? If so, that would create a ',', which is forbidden in OS. If you use SHIFT + ".;" on a french keyboard, that should work, at least I never had any issues with that.

So unless it's something else, I think this could be closedd
