### ISSUE TITLE
Menu bar sometimes un-responsive after waking computer from sleep (Bugzilla #936)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#204]
On 2012-09-27 10:17:42, @DavidGoldwasser wrote:

> I often leave the OpenStudio Application open while my computer sleep overnight. On a few occasions the menu bar was un-responsive, but the rest of the application worked.
> 
> Evan thinks this may just be a QT issue (maybe or maybe not specific to Windows 7, which is what I'm using). I was not able to duplicate this with a short sleep, but will test with an hour or two vs. a few seconds. Most users should save before sleeping anyway, but occurred to me if someone walked away from desk, computer could sleep and hit this. There is no other way to save now. At some point we may want to add a "ctrl S" to save shortcut which may help in this situation?
> 
> Hmm, actually kicking off a simulation may be able to force a save.

On 2012-09-27 10:18:21, @DavidGoldwasser wrote:

> Luigi, I don't consider this something we need to touch for 0.9.0

**Comment by evanweaver** [comment]
@DavidGoldwasser this bug appears to no longer be valid.

**Comment by DavidGoldwasser** [comment]
agreed
