### ISSUE TITLE
Assign thermostat to zones problem

### ISSUE THREAD

**Issue by fengcool** [NREL/OpenStudio#2042]
I have a problem when I assign a thermostat to a few specific HVAC zones. I highlight the zones, and click “apply to selected” button, however ALL the zones in my model are assigned the same thermostat. Please fix the problem. Thanks.

**Comment by DavidGoldwasser** [comment]
I think this issue fixed in 0.1.11 addresses the problem you are seeing. Let me know if you are describing something different, and I can re-open this.
