### ISSUE TITLE
ResultsViewer updated alias does not propagate to the Table or Tree Views

### ISSUE THREAD

**Issue by elainethale** [NREL/OpenStudio#2047]
In OpenStudio 0.10.0, when I open an EnergyPlus sqlite file in ResultsViewer and then update the file's alias in the bar under the main menu, it is of limited use because the name does not propagate down to the panes from which I can select data to plot.

**Comment by elainethale** [comment]
Slight modification--the alias does propagate down if I open up another file.

**Comment by macumber** [comment]
With move to DView closing this as won't fix
