### ISSUE TITLE
BCL tagged material that came in as part of a construction do not show at the bottom in the left pane when looking at materials (Bugzilla #937)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#205]
On 2012-09-27 10:40:47, @DavidGoldwasser wrote:

> BCL tagged materials that come in with a construction are sorted in with other materials, while BCL materials that came in as a material are at the bottom. This can be a little confusing.
> 
> This also affects the "My Model" tab when in the construction sub/tab. It doesn't affect the library because these materials don't show up in the library.
> 
> I noticed the same behavior when you are in the Construction Sets sub-tab and look at "Constructions" in "My Model" They are sorted in line.
> 
> I'm ok with BCL objects in the model being at the end or sorted, but just need to make it consistent. Library doesn't have to follow the same logic, but might be nice if it does.

**Comment by jmarrec** [comment]
Behavior today in OS 2.2.1 is that materials in My Model are sorted by name, regardless of whether they are BCL or not.
