### ISSUE TITLE
Wrong IP units for controllerWaterCoil min/max flow

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2057]
`Controller:WaterCoil` takes a Minimum Actuated Flow and a Maximum Actuated Flow. As seen in the [docs](http://bigladdersoftware.com/epx/docs/8-4/input-output-reference/group-controllers.html#field-maximum-actuated-flow), 

> **Field: Maximum Actuated Flow**
> This is the maximum water flow (m3/sec) through the coil. Set to the maximum design water flow for the coil.

In OpenStudio, CFM is asked instead of GPM.

![wrong units for min or max actuaded flow](https://cloud.githubusercontent.com/assets/5479063/12744976/62f7e586-c997-11e5-975b-25738d6f3fb9.png)

**Comment by MatthewSteen** [comment]
Might be an EP issue.

![image](https://cloud.githubusercontent.com/assets/8397034/12752734/18d58654-c981-11e5-8df8-0bd7732b0bfd.png)

**Comment by jmarrec** [comment]
Seems it is indeed, I'll open one there...
