### ISSUE TITLE
Child records can be removed from the ProjectDatabase with poor results (Bugzilla #939)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#206]
On 2012-09-28 13:36:30, @elainethale wrote:

> See ProjectFixture.DesignOfExperiments_RemoveAlgorithm, which has an example in which an AlgorithmRecord is deleted out from under its parent AnalysisRecord. It so happens that Analysis does not have to have an Algorithm. However, it probably wants to manage the process of Analysis::clearAlgorithm (which doesn't even exist) rather than having its Algorithm deleted out from under it using the ProjectDatabase record classes. 
> 
> To avoid the throw that happens in the test, we could:
> 1. Not let child records be removed through the public interface.
> 2. At least have child records register their removal with their parent record classes (which will still result in exceptions or crashes when the child is required).
> 3. Blend 1 and 2 by also marking up which children are strictly required.

**Comment by jmarrec** [comment]
Irrelevant in PAT 2x
