### ISSUE TITLE
PAT 1.10.0 Run tab breaks if run cancelled

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2060]
If the run is cancelled the sim bars become un-highlighted and aren't able to be re-highlighted by selecting individually or by using the Select All/Clear Selection buttons.

**Comment by MatthewSteen** [comment]
![image](https://cloud.githubusercontent.com/assets/8397034/12796648/196ba858-ca7d-11e5-8fe0-4cce89a7dc22.png)

**Comment by macumber** [comment]
Is this new in 1.10?

**Comment by MatthewSteen** [comment]
I hadn't encountered it before this.

**Comment by macumber** [comment]
I just tried this in 1.10.  When I canceled the runs I did see that I could not click on/select the design alternatives.  However, I could click the clear buttons (both for individual datapoints and for all).  Once the results were cleared I could select the rows and rerun them.  So you have to clear results befor trying to rerun.  Does that match with what you are seeing?

**Comment by macumber** [comment]
You can still expand the rows to look at simulation errors.
