### ISSUE TITLE
PAT 1.10.0 stops working if user changes User Defined Measure category

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2061]
After opening a project from the first 1.10.0 build in the current build. If the user tries to change one of the External File User Defined Measure category tags the following messages appear.

![image](https://cloud.githubusercontent.com/assets/8397034/12796971/f7cadd48-ca7e-11e5-937a-677faa291da2.png)

![image](https://cloud.githubusercontent.com/assets/8397034/12796973/f8f06fee-ca7e-11e5-89e3-86c1f0ec4fa9.png)

![image](https://cloud.githubusercontent.com/assets/8397034/12797130/a8f008be-ca7f-11e5-9783-8ce93800a390.png)

**Comment by MatthewSteen** [comment]
Selecting No in both cases will cause the crash, selecting Yes will not.

**Comment by macumber** [comment]
@DavidGoldwasser can you test the following?

Create an external model in PAT, add user defined measures, run it, return to the external measure and try 1) changing measure taxonomy, name, cost, etc, 2) adding new user defined measures, 3) removing user defined measures
