### ISSUE TITLE
Tariff Selection Time And Date Dependent measure has wrong season for winter demand charge

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2065]
FYI: @DavidGoldwasser 

![image](https://cloud.githubusercontent.com/assets/8397034/12856564/c27d4e2a-cc02-11e5-85dd-f935ed12c523.png)

**Comment by DavidGoldwasser** [comment]
@MatthewSteen thanks, updated measure is on BCL, may take a few hours to show in GUI.
