### ISSUE TITLE
Any chance OpenStudio could use "!-" instead of "!"? (Bugzilla #941)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#207]
On 2012-10-04 08:41:07, @DavidGoldwasser wrote:

> Email came from Mike Whitte
> 
> I thought I'd take a quick look at Annie Marston's trouble file, and noticed that OpenStudio idf export does not follow the automatic end-line convention that IDF Editor and the transition utilities do.  
> Any chance OpenStudio could use "!-" instead of "!"?
> 
> OpenStudio
> Version,
>    7.1;                      ! Version Identifier
> 
> Transition and IDF Editor
> Version,
>      7.1;                     !- Version Identifier
> 
> As things stand currently, if the file is exported from OpenStudio, and then edited in IDF Editor, you get this:
> ! Version Identifier
> Version,
>      7.1;                     !- Version Identifier
> 
> Mike

Keywords: ForwardTranslation

**Comment by jmarrec** [comment]
Fixed.
