### ISSUE TITLE
Missing Object Types in Sketchup Plugin Inspector

### ISSUE THREAD

**Issue by mattdoiron** [NREL/OpenStudio#2071]
With the recent v1.10 of OpenStudio and Sketchup 2016, there are a significantly reduced set of objects viewable in the SketchUp plugin's Inspector. The most important misisng object type is constructions. I'm unsure if this was intentional, but if so please restore them! I often define constructions within the plugin and also find it useful to change the render colour of constructions so I can see that they have been defined correctly for a given portion of the building.

Here is a screenshot: 
![inspector](https://cloud.githubusercontent.com/assets/3885555/12986075/48d018f8-d0aa-11e5-86eb-a451dbb19b60.png)

**Comment by eringold** [comment]
See [this](https://github.com/NREL/OpenStudio/issues/1979) issue and resolution for why the objects available to be edited in the plugin have been changed.
