### ISSUE TITLE
Cannot create thermostats in Sketchup 2016 with OS 1.10

### ISSUE THREAD

**Issue by asult** [NREL/OpenStudio#2072]
Hi, I am having trouble creating new thermostats.

Heating and cooling thermostat schedules can be created in OS, but I cannot create new thermostats in Sketchup 2016 plugin inspector. Cannot create thermostats in Openstudio either, how should it be done now?

**Comment by macumber** [comment]
This functionality was removed from the SketchUp plug-in, it is now only available in the OpenStudio application

**Comment by asult** [comment]
Thank you for responding. I cannot find a way to do it in Openstudio though.

**Comment by macumber** [comment]
There is no thermostat tab, a unique thermostat is created for each thermal zone in the Thermal Zones tab under HVAC Systems when you drag a schedule onto the Cooling or Heating Thermostat Schedules.  You can apply a schedule to multiple thermal zones using the Apply to Selected feature of the grid view.
