### ISSUE TITLE
Deleting space orphans lifecycle cost objects that had been associated with the space

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2074]
This came up with user model that has cost associated with space (from K12 infiltration measure, but other measures may do this as well). I tried deleting the space from SketchUp using 1.10.3, may or may not do the same thing if deleted via API. App can't delete space. I have not tested if lifecycle cost objects have similar issues being orphaned when liked to other object types.

Object before space deleted:

OS:LifeCycleCost,
  {9ed50b4f-ebd0-4ffb-9edc-7a568d678265}, !- Handle
  Space 101 - Entry Infiltration Cost,    !- Name
  Construction,                           !- Category
  Space,                                  !- Item Type
  {693efcac-82da-402a-9124-46b744b90949}, !- Item Name
  5000,                                   !- Cost
  CostPerEach,                            !- Cost Units
  ,                                       !- Start of Costs
  ,                                       !- Years from Start
  ,                                       !- Months from Start
  25;                                     !- Repeat Period Years

Object after space deleted:

OS:LifeCycleCost,
  {9ed50b4f-ebd0-4ffb-9edc-7a568d678265}, !- Handle
  Space 101 - Entry Infiltration Cost,    !- Name
  Construction,                           !- Category
  Space,                                  !- Item Type
  ,                                       !- Item Name
  5000,                                   !- Cost
  CostPerEach,                            !- Cost Units
  ,                                       !- Start of Costs
  ,                                       !- Years from Start
  ,                                       !- Months from Start
  25;                                     !- Repeat Period Years

**Comment by macumber** [comment]
Yuck, this shouldn't be happening.  I'll look into this bug, and add a fix to the diagnostic user script

**Comment by macumber** [comment]
@DavidGoldwasser how did you delete the space?  I am not able to reproduce this in a unit test
