### ISSUE TITLE
liquid flow rate IP units

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2076]
Many of the liquid flow rate fields in the IDD are missing the IP unit conversion to gal/min and default to ft3/min.

**Comment by jmarrec** [comment]
@MatthewSteen you fixed it it yourself in #2077.

So unless you can find some still left over, can you please close? thanks!

**Comment by jmarrec** [comment]
Assuming closed by #2077, can always reopen if we find another one missing (I couldn't)
