### ISSUE TITLE
Fix ShadingControl solar setpoint and units handling

### ISSUE THREAD

**Issue by rpg777** [NREL/OpenStudio#2078]
Issue raised [here](https://unmethours.com/question/15094/issues-with-switchable-glazing-solar-gain-setpoint/). Need to stick to watts for the setpoint (and translate to lux exclusively in the Radiance domain), and roll the object back to a reasonable watts-based default value.

**Comment by macumber** [comment]
@rpg777 are you trying to get this in by 1.11?  if so can you tag it with the milestone?

**Comment by rpg777** [comment]
<a href="https://github.com/NREL/OpenStudio/commit/ff0ea68dd9eddb5cf5c62c5353f4e2cee3279dda">fixed</a>
