### ISSUE TITLE
Fan:ZoneExhaust Balance Exhaust Fraction default to the opposite of EnergyPlus

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2079]
From the docs on [Fan:ZoneExhaust](http://bigladdersoftware.com/epx/docs/8-4/input-output-reference/group-fans.html#field-balanced-exh)ust-fraction-schedule-name

> **Balanced Exhaust Fraction Schedule Name**
> 
> This field is optional. If it is not used, then **all the exhaust air flow is assumed to be unbalanced** by any simple airflows, such as infiltration, ventilation, or zone mixing. Unbalanced exhaust is then modeled as being provided by the outdoor air system in the central air system

In OpenStudio App, if you leave this field blank, it'll end up being `Always On Discrete` thus making it completely **balanced**.

This field should be either mandatory or default to Always Off.

I hadn't filled this field thinking it would default to unbalanced, and it took me a while to understand where my problem was lying...

Bonus point: why can we select the `model.alwaysOnDiscrete` in the App but not the `model.alwaysOffDiscrete`?

**Comment by kbenne** [comment]
@jmarrec I cannot reproduce this.

**Comment by jmarrec** [comment]
Me neither.
