### ISSUE TITLE
Deleting AirTerminal with reheat does not delete HW coil

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2080]
When you delete an ATU such as `AirTerminal:SinglueDuctVAVReheat` that had a HW coil connected to a HW loop, the coil stays behind and crashes E+

**Comment by jmarrec** [comment]
This might have been mentioned already, but it would be certainly nice to be able to tell which coil on a HW loop is actually not connected to any terminal or zonehvac. though I supposed if you make sure this never happens, there's no point differentiating them

**Comment by macumber** [comment]
@kbenne tag with 1.11 if you want
