### ISSUE TITLE
Dropping Schedule

### ISSUE THREAD

**Issue by Machbo** [NREL/OpenStudio#2081]
I am losing a schedule name on a Service Hot Water Fixture when running a simulation in OS.  When I enter it into the idf, it shows up in OS, but I lose it again every time I run the simulation.

**Comment by jmarrec** [comment]
Check your schedule's TypeLimits

**Comment by Machbo** [comment]
I'm just using one of the occupancy schedules to test.  It is fractional and between 0 and 1 at all times.

**Comment by Machbo** [comment]
I can't see any reason for this happening, I believe it to be a bug in OS,

**Comment by Machbo** [comment]
I have just run the EP idf editor and entered a name for the schedule and then run the simulation in EP.  It ran through with no problem.

**Comment by asparke2** [comment]
@Machbo can you upload your .osm file so we can reproduce this?

**Comment by Machbo** [comment]
This issue was resolved at Unmethours by @kbenne.
https://unmethours.com/question/15131/i-cant-get-a-service-hot-water-plant-loop-to-run/?answer=15143#post-id-15143

**Comment by kbenne** [comment]
Resolved yes, but I think I'm going to make some changes to make things more robust. I'm going leave this issue open.

**Comment by Machbo** [comment]
Thanks Kyle, I have it up and running and don't need anymore help. I understand what you did and actually figured out how I made it happen. In the facility tab, I somehow managed to get the Always on Discrete schedule in an exterior equipment load. In that area the fraction is editable I believe. 

Thanks again, 
Mark 

----- Original Message -----

**Comment by macumber** [comment]
@kbenne you want to tag this with 1.11?
