### ISSUE TITLE
Mismatch between OpenStudio and EnergyPlus idd choice for PlantLoop Load Distribution Scheme

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#2086]
See: https://unmethours.com/question/15211/plant-load-distribution-scheme-getting-reset-from-uniform-to-sequential/

Causes any load distribution choice other than 'Optimal' to default to 'SequentialLoad' in the idf.

**Comment by macumber** [comment]
@kbenne can you tag with 1.11 if you want this in?  Not sure if this is Major or Normal

**Comment by kbenne** [comment]
This is taken care of here.

https://github.com/NREL/OpenStudio/pull/2147
