### ISSUE TITLE
PAT XML export is not exporting user-defined names

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2088]
Reported by Elizabeth.  Her PAT project has nice names in the GUI, but on export, everything in the XML has the default names like "Measure Whatever Alternative 1."

Suspect that this was introduced during the cleanup of name vs. displayName that @macumber did when adding user-defined Measures.  I should have caught this during testing.

**Comment by asparke2** [comment]
BTW this is for any Measure, not just user-defined Measures.

**Comment by macumber** [comment]
@asparke2 is this something you can fix for 1.11?

**Comment by asparke2** [comment]
Either of us is fine by me.  I would like to get it into the next iteration release; Elizabeth has several projects coming up soon that would hit this.

**Comment by macumber** [comment]
If you can do this I'll put it back to you, that would be great!
