### ISSUE TITLE
PAT deletes all datapoints after closing and reopening

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2092]
I noticed this behavior in 10.1, 10.2 and now 10.3.

I run a PAT analysis with a bunch of design alternatives (usually takes all night long). I can see the results no problem.

If I close PAT, the datapoints are still there.

If I reopen it, *ZWOOOSH* they're gone. I've got only one left right now, because I had the SQL file opened in other applications so it deleted every folder in the datapoint folder and stopped at EnergyPlus-0 because it couldn't delete the SQL file.

**This has happened to me consistently and at least 5 or 6 times, so this isn't an isolated event.**

Maybe it's worth saying that the PAT folder ends up being 40 GB (I'm requesting quite a few ouputs to the SQL file) before deletion, but I have 250 GB free on my disk.

**Comment by macumber** [comment]
@jmarrec I can't reproduce this.  Do you have any steps that can be followed to reliably reproduce this?  Do you happen to be switching between versions of PAT when you reopen the project?

**Comment by macumber** [comment]
Or updating any of the OSMs or Measures?

**Comment by jmarrec** [comment]
Dan, I'm on 1.10.3, haven't took the time to upgrade to 1.10.4 yet.

I just created a blank project in PAT 1.10.3, imported a simple model, added 2 design alternatives with OpenStudio measure.
I just run the simulations, I see the datapoints.
I close PAT, I sill see the datapoints.
I reopen PAT, reopen the projects: they're gone

**Comment by jmarrec** [comment]
Just tried on 1.10.4, didn't get this behavior, so I'll close this one

**Comment by macumber** [comment]
@MatthewSteen @eringold did either of you ever see this?

**Comment by MatthewSteen** [comment]
No, only this message when opening an existing project with the corresponding version of PAT:

![image](https://cloud.githubusercontent.com/assets/8397034/13463608/435ea952-e04a-11e5-9924-a24946ddf62c.png)

**Comment by macumber** [comment]
@MatthewSteen did you get that message when you actually were opening a past project with a new version of pat?  Or did you get that incorrectly when opening a pat project with the same version of pat?

**Comment by MatthewSteen** [comment]
Same version.

**Comment by macumber** [comment]
Hmm that is not good, can you reproduce that?  Just make a pat project, run it, close it, reopen?  I haven't seen it give that warning in that case, any special steps needed to make it do that?

**Comment by macumber** [comment]
Let's all keep an eye out for this with the release candidate, if it pops back up we will reopen this

@DavidGoldwasser @asparke2 FYI

**Comment by mapascual** [comment]
This is also happening to me in PAT 1.14.0
