### ISSUE TITLE
PAT Cloud not working in 1.10.0

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2094]
We are aware that Cloud runs through PAT are not working in OpenStudio. We are working on a new interface for PAT 2.0 due out at the end of September of this year. Until then we plan to disable the Cloud button in PAT. If you projects that are too large to run on your computer in a timely manor we have the following suggestions.

1. When you are ready to run, move to another machine in the office with more cores.
2. Split the runs up into multiple projects and run on multiple computers
3. Use the OpenStudio Analysis Spreadsheet. This will allow you to run jobs on the cloud using OpenStudio server. It also provides sampling to more quickly generate design alternatives and advanced visualizations of the project. (edited)

@asparke2  is probably most concerned with are EDAPT users. For them option 1 (use a computer with more cores) is their only easy option, since they need to generate the xml for EDAPT.

**Comment by chrisbalbach** [comment]
Suggestion # 3, when migrating a project from the PAT interface via the export feature, also does not work (see attached image) - either a new or related bug

![2016-02-24_13-00-02](https://cloud.githubusercontent.com/assets/5746765/13295470/05abc7f0-daf7-11e5-8f6e-e2a3139da383.jpg)

This requires Users of option (3) to recreate the entire analysis using a spreadsheet template, which is not ideal.

**Comment by macumber** [comment]
Fixing the export might be something we can handle for 1.11, I believe this issue is still valid https://github.com/NREL/OpenStudio/issues/1708

**Comment by macumber** [comment]
Will disable the cloud button and try to fix export
