### ISSUE TITLE
new FanZoneExhaust fields not turned on after version update

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2095]
Specifically these:

> Minimum Zone Temperature Limit Schedule Name
> Balanced Exhaust Fraction Schedule Name

**Old object from previous version**

![image](https://cloud.githubusercontent.com/assets/8397034/13294477/5eb7ea56-dae1-11e5-9f24-ce7ed2d846c7.png)

**New object from 1.10.4**

![image](https://cloud.githubusercontent.com/assets/8397034/13294482/65bc0e40-dae1-11e5-9dfb-8ee3e2a8d8f3.png)

**Comment by jmarrec** [comment]
@kbenne can you close this one please?

Tested in OS 2.2.1:

![screen shot 2017-09-28 at 4 36 01 pm](https://user-images.githubusercontent.com/5479063/30972544-25fb61de-a46b-11e7-93e0-5bced4cb386e.png)

**Comment by MatthewSteen** [comment]
Looks good in 2.3.0
