### ISSUE TITLE
Incomplete published EDAPT Schema (Refrigeration)

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/OpenStudio#2096]
Using PAT v1.10.0 (Win 64Bit), a datapoint was created from an external file. The seed model refrigeration condensing unit fan power object was not assigned any cost attribution elements. The datapoint .osm represented reduced fan power associated with ECM fans installed on refrigeration equipment outdoor condensing units. The datapoint osm file was confirmed to have run properly in the OS Application without error (except nuisance errors). 

This "user-defined" measure was then categorically tagged with a single end-use of as "Refrigeration, Condensers" and attributed with a price of $300. 

Attached xml file export from PAT results fails a schema validation against the EDAPT schema published here: https://eda-pt.org/system/files/results_schema_3_1.xsd.  Examination of the schema shows no enumeration values for ANY refrigeration categories.

[PEA.zip](https://github.com/NREL/OpenStudio/files/145360/PEA.zip)

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#11
