### ISSUE TITLE
TimeStep of 6 per hour in new model isn't respected when simulation is run

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2099]
In a new model there is no time step object in the OSM, but the GUI shows 6 time steps per hour. If you run a simulation you see this error.

   ** Warning ** No Timestep object found.  Number of TimeSteps in Hour defaulted to 4.

Once you go in the GUI and change time step value away from 6 and then back to it, then the timestep is written out and the error goes away.

OS:Timestep,
  {29163c90-40ba-49d0-9dbf-7f439aff1cb7}, !- Handle
  6;                                      !- Number of Timesteps per Hour

@macumber this sounds familiar, but I don't see it filed anywhere, May have been related to other simulation parameters. When I changed the time step it wasn't just that object that got added to the OSM, but also all other parameters. Why don't we always just have the objects in the model?

**Comment by macumber** [comment]
If the GUI is showing a default we might not be translating the default, this is similar to what is reported in this ticket https://github.com/NREL/OpenStudio/issues/2100

**Comment by macumber** [comment]
Hmm, not looks like it should get translated:

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateTimestep.cpp#L36

**Comment by macumber** [comment]
Sounds like the GUI needs to create a TimeStamp object if it does not exist

**Comment by macumber** [comment]
The following objects are not created until you go to the simulation settings tab:

```
OS:RadianceParameters,
OS:SimulationControl,
OS:Sizing:Parameters,
OS:ProgramControl,
OS:Timestep,
OS:OutputControl:ReportingTolerances,
OS:ConvergenceLimits,
OS:ShadowCalculation,
OS:SurfaceConvectionAlgorithm:Inside,
OS:SurfaceConvectionAlgorithm:Outside,
OS:HeatBalanceAlgorithm,
OS:ZoneAirHeatBalanceAlgorithm,
OS:ZoneAirContaminantBalance,
OS:ZoneCapacitanceMultiplier:ResearchSpecial,
OS:RunPeriod,
```

I am thinking that many of these need to be created at Model::new and Model::load time.  Thoughts?

@kbenne @mbadams5 @asparke2 @DavidGoldwasser

**Comment by macumber** [comment]
I think the bug report is slightly wrong, if you got to the point where you could see the Timestep in the GUI then it exists.  But if you made a new model and ran it the object would not exist, when you went back and looked in the GUI you would see it and be confused.

**Comment by macumber** [comment]
Also confusing that the E+ default is different than the E+ IDD default

**Comment by asparke2** [comment]
I support adding those in at model creation.  It would help address  https://github.com/NREL/OpenStudio/issues/1491 too.

**Comment by macumber** [comment]
I made a minimal fix here, https://github.com/NREL/OpenStudio/commit/a7b9a396c1f65e219b6f7985989dbf8e2ad0f3b8 

If we want to put it in deeper that is cool, I just don't know the list of objects to include.  Even on the simulation tab I don't know that all the objects on that tab should be constructed for every model?  Although, maybe they should be?

**Comment by DavidGoldwasser** [comment]
@macumber with old code I think you have to click on the field, change it to non default value, and then change it back to it to have it work, just seeing the value didn't assure that the object was made. But your fix to force that object to be made when the App launches is fine.

I've had trouble getting my build env. up. I'm going to see if I can get it working at home tonight, away from NREL network. Then I can check this and daylight savings branches.

**Comment by DavidGoldwasser** [comment]
@macumber so here is what I see now.

- When I open and save an OSM flle it doesn't write OS:Timestep.
- When I go to sim settings tab it shows 6, but still doesn't worke OS:Timestep object.
- When I run simulation this warning shows on eplusout.err "** Warning ** No Timestep object found.  Number of TimeSteps in Hour defaulted to 4."
- What's odd is that the EnergyPlus idd for 8.5 shows default of 6 which is what shows in OS GUI.

@Myoldmopar is the EnergyPlus warning an incorrect warning.

@macumber just to follow up on one last thing.
- When I go and change the value away from 6 it then gets saved to the OSM, and also the IDF.

So while we haven't gotten OpenStudio GUI to force that object to be made, if EnergyPlus is really running at 6 timesteps an hour, then we can still close this since they are in sync.

**Comment by macumber** [comment]
Let's not close this until it is really fixed

**Comment by DavidGoldwasser** [comment]
Ok,

@Myoldmopar I looked at the eio file It seems to show 4 time steps as well.
`! <Timesteps per Hour>, #TimeSteps, Minutes per TimeStep {minutes}
 Timesteps per Hour,  4, 15`

Here is the Idd
`Timestep,
       \memo Specifies the "basic" timestep for the simulation. The
       \memo value entered here is also known as the Zone Timestep.  This is used in
       \memo the Zone Heat Balance Model calculation as the driving timestep for heat
       \memo transfer and load calculations.
       \unique-object
       \format singleLine
  N1 ; \field Number of Timesteps per Hour
       \required-field
       \note Number in hour: normal validity 4 to 60: 6 suggested
       \note Must be evenly divisible into 60
       \note Allowable values include 1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30, and 60
       \note Normal 6 is minimum as lower values may cause inaccuracies
       \note A minimum value of 20 is suggested for both ConductionFiniteDifference
       \note and CombinedHeatAndMoistureFiniteElement surface heat balance algorithms
       \note A minimum of 12 is suggested for simulations involving a Vegetated Roof (Material:RoofVegetation).
       \default 6
       \type integer
       \minimum 1`

**Comment by DavidGoldwasser** [comment]
I guess the fact that if you have the object but don't have that field defaults to 6 doesn't mean that if you are missing that object all together that the value also has to be six. Although it is a bit of an odd choice not to have them in sync.

**Comment by macumber** [comment]
@DavidGoldwasser I think this just did not get merged for some reason

@evanweaver is there still time to make sure [this commit](https://github.com/NREL/OpenStudio/commit/7424abeda4b7c31a9e86fd263faa07de16a027fc) makes it into the iteration build?

**Comment by evanweaver** [comment]
@macumber no problem, has this code now been merged? I'll re-release when it has been.

**Comment by macumber** [comment]
Yup it's there

**Comment by DavidGoldwasser** [comment]
Looks good. @evanweaver thanks for the new installer. No issues with it, I'll do more testing tomorrow.

**Comment by evanweaver** [comment]
@DavidGoldwasser thanks for kickin' the tires.
