### ISSUE TITLE
Daylight control min input power is not reflected in energyplus

### ISSUE THREAD

**Issue by fengcool** [NREL/OpenStudio#2100]
Hi,

When I use Openstudio sketchup plugin, add a new “daylight control” to a zone, however the “minimum input power” and “minimum light output” values I specified are not reflected in EnergyPlus IDF file. Please fix the bug. Thanks.

**Comment by macumber** [comment]
These should be translated here: https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp#L416.  Note that the fractions are only translated from the primary daylighting control, not the secondary one

**Comment by fengcool** [comment]
Thanks. I use the default min input power value, that is why it is not explicitly shown in IDF file.

**Comment by macumber** [comment]
Not translating defaults is a bad pattern that we used to use, I think I will leave this ticket open to address that but it doesn't seem like a critical bug.  Thanks for the report!

**Comment by kbenne** [comment]
@mpraprost We want to remove all of these ::isFooDefaulted checks in this file. Here is one example https://github.com/NREL/OpenStudio/blob/develop/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp#L491

**Comment by mpraprost** [comment]
@kbenne when removing the ::isFooDefaulted checks, do we want to remove the entire if statement, or simply remove the condition (and keep the lines inside the if statement)?

**Comment by kbenne** [comment]
hey @mpraprost please remove the if statement but keep the lines inside the if statement.
