### ISSUE TITLE
Air wall construction missing

### ISSUE THREAD

**Issue by fengcool** [NREL/OpenStudio#2113]
Hi,

I am using Openstudio 1.10.0. I start the project using template “office, 189.1, 5B”. The “air wall” construction is missing. I try several other templates, air wall is still missing. Please help. Thanks.

**Comment by DavidGoldwasser** [comment]
@fengcool are you in SketchUp plugin or OS app. SketchUp plugin should have it in template. in OS app it can be pulled in from the library. If that doesn't seem to be the case for you please provide more details and I can re-open this.
