### ISSUE TITLE
1.10.4 - Thermal Zones inspector breaks after deleting zone hvac object

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2117]
In my case, deleting a FanZoneExhaust from a zone. Workaround is to navigate to a different tab and then back to Thermal Zones.

**My Model**
![image](https://cloud.githubusercontent.com/assets/8397034/13471435/d46ad8bc-e06d-11e5-88fa-36d5c435d5c1.png)

**Library**
![image](https://cloud.githubusercontent.com/assets/8397034/13471446/dd65e10a-e06d-11e5-97fb-2939b7099c4d.png)

**Edit**
![image](https://cloud.githubusercontent.com/assets/8397034/13471453/e6d76e70-e06d-11e5-8599-253ba6f13968.png)

**Comment by MatthewSteen** [comment]
This behavior is inconsistent and may take a few attempts to reproduce with FanZoneExhaust or other objects.

**Comment by kbenne** [comment]
@evanweaver can you take this one?

**Comment by evanweaver** [comment]
yup

**Comment by MatthewSteen** [comment]
Possibly related to or a duplicate of #1550.

**Comment by jmarrec** [comment]
This issue is probably stale isn't it?

**Comment by MatthewSteen** [comment]
Haven't seen this in a while.
