### ISSUE TITLE
ModelToRad Preprocess makes bad model clone (Bugzilla #950)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#212]
On 2012-10-10 11:08:31, @rpg777 wrote:

> The modeltoidf bit in the ModelToRadPreProcess is failing with models containing interior doors or windows, because the cloned model has all its interior surfaces set to adiabatic -- the exported .idf, if containing interior doors/windows, will not pass muster with EnergyPlus.
> 
> Just need an additional step where all adiabatic surfaces are stripped of subsurfaces, I think. Dan?

**Comment by evanweaver** [comment]
No longer valid as Radiance is in a measure.

**Comment by rpg777** [comment]
This was fixed. The fact that Radiance simulations are performed via measure did not invalidate this issue.
