### ISSUE TITLE
heat pump water heater (hpwh) object cooling/heating priority always 1

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2125]
The WaterHeaterHeatPump object cooling/heating sequence in the ZoneHVACEquipmentList object is set to 1 no matter what order it was added to the zone in the GUI. In the image below the HPWH objects were the last to be added to the zone, but float to the top.

![image](https://cloud.githubusercontent.com/assets/8397034/13548013/7eb8537c-e2a2-11e5-9e39-554d33444b36.png)

**Comment by MatthewSteen** [comment]
Looks like heating and cooling priorities are hard-assigned.

https://github.com/NREL/OpenStudio/blob/8296251db964cfdac272468381950d6327b42500/openstudiocore/src/model/WaterHeaterHeatPump.cpp#L511

**Comment by jmarrec** [comment]
Still relevant today: https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/WaterHeaterHeatPump.cpp#L523

This would just be a matter of removing these two lines.

Was there any reason you chose to do this @kbenne (you were the one who added it in https://github.com/NREL/OpenStudio/commit/1c05a0de18385e7f16c53a24d29bc5db87042266 on Fri Jun 5 13:01:36 2015 -0500)

**Comment by asparke2** [comment]
@kbenne figure out the original reason for implementing this before changing anything.

**Comment by jmarrec** [comment]
I can speculate here on why it's that way:

* The IDF example all have it first in line
* More importantly, **the HPWH just adds a load to the Zone, its purpose is not to condition the zone**, and therefore **you probably do want to put it first in line to ensure the rest of the equipment sees its added load** (especially true in older versions where the zone Load Distribution Scheme was SequentialLoad and couldn't be changed)

That being said, I took an example file from E+ (`HeatPumpWaterHeater.idf`) and put the HPWH second in the zone, and E+ didn't complain one bit about it.

Unless someone can give arguments as to why we should alter the current behavior, I suggest to leave it that way.

**Comment by MatthewSteen** [comment]
Thanks @jmarrec.
