### ISSUE TITLE
1.10.4 EnergyPlus crash with Output:Table:SummaryReports measure

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2126]
EnergyPlus will crash with an EP measure that sets the `Output:Table:SummaryReports` object to anything other than 'AllSummary'. Possibly related to the version of OS or model size as the measure has run successfully in a previous version with a smaller model.

>Errors
Process crashed.
Process exited with a non-zero exit code of: -1073741819
Process crashed.
Error report file indicates that the process did not complete
Error report file indicates that the process did not complete successfully
GetSurfaceData: There are 6 degenerate surfaces; Degenerate surfaces are those with number of sides

**Comment by macumber** [comment]
I tried with AllSummaryAndMonthly and did not see a crash.  If you get an Idf that crashes when you run it in EP-Launch I'd submit that to the E+ team as a bug

**Comment by macumber** [comment]
@MatthewSteen is this still valid?
