### ISSUE TITLE
Zone Tab - OS:ZoneHVAC:PackagedTerminalHeatPump fields won't go to hard size in GUI (Bugzilla #951)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#213]
On 2012-10-10 11:10:42, @DavidGoldwasser wrote:

> There is also an âOutdoor Air Flow Rate During Cooling Operationâ  as well as âHeatingâ and âno cooling or heatingâ . All of those are set to Autosize. I want to add a step 8 as shown below, but when I move away from the object and come back after changing it to hardsize it at least in the GUI flips back to Autosize.
> 
> So I did go into osm file with a text editor. If I set it to "0" there versus "Autosize" it does show it as hardsized in the GUI. I can use this as work around to prep file for Brent.
> 
> I also tested in the GUI changing from autosize to hardsize. That does seem to stick (at least in the GUI).

On 2012-10-10 11:13:02, @DavidGoldwasser wrote:

> Ok Kyle, thing I figured something out, and maybe don't even need fix now.
> 
> I had been switching to hardsize, but leaving the value at "0". If instead i type a value like 2 it does stick. And then I can change it back to "0". Even just clicking in the field with the "0" is enough without changing it.

**Comment by evanweaver** [comment]
Fixed.
