### ISSUE TITLE
Extra singlezone SPM humidity min created if humidifier downstream of fan

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2145]
If you have the configuration below, where you have a humidifier downstream of a fan, and therefore a humidity control SPM on the supply outlet node, the SPM magic creates an unnecessary clone of the humidity SPM on the upstream side of the humidifier.  @KaiyuSun found this configuration in the outpatient reference building.

I think the current workarounds are either to move the humidifier upstream of the fan, or to manually specify the SPMs so the magic doesn't happen.

![image](https://cloud.githubusercontent.com/assets/2009290/13688993/c8c4dc26-e6e2-11e5-9872-ca1d0d687ea7.png)

Here's the example OSM:
[spm_humidity_minimum.osm.txt](https://github.com/NREL/OpenStudio/files/168262/spm_humidity_minimum.osm.txt)

**Comment by jmarrec** [comment]
This happens here: https://github.com/NREL/OpenStudio/blob/7cec475621233fcd772de2c6715ef9252bcbb7a6/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVAC.cpp#L195-L204
