### ISSUE TITLE
Chilled Water & Ice Storage objects missing from My Model on HVAC tab

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2152]
Similar to a WaterheaterMixed, the ThermalStorageChilledWaterStratified &   ThermalStorageIceDetailed objects are water-to-water components that can be connected to one loop on the demand side and another on the supply side.  In order to do this in the GUI, you need library categories for those objects on the My Model section of the HVAC tab.

Workaround:  connect the ThermalStorage object to the other loop via an OpenStudio Measure.

**Comment by eringold** [comment]
Note: [ThermalStorageIceDetailed](http://bigladdersoftware.com/epx/docs/8-6/input-output-reference/group-plant-equipment.html#thermalstorageicedetailed) has a single set of input/outlet node connections.

**Comment by jmarrec** [comment]
Should be closed per #2815, details in #2266

**Comment by jmarrec** [comment]
Bump to close!
