### ISSUE TITLE
HVAC Tab - Thermal Zones ni Library collapse as soon as you add one to drop zone (Bugzilla #954)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#216]
On 2012-10-11 09:04:14, @DavidGoldwasser wrote:

> This makes it awkward to drop on multiple zone, because you have to keep expanding the list of zones.
> 
> This only happens on certain template. It seems to be template that have non direct terminals. on them.

On 2012-11-16 12:40:28, @DavidGoldwasser wrote:

> Only affects templates 5 & 7, so seems related to hot water reheat. But if I build my own loop with hot water reheat it doesn't exhibit this behavior.

**Comment by jmarrec** [comment]
No longer true in OS 2.2.1, it stays expanded.
