### ISSUE TITLE
Open Studio 1.10.0 makes SketchUp 2016 crash

### ISSUE THREAD

**Issue by ram5931** [NREL/OpenStudio#2161]
All,
 I am having a hard time trying to figure out why Open Studio makes SketchUp 2016 crash. Sketchup will work fine but when I install Open Studio, as soon as I do a File - Open SketchUp will crash. Anybody have an idea why?

**Comment by macumber** [comment]
@ram5931 what platform are you on?  Mac or Windows?  If Windows, are both SketchUp and OpenStudio 32bit or 64bit?

**Comment by macumber** [comment]
Also, do you have any other plugins installed?
