### ISSUE TITLE
Sometimes when running a simulation a full IDF isn't run, but simulation finishs without error (Bugzilla #955)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#217]
On 2012-10-11 10:30:50, @DavidGoldwasser wrote:

> Created an attachment (id=225)
> Use this to produce problem with forward translation.
> 
> Of course there are no results, since the IDF is almost empty. This should show as Failed.
> 
> You can duplicate this using the attached file
> 1. Open the file
> 2. select the fan for the airloop and change âAvailability Schedule Nameâ to "Always On" instead of "Always On 2".
> 3. Set weather file to Golden, it already has ddy
> 4. Save and run a simulation.
> 1. If you switch back to "Always On 2" then it will export and run correctly.
> 
> A seperate mystery is why "Always On" doesn't work since it looks just like "Always On 2" except it uses a rule vs. default profile. Maybe it has a different class?

On 2012-12-12 11:15:09, @elainethale wrote:

> It sounds like the problem is with running the simulation and reporting results ... not with forward translation per se ... Are you expecting the Forward Translation step to be marked as failed, or the EnergyPlus simulation?

On 2012-12-12 11:26:24, @DavidGoldwasser wrote:

> The underlying bug may have been fixed, but the concern I had was that The simulation tab sold me everything worked, yet I had no simulation results. I think the forward translation should have shown as failed; and this should happen without the user having to dig through the tree.
> 
> I'd almost like to have this halt before trying to run a simulation. I can imagine a less sever case where only a few objects are missing, and then I would have seen results, and never questioned them. It is only because this model was almost empty that I realized something was wrong.

On 2012-12-17 10:44:18, @elainethale wrote:

> This sounds like a problem with how the run tab/RunManager works and displays information. I am reassigning it to Jason.

Original attachments:
- 1010_MultiHVAC_c.osm (ID 225)

Keywords: ForwardTranslation

**Comment by evanweaver** [comment]
Pre-2.0 issue.
