### ISSUE TITLE
Expose Sky Clearness field in OS App for Design Days

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2175]
See https://unmethours.com/question/16033/openstudio-solar-model-indicator/?comment=16056#post-id-16056

I don't see a reason why this field shouldn't be exposed, the two Tau (taub and taud) are exposed

**Comment by arif-hanif** [comment]
if you have the clearness number in the ddy file when you import the App stores the value in the simulation even  though it is not exposed in the app.

**Comment by jmarrec** [comment]
The "Sky Clearness" is now available in the OS App, the only problem is that it's on the wrong tab, should be in "Solar" instead of Pressure/Wind/Precipitation

**Comment by jmarrec** [comment]
Fixed in #2815:

Moved Sky Clearness to the right tab "Solar":

![2175_skyclearness_on_solar_tab](https://user-images.githubusercontent.com/5479063/31218666-58bf3ea6-a9bb-11e7-94c9-d0b61adf827d.png)
