### ISSUE TITLE
WaterHeaterMixed - Ambient Temperature Indicator : Outdoors does not work

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#2177]
Need to make the oa node as an actual oa node.

**Comment by DavidGoldwasser** [comment]
@kbenne looks like I just made story in Pivotal. Can you give me a quick instruction on how to test if this fix worked.

**Comment by dstuder** [comment]
@DavidGoldwasser Testing this now.

**Comment by dstuder** [comment]
@kbenne @DavidGoldwasser Looks like setting the “Ambient Temperature Indicator” to “Outdoors” (and also specifying an outdoor air node) now leads to the proper heat transfer, so from my end, this is complete. However, Kyle's not above implies to me that OS should be inserting an outdoor air node if one isn't specified, and that behavior is not present.
