### ISSUE TITLE
Plenum Space Type - space.spaceType.is_initialized not functioning as expected

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2178]
OpenStudio has special logic that automatically creates a space type called "Plenum Space Type" if you use a thermal zone as a supply or return air plenum. That space type is used for spaces that are part of the thermal zone used as a supply/return air plenum if they don't already have a space type hard assigned. 

When I call `space_type.spaces` on "Plenum Space Type" it finds the plenum spaces.

But when I hit one of the spaces that is using the Plenum Space Type when doing `spaces.each do` it shows that there isn't a space type assigned. `space.spaceType.is_initialized` returns false.

This causes an issue because many measures first process spaces that have space types assigned, by altering the space type, and then loop through spaces to alter spaces that don't have space types assigned. The plenum spaces in this scenario may be processed twice. I ran into issues similar to this on the QAQC measures with the medium office prototype building.

I believe the solution here is to update the 'spaceType' for 'space' to look and see if "Plenum Space Type" is used. If it is then `space.spaceType.is_initialized` should return true.

cc: @asparke2 @kbenne

**Comment by macumber** [comment]
FYI: Plenum Space Type is similar to the Always On schedules in that it is searched for by name
