### ISSUE TITLE
Plenum Space Type - Odd behavior when rename space type

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2179]
I'm showing this in the GUI, but would impact measures as well where the measure writer renames a space type after altering it (e.g. after lowering infiltration by%). See screenshots with description of behavior.

![screen shot 2016-03-31 at 9 30 43 am](https://cloud.githubusercontent.com/assets/4857055/14182069/0370866e-f727-11e5-89b8-d1a4b5cda3e4.png)
This is a picture of the Medium Office Prototype building. The measure doesn't make a "Plenum Space Type" space type directly, that was made by OpenStudio behind the scenes. In this case I assigned a schedule set so I could add infiltration, but another common change would be setting measure tags or a construction set.

![screen shot 2016-03-31 at 9 31 09 am](https://cloud.githubusercontent.com/assets/4857055/14182143/4361bdba-f727-11e5-8ee6-1d778f56b687.png)
I renamed the space type and didn't appear to cause any issues. If I save my model and look at the OSM by hand the "Custom Plenum ST" is in my OSM, and "Plenum Space Type" is not. Oddly if I run a simulation a downstream OSM that isn't saved in the project directory adds in a new empty "Plenum Space Type" object which is used by the plenums. This shows up on the standard report but I can't inspect it in the OSM file (yet)

![screen shot 2016-03-31 at 9 31 42 am](https://cloud.githubusercontent.com/assets/4857055/14182231/a6965c92-f727-11e5-9377-146b45e5a633.png)
Once you go to the Spaces tab then OpenStudio generates a new "Plenum Space Type" in the model which you can see in the grid view for the spaces. Just leaving the Space Type tab isn't enough (e.g. going to Building Tab doesn't re-add the space type).

![screen shot 2016-03-31 at 9 31 56 am](https://cloud.githubusercontent.com/assets/4857055/14182288/d5aacea0-f727-11e5-9455-5492959872a8.png)
Now when I go back to the Space Type tab I can see the newly made "Plenum Space Type" It doesn't have any of the customizations that I had previously made to it, Those customizations are in the "Custom Plenum ST" space type which isn't used by anything.

Talking with @macumber I think the solution here may be to lock down the name of the "Plenum Space Type" space type (both in GUI and API), but I'm open to other solutions. If the new space type had the customizations that I had previously made, that would be fine, or if OpenStudio hard assigned "Custom Plenum ST" to the affected spaces, that would also be ok. I understand all of these solutions may not be ideal.

If we don't make changes then we should document well how "Plenum Space Type" works. For example would a user know that it works with return and supply air plenums, but not unconditioned (ducted) plenums and attics. If a user (through a measure or manually) converted an open return air plenum to a ducted plenum (by removing the HVAC plenum object) and they didn't go back and inspect the model, they would miss that the building default space type now would be applied to the plenum spaces instead of the "Plenum Space Type". 

cc: @asparke2 @kbenne @evanweaver

**Comment by macumber** [comment]
Solution is to not allow user to edit the name of the Plenum Space Type

**Comment by DavidGoldwasser** [comment]
@asparke2 and @macumber I still think we should keep this on the radar for documentation in the future. This automatic space type application can be confusing and brakes typical pattern. I would think the plenum space type would typically have custom construction set for floor and ceilings, similar to attics, and may also have infiltration. It is made empty by default. Should other spaces not included in the building area also get this or just those with plenum as return or supply plenum.

**Comment by macumber** [comment]
@DavidGoldwasser can you weigh in on this again?  I reverted the code that was preventing us from changing the name because that was leading to other issues, can we just live with this issue?

**Comment by jmarrec** [comment]
Re #2853, @macumber I'm not 100% sure I'm following the logic now that you changed it in the last 4 commits.

You are allowing the Plenum Space Type to be cloned and renamed. I thought the idea was that this one be should unique. I was assuming it was used in Forward Translation, or for other things like isPlenum(), but now I see that it apparently isn't.

So I'm not sure why we need a Model-"unique" plenum space type to begin with, it seems completely useless. Am I missing something there?

**Comment by macumber** [comment]
The idea is that we don't want plenums to inherit building level space types (e.g. with lights, people, etc)

We want plenums to inherit an empty (to start with at least) space type

**Comment by macumber** [comment]
You might want to add loads to your plenum space type (David adds infiltration), we could go back to not allowing you to change the name of the space type, but i felt like not allowing you to clone it was a step too far.  So I thought we should just rewind under the principle that it is better to keep things simple.  Another option was to simply lock down the name in the UI but not the API, I do think the user needs to understand this is a special space type at least.

**Comment by jmarrec** [comment]
Got it, not inheriting building space type was the part I was missing. Thanks

**Comment by macumber** [comment]
Can this be closed as of 2.4.0 @jmarrec ?

**Comment by jmarrec** [comment]
As far as I’m concerned yes
