### ISSUE TITLE
Mac only issue with Prototype Type Measure (will only impact 1.11.1 or later)

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2180]
@asparke2 and I have been testing this. On Mac and Windows in 1.10.0 there are Boost asserts with the Prototype Measure for Medium Office, but it doesn't stop the measure from running.

```
[openstudio.runmanager.LocalProcess] <1> Starting LocalProcess: /Applications/OpenStudio 1.10.5/sharedresources/EnergyPlus-8-5-0/energyplus
[BOOST_ASSERT] <2> Assertion polygon.inners().empty() failed on line 552 of std::vector<Point3d> openstudio::verticesFromBoostPolygon(const BoostPolygon &, std::vector<Point3d> &, double) in file /Users/alexswindler/OpenStudio/openstudiocore/src/utilities/geometry/Intersection.cpp.
[BOOST_ASSERT] <2> Assertion polygon.inners().empty() failed on line 552 of std::vector<Point3d> openstudio::verticesFromBoostPolygon(const BoostPolygon &, std::vector<Point3d> &, double) in file /Users/alexswindler/OpenStudio/openstudiocore/src/utilities/geometry/Intersection.cpp.
```

But when run on 1.10.5 or later on mac only (OS App or command line) the measure fails. The following lines are in addition to the Boost asserts. I tested on a non dev mac to confirm it isn't just my machine.

```
Assertion failed: (false), function assertion_failed, file /Users/alexswindler/OpenStudio/openstudiocore/src/utilities/bcl/../core/Assert.hpp, line 51.
Abort trap: 6
```

We haven't tracked down why yet. Ideally we would like to fix this for 1.11.1 which will be the first installer with the openstudio-standards gem.

**Comment by macumber** [comment]
Likely an issue with polygon methods failing on complex daylighting shapes

**Comment by mbadams5** [comment]
@DavidGoldwasser Are you using the most recent code from OpenStudio-Standards? With current master, I pass all 90 Medium Office unit tests if I test all 15 climate zones and 6 vintages. This is on my Mac with OpenStudio 1.10.0

**Comment by macumber** [comment]
If the error is occurring in all versions but only halting in the 1.10.5 Mac builds then it is possible that those Mac builds have different configurations (normally asserts are compiled out in release builds).  However, you aren't getting good answers back in the other builds so it is a problem in all packages

**Comment by DavidGoldwasser** [comment]
@mbadams5 I'm fine to on 1.10.0. Only breaks 1.10.5 or later. I tested with what is on ruby gems and also current master on openstudio-standards repo.

**Comment by asparke2** [comment]
@macumber Yeah, these are assertions thrown in the daylighting shapes.  I detect them and then try a different approach when they happen, which makes the modeling results good enough.  I think you're right about the assertions not being compiled out in the Mac build this time.  The linux build appears to be fine; the openstudio-standards CI is running fine with 1.10.6 and 1.11.0.

**Comment by macumber** [comment]
Probably need to change these from asserts to some other error handling

**Comment by asparke2** [comment]
In openstudio-standards, or in the geometry library?

**Comment by DavidGoldwasser** [comment]
@evanweaver's updated installer doesn't fail at the asserts, so the measure completes successfully. @macumber are you fine closing this issue  or do you want to keep it open to address why asserts are being thrown.

**Comment by macumber** [comment]
Yes let's leave it open to fix the assert, my guess is that the assert should be replaced by different error handling since this error does occur in regular use

**Comment by DavidGoldwasser** [comment]
@asparke2 did you put in some work around to get around this for the prototypes?

**Comment by asparke2** [comment]
@DavidGoldwasser I don't remember what this is about at all, but if it's still happening then I probably never made an attempt to fix.  I honestly haven't used the prototype measure in several years.

**Comment by jmarrec** [comment]
I'm closing, happy to reopen (or open a fresh issue) if someone hits it again.
