### ISSUE TITLE
Wrong boundary in OS:WaterHeater:HeatPump  'Minimum Inlet Air Temperature for Compressor Operation'

### ISSUE THREAD

**Issue by Anto-F** [NREL/OpenStudio#2182]
The 'Minimum Inlet Air Temperature for Compressor Operation' should be -5°C (ref EnergyPlus InputOutput Reference).
Currently, we cannot type any value below 5°C (OpenStudio 1.11).

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/resources/model/OpenStudio.idd#L22795

**Comment by jmarrec** [comment]
This already made it in develop

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/resources/model/OpenStudio.idd#L23385

Close it

**Comment by jmarrec** [comment]
@macumber Like I said a while ago, you can close this one.
