### ISSUE TITLE
Daylight savings time allways get the American option

### ISSUE THREAD

**Issue by dani71** [NREL/OpenStudio#2185]
Hi,
I'm trying to use **daylight savings time** with the european option, that consists in the last sunday of march and the last sunday of october.

But no matter what I choose **in the OS interface**, what I allways get in the run\1-UserScript-0\out.osm file is:
```
OS:RunPeriodControl:DaylightSavingTime,
  {ca77f7f6-cbc4-40cc-b111-81fcaa8feeda}, !- Handle
  2nd Sunday in March,                    !- Start Date
  1st Sunday in November;                 !- End Date
```
and in the expanded.idf file:
```
RunPeriodControl:DaylightSavingTime,
  2nd Sunday in March,                    !- Start Date
  1st Sunday in November;                 !- End Date
```

thanks.

**Comment by DavidGoldwasser** [comment]
Here are results with OpenStudio 1.11.5 installer

`OS:RunPeriodControl:DaylightSavingTime,
  {32386287-d4f2-4518-874d-4645ac86f0d1}, !- Handle
  5th Sunday in Mar,                      !- Start Date
  5th Sunday in Oct;                      !- End Date`

`RunPeriodControl:DaylightSavingTime,
  5th Sunday in Mar,                      !- Start Date
  5th Sunday in Oct;                      !- End Date`

**Comment by DavidGoldwasser** [comment]
@macumber even if I set my calendar year to 2017 which doesn't have a fifth Sunday in May, it still shows what I have above.
http://www.timeanddate.com/calendar/?year=2017&country=1

OS:YearDescription,
  {5fbdc92e-b5cc-4ab0-9bdb-51bbcec06b6d}, !- Handle
  2017,                                   !- Calendar Year
  ,                                       !- Day of Week for Start Day
  ;                                       !- Is Leap Year
