### ISSUE TITLE
change 90.1 construction sets to match the PRM

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2188]
In particular the walls and floors.

Table G3.1 no. 5
>b. Opaque Assemblies. Opaque assemblies used for new buildings, existing buildings, or additions shall conform with the following common, lightweight assembly types and shall match the appropriate assembly maximum U-factors in Tables 5.5-1through 5.5-8:

>• Roofs—Insulation entirely above deck
• Above-grade walls—Steel framed
• Floors—Steel joist

**Comment by asparke2** [comment]
We are not going to do this.  The construction sets are defined by the Prototype buildings, which have different construction types than Appendix G.
