### ISSUE TITLE
Many model test failures (Bugzilla #957)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#219]
On 2012-10-12 10:16:22, @macumber wrote:

> There are many model test failures in material object tests which were autogenerated by never retouched to have correct values.  These should not be hard to fix, just need to assign appropriate test values.

On 2012-10-12 10:24:37, @macumber wrote:

> To reproduce need to run the model tests, either at the command line or from within Visual Studio.

**Comment by evanweaver** [comment]
1133 passed
1 skipped (ISOModelFixture, DISABLED_ForwardTranslator)
1 failed (ModelFixture, Surface_createAdjacentSurface)

@macumber I am going to close this, with the knowledge that you are currently working on Surface_createAdjacentSurface, and Kyle is working on the release-only test failure.
