### ISSUE TITLE
MultiSpeed Coil Inlet/Outlet Nodes Not Being Connected Properly

### ISSUE THREAD

**Issue by dstuder** [NREL/OpenStudio#2191]
There appears to be an issue when attempting to add multispeed coil objects (CoilHeatingDXMultiSpeed or CoilCoolingDXMultiSpeed) to an AirLoopHVAC:UnitarySystem object. Using:

new_heating_coil = OpenStudio::Model::CoilHeatingDXMultiSpeed.new(model)                    
air_loop_hvac_unitary_system.setHeatingCoil(new_heating_coil)

Successfully includes the coil in the model, but the Air Inlet Node and Air Outlet Node names in the coil object itself are found to be blank, causing the simulation to fail.

This issue is not seen with single speed coils. For example, using:

new_cooling_coil = OpenStudio::Model::CoilCoolingDXSingleSpeed.new(model)                    
air_loop_hvac_unitary_system.setCoolingCoil(new_cooling_coil)

Successfully incorporates the coil into the model and makes the appropriate node connections. This behavior was observed in 1.10.4 and 1.11.0.

**Comment by shorowit** [comment]
@dstuder Is this the same as https://github.com/NREL/OpenStudio/issues/2172?

**Comment by dstuder** [comment]
@shorowit Yes, I believe so. Didn't see it when I looked earlier.

**Comment by DavidGoldwasser** [comment]
@kbenne I'll close this as a duplicate but you are assigned to the other copy of it.
