### ISSUE TITLE
assert(!@@co.getDefaultEPWLocation.to_s.empty?) fails in mac on template reporting measure

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2194]
This only affects the unit tests on mac, nor running the measure anywhere else.

https://github.com/NREL/OpenStudio/blob/8296251db964cfdac272468381950d6327b42500/openstudiocore/src/utilities/bcl/templates/ReportingMeasure/tests/reporting_measure_test.rb#L20

Here is the code I currently use in other reporting measure. In this approach a copy of the weather file is in the measure's test directory.
https://github.com/NREL/OpenStudio/blob/8296251db964cfdac272468381950d6327b42500/openstudiocore/src/pat_app/Measures/StandardReports/tests/OpenStudioResults_Test.rb#L15

**Comment by macumber** [comment]
My guess is this has to do with the E+ install on Mac, here is the code that sets the default epw dir:

https://github.com/NREL/OpenStudio/blob/8296251db964cfdac272468381950d6327b42500/openstudiocore/src/runmanager/lib/ConfigOptions.cpp#L1071

Do you have either of these folders in your E+ install?

      openstudio::path weatherdir1 = eplus.localBinPath.parent_path().parent_path() / toPath("WeatherData");
      openstudio::path weatherdir2 = eplus.localBinPath.parent_path() / toPath("WeatherData");

**Comment by DavidGoldwasser** [comment]
"WeatherData" sits right under the EnergyPlus install. I thought at one point this just happened in my dev environment but I confirmed it also happens on my install of 1.11.0.

**Comment by jmarrec** [comment]
This is very outdated, closing.

https://github.com/NREL/OpenStudio/blob/d05bc3a9ba090cf986cde56b7616b7dc445ac2f1/src/utilities/bcl/templates/ReportingMeasure/tests/reporting_measure_test.rb#L14-L19
