### ISSUE TITLE
Timeseries Not Found is being thrown on template reporting measure

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2195]
https://github.com/NREL/OpenStudio/blob/8296251db964cfdac272468381950d6327b42500/openstudiocore/src/utilities/bcl/templates/ReportingMeasure/measure.rb#L119

This happens mac or windows in unit test or GUI. Only shows in unit test if you add "show_output(results)"

**Comment by DavidGoldwasser** [comment]
@macumber looks like key value is the issue. Works if set to 'Environment' instead of blank.
https://github.com/NREL/OpenStudio/blob/8296251db964cfdac272468381950d6327b42500/openstudiocore/src/utilities/bcl/templates/ReportingMeasure/measure.rb#L113

**Comment by macumber** [comment]
If this is in the template new measure we should fix it

**Comment by DavidGoldwasser** [comment]
@macumber I fixed the issue related to timeseries data, but there is another issue (mac specific) on this template related to getting the EPW file in the test. It fails on line 20.

https://github.com/NREL/OpenStudio/blob/8296251db964cfdac272468381950d6327b42500/openstudiocore/src/utilities/bcl/templates/ReportingMeasure/tests/reporting_measure_test.rb#L18-L24

Do you want me to make a new issue for that or add to this one. Here is the branch I'm working on, I'll hold of on pull request until the second issue is fixed.
https://github.com/NREL/OpenStudio/commits/120391243_reporting_measure_template

I don't have a direct mac fix for this, all of the reporting measures I write include the one or more epw's alongside the osm's in the tests directory.

**Comment by DavidGoldwasser** [comment]
Found this file
$HOME/Library/Preferences/com.nrel.OpenStudio.plist

For runmanager_default_weather location it has this '/Applications/OpenStudio 1.11.3/sharedresources/EnergyPlus-8-5-0/WeatherData'

@kbenne can you think of any reasons that this fails in a measure test.

`  # class level variable
  @@co = OpenStudio::Runmanager::ConfigOptions.new(true)
  assert(!@@co.getDefaultEPWLocation.to_s.empty?)
`

**Comment by DavidGoldwasser** [comment]
If we don't get this working by Thursday, my proposed solution is to include the epw with the measure test, that is what I have typically done, sometimes for convenience, other times because I need a specific weather file for the test.

**Comment by macumber** [comment]
@DavidGoldwasser did you fix this?  If so can you close, if not can you tag for 1.14?

**Comment by DavidGoldwasser** [comment]
@macumber still seems valid. All the reporting measures I write have to have copy of epw with measure. The template files on this line

    assert(!@@co.getDefaultEPWLocation.to_s.empty?) 

with this error Expected false to be truthy.

@macumber unless you have another idea I'll included the epw file in the test. That will use Runner for 1.x and CLI with OSW for 2.x

**Comment by macumber** [comment]
@DavidGoldwasser is this fixed?

**Comment by DavidGoldwasser** [comment]
It wasn't directly fixed, i avoided it by removing it's use from all reporting measure tests and the template reporting measure test. All reporting measure tests now have their own EPW file.

Unless you want to try to fix on Mac I'm fine closing this.
