### ISSUE TITLE
SWIG takes 22 minutes to complete on OpenStudioModelHVAC

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2198]
Can we break this up into multiple modules @kbenne and @mbadams5 ?

**Comment by macumber** [comment]
Also takes about 1.5GB of RAM to compile.  The wrapper source file is 46 MB, which is 3x bigger than the next largest module (Resources)

**Comment by caceres** [comment]
I am trying to compile in ubuntu 14.04 and the building stop at 
37% Generating ruby_OpenStudioModelHVAC_wrap.cxx. 
Three hours ago. Is this normal?

**Comment by macumber** [comment]
@kbenne @mbadams5 I think we just need to break this up, you guys would know the best functional lines

**Comment by macumber** [comment]
@kbenne @mbadams5 bump, we should do this next year, it takes ~6-7GB of memory to compile this file, makes it hard to use virtual machines to manage builds

**Comment by kbenne** [comment]
yeah the base classes probably draw some clear lines without much effort.

**Comment by asparke2** [comment]
@kbenne @mbadams5 did this get fixed during the 2.X overhaul?  If so, can you close?

**Comment by macumber** [comment]
Not fixed

**Comment by macumber** [comment]
Shows the SWIG and compile times for this task compared to others

![image](https://user-images.githubusercontent.com/1327850/30343117-7b49e58e-97b9-11e7-918a-36469df1a962.png)
