### ISSUE TITLE
Diagnostic script should test that sub surface points are within base surface

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2199]
https://unmethours.com/question/3908/openstudio-error-sub-surface-is-not-contained-by-its-base-surface/?comment=16563#post-id-16563

**Comment by DavidGoldwasser** [comment]
@macumber, "sub surface not contained by base surface" isn't is checked when an OSM is opened. I'm not sure if that check is using native SketchUp API methods or the openStudio.within method you refer to. In the past this has falsely triggered at times.

I made the "Remove Orphan and Unused Objects" measure to replace the diagnostic script for use outside of SketchUp. I'd prefer to add this new functionality there. I could copy it to the diagnostic script as well, but I'd rather just setup the plugin to call this measure.

What does the openStudio.within do for sub-surfaces that are not in the same plane as base surface, but if they were projected onto the plane, would fit within it? Ideally I would like to allow these to pass the test.

Also would like the sub-surface to share an edge with the base surface (like prototype buildings were fenestration is as wide as the base surface with both offsets.

**Comment by macumber** [comment]
You have to project sub surfaces to the surface in order to use within, I'm not entirely sure what happens if points are exactly on the edge

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/24
