### ISSUE TITLE
HVAC Tab - Hard to tell when outdoor air object is selected (Bugzilla #960)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#220]
On 2012-10-20 20:37:45, @DavidGoldwasser wrote:

> All other objects turn dark when you selected, but the outdoor air object doesn't have any visual indication that it is selected.
> 
> It is also unique from all others in that it has a lighter un-selected color.

**Comment by jmarrec** [comment]
No longer true in OS 2.2.1
