### ISSUE TITLE
Update forward translator so it doesn't translate orphan surfaces

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2204]
Update forward translator so it doesn't translate orphan surfaces. Orphan surface defined as a planar surface that doesn't have a parent surface group. 

Ran across it in this post on UnmetHours
https://unmethours.com/question/16738/input-errors-in-sketchup-model-leading-to-fatal-errors-in-open-studio/

We already have a measure to remove the orphan surfaces from the model as a workaround. I'm also referencing to related issues for user scripts in the plugin related to cleanup of orphan objects. 
Issue #1560 and issue #250

**Comment by macumber** [comment]
Upgrading to major since this causes simulation failure
