### ISSUE TITLE
Fix Variable Speed Pump reporting in standard report

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2208]
https://unmethours.com/question/16894/openstudio-results-plant-loop-details-correct/?answer=16905#post-id-16905

**Comment by eringold** [comment]
@DavidGoldwasser do you have any plans to start using the `autosizedFoo` methods from openstudio_standards to start reporting [autosized](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/pat_app/Measures/StandardReports/resources/os_lib_reporting.rb#L1056) values? I've added some to my own reports, and would be willing to help.

**Comment by DavidGoldwasser** [comment]
@eringold that's a great idea. I made a branch with fixes for exterior lights and pump reporting (it affected both constant and variable speed pumps). 
https://github.com/NREL/OpenStudio/tree/160428_standard_report_update

I'm going to merge the changes I made into develop to make it into the 1.11.2 installer, but if you want to help with changes for 1.11.3 or later that would be great.

Here is one question for you. If we are always going to calculate the resulting size to display, is it still beneficial do know if that size came from auto-sizing routine vs. a value entered by the modeler? Instead of just showing "3,452.5" or should it be "3,452.5 (as)". Or maybe a column could be added to indicate if it is autosized in the osm file. I'm going to ping @asparke2 to get his thoughts on this as well. I don't know that we have logic to get autosized values for all component types.

Another area the measure can use some work is support for newer HVAC components. Any component type will work and show as a row in the table. But I had to put in component type specific logic to show sizing and capacity information about that component.

**Comment by eringold** [comment]
@DavidGoldwasser my thinking has been that it is useful to delineate auto- vs hard-sized values in the report, so I've been appending "(Autosized)" to those values. I'm sure there is any number of more elegant ways to do it, though. You can see some of what I've done with HVAC reporting in the attached file:
[report.pdf](https://github.com/NREL/OpenStudio/files/243715/report.pdf)

As you can see, I took a more 'component type-specific logic' approach, which is definitely more tedious to write. I also had to add some autosize methods for components, but this was done months ago, and I haven't recently checked to see what openstudio_standards supports now.
