### ISSUE TITLE
Assertion failed when cloning material (Bugzilla #963)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#221]
On 2012-10-23 16:05:23, @macumber wrote:

> Example script and model from Phylroy Lopez

On 2012-10-23 16:06:25, @macumber wrote:

> Created an attachment (id=227)
> Test script

On 2012-10-23 16:06:47, @macumber wrote:

> Created an attachment (id=228)
> Test file

Original attachments:
- Clone_glazing_error.rb (ID 227)
- in.osm (ID 228)

**Comment by jmarrec** [comment]
Do you guys have a way to retrieve the script and/or files so we can test if this is still a thing?

**Comment by jmarrec** [comment]
@macumber bump. Without more info, I'm inclined to just close it (it's 6 years old)

**Comment by macumber** [comment]
Let's just close
