### ISSUE TITLE
Can't Access Local BCL Using C# Bindings

### ISSUE THREAD

**Issue by pflaumingo** [NREL/OpenStudio#2211]
Accessing the local BCL doesn't seem to work with 64-bit c# bindings. I'm not very sure of the source of the issue however I tried creating a simple console application in Visual Studio and accessing the local BCL:

var localBCL = LocalBCL.instance();

I then tried calling the prodAuthKey, components and measures methods but none of them return anything. The libraryPath returned the correct path though. I inspected the components.sql file and there is a prodAuthKey set and a series of components and measures. I then tried the same process with the Ruby bindings using Notepad++ and it worked fine - I double checked my C# reference and openstudio path for Ruby were the same bundled release.

This is as far as I've gotten and I'm not sure whether it has something to do with SWIG or something else, but I can't seem to access the local BCL with the C# bindings.

**Comment by macumber** [comment]
@pflaumingo can you verify if this is still an issue?

**Comment by jmarrec** [comment]
@pflaumingo Is this still an issue?

**Comment by pflaumingo** [comment]
No idea, haven't looked at the C# bindings in forever.

**Comment by jmarrec** [comment]
at 3.0.0-rc3, Built the C# bindings, and taken the csharp example `ModelCreateExample`, tweak the config so it builds and runs, then added this code:

```
var localBCL = OpenStudio.LocalBCL.instance();
var prodAuthKey = localBCL.prodAuthKey();
MessageBox.Show("Your LocalBCL prodAuthKey is: " + prodAuthKey);
```

It does show my `prodAuthKey `just fine.
