### ISSUE TITLE
Error when cloning CoolingTowerVariableSpeed

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2212]
OpenStudio 1.11.1, Windows 7

When I clone a `CoolingTowerVariableSpeed` and then attach the clone to the supply side of the same plant loop the original was on, the original gets removed from the loop.  This doesn't occur for `CoolingTowerSingleSpeed` or `ChillerElectricEIR`.  Also, the resulting model crashes if you try to navigate to the loop in the OS App.

Hit this issue working on Baseline Automation; don't think it's possible to create this model in the OS App.  So far the workaround I've come up with is to create a new tower and manually copy all the  fields instead of cloning.  Works, but it's annoying.

Suspect the issue might have something to do with the sharing of the cooling tower fan curve, but can't pin it down.

Run ruby code below to replicate.  Crash the app by navigating to the plant loop in `4_after_attaching_clone.osm` or `5_after_reattaching_first_tower.osm`.

``` ruby
require 'openstudio'

def is_attached?(comp)
  if comp.inletModelObject.is_initialized
    puts "-   #{comp.name} attached"
  else
    puts "-   #{comp.name} NOT attached"
  end
end

# Create a plant loop and a var speed cooling tower
model = OpenStudio::Model::Model.new
cw_loop = OpenStudio::Model::PlantLoop.new(model)
cw_loop.setName("Condenser Loop")
first_tower = OpenStudio::Model::CoolingTowerVariableSpeed.new(model)
first_tower.setName("First Tower")

model_status = "1_before_attaching_first_tower"
puts model_status
is_attached?(first_tower)
model.save(OpenStudio::Path.new("#{Dir.pwd}/#{model_status}.osm"), true)

# Attach the cooling tower
cw_loop.addSupplyBranchForComponent(first_tower)

model_status = "2_after_attaching_first_tower"
puts model_status
is_attached?(first_tower)
model.save(OpenStudio::Path.new("#{Dir.pwd}/#{model_status}.osm"), true)

# Clone the cooling tower
clone_tower = first_tower.clone(model).to_CoolingTowerVariableSpeed.get
clone_tower.setName("Clone Tower")

model_status = "3_after_cloning_first_tower_but_before_attaching_clone"
puts model_status
is_attached?(first_tower)
is_attached?(clone_tower)
model.save(OpenStudio::Path.new("#{Dir.pwd}/#{model_status}.osm"), true)

# Attach the clone
cw_loop.addSupplyBranchForComponent(clone_tower)

model_status = "4_after_attaching_clone"
puts model_status
is_attached?(first_tower)
is_attached?(clone_tower)
model.save(OpenStudio::Path.new("#{Dir.pwd}/#{model_status}.osm"), true)

# Re-Attach the first tower
cw_loop.addSupplyBranchForComponent(first_tower)

model_status = "5_after_reattaching_first_tower"
puts model_status
is_attached?(first_tower)
is_attached?(clone_tower)
model.save(OpenStudio::Path.new("#{Dir.pwd}/#{model_status}.osm"), true)

# Translate to IDF and save for debugging
forward_translator = OpenStudio::EnergyPlus::ForwardTranslator.new
idf = forward_translator.translateModel(model)
idf_path = OpenStudio::Path.new("#{Dir.pwd}/#{model_status}.idf")  
idf.save(idf_path,true)
```

**Comment by jmarrec** [comment]
Confirmed there is still something wrong. OS App doesn't crash anymore because the orphaned node is caught following the safeguard I put in place in PR #3117.
I'll track down the problem.

**Comment by jmarrec** [comment]
https://github.com/jmarrec/OpenStudio/blob/8ec66853fd06ab792ae6352a9e2bd6af1e270284/openstudiocore/src/model/CoolingTowerVariableSpeed.cpp#L132

Calls ModelObject_Impl instead of StraightComponent_Impl. The difference being that StraightComponent_Impl will reset the inlet and outlet Ports of the cloned CT... So here you end up with two CTs having the same inlet and outlet, so it's unhappy.
