### ISSUE TITLE
Spectral Data Set name doesn't forward translate to IDF

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2216]
I see that it should translate in [ForwardTranslateStandardGlazing](https://github.com/NREL/OpenStudio/blob/8296251db964cfdac272468381950d6327b42500/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateStandardGlazing.cpp#L51)

My object is fine:

```

OS:WindowMaterial:Glazing,
 {c2731543-ca13-494c-969a-d4b61633b280}, !- Handle
 Guardian SunGuard  SNX 60/28 _8Clear, !- Name
 Spectral,                               !- Optical Data Type
 Guardian SunGuard  SNX 60/28 _8Clear Spectral Data, !- Window Glass Spectral Data Set Name
 0.00838,                                !- Thickness {m}
 ,                                       !- Solar Transmittance at Normal Incidence
 ,                                       !- Front Side Solar Reflectance at Normal Incidence
 ,                                       !- Back Side Solar Reflectance at Normal Incidence
 ,                                       !- Visible Transmittance at Normal Incidence
 ,                                       !- Front Side Visible Reflectance at Normal Incidence
 ,                                       !- Back Side Visible Reflectance at Normal Incidence
 0,                                      !- Infrared Transmittance at Normal Incidence
 0.84,                                   !- Front Side Infrared Hemispherical Emissivity
 0.02,                                   !- Back Side Infrared Hemispherical Emissivity
 1.0003,                                 !- Conductivity {W/m-K}
 1;                                      !- Dirt Correction Factor for Solar and Visible Transmittance
```

But in my IDF the spectral data set name is gone.

What's the matter?

**Comment by jmarrec** [comment]
I think I know what's happening.

I actually use the "inject_idf_objects" measure to add my Spectral Data Sets (`MaterialProperty:GlazingSpectralData`) at runtime. But if you do a forward translate from .osm to .idf using command line, you get the following:

    [utilities.idf.WorkspaceObject] <0> Object of type 'WindowMaterial:Glazing' and named 'Guardian SunGuard  SNX 60/28 _6Clear', points to an object named Guardian SunGuard SNX 60/28_6Clear Spectral Data from field 2, but that object cannot be located.

At this point, the idf doesn't have the "Window Glass Spectral Data Set Name" anymore:

    WindowMaterial:Glazing,
      HAYAT1_Guardian SunGuard  SNX 60/28 _6Clear, !- Name
      Spectral,                               !- Optical Data Type
      ,                                       !- Window Glass Spectral Data Set Name
      0.006,                                  !- Thickness {m}
      ...

**Comment by macumber** [comment]
I'm not sure how or why this got messed up but basically the OS Model does not support `MaterialProperty:GlazingSpectralData`.  The only real way to fix this issue is to wrap that object

OS Model IDD
```
  A4, \field Window Glass Spectral Data Set Name
       \note Used only when Optical Data Type = Spectral
       \type alpha
```

E+ IDD
```
  A3 , \field Window Glass Spectral Data Set Name
       \note Used only when Optical Data Type = Spectral
       \type object-list
       \object-list SpectralDataSets
```
