### ISSUE TITLE
BCLMeasure should force update if measure.xml missing class_name or other required fields

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2217]

**Comment by macumber** [comment]
@DavidGoldwasser several measures in the openstudio measure repo are affected by this, AedgK12InteriorLightingControls and AedgK12ElectricEquipmentControls are the ones I saw

**Comment by macumber** [comment]
@DavidGoldwasser can you verify by manually removing these fields from the xml and updating?

**Comment by DavidGoldwasser** [comment]
Looks good. I confirmed that the XML for the two files mentioned do have class in xml, and I tested another measure by hand deleting the class field and it was added back.

**Comment by DavidGoldwasser** [comment]
FYI - had been closed in Pivotal but left open here by mistake.
https://www.pivotaltracker.com/n/projects/134010
