### ISSUE TITLE
Temp dir is not deleted

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2221]
To reproduce, open the app, close it, temp directory is not deleted.  Temp dir should be in C:/Users/xxx/AppData/Local/Temp/ or C:/Users/xxx/AppData/Local/Temp/1/.  Log file shows this:

[removeDir] <-1> removeDir 'C:/Users/xxx/AppData/Local/Temp/1/OpenStudio.D11220'
[removeDir] <-1> removeDir 'C:/Users/xxx/AppData/Local/Temp/1/OpenStudio.D11220/resources'
[removeDir] <-1> removeDir 'C:/Users/xxx/AppData/Local/Temp/1/OpenStudio.D11220/resources/files'
[removeDir] <-1> removeDir 'C:/Users/xxx/AppData/Local/Temp/1/OpenStudio.D11220/resources/run'
[removeDir] <-1> removeDir 'C:/Users/xxx/AppData/Local/Temp/1/OpenStudio.D11220/resources/scripts'
[removeDir] <1> Failed to remove file 'C:/Users/xxx/AppData/Local/Temp/1/OpenStudio.D11220/resources/project.log'
[removeDir] <1> Failed to remove file 'C:/Users/xxx/AppData/Local/Temp/1/OpenStudio.D11220/resources/project.osp'
[removeDir] <1> Failed to remove file 'C:/Users/xxx/AppData/Local/Temp/1/OpenStudio.D11220/resources/run.db'
[removeDir] <1> Failed to remove directory 'C:/Users/xxx/AppData/Local/Temp/1/OpenStudio.D11220/resources'
[removeDir] <1> Failed to remove directory 'C:/Users/xxx/AppData/Local/Temp/1/OpenStudio.D11220/resources'
[removeDir] <1> Failed to remove directory 'C:/Users/xxx/AppData/Local/Temp/1/OpenStudio.D11220'

Not sure if this happens on Mac or Linux

**Comment by jmarrec** [comment]
![30gb of openstudio folders](https://cloud.githubusercontent.com/assets/5479063/15151225/924dce5a-16d0-11e6-9c55-3c7fb2b76459.png)

Yep, 30 GB of OpenStudio folders. Some of them only have a resource folder with `project.log`, `project.osp` and `run.db` in there.

Others have the full run directory with some 7 GB .eso and some 9 GB sql.

**Comment by jmarrec** [comment]
Good job finding this needle in this specific haystack @macumber !
