### ISSUE TITLE
Daylighting Controls Measure: OS:Daylighting:Control objects do not forward translate in certain cases

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2225]
I was testing this from this user post.
https://unmethours.com/question/17192/add-daylight-sensor-at-the-center-of-space/

After seeing this with a model made by the measure, I was able to reproduce with a fresh model by hand.
1. Add new space to empty model, optionally draw geometry
2. Assign thermal space to new thermal zone
3. Add daylighting control to space.
4. Save OSM file (it has daylighting control object associated with thermal zone.)
5. Export IDF file (it doesn't have daylighting control)

cc: @rpg777

**Comment by macumber** [comment]
I just did this in 1.11.0 and could not reproduce, I tried with and without surfaces in the space.

**Comment by DavidGoldwasser** [comment]
Sorry @macumber I think you are right. I was searching for the name of the daylighting control object in the IDF, but I see it isn't named, but just refers to the zone name. I'll close this as invalid.

**Comment by rpg777** [comment]
But, the user is still having the issue.

**Comment by macumber** [comment]
My guess is the measure isn't hooking the control up to the zone?  Maybe they are running the measure before zones are created?

**Comment by rpg777** [comment]
Maybe; I don't have time to test it right now, but I wouldn't call this issue "invalid". Reopening.

**Comment by DavidGoldwasser** [comment]
The measure appears to be hooking up to zones, but maybe there is something unique about the input model the user has. The test model for the measure has zones with one space and zones with many spaces. They zones have daylighting controls hooked up, and those make it into the IDF file as well.

@rpg777 what I meant was invalid was the forward translation issue. If there is an issue with the measure I could file an issue for that.

**Comment by rpg777** [comment]
The issue *is* with the measure; the GH Issue was poorly named, and has been changed to reflect the issue. No need to make a whole new ticket.

**Comment by macumber** [comment]
Not to stir up the pot any more but I think if the issue really is with the measure we should put the issue in the measure repo's issues.  OpenStudio issues are backlogged enough without having issues for other measures in here.  Just my 2 cents

**Comment by rpg777** [comment]
Oh, you're absolutely right Dan-o. I didn't realize we were tracking measure issues directly in that repository. (duh)
