### ISSUE TITLE
AirLoopHVACUnitarySystem fan placement doesn't default

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2229]
Left the unitary fan placement to be blank. According to the [I/O](http://bigladdersoftware.com/epx/docs/8-5/input-output-reference/group-unitary-equipment.html#field-fan-placement):

>  If this field is left blank, the default is blow through.

I'm getting the following error when running the simulation

```
** Severe  ** AirLoopHVAC:UnitarySystem = WATER-COOLED RTU AIRLOOPHVAC UNITARYSYSTEM
**   ~~~   ** Illegal Fan Placement = 
```

Apparently openstudio has this optional initialized to an empty string

```
[1] (main)> unitary.fanPlacement.get
=> ""
```

Not sure if this is an openstudio or EnergyPlus error though

**Comment by Cole4242** [comment]
Hi, I was wondering if you were able to resolve this issue? Thanks!

**Comment by jmarrec** [comment]
Just hard set the fan placement for the time being.

**Comment by asparke2** [comment]
This is fixed in [the code](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitarySystem.cpp#L180-L188).  Confirmed in OS 2.1.0
