### ISSUE TITLE
Radiance simulation fails if spaces in file name (Bugzilla #965)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#223]
On 2012-10-23 16:11:40, @macumber wrote:

> There needs to be an ongoing test to catch this

**Comment by macumber** [comment]
@rpg777 can you test this?

**Comment by rpg777** [comment]
@macumber, this works -- has for a while AFAIK, and I just tested it on a simple model. I don't have a unit test for it, but the Radiance forward translator replaces spaces with underscores for exported space name references.

**Comment by macumber** [comment]
@rpg777 was it spaces in the Space name or spaces in the filename?  I thought the issue was for the latter?  Just wait until someone runs a model named प्रकाशीय.osm....

Please find your translated text below:

    daylighting (English)
    प्रकाशीय (Hindi)

**Comment by rpg777** [comment]
Right again, Dan-o. Well that issue is fixed too. Just tested a model with spaces in the file name ("spaces in name.osm") and the Radiance loop worked fine.
