### ISSUE TITLE
Site:GroundTemperature:Deep not forward translating

### ISSUE THREAD

**Issue by nmerket** [NREL/OpenStudio#2237]
In the newly added `SiteGroundTemperatureDeep` object, it's not getting forward translated into the idf. It appears that I forgot to put the appropriate include [here](https://github.com/NREL/OpenStudio/blob/792d26fcdd32e3b412079178a29983e640960eb0/openstudiocore/src/sdd/ForwardTranslator.cpp#L125).

Is there some sort of unit testing for the forward translator that I should be doing? @macumber

**Comment by macumber** [comment]
We typically test new objects with integration (e.g. run a simulation) tests in the openstudio-resources project.  That is likely to be changing soon though as we want to rearrange this for openstudio 2.0.  I would suggest doing some manual tests using pat for now

**Comment by macumber** [comment]
@nmerket can you fix this by 6/9 so it can make it into the 1.12 release?

**Comment by nmerket** [comment]
Yes
