### ISSUE TITLE
Unit conversion error - in^2 to cm^2

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2240]
OpenStudio's unit conversion doesn't handle "cm^2" correctly.  Users will see this as incorrect unit conversion in IG, particularly in the SpaceInfiltration:EffectiveLeakageArea object.  Because I can reproduce this easily using ruby, I don't think it is an issue with the OS App.

In reality, 1 in^2 = 6.45 cm^2

`puts OpenStudio.convert(1.0, 'in^2', 'cm^2').get => 0.645`

OpenStudio is off by a factor of 10.

**Workaround**: manually convert your area to cm2, switch the OS App to SI, and enter the value.  This will make sure that the IDF gets the right numbers.

Here is 1.0 in2 in the inspector:
![leakage_ip](https://cloud.githubusercontent.com/assets/2009290/15437938/ff6d24a0-1e86-11e6-9fa0-bf5fd7653318.PNG)

Switch to SI units:
![leakage_si](https://cloud.githubusercontent.com/assets/2009290/15437939/ff716fec-1e86-11e6-8dff-97b7500ac616.PNG)

The IDF contains the value you entered as cm2 in SI mode:
![leakage_idf](https://cloud.githubusercontent.com/assets/2009290/15437937/ff6c35a4-1e86-11e6-9978-48d9f0d8b5a6.PNG)

**Comment by DavidGoldwasser** [comment]
@asparke2  or @macumber we may want to let this user know about change coming in 1.12
https://unmethours.com/question/18349/openstudio-versionupdater-incorrect-effectiveleakageareas/

Sounds like may have also been changed between 1.4 and 1.11.

**Comment by adhilton25** [comment]
The issue isn't that the conversion from in^2 to cm^2 is wrong. The conversion was set for m(m^2) (the units previously displayed) to in^2. However, the translation to the idf however was not correct in prior versions when the displayed units were m(m^2). A value of 10 m(m^2) input should be translated to 100 cm^2 on the idf. Changing this displayed units to cm^2 addresses the idf translation bug but now exposes the bug converting from in^2 to cm^2. 

If this is addressed how with the current commit there will still be a version translation issue where values will be high by a factor of ten.
