### ISSUE TITLE
Bad data in energyPlusOutputRequests of reporting measure can break simulation

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2241]
Ideally a bad reporting measure can only mess up itself, but as I noticed with my own bad measure, it can caused failed simulation. This is in the OS app GUI.

@macumber is there an easy way to validate what is being added to the IDF prior to running so that we don't break the simulation and all other reporting measure that are in the workflow?

Here is an example of request that will break things.
`request_elec = OpenStudio::IdfObject.load("Output:Meter,,Electricity:Facility,Hourly;").get`

**Comment by DavidGoldwasser** [comment]
@macumber here code where the test in template reporting measure adds the requests to workspace. It is more forgiving and still produces a successful EnergyPlus run.
https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/utilities/bcl/templates/ReportingMeasure/tests/reporting_measure_test.rb#L64-L68

**Comment by macumber** [comment]
Just for posterity, "Output:Meter,,Electricity:Facility,Hourly;" is not a valid IDF object

**Comment by macumber** [comment]
@DavidGoldwasser what is the desired resolution here?

**Comment by DavidGoldwasser** [comment]
I think the desired behavior is not to allow invalid output variable requests into the IDF file, have that specific reporting measure error, but have the simulation and other reporting measures run.

I like this same behavior if a reporting measure fails in the run section. I guess this does get tricker though as we start needing the registerValues from reporting measures to run analysis reporting scripts. so I think I'm ok accepting the existing behavior. If you want to you can re-open if the other approach is feasible.

**Comment by macumber** [comment]
I still don't understand what the desired behavior was?  If someone puts a bogus request in that method you can either skip adding the object and fail later, add a bad object and fail later, or detect a bad object and fail immediately.  Are you suggesting that only the reporting measure with the bad request get's skipped?  Measures in the workflow are kind of all or nothing, if one fails they all fail.  I guess you are thinking of an exception for reporting measures?

**Comment by DavidGoldwasser** [comment]
> Are you suggesting that only the reporting measure with the bad request get's skipped

Yes, that is what I was suggesting, but I also see reasons not to do that. If we had time to spare it could be nice to skip failing reporting measures.
