### ISSUE TITLE
OpenStudio crashes when going to "Measures" tab on two user models

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2243]
Started with this unmet hours post. Brian and another user have emailed me OSM files. I thought deleting the directory matching the OSM would resolve, this but it didn't. The users are both on Windows with 1.11.0. I tested on mac with 1.11.3.

Here is a link to the user files to reproduce this.
https://github.com/NREL/OpenStudio-files/tree/master/Git%20Issue%20Files/issue%202243%20

**Comment by macumber** [comment]
@DavidGoldwasser I get this error when trying to pull:

error: unable to create file Git Issue Files/issue 2243 /ASU-EastCampusBldg.052316.v5.osm (No such file or directory)
error: unable to create file Git Issue Files/issue 2243 /CVBP - Proposed - FINAL.osm (No such file or directory)

It appears that the trailing white space in the 'issue 2243 ' portion of the path causes git to blow up.  Can you rename this directory?

**Comment by macumber** [comment]
Fixed in https://github.com/NREL/OpenStudio/commit/369da6fc3f104f6074f6724476789a970015dc7a

**Comment by DavidGoldwasser** [comment]
Sorry, I can fix that in the morning. In the mean time you can find the files in the OpenStudio email, or check out the first commit to the files repo from today and look under user files sub directory.

**Comment by DavidGoldwasser** [comment]
https://github.com/NREL/OpenStudio-files/commit/36d251a738df563e94eea249784626b47e8e8065
