### ISSUE TITLE
Handle "Baseline" checks on PAT XML export

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2249]
In the PAT export, we should only export a checks with the category "Baseline" if the design alternative is indeed the baseline.

**Comment by macumber** [comment]
Did you already fix this and just want me to pull it?

**Comment by asparke2** [comment]
Code review then pull please.  I tested the fix, but maybe I did some bad C++.

https://github.com/NREL/OpenStudio/pull/2250

**Comment by macumber** [comment]
Ok cool, what is up with the IDD changes?

**Comment by asparke2** [comment]
Evan copied those files to the wrong place last week and committed to develop, which broke the build.  I moved them back to the correct spot, which fixed the build and let me test my stuff.  I think he probably already made that change on develop.
