### ISSUE TITLE
Water Heater Setting Problem (from user post, see URL for post) (Bugzilla #971)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#225]
On 2012-10-26 15:43:53, @DavidGoldwasser wrote:

> My OpenStudio is upgrade to 0.9.1 and I can set schedule limit type.. But I found another error in OpenStudio. I set water usage and equipment for water heater. When ambient temperature indicator is set to thermal zone, error shows during compiling. 
> 
> *\* Severe *\* WaterHeater:Mixed = OS:WATERHEATER:MIXED: Invalid Ambient Temperature Indicator entered=THERMALZONE 
> *\* ~~~ *\* Valid entries are SCHEDULE, ZONE, and OUTDOORS. 
> 
> From OpenStudio, choices are three; Schedule, ThermalZone and Outdoors. The naming of ThermalZone is wrong and Zone is correct. Could you change ambient temperature indicator choices for water heater from ThermalZone to Zone?
> 1. OpenStudio can open a file with ThermalZone: When it is changed from ThermalZone to Zone, the error is occurred to open OSM file.
> 2. EnergyPlus only accept Zone not ThermalZone.

On 2013-01-11 11:15:32, @DavidGoldwasser wrote:

> <batch comment: added this to Pivotal Epic,
> https://www.pivotaltracker.com/epic/show/458473>

On 2013-01-11 11:28:36, @DavidGoldwasser wrote:

> Looks like may just be one line fix.

Keywords: ForumPost

**Comment by jmarrec** [comment]
Can be closed, see https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateWaterHeaterMixed.cpp#L246

**Comment by evanweaver** [comment]
Fixed.
