### ISSUE TITLE
Upgrade from 1.11.4 to 1.11.5 leads to empty OutdoorAir:NodeList in IDF file

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2273]
See the model here: https://unmethours.com/question/18238/simple-water-system-problem/

It runs fine on 1.11.4, when upgraded to 1.11.5 I end up with an IDF that crashes because of

```
OutdoorAir:NodeList,
  ;                                       !- Node or NodeList Name 1
```

**Comment by asparke2** [comment]
Not going to fix this at this point.  Can reopen if it happens in future version updates.
