### ISSUE TITLE
Water Heat Trank associated with Heat Pump Water Heater can't be dragged from My Model to Plant Loop

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2274]
Also looks like missing icon. May be related to issue #1964

**Comment by fkung** [comment]
While people are working on this object, you may also want to fix the naming inconsistency. In the "HVAC Systems" tab, the object is listed in the Library under "Water Heater - Heat Pump," but in the "Thermal Zones" tab, the object is listed in the Library under "Heat Pump Water Heater." This is secondary to the drag-and-drop problem, but using a consistent name will help people find it easier.

**Comment by jmarrec** [comment]
I've tried to find where each "My Model" collapsible item is actually getting populated but couldn't.

The WaterHeater:Mixed should have been added to the model when you drag it into a thermal zone.

And the "WaterHeater;Mixed" type is properly defined in the controller for Main right Column: 

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/openstudio_lib/MainRightColumnController.cpp#L1007

There's probably a check somewhere happening for WaterToWater Components or something that looks whether it's already connected to one loop, but I have no idea where

**Comment by jmarrec** [comment]
I fixed the naming inconsistency in #2815, but this doesn't solve the main issue.

Thermal Zone - Library:

![2274_naming_thermalzone_library](https://user-images.githubusercontent.com/5479063/31220399-9a4be126-a9c0-11e7-93ba-1bf940e76241.png)

Thermal Zone - My Model:

![2274_naming_thermalzone_mymodel](https://user-images.githubusercontent.com/5479063/31220413-a7e7b9a4-a9c0-11e7-8a8c-69b01aee632b.png)


HVAC System - My Model:

![2274_naming_hvacsystem_library](https://user-images.githubusercontent.com/5479063/31220417-ac6f7f2a-a9c0-11e7-99a3-3315202ba79d.png)

**Comment by jmarrec** [comment]
You still can't see the associated WaterHeater:Mixed in the HVAC Systems - My Model, and you can't drag a WaterHeaterHeatPump from the Library to a plant Loop, so having WaterHeaterHeatPump on HVAC Systems Subtab is useless right now, same as having WaterHeaterHeatPump on the Thermal Zone - My Model.

Perhaps it would make sense to add a `WaterHeaterHeatPump::addToNode()` method, that would attach the tank to a plant loop. I'm not sure here.
