### ISSUE TITLE
1.11.5 - Surface class shadingSurfaceGroup method doesn't work

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2279]
The following code and output indicates that there might be an issue with the `Surface` class `shadingSurfaceGroups` method. Both the `Space` class and `Surface` class have a `shadingSurfaceGroups` method, but return different array sizes.

```
model.spaces.each do |space|
  
  puts "#{space.name} = #{space.shadingSurfaceGroups.size}"

  space.surfaces.each do |surface|
    puts "=> #{surface.name} = #{surface.shadingSurfaceGroups.size}"
  end

end
```

```
Space 101 = 2
=> Surface 1 = 0
=> Surface 2 = 0
=> Surface 3 = 0
=> Surface 4 = 0
=> Surface 5 = 0
=> Surface 6 = 0
Space 102 = 2
=> Surface 7 = 0
=> Surface 8 = 0
=> Surface 9 = 0
=> Surface 10 = 0
=> Surface 11 = 0
=> Surface 12 = 0
```

**Comment by macumber** [comment]
`[Space::shadingSurfaceGroups](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/Space.cpp#L728)` will return all shading groups in the space.  

Shading groups in a Space can be [associated with a particular SubSurface](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/ShadingSurfaceGroup.hpp#L95) in the Space.  If a shading surface group is also associated with a SubSurface then it will be returned by `[Surface::shadingSurfaceGroups](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/Surface.cpp#L1764)`.
