### ISSUE TITLE
If you attempt to import a 7.1 IDF file into the OpenStudio (which is expecting 7.2) it can crash (Bugzilla #985)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#228]
On 2012-11-06 13:29:33, @DavidGoldwasser wrote:

> Kyle, I ran across this testing bug 866. I didn't upgrade to EnergyPlus 7.2 and tried to import the 7.1 example file into the current trunk.
> 
> It crashes SketchUp and locks up the OpenStudio application. Seems we should look at the version object in the IDF file and refuse to try to import it if it isn't the right version. Or at least should fail more gracefully.
> 
> Not sure if this should be assigned to you, but was my best guess.

On 2012-11-06 13:31:27, @kbenne wrote:

> I think your proposed fix is a good one.

On 2012-11-06 14:20:18, @DavidGoldwasser wrote:

> This may be invalid. I'll retest after bug 866 is closed. I did try to open a few other 7.1 IDF files and they failed draft strictness but didn't crash.

Keywords: CrashNoDataLoss, ForwardTranslation

**Comment by jmarrec** [comment]
Tested with 2.7.1 in both Sketchup and OS App by loading a IDF at version 7.0. It does try to load the file, though it doesn't crash.

![image](https://user-images.githubusercontent.com/5479063/53492257-b7869000-3a98-11e9-852f-cfd81ec6430e.png)
