### ISSUE TITLE
Can't add weather file from "resources" folder with Apply Measures Now

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2289]
I ran across this making the BESTEST measures. I have a file named "DRYCOLDTMY.epw" in the measure's resources folder. The measure gets the absolute path for that and sets the weather path to that. Very much like what is done for create prototype building, except that in that case, the epw file lives in the gem vs. the "resources" folder of the measure.

Below is a picture of the temporary folder that "Apply Measures Now" is run in. Notice that a .rb file is there along with the contents of the resources folder. 
![screenshot 2016-06-30 14 45 30](https://cloud.githubusercontent.com/assets/4857055/16504083/5da7063c-3ed3-11e6-9027-3a2583647006.png)

Here is a picture of the measure info dialog showing the path that was set for the weather file.
![screenshot 2016-06-30 14 48 19](https://cloud.githubusercontent.com/assets/4857055/16504124/94454cb2-3ed3-11e6-857f-e07f2bf71556.png)

By the time the dialog above shows up, much of the content in the temp dialog has been thrown away. Logs and the starting/final osm are left behind, so that when I hit "accept" the file can be loaded. These files remain until the next time I run "Apply Measures Now"
![screenshot 2016-06-30 14 45 39](https://cloud.githubusercontent.com/assets/4857055/16504182/e13458a6-3ed3-11e6-9e03-5304de6ac961.png)

This results in an error that strips the weather file setting out after I accept.
![screenshot 2016-06-30 15 05 57](https://cloud.githubusercontent.com/assets/4857055/16504241/3212915c-3ed4-11e6-9b97-fed06922e0e1.png)

@evanweaver @macumber is there any reason we have to delete any of the measure files? If we left them there, with the other files until "Apply Measures Now" is run again, then it could avoid this error. Is that complicated to implement or would it create any other issues?

Measure runs fine in the workflow, unit test, and on OS server. I don't think PAT 2.0 would hit this unless it works in temp directory with similar behavior (measure removed before E+ run or before epw copied to "files" directory.)

**Comment by DavidGoldwasser** [comment]
I don't think this has to be fixed for 1.13.0, but I just wanted to document it well. Here are some possible work-arounds (this measure will have many weather files when done).

- Don't use apply measures now
- Add EPW files to openstudio-standards gem (doesn't seem like good idea, unless it is for prototype/archetype projects)
- Add user argument for "weather path" that points to local folder so avoid referring to temp location. (also not great idea).

**Comment by jmarrec** [comment]
Is this still a thing now that 2.X is out?

Also seems somewhat related to https://github.com/NREL/OpenStudio/issues/3114
