### ISSUE TITLE
OSIntegerEdit boxes seems to allow user to input non-integer values (Bugzilla #987)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#229]
On 2012-11-09 15:37:26, @macumber wrote:

> Created an attachment (id=239)
> Screenshot
> 
> I changed space load instance multiplier from integer to double but this is still visible in other inspectors (e.g. ConstructionWithInternalSource).  The non-integer value does not stick in the object and gets refreshed eventually but seems to stick for a while.

Original attachments:
* OSIntegerEdit.jpg (ID 239)

**Comment by evanweaver** [comment]
@macumber this appears to have been fixed.

**Comment by macumber** [comment]
Space load instance multipliers are fractional, https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/SpaceLoadInstance.hpp#L53, so the original bug report was invalid (at least in context of space load multiplier)

However, the multiplier has a minimum of 0.  I noticed that I can enter in a negative number in the multiplier field in grid view.  Number appears to stick but gets cleared when I switch tabs and come back,

**Comment by macumber** [comment]
@evanweaver not sure if you want to open a new issue for the negative multipliers in gridview. If you open a new issue I think you can close this one.

**Comment by evanweaver** [comment]
@macumber I've been considering a more holistic fix, and also thinking about how this bug fits with https://github.com/NREL/OpenStudio/issues/656.  I think that extending the OSConcepts to expose base Qt widget validator functionality of min, max, and range would be good starting place for gridview instances.

**Comment by macumber** [comment]
Ok, let's just keep #656 then
