### ISSUE TITLE
Subsurfaces Tab in Spaces has Bogus Search Field

### ISSUE THREAD

**Issue by rpg777** [NREL/OpenStudio#2294]
There is a search field, labeled "Space Name", among the filters on the subsurfaces page of the Spaces Tab in the app, e.g.:

![screen shot 2016-07-07 at 10 38 15 am](https://cloud.githubusercontent.com/assets/3161332/16661311/95f32988-442f-11e6-8561-e987c9d7226b.png)

...there should be a filter pulldown for "Subsurface Type".

**Comment by evanweaver** [comment]
See also the spaces shading sub-tab.
