### ISSUE TITLE
gbxml import makes bad OS:Schedule:Week

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#2298]
Importing a gbxml file generated by Autodesk Revit Energy Analysis creates OS:Schedule:Week objects without `CustomDay1 Schedule:Day Name` fields. When translated to idf and the (OS v1.12.0) model is run, these objects throw a Severe error, since the fields are required per EnergyPlus idd:

    ** Severe  ** IP: IDF line~18315 Error detected in Object=SCHEDULE:WEEK:DAILY, name=WS-57- EQUIP
    **   ~~~   ** Field [CustomDay2 Schedule:Day Name] is required but was blank

gbxml:
```xml
  <WeekSchedule id="ws-57-Equip" type="Fraction">
    <Name>7DayWeek - Office/Lab</Name>
    <Day dayType="Weekday" dayScheduleIdRef="ds-202-Equip" />
    <Day dayType="Sat" dayScheduleIdRef="ds-200-Equip" />
    <Day dayType="Sun" dayScheduleIdRef="ds-201-Equip" />
    <Day dayType="HeatingDesignDay" dayScheduleIdRef="ds-201-Equip" />
    <Day dayType="CoolingDesignDay" dayScheduleIdRef="ds-202-Equip" />
    <Day dayType="Holiday" dayScheduleIdRef="ds-201-Equip" />
  </WeekSchedule>
```

OS:

    OS:Schedule:Week,
    {87fbf0d9-068c-4739-a0a1-f48aefe5ec40}, !- Handle
    ws-57-Equip,                            !- Name
    ,                                       !- Schedule Rendering Name
    {e5242dfb-9950-42cd-8d23-bb2c4e3a675f}, !- Sunday Schedule:Day Name
    {039f8280-6f83-4b63-96a9-1116650f2fe5}, !- Monday Schedule:Day Name
    {039f8280-6f83-4b63-96a9-1116650f2fe5}, !- Tuesday Schedule:Day Name
    {039f8280-6f83-4b63-96a9-1116650f2fe5}, !- Wednesday Schedule:Day Name
    {039f8280-6f83-4b63-96a9-1116650f2fe5}, !- Thursday Schedule:Day Name
    {039f8280-6f83-4b63-96a9-1116650f2fe5}, !- Friday Schedule:Day Name
    {0c6ec63b-0519-45cf-bc0c-656fcb5b7ba3}, !- Saturday Schedule:Day Name
    {159d3cff-9885-4edb-8b8e-3be98e047d1c}, !- Holiday Schedule:Day Name
    {043930dc-e3ee-42d0-9218-fd96bc7f8e33}, !- SummerDesignDay Schedule:Day Name
    {a19aa9f1-fd13-4218-bf38-fc78570c32b8}, !- WinterDesignDay Schedule:Day Name
    ,                                       !- CustomDay1 Schedule:Day Name
    ;                                       !- CustomDay2 Schedule:Day Name

IDF:

    Schedule:Week:Daily,
    ws-57-Equip,                            !- Name
    ds-201-Equip,                           !- Sunday Schedule:Day Name
    ds-202-Equip,                           !- Monday Schedule:Day Name
    ds-202-Equip,                           !- Tuesday Schedule:Day Name
    ds-202-Equip,                           !- Wednesday Schedule:Day Name
    ds-202-Equip,                           !- Thursday Schedule:Day Name
    ds-202-Equip,                           !- Friday Schedule:Day Name
    ds-200-Equip,                           !- Saturday Schedule:Day Name
    {67a12c2d-c2c9-44c8-a121-306a72998a58}, !- Holiday Schedule:Day Name
    {f39004cd-7048-4ffe-8e35-cc085a70929e}, !- SummerDesignDay Schedule:Day Name
    {5c800f1f-ddec-46a3-b166-62b1005ba2ec}, !- WinterDesignDay Schedule:Day Name
    ,                                       !- CustomDay1 Schedule:Day Name
    ;                                       !- CustomDay2 Schedule:Day Name

**Comment by macumber** [comment]
File added to files repo

**Comment by macumber** [comment]
@eringold was this fix acceptable to you?

**Comment by eringold** [comment]
Yep, no longer getting the errors. Thanks, @macumber!
