### ISSUE TITLE
Issue with Zone Sensible Cooling and Heating when heating or cooling only system

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2299]
Two EnergyPlus tables are combined into one Table in the OpenStudio standard report. The code for this expected the zone names to match across both tables, but when there is no cooling or heating "None" shows up and the zones that don't have cooling do not show up. As a result the table shown below looks empty. This should be easy to fix. Also fix table name which doesn't make sense.

![screenshot 2016-07-13 11 27 33](https://cloud.githubusercontent.com/assets/4857055/16813164/a077a1dc-48ed-11e6-9739-2ea8e814f5d9.png)

**Comment by macumber** [comment]
@DavidGoldwasser does this require any change OpenStudio source code or is this simply in the measure?

**Comment by DavidGoldwasser** [comment]
@macumber Only change to source code is committing updated copy of measure once I fix in OpenStudio-measures repo.

I'll keep a list of any other changes to report and try to copy to source code in single commit, also single push to BCL.
