### ISSUE TITLE
gbXML import/export should properly use names and ids

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2303]
Right now we are conflating names with ids

**Comment by pflaumingo** [comment]
Are you going to be making substantial gbXML import changes?

**Comment by DavidGoldwasser** [comment]
@macumber Construction and Material objects from ZNETH  don't get names from gbXML. Have UUID instead.

**Comment by DavidGoldwasser** [comment]
Hmm, odd. Looking at Eric's file from schedule issue with same build. His constructions and materials have names. Maybe something invalid in the ZNETH file?
