### ISSUE TITLE
OS App crashes when switching to Measures tab with specific model

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2308]
This is a 1.9.0 model from an EDAPT user.  It has a Measure attached to it.  Starting in 1.12.0, the OS App crashes when you switch to the Measures tab after opening the model and updating it.

The link to the model is [here](https://github.com/NREL/OpenStudio-files/blob/master/Git%20Issue%20Files/Issue2308.zip).

**Comment by asparke2** [comment]
Update:  even if you delete the folder associated with the project this happens so I don't know of a workaround besides using 1.11.0.  I also noticed that this file takes a long time to save, could it be size related?

**Comment by jmarrec** [comment]
I'm having the same issue on a model upgraded from 1.11.3 to 1.12.1.

I did a git commit, upgraded the model, and foudn that my OS:Coil:Heating:DX:SingleSpeeds were ill-constructed: the `Air Inlet Node Name` is blank.

In 1.11.3:

    OS:Coil:Heating:DX:SingleSpeed,
      {5beebe06-2840-4d7b-a337-2998948092dd}, !- Handle
      Top-Right_Elevator PSZ-HP Coil Heating DX SingleSpeed, !- Name
      {93eb51cb-9c40-4219-b35c-0ddca6eebda9}, !- Availability Schedule Name
      Autosize,                               !- Rated Total Heating Capacity {W}
      3.3,                                    !- Rated COP {W/W}
      Autosize,                               !- Rated Air Flow Rate {m3/s}
      {bedd6a5a-c802-4fa5-a3d5-0cfbfe68d8e5}, !- Air Inlet Node Name
      {fe0d79cc-d9ff-41e9-9ab2-640cf9d6c01e}, !- Air Outlet Node Name

In 1.12.1:

    OS:Coil:Heating:DX:SingleSpeed,
      {5beebe06-2840-4d7b-a337-2998948092dd}, !- Handle
      Top-Right_Elevator PSZ-HP Coil Heating DX SingleSpeed, !- Name
      {93eb51cb-9c40-4219-b35c-0ddca6eebda9}, !- Availability Schedule Name
      Autosize,                               !- Rated Total Heating Capacity {W}
      3.3,                                    !- Rated COP {W/W}
      Autosize,                               !- Rated Air Flow Rate {m3/s}
      773.3,                                  !- Rated Supply Fan Power Per Volume Flow Rate {W/(m3/s)}
      ,                                       !- Air Inlet Node Name
      {fe0d79cc-d9ff-41e9-9ab2-640cf9d6c01e}, !- Air Outlet Node Name


Manually re-setting the Air Inlet Node handles fixed the problem

**Comment by macumber** [comment]
@kbenne you might know about this?

**Comment by macumber** [comment]
Added file Issue2308b.osm from @jmarrec to files repo

**Comment by kbenne** [comment]
I'm sure I'm culpable.

**Comment by MatthewSteen** [comment]
We're also encountering this issue. Our model also has several CoilHeatingDXSingleSpeeds. However, manually setting the Air Inlet Node Name to the OS Connection handle did not lead to a fix. The model still crashes when navigating to the Measures tab and will also crash if attempting to sim.

**Comment by geraldopithon** [comment]
I'm having the same issue too. 

In my case, it is a Baseline Model to ASHRAE 90.1 with around 20 systems.

@jmarrec , is your suggestion to copy and paste the missing code from the OS 1.11 file to OS 1.12 file?

Do you think if I edit my source code from OS 1.11, only replacing the OS version in the line 4, can I have some problem or it is good?

**Comment by jmarrec** [comment]
@geraldopithon: in this case that's exactly what I did yes (in practice I used a diff tool)

Regarding your last comment, why don't you just try it out and let us know?

**Comment by geraldopithon** [comment]
@jmarrec ok, thanks!

I tried to replace the OS version manually, but it haven't work. The message bellow was shown:

_Model with Version 1.12.0 IDD is not valid to draft strictness level.

The collection is INVALID at strictness level 'Draft', because of the errors:
Field      level data error of type DataType          .
Error is in an object of type 'OS:Coil:Heating:DX:SingleSpeed', named '1A_AREA_EXPEDIENTE_1_Coil Heating DX Single Speed 19', in field 6.
Additional information about the error type: field-level data is of an incorrect type._

I will wait another update version to use OS after 1.12.

**Comment by DavidGoldwasser** [comment]
Added file emailed from @MatthewSteen to private repo
https://github.com/NREL/OpenStudio-files/tree/master/Git%20Issue%20Files/Issue%202308

**Comment by asparke2** [comment]
@kbenne FYI Taylor at G14 just hit this too

**Comment by chrisbalbach** [comment]
We @ PSD have also hit this issue... Is there a recommended work-around/fix aside from waiting for v1.13.0? Does anything in 1.12.6 smash this bug?

**Comment by geraldopithon** [comment]
@chrisbalbach , 
I installed the OS 1.12.6 and the problem still remains. My model crashed again.
I suggest you dont't update after version OS 1.11.

**Comment by macumber** [comment]
Moving to a 1.13 milestone, @kbenne I can take a first look at this, I'm 99% sure it'll be a ForwardTranslator thing

**Comment by macumber** [comment]
Here is the call stack for the 2308 file:

```
openstudio_energyplus.dll!boost::optional<openstudio::model::ModelObject>::operator->() Line 641	C++
openstudio_energyplus.dll!openstudio::energyplus::ForwardTranslator::populateBranch(openstudio::IdfObject & branchIdfObject, std::vector<openstudio::model::ModelObject,std::allocator<openstudio::model::ModelObject> > & modelObjects, openstudio::model::Loop & loop) Line 150	C++
openstudio_energyplus.dll!openstudio::energyplus::ForwardTranslator::translateAirLoopHVAC(openstudio::model::AirLoopHVAC & airLoopHVAC) Line 468	C++
openstudio_energyplus.dll!openstudio::energyplus::ForwardTranslator::translateAndMapModelObject(openstudio::model::ModelObject & modelObject) Line 522	C++
openstudio_energyplus.dll!openstudio::energyplus::ForwardTranslator::translateModelPrivate(openstudio:model::Model & model, bool fullModelTranslation) Line 416	C++
openstudio_energyplus.dll!openstudio::energyplus::ForwardTranslator::translateModel(const openstudio::model::Model & model, openstudio::ProgressBar * progressBar) Line 109	C++
```

Relevant code:
```
if( auto straightComponent = modelObject.optionalCast<StraightComponent>() )
{
  inletNode = straightComponent->inletModelObject()->optionalCast<Node>();
  outletNode = straightComponent->outletModelObject()->optionalCast<Node>();
```

**Comment by kbenne** [comment]
thanks @macumber. standby. should be easy fix.

**Comment by macumber** [comment]
Think I have a solution

**Comment by kbenne** [comment]
great. i'll just relax then :)
