### ISSUE TITLE
Cannot create custom window construction

### ISSUE THREAD

**Issue by Dinosaver** [NREL/OpenStudio#2312]
OS 1.11 Cannot create a window construction which consists just from glass layers and air layers - Open Studio gets frozen.

**Comment by macumber** [comment]
Thanks for the report, can you give more details here?  What material types are you using?  What order are you adding them in?  I was not able to reproduce, if you can describe exactly what you did that would help

**Comment by macumber** [comment]
I may have been able to reproduce this by going:

Window Material Gas
Window Material Glazing
Window Material Gas

I think OpenStudio is doing some validation that the outside layers can't be gas.  The app didn't crash but it did slow down a lot.  Does that sound like what you are seeing?  It is problematic because you have to add the gas layer to the end before you can add a glass layer

**Comment by Dinosaver** [comment]
Hello, Den, thank you for the quick answer.

I did nothing special, just create a new window construction and added
Window material glazing - simple 3 mm glass, then window material gas - air
with 14 mm thickness, then tried to add a new glass layer, it took several
minutes, then new gas layer (I wanted to model quadruple glazing) and the
OS got frozen. I shut it down and tried to create a window again, I didn't
wait more than 5 min, but before I've experienced smthg similar with a
model with large numbers of spaces - OS gets tremendously slow... But
simple window construction...
Would be interesting to try it with walls or roofs and create 4-5 layers
constructions.

С уважением

Nikolay Gerasimov
PhD, RICS Certified BIM-Manager
+7-921-433-49-11
russianbem.blogspot.com


2016-07-28 18:32 GMT+02:00 Dan Macumber <notifications@github.com>:

**Comment by macumber** [comment]
Yeah, this sounds like over-zealous validation in the model

**Comment by Dinosaver** [comment]
OS cannot model 5 layers construction? Can it use Window files? Is it only
for windows?

28 Июл 2016 г. 14:19 пользователь "Dan Macumber" <notifications@github.com>
написал:

**Comment by macumber** [comment]
OS can model those constructions, I think this is only an issue with the GUI being slow

**Comment by Dinosaver** [comment]
Any chance to improve it? GUI is important :)

28 Июл 2016 г. 14:33 пользователь "Dan Macumber" <notifications@github.com>
написал:

**Comment by DavidGoldwasser** [comment]
Looks good with latest internal installer
![screen shot 2016-12-06 at 12 57 57 pm](https://cloud.githubusercontent.com/assets/4857055/20941481/b7f7751a-bbb3-11e6-8416-b4694cb2306d.png)
