### ISSUE TITLE
OS 1.12.1 to 1.12.2 Conversion Error

### ISSUE THREAD

**Issue by dstuder** [NREL/OpenStudio#2314]
I updated a model I had in 1.12.1 (Standalone Retail prototype building) to 1.12.2 and while the .osm files are identical, when I go to run the 1.12.2 model, the resulting idf is missing a WaterUse:Equipment object, which causes the simulation to crash.

**Comment by kbenne** [comment]
I think this is it

https://github.com/NREL/OpenStudio/commit/462ae9e7461f3b7d1f94fb02ab3a96a632d9f5fc#commitcomment-18403350

**Comment by dstuder** [comment]
Indeed, thanks. Assigning a space to the water use object fixes the issue. I’ll track this; Andrew’s suggestion to make an exception would be very useful.

Danny

**Comment by macumber** [comment]
Yup, I'll fix it tomorrow 

@asparke2 thanks for finding this
