### ISSUE TITLE
incorrct areas in EnergyPlus Results

### ISSUE THREAD

**Issue by snlavu** [NREL/OpenStudio#2317]
In version 1.12, the floor area in input verification summary and Total building area is incorrect. Volume in Zone summary does correspond to the multiple spaces to 1 zone volume. 
PLease confirm of this is only output error and has assigned loads, hvac according tot he total floor area.

**Comment by macumber** [comment]
We need more information here.  Do you have a model you can share?  What is the problem with the area?  Are there specific spaces that are being counted when they should not be?

**Comment by snlavu** [comment]
Apt12A consists of 2 spaces combined into 1 zon- named APT 12A(1BR)_FL12, similarly Apt4A contains 8 spaces combined into 1 zone.
Both of these return with same area in the Html attached!!! The volume does vary. as a result the EUI in the site and source energy is skewed! 

LEt me know if you need additional files.

**Comment by macumber** [comment]
I am working on something for this now, do you have multiple levels in your building?  Some stories are on second level and others are on the first?

**Comment by snlavu** [comment]
yes, I have each space detailed for the 12 floors in the spaces description. No multipliers were applied.  I have combined multiple spaces to single zone for floor 4-11 into Floor 4 zones and 12&13 into Floor 12 zone.

**Comment by macumber** [comment]
For now the recommendation would be to assign a separate thermal zone to each story of your building

**Comment by snlavu** [comment]
Are any of the space loads being incorrectly assigned with this approach? If its only output report, then it does not bother me much. If the loads are being incorrectly calculated , then I could perhaps input total wattage into zone. What I would avoid is adding 100 zones and painstakingly apply a PTAC to each of them with the slow tick selection in the interface!

**Comment by macumber** [comment]
@snlavu we have some builds that include a fix for this for testing, if you are willing to try these it would be very helpful:

https://openstudio-builds.s3.amazonaws.com/1.12.2/OpenStudio-1.12.2.e649e83f48-Darwin.dmg

https://openstudio-builds.s3.amazonaws.com/1.12.2/OpenStudio-1.12.2.e649e83f48-Win64.exe

**Comment by macumber** [comment]
Note that these are test builds so please make backups of your files before trying these

**Comment by macumber** [comment]
Also, measures are a perfect option for avoiding lots of clicks in the GUI :-)

**Comment by snlavu** [comment]
Is the original error - were the space loads being incorrectly assigned? Is the energy consumption going to be affected with the new build?

**Comment by macumber** [comment]
Yes and yes

**Comment by asparke2** [comment]
@macumber Can you close this if the changes got merged?

**Comment by macumber** [comment]
I'm not sure if this got fixed, needs testing. 

@david_goldwasser will be interested

**Comment by evanweaver** [comment]
@DavidGoldwasser please test and confirm

**Comment by DavidGoldwasser** [comment]
Yes, I believe this is fixed, there also is an explicit check in reporting measure with small tolerance that will issue warning that will check if EnergyPlus reported area isn't the same as OpenStudio reported area.

Details of how it was checked are in issue #561
