### ISSUE TITLE
BCL measure Change VAV box Minimum Flow to 0.4cfm/sf has wrong display name

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2318]
FYI @asparke2. [BCL LINK](https://bcl.nrel.gov/node/82296)

```
def name
    return "Change Supply Fan Pressure Rise"
end
```

There's also an extra `sf` folder in the directory.

**Comment by MatthewSteen** [comment]
Still an issue.

**Comment by jmarrec** [comment]
Moved to https://github.com/NREL/OpenStudio-measures/issues/95
