### ISSUE TITLE
Thermal Zone Tab - If  thermal zone is on loop and you try and add it again the terminal is removed (Bugzilla #990)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#232]
On 2012-11-16 12:35:20, @DavidGoldwasser wrote:

> Kind of an edge case, but still a bug. If I drag a thermal zone onto a loop. It only does this if it is the only zone on the loop.

**Comment by jmarrec** [comment]
No longer true, I get an "Component not allowed at this location" if I try to add a thermal zone twice.
