### ISSUE TITLE
PAT select measures 

### ISSUE THREAD

**Issue by snlavu** [NREL/OpenStudio#2320]
Unable to pick multiple measures to 'Create One with Selected Measures'. The option does not highlight when multiple measures are highlighted.
![issues](https://cloud.githubusercontent.com/assets/12649036/17260546/1099af74-559f-11e6-8d22-a4536e25b6d4.JPG)

**Comment by macumber** [comment]
The options under "Baseline+Wall" are mutually exclusive, each design alternative can have at zero or one of those options.  Create one for each selected measure would make three design alternatives, one for each option.  Create one with selected measures would try to make one design alternatives that included all three options (which is not allowed).  If you wanted to try combinations, you could drag the measure in to a new measure group on the first tab.  You are allowed to combine options between measure groups. Does that make sense?
