### ISSUE TITLE
Changing StartDayOfWeek Causes Schedules to Be Blank inIDF

### ISSUE THREAD

**Issue by chriswmackey** [NREL/OpenStudio#2322]
@macumber ,

I am opening up this issue as per our previous discussion [here](https://github.com/NREL/OpenStudio/issues/2304#issuecomment-233494688).

I know that this image is in the previous discussion but I'm adding it again here because it succinctly sums up the bug:
![osyeardescriptionbug](https://cloud.githubusercontent.com/assets/5567574/17308397/bf2065d2-5807-11e6-8d66-c261f51a8216.png)
Essentially, I change the startDayOfWeek using the setString() method and the schedules are wiped out in the IDF.

Here is an example .osm file that will cause the IDF to be generated with wiped-out schedules:
https://www.dropbox.com/s/tmzxj4fwgyvhmbp/OsYearDescriptionBug.osm?dl=0

Let me know if there's any other info that I could provide,
-Chris

**Comment by macumber** [comment]
@chriswmackey are you able to confirm if this is still valid?  Specifically, can you translate your OSM to IDF before and after calling setString on the YearDescription object?

**Comment by chriswmackey** [comment]
@macumber ,
I just tested it with version 1.13.0 and the issue is still there:

![ydsbroken](https://cloud.githubusercontent.com/assets/5567574/20834550/085946bc-b864-11e6-95e7-c8f33ac8ce13.JPG)

Let me know if you would like me to test it out with one of the pre-releases.
-Chris

**Comment by macumber** [comment]
I guess what I need is a unit test, can you write a small bit of code where you make the schedule and write it to IDF ok, then you do something, after that translation to IDF is messed up?

**Comment by chriswmackey** [comment]
@macumber ,
I understand that a unit test is needed but this is definitely going to be a longer one.  I'll try to put one together tomorrow once I get a bit more time.
-Chris

**Comment by chriswmackey** [comment]
@macumber ,
I am sorry for being so incredibly late on this one.  Let me check to be sure that I can recreate the error in OpenStudio 2.0 and, if so, I'll post a unit test.

**Comment by chriswmackey** [comment]
@macumber ,

This issue still seems to be present in OpenStudio 2.0.0, although I could not test the missing schedules because of difficulties of getting the EnergyPlusForwardTranslator to work in 2.0.0.  Accordingly, I have included a unit test below that creates an IDF that is missing the schedule values like so:
![missingschedule](https://cloud.githubusercontent.com/assets/5567574/21744724/33a1c942-d4e9-11e6-8da4-30805da00f03.JPG)

You will see that, if you comment out the setting of the year description, the start dates, end dates, and weekly schedules make it into the IDF correctly:
![schedulespresent](https://cloud.githubusercontent.com/assets/5567574/21744725/39875930-d4e9-11e6-9e46-e607a152376a.JPG)

Here is the unit test code:
```
# Import the classes
import OpenStudio as ops
import os

# Create the model
model = ops.Model()
startDOW = "Tuesday"
yearDesc = ops.OpenStudioModelSimulation.getYearDescription(model)
yds = model.getObjectsByType(ops.IddObjectType("OS:YearDescription"))
yds[0].setString(2, startDOW)

# Add a schedule.
weeklySchd = ops.ScheduleWeek(model)
weeklySchd.setName("TestWeek")
startDate = ops.Date(ops.MonthOfYear(1), 1)
endDate = ops.Date(ops.MonthOfYear(12), 31)
OSSchedule = ops.ScheduleYear(model)
OSSchedule.setName("TestSched")
OSSchedule.addScheduleWeek(endDate, weeklySchd)

# Write te IDF
projectFolder = "C:/ladybug/"
idfFilePath = ops.Path(os.path.join(projectFolder, "ModelToIdf", "in.idf"))
forwardTranslator = ops.EnergyPlusForwardTranslator()
workspace = forwardTranslator.translateModel(model)
workspace.save(idfFilePath, True)

```
Hope this helps and sorry, again for the delay.
-Chris

**Comment by macumber** [comment]
Thanks @chriswmackey I can see what was going on now, I am going to close this as "user error" but it really isn't your fault.

**Comment by chriswmackey** [comment]
@macumber ,

Thanks for looking into this.  Unfortunately, I don't seem to be able to use the `makeDate()` method for the same reason that I can't use the `setDayofWeekforStartDay()` method.  The following code on my end:

```
import OpenStudio
model = OpenStudio.Model()
yearDesc = OpenStudio.OpenStudioModelSimulation.getYearDescription(model)
yearDesc.setDayofWeekforStartDay("Monday")
```

returns the following error:
`Runtime error (MissingMemberException): 'SWIGTYPE_p_openstudio__model__YearDescription' object has no attribute 'setDayofWeekforStartDay'`

This goes all of the way back to why I originally had to use the `setString()` method instead of the methods on the yearDescription object.  So it seems that I won't be able to replace the code in Honeybee until I can access the full yearDescription object.  Do you know if this will be addressed in version 2.0?  Otherwise, I can wait until all of the date stuff is rewritten, as you say.

Thank you again!

**Comment by macumber** [comment]
Ah I forgot about that, let me see if I can bring that object back since it is required.  Alternatively I could just tack that method on Model as well, model.makeDate()

**Comment by chriswmackey** [comment]
That would be wonderful, @macumber .  Thank you, as always, for all of the great support!

**Comment by macumber** [comment]
I'm going the easy route, just going to add those methods to Model.  This will be in the 2.0.5 package that is coming out Friday or early next week, it will be our 2.1 preview so would be great if you could do some testing with it.

**Comment by chriswmackey** [comment]
Wonderful!  I would be happy to run some tests once the 2.0.5 package is out.  Thank you, again, for working this in.  It will be nice to finally be able to write this into the OSM from Honeybee.
