### ISSUE TITLE
PAT cloud setting

### ISSUE THREAD

**Issue by snlavu** [NREL/OpenStudio#2324]
Parametric Analysis Tool in 1.11 and 1.12  versions does not allow setting up cloud setting in the interface.

**Comment by MatthewSteen** [comment]
See this...
https://unmethours.com/question/18376/parametricanalysistool-cloud-menu-options-are-greyed-grayed-out/

**Comment by snlavu** [comment]
Export analysis spreadsheet fails! Followed methodology as described in http://nrel.github.io/OpenStudio-user-documentation/tutorials/large_scale_analysis/

**Comment by macumber** [comment]
This is all going to be replaced by PAT 2.0, I don't we are going to support this export issue

**Comment by snlavu** [comment]
When is the new release expected? We need this feature for a project that is starting soon!

**Comment by ljbrackney** [comment]
This functionality is expected to be back in PAT for OpenStudio 2.0.0 to be released around 9/30.  The new version of PAT will show up in iteration releases shortly before that if you want to get your feet wet with the new interface and lend a hand with testing.

**Comment by snlavu** [comment]
Is there an iteration that I could experiment with ? Also, in the new version is there a way to convert equest geometry ? The converter measure posted in the download section for the current version  seems to have trouble with finding relevant files. Is this being addressed in the new version. Also, is there a spreadsheet analysis feature in the new version?

**Comment by macumber** [comment]
@snlavu when using the measures in the openstudio-standards branch, make sure you are using a version of OpenStudio that includes the same version of openstudio-standards.  For example, looking at the [OpenStudio version matrix](https://github.com/NREL/OpenStudio/wiki/OpenStudio-Version-Compatibility-Matrix) you can look at the [Gemfile](https://github.com/NREL/OpenStudio/blob/v1.12.0/dependencies/ruby/Gemfile) for 1.12.0.  This shows that OpenStudio 1.12.0 is using openstudio-standards 0.1.3.  Therefore you can pull the [measure](https://github.com/NREL/openstudio-standards/tree/v0.1.3/measures) from the 0.1.3 tag in the openstudio-standards repo/.

**Comment by macumber** [comment]
Also, the new version of PAT will be aligned with the spreadsheet export.  However, there are not currently iteration packages including the new version of PAT to test yet.

**Comment by snlavu** [comment]
Can you explain this further? 

.....Therefore you can pull the measure from the 0.1.3 tag in the openstudio-standards repo/. 

I have open studio 1.12.2 installed and have copied the sub folder as listed in this link- https://github.com/phylroy/OpenStudio-Prototype-Buildings/archive/master.zip
And copied the specific measure pertaining to equest converter
\lib\btap\measures\btap_equest_converter
ino the measures folder. How do I go about from here?

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
