### ISSUE TITLE
Embedded Ruby does not respect RUBYLIB enviornment variable

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2329]
It is not added to front of $: as it would be in ruby

**Comment by macumber** [comment]
I believe this is part of the plan for loading newer versions of gems in the CLI

**Comment by macumber** [comment]
To replicate, test.rb contains:
puts $:.join("\n")

E:\openstudio-2-0\core-build\Products\Debug>ruby test.rb
C:/ruby-2.0.0-p594-x64-mingw32/lib/ruby/site_ruby/2.0.0
C:/ruby-2.0.0-p594-x64-mingw32/lib/ruby/site_ruby/2.0.0/x64-msvcrt
C:/ruby-2.0.0-p594-x64-mingw32/lib/ruby/site_ruby
C:/ruby-2.0.0-p594-x64-mingw32/lib/ruby/vendor_ruby/2.0.0
C:/ruby-2.0.0-p594-x64-mingw32/lib/ruby/vendor_ruby/2.0.0/x64-msvcrt
C:/ruby-2.0.0-p594-x64-mingw32/lib/ruby/vendor_ruby
C:/ruby-2.0.0-p594-x64-mingw32/lib/ruby/2.0.0
C:/ruby-2.0.0-p594-x64-mingw32/lib/ruby/2.0.0/x64-mingw32

E:\openstudio-2-0\core-build\Products\Debug>openstudio.exe test.rb
:
:/ruby/2.0.0
:/ruby/2.0.0/x86_64-darwin13.4.0
:/ruby/2.0.0/x64-mswin64_120
:/ruby/2.0.0/bundler/gems/openstudio-standards-143191b8e720/openstudio-standards
/lib
:/ruby/2.0.0/bundler/gems/OpenStudio-workflow-gem-586792578e8d/lib

E:\openstudio-2-0\core-build\Products\Debug>set RUBYLIB=E:\

E:\openstudio-2-0\core-build\Products\Debug>echo %RUBYLIB%
E:\

E:\openstudio-2-0\core-build\Products\Debug>ruby test.rb
E:\
C:/ruby-2.0.0-p594-x64-mingw32/lib/ruby/site_ruby/2.0.0
C:/ruby-2.0.0-p594-x64-mingw32/lib/ruby/site_ruby/2.0.0/x64-msvcrt
C:/ruby-2.0.0-p594-x64-mingw32/lib/ruby/site_ruby
C:/ruby-2.0.0-p594-x64-mingw32/lib/ruby/vendor_ruby/2.0.0
C:/ruby-2.0.0-p594-x64-mingw32/lib/ruby/vendor_ruby/2.0.0/x64-msvcrt
C:/ruby-2.0.0-p594-x64-mingw32/lib/ruby/vendor_ruby
C:/ruby-2.0.0-p594-x64-mingw32/lib/ruby/2.0.0
C:/ruby-2.0.0-p594-x64-mingw32/lib/ruby/2.0.0/x64-mingw32

E:\openstudio-2-0\core-build\Products\Debug>openstudio.exe test.rb
:
:/ruby/2.0.0
:/ruby/2.0.0/x86_64-darwin13.4.0
:/ruby/2.0.0/x64-mswin64_120
:/ruby/2.0.0/bundler/gems/openstudio-standards-143191b8e720/openstudio-standards
/lib
:/ruby/2.0.0/bundler/gems/OpenStudio-workflow-gem-586792578e8d/lib

**Comment by macumber** [comment]
@asparke2 is this needed for first release of OpenStudio 2.0?

**Comment by kbenne** [comment]
https://github.com/NREL/OpenStudio/commit/229d3b89d8ed045f6e6e4a4c6e406a2e7d936f43

and then

https://github.com/NREL/OpenStudio/commit/b63a35ad0aa0b3315488c0b33e1d1ad74858b7e2
