### ISSUE TITLE
CLI documentation

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2334]
@kbenne what do you think?  any way to turn a markdown doc into a man page?

**Comment by pachi** [comment]
pandoc could do it, though I have not tested it myself. http://pandoc.org

**Comment by macumber** [comment]
@DavidGoldwasser can you accept if documentation [here](http://nrel.github.io/OpenStudio-user-documentation/reference/command_line_interface/) is sufficient?

**Comment by rHorsey** [comment]
@DavidGoldwasser - is Dan's link sufficient?
