### ISSUE TITLE
OSW flag to stop before energy or run reporting measures only

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2336]

**Comment by macumber** [comment]
@evanweaver @kflemin is this a feature in initial pat release in december?

**Comment by macumber** [comment]
I think this is best fixed by adding explicit workflow steps

**Comment by macumber** [comment]
If this feature is just for the CLI and not PAT, I think it can be closed.  @shorowit can you confirm this is working?

**Comment by shorowit** [comment]
I have been successfully using `openstudio.exe run -m`, if that's what you're asking. 

(I do sometimes get permission denied errors on my run.log file, though that may be unrelated.)

**Comment by macumber** [comment]
Thanks Scott
