### ISSUE TITLE
Incorrect Display Name for 'Central Heating Maximum System Air Flow Ratio'

### ISSUE THREAD

**Issue by adhilton25** [NREL/OpenStudio#2339]
The field that gets translated to `Central Heating Maximum System Air Flow Ratio` in the `Sizing:System` object is labeled as `Minimum System Air Flow Ratio`. This causes the user (me) to inaccurately assume what the value in this field controls.

**OS**

![image](https://cloud.githubusercontent.com/assets/19593469/17935547/ee2218d4-69d8-11e6-8bf9-f9ddd918c893.png)

**IDF**
...

```
Autosize,                               !- Design Outdoor Air Flow Rate {m3/s}
0.3,                                    !- Central Heating Maximum System Air Flow Ratio
-17.7777777777777,                      !- Preheat Design Temperature {C}
```

...

**Comment by asparke2** [comment]
Closing this issue.  The general practice (to keep the API stable) is to keep the methods and IDD field name changes out.
