### ISSUE TITLE
isomodel measure inconsistency

### ISSUE THREAD

**Issue by miwamasa** [NREL/OpenStudio#2345]
There is an incosistency in isomodel/SimulationMeasure
at "  Calculating Electric and Gas Loads" between the following two

   OpenStudio/openstudiocore/resources/isomodel/SimulationMeasure/measure.rb
   OpenStudio/openstudiocore/resources/isomodel/SimulationMeasure/osm2iso.rb

in "osm2iso.rb", all x_occ_total and x_unocc_total is sumed up using "+=" 
but in "measure.rb",   "+=" is changed to "="

which one is true?

from "measure.rb"

```
    space_types.each do |space_type|
        # work with the lighting schedule - luminaires are not supported at this time
        space_area = space_type.floorArea
        space_type.lights.each do |light|
            if not light.schedule.empty?    # look for a lighting schedule
                sched = light.schedule.get  # get the schedule
                light_total_area += space_area
                light_occ_total = occ_aves[sched.name.to_s] * space_area
                light_unocc_total = unocc_aves[sched.name.to_s] * space_area
            end
        end
```

from "osm2iso.rb"

```
   space_types.each do |space_type|
    # work with the lighting schedule - luminaires are not supported at this time
    space_area = space_type.floorArea
    space_type.lights.each do |light|
        if not light.schedule.empty?    # look for a lighting schedule
            sched = light.schedule.get  # get the schedule
            light_total_area += space_area
            light_occ_total += occ_aves[sched.name.to_s] * space_area
            light_unocc_total += unocc_aves[sched.name.to_s] * space_area
        end

```

**Comment by macumber** [comment]
@miwamasa thanks for the report, have you been using this measure?  the team implementing this functionality did not fully test their implementation and we have not been recommending that people use it yet.

**Comment by miwamasa** [comment]
Thanks. We actually using this for our R&D project.  I understood that this measure is in development stage. I wil let you know whatever I found in trying this iso measure, that might help you.

**Comment by macumber** [comment]
Awesome!

**Comment by asparke2** [comment]
Closing this issue as the group adding the ISO model is no longer continuing work on this feature.
