### ISSUE TITLE
ZoneCapacitanceMultiplierResearchSpecial not translated to E+

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2354]
Using an OSM with the following object; the IDF does not have a corresponding object.

```
OS:ZoneCapacitanceMultiplier:ResearchSpecial,
  {6bfced16-b16f-47f6-8223-f7e267d75d19}, !- Handle
  ,                                       !- Temperature Capacity Multiplier
  15,                                     !- Humidity Capacity Multiplier
  ;                                       !- Carbon Dioxide Capacity Multiplier
```

**Comment by macumber** [comment]
https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator.cpp#L2576

**Comment by macumber** [comment]
@shorowit if you want this in 1.14 are you able to implement the change?

**Comment by shorowit** [comment]
It's a pretty low priority for us. But if no one else does it, @nmerket will eventually get to it.

**Comment by nmerket** [comment]
It's on my list now. What was that link above supposed to point to @macumber? It seems to have moved.

**Comment by macumber** [comment]
Awesome, thanks @nmerket, the link was pointing to code that is now at https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator.cpp#L2675

I guess we added 99 lines of translator between this post at now
