### ISSUE TITLE
Crash in translate ZoneHVACEnergyRecoveryVentilator 

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2364]
Adam Hilton created a ZoneHVACEnergyRecoveryVentilator using the following code:

```
ervController = OpenStudio::Model::ZoneHVACEnergyRecoveryVentilatorController.new(model)
ervController.setName("#{objectName}: Controller")
heatExchanger = OpenStudio::Model::HeatExchangerAirToAirSensibleAndLatent.new(model)
heatExchanger.setName("#{objectName}: Heat Exchanger")
supplyFan = OpenStudio::Model::FanOnOff.new(model)
supplyFan.setName("#{objectName}: Supply Fan")
supplyFan.setPressureRise(62.2722275)
supplyFan.setMaximumFlowRate(flowRate)
supplyFan.setMotorEfficiency(0.9)
exhaustFan = OpenStudio::Model::FanOnOff.new(model)
exhaustFan.setPressureRise(62.2722275)
exhaustFan.setMaximumFlowRate(flowRate)
exhaustFan.setName("#{objectName}: Exhaust Fan")
exhaustFan.setMotorEfficiency(0.9)
erv = OpenStudio::Model::ZoneHVACEnergyRecoveryVentilator.new(model,heatExchanger,supplyFan,exhaustFan)
erv.setController(ervController)
erv.setAvailabilitySchedule(schedule)
erv.setSupplyAirFlowRate(flowRate)
erv.setExhaustAirFlowRate(flowRate)
erv.setName(objectName)
thermalZone.addEquipment(erv)
```

resulting model causes a crash [here](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACEnergyRecoveryVentilator.cpp#L103)

**Comment by MatthewSteen** [comment]
possibly related to #2184

**Comment by adhilton25** [comment]
@MatthewSteen Yeah, I remember the UV problem, but I think this is different. The equipment nodes are setup and connected correctly. It looks like the exhaust outlet node doesn't get added to the zone exhaust list and supply inlet outdoor air node doesn't get created. It works fine when you drag and drop the erv from the library.

**Comment by macumber** [comment]
@kbenne should this be in 1.14?

**Comment by adhilton25** [comment]
This may just be an oversight on my behalf, and might not actually be an issue. It's thermal zone `addEquipment` method that's the problem. It adds the object to the equipment list, but doesn't connect the nodes, I don't know if this is the desired behavior. The method is described as '...relatively dumb' in the SDK documentation. It works fine with the zone HVAC `addToThermalZone` method, which is probably what I should have been using all along.

**Comment by asparke2** [comment]
Closing as @adhilton25 is correct, `addToThermalZone` is the method that does this.
