### ISSUE TITLE
Error in intersectSurfaces

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2370]
Intersection fails to divide surface, error occurs in measure test for:

openstudio-beopt\measures\ResidentialGeometrySingleFamilyDetached\

Was not able to reproduce outside of the measure

**Comment by macumber** [comment]
@shorowit

**Comment by shorowit** [comment]
@macumber I forget how you reproduced this "outside of the measure", but I can reproduce the issue using an OSW (see below) with OpenStudio 2.0. It's a pretty big blocker for us.

[2000sqft_2story_FB_GRG_UA.osw.txt](https://github.com/NREL/OpenStudio/files/575823/2000sqft_2story_FB_GRG_UA.osw.txt)

**Comment by macumber** [comment]
Thanks @shorowit its on my queue, pat has to come first though, we are all focused on that

**Comment by shorowit** [comment]
This is working in the latest OS 2.0 build! Thanks @macumber!
