### ISSUE TITLE
OpenStudio 2.0: Importing C# library in IronPython threw 'OpenStudio.OpenStudioModelCorePINVOKE'

### ISSUE THREAD

**Issue by mostaphaRoudsari** [NREL/OpenStudio#2371]
This is an issue that we had with OpenStudio 1 which was solved at some point but is again back. Here is the code:

```python
import sys
import clr
sys.path.append(r'C:\Program Files (x86)\openstudio2-1.13.0\bin')
sys.path.append(r'C:\Program Files (x86)\openstudio2-1.13.0\CSharp\openstudio')
clr.AddReferenceToFileAndPath(r"C:\Program Files (x86)\openstudio2-1.13.0\CSharp\openstudio\openStudio.dll")

import OpenStudio
model = OpenStudio.Model()
```
and the error:
**SystemError: The type initializer for 'OpenStudio.OpenStudioModelCorePINVOKE' threw an exception.**

**Comment by macumber** [comment]
Nooooo!!!!!  I was hoping OpenStudio 2.0 would be the final nail in all the coffin for [this issue](https://github.com/mostaphaRoudsari/Honeybee/issues/214).  One thing to mention in case it is the issue is that the OpenStudio 2.0 Windows installer is 64 bit even though it is installed in 'Program Files (x86)' (this is just an installer bug).  So you would have problems if you were trying to load it into a 32 bit process.

**Comment by macumber** [comment]
Also OpenStudio.dll is the C# wrapper that you should load, openstudio_csharp.dll are the native extensions.  I think you got that right (only thing I noticed was wrong capitalization of openStudio.dll).  You should not need to append 'C:\Program Files (x86)\openstudio2-1.13.0\bin' to the path to load the C# bindings, you only need the two files in the CSharp directory.  The openstudio.exe in the bin is needed to apply measures and run simulations but it is statically linked so does not need any of the dlls.  Those three files are all you should need to distribute with Honeybee.

**Comment by macumber** [comment]
Just some notes:

http://stackoverflow.com/questions/3907041/swig-mono-c-sharp-example-errors-of-not-finding-the-library

```
import sys
import clr
#sys.path.insert(0, r'C:\Program Files\openstudio2-1.13.0\bin')
#sys.path.insert(0, r'C:\Program Files\openstudio2-1.13.0\CSharp\openstudio')
sys.path.insert(0, r'E:\openstudio-2-0e\core-build\_CPack_Packages\win64\IFW\OpenStudio-1.13.0-win64\packages\CSharpAPI\data\CSharp\openstudio')

print os.environ["PATH"]
#os.environ["PATH"] = 'E:\openstudio-2-0e\core-build\_CPack_Packages\win64\IFW\OpenStudio-1.13.0-win64\packages\CSharpAPI\data\CSharp\openstudio;' + os.environ["PATH"]

#print dir(clr.LoadAssemblyFromFile(r"OpenStudio.dll"))
clr.LoadAssemblyFromFile('OpenStudio.dll')

#print "yo"
#from ctypes import *
#try:
#    #cdll.LoadLibrary("openstudio_csharp.dll")
#    CDLL("openstudio_csharp.dll")
#except Exception  as inst:
#    print type(inst)
#    print dir(inst)
#    print inst.message
#    print dir(inst.clsException)
#    print inst.clsException.InnerException
#    print inst.clsException.StackTrace
#    print inst.clsException.Source

#clr.AddReferenceToFileAndPath(r"C:\Program Files\openstudio2-1.13.0\CSharp\openstudio\OpenStudio.dll")

import OpenStudio
print "Hello"

try:
    model = OpenStudio.Model()
except Exception  as inst:
    print type(inst)
    print dir(inst)
    print inst.message
    print dir(inst.clsException)
    print inst.clsException.InnerException
    print inst.clsException.StackTrace
    print inst.clsException.Source
    
print "Goodbye"
```

**Comment by macumber** [comment]
This code seems to indicate that the python interpreter in Grasshopper is 32bit:

    print("%x" % sys.maxsize, sys.maxsize > 2**32)

Got the code from [here](http://stackoverflow.com/questions/1405913/how-do-i-determine-if-my-python-shell-is-executing-in-32bit-or-64bit-mode-on-os)

**Comment by mostaphaRoudsari** [comment]
@macumber I had the exact same feelings! :|. Thanks for checking it though. 

From the bottom to the top. Rhino has both 32bit and 64bit but Honeybee works on the 64bit.

![image](https://cloud.githubusercontent.com/assets/2915573/19213319/2cc0fb4c-8d37-11e6-80f5-e79b952090ef.png)

Here is the exception from running your sample code:

```python
c:\Program Files\Rhinoceros 5 (64-bit)\System\;c:\Program Files\Common Files\McNeel Shared\Rhinoceros\5.0\;c:\Program Files\Rhinoceros 5 (64-bit)\System\;c:\Program Files\Common Files\McNeel Shared\Rhinoceros\5.0\;C:\Program Files (x86)\gs\gs9.18;C:\Program Files\Microsoft MPI\Bin\;C:\ProgramData\Oracle\Java\javapath;.;C:\DAYSIM\lib\;C:\DAYSIM\bin\;C:\Perl64\site\bin;C:\Perl64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Common Files\Autodesk Shared\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Program Files\Docker Toolbox;C:\Program Files (x86)\ImageMagick-6.9.3-Q16;C:\Program Files (x86)\gs\gs9.18;C:\Program Files\Microsoft MPI\Bin\;C:\ProgramData\Oracle\Java\javapath;.;C:\DAYSIM\lib\;C:\DAYSIM\bin\;C:\Perl64\site\bin;C:\Perl64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Common Files\Autodesk Shared\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft MPI\Bin\;C:\ProgramData\Oracle\Java\javapath;.;C:\python27;C:\Program Files (x86)\ImageMagick-6.9.3-Q16;C:\Program Files (x86)\gs\gs9.18;C:\Program Files\Microsoft MPI\Bin\;C:\ProgramData\Oracle\Java\javapath;.;C:\DAYSIM\lib\;C:\DAYSIM\bin\;C:\Perl64\site\bin;C:\Perl64\bin;C:\W
Hello
<type 'exceptions.SystemError'>
['Equals', 'GetHashCode', 'GetType', 'InitializeFromClr', 'Item', 'MemberwiseClone', 'ReferenceEquals', 'ToString', '__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__getitem__', '__getslice__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__unicode__', 'args', 'clsException', 'message']
The type initializer for 'OpenStudio.OpenStudioModelCorePINVOKE' threw an exception.
['Data', 'Equals', 'GetBaseException', 'GetHashCode', 'GetObjectData', 'GetType', 'HResult', 'HelpLink', 'InnerException', 'MemberwiseClone', 'Message', 'ReferenceEquals', 'Source', 'StackTrace', 'TargetSite', 'ToString', 'TypeName', '__class__', '__delattr__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'add_SerializeObjectState', 'remove_SerializeObjectState']
System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'openstudio_csharp': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at OpenStudio.OpenStudioModelCorePINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_OpenStudioModelCore(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at OpenStudio.OpenStudioModelCorePINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at OpenStudio.OpenStudioModelCorePINVOKE.SWIGExceptionHelper..ctor()
   at OpenStudio.OpenStudioModelCorePINVOKE..cctor()
   at Microsoft.Scripting.Interpreter.NewInstruction.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
Microsoft.Dynamic
Goodbye
```

**Comment by macumber** [comment]
I'm pretty sure it's an architecture/platform thing, I'll keep looking.

**Comment by macumber** [comment]
I want this fixed for the official 2.0 release in December

**Comment by mostaphaRoudsari** [comment]
> I want this fixed for the official 2.0 release in December

Yes please! :) @chriswmackey has been working hard to get all the OpenStudio features in Honeybee up and running and we were going to officially migrate from EnergyPlus to OpenStudio in the next release! Let us know if there is anything that you need us to provide/test.

**Comment by chriswmackey** [comment]
@macumber and @mostaphaRoudsari ,

Thank both of you for being ahead of the curve.  I can also supply another machine to test out fixes as I remember the previous instantiations of this issue did not affect all machines.  Are the 2.0 dll's available for download anywhere?  I understand if they're released to a limited audience at this point.

-Chris

**Comment by mostaphaRoudsari** [comment]
@chriswmackey sent!

**Comment by chriswmackey** [comment]
Thank you, @mostaphaRoudsari .

I can confirm that the issue afflicts my system as well:
![image](https://cloud.githubusercontent.com/assets/5567574/19216688/9de9526c-8d94-11e6-9d32-be4665de5314.png)

-Chris

**Comment by macumber** [comment]
This was an issue caused by changes needed to get Webkit working in the app.  I rebuilt and uploaded a [zip](https://openstudio-builds.s3.amazonaws.com/DansStuff/openstudio2-1.13-issue2371.zip) and a [7z](https://openstudio-builds.s3.amazonaws.com/DansStuff/openstudio2-1.13-issue2371.7z) with the two dlls needed to run the C# bindings (@kbenne 7z verison is less than 20 MB!).  Extract one of those packages somewhere (e.g. E:\csharp\) then you should be good to go:

```
import sys
import clr
sys.path.insert(0, r'E:\csharp')
clr.AddReferenceToFileAndPath(r'E:\csharp\OpenStudio.dll')

import OpenStudio
model = OpenStudio.Model();
print model;

```

**Comment by macumber** [comment]
I tested that this works with command line IronPython if that is interesting to anyone else @mbadams5 @MatthewSteen @jmarrec ?

**Comment by mostaphaRoudsari** [comment]
@macumber I'm still getting the same error after testing the zipped version.

```python
<type 'exceptions.SystemError'>
['Equals', 'GetHashCode', 'GetType', 'InitializeFromClr', 'Item', 'MemberwiseClone', 'ReferenceEquals', 'ToString', '__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__getitem__', '__getslice__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__unicode__', 'args', 'clsException', 'message']
The type initializer for 'OpenStudio.OpenStudioModelCorePINVOKE' threw an exception.
['Data', 'Equals', 'GetBaseException', 'GetHashCode', 'GetObjectData', 'GetType', 'HResult', 'HelpLink', 'InnerException', 'MemberwiseClone', 'Message', 'ReferenceEquals', 'Source', 'StackTrace', 'TargetSite', 'ToString', 'TypeName', '__class__', '__delattr__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'add_SerializeObjectState', 'remove_SerializeObjectState']
System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'openstudio_csharp': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at OpenStudio.OpenStudioModelCorePINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_OpenStudioModelCore(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at OpenStudio.OpenStudioModelCorePINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at OpenStudio.OpenStudioModelCorePINVOKE.SWIGExceptionHelper..ctor()
   at OpenStudio.OpenStudioModelCorePINVOKE..cctor()
   at Microsoft.Scripting.Interpreter.NewInstruction.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run3[T0,T1,T2,TRet](T0 arg0, T1 arg1, T2 arg2)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
Microsoft.Dynamic
```

**Comment by macumber** [comment]
Can you try adding the openstudio location to your path?  Either before starting ipython or after, using 

    os.environ["PATH"] = 'C:\csharp;' + os.environ["PATH"]

**Comment by mostaphaRoudsari** [comment]
Still the same!  :(

![image](https://cloud.githubusercontent.com/assets/2915573/19227243/13da3252-8e85-11e6-8e24-351b60c009d3.png)

Let's see if it will work on @chriswmackey's system.

**Comment by jmarrec** [comment]
I'm on mac right now. I installed the `OpenStudio2-1.13.0.046dcfd9c9-Darwin` but there's no CSharp nor Python folders/bindings anyways.

**Comment by macumber** [comment]
Hey @jmarrec you are right, we don't have C#/Mono bindings on Mac.  As far as the Python bindings go, I don't think we have built those with 2.x yet.  We should be able to get those down to a single dll but it will take a little bit of work.

**Comment by macumber** [comment]
I just took another look at this and verified that I can load the dlls in the 7Zip package.  I used ProcessExplorer to view the dlls loaded by IronPython and didn't see anything loaded that you might not have on your machine.  Here are md5sums just to verify we are looking at the same files:

```
dmacumbe@dmacumbe-24908s MINGW64 /e/csharp
$ md5sum OpenStudio.dll
398d538a18428ee80b6c00ea7ced0454

dmacumbe@dmacumbe-24908s MINGW64 /e/csharp
$ md5sum.exe openstudio_csharp.dll
696175d7fbac9aba8a354e429621cd99 
```



![10-10-2016 8-31-12 am](https://cloud.githubusercontent.com/assets/1327850/19239628/2b34257c-8ec4-11e6-8b70-81885ae4a2f3.jpg)

**Comment by macumber** [comment]
@mostaphaRoudsari what version of Windows are you on?

**Comment by chriswmackey** [comment]
@macumber and @mostaphaRoudsari ,

Sorry for being late here.  I got the chance to test out your fixed version, @macumber , and I can confirm that it is working on my system:

![image](https://cloud.githubusercontent.com/assets/5567574/19246721/ba177614-8ef5-11e6-9e96-c8305736ac7b.png)

 I am running Windows 8.1 and I will try to test it out on other versions of Windows soon.
Thanks again for responding to everything so quickly, @macumber 

-Chris

**Comment by mostaphaRoudsari** [comment]
@chriswmackey great that you can load it on your machine.
@macumber I'm using Windows 8.

**Comment by chriswmackey** [comment]
I just tried it out on Windows 7 and I also got it to work:
![osworking](https://cloud.githubusercontent.com/assets/5567574/19247010/19a06054-8ef7-11e6-9682-d8b3850846f0.JPG)

So we have 3 successful cases out of 4, which is a good sign.  Looking forward to your response, @macumber .

-Chris

**Comment by mostaphaRoudsari** [comment]
@macumber  Here is my try with Process Explorer.

![image](https://cloud.githubusercontent.com/assets/2915573/19247692/629df0de-8efa-11e6-9974-5636aec3724c.png)

Can you send me the list of dlls? I can check one by one to find what's the differences or what is missing?

**Comment by macumber** [comment]
I can't get a text list, here are screenshots:

![10-10-2016 4-23-43 pm](https://cloud.githubusercontent.com/assets/1327850/19253118/1fe33bc6-8f06-11e6-94ea-e4453ef70e55.jpg)
![10-10-2016 4-23-58 pm](https://cloud.githubusercontent.com/assets/1327850/19253119/216cdb64-8f06-11e6-8792-57d190104c20.jpg)

We have different versions of IronPython but I don't see that making a huge difference.

**Comment by mostaphaRoudsari** [comment]
@macumber, here is the missing dlls.

api-ms-win-core-xsta-12-1-0.dll
	apisetschema.dll
	crypt32.dll
	dbghelp.dll
	IPHLPAPI.DLL
	lpk.dll
	Microsoft.Dynamic.dll (instead I haveMicrosoft.Dynamic.ni.dll)
	Microsoft.Scripting.dll (instead I have Microsoft.Scripting.ni.dll)
	mpr.dll
	msasn1.dll
	msvcp120.dll
	nlssorting.dll
	nsi.dll
	**OpnStudio_csharp.dll** (I have OpenStudio loaded twice)
	PGHook.dll
	psapi.dll
	RpcRtRemote.dll
	sortdefault.nlp
	usp10.dll
	winnsi.dll
	ws2_32.dll
	wsock32.dll

**Comment by macumber** [comment]
I saw that you had a few dlls listed twice but I think that might be because you had two things selected in the ProcessExplorer tree.  Can you try selecting just the ipy64 process and see if it lists OpenStudio.dll twice?

**Comment by mostaphaRoudsari** [comment]
I checked. It's only ipy64.

**Comment by macumber** [comment]
Hmm that is weird that OpenStudio.dll is listed twice, not sure if that means anything or not.  The exception occurs during the call to OpenStudio::Model() when we try to load the openstudio_csharp.dll.  I suspect that there is a dependency of openstudio_csharp.dll that can't be found on your machine.  Can you try installing both the 64bit and 32bit MSVC runtime libraries (120 version) from here:

https://www.microsoft.com/en-us/download/details.aspx?id=40784

I just tested on a clean box and could not run the program until I installed these.

**Comment by macumber** [comment]
@kbenne FYI, are we shipping MSVC runtime libraries on Windows?

**Comment by kbenne** [comment]
I think so, but they are probably only included in the bin directory. Since we have separate install locations for ruby and C# we either need to install the runtimes again or consider a different layout.

**Comment by kbenne** [comment]
since we have a component installer maybe installing the runtimes in two (or three) different places isn't so terrible. thoughts?

**Comment by macumber** [comment]
Yes we are and you are right only in the bin directory.  @mostaphaRoudsari you can either add the openstudio/bin directory to the path or copy the 'msvcp120.dll' and 'msvcr120.dll' into the directory with the new C# bindings I sent you.

**Comment by macumber** [comment]
Yeah I'd say we should install those dlls in the C# directory, it's like 1.5MB total.  Not sure why Microsoft doesn't just ship these with Windows in the first place...

**Comment by mostaphaRoudsari** [comment]
@macumber I'm not sure if copying the files would help. If you check [the first comment](https://github.com/NREL/OpenStudio/issues/2371#issue-181796150) I add `bin` folder to path before importing OpenStudio. I will download the dll files and let you know how it goes.

**Comment by mostaphaRoudsari** [comment]
:tada:

Thanks, @macumber. I added the path to bin folder and used the new OpenStudio dll files and now it's working.

![image](https://cloud.githubusercontent.com/assets/2915573/19282194/4353f4d2-8fbb-11e6-88ec-f626fee1b6d6.png)

**Comment by macumber** [comment]
Woo!  The first package we sent out was linked to dynamic Qt libraries, the newest one has them statically linked so that is why this didn't work the first time.  Unleash the honeybees!

**Comment by chriswmackey** [comment]
I tested it out on Windows 10 and I was able to get it working:
![image](https://cloud.githubusercontent.com/assets/5567574/19291464/48161d6a-8fe3-11e6-86d4-0af428fb609e.png)

I think that it is safe to conclude at this point that the issue doesn't have anything to do with operating system version (now that Windows 7, 8, and 10 have all worked for me).  All of my tests have been with the ironPython version that comes with Rhino.  Is this also the case for you, @mostaphaRoudsari ?

**Comment by chriswmackey** [comment]
... and I posted that after the issue was fixed.  Glad that it got resolved!

**Comment by macumber** [comment]
@arif-hanif how are you using C# bindings on Linux?  Did you build these yourself?

**Comment by chriswmackey** [comment]
@macumber ,

I have unfortunately uncovered a recent case of this issue again with OpenStudio 2.1.0.  The computer was using C# bindings and running Windows 10.  It is presently the only case of this issue that I know of for OpenStudio 2.1.0 and I am sure that there are hundreds of other machines running it fine.

Still, it seems we are not yet finished with this issue.  Do you know if there are ant SWIG updates on the horizon that might help this case?  Also, if there any information that we could get you from this computer experiencing the issue, please let us know and we would be happy to provide it.  The exception is exactly the same as the previous cases and occurs when one initializes the model object:

The type initializer for 'OpenStudio.OpenStudioModelCorePINVOKE' threw an exception.

Thank you, as always,
-Chris

**Comment by macumber** [comment]
Thanks @chriswmackey this error is the generic error that SWIG provides when a dll dependency fails to load (either missing, or wrong version, or something).  I think we have found many of the potential problems but I guess there must be something we are still missing.  The solutions are still the same, try to track down the missing or incorrect dlls being loaded with dependency walker or a similar tool.

**Comment by chriswmackey** [comment]
@macumber ,
Thank you for the response. I don't have direct access to the computer that is experiencing the issue but the colleague of mine who is experiencing it is close by so there's a chance that we could do some debugging. If we manage to run dependency walker and track down the dll that is misbehaving, we will report it here.
Thanks again,
-Chris

**Comment by ronaldreagonr** [comment]
Hi I have 1. Solution exception:The type initializer for 'OpenStudio.OpenStudioModelCorePINVOKE' threw an exception. ISSUE
