### ISSUE TITLE
Thermal Storage Number of Nodes forward translation

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2373]
User on UnmetHours identified this and as shown below I was able to confirm the issue.
https://unmethours.com/question/20564/thermal-energy-storage-tank-fields-reversed/

The fields are not reversed. It seems like Tank Recovery Time is forward translated correctly, but the Number of Nodes field in forward translation seems to always result in the value entered for Tank Recovery Time.
![screenshot 2016-10-12 08 55 21](https://cloud.githubusercontent.com/assets/4857055/19315192/04abddc2-905a-11e6-817e-d869b69091bd.png)

Nothing looks obviously wrong to me here.
https://github.com/NREL/OpenStudio/blob/5bf588f92e207cee5a2bc7ef8c9f939d29c0188a/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateThermalStorageChilledWaterStratified.cpp#L357

I did notice that the Tank Recovery Time takes a double with Number of Nodes takes an integer. If the entered Tank Recovery Time value isn't an integer, it gets rounded down when used for Number of Nodes.

**Comment by jmarrec** [comment]
I wrote a quick ForwardTranslate Gtest for this in #2825. Turns out this was apparently already working as of 2.3.0, but at least it won't happen ever again.
