### ISSUE TITLE
ScheduleRuleset.remove orphans winter and summer profiles

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2376]
The default profile and rules are deleted, but the summer and winter design day are not.

As a note there are similar tickets open for RenderingColor objects and for the child objects for DefaltConstructionSets.

**Comment by macumber** [comment]
@DavidGoldwasser can you link to the other issues?

**Comment by DavidGoldwasser** [comment]
related to issue #114 issue #118
