### ISSUE TITLE
remove limit on number of fans on air loops

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2377]
Currently OS limits the number of fans that can be assigned to the following objects to (2), which is not present in EnergyPlus. One use case would be [approximating a DOAS to AHU system](https://unmethours.com/question/20545/approximating-doas-to-ahus-in-energyplus/).

* AirLoopHVAC
* AirLoopHVACOutdoorAirSystem
* AirLoopHVAC + AirLoopHVACOutdoorAirSystem 

![image](https://cloud.githubusercontent.com/assets/8397034/19374679/cb46012a-918a-11e6-9f99-9cc02939d153.png)

![image](https://cloud.githubusercontent.com/assets/8397034/19374706/fd06ef6c-918a-11e6-83ae-a6f5c147926b.png)

![image](https://cloud.githubusercontent.com/assets/8397034/19374584/1c69bd22-918a-11e6-9998-a243bcd2d960.png)

**Comment by kbenne** [comment]
@MatthewSteen would you like to shine your developer credentials? It is an easy fix. Just remove these lines...

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/FanConstantVolume.cpp#L220

and do similar for FanVariableVolume.
