### ISSUE TITLE
No Thermostats for cooling only/ heating only zones

### ISSUE THREAD

**Issue by snlavu** [NREL/OpenStudio#2379]
OSM does not translate heating only or cooling only thermostats into energy plus objects! I expected there would be ThermostatSetpoint:SingleHeating / ThermostatSetpoint:SingleCooling. There is no thermostat at all! The energy model results would be greatly skewed because of this! essentially would assume that the zones are unconditioned ! OSM does run completely unless there as a zero flow issue! 
Using version 1.13.

**Comment by DavidGoldwasser** [comment]
@kbenne and @asparke2 I agree that it would be better for the simulation to fail instead of running with unexpected results.

It might be nice to support other thermostat types on translation. @snlavu the work around we normally use for this is to set a cooling setpoints hotter than we would ever see in the building. Not pretty but it works

**Comment by macumber** [comment]
@kbenne do you think this should be in 1.14?

**Comment by MatthewSteen** [comment]
This is problematic and misleading to the user. For warehouses, vehicle maintenance bays, etc, which often have heating only spaces the zone can appear to be controlled to the heating setpoing - i.e. zero unmet cooling hours - but not be controlled to setpoint when looking at the timestep outputs as seen below.

**Heating Only Zone vs. Heating and Cooling Zone**

![image](https://user-images.githubusercontent.com/8397034/28556513-10685fb4-70c4-11e7-85c5-f13dd7913741.png)

**Comment by kbenne** [comment]
I'm reluctant not totally opposed to adding new thermostat types. My reluctance is that it may complicate the user interface, and in general I tend to prefer fewer types than more.

![screen shot 2017-07-25 at 7 54 02 am](https://user-images.githubusercontent.com/707488/28572946-8928ad06-710e-11e7-8410-7d96de6e53ba.png)

How do you guys feel about letting the os -> idf translator generate single heating / single cooling thermostats if one of the schedules is undefined? Is that too magical? I also try to avoid a lot of magic in the translator, but I think in this case I prefer translator work over more object types.

**Comment by MatthewSteen** [comment]
@kbenne i think your approach to magically translate to single setpoint objects makes sense and would be my preference over adding more columns etc. Incidentally, my issue above was not related to the setpoints, but rather the air terminals.
