### ISSUE TITLE
Model test failures (Bugzilla #1004)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#238]
On 2012-12-13 11:59:55, @macumber wrote:

> ModelFixture.RoofVegetation_SpecificHeatofDrySoil_Quantity
> ModelFixture.SimulationControl_LoadsConvergenceToleranceValue_Quantity
> ModelFixture.SimulationControl_TemperatureConvergenceToleranceValue_Quantity

On 2012-12-13 12:00:45, @macumber wrote:

> http://my.cdash.org/testDetails.php?test=10117541&build=423551
> http://my.cdash.org/testDetails.php?test=10117566&build=423551
> http://my.cdash.org/testDetails.php?test=10117567&build=423551

**Comment by evanweaver** [comment]
ModelFixture.RoofVegetation_SpecificHeatofDrySoil_Quantity currently passes
SimulationControl_LoadsConvergenceToleranceValue_Quantity currently passes
SimulationControl_TemperatureConvergenceToleranceValue_Quantity currently passes
