### ISSUE TITLE
Refrigeration missing from monthly peak demand

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2383]
Monthly peak for Electricity Refrigeration is missing form OpenStudio SQL query. Issue may be related to Building Energy Performance - Electricity Peak Demand object in OpenStudio generated IDF files. It is missing the refrigeration field at the end. Need to investigate where in the code this is added.
cc: @asparke2 

Output:Table:Monthly,
  Building Energy Performance - Electricity Peak Demand,  !- Name
    2,                       !- Digits After Decimal
    Electricity:Facility,  !- Variable or Meter 1 Name
    Maximum,            !- Aggregation Type for Variable or Meter 1
    InteriorLights:Electricity,  !- Variable or Meter 1 Name
    ValueWhenMaximumOrMinimum,            !- Aggregation Type for Variable or Meter 1
    ExteriorLights:Electricity,  !- Variable or Meter 2 Name
    ValueWhenMaximumOrMinimum,            !- Aggregation Type for Variable or Meter 2
    InteriorEquipment:Electricity,  !- Variable or Meter 3 Name
    ValueWhenMaximumOrMinimum,            !- Aggregation Type for Variable or Meter 3
    ExteriorEquipment:Electricity,  !- Variable or Meter 4 Name
    ValueWhenMaximumOrMinimum,            !- Aggregation Type for Variable or Meter 4
    Fans:Electricity,        !- Variable or Meter 5 Name
    ValueWhenMaximumOrMinimum,            !- Aggregation Type for Variable or Meter 5
    Pumps:Electricity,       !- Variable or Meter 6 Name
    ValueWhenMaximumOrMinimum,            !- Aggregation Type for Variable or Meter 6
    Heating:Electricity,     !- Variable or Meter 7 Name
    ValueWhenMaximumOrMinimum,            !- Aggregation Type for Variable or Meter 7
    Cooling:Electricity,     !- Variable or Meter 8 Name
    ValueWhenMaximumOrMinimum,            !- Aggregation Type for Variable or Meter 8
    HeatRejection:Electricity,  !- Variable or Meter 9 Name
    ValueWhenMaximumOrMinimum,            !- Aggregation Type for Variable or Meter 9
    Humidifier:Electricity,  !- Variable or Meter 10 Name
    ValueWhenMaximumOrMinimum,            !- Aggregation Type for Variable or Meter 10
    HeatRecovery:Electricity,!- Variable or Meter 11 Name
    ValueWhenMaximumOrMinimum,            !- Aggregation Type for Variable or Meter 11
    WaterSystems:Electricity,!- Variable or Meter 12 Name
    ValueWhenMaximumOrMinimum,            !- Aggregation Type for Variable or Meter 12
    Cogeneration:Electricity,!- Variable or Meter 13 Name
    ValueWhenMaximumOrMinimum;            !- Aggregation Type for Variable or Meter 13

**Comment by DavidGoldwasser** [comment]
Found the code that calls this. Should be 2 line fix. Will still need to test that changing this fixes the SQL query used in standard report. I already tested that it updates the E+ HTML table.
https://github.com/NREL/OpenStudio/blob/5bf588f92e207cee5a2bc7ef8c9f939d29c0188a/openstudiocore/src/runmanager/lib/EnergyPlusPreProcessJob.cpp#L395-L425

**Comment by macumber** [comment]
@DavidGoldwasser is this complete?

**Comment by DavidGoldwasser** [comment]
Was merged in this pull request
https://github.com/NREL/OpenStudio/pull/2389
