### ISSUE TITLE
Change peak flow rate in water use equipment definitions from m3/s to m3/h or dm3/s

### ISSUE THREAD

**Issue by pachi** [NREL/OpenStudio#2391]
The current SI units for the peak flow rate in water use is m3/s and this leads to extremely small figures for DHW use.

Compared to gpm, this is 15850 times smaller, and numbers with 5 or six decimal positions are usual for residential units (and the current precission for the field is 6 digits).

As an example, consider the DHW use for a 4 people single family house, with a total daily heat water (at 60ºC) of 112 l/day, and a peak demand which is around a 10% of the daily total. That means we have
a peak demand of 112/3600/1000/10 = 3e-6.

As far as I can tell, the precission of the field is 6 digits, and this is a problem for even smaller flows, which are not unusual. This also means that this extremely small unit poses not only a usability problem (GUI), but also a precission problem, and is very prone to errors (skipping a decimal point is easy).

**Comment by macumber** [comment]
@asparke2 what do you think of this?  could this be done in the GUI only and not change the value in the OSM or is that confusing?

**Comment by asparke2** [comment]
I think it'd be fine to change in the GUI, but leave the C++ alone.

**Comment by pachi** [comment]
I'd suggest using litres per second (l/s) in the GUI and indeed keeping m3/h internally if there's no precision problem there.

**Comment by pachi** [comment]
Increasing the number of digits the GUI inputs allows (so figures in the order of 1e-7 are accepted) could be good enough, and less confusing than changing the units.

**Comment by pachi** [comment]
I've just seen that it is allowed using scientific notation with exponents. Therefore, I'm fine closing this bug as it's just a minor usability issue.
