### ISSUE TITLE
Cash flow for fuels not populating because of E+ query change

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2393]
May be a few versions old, but table is now "Energy and Water Cost Cash Flows (Without Escalation)" instead of "Energy Cost Cash Flows (Without Escalation)". Fix will correct this, and also remove work around for water, which used to not show up with fuels, but now does.

**Comment by DavidGoldwasser** [comment]
Fix is live on measure repo
https://github.com/NREL/OpenStudio-measures/commit/8a0ea00fe51b4e2b4a07cd65a7fd03f5270392e1

**Comment by macumber** [comment]
@DavidGoldwasser did you fix this in the measure on develop?

Also, we point OpenStudio 2.0 App to a particular UID on BCL here:

https://github.com/NREL/OpenStudio/blob/os_2_0_develop/openstudiocore/src/openstudio_lib/OSDocument.cpp#L1350

Is this pointing the correct measure on BCL?

**Comment by DavidGoldwasser** [comment]
@macumber That is the correct UID to point to. I have not pushed to OpenStudio repo yet. I'll do that today
