### ISSUE TITLE
  require 'openstudio/ruleset/ShowRunnerOutput' show_output for initial and final condition not showing text for 2x

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2395]
Don't have to be fixed in 1.14 but want to fix this sometimes. Used a lot in visually inspecting measure tests. Below is 2.x view of initial and final condition, vs. seeing the message in 1.x

**INITIAL CONDITION**
#<OpenStudio::LogMessage:0x007f9724082d08>
**FINAL CONDITION**
#<OpenStudio::LogMessage:0x007f9724081e80>
**INFO MESSAGES**

**Comment by DavidGoldwasser** [comment]
This doesn't affect info, warning, or error messages, however related to this if I need to test text in those messages as part of a measure test, I had to split to 2.x vs .1.x code as shown here.
https://github.com/NREL/OpenStudio-measures/blob/develop/NREL%20working%20measures/openstudio_results/tests/OpenStudioResults_Test.rb#L138-L162

**Comment by macumber** [comment]
https://github.com/NREL/OpenStudio-measures/blob/geometry_simplification/NREL%20working%20measures/create_typical_building_from_model/tests/create_typical_building_from_model_test.rb#L171-L176

**Comment by macumber** [comment]
@DavidGoldwasser I think this is fixed in 2.0.4, can you confirm?  I ran the create_typical_building_from_model_test.rb file (had to modify it due to missing method errors) and got this output, notice initial and final condition printed twice:

```
stepInitialCondition: The building started with 505 objects.
stepFinalCondition: The building finished with 462 objects.
**MEASURE APPLICABILITY**
0 = Success
**INITIAL CONDITION**
The building started with 505 objects.
**FINAL CONDITION**
The building finished with 462 objects.
**INFO MESSAGES**
```

**Comment by macumber** [comment]
Assigned to @DavidGoldwasser to confirm

**Comment by DavidGoldwasser** [comment]
@macumber do you think this is just on mac?

Here is what i see in newest installer

stepInitialCondition: The building started with 505 objects.
stepFinalCondition: The building finished with 563 objects.
**MEASURE APPLICABILITY**
[openstudio.WorkflowStepResult] <0> WorkflowStepResult value called with undefined stepResult, returning 'Success'
0 = Success
**INITIAL CONDITION**
#<OpenStudio::LogMessage:0x007fa8f2e26da8>
**FINAL CONDITION**
#<OpenStudio::LogMessage:0x007fa8f2e26b28>
**INFO MESSAGES**
Removing 241 objects from model

**Comment by macumber** [comment]
I think this was fixed in the CLI but not the ruby bindings, should be fixed in both now
