### ISSUE TITLE
GeneratorPhotovoltaic::simple constructor makes incomplete object

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#2396]
panel = OpenStudio::Model::GeneratorPhotovoltaic.simple(model)

Will make the following object: 

    OS:Generator:Photovoltaic,
    {221cce3f-7243-4c97-9e95-2884f9831d1b}, !- Handle
    Generator Photovoltaic 1,               !- Name
    ,                                       !- Surface Name
    {09e379c3-2171-4382-8089-2bae7bd33bc3}; !- Module Performance Name

missing the last three fields, 'Heat Transfer Integration Mode', 'Number of Series Strings in Parallel' and 'Number of Modules in Series'. Those fields are created if they are explicitly set or reset. 

I'm actually not sure if this is a bug or not, i.e. if it's by design that those fields don't get a default value and must be explicitly set. If so, might consider adding them as arguments to the sketchup plugin userscript. Ref: https://unmethours.com/question/21269/pv-shading-effect-on-thermal-loads-using-openstudio/

@macumber @jmarrec

**Comment by jmarrec** [comment]
This is by design, the `PhotovoltaicPerformance:Simple` doesn't care for Series/Parallel configuration since you're modeling a simple, fixed, efficiency.

Source: http://bigladdersoftware.com/epx/docs/8-6/input-output-reference/group-electric-load-center-generator.html#photovoltaic-generators

**Comment by jmarrec** [comment]
I also don't think that the Heat Integration mode is taken into account with this PVPerf:Simple object.

In the E+ [CalcSimplePV routine](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/Photovoltaics.cc#L775) there is no mention of the cell integration mode.
Compare that to the Sandia model for example [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/Photovoltaics.cc#L1007)

**Comment by eringold** [comment]
Thanks for the explainer @jmarrec!
