### ISSUE TITLE
 OpenStudio SketchUp 2016 crashed when opens

### ISSUE THREAD

**Issue by jcompostella** [NREL/OpenStudio#2397]
Hi, just installed OpenStudio SketchUp 2016. Every time I open it, it crashes. Can you help?

**Comment by macumber** [comment]
Reported at https://unmethours.com/question/21310/openstudio-sketchup-2016-crashes-every-time-i-open-the-tool/, let's have the conversation on unmethours in case others have input

**Comment by jcompostella** [comment]
Hi macumber, the error persists. Every time I open OpenStudio SketchUp 2016 crashes. Still cannot use the product. Could you please help?
