### ISSUE TITLE
After 0.10.0 release we need to look at naming of OnDemand SpaceTypes (Bugzilla #1006)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#240]
On 2012-12-13 12:58:46, @DavidGoldwasser wrote:

> Forgot to document this, we hit it in NGrid work. When we have very long names for loads and we have multiple types of the same object in a zone (such as task and general lighting, or blended space types), EnergyPlus has to concatenate the load name with the thermal zone name. Since the unique part of our name is at the end the names are duplicates when the get truncated, and this results in severe errors in the simulation. It still runs, but with incomplete data.
> 
> Our solution for Ngrid was to reverse the order of the elements that go into the name of the space so the unique elements are first. We can do that or we can abbreviate more (e.g. "qsr" for "QuickServiceRestaurant" in the object name.
> 
> Not a bug, but when we do update this may be nice to grab the thermostat schedules as well, and just drop them in the file (this is a hole in current workflow, users have to go back to templates to get this).
> 
> We also wrote a construction set wizard for Ngrid. The same inputs used to get OnDemand space types could make the construction set. This would almost replace the need to have pre-made templates at all. The current script uses a local OSM file for data, but there isn't any reason we can't do constructions similar to SpaceTypes. We could even pull from BCL constructions vs. making our own on the fly; may result in many duplicates of the same material though?

**Comment by asparke2** [comment]
Not relevant anymore b/c no on-demand space types
