### ISSUE TITLE
OS App crashes if turn on output variable and switch away from and back to output variable tab

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2400]

**Comment by Pinoquio1891** [comment]
I suggest the following two changes to resolve the bug:

--- a/openstudiocore/src/openstudio_lib/VariablesTabView.cpp
+++ b/openstudiocore/src/openstudio_lib/VariablesTabView.cpp
@@ -80,7 +80,8 @@ namespace openstudio {
       *m_variable,
       static_cast<std::string (*)(const std::string&)>(&openstudio::toString),
       // &model::OutputVariable::roughnessValues,
-      nullptr,
+      //nullptr,
+      std::bind(&model::OutputVariable::reportingFrequencyValues),
       std::bind(&model::OutputVariable::reportingFrequency, m_variable.get_ptr()),
       std::bind(&model::OutputVariable::setReportingFrequency, m_variable.get_ptr(), std::placeholders::_1),
       boost::none,

--- a/openstudiocore/src/shared_gui_components/OSConcepts.hpp
+++ b/openstudiocore/src/shared_gui_components/OSConcepts.hpp
@@ -522,13 +522,16 @@ class RequiredChoiceConceptImpl : public ChoiceConcept {
   virtual std::vector<std::string> choices() override {
     m_choicesMap.clear();
     std::vector<std::string> result;
-    std::vector<ChoiceType> typedChoices = m_choices();
-    for (typename std::vector<ChoiceType>::const_iterator typedChoice = typedChoices.begin();
-         typedChoice != typedChoices.end(); ++typedChoice)
+    if (m_choices != nullptr)
     {
-      std::string choice = m_toString(*typedChoice);
-      result.push_back(choice);
-      m_choicesMap.insert(typename std::map<std::string,ChoiceType>::value_type(choice,*typedChoice));
+        std::vector<ChoiceType> typedChoices = m_choices();
+        for (typename std::vector<ChoiceType>::const_iterator typedChoice = typedChoices.begin();
+            typedChoice != typedChoices.end(); ++typedChoice)
+        {
+            std::string choice = m_toString(*typedChoice);
+            result.push_back(choice);
+            m_choicesMap.insert(typename std::map<std::string, ChoiceType>::value_type(choice, *typedChoice));
+        }
     }

**Comment by macumber** [comment]
Thanks for the patch @Pinoquio1891 , didn't apply it directly since the formatting got messed up but I think you were correct in your suggestion.  Were your changes to OSConcepts.hpp meant to avoid crashes if nullptr was passed in for the choice function?  I didn't address anything like that.  In the future, please feel free to make pull requests directly, thanks again!
