### ISSUE TITLE
Is the E+ Ground Heat Exchanger:Slinky model present in Open Studio?

### ISSUE THREAD

**Issue by jcompostella** [NREL/OpenStudio#2404]
Is the E+ Ground Heat Exchanger:Slinky model present in Open Studio?

**Comment by MatthewSteen** [comment]
@jcompostella please use Unmet Hours for questions as described [here](https://github.com/NREL/OpenStudio/blob/develop/CONTRIBUTING.md). 

To answer your question it's not yet in the application or the [API](https://s3.amazonaws.com/openstudio-sdk-documentation/cpp/OpenStudio-1.13.0-doc/model/html/annotated.html). One would have to write an [EnergyPlus Measure](http://nrel.github.io/OpenStudio-user-documentation/reference/measure_writing_guide/#energyplus-measures) to add it to the IDF created by OpenStudio prior to simulation.
