### ISSUE TITLE
OS toolbar greyed out with .osm loaded (Bugzilla #1007)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#241]
On 2012-12-13 13:22:36, @rpg777 wrote:

> Created an attachment (id=243)
> example file
> 
> Had a user at the Portland training experience this. He's done a commendable job of documenting the bug, which I will simply copy in here. Here's his email, and I'll attach his files. (User's email: jpanoscha@speakeasy.net)
> 
> Hi Rob,
> 
> I enjoyed your OpenStudio seminar here in Portland last Friday.  I would
> like to follow up on some software problems I was having.  My OpenStudio
> toolbar was graying out in SketchUP during certain operations.  It seems
> like I am having communication or compatibility issues between SketchUP and
> OpenStudio.
> 
> The graying out first happens when I try to open an OpenStudio Template from
> the "New OpenStudio Model from Template" button.  I can not continue with
> OpenStudio after this.
> If I reopen SketchUp, I can begin to us the OpenStudio tools to build a
> model from scratch without using a template, and I can get as far into the
> exercise as inserting 'New Daylighting Controls" before I crash again.
> 
> Attached are the two test files I was working on during the seminar incase
> that helps.
> Test.osm crashed out right away.
> Example2.osm:  I was able to build the model with out loading a template.
> 
> Any ideas?
> 
> Thanks.
> 
> Juergen Panoscha
> 
> This is what I have installed,
> Laptop: HP Pavilion dv6 with Windows 7 Home Premium
> SketchUP: Google SketchUP V8.0.3117 Free version.  I have had this installed
> on the laptop for a year and a half.
> OpenStudio: V 0.9.5 Build 10372.  Installed last week.

On 2012-12-13 13:23:06, @rpg777 wrote:

> Created an attachment (id=244)
> 'nother example file

On 2012-12-17 09:39:43, @DavidGoldwasser wrote:

> There seem to be two issues here. One, is an issue with the templates not loading correctly. The other is the crash when working on a model. I don't really have any details on when the crash is happening. For the templates, I expect that either his template files have become corrupted, or he is pointed to a very old or newer version. (e.g. opening 0.9.6 template with 0.9.5)
> 
> I see his email and will follow up. I tested these on my machine with 0.9.5 on windows 7 with SU 8 and wasn't able to reproduce the problem.
> 
> Also I'm changing the bug from "Blocker" to "Normal". I'm expecting I may close it soon as "works for me", but do want to follow up with the user first. If it was just a configuration issue on his machine, and not something that happens with a clean install. The crash I'm sure is valid, but I need to see if I have steps to repeat it vs. a random crash.

Original attachments:
- example2.osm (ID 243)
- test.osm (ID 244)

**Comment by jmarrec** [comment]
Irrelevant today (no more "New model from template" in sketchup)
