### ISSUE TITLE
Add AvailabilityManager:HighTemperatureTurnOff and others for solar collector

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2410]
As noted in [this unmethours post](https://unmethours.com/question/21472/availability-managers-for-highlow-temperature-turn-off-in-os/), the example files for the solar collector objects use these 3 availability managers which aren't in OpenStudio:

- AvailabilityManager:HighTemperatureTurnOff
- AvailabilityManager:HighTemperatureTurnOn
- AvailabilityManager:DifferentialThermostat

These objects are poorly designed because they are the only AvailabilityManagers used on PlantLoops.

## Workarounds
 - Use an EnergyPlus Measure to add them
 - Use EMS (now available in OpenStudio SDK) to control them yourself

**Comment by asparke2** [comment]
@kbenne ugh.

**Comment by phylroy** [comment]
+1 for this.   Is there a sample EMS script that you guys have handy?

**Comment by jmarrec** [comment]
`AvailabilityManagerDifferentialThermostat` was implemented in ae66f40d6f95a5c8b67b388726d193e348f7714f
