### ISSUE TITLE
"Ground Heat Exchanger : Vertical" with "water-to-water heat pump-cooling" - bad in/out ground temperature only for 2nd plant loop

### ISSUE THREAD

**Issue by ebotman** [NREL/OpenStudio#2412]
**HVAC Plant loops configurations:**
- plant loop 1: "ground heat exchanger: vertical"  + "constant speed pump" + "Heat Pump:Water to Water: Equation fit: Cooling"  for cooling a simple box +  "Coil Cooling Water"
- plant loop 2: Identical configuration with "ground heat exchanger: vertical"  + "constant speed pump" + "Heat Pump:Water to Water: Equation fit: Cooling"  for cooling a other simple box +  "Coil Cooling Water"

**Results:** Ground Heat Exchanger Inlet and Outlet temperatures are ok for plant loop 1

**Problem**: Ground Heat Exchanger Inlet and Outlet temperatures are NOT OK for plant loop 2. The Outlet temperature goes below the ground temperature, which is abnormal.

All the parameters are exactly the same for the 2 vertical bore fields, and for the 2 heat pumps. 
When I link the 2 heat pumps to the plant loop 1, it's ok, When I link the 2 heat pumps to the plant loop 2, it goes wrong. I chechek if there could be a swap between Input nodes and Output nodes, either for the ground exchanger, either for the heat pumps, all seems to be ok. 

At this time, I suspect the 2nd column of GroundHeatExchanger:Vertical objects. Do you have some more ideas for further investigations ? 

Is this a known issue ? 

OS 1.13.0 build "fb588cc683"  -  EP 8.6.0 - Windows 7 pro

Thanks for your help,

**Comment by asparke2** [comment]
Might be related to https://github.com/NREL/OpenStudio/issues/2412

**Comment by ebotman** [comment]
I
 don't think so, the first vertical bore hole
 works fine, only the secund one present a
 bad result. 
Can you let me know how in which direction
 investigate the issue.

 >>  Might be related
 to #2412

 --------------------
Energy Village sprl - Bureau d'études
 - Bureau d'Etudes spécialisé
 en énergétique du bâtiment,
 en efficacité énergétique
 industrielle et en énergies renouvelables
Energy Village Installations sprl - Installations
 techniques pour batiments performants
Place Vandervelde, 7 
B - 7370 DOUR
BELGIUM 
Email: etienne.botman@energy-village.be
www:
 http://www.energy-village.be
 
GSM: +32 485 705 867 
Tel: +32 65 69 15 60
N° entreprise: BE 0824.008.169
http://www.energy-village.be/images/EV_docs/Disclaimer.txt
 
----------------------- Original Message
 -----------------------

**Comment by jmarrec** [comment]
Closing, this is both stale and probably a modeling error or EnergyPlus issue.
