### ISSUE TITLE
Can't assign CoilHeatingElectric to ZoneHVACFourPipeFanCoil

### ISSUE THREAD

**Issue by LyleKeck** [NREL/OpenStudio#2413]
Both the ZoneHVACFourPipeFanCoil constructor and the method .setHeatingCoil won't assign CoilHeatingElectric as heating coil.  Works fine with CoilHeatingWater, but not CoilHeatingElectric.

**Comment by eringold** [comment]
So I think https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/ZoneHVACFourPipeFanCoil.cpp#L678 needs to be 

    if( heatingCoil.iddObjectType() == IddObjectType::OS_Coil_Heating_Water || heatingCoil.iddObjectType() == IddObjectType::OS_Coil_Heating_Electric )

which is [allowed](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/resources/model/OpenStudio.idd#L21605) in the Idd. 

Hat tip @MatthewSteen

**Comment by eringold** [comment]
And probably a similar OR addition here: https://github.com/NREL/OpenStudio/blob/5bf588f92e207cee5a2bc7ef8c9f939d29c0188a/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACFourPipeFanCoil.cpp#L173

**Comment by kbenne** [comment]
@MatthewSteen is correct. Do you want to make the change or me?

**Comment by eringold** [comment]
@kbenne, @LyleKeck was saying on slack that this kind of blocking his work. While I do want to start contributing real commits, I don't really have the availability to dive in right now. Maybe @MatthewSteen or @LyleKeck want to give it a shot. 

I just wanted to make sure there isn't anything else that needed changing.

**Comment by kbenne** [comment]
Ok well it is my job. I'll push up a commit today and I'll jump on the slack channel and see how we can best deliver a fix quickly.

**Comment by asparke2** [comment]
Confirmed that this is fixed in [the code](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACFourPipeFanCoil.cpp#L177-L180).
