### ISSUE TITLE
Life cycle analysis length does not accept value greater than 25

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/OpenStudio#2417]
The Analysis Length (Years) field on the the Life Cycle Costs tab changes to 25 if values over 25 are entered. EnergyPlus can accept longer analysis lengths so this field should support more than 25 years.

https://unmethours.com/question/21776/how-can-i-change-analysis-length-in-life-cycle-costs-to-50-years/

**Comment by JasonGlazer** [comment]
Just realized that it needs to be on "custom"

**Comment by JasonGlazer** [comment]
Even on "custom" the value for Analysis Length does not accept value greater than 30.

**Comment by DavidGoldwasser** [comment]
@macumber I confirmed that 1.13.0 accepted any integer (negative or any positive). the valued options in EnergyPlus are 1 to 100. As @JasonGlazer found 1.14.0 is limited between 1 and 30 years.

Here is filed description from EnergyPlus idd.

`   N6,  \field Length of Study Period in Years
        \type integer
        \minimum 1
        \maximum 100
        \note Enter the number of years of the study period. It is the number of years that the study continues
        \note based on the start at the base date. The default value is 25 years. Only integers may be used
        \note indicating whole years.`

**Comment by DavidGoldwasser** [comment]
Confirmed that 2.0 is also affected by this.

**Comment by macumber** [comment]
It's not an IDD issue:

    N6, \field Length of Study Period in Years
       \note Enter the number of years of the study period. It is the number of years that the study continues
       \note based on the start at the base date. The default value is 25 years. Only integers may be used
       \note indicating whole years.
       \type integer
       \default 25
       \minimum 1
       \maximum 100

**Comment by macumber** [comment]
Here is the code that seems to be involved, https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/LifeCycleCostParameters.cpp#L559

It looks like we are preventing analysis periods > 25 years if we are using FEMP assumptions, and > 30 years if you are using NIST fuel escalation rates.  If you turn FEMP and NIST assumptions off you can enter your own data.  I guess this is as designed.

**Comment by JasonGlazer** [comment]
Yes, the maximum number of years in EnergyPlus is 100 although that is kind of arbitrary. I have heard of life cycle cost analyses using 40 or 50 years but that is about the most I have heard of, so I doubled it to 100 just to be conservative but I am not sure that the impact of the 100th year would ever be significant.

**Comment by macumber** [comment]
We implemented this logic because FEMP and NIST both put limits on their assumptions, e.g. NIST provides fuel escalation rates to use for 30 yr analysis but they don't make any assumptions about beyond that

**Comment by JasonGlazer** [comment]
Makes sense. It would be nice if the GUI hinted at the reason for the 25 or 30 year limit somehow.
