### ISSUE TITLE
Scripts do not default to the entire building option Label: Component-OS App  severity - Minor Bug

### ISSUE THREAD

**Issue by gokmartian** [NREL/OpenStudio#2418]
![problem1](https://cloud.githubusercontent.com/assets/22801677/21525438/83d22162-ccda-11e6-9c07-10c3904853d9.JPG)
Encountered this bug for certain BCL scripts when running them in OS 1.14.0, which have the option to apply the measure to the entire building (Entire Building) or Space Types (All Space Types):  
The dropdown field in the image is arranged alphabetically, but it defaults to the entire building. If I run the script as is, it sets an LPD of 1 W/sf to the entire building, even though it shows that it applies only to spaces with the Apartment Space Type. If I scroll down once and click on any of the options, it works fine. This looks confusing. Can the functionality be changed so that it displays the Entire building option as the default too, like the previous version? Thanks.

**Comment by DavidGoldwasser** [comment]
@gokmartian, thanks again for your help. @macumber this also happens on 1x PAT, and 2x OS app, but not on 2x PAT. I also don't see it on string choice list like WWR measure. It correctly sets the default value defined in the measure arguments method. I looked at this measure to see that it it has a default and also tested on other measures with the same results.
