### ISSUE TITLE
PAT 1.14.0 issue, results are deleted when project is opened

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2419]
I confirmed on mac what UH user posted. This isn't a 1.13 to 1.14 transition issue. Happens with fresh 1.14.0 files.
https://unmethours.com/question/21807/pat-1140-deletes-old-results-on-reopening-project-file/

Steps to reproduce:

1. Create a new PAT project and set seed file.
2. Add a measure and create one or more design alternatives (this is probably optional step)
3. Run Analysis
4. Look at results page (to confirm you can see results)
4. Quit PAT (look and confirm that datapoint directories still exist)
5. Re-launch PAT and load the project
6. At this point, the datapoint directories are gone and if you go to the results page the data is gone there.

**Comment by macumber** [comment]
@DavidGoldwasser can you replace the measure.xml for the StandardReports measure in your 1.14 install with the measure.xml in my last commit and see if that fixes your issue?

**Comment by macumber** [comment]
Ps you may need to synch measures with your project, basically pat thinks the measure changed so it deletes results

**Comment by snlavu** [comment]
Will syncing measures work with PAT 1.14 to fix this issue?

**Comment by macumber** [comment]
Syncing will only work if you fix the measure.xml for the standard reporting measure in your OpenStudio install first, for me this is at:

C:\Program Files\OpenStudio 1.14.0\share\openstudio-1.14.0\pat\Measures\StandardReports

**Comment by DavidGoldwasser** [comment]
@macumber looks good. Tested without 1H admin.

**Comment by snlavu** [comment]
I am not sure how this fix works. Could you elaborate what is to be done in
the measure.xml file?

**Comment by macumber** [comment]
Now that David verified the fix we will create new patched installers.  I would suggest waiting for those and simply reinstalling.
