### ISSUE TITLE
OpenStudio 2.0.0 GbXMLReverseTranslator > The type initializer for 'OpenStudio.OpenStudioGBXMLPINVOKE' threw an exception.

### ISSUE THREAD

**Issue by mostaphaRoudsari** [NREL/OpenStudio#2421]
@macumber I think this is happening for a very similar reason as this one #2371 and there is a dependency which is not available. I can create OpenStudio.Model with no issues.

```python
import OpenStudio as ops
translator = ops.GbXMLReverseTranslator()
```

**Comment by macumber** [comment]
Hmm, can you initialize the EnergyPlusForwardTranslator or EnergyPlusReverseTranslator?

**Comment by macumber** [comment]
I am able to reproduce this by running the following code with IronPython:

`import sys
import clr
sys.path.insert(0, r'C:\Program Files\OpenStudio 2.0.0\CSharp\openstudio')
#clr.AddReferenceToFileAndPath(r'C:\Program Files\OpenStudio 2.0.0\CSharp\openstudio\openstudio_csharp.dll')
#clr.AddReferenceToFileAndPath(r'C:\Program Files\OpenStudio 2.0.0\CSharp\openstudio\openstudio_translators_csharp.dll')
clr.AddReferenceToFileAndPath(r'C:\Program Files\OpenStudio 2.0.0\CSharp\openstudio\OpenStudio.dll')

import OpenStudio
model = OpenStudio.Model();
print model;

translator = OpenStudio.GbXMLReverseTranslator();
print translator;`

@kbenne I think this has to do with breaking openstudio_translators_csharp.dll out to its own dll, I don't think OpenStudio.dll knows how to properly load both openstudio_csharp.dll and openstudio_translators_csharp.dll.  Maybe we should break out a separate OpenStudioTranslators.dll that would pair with openstudio_translators_csharp.dll?

**Comment by macumber** [comment]
@mostaphaRoudsari if you can explicitly load the native dll openstudio_translators_csharp.dll using the clr or sys libraries that might work too.

**Comment by mostaphaRoudsari** [comment]
@macumber thank you for checking this issue. Trying to add `openstudio_translators_csharp.dll` or `openstudio_csharp.dll` gives me this error.
`Runtime error (BadImageFormatException): The module was expected to contain an assembly manifest. (Exception from HRESULT: 0x80131018)`

**Comment by kbenne** [comment]
I think I know where to start digging on this and I will investigate today. @mostaphaRoudsari have you tried using the idf translator? I have tested this from C# and believe it is working so I'm hoping that it is the gbxml translator in particular that is messed up.

**Comment by kbenne** [comment]
I see now. It looks like I never moved my commit for this over from the 2.0 branch. This is what we need https://github.com/NREL/OpenStudio/commit/9995a940386e9c8019bc56908905c6f9a4bea079.

**Comment by mostaphaRoudsari** [comment]
Hi @kbenne! Thanks for checking this. When do you think these changes will be merged? Let me know if you still want me to test the idf translator. I haven't checked it with the version 2.0.0

**Comment by kbenne** [comment]
I just merged to develop so at minimum it will be in our next iteration package.

**Comment by chriswmackey** [comment]
@kbenne , @macumber , and @mostaphaRoudsari ,

I have just checked the EnergyPlus translators and I have the same issue with a PINVOKE error:
https://github.com/NREL/OpenStudio/issues/2426

@kbenne , let us know when there is a compiled version with your fixes and we can test it on all of the translators.

-Chris

**Comment by mostaphaRoudsari** [comment]
@macumber @kbenne I just test this with version 2.0.2 and it works fine! Thanks you for the fix.

**Comment by chriswmackey** [comment]
Awesome!  I'll check the IDF translators now.

**Comment by chriswmackey** [comment]
IDF translators are also working!
