### ISSUE TITLE
Import gbXML doesn't import construction for subsurfaces

### ISSUE THREAD

**Issue by mostaphaRoudsari** [NREL/OpenStudio#2423]
Both fenestration surfaces and shading surfaces are imported with no construction.

![image](https://cloud.githubusercontent.com/assets/2915573/21536123/6b6daf0c-cd4c-11e6-8b05-37fa668a20db.png)

I used OpenStudio gbXML exporter to create the file, and it might be an issue with the exporter not writing the constructions to xml correctly.

**Comment by macumber** [comment]
Thanks @mostaphaRoudsari can you post a gbXML file here?  I had done some work with window constructions but there are several different ways they can be represented in gbXML

**Comment by mostaphaRoudsari** [comment]
Here it is: [seb.txt](https://github.com/NREL/OpenStudio/files/678116/seb.txt). I renamed it to txt to be able to upload it.

**Comment by DavidGoldwasser** [comment]
@mostaphaRoudsari I was able to import gbXML with sub-surfaces with constructions and materials. When I tried your gbXML there was a construction associated with the sub-surface, but it doesn't have any materials. Looking them side by side below, maybe the missing visible Transmittance value on your window is creating the issue?

As a note, about mine on the right, it comes in as simple glazing, using the first of the SolarHeatGainCoeff values.

<img width="1622" alt="screen shot 2018-08-16 at 2 22 52 pm" src="https://user-images.githubusercontent.com/4857055/44233238-854abc00-a160-11e8-8f54-cd8bc64050dd.png">

**Comment by jasondegraw** [comment]
I was not able to reproduce this issue, and there is now a passing unit test for the ReverseTranslator:

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/gbxml/Test/ReverseTranslator_GTest.cpp#L154

It's named `ReverseTranslator_SubSurfaceConstructions` for when the link goes stale.

**Comment by mostaphaRoudsari** [comment]
Thanks @jasondegraw and @DavidGoldwasser. I haven't checked gbXML importer recently. @chriswmackey do we have any issues related to subsurfaces?
