### ISSUE TITLE
Unable to run OpenStudio.App from Sketchup on Mac (OS 2.0.0)

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2427]
System info:

* Sketchup 2016
* macOS Sierra 10.12.2
* OpenStudio 2.0.0 (47ba3cbe19)

----

I cannot launch OpenStudio App from sketchup

I see it’s trying to do it, in the ruby console but it fails:

```
open -a "/usr/local/openstudio-2.0.0/bin//OpenStudioApp.app" --args "/Users/julien/Documents/OpenStudio-Test/model.osm"
```
If I run that into a terminal:

> FSPathMakeRef(/usr/local/openstudio-2.0.0/bin//OpenStudioApp.app) failed with error -43.

This is the right call it should make (no `bin/` subdirectory)

```
open -a "/usr/local/openstudio-2.0.0/OpenStudioApp.app" --args "/Users/julien/Documents/OpenStudio-Test/model.osm"
```

**Comment by macumber** [comment]
Relevant line:

https://github.com/NREL/OpenStudio/blob/72e4961a2d6547dcb40be48f722345b5691e3a74/openstudiocore/sketchup_plugin/openstudio/sketchup_plugin/lib/MenuManager.rb#L570
