### ISSUE TITLE
PAT on mac launches 5 instances of Ruby

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2430]
System info:

* Sketchup 2016
* macOS Sierra 10.12.2
* OpenStudio 2.0.0 (47ba3cbe19)

----

I’m wondering why PAT launches 5 instances of ruby with 250-300MB when I’m really not doing anything at the moment. The ruby instances get launched only after I create a new project. "Starting local server" is displayed and over the course of a couple minutes each instance is spun after the next (they get initialized with about 50 MB memory and then ramp quickly up to ~250 MB).

I'm having trouble seeing why 5 instances are needed when I'm not doing anything (just waiting on the first tab)

**Comment by kbenne** [comment]
Those are the worker processes being launched based on how many processor cores you have. As you observed, the software is currently designed to start the workers when you create or load a new project. One positive side effect of this is that the workers can be spinning up while you are building your project and then they are ready when you click the run button.

**Comment by jmarrec** [comment]
I have 2 CPUs,  4 threads. Technically It should spin off 4-1 = 3 ruby instances:

https://github.com/NREL/OpenStudio-PAT/blob/faf75639c4460239a10cca4633448061729d3ac2/app/app/project/osServerService.js#L24

```
// set number of workers
    vm.numCores = os.cpus().length;
    vm.numWorkers = 1;
    if (vm.numCores) {
      vm.numWorkers = vm.numCores == 1 ? 1 : (vm.numCores - 1);
}
```
Shouldn't I have 3 ruby instances?

**Comment by rHorsey** [comment]
Two of those processes are rails and the analysis / background queue, each of which constitute a separate ruby process. As such, the number of worker processes is actually the total number of ruby processes minus 2.

**Comment by jmarrec** [comment]
@rHorsey thanks. Would you mind quickly pointing me to the source code location where it spins both of them?

**Comment by rHorsey** [comment]
My pleasure! The shell commands are created in these lines: https://github.com/NREL/OpenStudio-server/blob/dockerize-master/bin/resources/local.rb#L194-L206 and executed in these: https://github.com/NREL/OpenStudio-server/blob/dockerize-master/bin/resources/local.rb#L216-L296 . Each is in turn executed by the scripts in this folder: https://github.com/NREL/OpenStudio-server/tree/dockerize-master/bin/resources/local -- does that help at all?

**Comment by jmarrec** [comment]
I was trying to pinpoint the moment in the OpenStudio-PAT appication where it does that. I can't figure it out, but I guess it doesn't matter that much.

(There's this mention of railsDir, but it isn't used anywhere that I can find using github: https://github.com/NREL/OpenStudio-PAT/blob/47a5ce785443c0e7d873864f59388bc371d7ae5b/app/app/project/projectService.js#L84)

**Comment by jmarrec** [comment]
Thanks for the clarifications. I guess at some point I'd like for the number of workers to be customizable (have an option "Auto" or "X workers")
