### ISSUE TITLE
PAT unable to reopen 2.0.0 project on Mac

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2431]
System info:

* Sketchup 2016
* macOS Sierra 10.12.2
* OpenStudio 2.0.0 (47ba3cbe19)

----

If I try to Open a new project, I can't select any file to open it. I assume the `pat.json` should be the one?

![screen shot 2017-01-09 at 13 29 04](https://cloud.githubusercontent.com/assets/5479063/21766582/a5796fac-d66f-11e6-80d4-f24c1becc72c.png)

**Comment by kbenne** [comment]
This might need a design revision, but currently PAT expects you to select the directory containing pat.json, not the json file directly.

**Comment by jmarrec** [comment]
Hum, I guess I was still too used to the 1.x way of using the `.osp` file. It does work when I select the folder. Not very intuitive **to me**, but I understand the logic. This would mean allowing selection of all `.json` files, or maybe all `pat.json` files would work. Then it'd be simple to allow selecting a folder or pat.json, check if a folder was selected, if it's a file use parent directory or something.

Not critical per se anyways. Not sure if we leave that open or close it. Maybe you could tag it as "low priority" or something if you think it's worth pursuing down the road

**Comment by DavidGoldwasser** [comment]
I do think if you have a file selected that it would behave as if it has the parent directory selected. I agree isn't intuitive.
