### ISSUE TITLE
OS 2.0 on mac shows up a second, bouncing, icon when on Results tab

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2436]
System info:

* Sketchup 2016
* macOS Sierra 10.12.2
* OpenStudio 2.0.0 (47ba3cbe19)

----

In OS 2.0.0 on Mac, when you go to the Results tab, there’s a second OS icon that just keeps on bouncing in your dock.

It happens whether you load a model or not, and disappears once you move to another tab.

![screen shot 2017-01-10 at 13 14 57](https://cloud.githubusercontent.com/assets/5479063/21813874/e130b1c0-d757-11e6-91d4-052a59b5dd43.png)

**Comment by kbenne** [comment]
@jmarrec can you test again? I'll send you a build on Slack.

**Comment by jmarrec** [comment]
I still have a bouncing icon (and an model build on 2.0.0 doesn't run, yet it bounces on the results tab (nothing to show...))
