### ISSUE TITLE
HTML report formatting messed up in OS App 2.0.0

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2438]
The reports tab in the OS App 2.0.0 renders the reports poorly.  Notice the red scroll bars.

This is what the EnergyPlus html file looks like:

![image](https://cloud.githubusercontent.com/assets/2009290/21827538/55465f7e-d749-11e6-8061-2cf4119ff006.png)

This is OpenStudio Results (screenshot from user):

![os_results_formatting](https://cloud.githubusercontent.com/assets/2009290/21827571/7e3863d2-d749-11e6-88a1-ef030470f0d7.jpg)

**Comment by ljbrackney** [comment]
Not disagreeing that Andrew's seeing this on Windows, but both reports render fine on MacOS.

**Comment by padmassun** [comment]
Also have same issue.

Windows 7 64 bit
Installed from OpenStudio-2.0.0.47ba3cbe19-Windows.exe
SketchUp 2016

**Comment by macumber** [comment]
Michael Deru just reported the same

**Comment by DavidGoldwasser** [comment]
@macumber, I did just confirm in 2.0.3 that this only affects the OpenStudio app in 2.x.

PAT 2.x renders OpenStudio and EnergyPlus reports fine.

**Comment by chrisbalbach** [comment]
Still happening in OS Application (installation v2.0.4 Windows release) from Github. 
Renderings (of any report) in the Results Summary Tab is unusable, while the underlying HTML files are entirely viewable when opened in a native browser (tested chrome and firefox).

**Comment by ljbrackney** [comment]
This has been addressed in 2.0.5.

**Comment by macumber** [comment]
Figured out the problem, we need to install WebEngine resources on Windows:

https://doc.qt.io/qt-5/qtwebengine-deploying.html#deploying-resources

![3-18-2017 4-53-22 pm](https://cloud.githubusercontent.com/assets/1327850/24076647/bd9ea2b6-0bfb-11e7-8be1-6967c7190127.png)

**Comment by macumber** [comment]
@kbenne FYI
