### ISSUE TITLE
XP specific Radiance problem (Bugzilla #1012)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#244]
On 2012-12-21 10:52:11, @DavidGoldwasser wrote:

> I ran the InstallationTest.osm file on an XP non dev machine with OpenStudio 0.10.0.
> 
> It ran through fine with radiance with the simulation appears to finish, but doesn't seem to show any daylight in the building. Below is typical output for each day in the simulation.
> 
> 
> Radiance (rcontrib) calculating: 1 16 00:00:00
> Radiance (rcontrib) calculating: 1 16 01:00:00
> Radiance (rcontrib) calculating: 1 16 02:00:00
> Radiance (rcontrib) calculating: 1 16 03:00:00
> Radiance (rcontrib) calculating: 1 16 04:00:00
> Radiance (rcontrib) calculating: 1 16 05:00:00
> Radiance (rcontrib) calculating: 1 16 06:00:00
> Radiance (rcontrib) calculating: 1 16 07:00:00
> Radiance (rcontrib) calculating: 1 16 08:00:00
> ERROR: simulation command generated no results: gendaylit -ang 1.97959842242689 -58.8943230432234 -L 1324.42209513165 2495.57300641036 | perl "C:/Program Files/Radiance/bin\..\bin\genskyvec.pl" -m 2  | dctimestep ./output/dc/merged_space/maps/merged_space.dmx | rcalc -e "$1=179*($1*0.265+$2*0.67+$3*0.065)"
> INFO: simulation command generated no results, stuffing with 0's
> Radiance (rcontrib) calculating: 1 16 09:00:00
> ERROR: simulation command generated no results: gendaylit -ang 10.9258846027151 -48.0553738046673 -L 9194.88524251145 10145.6206358202 | perl "C:/Program Files/Radiance/bin\..\bin\genskyvec.pl" -m 2  | dctimestep ./output/dc/merged_space/maps/merged_space.dmx | rcalc -e "$1=179*($1*0.265+$2*0.67+$3*0.065)"
> INFO: simulation command generated no results, stuffing with 0's
> Radiance (rcontrib) calculating: 1 16 10:00:00
> ERROR: simulation command generated no results: gendaylit -ang 18.3676418105794 -35.8012557462888 -L 14027.7906340373 15948.6039639181 | perl "C:/Program Files/Radiance/bin\..\bin\genskyvec.pl" -m 2  | dctimestep ./output/dc/merged_space/maps/merged_space.dmx | rcalc -e "$1=179*($1*0.265+$2*0.67+$3*0.065)"
> INFO: simulation command generated no results, stuffing with 0's
> Radiance (rcontrib) calculating: 1 16 11:00:00
> ERROR: simulation command generated no results: gendaylit -ang 23.7497248281376 -21.9638575090757 -L 3212.511017717 16801.752866818 | perl "C:/Program Files/Radiance/bin\..\bin\genskyvec.pl" -m 2  | dctimestep ./output/dc/merged_space/maps/merged_space.dmx | rcalc -e "$1=179*($1*0.265+$2*0.67+$3*0.065)"
> INFO: simulation command generated no results, stuffing with 0's
> Radiance (rcontrib) calculating: 1 16 12:00:00
> ERROR: simulation command generated no results: gendaylit -ang 26.5215812970404 -6.82993408560458 -L 17596.3659391991 20831.1313244393 | perl "C:/Program Files/Radiance/bin\..\bin\genskyvec.pl" -m 2  | dctimestep ./output/dc/merged_space/maps/merged_space.dmx | rcalc -e "$1=179*($1*0.265+$2*0.67+$3*0.065)"
> INFO: simulation command generated no results, stuffing with 0's
> Radiance (rcontrib) calculating: 1 16 13:00:00
> ERROR: simulation command generated no results: gendaylit -ang 26.3326125646739 8.77204201860027 -L 51378.310720595 17568.8461034724 | perl "C:/Program Files/Radiance/bin\..\bin\genskyvec.pl" -m 2  | dctimestep ./output/dc/merged_space/maps/merged_space.dmx | rcalc -e "$1=179*($1*0.265+$2*0.67+$3*0.065)"
> INFO: simulation command generated no results, stuffing with 0's
> Radiance (rcontrib) calculating: 1 16 14:00:00
> ERROR: simulation command generated no results: gendaylit -ang 23.2084237740735 23.7789732855799 -L 44709.1300591738 16189.9765452611 | perl "C:/Program Files/Radiance/bin\..\bin\genskyvec.pl" -m 2  | dctimestep ./output/dc/merged_space/maps/merged_space.dmx | rcalc -e "$1=179*($1*0.265+$2*0.67+$3*0.065)"
> INFO: simulation command generated no results, stuffing with 0's
> Radiance (rcontrib) calculating: 1 16 15:00:00
> ERROR: simulation command generated no results: gendaylit -ang 17.5366122317025 37.4224422278727 -L 15108.5762723075 14567.7325618883 | perl "C:/Program Files/Radiance/bin\..\bin\genskyvec.pl" -m 2  | dctimestep ./output/dc/merged_space/maps/merged_space.dmx | rcalc -e "$1=179*($1*0.265+$2*0.67+$3*0.065)"
> INFO: simulation command generated no results, stuffing with 0's
> Radiance (rcontrib) calculating: 1 16 16:00:00
> ERROR: simulation command generated no results: gendaylit -ang 9.8774656888365 49.4833048198452 -L 6811.20771983671 8076.80646311502 | perl "C:/Program Files/Radiance/bin\..\bin\genskyvec.pl" -m 2  | dctimestep ./output/dc/merged_space/maps/merged_space.dmx | rcalc -e "$1=179*($1*0.265+$2*0.67+$3*0.065)"
> INFO: simulation command generated no results, stuffing with 0's
> Radiance (rcontrib) calculating: 1 16 17:00:00
> ERROR: simulation command generated no results: gendaylit -ang 0.777659702159811 60.1706929778419 -L 727.312004026663 1811.79595963327 | perl "C:/Program Files/Radiance/bin\..\bin\genskyvec.pl" -m 2  | dctimestep ./output/dc/merged_space/maps/merged_space.dmx | rcalc -e "$1=179*($1*0.265+$2*0.67+$3*0.065)"
> INFO: simulation command generated no results, stuffing with 0's
> Radiance (rcontrib) calculating: 1 16 18:00:00
> Radiance (rcontrib) calculating: 1 16 19:00:00
> Radiance (rcontrib) calculating: 1 16 20:00:00
> Radiance (rcontrib) calculating: 1 16 21:00:00
> Radiance (rcontrib) calculating: 1 16 22:00:00
> Radiance (rcontrib) calculating: 1 16 23:00:00

Keywords: BadSimResults

**Comment by rpg777** [comment]
This behavior is better captured in other issues, most of which have been fixed, and the remaining cases are better documented in other issues.
