### ISSUE TITLE
PAT 2.0.0 won't launch on Windows 7 64-bit

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2440]
From a Windows 7 64-bit user:

> I just downloaded version 2.0, and when I try and open PAT I immediately get an error message saying that “OpenStudio Parametric Analysis Tool has stopped working”. The “problem details” provided by windows are as follows, in case that’s helpful:

```
Problem signature:
  Problem Event Name:                        APPCRASH
  Application Name:                             ParametricAnalysisTool.exe
  Application Version:                           1.2.8.0
  Application Timestamp:                     57906c11
  Fault Module Name:                          ParametricAnalysisTool.exe
  Fault Module Version:                        1.2.8.0
  Fault Module Timestamp:                  57906c11
  Exception Code:                                  80000003
  Exception Offset:                                0000000000310a6d
  OS Version:                                          6.1.7601.2.1.0.256.4
  Locale ID:                                             1033
  Additional Information 1:                  c94a
  Additional Information 2:                  c94a70d12ad6af7b2f10d473a407b6f5
  Additional Information 3:                  8008
  Additional Information 4:                  80082f01ada0e37c3d920128d7dd699f
```

This user also reported that the OpenStudio Application opens, but gives the message “Could not find or download OpenStudio Results Measure.”  This leads me to believe there may be a firewall in place that is blocking the download.

I have successfully used PAT 2.0.0 on Windows 7 64-bit myself, so I don't think it's a universal issue.

**Comment by kbenne** [comment]
This is the space in install path issue. https://github.com/NREL/OpenStudio/issues/2434
