### ISSUE TITLE
OS2.0 can't add BCL key

### ISSUE THREAD

**Issue by michaelderu** [NREL/OpenStudio#2441]
OS2.0 does not recognize my BCL auth key when copied from my BCL account. 
Windows 7.0

**Comment by eringold** [comment]
Ran into this as well in Windows 10, using an API v1.1 key:

![image](https://cloud.githubusercontent.com/assets/10799524/22629637/e67d64b2-eba6-11e6-9477-e52d1180ab8f.png)

**Comment by DavidGoldwasser** [comment]
@eringold did you see this today (or later in the week when BCL was down. Can you replicate this after first checking that BCL is up using web browser. Make sure no leading or trailing spaces on your key.

I was able to throw away my BCL directory and re-setup key in 2.0.1, but tat was on Mac, not on Windows 10. @asparke2 has the BCL key worked for you on Windows 7?

**Comment by eringold** [comment]
I did see it Sunday, but verified that BCL was up (had to log in to access my key). I also made sure there were no leading or trailing spaces. I also tried deleting the BCL directory, to no avail.

Just tried again now, got the same message.

**Comment by DavidGoldwasser** [comment]
@macumber any ideas on this? While @eringold is in WIndows 10 @michaelderu is on Windows 7.

**Comment by eringold** [comment]
@DavidGoldwasser @asparke2 
I just installed a fresh v2.0.1 on my work machine (Windows 7), and had BCL access right away (without entering a key). There are other v1.X installations on this machine that had already been connected to BCL.

My earlier comments were using my personal laptop that had a fresh Windows 10 installation on it, so no previous OS versions installed or connected to BCL. Tonight I'll try installing and connecting to BCL with v1.14 first, see if that helps.

**Comment by macumber** [comment]
With the recent BCL spottiness I'd just request that we check if this is working in 1.14.  If it works in 1.14 but not 2.0 at the same time then there is an issue.  Throwing away (or just temporarily renaming) the BCL directory is a good way to clear out previous keys and make sure you can start from scratch.

**Comment by ljbrackney** [comment]
I couldn't speak to Windows issues, but I blew away my BCL DB for a fresh install of 2.0 on Mac, entered my BCL key, and everything worked fine during my testing in December.  I've not had any trouble w/ iteration updates either.

**Comment by eringold** [comment]
Hmm. Well I just renamed the BCL folder (work machine; Win 7) and was able to connect with my key in v2.0.1. 

I'll try some things on Windows 10 tonight.

**Comment by eringold** [comment]
On Windows 10 machine, I was able to connect to BCL using v1.14.0. I remain unsuccessful with v2.0.0 or v2.0.1. Tried both purging the BCL folder and leaving it the same after connecting with v1.14. I can provide the components.sql files if that would help.

Also, I was able to access BCL content and download measures using PAT 2.0. I guess that does it's own thing, since it never asks for a key.

**Comment by macumber** [comment]
@michaelderu @eringold I have not been able to reproduce this.  We had been seeing issues with the BCL going down fairly often, it is possible that you were trying to set these keys when the BCL was down.  Have you had this problem anymore?  If you don't mind, copy the BCL directory in your user directory to a temporary location and try again?  That will require you to input your keys again.  Once you are done testing you can copy the old directory back.

**Comment by eringold** [comment]
@macumber I'll try again when I get home. I'm certain that I could access BCL from a browser when I was doing those tests.

**Comment by ljbrackney** [comment]
I routinely blow away my key to test that. I most recently verified it works with 2.0.5.

On Mar 13, 2017, at 11:03 AM, Dan Macumber <notifications@github.com<mailto:notifications@github.com>> wrote:


@michaelderu<https://github.com/michaelderu> @eringold<https://github.com/eringold> I have not been able to reproduce this. We had been seeing issues with the BCL going down fairly often, it is possible that you were trying to set these keys when the BCL was down. Have you had this problem anymore? If you don't mind, copy the BCL directory in your user directory to a temporary location and try again? That will require you to input your keys again. Once you are done testing you can copy the old directory back.

-

**Comment by eringold** [comment]
@macumber still no luck. Tried with 2.0.4, and with deleting the BCL directory.

**Comment by macumber** [comment]
No luck meaning it is not working?  If you are still having trouble can you write the steps you are following so I can try to reproduce?

**Comment by eringold** [comment]
On Windows 10 Home x64, starting with no OpenStudio installed, no BCL folder:

- Install OpenStudio 1.14.0, open app
- Enter key (Components and Measures -> Find Measures), successfully connect to BCL, the measure browse window comes up, I can download measures into BCL folder
- Copy BCL folder to another location

- Install OpenStudio v2.0.4, open app
- Components and Measures -> Find Measures
- Enter key (no trailing space), hit ok
- Get the 'BCL auth key is invalid' window. 

Comparing the components.sql created from 1.14 and 2.0.4, the 2.0.4 is missing the key (#MprodAuthKey?). I can send you these files.

**Comment by macumber** [comment]
Issue was missing ssleay32.dll and libeay32.dll files in /bin

The validateAuth key method is really lame, basically all it does it check that it can access the BCL, no authentication of the key occurs

**Comment by macumber** [comment]
This fix will not make 2.0.5, affected users can copy the dlls from an OpenStudio 1.x install

**Comment by eringold** [comment]
Thanks Dan!
