### ISSUE TITLE
Unable to edit Arguments for measures in PAT 2.0.0

### ISSUE THREAD

**Issue by padmassun** [NREL/OpenStudio#2443]
Hello,

I am using a measure from BCL "Set Window to Wall Ratio by Facade", and I am unable to edit "Window to Wall Ratio (fraction)", "Still Height (in)", and "Cardinal Direction". These have the values of '0.4', '30', and 'South' as default values respectively.

After checking the Variable checkbox, and double clicking the certain field, sometimes I am unable to edit the values.

Thanks.

Analysis set to Manual
Default Seed Model location and Default Weather File locations are chosen
Clicked on '+Add Measure' on the 'OpenStudio Measures tab'
Chose "Set Window to Wall Ratio by Facade" measure
Clicked on '+Add Measure Option'
The default values are shown here, and I am able to edit name and description of the measure option. After checking the Variable checkbox, and double clicking the certain field, sometimes I am unable to edit the values (Sometimes the drop-down menus don't work properly, and I am unable to change them, and (sometimes) the background of the cell turns blue-grey).

Windows 7 64 bit
Installed from OpenStudio-2.0.0.47ba3cbe19-Windows.exe
SketchUp 2016

**Comment by DavidGoldwasser** [comment]
This has been fixed in 2.0.3
