### ISSUE TITLE
Unable to run Local Simulation on PAT 2.0.0

### ISSUE THREAD

**Issue by padmassun** [NREL/OpenStudio#2447]
Hello,

Whenever I attempt to run a local simulation on PAT 2.0.0, the progress is stuck on "Starting Server." The server status shows a red X, and here is the following text from the 6th tab ('Server' with a cloud and OS icon):

Status: stopped
Type: local
URL: http://localhost:8080

Do I need to install [https://github.com/NREL/OpenStudio-server] in this PC to run this simulation? I am able to ping 'localhost' with cmd, but unable to ping 'localhost:8080' and 'http://localhost:8080'. 

So how do I start a local server for PAT?

Thank you.

Windows 7 64 bit
Installed from OpenStudio-2.0.0.47ba3cbe19-Windows.exe
SketchUp 2016

![image](https://cloud.githubusercontent.com/assets/24966493/22114618/272406fa-de38-11e6-902c-771933850bc9.png)

![image](https://cloud.githubusercontent.com/assets/24966493/22114640/395e620c-de38-11e6-8dea-6224e2a46d28.png)

**Comment by shorowit** [comment]
If you installed OpenStudio to the default location (in Program Files), you might try reinstalling it to a location that doesn't have spaces in the file path (like directly on C:\). I believe the issue you're seeing can result from this.

**Comment by ljbrackney** [comment]
It should start automatically, but takes a little bit of time.  A couple troubleshooting steps:


  1.  Open your task manager and verify that multiple (probably 5 or more depending on the number of cores you have) ruby processes and a single mongod process start in the background - those constitute the bulk of the server.
  2.  Once those are all running, you should be able to ping the server using the server tools options from the pulldown menu in PAT.
  3.  If you killed PAT or some of those processes via the task manager without letting PAT shutdown properly, you may find a file left over in your project directory named local_configuration.json.  With PAT not running, delete that file and try restarting PAT.

If those still don't work, please attach the contents of your project's logs directory and we'll debug further.

**Comment by macumber** [comment]
@ljbrackney @DavidGoldwasser can we close this?

**Comment by ljbrackney** [comment]
Yes

On Mar 6, 2017, at 4:54 PM, Dan Macumber <notifications@github.com<mailto:notifications@github.com>> wrote:


@ljbrackney<https://github.com/ljbrackney> @DavidGoldwasser<https://github.com/DavidGoldwasser> can we close this?

-
