### ISSUE TITLE
Crash when adding / removing Ruleset schedule to load definition in space types / loads

### ISSUE THREAD

**Issue by Pinoquio1891** [NREL/OpenStudio#2451]
Hi!
I observe somewhat random crashes when adding a ruleset schedules to loads in space types. The crash almost always occurs e.g. adding any default people defintion from the library and assigning default ruleset schedules to activity and occupation. Anyway sometime this still works, but further removing and adding schedules results 100% in a crash. I can reproduce this behavior for 2.0.0 and 2.0.0 and head/develop revision. 
The problem actually is in the assignment of the pixmap icon (OSLoadNamePixmapLineEdit.cpp, ~ line 80:
     auto pixmap = IconLibrary::Instance().findMiniIcon(m_modelObject->iddObjectType().value()); 
) due to the fact, that the modelObject is broken (not a null pointer though). If someone can give me further hints I'll try to fix it. The fact, that the crash is not 100% reproducible and that it sometimes does not occur while debugging the application might indicate sort of a race condition between qt and nano signal/slot system?
Cheers
Chris

**Comment by macumber** [comment]
Thanks for this really great report, I expect that your observation might be correct.  If you come up with a fix please feel free to make a pull request.  Also, feel free to introduce yourself with an email to openstudio@nrel.gov or join the unmethours slack channel, https://unmethours.com/question/11053/unmet-hours-slack-channel-chat/.

**Comment by macumber** [comment]
This appears to happen because the grid is doing a refresh/redraw but still reacting to the on change signal from the model object
