### ISSUE TITLE
Measure syncing issues

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#2453]
The following is a description of Measure oddities from Matt Leach. We can follow up with him if we need help reproducing.

There are problems with Measure syncing: (i) I keep having to sync the same measures even though nothing has changed; (ii) if I sync right after I just synced, OS still thinks that some of the same measures need to be synced again; (iii) it looks like it is possible to sync measures and then run without being forced to save, which means the updated measures never really updated (I had intermittent crashing which seemed to be related to this issue)

**Comment by ljbrackney** [comment]
I've had issues with measures showing as having updates in PAT 2.0.  When I try to sync, things get stuck on the update dialog.  The measure continues to show as having an available update.

**Comment by macumber** [comment]
Are these symptoms present when using one instance of OS App or PAT at a time?  Or are these symptoms related to having two separate measure managers watching the same directory at the same time?

**Comment by kbenne** [comment]
well after recent revelations about two measure managers accessing the same measure directory at the same time I started to wonder about that too @macumber. In Matt's case I'm 90% sure he only had a single app instance and no pats running. He hasn't generally been using Pat.

**Comment by ljbrackney** [comment]
I tend to leave both the App and PAT running at the same time.  I did spend a bit of time Friday morning trying to find some rhyme or reason to the weird measure manager behavior that I was noticing, which is a little different than Matt's.  The issue that I first spotted involved seeing NO measures available in the App.  I thought it might be a conflict between two instances trying to hit things at once, or possibly a race condition when trying to display things in the GUI before the manager process had fired up.  I've not been able to replicate things reliably, and restarting the app usually clears it up when it does happen.  I'll keep poking around...

**Comment by macumber** [comment]
Think some of this is due to the fact that you have to save your model after synching measures, the model does not show as out of date so this is really easy to miss, need to fix that

**Comment by macumber** [comment]
When I make a change to a measure, then click update, it correctly offers to update the measure.  When I click update again, it incorrectly detects a change and offers to update the measure again.  Clicking update a third time does not show any updates to the measure.

**Comment by macumber** [comment]
@ljbrackney if there are issues having to do with multiple measure managers running at the same time let's file those as separate bugs.
