### ISSUE TITLE
OS Results Measure Download

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#2454]
"When I open OS 2.0, it thinks for a long time and then gives be an error saying the OS Results Measure could not be found/downloaded.  Note that I am NOT connected to BCL." -- Matt Leach.

**Comment by macumber** [comment]
That sounds like expected behavior.  You should be able to download the os results measure from the bcl and it will stop doing this

**Comment by kbenne** [comment]
you can close this if you want.

**Comment by macumber** [comment]
Only thing I can think of is a qsetting that says "try to download measure in the future"?
