### ISSUE TITLE
Measure arguments display red when they shouldn't.

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#2456]
In the Measures tab, if a measure has required arguments (which are supposed to display in red text until specified), ALL of the arguments display in red.  Even after the required arguments are specified, the red text doesn't go away until clicking off and back

**Comment by eringold** [comment]
Not only that, but the measure will appear broken in Apply Measure Now, with mouseover text claiming 'undefined method' for (in one case) `OpenStudio::Ruleset::makeChoiceArgumentOfWorkspaceObjects`: 

![image](https://cloud.githubusercontent.com/assets/10799524/22942282/239c5852-f2a6-11e6-9d4e-55d31b750297.png)

Despite that, the measure will run correctly. Changing all arguments to not required makes everything look normal again.

**Comment by macumber** [comment]
@eringold these were actually two separate issues, but if you see anything else where a measure that worked in 1.14 does not work in 2.0 please let us know!

**Comment by macumber** [comment]
Closed in https://github.com/NREL/OpenStudio/pull/2504/commits/3291356ee9320a060c2f1744b153d9cbf9447a33
