### ISSUE TITLE
OS App Units missing on Materials and Internal Loads (except for people) in 2.0.1

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2457]
@kbenne I don't have 2.0.0 installed, so I can't confirm if this is new or not. Was not an issue in 1.14.0. 

cc @macumber

**Comment by DavidGoldwasser** [comment]
I did confirm this was also broken in 2.0.0. (on windows) and was fine in 1.14.0.

**Comment by kbenne** [comment]
I believe this is the root cause..

https://github.com/NREL/OpenStudio/commit/845e17c4eaa718b2032288266d0b4a73c3f9996d

**Comment by DavidGoldwasser** [comment]
Is there a pattern in what is done for People Definitions that can work elsewhere? or is implementing that just a lot of work. It would be a really big loss in 2x not to have units, I think even if we don't put them in 2.1 they have to go in soon after. I guess it is a matter of time and risk and what else has to be done for the release. We should decide something on this at iteration meeting tomorrow.

@asparke2 any thoughts, is it even an option not to have units working?

**Comment by macumber** [comment]
@kbenne and i are going to get this in the release, hopefully make 2.0.5 but will make 2.1 for sure

**Comment by macumber** [comment]
https://www.pivotaltracker.com/story/show/141187433

**Comment by macumber** [comment]
Noticing that space loads like electric equipment have fields 'Energy Per Space Floor Area', should be 'Watts Per Space Floor Area' or 'Power Per Space Floor Area'

**Comment by macumber** [comment]
@DavidGoldwasser can you test this?  I think it is closed.

**Comment by evanweaver** [comment]
See https://www.pivotaltracker.com/n/projects/134010/stories/141187433

Ticket accepted by David June 8 2017
