### ISSUE TITLE
WSHP, GSHP Plant loop temperatures 

### ISSUE THREAD

**Issue by snlavu** [NREL/OpenStudio#2458]
I have issues with getting the WSHP and GSHP to run successfully on the Open studio. After looking through the following blog(https://unmethours.com/question/20784/how-does-one-set-minimum-water-flow-rates-through-wahps/), my problem seems to be solved with making the

Constant; Heat pump Coil water flow mode 
in Energy plus input file and running it in Energy plus. 

Unfortunately, the above filed is not editable in OSM. Is there a fix on this issue with 1.14 version?

**Comment by jmarrec** [comment]
It seems that this field [Heat Pump Coil Water Flow Mode](http://bigladdersoftware.com/epx/docs/8-7/input-output-reference/group-unitary-equipment.html#field-heat-pump-coil-water-flow-mode-000) only exists for the `AirLoopHVAC:UnitaryHeatPump:WaterToAir` which isn't even implemented in OpenStudio.

So I assume you are you talking about [ZoneHVAC:WaterToAirHeatPump](http://bigladdersoftware.com/epx/docs/8-7/input-output-reference/group-zone-forced-air-units.html#field-heat-pump-coil-water-flow-mode-001), right?
