### ISSUE TITLE
objects display Node handles instead of names

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2460]
Observed in 1.14.0 for the following objects, but possibly occurs in more.

* GeneratorMicroTurbineHeatRecovery - FYI @jmarrec 
* HumidifierSteamElectric
* PipeIndoor
* PipeOutdoor

---

![image](https://cloud.githubusercontent.com/assets/8397034/22475096/255851e8-e79b-11e6-849f-37209ee70ddb.png)

![image](https://cloud.githubusercontent.com/assets/8397034/22475013/efbd9dea-e79a-11e6-8301-34713e2e9edf.png)

![image](https://cloud.githubusercontent.com/assets/8397034/22476466/c48b5c20-e79f-11e6-8af7-07bdd5528af3.png)

![image](https://cloud.githubusercontent.com/assets/8397034/22476481/d25de674-e79f-11e6-9050-fdd0e9239de9.png)

**Comment by eringold** [comment]
Also:

- ThermalStorage:Ice:Detailed (Inlet/Outlet Node Name)
- ThermalStorage:ChilledWater:Stratified (Use/Source Side Inlet/Outlet Node Name)
- TemperingValve (Inlet/Outlet Node Name)
- Water Heater Stratified (Use/Source Side Inlet/Outlet Node Name)

**Comment by MatthewSteen** [comment]
And...

* SolarCollectorFlatPlateWater
* SolarCollectorIntegralCollectorStorage

**Comment by eringold** [comment]
And:
- ZoneHVAC:UnitVentilator

**Comment by kbenne** [comment]
Yeah. generally we just hide these fields. That information is shown in the hvac layout diagram. I have noticed some of these fields creeping in too. 

There is a policy xml file that is used to hide fields like this.

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/openstudio_lib/library/OpenStudioPolicy.xml

**Comment by eringold** [comment]
@kbenne said via slack "a syntax error in the xml will halt the parsing"

Which I think is due to the lack of `<\POLICY>` line here: https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/openstudio_lib/library/OpenStudioPolicy.xml#L916

**Comment by jmarrec** [comment]
The current develop no longer has a `<\POLICY>` tag. Is it fixed in the OS App now?

**Comment by eringold** [comment]
In OS v2.2.0 this appears to be fixed.
