### ISSUE TITLE
Resultsviewer & Radiance in V2.0.x

### ISSUE THREAD

**Issue by Pinoquio1891** [NREL/OpenStudio#2465]
Hi!
I have been testing some more things in V2.0.0/1 and I found that neither the ResultsViewer nor Radiance and also the RadianceMeasure are included in the installer file.
Cheers
Chris

**Comment by ljbrackney** [comment]
Radiance will be back in 2.1.0 - that's being worked on right now.

ResultsViewer is being deprecated in favor of a new application called Dview.  I'm not currently sure when it will be showing up in an installer.

**Comment by asparke2** [comment]
Until DView is ready, we need to keep packaging ResultsViewer.  We can't not ship anything to look at detailed results.

@kbenne @ljbrackney FYI

**Comment by kbenne** [comment]
https://github.com/NREL/OpenStudio/pull/2513
