### ISSUE TITLE
No gbXMLtoIdf.exe file is generated anymore

### ISSUE THREAD

**Issue by ehsankamel** [NREL/OpenStudio#2466]
It seems the "gbxmltoidf.exe" file is not being generated anymore. Is there any reason for removing it from CMakeLists.txt files? 
@macumber

**Comment by macumber** [comment]
We weren't aware of anyone using this executable and the functionality could be easily wrapped into openstudio.exe, was this a program you were using?

**Comment by ehsankamel** [comment]
Do you mean "openstudio.exe" or "openstudioapp.exe" ? I didn't know if I could use the gbxmltoidf functionality in openstudio.exe and I don't know how. 

I was going to use this program in another software package that I am developing for my dissertation in order to eliminate the need for running openstudioapp.exe and to automate the whole process. That's why I need an executable file that can be run directly to convert gbXML to IDF.

So, should I simply edit the CMakeLists.txt files to bring it back or you have other suggestions? 

I appreciate your help @macumber

**Comment by macumber** [comment]
I would not want to bring that program back.  Instead we can add options to openstudio.exe which is a command line tool that can be run in an automated way.  What is your complete workflow?  openstudio.exe 's main purpose is running simulation workflows that can involved applying OpenStudio Measures.  You could also write a measure to convert a gbXML to IDF, or pretty much anything you would like to do.

**Comment by macumber** [comment]
This is actually a perfect application for [openstudio.exe](http://nrel.github.io/OpenStudio-user-documentation/reference/command_line_interface/).  

You would create a workflow (OSW) file with two measures.  The first measure is a Model measure and takes an input which is the file name or path to the gbXML file, that measure would load the gbXML into OpenStudio format.  It would then run EnergyPlus (you can configure openstudio.exe to use your custom EnergyPlus version using the ENERGYPLUS_EXE_PATH environment variable).  Finally, you would create a Reporting Measure to read simulation results and write them back to gbXML.  

You should check out the example OSW that comes with OpenStudio 2.0.  If you want to try to write your own measure you can ask questions about using the API (e.g. how to convert a gbXML to OpenStudio) on unmethours.
