### ISSUE TITLE
Attempting to add WaterHeater:HeatPump to supply side of plant loop creates orphaned node

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#2468]
Tested in v2.0.1, Windows x64. 

@kbenne:
The supply side of a plant loop is no place for a  WaterHeater:HeatPump (or WaterHeater:HeatPump:WrappedCondenser). Attempting to add either there will prompt the message `The selected component is not allowed at this location`, yet a branch and node will be created there anyway:

![image](https://cloud.githubusercontent.com/assets/10799524/22835084/c395736e-ef74-11e6-85d1-a79c15dace0c.png)

**Comment by jmarrec** [comment]
This actually happens with every object. Try to put a AirLoopHVACUnitarySystem on the supply side of a plant loop, you'll get the same behavior.

**Comment by MatthewSteen** [comment]
I was able to manually fix by adding an allowed object and then deleting it, which deleted the extra node.

**Comment by jmarrec** [comment]
I can't recreate this in 2.6.0 on Ubuntu 16.01. Perhaps it was fixed.

Can either @eringold and @MatthewSteen try on Windows with the latest OS version please?

**Comment by eringold** [comment]
Confirmed not happening in 2.6.0 on windows.

**Comment by JShultz89** [comment]
@eringold @MatthewSteen I am experience the orphaned element when adding a WaterHeater:HeatPump or WaterHeater:HeatPump:WrappedCondenser. I am using 2.6.0 on Windows 10. 

Was there a solution found?
