### ISSUE TITLE
PAT 2.0.2 can't quit without saving

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2469]
![screen shot 2017-02-10 at 2 40 20 pm](https://cloud.githubusercontent.com/assets/4857055/22845252/f2b44150-ef9e-11e6-8044-a79db2c4ea77.png)

At some point I could quit without saving changes, but now it just brings me back to the app.

@asparke2 ok to put in March milestone and in Pivotal?

**Comment by DavidGoldwasser** [comment]
Hmm, PAT 2.0.2 won't quit some existing projects, but will quit on new empty project, so issue may not be related to cancel vs. save button at all.

**Comment by DavidGoldwasser** [comment]
Closing this as invalid, made with unofficial installer.

**Comment by eringold** [comment]
@DavidGoldwasser I can't get PAT 2.0.1 to quit in a new, empty project (Windows x64), even after saving the project. Neither File->Quit, Window->Close, upper-right X or close from the task bar works; I have to kill the process.

**Comment by ljbrackney** [comment]
Pressing cancel on the save dialog proceeds to quit without saving.  Not obvious, but...

On Feb 10, 2017, at 2:12 PM, eringold <notifications@github.com<mailto:notifications@github.com>> wrote:


@DavidGoldwasser<https://github.com/DavidGoldwasser> I can't get PAT 2.0.1 to quit in a new, empty project (Windows x64), even after saving the project. Neither File->Quit, Window->Close, upper-right X or close from the task bar works; I have to kill the process.

-

**Comment by MatthewSteen** [comment]
I'm experiencing the same as @eringold, but in 2.0.2. 

I have been unable to close an existing project (path does not have any spaces) using either File > Quit, `CTRL + Q`, or the ` X `.

build: fcf99c0
system: Windows 7 x64
