### ISSUE TITLE
ChillerElectricEIR::chilledWaterInletNodeName does not return a node name

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#2470]
With the following code, `in_node` is an OS:Connection object, not a node. This is confusing, given the method name: 

```
require 'openstudio'

model = OpenStudio::Model::Model.new
cw_loop = OpenStudio::Model::PlantLoop.new(model)
chw_loop = OpenStudio::Model::PlantLoop.new(model)

chiller = OpenStudio::Model::ChillerElectricEIR.new(model)
cw_loop.addDemandBranchForComponent(chiller)
chw_loop.addSupplyBranchForComponent(chiller)

in_node_name = chiller.chilledWaterInletNodeName
in_node = model.getModelObjectByName(in_node_name).get
puts in_node
```

[This](https://github.com/NREL/OpenStudio/blob/72e4961a2d6547dcb40be48f722345b5691e3a74/openstudiocore/src/model/ChillerElectricEIR.cpp#L213) (I think) is what needs to be built out. 

Workaround: use `chiller.supplyInletModelObject.get`, which does return a node.

**Comment by jmarrec** [comment]
Removed in https://github.com/NREL/OpenStudio/pull/3847/files
