### ISSUE TITLE
CLI run does not work in git bash on windows

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2476]

**Comment by macumber** [comment]
Also look into behavior of CLI when called from bundle and rake tasks which set gem environments https://github.com/macumber/openstudio-env

**Comment by shorowit** [comment]
For what it's worth, CLI works for me in git bash on windows.

**Comment by asparke2** [comment]
OS 2.0.4 CLI works for me on Windows.

**Comment by shorowit** [comment]
OS 2.0.3 CLI has issues for me. It seems to be influenced by external conditions, which is not good.

For example, this works for me:
```
C:\Users\shorowit\Documents\GitHub\OpenStudio-BEopt>c:\openstudio-2.0.3\bin\openstudio.exe run -m -w C:\Users\shorowit\Documents\GitHub\OpenStudio-BEopt\hvac_None.osw
```

But then if I switch to the openstudio bin dir, I get an error:
```
c:\openstudio-2.0.3\bin>openstudio.exe run -m -w C:\Users\shorowit\Documents\GitHub\OpenStudio-BEopt\hvac_None.osw
Exception: Embedded file not found ':c:/ruby/2.2.0/gems/openstudio-workflow-1.1.1/lib/openstudio/workflow/version.rb'
eval:71:in `getFileAsString': unexpected return
```

And now if I switch back to the original dir that worked, it no longer works:
```
c:\Users\shorowit\Documents\GitHub\OpenStudio-BEopt>c:\openstudio-2.0.3\bin\openstudio.exe run -m -w C:\Users\shorowit\Documents\GitHub\OpenStudio-BEopt\hvac_None.osw
Exception: Embedded file not found ':c:/ruby/2.2.0/gems/openstudio-workflow-1.1.1/lib/openstudio/workflow/version.rb'
eval:71:in `getFileAsString': unexpected return
```

Above commands run simply in cmd.exe, Windows 64.

**Comment by shorowit** [comment]
In summary, I think the ticket should remain open. Unless you think it's been fixed for OS 2.0.4.

**Comment by asparke2** [comment]
@shorowit Can you test w/ 2.0.4?  @macumber changed the way that the gem path is resolved, which fixed some CLI stuff for me.

**Comment by shorowit** [comment]
I get the same results for 2.0.4.

```
c:\openstudio-2.0.4\bin>openstudio.exe run -m -w C:\Users\shorowit\Documents\GitHub\OpenStudio-BEopt\hvac_None.osw
Exception: Embedded file not found ':c:/ruby/2.2.0/gems/openstudio-workflow-1.1.1/lib/openstudio/workflow/version.rb'
eval:71:in `getFileAsString': unexpected return
```

**Comment by macumber** [comment]
@shorowit is your previous command failing in a git shell?  the command prompt looks like a normal msdos prompt

**Comment by macumber** [comment]
Also can you please share your 'hvac_None.osw' file, are you running against master on the beopt repo?

**Comment by macumber** [comment]
@shorowit is having trouble running cli, seeing but difficult to reproduce, going to close this and reopen new issue when we can reproduce
