### ISSUE TITLE
ZoneVentilation:NaturalVentilation shows unconventional IP unit for Fan Pressure Rise

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#2478]
Verified in v1.14.0 and v2.0.1:

![image](https://cloud.githubusercontent.com/assets/10799524/23037637/57c55698-f444-11e6-9da7-290edf9e6aa1.png)

Workaround:

![image](https://cloud.githubusercontent.com/assets/10799524/23037826/0855fecc-f445-11e6-8851-6541d19b7c92.png)

(Or input value in SI. 1 min*ton/ft^3 = 7451789.16157332 Pa)

@evanweaver

**Comment by evanweaver** [comment]
@eringold  this is now fixed and should be in this evening's iteration build.
