### ISSUE TITLE
can't remove material layers from ConstructionInternalSource

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2479]
Occurs in 1.14.0 and 2.0.2. 

To reproduce:

1. Create Internal Source Construction
2. Add material(s) to construction
3. Try to remove using the (X) on the material icon

**Comment by asparke2** [comment]
Confirmed still an issue with OS App 2.1.0

**Comment by evanweaver** [comment]
Weird. Add 3 or more materials and you can delete all but 2.

**Comment by macumber** [comment]
There might be some API stuff going on, internal source means you have a source between layers, so there is a minimum of 2 layers needed.

**Comment by macumber** [comment]
Although it is always possible the API is too strict

**Comment by evanweaver** [comment]
Thanks @macumber. So, @asparke2 and @MatthewSteen, what is the desired behaviour? Right now, you can have 0, or 2 or more. If we reduce strictness, and allow only 1 then we would need to trap the situation where the user tries to move forward (i.e. change fields, change tabs) with only that one defined, perhaps by popping a dialog. Or, if there are only 2 left, and the user wants to delete 1, we could delete both remaining. Or, we can wait for Marj to return so we can determine a way forward :)

**Comment by evanweaver** [comment]
@DavidGoldwasser

**Comment by DavidGoldwasser** [comment]
My view is that any number of layers should be valid for the API and the GUI. You won't always have a model that is ready to run, but we don't stop anybody from creating a standard construction without any layer.

**Comment by macumber** [comment]
I agree with @DavidGoldwasser, just let the object get made however you want and log errors at translation time.  I am not sure if the API will need to be relaxed to allow this.

**Comment by evanweaver** [comment]
@macumber @asparke2 @MatthewSteen I agree with David. He pointed out that we currently allow zero layers, so it seems reasonable that we would also allow one layer.

**Comment by evanweaver** [comment]
Perfect timing Dan. I'll take a look at Model's API and then send you a PR.

**Comment by MatthewSteen** [comment]
Sounds good to me, thanks.

**Comment by evanweaver** [comment]
Fixed via https://www.pivotaltracker.com/n/projects/134010/stories/154537565.

**Comment by macumber** [comment]
@evanweaver pivotal is not public so probably not useful to link to pivotal from here
