### ISSUE TITLE
Naming for Schedule:Week:Daily objects has UUID and no relation to named objects in model (Bugzilla #1016)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#248]
On 2012-12-21 11:58:40, @DavidGoldwasser wrote:

> Here is an example.
> Schedule:Week:Daily {4fe8a569-c728-4623-a83b-6aa63af4a62d}
> 
> The UUID doesn't even come from the OSM file, seems to be bade on translation. Makes it very hard to trace errors.

On 2013-01-10 11:37:04, @DavidGoldwasser wrote:

> <batch comment: added this to Pivotal Epic, https://www.pivotaltracker.com/epic/show/458473>

On 2013-06-06 15:02:28, @DavidGoldwasser wrote:

> Ran across this again, now that sorting is better making it feasible to diff IDF's  I'm hitting this again. Looks like it is in Pivotal but in ICE box, which is probably fine until after the next release
> 
> Kyle, I'm copying you because there are some other objects that do this as well, listed below. 
> 
>   BranchList {09408645-c29e-4272-ae7d-d32c7237f2c7}, !- Branch List Name
>   Branch {ec02ea73-2960-4b26-b4fd-1bea6da5a22e}, !- Name
>   AirLoopHVAC:ControllerList {42ffb41c-22cb-4106-a3bc-69a7450c3b3a}, !- Controller List Name
>   AirLoopHVAC:OutdoorAirSystem:EquipmentList {be2024aa-a26e-407d-9b40-586963d0b396}, !- Outdoor Air Equipment List Name
>   AvailabilityManagerAssignmentList {3c670d23-a1a4-4b25-b6d5-62663a15710a}; !- Availability Manager List Name
>   AvailabilityManager:Scheduled {17d071cb-8420-4c2e-ad5b-df6c05d1249b}; !- Availability Manager Name 1
>   AvailabilityManager:Scheduled {17d071cb-8420-4c2e-ad5b-df6c05d1249b}, !- Name
>   Schedule:Compact {ebad90b6-a87f-4f65-b5eb-3c5e4d765cec}; !- Schedule Name
>   OutdoorAir:Mixer {e1011a08-639c-494b-9d55-1eb0ebf800a3}, !- Name
>   AirLoopHVAC:SupplyPath {b022e13e-0906-4262-9590-a3b706d66d47}, !- Name
>   AirLoopHVAC:ReturnPath {a14b8ec4-5dd5-47bf-9e86-0ffa190c76b7}, !- Name
>   ZoneHVAC:AirDistributionUnit {54740b36-4ca2-4d79-ad9e-3fcb1161ad35}, !- Name
> 
> LifeCycleCost:Parameters,
>   {248eeab8-c8f5-4a18-b95a-d1d54d29cd4d}, !- Name
> 
> I may have missed some, but these were the ones that jumped out.

Keywords: ForwardTranslation

**Comment by jmarrec** [comment]
Still true in OS 2.2.1

**Comment by jmarrec** [comment]
This has been fixed. https://github.com/NREL/OpenStudio/pull/3081
