### ISSUE TITLE
Discrete and pivot variables w/ choice arguments not populating correctly in PAT 2.0.3

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2481]
![pivot](https://cloud.githubusercontent.com/assets/2230150/23236770/64b3dcd8-f90f-11e6-8c93-2eeefbab3a8b.jpg)

I believe this was working in 2.0.2, but no measure input value options are available in 2.0.3 for arguments with choice lists.

**Comment by evanweaver** [comment]
@ljbrackney this was just fixed with https://www.pivotaltracker.com/n/projects/134010/stories/140453547
