### ISSUE TITLE
Duplicate Option only works after leaving tab and coming back

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2483]
@asparke2 and I were testing and ran into this. If I add a measure option and then try to duplicate it, no options come up to select.
![screen shot 2017-02-23 at 11 29 58 am](https://cloud.githubusercontent.com/assets/4857055/23275014/10d5267c-f9c2-11e6-88af-e393118929aa.png)

When I leave the measure option tab and come back after adding design options but before trying to duplicate them, then it works as expected.
![screen shot 2017-02-23 at 11 31 09 am](https://cloud.githubusercontent.com/assets/4857055/23275040/2f176e1a-f9c2-11e6-918e-1d0f0407a010.png)

This was tested in the 2.0.3 installer

**Comment by evanweaver** [comment]
@DavidGoldwasser fixed with https://www.pivotaltracker.com/n/projects/134010/stories/140521323

**Comment by DavidGoldwasser** [comment]
Tested 02.28 installer
