### ISSUE TITLE
Empty output selection in 2.0.3 on Mac

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2485]
No outputs are available for selection on Mac.

![outputs](https://cloud.githubusercontent.com/assets/2230150/23320303/00c90c6c-fa8f-11e6-8bc1-fabb7e1e6d04.jpg)

David tells me this is what things look like on Windows.

![2-24-2017 1-42-26 pm](https://cloud.githubusercontent.com/assets/2230150/23320367/4889479c-fa8f-11e6-8253-bb24c4ea85de.png)

**Comment by DavidGoldwasser** [comment]
So just to confuse things a bit, Here are my mac results. If I use the repo version of measure (on develop) I see the same as I did on windows.

![screen shot 2017-02-24 at 2 54 03 pm](https://cloud.githubusercontent.com/assets/4857055/23322439/3444bba6-faa1-11e6-958b-56bc3e0b89cd.png)
(mac screenshot of OpenStudio Results from repo (develop) in 2.0.3

But if I get the BCL version (fresh download today) I see this which is different than Larry's in that I see the check boxes but I still don't have the text
![screen shot 2017-02-24 at 2 51 25 pm](https://cloud.githubusercontent.com/assets/4857055/23322466/5299d370-faa1-11e6-8131-555b9b73ef17.png)

**Comment by DavidGoldwasser** [comment]
Prior to this commit I made today, which seemed to juggle around some content in the XML
https://github.com/NREL/OpenStudio-measures/commit/bb1035f99d5554042a16e4c48f2f31524e5cd0c1#diff-a1ed8fbee31c39cc3add3c0d86e47695

The last commit was made on January 31st just prior to uploading the measure to BCL
https://bcl.nrel.gov/node/82918

Not sure why I'm seeing different behavior in GUI between the two.

**Comment by DavidGoldwasser** [comment]
Ok, so can't diff xml coming out of BCL is very different.

Here is typical argument object from repo xml
`  <argument>
      <name>building_summary_section</name>
      <display_name>Model Summary</display_name>
      <type>Boolean</type>
      <required>true</required>
      <model_dependent>false</model_dependent>
      <default_value>true</default_value>
      <choices>
        <choice>
          <value>true</value>
          <display_name>true</display_name>
        </choice>
        <choice>
          <value>false</value>
          <display_name>false</display_name>
        </choice>
      </choices>
    </argument>`

And here is the same from BCL
`<argument>
   <name/>
   <display_name/>
   <type/>
   <required>false</required>
   <model_dependent>false</model_dependent>
  </argument>`

Here is repo output
`  <output>
      <name>electricity_ip</name>
      <display_name>electricity_ip</display_name>
      <short_name>electricity_ip</short_name>
      <type>Double</type>
      <model_dependent>false</model_dependent>
    </output>`

and here is bcl output
`<output>
   <name/>
   <display_name/>
   <type/>
   <model_dependent>false</model_dependent>
  </output>`

There may be other changes but these are the ones that jumped out at me. @macumber I assume OpenStudio isn't trying to update XML's in the BCL directory because it doesn't want to alter BCL measures, but if it did everything needed to update the bcl is in the measure.rb

**Comment by DavidGoldwasser** [comment]
This reminds me of this story (no git issue, it was in Google Doc before)
https://www.pivotaltracker.com/n/projects/134010/stories/137187799

For a while the scheme_version, xml_checksum, class_name, and display_name were being stripped out. Just thought I would like it to this for reference.

**Comment by macumber** [comment]
Well it is known that xmls downloaded from BCL are not accurate, I thought @kflemin was making a call to force a refresh after downloading via PAT.  The unfortunate side effect of this is that version id would not match what is in BCL.

**Comment by macumber** [comment]
Actually I think if @kflemin is using the 'download_bcl_measure' api of the measure manager server then if anything needs to get more of a forced refresh i can do it.

**Comment by DavidGoldwasser** [comment]
If the version_id doesn't match BCL will it always look like to user that there is an updated measure available?

**Comment by macumber** [comment]
no, we added a timestamp check as well

**Comment by kflemin** [comment]
Is the measure manager running correctly?  Do you see any errors related to measure manager in the developer console?  I am using the download_bcl_measure api of the measure manager server.  I've seen these behaviors before in the development environment, and they were related to the measure manager not running / no longer being connected to PAT.

**Comment by ljbrackney** [comment]
It appeared to be running.  I added measures to my project and could see BCL and local library content that wasn't in my project.  I can step through this in greater detail with you on Monday.

On Feb 24, 2017, at 9:33 PM, Katherine Fleming <notifications@github.com<mailto:notifications@github.com>> wrote:


Is the measure manager running correctly? Do you see any errors related to measure manager in the developer console? I am using the download_bcl_measure api of the measure manager server. I've seen these behaviors before in the development environment, and they were related to the measure manager not running / no longer being connected to PAT.

-
