### ISSUE TITLE
Cross version OS app/PAT handling of measure.xml file

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2487]
Steps to change all measure.xmls in a directory.

1. Download this repo in develop branch
https://github.com/NREL/OpenStudio-measures

2. Set your "My Measures" directory 
https://github.com/NREL/OpenStudio-measures/tree/develop/NREL%20working%20measures

3. Launch 2.0.3 OS app and go to measures tab. If you then look back at GitHub change log you shouldn't see anything.

![screen shot 2017-02-24 at 3 30 54 pm](https://cloud.githubusercontent.com/assets/4857055/23323912/165e9bd2-faa8-11e6-8918-79a522b1cf50.png)

4. Quit OpenStudio 2.0.3 and launch OpenStudio 1.14.0, and go to the measures tab (I think similar behavior exists with 2.0.0 and 2.0.3 but I don't have that installed now to test)

5. You will now see 209 files changed in the GitHub change log. in this case the "outputs" section was removed which also triggered version_id and version_modified to change.

![screen shot 2017-02-24 at 3 36 11 pm](https://cloud.githubusercontent.com/assets/4857055/23323901/08f773ec-faa8-11e6-8af9-b2912bb8c490.png)

6. Now quit 1.14.0 and launch 2.0.3 again, and go to the measures tab

7. If you look back at GitHub change log, now outputs is back, but a fresh version_id and version_modified has been added, which doesn't match the committed repo one.

![screen shot 2017-02-24 at 3 38 31 pm](https://cloud.githubusercontent.com/assets/4857055/23323889/f9a643c8-faa7-11e6-9f23-6ae72843bdcb.png)

The issue here is confusion for people working on repo where they change one measure but hundreds of XML's are updated, it also creates tons of merge conflicts in branches making. The only way I can think of to avoid this is to avoid structural changes to the XML file whenever possible, so this happens less often. Unless there is a way the version_id and version_updated is some form of checksum based on content that would match what it originally did. We can also have users always make commits after updating XML's with the latest version (or maybe the latest major version). Another alternative that I think isn't an option is just not to have an measure.xml, add the few things needed like uid and taxonomy to measure.rb and let measure.xml be generated when needed.

**Comment by macumber** [comment]
Thanks Dave.  I hope we dont have to change anything back in 1.14, but if so I would support that.  I know this is a big issue for people working on measures

**Comment by DavidGoldwasser** [comment]
After March I'm hoping very few people much less measure developers are using 1.x. I'm mainly interested in avoiding or minimizing how often we change the xml schema in future 2.x releases. Then the xml will only change when the measure content does.
