### ISSUE TITLE
Minor cosmetic issue on PAT HTML rendering - extra scroll bar

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2488]
As shown below there is an extra scroll bar in the HTML rendering for PAT 2.x. Trivial and doesn't affect ability to view, but if someone is in that code anyway could fix this.

![2-27-2017 10-13-06 am](https://cloud.githubusercontent.com/assets/4857055/23371641/0c9b1776-fcd6-11e6-9005-8975cb964b0d.png)

**Comment by macumber** [comment]
Possibly related to https://github.com/NREL/OpenStudio/issues/2438

**Comment by DavidGoldwasser** [comment]
@macumber possible but #2438 is OS app specific and this is PAT specific.

**Comment by kflemin** [comment]
this has to do with the way this page is implemented. There is a scrollbar for the modal window and another scroll bar inside the frame showing the report.  They can't be removed.
