### ISSUE TITLE
ReverseWithLimits Can't be Set Using '.setDamperHeatingAction'

### ISSUE THREAD

**Issue by adhilton25** [NREL/OpenStudio#2490]
The `.setDamperHeatingAction` method doesn't currently support setting the 'ReverseWithLimits' option for `AirTerminalSingleDuctVAVReheat`. The option is in the [idd](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/resources/model/OpenStudio.idd#L10308) and correctly translated so I think it's just a matter of adding the following block [here](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/AirTerminalSingleDuctVAVReheat.cpp#L452).

    else if( istringEqual(value,"ReverseWithLimits") )
    {
      this->setString(OS_AirTerminal_SingleDuct_VAV_ReheatFields::DamperHeatingAction,"ReverseWithLimits");
    }

**Comment by asparke2** [comment]
@kbenne Can you do this when you do the E+ update?  This is that new enum that you had to fix in the fwd translator a while back.

**Comment by kbenne** [comment]
Looks like this happened during the 8.7 update.

![screen shot 2017-03-15 at 11 52 02 am](https://cloud.githubusercontent.com/assets/707488/23960417/e9402936-0975-11e7-9c39-43f46d681712.png)
<img width="1440" alt="screen shot 2017-03-15 at 11 52 36 am" src="https://cloud.githubusercontent.com/assets/707488/23960420/ecd4b418-0975-11e7-96de-e4e596358754.png">

**Comment by asparke2** [comment]
@kbenne Can you set this via the API now?

**Comment by adhilton25** [comment]
@kbenne Yes, the gui and translation are fine. It's the setter in the API that doesn't have the support.

**Comment by kbenne** [comment]
that should take care of it.
