### ISSUE TITLE
data_point.zip doesn't copy to local results for prototype measure

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2495]
From @DavidGoldwasser

When I used the prototype measure in a workflow the Results (SQL file) fails to copy to local results. See screenshot below. The log message shows “vendor-93aa470504.js:24010 Invalid LOC header (bad signature)”

+larry.brackney@nrel.gov FYI, figured it was just using the Prototype measure in a design alternative that was causing the issue. +asparke2@gmail.com I assume this may be change to measure vs. PAT, but not sure. I thought the sizing run in measure could be causing issues?

**Comment by asparke2** [comment]
I believe the root of this issue is the handling of .zip files on Windows vs. Mac.  @henryHorsey and I tested a fix which appears to work.

**Comment by macumber** [comment]
@henryHorsey  is this closed?

**Comment by macumber** [comment]
@henryHorsey @asparke2 is this closed?

**Comment by asparke2** [comment]
@macumber I still need to test this

**Comment by asparke2** [comment]
Tested with 2.0.5 on Windows
