### ISSUE TITLE
Chinese characters in Design Alternatives grid

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2496]
For some reason there are Chinese? characters in the Design Alternatives grid. Screenshot from 2.0.4 in Windows. 

This only appears in the installed version.  When I run the developer version from code, these look like check mark symbols.

![](https://cloud.githubusercontent.com/assets/2009290/23523399/f8c82d54-ff43-11e6-9d03-5dffbbf31779.png)

**Comment by kbenne** [comment]
@kflemin is this for me to review or to fix?

**Comment by jmarrec** [comment]
Same problem on Mac. This also does it when you click on a column header to sort with it. I can see it change, probably supposed to be uparrow and downarrow.

![screen shot 2017-03-28 at 11 30 24](https://cloud.githubusercontent.com/assets/5479063/24398520/0c1a379c-13aa-11e7-80e4-7e905190c4dc.png)

**Comment by shorowit** [comment]
This is fixed.
