### ISSUE TITLE
All options not getting first column value when measure arg isn't "variable"

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2497]
If a measure argument is not "variable," when you change the value in the first option, all of the other options should change to use this same value. This currently happens if you check then uncheck the "variable" box, but should happen whenever you change the value in the first option.

After this is fixed, you should not be able to have a different input for an argument unless the argument is "variable"

![](https://cloud.githubusercontent.com/assets/2009290/23522085/ec63f5d4-ff3e-11e6-81dc-4e50b01fe063.png)

**Comment by jmarrec** [comment]
+1

**Comment by asparke2** [comment]
Fixed in 2.1.0
