### ISSUE TITLE
Clean up OpenStudio-PAT repo README

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2498]
requested by @pmkary

**Comment by asparke2** [comment]
Agree.  At a minimum, we should include:

1. What the repo is
2. Where to report issues (OpenStudio issues)
3. Where the build instructions live (Wiki)

**Comment by macumber** [comment]
@asparke2 do you really want this assigned to you?  should be assigned to @evanweaver or @kflemin ?

**Comment by macumber** [comment]
@asparke2 is this complete?  can we close it?

**Comment by asparke2** [comment]
No, it is still the electron boilerplate:

https://github.com/NREL/openstudio-pat

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#12
