### ISSUE TITLE
Can't select multiple design alternatives at a time and duplicate them

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2499]
I thought there was a time this worked, but doesn't with 2.0.4. not important for 2.1 release but I wanted to document it for a future release.

I'm referent to being able to check more than one row using the left column.

![screen shot 2017-03-03 at 9 25 18 am](https://cloud.githubusercontent.com/assets/4857055/23559194/64378fd0-fff3-11e6-9981-1694c6d87718.png)

**Comment by kflemin** [comment]
you cannot select multiple rows in the grid...you must duplicate one at a time.
