### ISSUE TITLE
Make PAT "Additional Analysis Files" path relative

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2500]
Currently, in PAT, the paths to "Additional Analysis Files" directories are absolute paths.

Pros to absolute paths:
- If you copy/paste the project or move the project on your local computer, you don't have to update the path.

Pros to relative paths:
- If you send the project to another user, you can copy the resources directory into the PAT project directory and when the new user opens the project, it will run without them having to change anything in PAT.
- If you share projects via DropBox (common w/ PAT 1.X users), as long as the resources directories are also in the DropBox folder, the project will run without having to update anything.

This came up because the Residential team expects to have to share files w/ BPA.  Ideally, the less setup required, the better.

**Comment by asparke2** [comment]
@brianlball can you weigh in on this?

**Comment by brianlball** [comment]
the spreadsheet is relative paths, but like you state it does have its cons.

can we handle both cases?

**Comment by asparke2** [comment]
@kflemin What do you think?  Can we handle both relative and absolute paths?

**Comment by kflemin** [comment]
this should be fixed, the path is now relative to the project directory.  https://github.com/NREL/OpenStudio-PAT/commit/37991085d59ad9d545d5ba6d1d66ebbb431f7468
