### ISSUE TITLE
Show units & descriptions for arguments in PAT

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2501]
PAT 2.X "Project Measures & Options" tab doesn't show units or descriptions for measure arguments.  These need to be included.  Units are particularly important for clarity.

Argument units in PAT 1.X.  Could append to argument name in () or add a units column.
![image](https://cloud.githubusercontent.com/assets/2009290/23567042/b6b62d8e-0011-11e7-8c19-5faa596d6ccd.png)

Argument descriptions in PAT 1.X.  Could add in Mouseover in PAT 2.X
![image](https://cloud.githubusercontent.com/assets/2009290/23567015/95765aae-0011-11e7-8748-c5f535a8f03d.png)

**Comment by shorowit** [comment]
+1

**Comment by DavidGoldwasser** [comment]
@evanweaver I see units in some cases in 2.1.0 installer, but it looks like it doesn't like special characters. Look in image below how 'ft' is fine, but 'ft^2' is not.

![screen shot 2017-03-31 at 10 01 23 am](https://cloud.githubusercontent.com/assets/4857055/24558743/7bad8cf2-15f9-11e7-83fb-b7b5c6c720ae.png)

**Comment by DavidGoldwasser** [comment]
After going through it with @evanweaver looks like issue occurs when data is written to 'pat.json'. Looks like this

```
units": "",
```

If I manually change the unit string to 'ft^2' in this file the GUI displays it fine. The '^' seems to be issue, as 'ft2' is fine if that is used in measure.rb and measure.xml instead. I assume there could be other offending alpha numeric characters.

**Comment by asparke2** [comment]
tested and closed using developer setup

**Comment by shorowit** [comment]
@evanweaver As far as I can tell, argument descriptions only show up in manual mode, not algorithmic mode. This makes it difficult to convey information to our PAT users.

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#13
