### ISSUE TITLE
Skipping measures in datapoint throws measure messages out of sync

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2503]
<img width="1920" alt="screen shot 2017-03-03 at 2 08 28 pm" src="https://cloud.githubusercontent.com/assets/4857055/23569167/38cde2e0-001b-11e7-8343-59d7f3ee7fa9.png">

The messages shown are meant for the PV measure a few steps down. This is in 2.0.4

Cause - choosing "None" as measure option for one or more measures for a datapoint. The skipped measure shows the log message of the next measure (or a few steps further of "None" was used for more than one measure for the datapoint).

**Comment by macumber** [comment]
Can you post the osw files (in and out)?  That will identify if this is a WFG thing or a PAT thing

**Comment by macumber** [comment]
Whoops my commit referenced the wrong bug, multitasking is hard...

**Comment by DavidGoldwasser** [comment]
Looks like this is affecting the OSW.

Here is part of it before measure option of "None" was used.

`   {
      "arguments": {
        "costTotalKitchenSystem": 0,
        "numberOfStudents": 650
      },
      "description": "Option 1 Description",
      "measure_dir_name": "AedgK12Kitchen",
      "measure_id": "92750b5a-7eb5-4df5-899f-c186c7c27935",
      "measure_type": "ModelMeasure",
      "name": "Kitchen AEDG Primary",
 `

Here is pat of the OSW after measure option was set to "None". Most of this content is from PV but the name, and description are from VRF measure. I confirmed measure_id is from the PV measure.

`    {
      "arguments": {
        "cell_efficiency": 0.18,
        "fraction_of_surface": 0.75,
        "inverter_efficiency": 0.98
      },
      "description": "Measure replaces existing HVAC system (if any) with a Variable Refrigerant Flow (VRF) system with DOAS HVAC system (one DOAS per floor).  The VRF with DOAS system (centralized DOAS, with zone level conditioning) is applied to all space types except storage spaces like stairwells, mechanical/electrical rooms etc.",
      "measure_dir_name": "add_rooftop_pv",
      "measure_id": "34550614-0c87-44db-9252-0ca0915b1e64",
      "measure_type": "ModelMeasure",
      "name": "vr_fwith_doaszedg",`

**Comment by DavidGoldwasser** [comment]
Here are the two measure (that are out of sync on run tab) shown in the measure options tab

<img width="927" alt="screen shot 2017-03-03 at 8 26 21 pm" src="https://cloud.githubusercontent.com/assets/4857055/23575760/e200eae0-004f-11e7-95db-644d9157900e.png">

<img width="859" alt="screen shot 2017-03-03 at 8 26 37 pm" src="https://cloud.githubusercontent.com/assets/4857055/23575761/e5c8062c-004f-11e7-9dbc-f34f9342840a.png">

**Comment by DavidGoldwasser** [comment]
And here they are in pat.json, look fine.

VRF
`      "measure_dir": "/Users/dgoldwas/Documents/working/PAT_01311341_zedg_test/measures/vr_fwith_doaszedg",
      "name": "vr_fwith_doaszedg",
      "directory": "/Users/dgoldwas/Documents/working/PAT_01311341_zedg_test/measures/vr_fwith_doaszedg",
      "uid": "83cf7834-2554-49c3-8910-5b6679060bb7",
      "uuid": "{83cf7834-2554-49c3-8910-5b6679060bb7}",
      "version_id": "62ad5129-5a36-4d4e-bd65-c6545b4072cd",
      "version_uuid": "{62ad5129-5a36-4d4e-bd65-c6545b4072cd}",
      "version_modified": "20170301T064747Z",
      "xml_checksum": "16B68B0C",
      "display_name": "VRFwithDOAS_ZEDG",
      "class_name": "VRFwithDOASZEDG",
      "description": "Measure replaces existing HVAC system (if any) with a Variable Refrigerant Flow (VRF) system with DOAS HVAC system (one DOAS per floor).  The VRF with DOAS system (centralized DOAS, with zone level conditioning) is applied to all space types except storage spaces like stairwells, mechanical/electrical rooms etc.",
      "modeler_description": "Airloops are dedicated to ventilation (DOAS) and have constant or variable speed fan operation, gas furnace heating,single speed DX cooling and optional energy recovery and/or direct evaporative cooling.  Conditioning is provided at the zone level with VRF system with cycling fans. Only air cooled VRF system is modeled. ",
      "tags": "HVAC.Whole System",
      "outputs": [],`

PV
`      "measure_dir": "/Users/dgoldwas/Documents/working/PAT_01311341_zedg_test/measures/add_rooftop_pv",
      "name": "add_rooftop_pv",
      "directory": "/Users/dgoldwas/Documents/working/PAT_01311341_zedg_test/measures/add_rooftop_pv",
      "uid": "34550614-0c87-44db-9252-0ca0915b1e64",
      "uuid": "{34550614-0c87-44db-9252-0ca0915b1e64}",
      "version_id": "67b8a80f-6618-485f-8099-fceea84bc907",
      "version_uuid": "{67b8a80f-6618-485f-8099-fceea84bc907}",
      "version_modified": "20170303T201437Z",
      "xml_checksum": "C78730CC",
      "display_name": "Add Rooftop PV",
      "class_name": "AddRooftopPV",
      "description": "This measure will create new shading surface geometry above the roof for each thermal zone inyour model where the surface azmith falls within the user specified range. Arguments are exposed for panel efficiency, inverter efficiency, and the fraction of each roof surface that has PV",
      "modeler_description": "The fraction of surface containing PV will not only set the PV properties, but will also change the transmittance value for the shading surface. This allows the measure to avoid attempting to layout the panels. Simple PV will be used to model the PV.",
      "tags": "Onsite Power Generation.Photovoltaic",
      "outputs": [],`

**Comment by macumber** [comment]
Can you post the datapoint (OSW, seed, measures, etc)?  When I run the test in the WFG related to skipping measures I don't see this issue

https://github.com/NREL/OpenStudio-workflow-gem/blob/osw/spec/openstudio/workflow/workflow_analysis_spec.rb#L65

**Comment by DavidGoldwasser** [comment]
@macumber here is zip file or project.
https://drive.google.com/open?id=0BziGk7eItbVVQXdLQnhMWURGTE0

**Comment by macumber** [comment]
Assigned back to @DavidGoldwasser to reproduce with simpler model

**Comment by DavidGoldwasser** [comment]
I haven't been able to reproduce this on a new project. Will close unless it comes back up.

**Comment by DavidGoldwasser** [comment]
I was able to re-produce this on a clean simple model. Issue seems to come up only when all of the datapoints in the project use "None" for a particular model. If just one of the datapoints doesn't use "None" then all of the datapoints are fine.

Here are the datapoints in GUI

![screen shot 2017-03-30 at 2 41 45 pm](https://cloud.githubusercontent.com/assets/4857055/24525356/255b9f62-1557-11e7-81be-cab8efbb15d4.png)

And here is the run tab. Notice how add_rooftop_pv which should't have any information is populated by the Tariff measure. Tariff measure is populated by OpenStudio Results, and OpenStudio results doesn't show up on the list of measures on the run tab.

![screen shot 2017-03-30 at 2 42 06 pm](https://cloud.githubusercontent.com/assets/4857055/24525424/6e2c98d6-1557-11e7-8a9b-ba9005ae860e.png).

Here is text from one of the data_point.osw files
```
    {
      "measure_dir_name": "tariff_selection_flat",
      "arguments": {
        "demand_window_length": "QuarterHour",
        "elec_rate": 0.12,
        "gas_rate": 0.5,
        "water_rate": 0.005,
        "disthtg_rate": 0.2,
        "distclg_rate": 0.2
      },
      "name": "add_rooftop_pv",
      "description": "This measure will create new shading surface geometry above the roof for each thermal zone inyour model where the surface azmith falls within the user specified range. Arguments are exposed for panel efficiency, inverter efficiency, and the fraction of each roof surface that has PV",
      "measure_id": "539c3e8e-6c41-4f50-ac61-6cbbf1ee1b55",
      "version_id": "0069dc39-cb7e-4740-905a-79675c38e80a",
      "taxonomy": "Economics.Life Cycle Cost Analysis",
      "measure_type": "EnergyPlusMeasure"
    },
```

I don't think this is critical for 2.1.0, so fine if it goes later. I believe everything is running correctly, but the name and description information on the OSW is mixed up. But of course for user who doesn't know this would be confusing.

**Comment by kflemin** [comment]
The problem is in the out.osw file.  The "name" and "description" keys in each of the steps doesn't have information from the correct measures when a previous measure is skipped. The data are off by one following the skipped measure.
<img width="1423" alt="screen shot 2017-06-13 at 12 52 57 pm" src="https://user-images.githubusercontent.com/2205659/27100236-9409b732-503a-11e7-9440-f0ed00c7853a.png">
.

**Comment by macumber** [comment]
I do not see this happen in 2.1.0 installer and I know that we added a unit test/fix for this in WFG https://github.com/NREL/OpenStudio-workflow-gem/blob/develop/spec/openstudio/workflow/workflow_analysis_spec.rb#L578

Is anyone still seeing this?  If so let's get together and look at the datapoints

**Comment by macumber** [comment]
@asparke2 pointed out that this bug only occurs if a measure is skipped in all datapoints.  When this happens the measure is omitted from the problem->workflow in the analysis.json but not omitted from the design_alternatives leading to off by one errors when the server converts this to datapoint.json files.  I think the right solution is for PAT to include all measures in the problem->workflow of analysis.json even if they are skipped in all datapoints.  I've attached a PAT project that reproduces this issue as well as the resulting analysis.json

[Skipping.zip.txt](https://github.com/NREL/OpenStudio/files/1075651/Skipping.zip.txt)

[analysis.json.txt](https://github.com/NREL/OpenStudio/files/1075666/analysis.json.txt)

**Comment by kflemin** [comment]
@macumber, thanks for the additional information.  I think there was a reason to not send the skipped measure to the server.  It might be better to remove the skipped measure from the design alternatives instead.  I'll try that first.

**Comment by macumber** [comment]
Removing the measure from the analysis.json completely would only cause issues if you later added new datapoints that did not skip the measure, then the datapoints would not be in the same parameter space.  But I don't think you can do that now (add datapoints to a previously run analysis) so I guess it doesn't matter.  I also recall there was a reason for not sending the skipped measures and I think I might have even suggested removing the measures from the json :-)

**Comment by kflemin** [comment]
this should be fixed now: https://github.com/NREL/OpenStudio-PAT/commit/932c19fb1f06ff74ef0662857e878cb9652f4dc5

**Comment by DavidGoldwasser** [comment]
Looks good! Tested on local manual run with development build on mac.
