### ISSUE TITLE
RDD file isn't included in data_point.zip

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2505]
This file is useful to users.  I think the solution is to comment out [this line in the workflow gem](https://github.com/NREL/OpenStudio-workflow-gem/blob/6c95fb95a92c3ebf1233219fd3bf89f493f71dab/lib/openstudio/workflow/jobs/run_postprocess/run_postprocess.rb#L107).

**Comment by macumber** [comment]
Also keeping mtd
