### ISSUE TITLE
For measure args without default values I have to set as variable to run properly

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2507]
This has happened with both of these measures.

Change Building Location has two string arguments and a choice argument, all of the fields are effected by this.
https://github.com/NREL/OpenStudio-measures/tree/develop/NREL%20working%20measures/ChangeBuildingLocation

Made a new measure today that has 5 optional string arguments, which hit same issue.
https://github.com/NREL/OpenStudio-measures/tree/develop/NREL%20working%20measures/ee_workflow_log

I can provide projects where this happens.

**Comment by kflemin** [comment]
this should be fixed now.
https://github.com/NREL/OpenStudio-PAT/commit/f4a87ce04e5cef742fadd89f42374819955e6489

**Comment by DavidGoldwasser** [comment]
@kflemin I tested in new Mac installer today and still saw same issue. Here is what OSW looks like for this measure. It isn't showing any values. I have single option with values entered for each of three arguments, none set to variables.

```    {
      "measure_dir_name": "ChangeBuildingLocation",
      "arguments": {
        "__SKIP__": false
      },
      "name": "Change Building Location Chicago",
      "description": "Option 1 Description: Change the building location",
      "measure_id": "d4db4971-f5ba-11e3-a3ac-0800200c9a66",
      "version_id": "50a490da-9b6c-41fd-ba59-f3d36d6657e0",
      "taxonomy": "Whole Building.Space Types",
      "measure_type": "ModelMeasure"
    },```

**Comment by DavidGoldwasser** [comment]
@macumber if I skip a measure that has required arguments without default values when OpenStudio runs it also hits this. Is there a way the CLI can look for Skipped argument first, and if it see's that don't worry if anything else is missing. Otherwise not sure how in the PAT GYU  I can populate argument values for measure I'm skipping.

**Comment by macumber** [comment]
I'm having trouble following you @DavidGoldwasser .  I understand the issue about not caring to validate measure arguments if the measure is going to be skipped.  I don't understand how that relates to PAT.  I can make a change in workflow gem, but PAT bugs have to be routed to the PAT team.

**Comment by DavidGoldwasser** [comment]
@macumber if a measure is set to be skipped in the OSW and is missing required default value for another argument, it breaks when it runs. Was wondering if the "skipped" value can be looked at first, so missing default arguments wouldn't be an issue. @kflemin has a fix for making OSW's where the "static" value for an argument will also be set for the measure's "default value". This follows with what the Analysis spreadsheet sees does. It was just odd that the CLI breaks on a measure that isn't even being run, at least from the user's perspective it isn't being run, but under the hood it is running.

**Comment by macumber** [comment]
This was fixed in the workflow gem here https://github.com/NREL/OpenStudio-workflow-gem/commit/c9a53a165f53a763955a7534af5f18bd436b5807

Kat's fixes to PAT are separate i think

**Comment by rHorsey** [comment]
Released WFG v 1.1.5

**Comment by DavidGoldwasser** [comment]
@kflemin and @macumber I still have to set required arguments without default values as variables with latest installer from today (OpenStudio-2.0.5.ea07797068-Darwin)

This also is creating problem where I want to skip a measure that has required arguments without default values. I don't have an work around for this situation.

**Comment by asparke2** [comment]
@kflemin I confirmed that this is still a bug in PAT 2.0.5 from 3/22.

The arguments "Weather Directory," "Weather File Name" and "Climate Zone" are `required` arguments which do not have default values.  I manually entered values in PAT:
![image](https://cloud.githubusercontent.com/assets/2009290/24221857/9c18cc58-0f15-11e7-8ace-a7916c0a1bee.png)

But the values I entered aren't making it to the server:
![image](https://cloud.githubusercontent.com/assets/2009290/24221842/8e3f83ec-0f15-11e7-89b1-8f9c1daf43d0.png)

If I make these arguments `variable` and re-run, the arguments _DO_ make it to the server.

**Comment by ljbrackney** [comment]
I was just chatting w/ Kat about another default value error that may be related.  She mentioned a fix she was working on.

**Comment by ljbrackney** [comment]
I tried a similar workaround on my SEB project.  It changed the nature of the failure - no longer a default error, but a weird type casting of a string (end date) to a double.

**Comment by kflemin** [comment]
@ljbrackney, can you send me the project that has the 'change building location' measure?  I'll test it locally.  thanks!

**Comment by DavidGoldwasser** [comment]
Looks good in 2.1.1
