### ISSUE TITLE
OS App Sometimes Segfaults when opening a model from an earlier version of OS

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2508]
I've now had multiple 2.0.x models crash the app on opening in 2.0.5.  Model opens, version update dialog pops up, click ok, boom.  Behavior is inconsistent - sometimes it crashes immediately.  It can also crash when quitting the app without saving - as one would do when trying to test repeatability.  I've seen this with 2.0.0 and 2.0.4 models.

**Comment by ljbrackney** [comment]
Likely related:  Sometimes App reports that OS Reporting measure (which was in the model) has empty arguments - then crashes.  When I have been able to work with the model and save before a crash, I've removed the Reporting measure and re-added it.  That seems to fix the crash.

**Comment by macumber** [comment]
I don't think this has to do with the reporting measure, the app is failing to build the component libraries which is a classic failure of the version translator.  I see this message in the log:
```

[openstudio.osversion.VersionTranslator] <1> The collection is INVALID at strictness level 'Draft', because of the errors:
Object     level data error of type NoIdd             .
Error pertains to an object of type 'Catchall', named ''.
Additional information about the error type: input data definition is missing or empty.

[OpenStudioApp] <1> Failed to load hvaclibrary
```

@kbenne

**Comment by macumber** [comment]
@kbenne I wrote the following script to try to find out which objects are messed up in the translator but it is acting really weird, maybe there is some issue with a merge of cbecc transition rules?  something else?  I don't get why i can load the file outside of the version translator but not through it, I think that must mean the issue is in the translator?

```

require 'openstudio'

p = 'E:\openstudio\openstudiocore\src\openstudio_app\Resources\hvaclibrary\hvac_library.osm'

m = OpenStudio::Workspace.load(p, "OpenStudio".to_IddFileType)
puts m.get.objects(true)[-1]
puts m.get.validityReport("Draft".to_StrictnessLevel)
puts

m = OpenStudio::Model::Model.new(m.get)
puts m.objects(true)[-1]
puts m.validityReport("Draft".to_StrictnessLevel)
puts

vt = OpenStudio::OSVersion::VersionTranslator.new
m = vt.loadModel(p)

```

**Comment by kbenne** [comment]
You know I closed this, but maybe I shouldn't have. I think there may be two issues conflated here. Somehow we got on the track of hvac lib, which was a real issue, but @ljbrackney originally reported something else about opening models.

**Comment by kbenne** [comment]
@ljbrackney want to send me a trouble model?
