### ISSUE TITLE
OS App Runs Fail in Postprocess

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2509]
Tail of run report looks like:

> EnergyPlus Run Time=00hr 00min  7.93sec
> Returned from state simulation
> Starting state reporting_measures
> Applying OpenStudioResults
> Result: Success
>  Initial Condition: Gathering data from EnergyPlus SQL file and OSM model.
>  Final Condition: Generated report with 21 sections to ./report.html.
> Applied OpenStudioResults
> Returned from state reporting_measures
> Starting state postprocess
> Failure

This has occurred in every test model I've tried to run in 2.0.5 so far.  EPlus and OS Reports are generated and look okay.

**Comment by macumber** [comment]
I think this was fixed in https://github.com/NREL/OpenStudio-workflow-gem/commit/e56ac3d2ca81907abcbc69aeda647311f1968a01

**Comment by macumber** [comment]
Will be in next 2.0.5 package for testing
