### ISSUE TITLE
SketchUp plugin classifies doors as windows when pasting geometry in space

### ISSUE THREAD

**Issue by kpelckmans** [NREL/OpenStudio#2510]
Steps to reproduce:
- copy existing geometry that contains doors and windows
- create new space
- past existing geometry in space

Expected result:
- 4 doors and 1 window

Result:
- 2 doors and 3 windows

[OpenStudio converts to windows.zip](https://github.com/NREL/OpenStudio/files/830230/OpenStudio.converts.to.windows.zip)

Probably I am doing something wrong, but cannot seem to find it.

Many thanks for your answer,

Kristof

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/22
