### ISSUE TITLE
Dropdown menu for "Select Cluster or Make New One" is not functioning correctly. PAT v2.0.4 (windows 7)

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/OpenStudio#2512]
Run Screen of PAT 2.0.4 (Windows 7 64 bit install) 

After entering and saving the cluster settings (and getting an acknowledgement that they were saved) The PAT application dropdown box for selectring a cluster does not allow a user to retrieve the saved cluster settings. 

![image](https://cloud.githubusercontent.com/assets/5746765/23806061/39e2056c-058e-11e7-81e1-a4b90294e4ba.png)

**Comment by asparke2** [comment]
@chrisbalbach Did you try to open the cluster settings in the same project where you saved them, or a different project?  Cluster settings are saved per-project.

**Comment by ljbrackney** [comment]
Stickiness of these settings was an issue in 2.0.4.  I believe this is resolved in 2.0.5.

**Comment by asparke2** [comment]
Confirmed fix with development version, should be closed w/ 2.1.2 release
