### ISSUE TITLE
AWS Workers Stuck in Queued State w/ 4 Core Server

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2518]
m3.xlarge server leaves all worker jobs stuck in queued state.  Ry recommended going to m3.2xlarge which worked.  He may have already fixed this, but putting a ticket in to make sure it doesn't slip through cracks.

**Comment by rHorsey** [comment]
Fixed by https://github.com/NREL/OpenStudio-server/commit/133d7e23637e1ebebd739f2bc94d3b0e64f6aec5
