### ISSUE TITLE
LHS Samples Not Being Respected

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2520]
Number of samples looks to be set to 5 regardless of what is entered.  Other algorithm settings (e.g. DOE samples) do appear to work correctly.

**Comment by kflemin** [comment]
this should be fixed:
https://github.com/NREL/OpenStudio-PAT/commit/c9034a6db9d213863059c95e4dd40f4e22d03d01

**Comment by ljbrackney** [comment]
Verified!
