### ISSUE TITLE
Results Tab Not Working on Cloud Run

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2521]
Cloud algorithm run completes normally.  Downloaded data points and verified that OpenStudio Results measure did run in the workflow.  Results tab says all autogenerated points did not include the OpenStudio Results measure -> No summary report.

**Comment by asparke2** [comment]
@ljbrackney In algorithmic mode, the datapoint.osw information does not get included in the pat.json (and therefore does not get passed to the Project Reports tab) b/c the datapoint.osw format has too much information which would easily fill up memory for large runs.  The intent, which @kflemin is working on, is for PAT to pass the results and metadata CSVs to the project reports tab for algorithmic runs. I don't know that I'll have enough time to build a project report to read this data in time for the release.  @kflemin I think this means we need to pass another piece of data (Manual vs. Algorithmic mode) to the project reports so we can at least notify users that the project reports don't work in Algorithmic mode.

**Comment by ljbrackney** [comment]
Thanks for clarifying.  It's kind of hard to rapidly see what's going on across an analysis without the server plots working.  At a minimum, the reports tab needs to provide alternative guidance to the user, so I'll leave this issue open.

**Comment by ljbrackney** [comment]
Another thought.  Would it be worth embedding a link to the results csv in the results window for algorithm runs?

**Comment by asparke2** [comment]
Yeah that's probably a good idea

**Comment by ljbrackney** [comment]
Moved to 2590
