### ISSUE TITLE
PAT is orphaning measure manager processes

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2524]
openstudio processes are not being shutdown correctly (on Mac at least).  Just found out I had a dozen or more processes hanging out in the background when I went to add a new measure to a project and it wouldn't let me.  Killed processes and things were okay again.

**Comment by macumber** [comment]
I haven't really been involved with PAT starting and stopping measure manager.  Not sure if this would be a @rHorsey or @kflemin thing?  Or a @kbenne thing?

**Comment by ljbrackney** [comment]
Ok.  I added Kat to this.

**Comment by kflemin** [comment]
Can you provide a sequence of events that would reproduce this?  (Do you open and close pat right away?  Is the app also open?  etc..)  thanks!

**Comment by ljbrackney** [comment]
After discussing this with Kat, I suspect the openstudio tasks were actually orphaned by the App when I was debugging segfaults in an earlier package.  Measure management in the App doesn't seem to care about orphaned openstudio processes, whereas PAT can't deal with it.  I'm going to close this issue, but we may want to document that in a known issue or put a Q/A on Unmet Hours about it.  It WILL happen to people.

**Comment by macumber** [comment]
Do the orphaned measure managers cause a problem or is it just that they exist?  At some point we may want a measure manager service (one for all processes to share) but that would require a good bit of hardening

**Comment by ljbrackney** [comment]
They do cause a problem for PAT.  The measure manager dialog in PAT can't find any measures if there are orphans.  That's the clue there's a problem. OS App doesn't seem to care one way or another.

**Comment by macumber** [comment]
Hmm, so any orphan measure manager prevents PAT from being able to use its measure manager?

Can you use PAT's measure manager if the App (and its non-orphaned measure manager) are running?

If you start a random measure manager on some random port (e.g. openstudio measure -s 3030) will that break PAT?

**Comment by ljbrackney** [comment]
You can have the App running along with PAT.  If you start getting multiple orphans things break down in PAT.  You can probably test that by killing the App repeatedly while stopping and starting PAT and checking measure functionality.  The failure mode in PAT is that the measure manager will be empty regardless of which sources or categories are checked.
