### ISSUE TITLE
ResultsViewer button in App starts RV but doesn't load data

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2525]
RV launches, but doesn't automatically open the correct sql file.  Manually navigating to the sql file and opening it works okay.

**Comment by macumber** [comment]
@ljbrackney this is working for me on windows, both right after I run and when I re-open a previously run osm.  

Have you tried both of these cases?  Does it not work in either case?  If it only doesn't work right after the run I would guess that the automatic save that is supposed to happen after a run isn't happening.  If neither case works I would guess that this is a Mac only thing.

@kbenne FYI

**Comment by ljbrackney** [comment]
I tested it on a previously run and saved model.  I can check it with a fresh run tomorrow.

On Mar 16, 2017, at 8:50 PM, Dan Macumber <notifications@github.com<mailto:notifications@github.com>> wrote:


@ljbrackney<https://github.com/ljbrackney> this is working for me on windows, both right after I run and when I re-open a previously run osm.

Have you tried both of these cases? Does it not work in either case? If it only doesn't work right after the run I would guess that the automatic save that is supposed to happen after a run isn't happening. If neither case works I would guess that this is a Mac only thing.

@kbenne<https://github.com/kbenne> FYI

-
