### ISSUE TITLE
joinAll method sometimes doesn't include all surfaces

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2527]
Hit this making a measure to join all ground exposed surfaces
https://github.com/UnmetHours/openstudio-measures/blob/master/get_lat_long_from_ground_exposed_floors/measure.rb#L107

Test model shown has 4 zones, with the south zone split into 5 surfaces.
https://github.com/UnmetHours/openstudio-measures/blob/master/get_lat_long_from_ground_exposed_floors/tests/get_lat_long_from_ground_exposed_floors_test.rb

This image shows the non-joined spaces
![screen shot 2017-03-20 at 12 40 40 pm](https://cloud.githubusercontent.com/assets/4857055/24132044/05eb02e0-0db8-11e7-9834-284d1e884ac9.png)

This shows what it looks like after joinAll
![screen shot 2017-03-20 at 12 44 35 pm](https://cloud.githubusercontent.com/assets/4857055/24132052/142c7c30-0db8-11e7-8836-f501136d356d.png)

I was surprised that if I change order that the polygons are passed in, the results changed
```combined_polygons = OpenStudio.joinAll(floor_polygons.reverse, 0.01)```
![screen shot 2017-03-20 at 12 47 13 pm](https://cloud.githubusercontent.com/assets/4857055/24132080/525bbd90-0db8-11e7-9286-0f9015ecb8c5.png)

I looped through joinAll multiple times when shifting the order polygons. Works a number of test cases, but not ideal.
https://github.com/UnmetHours/openstudio-measures/blob/master/get_lat_long_from_ground_exposed_floors/measure.rb#L114-L118

This isn't something we need in 2.1 release.
@asparke2 since you use this for daylighting area in standards, may want to see if it is affecting that functionality.

**Comment by jmarrec** [comment]
I'm having trouble reproducing the issue. when I call joinAll on the floor polygons of the model, I logically get a result that's a perfect rectangle:

![image](https://user-images.githubusercontent.com/5479063/121382389-d8601000-c946-11eb-91f9-44870be71cdc.png)


Here's the ruby code I used to test it out, with the linked example_model.osm: https://raw.githubusercontent.com/UnmetHours/openstudio-measures/master/get_lat_long_from_ground_exposed_floors/tests/example_model.osm

```
include OpenStudio::Model

def osload(path)
  translator = OpenStudio::OSVersion::VersionTranslator.new
  ospath = OpenStudio::Path.new(path)
  model = translator.loadModel(ospath)
  if model.empty?
      raise "Path '#{path}' is not a valid path to an OpenStudio Model"
  else
      model = model.get
  end
  return model
end

model = osload('example_model.osm')
#model = osload('secondary_school.osm')

lat = 39.7392000000

lon = -104.9903000000


# Identity matrix for setting space origins
m = OpenStudio::Matrix.new(4,4,0)
m[0,0] = 1
m[1,1] = 1
m[2,2] = 1
m[3,3] = 1

# target origin for all spaces
m[0,3] = 0.0
m[1,3] = 0.0
m[2,3] = 0.0


model.getSpaces.each do |space|
  space.changeTransformation(OpenStudio::Transformation.new(m))
end

# loop through surfaces
floor_polygons = []
starting_footprint_area = 0.0
model.getSurfaces.each do |surface|
  next if not (surface.outsideBoundaryCondition == "Ground" || surface.outsideBoundaryCondition == "OtherSideCoefficients")
  next if not surface.surfaceType == "Floor"
  puts "#{surface.name} is a ground exposed floor"
  starting_footprint_area += surface.grossArea

  # add to polygons
  new_floor_polygon = []
  surface.vertices.each do |vertex|
    new_floor_polygon << OpenStudio::Point3d.new(vertex.x, vertex.y, 0.0)
  end
  floor_polygons << new_floor_polygon

  # loop through vertices
  vertex_array_lat_long = []
  surface.vertices.each do |vertex|
    point_lat_lon = OpenStudio::PointLatLon.new(lat, lon, 0.0)
    vertex_array_lat_long << point_lat_lon.fromLocalCartesian(vertex)
  end

  # if we want to see lat long of space surfaces
  vertex_array_lat_long.each do |i|
    #puts "[#{i.lon},#{i.lat}],"
  end

end

combined_polygons = OpenStudio.joinAll(floor_polygons, 0.01)

puts "combined_polygons.size=#{combined_polygons.size}"

m2 = Model.new
combined_polygons.each do |polygon|

  space = Space::fromFloorPrint(polygon, 3, m2)

end

m2.save('after.osm', true)

m3 = Model.new
puts "combined_polygons.size=#{combined_polygons.size}"
combined_polygons.reverse.each do |polygon|

  space = Space::fromFloorPrint(polygon, 3, m3)

end

m3.save('after_reversed.osm', true)
```

I'm going assume this is fixed until @DavidGoldwasser can help reproducing a potential bug.
