### ISSUE TITLE
PAT won't download datapoint zip on Mac

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2529]
@rHorsey It looks like your Windows vs. Mac differentiation for the datapoint zip file never got merged:

https://github.com/NREL/OpenStudio-server/blob/dockerize-master/server/app/controllers/data_points_controller.rb#L360

**Comment by ljbrackney** [comment]
Can this be closed?

**Comment by asparke2** [comment]
If you open a PAT project and look inside `/localResults/12345...` do you see a `data_point.zip` file?  If you do, and you can successfully open up the .zip and look at the files inside, then this can be closed.

@rHorsey It looks like PAT is now [wired up](https://github.com/NREL/OpenStudio-PAT/blob/0aeaf99c918e91bc094a83da13a92230ecc0e6e8/app/app/project/osServerService.js#L1452) to [download_result_file](https://github.com/NREL/OpenStudio-server/blame/develop/server/app/controllers/data_points_controller.rb#L369) instead of [download_report](https://github.com/NREL/OpenStudio-server/blame/develop/server/app/controllers/data_points_controller.rb#L350).  Based on the code, I don't think that `download_report` would work correctly on Mac or Linux.  I think that [this line](https://github.com/NREL/OpenStudio-server/blame/develop/server/app/controllers/data_points_controller.rb#L360) needs to be replaced with a platform switch like [this](https://github.com/NREL/OpenStudio-server/blame/develop/server/app/controllers/data_points_controller.rb#L374-L378).  If `download_result` is not deprecated, it probably still deserves this fix.

**Comment by rHorsey** [comment]
Thanks for chasing this down @asparke2 ! https://github.com/NREL/OpenStudio-server/commit/adcf9ade29a1facf05a63b8b7fa7ab7f60de05bf should fix this. I'll not here when it's merged into develop. Let's leave this open until we make you and @DavidGoldwasser new server packages, and have you both test it to make triply sure.

**Comment by rHorsey** [comment]
Merged with https://github.com/NREL/OpenStudio-server/pull/181

**Comment by DavidGoldwasser** [comment]
Tested with 2.1.2 mac today. Me on NREL24a, and @ljbrackney on AWS

**Comment by asparke2** [comment]
@DavidGoldwasser This needs to be tested on a local run.

**Comment by DavidGoldwasser** [comment]
I'm seeing 'datapoint.zip' in "localResults" as well on local manual run.

**Comment by ljbrackney** [comment]
If I understand what Andrew was discussion - he's talking about an algorithmic run that runs on a locally hosted instance of OS Server.  There's really no such thing as a discrete download step for manual mode.  We've tested downloads from AWS and external dedicated servers, but I don't think anyone has tested PAT with a local dedicated server.

**Comment by rHorsey** [comment]
@ljbrackney What are you considering a local dedicated server vs an external dedicated server in the comment above?

**Comment by ljbrackney** [comment]
I understood people wanted verification that this works with a full instance of OS server on the same physical machine. That seems like a seriously cornerish case, and I'm satisfied that downloads are working on Mac for AWS and our own servers.

On Jun 9, 2017, at 2:37 PM, rHorsey <notifications@github.com<mailto:notifications@github.com>> wrote:


@ljbrackney<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fljbrackney&data=02%7C01%7Clarry.brackney%40nrel.gov%7C206d130d31804db3018c08d4af7fbd8e%7Ca0f29d7e28cd4f5484427885aee7c080%7C1%7C0%7C636326410550866534&sdata=3IHnfZCAFQsK5ZyRrR%2BPUwE0DDqaETaWLL%2BJLFkIzk4%3D&reserved=0> What are you considering a local dedicated server vs an external dedicated server in the comment above?

-
