### ISSUE TITLE
Crash on go to results after saving new model

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2530]
- Launch OS app (03/20 installer)
- Save model
- go to results tab

This crashes on mac

**Comment by kbenne** [comment]
The symptom looks really close to this. https://github.com/NREL/OpenStudio/pull/2528 bouncing doc icon is very close to a crash. more than it may seem.

**Comment by DavidGoldwasser** [comment]
Not sure if this is helpful, but if you go to results tab before saving the file it doesn't crash.
