### ISSUE TITLE
Variable distribution plots appear on server as broken links

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2541]
Variable distribution plots from R aren't being generated or aren't where they're supposed to be on AWS or Brian's box.  A typical broken link takes the form of:

http://YourAWSURLhere/assets/variables/58d2a13806e53e0001844802/original/r_samples_plot20170322-1-dv4gwc.png?1490198840

**Comment by rHorsey** [comment]
FYI @ljbrackney This should also have a 2.1.1 milestone. We decided this and the mongo bug were a combination of not-intrusive enough and high risk enough to wait until after the iteration package to patch.

**Comment by rHorsey** [comment]
This is a confirmed static assets issue.

**Comment by ljbrackney** [comment]
Fixed and verified.  Thanks Nick and Ry!
