### ISSUE TITLE
PAT Add Measure - Missing "Category" Filter

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2543]
- OpenStudio Version: 2.0.5
- Operating System: macOS Sierra 10.12.3

When I click on “Add Measures”, it loads the window titled "Building Component Library" (is this really an appropriate title???), and there’s no filter for “Category"

![screen shot 2017-03-28 at 11 22 09](https://cloud.githubusercontent.com/assets/5479063/24399218/58cb3008-13ac-11e7-96ae-0e5dab195bbe.png)

**Comment by eringold** [comment]
There are category filters in the Windows x64 PAT install (v2.0.5).

**Comment by asparke2** [comment]
@ljbrackney Can you confirm that there are indeed categories in PAT 2.X now and close this issue if there are.  They should look something like this:

![image](https://cloud.githubusercontent.com/assets/2009290/25918902/3dd00b84-358a-11e7-98f8-98e4fb276e62.png)

**Comment by ljbrackney** [comment]
Confirmed in 2.1.0 - used in a demo yesterday. :)
