### ISSUE TITLE
PAT arg default value is missing

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2544]
Create a new project, add the attached measure, and add a measure option. Note that Garage Width and Garage Protrusion are blank, whereas they should have default values of 0.0.

[ResidentialGeometrySingleFamilyDetached.zip](https://github.com/NREL/OpenStudio/files/880240/ResidentialGeometrySingleFamilyDetached.zip)

**Comment by DavidGoldwasser** [comment]
I'm seeing this as well in the initial 2.1.0 installer. Here is what I see in the console for an argument

```
vendor-a38330f47a.js:24014 bldg_type_c_fract_bldg_area  value is '', this will most likely cause errors on server(anonymous function) @ vendor-a38330f47a.js:24014(anonymous function) @ app-49b4d77211.js:9567i @ vendor-a38330f47a.js:95091ba @ vendor-a38330f47a.js:103179(anonymous function) @ app-49b4d77211.js:9562i @ vendor-a38330f47a.js:95091ba @ vendor-a38330f47a.js:103179e.exportManual @ app-49b4d77211.js:9508e.exportOSA @ app-49b4d77211.js:9356e.runWorkflow @ app-49b4d77211.js:13044e.warnBeforeDelete @ app-49b4d77211.js:12989fn @ VM674:4t @ vendor-a38330f47a.js:26028i @ vendor-a38330f47a.js:36407$eval @ vendor-a38330f47a.js:27809$apply @ vendor-a38330f47a.js:27909(anonymous function) @ vendor-a38330f47a.js:36412Ye @ vendor-a38330f47a.js:13361n @ vendor-a38330f47a.js:13349
vendor-a38330f47a.js:24014 argument:  Object {display_name: "Building Type C Fraction of Building Floor Area", display_name_short: "bldg_type_c_fract_bldg_area", name: "bldg_type_c_fract_bldg_area", value_type: "double", default_value: ""…}
```

Here is what I see for a variable, warning doesn't show, but still setting value as empty string.

```
arg:  Object {name: "bldg_type_b_fract_bldg_area", display_name: "Building Type B Fraction of Building Floor Area", description: "", type: "Double", required: true…}
```

Issue #2545 may be related to this?

**Comment by DavidGoldwasser** [comment]
@kflemin I'm not sure, but think I'm seeing this on bool arguments as well, but only when the default value is FALSE. I'll do a little more testing on clean project to confirm.

**Comment by DavidGoldwasser** [comment]
I was able to reproduce this with "AddCostPerAreaToConstruction" measure. It has two bool args. One defaults to true and is fine. The other defaults to false (see link below).
https://github.com/NREL/OpenStudio-measures/blob/develop/NREL%20working%20measures/AddCostPerAreaToConstruction/measure.rb#L70-L74 

It gets this error when I run it in project. Was clean project with small office building prototype as seed, and only this measure.
```
"[15:27:32.027894 ERROR] Could not set argument 'demo_cost_initial_const' to value ''
```

Here is view of arguments. I set default doubles and integers that were 0 manually to avoid error with them in current installer.

![screen shot 2017-03-30 at 3 22 02 pm](https://cloud.githubusercontent.com/assets/4857055/24527181/4e0eae16-155e-11e7-973a-753f5daecabc.png)

If I manually check and then uncheck the box, leave the tab, and come back then it shows "false" and the measure runs.

![screen shot 2017-03-30 at 3 34 25 pm](https://cloud.githubusercontent.com/assets/4857055/24527216/750eb2ea-155e-11e7-90ce-6149249f8ca2.png)

**Comment by DavidGoldwasser** [comment]
@kflemin this is working for me with the newest 2.1.0 installer. I did notice that existing files made with older versions may still see this, but a clean project worked as expected. @shorowit I'll close this, but if some reason doesn't work for you on fresh project, let me know.
