### ISSUE TITLE
Optional (string) argument not working as expected in PAT 2.1.0

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2545]
I upgraded the change building location measure to have an optional argument for 'weather_directory'. This was done to make use of the 'runner.findFile' method in OpenStudio to find any files included with the analysis. I tested this in 2.0.5 and it worked fine. I had the epw, ddy, and stat files in the 'weather' directory.
https://github.com/NREL/OpenStudio-measures/blob/develop/NREL%20working%20measures/ChangeBuildingLocation/measure.rb#L94-L118

When I ran the measure without setting 'weather_path' it found the file. PAT 2.1.0 now writes this as an empty string value in the OSW (shown below).

```
    {
      "measure_dir_name": "ChangeBuildingLocation",
      "arguments": {
        "weather_directory": "",
        "weather_file_name": "USA_CA_Chula.Vista-Brown.Field.Muni.AP.722904_TMY3.epw",
        "climate_zone": "Lookup From Known Locations"
      },
      "name": "Change Building Location Chula.Vista",
      "description": "Option 1 Description: Change the building location",
      "measure_id": "d4db4971-f5ba-11e3-a3ac-0800200c9a66",
      "version_id": "a9b8ede7-349b-4899-8ae9-c8eff7d22fae",
      "taxonomy": "Whole Building.Space Types",
      "measure_type": "ModelMeasure"
    },
```

There are very few measure that use optional arguments, and the ones I'm aware of (AEDG HVAC measures) are not an optional string argument, but are optional choice arguments. If we don't want to support optional arguments, I'm happy to change the measure to use the empty string to trigger the use of `runner.findFile'. 

@asparke2 or @macumber any thoughts on this.

I'm fine with fix for this, if any changes are made, to be sometime after 2.1.0. Looking back at 2.0.5 out.osw it appears to skip the argument, doesn't even show up in file. Assume that changed in 2.1.0 as a result of some other bug fix.

**Comment by macumber** [comment]
It would be correct to either omit the key 'weather_directory' or to set the value to nil (whatever JSON wants that to be).  We do not treat empty strings as nil.

**Comment by macumber** [comment]
Depending on where this happens, @rHorsey might also be the person to assign

**Comment by DavidGoldwasser** [comment]
Add overhang by projection factor is another measure with optional argument.

**Comment by kflemin** [comment]
This commit should fix the issue, but please test.
https://github.com/NREL/OpenStudio-PAT/commit/ec26572edb5e71ec4997c6eb073d566ad31e6d0b

**Comment by asparke2** [comment]
Confirmed w/ developer environment.  If an optional argument is not filled in, both the key and the value are left out of the OSA, which the server seems to handle correctly.
