### ISSUE TITLE
OpenStudio 2.0 Ruby inteface mismatch? or missing? from 1.x versions

### ISSUE THREAD

**Issue by miwamasa** [NREL/OpenStudio#2547]
I have been  using ruby interface to manupulate osm.
Some of my existing script does not work under OpenStudio 2.0 enviroment.

For example, following Ems_test.rb reports several errors

OpenStudio / openstudiocore / ruby / openstudio / model / test / Ems_Test.rb 

followings are the two of the errors I found on the Ems_Test.rb
I have corrected manually the first API error, then I encountered the second.

1)API error for "EnergyManagementSystemSensor.new"
 
>  1) Error:
> TestEms#test_ems:
> ArgumentError: Wrong arguments for overloaded method 'EnergyManagementSystemSens
> or.new'.
> Possible C/C++ prototypes are:
>     EnergyManagementSystemSensor.new(openstudio::model::Model const &model, open
> studio::model::OutputVariable const &outvar)
> ......
> 

2)"OpenStudio::Model::Meter" class is missing.

> 1) Error:
> TestEms#test_ems:
> NameError: uninitialized constant OpenStudio::Model::Meter
>     EM_test.rb:50:in `test_ems'

**Comment by asparke2** [comment]
That test should be removed; I believe it was accidentally committed before the development of EMS objects was complete.  As for `OpenStudio::Model::Meter,` it was renamed `OpenStudio::Model::OutputMeter` last June by this PR:  https://github.com/NREL/OpenStudio/pull/2263

**Comment by asparke2** [comment]
@macumber I think that this test file snuck through the ruby code purge, probably from the EMS branch merge, and should be removed.
https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/ruby/openstudio/model/test/Ems_Test.rb

**Comment by macumber** [comment]
Yeah that test should be removed and a new test added to regression repo, @brianlball FYI

**Comment by macumber** [comment]
https://github.com/NREL/OpenStudio/commit/1f84fa7a4ceb4e13473425f92e752ec1d14f6827
