### ISSUE TITLE
Visualize should be defaulted to true for any selected outputs

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2552]
The design as-is has me pick which outputs I want.  Then I get to tell the UI that I REALLY REALLY want them as outputs.  No seriously, make them outputs because I want to see them.

**Comment by kflemin** [comment]
added this feature in commit: https://github.com/NREL/OpenStudio-PAT/commit/5eb1ad9d203f0c8d926ce4ff9293502fc56e4ee8

should also work retroactively for existing projects.

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#15
