### ISSUE TITLE
PAT 2.1.0 datapoint error due to optional arg

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2557]
See attached project file. 

[pat_bug.zip](https://github.com/NREL/OpenStudio/files/906159/pat_bug.zip)

The second measure (Ceiling Thermal Mass) has 4 required double arguments and 4 optional double arguments, which are not provided. The datapoint fails on one of the optional double arguments:
```
[10:12:14.081147 INFO] Setting argument value 'cond1' to '1.1112' 
[10:12:14.081147 INFO] Setting argument value 'cond2' to '' 
[10:12:14.200159 ERROR] Could not set argument 'cond2' to value '' 
```

**Comment by asparke2** [comment]
@shorowit Can you make a separate issue for the second thing?

**Comment by shorowit** [comment]
Done.

**Comment by kflemin** [comment]
should be fixed by this commit: https://github.com/NREL/OpenStudio-PAT/commit/375523b7701096593c3ecabe8a575e8ed5425dc9

**Comment by asparke2** [comment]
Confirmed fixed w/ developer environment.  The optional arguments that aren't filled in are left out of the OSA.
