### ISSUE TITLE
Can't start Amazon server on Windows w/ PAT 2.1.0

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2558]
Tried to start an Amazon cluster, but it never gets past the "starting" icon.  Nothing shows up in the EC2 console.  Based on the developer console output, it appears that there is a problem in setting up the environment variables or reading the credentials yml file.

![image](https://cloud.githubusercontent.com/assets/2009290/24814699/f868121c-1b8f-11e7-8b20-cff1340de7af.png)

**Workaround**

1. Close PAT
2. Open the `pat.json` file (inside your pat project folder) in a text editor
3. Change `"yamlFilename":` 
4. From `"..\\..\\Users\\shorowit\\AppData\\Roaming\\.aws\\my_credential_filename",`
5. To:  `"my_credential_filename",`
6. Open the project in PAT and launch the server

**Comment by shorowit** [comment]
I'm having the same problem. It continues to work on my old laptop but doesn't work on my new laptop.

**Comment by shorowit** [comment]
I got it to work! 

The PAT project on my old laptop had this in the pat.json:
`"yamlFilename": "shorowit",`
while the new laptop had:
`"yamlFilename": "..\\..\\Users\\shorowit\\AppData\\Roaming\\.aws\\shorowit",`

I updated the pat.json file with the line from my old laptop and was able to start an AWS cluster.

@rHorsey

**Comment by asparke2** [comment]
@kflemin made a fix for this that I tested.  It was parsing the slashes in the Windows paths wrong.

**Comment by ljbrackney** [comment]
Feedback from multiple users that this continues to be blocking on Windows.

**Comment by rHorsey** [comment]
This will be an issue until a new build is rolled. That being said, the issue appears to be closed when tested in a development environment. @ljbrackney is it customary for us to close these sorts of issue out at this stage, or wait until a new build confirms the fix to close them out? If the later, should we assign them to the build milestone?

**Comment by ljbrackney** [comment]
Verify before closing please.

On May 24, 2017, at 9:30 PM, rHorsey <notifications@github.com<mailto:notifications@github.com>> wrote:


This will be an issue until a new build is rolled. That being said, the issue appears to be closed when tested in a development environment. @ljbrackney<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fljbrackney&data=02%7C01%7Clarry.brackney%40nrel.gov%7Cc480329aaf434192196008d4a326cf64%7Ca0f29d7e28cd4f5484427885aee7c080%7C1%7C0%7C636312834475279581&sdata=6V6pkQwoQFucTBjOsJ2J5zFPrUJcvKPAMuOISwXgvj0%3D&reserved=0> is it customary for us to close these sorts of issue out at this stage, or wait until a new build confirms the fix to close them out? If the later, should we assign them to the build milestone?

-

**Comment by rHorsey** [comment]
Confirmed by @shorowit
