### ISSUE TITLE
PAT 2.1.0 missing units

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2559]
See attached project file.

[pat_bug.zip](https://github.com/NREL/OpenStudio/files/906534/pat_bug.zip)

There's a bug where units are shown for every other argument in the second measure even though all 8 arguments have units.

![f669b452-1b7b-11e7-8e11-d832ab63b5ef](https://cloud.githubusercontent.com/assets/5861765/24815167/88a61666-1b91-11e7-92c6-12404659ac73.png)

**Comment by asparke2** [comment]
Working with developer build.  Confirmed fixed after updating the measure.
