### ISSUE TITLE
E+ ForwardTranslator should write out non-template IDF for ideal air loads (Bugzilla #1025)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#256]
On 2013-01-02 11:29:40, @macumber wrote:

> We can then deprecate ExpandObjects in our simulation workflows or move it to the end of any idf scripts (if there are any)

**Comment by jmarrec** [comment]
ref #2799

**Comment by macumber** [comment]
Would really like to get rid of ExpandObjects, it requires us to build Fortran which is a whole extra can of worms when adding a new platform

**Comment by jmarrec** [comment]
That shouldn't be too hard given that  there's already code for the actual zone HVAC ideal air load object in both model and forward translate. The only case that leads to the HVAC template version is when you check the checkbox for the zone. 
We'd have to change zone.setUseIdealAirLoads to create an actual model object and place it on the equipment list, similar to what's done for airloopHVAC/availabilityManagerNightCycle

**Comment by jmarrec** [comment]
Still true as of 3.2.0-alpha, permalink:

https://github.com/NREL/OpenStudio/blob/a007b7801e3bb05731f012f585facdd814ef31fb/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp#L677-L684

**Comment by jmarrec** [comment]
Track it down in #3101
