### ISSUE TITLE
intersectSurfaces having inconsistent results on measure test for model articulation

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2560]
I run the same test three times, and get three different results. This test is update to model articulation to allow partial top floors by entering 5.5 vs 6 for number of above grade stories.

In this run of test the right side split non-convex surfaces, and didn't intersect or split non-convex  on the left.

![screen shot 2017-04-07 at 1 23 12 pm](https://cloud.githubusercontent.com/assets/4857055/24817485/decf3a1a-1b99-11e7-8cd8-fa3db91bd883.png)

In another test got similar results although while the right side intersected it didn't split non-convex

![screen shot 2017-04-07 at 1 23 54 pm](https://cloud.githubusercontent.com/assets/4857055/24817496/ec99cf16-1b99-11e7-8a41-80ce4d45b896.png)

Another time also similar to the first. In this case everything on the right did what it should the left side did intersect but didn't split non-convex

![screen shot 2017-04-07 at 1 24 25 pm](https://cloud.githubusercontent.com/assets/4857055/24817500/f21bd0e2-1b99-11e7-9429-849117c3f445.png)

@macumber I haven't committed this code, but I can point you to test and provide OSM's to you.

**Comment by macumber** [comment]
Bummer, I have some hope that upgrading boost might fix some of these things.  

My first question will be why are you generating this weird top floor that doesn't match the other floors footprints?

**Comment by macumber** [comment]
Another option is to do some sorting of spaces and surfaces before matching, that will at least make this deterministic.

**Comment by DavidGoldwasser** [comment]
I updated the number of stories above grade to take any double (1 or greater) vs. just positive integers. This was done for project to model specific tenants from a building that may span full and partial stories

This test happens to use 5.5 stories above grade. My current logic just reduces the floor area of the top story while maintaining the same aspect ratio and x,y origin. I could just change the width or height but not both.

I'm not currently sorting the space going into this vector so I can try that.
`OpenStudio::Model.intersectSurfaces(spaces)`

I thought about running this a few hundred times (via a script) and store metrics of results by looking at surface count and matched surface count. I'm currently just running test in ruby, and not through CLI. I don't think that would make a difference.

Issue #2527 with joinAll popped in my head as something potentially related. It was order specific.

**Comment by gokmartian** [comment]
I think I have a similar version of this problem. My model has two buildings. Different floors of the buildings don't have similar floor plans, as above. Intersection and surface matching completely removes surfaces from one of the surfaces, and creates holes. The other matching surface, as a result, is set to outdoors/roofcieling/ground, instead of getting matched to the adjacent surface. Different holes in other surfaces are created when I intersect and match again.

**Comment by jmarrec** [comment]
@DavidGoldwasser Could you try and reproduce with 3.2.1 or provide models? #4221 may have fixed this...
