### ISSUE TITLE
Apply Measure Now Clears Measures Tab

### ISSUE THREAD

**Issue by adhilton25** [NREL/OpenStudio#2562]
Running a measure in the OS App 'Apply Measure Now' dialog clears all measures in the measures tab in 2.1.0. Tested on multiple computers, on multiple *.osm files, with multiple measures. Even the 'blank' model file initially loaded can exhibit this behavior.

1. Launch the OS App
2. Verify that the 'OpenStudio Results' reporting measure is in the measures tab or drag and drop another measure in
3. Save the *.osm
4. Apply any measure using 'Apply Measure Now'
5. After the file reloads, navigate to the measures tab to find * poof * all the measures cleared

**Comment by adhilton25** [comment]
Is this on the radar for 2.2.0 at all?

**Comment by ljbrackney** [comment]
I don't see commits against it, so I suspect not given that the release is being prepared as I type this.

**Comment by adhilton25** [comment]
Ah, okay, thanks. Guess I'm still on 1.14 for a while longer then ;)

**Comment by macumber** [comment]
Sorry we missed this, it is pretty serious, I just confirmed this still exists in 2.2.0.  I'll label as blocker since it results in data loss.

**Comment by adhilton25** [comment]
No worries, thanks for the update. I really appreciate everything you guys are do!
