### ISSUE TITLE
Pre-run error checking in PAT for algorithmic mode 

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2563]
Sometimes no simulations will run and there are no obvious errors for a user to diagnose the issue.  As we encounter combinations that cause failures, the should be added to this list so they can be addressed in the future.

Error-causing conditions:
1. Need at least 1 argument.  You can't set everything to Pivot to run a full factorial.
2. Need to fill in weighting factors for discrete arguments, even when running full factorial.

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#17
