### ISSUE TITLE
PAT 2.1.0 integer_sequence distribution for pivot variable

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2564]
In PAT 2.1.0, there is no way to specify integer_sequence distribution for a pivot variable using diagonal sampling. This is a blocker for ResStock, as the user would have to type in the individual numbers 1 through 100,00 for example.

(I could have sworn this was implemented, but I don't see it in the released version.)

**Comment by asparke2** [comment]
This is a blocker for ResStock to use OS 2.0

**Comment by rHorsey** [comment]
Fixed by https://github.com/NREL/OpenStudio-PAT/commit/ce7e34122c0d247378ba45aaf7864f006afc5771 - this will be in 2.1.1. Can someone with sufficient privileges close this issue?
