### ISSUE TITLE
Window 2.1 installer sometimes silently quits

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2566]
I'm seeing this on fresh NREL windows 7 machine with this installer from GitHub releases
OpenStudio-2.1.0.fae436fc10-Windows.exe

@macumber has seen something similar on his home machine. This doesn't seem to always happen, not sure what makes specific systems unique. I have deleted and re-downloaded installer, but will try a few more things.

**Comment by DavidGoldwasser** [comment]
@evanweaver maybe just need to re-post installer to GitHub releases?
https://github.com/NREL/OpenStudio/releases/tag/v2.1.0

The installer at link above is 245mb, but when I want to OpenStudio website logged in and downloaded, I get a 314mb installer, which ran fine.
https://www.openstudio.net/downloads

**Comment by ljbrackney** [comment]
I've seen the installer hang on Mac. Very rare. Killing the proc and restarting fixes it.

On Apr 12, 2017, at 8:22 AM, David Goldwasser <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm seeing this on fresh NREL windows 7 machine with this installer from GitHub releases
OpenStudio-2.1.0.fae436fc10-Windows.exe

@macumber<https://github.com/macumber> has seen something similar on his home machine. This doesn't seem to always happen, not sure what makes specific systems unique. I have deleted and re-downloaded installer, but will try a few more things.

-

**Comment by evanweaver** [comment]
This has been rectified, and I have implemented corrective action for the future.

**Comment by macumber** [comment]
Issue was partial packages due to upload failure for posterity sake
