### ISSUE TITLE
SketchUp plugin can't open files with non a-z letters in filepath 

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/OpenStudio#2567]
[From this unmethours question](https://unmethours.com/question/23709/problem-to-save-osm-file/).
User had an **é** in their windows username, which prevented them from opening or saving files to their desktop/documents directories.  Using Sketchup 2017 Make and OpenStudio 2.1.0 (Window 10 64 bits).

I was able to re-create the issue on my machine with an é in a directory name. I can save, but not open the .osm file.

**Comment by asparke2** [comment]
**Workaround**
Don't put special characters in the file path.

**Comment by macumber** [comment]
Also affects OpenStudio Application

**Comment by jmarrec** [comment]
agreed that one should always avoid special characters AND spaces as much as possible (why create some cause for trouble if you can get around it). 

IMHO, what's really problematic is when your username on windows already is setup like this... Save for creating a brand new user, it's a nightmare to change. I've seen this problem pop up on UH a few times already so it's not uncommon.

This may be related to #2832 too (can't double click to open a file with a space in the name)

**Comment by jmarrec** [comment]
I think I fixed the OpenStudio Application problem - NOT the Sketchup Plugin one - in #3207.

**Comment by jmarrec** [comment]
Will test and try to reproduce this bug in current develop, see where we're at nowadays after a few path/encoding issues have been addressed.

**Comment by jmarrec** [comment]
Tried in OpenStudio 2.7.1, opened sketchup, click "Load Model", and selected a model located at `C:\Users\julien\AfolderwithspécialCHar#%ù\test271.osm` and it worked fine.

**Comment by jmarrec** [comment]
Interestingly, OpenStudio::Path.new fails with the example above though (but that's unrelated to this issue)

```
[1] 2832_CannotLoadSpaces(main)> path = "C:/Users/julien/Afolderwithsp\xE9cialCHar#%\xF9/test_model.osm"
=> "C:/Users/julien/Afolderwithsp\xE9cialCHar#%\xF9/test_model.osm"
[2] 2832_CannotLoadSpaces(main)> OpenStudio::Path.new(path)
RuntimeError: bad conversion
from (pry):4:in `initialize'
```

**Comment by macumber** [comment]
The path error is not good and should be captured with ruby and c++ unit tests and an issue

**Comment by jmarrec** [comment]
Opened a specific issue at #3436
