### ISSUE TITLE
Install Instructions page needs to be updated for 2.x

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2568]
http://nrel.github.io/OpenStudio-user-documentation/getting_started/getting_started/#installation-steps

- [ ] SketchUP 2016 needs to change to 2017

- [ ] Ruby version needs to be upgraded.

Maybe be other changes needed as well, but wanted to document this while I was thinking about it.

**Comment by jmarrec** [comment]
I wrote new installation instructions, I assumed the original instructions were in markdown, so I converted the github.io page's HTML to markdown and modified that


# Installation and Introductory Tutorial

This page walks you through installing OpenStudio, the basics of the applications, and the basic workflow.

## Installation Instructions

OpenStudio is supported on Windows 7 – Windows 10, OS X 10.9 – 10.13, and 64-bit Ubuntu 14.04 & 16.04.

**Note: as of version 2.0.0, OpenStudio is no longer available in a 32 bit version.**

OpenStudio 2.3.0 supports EnergyPlus Release 8.8.0, which is bundled with the OpenStudio installer. It is no longer necessary to download and install EnergyPlus separately. Other builds of EnergyPlus 8.8 are not supported by OpenStudio 2.3.0.

OpenStudio 2.3.0 supports Radiance 5.0.a.12, which is bundled with the OpenStudio installer. It is no longer necessary to download and install Radiance separately, and OpenStudio will use the included Radiance version regardless of any other versions that may be installed on the system. Other builds of Radiance are not supported by OpenStudio 2.3.0.

### Installation Steps

#### Download and install SketchUp

1.  The OpenStudio SketchUp Plug-in requires [SketchUp 2017](http://www.sketchup.com/download/all) (not available for Linux), either Make or Pro. The OpenStudio SketchUp Plug-in does not support older versions of SketchUp. SketchUp 2017 is only available as a 64-bit version.

#### Download and install OpenStudio

1.  Login to the [OpenStudio website](https://www.openstudio.net/downloads). Create an account if you don't have one. EnergyPlus and OpenStudio now share a password.
2.  Click "Downloads" at the top of the page.
3.  Choose the installer that matches your operating system. The OpenStudio package contains the following tools:
    *   SketchUp Plug-in
    *   OpenStudio Application
    *   Parametric Analysis Tool(PAT)
    *   ResultsViewer

If you have installed Sketchup 2017 before installing OpenStudio, the OpenStudio Sketchup Plug-in should have been recognized and loaded by Sketchup automatically. If the OpenStudio Plug-in does not automatically load in SketchUp, open the `Window->Preferences->Extensions` window in SketchUp and enable the OpenStudio plug-in if it is listed.


#### Optional - Setup a Building Component Library (BCL) Account

BCL content can now be accessed from within the OpenStudio SketchUp Plug-in and from the standalone OpenStudio application. To take advantage of this integration, you will need to follow the steps outlined here to request a BCL key.

1.  Login to [Building Component Library (BCL)](https://bcl.nrel.gov/). Create an account if you don't have one. Follow the instructions from the email sent to you upon registration and then login.
2.  Click on the `My Dashboard` near the top right of the website.
3.  Copy the text after `API v1.1 key`: then paste the key into the SketchUp Plug-in, the OpenStudio application, or the Parametric Analysis Tool (PAT). **You only need to configure the key in one place and it will be used globally throughout the OpenStudio tools.** Additionally, this key will be maintained when you install updates to OpenStudio.

Enter the key through the OpenStudio SketchUp Plug-in under the menu `Plugins->OpenStudio User Scripts->Building Component Library->Setup BCL Key` and click `OK`. **Or** register the key through the OpenStudio Application under the menu `Components & Measures->Find Components`. If a key is not already registered, it will prompt you for one.

![Key request dialog](../../img/bcl_key_request.png)

#### Optional - Install Ruby

If you plan to use the OpenStudio SDK Ruby bindings via command prompt on Windows, you must install Ruby. OS X already has Ruby installed, but still needs steps 3 to 5 to point Ruby to the OpenStudio ruby bindings.

**Note that as of 2.0.0, OpenStudio nows ships with a [Command Line Interface (CLI)](http://nrel.github.io/OpenStudio-user-documentation/reference/command_line_interface/) that is a self-contained executable which includes everything needed to apply OpenStudio Measures to an OpenStudio Model and run an EnergyPlus simulation**.

1.  Download the [Ruby 2.0.0 x64](http://rubyinstaller.org/downloads/) installer.
2.  Add `C:\Ruby200\bin` (or wherever you installed Ruby) to the PATH environment variable. [Detailed instructions](http://geekswithblogs.net/renso/archive/2009/10/21/how-to-set-the-windows-path-in-windows-7.aspx).
3.  Create a text file with the following text inside:

    `require 'C:\Program Files (x86)\OpenStudio 2.3.0\Ruby\openstudio.rb'`

4.  Save the file as `openstudio.rb` here: `C:\Ruby200\lib\ruby\site_ruby\openstudio.rb` (next to the `2.0.0` folder).

5.  Test your installation by opening a command prompt and typing: `irb` ENTER. Then, type `require 'openstudio'` ENTER. If you see `=> true`, it's working.


```
# Installation and Introductory Tutorial

This page walks you through installing OpenStudio, the basics of the applications, and the basic workflow.

## Installation Instructions

OpenStudio is supported on Windows 7 – Windows 10, OS X 10.9 – 10.13, and 64-bit Ubuntu 14.04 & 16.04.

**Note: as of version 2.0.0, OpenStudio is no longer available in a 32 bit version.**

OpenStudio 2.3.0 supports EnergyPlus Release 8.8.0, which is bundled with the OpenStudio installer. It is no longer necessary to download and install EnergyPlus separately. Other builds of EnergyPlus 8.8 are not supported by OpenStudio 2.3.0.

OpenStudio 2.3.0 supports Radiance 5.0.a.12, which is bundled with the OpenStudio installer. It is no longer necessary to download and install Radiance separately, and OpenStudio will use the included Radiance version regardless of any other versions that may be installed on the system. Other builds of Radiance are not supported by OpenStudio 2.3.0.

### Installation Steps

#### Download and install SketchUp

1.  The OpenStudio SketchUp Plug-in requires [SketchUp 2017](http://www.sketchup.com/download/all) (not available for Linux), either Make or Pro. The OpenStudio SketchUp Plug-in does not support older versions of SketchUp. SketchUp 2017 is only available as a 64-bit version.

#### Download and install OpenStudio

1.  Login to the [OpenStudio website](https://www.openstudio.net/downloads). Create an account if you don't have one. EnergyPlus and OpenStudio now share a password.
2.  Click "Downloads" at the top of the page.
3.  Choose the installer that matches your operating system. The OpenStudio package contains the following tools:
    *   SketchUp Plug-in
    *   OpenStudio Application
    *   Parametric Analysis Tool(PAT)
    *   ResultsViewer

If you have installed Sketchup 2017 before installing OpenStudio, the OpenStudio Sketchup Plug-in should have been recognized and loaded by Sketchup automatically. If the OpenStudio Plug-in does not automatically load in SketchUp, open the `Window->Preferences->Extensions` window in SketchUp and enable the OpenStudio plug-in if it is listed.


#### Optional - Setup a Building Component Library (BCL) Account

BCL content can now be accessed from within the OpenStudio SketchUp Plug-in and from the standalone OpenStudio application. To take advantage of this integration, you will need to follow the steps outlined here to request a BCL key.

1.  Login to [Building Component Library (BCL)](https://bcl.nrel.gov/). Create an account if you don't have one. Follow the instructions from the email sent to you upon registration and then login.
2.  Click on the `My Dashboard` near the top right of the website.
3.  Copy the text after `API v1.1 key`: then paste the key into the SketchUp Plug-in, the OpenStudio application, or the Parametric Analysis Tool (PAT). **You only need to configure the key in one place and it will be used globally throughout the OpenStudio tools.** Additionally, this key will be maintained when you install updates to OpenStudio.

Enter the key through the OpenStudio SketchUp Plug-in under the menu `Plugins->OpenStudio User Scripts->Building Component Library->Setup BCL Key` and click `OK`. **Or** register the key through the OpenStudio Application under the menu `Components & Measures->Find Components`. If a key is not already registered, it will prompt you for one.

![Key request dialog](../../img/bcl_key_request.png)

#### Optional - Install Ruby

If you plan to use the OpenStudio SDK Ruby bindings via command prompt on Windows, you must install Ruby. OS X already has Ruby installed, but still needs steps 3 to 5 to point Ruby to the OpenStudio ruby bindings.

**Note that as of 2.0.0, OpenStudio nows ships with a [Command Line Interface (CLI)](http://nrel.github.io/OpenStudio-user-documentation/reference/command_line_interface/) that is a self-contained executable which includes everything needed to apply OpenStudio Measures to an OpenStudio Model and run an EnergyPlus simulation**.

1.  Download the [Ruby 2.0.0 x64](http://rubyinstaller.org/downloads/) installer.
2.  Add `C:\Ruby200\bin` (or wherever you installed Ruby) to the PATH environment variable. [Detailed instructions](http://geekswithblogs.net/renso/archive/2009/10/21/how-to-set-the-windows-path-in-windows-7.aspx).
3.  Create a text file with the following text inside:

    `require 'C:\Program Files (x86)\OpenStudio 2.3.0\Ruby\openstudio.rb'`

4.  Save the file as `openstudio.rb` here: `C:\Ruby200\lib\ruby\site_ruby\openstudio.rb` (next to the `2.0.0` folder).

5.  Test your installation by opening a command prompt and typing: `irb` ENTER. Then, type `require 'openstudio'` ENTER. If you see `=> true`, it's working.
```
