### ISSUE TITLE
PAT 2.1.0 Analyses Fail w/ No Useful User Feedback Under Some Default Arg Conditions

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2569]
Some PAT projects with no defaults cause a server failure and return an "undefined" state to PAT.  Data points all fail with no useful feedback to the user unless they open the developer console.  Some of the failed default cases I've seen include:

1) Model choice arguments that come unset when changing a seed model
2) Life cycle cost arguments that actually do have 0 as a default, but show up as '' in the debug window for some reason.  Changing the default to 1 appears to fix the problem.

Minimum) PAT should open a dialog stating there's an issue with one or more undefined default values.
Better) PAT would enumerate the undefined default arguments in said dialog window.
Best) would be to harden the server since these conditions should still run in many cases.

The minimum or better cases should be doable without a lot of fuss since there are debug console messages containing exactly this kind of info - it's just a matter of exposing it so a typical user can see it.

**Comment by kflemin** [comment]
added the "better" option and also the analysis will not run if errors are found: https://github.com/NREL/OpenStudio-PAT/commit/31a8a89e125dba126eca831093f22008cb6aff66

**Comment by asparke2** [comment]
Looks like "false" boolean arguments are being incorrectly interpreted as blank.  The error trapping is therefore blocking any run where a boolean argument is set to "false."  When a boolean argument is set to "true," it is correctly interpreted as "true" in the analysis JSON.  Not sure if this is new behavior or if it is existing behavior that is now being brought to light by the error trapping.

![image](https://cloud.githubusercontent.com/assets/2009290/26835280/33c148d6-4a95-11e7-97aa-5713ec3b9e9a.png)

![image](https://cloud.githubusercontent.com/assets/2009290/26835253/1e81f4c0-4a95-11e7-8096-037f44fad800.png)

**Comment by kflemin** [comment]
the evil == operator!  fixed for real hopefully!  https://github.com/NREL/OpenStudio-PAT/commit/8786d4d8f1c0db1f7fbbf476cc06a9426371d6e1

**Comment by asparke2** [comment]
Confirmed w/ developer environment.
