### ISSUE TITLE
Simulation Settings Tab - Some fields on Mac are being truncated (Bugzilla #1026)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#257]
On 2013-01-03 08:48:39, @DavidGoldwasser wrote:

> Created an attachment (id=258)
> Screenshot on app
> 
> Only noticed this on Run Period and Radiance sections. This is on current trunk build. I'm pretty sure it is mac specific but don't have a windows build right now to test with.

Original attachments:
* Screen shot 2013-01-03 at 8.37.52 AM.png (ID 258)

**Comment by evanweaver** [comment]
@DavidGoldwasser your original attachment is not available, so I am unable to compare it to the App's current state. Please verify that you still have the above concerns. If you still have a desire for some GUI changes, we need to have @marj-schott review and approve them, prior to me working on them.

**Comment by DavidGoldwasser** [comment]
Looks good now
