### ISSUE TITLE
PAT ability to rename measures in algorithmic mode

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2571]
In PAT, if you have a measure Foo and duplicate it in algorithmic mode, you get Foo 2, Foo 3, etc. It'd be really helpful for ResStock if you could rename the measure display names in the interface to keep track of things.

@asparke2

**Comment by ljbrackney** [comment]
+1 for renaming capability.

On Apr 13, 2017, at 9:06 AM, Scott Horowitz <notifications@github.com<mailto:notifications@github.com>> wrote:


In PAT, if you have a measure Foo and duplicate it in algorithmic mode, you get Foo 2, Foo 3, etc. It'd be really helpful for ResStock if you could rename the measure display names in the interface to keep track of things.

@asparke2<https://github.com/asparke2>

-

**Comment by shorowit** [comment]
Screenshot of issue:

![image](https://user-images.githubusercontent.com/5861765/26938526-ae9d0e9e-4c31-11e7-8bd4-7fe48d4fcd00.png)

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#19
