### ISSUE TITLE
Odd behavior on measure options grid for bool template

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2574]
This behavior prevents ability to change bool value on anything after the first measure option. Screenshots below walk through the process

<img width="1254" alt="screen shot 2017-04-13 at 11 25 27 pm" src="https://cloud.githubusercontent.com/assets/4857055/25034106/6b343148-20a1-11e7-8eba-f297450ea426.png">
Image above shows new project with measure option made for measure with a number of  bool arguments

<img width="1257" alt="screen shot 2017-04-13 at 11 25 38 pm" src="https://cloud.githubusercontent.com/assets/4857055/25034123/8cae6bf4-20a1-11e7-9c14-ee321866f22b.png">
If you click on a value it changes to a checkbox vs. "true/false" text but will switch back to text if you leave and come back. There is a second box next to it, but acts like mirror of first, both checked or unchecked.

<img width="1258" alt="screen shot 2017-04-13 at 11 26 05 pm" src="https://cloud.githubusercontent.com/assets/4857055/25034147/b1828c3a-20a1-11e7-8ac2-01cdd0991b39.png">
Screenshot above shows view after second measure option added, looks as expected.

<img width="1257" alt="screen shot 2017-04-13 at 11 26 26 pm" src="https://cloud.githubusercontent.com/assets/4857055/25034162/c5e019f4-20a1-11e7-8dd3-342584bd14cc.png">
If I try to alter the bool value on the second measure option the text disappears. If I leave tab and come back still shows as "true". There is no easy way to get it to false without jumping through some hoops. I don't know if this behavior exists at all on windows.

**Comment by asparke2** [comment]
tested and closed using developer setup
