### ISSUE TITLE
OS 2.1.0 SketchUp Plugin Attempts Install in Wrong Directory

### ISSUE THREAD

**Issue by adhilton25** [NREL/OpenStudio#2576]
The installer attempts to install the plugin to C:/ regardless of where the install directory, or more importantly SketchUp is. My local disk drive letter is D:/ and is where SketchUp is installed, but I get an error saying that it couldn't create the folder on C:/, on which I have no drive mounted.

![image](https://cloud.githubusercontent.com/assets/19593469/25139566/e2ba03ce-241a-11e7-9e8a-94c099d1a62f.png)

**Comment by jmarrec** [comment]
Closing as it's outdated. future issues should be opened to https://github.com/NREL/openstudio-sketchup-plugin
