### ISSUE TITLE
Boost error if you try to run simulation with eplusout.err file open (Bugzilla #1028)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#258]
On 2013-01-07 08:38:19, @DavidGoldwasser wrote:

> You can not cancel and re-run the simulation without quitting OpenStudio. This also happens if any other files are open such as scripts or script error files.
> 
> There may be a similar bug already open, but I wasn't sure.

**Comment by evanweaver** [comment]
Fixed. App no opens a copy.
