### ISSUE TITLE
About ParametricAnalysisTool doesn't show proper version number

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2581]
just shows 0.0.1.

For reference, here is what OS app looks like.

![screen shot 2017-04-20 at 8 49 26 am](https://cloud.githubusercontent.com/assets/4857055/25236913/61eb21a0-25a6-11e7-94c4-3562dbdc4b64.png)

**Comment by DavidGoldwasser** [comment]
I thought I had seen this fixed in later 2.1.x, but It is still valid in the 2.2.0 (pre) installer.

**Comment by DavidGoldwasser** [comment]
@evanweaver this is still valid in 2.2.2

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#20
