### ISSUE TITLE
PAT 2.1.0 bug when switching discrete -> integer_sequence

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2582]
All of the discrete textboxes still remain when switching to integer_sequence. Screenshot:

![patbug](https://cloud.githubusercontent.com/assets/5861765/25237423/e06202aa-25a7-11e7-89db-f9b00dedad12.png)

**Workaround**
Click the `X` button to delete the discrete textboxes.

**Comment by shorowit** [comment]
And if you delete all the discrete values, the "+" button still remains.

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#21
