### ISSUE TITLE
Duplicate discrete variables cause server failures

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2588]
Submitting a project with duplicate discrete values causes an untrapped failure on OS Server in the DOE algorithm - and likely others.  @brianlball suggests this is easiest to trap on the GUI client side of the house.  This would be a fairly stupid user error, but it should be trapped if at all possible.

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#23
