### ISSUE TITLE
getString should return empty optional for empty pointer fields (Bugzilla #1033)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#259]
On 2013-01-09 11:56:58, @macumber wrote:

> Currently returns a string which is set to have value ""

**Comment by jmarrec** [comment]
It's sometimes confusing to remember that you have to specifically tell getString to returnInitializedEmpty, but this works as expected

https://github.com/NREL/OpenStudio/blob/d05bc3a9ba090cf986cde56b7616b7dc445ac2f1/src/utilities/idf/IdfObject.hpp#L154
