### ISSUE TITLE
PAT Results Tab Shows Datapoint Errors in Algorithm Mode

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2590]
PAT currently displays datapoint errors on the results tab:

_The OpenStudio Results measure was not included in DOE Autogenerated 1, cannot show results._

Instead it should state that algorithm results aren't available on the reports tab and should be obtained from the server - perhaps with a URL link.

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#24
