### ISSUE TITLE
 GroundHeatExchangerVertical::gFunctions not swigged

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2591]
GroundHeatExchangerVertical::gFunctions did not get swigged and cannot be used in a measure.

@macumber @jasondegraw

**Comment by macumber** [comment]
My suggestion is to create a small struct like class:

class GFunction{
  GFunction(double, double);
  double whateverFirst() const;
  double whateverSecond() const;
}

std::vector<GFunction> gFunctions();

and export the type std::vector<GFunction>

**Comment by nmerket** [comment]
from @shorowit 

> the issue is that these methods work (`addGFunction`, `removeGFunction`, and `removeAllGFunctions`), but the method to obtain the values (`gFunctions`) does not. Which means we can't write a unit test for it in our GSHP model.
