### ISSUE TITLE
Can't run PAT 2.X projects from network drive

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2592]
If your PAT project is stored on a network drive and you open it from that location, the simulations won't run correctly because the analysis won't start.

**Workaround:**
1. Copy PAT project from the network drive to your computer
2. Open the copied PAT project and run simulations
3. Close PAT
4. Copy PAT project back to the network drive

**Comment by rHorsey** [comment]
This issue was moved to NREL/OpenStudio-server#253
