### ISSUE TITLE
PAT 2.1.0 Model generated datapoints have no means of attaching measure taxonomy tags.

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/OpenStudio#2594]
Description of Issue:

In previous versions of PAT (v1.14.0 going back to to v1.9.0), users were able to create a design alternative datapoint by uploading a .osm file. From within the (legacy) PAT GUI, users were then able to tag the model generated design alternative datapoint with (cost) and (measure taxonomy category) pairs. This information was included in the EDAPT .xml export file, and post processed by EDAPT for incentive calculations and automated table generation of results. 

The current version of PAT 2.1.0 does not support the tagging of model generated datapoints with (cost) and (measure taxonomy category) pairs. This prevents PAT users from generating necessary XML data exports, for specific design alternative datapoints that are simply "model generated". 

In conversation with Andrew Parker, the recommended fix is to extend the EDAPT project reporting measure to include a drop-down list item for each measure that is included in a design alternative. These dropdowns would have (inherited) values from the appropriate measure. 

PAT 2.1.0 Users could then attach a cost measure to account for the cost attributres of the model datapoint, and also override the default measure category associated with the cost measure to achieve the desired end. 
 
This requires modifying the EDAPT Export HTML document and re-distributing is via a subsequent PAT release.

**Comment by asparke2** [comment]
Solution is to make the measure category and subcategory editable on the EDAPT export Project Report.  Users will have add generic cost measure, include in design alternative, then set the categories correctly before export.

**Comment by macumber** [comment]
@kflemin should this be moved to PAT repo

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#51
