### ISSUE TITLE
PAT extraneous algorithm setting for Diagonal

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2595]
PAT 2.0 includes an algorithm setting for Number of Samples when using Diagonal sampling, but this value is not actually used. Rather, the number of datapoints is defined by the pivot variables. As this would be confusing to a user, the Number of Samples textbox ought to be removed from the interface.

Not sure if this is true of any algorithms other than Diagonal? @brianlball

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#25
