### ISSUE TITLE
PAT does not filter incompatible (newer) AMIs

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2599]
PAT 2.1.0 shows 2.1.1 AMIs in the choice list for configuring an AWS Cluster.  Need filtering logic in GUI.

**Comment by rHorsey** [comment]
@ljbrackney I'm not sure we actually need to turn this off. Maybe just gray out the text and say 'Not recommended in this version of PAT'? At this point the OSA format isn't changing, save for bug fixes, and this offers a quick and easy way to test code against new OS versions? Unless you've tried this and it's failed, in which case disregard the above as hubristic!

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#26
