### ISSUE TITLE
HVAC Tab - Viewing Loop with lots of hot water reheat objects is very slow (Bugzilla #1034)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#260]
On 2013-01-09 21:37:03, @DavidGoldwasser wrote:

> Created an attachment (id=264)
> Ft. Carson model
> 
> Open attached file, switch to loops tab and then switch to OS:PlantLoop 1. Takes about 2 minutes to show that loop
> 
> much slower than similar air loop.

Original attachments:
- FtCarson_Baseline_092712_b.osm (ID 264)

Keywords: Performance

**Comment by evanweaver** [comment]
Fixed via several optimization efforts.
