### ISSUE TITLE
Ability to skip NA simulations

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2601]
For ResStock, it would be extremely helpful to be able to skip simulations. The context is that we have measures (e.g., apply wall insulation) that only apply to a subset of the building stock (e.g., buildings with uninsulated walls). If the simulation continues without applying this measure, it means we are running a huge number of additional simulations that we don't need to be.

Skipping simulations should work by using:
```
runner.registerAsNotApplicable
return false
```
Using `registerAsNotApplicable; return true` should work as it does now (measure is not applied but simulation continues).

Note that one can of course use `registerError; return false` as a way to not run simulations, but then it becomes really difficult to determine what's a "true" error (e.g., measure syntax error) and what is simply us trying to skip a simulation.

@macumber @rHorsey @asparke2 @brianlball

**Comment by macumber** [comment]
https://github.com/NREL/OpenStudio/commit/97a52031d59c1e0e70b6db20ad424d6be5ac5377

**Comment by macumber** [comment]
https://github.com/NREL/OpenStudio-workflow-gem/commit/77e5a95b3c631278ec1c47c5fce557997b710f2d

**Comment by rHorsey** [comment]
This should be done. Testing it well is difficult until we have 2.1.2 builds, but that should be doable shortly.

**Comment by shorowit** [comment]
Worked well in my tests!
