### ISSUE TITLE
Deal with external volume storage driver

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2605]
Probably best to fix this with Convoy and a 30/30 data-vol/docker-lib solution with thinpool scaling for the remaining 40. Additionally, this would let us back-up and re-provision the mounted fs for simulations, as well as the mongo collections.

**Comment by nmerket** [comment]
Allow me to ask an ignorant question: This solution sounds complicated. What about just increasing the size of the volume and/or making open studio do a better job of cleaning up after itself?

**Comment by rHorsey** [comment]
@nmerket Thanks so much for your 'ignorant' question! For future reader's sake, it's worth noting that making OpenStudio clean up after itself can buy quite a bit of room to run on this issue, and the size of the mount can be manually increased as well concurrently. (Thanks to @phylroy for this realization.) That having been said, it finally occurred to me that a non-thinpool approach to this issue will be non-perfect, but entirely reasonable and stable. I'll try and get it implemented Friday. Thanks!!!

**Comment by rHorsey** [comment]
Will be fixed with https://github.com/NREL/OpenStudio-server/pull/179

**Comment by rHorsey** [comment]
@shorowit can you confirm that this is fixed?

**Comment by shorowit** [comment]
Was able to run ~6000 simulations without hitting this issue. Seems good.
