### ISSUE TITLE
Implement server & worker init & final scripts

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2608]
Necessary for ResStock and ComStock

**Comment by rHorsey** [comment]
Worker is implemented and tested. Server will get implemented next week.

**Comment by rHorsey** [comment]
@shorowit found a lovely bug with *.sh files coming from windows. This has been addressed using dos2unix in https://github.com/NREL/OpenStudio-server/commit/7dc6836f02ba8a450f0438d410091efa4a0c97e1

**Comment by rHorsey** [comment]
Worker looks to be mostly stable. There are some paradoxes in when to apply worker finalization in the workflow, but otherwise the implementation appears solid.

**Comment by rHorsey** [comment]
Worker is being merged in. Sever remains to be done.

**Comment by asparke2** [comment]
Sweet!

**Comment by rHorsey** [comment]
This issue was moved to NREL/OpenStudio-server#248
