### ISSUE TITLE
HVAC Tab - When you add System type 7 and look in edit tab, chiller shows as air cooled (Bugzilla #1035)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#261]
On 2013-01-09 21:42:15, @DavidGoldwasser wrote:

> 1. launch OpenStudio
> 2. Go to HVAC tab and add system 7
> 3. switch to PlantLoop 2
> 4. Select Chiller.
> 5. The system is modeled in the diagram as water cooled, but edit tab shows air cooled.
> 
> Matt also thought that maybe changing this should change model. Or it should be read only?

**Comment by evanweaver** [comment]
Fixed. Verified in 2.4.0.
