### ISSUE TITLE
OpenStudio CLI fails to run properly if not run using absolute path. 

### ISSUE THREAD

**Issue by phylroy** [NREL/OpenStudio#2616]
**OS: Ubuntu 14.04
Openstudio Version : 2.1.1
Component: OpenStudio CLI**

**Issue**:  OpenStudio CLI fails to run properly if not run using absolute path. 

The cli is installed to /usr/bin/openstudio-2.1.1.  When it is invoked from the command line like so

```
export ENERGYPLUS_EXE_PATH=/path/to/energyplus
openstudio-2.1.1 run --debug -w workflow.osw

```

Most basic functionality exists, however if a simulation is required, it will not run the simulation and also complain that there was no SQLite file produced. 

**Workaround**

if a full path is use as the following examples, it will work fine. 

```
/usr/bin/openstudio-2.1.1 run --debug -w workflow.osw
/usr/Ruby/../bin/openstudio run --debug -w workflow.osw

```

**Comment by rHorsey** [comment]
I assumed it was something in https://github.com/NREL/OpenStudio-workflow-gem/blob/develop/lib/openstudio/workflow/util/energyplus.rb but the workaround makes me question this. @phylroy was this on OSX or a Linux flavor?

**Comment by phylroy** [comment]
Hey Ryan,

It was on Linux Ubuntu 14.04

On May 25, 2017 12:08 AM, "rHorsey" <notifications@github.com> wrote:

I assumed it was something in https://github.com/NREL/
OpenStudio-workflow-gem/blob/develop/lib/openstudio/
workflow/util/energyplus.rb but the workaround makes me question this.
@phylroy <https://github.com/phylroy> was this on OSX or a Linux flavor?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NREL/OpenStudio/issues/2616#issuecomment-303917194>,
or mute
the thread

**Comment by phylroy** [comment]
Whoops Henry...damn. early morning....

**Comment by jmarrec** [comment]
9b2a8be did the job on Ubuntu, I no longer need to set ENERGYPLUS_EXE_PATH for the cli to work, and the OS App doesn't complain it can't find hvac_library.osm etc
