### ISSUE TITLE
Custom Output Variables don't make it into analysis JSON properly

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2617]
Output variables that are described in the measure.rb are show up on the analysis JSON with CamelCase "MyMeasure.my_variable_name". But custom outputs typed in PAT by the user come in like "MyMeasure.my_measure.my_variable_name". The variables appear to be fine with values in datapoint JSON files but are not added to csv results or visualizations.

"unmet_hours_during_occupied_heating" in the screenshot below was described in outputs method in measure.rb. "end_use_electricity_heating" was added in PAT GUI based on runner.registerValue name used in the measure. It demonstrates the issue.

![screen shot 2017-05-22 at 11 50 02 am](https://cloud.githubusercontent.com/assets/4857055/26321993/5cba5de6-3ee6-11e7-9e1d-e58a0cbd9ff7.png)

**Comment by DavidGoldwasser** [comment]
Here are some additional screenshots of GUI

![screen shot 2017-05-23 at 9 14 03 am](https://cloud.githubusercontent.com/assets/4857055/26361442/385b0bb4-3f98-11e7-97d0-9526a44bc339.png)

![screen shot 2017-05-23 at 9 14 11 am](https://cloud.githubusercontent.com/assets/4857055/26361449/3c3a44fc-3f98-11e7-9981-28f40231f967.png)

**Comment by kflemin** [comment]
this is fixed with this commit: https://github.com/NREL/OpenStudio-PAT/commit/cecb0452a825b5a51161a54ec647fdf06d8c2edd  

Note that you will have to re-enter old custom outputs as they will not fix themselves.

**Comment by rHorsey** [comment]
@DavidGoldwasser or @asparke2 - Can one of you confirm in a dev PAT environment? Thanks!

**Comment by DavidGoldwasser** [comment]
@henryHorsey If I can borrow someone's dev environment I can test this. My machine isn't currently setup for development.

**Comment by DavidGoldwasser** [comment]
Tested with 2.1.2 installer on mac running on NREL24a
