### ISSUE TITLE
Successive add/delete of Measures in App's Measures Tab Creates Cruft

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2619]
Successively adding and deleting something like the Results Measure produces increasing variants of the Measure in the model's measures directory - each suffixed with an additional " 1"

![measures](https://cloud.githubusercontent.com/assets/2230150/26364163/395c8bdc-3f98-11e7-8410-d6f64a932e39.png)

Deleting the model folder doesn't clear this up - as all of the files are written upon OSM save.  So these Measures are persisting in the OSM somehow.

**Comment by rHorsey** [comment]
@macumber & @kbenne Shout out for the added spaces not causing massive and indecipherable errors!

**Comment by ljbrackney** [comment]
No longer see this behavior.
