### ISSUE TITLE
Any reason for 2x API to support Meter as well as OutputMeter, or should measures using this just change

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2621]
I just updated the one measure I know that uses this.
https://unmethours.com/question/24584/add-meter-bcl-measure-error-os-21/?answer=24598#post-id-24598

If we don't think there are a lot of uses of this (which I expect there are not) then we can just close this, but I thought I'd ping @kbenne, @macumber to confirm that it doesn't need a fix.

This is not a utility bill object, but the EnerygPlus meter output request.

**Comment by rHorsey** [comment]
This is used in several deployed frameworks I'm aware of. Outside of AssetScore, however, I'm unaware of any of them currently intending to migrate to the 2.X suite.

**Comment by macumber** [comment]
We could add in backwards compatible interfaces if that is required, i had a reason not to do this at the time but I can't recall it right now

**Comment by jmarrec** [comment]
This change from `Meter` to `Output:Meter` happened when I did PR #2263

**Comment by macumber** [comment]
Happened before 1.14 which is the LTS version of 1.x

**Comment by jmarrec** [comment]
Given the won't fix label, perhaps this issue should be closed @macumber?
