### ISSUE TITLE
Feature Request: Add actual number of floors to model. 

### ISSUE THREAD

**Issue by phylroy** [NREL/OpenStudio#2628]
Sometimes the number of defined BuildingStory object is not the actual number of floors in the building due to multipliers.  For some standards, and residential buildings that are defined by diff. It would be good for standards work to have this data field added to the model class.

**Comment by shorowit** [comment]
Can you store that information here?
https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-2.1.1-doc/model/html/classopenstudio_1_1model_1_1_building.html#af082f581d4a65c52b3502a5b59ceac2f

**Comment by phylroy** [comment]
I did not see that! Thanks!
