### ISSUE TITLE
HVAC Tab - more meaningful node and mixed air setpoint manager names (Bugzilla #1037)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#263]
On 2013-01-09 21:53:44, @DavidGoldwasser wrote:

> For diagnostic purposes Matt thought nodes and mixed air setpoint managers should be named based on adjacent objects vs. just numeric.
> 
> He thought we should at least do this for templates. He also hit old bug about nodes breaking when objects such as fans are removed from loop. He thought maybe that could self heal, or at least could be part of our pre-flight checking.

**Comment by evanweaver** [comment]
Closed. Works as intended. Please reopen if it is a high-priority feature request.
