### ISSUE TITLE
OS Cloud Management Console pagination bugs

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2630]
See description and screenshots here:
https://github.com/NREL/OpenStudio-server/issues/172

Ry: "I think it's a major-bug"

cc @rHorsey

**Comment by rHorsey** [comment]
Fixed by https://github.com/NREL/OpenStudio-server/commit/ef82945ed6e1c14ca9cc95a006158f562dbe773d - waiting to 2.1.1-p2 build to confirm and close.

**Comment by shorowit** [comment]
Looks good to me.
