### ISSUE TITLE
Issue with Measure Manager in PAT

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2638]
PAT will mark a project measure as broken. Haven't been able to find the inciting incident or step(s), but an existing measure in a PAT project will be indicated as broken and unable to be updated. Running ```openstudio measure -u [measure_dir]```, and then quitting and restarting PAT has worked in the past, but not consistently. 

I currently have a project that refuses to allow me to update the measure even after cleansing it with the cli as above. The measure.xml reports no error, but the broken icon continues to display in PAT.

**Comment by ljbrackney** [comment]
Verified in at least one of my test projects - Prototype measure shows up as broken but project runs fine.

**Comment by rpg777** [comment]
This just in, if you wait long enough after a PAT restart (> 00:01:00), PAT seems to get itself sorted.

**Comment by ljbrackney** [comment]
I'm also seeing measures w/ available updates.  Clicking the update button appears to update it, and the indicator disappears briefly but then comes right back.

**Comment by macumber** [comment]
Few thoughts after meeting with @rpg777:

If you have one measure manager running and you use the CLI (or another instance of PAT/OS App) to update a measure, the first measure manager instance may not be aware of the changes made to the measure.xml by another process (a file checksum test may be required).

The error Rob saw reported comes from here, https://github.com/NREL/OpenStudio/blob/a9720bbcc97bc4d8beb280dfc87126822d40238e/openstudiocore/src/measure/OSMeasureInfoGetter.cpp#L290, his measure was derived from 'OpenStudio::Ruleset::ModelUserScript' rather than 'OpenStudio::Measure::ModelMeasure'.  It is possible that old name is not supported in some context?

**Comment by rpg777** [comment]
I just updated the Measure Writer's Reference Guide to reflect the change in preference for ```OpenStudio::Measure::ModelMeasure``` over ```OpenStudio::Ruleset::ModelUserScript``` for measure class instantiation, BTW.

**Comment by macumber** [comment]
@rpg777 's issue was specific to the "superclass mismatch error" , I am not sure @ljbrackney was seeing that same error.  We'll need more information about how to reproduce/what the actual error is

**Comment by macumber** [comment]
Also note that running measure -u on a measure should only be done while PAT is not running and you may have to add whitespace or make some other change to your measure files to force measure manager to detect a change.

**Comment by ljbrackney** [comment]
MM-related issues I see with regularity:

  1.  Fail to download results measure dialog routinely shows w/ new models in the App
  2.  PAT weirdness with update icons - Downloading an update makes icon go away briefly, but it quickly reappears.

**Comment by macumber** [comment]
Thanks @ljbrackney 

On 1) are you deleting the results measure from your local bcl so it should be re-downloading?

On 2) you should not really be seeing updates available on remote BCL, we are not updating measures there with any regularity.  When you say downloading an update do you mean processing a local update?  Like you changed a measure in my measures directory and want to update it in your project?

**Comment by ljbrackney** [comment]
I haven't deleted it, and I didn't do anything screwy like manually install it outside of the manager.  Do you want me to try that?

I'm saying that I have seen 1 or 2 measures that were identified as having available updates - e.g. DOE prototype and results - that exhibit this behavior.

**Comment by macumber** [comment]
If the results measure is already downloaded and in your local bcl, then there should be no issues adding it to a new model.  Only thing that jumps to my mind is that the measure manager might not be fully started and ready when the results measure is requested which would make this related to https://github.com/NREL/OpenStudio/issues/2613

**Comment by macumber** [comment]
Working with @rpg777 saw some erratic behavior where measure was marked as broken, changing measure by adding whitespace and re-checking for updates cleared the error.  It was possible that measure manager had crashed when measure was first marked as having an error (measure manager did crash on one run of PAT).  Once error is in xml then measure.rb must be updated to cause another refresh

**Comment by ljbrackney** [comment]
I am still seeing the Measure has available update icon in PAT, but it looks like  PAT/MM IS downloading a new version based on timestamps in measure directoryl

**Comment by ljbrackney** [comment]
I found a project with multiple out of date measures and can qualify the above behavior.  The OpenStudio Results measure is the only one that seems to exhibit this behavior.  Other measures that had available updates were updated correctly and the icon disappeared correctly.

**Comment by macumber** [comment]
@kflemin should this be moved to PAT?

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#52
