### ISSUE TITLE
PAT 2.1.1 copy measure creates invalid measure

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2639]
Initial state:
![image](https://user-images.githubusercontent.com/5861765/26943699-b5776338-4c43-11e7-8850-c084c68fd8dc.png)

Click Copy on Apply Upgrade measure:
![image](https://user-images.githubusercontent.com/5861765/26943711-beefd67a-4c43-11e7-8f71-040efde912c2.png)

Try to Add to the project (Error - not unique name):
![image](https://user-images.githubusercontent.com/5861765/26943718-c64e0be4-4c43-11e7-8328-017547a97075.png)

If I now click Copy on either of the Apply Upgrade measures, I successfully get Apply Upgrade2, which can be added to the project.

**Comment by macumber** [comment]
@shorowit i cannot replicate this in my current build

We will put out a new package early this week, can you try to reproduce with that?

**Comment by shorowit** [comment]
Could this have to do with the fact that my measure is called `ApplyUpgrade` and the first copy ends up called `apply_upgrade`?

**Comment by evanweaver** [comment]
@shorowit have you noticed this in 2.2.0?

**Comment by shorowit** [comment]
@evanweaver Yes, I can still reproduce it in 2.2.0.

**Comment by shorowit** [comment]
@evanweaver Still an issue in your latest 2.2.2 build. Here's the debug window:

![image](https://user-images.githubusercontent.com/5861765/30454234-daa73f4a-9958-11e7-9247-46fb3ce79a9d.png)

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#28
