### ISSUE TITLE
Updating measure in PAT doesn't handle new and/or deleted arguments properly.

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2643]
Scenario 1: Measure in PAT project is edited in external repo and a new argument is added. If you update that measure in PAT, it will see that there is an update, but the new argument doesn't show up in the interface. This is true for both manual and algorithmic. If the new argument has a default measure than things will run fine, but the user won't know they are missing the argument but they can't control the value. If the new argument doesn't have a default value then the measure will fail.

Scenario 2: Measure in PAT project edited in external repo and an argument is removed (or renamed). If you update that measure in PAT, it will see that there is an update, but the old argument will still show up in the interface. The simulation will fail because it will try to set arguments for a measure that doesn't exist.

In both Scenarios the work around is to delete the measure from the project, then re add it back. When added back it is now has all of the proper arguments. On a small project this isn't a big deal, but would waste a lot of time on larger project. For manual run you would have to re-make measure options and then update all design alternatives to use the proper measure argument. Error prone and time consuming. In algorithmic mode would need to setup static argument values and variables.

**Comment by DavidGoldwasser** [comment]
@macumber I'm not convinced this is measure manager, I think it is doing it's job, but the PAT project is just keeping what it had when the measure was first imported?

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#49
