### ISSUE TITLE
Cancel run from PAT prevents later analyses from starting

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2644]
1. Start an analysis running (I used 24B) via PAT.
2. Click "Cancel Run" in PAT.
3. The status of this project will change to "completed" on the server.
4. Try to re-run the analysis again via PAT.

Result: A new analysis will be created, but it will stay at status "queued" and will never start running.

Going into the server and clicking "Delete Project" removes the project that is stuck at "queued", but even analyses run after this get stuck at "queued."

This is an issue especially when running on 24A or 24B because it requires them to be restarted in order to start processing projects again.

**Comment by rHorsey** [comment]
This appears to be a PAT interaction only issue. It seems like the cloud console buttons work as expected. I'll work with Kat on finding the difference between the calls to the server.

**Comment by rHorsey** [comment]
It's a get vs post issue apparently. The analysis looks like it's queued in the log, but it's not. 👎 I'm starting by adding in the rails log to the admin screen so I can see the log more clearly, and then I'll compare the jobs queue against the log real time.

**Comment by rHorsey** [comment]
This issue was moved to NREL/OpenStudio-server#247
