### ISSUE TITLE
Solution exception:index out of range: 0 _ energyPlus

### ISSUE THREAD

**Issue by shuet01** [NREL/OpenStudio#2650]
Hi everyone,

I encounter an error when I launch EnergyPlus simulation component : the message show "Solution exception:index out of range: 0". I really don´t know what is the problem with my model, it is a very simple one by the way... I would like next add a downdraft evapoative cooling tower, but next step... Could you please help me to fix this first problem ? It may also be a pb with the installation of the different softwares used ..

![capture_pb_energypluscomponent](https://user-images.githubusercontent.com/29371274/27114407-b91c5d34-50c3-11e7-9804-4717246ed3d6.PNG)

Thank you in advance for your help !

Severine

**Comment by mostaphaRoudsari** [comment]
Hi @shuet01, This is a Honeybee error and not OpenStudio. Post your question yo the [ladybug forum](http://www.grasshopper3d.com/group/ladybug/forum).

**Comment by rHorsey** [comment]
Thanks @mostaphaRoudsari !
