### ISSUE TITLE
Change template for new measures to replace deprecated OpenStudio::Ruleset with OpenStudio::Measure

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2656]
When you click on "Create new measure", the measure template has references to deprecated `OpenStudio::Ruleset::` instead of the new `OpenStudio::Measure`

OpenStudio::Ruleset::ModelUserScript => OpenStudio::Measure::ModelMeasure

OpenStudio::Ruleset::OSArgumentVector => OpenStudio::Measure::OSArgumentVector

OpenStudio::Ruleset::OSArgument=> OpenStudio::Measure::OSArgument

**Comment by shorowit** [comment]
`OpenStudio::Ruleset` is also used in the template unit test, so this should be updated too.

**Comment by DavidGoldwasser** [comment]
I also need to identify proper change for 

```OpenStudio::Ruleset::WorkspaceUserScript```

and 

``` OpenStudio::Ruleset::ReportingUserScript```

Do the changes from them follow the same patten? Replace "UserScript" with "Measure"

**Comment by jmarrec** [comment]
This issue is getting stale when the work appears to have been done already (referenced Pull Request). Maybe it's time to revisit?

**Comment by DavidGoldwasser** [comment]
@macumber did you want to merge that into 2.3 or after?

**Comment by macumber** [comment]
After 2.3 for sure

**Comment by jmarrec** [comment]
I'm closing this issue, the pull request is enough.
