### ISSUE TITLE
Cannot delete Measure Option in PAT

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2657]
OS 2.1.1, macOS Sierra 10.12

Sometimes when I click on the cross to delete a measure option, it stays there (the cross itself disappears). Upon save and reopen, it's still there, but when I do it again, it disappears. It may be when I click quickly on something else after

![screen shot 2017-06-16 at 2 13 30 pm](https://user-images.githubusercontent.com/5479063/27226181-045183e8-529e-11e7-9877-fdacae653eee.png)

**Comment by DavidGoldwasser** [comment]
@evanweaver have you heard any other reports like this. I can't reproduce this on 2.1.2 macOS 10.11.6

**Comment by evanweaver** [comment]
@DavidGoldwasser I've experienced this nor heard of it before.

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#48
