### ISSUE TITLE
SpaceType tab -Using "Flow/ExteriorWallArea" produces a simulation with no infiltration (Bugzilla #1040)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#266]
On 2013-01-09 22:12:28, @DavidGoldwasser wrote:

> Matt used this with a non 0 value in the Flow per Exterior Surface Area field for a Space Infiltration Design Flow Rate object. If instead he chooses "Flow/ExteriorArea" for the calculation method then it does work. It seems there should be another data field for use with the "Flow/ExteriorArea" option.

Keywords: BadSimResults

**Comment by evanweaver** [comment]
Fixed. Tested in 2.4.0.
