### ISSUE TITLE
Cannot quit PAT

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2661]
I am running PAT in developer mode based on instructions from @asparke2.  I cannot quit PAT.  Every time I try to quit PAT I get the message 

    Uncaught Error: EBUSY: resource busy or locked, unlink 'E:\test\skipping\data\db\collection\0-6062630297938895337.wt'fs.unlinkSync @ fs.js:1093rimrafSync @ E:\openstudio-PAT\ap\node_modules\rimraf\rimraf.js:305removeSync @ E:\openstudio-PAT\app\node_modules\fs-jetpack\lib\remove.js:11remove@ E:\openstudio-PAT\app\node_modules\fs-jetpack\lib\jetpack.js:185localServerCleanup @ osServerService.js:1129(anonymous function) @ osServerService.js:1035exithandler @ child_process.js:205emitTwo @ events.js:106emit @ events.js:191maybeClose @ internal/child_process.js:850(anonymous function) @ internal/child_process.js:323emitOne @ events.js:96emit @ events.js:188_handle.close @ net.js:492

then have to kill all child processes

**Comment by asparke2** [comment]
I had seen this in the past, so I made a .cmd script to kill the processes:

```
Taskkill /IM ruby.exe /F
Taskkill /IM mongod.exe /F
Taskkill /IM openstudio.exe /F
pause
```

Not sure why it happened, but it stopped eventually.

**Comment by ljbrackney** [comment]
Haven't seen this on mac with PAT itself, but the OpenStudio process gets orphaned with regularity.

On Jun 19, 2017, at 12:49 PM, asparke2 <notifications@github.com<mailto:notifications@github.com>> wrote:


I had seen this in the past, so I made a .cmd script to kill the processes:

Taskkill /IM ruby.exe /F
Taskkill /IM mongod.exe /F
Taskkill /IM openstudio.exe /F
pause


Not sure why it happened, but it stopped eventually.

-

**Comment by shorowit** [comment]
I see this sometimes. I'm not really sure why it occurs. Here's what I'm seeing in the console:

```
howDebugMessages =  true
app-34e9a91c6c.js:1305 EXIT BUTTON CLICKED?:  true
vendor-ad64e72158.js:24014 Project::modifiedModal
vendor-ad64e72158.js:24014 Resolving modifiedModal()
vendor-ad64e72158.js:24014 Stop Measure Manager Server
vendor-ad64e72158.js:24014 vm.Project: e {$log: Object, jetpack: Object, fs: Object, MeasureManager: e, dialog: Object…}
vendor-ad64e72158.js:24014 vm.Project.projectDir: C:\Users\shorowit\Documents\GitHub\OpenStudio-BuildStock\project_resstock_testing
vendor-ad64e72158.js:24014 stop server command:  "C:\openstudio-2.1.2\pat\ruby\bin\ruby.exe" "C:\openstudio-2.1.2\pat\OpenStudio-server\bin\openstudio_meta" stop_local "C:\Users\shorowit\Documents\GitHub\OpenStudio-BuildStock\project_resstock_testing"
app-34e9a91c6c.js:8301 THE PROCESS TERMINATED
vendor-ad64e72158.js:24014 exit code:  1
vendor-ad64e72158.js:24014 child:  ChildProcess {domain: null, _events: EventHandlers, _eventsCount: 2, _maxListeners: undefined, _closesNeeded: 3…}
vendor-ad64e72158.js:24014 stdout:  E, [2017-06-28T13:34:49.664572 #13424] ERROR -- : Unable to find the local configuration json at C:/Users/shorowit/Documents/GitHub/OpenStudio-BuildStock/project_resstock_testing/local_configuration.json

vendor-ad64e72158.js:24014 stderr:  
app-34e9a91c6c.js:8315 exec error:  Error: Command failed: "C:\openstudio-2.1.2\pat\ruby\bin\ruby.exe" "C:\openstudio-2.1.2\pat\OpenStudio-server\bin\openstudio_meta" stop_local "C:\Users\shorowit\Documents\GitHub\OpenStudio-BuildStock\project_resstock_testing"(…)
vendor-ad64e72158.js:24014 LOCAL SERVER CLEANUP
C:\openstudio-2.1.2\pat\resources\app.asar\node_modules\rimraf\rimraf.js:312 Uncaught Error: EBUSY: resource busy or locked, unlink 'C:\Users\shorowit\Documents\GitHub\OpenStudio-BuildStock\project_resstock_testing\data\db\collection-0-6689766526830274027.wt'
```

**Comment by shorowit** [comment]
I've not observed this issue for a while now.

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#47
