### ISSUE TITLE
Problems with results measure

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2662]
Error 1) Start new PAT project, do not assign seed model, add results measure to workflow.  Get developer message:

    angular.js:14199 measure.seed is undefined. Unable to compute measure arguments.

Should not need a seed model to compute arguments, should use empty model

Error 2) Go to check for updates, results measure shows as having update (even though version id and timestamp match what is on BCL exactly). 

Press update button for results measure, get message:

An update for this local measure is available from the BCL. Update Local BCL and Apply to your Project?

Press update local bcl and project, measure is downloaded and updated in project, checksums and timestamps remain the same

Error 3) Go to check for updates, results measure shows as having update (even though version id and timestamp match what is on BCL exactly).

**Comment by macumber** [comment]
Error 4) press delete button on results measure in workflow, results measure is deleted from Local BCL!

**Comment by macumber** [comment]
@ljbrackney are these similar to what you are seeing?

**Comment by macumber** [comment]
Starting OS App correctly downloaded and applied the results measure to a new osm

**Comment by ljbrackney** [comment]
I've also seen the unable to compute arguments message.  Errors 2 and 3 sound right.  I haven't observed 4, but I haven't tried that either.

**Comment by jmarrec** [comment]
I'm having error 3) all the time as well.

**Comment by macumber** [comment]
@kflemin should this be moved to PAT repo?

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#58

**Comment by kflemin** [comment]
Fixed #1 in 522236aa4c664b625d6a1b4f93f7ace0d261a2b3
