### ISSUE TITLE
App not shutting down correctly

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2665]
App in my most recent installer doesn't always shut down correctly.  It appears to be measure manager related - the app appears to crash reliably if there is an orphaned measure manager process.  I have also seen the app hang during shutdown.  Killing the measure manager process frees the app up, but generates a MM-related error as you might expect.

**Comment by ljbrackney** [comment]
Poking at this further, it appears the issue is related to using menu bar commands too quickly after starting the app.  Quitting causes a crash and orphans MM processes.

**Comment by macumber** [comment]
Are you able to make a video of this? 

@kbenne FYI

**Comment by macumber** [comment]
I don't think the file menu's should be constructed until everything is ready to go after https://github.com/NREL/OpenStudio/commit/c1f5c75f4b67d4af4660ca47be853e1436b47805 but I'm not looking on Mac where the app file bar is handled differently

**Comment by macumber** [comment]
I suspect that if you ask MM to scan a directory with a lot of measures (e.g. measures repo) and you quit the app while this is running there might be issues

**Comment by ljbrackney** [comment]
My BCL directory:

drwxr-xr-x   3 lbrackne  NREL_NT\Domain Users    102 Mar 10 12:20 18c59c3c-d994-46a9-b3eb-39b983b93ef8
drwxr-xr-x   3 lbrackne  NREL_NT\Domain Users    102 Mar 31 13:27 1e29e117-3916-4368-b24d-75da54045956
drwxr-xr-x   3 lbrackne  NREL_NT\Domain Users    102 Mar 10 12:21 28e4e4fb-a10a-4f85-82f9-c4ad2dd3cf12
drwxr-xr-x   3 lbrackne  NREL_NT\Domain Users    102 Mar 10 12:21 298c5638-bd9d-4d6a-9c8a-e0514df4db4a
drwxr-xr-x   3 lbrackne  NREL_NT\Domain Users    102 Jun  8 10:41 34550614-0c87-44db-9252-0ca0915b1e64
drwxr-xr-x   3 lbrackne  NREL_NT\Domain Users    102 Mar 10 12:21 3d7edb7b-aeff-4a59-87f2-138766b48c11
drwxr-xr-x   3 lbrackne  NREL_NT\Domain Users    102 May  9 10:37 3ff4b412-8689-4b11-a588-935c621dc97d
drwxr-xr-x   3 lbrackne  NREL_NT\Domain Users    102 Mar 16 13:37 6e1f34f9-92e1-44ea-9279-de0b9b64f6a1
drwxr-xr-x   3 lbrackne  NREL_NT\Domain Users    102 Apr 18 13:54 92bee759-86ae-4617-92e2-f8e5aa9dc684
drwxr-xr-x   3 lbrackne  NREL_NT\Domain Users    102 May 16 08:30 9b530f72-e5ab-467b-acd6-b5c3458d7b55
drwxr-xr-x   4 lbrackne  NREL_NT\Domain Users    136 Jun 20 08:04 a25386cd-60e4-46bc-8b11-c755f379d916
drwxr-xr-x   3 lbrackne  NREL_NT\Domain Users    102 Mar 10 12:22 aa5fbc1c-4dc2-4a51-84fa-ce5e291f77b6
drwxr-xr-x   4 lbrackne  NREL_NT\Domain Users    136 Mar 20 12:11 be90fd0b-a651-467a-bc8d-29d310b0f937
drwxr-xr-x   4 lbrackne  NREL_NT\Domain Users    136 Mar 20 12:12 c5ab60e9-b8e5-4653-a502-5ed030f1335d
-rw-r--r--   1 lbrackne  NREL_NT\Domain Users  65536 Jun 20 08:06 components.sql
drwxr-xr-x   4 lbrackne  NREL_NT\Domain Users    136 May  3 07:43 d37b7ed5-887a-4d1f-b304-259462eadbe9
drwxr-xr-x   3 lbrackne  NREL_NT\Domain Users    102 Mar 10 12:19 f347ae80-48b4-4c40-bfd4-6c5139b38136
drwxr-xr-x   3 lbrackne  NREL_NT\Domain Users    102 Mar 15 09:51 f4669f10-fda5-489d-8e1c-7ca3c2d40378
drwxr-xr-x   3 lbrackne  NREL_NT\Domain Users    102 May 10 14:33 f8da4150-edc6-0131-66a9-48e0eb16a403
drwxr-xr-x   3 lbrackne  NREL_NT\Domain Users    102 May 10 14:33 faaf0780-edc6-0131-66e1-48e0eb16a403
drwxr-xr-x   4 lbrackne  NREL_NT\Domain Users    136 May  3 07:44 ffdf05ce-34c2-498e-9ca8-4ef8fe3a9af5

Does that look like "a lot?"

**Comment by macumber** [comment]
Shouldn't be, but might be enough.  This could especially occur if you shutdown while on the measures tab

**Comment by ljbrackney** [comment]
That I have done.

**Comment by macumber** [comment]
This might be related for interactions with measure managers launched by PAT https://github.com/NREL/OpenStudio/issues/2663

**Comment by macumber** [comment]
Looks like the cause of this was having two entries for the standard results measure in the local bcl index but one of the results measures was not present on disk (not sure if deleted manually or by software).  This caused issues for this line of code:

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/openstudio_lib/OSDocument.cpp#L1397
