### ISSUE TITLE
Closing App Window on Mac Destroys Menu Options

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2667]
On Mac, clicking the close window button in the App also eliminates all Menu options.  There is no way to open or create a new model at that point and the Quit option is grayed out.  The only recourse is to right click on the App icon to quit.  I'm concerned this may be related to the focus issue with the hidden dialog that Kyle just worked on.  Temporarily assigning to him for a quick look.

**Comment by kbenne** [comment]
yeah. it does sound related.

**Comment by ljbrackney** [comment]
Working correctly in new build.  Thanks!
