### ISSUE TITLE
PAT Shows Updates Available for Measures but Clicking the Update Button Does Nothing

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2668]
When clicking add measures several project Measures indicate that updates are available.  Clicking the update icon brings up the correct dialog stating that a local update is available, but clicking the update button does nothing.  Leaving the Measure Manager window and re-entering shows the Measure still has an available update.

When checking for updates, those Measures and a few others indicate updates are available.  Same behavior for Measures with local updates.  Correct behavior for Measure with BCL update available with the exception that the Measure icon still indicates an update is available even though it just pulled a new one from BCL.  (This is behavior I noted last week in a 2.1.2 build, but persists with today's 2.2.0 build I just made.)

@macumber Note this is a PAT project created prior to me blowing away my BCL yesterday.  I re-added those Measures from the App's Measure Manager.  So they're essentially the same Measure as before (as evidenced by BCL updates not showing up), but the Manager in PAT sees they're out of sync somehow.

**Comment by ljbrackney** [comment]
Further, the project no longer runs.  Had to blow away ALL Measures in the project and rebuild the alternatives. :(  Lesson learned - don't allow OpenStudio to corrupt your Local BCL forcing you to delete it.  Not sure what you want to do with this issue.

**Comment by macumber** [comment]
@kflemin should this be moved to the PAT repo?  Can we reproduce this outside of PAT?

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#53
