### ISSUE TITLE
Prevent user from naming PAT project 'PAT'

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2669]
Currently it's allowed to name your project 'PAT'. The problem is that `pat.json` is overwritten by the ProjectName.json that is created when you run the analysis. Basically you need to trash your entire project and start from scratch (in my case that's 30 min of work gone out the window).

Should forbid the user from naming a project "PAT"

**Comment by shorowit** [comment]
Fixed in 2.2.1. 
https://github.com/NREL/OpenStudio-PAT/commit/1a63d94ed9b8907f59097d1dcd67f54948d59832
