### ISSUE TITLE
SpaceType tab - checking to a new space type object clear out the object in the edit tab (Bugzilla #1041)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#267]
On 2013-01-09 22:23:15, @DavidGoldwasser wrote:

> This is an old issue but one Matt ran across. To show this create a few space types each with design spec outdoor air. Go to one of the two spaces and inspect that object. When you change space types the edit tab doesn't clear out. As a result can inadvertently change the wrong object.
> 
> I checked this in the HVAC tab. When you switch loops the edit tab clears out. Would expect that behavior here. Edit tab doesn't really get used many other places, although there is a similar bug that was added a few days ago for the schedule tab.

**Comment by evanweaver** [comment]
Closed. Correct behavior confirmed in 2.4.0.
