### ISSUE TITLE
PAT 2.1.2 deletes measure from library

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2676]
I removed a measure from a PAT project, and not only was it removed from the project, but the measure was deleted from my measure library. That is not good. Thankfully I have a fairly recent version of it committed on GitHub, but I did lose some changes.

**Comment by DavidGoldwasser** [comment]
@macumber I remember you looking for this happening sometime in the past, but it wasn't something we could repeat. This doesn't happen for me when I delete a measure from a project.

**Comment by macumber** [comment]
Noted in the comments here https://github.com/NREL/OpenStudio/issues/2662

**Comment by macumber** [comment]
It deleted the results measure from my local bcl

**Comment by shorowit** [comment]
Not sure if it's helpful, but here was the full sequence of events:
- Start PAT, load existing project file.
- Click Update Measures button, the measure of interest had an update (as I had made changes to it), update it.
- Click X next to the measure of interest to remove it from the project. (I removed it with the intention of re-adding it so that everything would be fully defaulted.)

At this point, when I went to re-add the measure, it wasn't showing up in the list for adding. Then I realized it was because it was deleted from my library.

**Comment by shorowit** [comment]
Seems to be working OK in PAT 2.2.1 -- haven't been able to reproduce it with a couple tests.

**Comment by ljbrackney** [comment]
@shorowit can you verify that PAT no longer deletes the measure from the project's measures directory?  That's not necessarily horrible, but it does lead to project bloat over time.

**Comment by shorowit** [comment]
Just tried a quick test; it was indeed removed from the project's measures directory.

**Comment by ljbrackney** [comment]
Weird.  It left measures in the project when I tried it on Mac.

**Comment by DavidGoldwasser** [comment]
@ljbrackney I can also confirm that on mac delated measures are not being removed from the projects "measures" folder.

**Comment by kflemin** [comment]
the non-delete on mac should be fixed by: https://github.com/NREL/OpenStudio-PAT/commit/ba3d40e701d15ea7f596ef8826d52f049755da8b  

Scott, I think your bug was probably caused by your garbled measure_dir paths (with both // and \).  The fix above should prevent deletion from your my_measure directory.  If the deletion from the project directory doesn't work, I would suggest that you open pat.json and inspect the measure_dir paths to see if they "look right".
