### ISSUE TITLE
Allow custom analysis name different than PAT project name

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2678]
This is similar to "Analysis Name" in the Run setup section of the analysis spreadsheet. Both on local and cloud runs i may have 10-15 runs with the same name, and it is hard to keep track of them. It isn't reasonable to keep doing save as locally on PAT projects for this. I typically appended some common name with what is unique about that run. When doing QAQC I fix one thing and re-run ,fix another re-run, and look at changes from one run to the next.

There is a "projectName" field at the top of pat.json, but changing that in text editor and saving didn't affect name of analysis on server, and when PAT project is saved "projectName" as revered back to the parent directory name. There is a separate field in pat.json for "projectDir" that gives full path. Not sure if/where "projectName" is used.

**Comment by shorowit** [comment]
+1

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#30
