### ISSUE TITLE
Results Icon in PAT's Run Tab Not Populating Correctly

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2680]
Observed in build with PAT SHA: 23608c48727821d8ac530e142af60ca78d1bbda6

Ran large project on 24a.  Project ran fine w/ point truncation in PAT.  Even when downloading data points and models, the results icon remains grayed out.  The HTML files in the zip are fine.

![results](https://user-images.githubusercontent.com/2230150/27601955-e95a5746-5b25-11e7-8507-b65ba4c4a1c4.png)

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#31
