### ISSUE TITLE
Surface disappears after saving in SketchUp - after using Intersect and Divide Inter-Zone Surface for the entire model

### ISSUE THREAD

**Issue by padmassun** [NREL/OpenStudio#2681]
Hello,

Some surfaces disappear after opening a saved document whose model has its surfaces intersected before the save.

Starting model: https://github.com/NREL/openstudio-standards/blob/47252763df700d5fac194ac98c2a9f69428edb15/openstudio-standards/data/geometry/Geometry.hospital_new.osm
SketchUp Pro 2017 Ver. 17.2.2555 64-bit, Plugin Ver. 2.1.1
OpenStudio Ver. 2.1.1 Build 141d4b9cb6 64-bit
Windows 7 64-Bit

#### Instructions to replicate this issue:

1. After opening the starting model osm file in SketchUp, I `Select all (ctrl + A)` and choose `Surface Matching` option in the OpenStudio Plugin toolbar
2.  Under `Intersect and Divide Inter-Zone Surfaces` click on the `Intersect In Entire Model`
3. Save the model with a new file name
4. Restart SketchUp
5. Open previous saved model and some surfaces disappear.

![image](https://user-images.githubusercontent.com/24966493/27604613-ce4e6f88-5b47-11e7-9ae9-ca3e9f62e946.png)
**Figure 1: Isolated view of Space: `ER_NurseStn_Lobby_Flr_1`**

As shown above, some of the surfaces are no longer there (or rendered). The inspector show that these surfaces exist

After opening, I have saved the file with a different name, and here is the screenshot of the diff. 

![image](https://user-images.githubusercontent.com/24966493/27605019-4657d784-5b49-11e7-9584-81f0df2a22e6.png)

**Comment by DavidGoldwasser** [comment]
@padmassun the SketchUp intersection relies on parts of SketchUp API we don't have control of. Can you confirm if there are issues with the "Intersect Surfaces" option in the Surface matching measure on BCL. This uses just OpenStudio's API.
https://bcl.nrel.gov/node/39833

Here is an UnmetHours post about the measure. The native OpenStudio intersect isn't perfect, but has been more reliable than the SketchUp plugin version, and it also splits surfaces up convex surfaces as needed.
https://unmethours.com/question/909/surface-interaction-and-match-problem/?answer=1146#post-id-1146
