### ISSUE TITLE
PAT order of design alternatives isn't preserved

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2682]
I define the order of my DA because I have good reasons to on the Design Alternatives Tab.
On the Run tab, it's a different order.
On the Results Summary table, it's the order of the Run Tab, but in reversed..

The order defined on the DA Tab should be preserved.

**Comment by jmarrec** [comment]
So I understand jack squat about electron app development nor debugging.

But I was able to test a couple of things.

Project.designAlternatives is the order I have defined and would like to keep.

Project.datapoints is another order (the one in the Run Tab).

On the Summary Results table, Project.datapoints is passed to the webview as $scope.results, and $scope.resultsWithInfo is reversed order from $scope.results.

I don't follow where Project.datapoints is set, but It should be something like:

    For da in Project.designAlternatives:
        if da.isSelected:
            Project.datapoints.append(da)

**Comment by jmarrec** [comment]
Ok I think I understand what's going on, and can propose steps to retrace the behavior.

Create two design alternatives, Alt1 and Alt2, in this order.

Go to the run tab. [runController.js#L199](https://github.com/NREL/OpenStudio-PAT/blob/develop/app/app/run/runController.js#L199), setUpDatapoints is called.

It doesn't find any datapoints currently, so it goes into the loop in #L222 and creates datapoints in the same order as the designAlternatives.

Now go back to the design Alternatives tab, and reorder your alternatives so you have ['Alt2', 'Alt1']

Go back to the run tab. setUpDatapoints is called again, but this time it does find the datapoints corresponding to the da. So nothing is done. The datapoints array is still ['Alt1', 'Alt2'].

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#32
