### ISSUE TITLE
PAT can show incorrect # of datapoints

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2684]
Running 20k simulations via algorithmic mode in PAT 2.1.2.

When PAT refreshes, it sometimes shows a total # of datapoints that is greater than or less than 20k.

![image](https://user-images.githubusercontent.com/5861765/27664156-291f2552-5c23-11e7-8573-483dbb011bc2.png)

![image](https://user-images.githubusercontent.com/5861765/27664157-2c6317b4-5c23-11e7-9e64-fe7c13aaa341.png)

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#33
