### ISSUE TITLE
PAT improvements for Algorithmic projects

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2685]
When you have a project in Algorithmic mode, which therefore only runs on the cloud, there are some annoyances that occur when you open the project:
- The run screen dropdown defaults to "Run Locally". Ideally, you would see the exact same information on the Run screen that you saw when you closed PAT and saved your project.
- The local server automatically starts up (even though you will not be using it)
- You cannot reconnect to an existing analysis on an existing server. If you connect to an existing server, it will want to clear your results and create a new analysis on the server. 

@asparke2

**Comment by ljbrackney** [comment]
+1
+0 - There are use cases where you want to "pre-flight" check analyses locally before committing to the cloud
+1

**Comment by shorowit** [comment]
@ljbrackney Not sure I follow your second point. PAT currently only allows running algorithmic mode analyses on the cloud, doesn't it?

**Comment by ljbrackney** [comment]
PAT was intended to allow tests of the Seed and measures in manual mode prior to switching to algorithm mode.  I have projects where I've configured both and jump between them for testing.

**Comment by shorowit** [comment]
Sure. Presumably PAT would start the local server if you switch from algorithmic mode to manual mode then. And stop it when you switch back.

**Comment by ljbrackney** [comment]
That was not part of the original design spec for PAT.  The assumption was that local server always starts.  Implementing the behavior you describe would be problematic.

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#34
