### ISSUE TITLE
Issues with PAT2.1.2

### ISSUE THREAD

**Issue by snlavu** [NREL/OpenStudio#2689]
I am running into a couple of issues with the new PAT and looking for a solution. Currently using a v2.1.2 with instructions to model via PAT from https://github.com/NREL/OpenStudio/re...

I have posted this earlier on unmet hours and have reduced the issues down to 

First off, the simulations take really long to run- I am running locally but the parent file runs 5 mins but the run time on the parametrics as per the window is 42 mins! 

2-obtaining the results as a incremental from baseline. The window keeps saying that open studio results have not been applied to the specific measures- which is not the case. I applied this and as the measure description goes, this has a basis from SEED model and should apply to eventual parms. The measure has been applied to all the alternatives! 

3- visibility of the generated output reports. It seems like the eplus.tbl(which used to sit in the Energy plus folder for each data point) is now inside a zip folder. This makes it impossible to auto link the results from worksheets! Is there an option to unzip the folder and keep in the local? Also, Is there a way to link the datapoint names and measure name as a excel/ text document? I am aware that this is available on the run tab under each alternative.

5- on the sidelines and i think this might be available somewhere... is the result of the simulation in an excel format for all the runs! Is this sitting in any of the run files? I expected to find this on the localhost URL but could not find useful spreadsheets- I am guessing this is also due to open studio results measure not doing its job in the PAT.

**Comment by evanweaver** [comment]
@snlavu can you email us a PAT project which reproduces issue #2?

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#35
