### ISSUE TITLE
Duplicate Measure, breaks if you then update the measure

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2690]
CC @henryHorsey 

If you duplicate a measure instance named "My Measure" you get one named "My Measure 2" (as described in #2570) and everything works fine, as shown below with "Create Typical Building From Model"

![screen shot 2017-07-10 at 2 40 32 pm](https://user-images.githubusercontent.com/4857055/28039348-2b884d40-657f-11e7-831f-b4de7f12a7d1.png)

If you have to update the measure code in the project, the name of the second instance is re-named back the original name without the numeric suffix as shown below. This prevents the analysis from successfully running. There isn't a way in the GUI to manually re-name the measure instance (#2571) to fix this.

![screen shot 2017-07-10 at 2 43 20 pm](https://user-images.githubusercontent.com/4857055/28039397-6be0c796-657f-11e7-9705-f8c22204a495.png)

Maybe failure is related to Asset Score issue #2629?

**Comment by shorowit** [comment]
Would love to see this worked on. When you have lots of duplicated measures, it creates a real headache.

**Comment by evanweaver** [comment]
@shorowit understood, however now I absolutely must focus on another project for the next week or 2, before Anya is away on maternity leave.

**Comment by shorowit** [comment]
FIxed in 2.2.1. Thanks!
https://github.com/NREL/OpenStudio-PAT/commit/a18f340eb44ecb68875524b236a55dab9d887605
