### ISSUE TITLE
User Reports PAT Local Server Not Starting Reliably on Mac

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2695]
User reports that Ruby processes begin to start and then quit during PAT startup.  Using the Start Server button multiple times eventually resulted in Ruby processes starting and remaining active.  I have requested log files from the user, but here is a screenshot of the developer window in PAT:

![kromer](https://user-images.githubusercontent.com/2230150/28432821-437c56f0-6d3e-11e7-99a5-d427713d3755.png)

**Comment by ljbrackney** [comment]
User logs attached now.

[logs.zip](https://github.com/NREL/OpenStudio/files/1163346/logs.zip)

**Comment by ljbrackney** [comment]
Update: User reports that routinely the server does not start automatically - Ruby processes briefly start then die.  Manually starting the server from the dialog in PAT generally works ok.

**Comment by ljbrackney** [comment]
Failed start:
![unknown](https://user-images.githubusercontent.com/2230150/28472753-9f8c7728-6df6-11e7-9b47-959ca95f886e.png)

![unknown-1](https://user-images.githubusercontent.com/2230150/28472764-b242de02-6df6-11e7-95cd-513223681cbc.png)

After manual start:

![unknown-2](https://user-images.githubusercontent.com/2230150/28472777-be217904-6df6-11e7-8319-247d6e6b6428.png)

PAT works normally after this.

**Comment by rHorsey** [comment]
From the delayed jobs log: 

<img width="791" alt="screen shot 2017-07-26 at 12 54 41 pm" src="https://user-images.githubusercontent.com/9537073/28638300-b39abd6a-7201-11e7-8e52-858fabcca5d4.png">

This should mean that the analysis.json was formed with an different array lengths across the discrete values arrays in which design alternatives are passed. This problem however would not explain the behaviors described above, as it would only be triggered after an analysis is submitted.
