### ISSUE TITLE
Measures that download components from BCL not running properly in local PAT runs

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2696]
I'm using "GetSiteFromBuildingComponentLibrary" in for a porject. This is similar to "Change Building Location" but instead of pointing to epw, design day and state file it takes a zip code and gets site component from BCL.

I have tested this in PAT before on an cloud based manual run (NREL24b) and re-confirmed today that it still works fine.

The screenshot below shows the first local run of a fresh project. The site component being requested was not already in my local library. Notice that the first datapoint worked, but all the others has error that had error about a temporary directory not existing, I confirmed that that directory does in fact not exist. "does not exist, could not be opened". Failed at this line
https://github.com/NREL/OpenStudio-measures/blob/typical_model_articulation/NREL%20working%20measures/get_site_from_building_component_library/measure.rb#L67

![screen shot 2017-07-21 at 10 52 44 am](https://user-images.githubusercontent.com/4857055/28478050-f5f244f4-6e13-11e7-8e86-f7e72892d55d.png)

Next I re-ran it, thinking maybe there was a timing issue where because of first datapoint, it thought component was ready, but it wasn't. Instead of all datapoints working this time, they all failed, but with a different error.
https://github.com/NREL/OpenStudio-measures/blob/typical_model_articulation/NREL%20working%20measures/get_site_from_building_component_library/measure.rb#L70

![screen shot 2017-07-21 at 11 08 59 am](https://user-images.githubusercontent.com/4857055/28478149-55c6394e-6e14-11e7-9cc5-6f8a82ee1651.png)

I did confirm that the component really was in my BCL directory

![screen shot 2017-07-21 at 11 10 10 am](https://user-images.githubusercontent.com/4857055/28478161-61f16fb8-6e14-11e7-8209-bd35dd10303e.png)

Then did a cloud run to see if it has same issue. It ran fine there. The error on the last datapoint was an EnergyPlus failure not related to the site measure.

![screen shot 2017-07-21 at 11 17 58 am](https://user-images.githubusercontent.com/4857055/28478231-ba819f4a-6e14-11e7-999d-62f1b0f7b8c5.png)

**Comment by ljbrackney** [comment]
Can we close this?  Downloads appear to be working.

**Comment by DavidGoldwasser** [comment]
@ljbrackney This wasn't a BCL outage, it was about downloading and using components within a measure. Only made it major because of Get Weather for from zip code used for some model articulation projects. Since it works fine on server, I'm fine having this fixed sometime after 2.3.0.

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#36
