### ISSUE TITLE
Update Object Information window when user uses "Stretch Tool" (Bugzilla #33)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#27]
On 2011-07-01 13:37:28, @DavidGoldwasser wrote:

> Re generate object information data if users uses scale tool on a zone. In the past I recommended against users doing this, but as it turns out it works well, and could be very usefull. Right now the only issue is that you have to save close and re-open the IDF/OSM to get accurate data in the object info window. It would be great if this could update without having to re-open. For now I can just show this in the documentation, but if it can work directly that would be great. I'll put it in first quarter, but it could slide.
> 
> Bug imported from Excel; Status -unknown; Created on - 12/29/10; By - David Goldwasser; Owned by -

On 2011-11-16 09:50:17, @DavidGoldwasser wrote:

> <batch change comment> Moving older bugs to "retest" milestone. Will re-test these and then assign to appropriate milestone. These were all 0.6.0 prior to change.

On 2011-11-17 10:41:16, @lgentile wrote:

> Still potential issue. This was an old bug. Please re-test/verify.

On 2012-01-17 14:20:00, @DavidGoldwasser wrote:

> Moved to enhancement

On 2012-08-28 14:46:24, @DavidGoldwasser wrote:

> Just as an update in this bug. It no longer does work, and users have used this and then had the SketchUp model out of sync with the OSM model. Would be nice to support this.
> 
> See URL for forum post.

**Comment by DavidGoldwasser** [comment]
Not adjusting for transformation of scaled groups.
