### ISSUE TITLE
number of surfaces created by geometry editor translator is not deterministic

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio#2709]
Translation of attached json randomly results in between 100 and 102 surfaces.

[MF_corr_12unit.json.txt](https://github.com/NREL/OpenStudio/files/1195381/MF_corr_12unit.json.txt)

**Comment by macumber** [comment]
Might have been fixed by https://github.com/NREL/OpenStudio/commit/a77efb0c605b583b6511db9c5e95353f7adf91d9

**Comment by DavidGoldwasser** [comment]
@joseph-robertson I can't reproduce this in 2.4.3, but I thought I'd have you test as well before I accept

**Comment by joseph-robertson** [comment]
Can't reproduce.
