### ISSUE TITLE
Save as in App breaks model

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2711]
Model is running fine.  Did a save-as to change the name.  New model runs but report results are jacked up.  (Wrong building name, no square footage, etc.)  Nuking the contents of the model folder, re-adding epw and results measure then re-running fixes it.

**Comment by ljbrackney** [comment]
Good Run:

![report1_720](https://user-images.githubusercontent.com/2230150/28953649-729481c8-788e-11e7-898b-751e0d3b441f.png)

Save-As -> Bad Run:

![pasted_image_at_2017_08_03_09_46_pm_1024](https://user-images.githubusercontent.com/2230150/28953660-836bb368-788e-11e7-8620-55baa8e1111b.png)

**Comment by macumber** [comment]
I just tried to reproduce this by running a small model.  Then I saved as another file, changed weather file, and re-ran; got expected changes in reports.  Next I saved as again, changed building name, and re-ran; got expected changes in reports.  

Can you re-test to see if this is still valid?

**Comment by DavidGoldwasser** [comment]
I can't reproduce this on Mac. I had a model with OpenStuido, E+ and Reporting measures. I ran it, did SaveAs. The new model still had measure and report. I re-ran the simulation and still worked. @ljbrackney on your example was it just the envlope table that was wrong? It either looks like an empty model, or a model that doesn't have en exterior surface or sub-surfaces, not not sure how that happened with the SaveAs.

**Comment by evanweaver** [comment]
Closed due to not being reproducible.
