### ISSUE TITLE
Add Ideal Air Load Column as Multi-Selectable in the Thermal Zones Tab

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2712]
Why no Apply to Selection button for Ideal Air Loads?  Sad.

**Comment by eringold** [comment]
Would also be _really_ nice to be able to apply a deletion to selected.

**Comment by jmarrec** [comment]
@eringold A deletion of?
If ThermalZones, it works already.

**Comment by eringold** [comment]
@jmarrec I think I meant applying the deletion of a piece of equipment/thermostat from a zone to selected zones. Now that I think about it further I'm not sure how that would work in the UI. In any case it's unrelated to the issue at hand.
