### ISSUE TITLE
roofceiling adjacent to outdoors instead of surface after geometry editor translation

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio#2715]
Translation of attached json randomly results in the garage space's ceiling being adjacent to outdoors/surface.

I even tried intersecting/matching.

[SFD_FA.json.txt](https://github.com/NREL/OpenStudio/files/1205256/SFD_FA.json.txt)

**Comment by macumber** [comment]
Might have been fixed by https://github.com/NREL/OpenStudio/commit/a77efb0c605b583b6511db9c5e95353f7adf91d9

**Comment by DavidGoldwasser** [comment]
![screen shot 2018-03-09 at 2 25 23 pm](https://user-images.githubusercontent.com/4857055/37230731-c543d8e8-23a5-11e8-93bc-6758e5e900a0.png)

Using 2.4.3 installer I created 4 stacked spaces in different configurations and re-merged them a few times (making small changes between merges).
