### ISSUE TITLE
SketchUp Plugin can't handle rectangular room with filled in C shaped surfaces

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2717]
https://unmethours.com/question/25757/some-surfaces-are-being-counted-twice-in-the-surface-area/

I user modeling cleanly in the SketchUp plugin can end up with a model with too much floor area, wall etc. In the case of floor not only messes up envelope, but also area based loads and building EUI calculation. There are no warnings when opening this in SketchUp about surfaces being split or surfaces on top of each other, in some cases user may become aware of this through surface matching failure, or warning in EnergyPlus about InterZone Surface Areas not matching, but is easy to imagine it going un-noticed.

I don't know if there is anything we can do to fix this in the SketchUp plugin, but we should make this a test case for the geometry editor to see if it handles it cleanly. 

![screen shot 2017-08-09 at 1 29 10 pm](https://user-images.githubusercontent.com/4857055/29141293-d0f7e2c0-7d0a-11e7-99c5-d42aa0eaeb4b.png)

**Comment by DavidGoldwasser** [comment]
Looks good in Geometry Editor. Below is my workflow and results.

1. Create first story with single rectangle space
2. Create new story with rectangle space matching the first story
3. Create a smaller rectangle that results in C shape
4. Run simulation and inspect floor area to see that nothing is missing or double counting.

![screen shot 2017-08-24 at 12 07 19 pm](https://user-images.githubusercontent.com/4857055/29681834-2f08fdf6-88c6-11e7-9500-74511bd4bd57.png)

![screen shot 2017-08-24 at 12 10 41 pm](https://user-images.githubusercontent.com/4857055/29681838-3478fd36-88c6-11e7-8bd2-482497a8ded4.png)

@macumber I'm fine closing this unless you wanted to test other draw order, but I think as long as the 2d tool doesn't let two spaces on a story occupy the same space, then it should be fine.

**Comment by macumber** [comment]
@DavidGoldwasser I am confused by your first image.  Are those surfaces in the same space or in different spaces?  The floorspace image has two separate spaces.

When I attempted to make two surfaces in one space like what you had drawn, one was characterized as a subsurface

![image](https://user-images.githubusercontent.com/1327850/34899000-70964678-f7b3-11e7-976b-411dbc077a05.png)

**Comment by macumber** [comment]
Assigning back to @DavidGoldwasser to confirm if this is valid and to provide more information on how to reproduce if it is

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/21
