### ISSUE TITLE
PAT hangs when running simulation on the cloud

### ISSUE THREAD

**Issue by nmerket** [NREL/OpenStudio#2719]
When I start a batch simulation using algorithmic mode on AWS, the PAT application runs hot (100% CPU) and then locks up.

Mac OSX 10.11.6 (15G1611)
PAT 2.2.0

@rHorsey

**Comment by nmerket** [comment]
@ejhw @shorowit

**Comment by ejhw** [comment]
For me, PAT was very slow to respond during the 13 hours of runs on AWS, and has been not responding since the runs ended (6 hours).

Mac OS X 10.10.5 (14F2511)
PAT 2.2.1.6d72d84a0d

**Comment by ljbrackney** [comment]
I've seen PAT struggle with very large cloud runs - maxing CPU and essentially hanging.  I don't what it's doing - presumably retrieving completion status messages.

**Comment by evanweaver** [comment]
Added to Pivotal

**Comment by kflemin** [comment]
this should be fixed.

**Comment by shorowit** [comment]
Initial testing on Mac (@ejhw) and Windows (me) looks good.

**Comment by rHorsey** [comment]
Thanks @ejhw !
