### ISSUE TITLE
Third PAT algorithm argument in Morris should be Grid Jump

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2723]
Morris arguments are:

        algorithm: {
          r: 2,
          levels: 2,
          grid_jump: 1,
          type: 'oat',
          norm_type: 'minkowski',
          p_power: 2,
          debug_messages: 0,
          failed_f_value: 1e18,
          objective_functions: []
        }

In PAT UI, the third argument is mis-identified as levels also.  The description "Integer specifying the number of levels that are increased/decreased for computing the elementary effects" is ok

**Comment by kflemin** [comment]
fixed in: https://github.com/NREL/OpenStudio-PAT/commit/e6ee30c1068a6ba98e71c52777e3313d94c8f99d

**Comment by ljbrackney** [comment]
Tested
