### ISSUE TITLE
Surfaces are not matched on merge

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2725]

**Comment by ljbrackney** [comment]
This looks like it's working to me.

**Comment by macumber** [comment]
Ive hit some failures, it's going to be intermittent but the errors did not come through when they did happen, that'll be my standard for this release.  Bulletproof intersection and matching requires geom lib

**Comment by macumber** [comment]
@DavidGoldwasser can you test with Larry's new packages?
