### ISSUE TITLE
Error working on gbXML file after I imported it (Bugzilla #1053)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#273]
On 2013-01-18 00:16:33, @DavidGoldwasser wrote:

> Created an attachment (id=266)
> gbXML file fro m Vasari
> 
> Here are my steps. I'm not sure if I can reproduce it.
> 
> 1. import the attached gbXML
> 2. Switch to render by story
> 3. Run add building story user script
> 4. switch to render by thermal zone (I get the error below)
> 
> Error: #<NoMethodError: undefined method `disable' for nil:NilClass>
> C:/Program Files (x86)/OpenStudio 0.10.0/Ruby/openstudio/sketchup_plugin/lib/interfaces/DrawingInterface.rb:974:in `remove_observers'
> C:/Program Files (x86)/OpenStudio 0.10.0/Ruby/openstudio/sketchup_plugin/lib/interfaces/DrawingInterface.rb:984:in `remove_observers'
> C:/Program Files (x86)/OpenStudio 0.10.0/Ruby/openstudio/sketchup_plugin/lib/interfaces/DrawingInterface.rb:984:in `each'
> C:/Program Files (x86)/OpenStudio 0.10.0/Ruby/openstudio/sketchup_plugin/lib/interfaces/DrawingInterface.rb:984:in `remove_observers'
> C:/Program Files (x86)/OpenStudio 0.10.0/Ruby/openstudio/sketchup_plugin/lib/interfaces/SurfaceGroup.rb:390:in `remove_observers'
> C:/Program Files (x86)/OpenStudio 0.10.0/Ruby/openstudio/sketchup_plugin/lib/interfaces/DrawingInterface.rb:984:in `remove_observers'
> C:/Program Files (x86)/OpenStudio 0.10.0/Ruby/openstudio/sketchup_plugin/lib/interfaces/DrawingInterface.rb:984:in `each'
> C:/Program Files (x86)/OpenStudio 0.10.0/Ruby/openstudio/sketchup_plugin/lib/interfaces/DrawingInterface.rb:984:in `remove_observers'
> C:/Program Files (x86)/OpenStudio 0.10.0/Ruby/openstudio/sketchup_plugin/lib/interfaces/ModelInterface.rb:1197:in `remove_observers'
> C:/Program Files (x86)/OpenStudio 0.10.0/Ruby/openstudio/sketchup_plugin/lib/interfaces/ModelInterface.rb:1197:in `each'
> C:/Program Files (x86)/OpenStudio 0.10.0/Ruby/openstudio/sketchup_plugin/lib/interfaces/ModelInterface.rb:1197:in `remove_observers'
> C:/Program Files (x86)/OpenStudio 0.10.0/Ruby/openstudio/sketchup_plugin/lib/interfaces/ModelInterface.rb:1572:in `paint_now'
> C:/Program Files (x86)/OpenStudio 0.10.0/Ruby/openstudio/sketchup_plugin/lib/PluginManager.rb:247:in `process_events'
> C:/Program Files (x86)/OpenStudio 0.10.0/Ruby/openstudio/sketchup_plugin/lib/PluginManager.rb:245:in `each'
> C:/Program Files (x86)/OpenStudio 0.10.0/Ruby/openstudio/sketchup_plugin/lib/PluginManager.rb:245:in `process_events'
> C:/Program Files (x86)/OpenStudio 0.10.0/Ruby/openstudio/sketchup_plugin/lib/PluginManager.rb:258:in `start_event_processing'
> C:/Program Files (x86)/OpenStudio 0.10.0/Ruby/openstudio/sketchup_plugin/lib/interfaces/DrawingInterface.rb:974:in `call'
> C:/Program Files (x86)/OpenStudio 0.10.0/Ruby/openstudio/sketchup_plugin/lib/interfaces/DrawingInterface.rb:974

Original attachments:
* Project2.xml (ID 266)

**Comment by macumber** [comment]
Can't find this file to reproduce
