### ISSUE TITLE
Opening existing floorplan in editor freezes app

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2730]
Clicking on open floorplan brings up the file menu, but it is completely unresponsive and effectively hangs the app.

**Comment by macumber** [comment]
Do you think it is required to be able to open an external floorplan?  My first inclination would be to hide the buttons allowing open, save, import in the embedded editor.

**Comment by ljbrackney** [comment]
This problem has now moved from the import floorplan button, which was removed, to the editor startup dialog.  Selected import floorplan locks up the app with an unresponsive file system dialog.

**Comment by macumber** [comment]
We do need to support image import so need to keep this open
