### ISSUE TITLE
Units in geometry editor are not tied to OpenStudio App units

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2731]
Units in geometry editor always default to SI regardless of settings in the App.

**Comment by macumber** [comment]
Currently you can't change Floorspace units after creating a floorplan, the primary concern being that changing units after creation would mean that geometry on the grid would no longer be on the grid.

Needs enhancement https://github.com/NREL/floorspace.js/issues/169

**Comment by macumber** [comment]
@ljbrackney I think this is fixed as good as we can for now, when the editor can change units midstream we can revisit a feature request to update the units in the app and reflect that in the editor

**Comment by jmarrec** [comment]
THis is a FloorSpace / OpenStudioApplication thing, I'm closing it here. NREL/floorspace.js#169 will be the point of entry anywawys
