### ISSUE TITLE
Geometry boundary conditions in editor preview are wrong

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2733]
Created simple four space model, set floor to ceiling height, and went to preview.

![geom](https://user-images.githubusercontent.com/2230150/29488639-dcff2388-84c3-11e7-98bc-968ed11d1f89.png)

Two spaces have no floors, and floor height appears to be ignored.

**Comment by ljbrackney** [comment]
I noticed this in the console window - perhaps relevant?

QLayout: Attempting to add QLayout "" to openstudio::PreviewWebView "", which already has a layout
[utilities.geometry.computeTriangulation] <1> Failed to partition polygon
[modelToThreeJS] <1> Failed to triangulate surface  6 with 0 sub surfaces
[utilities.geometry.computeTriangulation] <1> Failed to partition polygon
[modelToThreeJS] <1> Failed to triangulate surface  18 with 0 sub surfaces
[utilities.geometry.computeTriangulation] <1> Failed to partition polygon
[modelToThreeJS] <1> Failed to triangulate surface  7 with 0 sub surfaces

**Comment by macumber** [comment]
Hmm, I think those messages are just related to the preview, possibly why floors are not shown in your preview.  That might be a second issue in addition to the incorrect boundary conditions.

**Comment by ljbrackney** [comment]
Looks good now!
