### ISSUE TITLE
No option to continue editing geometry after merge operation

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2734]
There appears to be no way to continue working on geometry once the floorplan has been merged.  This may be a design decision that assumes a floorplan.json always exists, but it is problematic for workflows involving existing OSMs or procedurally generated geometry that requires modification.  I will enter this as a feature request, but it's potentially a blocking bug.

**Comment by macumber** [comment]
This is not the intent of the design.  If you start in SketchUp or import a gbXML, you will have existing geometry in the model when you first go to the floorplan editor.  In this case you are not able to create a floorplan.

However, if you start a floorplan in an empty model, you will get a floorplan.json file in your companion directory.  If you merge with the current model, do work in the app, then switch back to the floorplan editor it is supposed to reload your floorplan and merge in changes from the current model.  You can make changes to the floorplan and re-merge.  That is the intent anyway.  

Can you describe the steps you are doing and the issue that is preventing you from doing what you want to do?

**Comment by ljbrackney** [comment]
I think we need a means of generating a floorplan.json from osm for legacy models or procedurally generated models.  It may be as simple as a measure to generate a floorplan.json, but I may want to modify these models (particularly procedural ones) without resorting to the PlugIn.

**Comment by macumber** [comment]
I agree, not sure that will be feasible for 2.3.0 though.  I was thinking this would come in 2.4.0.  We may want to revist the procedural generation measures to have them create a floorplan first, then extrude that to the full model.  

For models that start in SketchUp, we can convert to floorplan, but this will be lossy, the first time you merge you will lose any 3D details and a lot of other stuff until we really beef up the OSM->floorplan translator.

**Comment by ljbrackney** [comment]
I think your notion of procedurally creating floorplan.json within the existing measures is a good one, and probably the right thing to do.

I guess I'm less concerned about models that were authored in SU originally.

**Comment by ljbrackney** [comment]
This is probably working as intended.  We need to revisit how Measures like the prototype or articulation measures work in the future - they probably need to generate floorplan.json files as well.
