### ISSUE TITLE
Boundary condition between floors doesn't appear correct

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2738]
Inspecting the boundary condition between floors suggest that it's considered a ground contact surface when it should be an interior boundary.  I'm guessing this is a translation issue and not a drawing issue, although failing to snap to lower floor boundaries could create ledges or overhangs with their own boundary condition issues.

![2nd](https://user-images.githubusercontent.com/2230150/29496328-40131eea-8585-11e7-8c0e-83d3f92e000e.png)

**Comment by macumber** [comment]
Can you make sure you are on the latest commit?  I did add some intersect and merge code which you can see in https://github.com/NREL/openstudio-geometry-editor/issues/150.  We probably do need some feedback, especially if the intersections fail.

**Comment by ljbrackney** [comment]
I am testing a build from Friday night.  I just updated and will rebuild - that will take my hamsters a while...

**Comment by macumber** [comment]
K, it might well be that the code is there just not working, I just wanted to make sure we were on the same place.  Thanks for kicking the tires!

**Comment by ljbrackney** [comment]
Working nicely!
