### ISSUE TITLE
Default sets in building tab aren't pre-loaded

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2739]
This should be marked as severity - Minor Nitpick.  Assigning default sets in the building tab prior to creating constructions has no effect on new spaces that are created - they should inherit sets from floor or building.  Perhaps this hasn't been implemented yet?

**Comment by macumber** [comment]
Just trying to be clear on this, you are setting a default construction set at the building level in the app, then going to the geometry editor and new spaces drawing in the editor are not inheriting the construction set.  That is the issue?   You are right that is not yet implemented.  When you merge back to the model, the OSM spaces should show the inheritance.

**Comment by ljbrackney** [comment]
That is the issue.

**Comment by macumber** [comment]
Waiting on https://github.com/NREL/openstudio-geometry-editor/issues/89

**Comment by jmarrec** [comment]
Still true in 2.9.0 (and current develop)
