### ISSUE TITLE
PAT Doesn't Correctly Skip Measures When Selected Points are Re-Run

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2742]
Selecting and running or re-running a point does not correctly skip measures.  Here are my data points:
![points](https://user-images.githubusercontent.com/2230150/29585105-cb444852-873a-11e7-8fd1-d3f4cf20a348.png)

Note that this point is ok:
![ok](https://user-images.githubusercontent.com/2230150/29585112-d6ca69f4-873a-11e7-9af0-613cb2be75e6.png)

But this one doesn't skip measures correctly:
![notok](https://user-images.githubusercontent.com/2230150/29585128-e58ec610-873a-11e7-9487-2cd361906c44.png)

**Comment by ljbrackney** [comment]
Also note that the measure output messages in the selected point are jumbled up as well.  So this problem isn't just effecting the skip behavior.

**Comment by ljbrackney** [comment]
This problem persists in the 2.2.1-a7095b553a build

**Comment by kflemin** [comment]
@ljbrackney, would you mind sending me this project so I can test with it?  thanks!

**Comment by kflemin** [comment]
This is fixed.  Note that when single datapoints are rerun, only the measures included in that datapoint are sent to the server.  The results in the datapoint will not show the measures that were skipped b/c they were never sent to the server.  See example below:
![image](https://user-images.githubusercontent.com/2205659/30342529-727153a4-97b7-11e7-9518-4ca9d2c3d87a.png)

**Comment by ljbrackney** [comment]
Perfect!

**Comment by kflemin** [comment]
@ljbrackney, can we close this one?
