### ISSUE TITLE
Going to Preview Tab throws away unmerged changes

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2745]
If you have un-merged changes and go to "Preview" tab you loose them. I know users should go to the "Preview" button next to "Merge" instead, but if you don't think of that you lose your work without any warning.

Would be nice to at least have a warning dialog pop up, or maybe don't let them click it until a merge, assuming there is some way to see if it is dirty.

The same behavior is true if you click on any other major OS app tab and go back to editor.

**Comment by macumber** [comment]
It shouldn't lose changes, they should be saved in the floorplan json file when you leave the tab and reloaded when you come back.  If you are not seeing that then this is a bug.

**Comment by DavidGoldwasser** [comment]
I'm not seeing that

**Comment by macumber** [comment]
Having an unmerged space appears to crash the app
