### ISSUE TITLE
Prevent PAT from running projects with zero variables

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2746]
It's not clear what's happening when projects with zero variables fail to run, and a dialog saying PAT doesn't allow that configuration would be helpful.  A legitimate use case that users might attempt (I did) is to set up a Seed, weather file, and reporting measure just to test out the baseline before adding additional measures and variables.

**Comment by brianlball** [comment]
Can that case get defaulted to the single_run method?  Thats what it was designed to do.

**Comment by kflemin** [comment]
would 'single_run' be ok to run locally?

**Comment by brianlball** [comment]
i think so.  It doesnt use R at all

**Comment by kflemin** [comment]
ok, i'll give it a shot

**Comment by ljbrackney** [comment]
You should do whatever is easiest and lowest risk.  If popping up a dialog saying "You need at least one variable to run in PAT you schmuck!" is easy, that's fine too.

**Comment by kflemin** [comment]
I tried 'single_run' and that didn't work (0 datapoints were created).  So I added error handling instead: https://github.com/NREL/OpenStudio-PAT/commit/864efb67cbc34732202550395f3d07c1d882b080

**Comment by ljbrackney** [comment]
Tested
