### ISSUE TITLE
Levels in Morris Method Must be >1

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2748]
Number of Levels in Morris method must be at least two or R pukes out nonsensical points.  Please put a lower limit on that parameter in PAT.

**Comment by kflemin** [comment]
added error handling: https://github.com/NREL/OpenStudio-PAT/commit/6372f3051772e9fa81f1b192e27a43c85801f6ef

**Comment by ljbrackney** [comment]
Tested
