### ISSUE TITLE
EMS:Sensor constructor with OutputVariable should get the KeyValue 

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2750]
```ruby
$ puts var

OS:Output:Variable,
  {7b02eb4e-6db3-4ef1-ab65-8cea7206c6d8}, !- Handle
  Output Variable 1,                      !- Name
  AUXCW Supply Pump Outlet Node,          !- Key Value
  System Node Temperature;                !- Variable Name
```

```ruby
$ ems_sensor = OpenStudio::Model::EnergyManagementSystemSensor.new(model, var)
$ puts ems_sensor

OS:EnergyManagementSystem:Sensor,
  {601fc17c-17ff-4005-bc7e-bcc64ab11b79}, !- Handle
  Energy_Management_System_Sensor_1,         !- Name
  ,                                       !- Output Variable or Output Meter Index Key Name
  {7b02eb4e-6db3-4ef1-ab65-8cea7206c6d8}; !- Output Variable or Output Meter Name
```

Related links:

* EMSSensor's [constructor](https://github.com/NREL/OpenStudio/blob/2e71acadf03eb258ca9297679d3b21d96163686b/openstudiocore/src/model/EnergyManagementSystemSensor.cpp#L182)

* [EnergyManagementSystemSensor.new::setOutputVariable](https://github.com/NREL/OpenStudio/blob/2e71acadf03eb258ca9297679d3b21d96163686b/openstudiocore/src/model/EnergyManagementSystemSensor.cpp#L125)

* [Forward Translator](https://github.com/NREL/OpenStudio/blob/4bbc02abe49616fefc2952c84cb6dca5edc32284/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateEnergyManagementSystemSensor.cpp#L98)

Currently this is going to output a sensor without a Key, while my OutputVariable does have a Key. I would have expected it to carry the Key to the EMS Sensor

I'm not sure if you want to fix that in the constructor, the setupOutputVariable or the forward translator, but currently it doesn't work and it's a bit "unclear". 

Note: for clarity purposes, I'm actually doing it this way right now:

```ruby
ems_sensor = OpenStudio::Model::EnergyManagementSystemSensor.new(model, var.variableName)
ems_sensor.setKeyName(var.keyValue)
```

**Comment by brianlball** [comment]
use the setKeyName function
https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/EnergyManagementSystemSensor.hpp#L87

**Comment by jmarrec** [comment]
I am already.

But if you set to an OS:OutputVariable object instead of using strings, then it should get the right fields...

Envoyé de mon iPhone

**Comment by brianlball** [comment]
added this functionality to https://github.com/NREL/OpenStudio/pull/2890
the outputvar key cannot be the default value since * is not a valid EMS value
