### ISSUE TITLE
Norminal Floor to Ceiling Height and Nominal Z coordinate isn't populated in OSM BuildingStory objects 

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2752]
Minor issue. I did see if the story height is set to 20 that it does change the geometry, but it would be nice to set the nominal values as well.

**Comment by macumber** [comment]
Story multiplier in thermal zones are always one, even though the story multiplier is an editable field in geometry editor. Also it shows a default value of 0, when it should show 1.

**Comment by shorowit** [comment]
BuildingStory objects are now good in 2.4.1. Story multipliers aren't yet implemented, but give the user a warning and end up as thermal zone multiplier = 1.
