### ISSUE TITLE
PAT analysis name cannot contain . or continues to loop forever

### ISSUE THREAD

**Issue by kpelckmans** [NREL/OpenStudio#2755]
When one of the analysis contains a ., following error occurs
(id=59a2aa48b16ce714fb9dd0d0) (queue=simulations) FAILED (0 prior attempts) with Mongo::Error::OperationFailure: The dotted field 'Win 1.5 100P' in 'results.Win 1.5 100P' is not valid for storage. (57)

2 things can be enhanced:
1) do not restart the analysis when this problem occurs and show an error in the interface
2) validate that name cannot contain . in the interface

**Comment by macumber** [comment]
Thanks for the great report @kpelckmans !

**Comment by jmarrec** [comment]
Same issue as I reported here: https://github.com/NREL/OpenStudio/issues/2673

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#37
