### ISSUE TITLE
Add Comfort Fields for People Definition on the Loads definition tab

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2756]
Enable ASHRAE 55 Comfort Warnings, Mean Radiant Temperature Calculation Type, Thermal Comfort Model Type

**Comment by macumber** [comment]
I believe this is just a matter of fiddling with the inspector policy here:

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/openstudio_lib/library/OpenStudioPolicy.xml#L1464

**Comment by evanweaver** [comment]
Fixed via https://www.pivotaltracker.com/n/projects/134010.

**Comment by macumber** [comment]
Looks like the people definition object is not being constructed with enough fields to edit in the inspector

![image](https://user-images.githubusercontent.com/1327850/35646930-2b07a414-068e-11e8-9efa-1d4d52d3e2d1.png)

**Comment by macumber** [comment]
Also would be good to add the fields on this tab too 

![image](https://user-images.githubusercontent.com/1327850/35648032-a5bb9e88-0691-11e8-998a-96c990fde1f9.png)

**Comment by jmarrec** [comment]
@macumber I think you just need to click on the "Add Extensible Groups (+)" which will add a "Thermal Confort Model Type" extensible group and initialize the other fields.

![image](https://user-images.githubusercontent.com/5479063/53481006-9b74f580-3a7c-11e9-97bf-2e7a53e4000e.png)

As you keep clicking the (+) you can add more Comfort Model Types:

![image](https://user-images.githubusercontent.com/5479063/53481351-57362500-3a7d-11e9-8182-b6c9a77775fb.png)

I think it's working like it should, so I suggest closing, or renaming to "Add Comfort Fields for People Definition on the Loads definition tab" to address you comment about "Also would be good to add the fields on this tab too"

**Comment by macumber** [comment]
Let’s keep open and rename
