### ISSUE TITLE
OS Server Dies Mid-Analysis

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2758]
UCI Partner was running an optimization - presumably with 2.2.0 on AWS.  rgenoud was making progress for a while then rolled over and died.

![view_analysis1](https://user-images.githubusercontent.com/2230150/29777575-63717c14-8bc1-11e7-82f6-664ebb3acc38.PNG)

![view_analysis2](https://user-images.githubusercontent.com/2230150/29777579-689c56c8-8bc1-11e7-87a4-8fee6d9ef4b8.PNG)

Is this a known issue that was fixed for 2.2.1?  I will be getting the project this morning for further debug.

**Comment by brianlball** [comment]
do we know what instance they were using?  its possible it ran out of storage if its a small instance.

**Comment by ljbrackney** [comment]
I don't know.  We can ask this afternoon, but in the meantime I'm just going to roll on 24a to get rolling.

**Comment by rHorsey** [comment]
This issue was moved to NREL/OpenStudio-server#241
