### ISSUE TITLE
PAT Measure Manager Not Finding New Content in MyMeasures

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2759]
Added a Measure to MyMeasures.

[RunPeriod.zip](https://github.com/NREL/OpenStudio/files/1257399/RunPeriod.zip)

This didn't show up in PAT's Measure Manager but DID show up in the App.  I manually edited the Measure's XML to delete a word from the description and restarted PAT.  The Measure now shows up and can be added to the project.

**Comment by macumber** [comment]
@kflemin should this be moved to PAT repo?

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#55
