### ISSUE TITLE
This file doesn't fail gracefully (Bugzilla #1063)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#276]
On 2013-01-30 20:22:35, @DavidGoldwasser wrote:

> Created an attachment (id=277)
> Change weather file and try to run
> 
> It just looks like it is running, but isn't. If you look in the tree three is a directory for EnergyPlus output, but the error files looks empty.

On 2013-01-30 20:30:45, @DavidGoldwasser wrote:

> Hmm, when I export to an IDF file and run in EP Launch it hangs in the same way. We used to have an issue with OpenStudio hanging when EP crashes, but here it looks like it is hanging and not crashing. Maybe issue is in ForwardTranslation? or it could be EnergyPlus issue?

Original attachments:
- Building 30c medoffice.osm (ID 277)

Keywords: UserFile

**Comment by evanweaver** [comment]
Pre-2.0 issue.
