### ISSUE TITLE
PAT Doesn't Show Analysis Complete for Modest Cloud Runs

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2763]
Completed a Morris Method run on 24a w/ 100-140 points.  Server completes normally.  PAT appears stuck in "Analysis running" state, and run must be cancelled to unlock PAT.  A large number of datapoints have been returned from the server to PAT, but it's getting jammed up at some point.  This should be replicable with the SEB_Morris project in the PAT repo and Morris settings of 10 and 10 for the first two algorithm parameters.

**Comment by kflemin** [comment]
Could not replicate with the project/settings mentioned above.  Do you have another project that I could test with?

**Comment by ljbrackney** [comment]
This appears to be working now.  Perhaps fixed by something server side.  Will reopen if it pops up again.
