### ISSUE TITLE
PAT double/integer bug

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2766]
We defined a measure argument that's a double, but PAT shows up/down arrows and displays a tooltip as if it thinks it needs an integer:
![image](https://user-images.githubusercontent.com/5861765/29926870-d9fe29ce-8e21-11e7-8e55-fd4c0e645312.png)

It appears that the double value does get used correctly. But a PAT user in the private sector got confused by this and thought they could only enter an integer value.

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#38
