### ISSUE TITLE
Many users reporting errors with Missing Energy+.ini (Bugzilla #1065)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#277]
On 2013-02-05 08:52:30, @DavidGoldwasser wrote:

> https://openstudio.nrel.gov/forums/openstudio-plug-sketchup/help-desk/simulation-error
> https://openstudio.nrel.gov/forums/openstudio-application/bug-reports-and-feature-requests/energyini
> 
> Dan think's this is the issue. Just needing to copy that file into the E+ working directory.  I vote we file a bug for Jason, I don't think it should be that hard to fix.
> 
> Not sure if the installer does this or scan for tools. Scan for tools would be ideal if it works.

**Comment by felixcollins** [comment]
Is there a work around?

**Comment by macumber** [comment]
Duplicate of https://github.com/NREL/OpenStudio/issues/185
