### ISSUE TITLE
PAT Updating measures doesn't preserve argument order

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2770]
If I update a measure in PAT where I've inserted an argument at the top of the measure.rb, the argument appears at the end of the measure in PAT. If I want the argument to correctly appear at the top, I have to delete the measure from my project, re-add it, and then re-enter all of the argument values.

It may not sound too bad, but I have to update four PAT projects, each with this measure duplicated multiple times, so it creates a fairly lengthy process for me.

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#39
