### ISSUE TITLE
Qt WebEngine problems on Ubuntu preclude ResultsViewer (OS 2.2.1) and DView (OS 2.2.2) from running on Ubuntu

### ISSUE THREAD

**Issue by evanweaver** [NREL/OpenStudio#2777]
ResultsViewer call stack on Ubuntu 14.4

bldadmin@ubuntu:~$ cd /usr/bin/
bldadmin@ubuntu:/usr/bin$ ./OpenStudioApp
REQUEST REFRESHALL CALLED 
 REFRESHALL CALLED 
 DO REFRESH CALLED 0
[0913/093230:WARNING:resource_bundle.cc(291)] locale_file_path.empty() for locale 
Qt WebEngine ICU data not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install/resources. Trying parent directory...
Qt WebEngine ICU data not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install. Trying application directory...
Installed Qt WebEngine locales directory not found at location /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /usr/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Qt WebEngine resources not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install/resources. Trying parent directory...
Qt WebEngine resources not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install. Trying application directory...
[0913/093230:WARNING:resource_bundle.cc(291)] locale_file_path.empty() for locale 
/usr/bin/ResultsViewer: error while loading shared libraries: libqwt.so: cannot open shared object file: No such file or directory

**Comment by evanweaver** [comment]
We should verify that DView starts on Ubuntu.

**Comment by evanweaver** [comment]
DView call stack on Ubuntu 14.4


Qt WebEngine ICU data not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install/resources. Trying parent directory...
Qt WebEngine ICU data not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install. Trying application directory...
Installed Qt WebEngine locales directory not found at location /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /usr/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Qt WebEngine resources not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install/resources. Trying parent directory...
Qt WebEngine resources not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install. Trying application directory...
[0913/132859:WARNING:resource_bundle.cc(291)] locale_file_path.empty() for locale 
/usr/bin/DView: error while loading shared libraries: libwx_baseu_net-3.0.so.0: cannot open shared object file: No such file or directory

**Comment by macumber** [comment]
Why is DView invoking WebEngine?  Does it include a web browser?

**Comment by macumber** [comment]
Oh I see, you are starting the app and then launching it?

**Comment by evanweaver** [comment]
Yep

**Comment by macumber** [comment]
Cool, the WebEngine errors are not related to why the apps are failing.  Only the last messages about 

    /usr/bin/DView: error while loading shared libraries: libwx_baseu_net-3.0.so.0: cannot open shared object file: No such file or directory

are relevant.  You should be able to replicate by just running

    /usr/bin/DView

Does that have the same issue?  If not, then something the app is doing is messing with the environment.

**Comment by eshadd** [comment]
Also noticed that Geometry tab makes OS close. Possibly same Dview issue?

**Comment by macumber** [comment]
What operating system are you using @eshadd?  If Windows, I suspect your issue is related to https://github.com/NREL/OpenStudio/issues/2604 rather than this one

**Comment by macumber** [comment]
For this issue we just need to statically link the wx libraries or ship shared object libraries on Linux

**Comment by macumber** [comment]
For this issue we just need to statically link the wx libraries or ship shared object libraries on Linux

**Comment by eshadd** [comment]
@macumber I'm using Linux.

**Comment by evanweaver** [comment]
This issue was moved to NREL/wex#59
