### ISSUE TITLE
Surface Search can fail after copying surface group objects (Bugzilla #1066)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#278]
On 2013-02-05 11:19:15, @DavidGoldwasser wrote:

> Found this out working on issue on forum.
> https://openstudio.nrel.gov/forums/openstudio-application/bug-reports-and-feature-requests/failure-save-edit-following-surface-s
> 
> Here are steps to repeat
> 1. Launch Plugin
> 2. Create Shading Group, open and draw a rectangle, exit out of group
> 3. Copy this group somewhere else using the move/copy (ctrl)to a new location.
> 4. Run Surface Search for "OS:ShadingSurface". Both groups should be visible, but only the original one is, and the following ruby error is produced.
> 
> WARNING: make_unique is a deprecated methodof Sketchup:Group
> Error: #<NoMethodError: undefined method `visible=' for #<Sketchup::ShadowInfo:0x7609d3c>>
> C:/SVN_OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/dialogs/SurfaceSearchDialog.rb:604:in `search'
> C:/SVN_OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/dialogs/SurfaceSearchDialog.rb:516:in`each_index'
> C:/SVN_OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/dialogs/SurfaceSearchDialog.rb:516:in `search'
> C:/SVN_OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/dialogs/SurfaceSearchDialog.rb:415:in`on_search_model'
> C:/SVN_OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/dialogs/SurfaceSearchDialog.rb:60:in `add_callbacks'
> 
> Oddly if I re-open with fresh SketchUp launch both surfaces look fine, but errors still happens, and sometimes it is the other surface that changes.
> 
> If I try this with spaces things work fine, interior partition surfaces, or shading surfaces within a space it also works. Jus issue with site/building shading. 
> 
> I did confirm it doesn't matter if I use move/copy or ctrl-c and ctrl-v

Keywords: ForumPost

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/43
