### ISSUE TITLE
thermal_zone.airLoopHVACTerminal returns PTAC object

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio#2785]
In OS 2.2.1, thermal_zone.airLoopHVACTerminal returned AirTerminalSingleDuctUncontrolled, as expected (PTAC is also in the list of zone HVAC equipment). Now in OS 2.2.2, thermal_zone.airLoopHVACTerminal returns ZoneHVACPackagedTerminalAirConditioner and not the AirTerminalSingleDuctUncontrolled, thus breaking our residential measures.
[SFD_HVACSizing_Equip_GF_RAC_Fixed.osm.txt](https://github.com/NREL/OpenStudio/files/1307377/SFD_HVACSizing_Equip_GF_RAC_Fixed.osm.txt)

@kbenne @shorowit

**Comment by kbenne** [comment]
@joseph-robertson  this is officially weird. The ptac is returning an AirLoopHVAC instance. Can you think of any reason why that might be?

**Comment by kbenne** [comment]
Hey @joseph-robertson can you send me a 2.2.1 version of the model?

**Comment by shorowit** [comment]
This looks fixed in 2.3.
