### ISSUE TITLE
removing airloop removes ptac from inlet port list

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio#2787]
```
air_loop.addBranchForZone(control_zone)
ptac.addToThermalZone(control_zone)
air_loop.remove
```
The `ptac` is no longer in the inlet port list for `control_zone`resulting in E+ error (osm [before](https://github.com/NREL/OpenStudio/files/1311180/before.osm.txt) and osm [after](https://github.com/NREL/OpenStudio/files/1311179/after.osm.txt)):

   ** Severe  ** GetPTUnit: ZoneHVAC:PackagedTerminalAirConditioner="RESIDENTIAL ROOM AC ZONE PTAC"
   **   ~~~   ** ..Air-conditioners air outlet node name must be the same as a zone inlet node name.
   **   ~~~   ** ..Zone inlet node name is specified in ZoneHVAC:EquipmentConnections object.
   **   ~~~   ** ..Air-conditioners outlet node name = NODE 25

@kbenne @shorowit 

Extra resources: 
[resstock.osm.txt](https://github.com/NREL/OpenStudio/files/1311165/resstock.osm.txt)
[measures.osw.txt](https://github.com/NREL/OpenStudio/files/1311164/measures.osw.txt)

**Comment by jmarrec** [comment]
Very probably linked to https://github.com/NREL/OpenStudio/issues/2785

**Comment by shorowit** [comment]
I don't think they are linked. This bug has existed across multiple versions whereas #2785 broke between OS 2.2.1 and 2.2.2.

**Comment by kbenne** [comment]
I'm working on this. I think we will know soon.

**Comment by shorowit** [comment]
This bug is still present in the 2.3 pre-release. Same error message as above.

**Comment by shorowit** [comment]
How to more easily reproduce:
1. Run [resstock.osm.txt](https://github.com/NREL/OpenStudio/files/1403445/resstock.osm.txt) via OpenStudio 2.3. It runs successfully.
2. Run [resstock_without_airloop.osm.txt](https://github.com/NREL/OpenStudio/files/1403446/resstock_without_airloop.osm.txt) via OpenStudio 2.3. It fails with the above EnergyPlus error. The only change made was to load resstock.osm and call `model.getAirLoopHVACs[0].remove`.

If you look at the IDF created from resstock.osm, it has:
```
NodeList,
  living zone Inlet Node List,            !- Name
  Node 37,                                !- Node Name 1
  Node 40,                                !- Node Name 2
  Node 42,                                !- Node Name 3
  Node 44;                                !- Node Name 4

ZoneHVAC:PackagedTerminalAirConditioner,
  residential room ac zone ptac,          !- Name
  Always On Discrete,                     !- Availability Schedule Name
  Node 39,                                !- Air Inlet Node Name
  Node 40,                                !- Air Outlet Node Name
  ...
```

The PTAC Air Outlet Node Name (Node 40) correctly shows up in the zone NodeList.

Here's the IDF from resstock_without_airloop.osm:
```
NodeList,
  living zone Inlet Node List,            !- Name
  Node 42,                                !- Node Name 1
  Node 44;                                !- Node Name 2

ZoneHVAC:PackagedTerminalAirConditioner,
  residential room ac zone ptac,          !- Name
  Always On Discrete,                     !- Availability Schedule Name
  Node 39,                                !- Air Inlet Node Name
  Node 40,                                !- Air Outlet Node Name
  ...
```

In this case, Node 40 is no longer in the zone NodeList, which causes the E+ error.

**Comment by shorowit** [comment]
Failing test: https://github.com/NREL/OpenStudio-resources/pull/19

**Comment by jmarrec** [comment]
I have been investigating this issue.

It happens in a very specific scenario. Here are scenarios, with the zone equipment in order:

* [ATU, PTAC] = ok
* [PTAC, ATU] = ok
* [PTAC1, ATU, PTAC2] = ok
* [PTAC1, ATU, PTAC2 , Dehumidificator] = PTAC1 is no longer on the Zone Air Inlet NodeList

At the end I'm putting is a MCVE (Minimal Complete, Verifiable Example) with nodes named correctly all throughout.

I've used LLDB as a debugger to see what's happening

```
br set --file /home/julien/Software/Others/OpenStudio/openstudiocore/src/model/AirLoopHVAC.cpp --line 266
```

AirLoopHVAC_Impl::remove is called, and it loops on the components (after dealing with the supply components - with I don't have anyways), around [AirLoopHVAC.cpp#L266](https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/model/AirLoopHVAC.cpp#L266)

It loops in this order:

```
a.components.map{|c| c.name.to_s}

["AirLoop Supply Inlet Node",
 "AirLoop Supply Outlet Node",
 "AirLoop Demand Inlet Node",
 "Air Loop HVAC Zone Splitter 1",
 "ATU",
 "ATU Outlet to Zone Node",
 "Thermal Zone 1",
 "Zone Return Air Node",
 "Air Loop HVAC Zone Mixer 1",
 "AirLoop Demand Outlet Node"]

```

Until just after the "ATU" is removed, the zone inletPortList still has 4 extensible groups

Once "ATU Outlet to Zone Node" is disconnected, it only has 3: PTAC1, PTAC2, Dehum, which is right.

Then once "Thermal Zone 1" is "disconnected", it has 2.

On this line: https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/model/ThermalZone.cpp#L1819

PortList_Impl::airLoopHVACPort obviously doesn't find an HVAComp that it on an AirLoop, so it skips to  the last resort and calls nextPortIndex here: https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/model/PortList.cpp#L278

https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/model/PortList.cpp#L221

nextPortIndex returns "3", so https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/model/ThermalZone.cpp#L1824

    _model.disconnect(pl,plPort);

https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/model/Model.cpp#L1747

sourceObject is the "PTAC1 Outlet to Zone Node" here... sourcePort and target ports are both 3...

On this line: https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/model/Model.cpp#L1778 it's gone, and I lost track of my frame.


----

## Ruby testing

```ruby
include OpenStudio::Model

require '/home/julien/Software/Others/OpenStudio-resources/model/simulationtests/lib/baseline_model.rb'

m = Model.new

z = ThermalZone.new(m)

fan = FanConstantVolume.new(m)
hc = CoilHeatingElectric.new(m)
cc = CoilCoolingDXSingleSpeed.new(m)
ptac1 = ZoneHVACPackagedTerminalAirConditioner.new(m, m.alwaysOnDiscreteSchedule, fan, hc, cc)
ptac1.addToThermalZone(z)
ptac1.setName("PTAC1")

a = AirLoopHVAC.new(m)
atu = AirTerminalSingleDuctUncontrolled.new(m, m.alwaysOnDiscreteSchedule)
atu.setName("ATU")
a.addBranchForZone(z, atu)


# Second PTAC - works until there
fan = FanConstantVolume.new(m)
hc = CoilHeatingElectric.new(m)
cc = CoilCoolingDXSingleSpeed.new(m)
ptac2 = ZoneHVACPackagedTerminalAirConditioner.new(m, m.alwaysOnDiscreteSchedule, fan, hc, cc)
ptac2.addToThermalZone(z)
ptac2.setName("PTAC2")


# Once I add the dehum, PTAC1 is removed
dehum = ZoneHVACDehumidifierDX.new(m)
dehum.addToThermalZone(z)
dehum.setName("Dehum")


a.supplyInletNode.setName("AirLoop Supply Inlet Node")
a.supplyOutletNode.setName("AirLoop Supply Outlet Node")
a.demandInletNode.setName("AirLoop Demand Inlet Node")
a.demandOutletNode.setName("AirLoop Demand Outlet Node")

z.returnAirModelObject.get.setName("Zone Return Air Node")
# atu.outletModelObject.get.to_Node.get.setName("ATU Outlet Node")
z.zoneAirNode.setName("Zone Air Node")

z.inletPortList.getTarget(3).get.getTarget(2).get.setName("PTAC1 Outlet to Zone Node")
z.inletPortList.getTarget(4).get.getTarget(2).get.setName("ATU Outlet to Zone Node")
z.inletPortList.getTarget(5).get.getTarget(2).get.setName("PTAC2 Outlet to Zone Node")
z.inletPortList.getTarget(6).get.getTarget(2).get.setName("Dehum Outlet to Zone Node")


z.exhaustPortList.getTarget(3).get.getTarget(4).get.setName("Zone Exhaust to PTAC1 Node")
z.exhaustPortList.getTarget(4).get.getTarget(4).get.setName("Zone Exhaust to PTAC2 Node")
z.exhaustPortList.getTarget(5).get.getTarget(4).get.setName("Zone Exhaust to Dehum Node")

m.save('before.osm', true)

ft = OpenStudio::EnergyPlus::ForwardTranslator.new
w = ft.translateModel(m)
w.save('before.idf', true)

# Enable lldb/gdb before this call
a.remove

m.save('after.osm', true)
w = ft.translateModel(m)
w.save('after.idf', true)

```

**Comment by jmarrec** [comment]
Ok, I think the problem is here:
https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/model/Model.cpp#L1740

    if( boost::optional<HVACComponent> hvacComponent = targetObject->optionalCast<HVACComponent>() )

If you take the ruby code above, and stop just before `a.remove`, then do this:

```
n = m.getNodeByName("ATU Outlet to Zone Node").get

atu.disconnect
atu.remove
n.disconnect


pl = z.inletPortList
pl.modelObjects.map{|c| c.name.to_s}

port = pl.airLoopHVACPort

object = pl.to_ModelObject.get
```

I think this cpp line is the same as pl.getTarget(3), which returns the **first extensible group** in this case, instead of trying to do pl.modelObject(port) which returns the modelObject at the 3 port Index (0 idnexed), which in this case would fail.

**Comment by jmarrec** [comment]
See  dc4a98f, I think the problem is that airLoopHVACPort was returning a portIndex, and not a port. I haven't had time to build and confirm it works as expected, and I have to run.

**Comment by jmarrec** [comment]
I build and tested with the above ruby example, the resulting IDF has the right nodes.

Should run it against the full OpenStudio-resources to ensure there aren't other problems, but it's looking good. I will resume on monday.

**Comment by shorowit** [comment]
Thanks @jmarrec! I verified that the OpenStudio-resources test I posted above passes with your fix.
