### ISSUE TITLE
OpenStudioApp crashes on geometry tab in Ubuntu

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2788]
Set DISPLAY env variable
Start container with https://github.com/canmet-energy/docker-openstudio/blob/master/Dockerfile
Connect with XServer (e.g. XMing)

**Comment by jmarrec** [comment]
This works now, and even if not it's an OpenStudioApplication issue.

Anyways, fixed in https://github.com/NREL/OpenStudioApplication/pull/98
