### ISSUE TITLE
FourPipe Fan Coil fails in 2.2.2 simulation with EnergyPlus 8.8

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2789]
I hit this with LargeHotel prototype building, I thought issues were related to custom standards gem I was using, but then want back and recreated with 2.2.1 install OS app, and then 2.2.2.

Below is text from OSM and IDF from 2.2.1 OSM model where I ran the prototype measure for LargeHotel.

OS:ZoneHVAC:FourPipeFanCoil,
  {844b2ba4-0a1e-4b1a-8157-c89a692f531c}, !- Handle
  Room_1_Flr_3 ZN FCU,                    !- Name
  {6e4c076a-4106-49eb-8b37-8abd232ab192}, !- Availability Schedule Name
  CyclingFan,                             !- Capacity Control Method
  autosize,                               !- Maximum Supply Air Flow Rate {m3/s}
  ,                                       !- Low Speed Supply Air Flow Ratio
  ,                                       !- Medium Speed Supply Air Flow Ratio
  0,                                      !- Maximum Outdoor Air Flow Rate {m3/s}
  ,                                       !- Outdoor Air Schedule Name
  {070e08d7-1de9-4bf9-b3af-0af136e083ce}, !- Air Inlet Node Name
  {86bca03e-204c-46c0-83e8-b86e04fddd88}, !- Air Outlet Node Name
  OutdoorAir:Mixer,                       !- Outdoor Air Mixer Object Type
  ,                                       !- Outdoor Air Mixer Name
  {08e84941-83a3-4623-9671-f0d9353a90d5}, !- Supply Air Fan Name
  {c51b4f55-002f-49d3-b79d-e142a11c485c}, !- Cooling Coil Name
  autosize,                               !- Maximum Cold Water Flow Rate {m3/s}
  ,                                       !- Minimum Cold Water Flow Rate {m3/s}
  ,                                       !- Cooling Convergence Tolerance
  {6fd60342-a4b7-4abc-838d-422a89352dbf}, !- Heating Coil Name
  autosize,                               !- Maximum Hot Water Flow Rate {m3/s}
  ,                                       !- Minimum Hot Water Flow Rate {m3/s}
  ,                                       !- Heating Convergence Tolerance
  ,                                       !- Supply Air Fan Operating Mode Schedule Name
  autosize,                               !- Minimum Supply Air Temperature in Cooling Mode {C}
  autosize;                               !- Maximum Supply Air Temperature in Heating Mode {C}`

ZoneHVAC:FourPipeFanCoil,
  Room_1_Flr_3 ZN FCU,                    !- Name
  Always On Discrete,                     !- Availability Schedule Name
  CyclingFan,                             !- Capacity Control Method
  Autosize,                               !- Maximum Supply Air Flow Rate {m3/s}
  ,                                       !- Low Speed Supply Air Flow Ratio
  ,                                       !- Medium Speed Supply Air Flow Ratio
  0,                                      !- Maximum Outdoor Air Flow Rate {m3/s}
  ,                                       !- Outdoor Air Schedule Name
  Node 165,                               !- Air Inlet Node Name
  Node 166,                               !- Air Outlet Node Name
  OutdoorAir:Mixer,                       !- Outdoor Air Mixer Object Type
  Room_1_Flr_3 ZN FCU OA Mixer,           !- Outdoor Air Mixer Name
  Fan:OnOff,                              !- Supply Air Fan Object Type
  Room_1_Flr_3 ZN Fan Coil fan,           !- Supply Air Fan Name
  Coil:Cooling:Water,                     !- Cooling Coil Object Type
  Room_1_Flr_3 ZN 'FCU Cooling Coil,      !- Cooling Coil Name
  Autosize,                               !- Maximum Cold Water Flow Rate {m3/s}
  ,                                       !- Minimum Cold Water Flow Rate {m3/s}
  ,                                       !- Cooling Convergence Tolerance
  Coil:Heating:Water,                     !- Heating Coil Object Type
  Room_1_Flr_3 ZN FCU Heating Coil,       !- Heating Coil Name
  Autosize,                               !- Maximum Hot Water Flow Rate {m3/s}
  ,                                       !- Minimum Hot Water Flow Rate {m3/s}
  ,                                       !- Heating Convergence Tolerance
  ,                                       !- Availability Manager List Name
  ,                                       !- Design Specification ZoneHVAC Sizing Object Name
  ,                                       !- Supply Air Fan Operating Mode Schedule Name
  Autosize,                               !- Minimum Supply Air Temperature in Cooling Mode {C}
  Autosize;                               !- Maximum Supply Air Temperature in Heating Mode {C}`

Next I did a save as, and then Opened that model in 2.2.2. I didn't re-run the prototype measure, just opened and version translated the 2.2.1 model (OSM then IDF object)

OS:ZoneHVAC:FourPipeFanCoil,
  {844b2ba4-0a1e-4b1a-8157-c89a692f531c}, !- Handle
  Room_1_Flr_3 ZN FCU,                    !- Name
  {6e4c076a-4106-49eb-8b37-8abd232ab192}, !- Availability Schedule Name
  CyclingFan,                             !- Capacity Control Method
  autosize,                               !- Maximum Supply Air Flow Rate {m3/s}
  ,                                       !- Low Speed Supply Air Flow Ratio
  ,                                       !- Medium Speed Supply Air Flow Ratio
  0,                                      !- Maximum Outdoor Air Flow Rate {m3/s}
  ,                                       !- Outdoor Air Schedule Name
  {070e08d7-1de9-4bf9-b3af-0af136e083ce}, !- Air Inlet Node Name
  {86bca03e-204c-46c0-83e8-b86e04fddd88}, !- Air Outlet Node Name
  OutdoorAir:Mixer,                       !- Outdoor Air Mixer Object Type
  ,                                       !- Outdoor Air Mixer Name
  {08e84941-83a3-4623-9671-f0d9353a90d5}, !- Supply Air Fan Name
  {c51b4f55-002f-49d3-b79d-e142a11c485c}, !- Cooling Coil Name
  autosize,                               !- Maximum Cold Water Flow Rate {m3/s}
  ,                                       !- Minimum Cold Water Flow Rate {m3/s}
  ,                                       !- Cooling Convergence Tolerance
  {6fd60342-a4b7-4abc-838d-422a89352dbf}, !- Heating Coil Name
  autosize,                               !- Maximum Hot Water Flow Rate {m3/s}
  ,                                       !- Minimum Hot Water Flow Rate {m3/s}
  ,                                       !- Heating Convergence Tolerance
  ,                                       !- Supply Air Fan Operating Mode Schedule Name
  autosize,                               !- Minimum Supply Air Temperature in Cooling Mode {C}
  autosize;                               !- Maximum Supply Air Temperature in Heating Mode {C}`

ZoneHVAC:FourPipeFanCoil,
  Room_1_Flr_3 ZN FCU,                    !- Name
  Always On Discrete,                     !- Availability Schedule Name
  CyclingFan,                             !- Capacity Control Method
  Autosize,                               !- Maximum Supply Air Flow Rate {m3/s}
  ,                                       !- Low Speed Supply Air Flow Ratio
  ,                                       !- Medium Speed Supply Air Flow Ratio
  0,                                      !- Maximum Outdoor Air Flow Rate {m3/s}
  ,                                       !- Outdoor Air Schedule Name
  Node 165,                               !- Air Inlet Node Name
  Node 166,                               !- Air Outlet Node Name
  ,                                       !- Outdoor Air Mixer Object Type
  ,                                       !- Outdoor Air Mixer Name
  Fan:OnOff,                              !- Supply Air Fan Object Type
  Room_1_Flr_3 ZN Fan Coil fan,           !- Supply Air Fan Name
  Coil:Cooling:Water,                     !- Cooling Coil Object Type
  Room_1_Flr_3 ZN 'FCU Cooling Coil,      !- Cooling Coil Name
  Autosize,                               !- Maximum Cold Water Flow Rate {m3/s}
  ,                                       !- Minimum Cold Water Flow Rate {m3/s}
  ,                                       !- Cooling Convergence Tolerance
  Coil:Heating:Water,                     !- Heating Coil Object Type
  Room_1_Flr_3 ZN FCU Heating Coil,       !- Heating Coil Name
  Autosize,                               !- Maximum Hot Water Flow Rate {m3/s}
  ,                                       !- Minimum Hot Water Flow Rate {m3/s}
  ,                                       !- Heating Convergence Tolerance
  ,                                       !- Availability Manager List Name
  ,                                       !- Design Specification ZoneHVAC Sizing Object Name
  ,                                       !- Supply Air Fan Operating Mode Schedule Name
  Autosize,                               !- Minimum Supply Air Temperature in Cooling Mode {C}
  Autosize;                               !- Maximum Supply Air Temperature in Heating Mode {C}

Notice OutdorAirMixerName missing from the newer IDF object. and the error from eplusout.err is `**  Fatal  ** SimOAMixer: OutdoorAir:Mixer not found=`

**Comment by asparke2** [comment]
Fixed by https://github.com/NREL/OpenStudio/commit/34238e7c2c48de2dd1a5dc7877693536864d0854, tested by building locally.
