### ISSUE TITLE
Facility Tab - The on/off switch for thermostats does not function (Bugzilla #1067)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#279]
On 2013-02-06 14:12:16, @DavidGoldwasser wrote:

> Steps to repeat this.
> 1. launch OpenStudio
> 2. Create two thermal zones
> 3. Go to facility tab
> 4. Select one of the thermal zones and turn thermostat on
> 5. Switch to the other zone and then back to the first one. While the thermostat should be on, it is off.
> 
> This was noticed by users who saw drop zones were not working, but if I turn the thermostat on via thermal zone tab, then drop zones in facility tab does work.
> 
> I also tested the on/of switch for IdealAir loads and expected it not to work, but it seemed to work fine.

Keywords: UserFile

**Comment by jmarrec** [comment]
Irrelevant due to GUI refactor
