### ISSUE TITLE
WorkflowStepValue.units is not initialized.

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2791]
Even though units are in the OSW file, the boost optional is always not initialized.
https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-2.2.0-doc/utilities/html/classopenstudio_1_1_workflow_step_value.html#ad4a93507ee09de4bef3d38be1c509ed3

Name and value work fine, here is sample OSW I'm pulling from.

` {
                  "name" : "end_use_heating",
                  "units" : "kBtu",
                  "value" : 3966008.0455542319
               },`

I thought this had been filed before, but couldn't find it. I hit this trying to export results to CSV with post processing script, and wanted to avoid confusion on units.

**Comment by jmarrec** [comment]
@DavidGoldwasser Do you have code to reproduce this please? I've seen a couple of issues related to this where the wrong overloaded method was used in a measure, so I'd like to see if it's really an OpenStudio issue or not.

**Comment by DavidGoldwasser** [comment]
@jmarrec I don't have anything to reproduce this and have not seen it in a while. I'm fine closing it and can re-open if I see it again.
