### ISSUE TITLE
OS App Crash when switching from zone equipment inspector to HVAC Systems tab

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2792]
Go to Thermal Zone tab
Create a zone
Drag for example "CV Unit Heater HW" from the Library to the thermal zone (works with Unit Ventilator too, PTAC, probably any other)
Click on it to bring the right column inspector
Click on "HVAC Systems" tab (even if you wait a long time before doing this, it crashes)
=> crash

First noticed in OS 2.2.0, confirmed behavior in OS 2.2.2
macOS Sierra 10.12.6

**Comment by LyleKeck** [comment]
App also crashes occasionally when adding zone equipment (FourPipeFanCoil) to zone on the Thermal Zone tab.  Also can crash after adding zone equipment and then selecting the AirLoop from the system dropdown on the HVAC Systems tab

**Comment by macumber** [comment]
Assigned to @kbenne to verify if it crashes on mac

**Comment by macumber** [comment]
@jmarrec @kbenne did this get fixed?

**Comment by kbenne** [comment]
I can no longer reproduce this, and based on the callstack from @jmarrec I think it was fixed here https://github.com/NREL/OpenStudio/commit/e86278e6091bf025ccb49447ef48504888146b4b#diff-87cebb5848376f7a0e478a2ba4c19802
