### ISSUE TITLE
Modifying Construction Rendering Color in SketchUp OS Plugin or OS APP

### ISSUE THREAD

**Issue by mleach-noresco** [NREL/OpenStudio#2794]
In the plugin, you used to be able to change rendering colors for constructions when you were rendering by construction.  But now, when you click on a surface when rendering by construction you get the surface properties instead of the construction properties.  That's fine, but it would be nice to be able to select constructions in the inspector window and be able to modify rendering color.  Additionally, there is only a roundabout way of selecting rendering color in the OS App.  It is not exposed in the Constructions tab.  The only way to do it is to click on a construction for an individual surface and then change the color in the right column.

**Comment by macumber** [comment]
Not adding new features to SketchUp plug-in
