### ISSUE TITLE
Build fails with `No rule to make target 'src/utilities/idd/IddFieldEnums.ixx'`

### ISSUE THREAD

**Issue by abbaad** [NREL/OpenStudio#2796]
I'm trying to build OpenStudio (v2.2.0) on archlinux, on an x86-64 machine. There seems to be an issue with `cmake` not picking up dependencies correctly. The error in context is:
```
Scanning dependencies of target CreateEmbeddedSource
[  1%] Building CXX object embedded/CMakeFiles/CreateEmbeddedSource.dir/CreateEmbeddedSource.cpp.o
[  1%] Linking CXX executable ../Products/CreateEmbeddedSource
[  1%] Built target CreateEmbeddedSource
Scanning dependencies of target openstudio_modeleditor_static_GeneratedHeaders
[  1%] Generating ui_precisiondialog.h
[  1%] Generating ../../openstudio_modeleditor_static_HeadersGenerated_done.stamp
[  1%] Built target openstudio_modeleditor_static_GeneratedHeaders
Scanning dependencies of target openstudio_utilities_static_GeneratedHeaders
make[2]: *** No rule to make target 'src/utilities/idd/IddFieldEnums.ixx', needed by 'openstudio_utilities_static_HeadersGenerated_done.stamp'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:1437: src/utilities/CMakeFiles/openstudio_utilities_static_GeneratedHeaders.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```
I have attached the full typescript as well: [typescript.txt](https://github.com/NREL/OpenStudio/files/1334578/typescript.txt)

It might to be a problem with Swig not being used correctly by `cmake`. Even though I have `swig-3.0.12` installed locally, the makefile insists on compiling `swig-3.0.7` from scratch.

**Comment by macumber** [comment]
There is an executable named GenerateIddFactory.exe that gets built very early in the build process.  This gets run to generate some files based on the IDD.  You can go to your build directory and find this exe and try to run it, my guess is there are some missing run time dependencies

**Comment by ljbrackney** [comment]
I have to manually make GenerateIddFactory and GenerateIddFactoryRun prior to making pretty much anything on a "clean" system.

**Comment by jmarrec** [comment]
I stumbled onto this again today while doing a clean build, trying to build the current develop.
`make GenerateIddFactory` (nothing to do there) and `make GenerateIddFactoryRun` (this did something) solved the problem... It's annoying and confusing though.

**Comment by macumber** [comment]
@evanweaver is this affecting CI machines?

**Comment by evanweaver** [comment]
@macumber no, not CI and not build boxes.

**Comment by jmarrec** [comment]
I have *some* doubt this is true. To be perfectly clear, It does that only on a clean build only, so obviously if the boxes are already set up and build correctly once it’s ok.
I had that on multiple OSes

——
Sent from a mobile device, please excuse the brevity.
Julien Marrec, EBCP, BPI MFBA
Owner


Direct: +33 6 95 14 42 13
Website: www.effibem.com

LinkedIn (en) | (fr)

**Comment by ljbrackney** [comment]
@jmarrec is correct.  Once you've built the IDDFactory stuff, you're good to go.  This is a problem on new build systems or following make clean.

**Comment by rh0dium** [comment]
FYI - If someone can comment here is what I did to "build the IDDFactory stuff"
```shell
  cd src/generateiddfactory/
  make
  cp EnergyPlus-8.9.0-eba93e8e1b-Linux-x86_64/EnergyPlus-8-9-0/Energy+.idd  eplus.idd
  ./Products/GenerateIddFactory-2.5.2  -i eplus.idd -o src/utilities/idd
```

**Comment by jmarrec** [comment]
@rh0dium did that actually work? I’d be kinda surprised.

These are two make targets. You should run them in your build directory (eg: ./build or wheverer you place it out of source):

make GenerateIddFatory
make GenerateIddFactoryRun

Then you can call just ‘make’ again and it’ll work (make calls the target ‘all’ by default)

I wrote these instructions for macOS but they hold true for Linux except the OpenSSL/brew stuff: https://github.com/jmarrec/OpenStudio-2.0-Python3/blob/master/Building_OS2.0_on_Mac.md

**Comment by rh0dium** [comment]
@jmarrec - It did and it's very repeatable.

**Comment by macumber** [comment]
@jasondegraw FYI

**Comment by jasondegraw** [comment]
Just for the record, I hit this on brand new Ubuntu 16.04 and 18.04 VMs. On both, `make GenerateIddFactory; make GenerateIddFactoryRun` gets the build going again, but only 16.04 finishes. 18.04 bombs out on something that looks like a boost thing.

**Comment by ljbrackney** [comment]
For clean builds on my Mac, I’ve always had to manually build GenerateIddFactory and GenerateIddFactoryRun before building any other stuff.  Weird, but something I’ve lived with…

**Comment by jmarrec** [comment]
Do we actually want to spend time looking into this, or do we just want to update the "Configuring Build Environments" wiki page to include this information?

**Comment by macumber** [comment]
I think we want to figure this out, it’s like an issue with cmake that could lead to other problems
