### ISSUE TITLE
OS App only shows the custom editable measure, name and not the one defined in measure.rb and measure.xml

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2798]
OS app used to show both the un-editable measure name set by the measure writer and an editable name which allows multiple instances of the measure to have the same name.

I wanted to edit one of the measures on a project, but it wasn't clear at first what measure it was. I had to either recognize the arguments or modeler description, or dig around in the OSW.

Not something that needs to be addressed for 2.3.0. May have been this way since 2.x?

**Comment by macumber** [comment]
David is it sufficient to show the un-editable measure name when you click on a measure step, or do you want both the un-editable measure name and the user entered name to show up in the list?

![image](https://user-images.githubusercontent.com/1327850/34898366-f48066de-f7af-11e7-890a-1fae5660a351.png)

**Comment by DavidGoldwasser** [comment]
@jmarrec If we make a change I'm fine with the non-editable name just showing in the edit tab. But it does seem now that when measures are dragged over have a meaningful names so I'm also fine closing this without any changes as well.

**Comment by jmarrec** [comment]
I've reproduced this in OS App, and now I understand why it could get confusing indeed, so I propose we do make a change, shouldn't be too hard to add the non-editable name on the edit tab.

**Comment by macumber** [comment]
Yes please add the non-editable name where appropriate
