### ISSUE TITLE
workspace.getObjectsByType() for ZoneHVAC:IdealLoadsAirSystem objects

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/OpenStudio#2799]
I have an EnergyPlus measure that edits the ZoneHVAC:IdealLoadsAirSystem objects.

I call ```workspace.getObjectsByType("ZoneHVAC:IdealLoadsAirSystem".to_IddObjectType)``` in run the section of my measure.

This works fine in OpenStudio v1.14, but returns an empty array in OpenStudio v2.2.0.
The ```workspace.getObjectsByType()``` works for other object types, e.g. ```workspace.getObjectsByType("ElectricEquipment".to_IddObjectType)``` correctly returns an array of ```ElectricEquipment``` objects.  I'm not aware of other objects for which the ```workspace.getObjectsByType()``` call no longer works in OpenStudio v2.2.0.

This is not a blocker; I can change the measure to be an OpenStudio measure with the ```ZoneHVACIdealLoadsAirSystem``` object instead of an EnergyPlus measure

**Comment by jmarrec** [comment]
Seems like if you check the "Ideal Air Loads" checkbox on the ThermalZone tab, you end up with a `HVACTemplate:Zone:IdealLoadsAirSystem` instead.

    workspace.getObjectsByType("HVACTemplate:Zone:IdealLoadsAirSystem".to_IddObject)

**Comment by mdahlhausen** [comment]
It writes both. The ```HVACTemplate:Zone:IdealLoadsAirSystem``` appears in the .idf written by OSv1.14 as well.  I tried the ``workspace.getObjectsByType("HVACTemplate:Zone:IdealLoadsAirSystem".to_IddObject)``` call, same error.

**Comment by jmarrec** [comment]
to_IddObjectType. 
Worked when I used the forward translator in irb at least 
I guess one other thing is that I haven't thought before about whether energyplus measures are triggered before or after expandobject (e+).
At least you should find either the hvactemplate or the zonehvac but not both (for the same zone at least)

Envoyé de mon iPhone

**Comment by jmarrec** [comment]
Ref #256

**Comment by mdahlhausen** [comment]
So I copied the code a few comments above incorrectly.

The call in the measure is: 
[```ideal_loads_objects = workspace.getObjectsByType("ZoneHVAC:IdealLoadsAirSystem".to_IddObjectType)```](https://github.com/mdahlhausen/scrappEplus/blob/e3cb01bc344c560a842b50d6d9d272fb5bf67c53/OpenStudio/Measures/ideal_loads_options/measure.rb#332)
I run the same measure on v1.14 and v.2.2.  The only difference being this call returns an empty array in v2.2.

The key question is: _what changed in OS v2.+ from OS v1.14 in how and the order in which ZoneHVAC:IdealLoadsAirSystem objects get written_?

**Comment by mdahlhausen** [comment]
So the order did change.
In OS v1 series, the order of operations is: 
Expand Objects -> EnergyPlus Measures -> Pre-Process

In OS v2 series, the order of operations is: 
EnergyPlus Measures -> Expand Objects -> Pre-Process

HVACTemplate objects, including ```HVACTemplate:Zone:IdealLoadsAirSystem``` objects, are translated into EnergyPlus objects (```ZoneHVAC:IdealLoadsAirSystem``` objects) in the Expand Objects step.

This means EnergyPlus measures in OS v2.+ can't include any ```get``` calls to an object formed from expanding an HVACTemplate object because they don't exist yet.

I'm not sure if this was on purpose or not.  If on purpose, this issue can be closed.  For completeness, all that means is an object expand from an HVACTemplate object should be editable in the model API.
