### ISSUE TITLE
Copy Multiple on zones is producing an extra zone(s) (Bugzilla #36)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#28]
On 2011-07-01 13:40:08, @DavidGoldwasser wrote:

> If you copy a zone or zones generally things work fine, but I've noticed a problem if you copy a zone and then use a (*#) to make multiple vs. a single copy. For example a single zone copied over and then a *4 used should produce 5 zones in a row. That is what appears but the first copied zone (next to the original zone) has a duplicate on top of it. I ran across this because of surface matching problems that were in the end due to the duplicate zone. Looking back EnergyPlus 1.0.6 exhibits this same problem (so it is a bug in our release version). I'll have to go back and look at 1.0.5 for this. If it was there I sure missed it for a long time. Not surprisingly the same thing happens with a /# vs. a *# for multiple copies. A user work around for this is not to use multiple copy or if they do they need to go and remove the duplicate copy after they make it. I can't find a way to avoid the unwanted duplicate from being made.
> 
> Bug imported from Excel; Status -confirmed; Created on - 12/29/10; By - David Goldwasser; Owned by -

On 2011-11-16 09:50:18, @DavidGoldwasser wrote:

> <batch change comment> Moving older bugs to "retest" milestone. Will re-test these and then assign to appropriate milestone. These were all 0.6.0 prior to change.

On 2011-11-17 10:41:16, @lgentile wrote:

> Still potential issue. This was an old bug. Please re-test/verify.

On 2012-01-17 14:19:05, @DavidGoldwasser wrote:

> Copy multiple is now broken on space level. This is because the select is changed after the copy. But if we do fix that then it will be making an extra zone. That fix may involve Google's input.

Keywords: ReleaseNotes

**Comment by DavidGoldwasser** [comment]
Observer Issue

**Comment by macumber** [comment]
@DavidGoldwasser @asparke2 @kbenne @axelstudios it seems like things like this (e.g. known issues but we won't fix for various reasons) are the right things to document as known issues in release notes.  Is that right?

**Comment by DavidGoldwasser** [comment]
It is in the release notes with a link to this bug. So that brings up a question. Even though we close it here, can we leave it in the release notes. I think if something is closed but tagged as "won't fix" maybe it stays in release notes?

**Comment by macumber** [comment]
That is what I was thinking
