### ISSUE TITLE
Measure manager does not check for updates to outputs section

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2801]
We have some reporting measures for ResStock/ComStock with output sections that are dynamically generated (based on information outside the measure/model). Currently the measure will not show up as updated even if there are changes to these outputs. Would it be possible to check for new outputs when determining if a measure has updates?

As a workaround, we can force an update by making a minor change to the measure.rb in order to generate a new measure.xml with the appropriate outputs. But it's easy to forget this step and makes our workflow more complicated.

cc @joseph-robertson @rHorsey

**Comment by shorowit** [comment]
@ljbrackney points out that the ability to force an update could help here.

**Comment by shorowit** [comment]
(We wouldn't be asking for this change if there was a way to runner.registerValue and tell OS that we want it to be an output -- as opposed to providing an output list for PAT/server that we need to keep updated. All we want is the output to be available in the results csv file.)

**Comment by macumber** [comment]
@shorowit did part of this issue's conversation go missing?  I am confused about what you mean by:

"ResStock/ComStock with output sections that are dynamically generated (based on information outside the measure/model)."

Is your measure loading some file outside of the measure directory?  If so, the only remedy would be a force check update button.

**Comment by shorowit** [comment]
Good point. Yes, the measure uses files outside the measure directory to generate the outputs section.

**Comment by jmarrec** [comment]
There's not much we can do to support such a corner case. The need for update is determined by checksuming the measure files. If you're using outside stuff on your filesystem that's a totally different thing that I'm not sure we ever want to support. If you still free strongly about it, you can reopen and we can discuss more.
