### ISSUE TITLE
OpenStudioApp crashes on Ubuntu unless run from /usr/bin

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2802]
Calling the executable name from a directory outside of /usr/bin results in build component libraries failing to be found and app crashing.  Calling full path to executable does work.  For example:

```
cd ~
/usr/bin/OpenStudioApp # will work
OpenStudioApp # will crash
```

**Comment by pachi** [comment]
This may be related to a problem when trying to find resources such as MinimalTemplate.osm and hvaclibrary/hvac_library.osm in OpenStudioApp:buildCompLibraries() (in OpenStudioApp.cpp).

(The resource dir is installed directly in /usr and not in /usr/share/openstudio-2.2.2)

**Comment by jmarrec** [comment]
Still today today with 2.7.0

**Comment by macumber** [comment]
@jmarrec Did your symlink work fix this?
