### ISSUE TITLE
 "Could not set argument" should show visible error in GUI

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2806]
I hit this error in a workflow where I had full model as seed, and then had EE measures for both LPD reduction and night time lighting reduction. The arguments for the reduce night time lighting has a choice argument of all lighting defs in the model that are used by an instance. Using the seed model it can pick 'Office OpenOffice Lights Definition'. If that was passed in to the measure and was gone, the measure would gracefully fail and explain why, but it seems like the arguments section is run again with the updated model (post LPD reduction) and fails. I'm fine with it failing in this way, but it seems like there should be an error in the GUI for that measure step in the workflow. It isn't ideal for users to have to dig through the JSON file on the server to identify the reason for the cause.

```
[13:11:01.058692 ERROR] Could not set argument 'lights_def' to value 'Office OpenOffice Lights Definition'
```

![screen shot 2017-10-02 at 1 39 31 pm](https://user-images.githubusercontent.com/4857055/31097027-2a30ac9c-a77b-11e7-81c0-df3727f115ea.png)

**Comment by DavidGoldwasser** [comment]
For reference. Here is zip of the project. There is a separate issue for the first two datapoints failing, this one is more about showing an error for the expected failure of the last datapoint.
https://github.com/NREL/OpenStudio-files/blob/master/Git%20Issue%20Files/issue2807.zip

@macumber, @kflemin, @asparke2 any thoughts on best solution. For now I guess it is just about better showing error to user. Eventually could let user type name or generate the values in GUI dynamically by running upstream measures. For now user would run upstream manually first and load as 'dummy' seed for this measure arg calculation.

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#41
