### ISSUE TITLE
Scan For Tools won't remove E+ Missing notice (Bugzilla #1069)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#281]
On 2013-02-11 14:19:49, @axelstudios wrote:

> If OpenStudio does not have any tools configured, running Scan for Tools will not remove the notice about E+ missing on the Run Simulation tab.
> "Notice: EnergyPlus 7.2.- is required and not yet located"
> The simulation runs fine, but the notice needs to be removed

On 2013-02-11 14:20:13, @axelstudios wrote:

> Created an attachment (id=278)
> Screenshot

Original attachments:
* screen.png (ID 278)

**Comment by macumber** [comment]
@axelstudios is this still valid?

**Comment by axelstudios** [comment]
Nope
