### ISSUE TITLE
Bad Surface Names from Geometry Editor

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2810]
While Spaces made in the editor have logic names based on story and space number, and surfaces made by surface matching are prefixed with "surface ", othe surfaces just have a number. Not ideal for searching through files for errors because numbers may exist in other fields. At a minimum might be nice to do "Surface #", but if you wanted to follow the space type naming logic can do "Surface 1-2-#", where # starts at 1 for each space.

Or could use approach like this measure which renames based on parent space, surface, type, orientation, and then number if there are multiple surfaces in space space with same orientation. Get surface names something like "Office 204 Wall 270-2"
https://github.com/NREL/OpenStudio-measures/tree/develop/NREL%20working%20measures/RenameSpaceSurfacesBasedonParentSpaceandOrientation

![screen shot 2017-10-02 at 2 26 33 pm](https://user-images.githubusercontent.com/4857055/31098840-410f7e06-a781-11e7-83af-407508504e8f.png)

**Comment by macumber** [comment]
These should be named 'Face X' now.  It still isn't a smart name, but it is better than 'X'.  If we want smart naming, could implement that as a measure

**Comment by DavidGoldwasser** [comment]
@macumber that sounds fine. If someone wants something fancy we have a measure that renames surfaces after parent space, surface type and orientation. Sub-surfaces are named after base surfaces.

I can test this next installer.

**Comment by DavidGoldwasser** [comment]
@macumber this looks good. I did notice that windows and shading surfaces use the same "Face" prefix and building surfaces. That is fine for now, but at some point in the future could be nice to
