### ISSUE TITLE
output hash should be included in the OSA for a manual simulation

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2811]
Would be ideal for local and cloud, but also fine if just on cloud. Currently there is a results.csv but it just as input and status columns, not any of the outputs.

Ideally would enable the Outputs tab for manual projects, but obviously the objective function columns would not matter, but maybe could be done without change to GUI, if this is limited to only outputs described in the measure.rb?

My workflow without this is to make a algorithmic run for what I would otherwise do as manual run, or to write a script to create CSV by scraping the data out of the out.osw files from individual datapoints, which is similar to how PAT project reports work.

Another alternate workflow would be to write a PAT script which brings up radio buttons for all the registerValues, and allows the user to build up CSV post run on the fly, vs. having to identify what they are interested in prior to the run.

**Comment by macumber** [comment]
@kflemin should this be moved to the PAT repo?

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#57
