### ISSUE TITLE
Missing .dlls when trying to run OS 2.3

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2820]
@joshdr83 says:
> I keep getting a missing .dll file message that doesn't let OS restart and I have to reinstall... Using OS 2.3 with Windows 10 Pro. This happened with OS 2.2 as well...

![image](https://user-images.githubusercontent.com/5861765/31357993-1af56e08-ad01-11e7-9274-f308183f9254.png)

**Comment by macumber** [comment]
@shorowit is this still valid?

**Comment by shorowit** [comment]
That's a question for @joshdr83, I just reported the problem on his behalf.

**Comment by joshdr83** [comment]
@shorowit @macumber I have been on a couple different projects the past couple months, but will be diving back into it early next week. I assume it will still happen if it has not been fixed? I will let you know.

**Comment by jmarrec** [comment]
@joshdr83 A year later, did you encounter the same problem? Otherwise I suggest closing.
