### ISSUE TITLE
OpenStudio App Crashes if change "Surface" boundary to "Outdoors" when you leave tab

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2822]
I was testing another issue on this. When I switch from "Surface" to "Outdoors" the GUI does change sun and wind exposure right way, but not the boundary object. It changes the boundary condition and sun and wind on matched surface as well. If you leave tab right after changing boundary condition without going to another grid cell first, OpenStudio will crash. If you click elsewhere and then switch tabs it won't crash, so kind of an edge case but still worth fixing.

Tried this with three different models in 2.3.0 on Mac.

**Comment by jmarrec** [comment]
@DavidGoldwasser do you still get this with 2.6.0? I cannot reproduce on Ubuntu.

**Comment by asparke2** [comment]
@kbenne to confirm if this still causes a crash

**Comment by jmarrec** [comment]
Confirmed crash still exists with 2.6.0 on macOS Sierra

**Comment by macumber** [comment]
@jmarrec @kbenne did this get fixed?

**Comment by macumber** [comment]
@DavidGoldwasser can you accept this?

**Comment by DavidGoldwasser** [comment]
@macumber traditional 2.8.1 still crashes, but pre 3x 2.8.1 does not crash.

**Comment by macumber** [comment]
@kbenne will retest and see if he can reproduce, @DavidGoldwasser will provide test model

**Comment by DavidGoldwasser** [comment]
@kbenne I can re-produce this with the `example_model.osm` generated by OpenStudio and used in measure templates. I'll email you a copy of the file

**Comment by kbenne** [comment]
@DavidGoldwasser ping. Can you retest on 3.x?

**Comment by DavidGoldwasser** [comment]
@kbenne I can confirm it does not crash on 3.x mac or windows.
