### ISSUE TITLE
Odd Summary Table behavior for EUI when design alternatives have negative value.

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2829]
EUI's for datapoints

GSHP = -24.14
VRF = -23.51
Fain Coil = -20.42

Notice how the signs are reverse on the % vs. kBtu/ft^2 values for EUI

<img width="1680" alt="screen shot 2017-10-21 at 12 49 32 pm" src="https://user-images.githubusercontent.com/4857055/31855002-17cb3ea8-b65f-11e7-99a6-cb9cafb744bf.png">

**Comment by DavidGoldwasser** [comment]
@asparke2 I did quick test with a baseline with a positive EUI, and then both a negative and positive alternative. In both of those cases things are fine. Only an issue when the baseline has a negative EUI.

![screen shot 2017-12-07 at 9 29 03 am](https://user-images.githubusercontent.com/4857055/33726233-ae712d9e-db31-11e7-8c8c-d82f6b5994e7.png)

Here is relevant code. Similar formula used for gas and elec, but those shouldn't be negative like EUI is. We could add gross in addition to net EUI if there was interest
https://github.com/NREL/OpenStudio-PAT/blob/develop/app/app/reports/projectReports/Summary%20Table.html#L81-L84

This should be changed
`100*(baseline.peak_electric_demand_ip - run.peak_electric_demand_ip)/baseline.peak_electric_demand_ip`

To something like this
`100*(run.peak_electric_demand_ip) - baseline.peak_electric_demand_ip/baseline.peak_electric_demand_ip.abs`

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#42
