### ISSUE TITLE
Using IP units for OutputControl:Table:Style in IDF scripts breaks results tab in OS app (Bugzilla #1072)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#283]
On 2013-02-15 08:48:14, @DavidGoldwasser wrote:

> Created an attachment (id=279)
> Example Quantity TakeOff measure
> 
> We generate the OutputControl:Table:Style obeject on forward translation but we don't specify units, so it defaults to SI. I found out that if an IDF script changes the units to IP units the simulation runs without error but the results page (graphs and tables) are empty. When you launch ResultsViewer the ABUPS table is fine and is in IP.
> 
> I cc'd Andrew on this because I know he would just assume have the ABUPS table always in SI units, and that change itself is probably a single line of code, but it appears that the results tab in the app would need some adjustment to accept this.
> ## Below is the code you can use to generate this. I attached a full example script
> 
> table_style = workspace.getObjectsByType("OutputControl:Table:Style".to_IddObjectType)
> table_style_ip = table_style[0].setString(1,"InchPound")

Original attachments:
- measure.rb (ID 279)

**Comment by macumber** [comment]
Once we have a reporting measure that is up to parity with the eplustbl.html file we will block the users ability to change this flag.  Looking at Workflow::addStandardWorkflow it appears that EnergyPlusPreProcessJob is the right place to do this.

**Comment by macumber** [comment]
Feature request for IP reporting measure https://github.com/NREL/OpenStudio/issues/1611

**Comment by MatthewSteen** [comment]
Also prevents the end use results from displaying in PAT.
