### ISSUE TITLE
Double-clicking osm does not load file if file path contains white space

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#2832]
Tested in Windows 7 and 10, OS v2.2.0 and v2.3.0.

1. Save osm to file path that contains white space (e.g. "C:/Project Name/project.osm")
2. Double-click on osm
3. OS app should launch with an empty 'Untitled' file.

Credit to @macumber for diagnosing.

**Comment by macumber** [comment]
@asparke2 @kflemin this was the root reason Amy could not see district systems in her OSMs, she was double clicking but the path had a space so an empty model was loaded

**Comment by jmarrec** [comment]
This is obviously a quoting problem.

If I double click on `C:\Users\julien\Software\Others\Openstudio-Issues\2018-06\2832_CannotLoadSpaces\a file with spaces.osm`, here are the content of argv:

```
arg 0: C:\Users\julien\Software\Others\OS-build\Products\Debug\OpenStudioApp.exe
arg 1: C:\Users\julien\Software\Others\Openstudio-Issues\2018-06\2832_CannotLoadSpaces\a
arg 2: file
arg 3: with
arg 4: spaces.osm
```

I think I found the location where I need to quote the file path: 

https://github.com/NREL/OpenStudio/blob/68530f001d75503d3d3542e6e71c6d84d6f2fa37/openstudiocore/src/openstudio_app/install_operations.qs#L30

**Comment by jmarrec** [comment]
("@jmarrec jmarrec unassigned evanweaver 16 minutes ago". This happened when I added my comment above. That's weird as hell since I don't have write access...)
