### ISSUE TITLE
Cannot compute plane for points Could not create surface for vertices

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2834]
Created a two story floorplan which had the following errors.

<img width="1680" alt="screen shot 2017-10-31 at 11 34 05 am" src="https://user-images.githubusercontent.com/4857055/32240188-41aeddbc-be32-11e7-91e4-ebbe2721e082.png">

Despite that it did merge and looks like this in SketchUp Plugin

<img width="1680" alt="screen shot 2017-10-31 at 11 34 13 am" src="https://user-images.githubusercontent.com/4857055/32240194-4a48b592-be32-11e7-81a5-b7c4993e8270.png">

Here is what it looks like in Preview

<img width="1680" alt="screen shot 2017-10-31 at 11 34 47 am" src="https://user-images.githubusercontent.com/4857055/32240217-613f58aa-be32-11e7-9522-00b6afc8c162.png">

And here is what it looks like in SketchUp Pluign

<img width="1246" alt="screen shot 2017-10-31 at 11 36 06 am" src="https://user-images.githubusercontent.com/4857055/32240227-698676a6-be32-11e7-998c-51d5fa2d1e73.png">

If I run a simulation there is a fatal error related to surface with duplicate points.

```
   ** Severe  ** CalcCoordinateTransformation: Invalid dot product, surface="218":
   **   ~~~   **  ( 158.000,  98.000,  26.555)
   **   ~~~   **  ( 158.000,  30.000,  26.555)
   **   ~~~   **  ( 158.000,  30.000,  26.555)
   **   ~~~   **  ( 200.000,  30.000,  26.555)
   **   ~~~   **  ( 200.000,  30.000,  26.555)
   **  Fatal  ** CalcCoordinateTransformation: Program terminates due to preceding condition.
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=1
   ..... Last severe error=CalcCoordinateTransformation: Invalid dot product, surface="218":
```

I have also seen this fatal error on geometry editor created OSM's that didn't present warnings on merge. I updated a diagnostic surface matching measure to look for a number look for duplicate vertices in surface as well as collinear vertices in a surface, and duplicate surfaces in space.
https://github.com/NREL/OpenStudio-measures/commit/c666d41275e9636e6180c4ef9fb7f213d50d4b7e

Link to zip file
https://github.com/NREL/OpenStudio-files/blob/master/Git%20Issue%20Files/issue2834.zip

**Comment by macumber** [comment]
@DavidGoldwasser can you see if this is fixed in @ljbrackney 's latest builds?
