### ISSUE TITLE
Misc invalid OSM geometry generated by geometry editor in OS app 2.3.0

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2835]
Another issue addresses duplicate vertices in OSM surfaces, this one addresses a number of other geometry flaws.

1. Duplicate surfaces in a space.
2. Reversed surafces within a space
3. Collinear vertices within a surface
4. one surface in space spanning over multiple surfaces (like duplicate surfaces but harder to detect)

Here is example of 1, 2, and 4.

<img width="1272" alt="screen shot 2017-10-31 at 1 07 48 pm" src="https://user-images.githubusercontent.com/4857055/32243876-5d3916ec-be3c-11e7-9d98-54f901d12f84.png">

I updated diagnostic surface matching measure to address item 1, and hack for item 2 (may delete wrong surface) and item 3, as well as the duplicate vertices in surface from issue #2834. 

Item 4 is tougher to detect because there are not any methods to specifically look for this. It is possible that intersect might split this surface, at which point then I could do check for and remove duplicate surfaces, but that isn't ideal. 

Item 3 is an issue, but I'm not sure it is really a bug that the geometry editor should address. Maybe this should be built into intersect or surface matching methods. This prevents surfaces from matching when multi-story building has unique plans. @macumber I trust your judgement on best place in the workflow to address this.

An example below is the corridor not matching because of the adjacent classrooms that are split on first story but not second. That ended up with different vector of vertices in 1st floor corridor ceiling vs. reverse of 2nd floor corridor floor.

<img width="1224" alt="screen shot 2017-10-31 at 1 13 23 pm" src="https://user-images.githubusercontent.com/4857055/32244190-5e1cc328-be3d-11e7-8145-979b2e19d3b8.png">

Link to zip file
https://github.com/NREL/OpenStudio-files/blob/master/Git%20Issue%20Files/issue2835.zip

**Comment by DavidGoldwasser** [comment]
The other bugs I've filed for geometry editor let you know there is an issue because of a crash or a failed simulation. This one may go un-noticed by users, resulting in inaccurate simulation results because of incorrect accounting of exterior envelope. Bugs that impact simulation results are of very high importance.

**Comment by macumber** [comment]
Thanks @DavidGoldwasser would all of these issues be found in the following example:

![image](https://user-images.githubusercontent.com/1327850/33344849-8da14b9e-d447-11e7-9784-b0730806e379.png)

**Comment by macumber** [comment]
@DavidGoldwasser can you see if this is fixed in @ljbrackney 's latest builds?

**Comment by DavidGoldwasser** [comment]
@macumber everything was fixed on this story except item #3. When I ran measure to remove collinear points it matched.

![screen shot 2018-01-29 at 8 35 43 am](https://user-images.githubusercontent.com/4857055/35519025-59c0532e-04d0-11e8-9d3c-9747c37b20e1.png)
