### ISSUE TITLE
SpaceTypes (local and BCL) missing schedule for infiltration objects (Bugzilla #1073)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#284]
On 2013-02-19 13:07:01, @DavidGoldwasser wrote:

> There is another bug to fix schedules so there are not empty default rules. I think these two should be fixed together. The other bug is 1010 that is currently in the backlog. The proposed 'quick' fix for that is to either re-generate all of the schedules used in the templates (but UUID's make this tough) or write a measure to clean up schedules to clean up un-used rules.

On 2013-02-19 13:28:00, @DavidGoldwasser wrote:

> Looking at the data in the Utilities SVN the data looks ok.
> C:\SVN_Utilities\OpenStudio\on-demand\space_types\nrel_ref_bldg_templates\lib\Mater_Schedules.osm contains an object that looks similar to this. UUID below is from test model
> 
> OS:Schedule:Ruleset,
>   {35a7ff55-282f-4fe9-a08a-25a17d25533a}, ! Handle
>   Medium Office_Infil_Quarter_On,         ! Name
>   {064f0c00-3e25-448c-bc08-d7f13ed45d2a}, ! Schedule Type Limits Name
>   {7887de80-0bc3-4c8e-9f3b-e0f17bae54b8}, ! Default Day Schedule Name
>   {b14a916a-a016-438c-a9be-cb2eee00c29c}, ! Summer Design Day Schedule Name
>   {11ed72ea-6c4d-4fb1-bcf1-293c2e753dcd}; ! Winter Design Day Schedule Name
> 
> 
> C:\SVN_Utilities\OpenStudio\on-demand\space_types\supporting docs\space_types_and_standards.xlsx is asking for schedule by this name "Medium Office_Infil_Quarter_On", yet the resultign model doesn't have this.
> 
> In the test model the default schedule set points to this object
> 
> OS:DefaultScheduleSet,
>   {072d1229-9262-4616-ac54-8f494d750a58}, ! Handle
>   MediumOffice_Schedules,                 ! Name
>   ,                                       ! Hours of Operation Schedule Name
>   {019f4cd1-a7b7-4217-8f53-9ea8c578c130}, ! Number of People Schedule Name
>   {5c604b06-f7ff-45c2-88bd-68279ac690a3}, ! People Activity Level Schedule Name
>   {bd52a07d-c8b4-4c20-9a77-d1fc08b0aa08}, ! Lighting Schedule Name
>   {20802b5a-f05b-415d-b36d-fa4e964ffd1a}, ! Electric Equipment Schedule Name
>   ,                                       ! Gas Equipment Schedule Name
>   ,                                       ! Hot Water Equipment Schedule Name
>   {35a7ff55-282f-4fe9-a08a-25a17d25533a}, ! Infiltration Schedule Name
>   ,                                       ! Steam Equipment Schedule Name
>   ;                                       ! Other Equipment Schedule Name
> 
> Then the space type points to the schedule set
> 
> OS:SpaceType,
>   {2f665c03-c2d7-4d5c-a486-d217e0b43dd1}, ! Handle
>   ASHRAE_90.1-2004_MediumOffice,          ! Name
>   ,                                       ! Default Construction Set Name
>   {072d1229-9262-4616-ac54-8f494d750a58}, ! Default Schedule Set Name
>   {4eaf91bf-f3a4-4bad-bd2c-14610e4ef6e9}, ! Group Rendering Name
>   {91d4cb36-6afe-4b91-bbe6-89d317d8df3e}; ! Design Specification Outdoor Air Object Name
> 
> So maybe this is all really working and just a GUI issue on the OpenStudio app. Dan, I'll re-assign to you. Still a critical bug, but just not as critical.I'll attach model that text is from.

On 2013-02-19 13:29:04, @DavidGoldwasser wrote:

> Created an attachment (id=280)
> model from local template

On 2013-02-19 13:45:49, @DavidGoldwasser wrote:

> Dan, confirmed that forward translation seems to be working. Here is resulting object in IDF file. Looks like just a problem with GUI not showing inherited schedules like it does for other load objects.
> 
> Then again it is a pulldown menu, and maybe those just show the hard field value.
> 
> ZoneInfiltration:DesignFlowRate,
>   ASHRAE_90.1-2004_MediumOffice_Infil,    !- Name
>   ASHRAE_90.1-2004_MediumOffice,          !- Zone or ZoneList Name
>   Medium Office_Infil_Quarter_On,         !- Schedule Name
>   AirChanges/Hour,                        !- Design Flow Rate Calculation Method
>   ,                                       !- Design Flow Rate {m3/s}
>   ,                                       !- Flow per Zone Floor Area {m3/s-m2}
>   ,                                       !- Flow per Exterior Surface Area {m3/s-m2}
>   0.2,                                    !- Air Changes per Hour {1/hr}
>   ,                                       !- Constant Term Coefficient
>   ,                                       !- Temperature Term Coefficient
>   ,                                       !- Velocity Term Coefficient
>   ;                                       !- Velocity Squared Term Coefficient
> 
> 
> I guess easy fix is to make drop zone which probably won't happen for March. I'll lower the priority.

Original attachments:
* RefBldgMediumOfficeNew2004_Chicago_b.osm (ID 280)

Keywords: BadSimResults

**Comment by DavidGoldwasser** [comment]
invalid, it is in the schedule set but doesn't show in inspector choice list.
