### ISSUE TITLE
PAT manual analysis fails if no variables are setup

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2840]
I setup a PAT project where unique design alternatives were setup by skipping specific measures, with all measure shaving only one design option other than "none". This failed with the following error.

![screen shot 2017-11-08 at 10 10 52 am](https://user-images.githubusercontent.com/4857055/32563399-67370fea-c46e-11e7-9cf9-9160f776d82e.png)

I was able to work around this by just picking any argument in any measure and checking the variable option. I didn't even have to make a second measure option to go with the variable. Seems like we could handle this for the user vs. having failed analysis. This would be that un-common when looking at ECMS that are binary vs. something with a dial to adjust.

Note: the Time Series Objective functions were un-related issue.

**Comment by ljbrackney** [comment]
That is by design.  The server needs at least one variable to function properly without significant development.  It was easiest to trap this on the client side, and you need to check something (anything) as a variable for a project to work correctly.

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#43
