### ISSUE TITLE
Empty string or string with just space as string argument value is not treated as valid in PAT but is in OS app 

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2842]
I hit this in reporting measures for internal project where some times I want an argument value to be an empty string. The measure ran fine with this in OS app, but failed to make an OSA in PAT. I even tried changing the string argument value to a space vs. an empty string. Should have same behavior from OS app or PAT.

![screen shot 2017-11-09 at 11 05 11 am](https://user-images.githubusercontent.com/4857055/32621644-b05e556e-c53d-11e7-8e9b-371b2c3a63ec.png)

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#44
