### ISSUE TITLE
PAT app appears to run forever when server hits maximum RAM

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2843]
@henryHorsey my other 'run forever' scenarios happened when one ruby process got hung up. This is different. It is a 6 datapoint project, with about 20 model and E+ measures and 25 reporting measures.

Looking in temp.data the last datapoint did finish (I have all my html files in reports folder and and out.osw). For reference, the pat.json goes from about 0.6mb to 60MB when the project runs, and I save it. I was going to do larger algorithmic analysis on one of the boxes, this was just a test with few datapoints.

![screen shot 2017-11-10 at 12 19 42 pm](https://user-images.githubusercontent.com/4857055/32675299-adf406da-c613-11e7-8e0b-6c97696b3c76.png)

@kflemin not sure if there is anything PAT should do differently here?

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#45
