### ISSUE TITLE
An open DView instance will prevent new eplusout.sql from being written

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#2845]
Steps to replicate:
1. Open DView to review results of a simulated OpenStudio project
2. Make a change in that same project and re-simulate
3. eplusout.sql in the project folder will not be over-written with the new results (can be verified with the file time stamp, or with queries of the sql returning old stale results). 

From a practitioner POV, model troubleshooting sometimes involves repeatedly running simulations and comparing results. This was easy with ResultsViewer, where old results would be retained while new ones could be examined side-by-side in a new instance. A DView instance which locks the sql file from being over-written makes this process much more difficult. Additionally, the OS Results measure will show updated results, but other measures that rely on the project folder eplusout.sql will be returning out of date results.

**Comment by evanweaver** [comment]
This issue was moved to NREL/wex#56
