### ISSUE TITLE
External Wall Measure in PAT does not run

### ISSUE THREAD

**Issue by SuranaShilpa** [NREL/OpenStudio#2846]
Attached is the PAT file with some measures and design alternatives. Tested the wall insulation measure and bundled options. None of them run to complete. The analysis starts but does not complete. 

[VestasEnvelopeParamR01.zip](https://github.com/NREL/OpenStudio/files/1473081/VestasEnvelopeParamR01.zip)

Thanks,

Shilpa Surana 
Energy Analyst 
Brightworks Sustainability

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#46
