### ISSUE TITLE
Application does not reload OSM if external process overwrites OSM

### ISSUE THREAD

**Issue by rpg777** [NREL/OpenStudio#2848]
Changing the name of a space in the App deletes any existing daylighting controls in that space.

**Comment by rpg777** [comment]
@macumber pointed out to me that this is due to the one-way nature of the plugin. Mods via the plugin would need to be reloaded in the App prior to subsequent mods in the App; my "bug" demo workflow was clobbering the control points upon App save. Leaving the issue here but de-escalating it. Sort of a documentation issue for the moment.

**Comment by macumber** [comment]
If other process writes to OSM the OS App should offer to close the current model and load the modified OSM from disk.  This issue will be less important as the SketchUp plug-in is phased out

**Comment by ljbrackney** [comment]
Please be thoughtful about the potential for osm and floorplan.js to get out of sync.  It's an added layer of complexity that adds requirements for things like save as and worse.

**Comment by macumber** [comment]
Good point @ljbrackney , I'm not sure this is worth fixing.  The SketchUp plug-in implements this feature so it is a little weird the app doesn't.  However, once the SketchUp plug-in is deprecated you should have no need for another application to edit the OSM while you have it open in the app.

**Comment by jmarrec** [comment]
In my case, I use a terminal with ruby bindings to do stuff all the time while having the OS App open (way more often than I use sketchup + OS App in parallel). 

But at least PR #3229 will now allow you to click "revert to saved" even if it didn't find the model dirty, I guess that's fine enough.

**Comment by jmarrec** [comment]
I vote we should close this one, since #3229 provides what I need at least.
