### ISSUE TITLE
Daylighting Control Illuminance Setpoint Error

### ISSUE THREAD

**Issue by rpg777** [NREL/OpenStudio#2849]
Placing daylighting control points with the SU plugin results in controls with no illuminance setpoint, even though the default value is present in the inspector field when placed and the model is saved. (i.e., subsequent opening of the OSM in an editor shows null values.)

**Comment by jmarrec** [comment]
Happens because if its defaulted, it isn't translated. I'll remove this check and the equivalent for the secondary DaylitghingControl:

https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp#L371

**Comment by jmarrec** [comment]
Fixed in #2860
