### ISSUE TITLE
Some users have problems getting arguments in scritps tab (Bugzilla #1074)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#285]
On 2013-02-20 08:16:50, @DavidGoldwasser wrote:

> Various warnings. such as "Database not found where expected, boost error". Here are two forum posts. If I find others I'll add them here.
> 
> https://openstudio.nrel.gov/forums/openstudio-application/help-desk/idf-scripts-importidffilerb-error#comment-2231
> 
> https://openstudio.nrel.gov/forums/openstudio-application/bug-reports-and-feature-requests/script-access-blocked-mac-os-1082

**Comment by evanweaver** [comment]
Pre-2.0 issue.
