### ISSUE TITLE
PAT 2.3.0 on Windows - Local Server Not Starting - Server Error

### ISSUE THREAD

**Issue by DrNick13** [NREL/OpenStudio#2857]
PAT 2.3.0 is consistently not starting on opening a Project. Stopping/restarting the server sometimes reconnects the Local Server, but does not reliably reconnect. Ruby processes and mongod are opening, but look to be timing out and not starting.

On start-up:

![image](https://user-images.githubusercontent.com/33544587/33054494-9d4a05ce-cecd-11e7-999a-6a2c190737a0.png)

On attempted Local Run:
![image](https://user-images.githubusercontent.com/33544587/33054560-1241284e-cece-11e7-8d83-e8838839e663.png)

On Server Restart attempts:
![image](https://user-images.githubusercontent.com/33544587/33054940-acfd19b8-ced0-11e7-9b0d-d2f1ad06fb17.png)

**Comment by rHorsey** [comment]
This issue was moved to NREL/OpenStudio-server#251
