### ISSUE TITLE
add missing pump fields from E+ 8.5 and beyond

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#2858]

**Comment by aaron-boranian** [comment]
Make all of the VFD Pump inputs visible.

Specifically the min/max pressure schedules. This comes in handy when modeling a plant with low delta T syndrome.

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9430050)

**NOTE**: These seem to be related to PR #2859. It seems that @kbenne attempted to merge this, then @axelstudios deleted the branch. These min / max pressure inputs are not exposed in the latest OS v2.4, so this appears to still be an issue.
