### ISSUE TITLE
Sum of fraction radiant, fraction lost, etc can be > 1

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2867]
Applies to various types of equipment

**Comment by macumber** [comment]
Needs to be fixed in API and also handled in EnergyPlus translation similar to ThermalZone's fraction daylighting controls

**Comment by joseph-robertson** [comment]
Applies to:
* ElectricEquipment
* GasEquipment
* HotWaterEquipment
* SteamEquipment
* OtherEquipment
* others?
