### ISSUE TITLE
Opening and saving model in OS app deletes any variables added in the SketchUp Plugin (Bugzilla #1093)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#287]
On 2013-02-28 13:38:17, @DavidGoldwasser wrote:

> Here is forum post. I have confirmed this with current trunk.
> https://openstudio.nrel.gov/forums/openstudio-application/bug-reports-and-feature-requests/adding-output-variable-object
> 
> If we are not going to fix this then we should hide this in the inspector in the pluging and make users write a measure (or inject IDF with existing measure) to add requests that we don't offer in the variable's tab.

Keywords: ForumPost

**Comment by DavidGoldwasser** [comment]
@macumber will verify.

**Comment by evanweaver** [comment]
Closed. Please reopen if this is stall a valid bug.
