### ISSUE TITLE
The default chilled beam type is missing 

### ISSUE THREAD

**Issue by muh182** [NREL/OpenStudio#2879]
@kbenne @macumber 

If the chilled beam is placed and connected to a loop, the simulation fails. The chilled beam object is missing the chilled beam type:

`
   ** Severe  ** IP: IDF line~581 Error detected in Object=AIRTERMINAL:SINGLEDUCT:CONSTANTVOLUME:COOLEDBEAM, name=CHILLED BEAM
`

The solution is to change the chilled beam type from "active" to "passive" and then from "passive" to "active.

**Comment by jmarrec** [comment]
I added the CooledBeamType to the hvac_library.osm (was empty), so this should fix it.

Unsure whether we should also write a little something in the VersionTranslator.cpp to ensure that older models get update properly? Thoughts @kbenne?
