### ISSUE TITLE
PAT and OpenStudio store tools separately (Bugzilla #1100)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#288]
On 2013-03-01 12:15:50, @axelstudios wrote:

> It seems pretty silly that you have to scan for tools separately with OpenStudio, and then again with PAT to find the exact same tools...

On 2013-03-28 08:47:44, @macumber wrote:

> Also RunManager stores these separately as well

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
