### ISSUE TITLE
Cannot edit any of the Fractions for the loads in current develop in OS App

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2888]
After some tedious investigation (and a bit of luck probably), I realized it only allows 0 or 1 to be entered, exactly. If you try to put 1.0 or 0.0 it doesn't work. 

The IDD prevents you from inputting something higher than 1 or lower than 0, but it doesn't allow you to input a decimal separator in there for some reason. 

The underlying API calls work perfectly in ruby/c++.

This affects all the OSQuantityEdit fields (and OSDoubleEdit too) (eg for Luminaire Definition, you cannot set Lighting Power to 50.5 either, but 50 or 51 is ok)

@evanweaver any ideas?

**Comment by macumber** [comment]
This is the issue I thought might be related but I don't see any code changes associated with it https://github.com/NREL/OpenStudio/issues/1578

**Comment by jmarrec** [comment]
Could potentially be linked to my two commits that got merged in recently: 
https://github.com/NREL/OpenStudio/commits/develop/openstudiocore/src/shared_gui_components

**Comment by jmarrec** [comment]
I can enter 1e-3 just fine, and it does save to the osm...

**Comment by jmarrec** [comment]
This happens to me on Linux, @macumber said it's working for him on Windows... :/

**Comment by evanweaver** [comment]
Hi @jmarrec, @macumber and I just tested the 2.3.1 RC on Ubuntu and had no issues.

**Comment by jmarrec** [comment]
@evanweaver this is a locale issue.

QDoubleValidator uses the system locale.

$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=fr_FR.UTF-8
LC_TIME=fr_FR.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=fr_FR.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=fr_FR.UTF-8
LC_NAME=fr_FR.UTF-8
LC_ADDRESS=fr_FR.UTF-8
LC_TELEPHONE=fr_FR.UTF-8
LC_MEASUREMENT=fr_FR.UTF-8
LC_IDENTIFICATION=fr_FR.UTF-8
LC_ALL=

If do `export LC_NUMERIC="en_US.UTF-8"` in a terminal then `Products/OpenStudioApp` in the same, setting the number to "0.5" for example will work.

**Comment by jmarrec** [comment]
Fixed in #2888, works on my Ubuntu 16.04 with `LC_NUMERIC=ft_FR.UTF-8`

**Comment by evanweaver** [comment]
Thanks!
