### ISSUE TITLE
Reports Tab - EnergyPlus HTML table prevents results from showing for model (Bugzilla #1126)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#289]
On 2013-03-06 22:46:59, @DavidGoldwasser wrote:

> This is same issue as bug 1072 that affects the OpenStudio application. The example IDF script I have does this. Made sense for users to get ABUPS in IP since the rest of the app is IP, but it messing things up.
> 
> This is the workspace object involved. "OutputControl:Table:Style"

**Comment by macumber** [comment]
See https://github.com/NREL/OpenStudio/issues/283 for the resolution
