### ISSUE TITLE
2.3.1 AirLoopHVAC doesn't have an AvailabilityManagerAssignmentList assigned

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2891]
Updated a 2.3.0 model to 2.3.1, which caused the following [error](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/AirLoopHVAC.cpp#L1248) introduced in #2844. Workaround was to manually change the version back to 2.3.0. FYI @jmarrec and @kbenne.

>[15:32:14.896754 ERROR] Found error in state 'translator' with message ["E:\\Git\\OS1\\openstudiocore\\src\\model\\AirLoopHVAC.cpp@1248 : Object of type 'OS:AirLoopHVAC' and named 'Air Loop AHU'doesn't have an AvailabilityManagerAssignementList assigned, which shouldn't happen::/ruby/2.2.0/gems/openstudio-workflow-1.3.1/lib/openstudio/workflow/util/model.rb:66:in `translateModel'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.1/lib/openstudio/workflow/util/model.rb:66:in `translate_to_energyplus'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.1/lib/openstudio/workflow/jobs/run_translation.rb:54:in `perform'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.1/lib/openstudio/workflow/run.rb:261:in `step'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.1/lib/openstudio/workflow/run.rb:210:in `run'\n:/openstudio_cli.rb:821:in `execute'\n:/openstudio_cli.rb:620:in `execute'\n:/openstudio_cli.rb:1547:in `<main>'\neval:85:in `eval'\neval:85:in `require_embedded_absolute'\neval:70:in `block in require'\neval:64:in `each'\neval:64:in `require'\neval:2:in `<main>'"]}

**Comment by jmarrec** [comment]
I didn't think about writing a proper version translator, I'm on it.

**Comment by jmarrec** [comment]
Fixed in #2891 and tested with a 2.3.0 model that I had created in 2.3.0 bindings. I just extended my tests, and realized there's a problem with the AvailabilityManagerNightCycle, so I'll fix this now too...

**Comment by jmarrec** [comment]
Ok, done, I added a proper version translation for the AVM:NightCycle (has a new field inserted before the end, and need to create the 4 control Lists (ModelObjectLists)).

see #2891 for more info and testing.
