### ISSUE TITLE
Misc. GUI things I noticed (Bugzilla #1127)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#290]
Assigned to: Marjorie Schott

On 2013-03-07 11:45:30, @DavidGoldwasser wrote:

> These are trivial, but I just wanted to document them to discuss sometime after the release.
> 1. On the Measures tab the measure names in the library do not wrap. Many of the measures have very long names so they are descriptive enough. In the OS app, library objects wrapped, so it is a bit inconstant that they do not here. Many users may not know that they can expand the library width to see the full name.
> 2. On the Design Alternative tab the box below "Description" for the design alternative is grey. To me this normally indicates that it is a ready only text box vs. a place to enter text, I do however see the need to distinguish this from the description.

On 2013-03-07 12:01:05, @DavidGoldwasser wrote:

> 1. Splash screen. I like the look of this, but it almost looks like the interface vs. a splash screen. Something as simple as insetting it and putting a border around it may help. And since the real tabs are not clickable maybe they shouldn't be there, or it should prompt you to make a new project. Along these same lines could have a button on the splash screen to open project or make new (similar to what Kyle had for OS App a while back).

On 2013-03-11 00:17:09, @DavidGoldwasser wrote:

> 1. In the design alternative tab the name of a selected measure is right justified, and the start of the name is truncated. Other fields are left justified.

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
