### ISSUE TITLE
simulation errors and warnings notification unavailable

### ISSUE THREAD

**Issue by irfanirw** [NREL/OpenStudio#2905]
Do you know how to solve this? The simulation errors and warnings notifications was unavailable before, during, and after the simulation of my model (picture link below). I'm afraid that there was any major errors or warnings during my simulation that i could not check.
 
Anyway, I am using Sketchup 2017 and Openstudio version 2.3.1. I already tried some of the other versions like Openstudio 2.2.0, 2.3.0 including sketchup 2016 + Openstudio 2.0.0 but still doesn't work at all. Running on Windows 10 x64.

[image](https://user-images.githubusercontent.com/34654406/34112507-5876ba6e-e43f-11e7-8f87-34c2579f13db.png)

**Comment by macumber** [comment]
This question is best asked on unmethours.com, that is a forum where you will get answers in a timely way from other modelers.
