### ISSUE TITLE
inconsistent ForwardTranslator behavior

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2908]
Found in 2.3.0 and 2.4.0. Doesn't seem to be an issue with complete models, but it's currently blocking a unit test for some code we've developed. Steps to reproduce.

```
require 'openstudio'

m = OpenStudio::Model::Model.new
OpenStudio::Model::FanConstantVolume.new(m)
OpenStudio::Model::FanOnOff(m)
OpenStudio::Model::FanVariableVolume.new(m)
puts m

w = OpenStudio::EnergyPlus::ForwardTranslator.new.translateModel(m)
puts w
```

**Comment by MatthewSteen** [comment]
Same for CoilHeatingElectric.

---

```
require 'openstudio'

m = OpenStudio::Model::Model.new
OpenStudio::Model::FanConstantVolume.new(m)
OpenStudio::Model::FanVariableVolume.new(m)
OpenStudio::Model::CoilHeatingElectric.new(m)
OpenStudio::Model::CoilHeatingGas.new(m)
puts m

w = OpenStudio::EnergyPlus::ForwardTranslator.new.translateModel(m)
# remove objects added with forward translation
cls_names = ['LifeCycleCost:Parameters',
             'LifeCycleCost:UsePriceEscalation',
             'Building',
             'SimulationControl',
             'Sizing:Parameters',
             'RunPeriod',
             'GlobalGeometryRules',
             'ScheduleTypeLimits',
             'Schedule:Constant',
             'OutdoorAir:Node',
             'OutputControl:Table:Style',
             'Output:Table:SummaryReports',
             'Output:VariableDictionary',
             'Output:SQLite',
             'LifeCycleCost:NonRecurringCost']
cls_names.each do |cls_name|
  w.getObjectsByType(cls_name.to_IddObjectType).each { |obj| obj.remove }
end
puts w
```

**Comment by DavidGoldwasser** [comment]
@MatthewSteen You should be able to forward translate even incomplete models. I'll bing @kbenne about this.

**Comment by MatthewSteen** [comment]
I suspect that there's some magic happening to prevent orphaned objects, although I didn't notice anything in the code. For example, PumpConstantSpeed and PumpVariableSpeed objects are not translated unless they're on a PlantLoop.

**Comment by jmarrec** [comment]
This works as expected. A lot of objects aren't automatically translated, their translation is called from whatever parent object uses them.

All objects that **aren't** in `ForwardTranslator::iddObjectsToTranslateInitializer()` are not always translated unless they are actually used by something else. cf https://github.com/NREL/OpenStudio/blob/a1449287fe7855d289d7dc80eb5aa474ef9de9f6/openstudiocore/src/energyplus/ForwardTranslator.cpp#L3408
