### ISSUE TITLE
Back Side Solar Reflectance Field Not Editable in App

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2910]
When creating a Glazing Window Material in the app, the Back Side Solar Reflectance field cannot be edited for a material w/ SpectralAverage optical data.  No default is provided either.

![glass](https://user-images.githubusercontent.com/2230150/34445977-83c3978c-ec8c-11e7-970a-ba23f19498b8.png)

**Comment by evanweaver** [comment]
Fixed via https://www.pivotaltracker.com/n/projects/134010/stories/154539040
