### ISSUE TITLE
cli run does not find e+ when running a simulation

### ISSUE THREAD

**Issue by IainMacdonald** [NREL/OpenStudio#2911]
Running on docker using the cli to run the example osw file fails as e+ is not found (it works on windows though).

To reproduce this the following works: `docker pull nrel/openstudio:2.2.1; docker run -it nrel/openstudio:2.2.1 /bin/bash -c "cp -r /usr/Examples/compact_osw . && openstudio run -w compact_osw/compact.osw"` 

May be related to issue 2616.

**Comment by IainMacdonald** [comment]
if a full path is provided to the openstudio exe (i.e. /usr/bin/openstudio) then it works for the latest version.

**Comment by macumber** [comment]
duplicate of https://github.com/NREL/OpenStudio/issues/2616 which was fixed
