### ISSUE TITLE
Space fields not translated

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2912]
- [x] "below_floor_plenum_height"
- [x] "floor_to_ceiling_height"
- [x] "above_ceiling_plenum_height"
- [x] "floor_offset"
- [x] "open_to_below"

**Comment by shorowit** [comment]
open to below is correct in the osm, but not in the geometry preview.

**Comment by ljbrackney** [comment]
I've noted this also.

**Comment by macumber** [comment]
If incorrect rendering of air walls is the only remaining issue, I suggest closing this issue and logging the error here: https://github.com/macumber/openstudio-vA3C/issues/44
