### ISSUE TITLE
Shading objects not translated

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2914]
Also need to handle adjacency between shading and spaces

**Comment by macumber** [comment]
Shading objects are not intersected with regular surfaces

**Comment by shorowit** [comment]
In OS 2.4.1, I get this error with merge or preview when using shading objects:
![image](https://user-images.githubusercontent.com/5861765/36043742-8ff65e50-0d8d-11e8-93f7-5553b7293468.png)

**Comment by shorowit** [comment]
I'm not seeing shading objects show up in the geometry preview window in 2.5.0.

![image](https://user-images.githubusercontent.com/5861765/38321172-01ee758e-37f4-11e8-9eb5-e42ff5de5cd7.png)
