### ISSUE TITLE
Unable to Open IFC file from Openstudio

### ISSUE THREAD

**Issue by YukioCYH** [NREL/OpenStudio#2925]
Hi, I had some problem here regarding importing IFC to Open Studio. I followed all the steps on https://nrel.github.io/OpenStudio-user-documentation/tutorials/tutorial_ifcimport/ and also able to upload the IFC files onto Open studio as shown below.
![image](https://user-images.githubusercontent.com/34933205/34923142-0049e1a4-f9d4-11e7-8e33-78b22eb23921.png)
After clicking 'Download OSM file', Open studio will prompt a message to save or discard the original file that you opened previously. (usually I clicked discard)

But after discarding the original file, another file will automatically reopened again. And I assumed that it is the IFC file that I imported in previously. It do not open the IFC file that I imported but opened an empty file.

So I am not sure what is happening and probably something wrong with the format of my IFC file? But I export it from Sketch Up make 2017.
![image](https://user-images.githubusercontent.com/34933205/34923147-0f469f26-f9d4-11e7-95e5-d2018380571d.png)
Can someone please help? Thank you

Regards,

YH

**Comment by macumber** [comment]
The IFC import has developed by Penn State, https://faculty.ist.psu.edu/wu/papers/BIM-ASCE2013.pdf, so unfortunately I don't know too much about it.  I do know that it looks for certain types of surfaces and IFC keywords but I don't know what those are.  It's possible you could contact some of the authors of the paper I linked for more information?

**Comment by jmarrec** [comment]
Should we close this as won't fix @macumber ?

**Comment by macumber** [comment]
Yes let’s close as won’t fix for now
