### ISSUE TITLE
Update documentation for the install.qs script for silent installation

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2930]
This might already exist, in that case this is just a documentation issue

Edit: It does exist.

**TODO:**
   * [ ] Update docs to link to the install.qs script #2930 (comment)

**Comment by kbenne** [comment]
@axelstudios didn't you develop a js script to do this?

**Comment by axelstudios** [comment]
Kind of - We have to start packaging OpenStudio with Qt IFW v3 instead of v2.0.3 to actually use the silent option, but currently it's a fully-automated install process for Windows.  The Ubuntu installer is a `.deb` package, so that one can already be installed silently from the command line, and the Mac installer is a `.zip` which just contains the `.app` directory.

e.g. `OpenStudio-2.3.0.cf58ee1e38-Windows.exe --script install.qs` with this file saved as install.qs it will automatically install only the Ruby API.

```javascript
function Controller () {
  // gui.setSilent(true);
}

Controller.prototype.IntroductionPageCallback = function () {
  gui.clickButton(buttons.NextButton);
}

Controller.prototype.ComponentSelectionPageCallback = function () {
  var widget = gui.currentPageWidget();
  widget.deselectAll();
  widget.selectComponent('RubyAPI');
  gui.clickButton(buttons.NextButton);
}

Controller.prototype.TargetDirectoryPageCallback = function () {
  gui.clickButton(buttons.NextButton);
}

Controller.prototype.StartMenuDirectoryPageCallback = function () {
  gui.clickButton(buttons.NextButton);
}

Controller.prototype.ReadyForInstallationPageCallback = function () {
  gui.clickButton(buttons.NextButton);
}

Controller.prototype.FinishedPageCallback = function () {
  gui.clickButton(buttons.FinishButton);
}

```

**Comment by macumber** [comment]
I put an updated script at https://github.com/NREL/OpenStudio/blob/develop/install.qs, we can have the docs link to it

**Comment by IOMadness** [comment]
Hi, I'm a IT Tech at a university and we're trying to deploy OpenStudio 2.7 with this script, but it seems to be getting hung up after it shows "Installation Finished", and brings up a window waiting for the user to press "Next". I tried editing the install.qs file, and adding
gui.clickButton(buttons.NextButton);
in the Controller.prototype.FinishedPageCallback = function () section, but it doesn't seem to register.

**Comment by axelstudios** [comment]
@IOMadness Can you share the install script that you're currently testing?  I tried the one above (and the [one in the repo](https://github.com/NREL/OpenStudio/blob/develop/install.qs)) with OpenStudio v2.7.1 and Windows 10, and both exited successfully after the install process.

**Comment by IOMadness** [comment]
Ok, so, I'm not sure what was happening, but was able to try it again yesterday and it seemed to work fine the way it is. I was using the script basically as it is, just with the proper products and install location set. Not sure. Thanks anyway, I suppose.

**Comment by IOMadness** [comment]
Ok, so, I'm not sure what was happening, but was able to try it again yesterday and it seemed to work fine the way it is. I was using the script basically as it is, just with the proper products and install location set. Not sure. Thanks anyway, I suppose.

**Comment by jmarrec** [comment]
TODO:

* [ ] Update docs to link to the install.qs script https://github.com/NREL/OpenStudio/issues/2930#issuecomment-373594984

**Comment by jmarrec** [comment]
Done:

![image](https://user-images.githubusercontent.com/5479063/121146062-d95a4a00-c83f-11eb-9632-85d5c7928a89.png)

https://nrel.github.io/OpenStudio-user-documentation/getting_started/getting_started/
