### ISSUE TITLE
Require native gems in CLI

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2932]

**Comment by macumber** [comment]
Upgraded to major because blocking @shorowit

**Comment by macumber** [comment]
https://docs.google.com/document/d/10MKMEJ4NWxanrlVKKqMYzhehqrU5IIBYSBHbMltd4lY/edit#heading=h.xh61y0yzewmf

**Comment by aaron-boranian** [comment]
Allow use of gems in CLI and OS Server. Should be able to specify a gemfile or something to control which gems are used for a given workflow, maybe allow measures to specify their own gems and then bundle at the OSW level.

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/20159504)

**Comment by macumber** [comment]
I've reached the conclusion that we can't load native gems compiled against MinGW Ruby runtime into the OpenStudio CLI which is currently statically linked against the MSWin Ruby runtime.  We also can't statically link OpenStudio CLI built with MSWin against MinGW Ruby runtime.  It should be possible to dynamically link the OpenStudio CLI to the  MinGW Ruby runtime.

There are good notes on building MinGW ruby at http://rubyonwindowsguides.github.io/book/ch02-02.html

Attached is a script which attempts to create a single import library for all of the various .so files that are included in the Ruby lib\ruby\2.2.0\x64-mingw32 directory.

[make_dot_as.rb.txt](https://github.com/NREL/OpenStudio/files/1921914/make_dot_as.rb.txt)

Note that native gems should be able to load on Unix and Mac

**Comment by macumber** [comment]
When building Ruby, each extension is first checked with the `\src\Ruby\ext\#{ext}\extconf.rb` script.  This is were we can see all of the rules that turn on or off each extension.

**Comment by macumber** [comment]
Did some preliminary work on this branch https://github.com/NREL/OpenStudio/tree/ruby_ext

**Comment by nealkruis** [comment]
@macumber I think this is the blocking issue for accessing Modelkit from OpenStudio.

**Comment by macumber** [comment]
Believe that the best solution for this is https://github.com/NREL/OpenStudio/issues/3539

**Comment by jmarrec** [comment]
@kbenne I think your native gem approach closes that.
