### ISSUE TITLE
View Reports Tab - Open Copy in OpenStudio doesn't bring weather file over (Bugzilla #1153)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#294]
On 2013-03-11 11:08:42, @DavidGoldwasser wrote:

> When I Open a model from PAT in OpenStudio via the button on the results tab, it looks like it has a weather file, but when I saved and ran, EnergyPlus failed because of missing weather file (even though that same model ran fine in PAT.

On 2013-03-28 11:14:58, @axelstudios wrote:

> Doesn't seem to work on Linux - I ran a simulation fine in Pat, clicked one of the results to create a copy and open with OpenStudio, and the weather file wasn't carried through

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
