### ISSUE TITLE
More selective output

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2943]
@mostaphaRoudsari @chriswmackey have requested the ability to request less output data as it slows down import.  We need more information on this issue.  Does this refer to timeseries data?

**Comment by chriswmackey** [comment]
@macumber , I think that most of our desires here  would be addressed if we just investigated the part of the SDK about SQL Lite more. This was more of a comment that I made out of my own ignorance than anything else so I don't think it necessarily involves changes to the OpenStudio code base. Are there any measures or code examples that you have of the SQL workflows?  That could get me up to speed faster.

**Comment by mostaphaRoudsari** [comment]
@macumber, Is there a solution to customize the data that will be dumped into the sql file? If there is one then that's all we really need. Our understanding is that the current sqlite file schema is fixed and tables and data are generated regardless of user's input for output fields.

**Comment by jmarrec** [comment]
The SQL structure is set by E+. Then specifying OutputTable/OutputVariables/OUtputMeter will end up adding more or less data. https://github.com/NREL/OpenStudio/pull/3787 fixed the rest.
