### ISSUE TITLE
Improve Output Variables Reporting

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2947]
https://openstudio.uservoice.com/forums/308629-openstudio/suggestions/10100958-improve-output-variables-reporting

Problem: The current Output Variables tab does not include all OVs available and the Add Output Variables measure is cumbersome to use.

Rationale: Hourly output can be extremely useful for trouble shooting.

Solution: The existing Output Variable tab could be improved to show all OVs from the last sim's RDD file or none if the model has not been run yet. Additional features that would be useful are the ability to select groups of OVs and an option for specifying an OV's Key Value.

One solution could be to group OVs into expandable category bars similar to the Library sidebars found throughout the main OS tabs. These bars could allow the user to select all OVs of a certain category or individual OVs by expanding the bar. For example the user could select all Cooling Coil Output Variables or individual ones. Selecting all would probably need a warning about the number of OVs that would be reported. A string field for the Key Value could be added to trouble shoot specific objects but would not allow for multiple OVs for individual objects.

Context: see EnergyPlus object Output:Variable and the RDD file.

**Comment by aaron-boranian** [comment]
Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/10100958)

**Comment by brianlball** [comment]
This PR https://github.com/NREL/OpenStudio/pull/3020 added all the OutputVariables to outputVariableNames() methods for all ModelObjects.

**Comment by jmarrec** [comment]
In https://github.com/NREL/OpenStudio/pull/2700 I have added pretty much all specific object variables, with brian's PR I think this one can be closed. We can open specific PRs if we find out of date/lacking variables further down the road.
