### ISSUE TITLE
Allow editing multiple elements of same type withinin SketchUp plugin

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2956]
https://openstudio.uservoice.com/forums/308629-openstudio/suggestions/12943143-allow-editing-multiple-elements-of-same-type-withi

Currently if you select two of any model element (two spaces, two subsurfaces, etc) the Inspector tool reverts to the OS:Building view and you are not able to edit properties specific to the element type in your selection.

I propose the plugin include a check to see whether all elements in the selection are of the same type, and if they are then allow the Inspector tool to be used to edit the properties of that element type. It would be very valuable, for instance, to be able to select a group of spaces or zone and modify a property for the entire selection at once rather than needing to do it one-by-one.

**Comment by aaron-boranian** [comment]
Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/12943143)

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/20
