### ISSUE TITLE
allow user to specify VRF condenser type in GUI

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2960]
https://openstudio.uservoice.com/forums/308629-openstudio/suggestions/9564327-allow-user-to-specify-vrf-condenser-type-in-gui

Many inputs related to water-cooled and evaporatively cooled condensers are editable for VRF systems but only air-cooled condensers for VRF systems are supported in the app.

It would also be helpful if users could drag a VRF system to the load side of a condenser loop.

**Comment by aaron-boranian** [comment]
Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9564327)

**Comment by eringold** [comment]
There seems to be no way to make a water-cooled VRF system even with the SDK. Despite there being FT code to handle the plant nodes, (https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirConditionerVariableRefrigerantFlow.cpp#L771-L815), neither `plantLoop.addDemandBranchForComponent(vrf)` or `vrf.addToNode(demandBranchNode)` will do anything (as of 2.7.0).

**Comment by luisclv** [comment]
Even just having methods in the SDK to add the condenser to a branch in a plantloop would be useful. A lot of large building applications have water cooled systems.

**Comment by jmarrec** [comment]
THis is fixed already, https://github.com/NREL/OpenStudio/pull/3613
