### ISSUE TITLE
ScheduleDay reference is lost when after calling .setWinterDesignDaySchedule on ScheduleRuleset

### ISSUE THREAD

**Issue by pflaumingo** [NREL/OpenStudio#2968]
After instantiating a ScheduleDay object and passing it into the setWinterDesignDaySchedule method on a ScheduleRuleset, the reference to the ScheduleDay object is lost. This can be seen in the openstudio-standards gem [here](https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/standards/Standards.Model.rb#L2211) where after passing in the ScheduleDay object it then needs to get a reference to the ScheduleRuleset's winter design day ScheduleDay object again. If that call to ScheduleRulset.winterDesignDaySchedule is not made then any subsequent changes to the ScheduleDay do not translate.

**Comment by jmarrec** [comment]
This is working as designed, and the docstring is clear on what's happening.

https://github.com/NREL/OpenStudio/blob/9fcb8418a56cce41cbff51c28c0aa45af9ea32f7/src/model/ScheduleRuleset.hpp#L113-L116

And implementation:

https://github.com/NREL/OpenStudio/blob/9fcb8418a56cce41cbff51c28c0aa45af9ea32f7/src/model/ScheduleRuleset.cpp#L335-L360


This is perhaps a bit weird at first. cf `ScheduleRuleset_Impl::resources()` and `ScheduleRuleset_Impl::children()`: the defaultDaySchedule, and winter/summer/holiday Schedules aren't treated as resources but as children. 
I'm pretty sure the idea is that it would be very confusing to be able to share ScheduleDay accross ScheduleRuleset, where modification of one would modify another.
In particular, say you would clone a ScheduleRuleset (in the OSApp or the CLI), for eg a "Deck Temperature Schedule", so you could modify it to create a similar yet sligthly difference "Deck Temperature Schedule with Reset". If schedule days were a resource, the clone would be sharing these resources with the original one, and you would be modifying both ScheduleRulesets at the same time.
