### ISSUE TITLE
The save as dialog does not pre-populate the file name with the current filename. (Bugzilla #1162)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#297]
On 2013-03-12 12:22:53, @elainethale wrote:

> Linux, release, developer build. Do not know if this problem is specific to Linux and/or developer build.
> 
> When using save as, especially if I navigate away from the original location, I expect the filename to be preserved by default. Instead, it shows up as blank and I have to retype it.

**Comment by jmarrec** [comment]
Same on mac in 2.2.1. (I don't care personally)
