### ISSUE TITLE
Lighten dependencies for utilities geometry

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2970]
- [ ] Remove filesystem dependency in FloorplanJS and ThreeJS (or make compile time switch)
- [x] https://github.com/NREL/OpenStudio/issues/2966
- [ ] Move Workspace and BCL comparators out of Compare.hpp
- [x] Remove Qt functionality from JSON.hpp

**Comment by jmarrec** [comment]
Last one (Qt) is definitely happening in develop3

**Comment by jmarrec** [comment]
This has moved to openstudiocoalition/OpenStudioApplication anyways.
