### ISSUE TITLE
2.4.0 error: The zone inlet node in the controlled zone is not found.

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2972]
I'm getting a failed simulation when using two unitary systems, one as an airloophvac and one as a zonehvac. Simple test added here:
https://github.com/NREL/OpenStudio-resources/tree/unitary_systems_airloop_and_zonehvac

The above test works fine if I use just the airloophvac or just the zonehvac, but not both.

Error is:
```
   ** Severe  ** AirLoopHVAC:UnitarySystem "AIR LOOP HVAC UNITARY SYSTEM 1": The zone inlet node in the controlled zone (STORY 1 NORTH PERIMETER THERMAL ZONE) is not found.
   **  Fatal  ** Subroutine InitLoadBasedControl: Errors found in getting AirLoopHVAC:UnitarySystem input.  Preceding condition(s) causes termination.
```

The err file also has a weird severe (but not fatal) error:
```
   ** Severe  ** SizeUnitarySystem: AirLoopHVAC:UnitarySystem = AIR LOOP HVAC UNITARY SYSTEM 1
   **   ~~~   ** Illegal entry for Cooling Supply Air Flow Rate Method.
```

@kbenne @jmarrec

**Comment by kbenne** [comment]
This was an E+ bug which is tracked and closed here https://github.com/NREL/EnergyPlus/issues/6405.
Tested that the affected file is working on the OS branch supporting E+ 8.9.0
