### ISSUE TITLE
Unit inducing mistake when you set a Cooling Tower in OpenStudio / EnergyPlus

### ISSUE THREAD

**Issue by geraldopithon** [NREL/OpenStudio#2979]
To set Cooling Tower, if you use Evaporation Loss Mode: Loss Factor, you will need to set Evaporation Loss Factor. The unit showed is percent/K. So, InputOuputReference indicates a typical value from 0,15 to 0,27 [percent/K]. But you need to set in program 0,0015 to 0,0027 to result in reasonable results. In other words, you need "to do the percent" before you set this parameter. If not, the results are unreals.

**Comment by jmarrec** [comment]
This is working as designed.

```
  N11 , \field Evaporation Loss Factor
       \type real
       \units percent/K
       \note Rate of water evaporation from the cooling tower and lost to the outdoor air [%/K]
       \note Evaporation loss is calculated as percentage of the circulating condenser water rate
       \note Value entered here is percent-per-degree K of temperature drop in the condenser water
       \note Typical values are from 0.15 to 0.27 [%/K].
       \default 0.2
```

The default is 0.2%/K, and that's what's showed in the object.

![image](https://user-images.githubusercontent.com/5479063/76858579-0051e800-6858-11ea-9fc6-6ad4c781c478.png)
