### ISSUE TITLE
weather (epw) and ddy file path issues (Bugzilla #1163)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#298]
On 2013-03-12 12:36:32, @elainethale wrote:

> Linux, release, developer build. I do not know if this issue is platform-dependent.
> 
> 1. After I choose an epw file, I would expect the same folder to open up when I browse for a ddy file, but that is not happening.
> 
> 2. The last epw file location is not remembered.
> 
> 3. Similarly, the setting "Default Weather Location" under the Show Tools menu item is not hooked up.

**Comment by macumber** [comment]
@evanweaver I believe you are working on this

**Comment by evanweaver** [comment]
Both the epw and ddy folders are now persisted.
