### ISSUE TITLE
Wrap Schedule:File

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2988]

**Comment by macumber** [comment]
Related links:

https://unmethours.com/question/14348/can-you-load-schedulefile-in-openstudio/

https://github.com/NREL/OpenStudio/issues/2924
https://github.com/NREL/OpenStudio/issues/1451
https://github.com/NREL/OpenStudio/issues/50

**Comment by tsbyq** [comment]
Importing the schedules from an IDF with Shcedule:File would be a great feature!

**Comment by macumber** [comment]
Closing this enhancement, import of ScheduleFile is listed here https://github.com/NREL/OpenStudio/issues/3347
