### ISSUE TITLE
LoadProfilePlant.new(model) assigns bad default schedule scheduletypelimits

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#2991]
In OSv2.4: Creating a LoadProfilePlant through the API without including schedules in the constructor will create a default load schedule for the object:

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/LoadProfilePlant.cpp#L197

With values up to 10000, along with a ScheduleTypeLimits object of numeric type = Continuous, but no lower or upper limit values: 

```
OS:Schedule:Day,
  {87861c55-af9a-4398-8b78-a450abc59c90}, !- Handle
  Schedule Day 1,                         !- Name
  {bd3e4115-79ac-45e4-8312-9c4fbdbf74f3}, !- Schedule Type Limits Name
  ,                                       !- Interpolate to Timestep
  4,                                      !- Hour 1
  0,                                      !- Minute 1
  8000,                                   !- Value Until Time 1
  8,                                      !- Hour 2
  0,                                      !- Minute 2
  6000,                                   !- Value Until Time 2
  9,                                      !- Hour 3
  0,                                      !- Minute 3
  0,                                      !- Value Until Time 3
  12,                                     !- Hour 4
  0,                                      !- Minute 4
  6000,                                   !- Value Until Time 4
  24,                                     !- Hour 5
  0,                                      !- Minute 5
  10000;                                  !- Value Until Time 5

OS:ScheduleTypeLimits,
  {bd3e4115-79ac-45e4-8312-9c4fbdbf74f3}, !- Handle
  Dimensionless,                          !- Name
  ,                                       !- Lower Limit Value
  ,                                       !- Upper Limit Value
  Continuous;                             !- Numeric Type
```

However this ScheduleTypeLimits will be translated to an idf object with lower and upper limit values of 0 and 1:

```
ScheduleTypeLimits,
  Dimensionless 3,                        !- Name
  0,                                      !- Lower Limit Value {BasedOnField A3}
  1,                                      !- Upper Limit Value {BasedOnField A3}
  Continuous,                             !- Numeric Type
  dimensionless;                          !- Unit Type
```

Which will cause a fatal error:

```
   ** Severe  ** ProcessScheduleInput: Schedule="SCHEDULE RULESET 3" has values outside its Schedule Type (DIMENSIONLESS 3) range
   **   ~~~   **   Minimum should be >=0.000 and Maximum should be <=1.000
```

I'm not sure where the default lower/upper limit values come from, since while the field A3 in the E+ idd does specify `/default dimensionless` it doesn't have default numeric values.

**Comment by jmarrec** [comment]
Euh, @eringold are you sure you're looking at the same schedule type limits?
Because the API object is named "Dimensionless" and your IDF you're showing is named "Dimensionless 3".

I see no evidence whatsoever that default of 0 and 1 would be put for missing lower limit values.

https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateScheduleTypeLimits.cpp#L51

**Comment by eringold** [comment]
OK I was wrong, but I still think this might be a bug. 

When the LoadProfilePlant default schedules are created, they are assigned an existing scheduletypelimits object named "Dimensionless" (or, in my case, I had three 'Dimensionless' scheduletypelimits, and the "Dimensionless 3" object, with upper/lower limits of 0 and 1, was assigned). 

So the scheduletypelimits forwardtranslation was fine, the problem is the assignment of the scheduletypelimits when the scheduleruleset is created here: https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/LoadProfilePlant.cpp#L207

So probably what should happen is the LoadProfilePlant default schedules get their own scheduletypelimits with limits that match the schedule values (or check the limits in existing objects before assigning them to that schedule).

Thanks @jmarrec

**Comment by jmarrec** [comment]
So I dug in, and it's quite interesting frankly.

Anyways, the core thing happens here: https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/ScheduleTypeRegistry.cpp#L502:L533

`    {"LoadProfilePlant","Load","loadSchedule",true,"",OptionalDouble(),OptionalDouble()},`


----

Test 1: No existing one, OK

```
m = Model.new
p = LoadProfilePlant.new(m)
puts p.loadSchedule.scheduleTypeLimits.get
```

There's no ScheduleTypeLimits, so it creates one like we expect:

```
OS:ScheduleTypeLimits,
  {0d72993b-7b93-44ef-b44c-b9e1c5b739f1}, !- Handle
  Dimensionless,                          !- Name
  ,                                       !- Lower Limit Value
  ,                                       !- Upper Limit Value
  Continuous;                             !- Numeric Type
```

----

Test 2: there's a continuous schedule type limits already, but with a non reserved name

```
m = Model.new
sch_type_limits = ScheduleTypeLimits.new(m)
sch_type_limits.setName("A random Continuous one")
sch_type_limits.setLowerLimitValue(0.5)
sch_type_limits.setUpperLimitValue(0.7)
sch_type_limits.setNumericType("Continuous")

p = LoadProfilePlant.new(m)
puts p.loadSchedule.scheduleTypeLimits.get
```

```
OS:ScheduleTypeLimits,
  {7d43a055-4936-44e9-9fa8-d69837255b01}, !- Handle
  Dimensionless,                          !- Name
  ,                                       !- Lower Limit Value
  ,                                       !- Upper Limit Value
  Continuous;                             !- Numeric Type
```
-----

Test 3: existing one, named Dimensionless

```
m = Model.new
sch_type_limits = ScheduleTypeLimits.new(m)
sch_type_limits.setName("Dimensionless")
sch_type_limits.setLowerLimitValue(0.5)
sch_type_limits.setUpperLimitValue(0.7)
sch_type_limits.setNumericType("Continuous")

p = LoadProfilePlant.new(m)
puts p.loadSchedule.scheduleTypeLimits.get
```

```
OS:ScheduleTypeLimits,
  {9b8e9589-33b1-492e-9e15-3f2d2607e9b9}, !- Handle
  Dimensionless,                          !- Name
  0.5,                                    !- Lower Limit Value
  0.7,                                    !- Upper Limit Value
  Continuous;                             !- Numeric Type
```
