### ISSUE TITLE
OS app geometry refresh needs ok/cancel dialog

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2993]
If you (accidentally) click Refresh on the OS app's geometry tab, you will immediately lose your active work (that hasn't been merged) with no way to undo/redo. A user might think refresh is going to fix glitches in the geometry editor while preserving their active work. Should probably have a dialog that tells the user they will lose any work since their last merge with ok/cancel buttons?

**Comment by macumber** [comment]
@shorowit refresh should not be needed, it was a back up in case the editor crashed.  So do we need refresh and if so what should refresh do?

**Comment by jmarrec** [comment]
@shorowit thoughts?

**Comment by jmarrec** [comment]
@shorowit I'm having trouble reproducing this on Windows with 2.71, could you help?

Things I tried:

* If I'm on the 'Editor' tab, do something new, then click "Preview OSM" and in there I hit refresh, nothing is lot.

* If I'm on the 'Editor' tab, and try to switch to '3D View', I get a message
![image](https://user-images.githubusercontent.com/5479063/53496011-6c24af80-3aa1-11e9-9f6d-3e1bb7bd277f.png)

* If I go on the SpaceType tab, add new space types, then go to the '3D View' tab and hit 'Refresh', I still have my new added space types when I go back there.

**Comment by shorowit** [comment]
Hmm, looks like the Refresh button was removed at some point. So this issue can be closed.

OS 2.4.1
![image](https://user-images.githubusercontent.com/5861765/53903477-0f754780-4001-11e9-9b78-a49b068d24c6.png)

OS 2.7.1
![image](https://user-images.githubusercontent.com/5861765/53903523-2a47bc00-4001-11e9-8df0-df0eae3c1037.png)
