### ISSUE TITLE
Re-arranged column order doesn't stick next launch (Bugzilla #99)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#30]
On 2011-07-01 14:39:27, @DavidGoldwasser wrote:

> 0.3.0 didn't have this, but the default sort order changed
> 
> Bug imported from Excel; Status -confirmed; Created on - 4/18/11; By - Brent Griffith; Owned by -

On 2011-11-16 09:50:25, @DavidGoldwasser wrote:

> <batch change comment> Moving older bugs to "retest" milestone. Will re-test these and then assign to appropriate milestone. These were all 0.6.0 prior to change.

On 2011-11-17 10:41:24, @lgentile wrote:

> Still potential issue. This was an old bug. Please re-test/verify.

On 2012-01-17 13:57:32, @DavidGoldwasser wrote:

> Originally reported by Brent, still a valid bug.

**Comment by jmarrec** [comment]
No reorder of columns is possible nowadays.
