### ISSUE TITLE
Application name is Pat.exe instead of ParametricAnalysisTool.exe (Bugzilla #1167)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#300]
On 2013-03-12 12:52:10, @elainethale wrote:

> I also like OpenStudioParametricTool.exe, but it looks like the title bar now says "Parametric Analysis Tool". In any case, Pat.exe does not match everything else. We have similar problems with the folder name(s) under src/.

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
