### ISSUE TITLE
OS App mac will crash if you go 

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#3019]
If you open an OSM file that doesn't have corresponding directly (like what you get off of downloaded PAT project) OpenStudio will crash if you go the results tab, with a message similar to this. Not finding the directory that it expects.

I re-created this with the following steps.

1. Launch OpenStudio
2 .Add few objects to model (like empty space types)
3. Save the model
4. Quit OS app
5. Throw away the directly that goes with the model you made, keeping only the OSM file
6. Launch OpenStudio and load the OSM
7. Go to results tab (should crash)

![screen shot 2018-03-05 at 8 44 50 am](https://user-images.githubusercontent.com/4857055/36985697-312928e6-2055-11e8-94ed-accd01dfb933.png)

I tested this in 2.4.2, but then also confirmed it in 2.4.0, so it isn't a new bug. I don't think many people hit this, so I don't think it is critical to fix this for 2.5.0 unless it is a low risk fix.

**Comment by jmarrec** [comment]
Happens on Ubuntu with 2.6.0 official too. 

Hard to debug with Ubuntu since I always get a crash on the results tab anyways, so I'll have to wait to boot windows for this.

**Comment by macumber** [comment]
Confirmed that this does not crash, however the app does automatically create a companion dir when saving, maybe a complete fix should create a companion dir on opening a model?

**Comment by jmarrec** [comment]
@macumber  My two cents on this is that I don't want a companion dir until I actually save my model. Sometimes I create models to test something via the bindings, and use OS App just to ensure it's all working. I wouldn't want to have to go clean up companion directories all the time.

**Comment by macumber** [comment]
The idea was to create the companion dir in the temp dir, you wouldn't put it in user dir until save.  That might already be happening, i didnt check for sure, but assume it wasnt otherwise i dont think that crash would have happened
