### ISSUE TITLE
Create New Measure - name only makes it into XML and not measure.rb (Bugzilla #1176)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#302]
On 2013-03-14 09:00:01, @DavidGoldwasser wrote:

> I see you are setting the class in measure.rb based on what the user entered but not the name. Could be nice to do that.
> 
> Also Nick had a point that two people could make measures with same names and class, and upload them to BCL. Was concerned that this could create conflicts if someone had both of those measures in their project.
> 
> We could always add a GUID to the class, or ideally append it with the BCL user name of the person making the measure, or some other unique check? Just something to think about, but certainly not something we need to worry about too much for now.

**Comment by macumber** [comment]
@DavidGoldwasser can you confirm this is fixed?
