### ISSUE TITLE
Measure Manager restart loop when opening network osms

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#3022]
Double-clicking an osm file in a network location launches the OpenStudio app but causes Measure Manager to enter a crash loop.  Repeatedly clicking `OK` results in the same crash dialog.

Launching the OpenStudio app and using File->Open with the network location works fine.

###### Tested on Windows 10 with OpenStudio v2.4.0
![image](https://user-images.githubusercontent.com/411466/37047966-c260a8b4-2129-11e8-83c3-7cac0864919a.png)

**Comment by jmarrec** [comment]
Not an SDK issue.
