### ISSUE TITLE
2.4.2 & 2.4.3 OS App crashes when going to HVAC tab

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#3023]
1. Open the App  (empty model)
2. Click on the HVAC tab
3. Crash!

Tested on Windows 7 with OS 2.4.2 and 2.4.3.

**Comment by asparke2** [comment]
@kbenne not sure if this is you or @evanweaver

**Comment by DavidGoldwasser** [comment]
I saw this happen once on an empty model, but then could not repeat it. I have also been able to go to HVAC tab and navigate loops on a non-empty model.

**Comment by brianlball** [comment]
This is a real thing.  I reported it to Julien and Kyle the other day.  It has to do with the new availability manager stuff. @jmarrec @kbenne

**Comment by kbenne** [comment]
Yeah. @brianlball brought this to my attention and I am looking into it. I think it is connected to

**Comment by snlavu** [comment]
Has there been a fix to this? I just installed 2.4.3 and opened a version 2.2 file. I am unable to navigate to HVAC. See attached.
[TS-VRF-aircooled.zip](https://github.com/NREL/OpenStudio/files/1794728/TS-VRF-aircooled.zip)

**Comment by evanweaver** [comment]
@snlavu this issue was reported by a user of 2.4.3. A fix should be available with 2.4.4 in another week, or so.

**Comment by klamoureux** [comment]
@evanweaver , any word on the release of 2.4.4? I am running into this issue as well. Maybe there is a way to revert a model back to 2.4.0 in order to continue working. Any ideas or advice? SketchUp 2017 will not open OS 2.4.3 .osm file once 2.4.0 is installed.

**Comment by evanweaver** [comment]
@klamoureux, it's imminent. I anticipate tomorrow or Friday.

**Comment by asparke2** [comment]
@kbenne been building and testing develop today (3/23) and still having this crash happen, can't get into HVAC tab at all.

**Comment by jmarrec** [comment]
I just built develop and I can get to the HVAC tab on Ubuntu. But when I launch OS App, it cannot load the hvac_library.osm etc

![image](https://user-images.githubusercontent.com/5479063/37894539-d49dcaf6-30de-11e8-89e2-e40d20e93759.png)

**Comment by kbenne** [comment]
@jmarrec. Different issue. That is related to not finding E+.

**Comment by jmarrec** [comment]
ok, but anyway, I can get to the HVAC tab on ubuntu with a debug build

**Comment by jmarrec** [comment]
@asparke2 Has this happened since 2.5.0 and above, especially in 2.6.0? If not, we should probably close

**Comment by asparke2** [comment]
@jmarrec No, I haven't seen this with the recent releases.
