### ISSUE TITLE
OS APP crashes when deleting Unitary equipment from an airloop

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#3024]
Reporting on Unmethours.com. I was able to replicate this on 2.4.3 mac installer
https://unmethours.com/question/30159/os-crashing-when-packaged-unit-on-an-existing-air-loop-is-deleted/

**Comment by DavidGoldwasser** [comment]
@kbenne yes, I can reproduce this with 2.4.3 installer and a clean model

**Comment by klamoureux** [comment]
I have also encountered this issue. HVAC System tab works on 2.4.0 but even after restart and reinstall 2.4.3 crashes. Once a model is made with 2.4.3 extensions present it cannot be opened by 2.4.0. Wondering if there is a fix in the works or if I can transfer my model to 2.4.0.

![image](https://user-images.githubusercontent.com/35307462/37737816-fab7262a-2d22-11e8-928c-f7a2e2b239f0.png)

I also noticed a library failed to install on re instillation. It seems to be hvac library related.

![image](https://user-images.githubusercontent.com/35307462/37737898-2f498f54-2d23-11e8-95da-e576e35e76ee.png)

**Comment by jmarrec** [comment]
Reproduced crash with current develop on Ubuntu 16.04. Added a Packaged Rooftop Air Conditioner, dragged the first AirLoopHVACUnitarySystem from the library to the mixedAirNode, remove it, crashed.

**Comment by jmarrec** [comment]
Crash happens here on [GridItem.cpp#L1360](https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/openstudio_lib/GridItem.cpp#L1360)

```c++
std::vector<model::AirLoopHVACSupplyPlenum> supplyPlenums = subsetCastVector<model::AirLoopHVACSupplyPlenum>(m_loop.demandComponents());
```
