### ISSUE TITLE
Weather files are incorrect for models opened in openstudio from results tab (Bugzilla #1179)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#303]
On 2013-03-14 11:17:47, @macumber wrote:

> Should be able to open osm, save it, and run

On 2013-03-14 11:18:06, @macumber wrote:

> Need to consider case where project is from another computer as well

On 2013-03-14 12:56:05, @macumber wrote:

> Could fix this by converting weather file path to absolute when opening in os app using the noSavePath flag

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
