### ISSUE TITLE
Allow user to edit input fields for Ideal Loads Air System

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/OpenStudio#3033]
Ideal Air Loads is a powerful design tool to determine appropriate sensible and latent capacities to apply when simulating a system with defined energy model components. In the OS App, there is a check box to “Turn On Ideal Air Loads” for each Thermal Zone. After clicking this box, the respective ZoneHVAC:IdealLoadsAirSystem EnergyPlus object is created. However, all input fields for this object are left to the EnergyPlus defaults defined in the EnergyPlus IDD. This can be very limiting, such as when a user wants to apply Ideal Air Loads for humidification and dehumidification RH setpoints. Default dehumidification control is for a constant cooling SHR and default humidification control is “None”, so RH is not controlled to their specifications.

This could be fixed by exposing input fields in the “Edit” pane on the right after clicking on the grid cell surrounding the Ideal Air Loads check box.

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/31546339)

**Comment by jmarrec** [comment]
The hvac_library already includes a full blown ZoneHVACIdealLoadsAirSystem for when you need more control than the "use ideal air" checkbox
