### ISSUE TITLE
Expose Surface/SubSurface Properties When Rendering by Construction

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/OpenStudio#3036]
When rendering by construction if you click on a surface or a subsurface the OpenStudio Inspector will show the construction properties, which generally is not of much benefit because there aren’t that many constructions on a project that you could only navigate to it visually. However, rendering by construction is a great visual tool to ensure that constructions are assigned correctly and exposing the surface/subsurface properties when in this view would make reassignment of constructions much quicker. Toggling between rendering by surfaceType and construction is too slow of an approach.

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/10039872)

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/19
