### ISSUE TITLE
Tab 4 - styling (Bugzilla #1184)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#304]
On 2013-03-15 22:56:16, @DavidGoldwasser wrote:

> Created an attachment (id=289)
> screenshot showing results on tab 4
> 
> Looks much butter with today's build. I do have a few comments.
> - At times numbers in the right most column are cut off by the vertical scroll bar.
> - There isn't much space for the design alternative tab. Would love to see that wider or have text wrap.
> - There is very little space between the design alternative and measure tab. Would be nice to add some space between them. Might also be nice to left justify the first two titles "Design Alternative Names" and "Measures"
> 
> screenshot attached

Original attachments:
* 0315_tab4.png (ID 289)

**Comment by evanweaver** [comment]
@DavidGoldwasser your original attachment is not available, so I am unable to compare it to PAT's current state.  Please verify that you still have the above concerns.  If you still have a desire for some GUI changes, we need to have @marj-schott review and approve them, prior to me working on them.

**Comment by DavidGoldwasser** [comment]
outdated
