### ISSUE TITLE
Use FreeCAD (open-cascade) for creating and editing geometry

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/OpenStudio#3042]
Use FreeCAD (open-cascade) for the modeling (Sketchup is not free). 
Have a look at the work done on the Arch-Bench.. 
http://www.freecadweb.org/wiki/index.php?title=Arch_Module

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/17008930)

**Comment by jmarrec** [comment]
FloorspaceJS is free and addresses that
