### ISSUE TITLE
Add Fan:SystemModel to OpenStudio

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/OpenStudio#3044]
Per the EnergyPlus InputOutputReference…“As of version 8.7, a new simple “Fan:SystemModel” input object was added that can be substitued for Fan:ConstantVolume, Fan:OnOff, Fan:VariableVolume, and FanPerformance:NightVentilation. Users are encouraged to migrate their models to use this new Fan in the air loop or zone equipment because the original fan objects may be deprecated and eventually removed in the future.”

Please add Fan:SystemModel to OpenStudio as EnergyPlus is encouraging users to migrate towards using this object for air loop and zone equipment fans.

It also includes a new design power sizing method for ‘Electric Power Per Unit Flow Rate’ which is geared toward the [W/CFM] metric many practitioners are familiar with.

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/33056077)

**Comment by jmarrec** [comment]
There are talks of deprecating the others type in E+, so this should get on our radar soonish.

**Comment by kbenne** [comment]
ping @kbenne
