### ISSUE TITLE
Updated user documentation on OpenStudio site

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/OpenStudio#3045]
Website tab for documentation on openstudio.net is not up to date. Link to users guide or something that is updated frequently would be nice. Need to know if we can now create geometry, generate Title 24 and LEED documentation, to name a few items.

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/18983395)

**NOTE**: This seems to be related to issue #1415.

**Comment by jmarrec** [comment]
Documentation seems pretty up to date.

https://nrel.github.io/OpenStudio-user-documentation/tutorials/creating_your_model/ for eg.
