### ISSUE TITLE
Tab 1 - gui isn't sorting choice objects in the pull down list (Bugzilla #1186)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#305]
On 2013-03-17 20:49:31, @DavidGoldwasser wrote:

> Don't want everyone writing measures to have to code this in the measure. If we con't do this for the release I can writ it into the scripts.

On 2013-06-27 08:39:56, @DavidGoldwasser wrote:

> I'm pretty sure this has been fixed so users doesn't have to sort list in measure.

**Comment by asparke2** [comment]
This is a feature request.
