### ISSUE TITLE
Create installer for 32 bits Linux version

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/OpenStudio#3050]
Problem: Installation on 32 bits Linux computer not possible (no package available)

Solution: Publish a Linux package for 32 bits computers

Context: I need to install OpenStudio on an old computer running Linux. Buying a new computer is unfortunately not an option.. So it would be nice to also have a 32 bits package for the Linux version of OpenStudio.

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/13854336)

**Comment by jmarrec** [comment]
This is going to affect like probably 1 user total, perhaps 2, so not worth the time.

If you need to, compile it yourself, or reach out if you want an installer I could prepare one.
