### ISSUE TITLE
Account for "North Axis" building variable in IDF when exporting to gbXML

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/OpenStudio#3051]
The current gbXML export capability of the OpenStudio plugin for SketchUp neglects an important variable, namely the “North Axis” specification. As a result, walls that were intended to be oriented one direction are instead oriented another, dramatically changing the results of any simulation using the exported gbXML.

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/12272151)

**Comment by macumber** [comment]
I believe that all vertices are translated to site (i.e. global) coordinates on translation to gbXML, https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/gbxml/ForwardTranslator.cpp#L900

The gbXML might not have a populated north axis field, but all the vertices should be correct.
