### ISSUE TITLE
Add minValue() and maxValue() to OpenStudio::TimeSeries

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/OpenStudio#3053]
OpenStudio::TimeSeries already has integrate() and averageValue(). minValue() and maxValue() would also be helpful. Would be even more helpful if these four functions could be implemented over DateTime ranges in addition to over the whole series.

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/11662809)

**Comment by jmarrec** [comment]
`TimeSeries::values` returns a Vector. and there's `double openstudio::maximum(const Vector&)` and many more

https://github.com/NREL/OpenStudio/blob/158903e0f44685a9e17247ea302d3ce5ba7a90c5/src/utilities/data/Vector.hpp#L131-L154

```
t = TimeSeries.new
OpenStudio::maximum(t.values)
```
