### ISSUE TITLE
Allow running PAT on local area network

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/OpenStudio#3055]
Problem: it’s not possible right now to dispatch PAT runs to another machine on a local area network. It would be nice to.

Rationale: whether you just have another personal machine standing by or you have a beast of a workstation dedicated to intensive calculus, being able to use those would be great. While EC2 is great, it’s not free, and there’s a bunch of time lost downloading files that are potentially huge (the SQL notably) over the internet

Solution: Similar to EC2, add a capability to select a local machine with openstudio installed to dispatch the PAT runs

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9591144) suggestion from @jmarrec

**Comment by ljbrackney** [comment]
PAT can run with local servers that have been provisioned with OS Server per the instructions in the OS Server repo.  We use this functionality all the time.

**Comment by brianlball** [comment]
follow the instructions [here](https://github.com/NREL/OpenStudio-server/wiki/User-OpenStudio-Server-Deployment) to setup your local server using Docker
