### ISSUE TITLE
Change PAT format files to be human readable

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/OpenStudio#3056]
Problem: Right now the PAT are non-ascii, so you cannot interact with them.

Solution: make PAT files human readable (JSON, XML, something like this)

I see several reasons why a text format (JSON, XML, whatever) would be better:
- Would be able to store and reuse the settings of the measures and design alternatives when PAT crashes or something is removed
- Ability to have the settings in a readable format would allow for easier reporting (explaining what each design alternative is in particular)
- Would allow for scripting… creating a bunch of design alternatives varying one or several parameters in a range (example: vary R value from 10 to 40 step 5). (I think the Spreadsheet analysis does that, but I’ve never used it.)

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9783915)

**Comment by mapascual** [comment]
👍

**Comment by jmarrec** [comment]
Pat as of 2.0 is Json (the osw), this is done

**Comment by DavidGoldwasser** [comment]
I agree with @jmarrec that with 2x PAT this should be closed. For those wanting to use PAT projects on version control repos I will offer the following advise.

1. Clear all results on the run tab (using the column header "C" in circle)
2. Save PAT project
3. Quit PAT
4. Now you can make commit to repository.

The reason for these steps 1 and 2 is that that the `pat.json` file is not only an input file format, but also stores high level otupts. As a result a 100k `pat.json` can go up to 20MB or more after an analysis has been run but before results have been cleared. The reason for step 3 is to get rid of many temporary files that exist only while PAT application is open, that you don't want as part of a repository.

The overloading of the `PAT.json` is similar to what happens with an OSW file with the CLI, but in with the CLI a new OSW is made and the input OSW is left un-changed.
