### ISSUE TITLE
Preserve PAT design alternatives after adding or deleting a measure group

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/OpenStudio#3057]
Problem: Right now, if you add one measure group, it’ll delete all design alternatives. This is pretty annoying when you only wanted to add one, to have to recreate all your design alternatives (package of measures)

Solution: only delete design alternatives if you delete one measure group that was included in said design alternative.

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9625170)

**Comment by jmarrec** [comment]
Project is now tracked at https://github.com/NREL/OpenStudio-PAT/
