### ISSUE TITLE
PAT for Ubuntu

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/OpenStudio#3058]
If you want to take advantage of the multicore feature of the Radiance measure (Linux) AND use the PAT (Windows and Mac), that’s not possible now because there’s no common platform.

It is possible if you set up a Linux server but that can be a daunting task.

Not pushing for Radiance multicore capability on Windows because Linux has other (speed) advantages and for users like me who do thousands of runs, shaving speed everywhere you can is very desirable.

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/31390069)

**Comment by jmarrec** [comment]
Please see https://github.com/NREL/OpenStudio-PAT/issues/56
