### ISSUE TITLE
Tab 3 - ruby errors for measure not as described as in command line run (Bugzilla #1188)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#306]
On 2013-03-17 21:09:11, @DavidGoldwasser wrote:

> When I hit issue in thermostat script I get this message
> ./user_script.83:in 'run'"undefined method 'name' for # (NoMethodError) from ./user_script:77:in 'each from ./user_script:in 'run' from in.rb: 189
> 
> When I run same measure command line I get more meaningful error.
> ...NoMethodError: undefined method 'name' for #OpenStudio::Model::OptionalSchedule:0xb4e4f00
> 
> Also odd that it isn't referring to measure.rb, but looks like maybe each instance is user_script.rb? I suppose that is fine, but may want to add a brief section into measure writing guide to show what an error looks like, so people can better trouble shoot their or other's scripts.

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
