### ISSUE TITLE
Allow Baseline cloud runs in PAT

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/OpenStudio#3060]
This would be helpful for large models.

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9923574)

**Comment by ljbrackney** [comment]
Need more detail for this issue.  You can already use PAT to run single (baseline) models as long as you specify at least one variable in the project - this can be as simple as just checking one or more arguments in the OS Results measure as a "variable."
