### ISSUE TITLE
Install Switches for Remote Deployment

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/OpenStudio#3063]
I work in an office where I have to service a lot of employees.
We use a program called Prism Deploy, to remotely install most of our software.
A lot of the time, an .exe or .msi will have install switches.
I then make a .bat file to run the .exe with the appropriate silent install switches.
This makes deploying software easier for the company, and the end user.

If there was an option to download an .msi that would be great.

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/31933192)

**Comment by jmarrec** [comment]
This is already possible by supplying an install.qs script to the installer. Please read this thread: https://github.com/NREL/OpenStudio/issues/3832
