### ISSUE TITLE
Publish an upgrade timetable for the SketchUp versions

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/OpenStudio#3065]
Publishing an upgrade timetable for the SketchUp versions would enable us to plan a corporate (University student lab) installation of Sketchup. At present, looking ahead for maximum compatibility over the next semester with Student downloads, we install the latest version of SketchUp; however, the latest version of OpenStudio is incompatible with this version of the SketchUp program. If we knew the timetable for compatibility changes for SketchUp we could manage our installation plan for the image for 600+ computers – perhaps delaying the installation of the newer version of sketchup or waiting to finalise the image if the newer version of OpenStudio is close.

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/17226053)

**Comment by ljbrackney** [comment]
@macumber Is the plan to entirely deprecate SU support in lieu of floorplan.js?

**Comment by jmarrec** [comment]
https://www.openstudio.net/new-future-for-openstudio-application
