### ISSUE TITLE
Allow measure transfer between "Always run" and "Measure group" in PAT

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/OpenStudio#3068]
Problem: right now you can’t move a measure from the “Always Run” group to the “Measure Group” and vice versa. I might have loaded a model with all the measures I’ll eventually need, but I might want to create design alternatives by adding them one at a time to see the incremental savings. Currently I have to delete them and recreate them in the “Measure group” which is time consuming and annoying.

Solution: make it switchable.

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/13830981) feedback from @jmarrec

**Comment by jmarrec** [comment]
Moot since pat 2.x
