### ISSUE TITLE
SpaceType properties lost in merge from Floorspace

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#3071]
1. Open a new model
2. Import a SpaceType from one of the CA DEER libraries
3. Look at the SpaceType on the Space Types tab
  - It should have a default schedule set, standards building type, and standards space type assigned
4. Go into Floorspace and create a new geometry (doesn't need to have anything inside)
5. Merge the geometry
6. Go back to the Space Types tab
  - The default schedule set, standards building type, and standards space type are now missing

@macumber suspects that the issue is in [this code](https://github.com/NREL/OpenStudio/blob/3549a2c2955007d05e8aa55371fcf5ce1e6b2a27/openstudiocore/src/model/ModelMerger.cpp).  I suspect that for properties not editable in Floorspace, calling `resetFoo()` for those properties is incorrect.

**Comment by evanweaver** [comment]
@macumber and @asparke2, my internet is still making it nearly impossible to remote desktop to my tower. There is a PAT error on the Windows package, but I think thatit may be related to a bad download of the PAT GitHub source zip.
