### ISSUE TITLE
Setting ideal air loads zone as plenum will make a bad ReturnPlenum object

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#3083]
Tested in OS 2.4.0.

Zones with Ideal Air Loads enabled are available for selection as supply or return plenum in the GUI (HVAC Systems tab, select zone on demand side of air loop, 'Select Supply/Return Plenum', 'New Supply/Return Plenum'). 
If selected, it appears the plenum is created (and an OS:AirLoopHVAC:ReturnPlenum object is created), but the with a blank 'Thermal Zone' field. I didn't try to run the osm, but assume it will cause problems.

Suggest either: A) don't make ideal air loads zones available to be selected as a plenum, or B) deactivate ideal air loads when the zone is selected, and properly assign the zone to the plenum.

**Comment by jmarrec** [comment]
Reproduced in 2.9.0 official.

**Comment by jmarrec** [comment]
AirLoopHVAC::setTHermalZone disallows zone that have the setUseIdealAirLoads(true).

https://github.com/NREL/OpenStudio/blob/52c211fd8bd9384b6490ba09b80a9d1b5b25cbcb/openstudiocore/src/model/AirLoopHVACReturnPlenum.cpp#L109
