### ISSUE TITLE
Geometry Editor not working on Unbuntu

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#3098]
Ubuntu 16.04, OpenStudio 2.5.0 (official .deb)

No matter what I do (load an existing model, new model), it's always blank with a bar showing "Error" in red, see picture:

![image](https://user-images.githubusercontent.com/5479063/38682546-a3974d2a-3e6b-11e8-959e-bf41d814a68f.png)

![image](https://user-images.githubusercontent.com/5479063/38682649-f1eca11e-3e6b-11e8-81fb-9fe91066fa60.png)

**Comment by pachi** [comment]
I've tried this with version 2.6. and I can use the editor, but the preview window remains blank.
The console output shows this, which may be related:
```
[0626/124728:WARNING:resource_bundle.cc(291)] locale_file_path.empty() for locale 
Qt WebEngine ICU data not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install/resources. Trying parent directory...
Qt WebEngine ICU data not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install. Trying application directory...
Installed Qt WebEngine locales directory not found at location /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install/translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /usr/local/openstudio-2.6.0/bin/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
Qt WebEngine resources not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install/resources. Trying parent directory...
Qt WebEngine resources not found at /home/dmacumbe/OpenStudio/super-build/Qt-prefix/src/Qt-install. Trying application directory...
[0626/124728:WARNING:resource_bundle.cc(291)] locale_file_path.empty() for locale 
Critical: THREE.WebGLRenderer: Error creating WebGL context.
Critical: Uncaught TypeError: Cannot read property 'getShaderPrecisionFormat' of null
```
It looks like there's a problem finding the Qt WebEngine data files (translations?) but also a problem creating the WebGL context which should be used to render the image.

Could it be that the Qt WebEngine problem is what is causing the WebGL error?

With regards to the Qt WebEngine problem, it looks like some qt.conf file would need to set the right paths ( https://doc.qt.io/qt-5.11/qt-conf.html , https://doc.qt.io/qt-5.11/qlibraryinfo.html#details ), but I haven't been able to found its location for the generated OpenStudio package.

**Comment by jmarrec** [comment]
Tested with OpenStudioApplication 3.0.0-pre1 https://github.com/NREL/OpenStudio/releases/tag/v3.0.0-pre1. Still not working.

**Comment by jmarrec** [comment]
Fixed by https://github.com/NREL/OpenStudioApplication/pull/98
