### ISSUE TITLE
SSH Connection problems with large job sets (Bugzilla #193)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#31]
On 2011-08-24 15:53:47, @lefticus wrote:

> There are SSH connection problems when queuing a large set of Job at once. The connection appears to time out during the process, then fail when the jobs actually begin.

On 2011-10-09 21:52:29, @lefticus wrote:

> Raising priority to "Major" if any large projects (like 179d) are to be attempted again, stabilizing the SSH support will be important.

On 2011-11-16 09:50:33, @DavidGoldwasser wrote:

> <batch change comment> Moving older bugs to "retest" milestone. Will re-test these and then assign to appropriate milestone. These were all 0.6.0 prior to change.

On 2011-11-17 10:41:33, @lgentile wrote:

> Still potential issue. This was an old bug. Please re-test/verify.

On 2012-01-17 13:31:18, @DavidGoldwasser wrote:

> Check with Jason to see if this is still valid

Keywords: Invalid?

**Comment by DavidGoldwasser** [comment]
@macumber thought you might now if this is still valid?

**Comment by macumber** [comment]
I think this is RunManager SSH stuff, no longer supported.
