### ISSUE TITLE
Tab 3 - After running a job and adding new alternatives the warnings disappear from original run (Bugzilla #1200)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#310]
On 2013-03-20 11:46:57, @DavidGoldwasser wrote:

> I ran a project with 16 alternatives. I then added about 30 more. It is nice that the original jobs didn't have to re-run, but I noticed that all of the previously generated errors and warnings are gone. That is useful data to keep to compare runs. for example one of the new runs has a warning. I want to see if a similar earlier run had that same error, but I can't.
> 
> Now I may have quit and re-loaded between original and new runs? Can't remember.
> 
> Even after the analysis finished everything in tab 4 was blank. Clicking run another time did seem to restart everything and populate Tab 4 with data.
> 
> Not sure I'll be able to reproduce, but thought I would document it.

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
