### ISSUE TITLE
Removing AvailabilityManager with sensor from loop leaves invalid EnergyManagementSystem:Sensor

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#3102]
@jmarrec 
In 2.5: 
I added an AvailabilityManager:HighTemperatureTurnOff to a plant loop and selected the Control Status sensor from the Edit pane. Then removed the AVM from the drop zone, replacing with another. 

EnergyPlus run failed with:
```
   ** Severe  ** Invalid Output:Variable or Output:Meter Name =AVAILABILITY MANAGER HIGH TEMPERATURE TURN OFF CONTROL STATUS
   **   ~~~   ** Entered in EnergyManagementSystem:Sensor=ENERGY_MANAGEMENT_SYSTEM_SENSOR_1
   **   ~~~   ** Output:Variable Name not found
   **  Fatal  ** Errors found in processing Energy Management System input. Preceding condition causes termination.
```
And these objects left in the OSM:
```
OS:AvailabilityManager:HighTemperatureTurnOff,
  {00b2e33f-18ae-4faa-8944-8d043b17f23f}, !- Handle
  AVM HighTempTurnOff,                    !- Name
  {165e640e-b982-44c5-ad66-f938128d5cba}, !- Sensor Node Name
  10.0000000000001;                       !- Temperature {C}

OS:EnergyManagementSystem:Sensor,
  {a4b863f7-ece7-426e-a69f-823465f871ac}, !- Handle
  Energy_Management_System_Sensor_1,      !- Name
  {00b2e33f-18ae-4faa-8944-8d043b17f23f}, !- Output Variable or Output Meter Index Key Name
  Availability Manager High Temperature Turn Off Control Status; !- Output Variable or Output Meter Name
```

..which I think should be deleted when the AVM is removed.

**Comment by jmarrec** [comment]
I didn’t deal with EMS when I implemented this, perhaps the ems sensor is preventing deletion.
I’ll test quickly tomorrow.
@eringold Did you add that EMS sensor yourself or was it automatically created (the later would be a surprise to me...)?

**Comment by eringold** [comment]
I added the EMS sensor. I didn't realize that was a separate thing from the AVM inputs, so the issue might be more generally about EMS sensors.

**Comment by jmarrec** [comment]
The EMS sensor thing isn't guilty, I am. The only thing I do when you click the cross (removeItem) is remove it from the AvailabilityManagerAssignmentList, but I don't remove it from the model. It's an easy fix though.

**Comment by jmarrec** [comment]
@macumber @kbenne @brianlball I'd like your input on these two questions:
* Is the current behavior for AVM correct? (meaning keep it in model, just don't translate it if not used by any AVMList)
* If so, shouldn't we implement something in ModelObject.cpp that would delete any EMS object that's hard-associated (meaning KeyValue isn't `*` but the object's name or handle) with the ModelObject, similar to what's done for addtionalProperties and LifeCycleCosts [here](https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/model/ModelObject.cpp#L1032)?
