### ISSUE TITLE
Display issue on EMS Sensor tab when list too long

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#3107]
![image](https://user-images.githubusercontent.com/5479063/38988702-88d348fe-43d4-11e8-873a-6bb90e871d81.png)

I think this is because the list of possible output variables for this object (which means EMS Sensors...) is too long. The frame isn't scrollable so it's trying to fit everything and can't do it properly so it's squashes them.

Platform: Ubuntu 16.04
Custom Debug build of current develop (2.5.1)

**Comment by brianlball** [comment]
how does it look for a fan object?  That has significantly less sensor options.

**Comment by jmarrec** [comment]
It looks just fine, hence why I think it's just because this one has a list too long.
