### ISSUE TITLE
Test models from measures make it into every datapoint folder (Bugzilla #1207)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#311]
On 2013-03-22 10:23:29, @DavidGoldwasser wrote:

> I understand that the test model gets downloaded from BCL with the measure, but seems odd that the models are in every datapoint folder.
> 
> If there were a few hundred design alternatives each with a few measures could be an extra GB of files that are not used for anything.

**Comment by jmarrec** [comment]
Does this still happen today? If so it should be moved to the PAT repo
