### ISSUE TITLE
REMOVE AirloopHVACUnitary or add the 'Setpoint' capability!!!

### ISSUE THREAD

**Issue by snlavu** [NREL/OpenStudio#3110]
This component is very deceiving with its capability. Since it can be only controlled with Setpoint it throws results way off for the DOAS framework(in one case a 3rd of the whole building energy was being under estimated!!)

 It CANNOT maintain zone outdoor air requirements because it is ONLY seeing the control zone. PLEASE correct this or remove the component from Open Studio completely! Using version 2.4.1.

**Comment by jmarrec** [comment]
This is already fixed, here's the proof in OS 2.9.0:

![image](https://user-images.githubusercontent.com/5479063/69965095-cdd3e780-1513-11ea-80b7-0214230bdc19.png)

I tested the ruby bindings, including FT'ing, and it works all fine.

```
m = Model.new
unitary = AirLoopHVACUnitarySystem.new(m)
a = AirLoopHVAC.new(m)
unitary.addToNode(a.supplyOutletNode)
unitary.controlType
=> "Load"
unitary.setControlType("Setpoint")
=> true
unitary.controlType
=> "Setpoint"

ft = OpenStudio::EnergyPlus::ForwardTranslator.new
w = ft.translateModel(m)
puts w.getObjectsByType("AirLoopHVAC:UnitarySystem".to_IddObjectType)

=> AirLoopHVAC:UnitarySystem,
  Air Loop HVAC Unitary System 1,         !- Name
  Setpoint,                               !- Control Type
  ,                                       !- Controlling Zone or Thermostat Location
  None,                                   !- Dehumidification Control Type
  [...]
```
