### ISSUE TITLE
VRF Terminal group missing from My Model pane

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#3115]
If I create a `ZoneHVACTerminalUnitVariableRefrigerantFlow` and assign it to a thermal zone using the API, I would expect to see the object in the My Model pane like the ThermalZone so that I can assign it (and the ThermalZone) to the AirConditionerVariableRefrigerantFlow from the HVAC Systems > VRF > My Model pane. 

According to @kbenne, the code needs an addition here: https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/openstudio_lib/MainRightColumnController.cpp#L996

![image](https://user-images.githubusercontent.com/8397034/39384812-468f92ce-4a2b-11e8-936f-6d6afeaaad26.png)

![image](https://user-images.githubusercontent.com/8397034/39384817-4b133cd8-4a2b-11e8-90fb-fd718e1a56df.png)

**Comment by jmarrec** [comment]
@MatthewSteen I randomly saw that you have a branch labeled with this issue on your fork<sup>1</sup>.

Are you planning to relocate the statement and open a PR?

----

<sup>1</sup> The added line on your fork is not at the right posotio, should be around line [1007](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/openstudio_lib/MainRightColumnController.cpp#L1007) - This portion is not really well ordered... Do note that the order of the items gets reversed once in the OS App - and replace `libraryWidget` by `myModelList` obviously.

**Comment by MatthewSteen** [comment]
I was, but wasn't able to get my build...building so don't have a timeframe. Have at it if you like.
