### ISSUE TITLE
Expandable arrows backwards on simulation settings tab (Bugzilla #1212)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#312]
On 2013-03-26 10:07:37, @macumber wrote nothing.

**Comment by evanweaver** [comment]
@macumber When first coding this widget I had the arrows on the right, but I noticed some strange behavior and moved them to the left to alleviate it.  In a nutshell: if you make the app as small as possible, and then click various headers to open them, depending on the underlying inspector, the open / close arrows can disappear.  Perhaps @kbenne knows of a trick to make it lay out well in all circumstances.

**Comment by evanweaver** [comment]
@macumber Working in PAT, I realized that the arrows on similar looking (but dissimilar widgets) collapsible rows are on the left.  For continuity between apps, I would suggest not merging my changes and close this bug with "as designed" or some such  :)
