### ISSUE TITLE
DView time x axis is wrong

### ISSUE THREAD

**Issue by brianlball** [NREL/OpenStudio#3122]
I did a simulation starting April 1st and the results reported in DView start at Jan 1st.

![image](https://user-images.githubusercontent.com/2235296/39709444-122bab9a-51d7-11e8-98c6-fad3270b1a85.png)

ResultsViewer from the same simulation 

![image](https://user-images.githubusercontent.com/2235296/39709481-372d35f8-51d7-11e8-8c7f-a7f39f0922c0.png)

**Comment by eringold** [comment]
https://github.com/NREL/wex/issues/42

**Comment by jmarrec** [comment]
Will be addressed on NREL/wex#42
