### ISSUE TITLE
Issues with 90.1 2010 constructions in template OSM files that ship with OpenStudio

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#3123]
See this UH post for details
https://unmethours.com/question/31291/having-difficulty-with-accurately-assigning-the-construction-set-for-my-model-i-included-details-below-does-anyone-know-what-i-am-missing-or-doing/?answer=31322#post-id-31322

@asparke2 I was going to put this issue in standards repo, but since the lookup is working fine in Space Type and Construction Set wizard, it might just be that template OSM's need to be re-generated and added to OpenStudio installer, might not be any code changes in OpenStudio standards.

**Comment by jmarrec** [comment]
Checked in 2.7.1 with libraries `ASHRAE 90_1_2010.osm` and `ASHRAE 90_1_2013.osm` and dragging the same set (Office, CZ 4A, eg `90.1-2010 - Office - ASHRAE 169-2006-4A`).

The naming conventions for Exterior Wall constructions are confusing (`Typical Insulated Exterior Mass Wall`) but the constructions themselves are fine.

The 90.1-2010 has an insulation layer called `Typical insulation R-14.76` and the  2013 has `Typical insulation R-19.72`.

I don't see any need for action on OpenStudio's part at least.

**Comment by jmarrec** [comment]
Is the wanted behavior to rename constructions to bear the "90.1-XXX" suffix? If so, please open a PR on openstudio-standards instead.
