### ISSUE TITLE
intersecting tool - loses surface (Bugzilla #1215)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#314]
On 2013-03-29 07:49:01, @macumber wrote:

> Mottillo, Maria Maria.Mottillo@NRCan-RNCan.gc.ca
> 
> Good morning David and Dan,
> 
> As mentioned during the OpenStudio training on Tuesday, please find attached the files that show the error that occurs after I use the intersect tool on my entire model. Specifically, one of my ground surfaces disappears! I was able to correct the error by re-creating the surface (if my memory serves me correctly, I may have done this directly in the osm file).
> 
> I have also run into the problem in the past where diagonal lines appear, sometimes with surfaces disappearing as well - if I can track down the files displaying this error, I will send them to you.
> 
> Have a nice weekend,
> Maria
> 
> Maria Mottillo
> Housing, Building and Communities
> CanmetENERGY
> Natural Resources Canada
> 580 Booth St, 13th Floor
> Ottawa, Ontario K1A 0E4
> Tel: 613 996-6110
> www.canmetenergy.nrcan.gc.ca

On 2013-03-29 07:49:36, @macumber wrote:

> Created an attachment (id=297)
> Before intersect

On 2013-03-29 07:51:21, @macumber wrote:

> Created an attachment (id=298)
> After intersect

Original attachments:
- Bldg119-beforeIntersect.osm (ID 297)
- Bldg119-afterIntersect.osm (ID 298)

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/42
