### ISSUE TITLE
Ubuntu installation failure

### ISSUE THREAD

**Issue by jbkoh** [NREL/OpenStudio#3141]
In Ubuntu 16.04, when I try to run ``sudo apt install OpenStudio-2.5.0.xxxxxx-Linux.deb``, it says 
```
The following packages have unmet dependencies:
 openstudio : Depends: libwxgtk3.0-0 but it is not installable
E: Unable to correct problems, you have held broken packages.
```
In the main apt repository ``libwxgtk3.0-0`` is replaced by ``libwxgtk3.0-0v5``. How can I fix this problem?

I used 2.5.0 found at https://www.openstudio.net/downloads.

Thanks!

Update: It looks like this problem has been solved in the master branch but there is no instruction of how to build it from the repository. It'd be great to have a development instruction. Thanks!

**Comment by rishihahs** [comment]
I used the commands in [.gitlab-ci.yml](https://github.com/NREL/OpenStudio/blob/develop/.gitlab-ci.yml) starting with `cmake ...` under `build_deploy_develop:ubuntu:`.

**Comment by jmarrec** [comment]
This should be fixed by my PR on https://github.com/NREL/OpenStudio/pull/3133
So 2.6.0 installation should work without any workaround.

(FYI, check out https://github.com/NREL/OpenStudio/pull/3094 too)

**Comment by jmarrec** [comment]
Closing for now since it appears to be fixed and no new information was provided indicating otherwise.
