### ISSUE TITLE
Redhat 7.x Support

### ISSUE THREAD

**Issue by rh0dium** [NREL/OpenStudio#3144]
Hey all,

There is currently some lagging support for building this on Redhat based systems (Redhat/CentOS).  After some work I was able to get it build on CentOS 7.4.  I have some notes and they are below.  I will be submitting a pull request which simply updates the CMakeLists.txt file for support.

### Required Packages
```
sudo yum install openssl-devel libXt-devel ncurses-devel mesa-libGL-devel autoconf expat-devel libpng12-devel freetype-devel dbus-glib-devel glib2-devel fontconfig-devel libXi-devel libXrender-devel GeoIP-devel chrpath patch libdrm-devel bzip2 automake gcc-c++ libdb-devel libpng-devel libXcursor-devel redhat-lsb-core
```

### Legacy ICU (42) Support

QT Builds really want .42 support.  You may need to uninstall the .50 version

```
wget http://www6.atomicorp.com/channels/atomic/centos/5/x86_64/RPMS/libicu42-devel-4.2.1-2.el5.art.x86_64.rpm
wget http://www6.atomicorp.com/channels/atomic/centos/5/x86_64/RPMS/libicu42-4.2.1-2.el5.art.x86_64.rpm
sudo yum install libicu42-*.rpm

sudo ln -s /usr/lib64/libicui18n.so.42 /usr/lib64/libicui18n.so
sudo ln -s /usr/lib64/libicuuc.so.42.1 /usr/lib64/libicuuc.so
```

Then you can follow the standard build as outlined [here](https://github.com/NREL/OpenStudio/wiki/Configuring-OpenStudio-Build-Environments#linux).

**Note:  On the first build you will get #2796 - I outline how I've worked around it.**

**Comment by jmarrec** [comment]
I'm assuming the build has gotten significantly better now that we separated the OSApp (and Qt with it). Can reopen a new issue fi the need arises.
