### ISSUE TITLE
Resource library files not updated to latest version causing slow app load time

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#3146]
For windows (at least) versions 2.5.0 and 2.5.1, the OSApp takes on the order of minutes to load an empty model. Prior versions load the app in seconds. 

Per @macumber, this is likely a function of template library versions being out of sync with application version, thus requiring version translation. These resource osm's area all v2.4.0: https://github.com/NREL/OpenStudio/tree/develop/openstudiocore/src/openstudio_app/Resources

**Comment by jmarrec** [comment]
Food for thoughts: the same can be said for BCL components... When you drag for eg a construction from the BCL it has to do version translation too.
Take the first one you find on BCL, "189.1 - Ext Wall Mass" or something, its version is < 0.10, and I counted 32 individual steps to get it to 2.6.1.
Obviously, the BCL stuff is peculiar, there's only one version uploaded and you want it to work in as many OpenStudio versions there are potentially out there.)

But yeah the `openstudio_app/Resources/` could be updated to latest without hurting anything, though. I suspect it's more or less the case, at least for the `openstudio_app/Resources/default`

**Comment by macumber** [comment]
Reported by @DavidGoldwasser @ljbrackney Marley and Amy

**Comment by macumber** [comment]
UI should tell user what it is doing so they know why the app is so slow to load

**Comment by eringold** [comment]
related to https://github.com/NREL/OpenStudio/issues/3235

**Comment by jmarrec** [comment]
Save for making sure we do update stuff before we release a package, (and given that CMake checking isn't wanted), there isn't more to do here: I did implement the "UI should tell user what it is doing so they know why the app is so slow to load" in https://github.com/NREL/OpenStudio/pull/3307. I think we can close this one.
