### ISSUE TITLE
Add HeatExchanger:Desiccant:BalancedFlow

### ISSUE THREAD

**Issue by MingboPeng** [NREL/OpenStudio#3147]
Hi All,

I found HeatExchanger:Desiccant:BalancedFlow is available in [E+](https://bigladdersoftware.com/epx/docs/8-6/input-output-reference/group-heat-recovery.html#heatexchangerdesiccantbalancedflow),  is there any plan to add this to OS? 

Or is there a way to add E+ object that has not been included in OS to current osm model?

Thanks in advance,
Mingbo

**Comment by jmarrec** [comment]
You can use an EnergyPlus measure to inject IDF code after OSM has been translated to IDF and before it gets simulated. See the [Measure Writing Guide](https://nrel.github.io/OpenStudio-user-documentation/reference/measure_writing_guide/) for more info.

**Comment by joseph-robertson** [comment]
This one is a bit challenging. Would requiring wrapping:
* HeatExchanger:Desiccant:BalancedFlow (AirToAirComponent?)
* HeatExchanger:Desiccant:BalancedFlow:PerformanceDataType1 (ResourceObject?)

Ctor of the first object would need to pass in the second object.
