### ISSUE TITLE
Menu hang on geometry click

### ISSUE THREAD

**Issue by viric** [NREL/OpenStudio#3149]
If I click the Geometry tab in OpenStudio it shows the design I have, but then I cannot click any other tab.

Windows x64 Openstudio 2.5.0.

**Comment by jmarrec** [comment]
Could you try with 2.9.1 now? If still have the same problem, please share your model with us. We need something to reproduce this if we want a shot at fixing it. Until then, I'm closing the issue, we can reopen if we have more to go on.

Thanks for the report
