### ISSUE TITLE
Some windows are walled in Geometry view

### ISSUE THREAD

**Issue by viric** [NREL/OpenStudio#3150]
Some of the windows I drew in SkeychUp are not transparent, but like glass over a wall, when I show them in the OpenStudio Geometry view.  Not all of the windows, but some of them.

I don't know what is wrong about them to fix that. Do you have any suggestion?

**Comment by ToniOchoc** [comment]
I had a similar problem with windows on double height walls. Splitting the wall surface fixed it. More info in this post:
https://unmethours.com/question/40137/solid-windows-in-openstudio-geometry/
