### ISSUE TITLE
Can't Launch DView on mac

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#3155]
I don't think this happens to everyone on mac, but I have seen this with installers after 2.4.3.

<img width="419" alt="screen shot 2018-06-15 at 11 13 14 pm" src="https://user-images.githubusercontent.com/4857055/41495995-da9a9da0-70f1-11e8-9038-2f3929d4bfab.png">

Process:               DView [27190]
Path:                  /Applications/OpenStudio-2.5.2/DView.app/Contents/MacOS/DView
Identifier:            DView
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           DView [27190]
User ID:               1089522351

Date/Time:             2018-06-15 23:13:12.553 -0600
OS Version:            Mac OS X 10.12.6 (16G1314)
Report Version:        12
Anonymous UUID:        A997F565-FBD1-1FB7-C8ED-730FC6BF3E06

Sleep/Wake UUID:       74CC5FC5-A273-450A-853E-8CC1902A15A7

Time Awake Since Boot: 38000 seconds
Time Since Wake:       4800 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/wxmac/lib/libwx_baseu_net-3.0.dylib
  Referenced from: /Applications/OpenStudio-2.5.2/DView.app/Contents/MacOS/DView
  Reason: image not found

Binary Images:
       0x10e17f000 -        0x10e54cff7 +DView (0) <1970BB10-33C8-3C7B-A468-0FFFE65EBCE9> /Applications/OpenStudio-2.5.2/DView.app/Contents/MacOS/DView
       0x116a6f000 -        0x116aacdc7  dyld (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> /usr/lib/dyld
    0x7fff83e28000 -     0x7fff84034ff7  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <1F4026C6-23C1-39E8-823D-72298FECF75C> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff84594000 -     0x7fff84594fff  com.apple.Carbon (154 - 157) <69F403C7-F0CB-34E6-89B0-235CF4978C17> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff84a4c000 -     0x7fff84a4cfff  com.apple.Cocoa (6.11 - 22) <85EDFBE1-75F0-369E-8CA8-C6A639B98FA6> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff86fc1000 -     0x7fff87057ff7  com.apple.framework.IOKit (2.0.2 - 1324.60.4) <454036AD-86AA-3ABB-8C53-B5F654A6824D> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff8a027000 -     0x7fff8a035fff  com.apple.opengl (14.0.16 - 14.0.16) <B428BB89-8FE1-3527-BF3E-F8F0A1060884> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff9924b000 -     0x7fff9924cffb  libSystem.B.dylib (1238.60.2) <F3BF9DA9-7FF1-3B43-A33F-3481DF9C8A82> /usr/lib/libSystem.B.dylib

Model: MacBookPro11,5, BootROM MBP114.0182.B00, 4 processors, Intel Core i7, 2.8 GHz, 16 GB, SMC 2.30f2
Graphics: AMD Radeon R9 M370X, AMD Radeon R9 M370X, PCIe, 2048 MB
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x152), Broadcom BCM43xx 1.0 (7.21.171.133.1a2)
Bluetooth: Version 5.0.5f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512G, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

**Comment by ljbrackney** [comment]
It launches and runs for me in OS 2.5.1 with OS 10.11.6 on my Air, but the app is missing its icon in the installer.

**Comment by DavidGoldwasser** [comment]
This works for me with 2.6.0
