### ISSUE TITLE
OpenStudio::EpwFile.new(weather_file) returns 'my.epw' cannot be processed

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#3157]
This works fine in 2.5.0, but fails in 2.5.2 across all weather files.
https://github.com/NREL/BESTEST-GSR/blob/master/measures/bestest_building_thermal_envelope_and_fabric_load/measure.rb#L89

@macumber are you aware of any changes related to this after 2.5.0? I'm fine updating the measures if necessary, but wanted to make sure that this new failure isn't a bug in core code.

**Comment by macumber** [comment]
@joseph-robertson @jasondegraw FYI, probably some of the new weather file stuff?  @DavidGoldwasser is running the measure test with the CLI sufficient to reproduce the error?

**Comment by DavidGoldwasser** [comment]
Here is a link to measure test that reproduces this.
https://github.com/NREL/BESTEST-GSR/blob/master/measures/bestest_building_thermal_envelope_and_fabric_load/tests/bestest_building_thermal_envelope_and_fabric_load_test.rb

**Comment by jasondegraw** [comment]
@DavidGoldwasser Where there any other log/error messages? All of the paths to return false from the parsing function should have an associated log message, otherwise there's an unintended fall through someplace.

**Comment by DavidGoldwasser** [comment]
@jasondegraw here is the full error

>     <error type="test_good_argument_values_910" message="RuntimeError: /Users/alex/OpenStudio/openstudiocore/src/utilities/filetypes/EpwFile.cpp@2722 : EpwFile '/Users/dgoldwas/Documents/GitHub/NREL/BESTEST-GSR/measures/bestest_building_thermal_envelope_and_fabric_load/resources/DRYCOLDTMY.epw' cannot be processed...">

**Comment by DavidGoldwasser** [comment]
I'm not sure if this is related, but in addition to the three model articulation measures failing all tests, all three reporting measure tests, fail to produce a SQL file in the test setup, and seems to be related to weather files again. I just confirmed these tests ran in 2.5.0 but no 2.5.2

`[11:15:49.761126 ERROR] Found error in state 'os_measures' with message ["undefined local variable or method `weather_full_path' for #<RunOpenStudioMeasures:0x007fba04368268>::/ruby/2.2.0/gems/openstudio-workflow-1.3.3/lib/openstudio/workflow/jobs/run_os_measures.rb:42:in `perform'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.3/lib/openstudio/workflow/run.rb:269:in `step'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.3/lib/openstudio/workflow/run.rb:216:in `run'\n:/openstudio_cli.rb:841:in `execute'\n:/openstudio_cli.rb:632:in `execute'\n:/openstudio_cli.rb:1599:in `<main>'\neval:107:in `eval'\neval:107:in `require_embedded_absolute'\neval:92:in `block in require'\neval:86:in `each'\neval:86:in `require'\neval:2:in `<main>'"]}	
`

**Comment by jasondegraw** [comment]
@DavidGoldwasser Is there a way to see if any errors got logged before that? That's the `LOG_AND_THROW` that should occur after something has gone wrong.

**Comment by DavidGoldwasser** [comment]
I'll try to run it with the CLI this evening vs. the measure test. That is all I get back from the measure test

**Comment by joseph-robertson** [comment]
I guess this is a custom epw that I didn't test against?

**Comment by joseph-robertson** [comment]
We could delay reading of the design conditions row, but I believe @jasondegraw suggested we not do that. https://docs.google.com/document/d/1jz1I5K2aCswFUoCiUN10Rho3AnBy6J7762pEmwj1Ni0/edit#heading=h.ra0mwx4t1i97.

**Comment by jasondegraw** [comment]
@DavidGoldwasser No, don't change the files. It'll only fix the problem here, and not if someone else tries to use a similar file. It'd be nice if someone could figure out what the exact issue is, but @macumber's fix is probably the best approach for right now. It's in line with what we've done elsewhere for EPW issues.

**Comment by shorowit** [comment]
As far as I can tell, the EPW design conditions appear to have changed at some point because the current data in the files are different than what's described in the [E+ documentation](https://bigladdersoftware.com/epx/docs/8-9/auxiliary-programs/epw-csv-format-in-out.html#design-conditions-headerdata-csv). 

It's particularly confusing because the E+ documentation suggests 43 values in the design conditions row, the EPW above has ~60 values, and current EPWs have ~70 values.
