### ISSUE TITLE
Default library OSM locations are wrong in Ubuntu installer

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3158]

**Comment by macumber** [comment]
Default library location is correct if I start the app from the finder, but wrong if I start the app from the terminal in home directory

**Comment by jmarrec** [comment]
I can reproduce this on Ubuntu 16.04 with current develop (a5af93e) built in Debug Mode.

If I launch the App from the terminal from **anywhere** (including directly inside "Products" directory where OpenStudioApp resides), I get this repeatedly making the OS App unusable.

![image](https://user-images.githubusercontent.com/5479063/41708640-74b03b72-7541-11e8-986a-5657ae6bb3fd.png)

And also:

![image](https://user-images.githubusercontent.com/5479063/41708697-97efec4a-7541-11e8-94bc-d120c5caf84b.png)

If I go in "Files" (=finder) and navigate to the Products directory, and right-click on OpenStudioApp and select "Run" I don't get this problem.

**Comment by jmarrec** [comment]
Running from the terminal but as `sudo ./OpenStudioApp-2.5.2` does work though...

**Comment by jmarrec** [comment]
I no longer get this problem with current develop on Ubuntu 16.04, did you fix this @macumber?

**Comment by macumber** [comment]
I did not fix this as far as I can remember

**Comment by jmarrec** [comment]
I reproduced it with 2.8.0 installed.

```
(py37)julien@~$ OpenStudioApp-2.8.0 
[OpenStudio] <2> An unhandled exception has occurred: std::exception
(py37)julien@~$ /usr/local/bin/OpenStudioApp-2.8.0 
=> Works
```
