### ISSUE TITLE
User (Randy Maddox) reports that you cannot use user scripts when running radiance simulation (Bugzilla #1217)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#316]
On 2013-04-02 22:55:01, @macumber wrote nothing.

**Comment by macumber** [comment]
@DavidGoldwasser is this invalid?

**Comment by DavidGoldwasser** [comment]
@I'm not sure, but since by name is seems to pre-date measures, I think we can close it, and then re-open or make new issue if it comes up wit most current radiance workflow.
