### ISSUE TITLE
OSM made in 252 crashes when loaded

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#3162]
This was a clean 252 model. I added weather file, ddy, set climate zone, and went to geometry editor tab. I never merged it back, but app crashed while working in detail view of spaces. When I re-launched the model it crashes. @macumber I'll send you zip file on slack. The OSM file loads fine if I through away associated files, but not sure what is the problem. Just osw, epw, and openstudio_results measure.

**Comment by DavidGoldwasser** [comment]
I seem to be able to reproduce this pretty reliably with these steps
1. Launch OpenStudio
2. Choose EPW file (don't need to set design day or climate zone)
3. Go to geometry editor sub tab, make new floor plan (but don't draw any spaces)
4. Go back to main preview tab (not the preview button within the editor, do this without merging).
5. Save model, quite OpenStudio.
6. re-launch OpenStudio app and load file.

In some initial testing, just adding weather file doesn't cause this issue, just adding new floor plan without merging doesn't cause the issue, only both together.

**Comment by macumber** [comment]
@DavidGoldwasser I'm not able to reproduce this, any other Mac users seeing this?  @kbenne @ljbrackney @rpg777 @nllong ?

Can you make sure to post the long version in the issue report?  I might have just made a bad build (very possible)

**Comment by DavidGoldwasser** [comment]
@macumber I can't reproduce this in 2.6.0 using the steps above, or using the pre-made 2.5.2 OSM file. I'll close this.
