### ISSUE TITLE
E+ example file 1ZoneDataCenterCRAC_wPumpedDXCoolingCoil.idf fails to import

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#3165]
User report this in 2.1 and 2.5, I confirmed it in pre 2.6 release (although I don't get a crash, it doesn't import). 
https://unmethours.com/question/32137/openstudio-crashing-with-idf-import-versions-21-25/

I don't get the same detail as the user

> The collection is INVALID at strictness level 'Draft', because of the errors:
Object     level data error of type NoIdd             .
Error pertains to an object of type 'Catchall', named ''.
Additional information about the error type: input data definition is missing or empty.

**Comment by jmarrec** [comment]
I got this one.

**Comment by danjoh99** [comment]
Hey all, I'm still getting this error when trying to open CBECC-generated OSM files in the OS standalone app. The CBECC-generated OSM files are version 1.11.3, and they won't open in either OS 1.11.3 or 2.9.0. In both cases I get the error:
```
The collection is INVALID at strictness level 'Draft', because of the errors:
Object level data error of type NoIdd .
Error pertains to an object of type 'Catchall', named ''.
Additional information about the error type: input data definition is missing or empty.
```
I've tried deleting large sections of the OSM file in a text editor, piece by piece, trying to isolate the bad portion of the file. This exercise won't produce a file that will open. One conclusion could be there are bad portions throughout the file.

I've also done a COMPARE to a v.1.11.3 file that WILL open in OS. It's nearly 40,000 lines so it's hard to know for sure, but I don't see any obvious differences or syntax errors in the file that won't open.

I am able to open the CBECC-generated IDF in Openstudio.
I am able to open other CBECC-generated OSM files, from the same version of CBECC.

**Comment by jmarrec** [comment]
@danjoh99 If you share the offending OSM I suppose I could take a _quick_ look to try and give pointers. If you don't want to send it publicly, you can email it to me at julien at effibem dot com
