### ISSUE TITLE
Hitting delete key by mistake throws away your floor plan

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#3167]
I had selected something and hit the delete key just out of habit. I loose the floorpan I was working on without any warning. It would be nice to disable the delete key when in geometry editor or somehow warn the user and let them cancel out of this.

**Comment by tanushree04** [comment]
This issue seems to be on the floorspace.js side, move to https://github.com/NREL/floorspace.js/issues?
