### ISSUE TITLE
Copy and paste daylighting controls, glare sensors, illuminance maps does not work (Bugzilla #1218)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#317]
On 2013-04-05 15:25:51, @macumber wrote:

> Need to verify copy within same space works as well as copy and paste between spaces

**Comment by macumber** [comment]
Works for daylighting control but not glare sensor

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/41
