### ISSUE TITLE
Double-click doesn't open model in OpenStudio app

### ISSUE THREAD

**Issue by MikeWazz** [NREL/OpenStudio#3170]
I'm on a Windows 10 PC. When I double-click on an OSM file in File Explorer, the OpenStudio app opens, but the file/model doesn't open. I have to use the File > Open menu to locate my file and open it.

**Comment by shorowit** [comment]
Could be this? https://github.com/NREL/OpenStudio/issues/2832

**Comment by MikeWazz** [comment]
Yup, that's it. Thanks, Scott.
