### ISSUE TITLE
OpenStudio API documentation incorrectly identifies"UtilityCost_*" objects as wrapped  

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/OpenStudio#3172]
**Expected Behavior:** Documentation for OS API found [https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-2.5.1-doc/model/html/classes.html](url) suggests that these new instances of these Object classes can be created via the OpenStudio API:**

**1) UtilityCost_Charge_Block
2) UtilityCost_Charge_Simple
3) UtilityCost_Computation 
4) UtilityCost_Variable
5) UtilityCost_Tariff
6) UtilityCost_Qualify
7) UtilityCost_Variable**_ 

**Observered Behavior:** 
NOT POSSIBLE

**Platform Information**: 
Windows 10 64 Bit 

**OS version Information**
OS V2.6.0

**Suggested Actions from User**
Despite API documentation and many attempts in IRB to follow it, User was unable to successfully create a UtilityCost_Tariff object. Since all other UtilityCost_* objects are referenced to this object, after confirming failure, user stopped trying. Please confirm that UtilityCost_* objects are not available via the API and then remove them from the API documentation. It does not appear that these objects were ever supported (even thought documentation back top OS v1.x indicates, so they should not be marked as deprecated, but rather scrubbed from the publish documentation. 

_Note: User strongly suggests that if this scenario exists for ANY other OS objects (Not just missing, but false documentation in the API), they should also be removed_

**Comment by macumber** [comment]
I think these are dead files that we just need to remove.

**Comment by jmarrec** [comment]
Should we go ahead and remove the files?

**Comment by macumber** [comment]
Yes let’s remove
