### ISSUE TITLE
Daylighting results only applied to 1 zone out of 9 (Bugzilla #1219)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#318]
On 2013-04-08 10:34:08, @macumber wrote:

> This is a file from Randy Maddox who has tried to get radiance results for some time.  For some reason radiance results are only applied to one out of nine zones in his model, he renames his model with a new letter each time he rebuilds it so generation k means he has struggled with this a lot....

On 2013-04-08 10:34:50, @macumber wrote:

> Created an attachment (id=299)
> The problem file

On 2013-04-08 10:35:30, @macumber wrote:

> Created an attachment (id=300)
> Randy's write up

Original attachments:
* Building 00k3.osm (ID 299)
* Generation K.pdf (ID 300)

**Comment by macumber** [comment]
@rpg777 this is closed in pivotal, do you know if it is fixed?

 https://www.pivotaltracker.com/story/show/47649061

**Comment by rpg777** [comment]
It's fixed on my branch. Should probably leave this open because I'm not positive it's working on develop. =/ Sorry about that.
