### ISSUE TITLE
Update SDK Documentation references for OS API to "Latest Iteration" to point to OS v2.6.0

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/OpenStudio#3181]
**Expected Behavior**
SDK Documentation found at [https://openstudio-sdk-documentation.s3.amazonaws.com/index.html](url) should indicate a latest iteration of OS 2.6.0, per [https://github.com/NREL/OpenStudio/releases](url)

**Observed Behavior**
SDK Documentation found at [https://openstudio-sdk-documentation.s3.amazonaws.com/index.html](url) indicates the latest iteration of OS is v2.5.1

**Recommended Action**
Update OS SDK Documentation references to the latest public release.

**Comment by macumber** [comment]
@chrisbalbach 2.6.0 has not been officially released yet.  We are waiting on an issue related to PAT for Mac and also updates to measures on the BCL before officially releasing it
