### ISSUE TITLE
EnergyManagementSystem:InternalVariable internalDataIndexKeyName translation issue

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#3188]
@brianlball 
As with https://github.com/NREL/OpenStudio/issues/3182, internalDataIndexKeyName field in EnergyManagementSyste:InternalVariable does not replace uuid with object name on FT.

https://github.com/NREL/OpenStudio/blob/ef5169944777da7fd80d6332157a7eb164075291/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateEnergyManagementSystemInternalVariable.cpp#L69

**Comment by brianlball** [comment]
yup!  I added a fix for this to PR https://github.com/NREL/OpenStudio/pull/3187
