### ISSUE TITLE
Really long pull down lists in Space Attribute Tool can be problematic (Bugzilla #258)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#32]
On 2011-09-22 10:17:43, @DavidGoldwasser wrote:

> If you have a really long pulldown list for example with 70 thermal zones, and it goes off the screen, you can't scroll to the end of the list. This may just be a limitation of the basic SketchUp UI Dialog with pulldowns. For 0.6.0 This should be gone if we have Multi-select in Inspector.
> 
> Minor issue for now, don't think we have to fix for 0.5.0.

On 2011-09-28 08:41:43, @DavidGoldwasser wrote:

> First pass of bugs for 0.5.1. Some of Rob's mac bugs should be here as well

On 2011-11-16 09:50:34, @DavidGoldwasser wrote:

> <batch change comment> Moving older bugs to "retest" milestone. Will re-test these and then assign to appropriate milestone. These were all 0.6.0 prior to change.

On 2011-11-17 10:41:35, @lgentile wrote:

> Still potential issue. This was an old bug. Please re-test/verify.

On 2012-01-17 11:49:42, @DavidGoldwasser wrote:

> Still an issue, but I don't expect we will touch this for 0.7. Maybe put in QT dialog for 0.8

**Comment by DavidGoldwasser** [comment]
Addition of construction and space type wizard make this much less important.
