### ISSUE TITLE
Wrong OS:Daylighting:Control rotation angle translated

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#3216]
OpenStudio only translates the OS:Daylighting:Control input 'theta rotation around the Y-Axis' (the other rotations are ignored), and sets that value to the Daylighting:ReferencePoint input "Glare Calculation Azimuth Angle of View Direction Clockwise from Zone y-Axis". This happens here:
https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp#L457-L469

In OpenStudio, 'rotation around the Y-axis' (the zone north axis) is rotation in the vertical plane. This can be seen in Sketchup if you place a daylighting control object and change the theta value. The expected Daylighting:ReferencePoint EnergyPlus input, however, is "the angle, measured clockwise in **the horizontal plane**, between the zone y-axis and the occupant view direction." (ref: https://bigladdersoftware.com/epx/docs/8-9/input-output-reference/group-daylighting.html#field-glare-calculation-azimuth-angle-of-view-direction-clockwise-from-zone-y-axis).

In aircraft terms, for a body facing north, EnergyPlus is expecting the yaw angle, but OpenStudio is translating the roll angle. 

To reflect the expected input, OpenStudio should be translating the phiRotationAroundZAxis value.

**Comment by joseph-robertson** [comment]
Edit to the link above: https://github.com/NREL/OpenStudio/blob/develop/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp#L474-L478

**Comment by joseph-robertson** [comment]
Another potential issue:

https://github.com/NREL/OpenStudio/blob/develop/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp#L475

This is converted rad to deg. But isn't `primaryDaylightingControl->thetaRotationAroundYAxis()` already in degrees?

**Comment by jmarrec** [comment]
@eringold @joseph-robertson 

I am not certain the proposed fix is correct. These are Euler angles, not spherical coordinates.

Perhaps it should actually be `Psi Rotation Around X-Axis`  **- 90°**?

Here's a superb Pinta (opensource linux paint) drawing, in red is what I think OpenStudio does (Psi), and in Blue (Psi') is what I think EnergyPlus might be looking for:

![image](https://user-images.githubusercontent.com/5479063/73056475-72790280-3e8f-11ea-953a-b979865ba32d.png)

**Comment by eringold** [comment]
@jmarrec 
This is what Sketchup shows for a Theta rotation - the daylight object is rotated in the XZ plane, about the Y axis:

![OS_3216_1](https://user-images.githubusercontent.com/10799524/73139032-a3d80680-4026-11ea-9633-c6a87bb44f82.png)

My interpretation of the relevant EnergyPlus input is that it should receive what Sketchup shows as the Phi rotation - in the XY plane, about the Z axis:

![OS_3216_2](https://user-images.githubusercontent.com/10799524/73139053-edc0ec80-4026-11ea-871f-86c3f17fd874.png)

**Comment by dmacusb2** [comment]
@jmarrec is correct that these are Euler angles, the tricky part is that the rotations are applied successively about the `rotated` axes not the original axes.  EnergyPlus doesn't really handle rotation of the sensor in 3D, it only allows rotation in the 2D x-y plane.  The 3D rotations were there for radiance so we could have sensors on the ceiling, looking down.

**Comment by dmacusb2** [comment]
So what @eringold said is correct, EnergyPlus only cares about rotation about the z-axis.

**Comment by jmarrec** [comment]
Cool, thanks!

**Comment by joseph-robertson** [comment]
Where did we land on this?

@jmarrec

**Comment by jmarrec** [comment]
@joseph-robertson I don't know where @macumber 's comment went, but I have a trace in my email client, and he confirmed that your fix is good and so did @eringold. So I'm good with that. I approved the PR (which I cannot merge).
