### ISSUE TITLE
PAT v2.6.1 Measure Option Configuration Window not able to scroll vertically to show all user arguments

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/OpenStudio#3217]
**OS Version:** OS 2.6.1 (Win64)
**Native OS**: Window 7 Professional
**OS Application**: PAT 

**### Issue Description**
Issue occurs when applying and creating/configuring measure option(s) - PAT Manual mode - for "Create Residential Single Family Detached Geometry" measure. This measure contains (26) measure argument options, a combination of string, choice and double types, all of which are defaulted. 

**Expected Behavior**: Users should be able to vertically scroll to view/alter all (26) defaulted measure argument values. 

**Observed Behavior**: Users cannot vertically scroll to view/alter all (26) defaulted measure argument values. Only 13 of the 26 measure arguments are visible, as there are no visible handles on the right side of the frame for users grab and scroll the argument values. The final value visible in the user's frame is the roof Pitch Argument. 

See screen shot images below taken from PAT and from the OS Application 

![image](https://user-images.githubusercontent.com/5746765/44101175-d5b951e0-9fb4-11e8-97a7-ba34f36d823a.png)

![image](https://user-images.githubusercontent.com/5746765/44101289-16810100-9fb5-11e8-8087-d2d0b0e28382.png)

**Recommended Action**: Add vertical sliding handles to allow users to vertically 'pan' the frame.

**Comment by jmarrec** [comment]
@chrisbalbach : PAT is developed in another repository. Could you please move this issue here: https://github.com/NREL/OpenStudio-PAT/issues?

**Comment by jmarrec** [comment]
Moved to https://github.com/NREL/OpenStudio-PAT/issues/122
