### ISSUE TITLE
Multipliers not consistent (Bugzilla #1229)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#322]
On 2013-04-18 20:41:26, @macumber wrote:

> Space::numberOfPeople does not include people multiplier, etc
> 
> These types of methods need to be documented as using or not using multipliers

On 2013-04-18 22:52:51, @macumber wrote:

> Also guessing that construction.netArea() won't work for surfaces in spaces with multipliers

On 2013-04-19 06:32:00, @macumber wrote:

> Need to check that space multipliers are the same when setting adjacent surfaces or sub surfaces

**Comment by DavidGoldwasser** [comment]
@macumber see if still valid

**Comment by jmarrec** [comment]
Multipliers works as intended now. (Space multiplier isn't a thing, so ignoring the other two bullet points)

```
m = Model.new
s = Space.new(m)

pd = PeopleDefinition.new(m)
p = People.new(pd)
p.setSpace(s)

pd.setNumberofPeople(10)
p.setMultiplier(1)

s.numberOfPeople
=> 10

p.setMultiplier(10)
s.numberOfPeople
=> 100
```
