### ISSUE TITLE
When I split a matched surfaces, both  new surfaces are now matched to a single surface in another group (Bugzilla #1232)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#324]
On 2013-04-23 14:07:57, @DavidGoldwasser wrote:

> If there is a way to catch this should probably un-match the surfaces.

**Comment by jmarrec** [comment]
![image](https://user-images.githubusercontent.com/5479063/53488290-2dd1c500-3a8e-11e9-97b0-948177b0329e.png)

![image](https://user-images.githubusercontent.com/5479063/53488312-3de9a480-3a8e-11e9-98d5-d6c11de7e7da.png)

![image](https://user-images.githubusercontent.com/5479063/53488358-58238280-3a8e-11e9-86d3-0999ca01987a.png)

**Comment by macumber** [comment]
What happened in the last frame to delete a surface?

**Comment by jmarrec** [comment]
That's probably the "it has been automatically fixed"...

**Comment by macumber** [comment]
Oh that deletes it?  That is not good.....

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/40
