### ISSUE TITLE
ZoneHVACEquipmentList object's Load Distribution Scheme not wrapped

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio#3257]
ZoneHVAC:EquipmentList,
       \extensible:4 Duplicate the four fields Zone Equipment Object Type through Heating Priority
       \memo List equipment in simulation order.  Note that an ZoneHVAC:AirDistributionUnit or
       \memo AirTerminal:SingleDuct:Uncontrolled object must be listed in this statement if there is a forced
       \memo air system serving the zone from the air loop.
       \memo Equipment is simulated in the order specified by Zone Equipment Cooling Sequence and
       \memo Zone Equipment Heating or No-Load Sequence, depending on the thermostat request.
       \memo For equipment of similar type, assign sequence 1 to the first system intended to
       \memo serve that type of load.  For situations where one or more equipment types has limited capacity or
       \memo limited control, order the sequence so that the most controllable piece of equipment runs last.
       \memo For example, with a dedicated outdoor air system (DOAS), the air terminal for the DOAS
       \memo should be assigned Heating Sequence = 1 and Cooling Sequence = 1.  Any other equipment should
       \memo be assigned sequence 2 or higher so that it will see the net load after the DOAS air is added
       \memo to the zone.
       \min-fields 6
  A1 , \field Name
       \required-field
       \reference ZoneEquipmentLists
  A2 , \field Load Distribution Scheme
       \type choice
       \key SequentialLoad
       \key UniformLoad
       \key UniformPLR
       \key SequentialUniformPLR
       \default SequentialLoad
  A3 , \field Zone Equipment 1 Object Type
       \begin-extensible
       \type choice
       \key ZoneHVAC:TerminalUnit:VariableRefrigerantFlow
       \key ZoneHVAC:AirDistributionUnit
       \key AirTerminal:SingleDuct:Uncontrolled
       \key ZoneHVAC:EnergyRecoveryVentilator
       \key ZoneHVAC:EvaporativeCoolerUnit
       \key ZoneHVAC:HybridUnitaryHVAC
       \key ZoneHVAC:ForcedAir:UserDefined
       \key ZoneHVAC:FourPipeFanCoil
       \key ZoneHVAC:OutdoorAirUnit
       \key ZoneHVAC:PackagedTerminalAirConditioner
       \key ZoneHVAC:PackagedTerminalHeatPump
       \key ZoneHVAC:UnitHeater
       \key ZoneHVAC:UnitVentilator
       \key ZoneHVAC:VentilatedSlab
       \key ZoneHVAC:WaterToAirHeatPump
       \key ZoneHVAC:WindowAirConditioner
       \key ZoneHVAC:Baseboard:RadiantConvective:Electric
       \key ZoneHVAC:Baseboard:RadiantConvective:Water
       \key ZoneHVAC:Baseboard:RadiantConvective:Steam
       \key ZoneHVAC:CoolingPanel:RadiantConvective:Water
       \key ZoneHVAC:Baseboard:Convective:Electric
       \key ZoneHVAC:Baseboard:Convective:Water
       \key ZoneHVAC:HighTemperatureRadiant
       \key ZoneHVAC:LowTemperatureRadiant:VariableFlow
       \key ZoneHVAC:LowTemperatureRadiant:ConstantFlow
       \key ZoneHVAC:LowTemperatureRadiant:Electric
       \key ZoneHVAC:Dehumidifier:DX
       \key ZoneHVAC:IdealLoadsAirSystem
       \key ZoneHVAC:RefrigerationChillerSet
       \key Fan:ZoneExhaust
       \key WaterHeater:HeatPump:PumpedCondenser
       \key WaterHeater:HeatPump:WrappedCondenser
       \key HeatExchanger:AirToAir:FlatPlate
       \key AirLoopHVAC:UnitarySystem
       \required-field
  A4 , \field Zone Equipment 1 Name
       \required-field
       \type object-list
       \object-list ZoneEquipmentNames
  N1 , \field Zone Equipment 1 Cooling Sequence
       \required-field
       \type integer
       \minimum 1
       \note Specifies the zone equipment simulation order
       \note when the zone thermostat requests cooling
  N2 ; \field Zone Equipment 1 Heating or No-Load Sequence
       \required-field
       \type integer
       \minimum 1
       \note Specifies the zone equipment simulation order
       \note when the zone thermostat requests heating or no load

**Comment by jmarrec** [comment]
@joseph-robertson sorry for middling (got here from https://github.com/NREL/OpenStudio-resources/pull/53), but I'm pretty sure you need to write a VersionTranslation routine since you *inserted* an IDD field. See https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/osversion/VersionTranslator.cpp#L4005
You'll need to wrap it in a `VersionTranslator::update_2_6_1_to_2_6_2`
