### ISSUE TITLE
OpenStudio.Path() constructor is looking for a Path and not a String

### ISSUE THREAD

**Issue by mostaphaRoudsari** [NREL/OpenStudio#3261]
I tested some code against OpenStudio 2.6.1 on Windows using C# bindings and when I try to create a `Path` from a file path as a string it gives me a TypeError. Has it changed recently and how to create a `Path` from string with the new API. The code works fine in OpenStudio 2.4.

**Comment by macumber** [comment]
It did change in an attempt to better handle non-ascii characters in path, you should use the toPath method in OpenStudio core to convert strings to paths.

**Comment by mostaphaRoudsari** [comment]
@macumber thank you for the quick reply. Are you sure it is already part of C# distribution? Can't see it here.

![image](https://user-images.githubusercontent.com/2915573/45269134-ed9f6b80-b488-11e8-8bfe-56b22a802014.png)

**Comment by macumber** [comment]
Its a free method and not a class, all those look like classes?

**Comment by macumber** [comment]
Can you try: `OpenStudio.OpenStudioUtilitiesCore.toPath(osmPathName);`

**Comment by mostaphaRoudsari** [comment]
Thanks. This one worked. Unfortunately the SDK is not searchable and in cases like this are hard to find the correct namespace. Thank you for your help.
