### ISSUE TITLE
2.6.1 FloorSpace issues

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#3266]
1. You can't create doors. Go to the Components tab, switch the dropdown to Door, and click the + icon. Nothing happens. Windows and Daylighting Controls correctly create the new object. And it works fine in the standalone FloorSpaceJS.
2. You can't assign windows or daylighting controls. For example, create a window and then click on an edge. Nothing happens. It works fine in the standalone FloorSpaceJS.

**Comment by tanushree04** [comment]
Issue in Floorspace.js and not the SDK
