### ISSUE TITLE
2.6.1 FloorSpace windows/doors preview on wrong story

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#3267]
Open the attached floorplan. There are 2 windows and 2 doors attached to the space on the 2nd story. When you preview, the windows/doors appear on the 1st story instead of the 2nd story. Haven't looked at whether the OS model is similarly affected.

**Comment by shorowit** [comment]
Now with attachment...
[floorplan.json.txt](https://github.com/NREL/OpenStudio/files/2376368/floorplan.json.txt)

**Comment by macumber** [comment]
Issue is probably in the [FloorplanJS::toThreeScene](https://github.com/NREL/OpenStudio/blob/e077c7edfa6c94bb37aeb0e31f40b69ed2740223/openstudiocore/src/utilities/geometry/FloorplanJS.hpp#L149) method
