### ISSUE TITLE
RefrigerationWalkIn::zoneBoundaries causes segfault

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3272]
This is a regression in refrigeration_system.rb

**Comment by macumber** [comment]
This line is a little screwy https://github.com/NREL/OpenStudio/blob/8c81faf8bc80b0e8f96a4b2764e5958cd060a625/openstudiocore/src/model/RefrigerationWalkIn.cpp#L238

**Comment by jmarrec** [comment]
@macumber I can't seem to reproduce any problem there, though I don't see any changes to that file aside from Copyright updates. 

Here's the history of test results:

![image](https://user-images.githubusercontent.com/5479063/54128667-d8da6b00-440c-11e9-80e0-64cff87ec26d.png)

And the `refrigeration_system.rb` does access this method: https://github.com/jmarrec/OpenStudio-resources/blob/develop/model/simulationtests/refrigeration_system.rb#L31:L32

Unless you can reproduce a crash/error, let's close this.

**Comment by jmarrec** [comment]
@macumber ?
