### ISSUE TITLE
Missing construction layers for an OS: Construction object when importing from gbxml 

### ISSUE THREAD

**Issue by saeranv** [NREL/OpenStudio#3296]
I am working on a project where I define OSM surfaces, constructions and materials in Revit using the OpenStudio SDK and then convert this into a gbxml so I can work with the model using Honeybee in Grasshopper.   

Here they are listed in the gbxml Construction id:

![image](https://user-images.githubusercontent.com/1685956/46548804-1bb47780-c89e-11e8-8a9c-cabcee2fc2a8.png)

However, when importing the gbxml into the OpenStudio app, all my OS: Construction objects are missing material layers that are specified in the gbxml. 

![image](https://user-images.githubusercontent.com/1685956/46549083-e65c5980-c89e-11e8-8897-1f7b0b4e4f7a.png)

Furthermore, the missing materials are showing up in the Material tab. So it seems like the materials are being imported, they just aren't specified in the construction layers like they are in the gbxml:

![image](https://user-images.githubusercontent.com/1685956/46548888-4c94ac80-c89e-11e8-8bc9-06742a2f241a.png)

For reference here's the way one of my missing materials (in OS: Construction) is defined in gbxml:

![image](https://user-images.githubusercontent.com/1685956/46548976-91204800-c89e-11e8-95b9-b33effdbd837.png)

... and here's one that is not missing:

![image](https://user-images.githubusercontent.com/1685956/46549006-a8f7cc00-c89e-11e8-8e6e-6c9117ed536f.png)

Here's a simple gbxml that should reproduce the error. I had to change the file extension to .txt to get past github:
[simple_u_val_example.txt](https://github.com/mostaphaRoudsari/honeybee/files/2451254/simple_u_val_example.txt)

I'm using OpenStudio 2.5.0 on Windows 10. 

Let me know if further information is required.

**Comment by DavidGoldwasser** [comment]
Just for reference, I wanted to share structure of multi-layer gbXML constructions that I have recently tested. I'm not sure if I have seen any before that defines the layers within the `Construction` object instead of in the `Layer` object. Example shown below does import into OpenStudio with multiple construction layers.

Construction
```  <Construction id="aim0041">
    <U-value unit="WPerSquareMeterK">3.7021</U-value>
    <LayerId layerIdRef="aim0043" />
    <Name>Metal</Name>
    <Description>Metal door</Description>
  </Construction>
```

Layer
```
  <Layer id="aim0043">
    <MaterialId materialIdRef="aim0044" />
    <MaterialId materialIdRef="aim0050" />
    <MaterialId materialIdRef="aim0044" />
  </Layer>
```

Materials
```
  <Material id="aim0044">
    <Name>Metal surface</Name>
    <Description>Metal surface</Description>
    <Thickness unit="Meters">0.0008</Thickness>
    <Conductivity unit="WPerMeterK">45.2800000000001</Conductivity>
    <Density unit="KgPerCubicM">7824</Density>
    <SpecificHeat unit="JPerKgK">500</SpecificHeat>
  </Material>
  <Material id="aim0050">
    <Name>1 1/2 in wood</Name>
    <Description>1 1/2 in (40 mm) wood</Description>
    <Thickness unit="Meters">0.0376</Thickness>
    <Conductivity unit="WPerMeterK">0.15</Conductivity>
    <Density unit="KgPerCubicM">608</Density>
    <SpecificHeat unit="JPerKgK">1630</SpecificHeat>
  </Material>
```

**Comment by saeranv** [comment]
@DavidGoldwasser  

Does this have anything to do with the way I'm creating my OS:Construction objects? 

I'm doing the following (in C#):
```
// simplified exampel
osmConstruction = new Construction(osm);
osmConstruction.setName(name);
osmConstruction.setComment(description);

MaterialVector osmMaterialVector = new MaterialVector(materialLayers.Count);

MasslessOpaqueMaterial material = setMasslessOpaqueMaterial(matJSON, osm);
osmMaterialVector.Add(material);

 StandardOpaqueMaterial material = setStandardOpaqueMaterial(matJSON, osm);
 osmMaterialVector.Add(material);

//etc etc...

osmConstruction.setLayers(osmMaterialVector);

```

Although, this is creating a correct OS:Construction object in the osm file:

![image](https://user-images.githubusercontent.com/1685956/46558090-ffbecf00-c8b9-11e8-8b5a-e846030158b8.png)

**Comment by saeranv** [comment]
@DavidGoldwasser 
cc @ryanxwelch

Here's more data to help figure out at what point in my workflow I'm doing something different with my construction assembly that is creating a slightly different gbxml.

Here's how my construction assembly is defined in OpenStudio:

```
! 1IN Stucco
! 8IN CONCRETE HW RefBldg
! Typical Insulation
! 1/2IN Gypsum
OS:Construction,
  {e04bebb2-6e1c-4838-a5c5-2faf70b78650}, !- Handle
  Typical Insulated Exterior Mass Wall,   !- Name
  {2d3867af-d7b9-4bcc-be60-d1e2829a3718}, !- Surface Rendering Name
  {4c442cce-7e86-4d3d-a164-9f1bbee87d07}, !- Layer 1
  {ccee626d-6c26-41fa-bab7-c66a042584f5}, !- Layer 2
  {ab621fb7-9b3d-4b29-83d5-9ff5c6117258}, !- Layer 3
  {1d191853-00da-4762-b57d-c75df708f915}; !- Layer 4
```
Is this how the .osm file, that is being used to generate your working gbxml is defined?

Feel free to share your working gbxml and osm file if that is easier. 

Thanks, 

S

**Comment by macumber** [comment]
FYI https://github.com/NREL/OpenStudio/tree/Issue3296

**Comment by saeranv** [comment]
For what it's worth, here's another failed attempt I just tried at an alternative workflow.

I decided to go to my Honeybee roots and check to see, and mimic how Mostapha/Chris defines their OS:Constructions:

```
def getOSConstruction(self, HBConstructionlName, model):
        # call the layers form HB library
        materialNames, comments, UVSI, UVIP = self.hb_EPMaterialAUX.decomposeEPCnstr(HBConstructionlName)
        
        # create an empty vector to collect the materials
        materials = ops.MaterialVector()
        
        for materialName in materialNames:
            # check if the material has been already produced
            if not self.isMaterialInLib(materialName):
                # create an openstudio material for EP material
                OSMaterial = self.getOSMaterial(materialName, model)
                # keep track of materials
                self.addMaterialToLib(materialName, OSMaterial)
            else:
                # material has been already created so let's just use it
                OSMaterial = self.getMaterialFromLib(materialName)
            
            # add it as a layer
            materials.Add(OSMaterial)
    
        construction = ops.Construction(model)
        construction.setName(HBConstructionlName)
        construction.setLayers(materials)
    
        return construction
```

By comparing the two I observed that there is one mistake that I believe I made, I initiated a MaterialVector with a predefined length, then subsequently added OS:Materials to that MaterialVector (versus initating an empty vector and adding items to it afterwards).

However, after making the changes, exporting a osm -> .gbxml , and then importing the gbxml back in, I am still having the same problem, so that doesn't seem to have changed things.

**Comment by macumber** [comment]
@saeranv I think I fixed this here, https://github.com/NREL/OpenStudio/commit/741b211c7c7586ec62c7971c3ebd82da8b292811

It's too late to make this into 2.7.0, are you able to create your own builds?  Do you have a timeframe for needing this?

**Comment by saeranv** [comment]
Awesome thanks @macumber !

I don't know how to make my own builds, but I'll check with my colleagues to see if they can. The timeframe should be flexible, and if we have to wait I think that's fine. I decided to deal with this problem by defining my construction assemblies from scratch in Honeybee for this design iteration. When do you think the next OS version is coming out?

**Comment by saeranv** [comment]
@macumber so the feedback is that making our own builds would be too steep a building curve for us. So we will wait for the next release.

**Comment by saeranv** [comment]
FYI, I've tested the latest build on my end and my constructions are being extracted correctly (see import from gbxml OSM below). Thanks!

![image](https://user-images.githubusercontent.com/1685956/47532467-7417dd00-d87e-11e8-9d15-a14f8fc25d04.png)
