### ISSUE TITLE
ScheduleFile's generated using Apply Measure Now are lost

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3297]

**Comment by tsbyq** [comment]
The schedule file generated by a measure is saved in different locations depending on where the measure is applied.
(1). When the measure is applied in the "Apply Measure Now" interface, the schedule file is saved in a path like "../Temp/OpenStudioApp.ek8004/resources/"
(2). When the measure is applied in the Run tab of OS app, the schedule file is saved in a path like "../Temp/OpenStudioApp.ek5336/resources/measures/measure_name 1/resources/"

**Comment by macumber** [comment]
I think this issue is fixed by https://github.com/NREL/OpenStudio/commit/e8fd0b1b3df91d61baa4c94d4b8b41e3d4e164cd but will need to test to confirm.  @tsbyq are you able to make an OpenStudio build to test?
