### ISSUE TITLE
Render by Data broken (Bugzilla #259)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#33]
On 2011-09-22 14:11:06, @DavidGoldwasser wrote:

> You can load the sql but changing date/time doesn't change color or data values. Maybe this is related to the developer logging I have going on now. Need to test this is really broken?

On 2011-09-22 14:31:48, @DavidGoldwasser wrote:

> Also zone based sql data doesn't seem to back back at all. Is that an issue with mapping back from zones to spaces?
> 
> If we can't fix this we should disable render by data?
> 
> Render by Data isn't acting like timeseries data for me

On 2011-09-24 22:55:38, @DavidGoldwasser wrote:

> Dan, so data now loads for zone based, variables, but the update still isn't happening when you change the time of day or year. You have to click the "render by data" button again and then it updates. This is for surface or zone variables.
> 
> Import bug fix seems good.

On 2011-09-26 11:34:40, @DavidGoldwasser wrote:

> tested

On 2011-10-03 15:45:32, @DavidGoldwasser wrote:

> Dan, using this today it seemed broken again. The whole ResultsViewer dialog was slow, and update only happened when re-clicked render mode. (vs. changing time of day and time of year.
> 
> Just went back to 6706 and it works there, but is broken at 6727. I can do a little more testing tomorrow.

On 2011-10-05 16:08:53, @DavidGoldwasser wrote:

> I'll close this it works now, but we will have to work on performance. On a 15zone model looking at solar incident it takes about 6 seconds for rendering colors to change. Interestingly that is about the same amount of time it takes for the Rendering Settings dialog to load when I re-open it. This was much quicker in 0.4.0 and earlier.

On 2011-11-07 07:54:12, @macumber wrote:

> User is reporting that this is back:
> 
> https://openstudio.nrel.gov/forums/openstudio-plug-google-sketchup/bug-reports-and-feature-requests/render-data-value

On 2011-11-16 09:50:34, @DavidGoldwasser wrote:

> <batch change comment> Moving older bugs to "retest" milestone. Will re-test these and then assign to appropriate milestone. These were all 0.6.0 prior to change.

On 2011-11-17 10:35:28, @lgentile wrote:

> Still potential issue. This was an old bug. Please re-test/verify.

On 2011-11-17 10:41:35, @lgentile wrote:

> Still potential issue. This was an old bug. Please re-test/verify.

On 2012-01-26 09:40:59, @DavidGoldwasser wrote:

> So the comments before this describe the behavior for 0.6.0. But in 0.6.1 something changed. Dan, did you make a fix related to this.
> 
> In 0.6.1 when you go to render by data you briefly see color on the surfaces before they are replaced by white. When you drag the info tool over the data is there, but just not colored. As this is a SketchUp bug I don't expect us to address this in 0.7 so I'll move the milestone back.

**Comment by DavidGoldwasser** [comment]
feature deprecated.
