### ISSUE TITLE
gbXML imports openings with an openingType of "air" are assigned an AirWall construction by default crashing EnergyPlus

### ISSUE THREAD

**Issue by pflaumingo** [NREL/OpenStudio#3302]
This code [here](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/gbxml/ReverseTranslator.cpp#L912) is adding an AirWall construction to openings with an openingType of "air". This causes EnergyPlus to crash with the following output: "FenestrationSurface:Detailed="AIM75960 REVERSED" has an opaque surface construction; it should have a window construction"

**Comment by macumber** [comment]
Is this for interior or exterior openings?  Modeling of large openings is difficult and not something we handle right now.  What short term fix do you want?  We can backport something to 2.6.0-gbxml branch

**Comment by macumber** [comment]
Also, can you post an example file or give me a link privately?

**Comment by pflaumingo** [comment]
The model I have can't be shared - I'll send privately. I think a short term fix of just not applying a default construction would work fine while we figure out the more appropriate modeling path.

**Comment by pflaumingo** [comment]
@rpg777 any radiance concerns or requirements to be aware of here?

**Comment by jmarrec** [comment]
Fixed via https://github.com/NREL/OpenStudio/commit/bf17b66549ddc5c7a5badb7f0a84d12b93b44e81 it will now use `Construction:AirBoundary`
