### ISSUE TITLE
I opened a project Andrew made in 0.11.3 in current trunk, crashes when I try to select a measure instance in tab one (Bugzilla #1242)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#331]
On 2013-05-08 15:25:07, @DavidGoldwasser wrote:

> Created an attachment (id=320)
> zip file of project attached

Original attachments:
- Tes Xcel EDA Project with Costs 3.7z (ID 320)

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
