### ISSUE TITLE
Bundle tests take too much space

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3311]
Change to use gem other than openstudio-standards to save space.  Also tests should not change Gemfile.lock in source directory.

**Comment by jmarrec** [comment]
186ccd5db4180d9697fa7e513f2e20851c9a85c6 fixed it: the bundle_git now uses openstudio-extension instead

https://github.com/NREL/OpenStudio/blob/17912d4d6be39e999fdd174908189b8a61b2ada5/src/cli/test/bundle_git/Gemfile#L1-L6

**Comment by jmarrec** [comment]
Hum, we should wipe any references to openstudio-standards really.
