### ISSUE TITLE
BillingPeriod.modelConsumption doesn't gather values when fuel type for utility bill is "FuelOil_2"

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#3316]
I ran across this testing an updated version of CalibrationReportsEnhanced measure setup to add support for Fuel Oil #2. In a test model that shows consumption in EnergyPlus for Electricity, Natural Gas, and Fuel Oil #2, `BillingPeriod.modelConsumption' only returns boost optional for UtilityBills with fuel type of "Electricity" and "Gas" but not "FuelOil_2". "FuelOil_2" comes from adding utility bill in the OS App.

**Comment by DavidGoldwasser** [comment]
Needed for project, would, like to get this in the first 2.7.x installer after 2.7.0

**Comment by macumber** [comment]
Can you give me an example OSM?  Looks like the error is probably happening here:

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/UtilityBill.cpp#L1190

But I don't know why unless I can see the OSM and a SQL file

**Comment by macumber** [comment]
Fixed in https://github.com/NREL/OpenStudio/pull/3345/commits/b3edfdc249b6e40db2058b222e52b53fb9576ff9
