### ISSUE TITLE
Warnings on require openstudio

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3320]
ruby -v -e "require 'openstudio'" produces:

```
C:/openstudio-2.7.0/Ruby/openstudio.so: warning: method redefined; discarding old inspect
C:/openstudio-2.7.0/Ruby/openstudio.so: warning: method redefined; discarding old to_s
C:/openstudio-2.7.0/Ruby/openstudio.so: warning: method redefined; discarding old value
C:/openstudio-2.7.0/Ruby/openstudio.so: warning: method redefined; discarding old dup
C:/openstudio-2.7.0/Ruby/openstudio.so: warning: method redefined; discarding old inspect
C:/openstudio-2.7.0/Ruby/openstudio.so: warning: method redefined; discarding old to_s
C:/openstudio-2.7.0/Ruby/openstudio.so: warning: method redefined; discarding old next
....
```

**Comment by macumber** [comment]
Solution is probably to undef/alias old methods before redefining, could not get Kernel.warn to give me line number of warning

**Comment by jmarrec** [comment]
Still true today, tested with 2.9.0 on Ubuntu.

**Comment by jmarrec** [comment]
Closing, part if #3516

**Comment by pflaumingo** [comment]
Just leaving a note in case anyone runs into this. I had an issue with this making tests less clear so in my test helper I added the code snippet below and it suppressed the warnings. It's hacky and please chime in if you think there are any major side effects.

`ruby
_stderr, $stderr = $stderr, StringIO.new
require 'openstudio'
$stderr = _stderr
`
