### ISSUE TITLE
Measure Manager update measures doesn't work if only XML file has been updated

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#3329]
I thought there was an old issue about this that had been fixed, but I could find it.

In example I change only min_compatible in the XML file. version_id version_modified and xml_checksum are not updated.

To get upload to BCL to work I have to change measure.rb run measure manager, change meaure.rb back, then re-run measure manager.

As a note, while this works it does move the location of the data related to measure.rb in the XML which isn't as clean for version control.

**Comment by macumber** [comment]
FYI, this is where the XML checksum is computed, https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/utilities/bcl/BCLXML.cpp#L891

It will be difficult to change this without causing different versions of OpenStudio to see updates

**Comment by DavidGoldwasser** [comment]
We could always just add a note in measure writing guide that if updating XML by hand, for elements not in measure.rb that the version_id should also be updated by hand. We could also update this script to do this as well.
https://github.com/NREL/OpenStudio-measures/blob/develop/update_min_version.rb

**Comment by jmarrec** [comment]
Is this still an annoyance or can we close?
