### ISSUE TITLE
EMS:MeteredOutputVariable is swig'd wrong

### ISSUE THREAD

**Issue by brianlball** [NREL/OpenStudio#3336]
setEMSProgramOrSubroutineName() will fail in Ruby.
solution:  swig EMS:Program and EMS:Subroutine before EMS:MeteredOutputVariable

**Comment by macumber** [comment]
Just as an FYI @brianlball it is often enough to forward declare a class for SWIG, in this case it looks like there aren't circular dependencies so it's ok to just change the order

**Comment by brianlball** [comment]
fixed in PR https://github.com/NREL/OpenStudio/pull/3339
