### ISSUE TITLE
Update RunPeriod vs Annual reporting periods in OS

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3348]
E+ 8.9 now distinguishes between these two

**Comment by jmarrec** [comment]
I don't really get this issue. Do you @joseph-robertson ?

**Comment by joseph-robertson** [comment]
Maybe this? https://github.com/NREL/EnergyPlus/pull/6456

@jmarrec

**Comment by jmarrec** [comment]
@joseph-robertson I think you're right. So it requires handling that mostly in SqlFile stuff, like here: 

https://github.com/NREL/OpenStudio/blob/2fe43e38d04570310be30725a8c6d175853fa1fe/src/utilities/sql/SqlFileEnums.hpp#L53-L59

**Comment by joseph-robertson** [comment]
I guess I still don't totally understand what needs to be done here.

I do see that now in 9.2 we have separate Annual and Run Period reporting frequencies, whereas prior to 8.9 we did not. But under what scenario(s) can they be different? Here are some possible example scenarios I have in mind:

- [ ] Run Period is 1/1 to 12/31 (Annual is equal?)
- [ ] Run Period is 2/1 to 2/28 (Annual is equal?)
- [ ] Run Period is 12/1/2007 to 1/31/2008 (Annual has two values, 2007 and 2008? Whereas Run Period is the sum?)

Does this Annual vs Run Period even matter if OpenStudio does not yet support multi-year (or wrap-around) simulations?

@jmarrec @kbenne @jasondegraw

**Comment by jasondegraw** [comment]
@joseph-robertson From memory, the annual result only gets reported at the end of a 12/31. So for your second scenario it shouldn't get reported, and for the third there'll be just one on 12/31/2007. I wouldn't think it would matter too much without multiyear simulations, but it would still be good to support it. We're using an E+ measure to modify the RunPeriod year, it'd be helpful not to have to also mess with output variables.
