### ISSUE TITLE
AvailabilityManager:OptimumStart Incorrect Units

### ISSUE THREAD

**Issue by luisclv** [NREL/OpenStudio#3358]
**OS Version:** 2.6.1

## Problem
While displaying I-P units in Openstudio, adding a `AvailabilityManager:OptimumStart` from the library shows SI units for the gradient inpunts (the units show K/h instead of R/h).
## Solution
The GUI should display R/h when the global unit system is set up to I-P, and it should be able to convert the inputs from SI to I-P in the text file.

**Comment by jmarrec** [comment]
Fixed in develop3 (will be 3.0.0 when released officially) via https://github.com/NREL/OpenStudio/pull/3782
