### ISSUE TITLE
EnergyPlus ReverseTranslator does not handle Zone outside boundary condition for surfaces (Bugzilla #1260)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#338]
On 2013-05-31 08:09:38, @macumber wrote:

> Reported by Christian Frenzel <Frenzel@Transsolar.com>, Fri 5/31/2013 7:02 AM
> 
> - We encountered errors if the imported IDF applies 
>    âOutside Boundary Conditionâ = Zone 
>   Where as If âOutside Boundary Conditionâ = Surface the import for the same file worked fine.
>   Is this a known issue?

**Comment by macumber** [comment]
Looks like this is fixed https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ReverseTranslator/ReverseTranslateBuildingSurfaceDetailed.cpp#L109
