### ISSUE TITLE
[BUG] SWIGTYPE_p_openstudio__model__ZoneHVACTerminalUnitVariableRefrigerantFlow

### ISSUE THREAD

**Issue by MingboPeng** [NREL/OpenStudio#3398]
Hi, I think there is a bug in 2.7.0 version,
addTerminal in VRF is asking for "SWIGTYPE_p_openstudio__model__ZoneHVACTerminalUnitVariableRefrigerantFlow". 

![image](https://user-images.githubusercontent.com/9031066/50732455-d8420180-1149-11e9-8c6e-0d528945e8b3.png)

Thanks,
Mingbo

**Comment by chriswmackey** [comment]
@macumber ,

Here is a code example that you can run on your end to re-create the error:
```
import OpenStudio

model = OpenStudio.Model()
vrfAirConditioner = OpenStudio.AirConditionerVariableRefrigerantFlow(model)
vrfTerminalUnit = OpenStudio.ZoneHVACTerminalUnitVariableRefrigerantFlow(model)
vrfAirConditioner.addTerminal(vrfTerminalUnit)
```
I know that it is in Python but it should be quickly translate-able to Ruby.

Also, to be clear, this is an issue that affects the C# bindings

**Comment by macumber** [comment]
Thanks @chriswmackey , I think this must be specific to the C# bindings since the following Ruby code runs fine:

```
model = OpenStudio::Model::Model.new
vrfAirConditioner = OpenStudio::Model::AirConditionerVariableRefrigerantFlow.new(model)
vrfTerminalUnit = OpenStudio::Model::ZoneHVACTerminalUnitVariableRefrigerantFlow.new(model)
vrfAirConditioner.addTerminal(vrfTerminalUnit)

puts model
```

That makes me feel like this is a bit too risky to include in the release at this stage, I will mark it as high importance though

**Comment by chriswmackey** [comment]
Ok @macumber . I ran a few more tests and this seems to be the only issue with the C# bindings that is large enough to stop us from telling the Honeybee legacy users to move on from OpenStudio 2.5.  If this gets addressed in a pre-release after the release of 2.8, we should hopefully be able to point people towards an updated version of OpenStudio that is compatible with Honeybee legacy.

**Comment by chriswmackey** [comment]
Thank you @jmarrec and @macumber !

**Comment by jmarrec** [comment]
More C# swig cleanup in https://github.com/NREL/OpenStudio/pull/3494
