### ISSUE TITLE
Purge unused schedules button is disabled (Bugzilla #1265)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#341]
On 2013-05-31 08:31:42, @asparke2 wrote:

> Re-enable the purge unused schedules button; fix backend code if necessary (this bug was disabled to "fix" some backend issue that is hit when deleting unused schedules.

**Comment by macumber** [comment]
@DavidGoldwasser I just tested this and it appears to be fixed, can you confirm and close this ticket?

**Comment by macumber** [comment]
@DavidGoldwasser can you test and confirm or close this?
