### ISSUE TITLE
.setAshraeTaub() for OpenStudio:Model:DesignDay doesn't work for values greater than 1

### ISSUE THREAD

**Issue by lymereJ** [NREL/OpenStudio#3410]
The method to set the ASHRAE clear sky optical depth for beam irradiance (`.setAshraeTaub()`) for design day objects seem to only work for values between 0 and 1. If a value greater than 1 is passed to the method, the ASHRAE Taub doesn't get assign a value.

The default range in older versions of EnergyPlus was between 0 and 1 but the default range in EnergyPlus 9.0 is between 0 and 1.2.

**Comment by jmarrec** [comment]
the OpenStudio.idd is out of date for a lot of the object. Taub and Taud both have outdated maximum values, but that's not all. Changing the ranges is an easy fix, but not sure if it would be worth it to update the entire object's IDD to match E+ if we touch it.
