### ISSUE TITLE
"Always On Discrete hvac_library" makes Create Baseline Building measure fail

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#3418]
The `Always On Discrete hvac_library` that gets assigned to some Availability schedule fields causes an [OpenStudio error](https://github.com/NREL/OpenStudio/search?q=%22Required+availability+schedule+not+set%22&unscoped_q=%22Required+availability+schedule+not+set%22) when running the Create Baseline Building measure with the cryptic message...

```
ERROR Required availability schedule not set, using 'Always On' schedule
```

Solution is to find all fields that reference the schedule and assign to `Always On Discrete` instead. @asparke2

**Comment by jmarrec** [comment]
Can you give a specific example please?

**Comment by DavidGoldwasser** [comment]
@asparke2 is it possible baseline logic expects everything to to ScheduleRuleset and not AlwaysOnDiscrete? If so we could convert to ScheduleRuleset as pre-processor to running baseline?

**Comment by macumber** [comment]
This seems like an issue for Openstudio-Standards?

**Comment by MatthewSteen** [comment]
I tried to replicate the issue with a new model, but wasn't able to. However, this is the second model that I've experienced this error with. The first time, I asked Andrew about it on Slack who indicated that it was more of an OS issue. I'll close it for now and reopen if I can replicate it.
