### ISSUE TITLE
The dialog saying that measures were brought in from baseline seems to come up even when there are no measures (Bugzilla #1267)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#342]
On 2013-05-31 09:45:29, @DavidGoldwasser wrote:

> Seems like this should only trigger when there were measures to bring in, but I just saw it on a model that didn't have any measures. Kind of confusing.

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
