### ISSUE TITLE
Measure Tab - if you change seed model, you don't always see red triangle for measure where you should (Bugzilla #1268)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#343]
On 2013-05-31 10:04:32, @DavidGoldwasser wrote:

> If one of your measures has a choice argument using model objects, and the new model doesn't have that object, the field will be blank. That is happening, but the red triangle doesn't immediately come up next to it. 
> 
> If I switch to another major tab and then come back, the triangle is there. I thought it used to work without having to switch tabs, but maybe not. Pretty minor but I thought I'd file a bug for it.

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
