### ISSUE TITLE
error removing four pipe active beams in os v26 and v27

### ISSUE THREAD

**Issue by inkmug** [NREL/OpenStudio#3430]
Cannot remove four pipe active beam system in openstudio v2.6 and v2.7.

Detailed description and screenshots here:
https://unmethours.com/question/37348/error-removing-four-pipe-active-beams-in-os-v26-and-v27/

**Comment by jmarrec** [comment]
@inkmug Can you give an actual example (minimal if possible)? I'm having trouble reproducing it

**Comment by inkmug** [comment]
@jmarrec i also tried the hvac_library model, created one thermal zone, one empty air loop, and added the "Air Terminal Four Pipe Beam'. 
It worked when clicking on the cross to delete the beam object in the air loop. But when i changed the screen to other tab, the error occurred. 
OSA file attached.
[hvac_library_temp.zip](https://github.com/NREL/OpenStudio/files/2906969/hvac_library_temp.zip)

**Comment by inkmug** [comment]
@jmarrec Hi Julien, let me know if you received my previous message and if this is something that you can clarify or fix (if there's a bug) soon. If it will take some time for you to look at it, do i have to delete it manually along with all the connections, or what do you recommend? I need to move on given the project schedule. thanks!

**Comment by jmarrec** [comment]
I can reproduce this in OpenStudio 2.7.1 indeed, switching tabs produces the crash. I will investigate and fix this, but it won't happen soon enough if you are on a deadline.

I suggest removing the four pipe beam terminals using the ruby bindings as a workaround for now.
Load the model into a variable `m` then do `m.getAirTerminalSingleDuctConstantVolumeFourPipeBeams.each {|atu| atu.remove}` then save again.

If you don't know how to do this, you can email me your file, tell me which you want removed, and I'll do it.

**Comment by inkmug** [comment]
Hi, @jmarrec looks like the issue is fixed? How can I update on my end? Do I need to use a new version, reinstall v2.6, or download some kind of updated library file? thanks

**Comment by macumber** [comment]
Looks like the fix is included in OpenStudio 2.8.0 which you can download from https://www.openstudio.net/downloads

**Comment by inkmug** [comment]
thanks, is there any way i can use this in v2.6?

**Comment by macumber** [comment]
Unfortunately it looks like it required a code change that is not available in 2.6.0
