### ISSUE TITLE
EnergyPlus Reverse Translation of ZoneList gives weird error about Zone (Bugzilla #1270)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#344]
On 2013-06-04 08:30:05, @macumber wrote:

> Looks like typos:
> 
> OptionalModelObject ReverseTranslator::translateZoneList( const WorkspaceObject & workspaceObject )
> {
>    if( workspaceObject.iddObject().type() != IddObjectType::Zone ){
>     LOG(Error, "WorkspaceObject is not IddObjectType: Zone");
>     return boost::none;
>   }
> 
>   case openstudio::IddObjectType::ZoneList:
>     {
>       modelObject = translateZone(workspaceObject);
>       break;
>     }

On 2013-06-04 08:30:47, @macumber wrote:

> Also handle:
> 
> Error: Unknown IddObjectType: 'ProgramControl'
> Error: Unknown IddObjectType: 'Output:VariableDictionary'

**Comment by jmarrec** [comment]
see #1019

**Comment by jmarrec** [comment]
Fixed via #3776 in develop3
