### ISSUE TITLE
Enforce unique naming when using "OpenStudio::Model::LifeCycleCost.createLifeCycleCost" (Bugzilla #1272)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#345]
On 2013-06-04 14:35:57, @DavidGoldwasser wrote:

> So in place of the bad bug which didn't exist, is a minor bug. I think if you try to set a space name that is already used we don't let you do it (even though the UUID is all that matters) because it makes things bad in the GUI if names look the same.
> 
> While LifeCycleCost objects are not in the GUI now, it would be nice to enforce that naming. When I create an object using the method in the summary, with a name that is already used, it would be nice to either append the name, or add in the default name that I would get if I had not requested one.

**Comment by jmarrec** [comment]
@DavidGoldwasser Still a problem today?
