### ISSUE TITLE
Conan and python bindings

### ISSUE THREAD

**Issue by damianCaceres** [NREL/OpenStudio#3457]
Good night:
After the conan package manager introduction, I can compile OS in Ubuntu 18.04 but not the python bindings (py2 and py3)

`
[  7%] Building CXX object src/utilities/CMakeFiles/python_OpenStudioUtilities.dir/python_OpenStudioUtilities_wrap.cxx.o
In file included from /usr/include/python3.6m/Python.h:39:0,
                 from /home/damian/openstudio/build-core/src/utilities/python_OpenStudioUtilities_wrap.cxx:179:
/home/damian/.conan/data/zlib/1.2.11/conan/stable/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:35:53: error: ‘z_crc_t’ does not name a type
 static int decrypt_byte(unsigned long* pkeys, const z_crc_t* pcrc_32_tab)
                                                     ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/conan/stable/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:48:51: error: ‘z_crc_t’ does not name a type
 static int update_keys(unsigned long* pkeys,const z_crc_t* pcrc_32_tab,int c)
                                                   ^~~~~~~
/home/damian/.conan/data/zlib/1.2.11/conan/stable/package/aff0eb9e4c299cac0972a5fe39033141b3e50a6d/include/crypt.h:65:69: error: ‘z_crc_t’ does not name a type
 static void init_keys(const char* passwd,unsigned long* pkeys,const z_crc_t* pcrc_32_tab)
                                                                     ^~~~~~~
src/utilities/CMakeFiles/python_OpenStudioUtilities.dir/build.make:285: recipe for target 'src/utilities/CMakeFiles/python_OpenStudioUtilities.dir/python_OpenStudioUtilities_wrap.cxx.o' failed
make[2]: *** [src/utilities/CMakeFiles/python_OpenStudioUtilities.dir/python_OpenStudioUtilities_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:1135: recipe for target 'src/utilities/CMakeFiles/python_OpenStudioUtilities.dir/all' failed
make[1]: *** [src/utilities/CMakeFiles/python_OpenStudioUtilities.dir/all] Error 2

`
Thank you very much

**Comment by macumber** [comment]
I don't think anyone has yet built the python bindings on develop3.  Our initial focus is on separating the OS App so we probably won't be working on that in the near future.
