### ISSUE TITLE
No Fan:OnOff in HVAC library

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3470]

**Comment by jmarrec** [comment]
Can you actually put a Fan:OnOff directly onto an airloophvac? I was under the impression that FanOnOff could only live inside another component (zonehvac or unitary). There are plenty of FanOnOff inside the hvac_library but all are part of a containing component and therefore not showing in the OS app.

 (This is somewhat of a rhetorical question to remember to start by checking this)

**Comment by macumber** [comment]
I'm not sure.  The request was to put it in the system you get when you create a "Packaged Rooftop Unit" using the Add HVAC System template menu in the App.

**Comment by jmarrec** [comment]
Fan:OnOff cannot be placed directly onto an AirLoopHVAC branch, it must be inside another component such as a ZoneHVAC or a Unitary system.

I knew that looking at the E+ IDD, because Fan:OnOff doesn't bear these references:

```
       \reference-class-name validBranchEquipmentTypes
       \reference validBranchEquipmentNames
       \reference-class-name validOASysEquipmentTypes
       \reference validOASysEquipmentNames
```

I then made a test file anyways, taking 5ZoneAirCooled.idf and swapping the Fan:CV by a Fan:OnOff, and watched it failed:

```
   ** Severe  ** GetAirPathData: AirLoopHVAC = "VAV SYS 1".
   **   ~~~   ** ..Invalid Air Loop Component Type = "FAN:ONOFF".
   **   ~~~   ** ..Air Loop Component Name = "SUPPLY FAN 1".
   **   ~~~   ** ..reference Branch = "VAV SYS 1 MAIN BRANCH".
   **   ~~~   ** ...This component may only be referenced by a parent component such as AirLoopHVAC:Unitary:Furnace:HeatCool or similar.
   **  Fatal  ** GetAirPathData: Errors found retrieving input for AirLoopHVAC.
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=1
   ..... Last severe error=GetAirPathData: AirLoopHVAC = "VAV SYS 1".
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
```
