### ISSUE TITLE
Basic Envelope Change results opposite EUI results of those expected

### ISSUE THREAD

**Issue by Machbo** [NREL/OpenStudio#3483]
This is a very basic question.  I have two OpenStudio files.  The only difference is one wall construction with a higher R value between the two.  After running the simulation, the file with the higher R value in an exterior wall has returned a higher EUI.  I can't find the issue. I've attached the two files.  The ALt file is the improved wall construction with the worse EUI.  Any ideas?
[BuildingSim.zip](https://github.com/NREL/OpenStudio/files/3036053/BuildingSim.zip)

**Comment by macumber** [comment]
Hey @Machbo thanks for the report, this type of question is best asked on https://unmethours.com/questions/.  If it is found that there is an OpenStudio bug responsible we can reopen the ticket
