### ISSUE TITLE
Wrong "Temperature Setpoint Node Name" in CoilHeatingElectric

### ISSUE THREAD

**Issue by MingboPeng** [NREL/OpenStudio#3487]
Hi @macumber,

I found there is a bug when adding CoilHeatingElectric to loop. it's field "Temperature Setpoint Node Name" is not set correctly, this only happens when the Fan is added before the CoilHeatingElectric, and its "Temperature Setpoint Node Name" is set to Fan's inlet node, instead of loop's supplyOutletNode.

This happens in HVACTemplates.cpp where CoilHeatingElectric is added to fanInletNode. https://github.com/NREL/OpenStudio/blob/e077c7edfa6c94bb37aeb0e31f40b69ed2740223/openstudiocore/src/model/HVACTemplates.cpp#L548-L550

In OpenStudio App interface, this happens the same.

Please let me know if this is makes sense, or more info needed.

Thanks in advance,
Mingbo

**Comment by macumber** [comment]
Thanks for the great reports @MingboPeng. I don't think we will get this in the 2.8.0 release but I think @jmarrec should be able to get to it pretty easily. 

Do you have a repository with a set of automated tests we could run each release?  We don't have good test coverage for our C# bindings, running a test suite of your work could be very helpful.

**Comment by jmarrec** [comment]
Which HVACTemplate system are you using exactly? No further modifications?
Are you checking the resulting IDF file or the OSM itself?
Thanks

**Comment by MingboPeng** [comment]
Thanks @macumber , thanks for looking at this issue. Currently, I mainly use Visual Studio to see if there is any problem during [Irongbug](https://github.com/MingboPeng/Ironbug/tree/master/src/Ironbug.HVAC)'s compiling process.
Beside that, I do have a several unit tests for some workflows and basic use of OpenStudio API.
https://github.com/MingboPeng/Ironbug/tree/master/src/Ironbug.HVAC.Test
It is not clean structured at all, but happy to create a separate repository for C# binding tests.

Hi @jmarrec , what I can find is the [system 6 ](https://github.com/NREL/OpenStudio/blob/e077c7edfa6c94bb37aeb0e31f40b69ed2740223/openstudiocore/src/model/HVACTemplates.cpp#L548-L550) and [system 8](https://github.com/NREL/OpenStudio/blob/e077c7edfa6c94bb37aeb0e31f40b69ed2740223/openstudiocore/src/model/HVACTemplates.cpp#L819-L821)
Both of them are all because the CoilHeatingElectric is added to fanInletNode. Is there any reason that fan is added before CoilHeatingElectric? There is no problem that if add CoilHeatingElectric to supplyOutletNode first, then add fan to the loop.

This issue was not easy to found, I was comparing the OSM file line by line to find out this "Temperature Setpoint Node Name" issue in CoilHeatingElectric. and tested by changing its handle ID to the correct supplyOutletNode where has setpoing manager. the simulation gets the same results as I add CoilHeatingElectric before the fan.

Hope this helps.

**Comment by macumber** [comment]
This issue seems like something we should have covered in our regression tests?

**Comment by jmarrec** [comment]
I have enough information to reproduce I think (great thanks @MingboPeng!), I'll take a look early next week. It's possible the forward translator is also doing its thing. I'll report back

**Comment by jmarrec** [comment]
Are you seeing a difference in output results after e+ simulation? Total site energy for eg.

I took a brief look on my phone and I see that indeed since is just translated as is, BUT unless you have explicitly set a SetpointManager on coil outlet / fan inlet node, then openstudio adds a SPM:MixedAir to that node so it should all end up just fine.
(That would also answer Dan's question on regression: simulation runs and produces consistent results anyways).

If you don't have time to answer the above it's fine I'll set up a quick test.

**Comment by MingboPeng** [comment]
Thanks @jmarrec for looking at this issue. Yes, I checked the simulation results, that is how I found this issue (or may not be an issue). The simulation results are different between following two orders:

 **1. Add heating coil before the fan**
```
    var m1 = new Model();

    var lp1 = new AirLoopHVAC(m1);
    var supplyOutletNode1 = lp1.supplyOutletNode();
    ////Add heating coil
    var coil1 = new CoilHeatingElectric(m1);
    coil1.addToNode(supplyOutletNode1);
    ////Add fan
    var fan1 = new FanConstantVolume(m1);
    fan1.addToNode(supplyOutletNode1);
    ////Add SPM
    var spm1 = new SetpointManagerScheduled(m1, new ScheduleRuleset(m1, 20));
    spm1.addToNode(supplyOutletNode1);

    //check temperatureSetpointNode
    if (coil1.temperatureSetpointNode().is_initialized())
    {
      var coilTempNodeName = coil1.temperatureSetpointNode().get().nameString();
      var SpmNodeName = supplyOutletNode1.nameString();
      var isCoilTempNodeSetToSPM = coilTempNodeName == SpmNodeName;
      //isCoilTempNodeSetToSPM is True;
    }
```
**2. Add fan before heating coil**
```
    var m1 = new Model();
    var lp2 = new AirLoopHVAC(m1);
    var supplyOutletNode2 = lp2.supplyOutletNode();
    ////Add fan
    var fan2 = new FanConstantVolume(m1);
    fan2.addToNode(supplyOutletNode2);
    ////Add heating coil
    var fanInletNode = fan2.inletModelObject().get().to_Node().get();
    var coil2 = new CoilHeatingElectric(m1);
    coil2.addToNode(fanInletNode);

    ////Add SPM
    var spm2 = new SetpointManagerScheduled(m1, new ScheduleRuleset(m1, 20));
    spm2.addToNode(supplyOutletNode2);

    //check temperatureSetpointNode
    if (coil2.temperatureSetpointNode().is_initialized())
    {
      var coilTempNodeName = coil2.temperatureSetpointNode().get().nameString();
      var SpmNodeName = supplyOutletNode2.nameString();
      var isCoilTempNodeSetToSPM = coilTempNodeName == SpmNodeName;
      //isCoilTempNodeSetToSPM is False;
    }
 
```
The reason I see this might be an issue is because they looks identical in current OpenStudio App, until I checked the OSM file. Maybe it is good to expose the field "Temperature Setpoint Node Name" in the OpenStudio App, so that uses can actually see the difference, and have an opportunity to change it manually. (I know NREL is stopping working on the App interface)

**Comment by jmarrec** [comment]
After discussion with Kyle, we seem to have found a potential roadmap.

@MingboPeng How about the following:

* Change the coils addToNode methods to **not** set the 'Temperature Setpoint Node' field like it does now (it's an optional field)
* Optionally: show the 'Temperature Setpoint Node' in OS App.
    * I myself am against it. I think this is going to be confusing for most users, and if an advanced user wants to set it, she can use the bindings to do so.
* In the energyplus Forward Translator, if the field is blank at translation time, then set it to the supply outlet node of the coil (where a SPM:MixedAir will be created for you too)

The alternative is to simply delete the field in openstudio and always write to coil outlet node in FT, like what's done for CoilHeatingGas.

**Comment by MingboPeng** [comment]
@jmarrec  
I think this works, not setting the 'Temperature Setpoint Node' in addToNode method. This removes discrepancy of simulation results when user (even advanced user) add this CoilHeatingElect to airloop in a different order. 

Agree with 'Temperature Setpoint Node' in OS App. I think it can either be not shown (as it is now), or shown as a disabled field.

Let's preserve the API.

Thanks again for fixing this.
