### ISSUE TITLE
Loading libraries in app is incredibly slow

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#3501]
Starting the App (on Mac, can't speak for Windows) is incredibly slow.  I'm running with a couple of the DEER libraries, and the App takes 3-5 minutes to start - this is hitting both me and Sammy.  I think the time is being spent in version translation of the libraries.

**Comment by macumber** [comment]
You are probably right about the source of the slowness.  Can you (make a copy first) open your DEER libraries in the App directly and save them?  That will do the version translation for you.

@Shoussai FYI

**Comment by macumber** [comment]
I wonder if your preferences are pointing to templates from an older installer?

**Comment by ljbrackney** [comment]
They are - 2.7.1 to be exact.  I deleted all the entries and tried a restore to defaults, but it jumps right back to 2.7.1.  There's no way to navigate into the 2.8.0 version of the app/Contents/Resources/...

**Comment by macumber** [comment]
Related to https://github.com/NREL/OpenStudio/issues/3146

**Comment by jmarrec** [comment]
@ljbrackney try deleting the `~/Library/Preferences` plist files.

```
cd ~/Library/Preferences/
/bin/rm com.nrel.OpenStudio*
```

**Comment by macumber** [comment]
Fix also needs to have script added to CI before this is closed

**Comment by macumber** [comment]
@jmarrec do we also need to check if this is a new install and offer to relocate resource dir in preferences?

**Comment by jmarrec** [comment]
I'm not sure what happened above as I haven't been able to reproduce it.
Are you suggesting that the OpenStudio installer would just delete the preferences and reset the library to the defaults?

**Comment by ljbrackney** [comment]
No – unless that’s required to fix the issue.

I just started the App, and it took nearly 2 CPU minutes from launch to the App window opening and being ready for business.  This time was spent stuck on the library loading window – presumably in a translation step.

**Comment by jmarrec** [comment]
@ljbrackney yeah that is inacceptable. The fact that you can't restore the library defaults is the most problematic. Did you try deleting the .plist files as I suggested above? If so, it didn't fix the reset?
