### ISSUE TITLE
Verify CLI working with Ruby 2.5.5

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3516]
- [x] Gem::Specification.add_spec is deprecated and will be removed in RubyGems 3.0 (https://github.com/rubygems/rubygems/issues/2469)
- [x] warning: already initialized constant JSON::VERSION, something weird is going on when loading json, probably due to json pure gem. (Originally posted as https://github.com/NREL/OpenStudio/issues/3545)
     - Related: https://github.com/NREL/OpenStudio/issues/3320
- [ ] Cannot require file from disk in Debug mode on Windows
- [x] Run regression tests using develop3
- [x] Run measure tests using develop3
- [x] Run gbXML tests using develop3
- [ ] Get parallel working in CLI using develop3
- [ ] Allow require digest/sha1

**Comment by shorowit** [comment]
👍 for dealing with the json warnings. they are annoying.

**Comment by tijcolem** [comment]
Currently, no issues have been discovered using ruby 2.5.5 with CLI.  Keep issue open for now.

**Comment by tijcolem** [comment]
closing this issue.  can reopen separate issues related to ruby 2.5.5 if they become apparent.
