### ISSUE TITLE
Tab 4 - When you open model in OpenStudio results are blank (Bugzilla #1282)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#352]
On 2013-06-10 11:42:25, @DavidGoldwasser wrote:

> Maybe this is an OS bug vs. a pat bug, but it happens when you open a model from PAT. I thought at some point I could see results just by going to results tab in OS app. But know that is empty, as is the SQL file if I click "Open ResultsViewer for Detailed Reports".
> 
> As a test I took a manually run OSM file (ran via OS app), I saved, quit and re-opened and it does get the results. I assume this is due to different file structures of where results are found relative to the model.

On 2013-06-11 15:13:35, @DavidGoldwasser wrote:

> Also, if the model you are open is a design alternative then the weather file isn't brought over. If yous save and run it in OS app there will be a fatal error. 
> 
> If you open the Baseline model from tab 4 then the weather file seems to come along fine.

**Comment by evanweaver** [comment]
Closed. Unable to reproduce.
