### ISSUE TITLE
Make sizing:parameters object editable in Simulation Settings tab

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3522]
The sizing:parameters object controls the sizing of hvac components in a model. ASHRAE 90.1 Appendix G requires 1.25 sizing factor for heating and 1.15 sizing factor for cooling. In order to enable people to make their own 90.1-compliant systems with OpenStudio, this object must be made available for editing. The Simulation Settings tab is probably the best place to put it.

**Comment by jmarrec** [comment]
It's been there for ages, at least as far back as I can remember.

![image](https://user-images.githubusercontent.com/5479063/65685653-c3542800-e062-11e9-8370-85972620101e.png)
