### ISSUE TITLE
SWIG-Related Bug in OpenStudio 2.8 CSharp Bindings: (EntryPointNotFoundException): Unable to find an entry point named 'CSharp_OpenStudio_WorkspaceObject_SWIGUpcast'

### ISSUE THREAD

**Issue by chriswmackey** [NREL/OpenStudio#3529]
I have found an issue that seems to affect a small percentage of installations (likely < 10%) of OpenStudio 2.8 on Windows.  For the vast majority of 2.8 users, things seem fine but I know of at least one person that has experienced the following error:

`Runtime error: (EntryPointNotFoundException): Unable to find an entry point named 'CSharp_OpenStudio_WorkspaceObject_SWIGUpcast' in DLL 'openstudio_csharp.dll'.`

The error occurs when trying to get the RunPeriod object from the model like so:

```
import OpenStudio

model = OpenStudio.Model()
run_period = OpenStudio.Model.getRunPeriod(model)
```

Again, this issue only seems to affect certain machines and the vast majority seem to be fine.  I am trying to gather some data on what operating system people are using on [this forum post](https://discourse.ladybug.tools/t/honeybee-openstudio-2-8/6091/10) to see if we can find a pattern between the systems experiencing the issue.  The error above came from someone using Windows 10 Pro.  If there's any other info you want to me to gather to inform this issue, just let me know.

**Comment by macumber** [comment]
Thanks @chriswmackey yes anything you can do to diagnose would be helpful, I do suspect this might be related to Windows version as well as presence or absence of other dynamic libraries on the system

@tijcolem FYI

**Comment by chriswmackey** [comment]
Thanks @macumber .  Apparently, someone was able to solve it by reinstalling a few times if you check the forum link I posted.  Will let you know if I find out more.

**Comment by tijcolem** [comment]
The fact that reinstalling works leads me to believe it's a wrong dll (perhaps older version) and not finding the entry point due to something being updated in the new dll.   Have you tried uninstalling and reinstalling?

**Comment by MingboPeng** [comment]
This might because of an old version was loaded in the Rhino (Grasshopper) before the 2.8 installation, and two versions of OpenStudio are loaded in the same instance of Rhino.  Open or restart the rhino, and only load one version of OpenStudio would probably solve this problem.

**Comment by macumber** [comment]
Is requiring a restart of Rhino sufficient to fix this?  If so I think we can close it.

**Comment by chriswmackey** [comment]
This sounds possible and I know having g two instances of OpenStudio loaded cases errors. Let me check with the person experiencing the issue or try to recreate it myself.

**Comment by chriswmackey** [comment]
According to the person who reported the issue, that was indeed the problem.  So we can close out this issue now and sorry for the trouble.
