### ISSUE TITLE
Tab 1 - The measures in MyMeasures are not sorted by display name (Bugzilla #1286)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#353]
On 2013-06-12 15:08:05, @DavidGoldwasser wrote:

> I noticed when I look at "Economics.Life Cycle Cost Analysis" section that they are not in order. Doesn't seem to match the class name in the measure.rb either.
> 
> I am using the "final instances" as MyMeasures and this is the order I see the measures in the right pane.
> 
> Add Cost per Floor Area to Building
> Set Lifecycle Cost Parameters
> Add Cost per Floor Area to Electric Equipment
> Add Cost per Area To Construction
> Add Cost per Floor Area To Lights

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
