### ISSUE TITLE
Subsurfaces subtab doesn't filter Door, OverheadDoor, or Skylight objects

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#3531]
In 2.8.0 the Subsurfaces subtab doesn't filter Skylight SubSurface Types correctly. It looks like the filter is just showing the last object. Probably related to #2776.

**Many Skylights (no filter)**
![image](https://user-images.githubusercontent.com/8397034/57476835-ab673d80-7254-11e9-8587-9bfc771906e7.png)

**One Skylight (filter)**
![image](https://user-images.githubusercontent.com/8397034/57476848-b3bf7880-7254-11e9-99f9-cf09946826c8.png)

**Comment by MatthewSteen** [comment]
Also Doors...

**Many Doors (no filter)**
![image](https://user-images.githubusercontent.com/8397034/64132289-0258cb80-cd8c-11e9-9958-f8c7b7c3b827.png)

**One Door (filter)**
![image](https://user-images.githubusercontent.com/8397034/64132300-14d30500-cd8c-11e9-9494-b72c63c525a3.png)

**Comment by jmarrec** [comment]
@MatthewSteen I can't reproduce using 3.0.0-pre.

![image](https://user-images.githubusercontent.com/5479063/70056006-fecb1f80-15da-11ea-9868-e13984ba282d.png)


Could you send me your model privately please?

**Comment by MatthewSteen** [comment]
@jmarrec done.

**Comment by jmarrec** [comment]
@MatthewSteen Thanks for the model, I was able to reproduce the bug and fix it in https://github.com/NREL/OpenStudioApplication/pull/54
