### ISSUE TITLE
Segmentation fault in script run by CLI (such as an OS measure) hangs on Mac and never returns

### ISSUE THREAD

**Issue by ryandmeyer1017** [NREL/OpenStudio#3533]
I've encountered a scenario which causes the OS application to lockup but not crash. 

I have  an OS measure modifying SHW Plant Loops. At a high level, the measure keeps existing WaterUseConnections already defined in the model and places them on a new plant loop. The scenario that causes the OS application is as follows:

1. Find existing SHW plant loops in the model and remove(), but keep WaterUseConnections
2. Create new SHW plant loop
3. The lockup occurs when I call the addDemandBranchForComponent() method to add the WaterUseConnections to the new SHW plant loop. 

If I call the disconnect() method on the WaterUseConnections in addition to removing the existing SHW plant loops discussed in step 1, then the application does NOT lockup and the measure proceeds as expected. 

I am pointing this out because of the OS application lockup without crashing. This occurred implementing the measure both in the typical workflow or the Apply Measure Now method.

**Comment by jmarrec** [comment]
@ryandmeyer1017 Can you clarify one thing for me please: what do you mean by "keep WaterUseConnections"? Are you **cloning** them before remove or storing a pointer to them such as adding them to a Ruby Array?

When you call `PlantLoop::remove` any `WaterUseConnections` object attached to it will be disconnected **and** then removed.

So if you do the following (or something similar such as storing the `WaterUseConnections` in a ruby array, calling `PlantLoop::remove` then loop on the array to try to re-add the *now-disconnected* `WaterUseConnections` to the new plantLoop), you are producing a **hard crash** (Segmentation fault).

```
include OpenStudio::Model

m = Model.new

p1 = PlantLoop.new(m)
wc = WaterUseConnections.new(m)
p1.addDemandBranchForComponent(wc)

puts "Before: there is #{m.getWaterUseConnectionss.size} WaterUseConnections"
# Removing plantLoop will also remove WaterUseConnections
p1.remove
puts "After: there is #{m.getWaterUseConnectionss.size} WaterUseConnections"

p2 = PlantLoop.new(m)
# At this point wc is a disconnected object so you'll get a Segfault!
p2.addDemandBranchForComponent(wc)
```

**Comment by jmarrec** [comment]
I believe you are on Mac @ryandmeyer1017 aren't you? I wonder if it's not just the App that loses focus (which is a known issue). I think if you hit CMD+M or something you might be able to retrieve the focus. This was posted on an issue but I can't seem to find it again (@DavidGoldwasser might know).

FYI I tested a dumb dumb measure on Ubuntu to produce a crash, and the App doesn't lock up. If I open the 'Advanced Output" I see the full dump of the Segfault".

![image](https://user-images.githubusercontent.com/5479063/57617674-aa4e4d00-7581-11e9-9c75-859ddf045498.png)

measure.rb
```
include OpenStudio::Model


# start the measure
class A3533SHWCrash < OpenStudio::Measure::ModelMeasure
  # human readable name
  def name
    # Measure name should be the title case of the class name.
    return '3533_SHW_Crash'
  end

  # human readable description
  def description
    return 'Test for 3533, trying to produce a hard crash'
  end

  # human readable description of modeling approach
  def modeler_description
    return 'Attempt to produce a hard crash by trying to connect a removed WaterUseConnections to a plantLoop'
  end

  # define the arguments that the user will input
  def arguments(model)
    args = OpenStudio::Measure::OSArgumentVector.new

    return args
  end

  # define what happens when the measure is run
  def run(model, runner, user_arguments)
    super(model, runner, user_arguments)

    # use the built-in error checking
    if !runner.validateUserArguments(arguments(model), user_arguments)
      return false
    end

    p1 = PlantLoop.new(model)
    wc = WaterUseConnections.new(model)
    p1.addDemandBranchForComponent(wc)

    runner.registerInfo("Before: there is #{model.getWaterUseConnectionss.size} WaterUseConnections")
    p1.remove
    runner.registerInfo("After: there is #{model.getWaterUseConnectionss.size} WaterUseConnections")

    p2 = PlantLoop.new(model)
    # At this point wc is a disconnected object so you'll get a hard crash!
    runner.registerInfo("Trying to produce a hard crash")
    p2.addDemandBranchForComponent(wc)

    runner.registerFinalCondition("The building finished with #{model.getWaterUseConnectionss.size} spaces.")

    return true
  end
end

# register the measure to be used by the application
A3533SHWCrash.new.registerWithApplication
```

**Comment by jmarrec** [comment]
Ok I ran the same measure on develop with a Mac Debug Build in Apply Now, it gets stuck on the "Running Measure" (the green arrow keeps spinning). If I click "Cancel" I get brought back to the list of Apply Now Measures, and if I click "Cancel" again to go back to my model, the OS App crashes.

macOS Sierra 10.13.6
OpenStudio 2.8.0 d0721e8679

**Comment by jmarrec** [comment]
Hum, so I think this may be more of a openstudio-workflow-gem problem.

https://github.com/NREL/OpenStudio-workflow-gem/blob/v1.3.3/lib/openstudio/workflow/run.rb#L216

https://github.com/NREL/OpenStudio-workflow-gem/blob/v1.3.3/lib/openstudio/workflow/jobs/run_os_measures.rb#L52

https://github.com/NREL/OpenStudio-workflow-gem/blob/v1.3.3/lib/openstudio/workflow/util/measure.rb#L467

Basically it doesn't actually `rescue` from the C segfault on Mac. Thoughts @macumber please?

**Comment by jmarrec** [comment]
Ok the problem boils down to this:

```
Products/openstudio -e "m = OpenStudio::Model::Model.new; wc = OpenStudio::Model::WaterUseConnections.new(m); p = OpenStudio::Model::PlantLoop.new(m); wc.remove; p.addDemandBranchForComponent(wc)"
```

On Ubuntu, the segfault returns to the terminal. On Mac it keeps hanging.

**Comment by ryandmeyer1017** [comment]
A few notes to your questions above:

1. Yes, I am running Mac HighSierra 10.13.6 and OS 2.8.0
2. Yes, by 'keep' I am storing a pointer to the existing WaterUseConnections in an array and did not want to remove them from the model. It makes sense why the .disconnect() method called before .remove() works. 

Let me know if you need anything additional from me.

**Comment by jmarrec** [comment]
Thanks for your prompt reply @ryandmeyer1017. I have everything I need. Basically for you, do make sure you don't produce a segmentation fault by trying to manipulate removed objects, here do use `disconnect` first. We'll fix the underlying issue though.

**Comment by macumber** [comment]
I'm not sure that you can or should rescue a seg fault.  I think you can define some custom finalizer scripts that might run after a seg fault, that might be enough to write some output.

**Comment by macumber** [comment]
Also, why would a seg fault hang?  That is kind of odd.

**Comment by jmarrec** [comment]
The weird thing is that it's only on Mac that it doesn't actually exit: it hangs after producing the crash dump in the terminal (I can't even CTRL+C to kill it and get the prompt back), while on Ubuntu it prints "Segmentation Fault" and returns the prompt.

**Comment by macumber** [comment]
I wonder if it is trying to run the ensure block after the segfault?  In any case, I think fixing the segfault is sufficient here

**Comment by jmarrec** [comment]
I'm closing this issue as it is the result of user code.
