### ISSUE TITLE
Use E+ 9.1 bugfix builds in OS 2.8.1

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#3543]
E+ 9.1 bugfix builds will be provided by @Myoldmopar. Packages will include [this bugfix](https://github.com/NREL/EnergyPlus/pull/7280), which only affects a new feature introduced in E+ 9.1.

**Comment by Myoldmopar** [comment]
Release tagged [here](https://github.com/NREL/EnergyPlus/releases/tag/v91AndBugFix) at SHA e96d7c1

**Comment by macumber** [comment]
@tijcolem FYI

**Comment by jmarrec** [comment]
Probably should keep energyplus versions at 9.1.0 instead of 9.2.0 as it's confusing now.

**Comment by macumber** [comment]
Closed in https://github.com/NREL/OpenStudio/commit/7df25adc7a06e345ccb84572f6b6938988a011cd

**Comment by mjwitte** [comment]
> which only affects a new feature introduced in E+ 9.1.

@shorowit Actually, this bug affected any use of AirloopHVAC:UnitarySystem as zone equipment in combination with other zone equipment running after the unitary system since the time AirloopHVAC was added to EnergyPlus.
