### ISSUE TITLE
OpenStudio 2.8.1 Release

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3547]
- [x] Release standards gem (if needed), Andrew
- [x] Release workflow gem (if needed), Ry
- [x] Release measure tester gem (if needed), Nick
- [x] Double check gem files for correct versions of standards and workflow gems (use released versions only), Dan
- [x] Update resources and library files (if needed), Julien
- [x] Run Regression Tests, Julien
- [x] Create Debian, Darwin, and Windows untested build zips and upload to S3, Tim
- [x] Test and Release OpenStudio Measures, David
- [x] Run BEST tests with new installer, David
- [x] Run Standards Tests with new installer, Matt
- [x] Run AutoDesk tests with new installer, Noah
- [x] Test server changes with build zips, Anya
- [x] Create Release Notes (if needed), Dan
- [x] Release server (merge to master), Anya
- [x] Build Server packages, post on S3, Dan - Windows, Kyle - Mac
- [x] Update the server SHA in PAT, Tim
- [x] Update the PAT SHA in OpenStudio, Tim
- [x] OpenStudio release process, Tim
- [x] Create and name AMIs, Anya

**Comment by tijcolem** [comment]
This has been released.  https://github.com/NREL/OpenStudio/releases/tag/v2.8.1
