### ISSUE TITLE
Problems in model with Daylighting Control Object (Bugzilla #1290)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#355]
On 2013-06-17 14:32:45, @DavidGoldwasser wrote:

> Created an attachment (id=335)
> draft training model
> 
> I made a model for training. Space 202 has a daylighting control object that is associated with thermal zone 2. When I go to the OS app I don't see this object in the facility tab under the space, and I also don't see any variables for it in the Variables tab.
> 
> The object is making it into the IDF file
> Daylighting:Controls,
>   Thermal Zone 2,                         !- Zone Name
>   1,                                      !- Total Daylighting Reference Points
>   7.62889919565601,                       !- X-Coordinate of First Reference Point {m}
>   3.77292258116248,                       !- Y-Coordinate of First Reference Point {m}
>   0.762,                                  !- Z-Coordinate of First Reference Point {m}
>   ,                                       !- X-Coordinate of Second Reference Point {m}
>   ,                                       !- Y-Coordinate of Second Reference Point {m}
>   ,                                       !- Z-Coordinate of Second Reference Point {m}
>   1,                                      !- Fraction of Zone Controlled by First Reference Point
>   ,                                       !- Fraction of Zone Controlled by Second Reference Point
>   500,                                    !- Illuminance Setpoint at First Reference Point {lux}
>   ,                                       !- Illuminance Setpoint at Second Reference Point {lux}
>   1,                                      !- Lighting Control Type
>   0,                                      !- Glare Calculation Azimuth Angle of View Direction Clockwise from Zone y-Axis {deg}
>   ,                                       !- Maximum Allowable Discomfort Glare Index
>   ,                                       !- Minimum Input Power Fraction for Continuous Dimming Control
>   ,                                       !- Minimum Light Output Fraction for Continuous Dimming Control
>   ,                                       !- Number of Stepped Control Steps
>   ;                                       !- Probability Lighting will be Reset When Needed in Manual Stepped Control

Original attachments:
- Exercise_05.osm (ID 335)

Keywords: ReleaseNotes

**Comment by evanweaver** [comment]
No longer valid.
