### ISSUE TITLE
Identify objects to change/refactor for OpenStudio 3

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3551]
OpenStudio 3 will be an opportunity to remove or refactor any existing objects.  Let's identify objects here and then create new tickets to do the work

**Comment by macumber** [comment]
Move standards fields of OS:SpaceType and OS:Building to be AdditionalProperties?

Remove OS:StandardsInformation:Material and OS:StandardsInformation:Construction, replace with AdditionalProperties?

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio/issues/3379
https://github.com/NREL/OpenStudio/issues/3411

**Comment by jmarrec** [comment]
* [ ] #3525: AFN cleanup (which includes changed what the Ctors takes as argument, so breaking API)

**Comment by jmarrec** [comment]
* [ ] WaterHeaterHeatPump should be renamed to WaterHeaterHeatPumpPumped like the E+ class. It's  confusing. I aways have to check whether WaterHeaterHeatPumpPumped (no) and WaterHeaterHeatPumpWrapped (yes) are implemented to know which it is
* [ ] WaterHeaterHeatPump(Pumped) availablity schedule shouldn't be optional but default to always On

**Comment by jmarrec** [comment]
* [ ] Low temperature objects (`ZoneHVACLowTempRadiantVarFlow`, `ZoneHVACLowTempRadiantConstFlow` and `ZoneHVACLowTemperatureElectric`) should probably just default the Radiant Surface Type to "Ceilings" the Ctor and make `radiantSurfaceType()` return a non optional string instead of relying on IDD default  anyways (at least the `ZoneHVACLowTempRadiantVarFlow` is already NOT providing `isRadiantSurfaceDefaulted()` but are providing `resetRadiantSurfaceType()` though).

**Comment by jmarrec** [comment]
* #3870 : unique-object `OS:ClimateZones` should perhaps become `OS:ClimateZone`, non unique, with potentially CEC/ASHRAE specific getters for the underlying model object if we want to enforce unicity for these two. **This is a very low priority item given how much/for what it's actually used**

**Comment by jmarrec** [comment]
* [ ] AirLoopHVAC:UnitarySystem. Change name of field `DOAS DX Cooling Coil Leaving Minimum Air Temperature` to `Minimum Supply Air Temperature` to match E+


```
# OpenStudio.idd
  N2,  \field DOAS DX Cooling Coil Leaving Minimum Air Temperature
# EnergyPlus
  N2 , \field Minimum Supply Air Temperature
       \type real
       \units C
       \minimum 0.0
       \maximum 20.0
       \default 2.0
       \autosizable
       \note When Use DOAS DX Cooling Coil is specified as Yes, Minimum Supply Air Temperature
       \note defines the minimum DOAS DX cooling coil leaving air temperature that should
       \note be maintained to avoid frost formation. This field is not autosizable when
       \note the input for Use DOAS DX Cooling Coil = Yes.
```

**Comment by tijcolem** [comment]
@jmarrec 3.0.0 has been released so I'd like to close this issue. If there is anything worth keeping in here can we open new issues for these? Otherwise, let's just close.
