### ISSUE TITLE
As a user, I want the gbXML import to store the id attribute of each element so I can retrieve elements imported from the gbXML translator

### ISSUE THREAD

**Issue by pflaumingo** [NREL/OpenStudio#3554]
At times it is desired to be able to append information to elements that are stored in the gbXML, but not translated by the gbXML translator. An example could simply be a different opinion on how the translation occurs for a property. Currently the only way to retrieve elements is by name and there is no guarantee that the name is unique or that it is supported (sometimes OpenStudio translates characters such as commas). In order to be able to consistently retrieve desired elements, it would be good to store the id attribute of each gbXML element.

**Comment by macumber** [comment]
Thinking to use an additional property named "gbxml_id"

**Comment by pflaumingo** [comment]
Some objects such as spaces are translated with and "id" feature added to additional properties (ThermalZones). Although the gbXML schema doesn't seem to state that the id attribute has to be unique, I believe most vendors would/should use it as such.

**Comment by macumber** [comment]
Would it break anything for you if I moved "id" to a more descriptive attribute like "gbXMLId"?

**Comment by pflaumingo** [comment]
Nothing that couldn't be fixed easily
