### ISSUE TITLE
As a user, I want the gbXML import to store the CADObjectId element value of each element so I can map data back to the CAD/BIM environment

### ISSUE THREAD

**Issue by pflaumingo** [NREL/OpenStudio#3555]
This is required in addition to storing IDs because often the mapping from BIM/CAD to gbXML isn't one to one. For example, a single wall in BIM may be triangulated on export to gbXML and therefore be represented by multiple walls. When mapping back to the CAD/BIM environment it may be necessary to fetch all objects of a specific CADObjectId and transform the data (i.e. sum them) to get the desired result.

**Comment by macumber** [comment]
Thinking to use an additional property named "CADObjectId"

**Comment by pflaumingo** [comment]
I should note this is what is used with some objects currently (i.e. ThermalZones), but it'd be helpful to have it on other objects such as surfaces.

**Comment by macumber** [comment]
In schema version 6.01, CADObjectId can be an array of ids.  Is this ever used?  One OSM object relates to multiple CAD objects?

**Comment by pflaumingo** [comment]
I can't think of a time I've used it, but I could see it being possible. Would we split it as multiple additional properties? Or store it as one string with some separator?

**Comment by macumber** [comment]
Here's a list of issues to discuss:

- I've imported CADObjectId where it is allowed in the v6.01 schema
- I am importing id attribute from all objects as gbXMLId
- The schema allows for an array of CADObjectId, I am only importing the first one if any exist
    - CADObjectId has an optional programIdRef attribute, I think the idea is that a given element might have CADObjectId in multiple programs.  I am importing this as a separate programIdRef attribute if it exists, but only for the first CADObjectId.  Also, I am not traversing the document to find the Program name.
- I am applying the same CADObjectId and gbXML id to reversed surfaces and subsurfaces, I am adding an additional gbXMLReversed attribute to reversed surfaces (that way we can tell which one is reversed.
