### ISSUE TITLE
Windows Ruby 2.2.4 doesn't support running ruby from a directory that contains non-ascii characters

### ISSUE THREAD

**Issue by pflaumingo** [NREL/OpenStudio#3556]
This problem arises for international users that may have a user directory with non-ascii characters in it. Sometimes users may not have the ability to change the directory they are running the analysis from.

**Comment by jmarrec** [comment]
What version was this tested with? Was it tested with 2.9.0?

Related:

* https://github.com/NREL/OpenStudio/pull/3207
* https://github.com/NREL/OpenStudio/pull/3515

**Comment by jmarrec** [comment]
@pflaumingo I'm closing this. If you can supply info that allows me to reproduce, then go ahead and reopen. thanks!
