### ISSUE TITLE
Transfer conan distribution to OpenStudio org on bincrafters

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3559]

**Comment by tijcolem** [comment]
The bintray repo has been set up to store openstudio conan artifacts. 

https://api.bintray.com/conan/commercialbuilding/openstudio 

Travis and appveyor have been enabled to build https://github.com/NREL/conan-openstudio-ruby
Test runs were successful.  Now looking into adding encryption to securely upload conan builds to bintray.

**Comment by tijcolem** [comment]
This is done for both Travis and Appveyor.  
PR - https://github.com/NREL/conan-openstudio-ruby/pull/6

**Comment by jmarrec** [comment]
Confirmed good to go https://bintray.com/beta/#/commercialbuilding/nrel/openstudio_ruby:nrel?tab=overview

**Comment by jmarrec** [comment]
Confirmed good to go https://bintray.com/beta/#/commercialbuilding/nrel/openstudio_ruby:nrel?tab=overview
