### ISSUE TITLE
Getting the last OpenStudio model from runner doesn't work for post-processing measures

### ISSUE THREAD

**Issue by pflaumingo** [NREL/OpenStudio#3563]
Using OpenStudio 2.8.0 and running the following code snippet just returns a Model.new object when running post-processing measures only from the command line. It works fine when doing a full run.

```ruby
    model = runner.lastOpenStudioModel
    if model.empty?
      runner.registerError('Cannot find last model.')
      return false
    end
    model = model.get
    puts model
```

**Comment by DavidGoldwasser** [comment]
@pflaumingo I have always had to call this extra setup code for that to work in reporting measures.
https://github.com/NREL/OpenStudio-measures/blob/develop/lib/os_lib_reporting.rb#L41-L75

**Comment by jmarrec** [comment]
Tested in 2.9.0 by creating a "default" ReportingMeasure and adding just one line
```
    model = runner.lastOpenStudioModel
    if model.empty?
      runner.registerError('Cannot find last model.')
      return false
    end
    model = model.get
    puts "Model has #{model.objects.size} objects"
```

```
(py38)julien@test (master *%=)$ /bin/rm out.osw
(py38)julien@test (master *%=)$ cat workflow.osw 
{
   "created_at" : "20191125T135603Z",
   "seed_file" : "../test.osm",
   "steps" : [
      {
         "arguments" : {},
         "description" : "test for #3563",
         "measure_dir_name" : "Issue3563LastOpenStudioModel",
         "modeler_description" : "Replace this text with an explanation for the energy modeler specifically.  It should explain how the measure is modeled, including any requirements about how the baseline model must be set up, major assumptions, citations of references to applicable modeling resources, etc.  The energy modeler should be able to read this description and understand what changes the measure is making to the model and why these changes are being made.  Because the Modeler Description is written for an expert audience, using common abbreviations for brevity is good practice.",
         "name" : "Issue_3563_LastOpenStudioModel"
      }
   ],
   "updated_at" : "20191125T135806Z",
   "weather_file" : "USA_CO_Golden-NREL.724666_TMY3.epw"
}
(py38)julien@test (master *%=)$ openstudio run -p -w workflow.osw

(py38)julien@test (master *%=)$ grep objects out.osw
out.osw:40:            "step_info" : [ "Model has 298 objects", "Found timeseries." ],
```


This works fine, as I expected by looking at the OpenStudio-workflow-gem, it seems that run_initialization.rb should do the right thing.

Could you please try again in 2.9.0 @pflaumingo? 
Also, can you make sure that your path to the seed file is right and you aren't hitting this line?

https://github.com/NREL/OpenStudio-workflow-gem/blob/cf62056ec5701f2e20f196b941d96c46196cd282/lib/openstudio/workflow/jobs/run_initialization.rb#L130

**Comment by DavidGoldwasser** [comment]
A number of users have wanted to access the model in the arguments section of the reporting measures. That does appear to be a gap in functionality as neither the model, IDF, or runner are available in arguments method of reporting measure.

**Comment by jmarrec** [comment]
@DavidGoldwasser Moving your comment as an issue on https://github.com/NREL/OpenStudio-workflow-gem/issues/93

**Comment by jmarrec** [comment]
@pflaumingo I'm closing this one as I think it's fixed. Please reopen if you end up testing and it fails.
