### ISSUE TITLE
CoilWaterHeatingDesuperheater heating sources

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio#3564]
Should this list of possible heating sources be expanded to match what's in the energyplus idd? https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/CoilWaterHeatingDesuperheater.hpp#L155-L159

Should unit tests be expanded as well?

**Comment by shorowit** [comment]
Does https://github.com/NREL/OpenStudio/pull/3565 address this?

**Comment by joseph-robertson** [comment]
Yes: https://github.com/NREL/OpenStudio/pull/3565/files#diff-9777b13cb103632d702c9c2f8c774165R158-R162.
