### ISSUE TITLE
Changing the ShadowCalculation Method to TimestepFrequency

### ISSUE THREAD

**Issue by chriswmackey** [NREL/OpenStudio#3571]
I have searched pretty extensively through the OpenStudio SDK and through the issues posted on this github but I can't find any documentation showing how to change the Calculation Method on the `ShadowCalculation` object to be `TimestepFrequency` instead of the default `AverageOverDaysInFrequency`.

You can see here that the [SDK object for ShadowCalculation](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-2.2.0-doc/model/html/classopenstudio_1_1model_1_1_shadow_calculation.html) does not have any properties for CalculationMethod. 

Here is a screenshot showing the IDD field that I am hoping to edit from OpenStudio SDK:
![image](https://user-images.githubusercontent.com/5567574/59470676-75464c00-8e06-11e9-960b-38f4230bfa6c.png)

So that you know I am not the only one inquiring about this, here's a post from someone on our Ladybug forum asking about this:
https://discourse.ladybug.tools/t/shadow-calculation-method-editing-problem/6316

We apologize in advance if this is, in fact, exposed on the SDK and we have just been unable to locate it but we are fairly confident at this point that it is probably not yet exposed on the SDK. So we submit this issue as a feature request.

**Comment by macumber** [comment]
This will require adding a field in the OpenStudio idd and potentially adding version translation

**Comment by macumber** [comment]
Going to add the field to the end of the object so we don't have to do any version translation

**Comment by chriswmackey** [comment]
Thank, @macumber .  That would be perfect.
