### ISSUE TITLE
Use conan to build all Ruby extensions on all platforms

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3573]
Should not have to use homebrew.  Is it still ok to rely on apt?

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio/blob/develop3/CMakeLists.txt#L653

As of today, there are no `ADDITIONAL_RUBY_LIBS` passed on mac anymore. We have trouble with the readline one which doesn't support static on mac and need to figure out what to do (ship the dylib, or modify conan readline to allow static on mac, cf https://github.com/NREL/conan-openstudio-ruby/issues/8#issuecomment-519963213)

On Unix, we're still passing QDBM, but it might not be necessary given some of the recent changes I've done to conan openstudio ruby (properly passing gdbm_compat). I'll test that.

On Windows, there's a long list of stuff that isn't from conan, cf https://github.com/NREL/conan-openstudio-ruby/issues/8

**Comment by macumber** [comment]
Depends on https://github.com/NREL/conan-openstudio-ruby/pull/16

Link against homebrew readline on Mac for now, new ticket to transfer that to conan
Get FFI and other extensions working on Windows

**Comment by jmarrec** [comment]
Progress:
* Linux is all conan (tested and removed qdbm)
* mac is all conan: I still need to get CI to build new binaries, was waiting for bincrafters to merge my conan-readline PR which they did yesterday, waiting for their CI to publish the new recipe. But tested that readline static works already
* windows is the remaning issue

**Comment by jmarrec** [comment]
This is done right?

**Comment by tijcolem** [comment]
@lefticus @jmarrec  Not sure where this was left but I assume that this either complete or we got as far as we can with Windows when building ruby ext gems?  If there are still remaining native gems to be built, I assume this ties in nicely with the recent request to use Visual Studio 2019 clang/llvm to build OpenStudio and associated ruby gems.

**Comment by tijcolem** [comment]
Moving to Milestone to 3.1.0 and keeping open for now.

**Comment by lefticus** [comment]
It's been a rather long time since I looked at this, but last I knew everything that could work did so far.

**Comment by jmarrec** [comment]
I consider this achieved. There are a couple of things I wished worked the same on windows as it does on *nix and it can be seen on https://github.com/NREL/conan-openstudio-ruby/blob/master/conanfile.py#L34 and following

**Comment by tijcolem** [comment]
Closing this issue as I believe we got as far as we can.
