### ISSUE TITLE
Shading height is set to 80 ft but the height of the shading is the height of only one story

### ISSUE THREAD

**Issue by antonszilasi** [NREL/OpenStudio#3589]
Shading height is set to 80 ft but the height of the shading is the height of only one story, 
see the floor js json here: https://drive.google.com/file/d/1srbSWQeqPscuunlv1zAX4MJBByWIvcRl/view?usp=sharing

Here is a picture of the osm import: 
![shadingIssueDan](https://user-images.githubusercontent.com/8773483/60917595-9310a080-a24e-11e9-82f6-23a11eb416fd.jpg)

**Comment by macumber** [comment]
This error is actually in the FloorspaceJS JSON, the shading object field `floor_to_ceiling_height` is set to "80" which is a string, it should be 80 which is numeric.

@bgschiller FYI

**Comment by macumber** [comment]
![image](https://user-images.githubusercontent.com/1327850/61019640-271a5f00-a358-11e9-96b3-c3006d91f0fc.png)

**Comment by antonszilasi** [comment]
@macumber thanks for seeing this, you are right we'll get out floor js jsons written out as numbers now 
instead of strings.
