### ISSUE TITLE
Point develop3 to NREL bincrafters for OpenStudio Ruby

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3592]
https://github.com/NREL/OpenStudio/blob/develop3/ConanInstall.cmake#L83 should be https://bintray.com/commercialbuilding/openstudio/openstudio_ruby%3Aopenstudio/2.5.5-4c07d68b72%3Atesting

**Comment by macumber** [comment]
Or should we have merge to master push to a latest tag?

**Comment by jmarrec** [comment]
Fixed via #3596, reverted temporarily, but now added back in https://github.com/NREL/OpenStudio/commit/f238cefd76b92b2839ff49feca2efe2596c84fe1 and tested that works
