### ISSUE TITLE
If you attempt to run simulation with SQL file open it fails even after closing SQL and re-trying (Bugzilla #271)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#36]
On 2011-09-25 23:15:21, @DavidGoldwasser wrote:

> This is an old bug I thought was fixed, but may have come back. Not something we need to fix for 0.5.0

On 2011-11-16 09:50:35, @DavidGoldwasser wrote:

> <batch change comment> Moving older bugs to "retest" milestone. Will re-test these and then assign to appropriate milestone. These were all 0.6.0 prior to change.

On 2011-12-01 12:01:56, @macumber wrote:

> To reproduce:
> 
> 1) run energyplus simulation with sqlite output
> 2) open sqlite file in OpenStudio ResultsViewer
> 3) rerun energyplus, it will fail as expected
> 4) close ResultsViewer
> 5) rerun energyplus, it will continue failing, this is the bug

On 2012-01-13 15:22:00, @DavidGoldwasser wrote:

> Updated out of date Milestone Targer

On 2012-12-17 12:25:53, @DavidGoldwasser wrote:

> This isn't valid for the SketchUp Plugin, I'm going to remove from release notes, but still leave open and Assign to OS app, as I think this is still an issue, but maybe not as bad because we are using temp files. I'll retest sometime after 0.10.0 is out.

Keywords: ReleaseNotes

**Comment by DavidGoldwasser** [comment]
Still valid bug

**Comment by jmarrec** [comment]
Is it still a valid bug? Does DView make the same mistake as ResultsViewer (in the old days at least) of opening the file in write mode instead of read only?

**Comment by DavidGoldwasser** [comment]
@kbenne do you know if DView has same issue? If nobody knows we can test, but I haven't had a chance to yet.

**Comment by evanweaver** [comment]
Previously fixed.
