### ISSUE TITLE
If you change the name of a measure, but not any inputs, the old name still shows on tab 3 and 4 (Bugzilla #1297)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#360]
On 2013-06-26 12:05:31, @DavidGoldwasser wrote:

> Steps to recreate
> 
> 1. Make a pat project with baseline loaded and then add measures and make design alternative.
> 
> 2. Run the simulation (this step may not be necessary, but in my testing that is what I did)
> 
> 3. Go back to Tab 1 and rename a measure without changing any inputs.
> 
> 4. If you go to Tab 2 you will see the new name (only in the left pane). The right pane shows the old name.
> 
> 5. If you go to tab 3 or 4 you will still see the old name.
> 
> 6. Changing an input didn't fix this either.
> 
> 6. If you go to tab 2 make a new design alternative it uses the new name
> 
> Andrew, I thought this may affect edits to the description as well as the name, but I can't tell for sure in the GUI.
> 
> I assume this is a fix to do post release vs. before.

**Comment by macumber** [comment]
This appears to be fixed in 1.8.0
