### ISSUE TITLE
Chiller:Electric:EIR API related to node need a serious refactor

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#3606]
None of these should exist, especially not in the public header (`ChillerElectricEIR.hpp`):

```c++
  bool setChilledWaterInletNodeName(std::string chilledWaterInletNodeName);
  bool setChilledWaterOutletNodeName(std::string chilledWaterOutletNodeName);

  bool setCondenserInletNodeName(boost::optional<std::string> condenserInletNodeName);
  bool setCondenserInletNodeName(std::string condenserInletNodeName);
  void resetCondenserInletNodeName();

  bool setCondenserOutletNodeName(boost::optional<std::string> condenserOutletNodeName);
  bool setCondenserOutletNodeName(std::string condenserOutletNodeName);
  void resetCondenserOutletNodeName();

  bool setHeatRecoveryInletNodeName(boost::optional<std::string> heatRecoveryInletNodeName);
  bool setHeatRecoveryInletNodeName(std::string heatRecoveryInletNodeName);
  void resetHeatRecoveryInletNodeName();

  bool setHeatRecoveryOutletNodeName(boost::optional<std::string> heatRecoveryOutletNodeName);
  bool setHeatRecoveryOutletNodeName(std::string heatRecoveryOutletNodeName);
  void resetHeatRecoveryOutletNodeName();
```

All of these plant loop connections are supposed to be set using addToNode / addToTertiaryNode.

ChillerElectricEIR::addToNode should probably be overloaded to do something like what I've done for CentralHeatPumpSystem:

https://github.com/NREL/OpenStudio/blob/5dc8c4e966066dcbeffddfb0ae1f9a65d84536c5/src/model/CentralHeatPumpSystem.cpp#L194-L221

@eringold can give you a MCVE of a ruby script that produces a hard crash

**Comment by eringold** [comment]
```
m = OpenStudio::Model::Model.new

chiller = OpenStudio::Model::ChillerElectricEIR.new(m)

puts chiller

node = OpenStudio::Model::Node.new(m)

chiller.setHeatRecoveryInletNodeName(node.name.get)

puts chiller

chiller.setHeatRecoveryOutletNodeName(node.name.get)

puts chiller
```

The above will not hard crash, but will print:

    [BOOST_ASSERT] <2> Assertion result failed on line 665 of bool __cdecl openstudio::model::detail::ChillerElectricEIR_Impl::setHeatRecoveryInletNodeName(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >) in file C:\Users\jenkins\git\OpenStudio\openstudiocore\src\model\ChillerElectricEIR.cpp.

and 

    [BOOST_ASSERT] <2> Assertion result failed on line 685 of bool __cdecl openstudio::model::detail::ChillerElectricEIR_Impl::setHeatRecoveryOutletNodeName(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >) in file C:\Users\jenkins\git\OpenStudio\openstudiocore\src\model\ChillerElectricEIR.cpp.

and otherwise do nothing to the chiller.

**Comment by jmarrec** [comment]
Related to the tertiary node: https://github.com/NREL/OpenStudio/issues/3111
