### ISSUE TITLE
Schedule CSV written in measure is not found

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3609]
Users are having issues with CSV files generated by measures.  Users tend to write these in the measure directory which can lead to trouble.  Need to have good example measure with tests in several contexts (CLI, App, PAT, openstudio-resources)

**Comment by macumber** [comment]
Measure should do something simple like write a CSV file and associate it with a load

**Comment by macumber** [comment]
@mleachNREL thanks for the report

**Comment by jmarrec** [comment]
@macumber Where would that measure output the CSV to? The model companion folder? If so, under which folder, resources?

**Comment by macumber** [comment]
@jmarrec I think there are a couple of answers here.  When a measure writes a file, it should write it to the current working directory.  However, if the measure then creates a ScheduleFile to add to the model, the CSV file will be moved when you create the ExternalFile.  The code in [ExternalFile](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/ExternalFile.cpp#L230) moves CSV files to the first path in the WorkflowJSON's files list.

I just added this code to the Workflow gem to add a generated files folder at the first index so all ExternalFiles added by measures in a simulation go there.  Otherwise, we were getting files added back in shared resource directories which was not good for multiple runs referencing the same shared dirs.  https://github.com/NREL/OpenStudio-workflow-gem/pull/88/files#diff-96bc621ae550711d9461f358341b833dR88

We might need something similar to the temporary OSW used in ApplyMeasureNow, https://github.com/NREL/OpenStudio/blob/e077c7edfa6c94bb37aeb0e31f40b69ed2740223/openstudiocore/src/openstudio_lib/ApplyMeasureNowDialog.cpp#L107

**Comment by macumber** [comment]
Really this ticket is a documentation update.  We need an example measure for the CSVFile (which is a form of documentation).  We also should add a section on the measure writers guide about how to import files in a measure (from file paths) and how to write files in a measure (measures should write all files to the current working directory or the generated files path).

**Comment by jmarrec** [comment]
Will be fixed by
https://github.com/NREL/OpenStudio-user-documentation/pull/25

Related issue: https://github.com/NREL/OpenStudio/issues/4046
