### ISSUE TITLE
Tab 2 - Order of design alternatives made using "Create One For Each Selected Measure" can be odd (Bugzilla #1298)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#361]
On 2013-06-26 12:15:23, @DavidGoldwasser wrote:

> On a new project I'm used to seeing the design alternatives made in the same order of the OpenStudio measures.
> 
> I was working on a project where I deleted all of the design alternatives and edited a few measures in my second of 4 measure groups. When I re-made the design alternatives using the "Create One For Each Selected Measure".
> 
> The first three design alternatives are now group 2 measures and they order of them are not in the same order as shown in tab one and the left pane of tab 2. Maybe in order I lasted edited them? or maybe not.
> 
> The rest of the design alternatives are from measure groups 1, then 3, and then 4. Within each group they match the original order.
> 
> <update>
> Just for fun, I did some more.
> 1. delete all design alternatives
> 2. save project and quit PAT
> 3. Start PAT and load project
> 4. Go to tab 2, select all measures and click "Create One For Each Selected Measures".
> 
> This time they are back in the expected order (matching Tab 1 and left pane of Tab 2)

**Comment by macumber** [comment]
@kflemin should this be moved to PAT repo?

**Comment by kflemin** [comment]
Closing...this is really old and refers to PAT 1.
