### ISSUE TITLE
Create CSVFile class

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3611]

**Comment by joseph-robertson** [comment]
Notes:
* shouldn't need a new c++ csv library
* class would go in https://github.com/NREL/OpenStudio/tree/develop/openstudiocore/src/utilities/filetypes
* probably a constructor from file path to read a file, empty constructor for new file, save as method
* methods to get and set columns
* set of three files CSVFile.hpp, cpp, _Impl.hpp, with methods like read_external_file,write_external_file, something like that
