### ISSUE TITLE
OpenStudio Simulation crashes, Energyplus returns non-zero code

### ISSUE THREAD

**Issue by luisclv** [NREL/OpenStudio#3616]
**Platform: Windows 10
OS version: 2.8.0
Workstation Specs: i7-8750H & 64 GB RAM**

I can share the file privately if needed. The error appeared with the simulation files saved on a network location, it ran fine there until it didn't.

When running the simulation over the GUI, the simulation fails randomly. eplusout.err looks like it was stopped abruptly and does not indicate a _normal_ EnergyPlus error.

`   ** Warning ** In calculating the design coil UA for Coil:Cooling:Water CHW CLG COIL 15
   **   ~~~   ** the coil bypass factor is unrealistically large;
   **   ~~~   ** The initial design conditions are: Tair,in = 32.0000
   **   ~~~   **                                    Wair,in = 3.147510E-002
   **   ~~~   **              `

Moved the simulation to my local drive. Running the simulation using the CLI with the debug flag on returns the following:

`[13:24:00.242874 INFO] Running command '"C:\openstudio-2.8.0\EnergyPlus\ExpandObjects.exe"'
[13:24:00.535933 INFO] Running command '"C:\openstudio-2.8.0\EnergyPlus\energyplus.exe" 2>&1'
[13:24:14.134851 INFO] EnergyPlus returned 'pid 13952 SIGSEGV (signal 11)'
[13:24:14.134851 WARN] EnergyPlus returned a non-zero exit code. Check the stdout-energyplus log.
[13:24:14.136847 ERROR] :/ruby/2.2.0/gems/openstudio-workflow-1.3.3/lib/openstudio/workflow/util/energyplus.rb failed with EnergyPlus failed and did not create an eplusout.end file. Check the stdout-energyplus log., :/ruby/2.2.0/gems/openstudio-workflow-1.3.3/lib/openstudio/workflow/util/energyplus.rb:163:in 'call_energyplus'
:/ruby/2.2.0/gems/openstudio-workflow-1.3.3/lib/openstudio/workflow/jobs/run_energyplus.rb:44:in 'perform'
:/ruby/2.2.0/gems/openstudio-workflow-1.3.3/lib/openstudio/workflow/run.rb:269:in 'step'
:/ruby/2.2.0/gems/openstudio-workflow-1.3.3/lib/openstudio/workflow/run.rb:216:in 'run'
:/openstudio_cli.rb:937:in 'execute'
:/openstudio_cli.rb:726:in 'execute'
:/openstudio_cli.rb:1703:in '<main>'`

Running the in.idf file with my installed copy of EnergyPlus (not the one bundled with OpenStudio) runs fine.

**Comment by luisclv** [comment]
I traced the problem back to an Airloop. I have an Airloop connected to zones that have a multiplier of `11`. If I delete the Airloop, the simulation runs fine. If I add the Airloop back, the simulation crashes again. In both scenarios, running the .idf file with my local copy of EnergyPlus solves the issue.

**Comment by luisclv** [comment]
It looks like it is somehow related to the system airflow sizing. I added VRF equipment. If I leave it autosized, the simulation crashes again. Hard-sizing the airflows solves the issue.

**Comment by jmarrec** [comment]
@luisclv Are you sure you are using the exact same E+ build between the one OS used and your own local copy?

It does look very much like an E+ crash...

**Comment by jmarrec** [comment]
I'm closing, if it pops up again let us know.
