### ISSUE TITLE
Clear results doesn't always clear all results (Bugzilla #1299)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#362]
On 2013-06-26 14:24:36, @DavidGoldwasser wrote:

> I had a PAT project where I loaded external files and ran an analysis. Those seem to be stored under "alternatives" directory. After that run I added new measures which cleared out all design alternatives. Later when I ran again and then cleared results, the results from the original "alternatives" from the external files were still left.
> 
> Maybe those should have been deleted right when the design alternative was deleted. Unrelated, but I also noticed that measures that have been removed from the project remain behind.
> 
> I don't see this as something to fix for 1.0

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
