### ISSUE TITLE
Exposing the YearDescription in C# Bindings

### ISSUE THREAD

**Issue by chriswmackey** [NREL/OpenStudio#3621]
I believe that what I am submitting here is a feature request but it is totally possible that there is already a way to access what I am looking for and the several hours that I have spent trying to access it are instead the result of me being unable to understand the documentation or find any examples.

Specifically, I am trying to access the [YearDescription](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-2.8.0-doc/model/html/classopenstudio_1_1model_1_1_year_description.html) that is assigned to a given OpenStudio Model.  I have seen examples in Ruby of people being able to access the YearDescription as follows:

```
model = OpenStudio::Model::Model.new
yd = model.getYearDescription
yd.setIsLeapYear(true)
```

However, when I try to translate this over to my IronPython code where I am importing the OpenStudio C# bindings, I have the following code:

```
import clr
clr.AddReferenceToFileAndPath("C:/openstudio-2.8.0/CSharp/openstudio/openStudio.dll")
import OpenStudio

model = OpenStudio.Model()
yd = model.getYearDescription()
```
However this code gives me the following result:
`Runtime error (MissingMemberException): 'Model' object has no attribute 'getYearDescription'`

If I instead try the following code:
```
model = OpenStudio.Model()
yd = OpenStudio.Model.getYearDescription(model)
```
I get the following result:
`Runtime error (MissingMemberException): 'type' object has no attribute 'getYearDescription'`

Lastly when I try this code:
```
model = OpenStudio.Model()
yd = OpenStudio.OpenStudioModelSimulation.getYearDescription(model)
```
I am finally able to get something but it doesn't seem like it is a YearDecription because I cannot set the leap year on it and, when I print it, It looks like this:
```
<OpenStudio.SWIGTYPE_p_openstudio__model__YearDescription object at 0x000000000000009F [OpenStudio.SWIGTYPE_p_openstudio__model__YearDescription]>
```

So this has all lead me to believe that there is no way to access the model's YearDescription from the C# bindings.  This is a case where I would be very happy to be wrong but, if I am not, I would be interested in know if there's a reason why the YearDescription is not exposed in the C# bindings.

**Comment by macumber** [comment]
Thanks @chriswmackey can you call the following method on the OpenStudio Model class?

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/Model.hpp#L131

```
model = OpenStudio.Model()
yd = model.yearDescription()
```

**Comment by chriswmackey** [comment]
@macrumber ,
Trying that code, I get the following:
`Runtime error (MissingMemberException): 'Model' object has no attribute 'yearDescription'`
So I am afraid that one is not the solution.  

I should also note that I have tried the following code:
```
model = OpenStudio.Model()
OpenStudio.OpenStudioModelSimulation.getYearDescription(model)
yd = model.getObjectsByType(OpenStudio.IddObjectType("OS:YearDescription"))
```
... and I get an OpenStudio.WorkspaceObjectVector and, the first index [0] of the vector has a YearDescription object in there but it's not one that I can call the `setIsLeapYear` method for.

**Comment by macumber** [comment]
Here's the source:

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/ModelSimulation.i#L25

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/ModelSimulation.i#L81

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/ModelSimulation.i#L120

**Comment by macumber** [comment]
@chriswmackey would these convenience methods work for you, https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/Model.hpp#L135

You don't get access to the YearDescription object but can get at all of its data

**Comment by chriswmackey** [comment]
Thanks for digging into it, @macumber .  To clarify: does "getting access to the data" mean that this data can still be set/edited for a Model?  For example, will we be able to set the leap year for the simulation?  If so, that sounds fine to me.

**Comment by macumber** [comment]
Yes you can call ‘model.isLeapYear’ and ‘model.setLeapYear’

**Comment by chriswmackey** [comment]
Wonderful!  That should do it, then.
