### ISSUE TITLE
SpaceTypes missing from MyLibrary when in SpaceTypes tab

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#3625]
When in the space types tab and viewing "MyModel" in right pane "Space Types" are not visible. "Space Types" are visible when in "Library" they should be visible to drag into space type drop zone.

**Comment by macumber** [comment]
This might be intentional.  You can drag space types in from the library to clone into your model.  But if you drag a space type from my model in to space types, what happens?  Aren't the space types in the model visible in another list?

**Comment by jmarrec** [comment]
What Dan said. If you want to clone an existing SpaceType in your model, then use the "x2". 
If you go to the Thermal Zones tab, "My Model" won't present your with Thermal Zones either. If you go to Schedules Tab, same happens.

Closing as it works as expected.

**Comment by DavidGoldwasser** [comment]
Good point, agree, it shouldn't show.
