### ISSUE TITLE
Autodesk Revit 2020 + OpenStudio app

### ISSUE THREAD

**Issue by amagr0** [NREL/OpenStudio#3633]
Since Autodesk is using OpenStudio application through [Revit 2020](https://www.youtube.com/watch?v=aQ63HJ41X7A&t=3s), can we expect the continuity of the OpenStudio apllication?

[_Given the recent timing of this announcement, no entity or entities have yet announced specific plans to continue support for the OpenStudio Application after the transition period._
](https://www.openstudio.net/new-future-for-openstudio-application)

Is Autodesk that entity?

**Comment by tijcolem** [comment]
Autodesk is using the Openstudio SDK (Core) which will be supported and you can expect continuity of the SDK. OpenStudio Application will also be supported but it will be distributed as a separate application. This will take effect in April, 2020.  So both applications will be supported but on different release schedules and distribution channels. 

We recently released a pre-release of this SDK and App separation. Please refer to https://github.com/NREL/OpenStudio/releases/tag/v3.0.0-pre1 to understand what content will be provided in each distribution. This will become official in April 2020.
