### ISSUE TITLE
Add new Fields in AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass 

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#3639]
![image](https://user-images.githubusercontent.com/707488/63864432-743ca980-c975-11e9-9612-c9a206a1ba2e.png)

https://github.com/NREL/EnergyPlus/pull/7249

**Comment by jmarrec** [comment]
Cf https://github.com/NREL/EnergyPlus/pull/7249
