### ISSUE TITLE
E+ Change: Add support for supplemental heat to ZoneHVAC:TerminalUnit:VariableRefrigerantFlow

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#3645]
Consider adding new feature for optional supplemental heat. ignore for now. or add as time allows but consider this a new feature not a requirement of version update. (at least thats how i treat these types of things).

If you defer the handling of this feature that is fine, just remove it from the milestone.

**Comment by jmarrec** [comment]
I've got no clue what this is referring to. 

I've looked a the E+ 9.1.0 IDD, the 9.2.0 IDD, the 2.8.0 OS IDD and the current OS IDD. I see no change, and no missing fields on OS's side compared to E+. I can't pinpoint what this "new feature for optional supplemental heat" is?

@joseph-robertson @tijcolem Do you know what kyle is referring to?

**Comment by kbenne** [comment]
@jmarrec I think I referenced the wrong object. It should be ZoneHVAC:TerminalUnit:VariableRefrigerantFlow which has added a supplemental coil option. I changed the title of this issue.
