### ISSUE TITLE
E+ Change: AirLoopHVAC:UnitaryHeatCool:VAVChangeoverBypass

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#3648]
There is a new enum on Priority Control Node field. that is easy just bring over the new enum. The other change is a node that has to be referrenced if the system involves plenums. This needs research because i don't fully understand the change. I say if the unitary was not allowed with a plenum system before, then just ignore the new field and consider that a new feature for a later date.

**Comment by kbenne** [comment]
Update. there is an important request for some of these new fields in this object. see here... 

https://github.com/NREL/OpenStudio/issues/3639

@jmarrec it is important to close #3639 before the 2.9.0 release.

**Comment by jmarrec** [comment]
Closing as duplicate of #3639
