### ISSUE TITLE
E+ Change: Pump:VariableSpeed

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#3649]
There is a change to units so check that out and bring the new units over if they are correct in the context of the OS IDD. The other change is just a case change so i would ignore that because it will only server to mess up OS API

**Comment by jmarrec** [comment]
![image](https://user-images.githubusercontent.com/5479063/64183505-45896c00-ce6a-11e9-8632-03f548054ac6.png)

**Comment by jmarrec** [comment]
Fixed via #3661
