### ISSUE TITLE
E+ Change: Table:MultiVariableLookup

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#3651]
Have fun. I would not change the OS api or idd at all. Do it all in idf translator. It has to be possible if EnergyPlus is able to version translate. I think our OS API is pretty good.

**Comment by macumber** [comment]
Looks like this translator is going to need to write a CSVFile, good timing @joseph-robertson :-)

**Comment by macumber** [comment]
Oh never mind, the CSVFile is optional.  Would be a good option for later.
