### ISSUE TITLE
Fix ThermalStorageIceDetailed Forward Translator

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3654]
Need to fix this on the energyplus_9_2_idd_proposed branch https://github.com/NREL/OpenStudio/pull/3640/files#diff-4d0a7e22d316a3aff08b1a18a47dd6d4R95

**Comment by jmarrec** [comment]
E+ transition code is here: https://github.com/NREL/EnergyPlus/pull/7339/commits/941a6703227fe716e9133c5d3c48b06c5f4ce4aa#diff-6bcecd46a03668bc5e9998616e6e8066R476
