### ISSUE TITLE
Fix regression test errors

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3656]
Fix tests on https://github.com/NREL/OpenStudio-resources/tree/everybody_merge_now using https://github.com/NREL/OpenStudio/pull/3655.  Put your name next to issue when you start looking at that test

- [x] test_ems_scott_osm 
- [x] test_coil_waterheating_desuperheater_rb - JM: Fixed on https://github.com/NREL/OpenStudio-resources/pull/71
- [x] test_coil_waterheating_desuperheater_osm - JM: Deleted, shouldn't exist before 2.9.0 official
- [x] test_airterminal_fourpipebeam_rb
- [x] test_airterminal_fourpipebeam_osm
- [x] test_scheduled_infiltration_osm - Dan will look at
- [x] test_thermal_storage_rb - Julien: fixed with https://github.com/NREL/OpenStudio/pull/3667
- [x] test_thermal_storage_osm - Julien: fixed by https://github.com/NREL/OpenStudio/pull/3667
- [x] test_zone_hvac_equipment_list_rb - Julien: fixed by https://github.com/NREL/OpenStudio/pull/3667
- [x] test_zone_hvac_equipment_list_osm - Joe: Deleted, similar to coil_waterheating_desuperheater
- [x] test_autosizing_rb
- [x] test_schedule_fixed_interval_osm: JM - deleted OSM until official
- [x] test_schedule_fixed_interval_2_osm: JM - deleted OSM until official

**Comment by macumber** [comment]
@joseph-robertson can you look at the  test_zone_hvac_equipment_list failures?

**Comment by macumber** [comment]
I just made a commit that should fix several of these, I will update the list once tests run

**Comment by jmarrec** [comment]
`test_thermal_storage_rb` and `test_thermal_storage_osm` are failing because the ProposedEnergy+.idd won't allow the ThermalStorage:Ice:Detailed on a PlantEquipmentList.

here's the 2.8.1 ProposedEnergy+.idd

```
ThermalStorage:Ice:Detailed,
    \min-fields 14
       \memo This input syntax is intended to describe a thermal storage system that
       \memo includes smaller containers filled with water that are placed in a larger
       \memo tank or series of tanks.
       \memo The model uses polynomial equations to describe the system performance.
  A1 , \field Name
       \required-field
       \reference IceThermalStorageEquipment
       \reference-class-name validBranchEquipmentTypes
       \reference validBranchEquipmentNames
       \reference-class-name validPlantEquipmentTypes  ! remove?
       \reference validPlantEquipmentNames  ! remove?
  A2 , \field Availability Schedule Name
```

**Comment by jmarrec** [comment]
Added `test_schedule_fixed_interval_osm` and `test_schedule_fixed_interval_2_osm` which are currently failing
