### ISSUE TITLE
Fix unit test EnergyPlusFixture.ForwardReverseTranslatorActuator_EMS

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3658]
Work on everybody_merge_now branch https://github.com/NREL/OpenStudio/pull/3655

**Comment by brianlball** [comment]
attached fan to an airloop.  looks like it got removed in the FT if it was not attached.
https://github.com/NREL/OpenStudio/commit/390e6cca51b1e289d448c91588c9f2b62ee9ea94
