### ISSUE TITLE
Fix ModelFixture.ZoneHVACEquipmentList_Logic

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3662]
@joseph-robertson this test is failing on the `everybody_merge_now` branch.  I had to make a few changes to ZoneHVACEquipmentList.cpp because it was hard crashing on some of our unit tests.  Can you fix this test failure on the `everybody_merge_now` branch?

https://github.com/NREL/OpenStudio/pull/3655/commits/6cd0f5fcb464b7d6e62c3abcd47873bb1f69eec5

**Comment by joseph-robertson** [comment]
Fixed in 78cd8af.
