### ISSUE TITLE
Wrap ZoneProperty:UserViewFactors:bySurfaceName object

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#3664]
https://bigladdersoftware.com/epx/docs/9-1/input-output-reference/group-advanced-surface-concepts.html#zonepropertyuserviewfactorsbysurfacename

@yzhou601 Can you attach one of your IDF files that uses this object?

**Comment by yzhou601** [comment]
Sure, [GoogleDriveLinkToSampleFile](https://drive.google.com/file/d/1E67NgfPgLcMremXfvchEML42sw1NZ94E/view?usp=sharing).

**Comment by joseph-robertson** [comment]
Design doc: https://docs.google.com/document/d/1P8O6GRQAZda5kK_2Qu2CJRkBGUxTIhJwvJ0-JNpTU1A/edit#heading=h.c285d1mdhew5

TODO:
- [ ] Fill out design doc
- [ ] Get design doc review
