### ISSUE TITLE
AirLoopHVAC:UnitarySystem doesn't default Fan Placement=BlowThrough anymore

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio#3665]
Leads to no FT of Fan Placement, and then energyplus error.

**Comment by jmarrec** [comment]
I can't find anything that shows that this behavior actually changed. It was always the case.

**Comment by joseph-robertson** [comment]
Interesting. Well, I think we can close this then.

**Comment by jmarrec** [comment]
Will do once I confirm that #3667 actually fixes this.
