### ISSUE TITLE
Ruby load paths not correctly initialized in PAT or OS app (Bugzilla #1307)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#368]
On 2013-06-28 13:16:36, @macumber wrote:

> See forum post https://openstudio.nrel.gov/forums/openstudio-plug-sketchup/help-desk/using-ruby-libs-user-script
> 
> You can do 'require "net/http"' in the run method but not inside the arguments method.

**Comment by macumber** [comment]
Tested and closed, used the following code in name, arguments, and run sections:

    require "net/http"
    p = Net::HTTP.get('www.example.com', '/index.html') # => String
    md = /<title>(.*)<\/title>/.match(p)
