### ISSUE TITLE
rb_data_object_alloc is undefined

### ISSUE THREAD

**Issue by eshadd** [NREL/OpenStudio#3682]
When I run the OpenStudio CLI v2.8.0 in Ubuntu LTS 16.04 I get the following error:

`/usr/local/openstudio-2.8.0/Ruby/openstudio.so: undefined symbol: rb_data_object_alloc`

the **Installation Notes** [here ](https://github.com/NREL/OpenStudio/releases/tag/v2.8.0) say OS is compatible with Ubuntu 16.04 but OpenStudio uses Ruby 2.2.4 whereas Ubuntu LTS 16.04 uses Ruby 2.3 and rb_data_object_alloc is deprecated in Ruby 2.3.

I do have Ruby 2.2.4 installed on my machine. If I run that version of Ruby directly with:

`/home/eshadd/.rvm/rubies/ruby-2.2.4/bin/ruby`

OS CLI seems to run fine and get results but also displays the following warnings:

```
:/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/version.rb:4: warning: already initialized constant JSON::VERSION
:/ruby/2.2.0/json/version.rb:3: warning: previous definition of VERSION was here
:/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/version.rb:5: warning: already initialized constant JSON::VERSION_ARRAY
:/ruby/2.2.0/json/version.rb:4: warning: previous definition of VERSION_ARRAY was here
:/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/version.rb:6: warning: already initialized constant JSON::VERSION_MAJOR
:/ruby/2.2.0/json/version.rb:5: warning: previous definition of VERSION_MAJOR was here
:/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/version.rb:7: warning: already initialized constant JSON::VERSION_MINOR
:/ruby/2.2.0/json/version.rb:6: warning: previous definition of VERSION_MINOR was here
:/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/version.rb:8: warning: already initialized constant JSON::VERSION_BUILD
:/ruby/2.2.0/json/version.rb:7: warning: previous definition of VERSION_BUILD was here
:/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/common.rb:100: warning: already initialized constant JSON::NaN
:/ruby/2.2.0/json/common.rb:99: warning: previous definition of NaN was here
:/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/common.rb:102: warning: already initialized constant JSON::Infinity
:/ruby/2.2.0/json/common.rb:101: warning: previous definition of Infinity was here
:/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/common.rb:104: warning: already initialized constant JSON::MinusInfinity
:/ruby/2.2.0/json/common.rb:103: warning: previous definition of MinusInfinity was here
:/ruby/2.2.0/gems/json_pure-2.2.0/lib/json/common.rb:129: warning: already initialized constant JSON::UnparserError
:/ruby/2.2.0/json/common.rb:128: warning: previous definition of UnparserError was here
```

I did have RVM installed prior to upgrading to 16.04 from 14.04 but it's not functional now and I'd rather not re-install it because I recall that there were still incompatibilities with the system vs. OS Ruby that I had to find workarounds for.

**Comment by eshadd** [comment]
This [issue ](https://github.com/NREL/OpenStudio/issues/3545) is related but my issue is more about Ubuntu's Ruby 2.3 vs. OS Ruby 2.2.0 causing the `undefined symbol: rb_data_object_alloc `error.

**Comment by jmarrec** [comment]
The compatibility matrix is really explicit : https://github.com/NREL/OpenStudio/wiki/OpenStudio-Version-Compatibility-Matrix

We support Ruby 2.2.4. In pratice you can actually use any Ruby 2.2.x (I have tested with 2.2.7 and 2.2.10 personally). Ruby 2.3 isn't supported, period.

The warnings you are seeing are annoying but can be ignored.

Also, what you seem to be doing is loading the ruby bindings in your local ruby installation. If you use the CLI, it is self contained (ruby is bundled inside). So `openstudio my_script.rb` for eg will work on any platform.

**Comment by eshadd** [comment]
I'm calling the CLI with my own version of [this ](https://github.com/UnmetHours/openstudio-scripts/tree/master/OpenStudio_CLI_Template ) CLI template. It runs workflows with the line `openstudio run -w workflow.json`. I assume this would also run the CLI's bundled ruby? Maybe Linux/Ubuntu LTS is handling which ruby is implemented differently than expected.
