### ISSUE TITLE
Forward translate to epJSON

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#3685]
Eventually epJSON will replace IDF. And it should be faster?

**Comment by theo-armour** [comment]
@shorowit 

Do you know  the location of any epJSON sample files? I am interested in building a viewer for epJSON files.

**Comment by shorowit** [comment]
@theo-armour I'm not aware of a repository of them, but you can take any IDF file (e.g., those in the E+ ExampleFiles dir) and run  `energyplus -c file.idf` to create the equivalent file.epJSON. Note that it will also try to run the simulation though, and there's no way to disable that. But you can simply cause the simulation to error out (e.g., invalid weather file) or reduce the run period to get the JSON out faster.

**Comment by kbenne** [comment]
@lefticus. I think we might want finer grain tracking on this feature, but lets work from this top level GitHub issue as we develop an epJSON API in OpenStudio.

**Comment by lefticus** [comment]
Work is commencing on this branch https://github.com/NREL/OpenStudio/tree/epjson_support

Sorry, I forgot to reference this issue #

**Comment by lefticus** [comment]
63c1a22104735dd6e90a2dcaba984c800955640e has working conversions to epJSON, validated against EnergyPlus's output. Some work still needs to be done for error handling and cleaning up the API a bit, providing convenience functions and testing the Ruby API version.

**Comment by theo-armour** [comment]
@lefticus 

Thanks for the update.

I seem to have lost where the epJSON effort is being discussed and promulgated.

Can you kindly remind me?
