### ISSUE TITLE
Openstudio 2.8.1 crashing after clean install ("Measure Manager has crashed")

### ISSUE THREAD

**Issue by JanghyunJK** [NREL/OpenStudio#3686]
- I have Windows 10
- with EnergyPlus 9.1
- was trying OpenStudio 2.8.1 (deleted all other versions after seeing this issue)

First time using 2.8.1 (previously using 2.4.1 mostly and 2.7.0 for shortly), and I'm getting this error below when I start OpenStudioApp.exe. And it keep pops up even if I click OK button. Tried uninstalling/reinstalling everything. Hope I could get some quick advice on fixing this!

![error1](https://user-images.githubusercontent.com/26775789/65449084-74568a80-ddf7-11e9-9c0d-945232654103.PNG)

![error2](https://user-images.githubusercontent.com/26775789/65449094-79b3d500-ddf7-11e9-847f-5c5a982b9705.PNG)

**Comment by tijcolem** [comment]
I would try and remove all other previous OpenStudio installations via the Windows uninstall utility. It looks like it's a shared .dll that might be leftover from a previous install that is causing the issue. If the shared .dll are not being uninstalled, you may need to remove manually. but let's try simple uninstall first before attempting that.

**Comment by JanghyunJK** [comment]
@tijcolem 

- uninstalled all openstudios via WIndows uninstall tool
- restart computer
- checked all openstudio folders are gone
- install OpenStudio 2.8.1
- restart computer
- start OpenStudioApp.exe 

still having the same issue.

**Comment by tijcolem** [comment]
The issue might be the Measure Manager is loading an incompatible dll from the Ruby C:/Ruby22-x64 path.  You could do a simple test a temporary move or backup the: /Ruby22-x64 directory so that it doesn't load the .dll from that path. If that works, you may need to remove uninstall ruby and reinstall.

**Comment by JanghyunJK** [comment]
@tijcolem 
you were right. moving ruby folder actually made OpenStudio to start properly. but I'm seeing another crash while going through this instruction (https://github.com/NREL/openstudio-standards/blob/master/docs/DeveloperInformation.md). below are steps that I took and checking OpenStudio startup after each step. I'm getting the crash after "gem install json". And error messages is also down below.

- OpenStudio 2.8.1 installation => WORKS
- restart PC
- Ruby install (rubyinstaller-2.2.4-x64.exe) => WORKS
- restart PC
- Install devkit (DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe) => WORKS
- Run "ruby dk.rb init" & "ruby dk.rb install" => WORKS
- Create "openstudio.rb" directing to 2.8.1 => WORKS
- Create ENVariable GEM_PATH = C:\Ruby22-x64\lib\ruby\gems\2.2.0 => WORKS
- Create ENVariable GEM_HOME = C:\Ruby22-x64\lib\ruby\gems\2.2.0 => WORKS
- Copy&Paste libeay32.dll & ssleay32.dll to C:\Ruby22-x64\bin => WORKS
- Create cacerts.pem and add contents from nrel.pem => WORKS
- Create ENVariable SSL_CERT_DIR = C:\Ruby22-x64\ssl\certs / SSL_CERT_FILE = C:\Ruby22-x64\ssl\certs\cacerts.pem => WORKS
- Create ENVariable HOME = C:\Users\JKIM4 => WORKS
- Copy&paste client_secret.json to .credential folder => WORKS
- run "gem install bundler -v 1.17.1" => WORKS
- run "gem install json" => **ERROR**

![error3](https://user-images.githubusercontent.com/26775789/65608238-25316680-df6b-11e9-9e33-2414dae82fa6.PNG)
![error4](https://user-images.githubusercontent.com/26775789/65608244-282c5700-df6b-11e9-8cfe-85b9f008d42a.PNG)
![error5](https://user-images.githubusercontent.com/26775789/65608253-2bbfde00-df6b-11e9-8a53-c8faf1f2680f.PNG)

**Comment by tijcolem** [comment]
Can you try installing `gem install json_pure` vs `gem install json`

**Comment by JanghyunJK** [comment]
`gem install json_pure` worked. so far I'm not seeing a crash! thanks!

**Comment by tijcolem** [comment]
closing this issue. will open issue with openstudio-standards to update docs to `gem install json_pure`
