### ISSUE TITLE
Need to rework behavior of fixed measures and design alternatives from external models (Bugzilla #1308)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#369]
On 2013-06-28 14:47:00, @DavidGoldwasser wrote:

> In testing bug 1304 it looks like the external model is loaded then all fixed measures are applied. This can result in unexpected manipulation of the external model and often errors if a measure input refers to an item that doesn't exist.
> 
> What we have is fine for 1.0, but we should try to address this in one of the next 2-3 iteration releases.
> 
> Here are two possible solutions.
> 1. If we can have an external model design alternatives bring in its own fixed measures and then not use any from the PAT project that would work.
> 
> 2. Another solution is to kill the external model option in the design alternative tab and just make a special measure to do this. A single measure group for a measure called "Load External Model in place of Current Model" could have 4-5 instances each with links to a different model. Because Tab 1 gives control of when this occurs we can have it after the fixed measures we don't want but before ones we do one, like the utility measure. The only issue here is putting some thought into how the file the user browses to gets saved internal to the model (in a reasonable workflow that doesn't have them hand moving it). Maybe a special input type called "Path" that when it is chosen grabs the file and brings it in similar to what is done with a weather file?.

**Comment by Matt32258** [comment]
Hello,
I am not sure if this is what has happened but I was using the always run Reporting Measure = "Calibration Reports" successfully while in OS.  I ran PAT and did not get the reports and graphs I was expecting.  I did go back to the Sketchup GUI and modify geometry (eliminate some degenerate surfaces) and now OS does not give me End Use Breakdown and Calibration Report only shows existing.   Does this mean my model is now corrupted?  Are there lines that have been added to the .idf that need to be deleted?
Thank you,
Matt

**Comment by macumber** [comment]
@Matt32258 If the measures in your OSM become corrupt you can delete the companion directory and then open your OSM file.  This will create a new companion directory and you can re-add the measures.  We are going to try to fix #754 for the 1.6.0 release

**Comment by macumber** [comment]
@DavidGoldwasser @asparke2 is this still a valid issue or did Elaine fix it?

**Comment by asparke2** [comment]
I don't think that it has been changed.  Looking at it now, I think we need to discuss before making any changes, since people have workflows that take the current behavior into account.

**Comment by MatthewSteen** [comment]
@macumber @Matt32258 - as of 1.5.0 I haven't been able to permanently disassociate measures from an OSM by simply deleting the directory. They will be removed from the OSM file measure tab but will reappear in the newly created directory when the OSM is reopened. 

If you instead copy/paste the OSM to a new location the measures will be permanently disassociated from the model and the scripts folder will be empty. Without doing this the scripts folder will contain a "history" of the measures added/deleted/added... by the user.

**Comment by macumber** [comment]
@MatthewSteen that is very odd, there is no information about the measures stored in the OSM file, it is all in that directory.  Can you try this again?  You may have to close the OpenStudio app before deleting the directory and then restart the OpenStudio app to re-open the OSM.

**Comment by MatthewSteen** [comment]
@macumber - I couldn't reproduce in 1.5.0, another phantom issue I guess, will try to document better in the future.

**Comment by Matt32258** [comment]
Hi Folks,
I appreciate the advise.  I created a new blank folder copied just the .osm before running again.
The OS results summary still has the drop down for Calibration Report but does not show current data from the simulation. I am also not allowed to add the BCL Calibration Reports back to the model because it "conflicts with the built in measure".  I am going to try again and shut my machine down.  I realize that temporary folders are used extensively and I wonder if this might be affecting program control.  Best,  Matt

**Comment by Matt32258** [comment]
Greetings all,  
The .osm seems to be hard wired to run a calibration report ("built in") since it was used once before with the model.  However, it does not show the model results.  I have uninstalled and re-installed OS and deleted all files related to Measures and the Measures folders.  I am going to send the file to another computer that has never run PAT or Measures or OS 1.5. and see if I can shake this bug.  Please send me information on how control is coded in the .osm and maybe I can re-set this to begin cleanly.  Thank you,  Matt

**Comment by Matt32258** [comment]
I mean to say OS results are displayed but the Calibration Report does not.  Also interesting to note but when I was seeing the reports it would never pick up the month of February.
I will let you know how the model runs on anther computer.  Thank you,  Matt

**Comment by Matt32258** [comment]
Follow up.  OS does retain the measure Calibrate.  It will not operate or let you re-set once attached or inserted to the .osm file.

**Comment by Matt32258** [comment]
Problem solved.  I believe some changes or maybe a save operation left the required year input blank.  But this raises the question of having data that might start in the middle of the year.
Thank you,
Matt
