### ISSUE TITLE
Hard to understand message if choice argument is not found in model (Bugzilla #1309)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#370]
On 2013-06-28 14:52:40, @DavidGoldwasser wrote:

> I ran across this trying to add a cost to a lights def after also reducing the power. I'll try to attach when I get a chance.
> 
> When I ran I got a message that says "Script argument "lights_def" is required or has a default value, but the user argument does not have a value or a default value set".
> 
> I assume this is being generated by the built in error checking.
>     #use the built-in error checking 
>     if not runner.validateUserArguments(arguments(model), user_arguments)
>       return false
>     end
> 
> Here is code where I was trying to trap this
> 
> ```
> #check the Definition for reasonableness
> if lights_def.empty?
>   handle = runner.getStringArgumentValue("lights_def",user_arguments)
>   if handle.empty?
>     runner.registerError("No Lights Definition was chosen.")
>   else
>     runner.registerError("The selected Lights Definition with handle '#{handle}' was not found in the model. It may have been removed by another measure.")
>   end
>   return false
> else
>   if not lights_def.get.to_LightsDefinition.empty?
>     lights_def = lights_def.get.to_LightsDefinition.get
>   else
>     runner.registerError("Script Error - argument not showing up as Lights Definition.")
>     return false
>   end
> end  #end of if lights_def.empty?
> ```

On 2013-06-28 15:13:04, @DavidGoldwasser wrote:

> **\* Bug 1310 has been marked as a duplicate of this bug. ***

**Comment by jmarrec** [comment]
It's been clarified it seems.

https://github.com/NREL/OpenStudio/blob/7cec475621233fcd772de2c6715ef9252bcbb7a6/src/measure/OSRunner.cpp#L402-L410

https://github.com/NREL/OpenStudio/blob/7cec475621233fcd772de2c6715ef9252bcbb7a6/src/measure/OSRunner.cpp#L432-L439
