### ISSUE TITLE
Curve Biquadratic Object Not Honoring "Minimum Value of X" attribute in Curve Evaluation

### ISSUE THREAD

**Issue by eomere** [NREL/OpenStudio#3722]
**Expected behavior:**

Create OS:Curve:Biquadratic object
Call curveObject.evaluate(4.6,4.6)
Expected Result of 0.9743

**Observed behavior**
Result = 0.805. 
![Curve Object](https://user-images.githubusercontent.com/55591465/66581395-04156c00-eb4e-11e9-935f-03e7c5f3d3a5.PNG)

Possibly also an EnergyPlus bug

Here is an Excel Spreadsheet detailing the calculations
[Curve Object.xlsx](https://github.com/NREL/OpenStudio/files/3713284/Curve.Object.xlsx)

Using OpenStudio Version 2.8.1
Build Number 6914d4f590
OS: Windows 10

**Comment by jmarrec** [comment]
It's true, the calculation routine for this curve doesn't take the min/max output values.
It also doesn't check that the independent variable values are within bounds.

https://github.com/NREL/OpenStudio/blob/c7c81e794a834f435ed2717f51cedf477c389032/openstudiocore/src/model/CurveBiquadratic.cpp#L87:L96

Note that this is purely a convenience function, which isn't used by E+ at all.

**Comment by jmarrec** [comment]
Fixed in develop3 (will be 3.0.0 when released officially) via https://github.com/NREL/OpenStudio/pull/3775
