### ISSUE TITLE
Add new DOAS to AHU objects

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#3728]
New Feature Request: 
EnergyPlus v9.2 added a new feature to model DOAS supplying air to inlets of multiple AHUs:
https://github.com/NREL/EnergyPlus/pull/7230

New objects:
- AirLoopHVAC:DedicatedOutdoorAirSystem
- AirLoopHVAC:Mixer
- AirLoopHVAC:Splitter

It would be super to have these added at least to the SDK.

**Comment by MatthewSteen** [comment]
@eringold beat me to it 👍

**Comment by tijcolem** [comment]
@joseph-robertson could you please size up the effort on this?  Since it would be IDD change we'd need to tag to the 3.0 milestone release.

**Comment by joseph-robertson** [comment]
Design doc: https://docs.google.com/document/d/1HnocSAX1seOSYmALbX6pUCqiuSjyQa42oxx9wmtF5Ls/edit#

@tijcolem @jmarrec @kbenne

**Comment by jmarrec** [comment]
Will comment on the PR itself: https://github.com/NREL/OpenStudio/pull/3863
