### ISSUE TITLE
AvailabilityManagerNightCycle ApplicabilitySchedule field changes unexpectedly in app

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#3730]
Same issue that fans had in #3124 and confirmed the behavior is in 2.9.0. Also appears to happen when creating a model with the API (e.g. Create Baseline Building measure) and then opening it in the app. Found by @tjcain91.

1. create a new air loop
2. change night cycle control to cycle on full system
3. note ApplicabilitySchedule is defaulted to Always On Discrete
4. add new schedule to model and change name to have a number prefix (e.g. "1 Schedule")
5. ApplicabilitySchedule changes to new schedule

**Step 2**
![image](https://user-images.githubusercontent.com/8397034/66851573-3f41e180-ef38-11e9-924b-1c7d0047e9ed.png)

**Step 4**
![image](https://user-images.githubusercontent.com/8397034/66851630-63052780-ef38-11e9-9cfd-69628393a6d0.png)

**Step 5**
![image](https://user-images.githubusercontent.com/8397034/66851617-58e32900-ef38-11e9-90c3-80497aefeee0.png)

**Comment by jmarrec** [comment]
This is fixed by #3711 which is in develop but NOT in 2.9.0

**Comment by jmarrec** [comment]
I'm leaving it open until I show behavior with current develop

**Comment by jmarrec** [comment]
Did the steps you mentioned, no problem. Note the difference in which fields are actually shown in current develop compared to your screenshot above in 2.9.0:

![image](https://user-images.githubusercontent.com/5479063/67273339-868f1b80-f4be-11e9-8ad6-4f22c0142fe4.png)
