### ISSUE TITLE
fix failing unit tests related to ruby bundle

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#3733]
CLITest-test_bundle-bundle
CLITest-test_bundle-bundle_git

**Comment by lefticus** [comment]
@kbenne Yeah, I was just waking up from my funk of a cold and was coming to the same conclusions that it was just a misconfiguration for the missing bundle gem.

I have two thoughts:

 1. This comment makes me wonder if the test is truly valid, or if some associated task needs to be created https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/cli/test/test_bundle.rb#L4-L6
 2. Should there be some kind of smarter test during configure time to alert that the bundle gem is not properly installed?

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio/blob/a69ba2c6db3ec89bf4ec17776f8581617fe74823/openstudiocore/src/cli/openstudio_cli.rb#L687

**Comment by jmarrec** [comment]
```
ModelTests#test_model_articulation1_bundle_no_git_osw:
RuntimeError: Exit code 1:
W, [2019-12-13T15:24:23.810883 #12576]  WARN -- : Bundle activated but ENV['BUNDLE_WITHOUT'] is not set
Error executing argv: ["--bundle", "/home/julien/Software/Others/OpenStudio-resources/gemfiles/bundle_no_git/Gemfile", "--bundle_path", "/home/julien/Software/Others/OpenStudio-resources/gemfiles/bundle_no_git/gems", "run", "-w", "/home/julien/Software/Others/OpenStudio-resources/testruns/model_articulation1_bundle_no_git.osw/in.osw"]
Error: You must use Bundler 2 or greater with this lockfile. in :/ruby/2.5.0/gems/bundler-1.17.1/lib/bundler/lockfile_parser.rb:108:in `warn_for_outdated_bundler_version'
```

So these tests are always pretty much this:

```
    assert(system('bundle install --path ./test_gems'))
    assert(system('bundle lock --add_platform ruby'))
    assert(system("'#{OpenStudio::getOpenStudioCLI}' --bundle Gemfile --bundle_path './test_gems' --verbose test.rb"))
```

So you install the gems via your system Ruby... then you call `openstudio --bundle Gemfile --bundle_path ...` ? Does that just load them up, rather than try to reinstall them?

Via system, the `Gemfile.lock` ends up with

```
BUNDLED WITH
   2.0.2
```

Apparently openstudio uses an older bundler.

so:

* Should we really call the system commands to begin with?
* If so, then openstudio bundler needs to be updated to 2.0.2+ (not sure where it's coming from ....?)

**Comment by jmarrec** [comment]
Potential fix in https://github.com/NREL/openstudio-gems/pull/10

**Comment by jmarrec** [comment]
Ping @jmarrec rerun tests now that https://github.com/NREL/openstudio-gems/pull/13 was merged

**Comment by tijcolem** [comment]
The last issue is with Mac.  It's on me. I added a step to invoke the rvm to use ruby 2.5.5 and bundler 2.1.4, and while it's using those, these tests are still failing.

**Comment by jmarrec** [comment]
This works now.
