### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [NREL/OpenStudio#3734]
Would you like to wrap any pointer data members with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [QwtAbstractScale](https://github.com/NREL/OpenStudio/blob/8c81faf8bc80b0e8f96a4b2764e5958cd060a625/openstudiocore/src/qwt/qwt_abstract_scale.cpp#L17)
- [VariableList](https://github.com/NREL/OpenStudio/blob/e077c7edfa6c94bb37aeb0e31f40b69ed2740223/openstudiocore/src/openstudio_lib/VariablesTabView.cpp#L162)

**Comment by jmarrec** [comment]
Thanks for the suggestion!

Qwt Widget Library is just a library that we "use" in OpenStudioApplication: https://qwt.sourceforge.io/.
In fact, we DON'T use it anywhere... It's no longer present in develop3 (the prelease 3.0.0)

`VariableList` is part of the OpenStudioApplication, which uses Qt. I'm not sure how familiar you are with Qt, but Qt relies on a parent - child model and handles management of resources internally (cf: https://stackoverflow.com/questions/34433435/why-dont-the-official-qt-examples-and-tutorials-use-smart-pointers) (though sometimes it can be a bit cryptic to use, and we probably have cases where we do not parent widgets correctly)

So I'm going to close this one up. If you find other occurrences in `./openstudiocore/src` (develop) or `./src/` (develop3), then we can totally reopen the issue.

**Comment by elfring** [comment]
>…, and we probably have cases where we do not parent widgets correctly

Would you like to improve your software according to such an aspect?

**Comment by jmarrec** [comment]
I can't speak for NREL (especially given that the OpenstudioApplication is transitionning out of this project), but personally I'm always interested in making things better. Are you offerring help?
