### ISSUE TITLE
Add gems to CLI

### ISSUE THREAD

**Issue by tijcolem** [NREL/OpenStudio#3744]
One of our collaborators (NIST) wants to be able to use a specific ruby gem (https://rubygems.org/gems/protobuf/versions/3.10.2) inside the OS CLI.

**Comment by tijcolem** [comment]
- [ ] Create a ruby gem matrix showing what can be supported 
- [ ] Create a ruby gem matrix showing what is currently supported and shipped with CLI

**Comment by jmarrec** [comment]
Ref #3834

**Comment by tijcolem** [comment]
List of requested native gems.  Just a note, most of these gems work fine using c99 compliant compilers (e.g. gcc, clang). That makes sense given they ruby gems are Unix centric which also explains why ruby mingw on windows.  OpenStudio uses msvc to compile and therfore we need matching compiler so we use a ruby msvc version.  The msvc C compiler is *not* c99 compliant so when trying to compile certain native gems we hit errors such as
 ` C2057: error C2057: expected constant expression`

Here's an example of an offending line which msvc cannot compile. 

https://github.com/protocolbuffers/protobuf/blob/master/ruby/ext/google/protobuf_c/message.c#L192 

ruby gem | 18.04 ubuntu | Windows | Mac | Notes|
--- | --- | --- | --- | ---
nokogiri | X | | X|
google-protobuf | X | | X|
pycall-protobuf | X |X| X|
schematron-nokogir | X | | X|
Ox |  | | |  Alternative to nokogiri
Olga |  | | |  Alternative to nokogiri
SQL ODM/ORM |  | | |  Need ODM/ORM mapping gem

**Comment by nllong** [comment]
@tijcolem  -- Can we add [jaro_winkler](https://rubygems.org/gems/jaro_winkler) version 1.5.x to this list so that we can upgrade the rubocop library?

**Comment by shorowit** [comment]
@tijcolem It would also be nice to replace the [json_pure](https://rubygems.org/gems/json_pure) gem with the [json](https://rubygems.org/gems/json) gem, which has faster performance. 

My understanding is that no code changes are required as they provide the same interface and are developed by the same author. Indeed, they are both loaded in the same way (`require 'json'`).

**Comment by tijcolem** [comment]
@shorowit native json is already included as part of the standard native gems when you build ruby. So it's already in the CLI for 3.0.0.

**Comment by shorowit** [comment]
@tijcolem Really? I just installed OpenStudio-3.0.0-beta+d05bc3a9ba-Windows (last night's build) and it still shows json_pure.

```
PS C:\Users\shorowit> C:\openstudio-3.0.0-beta\bin\openstudio.exe gem_list
ansi (1.5.0) ':/ruby/2.5.0/gems/ansi-1.5.0'
ast (2.4.0) ':/ruby/2.5.0/gems/ast-2.4.0'
builder (3.2.4) ':/ruby/2.5.0/gems/builder-3.2.4'
bundler (2.1.0) ':/ruby/2.5.0/gems/bundler-2.1.0'
docile (1.3.2) ':/ruby/2.5.0/gems/docile-1.3.2'
git (1.6.0) ':/ruby/2.5.0/gems/git-1.6.0'
json_pure (2.2.0) ':/ruby/2.5.0/gems/json_pure-2.2.0'
minitest (5.4.3) ':/ruby/2.5.0/gems/minitest-5.4.3'
minitest-reporters (1.2.0) ':/ruby/2.5.0/gems/minitest-reporters-1.2.0'
openstudio-extension (0.2.0) ':/ruby/2.5.0/gems/openstudio-extension-0.2.0'
openstudio-standards (0.2.10) ':/ruby/2.5.0/gems/openstudio-standards-0.2.10'
openstudio-workflow (1.3.4) ':/ruby/2.5.0/gems/openstudio-workflow-1.3.4'
openstudio_measure_tester (0.2.0) ':/ruby/2.5.0/gems/openstudio_measure_tester-0.2.0'
parallel (1.12.1) ':/ruby/2.5.0/gems/parallel-1.12.1'
parser (2.7.0.2) ':/ruby/2.5.0/gems/parser-2.7.0.2'
powerpack (0.1.2) ':/ruby/2.5.0/gems/powerpack-0.1.2'
pycall (1.2.1) ':/ruby/2.5.0/bundler/gems/pycall.rb-5d60b274ac64'
rainbow (3.0.0) ':/ruby/2.5.0/gems/rainbow-3.0.0'
rake (12.3.1) ':/ruby/2.5.0/gems/rake-12.3.1'
rchardet (1.8.0) ':/ruby/2.5.0/gems/rchardet-1.8.0'
rubocop (0.54.0) ':/ruby/2.5.0/gems/rubocop-0.54.0'
rubocop-checkstyle_formatter (0.4.0) ':/ruby/2.5.0/gems/rubocop-checkstyle_formatter-0.4.0'
ruby-progressbar (1.10.1) ':/ruby/2.5.0/gems/ruby-progressbar-1.10.1'
simplecov (0.18.1) ':/ruby/2.5.0/gems/simplecov-0.18.1'
simplecov-html (0.11.0) ':/ruby/2.5.0/gems/simplecov-html-0.11.0'
unicode-display_width (1.6.1) ':/ruby/2.5.0/gems/unicode-display_width-1.6.1'
```

**Comment by tijcolem** [comment]
Hmm, that list could be misleading and looks like it's not showing the gems that built when we compile ruby.  

Can you do a simple test and write a little script and include `json/ext`as that should be explicit and include the native json gem.

**Comment by shorowit** [comment]
Ah, I see. Is this what you wanted?

OpenStudio 2.9.1:
```
PS C:\Users\shorowit> C:\openstudio-2.9.1\bin\openstudio.exe -e "require 'json/ext'"

Error: Preventing segfault if native JSON is built as MinGW
Backtrace:
        :/openstudio_cli.rb:736:in `eval'
        :/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        (eval):1:in `block in execute'
        :/openstudio_cli.rb:736:in `eval'
        :/openstudio_cli.rb:736:in `block in execute'
        :/openstudio_cli.rb:734:in `each'
        :/openstudio_cli.rb:734:in `execute'
        :/openstudio_cli.rb:1746:in `<main>'
        eval:116:in `eval'
        eval:116:in `require_embedded_absolute'
        eval:101:in `block in require'
        eval:95:in `each'
        eval:95:in `require'
        eval:3:in `<main>'
Exception: Preventing segfault if native JSON is built as MinGW
<main>: unexpected return
```

OpenStudio 3.0.0-beta:
```
PS C:\Users\shorowit> C:\openstudio-3.0.0-beta\bin\openstudio.exe -e "require 'json/ext'"
:/ruby/2.5.0/gems/json_pure-2.2.0/lib/json/version.rb:4: warning: already initialized constant JSON::VERSION
:/ruby/2.5.0/json/version.rb:4: warning: previous definition of VERSION was here
:/ruby/2.5.0/gems/json_pure-2.2.0/lib/json/version.rb:5: warning: already initialized constant JSON::VERSION_ARRAY
:/ruby/2.5.0/json/version.rb:5: warning: previous definition of VERSION_ARRAY was here
:/ruby/2.5.0/gems/json_pure-2.2.0/lib/json/version.rb:6: warning: already initialized constant JSON::VERSION_MAJOR
:/ruby/2.5.0/json/version.rb:6: warning: previous definition of VERSION_MAJOR was here
:/ruby/2.5.0/gems/json_pure-2.2.0/lib/json/version.rb:7: warning: already initialized constant JSON::VERSION_MINOR
:/ruby/2.5.0/json/version.rb:7: warning: previous definition of VERSION_MINOR was here
:/ruby/2.5.0/gems/json_pure-2.2.0/lib/json/version.rb:8: warning: already initialized constant JSON::VERSION_BUILD
:/ruby/2.5.0/json/version.rb:8: warning: previous definition of VERSION_BUILD was here
:/ruby/2.5.0/gems/json_pure-2.2.0/lib/json/common.rb:100: warning: already initialized constant JSON::NaN
:/ruby/2.5.0/json/common.rb:100: warning: previous definition of NaN was here
:/ruby/2.5.0/gems/json_pure-2.2.0/lib/json/common.rb:102: warning: already initialized constant JSON::Infinity
:/ruby/2.5.0/json/common.rb:102: warning: previous definition of Infinity was here
:/ruby/2.5.0/gems/json_pure-2.2.0/lib/json/common.rb:104: warning: already initialized constant JSON::MinusInfinity
:/ruby/2.5.0/json/common.rb:104: warning: previous definition of MinusInfinity was here
:/ruby/2.5.0/gems/json_pure-2.2.0/lib/json/common.rb:129: warning: already initialized constant JSON::UnparserError
:/ruby/2.5.0/json/common.rb:129: warning: previous definition of UnparserError was here
```

**Comment by tijcolem** [comment]
Right. And once we remove json_pure those annoying error messages go away.  

2.9.1 won't work unless you have an msvc compiled version of the json/ext gem. It's trying to load your json which is mingw and that's why you see that error.

**Comment by tijcolem** [comment]
But to your point, to list out the gems that are compiled with ruby, I need to find out if we can list those out via cli and/or ruby options.

**Comment by shorowit** [comment]
Sounds great! Thanks @tijcolem.

**Comment by tijcolem** [comment]
@nllong @jmarrec jara_winkler has issues on windows using msvc.  

```
 jaro.c(30): error C2146: syntax error: missing ‘;’ before identifier ‘SWAP’
jaro.c(30): error C2065: ‘SWAP’: undeclared identifier
jaro.c(30): warning C4047: ‘=’: ‘int’ differs in levels of indirection from
‘uint32_t *’
jaro.c(30): warning C4047: ‘=’: ‘uint32_t *’ differs in levels of indirection
from ‘int’
jaro.c(31): error C2146: syntax error: missing ‘;’ before identifier ‘SWAP’
jaro.c(31): error C2065: ‘SWAP’: undeclared identifier
jaro.c(45): error C2057: expected constant expression
jaro.c(45): error C2466: cannot allocate an array of constant size 0
jaro.c(45): error C2133: ‘short_codes_flag’: unknown size
jaro.c(46): error C2057: expected constant expression
jaro.c(46): error C2466: cannot allocate an array of constant size 0
jaro.c(46): error C2133: ‘long_codes_flag’: unknown size
NMAKE : fatal error U1077: ‘“C:\Program Files (x86)\Microsoft Visual
Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.E
```

We would need to fork https://github.com/tonytonyjan/jaro_winkler and fix these up if we want to support windows.

**Comment by nllong** [comment]
Perhaps we stay on the older version of Rubobop until this is resolved? I think that was 0.54.1. Thoughts @jmarrec

**Comment by shorowit** [comment]
In my opinion, rubocop is a _much_ lower priority than nokogiri/schematron.

**Comment by tijcolem** [comment]
We have solidified the list of supported natiive ext gems for 3.0.0 release. We can continue to work on this and make further progress.  Please see list above for supported gems for 3.0.0 release. Moving this to milestone 3.1.0 for further work.

**Comment by shorowit** [comment]
👍 Thanks for everyone's work here. We've already switched from REXML to Oga and found a nice performance benefit. And the transition was relatively straightforward.

**Comment by tijcolem** [comment]
closed via https://github.com/NREL/openstudio-gems/pull/22
