### ISSUE TITLE
Missing inputs to make CoilCooling:DX:TwoStageWithHumidityControlMode work for humidity control

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#3753]
(kind of a feature request)

When a CoilCooling:DX;TwoStageWithHumidityControlMode object is translated, a CoilSystem:Cooling:DX object is [created](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateCoilCoolingDXTwoStageWithHumidityControlMode.cpp#L170), with limited inputs:

```
CoilSystem:Cooling:DX,
  Two Stage DX Coil With Humidity Control CoilSystem, !- Name
  Always On Discrete,                     !- Availability Schedule Name
  Node 104,                               !- DX Cooling Coil System Inlet Node Name
  Node 101,                               !- DX Cooling Coil System Outlet Node Name
  Node 101,                               !- DX Cooling Coil System Sensor Node Name
  Coil:Cooling:DX:TwoStageWithHumidityControlMode,            !- Cooling Coil Object Type
  Two Stage DX Coil With Humidity Control; !- Cooling Coil Name
```

CoilSystem:Cooling:DX objects are not exposed in the SDK, but contain inputs necessary for making the coil work for controlling humidity, necessitating an EnergyPlus measure:
- [Dehumidification Control Type](https://bigladdersoftware.com/epx/docs/9-1/input-output-reference/group-heating-and-cooling-coils.html#field-dehumidification-control-type) - defaults to 'None', or no humidity control.
- [Run on Latent Load](https://bigladdersoftware.com/epx/docs/9-1/input-output-reference/group-heating-and-cooling-coils.html#field-run-on-latent-load)

Could these (and perhaps other) CoilSystem:Cooling:DX inputs be added to OS:CoilCoolingDXTwoStageWithHumidityControlMode and translated to the generated CoilSystem object? 

@kbenne @jmarrec

**Comment by kbenne** [comment]
Hey @eringold there is a new CoilCoolingDX model coming out in EnergyPlus 9.3, that is kind the one DX model to rule them all. OpenStudio is not adopting it in this release, but we will in version 3.1. Would it be alright if we directed people to use the new model when it is available instead of making this update?

**Comment by eringold** [comment]
@kbenne Sure, that makes sense.
As a temporary workaround for the issue, here's the key bit of EnergyPlus measure code I've been using:

```
    csc_dx = workspace.getObjectsByType("CoilSystem:Cooling:DX".to_IddObjectType)
    runner.registerInfo("#{csc_dx.size} CoilSystem Objects Found")
    csc_dx.each do |cs|
      name = cs.getString(0).get
      runner.registerInfo("#{name}")
      coil = cs.getString(5).get
      if coil.include?("Humidity") 
        cs.setString(7,'CoolReheat')
        cs.setString(8,'Yes')
        cs.setString(9,'Yes')
        runner.registerInfo("Added humidity control to #{name}")
      end
    end
```

**Comment by MatthewSteen** [comment]
@eringold thanks for the EP code. I was experiencing this issue on a baseline model for a natatorium.

**Before**
![image](https://user-images.githubusercontent.com/8397034/79778123-7d5bfb80-82f5-11ea-96fe-88ef0a81e2c0.png)

**After**
![image](https://user-images.githubusercontent.com/8397034/79778749-7bdf0300-82f6-11ea-9d69-53b5ea9b08aa.png)

**Comment by MatthewSteen** [comment]
@tijcolem I don't see any commits for the issue, did I miss something?
