### ISSUE TITLE
Python EMS

### ISSUE THREAD

**Issue by bonnema** [NREL/OpenStudio#3756]
Support Python EMS
 - Wrap new IDD objects
 - Attach python code to OSM, possible pattern is Schedule:File

Target completion date to coincide March release of EnergyPlus

**Comment by tijcolem** [comment]
Duplicate #3839

**Comment by asparke2** [comment]
@tijcolem is this feature happening?  I see that both issues (this and #3839) referencing the python EMS support have been closed.

**Comment by shorowit** [comment]
https://github.com/NREL/OpenStudio/issues/3839 is still open

**Comment by asparke2** [comment]
Ah yes, my bad, thanks @shorowit

**Comment by chrisbalbach** [comment]
+1
