### ISSUE TITLE
Large model intersect with model hangs for 30 minutes and then crashes

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#376]
This may or may not be related to issue #24. That issues is a 2 space model that crashes almost right away. This model uses the processor for 30 minutes and then crashes. May be same source issue, or may be memory problem. This model has about 160 spaces.

![7-10-2013 11-53-21 am](https://f.cloud.github.com/assets/4857055/836059/17ff2086-f2e8-11e2-92fc-080e7c29eb45.png)

Until the bug is fixed I'm trying to come up with a work around. Right now I exported the model to a DXF, and then ran simple SketchUp script to do intersection. It took about 40 seconds, and did not crash. It did results in some unexpected geometry. That unexpected geometry is due to the SketchUp bug. The plan is to have the user clean this up and then run a second basic OpenStudio user script to convert each SketchUp group (maybe on the layer named "OPENSTUDIO__MODEL__SPACE" to an OpenStudio model. I'm in essence doing the intersection completely outside of OpenStudio then translating the model to an OpenStudio model.

Here is a screenshot of the unexpected geometry, and then the code for my intersect script.
![7-22-2013 10-06-41 am](https://f.cloud.github.com/assets/4857055/836081/bbdbff1c-f2e8-11e2-8780-73a01b2701d8.png)

----------------
puts "Intersecting adjacent groups throughout model"

# get sketchup model
model = Sketchup.active_model
entities = model.active_entities
selection = model.selection #not using this right now

#make array of groups, and make unique
groups = []
entities.each do |entity|
  next if not entity.class.to_s == "Sketchup::Group"
  groups << entity
end 

#loop through groups
groups.each do |group|

  #intersect with rest of model
  group.entities.intersect_with(true, group.transformation, group, group.transformation, false, groups)

end
----------------

**Comment by macumber** [comment]
@DavidGoldwasser can we close this as won't fix?

**Comment by DavidGoldwasser** [comment]
Yes, we can close this, there is a more current one that had issues with OpenStudio based intersect in another issue. I may keep this model in mind for testing OpenStudio's native intersect.
