### ISSUE TITLE
Can't find ASHRAE climate zone in stat file even when present

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/OpenStudio#3760]
When running a series of measures: ChangeBuildingLocation, CreateBarFromBuildingTypeRatios, CreateTypicalBuildingFromModel and setting the weather file in ChangeBuildingLocation to:

CAN_QC_Montreal-McTavish.716120_CWEC2016.epw

Even though the stat file does have the line:

 - Climate Zone "6A" (ASHRAE Standards 169-2013 and 90.1-2016)

OpenStudio still says:

> Applying ChangeBuildingLocation
>   Result: Success
>   Initial Condition: No weather file is set. The model has 0 design day objects
>   Final Condition: The final weather file is Montreal-McTavish and the model has 3 design day objects.
>   Warn: Can't find ASHRAE climate zone in stat file.
>   Info: city is Montreal-McTavish. State is QC
>   Info: mean dry bulb is 0.0
>   Info: Adding object Montreal-McTavish Ann Htg 99.6% Condns DB
>   Info: Adding object Montreal-McTavish Ann Clg .4% Condns DB=>MWB
>   Info: Adding object Montreal-McTavish Ann Clg .4% Condns WB=>MDB
>   Info: Setting Climate Zone to Lookup From Stat File
> Applying CreateBarFromBuildingTypeRatios
>   Result: Success
>   Initial Condition: The building started with 0 spaces.
>   Final Condition: The building finished with 39 spaces.
>   Warn: Floor area of Retail Entry results in a bar with smaller than target minimum width.
>   Warn: Floor area of Retail Point_of_Sale results in a bar with smaller than target minimum width.
>   Warn: Floor area of Retail Back_Space results in a bar with smaller than target minimum width.
>   Info: 0.0 value for floor height will be replaced with smart default for Warehouse of 28.0.
>   Info: Set Building Rotation to 30.0
>   Info: Creating Space Types for Warehouse.
>   Info: Creating Space Types for SmallOffice.
>   Info: Creating Space Types for RetailStandalone.
>   Info: Intersecting surfaces, this will create additional geometry.
>   Info: Created Bar envlope with floor area of 11,000 (ft^2)
>   Info: Target party wall fraction is 0.0. Realized fraction is 0.0
> Applying CreateTypicalBuildingFromModel
>   Result: Fail
>   Initial Condition: The building started with 695 objects.
>   Error: Could not create default construction set for the building type Warehouse in climate zone ASHRAE 169-2013-Lookup From Stat File.
>   Error: [openstudio.standards.Model] Cannot find a climate zone set containing ASHRAE 169-2013-Lookup From Stat File
>   Error: [openstudio.standards.Model] Cannot find a climate zone set when 90.1-2007

I tried some other Montreal files and they all did the same thing.

This was in OpenStudio 2.8.1.

**Comment by jmarrec** [comment]
I can't find Mctavish online...

Can you paste EXACTLY the line from the stat file in a code block please? eg:

```
 - Climate type "6A" (ASHRAE Standards 90.1-2004 and 90.2-2004 Climate Zone)**
```

The relevant code block from ChangeBuildingLocation measure is this:
```
    climateZones = model.getClimateZones
    if args['climate_zone'] == 'Lookup From Stat File'

      # get climate zone from stat file
      text = nil
      File.open(stat_file) do |f|
        text = f.read.force_encoding('iso-8859-1')
      end

      # Get Climate zone.
      # - Climate type "3B" (ASHRAE Standard 196-2006 Climate Zone)**
      # - Climate type "6A" (ASHRAE Standards 90.1-2004 and 90.2-2004 Climate Zone)**
      regex = /Climate type \"(.*?)\" \(ASHRAE Standards?(.*)\)\*\*/
      match_data = text.match(regex)
      if match_data.nil?
        runner.registerWarning("Can't find ASHRAE climate zone in stat file.")
      else
        args['climate_zone'] = match_data[1].to_s.strip
      end

    end
```

I tried with `CAN_PQ_Montreal.Intl.AP.716270_CWEC.stat` and it correctly found "6A".

```   
      stat_file = '/home/julien/Downloads/CAN_PQ_Montreal.Intl.AP.716270_CWEC.stat'
      text = nil
      File.open(stat_file) do |f|
        text = f.read.force_encoding('iso-8859-1');
      end

      regex = /Climate type \"(.*?)\" \(ASHRAE Standards?(.*)\)\*\*/
      match_data = text.match(regex)
      if match_data.nil?
        puts "Can't find ASHRAE climate zone in stat file."
      else
        puts "Found Climate zone #{match_data[1].to_s.strip}"
      end
```
=> "Found Climate zone 6A"

**Comment by jmarrec** [comment]
Actually I did find the McTavish on climate.onebuilding.org: http://climate.onebuilding.org/WMO_Region_4_North_and_Central_America/CAN_Canada/QC_Quebec/CAN_QC_Montreal-McTavish.716120_CWEC2016.zip

It doesn't have the same format at the other files (eg IWEC).

McTavish CWEC
```
 - Climate type "Dfb" (Köppen classification)**
 - Climate Zone "6A" (ASHRAE Standards 169-2013 and 90.1-2016)
```
IWEC
```
 - Climate type "Dfb" (Köppen classification)**
 - Climate type "6A" (ASHRAE Standards 90.1-2004 and 90.2-2004 Climate Zone)**
```

If you look at the regex in ChangeBuildingLocation, it should be `Climate type ` exactly, and end up with `)**`

**Comment by jmarrec** [comment]
I think it's going to be much easier to modify the ChangeBuildingLocation Measure instead of fixing the EPW files :)

So I'm going to close up this one and move it to https://github.com/NREL/OpenStudio-measures/issues/288

**Comment by JasonGlazer** [comment]
@jmarrec I don't have access to that repo so please let me know if it gets fixed.

**Comment by jmarrec** [comment]
@JasonGlazer I'm making the fix and opening a PR.

In the meantime if you need to move fast, do the change manually to ChangeBuildingLocation/measure.rb by modifying the regex to be `regex = /Climate (?>type|zone) \"(.*?)\" \(ASHRAE Standards? (.*)\)\*?\*?/i`

**Comment by jmarrec** [comment]
I'm reopening for clarity, will close this one as I close https://github.com/NREL/OpenStudio-measures/issues/288
