### ISSUE TITLE
App crashes when trying to display an airloop with Coil:Heating:Desuperheater

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#3767]
In version 2.9.0, I used the Ruby bindings to add a Coil:HeatingDesuperheater to an existing AirLoopHVAC (using `coil.addToNode`). When I open the model in the app and navigate to the loop in the HVAC Systems tab, the app will close. 

I suspect this is because there is no icon to display for that coil type?

**Comment by jmarrec** [comment]
I suspect you suspect right.
