### ISSUE TITLE
Add methods to edit SummaryReports in OpenStudio SDK

### ISSUE THREAD

**Issue by tanushree04** [NREL/OpenStudio#3784]
Add methods to select [summary reports](https://bigladdersoftware.com/epx/docs/8-8/input-output-reference/output-table-summaryreports.html#inputs-064) to call specific report types for output reporting.

**Comment by jmarrec** [comment]
Note that by default we include the `AllSummary` which should enable all of them (if it doesn't, that's an EnergyPlus issue). There's no option to limit outputs to specific reports though.

**Comment by joseph-robertson** [comment]
@tanushree04,

so to be clear, you don't just want this in the idf:

```
Output:Table:SummaryReports,
  AllSummary;                             !- Report Name 1
```

but rather you want the ability to write something like

```
Output:Table:SummaryReports,
  AnnualBuildingUtilityPerformanceSummary,                   !- Report Name 1
  InputVerificationandResultsSummary;                             !- Report Name 2
```
?

**Comment by tanushree04** [comment]
@joseph-robertson Yes, that's correct. The ability to select only a few Summary Reports.
