### ISSUE TITLE
Expose the ZoneVentilation:WindandStackOpenArea in the Model SDK

### ISSUE THREAD

**Issue by chriswmackey** [NREL/OpenStudio#3785]
This is a feature request that I realize should have a lower priority over other critical issues on this github but I wanted to add it here because I know that the few thousand people making use of OpenStudio workflows in [Ladybug Tools](https://www.ladybug.tools/) will get a lot of mileage out of it.  Also, this feature should be comparatively faster to implement than most others since it only requires the addition of a single object to the OpenStudio SDK and the adding this object shouldn't interfere with other objects currently implemented in the SDK.  So I'm posting this because it seems like something with a larger payoff (that the ladybug tools community will definitely make use of) for a relatively small time investment.

Specifically, it would be great to have [ZoneVentilation:WindAndStack](https://bigladdersoftware.com/epx/docs/9-1/input-output-reference/group-airflow.html#zoneventilationwindandstackopenarea) objects exposed in OpenStudio SDK. In Ladybug Tools, we make use of these a lot to model window-based natural ventilation since they are much easier to understand, teach, and specify correct inputs for compared to something as complex as the airflow network.  And they are really all that's needed to model window-based ventilation when you are not worried about air flow between zones and just need a good estimate of single-sided or cross ventilation within a zone.  I should also say that they are a massive improvement over trying to get the [ZoneVentilation:DesignFlowRate object that is currently within the SDK](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-2.9.0-doc/model/html/classopenstudio_1_1model_1_1_zone_ventilation_design_flow_rate.html) to approximate buoyancy and wind-driven ventilation through windows since the flow through windows is dependent upon a lot of things that you can't easily put into a DesignFlowRate schedule (like the air temperature of the zone).

**Comment by jmarrec** [comment]
cf https://github.com/NREL/OpenStudio/pull/3788

**Comment by chriswmackey** [comment]
Woohoo! Thank you @jmarrec !!!
