### ISSUE TITLE
Allow SDK users to not write out SQLite and/or HTML reports if they don't want to

### ISSUE THREAD

**Issue by chriswmackey** [NREL/OpenStudio#3786]
Right now, there doesn't seem to be any method exposed in the SDK that lets people opt out of writing the SQLite and/or HTML outputs from the EnergyPlus simulation.  From the perspective of the OpenStudio GUI, I understand why this option is not something that would get used often.  However, as someone developing other applications using OpenStduio SDK, it would be very helpful to opt out of these EnergyPlus outputs in certain cases.  Particularly when you have a large model and are studying simulation outputs at fine timesteps in a format other than SQLite or HTML, generating either one of these files can add time to the EnergyPlus run.  So it would be nice to just opt out of them for cases where I know that we won't make use of them.

**Comment by jmarrec** [comment]
This is all done internally by `ForwardTranslator::createStandardOutputRequests()`: https://github.com/NREL/OpenStudio/blob/develop3/src/energyplus/ForwardTranslator.cpp#L4465:L4509

This can't be toggled off altogether, much less granularly (turn off only HTML or SQLite)

It's a quick and easy fix so I'll just do it.

**Comment by chriswmackey** [comment]
Thank you, @jmarrec  . I figured the ForwardTranslator was the right place for this. Am I understanding correctly that you would expose this as an option on the [ForwardTranslator](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-2.9.0-doc/energyplus/html/classopenstudio_1_1energyplus_1_1_forward_translator.html) similar to how the `setExcludeLCCObjects` works?  If so, that would be wonderful.

**Comment by jmarrec** [comment]
@chriswmackey Yes that's exactly what I did, see #3787

**Comment by chriswmackey** [comment]
Excellent! 🎉

**Comment by jmarrec** [comment]
Closed via #3787
