### ISSUE TITLE
We don't have proper people inputs to calculate PMV comfort

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#379]
Gregor wanted to use this, thought it should be needed by everyone. Could write measure short term, but maybe need to expand object.

What do you all think. @asparke2 @macumber @kbenne

**Comment by evanweaver** [comment]
@DavidGoldwasser @asparke2 In speaking with David, he said that if we do choose to do this bug, we should lower it's importance to minor.  With that in mind, as well as Andrew's earlier comments, I would like to ask if this is a bug, or is it actually a case of good GUI design where we choose not to expose everything, and just expose what most people need most of the time.

If you both feel that this is a bug which should be worked on, I need an explicit list of methods to be exposed, and we should have a brief discussion on the design's layout before I code it.
