### ISSUE TITLE
getRunPeriodControlDaylightSavingTime

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio#3795]
When you call `model.getRunPeriodControlDaylightSavingTime` and the object doesn't already exist, this will create the object and assign default values. I feel like there should be a way to retrieve dst start/end dates without creating this object...

**Comment by jmarrec** [comment]
There's no way to do it.

```cpp
iddObject = m.getIddObject("OS:RunPeriodControl:DaylightSavingTime".to_IddObjectType).get
field = iddObject.getField(1).get
field.properties.stringDefault.empty?
=> true
```

The OpenStudio.idd doesn't have a default value, this value is implemented in the object's Ctor.

Here's a stupid workaround:

```
cleanup = false
if m.getObjectsByType("OS:RunPeriodControl:DaylightSavingTime".to_IddObjectType).empty?
  cleanup = true
end

rp = m.getRunPeriodControlDaylightSavingTime
start = rp.startDate
end = rp.endDate

if cleanup
  rp.remove
end
```
