### ISSUE TITLE
Openstudio 3.0.0 Sketchup Plugin

### ISSUE THREAD

**Issue by rmcclung** [NREL/OpenStudio#3797]
Neither OpenStudio SDK 3.0.0-pre1 or OpenStudio Application v1.0.0-pre1 appear to include any trace of the Sketchup plug-in.  

Judging by github.com/NREL/openstudio-sketchup-plugin/releases it seems maybe it's going to be a separate installation file, but using the file from March, Sketch-up is failing to load openstudio_modeleditor.rb.  Which is unsurprising, because is doesn't exist in either of the new openstudio versions

**Comment by tijcolem** [comment]
Yes, this is correct. The plans moving forward will be for users to install the OpenStudio SketchUp Plugin using the SketchUp extension dialog.  Users will need to first install SketchUp and OpenStudio, then a user can download the latest plugin release from https://github.com/NREL/openstudio-sketchup-plugin/releases and use SketchUp to install it.  As you noted, we are having an issue with the release from March and working on a fix.  See https://unmethours.com/question/41430/openstudio-100-pre-1-installation-problem/ for more details.

I guess the important thing to highlight here is this is the more traditional workflow to install SketchUp extensions and why we are choosing to adopt this method vs including it in the installer. Really, the eventual goal will be to distribute the OpenStudio plugin through the extension warehouse, which is the official distribution channel.

**Comment by tijcolem** [comment]
Update.  We have a fix in place for Windows.  Still addressing OSX.
