### ISSUE TITLE
Cannot successfully launch OS v1.0.0 (pre-release) using Ubuntu v16.04

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/OpenStudio#3798]
**Version**: OS Application v1.0.0 pre-release, Ubuntu version 

**Observed Behavior**:
User attempted to download and install OS Application v1.0.0.from https://github.com/NREL/OpenStudio/releases/download/v3.0.0-pre1/OpenStudioApplication-1.0.0-pre1.b212b2f088-Linux.deb

User first installed the OS Application on an Ubuntu 16.04 "bare metal" machine configured to run OS Server 2.9.0. Installation of the Application appeared to be successful. But, launching the Application from the Ubuntu Application Manager resulted in the OS icon appearing in the ribbon, pulsing slowly then disappearing from the ribbon completely. User un-installed the OS Application, and attempted to install the OS Application from a command prompt. The same behavior was observed. 

User then created a 'fresh' virtual machine using VMWare and installed / configured Ubuntu v16.04 on it. Once the Ubuntu v16.04 image was installed, the user upgraded all recommended applications to (most) current versions (12/3/2019). User then downloaded the OS Application and installed it on the upgraded version of Ubuntu v16.04. Installation of the OS Application on the VM (using the Ubuntu package manager) appeared to be successful. But launching the OS Application from the Ubuntu Application Manager resulted in the OS icon appearing in the ribbon, pulsing slowly then disappearing from the ribbon completely.  Same behavior as described above. 

**Expected Behavior**: Successful download, install and launching of the OS Application using a freshly installed and configured (updated) version of Ubuntu v16.04. 

User can re-create observed behavior in a shared gotomeeting, as needed.

**Comment by tijcolem** [comment]
The Ubuntu OS Application v1.0.0 pre-release is only supported on Ubuntu 18.04 and will not run out of the box on 16.04.  I believe there are ways to backport shared libs that are needed to run on 16.04 (untested), and I can attempt to share these with you if you have to run on 16.04. Otherwise, I'd recommend updating to 18.04.
