### ISSUE TITLE
EpwFile .getTimeSeries method fails if the weather file represents a leap year

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/OpenStudio#3801]
Steps to recreate bug:
1) get a weather file with a leap year (Feb 29)
2) Run:
```
weather_file = 'path/to/weather_file.epw'
epw = OpenStudio::EpwFile.new(weather_file)
epw.getTimeSeries('Dry Bulb Temperature')
```
Error:
```
[utilities.time.Date] <2> Bad Date: year = 2009, month = Feb(2), day = 29. 
C:/Users/mdahlhau/Desktop/EULP/analyze_weather.rb:17:in `getTimeSeries': C:\Users\jenkins\git\OpenStudio\openstudiocore\src\utilities\time\Date.cpp@446 : Bad Date: year = 2009, month = Feb(2), day = 29.  (RuntimeError)
```

**Comment by jmarrec** [comment]
EpwDataPoint doesn't include the year in its date:

https://github.com/NREL/OpenStudio/blob/a1449287fe7855d289d7dc80eb5aa474ef9de9f6/openstudiocore/src/utilities/filetypes/EpwFile.cpp#L1645

----

Found a couple of typos while investigating this:

https://github.com/NREL/OpenStudio/blob/a1449287fe7855d289d7dc80eb5aa474ef9de9f6/openstudiocore/src/utilities/filetypes/EpwFile.cpp#L4596

https://github.com/NREL/OpenStudio/blob/a1449287fe7855d289d7dc80eb5aa474ef9de9f6/openstudiocore/src/utilities/filetypes/EpwFile.cpp#L4617

**Comment by jmarrec** [comment]
@mdahlhausen If you need a workaround immediately:

```
# id = OpenStudio::EpwDataField.new("Dry Bulb Temperature")
# units = OpenStudio::EpwDataPoint::getUnits(id)
units = 'C'
dates = OpenStudio::DateTimeVector.new()
values = []

epw.data.each do |pt|
  dates << OpenStudio::DateTime.new(OpenStudio::Date.new(OpenStudio::MonthOfYear.new(pt.month), pt.day, pt.year), pt.time)             
  values << pt.dryBulbTemperature.get
  # or
  # values << pt.getField(id).get
end  

t = OpenStudio::TimeSeries.new(dates, OpenStudio::createVector(values), units)
```

**Comment by mdahlhausen** [comment]
Thanks @jmarrec.  I ended up just removing the leap year days from my weather files, but your method is more elegant.
