### ISSUE TITLE
clang-format script feedback and adjustments

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#3806]
#3721 fixed #3718, by adding a .clang-format file, and @tijcolem added as a pipeline on jenkins.

**Fully enforcing coding styles / passing clang-format test will require reformatting the entire codebase in one go** to avoid having diffs popping up in files you touched (since the script added on CI only diffs files you actually changed in your PR) but in areas of the file you didn't modify: this would clutter the diffs and therefore the review process.

**Before we resort to that, we should monitor closely what the clang-format script is proposing as changes on PRs that are open, and adjust the policies to better align with the coding style we do want to enforce. This issue is meant to centralize this feedback/tweaking.**

* If you do run ./ci/clang-format.sh locally on one of your PRs, please commit the result in a specific commit so we can inspect it easily and include it here for others to review.
* If you spot areas of improvements, please highlight them.

**Comment by jmarrec** [comment]
Not a huge fan of this change, I think it was clearer in the original:

![image](https://user-images.githubusercontent.com/5479063/70476133-60592580-1ad6-11ea-8464-d88b20a4a344.png)

**Comment by tijcolem** [comment]
Looks good @jmarrec We def want to get a list of things we like / dislike before we make the change to the entire code base. Ideally, we only want to do that once.

**Comment by tijcolem** [comment]
List of potential changes to clang
[x] LOG Warn

**Comment by jmarrec** [comment]
![image](https://user-images.githubusercontent.com/5479063/70801716-e6fc5400-1daf-11ea-91f3-f123bf3480f9.png)

```
-  boost::optional<SurfacePropertyOtherSideConditionsModel> surfacePropertyOtherSideConditionsModel = modelObject.surfacePropertyOtherSideConditionsModel();
-  if (surfacePropertyOtherSideConditionsModel){
+  boost::optional<SurfacePropertyOtherSideConditionsModel> surfacePropertyOtherSideConditionsModel =
+    modelObject.surfacePropertyOtherSideConditionsModel();
```

**Comment by jmarrec** [comment]
* Generally speaking, in cpp files we indent the blocks in namespace detail, which clang-format doesn't do (either it indents every namespace or indents none). Not sure how much we care about that....

```c++
namespace openstudio {
namespace model {

namespace detail {
  
  void XXX_Impl::twoSpacesIndent() {
    std::cout << "That's the only namespace where we indent!" << '\n';
  }
}

void XXX::noIndent() {
  getImpl<ImplType>()->xxx();
}

} // namespace model
} // namespace openstudio
```

**Comment by jmarrec** [comment]
![image](https://user-images.githubusercontent.com/5479063/70803663-e0bca680-1db4-11ea-8ceb-08d47948fa28.png)


-    ASSERT_TRUE(independentVariableListObject.getExtensibleGroup(0).getString(Table_IndependentVariableListExtensibleFields::IndependentVariableName));
+    ASSERT_TRUE(
+      independentVariableListObject.getExtensibleGroup(0).getString(Table_IndependentVariableListExtensibleFields::IndependentVariableName));
```

`EXPECT_EQ(independentVariableObject.nameString(),` could be on same line:

```
-    EXPECT_EQ(independentVariableObject.nameString(), independentVariableListObject.getExtensibleGroup(0).getString(Table_IndependentVariableListExtensibleFields::IndependentVariableName).get());
+    EXPECT_EQ(
+      independentVariableObject.nameString(),
+      independentVariableListObject.getExtensibleGroup(0).getString(Table_IndependentVariableListExtensibleFields::IndependentVariableName).get());
   }
```

**Comment by jmarrec** [comment]
@tijcolem When would be a good time to run clang format against the all codebase then enforce coding styles?

**Comment by tijcolem** [comment]
I'd like to at the PR count down as low as possible before updating the code base with new clang-format. In particular,#3950 as it touches so many files.

**Comment by tijcolem** [comment]
Well. everything compiles fine on all 3 platforms but the ctests are failing now. Looking into..
