### ISSUE TITLE
On Mac if you lose path to Load Library in OS App, you can't browse back to it.

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#381]
This is under the file menu in the OS app. On windows this is the path
"C:\Program Files (x86)\OpenStudio 1.0.0\share\openstudio\OSApp"

On Mac it is underneath the OS package. From finder you can open the package, but when browsing to it in OS app you can't open the package to get to the right path.

**Comment by jmarrec** [comment]
No longer true (I think). If I do "load library" and go select somewhere else on my disk. Then try again, it points me to the library folder again.

**Comment by evanweaver** [comment]
@DavidGoldwasser and @jmarrec are you two in agreement that this is no longer an issue and should be closed?

**Comment by jmarrec** [comment]
I do.

**Comment by evanweaver** [comment]
Thanks @jmarrec.
