### ISSUE TITLE
Year 2015 and beyond doesn't have an OpenStudio::EpwFile.startDateActualYear

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio#3815]

**Comment by jmarrec** [comment]
Could you provide context / steps to reproduce please? I touched EpwFile recently and there's nothing I noticed that would treat files after 2015 differently.

**Comment by joseph-robertson** [comment]
I was wrong here. I didn't see that openstudio throws "[openstudio.EpwFile] <0> Header start day of the week and actual start day of the week do not match in EPW file '<path>'. Data will be treated as typical (TMY)" if your start day of the week in the epw header is not the actual start day for that year.
