### ISSUE TITLE
GenerateClass script issues

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#382]
string and optional arguments should be passed in as const &

For fields that have a set/reset the set function should take a type T, not an optional<T>

**Comment by macumber** [comment]
https://docs.google.com/document/d/1lFGikWM0ufbe-kWNi9vRD_EfRZe-mcIc4fDxA61YynI/edit

**Comment by jmarrec** [comment]
https://github.com/jmarrec/OpenStudio/blob/2700a16d28ce7f8bf10cbdf16bfd1b1ac4263b31/developer/ruby/SubProjectClassGenerators/ModelClassGenerator.rb#L324-L344
