### ISSUE TITLE
Adjust Jenkins settings post branch rename

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#3822]
On cbci_jenkins_lib, the following renames happened: 

```
openstudio_incremental_develop => openstudio_incremental_2_9_X-LTS.groovy
openstudio_incremental_develop3 => openstudio_incremental_develop.groovy
```

On Jenkins, the `openstudio-incremental-develop` pipeline seems to be referencing Jenkinsfile_develop3, which points to a a groovy lib that doesn't exist anymore `openstudio_incremental_develop3()`:

https://github.com/NREL/OpenStudio/blob/93c4d4253cbf8cce5e87268e17584318fbdde95e/Jenkinsfile_develop3#L8

Thus producing build errors such as https://ci.commercialbuildings.dev/blue/organizations/jenkins/openstudio-incremental-develop/detail/PR-3821/2/pipeline/:

```
 > git fetch --no-tags --progress https://github.com/NREL/cbci_jenkins_libs.git +refs/heads/master:refs/remotes/origin/master
Checking out Revision 9564dd03bc91812e1b78374f484c7a150f002d5e (master)

java.lang.NoSuchMethodError: No such DSL method 'openstudio_incremental_develop3' found among step
```

-----

I suggest renaming the Jenkinsfile as well, to be something like:

* `Jenkinsfile_2_9_X-LTS` which would call `openstudio_incremental_2_9_X-LTS`
* `Jenkinsfile_develop` which would call `openstudio_incremental_develop`

**Comment by jmarrec** [comment]
@tijcolem 2.9.X-LTS still pointing to `openstudio_incremental_develop()` instead of `openstudio_incremental_2_9_X-LTS()` (and perhaps jenkinsfile should be renamed too)


https://github.com/NREL/OpenStudio/blob/8de135fac78eda3b58b8381aac1f966e2c4c3186/Jenkinsfile_develop#L8

**Comment by tijcolem** [comment]
Looks like the 2_9_X-LTS still had a copy of the old Jenkins_develop. This has been removed. So now we have the following for incremental builds in each respective branch: 

2_9_X-LTS
https://github.com/NREL/OpenStudio/blob/2.9.X-LTS/Jenkinsfile_2_9_X-LTS#L8

develop (3.x) 
https://github.com/NREL/OpenStudio/blob/develop/Jenkinsfile_develop#L8

It should be good now and okay to close this issue.

**Comment by jmarrec** [comment]
I supposed they could all have use the name "Jenkinsfile", just call the different groovy libs, but I'm fine with this!
