### ISSUE TITLE
Update conan dependencies to use Conan Center Index packages where available + Boost monolithic

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#3825]
Update conan dependencies to use Conan Center Index packages where available.

Use Boost monolithic to enable MSVC 2019.

Build suddenly broke on all platforms this morning due to websocketpp conan dependency, and I used a workaround in https://github.com/NREL/OpenStudio/pull/3821

I also opened https://github.com/bincrafters/community/issues/1069 where it was strongly recommended we update to use conan center index packages (and was given great advice).

**Comment by tijcolem** [comment]
Opening an issue #3828 a reminder to switch to CCI.
