### ISSUE TITLE
Version Compatibility Matrix Updates for SDK v3.0

### ISSUE THREAD

**Issue by craigers290** [NREL/OpenStudio#3830]
Moving forward the compatibility matrix should 
- drop the Sketchup reference (which would be referenced in App documentation)
- Possibly add the OS App version (although maybe that's dropped and the App documentation is responsible for referencing the appropriate "equivalent" SDK version)
- Possibly add Operating System Capatibility since there are specific limitations based on version that would be helpful to have spelled out in the matrix

https://github.com/NREL/OpenStudio/wiki/OpenStudio-Version-Compatibility-Matrix

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio/wiki/OpenStudio-SDK-Version-Compatibility-Matrix
