### ISSUE TITLE
New CLI command for `measure --new` and `measure --copy`

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#3831]
currently you need a GUI (PAT or OS App) to create new measures. The GUI uses the code here based on the measure type requested and then modifies class names UUID and other fields. 
https://github.com/NREL/OpenStudio/tree/develop/src/utilities/bcl/templates

It would be really helpful for the CLI to do this so a) you can make and copy measures without a GUI, and b) GUI's can rely on the CLI to do this so they don't have to re-create the functionality.

**Comment by corymosiman12** [comment]
+1

**Comment by tijcolem** [comment]
If this can be implemented in ruby would you @DavidGoldwasser be able to write the ruby script? If so I will assign this ticket to you @DavidGoldwasser and then we can use the script in the cli @kbenne

**Comment by DavidGoldwasser** [comment]
I think should be able to do it in a ruby script. It is basically copying the template, and then doing some substations, for classes, name, tests, etc. based on the user entered new measure name.

The GUI exposes a lot of things that can be later edited in measure.rb like description and modeler description. Here are I think the minimum required arguments to this method. I assume this would be saved to your "My Measures" directory if we have access to that.

New Measure
- New Measure Display Name (from this camel case for class and snake name for directory will be created)
- Measure Type (OpenStudio, EnergyPlus, Reporting) could default to OpenStudio and make this optional
- Taxonomy (e.g. Envelope > Form). While this can be changed later it is only in measure.xml and not measure.rb. Maybe we make it an optional argument with a default if the method isn't provided a value (Would type and bottom level be separate arguments, what if they provide invalid inputs?

Below is screenshot markup showing the minimum inputs to put in CLI shown on what is available in the OS App.
![Screen Shot 2020-01-10 at 11 42 34 AM](https://user-images.githubusercontent.com/4857055/72177699-7e000000-339e-11ea-92dc-aea6d5c2d602.png)


Copy Measure
- Directory Name (of measure to copy. Assuming we have access to "My Measure" directory we don't need full path as an argument, just the directory name)
- Copied Measure Display Name (from this camel case for class and snake name for directory will be created)

**Comment by eringold** [comment]
> currently you need a GUI (PAT or OS App) to create new measures

@DavidGoldwasser I don't think the above is strictly true. Since [BCLMeasure](https://github.com/NREL/OpenStudio/blob/develop/src/measure/Measure.i#L44) is SWIG'd, you can create a new measure with the Ruby bindings:
```
require 'openstudio'
OpenStudio::BCLMeasure.new(measureName, measureClassName, OpenStudio::Path.new(path), taxonomy, OpenStudio::MeasureType.new(type), description, modelDescription)
```

**Comment by DavidGoldwasser** [comment]
@eringold that is a nice idea, could streamline implementation into CLI using this.

**Comment by DavidGoldwasser** [comment]
Want to document current bug in this process, when some special characters are used in description or modeler description,  such as an apostrophe, it breaks the measure. This can be fixed by putting the `return` string for those two methods in the `measure.rb` to double quotes instead of single quotes.
