### ISSUE TITLE
Package OpenStudio 2.5 With Qt IFW v3 For Silent Windows Installation

### ISSUE THREAD

**Issue by mhickey3** [NREL/OpenStudio#3832]
Hi Team,

Can someone please package OpenStudio 2.5 with QTIFW 3 to enable a remote silent deployment?
Or could someone supply an MSI installer for OpenStudio 2.5 with silent install switches?

The goal is to enable a silent Windows deployment.

Best,
mhickey3

**Comment by jmarrec** [comment]
Hello @mhickey3, we'll consier using QtIFW 3 going foward. For now you can definitely still do a silent installation, you just need a small install_script.qs to pass to the installer.

I wrote one that for EnergyPlus that can be used as a base. You'll see that the most complicated stuff is in the component selection, but if you're fine with having all components installed (App, Sketchup Plugin, CLI, etc) then it can be really really simple. Take a look here: https://github.com/jmarrec/EnergyPlus/blob/7589_SilentInstall_QtIFW/cmake/qtifw/install_script.qs

**Comment by tijcolem** [comment]
QtIFW is installed in CI machines. Just need to update in CMakeList to update to use new version.

**Comment by jmarrec** [comment]
This is already enabled for 2.9, not sure what was used to build 2.5.0.

@mhickey3

Can you run this for me please? `OpenStudio-2.5.0.366cbe0e3a-Windows.exe  --framework-version`

And there's already an install.qs script here that you can use, I forgot about it: https://github.com/NREL/OpenStudio/blob/2.9.X-LTS/install.qs

You can enable gui.setSilent(true) on line 3, and customize line 14 to 24 to unselect components you do not need.. Place this file next to the installer (or maintenancetool.exe for uninstall):

```shell
OpenStudio-2.5.0.366cbe0e3a-Windows.exe --verbose --script install_script.qs AllUsers=true`

# Uninstall
cd C:\openstudio-2.5.0\
maintenancetool.exe --script install_script.qs AllUsers=true
```

**Comment by jmarrec** [comment]
```
C:\Users\julien\Downloads>OpenStudio-2.5.0.366cbe0e3a-Windows.exe --framework-version
C:\Users\julien\Downloads>2.0.3
C:\Users\julien\Downloads>OpenStudio-2.7.0.544f363db5-Windows.exe --framework-version
C:\Users\julien\Downloads>2.0.3
C:\Users\julien\Downloads>OpenStudio-2.9.0.801faa459c-Windows.exe --framework-version
C:\Users\julien\Downloads>2.0.3
C:\Users\julien\Downloads>OpenStudio-2.9.1.3472e8b799-Windows.exe --framework-version
C:\Users\julien\Downloads>2.0.3
```

@tijcolem so yeah, windows is still using QtIFW 2.x, unlike Ubuntu (and probably mac). This does need to be brought up to 3.1.1 for consistency (and enabling gui.setSilent)
