### ISSUE TITLE
HeatPumpWaterToWaterEquationFit fields cause crash during forward translation

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#3837]
The `Companion Cooling/Heating Heat Pump Name` fields in the `HeatPumpWaterToWaterEquationFit*` objects cause several problems when a model has one cooling and one heating object that both reference each other. See code below and note that they must be connected to plant loops and both must reference each other. Removing one reference will fix the issue, but they should be able to according to the EnergyPlus `WWHPSimpleAuto.idf`. I suspect it's a recursion issue introduced in #3690.

FYI @jmarrec

2.9.0 OSM = [18154-Proposed.txt](https://github.com/NREL/OpenStudio/files/4041781/18154-Proposed.txt)

---

In the app, a model (1) will crash if a measure is added because of FT and (2) will never run EnergyPlus.

![image](https://user-images.githubusercontent.com/8397034/72091804-3dd14c80-32ce-11ea-9225-069e2d80ecae.png)

![image](https://user-images.githubusercontent.com/8397034/72091708-08c4fa00-32ce-11ea-92af-0f8df43285d6.png)

---

```
require 'openstudio'
include OpenStudio::Model

error = false

model = Model.new

plant_loop_cup_clg = PlantLoop.new(model)
plant_loop_cup_htg = PlantLoop.new(model)
plant_loop_wwhp_clg = PlantLoop.new(model)
plant_loop_wwhp_htg = PlantLoop.new(model)

wwhp_clg = HeatPumpWaterToWaterEquationFitCooling.new(model)
wwhp_htg = HeatPumpWaterToWaterEquationFitHeating.new(model)

plant_loop_cup_clg.addDemandBranchForComponent(wwhp_clg)
plant_loop_wwhp_clg.addSupplyBranchForComponent(wwhp_clg)

plant_loop_cup_htg.addDemandBranchForComponent(wwhp_htg)
plant_loop_wwhp_htg.addSupplyBranchForComponent(wwhp_htg)

if error
  wwhp_clg.setCompanionHeatingHeatPump(wwhp_htg)
  wwhp_htg.setCompanionCoolingHeatPump(wwhp_clg)
end
  
translator = OpenStudio::EnergyPlus::ForwardTranslator.new()
workspace = translator.translateModel(model)
```

If `error = true` above, the FT results in `SystemStackError: stack level too deep`

**Comment by jmarrec** [comment]
#3690 is a just a hvac_library change.

But it is a recursion issue. The FTs call each other:

https://github.com/NREL/OpenStudio/blob/develop/src/energyplus/ForwardTranslator/ForwardTranslateHeatPumpWaterToWaterEquationFitHeating.cpp#L183

https://github.com/NREL/OpenStudio/blob/728a249e61818e66868c78723fb93cbb570fdab7/src/energyplus/ForwardTranslator/ForwardTranslateHeatPumpWaterToWaterEquationFitCooling.cpp#L182

**Comment by joseph-robertson** [comment]
@jmarrec Do we also want a functional test in OpenStudio-resources for this?

**Comment by jmarrec** [comment]
Yeah this is only being tested for in autosize_hvac, so I'd say it's probably a good time to add a test for HeatPumpWaterToWaterEquationFitCooling/Heating  indeed
