### ISSUE TITLE
Support EnergyPlus Python plugins (Python EMS)

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#3839]
New EnergyPlus release will have preliminary Python plugin capabilities.

@Myoldmopar

**Comment by jmarrec** [comment]
I'd like for this to be implemented. Could we discuss putting it on the roadmap? 

Supporting the PythonPlugin as a replacement to EMS would be actually quite simple (unless I'm mistaken), and very similar to ScheduleFile, it's just a matter of moving the referenced python file around when running the sim

**Comment by chrisbalbach** [comment]
+1

**Comment by joseph-robertson** [comment]
Moved remaining items to https://github.com/NREL/OpenStudio/issues/4634.
