### ISSUE TITLE
Sun/Wind exposure defaults for walls/ceilings when OtherSideCoefficients outside boundary condition is set

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#3840]
Setting a surface outside boundary condition to 'OtherSideCoefficients' will reset that surface's Sun and Wind Exposure to defaults:

https://github.com/NREL/OpenStudio/blob/2c4dd5c9d790d1e1a019b328ca06957660733478/src/model/Surface.cpp#L915-L931

For surfaces other than floors, this will set them to be 'SunExposed/WindExposed':

https://github.com/NREL/OpenStudio/blob/2c4dd5c9d790d1e1a019b328ca06957660733478/src/model/Surface.cpp#L1278-L1345

EnergyPlus will ignore solar effects for surfaces with OtherSideCoefficients, but will write a warning for each surface. I'm not sure if the same is true for wind effects. However, if a user is defining OtherSideCoefficients, shouldn't their choices for sun/wind exposure be retained and not reset?

**Comment by kbenne** [comment]
@kbenne write a unit test for this and then @mpraprost can work within that

**Comment by jmarrec** [comment]
Fixed va #3867 and #3916
