### ISSUE TITLE
Debugging output in results measure

### ISSUE THREAD

**Issue by jasondegraw** [NREL/OpenStudio#3843]
I'm not sure where to leave this, possibly it has already been fixed but I can't tell. So I'll leave it here. When running in the app (2.91), I noticed that the [results measure (it might be line 3095 here)](https://github.com/NREL/OpenStudio-measures/blob/develop/nrel_published/openstudio_results/resources/os_lib_reporting.rb#L3095) is adding some "informative" greetings to the output. I normally run from scripts, and I have no idea if it shows up anyplace else.

![orz](https://user-images.githubusercontent.com/4623433/72381133-d6a80380-36e4-11ea-8071-328299a889e8.png)

**Comment by DavidGoldwasser** [comment]
Thanks @jasondegraw I have another fix I'm working on in that measure, I'll make sure to remove this looking. I am the culprit from that, I was working on binning of zone temp and humidity table.

**Comment by DavidGoldwasser** [comment]
I have this fixed in this branch. It will be merged soon and then pushed to BCL
https://github.com/NREL/OpenStudio-measures/tree/openstudio_results_warning_table
