### ISSUE TITLE
autosize ZoneHVACUnitHeater Maximum Hot Water Flow Rate

### ISSUE THREAD

**Issue by MingboPeng** [NREL/OpenStudio#3854]
It seems by default when ZoneHVACUnitHeater is created by API, its field "Maximum Hot Water Flow Rate" is set to empty, instead of "autosize". 

By checking this ZoneHVACUnitHeater in OS APP, this field is also not set to "autosize". This causes the ZoneHVACUnitHeater not running correctly with an empty value of "Maximum Hot Water Flow Rate".

![image](https://user-images.githubusercontent.com/9031066/72699469-867ed600-3b16-11ea-81cb-ae5b798503e9.png)

It would be great to make this "Maximum Hot Water Flow Rate" autosize by default.

Thanks,
Mingbo

**Comment by jmarrec** [comment]
Thanks for the catch @MingboPeng. Will address this shortly.
