### ISSUE TITLE
PAT crashes if I have SQL file open in ResultsViewer and then load a new baseline model

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#386]
I ran analysis, opened baseline SQL file in ResultsViewer then loaded a new baseline model into the project.

**Comment by macumber** [comment]
I don't get this crash anymore, I do see this dialog which is expected
![2-23-2015 2-46-53 pm](https://cloud.githubusercontent.com/assets/1327850/6338274/e8683086-bb6a-11e4-82f5-3dccda91497d.jpg)

**Comment by DavidGoldwasser** [comment]
@macumber I'm fine closing it based on your test. That was a pretty stale bug.
