### ISSUE TITLE
Incorrect Field Name in PeopleDefinition in OS App

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#387]
In the OS App, the field currently labeled "Sensible Heat Fraction Radiant" should simply be labeled "Sensible Heat Fraction"
![people_def_bug](https://f.cloud.github.com/assets/2009290/844182/2d201178-f3ce-11e2-9448-cc43dd7f5d58.PNG)

**Comment by evanweaver** [comment]
Fixed via Pivotal 90020870
