### ISSUE TITLE
OpenStudio ClimateZones initialization behavior and .clear behavior are inconsistent

### ISSUE THREAD

**Issue by pflaumingo** [NREL/OpenStudio#3870]
When initializing an OpenStudio Model, it creates a blank ClimateZone object as can be seen here: 

https://github.com/NREL/OpenStudio/blob/da39c25c4d5a0a561457f25971513b8f9665dbaa/src/model/ClimateZones.cpp#L538-L545

A call to model.getClimateZones.numClimateZones therefore returns 1. However, if .clear is called, it removes the blank ClimateZone and numClimateZones equals 0. I think these behaviors should be consistent. If it's initialized with a ClimateZone it's suggestive that OpenStudio needs one, but if OpenStudio doesn't need one (I'm not aware of a reason it does) then we should consider removing the addition during initialization.

The issue I'm having is when doing some state verification because if I don't add a climate zone it's length is 1, but if I add only 1 climate zone its length remains as 1.

**Comment by shorowit** [comment]
Here's one way you can detect the number of climate zones without triggering OS to create one.

```
irb(main):001:0> require 'openstudio'
=> true
irb(main):003:0> m = OpenStudio::Model::Model.new
=> #<OpenStudio::Model::Model:0x00000006676aa0 @__swigtype__="_p_openstudio__model__Model">
irb(main):004:0> m.getObjectsByType("OS:ClimateZones".to_IddObjectType).size
=> 0
irb(main):005:0> m.getClimateZones
=> #<OpenStudio::Model::ClimateZones:0x0000000643bce0 @__swigtype__="_p_openstudio__model__ClimateZones">
irb(main):006:0> m.getObjectsByType("OS:ClimateZones".to_IddObjectType).size
=> 1
```

**Comment by pflaumingo** [comment]
Thanks for sharing @shorowit, I may use that short term but it still doesn't address the bigger issue.

**Comment by jmarrec** [comment]
This has been here since the dawn of the git history on this repo.
There's a variety of things that are wrong about this object.

The fields that prompted this pushExtensibleGroups are actually deprecated:

```
OS:ClimateZones,
       \unique-object
       \extensible:4
       \min-fields 7
  A1, \field Handle
       \type handle
       \required-field
  A2, \field Active Institution
       \deprecated
       \type alpha
       \default ASHRAE
  N1, \field Active Year
       \deprecated
       \type integer
       \minimum 0
       \default 2006
  A3, \field Climate Zone Institution Name
       \type alpha
       \begin-extensible
       \default ASHRAE
  A4, \field Climate Zone Document Name
       \type alpha
       \default ANSI/ASHRAE Standard 169
  N2, \field Climate Zone Document Year
       \type integer
       \minimum 0
       \default 2006
  A5; \field Climate Zone Value
       \type alpha
       \required-field
```

It doesn't dump correctly, cf the first group is lacking "ASHRAE" for Institution Name (and doc name and default year)
```
m = Model.new
c = m.getClimateZones
c.setClimateZone("ASHRAE", "1A")
c.setClimateZone("CEC", "1A")
c.setClimateZone("COUCOU", "HELLO")

puts c
OS:ClimateZones,
  {57b38793-4be4-42c6-926b-067049b9fae5}, !- Handle
  ,                                       !- Active Institution
  ,                                       !- Active Year
  ,                                       !- Climate Zone Institution Name 1
  ,                                       !- Climate Zone Document Name 1
  ,                                       !- Climate Zone Document Year 1
  1A,                                     !- Climate Zone Value 1
  CEC,                                    !- Climate Zone Institution Name 2
  California Climate Zone Descriptions,   !- Climate Zone Document Name 2
  1995,                                   !- Climate Zone Document Year 2
  1A,                                     !- Climate Zone Value 2
  COUCOU,                                 !- Climate Zone Institution Name 3
  ,                                       !- Climate Zone Document Name 3
  0,                                      !- Climate Zone Document Year 3
  HELLO;                                  !- Climate Zone Value 3
```

There's no real reason this would be a single object with extensible groups, rather it could just be `OS:ClimateZone` and we could have several. Or if we actually wanted to limit that to ASHRAE and CEC, then just implement one unique class for each.

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio/blob/2d10c15203ce8d8f22ef4bd853ad7f8d2ff84fd0/src/model/test/ClimateZones_GTest.cpp#L51-L65
