### ISSUE TITLE
Adding advanced output variables to sdk

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio#3872]
"Do you know if os is supporting adding advanced output variables, eg. https://bigladdersoftware.com/epx/docs/9-2/input-output-reference/group-thermal-zone-description-geometry.html#additional-window-outputs-advanced ? I looked up in sdk docs, without luck to find a similar functionality. In E+, if we add an object of : Output:Diagnostics,DisplayAdvancedReportVariables , E+will know we want those additional variables, and allow specifying those variables in Output:Variable objects."

**Comment by shorowit** [comment]
Pretty sure it's not supported. There is an EnergyPlus BCL measure that handles this: https://bcl.nrel.gov/node/39191

Would definitely be nice to move it into the SDK.

**Comment by jmarrec** [comment]
It's not supported, but real easy to add to the SDK. It's also really easy to create measures for that, but I suppose depending on your workflow that might be annoying versus adding them at model time.

In case we want them in the model API, I would go ahead and add all of these small control/diag unique objects at the same time:

```
Output:Diagnostics
Output:DebuggingData
Output:JSON
```

**Comment by shorowit** [comment]
Our problem is that we want to use some of the Output:Variables that Output:Diagnostics provides access to in an EMS program. We can make everything work as is, but then our OpenStudio measure will depend on an EnergyPlus measure having to be run in the same workflow. So it'd be far more ideal to have access to the Output:Diagnostics object in the model.

@jmarrec That would be great if you could implement these! Note that Output:Diagnostics is not a unique object in EnergyPlus land: you can have multiple of the object in your IDF, and for each instance, you can specify up to 2 values (each from the same set of enum choices). What a weird object. I'd be fine with OpenStudio simplifying it.

**Comment by jmarrec** [comment]
@shorowit I checked E+ code, I think it'll work just fine with one `Output:Diagnostics` that has N (N pteotnially >2) extensible fields, but I'll have to actually try.

Output:DebuggingData is even worse FYI. It uses a numeric value for a boolean, instead of `\type choice` with "Yes"/"No" keys.

Anyways, check out PR #3876 if you want to try early.

**Comment by shorowit** [comment]
@jmarrec I was going to grab the CI build but it looks like the Windows build is failing?

**Comment by jmarrec** [comment]
Something happening in csharp hence why I didn't see it on ubuntu. Will fix it, thanks CI!
