### ISSUE TITLE
SpaceInfiltrationDesignFlowRate DesignFlowRateCalculationMethod API magic does not work for Flow/ExteriorWallArea case

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#3880]
Issue overview
--------------
The API magic for the SpaceInfiltrationDesignFlowRate class' DesignFlowRateCalculationMethod field does not handle the `Flow/ExteriorWallArea` case. Currently there isn't a setter for `DesignFlowRateCalculationMethod` in the [SDK](https://s3.amazonaws.com/openstudio-sdk-documentation/cpp/OpenStudio-2.9.0-doc/model/html/classopenstudio_1_1model_1_1_space_infiltration_design_flow_rate.html). 

## Current Behavior
The `setFlowperExteriorSurfaceArea` method changes the `DesignFlowRateCalculationMethod` field to `Flow/ExteriorArea`. However, the user's intent could be `Flow/ExteriorWallArea`. One common use case is 90.1 G3.1.1.4.

## Expected Behavior
See below.

## Steps to Reproduce
```
require 'openstudio'
include OpenStudio::Model

m = Model.new

sidfr_floor = SpaceInfiltrationDesignFlowRate.new(m)
sidfr_wall = SpaceInfiltrationDesignFlowRate.new(m)

puts m, ''

sidfr_floor.setFlowperSpaceFloorArea(0.1)
sidfr_wall.setFlowperExteriorSurfaceArea(0.1)

puts m
```

## Possible Solution
Add a `Flow per Exterior Wall Area` field and magic to set `DesignFlowRateCalculationMethod` to `Flow/ExteriorWallArea`. 

Alternatively, this could be moved to an EnergyPlus issue to add the same field because it seems inconsistent with other EnergyPlus object's behavior with choice fields. 

### Environment
 - Platform (Operating system, version): Windows 10
 - Version of OpenStudio (if using an intermediate build, include SHA): 2.9.0

### Context
Models are generally very sensitive to infiltration so this issue could significantly affect energy results.

**Comment by jmarrec** [comment]
Is that a new choice in E+? Did you check OpenStudio.idd to see if its already there?

**Comment by MatthewSteen** [comment]
@jmarrec it's not and is already in the OpenStudio.idd. 

https://bigladdersoftware.com/epx/docs/8-2/input-output-reference/group-airflow.html#field-flow-per-exterior-surface-area

**Comment by MatthewSteen** [comment]
@jmarrec this might be more appropriate as an EnergyPlus issue because it's inconsistent with most other objects that use choice fields, i.e. only one field is used depending on a preceding choice field.

**Comment by jmarrec** [comment]
@MatthewSteen what doesn't work here?

```
sidfr_wall.setFlowperExteriorWallArea(0.2)
puts sidfr_wall
OS:SpaceInfiltration:DesignFlowRate,
  {ac3dbc68-2e37-474f-bcfb-5b00fc1dceea}, !- Handle
  Space Infiltration Design Flow Rate 2,  !- Name
  ,                                       !- Space or SpaceType Name
  ,                                       !- Schedule Name
  Flow/ExteriorWallArea,                  !- Design Flow Rate Calculation Method
  ,                                       !- Design Flow Rate {m3/s}
  ,                                       !- Flow per Space Floor Area {m3/s-m2}
  0.2,                                    !- Flow per Exterior Surface Area {m3/s-m2}
  ,                                       !- Air Changes per Hour {1/hr}
  ,                                       !- Constant Term Coefficient
  ,                                       !- Temperature Term Coefficient
  ,                                       !- Velocity Term Coefficient
  ;                                       !- Velocity Squared Term Coefficient
```

**Comment by MatthewSteen** [comment]
@jmarrec ah, I missed the `setFlowperExteriorWallArea` method, which does work, thanks.
