### ISSUE TITLE
Change end use (gas) energy between OS 2.8.1 and 2.9.1

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#3881]
The issue comes when we upgraded OpenStudio version from 2.8.1  to 2.9.1 since gas annual consumption is ~25% different ( 642 with 2.8.1 vs 467 in 2.9.1). I tried to investigate the issue and see that the ZoneHVAC:EquipmentList object was differently forward translated between 2 versions (left 2.9.1 vs right 2.8.1 as screenshoot). I updated the run folder in.idf from 9.1 to 9.2 using EnergyPlus then ran it directly the result came back to normal. I can submit the issue to OpenStudio Github but the project info would be exposed publicly. Please help me how to progress this issue further. 

Thanks,
Khanh
 
![Picture1](https://user-images.githubusercontent.com/707488/74692219-dac7b500-51ab-11ea-942e-963e67ac8601.png)

**JM: I saved the runfiles, can ask if needed again**

**Comment by wta12** [comment]
There might be 2 separated issues: 
- Gas EndUse as seen in report 
- Updated file from 2.8.1 doesn't automatically set the fraction schedule in  ZoneHVAC:EquipmentList field as EP 9.2 updated.

**Comment by jmarrec** [comment]
I am going to investigate a bit more because this is concerning, but I doubt this has anything to do with OpenStudio itself.

* E+ I/O ref guide for [Zone Equipment <x> Sequential Cooling Fraction Schedule Name](https://bigladdersoftware.com/epx/docs/9-2/input-output-reference/group-zone-equipment.html#field-zone-equipment-x-sequential-cooling-fraction)
    > References a schedule that specifies the fraction of the remaining cooling load this equipment will attempt to serve. Only applies if the load distribution scheme is SequentialLoad. Leaving this blank indicates a constant schedule of 1.0.

* OpenStudio `VersionTranslator::update_2_8_1_to_2_9_0` has correct rules (IMHO):
  * Note: the fields for Sequential Cooling/Heating fractions have been changed from numeric in E+ 9.1.0 to a schedule in 9.2.0
   * If sequential cooling fraction was blank, leave blank
   * Otherwise, take the numeric value, and create Schedule:Constant with it
https://github.com/NREL/OpenStudio/blob/04b65b87ef42bab80ff17386d68edebc50248cf4/src/osversion/VersionTranslator.cpp#L4548-L4594

**Comment by jmarrec** [comment]
So I took your in_Os291.osm model, ran it.

Then I added Sequential fraction schedules to ALL zoneHVACEqList (always 1), like E+ would have done (because OpenStudio used to write "1" if blank during FT to IDF). *See script below**. I ran that in 2.9.1 (E+ 9.2.0) as well: **zero differences**.

```
require 'openstudio'

include OpenStudio::Model

# Helper to load a model in one line
# It will raise if the path (or the model) isn't valid
#
# @param path [String] The path to the osm
# @return [OpenStudio::Model::Model] the resulting model.
def osload(path)
  translator = OpenStudio::OSVersion::VersionTranslator.new
  ospath = OpenStudio::Path.new(path)
  model = translator.loadModel(ospath)
  if model.empty?
      raise "Path '#{path}' is not a valid path to an OpenStudio Model"
  else
      model = model.get
  end
  return model
end

m = osload('in_Os291.osm')

# I could use m.alwaysOnContinuousSchedule, but let's be explicit
# Create a Schedule Type Limtis and a Schedule:Constant of always one
sch_type_lim = ScheduleTypeLimits.new(m)
sch_type_lim.setName("ZoneEqList ScheduleTypeLimts")
sch_type_lim.setLowerLimitValue(0)
sch_type_lim.setUpperLimitValue(1)
sch_type_lim.setNumericType("Continuous")

seq_sch = ScheduleConstant.new(m)
seq_sch.setScheduleTypeLimits(sch_type_lim)
seq_sch.setName("Always 1 Sequential Fraction Schedule")
seq_sch.setValue(1.0)

# Assign the always 1 schedule as sequential cooling/heating fraction schedule
# for all equipments
m.getThermalZones.each do |z|
  z.equipment.each do |eq|
    z.setSequentialCoolingFractionSchedule(eq, seq_sch)
    z.setSequentialHeatingFractionSchedule(eq, seq_sch)
  end
end

# Save under a new name
m.save('in_Os291_with_sequential_sch.osm', true)

```

**Comment by jmarrec** [comment]
**Ok, here's the actual difference: it's in the way the "Air Wall" is handled.**

I took your `in_Updated_EP_92.idf` (from the E+ Transition utility), and modified this:

```
Construction,
  Air Wall,                               !- Name
  Air Wall Material 1;                    !- Layer 1

Material,
  Air Wall Material 1,                    !- Name
  MediumSmooth,                           !- Roughness
  0.01,                                   !- Thickness {m}
  0.6,                                    !- Conductivity {W/m-K}
  800,                                    !- Density {kg/m3}
  1000,                                   !- Specific Heat {J/kg-K}
  0.95,                                   !- Thermal Absorptance
  0.7,                                    !- Solar Absorptance
  0.7;                                    !- Visible Absorptance
```

And replace it with what the 291 IDF had (except it's called `Air Wall_ConstructionAirBoundary`):

```
Construction:AirBoundary,
  Air Wall,                                      !- Name
  GroupedZones,                           !- Solar and Daylighting Method
  GroupedZones,                           !- Radiant Exchange Method
  None,                                   !- Air Exchange Method
  0;                                      !- Simple Mixing Air Changes per Hour {1/hr}
```

And now the results match as well.

**Comment by wta12** [comment]
@jmarrec : Thanks for doing reverse check.  Maybe I would run report to check zone heat transfer and load prediction to confirm this root.
In addition, can you import E+.idd from EP 9.1 installation ? I get error when import Idd file when tried to compare 2 idfs ?
```
idd_path = 'App/Run/EnergyPlus/9_1/Energy+.idd'
OpenStudio::IddFile::load(idd_path ).get
[utilities.idd.IddField] <2> Unknown field property text ') allowed in name' detected in field 'Name'
[utilities.idd.IddObject] <2> Cannot parse IddField text 'A1 , \field Name\required-field\type alpha\note This name becomes a variable for use in Erl programs\note no spaces or other special characters (-,+,/,\) allowed in name'.
[utilities.idd.IddFile] <2> Unable to construct IddObject from text: 
EnergyManagementSystem:Actuator,\memo Hardware portion of EMS used to set up actuators in the model\min-fields 4A1 , \field Name\required-field\type alpha\note This name becomes a variable for use in Erl programs\note no spaces or other special characters (-,+,/,\) allowed in nameA2 , \field Actuated Component Unique Name\required-field\type alphaA3 , \field Actuated Component Type\required-field\type alphaA4 ; \field Actuated Component Control Type\required-field\type alpha
```

**Comment by jmarrec** [comment]
We make some changes to our included ProposedEnergy+.idd to match our needs as well as ensure it can be parsed. Here you see the "problem" is that the `\note` has special characters `(-,+,/,\)` which makes the parsing fail.

I suggest taking our ProposedEnergy+.idd from 2.8.1 (which used E+ 9.1) here instead: https://github.com/NREL/OpenStudio/blob/v2.8.1/openstudiocore/resources/energyplus/ProposedEnergy%2B.idd

I think this issue should be closed, as we cannot do much about it. Do you agree @wta12?

**Comment by wta12** [comment]
@jmarrec : At the end, that's an input or engine issue? I did not rerun but as long as a workaround viable - I am ok. Just ring me when new versions of OS/EP change airwall object input - Thanks for promptly response

**Comment by jmarrec** [comment]
The change was in 2.9.0. It's unlikely going to change again.
