### ISSUE TITLE
Allow "CorrelationFromWeatherFile" for SiteWaterMainsTemperature's calculation method

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#3885]
Enhancement Request
--------------
Make the calculation method "CorrelationFromWeatherFile" available for the SiteWaterMainsTemperature object in the SDK.

## Detailed Description
Currently OpenStudio only supports "Schedule" and "Correlation". The "CorrelationFromWeatherFile" calculation method choice was made available in E+ v9.0. See https://github.com/NREL/EnergyPlus/pull/6771

**Comment by joseph-robertson** [comment]
Looks like someone may have added this since 2.9.1. I'm going to build develop and see if it works.

@shorowit
