### ISSUE TITLE
Wrap SimulationControl's Do HVAC Sizing Simulation for Sizing Periods

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#3892]
Make EnergyPlus's "Do HVAC Sizing Simulation for Sizing Periods" field in the Simulation Control object available in the SDK.

I also happened to notice that the SizingPlant object has a [setSizingOption](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-2.9.0-doc/model/html/classopenstudio_1_1model_1_1_sizing_plant.html#a85922c0e610aa827f46dadb4fd7f90cd) field wrapped, but the IDD for this field has a note that "if Coincident is chosen, then sizing is based on HVAC Sizing Simulations and the input field called Do HVAC Sizing Simulation for Sizing Periods in SimulationControl must be set to Yes". So presumably "Coincident" is not currently supported.

**Comment by jmarrec** [comment]
Add to end of "OS:SimulationControl":

```
  N5, \field Minimum Number of Warmup Days
  [...]
  A8, \field Do HVAC Sizing Simulation for Sizing Periods
      \note If Yes, SizingPeriod:* objects are exectuted additional times for advanced sizing.
      \note Currently limited to use with coincident plant sizing, see Sizing:Plant object
      \type choice
      \key Yes
      \key No
      \default No
  N6; \field Maximum Number of HVAC Sizing Simulation Passes
      \note the entire set of SizingPeriod:* objects may be repeated to fine tune size results
      \note this input sets a limit on the number of passes that the sizing algorithms can repeate the set
      \type integer
      \minimum 1
      \default 1
```
