### ISSUE TITLE
Errors on push pull operation (Bugzilla #303)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#39]
On 2011-10-04 12:09:15, @DavidGoldwasser wrote:

> When I do push pull operations either the new surface or the adjoining surface isn't rendering correctly when you make a new surface. In my testing when classifying was correct, one of the old surfaces losing its link to rendering modes. When the classification is incorrect, it is the new surface that doesn't change render modes correctly (I expect the classification issue is more of a byproduct of same issue rather than cause. Two screenshots attached. I can show you this more tomorrow.

On 2011-10-04 12:10:24, @DavidGoldwasser wrote:

> Created an attachment (id=34)
> render by class

On 2011-10-04 12:10:52, @DavidGoldwasser wrote:

> Created an attachment (id=35)
> render by boundary

On 2011-10-04 22:17:57, @macumber wrote:

> I'm having trouble reproducing, I know this has been an issue in the past

On 2011-11-16 09:50:38, @DavidGoldwasser wrote:

> <batch change comment> Moving older bugs to "retest" milestone. Will re-test these and then assign to appropriate milestone. These were all 0.6.0 prior to change.

On 2011-11-17 10:41:36, @lgentile wrote:

> Still potential issue. This was an old bug. Please re-test/verify.

On 2012-01-17 10:28:39, @DavidGoldwasser wrote:

> Dan, just re-tested and this is still an issue. Try splitting and using push pull 10 times or so and you should hit this issue (seems kind of random. Selecting the surfaces responds to the inspector, they just don't render correctly, yet things are fine when you re-open.

On 2012-01-17 10:30:19, @DavidGoldwasser wrote:

> Created an attachment (id=133)
> Screenshot after multiple split/push pull operations

Original attachments:
* pushpull01.png (ID 34)
* pushpull02.png (ID 35)
* bug303_0117.png (ID 133)

Keywords: Random, SyncWithSU

**Comment by DavidGoldwasser** [comment]
This has been fixed.
