### ISSUE TITLE
E+ 9.3.0: Support new field 'Minimum Air Flow Turndown Schedule Name' for AirTerminals

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#3906]
Enhancement Request
--------------

* ATU got a new field at end `Minimum Air Flow Turndown Schedule Name` : 
    * `AirTerminal:SingleDuct:VAV:HeatAndCool:NoReheat`, `AirTerminal:SingleDuct:ConstantVolume:Reheat`, `AirTerminal:SingleDuct:VAV:Reheat` , `AirTerminal:SingleDuct:VAV:HeatAndCool:Reheat`, `AirTerminal:DualDuct:VAV`
(`AirTerminal:SingleDuct:VAV:Reheat:VariableSpeedFan`)
* `AirTerminal:SingleDuct:Uncontrolled`, which was obsolete, is removed. This will not affect us as

**Comment by tijcolem** [comment]
@mdahlhausen. Would this be useful to get into the SDK?

**Comment by mdahlhausen** [comment]
@tijcolem yes, it would be nice to include this, but it isn't the highest priority.

**Comment by joseph-robertson** [comment]
`Minimum Air Flow Turndown Schedule Name`:
* `AirTerminal:SingleDuct:VAV:NoReheat`
* `AirTerminal:SingleDuct:VAV:Reheat`
* `AirTerminal:SingleDuct:VAV:Reheat:VariableSpeedFan`
* `AirTerminal:SingleDuct:VAV:HeatAndCool:NoReheat`
* `AirTerminal:SingleDuct:VAV:HeatAndCool:Reheat`
* `AirTerminal:DualDuct:VAV`
