### ISSUE TITLE
E+ 9.3.0: Support new object Coil:Cooling:DX and related

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#3907]
Enhancement Request
--------------

- `Coil:Cooling:DX`
- `Coil:Cooling:DX:CurveFit:Performance`
- `Coil:Cooling:DX:CurveFit:OperatingMode`
- `Coil:Cooling:DX:CurveFit:Speed`

Design doc: https://docs.google.com/document/d/1zDVgX5KFjjPxpSEbblYtxYh-Kpy7-ue45ZRgG8RjXAw/edit?usp=sharing

**Comment by kbenne** [comment]
@joseph-robertson here is the task for adding the new dx coil model. @jmarrec I think @joseph-robertson is going to take point on this, but you might be able to advise if issues come up.

cc @tijcolem

**Comment by joseph-robertson** [comment]
What about `Coil:Cooling:DX:CurveFit:Speed`?

**Comment by joseph-robertson** [comment]
I don't see any of these objects listed in the IO reference: https://bigladdersoftware.com/epx/docs/9-3/input-output-reference/index.html. Anyone have any idea about that?

@kbenne @jmarrec

**Comment by shorowit** [comment]
@joseph-robertson Seems like a bug in Big Ladder's documentation. If you download E+, they are in the pdf -- at the very end of "Group Heating and Cooling Coils".

**Comment by shorowit** [comment]
It's missing from the Table of Contents but is here: https://bigladdersoftware.com/epx/docs/9-3/input-output-reference/group-coil-cooling-dx.html#coilcoolingdx
