### ISSUE TITLE
E+ 9.3.0: Update ShadowCalculation to match object refactor in EnergyPlus 

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#3908]
Issue overview
--------------

cf https://github.com/NREL/OpenStudio/pull/3904#discussion_r387789980

New field to be added in ShadowCalculation, and one field renamed with keys renamed + one field rename. Will need VT.

## Expected Behavior

Given the names, I think we should just break API otherwise it's going to be very confusing.

| Old                   | New                                         |
|-----------------------|---------------------------------------------|
| -                     | Shading Calculation Method                  |
| Calculation Method    | Shading Calculation Update Frequency Method |
| Calculation Frequency | Shading Calculation Update Frequency Method |

@kbenne @tijcolem thoughts?

**Comment by tijcolem** [comment]
This is okay but this needs to be highlighted in the release notes.

**Comment by tijcolem** [comment]
Can we see how the regression test look after this change?

**Comment by jmarrec** [comment]
Fixed via #3913
