### ISSUE TITLE
Documentation typo in 3.0-pre1 release notes

### ISSUE THREAD

**Issue by vtnate** [NREL/OpenStudio#3909]
Issue overview
--------------
In release notes for OS 3.0-pre1 a link isn't formatted properly. See last line of `Installation Steps` here: https://github.com/NREL/OpenStudio/releases

## Current Behavior
Link is cut off half way through

## Possible Solution
Move closing paren to the end of the link

**Comment by tijcolem** [comment]
Thanks @vtnate for pointing that out. The link is fixed.
