### ISSUE TITLE
Warn if openstudio cli tries to load a unsupported long path on windows

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#3925]
The openstudio cli allows a custom include path to be specified, and on Windows systems this path might exceed to the supported file path length. Please add a warning to the openstudio cli so that users know which file contains an unsupported path length.

**Comment by joseph-robertson** [comment]
@kbenne to point @joseph-robertson to applicable file(s).

**Comment by joseph-robertson** [comment]
@kbenne I'm having trouble reproducing this issue. My interpretation is that you cannot pass a path to `--include` that is "too long". However, how would I ever manually create a folder structure on my windows system that has at least one file whose path is "too long"? Windows won't permit me to do that. Can you suggest a strategy?

**Comment by jmarrec** [comment]
@joseph-robertson Windows will allow you to go over MAX_PATH (260 chars). It is opt-in though: https://superuser.com/questions/1119883/windows-10-enable-ntfs-long-paths-policy-option-missing

**Comment by jmarrec** [comment]
Given that https://github.com/NREL/OpenStudio/blob/7cec475621233fcd772de2c6715ef9252bcbb7a6/src/cli/openstudio_cli.rb#L350-L353

I would actually suggest we do nothing here. We're going to introduce several extra checks (if OS windows, if so, is dir.size > 260) to try and do better than what ruby does and for a windows feature that is "advanced" and already fails to work properly in a very very large variety of cases (even cmd.exe and windows explorer are too dumb to support long paths).

**Comment by kbenne** [comment]
ok. I'm hearing let's not try to be better than ruby because we will probably fail. Sounds like a solid argument. I'm going to close the issue since I'm the one that reported it. If someone has an idea and wants to attack the issue then that is cool, but until then... close.
