### ISSUE TITLE
SimulationControl object clean up

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#394]
https://github.com/NREL/OpenStudio/blob/a007b7801e3bb05731f012f585facdd814ef31fb/src/model/SimulationControl.hpp#L227-L228

Now that RunPeriod is unique and SqlFile upcases envPeriodName for us we can clean this up quite a bit 

https://github.com/NREL/OpenStudio/blob/a007b7801e3bb05731f012f585facdd814ef31fb/src/model/SimulationControl.hpp#L230-L240

**Comment by jmarrec** [comment]
I'm tempted to just close this one. We can't break API, so these would have to stay there. If we also implement one that does it for a single option, and if in the future we start supporting multiple sim periods, then the singular getter would become problematic to support.

@kbenne reopen if you disagree
