### ISSUE TITLE
When I split matched surfaces all both new surfaces still match the same surface

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#395]
What should happen is the three surfaces involved should all revert to outdoors. Also if a surface is already matched to "surface a" and you manually match a different surface to surface "a" a similar thing happens. This second scenario could impact changes made in OS app, but I expect very few people play with matched surfaces there.

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/39
