### ISSUE TITLE
Dynamically generate proposed idd

### ISSUE THREAD

**Issue by tijcolem** [NREL/OpenStudio#3962]
E+ expands the extensible fields even with it uses the \begin-extensible code for the benefit of idfeditor. One idea is to leave the fields expanded in the proposed idd just like they are in E+, but make our code generator smart enough to detect the situation and not generate enums for all of those fields. I guess another option which Tim and I did not talk about it is enhancing idf editor to not require the extensible to be fully expanded, and then "fix" the EnergyPlus idd

**Comment by jmarrec** [comment]
## Differences

* \min-fields is missing in a lot of cases (that could be brought over to E+ without too much trouble)
* `\default` and `\required-field` on a bunch of fields (which isn't that big of a deal, and could be brought over to E+ too), eg `Boiler:Steam`
* ScheduleTypeLimits is mising some of our keys like `ClothingInsulation` (that could be brought over to E+ too, but IDF editor would need update to handle them)
* max-fields was added in our ProposedEnergy+.idd for a few cases like `Schedule:Year`, `\max-fields 267`
* Our parser chokes on a couple of `\note` that have special characters, and some fields like `  N13, \field Young's modulus` (`'` is problematic) or `\note no spaces or other special characters (-,+,/,\) allowed in name`
* `Schedule:File` is \url-object
* Some objects actually do not have the `\begin-extensible` marker, like `MaterialProperty:PhaseChange` (actually, pretty much ALL `MaterialProperty:XXX` at least) (but that could be handled in parsing, and also added to the E+ side). So we need to also add `\extensible:2` and `\max-fields 34` to limit the number of extensible fields (that can be inferred from parsing too)
* A few units aren't understood by our parser (which can be fixed): either compound units (`W/((m3/s)-Pa)`, or `(gal/min)/(Btu/h)`), or stuff like `\units W/m2 or deg C`
* Our idd doesn't have the `\required-field` on a few extensible groups (but other do, so not sure if it works or not), one example is Vertex fields (eg in `Shading:Site:Detailed`)
* A few `\min-fields` differences in values, eg `HeatPump:PlantLoop:EIR:Cooling` (E+ has 14, I calculated 15)

* We do not understand `\object-list` was the reference is from a `\reference-class-name validPlantEquipmentTypes`
```
  A2 , \field Equipment 1 Object Type
       \type object-list
       \object-list validPlantEquipmentTypes
```

## Examples

Regular extensible

```
 A4  , \field Time 1
       \begin-extensible
       \note "until" includes the time entered.
       \units hh:mm
 N1  , \field Value Until Time 1
 A5  , \field Time 2
       \note "until" includes the time entered.
       \units hh:mm
 N2  , \field Value Until Time 2
 A6  , \field Time 3
       \note "until" includes the time entered.
       \units hh:mm
```

Variant:
```
  N2,  \field Value 1
       \begin-extensible
       \default 0.0
        N3,N4,         N5,N6,N7,N8,         N9,N10,N11,N12,      N13,N14,N15,N16,     N17,N18,N19,N20, \note fields as indicated
  N21,N22,N23,N24,
```

A couple of weird things:

`\begin-extensible` is placed on the second occurrence

```
Site:SpectrumData,

  A2, \field Spectrum Data Type
      \required-field
      \type choice
      \key Solar
      \key Visible
  N1, \field Wavelength
      \type real
      \units micron
  N2, \field Spectrum
      \type real
  N3, \field Wavelength
      \type real
      \units micron
  N4, \field Spectrum
      \type real
  N5, \field Wavelength
      \begin-extensible
      \type real
      \units micron
  N6, \field Spectrum
      \type real
  N7, N8,       \note fields as indicated
```

`FluidProperties:GlycolConcentration` (https://github.com/NREL/EnergyPlus/issues/7244)

```
FluidProperties:GlycolConcentration,
       \memo glycol and what concentration it is
  A1,  \field Name
       \required-field
       \note In EnergyPlus IDD 9.1.0, reference FluidAndGlycolNames is added but causing problems because we expect both
       \note FluidProperties:Name and FluidProperties:GlycolConcentration to have the same name
  A2,  \field Glycol Type

```

**Comment by tijcolem** [comment]
We'll be closing this issue in favor of focusing time on the new epJSON format for E+.
