### ISSUE TITLE
OpenStudio3.0.0

### ISSUE THREAD

**Issue by gagsters888** [NREL/OpenStudio#3967]
Hi,

May I know how and where can I download the standalone openstudio application for openstudio sdk 3.0.0?

As I understand that openstudio sdk 3.0.0 does not come with the openstudio application, I have no idea how to download the standalone openstudio application for its sdk 3.0.0.

Thank you

**Comment by jmarrec** [comment]
NREL/OpenStudioApplication is the new home of the OpenStudioApplication.

You can download it from https://github.com/NREL/OpenStudioApplication/releases

Note that it will ALSO include the openstudio sdk 3.0.0, so no need to install both.

**Comment by gagsters888** [comment]
ok thanks for the information!
