### ISSUE TITLE
Solar Diffusing bug

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#397]
On the Materials Tab when selecting standard glazing material. Solar Diffusing can be turned on, but not off.  Not sure if this is being used for anything.

**Comment by evanweaver** [comment]
@macumber I'm not sure I understand.  The "Solar Diffusing" switch appears to be able to effectively change model's setter to both on, and off.

**Comment by macumber** [comment]
@evanweaver did you test this out and make sure the changes are being written to the OSM?  If you can test that out and it works, then go ahead and close the bug.

**Comment by macumber** [comment]
Just verified, this is fixed
