### ISSUE TITLE
Unexpected behavior related to geometry intersecting/matching

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio#3982]
Issue overview
--------------
Getting different number of resulting surfaces after intersecting/matching between 2.9.1 and 3.0.0.

## Current Behavior
![image](https://user-images.githubusercontent.com/8516790/81954403-aa7e8f80-95bd-11ea-8bf6-c6d41f035413.png)

## Expected Behavior
![image](https://user-images.githubusercontent.com/8516790/81954364-9dfa3700-95bd-11ea-9019-10c540734e82.png)

## Steps to Reproduce
1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform: windows

**Comment by jmarrec** [comment]
Reopen #3514 which deals with unit test failures and has a section on intersection,  cf https://github.com/NREL/OpenStudio/issues/3514#issuecomment-574251352

**Comment by DavidGoldwasser** [comment]
Here is a document I started to talk about intersection and other geometry bugs
https://nrel-my.sharepoint.com/:w:/g/personal/dgoldwas_nrel_gov/EU2mUnAelJFOkZx2x0Y1MfsB0U74TKqYtq7Nu3VoPcSFvw?e=Kd71xx

**Comment by kbenne** [comment]
@joseph-robertson can you review the level of effort to work around in res stock and consider if we may be able to close with no change?

**Comment by dmacusb2** [comment]
FYI, I'm doing some work for Ladybug around this and may have a PR this weekend, not sure if they are seeing the same problems you are.

**Comment by DavidGoldwasser** [comment]
@dmacusb2 what @joseph-robertson would like to do here is be able to intersect without triangulating the surfaces. One idea discussed was having an argument in intersection to not triangulate, or maybe a separate `intersect` and `triangulate` method (I know triangulate already exists on its own). I did say for general use for most users I will always want to triangulate after intersection to avoid non-convex exterior surfaces.

**Comment by macumber** [comment]
Hmm, looking at the image in this issue I don't really understand what the issue is.  It looks like an exterior roof surface is being triangulated?  What is that surface being intersected with?  The picture isn't very clear.  Anyway, I'm pretty sure this is not the issue that Labybug is seeing.

**Comment by joseph-robertson** [comment]
@macumber Is this more clear? I am intersecting the garage roof decks (space in foreground) with the attic roof deck (space in background). The intersected surface (highlighted) gets removed. The resulting attic roof deck (now with 6 vertices) is used downstream in our workflow to place eaves.

![image](https://user-images.githubusercontent.com/8516790/84553206-4b995c80-acc8-11ea-8f6a-2b0f8a4de092.png)

**Comment by macumber** [comment]
Does it cause a problem that the larger roof surface (outside of the intersection) is triangulated?

**Comment by joseph-robertson** [comment]
Yes, it does.

**Comment by macumber** [comment]
Well one approach would be to get all of the exterior roof surfaces and call joinAll on them.  I am currently working on a fix to joinAll.

**Comment by joseph-robertson** [comment]
But call joinAll only on surfaces that are on the same plane, right?

**Comment by macumber** [comment]
Well the original roof surface was one plane before you intersected it right?  If its not one plane then there is no way to not triangulate it.

**Comment by joseph-robertson** [comment]
Yeah, I just meant to distinguish between the front and back roof surfaces. So basically for the image at the very top of this issue, I would joinAll on surfaces 1, 2, 3 after intersecting/matching (which now does the triangulating by default)?

**Comment by joseph-robertson** [comment]
@macumber Can you point me to an example for using joinAll on multiple surfaces? Does each surface need to first be transformed to face coordinates?

**Comment by macumber** [comment]
Yes they need to be in reverse face coordinates (so face coordinates and then call reverse):
https://github.com/NREL/OpenStudio/blob/develop/src/utilities/geometry/Intersection.hpp#L85

There are some unit tests in this PR:
https://github.com/NREL/OpenStudio/pull/3993/files

**Comment by joseph-robertson** [comment]
Thanks @macumber. That sounds fine. The only thing that's unclear to me is how to re-assign the original z-coordinates to the (single) polygon after joinAll is called. Any ideas there?

**Comment by macumber** [comment]
Yeah, since all the surfaces are co-planar just pick one of their face transforms, then reverse all their vertices.  After you have joined them, reverse the vertices again and use the inverse of the face transform to put them back.

**Comment by joseph-robertson** [comment]
Related post: https://unmethours.com/question/45559/surface-matching-and-intersecting-adds-unnecessary-surfaces/

**Comment by ggartside** [comment]
I'm not seeing where concave surfaces are decomposed into triangles as the attached images suggest is happening although I'm sure I did when I first looked at this issue back in fall last year, @macumber has anything changed recently and/or can you point me to where concave surfaces are handled? I see where holes are removed during intersection.

**Comment by jmarrec** [comment]
@joseph-robertson Could you try again following #4221 or upload your model so I could do it please?

**Comment by joseph-robertson** [comment]
Verified that our unit tests are now passing using v3.2.0: https://github.com/NREL/resstock/pull/604.

**Comment by jmarrec** [comment]
Thanks @joseph-robertson !
