### ISSUE TITLE
Unsupported cli command for Revit logs empty error message on windows

### ISSUE THREAD

**Issue by lainsworth8801** [NREL/OpenStudio#3991]
Issue overview
--------------

On AWS windows instance, unsupported cli command for Revit, e.g. , --debug, displays empty error log when used.

## Current Behavior
<img width="920" alt="Screen Shot 2020-05-29 at 2 28 21 PM" src="https://user-images.githubusercontent.com/49968203/83835392-ec2ac380-a6ad-11ea-9692-b7b0f8a43a79.png">

## Expected Behavior
Should prompt user of error message when unsupported cli command is called:
![Screen Shot 2020-06-01 at 11 48 08 AM](https://user-images.githubusercontent.com/49968203/83835511-3318b900-a6ae-11ea-9ae5-b7b60d32b15c.png)

## Steps to Reproduce

1. install the latest OpenStudio cli for revit;
2. run openstudio.exe --debug --verbose run. Current behavior would show no error log message;

## Possible Solution
This issue consistently repeats on powershell and gitbash on AWS instance.
It is suspected that this issue is related to specific windows config as it doesn't repeat on MacOS, or Parallels.

### Environment
AWS windows 10 image 2019 Base - ami-0cb8c277ab5436fac

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): windows 10
 - Version of OpenStudio (if using an intermediate build, include SHA): v2.8.1

**Comment by tijcolem** [comment]
My guess is this confused with using the `-run` arg and --debug is a supported arg along with using that command. I'm going to close this is the CLI is working as expected here and it should error when the command is not valid. This could be a good enhancement to be able to use -`-debug `with the main command to see more output.  Using -`-verbose` is essentially doing that/ 

```
openstudio list_commands
Usage: openstudio [options] <command> [<args>]

    -h, --help                       Print this help.
        --verbose                    Print the full log to STDOUT
    -I, --include DIR                Add additional directory to add to front of Ruby $LOAD_PATH (may be used more than once)
    -e, --execute CMD                Execute one line of script (may be used more than once). Returns after executing commands.
        --gem_path DIR               Add additional directory to add to front of GEM_PATH environment variable (may be used more than once)
        --gem_home DIR               Set GEM_HOME environment variable
        --bundle GEMFILE             Use bundler for GEMFILE
        --bundle_path BUNDLE_PATH    Use bundler installed gems in BUNDLE_PATH
        --bundle_without WITHOUT_GROUPS
                                     Space separated list of groups for bundler to exclude in WITHOUT_GROUPS.  Surround multiple groups with quotes like "test development".

Common commands:
     energyplus_version    Returns the EnergyPlus version used by the CLI
     execute_ruby_script   Executes a ruby file
     gem_list              Lists the set gems available to openstudio
     list_commands         Lists the entire set of available commands
     measure               Updates measures and compute arguments
     openstudio_version    Returns the OpenStudio version used by the CLI
     ruby_version          Returns the Ruby version used by the CLI
     run                   Executes an OpenStudio Workflow file
     update                Updates OpenStudio Models to the current version

For help on any individual command run `openstudio COMMAND -h`

$ openstudio run -h
Usage: openstudio run [options]

Options:

    -w, --workflow [FILE]            Specify the FILE path to the workflow to run
    -m, --measures_only              Only run the OpenStudio and EnergyPlus measures
    -p, --postprocess_only           Only run the reporting measures
    -s, --socket PORT                Pipe status messages to a socket on localhost PORT
        --debug                      Includes additional outputs for debugging failing workflows and does not clean up the run directory
    -h, --help                       Print this help

```
