### ISSUE TITLE
Chiller ReformulatedEIR model

### ISSUE THREAD

**Issue by lymereJ** [NREL/OpenStudio#3992]
Enhancement Request
--------------
Include the EnergyPlus ReformulatedEIR chiller model in the SDK.

## Detailed Description
The SDK doesn't currently support the ReformulatedEIR chiller model. This model tends to simulate the performance of water-cooled variable speed and variable flow chillers more accurately. While this can be handled through measures, the goal would be to include it in openstudio-standards.

**Comment by kbenne** [comment]
@mdahlhausen can you triage and let us know if you need this for OS Standards

**Comment by mdahlhausen** [comment]
@kbenne This is a PNNL request for the DOE prototype building models.  Nice, but not critical.  I'd give it a 4/10 on priority, 10 being the highest.
