### ISSUE TITLE
3.0.1-beta1: GbXMLReverseTranslator applies incorrect scaling to windows

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#3997]
Issue overview
--------------

With `lengthUnit="Feet"`, the windows are incorrectly placed.

![gbxml scaling issue](https://user-images.githubusercontent.com/5479063/84749776-b85b7200-afba-11ea-8ec3-90482092ca8f.jpg)

Reported by @antonszilasi

## Current Behavior

Wrong scaling for windows

## Expected Behavior

Windows should be placed correctly, like they are in 2.9.1.

## Steps to Reproduce

I will make a unit test for this.

## Possible Solution

Move from QXml to pugixml missed a conversion factor `m_lengthMutiplier` as it previously existed here: https://github.com/NREL/OpenStudio/blame/e65085e23f2792b8726bdd6f3f143c31651d136a/openstudiocore/src/gbxml/ReverseTranslator.cpp#L559

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.0.1-beta1, c710464d0534eba5f2b52b3ac9b01a17c4a61a6e

**Comment by antonszilasi** [comment]
@jmarrec thanks for taking the initiative to fix this issue but im confused why this wasnt fixed here:
https://github.com/NREL/OpenStudio/issues/3951#event-3252557770
@tijcolem do you know why?

**Comment by jmarrec** [comment]
@antonszilasi #3951 is a different error, specific to surface Type assignment, and was a typo in if blocks.

This one is about scaling and is about a missing multiplication.

I can speculate the original file you sent for 3951 may have had the same problem, but I don't recall it having windows. Anyways I didn't identify a problem with scaling there.
Note that I also have set my diff editor (vim) to ignore vertices since they often suffer from rounding errors especially due to sketchup, so when diffing between 2.9.1 OSM and 3.x OSM I saw the surface types problems only.

Perhaps that's where the confusion comes from?

This is a good illustration of why writing good, detailed issues matters: the issue templates we have should help structure that by listing all the things you think are not working correctly to maximize the chances of seeing them addressed.
I personally don't use gbxml (or perhaps twice a year), so these aren't bugs I already know of.

**Comment by tijcolem** [comment]
@antonszilasi Yes, but it'll be called openstudio:3.0.1-rc2 with this change.
