### ISSUE TITLE
AvailabilityManagerNightCycle Manger issue

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#4020]
Issue overview
--------------
See post and video here
https://unmethours.com/question/45968/simulation-failed-when-adding-night-manager/

## Current Behavior

  ["C:\\Users\\jenkins\\git\\OpenStudio\\src\\model\\AvailabilityManagerNightCycle.cpp@243 : Object of type 'OS:AvailabilityManager:NightCycle' and named 'AVM Night Cycle 1' does not have a controlThermalZoneList attached:

## Steps to Reproduce

1. m = exampleModel()
2. Go to AirLoopHVAC, go to Control
3. **Drag an AVM:NightCycle from the Library** (do not use the "Use Night cycle" dropdown)

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.0.1 ff0e898ff96e0653e1b72da4200a3403b927fdaa

**Comment by DavidGoldwasser** [comment]
CC @kbenne @mdahlhausen any thoughts on this

**Comment by mdahlhausen** [comment]
Not sure.  Maybe some interaction with always on discrete schedule and the night cycle?  I haven't tried this in OS 3.0 yet.  Seems like a bug for sure.

**Comment by jmarrec** [comment]
I was able to reproduce, I edited the OP to include steps to reproduce.
