### ISSUE TITLE
Importing GbXML model into Openstudio from IES software

### ISSUE THREAD

**Issue by gagsters888** [NREL/OpenStudio#4022]
Hi, 

I have a building model from IES and I have export it as a GbXML file and tried to open it in openstudio but i got the following error that is shown in attachment_1. It says that the openstudio could not find the adjacent space etc. however I am still able to edit all my level 3 spaces. May I check with you how will this missing "adjacent surfaces" error affect my simulation?
![Attachment_1](https://user-images.githubusercontent.com/64857050/88010419-6b356780-cb47-11ea-825a-db4f1a60ac07.png)
 

Background information:

My actual building model is actually 5 stories high but the main story that my building model from IES that I have imported is do only on level 3 and the rest of the levels are considered "adjacent buildings" on my IES model.

**Comment by jmarrec** [comment]
Any chance you could share the gbXML model?

**Comment by gagsters888** [comment]
yes sure. 

This is the link for it.

https://drive.google.com/file/d/1qcWATVZAeEFqpZopLvBdT8bIPn35Im4O/view?usp=sharing

**Comment by jmarrec** [comment]
Your XML is faulty. Taking an example:

```
    <Surface id="surface-220" surfaceType="InteriorWall" constructionIdRef="GMB_0116">
      <AdjacentSpaceId spaceIdRef="LV000006"/>
      <AdjacentSpaceId spaceIdRef="LV000002"/>
     <RectangularGeometry> [...] <RectangularGeometry>
     <PlanarGeometry>[...]</PlanarGeometry>
```

Space id="LV000006" does exist, no problem. LV000002 is not in your XML.

I load the gbxml using the bindings:

```
rt = OpenStudio::GbXML::GbXMLReverseTranslator.new; m = rt.loadModel('model.xml').get()
```

So the gbXML ReverseTranslator does warn you about it:

```
[openstudio.gbxml.ReverseTranslator] <1> Could not find adjacent space 'LV000002' for surface 'surface-220'
```

```
surface = m.getSurfaceByName("surface-220").get
puts surface
```

```
OS:Surface,
  {29a03a8f-70f5-4ccc-b018-6fd6e034f55d}, !- Handle
  surface-220,                            !- Name
  Wall,                                   !- Surface Type
  {159fe05a-17da-48a1-acd4-e71d98c5a5cc}, !- Construction Name
  {e3fdd056-2785-4cc7-84a5-e2cbd92efa76}, !- Space Name
  Adiabatic,                              !- Outside Boundary Condition
  ,                                       !- Outside Boundary Condition Object
  NoSun,                                  !- Sun Exposure
  NoWind,                                 !- Wind Exposure
  ,                                       !- View Factor to Ground
  ,                                       !- Number of Vertices
  27.06, -12.57, 16.7999,                 !- X,Y,Z Vertex 1 {m}
  27.06, -11.53, 16.7999,                 !- X,Y,Z Vertex 2 {m}
  27.06, -11.53, 18.13,                   !- X,Y,Z Vertex 3 {m}
  27.06, -12.57, 18.13;                   !- X,Y,Z Vertex 4 {m}

```
puts surface.space.get.nameString
=> RA: Video Recording Room
```
puts surface.construction.get.nameString
=> [JTH]75mm_Drywall partition + 50mm Insulation
```


So this probably does what you want in the end. Anyways, this is not an OpenStudio problem, so closing.

**Comment by DavidGoldwasser** [comment]
@gagsters888 I wonder if using the "Adjacent Buildings" In IES is creating the issue. As an example if in OpenStudio you had three zones in a raw adjacent to each other, and match the surfaces, but only assign a zone to the middle space. The IDF could be malformed or provide unexpected results because the adjacent spaces were not in a zone and therefore would not make it to the IDF. (It would either fail with a bad match or more likely would convert the adjacent walls to outdoors, which isn't what you want.

Does IES have a way to assign them as adiabatic?, which is a common approach for modeling impact of adjacent buildings with similar thermostats setpoints. If not then you can update the OSM model before trying to run using the surfaces sub-tab of the OpenStudio Application.
