### ISSUE TITLE
Getting Multiple "Always on Discrete" schedules

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#403]
I thought the goal of the always on discrete was to prevent getting multiple "Always On" schedules. Or maybe it was just to hide them from the user. I ran across this adding SHW and DOAS using 1.0.0 to update training material

As shown on the image the pulldown menu gets cluttered with the multiple "Always On" schedules. I suppose you could just hide them from here, but they all are used on an object somewhere, so I don't know if that is a good option.

![7-29-2013 8-38-37 am](https://f.cloud.github.com/assets/4857055/872180/49832768-f85d-11e2-8813-db955a49a306.png)

**Comment by macumber** [comment]
@DavidGoldwasser @kbenne I think this is fixed right, can we close this?

**Comment by jmarrec** [comment]
Related to #2252, I think the HVAC library is at fault

**Comment by evanweaver** [comment]
Fixed by modifying HVAC library.
