### ISSUE TITLE
Limited functionality of clone Thermal Zone

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#4031]
Issue overview
--------------
Some elements that could be cloned with thermal zones are not

## Current Behavior
When cloning a thermal zone (in my case from one model to another) ZoneHVACComponent objects associated with a zone do not get cloned.

Air terminals are already cloned with air loops so they probably should not be cloned with the zone. Similar may be true if any ZoneHVACComponent objects have link to coils that are on plant loops.

I have confirmed that multipliers, volume, and thermostats are cloned.

## Steps to Reproduce

1.
2.
3.
4.

## Possible Solution
Here is code I use as work around for now
`      model_2.getThermalZones.sort.each do |zone|
        if ! model.getThermalZoneByName(zone.name.to_s).is_initialized
          zone.clone(model)
        end
        target_zone = model.getThermalZoneByName(zone.name.to_s).get
        zone.equipment.each do |equip|
          # this will get rid of terminals, terminals are added by clone air loop
          if equip.to_ZoneHVACComponent.is_initialized
            target_equip = equip.clone(model)
            target_equip = target_equip.to_ZoneHVACComponent.get
            target_equip.addToThermalZone(target_zone)
          end
        end
      end`

My test cases uses OS:ZoneHVAC:IdealLoadsAirSystem

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

**Comment by kbenne** [comment]
@DavidGoldwasser based on extended conversations on Slack, I think @jmarrec's commit is the only change we have planned at this time. Are you ok with that? Can I close or would you like to leave open for a future time when perhaps we might implement something like `deepClone`?

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio/commit/98e0109bb1f61301632581a9cc65f0f18c8865c7 serves no purpose currently, as it will encounter a PortList and the PortList has a Name field which uses UUID as names. same for Connection object for that matter.

Another issue is that cloning a ThermalZone for eg will change the number of fields in the clone due to https://github.com/NREL/OpenStudio/blob/fa9a77bf173556a2a044f64789a7f4f01b0df076/src/model/ThermalZone.cpp#L2405

**Comment by kbenne** [comment]
@jmarrec I'm going to close this issue but I added an enhancement request to remove the name field from PortList and Connection. https://github.com/NREL/OpenStudio/issues/4077

**Comment by jmarrec** [comment]
Works for me, thanks for opening #4077
