### ISSUE TITLE
Limited functionality of clone AirLoopHVAC

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#4033]
Issue overview
--------------
My use case is cloning from one model to another model, not within a model. I may find more issues, but I wanted to file with this initial problem.

- [ ] AvailabilityManagerAssignmentList isn't cloned with the air loop. This results in crash of app when go to control tab for the air loop, or failed export to IDF. This may be general clone Loop issue and not specific to plant loops. I have not tested plant loops yet.

## Current Behavior

![Screen Shot 2020-08-05 at 10 23 33 AM](https://user-images.githubusercontent.com/4857055/89442604-54c50980-d70c-11ea-837e-adec3d2643cc.png)

## Expected Behavior
Clone should result in valid air loop 

## Steps to Reproduce

1.
2.
3.
4.

## Possible Solution

Here is my ruby work around, not proposed solution, but shows what needs to change to make the loop valid
```
    # create and assign AvailabilityManagerAssignmentList to cloned air loops
    model.getAirLoopHVACs.sort.each do |air_loop|
      if air_loop.getString(4).to_s == ""
        list = OpenStudio::Model::AvailabilityManagerAssignmentList.new(air_loop)
        # line above adds list but doesn't associate it with air_loop. Line below is a work around to force it in
        air_loop.setString(4,list.handle.to_s)
      end
    end
```

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### Context
Clone air loops from one model to another as part of effort to combine many OSM's to one OSM.

**Comment by DavidGoldwasser** [comment]
Separate issue could be why ` OpenStudio::Model::AvailabilityManagerAssignmentList.new(air_loop)` doesn't associate the new list object with the air loop passed in as an argument.

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio/blob/757b0337ae7bc75a2d17a5853ef891300c47a154/src/model/AirLoopHVAC.cpp#L766-L770

**Comment by jmarrec** [comment]
```
[1] OS-build-release(main)> m = Model.new
=> #<OpenStudio::Model::Model:0x000055b91589abd8 @__swigtype__="_p_openstudio__model__Model">
[2] OS-build-release(main)> a = AirLoopHVAC.new(m)
=> #<OpenStudio::Model::AirLoopHVAC:0x000055b91580af60 @__swigtype__="_p_openstudio__model__AirLoopHVAC">
[3] OS-build-release(main)> avm = AvailabilityManagerNightCycle.new(m)
=> #<OpenStudio::Model::AvailabilityManagerNightCycle:0x000055b9156393a8 @__swigtype__="_p_openstudio__model__AvailabilityManagerNightCycle">
[4] OS-build-release(main)> a.addAvailabilityManager(avm)
=> true
[5] OS-build-release(main)> m2 = Model.new
=> #<OpenStudio::Model::Model:0x000055b915501940 @__swigtype__="_p_openstudio__model__Model">
[6] OS-build-release(main)> a.clone(m2)
[utilities.idf.Workspace] <-1> Renamed Object of type 'OS:Schedule:Constant' and named 'Always On Discrete' to 'Always On Discrete 1' to avoid a name conflict upon WorkspaceObject addition.
[BOOST_ASSERT] <2> Assertion ok failed on line 115 of virtual openstudio::model::ModelObject openstudio::model::detail::AvailabilityManagerAssignmentList_Impl::clone(openstudio::model::Model) const in file /home/ubuntu/git/OpenStudio/src/model/AvailabilityManagerAssignmentList.cpp.
[BOOST_ASSERT] <2> Assertion ok failed on line 115 of virtual openstudio::model::ModelObject openstudio::model::detail::AvailabilityManagerAssignmentList_Impl::clone(openstudio::model::Model) const in file /home/ubuntu/git/OpenStudio/src/model/AvailabilityManagerAssignmentList.cpp.
=> #<OpenStudio::Model::ModelObject:0x000055b9154c2fd8 @__swigtype__="_p_openstudio__model__ModelObject">

```

**Comment by jmarrec** [comment]
Oh yeah no wonder, this is is really dumb (I did that, mind you):

https://github.com/NREL/OpenStudio/blob/757b0337ae7bc75a2d17a5853ef891300c47a154/src/model/AvailabilityManagerAssignmentList.cpp#L96-L118

**Comment by jmarrec** [comment]
Replace : https://github.com/NREL/OpenStudio/blob/757b0337ae7bc75a2d17a5853ef891300c47a154/src/model/AirLoopHVAC.cpp#L766-L770
 with

```
    {
      AvailabilityManagerAssignmentList avmListClone(airLoopClone);
      avmListClone.setName(airLoopClone.name().get() + " AvailabilityManagerAssigmentList");
      // Clone all AVMs and populate the clone
      std::vector<AvailabilityManager> avmVector = availabilityManagers();
      for (const AvailabilityManager& avm : avmVector) {
        AvailabilityManager avmClone = avm.clone(model).cast<AvailabilityManager>();
        bool ok = avmListClone.addAvailabilityManager(avmClone);
        OS_ASSERT(ok);
      }
    }
```

And somehow just disable the `AvailabilityManagerAssignmentList_Impl::clone` or something.
