### ISSUE TITLE
Limited functionality of clone PlantLoop

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#4034]
Issue overview
--------------
Similar issue to Issue #4033 with missing availability manger assignment list in cloned plant loop.

## Steps to Reproduce

1.
2.
3.
4.

## Possible Solution
The work around is similar to air loop bud different field to change in the plant loop.
```
    # todo - code below here should be removed when SDK updated to handle this with clone plant loop method
    # create and assign AvailabilityManagerAssignmentList to cloned plant loops
    model.getPlantLoops.sort.each do |plant_loop|
      if plant_loop.getString(22).to_s == ""
        list = OpenStudio::Model::AvailabilityManagerAssignmentList.new(plant_loop)
        # line above adds list but doesn't associate it with air_loop. Line below is a work around to force it in
        plant_loop.setString(22,list.handle.to_s)
      end
    end
```

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

**Comment by kbenne** [comment]
@DavidGoldwasser never mind. I found that the issue is specific to cloning between different models. I got this.
