### ISSUE TITLE
Can you add "design return airflow fraction" to the OpenStudioSDK?

### ISSUE THREAD

**Issue by TheEnergyTutor** [NREL/OpenStudio#4039]
Enhancement Request
--------------
Energy Plus has this feature but OpenStudio does not.
It is important because often supply fans are not the same size as supply fans due to separate building exhaust fans and Ashrae requirements for bathrooms.

## Detailed Description
https://www.youtube.com/watch?v=G_qk_FGXMlo
This video shows how to do it through code which is way too much work for a simple setting. If several settings have to be done this way, nobody will use OpenStudio because of time constraints with a normal job.

**Comment by jmarrec** [comment]
here's the link to the E+ I/O ref for this field on AirLoopHVAC: https://bigladdersoftware.com/epx/docs/9-3/input-output-reference/group-air-distribution.html#design-return-air-flow-fraction-of-supply-air-flow

Seems like this field was added in E+ 8.8.


E+ IDD
```
   N2; \field Design Return Air Flow Fraction of Supply Air Flow
       \note The design return air flow rate as a fraction of supply air flow rate with no exhaust.
       \note This can be used to model a pressurized system or set to zero to model a DOAS with no return flow.
       \note Use ZoneAirMassFlowConservation to balance zone infiltration and mixing flows.
       \minimum 0.0
       \default 1.0
```

It's a numeric field, so easy to add getter, setter, and FT.

Make that required-field instead, and set it to 1.0 in the Ctor. This would requires adding this to our IDD:

```
   N2; \field Design Return Air Flow Fraction of Supply Air Flow
       \note The design return air flow rate as a fraction of supply air flow rate with no exhaust.
       \note This can be used to model a pressurized system or set to zero to model a DOAS with no return flow.
       \note Use ZoneAirMassFlowConservation to balance zone infiltration and mixing flows.
       \minimum 0.0
       \required-field
```

 Needs VT as a result, so probably best to insert it next to the N1  Design Supply Air Flow Rate field to match E+.

**Comment by jmarrec** [comment]
Retitled the issue since this repo only deals with SDK. moved the App portion to https://github.com/openstudiocoalition/OpenStudioApplication/issues/210
