### ISSUE TITLE
OS App Water Use Equipment Definitions, Peak Flow Rate Units always in SI units

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#404]
I couldn't find old bug so made a new one. We hit this in our training material, so while it isn't a critical issues, I have to add a special note explaining that it isn't showing IP units. Would be nice to fix.

If you have the object selected and switch to SI and back to IP units, you will see CFM, but as soon as you move to another category and then back, it jumps back to SI.

**Comment by kbenne** [comment]
@DavidGoldwasser I think it is working now. Could have been inadvertently fixed in https://github.com/NREL/OpenStudio/issues/1468 but more likely it was fixed prior. Can you confirm that it is no longer an issue?
