### ISSUE TITLE
OS App inconsistent use of "volume" vs. "speed" for fans

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#405]
In the library sometimes the object under a heading doesn't exactly match the heading. Below are once I noticed.

Fan Constant Volume / Constant Speed Fan
Fan Variable Volume / Variable Speed Fan

Pumps seem to use "speed" vs. "volume" at the heading and object level.

**Comment by evanweaver** [comment]
Closed.
