### ISSUE TITLE
Error reporting autosized capacity for CoilHeatingGas object

### ISSUE THREAD

**Issue by jkneifel** [NREL/OpenStudio#4062]
Issue overview
--------------

The current code for pulling the autosized value for CoilHeatingGas is failing to find the value because it is looking for "Design Size Nominal Capacity" for "Coil:Heating:Gas" in the E+ results but the results are reported in "Coil:Heating:Fuel". This error is only for gas heating coils; the same approach works for electric heating coils.

## Current Behavior

The value cannot be found and the measure reports a blank value.

## Expected Behavior

Should find the autosized value in the Coil:Heating:Fuel table

## Steps to Reproduce

1. Create a model with an autosized gas heating coil
2. Create a measure that searches for gas heating coils and reports the autosized capacity value (see "details" for example measure code).

## Possible Solution
Change the search in the E+ results to find the "Fuel" table instead of the "Gas" table of results.

## Details
Here is the code used to create the issue.:
if coil.to_CoilHeatingGas.is_initialized
    chg = coil.to_CoilHeatingGas.get
    runner.registerInfo("CoilHeatingGas found = #{chg}.")
    # Get the capacity
    capacity_w = nil

    if chg.nominalCapacity.is_initialized
        capacity_w = chg.nominalCapacity.get
    elsif chg.autosizedNominalCapacity.is_initialized
        runner.registerInfo("CoilHeatingGas has autosized capacity.")
        capacity_w = chg.autosizedNominalCapacity.get
    else
        runner.registerError("For #{coil.name} capacity is not available.")
    end
    runner.registerInfo("CoilHeatingGas capacity found = #{capacity_w}.")

### Environment
Win10.0.18363 Build 18363
OS 3.0.0
OS App v1.0.0

### Context

I am using a measure to develop whole building LCA results. This error is keeping me from evaluating any non-electric heating options.

**Comment by jmarrec** [comment]
Nope, that's not why it doesn't work as this is correctly handled in `ModelObject_Impl::getAutosizedValue`

https://github.com/NREL/OpenStudio/blob/1c9617fa4ed89ff595b712849bd34f575d7197a4/src/model/ModelObject.cpp#L257-L260

It works plenty fine. To diagnosticate why it's failing, use the bindings and recreate the query, and look at the log messages you get.

```ruby
# In my case I'm using 3.0.1, but it's the same as 3.0.0 on this aspect.
[1] run(main)> puts OpenStudio::openStudioLongVersion
3.0.1+09b7c8a554

[1] run(main) > OpenStudio::Logger.instance.standardOutLogger.setLogLevel(OpenStudio::Debug)
[2] run(main)> m = osload('in.osm')
[3] run(main)> c = m.getCoilHeatingGass[0]
=> #<OpenStudio::Model::CoilHeatingGas:0x00005628e344ced0
 @__swigtype__="_p_openstudio__model__CoilHeatingGas">
[4] run(main)> puts c
OS:Coil:Heating:Gas,
  {40f4d8b4-c7ad-45d2-b125-d00506bc000a}, !- Handle
  Coil Heating Gas 8,                     !- Name
  {31b24cd1-c317-4121-a32e-cf054c16a565}, !- Availability Schedule Name
  0.8,                                    !- Gas Burner Efficiency
  AutoSize,                               !- Nominal Capacity {W}
  {e3126ea7-0ffc-4360-9bdc-f207650b79ff}, !- Air Inlet Node Name
  {c0df2885-ffb6-4ad5-8c3d-2867df9e67c9}, !- Air Outlet Node Name
  ,                                       !- Temperature Setpoint Node Name
  0,                                      !- Parasitic Electric Load {W}
  ,                                       !- Part Load Fraction Correlation Curve Name
  0;                                      !- Parasitic Gas Load {W}

=> nil

[5] run(main)> sqlFile = OpenStudio::SqlFile.new('eplusout.sql')
[openstudio.energyplus.SqlFile] <0> Using unsupported EnergyPlus version 9.4.0
=> #<OpenStudio::SqlFile:0x00005628e3268fd8
 @__swigtype__="_p_openstudio__SqlFile">
[6] run(main)> m.setSqlFile(sqlFile)
=> true

[7] run(main)> c.autosizedNominalCapacity.get
[utilities.idf.Workspace] <-3> Adding object with handle {528ca184-70b0-4b8c-be2b-6edfcc101477}
=> 148279.48635569247
```

**Comment by jmarrec** [comment]
@jkneifel Thanks for reporting the issue! (It did help me notice I introduced a problem in that file very recently too)

If you have trouble figuring out what's going, you can share your model and I'll take a look. 

I'm going to close this one, and can reopen if after investigation you still think it's an OpenStudio bug.

**Comment by jkneifel** [comment]
Julien,
Thanks for the response. I cannot seem to figure out the issue, but I am a relative novice to OpenStudio. I appreciate any help you are willing to provide because I am at a loss.
I have provided a ZIP of my measure (attached) with the OSM model with an autosized gas heating coil within a unitary system in the "test" subfolder. There is a lot going on in the measure, but the specific code that is not working correctly is lines 1286-1303 of HVACandDHW.rb in the resources subfolder. I provided you with the entire measure just in case.
Note that the (autosized) capacity code is the same for CoilHeatingGas and CoilHeatingElectric (located just below the gas coil code), but only works for the electric coil. The code technically errors out when it hits line 1312 because it tries to round a nil value, but its because it is not finding the autosized capacity.
The coil is found:
Info: CoilHeatingGas found = OS:Coil:Heating:Gas,

{871a33d0-6913-4883-9486-ccdfa3d5f11a}, !- Handle

Coil Heating Gas 4, !- Name

{13af84d4-14b4-44cd-8194-59dbf9daecee}, !- Availability Schedule Name

0.8, !- Gas Burner Efficiency

Autosize, !- Nominal Capacity {W}

, !- Air Inlet Node Name

, !- Air Outlet Node Name

, !- Temperature Setpoint Node Name

0, !- Parasitic Electric Load {W}

, !- Part Load Fraction Correlation Curve Name

0; !- Parasitic Gas Load {W}

But the code never gets into the loop checking if the autosized capacity is initialized and reports back the initial nil value.

Info: CoilHeatingGas capacity found = .

Thanks,

Josh

________________________________

**Comment by jmarrec** [comment]
@jkneifel Adding attachments when replying to a github notification email does not work unfortunately. Would you mind hosting a zip on a file sharing website (google drive, dropox, wetransfer, whatever)? Otherwise you can email me directly at julien at effibem dot com.

**Comment by jkneifel** [comment]
Sorry. Did not realize that. Here is a path to the zip file on my google drive. https://drive.google.com/file/d/1QNlZqBF07R-IQxF-D4NDXvb9AYnbAzX8/view?usp=sharing

**Comment by jmarrec** [comment]
@jkneifel I requested access to it

**Comment by jkneifel** [comment]
Sorry, having issues with my work drive. Here is a link for my personal drive. https://drive.google.com/file/d/1nEzTKGzVnAfJnHKWYFj8RyCIDMVcNMjT/view?usp=sharing

**Comment by jkneifel** [comment]
@jmarrec Were you able to get access to the zip file through either drive? Thanks.

**Comment by shorowit** [comment]
@jmarrec Does your above commit suggest that there _was_ a bug here?

**Comment by jmarrec** [comment]
@shorowit  I made a too greedy search and replace while doing the fuel type rename. There was a bug on develop for a few days but not in any release 

I did get Joshua's files and took a lot and there is something weird happening though: inside the measure the autosizedNominalCapacity is not working, while if I use the same model and same sql under the run/ folder and try it out it works. I plan on taking another look tomorrow.

**Comment by shorowit** [comment]
Ah, got it, thanks for the explanation. In that case, I think we should reopen the issue while it's still under investigation.

**Comment by jmarrec** [comment]
@jkneifel I do not understand what's going on really.

If I go under <companion_folder>/run/ and do

```
[1] run(main)> m = osload('in.osm')
[2] run(main)> sql = OpenStudio::SqlFile.new()
[2] run(main)> sqlFile = OpenStudio::SqlFile.new('eplusout.sql')
[3] run(main)> m.setSqlFile(sqlFile)
[4] run(main)> coil =  m.getCoilHeatingGass[0]
[5] run(main)> puts coil
OS:Coil:Heating:Gas,
  {871a33d0-6913-4883-9486-ccdfa3d5f11a}, !- Handle
  Coil Heating Gas 4,                     !- Name
  {13af84d4-14b4-44cd-8194-59dbf9daecee}, !- Availability Schedule Name
  0.8,                                    !- Gas Burner Efficiency
  Autosize,                               !- Nominal Capacity {W}
  ,                                       !- Air Inlet Node Name
  ,                                       !- Air Outlet Node Name
  ,                                       !- Temperature Setpoint Node Name
  0,                                      !- Parasitic Electric Load {W}
  ,                                       !- Part Load Fraction Correlation Curve Name
  0;                                      !- Parasitic Gas Load {W}

=> nil
[6] run(main)> coil.autosizedNominalCapacity.get
=> 11200.713297285292
```


 In your measure file `resource/HVACAndDHW.rb` I recreated and decomposed the SQL query the C++ should be doing inside the block

```diff
  if coil.to_CoilHeatingGas.is_initialized
    chg = coil.to_CoilHeatingGas.get
    runner.registerInfo("CoilHeatingGas found = #{chg}.")
    # Get the capacity
    capacity_w = nil

+    sqlFile = coil.model.sqlFile.get
+    rowNames = sqlFile.execAndReturnVectorOfString("SELECT RowName FROM TabularDataWithStrings WHERE ReportName = 'Initialization Summary' AND ReportForString = 'Entire Facility' AND TableName = 'Component Sizing Information' AND Value = 'Coil:Heating:Fuel'").get
+    runner.registerInfo("rowNames: #{rowNames}")
+    rowName = rowNames[0]
+    x = sqlFile.execAndReturnFirstString("SELECT Value FROM TabularDataWithStrings WHERE ReportName = 'Initialization Summary' AND ReportForString = 'Entire Facility' AND TableName = 'Component Sizing Information' AND Value = 'Design Size Nominal Capacity [W]' AND RowName='#{rowName}'")
+    runner.registerInfo("x is initialized? #{x.is_initialized}")
+    val = sqlFile.execAndReturnFirstDouble("SELECT Value FROM TabularDataWithStrings WHERE ReportName = 'Initialization Summary' AND ReportForString = 'Entire Facility' AND TableName = 'Component Sizing Information' AND ColumnName='Value' AND RowName='#{rowName}'")
+    runner.registerInfo("val is initialized? #{val.is_initialized}: #{val.get}")
+    runner.registerInfo("OpenStudio #{OpenStudio::openStudioLongVersion}")

+    runner.registerInfo("chg is a #{chg.class}")
+    OpenStudio::Logger.instance.standardOutLogger.setLogLevel(OpenStudio::Trace)
+    capacity_w = chg.autosizedNominalCapacity().get()
    if chg.nominalCapacity.is_initialized
      runner.registerInfo("CoilHeatingGas capacity is hard coded.")
      capacity_w = chg.nominalCapacity().get
      runner.registerInfo("CoilHeatingGas hard coded capacity = #{capacity_w}.")
    elsif chg.autosizedNominalCapacity().is_initialized
      runner.registerInfo("CoilHeatingGas has autosized capacity.")
      capacity_w = chg.autosizedNominalCapacity().get
      runner.registerInfo("CoilHeatingGas autosized capacity = #{capacity_w}.")
    else
      runner.registerError("For #{coil.name} capacity is not available.")
    end
    runner.registerInfo("CoilHeatingGas capacity found = #{capacity_w}.")

    # Get the efficiency
    eff = chg.gasBurnerEfficiency

    runner.registerInfo("Coil efficiency = #{eff} for gas furnace have been found.")

    heating_coil_type = 'Furnace'
    heating_coil_fuel = 'NATURAL_GAS'
    heating_coil_capacity = capacity_w.round(0)
```

here is the output:

```
[11:40:13.231634 INFO] rowNames: ["          39"]
[11:40:13.232577 INFO] x is initialized? true
[11:40:13.233565 INFO] val is initialized? true: 11200.7133
[11:40:13.233585 INFO] OpenStudio 3.0.1+09b7c8a554
[11:40:13.233600 INFO] chg is a OpenStudio::Model::CoilHeatingGas
[11:40:13.235499 ERROR] Optional not initialized
	/home/julien/Software/Others/OpenStudio-Issues/2019-11/4062_CoilHeatingGasAutosized/NISTBIRDSNESTLCIAREPORT_JUL13/tests/OS2_4 NZERTF-10 min (02_26_2018)-CentralACGasHeat-autosized/measures/NISTBIRDSNESTLCIAREPORT_JUL13/resources/HVACandDHW.rb:1308:in `get'
```


**As you can see, the manual queries are working just fine, yet the autosizedNominalCapacity is failing, but it's supposed to be doing _exactly_ the same thing.**

https://github.com/NREL/OpenStudio/blob/v3.0.1/src/model/CoilHeatingGas.cpp#L630-L632

https://github.com/NREL/OpenStudio/blob/v3.0.1/src/model/ModelObject.cpp#L238-L384

@kbenne @tijcolem @joseph-robertson Is anyone seeing why this would not work please?
Additionally, I cannot figure how to get my C++ debugger (lldb) to hit the breakpoints I'm trying to set... It seems that measure.run is executed in another thread and I cannot capture. I haven't done any measure debugging in a while. Any tips? I'd like to run lne by line why autosizedNominalCapacity ends up returning nil

**Comment by jmarrec** [comment]
@jkneifel I had a lot of trouble figuring out why I wasn't hitting the C++ breakpoints I was setting until @kbenne put me on the right track.

your ruby resource files are:
1. WAY outdated
2. overwriting the methods of interest, cf `resources/HVACSizing.CoilHeatingGas.rb`

```
  # returns the autosized rated capacity as an optional double
  def autosizedNominalCapacity

    return self.model.getAutosizedValue(self, 'Design Size Nominal Capacity', 'W')
    
  end  
```

More importantly, cf `resources/HVACSizing.Model.rb` the `getAutosizedValue` is overwritten too but it's not taking the Coil:Heating:Fuel thing into account.

You should probably delete all of the HVACSizing.xxx files if the only thing you care about tis applySizingValues / autosizedXXX as they should all be implemented in C++ side (if that's not the case, let us know in another issue). If some are missing then re-add them, but go look for the up to date version at openstudio-standards repo.


Anyways, closing this one, it's a user error.

**Comment by jmarrec** [comment]
cd resources
/bin/rm -Rf HVACSizing*

Then go open measure.rb and remove the line 13 `require "#{File.dirname(__FILE__)}/resources/HVACSizing.Model"` and off you go, your measure runs to completion.
