### ISSUE TITLE
3D viewer causing OS to crash 

### ISSUE THREAD

**Issue by paczeterson** [NREL/OpenStudio#4075]
Issue overview
--------------
I created geometry in floorspace.js (https://drive.google.com/file/d/1OhMywtaWm1aTiDtioHe_jwYX1P8vSQ-G/view?usp=sharing), but when I load it into OS and merge the model, then I go to the 3D viewer it starts to load (the green progress bar advances a little) but then freezes and OS eventually crashes. I've had previous versions of the geometry (https://drive.google.com/file/d/1aW0kpEmFearRU264epQwmNufn_wr707B/view?usp=sharing)  load fine, so I'm unsure what is causing it to crash. 

## Current Behavior
openstudio crashing when trying to load the 3d view

## Expected Behavior
openstudio displaying the 3d view 

## Steps to Reproduce

1. Load the floorplan into the model 
2. Merge with existing OSM 
3. select 3D view tab

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): windows 
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.0.0

**Comment by macumber** [comment]
This probably belongs in the OpenStudioApplication repo, I created a duplicate issue: https://github.com/openstudiocoalition/OpenStudioApplication/issues/233

**Comment by tijcolem** [comment]
Close as this opened in[openstudiocoalition/OpenStudioApplication#233](https://github.com/openstudiocoalition/OpenStudioApplication/issues/233)
