### ISSUE TITLE
Forward translator issue related to fans

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/OpenStudio#4087]
Issue overview
--------------
There is an issue hit with openstudio standards where On/Off fans were not translating properly in the forward translator, causing broken node linkages and subsequent energyplus simulation failure.  I'll provide the steps to reproduce this error once the openstudio-standards release is out.

## Current Behavior
A fan object gets translated with broken nodes.

## Expected Behavior
The forward translator catches this issue and errors out with a report to the user if the fan is invalid.

## Steps to Reproduce
TBD

## Possible Solution
TBD

### Environment

Some additional details about your environment for this issue (if relevant):

**Comment by jmarrec** [comment]
Any update on this @mdahlhausen? If there is something to fix for the 3.1.0 release we need to do it now. Thanks!

**Comment by mdahlhausen** [comment]
I think I was able to reproduce the error, and it is is related to not specify a heating sizing method in some unitary system objects.  It's possible to add a bad fan object with the API to cause this, but I think most users won't encounter this, and EnergyPlus gives a warning what the error is.  So I'm going to close this issue - no changes to OpenStudio necessary.

**Comment by jmarrec** [comment]
thanks for looking into it!
