### ISSUE TITLE
Confirm if idf_output_requests still works in reporting measure template

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#4089]
I hit issues with this in openstudio_results and had to rely on different method where pre test osw added the reporting measure. See if issue exists here or was unique to the other measure
https://github.com/NREL/OpenStudio/blob/develop/src/utilities/bcl/templates/ReportingMeasure/tests/reporting_measure_test.rb#L71-L82

Can be addressed after 3.1

**Comment by DavidGoldwasser** [comment]
When I make new measure in 3.0.1 and run it without any changes test fails on this line
https://github.com/NREL/OpenStudio/blob/7e9cd9eaf5852eac614786a78a6b1447a2677806/src/utilities/bcl/templates/ReportingMeasure/tests/reporting_measure_test.rb#L124

with error `NoMethodError: undefined method `size' for false:FalseClass`

**Comment by DavidGoldwasser** [comment]
- [ ] This measure argument should be removed or fixed. First it isn't called anywhere in the run method, second, it is general practice to avoid dynamic arguments that show up on some datapoints and not others for use with parametric analyses. This has odd trigger of not showing when no zones. It should just be run to be save when run with no zones. There are some use cases for dynamic args like bool for each zone, but those are made knowing that there may be limitations in some parametric use cases if they don' they common seed model.
https://github.com/NREL/OpenStudio/blob/develop/src/utilities/bcl/templates/ReportingMeasure/measure.rb#L31-L36

**Comment by DavidGoldwasser** [comment]
- [ ] remove 1x/2x path for test, new measures should only be setup for 2x.

**Comment by DavidGoldwasser** [comment]
Will make pull request once I test with OpenStudio 3.1.0. Currently tested with 3.0.1.
cc @jmarrec @kbenne @tijcolem

**Comment by jmarrec** [comment]
Fixed via #4099 which was merged in #4100 so it didn't capture the automatic closing.
