### ISSUE TITLE
Issues with skp and OSM linking

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#409]
This is old issue, but a user sent us steps they think can reproduce this. I wonder if intersect is somehow making duplicate geometry and creates the issue. Email text follows.

-------

Mr. Goldwasser,

I recreated my model and saved it at each step in the design process. All the OSM files linked with the SKP files until I got to the part where I Projected Loose Geometry to make windows and doors. After I use that tool, the models do not link anymore. Do you know why projecting loose geometry could be causing this?

Thank you,

I don’t think it is anything wrong with the model. It is  a problem with how our plugin is linking osm and skp files (but it only happens sometimes).

Sent: Tuesday, July 30, 2013 11:15 AM
To: Goldwasser, David
Subject: Re: SKP not connecting to OSM

Dear Mr. Goldwasser,
Thank you for your reply. Could the problem be that I didn't use the Intersect and Divide Interzone Tool? I used the Surface Matching tool, but I do not know what the Intersecting tool does.
Thank you,
Clarissa

On Tue, Jul 30, 2013 at 1:08 PM, Goldwasser, David 

I see the same things. The linking of SketchUp files and OSM files has always been tricky. It is important not to double click the SKP but instead open SketchUp and then Open the SKP file. But even when I did that and browsed for your OSM I still get the error. I’m not sure why, but unless there is anything important in the SKP file I would just save the OSM file and don’t’ save the SketchUp file. I generally turn auto-save off.

I’m forwarding this to another developer  else so they can see the ruby error.

---
Error: #<NoMethodError: undefined method `drawing_interface' for nil:NilClass>
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/PlanarSurface.rb:364:in `paint_entity'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/PlanarSurface.rb:311:in `update_entity'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/SurfaceGroup.rb:132:in `update_child_entities'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/SurfaceGroup.rb:129:in `each'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/SurfaceGroup.rb:129:in `update_child_entities'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/SurfaceGroup.rb:122:in `update_entity'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/DrawingInterface.rb:154:in `draw_entity'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/ModelInterface.rb:905:in `attach_openstudio_model'
(eval):7:in `each_with_index'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/ModelInterface.rb:903:in `each'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/ModelInterface.rb:903:in `each_with_index'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/ModelInterface.rb:903:in `attach_openstudio_model'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/ModelManager.rb:217:in `attach_openstudio_model'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/ModelManager.rb:167:in `open_openstudio'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/CommandManager.rb:68:in `open_openstudio'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/ModelManager.rb:92:in `new_from_skp_model'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/observers/AppObserver.rb:53:in `onOpenModel'

Sent: Tuesday, July 30, 2013 10:57 AM
To: Goldwasser, David
Subject: SKP not connecting to OSM

Dear Mr. Goldwasser,
When I try to open my sketchup model, the OSM file does not successfully load. I had saved the SKP immediately after saving the OSM, so they should be linked. It's strange because when I launch the OpenStudio application from sketchup, it opens the correct OSM file. But, in SketchUp, the model looks all white or wire-frame and I cannot add new windows and such.
I ran the OSM Diagnostic Script and it found no problems. I have attached the SKP and OSM files. Does the size or shape of the zones in the model cause problems? This problem doesn't happen with my other models. Any advice would be greatly appreciated.

**Comment by macumber** [comment]
@DavidGoldwasser I think we broke this link, can we close this?
