### ISSUE TITLE
Doesn't look like OpenStudio::EndUseFuelType.getValues was updated for EnergyPlus 9.4

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#4091]
See link to issue on common measure for OpenStudio Results. The old code would loop through fuel types convert integer to string and then pass it to SQL tabular query. Additional Fuel was removed and a number of specific additional fuels were added.
https://github.com/NREL/openstudio-common-measures-gem/issues/26#issuecomment-698000362

My work around in measure for now is to use hard coded list of fuel types instead of the method.

**Comment by DavidGoldwasser** [comment]
Gas vs. Natural Gas may also be off, since I was seeing trouble with that as well.

**Comment by DavidGoldwasser** [comment]
I'm was also seeing some gas heating values missing from HVAC load profile and monthly values, but not sure it is due to this as the integer value of 1 returns "Natural Gas" which seems correct.
https://github.com/NREL/openstudio-common-measures-gem/issues/26#issuecomment-698001935

**Comment by DavidGoldwasser** [comment]
sqlFile.energyConsumptionByMonth(OpenStudio::EndUseFuelType.new(fuel_type) also fails with this error when new fuel types pass in. 

`Unknown OpenStudio Enum Value 'DIESEL'.`

**Comment by jmarrec** [comment]
@DavidGoldwasser Thanks for reporting this. I already expected OpenStudio results measure to face problems with the change. This is going to help doing a kind of compiler/script-error-driven development. I'm working on this.
