### ISSUE TITLE
Output:Table:Monthly for Gas not fucntioning

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#4092]
I think this is not formed correctly for EnergyPlus 9.4. It was made with OpenStudio 3.1.0 alpha

> Output:Table:Monthly,
  Building Energy Performance - Natural Gas, !- Name
  2,                                      !- Digits After Decimal
  InteriorEquipment:Gas,                  !- Variable or Meter Name 1
  SumOrAverage,                           !- Aggregation Type for Variable or Meter 1
  ExteriorEquipment:Gas,                  !- Variable or Meter Name 2
  SumOrAverage,                           !- Aggregation Type for Variable or Meter 2
  Heating:Gas,                            !- Variable or Meter Name 3
  SumOrAverage,                           !- Aggregation Type for Variable or Meter 3
  Cooling:Gas,                            !- Variable or Meter Name 4
  SumOrAverage,                           !- Aggregation Type for Variable or Meter 4
  WaterSystems:Gas,                       !- Variable or Meter Name 5
  SumOrAverage,                           !- Aggregation Type for Variable or Meter 5
  Cogeneration:Gas,                       !- Variable or Meter Name 6
  SumOrAverage;                           !- Aggregation Type for Variable or Meter 6

I think meter names should end with `:NaturalGas` or `:Natural Gas`.

This impacting the monthly results for gas and the hvac load profile table which also uses Gas

**Comment by DavidGoldwasser** [comment]
@jmarrec found where it is. Will fix Natural Gas add in new additional fuels
https://github.com/NREL/OpenStudio-workflow-gem/blob/3b5918b6a0d8891e245762600735abe729abe81b/lib/openstudio/workflow/jobs/resources/monthly_report.idf#L20

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio-workflow-gem/pull/120
