### ISSUE TITLE
Illuminance Mapr Rotation of 180 not correctly translated to E+ (Bugzilla #340)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#41]
On 2011-11-07 07:56:06, @macumber wrote:

> https://openstudio.nrel.gov/forums/openstudio-plug-google-sketchup/help-desk/illuminance-map
> 
> also need to check daylighting control

On 2011-11-29 10:37:15, @macumber wrote:

> This is the desired behavior, there is no correct way to map this to E+

On 2011-12-05 15:50:27, @DavidGoldwasser wrote:

> Seems we should warn user of this on export if we don't already.

On 2012-01-17 14:31:43, @DavidGoldwasser wrote:

> See if there is a warning issued for this.

On 2012-01-19 10:52:47, @DavidGoldwasser wrote:

> Batch moving bugs from SketchUp to "Code" component

On 2012-01-24 09:18:19, @DavidGoldwasser wrote:

> User reported and I confirmed same issue with daylighting control points. Maybe not an issue for illuminance map since E+ doesn't let you rotate them (although there is issue of global geometry rules to orient map with zone or with building.
> 
> Below is the warning on export to IDF.
> 
> Warning: Rotation of 180 radians about Z axis not mapped for OS:Daylighting:Control OS:Daylighting:Control 1

Keywords: ForwardTranslation

**Comment by DavidGoldwasser** [comment]
Needs testing. Maybe just issue for E+ vs. Radiance.

**Comment by macumber** [comment]
This is really just a nuisance warning, the field in OpenStudio doesn't have a place to go in IDF.

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp#L391

**Comment by DavidGoldwasser** [comment]
@macumber I assume this is fine to close?

**Comment by macumber** [comment]
Let's leave it open to remember to remove the warning

**Comment by jmarrec** [comment]
Permalink for where Dan linked to: https://github.com/NREL/OpenStudio/blob/c5bad04b2c03ddecf3bae3dd7d7721a56029212b/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp#L391

Nowadays (3.2.0-alpha):

https://github.com/NREL/OpenStudio/blob/a007b7801e3bb05731f012f585facdd814ef31fb/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp#L447-L450

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio/commit/7b2ebb57f1a5ca68e8c127dc5f575cb34d9984cc#diff-4d39d5c3b1480744fc212ca967d52012d6ef5963d84d89291acdd75df0547ec3 (PR #3858) changed things a bit
