### ISSUE TITLE
OS 3.1 EMS actuators

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4102]
Issue overview
--------------

A couple EMS actuators were changed right at the end in E+ 9.4. See https://github.com/NREL/EnergyPlus/pull/8304. I see lots of references to the old strings in the OpenStudio repo.

**Comment by jmarrec** [comment]
Thanks for the catch @shorowit . please see #4104 to ensure I didn't forget something, but I think it looks fine.

**Comment by jmarrec** [comment]
I messed up in #4104, I forgot to deal with version translation.
