### ISSUE TITLE
openstudio CLI measure update command is outdated

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/OpenStudio#4108]
Issue overview
--------------
The `openstudio measure -u path/to/measure` method updates the measure .xml file.  Currently, it is adding an <error> tag to the .xml

## Current Behavior
Currently, this command is adding an error line at the end of the .xml like this:
`<error>Unable to extract OpenStudio::Measure::OSMeasure object from C:/Users/mdahlhau/Documents/GitHub/PW-Corporate/speed_measures/ServerMeasures/speed_hvac/measure.rb. The script should contain a class that derives from OpenStudio::Measure::OSMeasure and should close with a line stating the class name followed by .new.registerWithApplication.</error>`
In OpenStudio v2.0+ series, the measure object was changed to the OpenStudio::Measure::ModelMeasure object, which is what I'm using in this measure.
The .xml still gets updated.

## Expected Behavior
The expected behavior is that the measure updater will look for a ModelMeasure (or other measure) object.

## Steps to Reproduce
Pull down any measure in the model articulation repo.
Install the openstudio CLI on a windows machine.
Change the measure.rb or test file in some way.
Run `openstudio measure -u path/to/measure`

## Possible Solution
Add ModelMeasure and the other <Type>Measure to the update function in the CLI.

### Environment
Windows 10

Some additional details about your environment for this issue (if relevant):
Windows 10
OpenStudio v3.1.0, though I've seen this going back at least to OS v2.8.0.

### Context
I'm trying to update measure .xmls.

**Comment by jmarrec** [comment]
Tested on **Ubuntu**, it appears to work with rc1. I will test on windows 10 next

```bash
cd openstudio-model-articulation-gem/lib/measures/AssignConstructionSetToBuilding
# Make meaningless change to measure.rb
$os_build_rel/Products/openstudio openstudio_version
3.1.0-rc1+6742e79574

$os_build_rel/Products/openstudio measure -u .
git diff measure.xml
```

```diff
diff --git a/lib/measures/AssignConstructionSetToBuilding/measure.xml b/lib/measures/AssignConstructionSetToBuilding/measure.xml
index 11317ab..6f01b7c 100644
--- a/lib/measures/AssignConstructionSetToBuilding/measure.xml
+++ b/lib/measures/AssignConstructionSetToBuilding/measure.xml
@@ -1,9 +1,10 @@
+<?xml version="1.0"?>
 <measure>
   <schema_version>3.0</schema_version>
   <name>assign_construction_set_to_building</name>
   <uid>6e68ddea-2cff-47a3-9daf-f2189e4cf132</uid>
-  <version_id>7d0a6fbc-4921-4fa8-bdc2-081108e9d60e</version_id>
-  <version_modified>20200229T024044Z</version_modified>
+  <version_id>a8d43858-bf7f-48cb-ab0c-0ddcc010e6ea</version_id>
+  <version_modified>20201006T092646Z</version_modified>
   <xml_checksum>1E963D9C</xml_checksum>
   <class_name>AssignConstructionSetToBuilding</class_name>
   <display_name>AssignConstructionSetToBuilding</display_name>
@@ -16,17 +17,17 @@
       <type>Choice</type>
       <required>true</required>
       <model_dependent>false</model_dependent>
-      <default_value>&lt;clear field></default_value>
+      <default_value>{c056207f-f51b-4c1b-aefe-3d5dbebcef57}</default_value>
       <choices>
         <choice>
-          <value>{96f339b3-3b1a-4d56-9da8-e8b682a5cf14}</value>
-          <display_name>&lt;clear field></display_name>
+          <value>{c056207f-f51b-4c1b-aefe-3d5dbebcef57}</value>
+          <display_name>&lt;clear field&gt;</display_name>
         </choice>
       </choices>
     </argument>
   </arguments>
-  <outputs/>
-  <provenances/>
+  <outputs />
+  <provenances />
   <tags>
     <tag>Envelope.Opaque</tag>
   </tags>
@@ -61,17 +62,6 @@
       <usage_type>readme</usage_type>
       <checksum>26A13C70</checksum>
     </file>
-    <file>
-      <version>
-        <software_program>OpenStudio</software_program>
-        <identifier>2.0.0</identifier>
-        <min_compatible>2.0.0</min_compatible>
-      </version>
-      <filename>measure.rb</filename>
-      <filetype>rb</filetype>
-      <usage_type>script</usage_type>
-      <checksum>6539FFE0</checksum>
-    </file>
     <file>
       <filename>AssignConstructionSetToBuilding_Test.rb</filename>
       <filetype>rb</filetype>
@@ -84,5 +74,16 @@
       <usage_type>license</usage_type>
       <checksum>E0468DD6</checksum>
     </file>
+    <file>
+      <version>
+        <software_program>OpenStudio</software_program>
+        <identifier>2.0.0</identifier>
+        <min_compatible>2.0.0</min_compatible>
+      </version>
+      <filename>measure.rb</filename>
+      <filetype>rb</filetype>
+      <usage_type>script</usage_type>
+      <checksum>09690542</checksum>
+    </file>
   </files>
 </measure>
```

**Comment by mdahlhausen** [comment]
my measure works fine; but I've seen the error on a lot of files.  Maybe it is related to the README?
We can set up a quick video conference and I can show you the error on my machine and we can try to reproduce it from there.

**Comment by mdahlhausen** [comment]
[nze_hvac.zip](https://github.com/NREL/OpenStudio/files/5336885/nze_hvac.zip)
Example measure that experiences this issue on my computer.

**Comment by macumber** [comment]
This relates to https://github.com/NREL/OpenStudio-workflow-gem/issues/122

OpenStudio should embed the error element under the main root, XML files should have only one root element

**Comment by tijcolem** [comment]
This is not reproducible with 3.1.0 release candidates so closing this issue.
