### ISSUE TITLE
3.1.0-rc1 Ruby bindings on Windows sql parse segfaults

### ISSUE THREAD

**Issue by tijcolem** [NREL/OpenStudio#4109]
This issue originated and discovered by @mdahlhausen. See the issue/problem below. 

--------------
Using ruby bindings on Windows segfaults when parsing eplusout.sql results file. 

## Expected Behavior
It should parse the eplusout.sql or fail gracefully if the eplusout.sql file is corrupt and/or returning incorrect info (e.g. bad query). 

## Steps to Reproduce
Using openstudio 3.1.0-rc1](https://github.com/NREL/OpenStudio/releases/tag/v3.1.0-rc1) run the following script using ruby bindings. See attached eplusout.zip (unzip first). 

```
require 'openstudio'
model = OpenStudio::Model::Model.new()
sql_fle_path = "#{File.dirname(__FILE__)}/eplusout.sql"
sql_file = OpenStudio::SqlFile.new(OpenStudio::Path.new(sql_fle_path))
model.setSqlFile(sql_file)
error_query = "SELECT ErrorMessage FROM Errors WHERE ErrorType in(1,2)"
errs = model.sqlFile.get.execAndReturnVectorOfString(error_query)
```
[eplusout.zip](https://github.com/NREL/OpenStudio/files/5334732/eplusout.zip)

### Environment

Some additional details about your environment for this issue (if relevant):
 - Windows 10 Pro x64
-  [Ruby 2.5.5 ](https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-2.5.5-1/rubyinstaller-devkit-2.5.5-1-x64.exe)

 - [OpenStudio-3.1.0-rc1+062e7a8260-Windows.exe](https://github.com/NREL/OpenStudio/releases/download/v3.1.0-rc1/OpenStudio-3.1.0-rc1+062e7a8260-Windows.exe)

**Comment by mdahlhausen** [comment]
To generalize this, any call to get a string from the sql file fails
`execAndReturnFirstString` and `execAndReturnVectorOfString` methods
```
# load sql as per the comment above
sql = model.sqlFile.get
string_query = "SELECT EnvironmentName FROM EnvironmentPeriods"
strings = sql.execAndReturnFirstString(string_query)
```

**Comment by lefticus** [comment]
@tijcolem I created a PR #4115 to address this.

I only tested on Windows so far, I'll kick off a sanity check on Linux right now.

**Comment by tijcolem** [comment]
Thanks @lefticus!  I'll get a build going and we'll do some internal testing. This is great.

**Comment by lefticus** [comment]
Linux looked good from my perspective.

**Comment by tijcolem** [comment]
Yep, Windows, Linux and mac all look good.  Just doing some internal testing here to confirm and then we'll get this merged in.
