### ISSUE TITLE
Bug importing Shading:Building and Shading:Site objects from IDF

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#4111]
See original report in OS App issues: https://github.com/openstudiocoalition/OpenStudioApplication/issues/242

**Comment by tijcolem** [comment]
@jmarrec Have you had a chance to look into this?

**Comment by jmarrec** [comment]
I'm looking into it now. I can see that OpenStudio import and DXF generation from E+ differ. I also don't know if I can trust the DXF feature in E+ though, I'm pretty sure I found a bug right now.

**Comment by jmarrec** [comment]
Will be fixed in https://github.com/NREL/OpenStudio/pull/4235
