### ISSUE TITLE
Error running create_DOE_prototype_building in 3.1.0-rc1

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#4112]
## Current Behavior
create_DOE_prototype_building from https://github.com/NREL/openstudio-model-articulation-gem/ fails to run in OpenStudio 3.1.0-rc1

## Expected Behavior
create_DOE_prototype_building runs successfully

## Steps to Reproduce

1. Unzip attached model
2. `/c/openstudio-3.1.0-rc1/bin/openstudio.exe run -w in.osw`

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows and Mac
 - Version of OpenStudio - 3.1.0.-rc1

### Context
Trying to run the following simulation with:

`/c/openstudio-3.1.0-rc1/bin/openstudio.exe run -w in.osw`

[create_DOE_prototype_building_debug.zip]
(https://github.com/NREL/OpenStudio/files/5338197/create_DOE_prototype_building_debug.zip)

This model works with OpenStudio 3.0.1

**Comment by tijcolem** [comment]
@macumber thanks for the report. @DavidGoldwasser Caught some errors when testing 3.1.0-rc1 with https://github.com/NREL/openstudio-model-articulation-gem/. We posted a 3.1.0-rc2 which resolved some of the issues but are still investigating the remaining ones.

**Comment by tijcolem** [comment]
I can reproduce this on my local machine. This is what I know so far. 

1 ) The error appears to do with not finding the weather file:  
`11:43:24.282120 ERROR] [openstudio.weather.Model] Stat file: :/ruby/2.5.0/gems/openstudio-standards-0.2.12.rc6/lib/openstudio-standards/weather/../../../data/weather/USA_FL_Tampa-MacDill.AFB.747880_TMY3.stat was not found when calculating ground temperatures.`

2 ) This `USA_FL_Tampa-MacDill.AFB.747880_TMY3.stat `is included in the latest openstudio-gems package.  e.g. https://openstudio-resources.amazonaws.com/dependencies/openstudio3-gems-20201007-darwin.tar.gz

find . -type f -name "USA_FL_Tampa-MacDill.AFB.747880_TMY3.stat"  
./ruby/2.5.0/gems/openstudio-standards-0.2.12.rc6/data/weather/USA_FL_Tampa-MacDill.AFB.747880_TMY3.stat

3 ) .stat files are embedded into the cli - https://github.com/NREL/OpenStudio/blob/develop/src/cli/CMakeLists.txt#L45

So it should be there, but clearly, it's not finding.

Interestingly, if you run the cli using custom gems option and reference the openstudio-standards gems, it works. This is the same standards gems that is the embedded cli tool I am running.  

Steps to run via custom gems 

Create Gemfile
```
cat >> Gemfile <<EOL
source 'http://rubygems.org' 
ruby "~> 2.5.0"
gem 'openstudio-standards', '= 0.2.12.rc6'
EOL
```

`bundle install --path gems`

`openstudio --bundle Gemfile --bundle_path Gemfile  run -w in.osw  => works`

**Comment by asparke2** [comment]
Problem is that openstudio-standards needs to first extract the epw/stat/ddy files from the CLI's embedded filesystem and write them to local disk, then check if they exist using `File.exist?`, then lastly read/parse them to extract info.  That process was not used by the code reading the `.stat` file when looking for ground temperatures.  Should be fixed when [this branch]( https://github.com/NREL/openstudio-standards/tree/fix/read_embedded_weather_files) is merged into openstudio-standards.

**Comment by tijcolem** [comment]
Thanks @asparke2!  I created a 3.1.0-rc3 with those standards changes and verified this does work (reproduced on my local mac). 

I'll be posted 3.1.0-rc3 installers here shortly.

**Comment by tijcolem** [comment]
Fixed via
https://github.com/NREL/OpenStudio/commit/dec0b9e0690c29c1bef72897a379a71b744b5085

Fixed via
https://github.com/NREL/openstudio-standards/commit/9a11ccd3f3af6d826a5b06c1391eb3132f881e53
