### ISSUE TITLE
Provide `openstudio --version` to confirm with common CLI conventions

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#4113]
Enhancement Request
--------------

I keep getting bit by this. I'm so used to doing `<CLI> --version` to get the version that I often do it for openstudio as well, only to get the help message and have to do `openstudio openstudio_version`. This is annoying.

## Possible Implementation

Just shortcut in the parsing of arguments similar to `-h/--help`

**Comment by shorowit** [comment]
👍 This has always bothered me as well.

**Comment by tijcolem** [comment]
closed via #4114
