### ISSUE TITLE
FanZoneExhaust schedule fields disabled in App for objects created with API

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#4116]
Issue overview
--------------
FanZoneExhaust objects created with the API have two schedule fields disabled in the App. Objects added to a model in the App are fine. Found in 2.9.0, but I assume it's present in newer versions based on a quick look at git blame.

## Current Behavior

![image](https://user-images.githubusercontent.com/8397034/95406733-6081a780-08d8-11eb-8c2a-bea437950677.png)

## Expected Behavior

![image](https://user-images.githubusercontent.com/8397034/95406798-89a23800-08d8-11eb-9a49-81847d5909c0.png)

## Steps to Reproduce

1. 
```
require 'openstudio'
include OpenStudio::Model
m = Model.new
tz = ThermalZone.new(m)
fze = FanZoneExhaust.new(m)
fze.addToThermalZone(tz)
m.save
```
2. Open model and add FanZoneExhaust to zone with an object from the library

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 10
 - Version of OpenStudio (if using an intermediate build, include SHA): 2.9.0

**Comment by jmarrec** [comment]
@MatthewSteen This looks like an OSApp issue, so report on https://github.com/openstudiocoalition/OpenStudioApplication/ instead no?

**Comment by jmarrec** [comment]
The hvac_library.osm properly initialized the schedule fields, so you can edit them in the App.
