### ISSUE TITLE
Can't install plugin for SketchUp 2019 or 2020

### ISSUE THREAD

**Issue by ReneDyhr** [NREL/OpenStudio#4118]
Issue overview
--------------
I have tried installing both SketchUp 2019 and 2020 trial mode and then installing the newest OpenStudio 3.0.1.
No matter what I do, I can't seem to get it to install the plugin for SketchUp

## Current Behavior
It doesn't install the OpenStudio Application and doesn't install the plugin for SketchUp

## Expected Behavior
Integration to SketchUp

### Environment
Windows 10

**Comment by jmarrec** [comment]
You can find the OpenStudioApplication at https://github.com/openstudiocoalition/OpenStudioApplication/ and the plugin repo is at https://github.com/openstudiocoalition/OpenStudioApplication/

**Please read the release notes:** https://github.com/NREL/OpenStudio/releases/tag/v3.0.0

> Following an important announcement related to future development of the OpenStudio Application released in September 2019 ([A Shift in BTO’s BEM Strategy: A New Future for the OpenStudio Application](https://www.openstudio.net/new-future-for-openstudio-application)), **this release marks the first installment of the separated OpenStudio SDK from the Application.**
Going forward, the SDK will continue to be distributed and released two times per year, in April and October. Development of the OpenStudioApplication has been moved to its own [NREL/OpenStudioApplication](https://github.com/NREL/OpenStudioApplication/) GitHub.

Below is the list of components that is included in this SDK installer:

__**OpenStudio SDK 3.0.0**__
- EnergyPlus
- Command Line Interface (CLI)
- Radiance
- Ruby API
- C++ SDK

**Comment by ReneDyhr** [comment]
Do I need to use the application and plug-in to use the newest sketchup? If so, does it then contain the newest updates as well with this repo?

**Comment by jmarrec** [comment]
Release Notes for how to install the sketchup plugin: https://github.com/openstudiocoalition/openstudio-sketchup-plugin/releases/tag/v1.0.1
