### ISSUE TITLE
SqlFile Crash

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#4126]
A bug was recently identified and fixed when using the SqlFile class from Ruby on windows https://github.com/NREL/OpenStudio/issues/4109

More recently it has been uncovered that the same issue exists anytime the SqlFile class is used from code compiled into a DLL and then linked to the OpenStudio.dll. This happens because of a couple of aligning facts.

1. The sqlite3 library depends on some global data
2. Much of the SqlFile implementation is now inlined
3. On windows the global data used by sqlite3 is actually scoped to the dll boundary and not in fact truly global

The proposed fix is to refactor all of the sqlite3 api calls into cpp source files, and remove these api calls from the inline header implementation.

**Comment by lefticus** [comment]
See #4128 for a proposed fix.
