### ISSUE TITLE
Misaligned sizing fields for VAV system sizing

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/OpenStudio#4131]
Issue overview
--------------
Currently, the default sizing behavior for systems in OpenStudio (also with the App) is:
'ZoneSum' in the 'System Outdoor Air Method' field of the 'Sizing:System` object
'VentilationRateProcedure' in the 'System Outdoor Air Method' field of the 'Controller:MechanicalVentilation' object, which is not exposed in the app.

These two values should be aligned.

## Current Behavior
For system sizing in cold climate zones (e.g. 6A), this issue results in undersizing of the main heating coil and supply air temperature during the design day run being ~1
[heating_sizing_debugging.xlsx](https://github.com/NREL/OpenStudio/files/5431841/heating_sizing_debugging.xlsx)
5F instead of the intended 55F.  The coil sizing details assume some amount of mixed air, even if the '100% outdoor air in heating' field is set to Yes in the Sizing:System object.  I'm not exactly clear on the 

## Expected Behavior
There should be warning or way to default the System Outdoor Air Method to use either the field in the Controller:MechanicalVentilation object, or the one in the Sizing System object.  I don't see a reason why they should be different during design sizing.

## Steps to Reproduce
Here is an example base model (120 zone office, served by VAV, in climate zone 6A).
[heating_sizing_debugging.zip](https://github.com/NREL/OpenStudio/files/5431847/heating_sizing_debugging.zip)
I've included an output spreadsheet of coil sizing results.

## Possible Solution
We need to have some discussion here on the best way to resolve this - either having one field default to the value in the other field, adding a warning message, or at least making sure this is available in the app.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):  Windows
 - Version of OpenStudio (if using an intermediate build, include SHA): OS > 3.0

### Context
This is causing an issue for any models using default HVAC constructors in openstudio-standards.  I can set both fields in the API, so there is no pressing need for a new release, but several other users may run into this sizing issue.

Thanks to @asparke2 and @kbenne for helping narrow down the issue.

**Comment by jmarrec** [comment]
This appears to be an OSApp issue only. The SDK Ctor are aligned, and the getter/setters exist for these fields.


https://github.com/NREL/OpenStudio/blob/a95f25828c28e59dc9a31caee0871515d3aed265/src/model/SizingSystem.cpp#L1016

https://github.com/NREL/OpenStudio/blob/a95f25828c28e59dc9a31caee0871515d3aed265/src/model/ControllerMechanicalVentilation.cpp#L195

**Comment by jmarrec** [comment]
Another thing that could explain why you see VentilationRateProcedure (in the Sizing:System though, not the controller OA (the other way around than in your OP) is perhaps the use a measure that relies on os_lib_hvac.rb: https://github.com/NREL/openstudio-extension-gem/blob/1b668ff44ff69dfdb64b21f32d06fc5b6ffc42c8/lib/openstudio/extension/core/os_lib_hvac.rb#L807

**Comment by asparke2** [comment]
I think the root of this confusion is that there was a behavior change in E+ that needs to be considered.  See documentation below:

**E+ 8.0 Sizing:System Field: System Outdoor Air Method**
The method used to calculate the system minimum outdoor air flow. The two choices are ZoneSum and VentilationRateProcedure (VRP). ZoneSum sums the outdoor air flows across all zones served by the system. VRP uses the multi-zone equations defined in 62.1-2007 to calculate the system outdoor air flow. VRP considers zone air distribution effectiveness and zone diversification of outdoor air fractions.

[E+ 9.4 Sizing:System Field: System Outdoor Air Method](https://bigladdersoftware.com/epx/docs/9-4/input-output-reference/group-design-objects.html#field-system-outdoor-air-method-000)
The method used to calculate the system minimum outdoor air flow. The two choices are ZoneSum and VentilationRateProcedure (VRP). ZoneSum sums the outdoor air flows across all zones served by the system. VRP uses the multi-zone equations defined in 62.1-2007 to calculate the system outdoor air flow. VRP considers zone air distribution effectiveness and zone diversification of outdoor air fractions. **VRP may also adjust autosized air terminal maximum and minimum supply flow rates if needed to ensure adequate outdoor air flow rate to each zone.**

Somewhere between 8.0 and 9.4, selecting `VentilationRateProcedure` also started to adjust the minimum damper positions, which in turn changes other aspects of sizing.  In the DOE prototype model creation process, there is [code that does this before E+ runs](https://github.com/NREL/openstudio-standards/blob/c9fd21e5f98d68145e9a6f6419fff4a469da563b/lib/openstudio-standards/standards/Standards.AirLoopHVAC.rb#L1746).

When you choose `VentilationRateProcedure` in the `Controller:MechanicalVentilation Field: System Outdoor Air Method`, then during the sizing run, the OA is governed by 62.1.  Depending on when the Sizing:System adjusts the minimum OA dampers positions (before or after running the design days), that could explain what's going on here.
