### ISSUE TITLE
CLI error using Windows Command Prompt

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4132]
Issue overview
--------------
I usually test the CLI on Windows using PowerShell, and it works fine:
![image](https://user-images.githubusercontent.com/5861765/97480039-83700c00-1918-11eb-84ef-263f94f49151.png)

But if I try to use Windows Command Prompt instead, it fails:
![image](https://user-images.githubusercontent.com/5861765/97480101-9682dc00-1918-11eb-9765-31e0520ad068.png)

The error is:
```
Exception: Embedded file not found ':c:/ruby/2.5.0/net/protocol.rb'
eval:172:in `getFileAsString': unexpected return
```

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 10
 - Version of OpenStudio (if using an intermediate build, include SHA): OpenStudio 3.1.0

**Comment by shorowit** [comment]
I'll note that some software developers outside NREL also encountered this error. I was thoroughly confused as to why they were hitting it, until I happened to try switching from PowerShell to Command Prompt and reproduced the error myself.

**Comment by jmarrec** [comment]
It works on my machine...

![image](https://user-images.githubusercontent.com/5479063/97550147-9266c500-19d1-11eb-9e39-12e76415110c.png)

**Comment by shorowit** [comment]
How weird is this?

![image](https://user-images.githubusercontent.com/5861765/97582067-f205a600-19ba-11eb-9453-0f769e100d99.png)

Note that C:\OpenStudio-3.1.0\bin\ is in my PATH.

**Comment by jmarrec** [comment]
Its on my path also. So is ruby 2.5
What else is in your PATH?

**Comment by shorowit** [comment]
I have ruby 2.5 in my PATH too.

![image](https://user-images.githubusercontent.com/5861765/97633425-b4743d80-19f9-11eb-85b4-a6d4b2e58528.png)

**Comment by tijcolem** [comment]
I was able to reproduce the same error as @shorowit. Then I ran the windows update utility and restarted my machine and now it works.  

![openstudio_cli_windows_cmd_error](https://user-images.githubusercontent.com/7087120/97724540-a8888a00-1a92-11eb-8cf6-596ad7afe2af.png)

My guesses as to why this would work would be registry settings that are refreshed/read on restart or the build version of windows.

**Comment by shorowit** [comment]
I still get different results when I run from the openstudio-3.1.0\bin dir versus somewhere else. @tijcolem, can you try running it from the bin dir?

For what it's worth, my machine is up to date (no Windows updates) and I recently restarted it. Still able to reproduce the error.

**Comment by tijcolem** [comment]
@shorowit  Yeah it does error when running the openstudio-3.1.0\bin dir vs elsewhere. So the same as what you are experiencing. 

![cli_error_2](https://user-images.githubusercontent.com/7087120/97727343-eaff9600-1a95-11eb-863b-925c15863a2b.png)

**Comment by arif-hanif** [comment]
i can report i get same error

**Comment by tijcolem** [comment]
Revisiting this error and discovered the problem is due to the case sensitive of "C" vs "c:" in windows command prompt. 
Observe the behavior below.  

Upper case C: drive
![upper_case](https://user-images.githubusercontent.com/7087120/101090437-e5eda500-3573-11eb-95f0-d9ef4c79ee09.png)

Lower case c: drive 
![lower_case](https://user-images.githubusercontent.com/7087120/101090502-fa31a200-3573-11eb-9fe7-4dbb0b67ee6c.png)

The fact that windows allows you to cd into lower case drive letter is somewhat funny, but clearly, the embedded ruby code in OpenStudio is case sensitive so it's picking up the working directly with "c" and cannot find the embedded files, and hence the error. This should be simple matter of just calling an .upcase function on the working directly for windows OS.

**Comment by shorowit** [comment]
😲

Wow, that is hilarious! Nice job tracking that down.

**Comment by jmarrec** [comment]
Boy, if somebody made that kind of bug on purposes to drive us nuts, he'd be a genius of evil.
