### ISSUE TITLE
Update Ruby to 2.7.0

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#4134]
Enhancement Request
--------------
It seems like just yesterday Ruby 2.5 seemed so new and fresh but it is getting long in the tooth and is headed for [end of life next March]( https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/#:~:text=Ruby%202.5%20series&text=except%20security%20fixes.-,If%20a%20critical%20security%20issue%20is%20found%2C%20we%20will%20release,the%20end%20of%20March%202021.)

I suggest updating to Ruby 2.7 series which is what the [Ubuntu 20.04 LTS release is using](https://packages.ubuntu.com/focal/ruby).

**Comment by macumber** [comment]
Wondering if this could be slated for the 3.2.0 or 3.3.0 release next year?

**Comment by jmarrec** [comment]
I've scoped the trouble to get an idea of how bad it would be.

see https://github.com/NREL/conan-openstudio-ruby/pull/31

Linux and Mac appear to be pretty much working (`openstudio --help` works) and windows has a few linking issues. But it's doable to fix.

**Comment by tijcolem** [comment]
@macumber  Is SketchUp now using 2.7.x series now?  I thought the ruby version was loosely tied to SketchUp.

**Comment by DavidGoldwasser** [comment]
@tijcolem SketchUp 2021 is using Ruby 2.7.1

**Comment by jmarrec** [comment]
https://ruby.sketchup.com/file.ReleaseNotes.html#label-Upgrade+Ruby+to+2.7.1

**Comment by tijcolem** [comment]
Checklist for updating to ruby 2.7.2

- [x] Build ruby 2.7.2 on all platforms and compilers (gcc 7,8,9, apple-clang 10,11, msvc 2019) * Dropped msvc 2017
- [x] Gem::Specification.add_spec was dropped in 2.7.2 so adding spec dirs as an alternative way of handling adding embedded specs.   
- [ ] Update openstudio-extension 0.3.0 [PR](https://github.com/NREL/openstudio-extension-gem/pull/106) 
- [ ] Update bcl 0.7.0 
- [ ] Update openstudio-workflow 2.2.0 [PR](https://github.com/NREL/OpenStudio-workflow-gem/pull/127)
- [ ] Update openstudio_measure_tester 0.3.0 [PR](https://github.com/NREL/OpenStudio-measure-tester-gem/pull/49)
- [x] Create a test gems package and use with OpenStudio. [ruby272](https://github.com/NREL/OpenStudio/tree/ruby_272)
- [x] Build and clean up tests for OpenStudio cli
- [ ] Update CI to use new ruby 2.7.2 images. Probably update to bases ubuntu 20.04 image as well.
