### ISSUE TITLE
LoadError changes current working directory in CLI

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#4150]
Issue overview
--------------
Loading a measure with a rescued LoadError in a workflow causes the current working directory to change.

## Current Behavior
Loading a measure which tries to load a gem but then falls back to load a resource file results in the current working directory changing.  This causes problems if the measure attempts to write a file.

## Expected Behavior
Rescuing the LoadError should not change the current working directory.

## Steps to Reproduce
`/c/openstudio-3.1.0/bin/openstudio.exe run -m -w workflow.osw` fails
`/c/openstudio-3.0.0/bin/openstudio.exe run -m -w workflow.osw` fails
`/c/openstudio-2.9.1/bin/openstudio.exe run -m -w workflow.osw` succeeds

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 10
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.1.0 and 3.0.0

**Comment by macumber** [comment]
[bug.zip](https://github.com/NREL/OpenStudio/files/5600439/bug.zip)

**Comment by tijcolem** [comment]
Thanks for the report on this @macumber. I am looking into this now. 

Looks like this is happening in the workflow gem. Possibly in this step here.  
https://github.com/NREL/OpenStudio-workflow-gem/blob/develop/lib/openstudio/workflow/run.rb#L290

**Comment by tijcolem** [comment]
fix for this is here.  https://github.com/NREL/OpenStudio-workflow-gem/pull/130 
I think this is happening in load.c and related to how it's working within the CLI.  Using `load` in pure ruby doesn't change cwd.

**Comment by tijcolem** [comment]
fixed via NREL/OpenStudio-workflow-gem#130
