### ISSUE TITLE
Recursive copy of the resources/ subfolder of a measure

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#4156]
Enhancement Request
--------------

User on unmethours here https://unmethours.com/question/49382/os-measure-subfolder/?comment=49406#post-id-49406 indicated he has many support files (eg: CSVs). Files need to be placed in the `resources/` subfolder so they are copied when cloning the measure. But it seems that copy is non recursive, so any subfolder under `resources/` (eg: `resources/data/`) is NOT copied. User would like a way to organize them better.

## Detailed Description

https://github.com/NREL/OpenStudio/blob/89408c89dc7e9f9dbf7ed258fa919ea6c2e6ce1f/src/utilities/bcl/BCLMeasure.cpp#L1106-L1135

## Possible Implementation

Make the copy recursive.

**Comment by jmarrec** [comment]
Here is a test measure I created:

```
└── recursive_resources_directory
    ├── asubfolder
    │   └── asubfile_in_another_subfolder.csv
    ├── docs
    ├── LICENSE.md
    ├── measure.rb
    ├── measure.xml
    ├── README.md
    ├── README.md.erb
    ├── resources
    │   ├── data
    │   │   └── subfile.csv
    │   ├── root.csv
    │   └── root.json
    └── tests
        ├── example_model.osm
        └── recursive_resources_directory_test.rb
```

here is the diff after cloning to my model subfolder:

```diff
--- ori.txt	2020-12-08 11:10:12.501257582 +0100
+++ new.txt	2020-12-08 11:10:09.833213729 +0100
@@ -1,17 +1,12 @@
 └── recursive_resources_directory
-    ├── asubfolder
-    │   └── asubfile_in_another_subfolder.csv
-    ├── docs
     ├── LICENSE.md
     ├── measure.rb
     ├── measure.xml
     ├── README.md
     ├── README.md.erb
     ├── resources
-    │   ├── data
-    │   │   └── subfile.csv
-    │   ├── root.csv
-    │   └── root.json
+    │   ├── root.csv
+    │   └── root.json
     └── tests
         ├── example_model.osm
         └── recursive_resources_directory_test.rb

```

**Comment by jmarrec** [comment]
This is more complicated than it looked at first glance. Places that would need to change:

https://github.com/NREL/OpenStudio/blob/ec74aaed8f61700a90b7cee3fe2eabd6c3f8fd32/src/utilities/bcl/BCLMeasure.cpp#L986-L1003

Potentially needs adjustment too:
https://github.com/NREL/OpenStudio/blob/ec74aaed8f61700a90b7cee3fe2eabd6c3f8fd32/src/utilities/bcl/BCLXML.cpp#L202-L233

**Comment by shorowit** [comment]
👍 👍 👍 

We would really like this. We have several measures that would benefit from being able to organize our resource files into subdirs.

FWIW, I recently asked @DavidGoldwasser about this and he said "No, it isn’t supported, It might, work at least locally, but would certainly break BCL which doesn’t expect that. The measure.xml will probably not pickup those files, and may not work on OpenStudio server. You also can’t make up other directory names that aren’t supported, documentation and tests are two other directories that are supported."

cc @joseph-robertson

**Comment by jmarrec** [comment]
The source code for the bcl website isn't open source, so I wouldn't want to speculate what it can or cannot do and how easy it is to fix. 

As far as openstudio SDK is concerned, it is doable for sure. 

As soon as it deals with directories and files it's typically annoying to test, as writing unit tests get tricky and you will get different problems on Windows than you do on Unix generally.

The question is whether it's worth it to spend time doing it. If we do think it is, I'm happy to take a crack at it.

**Comment by tijcolem** [comment]
Let's make this a lower priorty. I was also wondering if this can be implemented in boost?

**Comment by tijcolem** [comment]
All good to work on!

**Comment by DavidGoldwasser** [comment]
@kflemin and @nllong should be on this thread, as they need to support it in BCL. Future GitHub based BCL might make this easier? Measure manger and updates measure.xml

**Comment by DavidGoldwasser** [comment]
To me it makes more sense to support multiple directories under resources than to have users add random directories with their measure. Is it enough to allow just one level of nesting, or should users be allowed to go unknown levels down? It could be argued at some level of complexity of their resources they should distribute it as a gem? Assuming it is easy for them to add that gem to the OpenStudio CLI call.

**Comment by jmarrec** [comment]
Allowing nesting could be problematic on windows because of long paths limit (260 chars). Users dowloading BCL measures could see them not working if they end up exceeding 260 chars.

eg:

```
In [1]: len("C:/Users/julien/BCL/a25386cd-60e4-46bc-8b11-c755f379d916/59a144aa-c7c3-4da9-99bf-3c6758c7e577")
Out[1]: 93
```

**Comment by tijcolem** [comment]
The new BCL soft launch will be June. Perhaps once this is out then we can revisit this once that comes online.

**Comment by tijcolem** [comment]
@jmarrec [BCL2.0]( https://bcl2.nrel.gov/) is now online so we can probably resume this issue.

**Comment by jmarrec** [comment]
Cool. Who's a good resource to ask questions about how bcl2 does things to design how it should work?

**Comment by tijcolem** [comment]
@axelstudios Would be a good resource for BCL 2.0 related questions.

**Comment by jmarrec** [comment]
I'm scoping out this issue, and have a few questions about the design. I was hoping to get some input from people.

Question 1: 
a. Should we allow nesting subdirectories only under "resources"?
b. should we allow nesting subdirectories only under the approved directories ( resources docs tests )?
c. should we support any arbitrary structure (excluding the test/output directory that we expect to be created via openstudio measure --run-tests and probably any folder/file starting with . )

**Comment by shorowit** [comment]
I vote for B -- allow nesting subdirectories only under the approved directories ( resources docs tests ).

**Comment by jmarrec** [comment]
@shorowit So you want to allow A and E but not B,C , and D right?

**Comment by shorowit** [comment]
Right.

**Comment by DavidGoldwasser** [comment]
I want to bring in @nllong and @kflemin related to how it would impact BCL, and also PAT and OS Application (or other GUI's using BCL API)

**Comment by nllong** [comment]
As far as I know we would just need to emulate the behavior in PAT and the OpenStudio Analysis Gem, since I think they do their own zipping of resources.

**Comment by jmarrec** [comment]
BCL takes a zip of the folder, so it should be fine. BCLMeasure::clone is what matters, and how this ties into the XML.

THe measure.xml would be like this

```diff
  <file>
   <filename>resources.rb</filename>
   <filetype>rb</filetype>
   <usage_type>resource</usage_type>
   <checksum>200ACCE3</checksum>
  </file>
  <file>
+   <filename>subfolder/resources.rb</filename>
   <filetype>rb</filetype>
   <usage_type>resource</usage_type>
   <checksum>200ACCE3</checksum>
  </file>
```

OSApp definitely uses BCLMeasure::clone.

**Comment by jmarrec** [comment]
I thought that PAT was using the Measure Manager, so that should be fine as well no?

**Comment by nllong** [comment]
It does use measure manager to get/update measures. I think it zips up its own files before it sends off to OpenStudio Server (Analysis Framework) though. We just need to verify that it zips up all the directories before sending off to OS Server.

Da: Julien Marrec ***@***.***>
Data: venerdì, 20 agosto 2021 09:53
A: NREL/OpenStudio ***@***.***>
Cc: Long, Nicholas ***@***.***>, Mention ***@***.***>
Oggetto: Re: [NREL/OpenStudio] Recursive copy of the resources/ subfolder of a measure (#4156)

CAUTION: This email originated from outside of NREL. Do not click links or open attachments unless you recognize the sender and know the content is safe.

I thought that PAT was using the Measure Manager, so that should be fine as well no?

**Comment by DavidGoldwasser** [comment]
@jmarrec I'm fine with what what @shorowit suggested, only letting directories be nested under existing approved top level directories.

Regarding `docs` the use of that should only be for files not needed for the running of the measure. I don't know that it was ever implemented, but there was discussion of ignoring that when zipping up measure for openstudio analysis similar to ignoring `tests/output`. The downside of this is if you clone the measure you probably want to clone documentation. With us leaning on `readme.md` at the top level of the measure the main use for `docs` is relatively small png files. So may not be worth trying to remove that unless someone else has a different view.

**Comment by jmarrec** [comment]
When you clone a measure, currently the `docs/` directory is **not** cloned. Is this a behavior we want to keep, or should we clone the docs along with the measure?
