### ISSUE TITLE
ForwardTranslator typo in ElectricLoadCenterStorageConverter DesignMaximumContinuousInputPower field

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#4174]
Issue overview
--------------
A copy/paste typo in the forward translation of ElectricLoadCenterStorageConverter objects causes EnergyPlus to fail because it sets the _Simple Fixed Efficiency_  with the _Design Maximum Continuous Input Power_.

https://github.com/NREL/OpenStudio/blob/1e4f9fda38c9a4917b3a4a196a6c9f80d469502c/src/energyplus/ForwardTranslator/ForwardTranslateElectricLoadCenterStorageConverter.cpp#L75-L85

## Current Behavior

EnergyPlus will fail because the the _Simple Fixed Efficiency_, which is limited to values between 0.0 and 1.0, is set to the _Design Maximum Continuous Input Power_, which is almost always > 1.

## Expected Behavior

Forward translator should set the correct fields.

## Steps to Reproduce

See this Unmet Hours questions by @mattkoch (not sure if that's your GitHub username).

https://unmethours.com/question/50170/bug-in-os-sdk-290-for-oselectricloadcenterstorageconverter/?answer=50209#post-id-50209

## Possible Solution

Probably this...

    // designMaximumContinuousInputPower, optD
    optD = modelObject.designMaximumContinuousInputPower();
    if (optD) {
      idfObject.setDouble(ElectricLoadCenter_Storage_ConverterFields::DesignMaximumContinuousInputPower, *optD);
    }

## Details

NA

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA): 2.9.0

### Context
See Unmet Hours question above.

**Comment by shorowit** [comment]
https://github.com/NREL/OpenStudio/pull/4173
