### ISSUE TITLE
Openstudio Forward translator failing to translate ElectricLoadCenter:Distribution Inverter name attribute

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/OpenStudio#4175]
Issue overview
--------------
Models 
## Current Behavior
OpenStudio models using PVWatts Inverter Objects fail with the following error: (from eplusout.err)

 ** Severe  ** ElectPowerLoadCenter constructor ElectricLoadCenter:Distribution="ELECTRIC LOAD CENTER DISTRIBUTION 1", invalid entry.
   **   ~~~   ** Inverter Name is blank, but buss type requires inverter.
   **  Fatal  ** ElectPowerLoadCenter constructor Preceding errors terminate program

## Expected Behavior
Model should simulate as expected, without EnergyPlus failure 

## Steps to Reproduce

See attached files - .
1) in.osm file with properly specified ElectricLoadCenterDistribution object attributes
2) resulting in.idf file that is produced
 
## Possible Solution
It appears the forward translator is not properly handling the inverter assignment defined in the ElectricLoadCenterDistribution object.

## Details
N/A

### Environment

Some additional details about your environment for this issue (if relevant):
 - OpenStudio v3.1.0 (via OS App v1.1.0)
 - Windows 64 Bit OS

### Context
Not able to properly model ElectricLoadCenterDistribution interaction with PV Watts generation scenarios w/o potentially resorting to a EnergyPlus measure as a work around.

Not able to properly model ElectricLoadCenterDistribution  interaction with PV Watts + Simple Battery Storage either, which is a real drag. #

Proper operation of these features are needed to provide feedback for Grid Interactive Efficient Building Operation scenarios

**Comment by chrisbalbach** [comment]
[data_point.zip](https://github.com/NREL/OpenStudio/files/5752518/data_point.zip)

**Comment by chrisbalbach** [comment]
inspection of in.osm reveals data model appears complete. Inspection of in.idf file reveals data model is incomplete. 
Manual creation of inverter object (using idfeditor tool) and manual assignment of inverter object to Distribution Center object allows idf file to properly simulate.

**Comment by shorowit** [comment]
@chrisbalbach FWIW, we use PVWatts in the OS-HPXML workflow without a problem, see [relevant code here](https://github.com/NREL/OpenStudio-HPXML/blob/a305d6ddeb48df4413548f227d557ec56723b91e/HPXMLtoOpenStudio/resources/pv.rb#L17-L48). Maybe that will show you some way to avoid an EnergyPlus measure.

**Comment by joseph-robertson** [comment]
@chrisbalbach Couple of questions/observations about your osm.

Looks like you have 4 `ElectricLoadCenter:Distribution` objects in your osm:
* 1 and 3 have generators, but no inverters assigned (therefore I wouldn't expect inverters attached to these distribution objects in the idf)
* 2 and 4 have inverters, but no generators assigned (these distribution objects don't appear to be translated to idf; I'm investigating this)

Perhaps you're intending to have exactly 2 `ElectricLoadCenter:Distribution` objects in your model (combine distribution objects 1+2 and objects 3+4)?

**Comment by chrisbalbach** [comment]
My failed file appears to be due to an artifact of how the measure that inserts the ElectricLoad Distribution objects. 

Mea Culpa  (operator error)...

Closing issue.
