### ISSUE TITLE
Non-zero exit code for openstudio-cli ? 

### ISSUE THREAD

**Issue by spolloni** [NREL/OpenStudio#4177]
Enhancement Request
--------------
I am very new to OpenStudio, but found that the CLI `run` subcommand always returns zero exit codes even when the E+ simulation fails. Would it be desirable for the exit code to communicate such failure? 

In my use case we are invoking `openstudio`  from a python script and it would be very useful to receive non-zero codes from the child process when the simulation fails.

## Detailed Description
https://github.com/NREL/OpenStudio/blob/1e4f9fda38c9a4917b3a4a196a6c9f80d469502c/src/cli/openstudio_cli.rb#L970-L975

## Possible Implementation

Given that the `OpenStudio::Workflow::Run.run` method [returns the `@current_state` ](https://github.com/NREL/OpenStudio-workflow-gem/blob/8a71d6d38d2eabc064a77eb6e3e282b61c89fe21/lib/openstudio/workflow/run.rb#L228-L283), maybe the return code could depend on whether `@current_state == :errored` ?

**Comment by tijcolem** [comment]
Hi @spolloni.  This is a great thing to have. Your suggestion of capturing the @current_state and passing it back to the cli for the exit code should work fine. If you happen to have this coded up already we welcome Pull Requests from outside collaborators. If not, then we can triage and get this into our queue.  Let us know.
