### ISSUE TITLE
Provide OS SDK/API support for the EnergyPlus "CoilSystem:IntegratedHeatPump:AirSource" object 

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/OpenStudio#4183]
Enhancement Request
--------------
Provide OS SDK/API support for the EnergyPlus "CoilSystem:IntegratedHeatPump:AirSource" object 

## Detailed Description
User interest in using OpenStudio to evaluate the performance of (both packaged and engineered systems) HVAC/DHW systems that combine ccASHP (cold climate heat pumps) performance with integrated hot water generation (and storage) by users may be relatively low today but has very high rate of change given interest in building de-carbonization and electrificatio.

While OS users do have access to this EnergyPlus object via an EnergyPlus Measure, the requirement to add the EnergyPlus measure at the 'tail end' of a measure based workflow combined with the requirement to provide connections to several other supporting OS objects (heating coil, cooling coil and water heating coil) can make this approach fragile and difficult to generalize, as needed to support for larger scale analysis workflows. 

## Possible Implementation
To the degree possible, a 1:1 mapping of the EnergyPlus object attributes would appear to be sufficient and a lowest effort method for implementation.

**Comment by joseph-robertson** [comment]
FYI, this is already in progress under https://github.com/NREL/OpenStudio/pull/4172.
