### ISSUE TITLE
Performance of Workspace/IdfFile::save is slow compared to deferring to ruby

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#4187]
Enhancement Request
--------------

A chat with @shorowit on https://unmethours.com/question/50707/how-to-export-osm-to-idf-with-the-command-line/ highlighted the fact that doing `workspace.save('test.idf', true)` is quite slower than `File.open("test_open.idf", "w") { |f| f << workspace.to_s }`

@shorowit pointed me to the fact that the workflow gem itself uses the File.open method as a result: 
* osm code: https://github.com/NREL/OpenStudio-workflow-gem/blob/8a71d6d38d2eabc064a77eb6e3e282b61c89fe21/lib/openstudio/workflow/util/model.rb#L121
* idf code: https://github.com/NREL/OpenStudio-workflow-gem/blob/8a71d6d38d2eabc064a77eb6e3e282b61c89fe21/lib/openstudio/workflow/util/model.rb#L142

Both end up doing almost the same thing, that is first call `Workspace::toIdfFile` then `IdfFile::print`

https://github.com/NREL/OpenStudio/blob/c535aa3b938369a09bd2bb81d2d41228a3d279f7/src/utilities/idf/Workspace.cpp#L1763-L1765

https://github.com/NREL/OpenStudio/blob/c535aa3b938369a09bd2bb81d2d41228a3d279f7/src/utilities/idf/Workspace.cpp#L2779-L2782

## Detailed Description

I started with a small benchmark in ruby, to highlight the fact that the problem is indeed inside IdfFile::save.

```ruby
require 'openstudio'
require 'benchmark'

m = OpenStudio::Model::exampleModel()
ft = OpenStudio::energyplus::ForwardTranslator.new
w = ft.translateModel(m)
idf_file = w.toIdfFile()

n = 100
Benchmark.bm(7) do |x|
  x.report("save:")   { n.times do   ; w.save('test_save.idf', true); end }
  x.report("File.open:") { n.times do   ; File.open("test_open.idf", "w") { |f| f << w.to_s }; end }
  x.report("IdfFile::save:")   { n.times do   ; idf_file.save('test_idffile_save.idf', true); end }
  x.report("IdfFile File.open:") { n.times do   ; File.open("test_idffile_open.idf", "w") { |f| f << idf_file.to_s }; end }
end
```

|                    | user     | system   | total    | real     |
|--------------------|----------|----------|----------|----------|
| save:              | 1.068392 | 0.292359 | 1.360751 | 1.360749 |
| File.open:         | 0.931708 | 0.003739 | 0.935447 | 0.943765 |
| diff               | 12.79%   | 98.72%   | 31.26%   | 30.64%   |
|                    |          |          |          |          |
| IdfFile::save:     | 0.916088 | 0.274632 | 1.19072  | 1.198582 |
| IdfFile File.open: | 0.779713 | 0.018899 | 0.798612 | 0.806974 |
| diff               | 14.89%   | 93.12%   | 32.93%   | 32.67%   |

As can be seen, the same difference can be seen at Workspace or IdfFile level.

The IdfFile::save function is here: https://github.com/NREL/OpenStudio/blob/c535aa3b938369a09bd2bb81d2d41228a3d279f7/src/utilities/idf/IdfFile.cpp#L461-L515

I initially thought that the small amount of filesystem checking we do shouldn't pose such an overhead. And it turns out it doesn't. After profiling (with callgrind and perf), I couldn't find any evidence this was the case. The checking / setFileExtension functions take almost zero time.

I am pretty certain that the problem lies within the fact that we use a `boost::filesystem::ofstream` (ofstream in the C++ STL are notoriously slow, but boost may not), but way **more importantly we use `std::endl` everywhere including in `IdfObject.print` which is called for each object**, thus flushing potentially a thousand times or more during the write to the file.

## Possible Implementation

Investigate the endl situation, replace with '\n' if possible;

**Comment by jmarrec** [comment]
Here is a quick bench I created to reproduce the issue:

https://quick-bench.com/q/Z_id-_bM6Js4-bl8_rvfL7gjvOU

Locally, I did another test where I also use boost::filesystem::ofstream instead of std::ofstream. Results are the same.

```
-------------------------------------------------------------
Benchmark                   Time             CPU   Iterations
-------------------------------------------------------------
BM_OutputN             174472 ns       135769 ns         5004
BM_OutputEndl         1213572 ns      1160063 ns          592
BM_BoostOutputN        176619 ns       137023 ns         5121
BM_BoostOutputEndl    1209557 ns      1157464 ns          596
```

![image](https://user-images.githubusercontent.com/5479063/104727292-57a13d00-5735-11eb-9d78-332330d6c566.png)


Full code is here: https://gist.github.com/jmarrec/76ec8dd500d1f20ba2fb1ec1c72f156f

**Comment by DavidGoldwasser** [comment]
Is Issue #347 related to this
