### ISSUE TITLE
Investigate slimming OpenStudio CLI

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4189]
Enhancement Request
--------------
The `openstudio` CLI binary is currently over 200MB. This makes it challenging to package for desktop BEM applications. Are there ways to reduce its size?

For example, if the openstudio-standards gem is a significant contributor, some options are:
A) Don't include it in the CLI
B) Include it next to the CLI (i.e., don't compile it in) and have the CLI load it on demand if found. Then a BEM tool could choose not to include the gem in their installer package.

First step is to determine what components significantly contribute to its file size.

**Comment by jmarrec** [comment]
The embedded gems account for more than 3/4 of the CLI (I don't have hard numbers to back that up, so you'll have to trust me on it).

Then, take a look at the folder size for each of the embedded gems:

![image](https://user-images.githubusercontent.com/5479063/106280184-dcb04a00-623d-11eb-882f-53da58a0120d.png)

**Comment by jmarrec** [comment]
in the extracted openstudio-gems directory, 617.436 MB with standards, 38 MB without. That should give you an idea.

**Comment by jmarrec** [comment]
I'm making a build locally without standards, will report

**Comment by jmarrec** [comment]
I built twice already, but I expected to see more significant differences removing os-standards. I've wiped my build folder and cleaned my ccache just to make sure.

Before: 238M	./openstudio
After   : 193M	./openstudio

The files getting embedded are mostly text, and we are zipping them... text files can compress significantly.

As a test, I just took the openstudio-standards folder  which is 600 MB, zipped it using default ubuntu options, and it came out as 50 MB

**Comment by jmarrec** [comment]
Ok well, even after rebuild, that's the same result.

Before: 238M ./openstudio
After : 193M ./openstudio

**Comment by tijcolem** [comment]
I'm don't think a savings of 19% is worth removing it altogether based solely on size.. There may be other reasons to do so though. 

Thanks for running the numbers @jmarrec

**Comment by kbenne** [comment]
@jmarrec this is great analysis. Can you provide another data point? We make a standalone ruby bindings shared library target, which is similar to the cli but without ruby interpreter, or extensions. It is essentially the core cpp api plus the ruby wrappers. What is the size of that shared lib?

**Comment by jmarrec** [comment]
```
175M	.Products/ruby/openstudio.so
```

**Comment by jmarrec** [comment]
Bottom line: I was wrong. The embedded gems are not that a significant portion of the CLI, and even though 19% is a reduction for sure, I don't think saving 45 MB is worth the hassle/potential problems of distributing it separately.

**Comment by jmarrec** [comment]
@kbenne @tijcolem Close?

**Comment by shorowit** [comment]
> ```shell
> 85M	./Products/libopenstudiolib.so    # C++ lib
> 239M	./Products/openstudio             # CLI
> 175M	./Products/ruby/openstudio.so     # Ruby bindings shared library
> ```

Is this saying that 175M of the 239M CLI binary is simply the ruby bindings?

Interestingly, I see a big difference between my installations on Windows and Linux:

  | CLI binary | openstudio.so
-- | -- | --
Windows | 209M | 71M
Linux | 248M | 181M

**Comment by tijcolem** [comment]
This was good exercise to go through and good for reference when this topic resurfaces. It's surprising to me that the embedded gems didn't save more, but with only 19% savings, I agree it's not worth trying to separate that out. 

I'm going to close this.
