### ISSUE TITLE
"Disposing" of OpenStudio resources correctly, from .NET

### ISSUE THREAD

**Issue by DaveInCaz** [NREL/OpenStudio#4195]
When using OpenStudio from C# / .NET, it looks like most if not all OS classes implement the IDisposable interface. This interface is a standard .NET way to make sure that C# code will correctly free / cleanup any resources which are held by external code. 

("Resources" could be: allocated memory, file handles, etc. Anything that the C# environment won't be able to clean up because it exists outside of the .NET garbage handler.)

I guess I have two related questions...

1. Just for general awareness, what kinds of resources are being used by OpenStudio objects that fall into this category? To put it another way, when you call Dispose() on an OS object, what does generally need to do?

2. Is there any method to check and see what OS resources are still open? One of the difficulties with implementing IDisposable is that if you miss a case it won't be obvious. This might cause a memory leak or something along those lines.  If there was some way to interrogate OpenStudio to see what, if any, resources were still open (when you don't expect there to be any!) that could be a big help to determine if any such problems exist.

Thanks

**Comment by DaveInCaz** [comment]
This post discusses a related / general question about SWIG, but didn't seem to reach a firm conclusion (IMO):
https://stackoverflow.com/questions/44055101/do-i-need-to-dispose-of-swig-generated-objects

**Comment by jmarrec** [comment]
OpenStudio doesn't take handle on files that it doesn't release, and marginally does that (only when running workflows or saving the model), so I don't think you should worry about these things. If you really need to know more, please refer to the SWIG documentation.

Most of what openstudio does is have objects that internally are std::vector<std::string> to save the fields of all objects, and that's pretty much it. 

Does that reassure you a bit? I'd like to close this one as I don't see any actionable items.

**Comment by DaveInCaz** [comment]
I appreciate the clarification that OpenStudio doesn't keep file resources open.

But memory allocations are another concern...

In .NET if you have an object that is IDisposable you are generally "obligated" to manually clean it up; but because of the SWIG layer here I wasn't sure if that was just a standard thing that is added without meaning, or if it really is important.

Can you refer to any SWIG documentation that might be relevant?

Also, I looked in this repository for the SWIG code/configuration files but didn't find them (probably wasn't looking for the right things). Can you point me to that?

Thanks

**Comment by jmarrec** [comment]
Swig interface files are *.i

Swig 4.0 doc: http://www.swig.org/Doc4.0/SWIGDocumentation.html

See chapter 22 which deals specifically wit c#

**Comment by DaveInCaz** [comment]
@jmarrec I was asking where the OpenStudio SWIG configuration is located..?  Surely there must be some files in the repository that are used to setup how it is built? Or if not, does that mean it is a totally default implementation of SWIG C# bindings?

Thanks

**Comment by jmarrec** [comment]
Swig files are *.i

```
(py39)julien@OpenStudio (develop=)$ find . -name "*.i"
./src/model/ModelRefrigeration.i
./src/model/ModelGeometry.i
./src/model/Model.i
./src/model/ModelPlantEquipmentOperationScheme.i
./src/model/ModelZoneHVAC.i
./src/model/ModelStraightComponent.i
./src/model/ModelResources.i
./src/model/ModelSimulation.i
./src/model/Model_Common_Include.i
./src/model/ModelCore.i
./src/model/ModelAvailabilityManager.i
./src/model/ModelGenerators.i
./src/model/ModelHVAC.i
./src/model/ModelAirflow.i
./src/utilities/UtilitiesGeometry.i
./src/utilities/UtilitiesIdf.i
./src/utilities/UtilitiesTime.i
./src/utilities/idf/Idf.i
./src/utilities/idd/Idd.i
./src/utilities/UtilitiesData.i
./src/utilities/sql/SqlFile.i
./src/utilities/filetypes/Filetypes.i
./src/utilities/plot/ProgressBar.i
./src/utilities/UtilitiesCore.i
./src/utilities/geometry/Geometry.i
./src/utilities/units/QuantityConverter.i
./src/utilities/units/Quantity.i
./src/utilities/units/ScaleFactory.i
./src/utilities/units/Scale.i
./src/utilities/units/QuantityRegex.i
./src/utilities/units/QuantityFactory.i
./src/utilities/units/UnitFactory.i
./src/utilities/units/Unit.i
./src/utilities/data/TimeSeries.i
./src/utilities/data/Matrix.i
./src/utilities/data/Attribute.i
./src/utilities/data/Vector.i
./src/utilities/data/CalibrationResult.i
./src/utilities/data/EndUses.i
./src/utilities/data/Variant.i
./src/utilities/data/Data.i
./src/utilities/time/DateTime.i
./src/utilities/time/TimeImpl.i
./src/utilities/time/Time.i
./src/utilities/time/Calendar.i
./src/utilities/time/Date.i
./src/utilities/UtilitiesIdd.i
./src/utilities/UtilitiesBCL.i
./src/utilities/bcl/LocalBCL.i
./src/utilities/UtilitiesPlot.i
./src/utilities/UtilitiesFileTypes.i
./src/utilities/UtilitiesSql.i
./src/utilities/Utilities.i
./src/utilities/UtilitiesUnits.i
./src/utilities/core/v8/LanguageSpecific.i
./src/utilities/core/String.i
./src/utilities/core/python/LanguageSpecific.i
./src/utilities/core/ruby/LanguageSpecific.i
./src/utilities/core/Checksum.i
./src/utilities/core/System.i
./src/utilities/core/Exception.i
./src/utilities/core/Path.i
./src/utilities/core/Logger.i
./src/utilities/core/CommonImport.i
./src/utilities/core/UpdateManager.i
./src/utilities/core/UnzipFile.i
./src/utilities/core/Enum.i
./src/utilities/core/Singleton.i
./src/utilities/core/UUID.i
./src/utilities/core/CommonInclude.i
./src/utilities/core/ZipFile.i
./src/utilities/core/Core.i
./src/utilities/core/csharp/LanguageSpecific.i
./src/utilities/core/java/LanguageSpecific.i
./src/energyplus/EnergyPlus.i
./src/cli/EmbeddedScripting.i
./src/airflow/Airflow.i
./src/measure/Measure.i
./src/gbxml/gbXML.i
./src/osversion/OSVersion.i
./src/sdd/SDD.i
./src/radiance/HeaderInfo.i
./src/radiance/Radiance.i
./src/radiance/AnnualIlluminanceMap.i
./src/isomodel/ISOModel.i
```

Example:
https://github.com/NREL/OpenStudio/blob/develop/src/utilities/idf/Idf.i


<http://www.linkedin.com/in/julienmarrec>

**Comment by jmarrec** [comment]
The formatting got messed up because of email, but you have the list of ".i" files. 


Most of what we do is to extend a few class and define wrappers. But we do something that might be hard to grasp at first in the case of C# specifically: we also do partial class implementations (mostly on the `model/` namespace). It looks a bit weird, but I'll give you an example to help in comprehension: if for eg a class such as GeneratorPhotovoltaics has interactions with PlanarSurface (Surface/SubSurface/ShadingSurface). Because we have such a huge number of classes, we organize the classes in several swig modules. GeneratorsPhotovoltaics is defined in ModelGenerators.i, which is SWIG'ed much later than ModelGeometry.i in which PlanarSurface is defined.

So we initially ignore the surface getter

https://github.com/NREL/OpenStudio/blob/3d83fc2b65af73b597bc7b802aca02dac3680e6a/src/model/ModelGeometry.i#L42-L43

And we reimplement later with partial classes:

https://github.com/NREL/OpenStudio/blob/3d83fc2b65af73b597bc7b802aca02dac3680e6a/src/model/ModelGenerators.i#L146-L195

We do not deal with memory management or whatnot though, that is handled by Swig itself.

**Comment by DaveInCaz** [comment]
@jmarrec  thanks for the pointer to the .i files and the other details. Much appreciated.

I've taken some time to read some SWIG docs and look at the OpenStudio code. It seems like the memory management practices are where I still have some questions.

In the SWIG docs I see 3 situations related to different aspects of memory management:


**1. Memory ownership flag**
http://www.swig.org/Doc4.0/Java.html#Java_memory_management 
(This is actually the Java section, which the docs specifically cite for C#)

Docs state:

> Each proxy class has an ownership flag swigCMemOwn. The value of this flag determines who is responsible for deleting the underlying C++ object. If set to true, the proxy class's finalizer will destroy the C++ object when the proxy class is garbage collected. If set to false, then the destruction of the proxy class has no effect on the C++ object.


In sames of decompiled OpenStudio C# code the flag is `true` in all the examples I've seen. For instance, here's the C# constructor for a `Node` object:
```
        public Node(Model model)
            : this(OpenStudioModelHVACPINVOKE.new_Node(Model.getCPtr(model)), cMemoryOwn: true)
        {
            ...
        }
```

(`cMemoryOwn: true`)

Can we always assume, in every case, that this flag is `true`?  Or are there cases where it might not be? The docs state a few potential situations where that might be:

> when pointers or references are returned to Java [or C#], there is often no way to know where they came from. Therefore, the ownership is set to false.

But I don't know what OpenStudio actually does in those cases.

**2. Returning _references_ to C++ member variables**
http://www.swig.org/Doc4.0/CSharp.html#CSharp_memory_management_member_variables

This section explains a method of configuring SWIG wrapper classes to prevent parent objects from being garbage collected prematurely. From what I can see in the .i files, it doesn't look like OpenStudio is doing this.

For example, if we had C# code that did this:

`var foo = Model.getA.getB.getC;`

what is actually happening is two intermediate wrapper objects `A` and `B` are being created, and a final `C` object returned to C#. 

Could the `A` and `B` objects be collected at any time? Or would they be kept alive as long as a reference to `C` is held?

I guess that would only matter if in the case where `A` and `B` are destroyed and as a result, `C` _is no longer valid_. Maybe that never happens?


**3. Passing C++ objects between C# and C++**
http://www.swig.org/Doc4.0/CSharp.html#CSharp_memory_management_objects

This is similar to the last case, but covers the case where an object is created in C#, passed to C++, but C# thinks it is no longer referenced and garbage collects it, in turn destroying the C++ object which was in fact still referenced.

Could this case occur with OpenStudio objects?

---

Note that I'm not necessarily implying that OpenStudio should be doing something different in any of these cases, but we do need to know how these details work in order to program correctly on the C# side, I think.

Tying this back to the original question about `IDisposable` - the fact that all the C# wrapper objects have this interface is a strong indicator that special care does in fact need to be taken on the C# side for cases 1-3.

**Comment by jmarrec** [comment]
We do not return pointers.
Also, OpenStudio programs are short-lived anyways, so I very much doubt you'll run into problems.

While I can appreciate that you're trying to get to the bottom of the rabbit hole, unless you have a specific feature request or hit an actual bug or memory leak with the C# bindings that produces a crash or hinders performance significantly, I'm afraid there is nothing I can do for you at this point. 

I'd rather focus my time and effort on actually fixing real bugs or improving the software via new features, and I hope you can sympathize with that.

The SWIG mailing list (swig-user) is pretty active with good support from maintainers, and there were actually a couple of discussions in the past couple of weeks alone about similar questions such as IDisposable (eg https://sourceforge.net/p/swig/mailman/swig-user/?viewmonth=202101&viewday=21), so head over there if you really want to: http://www.swig.org/mail.html

**Comment by DaveInCaz** [comment]
@jmarrec  no there's no change or anything I'm requesting - just asking questions to understand how to program against OpenStudio correctly. (i.e., not reporting a bug or something).

I agree this is tricky to understand, but I don't agree that its an SWIG question per se; its a question of how OpenStudio has utilized SWIG. Is there some better forum to ask these questions?

**Comment by jmarrec** [comment]
the objects you are getting are shallow. They are just empty wrappers that forward to a private Implementation class, which is stored in your model. The only thing they store is a pointer to their Impl. And their destructor is empty.

https://github.com/NREL/OpenStudio/blob/207d714338a2386136517b0a83dfb2f3d067bfda/src/utilities/idf/IdfObject.hpp#L109

Only calling .clone(), .remove() would duplicate/remove the **underlying** object (the one that stores the values).

IMHO the best forum to ask more question **is** the swig-user mailing list. Or get a debugger and investigate yourself. 

That is as far I am going to go on this thread.
