### ISSUE TITLE
Cannot set outdoorAirMethod to AirChanges/Hour in DesignSpecificationOutdoorAir

### ISSUE THREAD

**Issue by dnix** [NREL/OpenStudio#4196]
Issue overview
--------------
Cannot explicitly or implicitly set `outdoorAirMethod ` to `AirChanges/Hour` in `DesignSpecificationOutdoorAir`.

## Current Behavior
Unable to set `outdoorAirMethod` to `AirChanges/Hour` by either explicitly by calling `setOutdoorAirMethod` or implicitly/automatically with `setOutdoorAirFlowAirChangesperHour`. On closer inspection, it seems only `Sum` and `Maximum` methods are available.

## Expected Behavior
All `outdoorAirMethod` methods should be exposed and available to be set, either explicitly by `setOutdoorAirMethod` or intelligently upon setting an Outdoor Air Flow value. 

## Steps to Reproduce
```
require 'openstudio'
include OpenStudio::Model

m = Model.new

oa = DesignSpecificationOutdoorAir.new(m)
puts oa

oa.setOutdoorAirFlowAirChangesperHour(4.0)
puts oa

oa.setOutdoorAirMethod('AirChanges/Hour')
puts oa

DesignSpecificationOutdoorAir.outdoorAirMethodValues
```

## Possible Solution
Update docs to indicate that only a subset of calculation methods are available, or update support for all (`Flow/Person`, `Flow/Area`, `Flow/Zone`, `AirChanges/Hour`, `Sum`, `Maximum`). Potentially follow behavior of `SpaceInfiltrationDesignFlowRate` class for setting calculation method automatically. 

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Linux
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.1.0+e165090621

### Context
Setting Outdoor Air Flow any given values with precision (and, e.g., without needing to reset all other Flow values) would be useful, and this would follow the pattern of Infiltration Flow rates in OS. Expected the OS SDK pattern to follow E+ here, and found no docs to indicate otherwise.

Appreciate any help and/or clarity here very much – thanks in advance to all!

**Comment by jmarrec** [comment]
It was a design choice to only provide Sum/Maximum.

```ruby
DesignSpecificationOutdoorAir::validOutdoorAirMethodValues
=> ["Sum", "Maximum"]
```
Sum and Maximum suffice to categorize all potential outcomes. And if we were to set the method to AirCHanges/Hour when calling `setOutdoorAirFlowAirChangesperHour` - and even worst: clearing all other fields - then we couldn't really provide a good experience for users wanting to use "Sum" or "Maximum" could we? So it was a **good decision**.


If you ONLY want to use OutdoorAirFlowAirChangesPerHour, then do reset (or set to zero) all others

```ruby
oa.setOutdoorAirFlowAirChangesperHour(4.0)
oa.resetOutdoorAirFlowRateFractionSchedule()
oa.resetOutdoorAirFlowperPerson()             
oa.resetOutdoorAirFlowRate()
oa.resetOutdoorAirFlowperFloorArea()
```

**Comment by jmarrec** [comment]
@dnix If you're using ruby, it's really to monkey patch if that's really what you want to provide. Here's an example I gave in https://github.com/NREL/OpenStudio/issues/3936. 

Sicne you may not know how to do this, I'm going to provide an example, and you can find another in https://github.com/NREL/OpenStudio/issues/3936

```
module DesignSpecificOutdoorAirExtensions
  def resetAll()
    self.resetOutdoorAirFlowAirChangesperHour()
    self.resetOutdoorAirFlowRateFractionSchedule()
    self.resetOutdoorAirFlowperPerson()
    self.resetOutdoorAirFlowRate()
    self.resetOutdoorAirFlowperFloorArea()
  end

  def setOutdoorAirFlowAirChangesperHour(val)
    resetAll()
    super(val)
  end

  def setOutdoorAirFlowRateFractionSchedule(val)
    resetAll()
    super(val)
  end

  def setOutdoorAirFlowperPerson(val)
    resetAll()
    super(val)
  end

  def setOutdoorAirFlowRate(val)
    resetAll()
    super(val)
  end

  def setOutdoorAirFlowperFloorArea(val)
    resetAll()
    super(val)
  end

end

class OpenStudio::Model::DesignSpecificationOutdoorAir
  prepend DesignSpecificOutdoorAirExtensions
end

m = Model.new

oa = DesignSpecificationOutdoorAir.new(m)
```

```ruby
[9] testfiles(main)> oa.setOutdoorAirFlowRate(0.1837)
=> true
[10] testfiles(main)> puts oa
OS:DesignSpecification:OutdoorAir,
  {22c55684-952e-4da2-8dff-216ad0ecefb4}, !- Handle
  Design Specification Outdoor Air 1,     !- Name
  ,                                       !- Outdoor Air Method
  ,                                       !- Outdoor Air Flow per Person {m3/s-person}
  ,                                       !- Outdoor Air Flow per Floor Area {m3/s-m2}
  0.1837,                                 !- Outdoor Air Flow Rate {m3/s}
  ,                                       !- Outdoor Air Flow Air Changes per Hour {1/hr}
  ;                                       !- Outdoor Air Flow Rate Fraction Schedule Name

=> nil
[11] testfiles(main)> oa.setOutdoorAirFlowAirChangesperHour(4.0)
=> true
[12] testfiles(main)> puts oa
OS:DesignSpecification:OutdoorAir,
  {22c55684-952e-4da2-8dff-216ad0ecefb4}, !- Handle
  Design Specification Outdoor Air 1,     !- Name
  ,                                       !- Outdoor Air Method
  ,                                       !- Outdoor Air Flow per Person {m3/s-person}
  ,                                       !- Outdoor Air Flow per Floor Area {m3/s-m2}
  ,                                       !- Outdoor Air Flow Rate {m3/s}
  4,                                      !- Outdoor Air Flow Air Changes per Hour {1/hr}
  ;                                       !- Outdoor Air Flow Rate Fraction Schedule Name

```

**Comment by dnix** [comment]
Thank you @jmarrec, I very much appreciate the thorough response and explanation
