### ISSUE TITLE
The waterheaterheatpump (pumpedcondenser and wrappedcondenser) system connection order generated by Openstudio is different with the ones from EnergyPlus

### ISSUE THREAD

**Issue by legend053** [NREL/OpenStudio#4197]
Issue overview
--------------

In my simulation case, I built waterheaterheatpump:wrappedcondenser from Openstudio and then exported to idf. After run by EnergyPlus, the water heater heat pump system connection order is different with the ones of energyplus examples. Below are the screenshots from each case.

In EnergyPlus examples, Coil:WaterHeating:AirToWaterHeatPump:Wrapped or Coil:WaterHeating:AirToWaterHeatPump:Pumped are before the tank. However, for the systems generated from Openstudio, the tank is before Coil:WaterHeating:AirToWaterHeatPump:Wrapped/Pumped.

Water Heater Heat Pump System Connection from EnergyPlus
Example 1 from EnergyPlus
![image](https://user-images.githubusercontent.com/7464388/106237286-180e3280-61c4-11eb-9985-0b9078ff8a47.png)

Example 2 from EnergyPlus
![image](https://user-images.githubusercontent.com/7464388/106237307-23615e00-61c4-11eb-9c60-91c01f60bf80.png)

My case
![image](https://user-images.githubusercontent.com/7464388/106237320-2bb99900-61c4-11eb-8981-714fc7ac0180.png)

Another one generated by Openstudio SDK
![image](https://user-images.githubusercontent.com/7464388/106237331-37a55b00-61c4-11eb-9880-395fdc357922.png)

Will it affect the simulation results and how to change the order?

Thank you

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 10
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.1

**Comment by jmarrec** [comment]
This is a fictious loop you're seeing in the Diafram. There is no branch order. There is no pump.

The WrapperCondenser object and Tank are setup exactly in the same way in the ForwardTranslated IDF from OSM as in the E+ example files

The `WaterHeater:HeatPump:WrappedCondenser` refers to  the `Tank Use Side Inlet Node Name` / `Tank Use Side Outlet Node Name`, and the tank's Use Side Inlet/Outlet nodes are correctly set accordingly. That's pretty much it. Whether the diagram shows them in order or another doesn't matter, it's a "circle" with only two points.
