### ISSUE TITLE
Bintray is sunsetting in May 2021, figure out alternative path forward to host our conan packages

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#4201]
Issue overview
--------------

Bintray is sunsetting in May 2021, figure out alternative path forward to host our conan packages

> Thank you for supporting JFrog through your use of Bintray. We are and continue to be a community-focused company, and in the spirit of transparency we’re giving you advance notice that as of May 2021, we will be sunsetting Bintray.

Source: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

## Possible Solution

* https://jfrog.com/open-source/#artifactory2
* https://docs.conan.io/en/latest/uploading_packages/running_your_server.html

Seems like they recommend Artifactory on the conan server docs

> Artifactory Community Edition (CE) for C/C++ is the recommended server for development and hosting private packages for a team or company. It is completely free, and it features a WebUI, advanced authentication and permissions, great performance and scalability, a REST API, a generic CLI tool and generic repositories to host any kind of source or binary artifact.

https://conan.io/downloads.html

**Comment by tijcolem** [comment]
We'll need to get the help of ITS NREL as this will require a self-hosted option with public access.

**Comment by alancarson** [comment]
At the risk of upsetting the apple cart... cloudsmith.com is the best equivalent to Bintray on the market. Cloudsmith is a fully managed service with a Package Delivery Network covering 23 formats including Conan. Worth considering.

Full disclosure; I work there. Happy to help if we can.

**Comment by tijcolem** [comment]
We have a plan to move forward with an internal solution for this.

**Comment by tijcolem** [comment]
Still moving forward with plans to host Jfrog CE internally.  Waiting on approvals before opening up externally.
