### ISSUE TITLE
Space area/floor missing in floor js json to osm import

### ISSUE THREAD

**Issue by antonszilasi** [NREL/OpenStudio#4203]
Issue overview
--------------

I am occasionally seeing a space without an area/floor when importing a floor js json into the osm

![image](https://user-images.githubusercontent.com/8773483/107588616-5131a400-6bc1-11eb-961a-f031347fc6fa.png)

When the space in the floor js json is totally fine

![image](https://user-images.githubusercontent.com/8773483/107590276-fc902800-6bc4-11eb-9767-3caeb68f5f86.png)

I have a script which checks area in the floor js json vs the area in the actual OpenStudio model and I can confirm that they dont match.

please find the floor js json and its resulting osm in the google drive links here:

json:
https://drive.google.com/file/d/1zP3kdnXn1PYlAzkBwdnibYutRyTgsxII/view?usp=sharing
osm:
https://drive.google.com/file/d/1zP3kdnXn1PYlAzkBwdnibYutRyTgsxII/view?usp=sharing

### Environment

OpenStudio 3.0.1

**Comment by ggartside** [comment]
@antonszilasi Hi I'm looking at this issue to see if it has been resolved and I'm having an issue getting the test file from your google drive. If you still have it can you email it to me at gerard.gartside at d-alchemy.com.

**Comment by ggartside** [comment]
Now verified there are no missing floor surfaces
