### ISSUE TITLE
In-correct ground adjacency/boundary for floor js json import

### ISSUE THREAD

**Issue by antonszilasi** [NREL/OpenStudio#4204]
Occasionally I am seeing floors which are not on the ground floor with ground contact adjacencies.

An example can be seen here:

![image](https://user-images.githubusercontent.com/8773483/107591698-6cec7880-6bc8-11eb-9627-c3a275025463.png)

Given that it is on the 2nd story this floor should have a surface adjacency

Find the floor js json here: https://drive.google.com/file/d/1zP3kdnXn1PYlAzkBwdnibYutRyTgsxII/view?usp=sharing

and resulting osm here: https://drive.google.com/file/d/1zP3kdnXn1PYlAzkBwdnibYutRyTgsxII/view?usp=sharing

### Environment

OpenStudio-3.0.1

**Comment by ggartside** [comment]
@antonszilasi Hi I'm looking at this issue to see if it has been resolved and I'm having an issue getting the test file from your google drive. If you still have it can you email it to me at gerard.gartside at d-alchemy.com. I will also request permission to get it from your google drive. Thanks
