### ISSUE TITLE
Initial area of other Surface X does not equal post intersection area, Face difference is self intersecting

### ISSUE THREAD

**Issue by antonszilasi** [NREL/OpenStudio#4209]
I am frequently seeing these warnings upon floor js json import into OpenStudio:

_1. [openstudio.model.Surface] <1> Initial area of other surface 'Face 266' 1392.56 does not equal post intersection area 1392.56_

_2. Face difference is self intersecting, result will not include this polygon, [[89.0016, 96.3168, 0], [89.0016, 93.8784, 0], [54.864, 93.8784, 0], [54.864, 0, 0], [49.9872, 0, 0], [49.9872, 34.2089, 0], [21.9456, 34.2089, 0], [21.9456, 21.336, 0], [18.7241, 21.336, 0], [18.7245, 0, 0], [18.7239, 34.2077, 0], [0, 34.2077, 0], [0, 39.0083, 0], [18.7025, 39.0083, 0], [18.7027, 55.4736, 0], [21.9456, 55.4736, 0], [21.9456, 39.0144, 0], [49.9872, 39.0144, 0], [49.9872, 93.8784, 0], [22.3327, 93.8784, 0], [22.3327, 76.8096, 0], [18.288, 76.8096, 0], [18.288, 93.8784, 0], [0, 93.8784, 0], [0, 96.3168, 0]]_

As far as I can tell it doesnt result in geometry problems but none the less the warning is concerning.

I have attached a floor js json with a google drive link which produces the warnings above when imported.

https://drive.google.com/file/d/1M_DQoJIolfbJzXCQ_RSzafV5pUZDc6xw/view?usp=sharing

### Environment

OpenStudio 3.0.1

**Comment by jmarrec** [comment]
@antonszilasi how do you import it?

Can't reproduce with 3.1.0

```
json = 'issue_4209.json'
floorplan = OpenStudio::FloorplanJS.load(json)
scene = floorplan.get.toThreeScene(true)
rt = OpenStudio::Model::ThreeJSReverseTranslator.new
m = rt.modelFromThreeJS(scene).get
=> #<OpenStudio::Model::Model:0x0000563fda437568 @__swigtype__="_p_openstudio__model__Model">
```

**Comment by antonszilasi** [comment]
@jmarrec I opened this issue before we upgraded to 3.1.0, I've tried with 3.1.0 and I cant reproduce these warnings perhaps we should close this issue?

**Comment by jmarrec** [comment]
Thanks for the reply. Agreed, let's close
