### ISSUE TITLE
Surface Search for non-convex shading surfaces is failing on user model

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#421]
It gets through one surface and then hits the ruby error below.
The user file is under this issue number in my network directory "Y:\5500\5500 HPBldg\davidg"

Error: #<NoMethodError: undefined method `visible=' for #<Sketchup::ShadowInfo:0x1494c744>>
C:/Program Files (x86)/OpenStudio 1.0.0/Ruby/openstudio/sketchup_plugin/lib/dialogs/SurfaceSearchDialog.rb:604:in `search'
C:/Program Files (x86)/OpenStudio 1.0.0/Ruby/openstudio/sketchup_plugin/lib/dialogs/SurfaceSearchDialog.rb:516:in`each_index'
C:/Program Files (x86)/OpenStudio 1.0.0/Ruby/openstudio/sketchup_plugin/lib/dialogs/SurfaceSearchDialog.rb:516:in `search'
C:/Program Files (x86)/OpenStudio 1.0.0/Ruby/openstudio/sketchup_plugin/lib/dialogs/SurfaceSearchDialog.rb:415:in`on_search_model'
C:/Program Files (x86)/OpenStudio 1.0.0/Ruby/openstudio/sketchup_plugin/lib/dialogs/SurfaceSearchDialog.rb:60:in `add_callbacks'
C:/Program Files (x86)/OpenStudio 1.0.0/Ruby/openstudio/sketchup_plugin/lib/dialogs/SurfaceSearchDialog.rb:637:in`call'
C:/Program Files (x86)/OpenStudio 1.0.0/Ruby/openstudio/sketchup_plugin/lib/dialogs/SurfaceSearchDialog.rb:637
Error: #<NoMethodError: undefined method `visible=' for #<Sketchup::ShadowInfo:0x1494c744>>
C:/Program Files (x86)/OpenStudio 1.0.0/Ruby/openstudio/sketchup_plugin/lib/dialogs/SurfaceSearchDialog.rb:604:in `search'
C:/Program Files (x86)/OpenStudio 1.0.0/Ruby/openstudio/sketchup_plugin/lib/dialogs/SurfaceSearchDialog.rb:516:in`each_index'
C:/Program Files (x86)/OpenStudio 1.0.0/Ruby/openstudio/sketchup_plugin/lib/dialogs/SurfaceSearchDialog.rb:516:in `search'
C:/Program Files (x86)/OpenStudio 1.0.0/Ruby/openstudio/sketchup_plugin/lib/dialogs/SurfaceSearchDialog.rb:415:in`on_search_model'
C:/Program Files (x86)/OpenStudio 1.0.0/Ruby/openstudio/sketchup_plugin/lib/dialogs/SurfaceSearchDialog.rb:60:in `add_callbacks'
C:/Program Files (x86)/OpenStudio 1.0.0/Ruby/openstudio/sketchup_plugin/lib/dialogs/SurfaceSearchDialog.rb:637:in`call'
C:/Program Files (x86)/OpenStudio 1.0.0/Ruby/openstudio/sketchup_plugin/lib/dialogs/SurfaceSearchDialog.rb:637

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/38
