### ISSUE TITLE
Nuget package regression

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#4216]
There has been an apparent regression in the OpenStudio Nuget package. Builds of the nuget package from the current OpenStudio development code result in the following runtime error in a simple test program. This issue should be investigated prior to 3.2.0 release.

![Screenshot from 2021-02-19 17-02-26](https://user-images.githubusercontent.com/707488/108570757-461ef800-72d4-11eb-8674-6f28095fa95d.png)

**Comment by tijcolem** [comment]
@kbenne  I think we can close. I found out that in Visual Studio when you create a new C# console app, it defaults to use "Any CPU" as the target arch and when trying to use the 3.2.0-alpha nuget package, it fails with that error message in your screen capture.   However, when you explicitly create either x64 or x86 Release targets, it works fine.  

Perhaps we can add some additional docs to inform users on correct way to set this up but I think we can safely close this issue as the current 3.2.0-alpha Nuget supports both x86 and x64.
