### ISSUE TITLE
No roof created for Floor js json import

### ISSUE THREAD

**Issue by antonszilasi** [NREL/OpenStudio#4222]
No roof was created for a space

![image](https://user-images.githubusercontent.com/8773483/108922838-ef2b6280-75f4-11eb-99cb-97274902df18.png)

![image](https://user-images.githubusercontent.com/8773483/108922882-0a966d80-75f5-11eb-9b3f-3116532d760d.png)

floor js json and osm can be found here:

https://drive.google.com/file/d/1rzLtT00NVP7xAp7_CZRN-wVdngWQj_jm/view?usp=sharing

https://drive.google.com/file/d/1tqfaMkVig332StyX_wLtau8WJrDfbiOD/view?usp=sharing

Environment

OpenStudio-3.1.0

**Comment by jmarrec** [comment]
If I import the OSM in the OSapp, I also see this in the console:

```
Critical: Error: unable to set component definition -- couldn't find one with id 77
```

I can't see the resulting geometry in OSApp, either after merging it with a a blank OSM, or opening the OSM you shared. Not sure why, but it's not helping debug it.

**Comment by jmarrec** [comment]
Ok, I see in the OSM that the origin is like (x, y) = (-5000, -2000), by panning (a ton) I found the building...

**Comment by jmarrec** [comment]
I created a Minimum Complete Verifiable Example: [floorplan_mcve.json.txt](https://github.com/NREL/OpenStudio/files/6107467/floorplan_mcve.json.txt)

I basically deleted all spaces that weren't necessary to create the issue, removed all windows, thermal zones, space types. I moved x,y coordinates so it'd be center around zero for ease of debugging too.


![image](https://user-images.githubusercontent.com/5479063/110450065-23a62080-80c3-11eb-9856-5460ef785054.png)

![image](https://user-images.githubusercontent.com/5479063/110450087-2a349800-80c3-11eb-8288-586e281ba427.png)

![image](https://user-images.githubusercontent.com/5479063/110450103-2f91e280-80c3-11eb-9710-4b9f20646faa.png)

**Comment by jmarrec** [comment]
Created a unit test on branch https://github.com/NREL/OpenStudio/tree/4222_floorspace_RoofIntersection

**Comment by antonszilasi** [comment]
@jmarrec sorry for not replying I need to check my github notifications more often do you still need my input here?

To answer your question

1. This floor js json is created with the our own version of the floorspace.js which is a clone of the NREL version with a few special drawing constraints it shouldn't affect how the floor js json is created.

2. The floor js json is imported into OpenStudio using the following code:

```
          floorplan = OpenStudio::FloorplanJS::load(floor_js_json_data)
          if floorplan.empty?
            raise "Cannot load floorplan from '#{floorplan_path}'."
          end

          scene = floorplan.get.toThreeScene(true)

          rt = OpenStudio::Model::ThreeJSReverseTranslator.new

          model = rt.modelFromThreeJS(scene)
          
          if model.empty? then raise "Cannot convert floorplan to model." end

          if !model.is_initialized then raise "floor is not initalized" else @model = model.get end

          # surfaces should be matched at this point, remove collinear vertices which are causing errors in EnergyPlus
          model.getSurfaces.each do |surface|
            surface.setVertices(OpenStudio.removeCollinear(surface.vertices))
          end
```

**Comment by antonszilasi** [comment]
I 

> @antonszilasi Could you clarify the json and osm situation? Which was created from the other? Bottom line: how did you create the json, and how did you create the OSM?

**Comment by antonszilasi** [comment]
> @antonszilasi Could you clarify the json and osm situation? Which was created from the other? Bottom line: how did you create the json, and how did you create the OSM?
> 
> @jmarrec sorry for not replying I need to check my github notifications more often do you still need my input here?
> 
> To answer your question
> 
> 1. This floor js json is created with the our own version of the floorspace.js which is a clone of the NREL version with a few special drawing constraints it shouldn't affect how the floor js json is created.
> 2. The floor js json is imported into OpenStudio using the following code:
> 
> ```
>           floorplan = OpenStudio::FloorplanJS::load(floor_js_json_data)
>           if floorplan.empty?
>             raise "Cannot load floorplan from '#{floorplan_path}'."
>           end
> 
>           scene = floorplan.get.toThreeScene(true)
> 
>           rt = OpenStudio::Model::ThreeJSReverseTranslator.new
> 
>           model = rt.modelFromThreeJS(scene)
>           
>           if model.empty? then raise "Cannot convert floorplan to model." end
> 
>           if !model.is_initialized then raise "floor is not initalized" else @model = model.get end
> 
>           # surfaces should be matched at this point, remove collinear vertices which are causing errors in EnergyPlus
>           model.getSurfaces.each do |surface|
>             surface.setVertices(OpenStudio.removeCollinear(surface.vertices))
>           end
> ```

**Comment by ggartside** [comment]
Verified that this is no longer an issue, there are no missing surfaces after import via ThreeJS and Floorspace Dorect
