### ISSUE TITLE
OS v3.2 UnitarySystem FT regression?

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4247]
Issue overview
--------------
I'm using one of the recent nightly builds (OpenStudio-3.1.1-alpha+6c050c1e03-Ubuntu-18.04) and one of my tests that creates a model with multiple HVAC systems generates EnergyPlus errors (e.g., "Node used as an inlet more than once"). The test worked fine in OS v3.1.

[os31.zip](https://github.com/NREL/OpenStudio/files/6160975/os31.zip)
[os32.zip](https://github.com/NREL/OpenStudio/files/6160976/os32.zip)

The error seems to be caused by the UnitarySystem FT, where A) the E+ 9.5 IDF has handles instead of names for some of the heating coils or heating coil references and B) the same coil handle ends up referenced by two different unitary systems. As far as I can tell, the OSM seems fine. If you diff the two IDFs, you'll see what I mean.

![image](https://user-images.githubusercontent.com/5861765/111566085-2effe880-8762-11eb-89c1-a2a27492375a.png)

**Comment by jmarrec** [comment]
There's a hiccup in the OSM itself... My money is on the name changes PR #4211.

here's a reconstructed diff showing the difference from the osv31.osm and the osv32.osm. As you can see in the osv32.osm (which is at 3.1.1-alpha) you have **two Coil:Heating:Electric with the exact same name**

```
OS:Coil:Heating:Electric,
  {3b7441bd-4535-4613-964e-e2732d44a42f}, !- Handle
  central ac and furnace htg coil,        !- Name
  {6dbf6cb9-1421-4393-aa9d-166009b421fa}, !- Availability Schedule Name
  1,                                      !- Efficiency
  1875.65484910222,                       !- Nominal Capacity {W}
  ,                                       !- Air Inlet Node Name
  ;                                       !- Air Outlet Node Name

OS:Coil:Heating:Electric,
  {e001ae56-d6e1-4af5-b2d1-12f3a4adff0b}, !- Handle
-  central ac and furnace htg coil 1,      !- Name
+  central ac and furnace htg coil,        !- Name
  {6dbf6cb9-1421-4393-aa9d-166009b421fa}, !- Availability Schedule Name
  0.92,                                   !- Efficiency
  1875.65484910222,                       !- Nominal Capacity {W}
  ,                                       !- Air Inlet Node Name
  ;                                       !- Air Outlet Node Name
```


To reproduce, I think I'm going to need your testfile (or better, a MCVE).

**Comment by jmarrec** [comment]
On the other hand, I can't reproduce the same with `Space`.

```
include OpenStudio::Model
m = Model.new
2.times do
  s = Space.new(m)
  s.setName("a space")
end

m.getSpaces.map{|c| c.nameString}
```

----

Using meta programming, I tested a few more, and amongst the list, CoilHeatingElectric is the only one that does not enforce unicity in name.

```
["ThermalZone", "Space", "CoilHeatingElectric", "CoilHeatingWater", "CoilHeatingGas", "CoilCoolingDXVariableSpeed", "CoilCoolingDXSingleSpeed", "CoilHeatingDXVariableSpeed", "CoilHeatingDXSingleSpeed", "CoilHeatingDXMultiSpeed", "CoilHeatingWaterToAirHeatPumpEquationFit"].each do |class_name|
  m = Model.new
  2.times do 
    obj = OpenStudio::Model::const_get(class_name).new(m)
    obj.setName("my object")
  end
  if m.method("get#{class_name}s").call.map{|o| o.nameString}.uniq.size < 2
    puts "#{class_name} does not enforce name unicity"
  end
end
```

**Comment by jmarrec** [comment]
This is the guilty line: https://github.com/NREL/OpenStudio/pull/4211/files#diff-17653f245bc4585ff70eece55b2c878c201d5596bb8883fb7371c85da9a094dbR373

**Comment by jmarrec** [comment]
Here are all types where we should expect a regression like on Coil:Heating:Electric

```ruby

factory = OpenStudio::IddFileAndFactoryWrapper.new("OpenStudio".to_IddFileType)
factory.objects.each do |iddObject|
  index_ = iddObject.nameFieldIndex
  next if index_.empty?
  if !iddObject.isRequiredField(index_.get)
    puts "#{iddObject.name}"
  end
end
```

```
OS:RunPeriod
OS:UtilityCost:Charge:Block
OS:UtilityCost:Charge:Simple
OS:UtilityCost:Computation
OS:UtilityCost:Qualify
OS:UtilityCost:Ratchet
OS:UtilityCost:Variable
OS:AirConditioner:VariableRefrigerantFlow
OS:Coil:Cooling:DX:VariableRefrigerantFlow
OS:Coil:Heating:DX:VariableRefrigerantFlow
OS:Coil:Heating:Electric
OS:Connection
OS:HVACComponentList
OS:SetpointManager:OutdoorAirReset
OS:ZoneHVAC:Baseboard:Convective:Electric
OS:ZoneHVAC:Baseboard:Convective:Water
OS:ZoneHVAC:TerminalUnit:VariableRefrigerantFlow
OS:ElectricLoadCenter:Storage:Simple
OS:ElectricLoadCenter:Storage:Converter
OS:Output:Meter
```

**Comment by jmarrec** [comment]
Ok, to fix it, I see two ways.

1. Modify Output:Meter so we don't have to have a workaround in WorkspaceObject::setName https://github.com/NREL/OpenStudio/blob/6c050c1e038fdec4382042d438804029ed2c48d4/src/utilities/idf/WorkspaceObject.cpp#L373
   * Plus: we avoid two extra checks just for this object, in a location that is likely going to be called very often (so _potential_ performance impact)
   * Cons: we need to change the OutputMeter IDD object and make sure API works (this object is already a weird one)

2. Add `\required-field` to all IDD objects where we need to enforce name unicity. It should have been there honestly to begin with
   * Plus: quick fix
   * Cons: We're likely to run into problems later unless we start enforcing it via a script that is run on all PRs (but do we want to maintain that and use resources to run that stuff?)

----

**Voting:**

* Please Use :+1: : to use solution 1
* Please Use :rocket: to use solution 2

**Comment by jmarrec** [comment]
There is no noticable performance hit by adding the two checks on https://github.com/NREL/OpenStudio/blob/6c050c1e038fdec4382042d438804029ed2c48d4/src/utilities/idf/WorkspaceObject.cpp#L373, I tested via a microbenchmark

![image](https://user-images.githubusercontent.com/5479063/111649560-c4ec4f80-8804-11eb-80dc-f632c20ccaeb.png)

**Comment by kbenne** [comment]
Thumbs up (option 1 for now). 

rocket ship would be ok post release.
