### ISSUE TITLE
Performance degradation when loading measure in 3.1.1 alpha

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#4249]
Issue overview
--------------

@shorowit tested the 3.1.1-alpha nightly, and noticed a serious slowdown in running a single measure (OpenStudio-HPXML)
 > OS measure is taking almost 4x longer: 1.2 seconds in 3.1.1 versus 4.5 seconds in 3.1.1-alpha.

> The biggest bottleneck I've noticed so far is here...
> v3.1:
> [07:50:03.052143 DEBUG] Loading Measure from /mnt/c/git/openstudio-hpxml/HPXMLtoOpenStudio/measure.rb
> [07:50:03.203673 DEBUG] Iterating over arguments for workflow item 'HPXMLtoOpenStudio'
> v3.2:
> [07:51:19.140217 DEBUG] Loading Measure from /mnt/c/git/openstudio-hpxml/HPXMLtoOpenStudio/measure.rb
> [07:51:21.737514 DEBUG] Iterating over arguments for workflow item 'HPXMLtoOpenStudio'

The workflow gem code in between is here: https://github.com/NREL/OpenStudio-workflow-gem/blob/3f0649059de3c3e95002641464985a7edb80cc7a/lib/openstudio/workflow/util/measure.rb#L339-L388

**Bottle neck appears to be the `load measure.to_s`**

### Benchmarking

I isolated the behavior inside a small benchmarking code.

```ruby
# For running with ruby 2.5.5
# require '/usr/local/openstudio-3.1.0/Ruby/openstudio.rb'
# For running with ruby 2.7.2
# require '/home/julien/Software/Others/OS-build-release/Products/ruby/openstudio.rb'
# For running with CLI: no-op

measure_path = './measure.rb'
class_name = 'CurveVisualizationApplyNow' # Modify to actual class name

model = OpenStudio::Model::exampleModel

ori_t = Time.now
load measure_path.to_s
load_t = Time.now - ori_t
puts "Loading measure time: #{load_t}"

measure_object_t = Time.now
measure_object = Object.const_get(class_name).new
measure_object_t = Time.now - measure_object_t
puts "Instantiate measure_object time: #{measure_object_t}"

clone_model_t = Time.now
clone_model = model.clone(true).to_Model
arguments = measure_object.arguments(clone_model)
clone_model_t = Time.now - clone_model_t
puts "Cloning model time: #{clone_model_t}"

iterate_argument_map_t = Time.now
argument_map = OpenStudio::Ruleset::OSArgumentMap.new
if arguments
  arguments.each do |v|
    argument_map[v.name] = v.clone
  end
end
iterate_argument_map_t = Time.now - iterate_argument_map_t
puts "Iterating over argument map time: #{iterate_argument_map_t}"
```

### Results

**With my specific measure, using the CLI:**

```
(py39)julien@curve_visualization_apply_now (master *%=)$ openstudio benchcode.rb 
Loading measure time: 0.003526157
Instantiate measure_object time: 2.084e-06
Cloning model time: 0.005812749
Iterating over argument map time: 0.000125448
(py39)julien@curve_visualization_apply_now (master *%=)$ $os_build_rel/Products/openstudio benchcode.rb 
Loading measure time: 0.158742372
Instantiate measure_object time: 4.438e-06
Cloning model time: 0.002678102
Iterating over argument map time: 0.000124235
(py39)julien@curve_visualization_apply_now (master *%=)$ openstudio --version
3.1.0+82d3ea2978
(py39)julien@curve_visualization_apply_now (master *%=)$ $os_build_rel/Products/openstudio --version
3.1.1-alpha+05ebb2b3f3
```

**With HPXMLtoOpenStudio measure, using the CLI**

```
(py39)julien@HPXMLtoOpenStudio (master %=)$ openstudio benchcode.rb 
Loading measure time: 0.169866195
Instantiate measure_object time: 3.286e-06
Cloning model time: 0.0015104
Iterating over argument map time: 0.00014267
(py39)julien@HPXMLtoOpenStudio (master %=)$ $os_build_rel/Products/openstudio benchcode.rb 
Loading measure time: 3.618246304
Instantiate measure_object time: 3.276e-06
Cloning model time: 0.001413977
Iterating over argument map time: 0.00014282
```

**Ruby timings with my measure:**

```
(py39)julien@curve_visualization_apply_now (master *%=)$ head -n1 benchcode_ruby255.rb 
require '/usr/local/openstudio-3.1.0/Ruby/openstudio.rb'
(py39)julien@curve_visualization_apply_now (master *%=)$ head -n1 benchcode_ruby272.rb 
require '/home/julien/Software/Others/OS-build-release/Products/ruby/openstudio.rb'
(py39)julien@curve_visualization_apply_now (master *%=)$ rvm use 2.5.5
Using /home/julien/.rvm/gems/ruby-2.5.5
r(py39)julien@curve_visualization_apply_now (master *%=)$ ruby benchcode_ruby255.rb 
Loading measure time: 0.009601101
Instantiate measure_object time: 2.534e-06
Cloning model time: 0.001855926
[OpenStudio.Measure] <0> OSArgumentMap is deprecated, use OpenStudio::Measure::OSArgumentMap instead.
Iterating over argument map time: 0.000194889
(py39)julien@curve_visualization_apply_now (master *%=)$ rvm use 2.7.2
Using /home/julien/.rvm/gems/ruby-2.7.2
(py39)julien@curve_visualization_apply_now (master *%=)$ ruby benchcode_ruby272.rb 
Loading measure time: 0.008933847
Instantiate measure_object time: 2.705e-06
Cloning model time: 0.001800973
[OpenStudio.Measure] <0> OSArgumentMap is deprecated, use OpenStudio::Measure::OSArgumentMap instead.
Iterating over argument map time: 0.000183057
```

**Bottle neck appears to be the `load measure.to_s`**

## Loading measure timings

| OS / Ruby     | CLI         | Ruby        |
|---------------|-------------|-------------|
| 3.1.0 / 2.5.5 | 0.169866195 | 0.009601101 |
| 3.1.1 / 2.7.2 | 3.618246304 | 0.008933847 |

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

**Comment by jmarrec** [comment]
I copied my `measure.rb` to `measure_fake.rb` and changed the class Name to `CurveVisualizationApplyNowFake`


Modified the top of the script to first load that measure, so I could rule out lazy load. Timings are way different:

```ruby
measure_path = './measure.rb'
class_name = 'CurveVisualizationApplyNow' # Modify to actual class name

model = OpenStudio::Model::exampleModel

# Rule out lazy load by loading a fake measure (same as measure.rb, class
# renamed)
load './measure_fake.rb'


ori_t = Time.now
load measure_path.to_s
load_t = Time.now - ori_t
puts "Loading measure time: #{load_t}"
[...]
```

| OS / Ruby     | CLI         | Ruby        | CLI, loading a duplicated measure first |
|---------------|-------------|-------------|-----------------------------------------|
| 3.1.0 / 2.5.5 | 0.169866195 | 0.009601101 | 0.000529101                             |
| 3.1.1 / 2.7.2 | 3.618246304 | 0.008933847 | 0.019157605                             |

**Comment by shorowit** [comment]
Briefly looked through ruby performance-related issues... is it possible the regression is related to this? https://bugs.ruby-lang.org/issues/15856

**Comment by shorowit** [comment]
Re-opening this in case more can be done. I'm seeing that OS v3.2 (w/ above performance improvement) is still roughly 30% slower than OS v3.1 for our typical workflow. Nearly all of the slow down is still when loading the measure ([as observed by @jmarrec](https://github.com/NREL/OpenStudio/pull/4261#pullrequestreview-620900666)).

**Comment by jmarrec** [comment]
I have tried more than a few things, each leading to worse performance than current. I've tried mapping fileNames directly in swig creating a ruby array (instead of passing a long `;` string and splitting). I've tried using `constexpr std::array`. I've even tried harcoding the fileNames directly in embedded_help.rb. This isn't helping.

Here's running the benchcode.rb 50 times:

![image](https://user-images.githubusercontent.com/5479063/113764217-f4fb8400-971a-11eb-806e-5ccf7fc25aad.png)

My work is on https://github.com/jmarrec/OpenStudio/tree/4249_perf_cli_try1 and https://github.com/jmarrec/OpenStudio/tree/4249_perf_cli_try2.

I'm ready to throw the towel on this one @tijcolem @shorowit

**Comment by shorowit** [comment]
Is it possible the issue is better w/ ruby v3? Or is there a reason we need to stick with ruby 2.7?

**Comment by shorowit** [comment]
For what it's worth, here's a really simple test that demonstrates the issue:

OpenStudio 3.1:
```
shorowit@SHOROWIT-36132S:~$ time openstudio -e "require 'oga'"

real    0m0.353s
user    0m0.234s
sys     0m0.094s
```

OpenStudio 3.2:
```
shorowit@SHOROWIT-36132S:~$ time OpenStudio-3.2.0-alpha+a007b7801e-Ubuntu-18.04/usr/local/openstudio-3.2.0-alpha/bin/
openstudio -e "require 'oga'"

real    0m0.615s
user    0m0.531s
sys     0m0.078s
```

**Comment by shorowit** [comment]
Using ruby 2.5.1p57 directly:
```
shorowit@SHOROWIT-36132S:~$ time ruby -e "require 'oga'"

real    0m0.163s
user    0m0.047s
sys     0m0.109s
```

Using ruby 2.7.0p0 directly:
```
shorowit@SHOROWIT-36132S:~$ time ruby -e "require 'oga'"

real    0m0.184s
user    0m0.094s
sys     0m0.078s
```

That seems to suggest it's something specific to OpenStudio...
