### ISSUE TITLE
Dual operation type for two-speed evaporative fluid coolers in component setpoint based plant equipment operation

### ISSUE THREAD

**Issue by lymereJ** [NREL/OpenStudio#4254]
Issue overview
--------------
The forward translator appears to use a `Dual` operation type when two-speed evaporative fluid coolers are used in comp onement setpoint based plant equipment operation. I would except the forward translator to use a `Cooling` operation type for this type of equipment.

## Current Behavior

This code (1) ...
```
model = OpenStudio::Model::Model.new()
heat_pump_water_loop = OpenStudio::Model::PlantLoop.new(model)
cooling_equipment = OpenStudio::Model::EvaporativeFluidCoolerTwoSpeed.new(model)
heat_pump_water_loop.addSupplyBranchForComponent(cooling_equipment)
cooling_equipment_stpt_manager = OpenStudio::Model::SetpointManagerScheduledDualSetpoint.new(model)
cooling_equipment_stpt_manager.addToNode(cooling_equipment.outletModelObject.get.to_Node.get)
translator = OpenStudio::OSVersion::VersionTranslator.new
trans = OpenStudio::EnergyPlus::ForwardTranslator.new
idf = trans.translateModel(model)
idf.save('./evap_test.idf', true)
```
... Generates the following IDF object:
```
PlantEquipmentOperation:ComponentSetpoint,
  Plant Loop 1 Setpoint Operation Scheme, !- Name
  EvaporativeFluidCooler:TwoSpeed,        !- Equipment Object Type 1
  Evaporative Fluid Cooler Two Speed 1,   !- Equipment Name 1
  Node 3,                                 !- Demand Calculation Node Name 1
  Node 7,                                 !- Setpoint Node Name 1
  Autosize,                               !- Component Flow Rate 1 {m3/s}
  Dual;                                   !- Operation Type 1
```

If we switch `cooling_equipment = OpenStudio::Model::EvaporativeFluidCoolerTwoSpeed.new(model)` to `cooling_equipment = OpenStudio::Model::EvaporativeFluidCoolerSingleSpeed.new(model)`, the code generates the following IDF object which uses the expected operation type for an evaporative cooler.

```
PlantEquipmentOperation:ComponentSetpoint,
  Plant Loop 1 Setpoint Operation Scheme, !- Name
  EvaporativeFluidCooler:SingleSpeed,     !- Equipment Object Type 1
  Evaporative Fluid Cooler Single Speed 1, !- Equipment Name 1
  Node 3,                                 !- Demand Calculation Node Name 1
  Node 7,                                 !- Setpoint Node Name 1
  Autosize,                               !- Component Flow Rate 1 {m3/s}
  Cooling;                                !- Operation Type 1
```

## Expected Behavior
I would expect (1) to generate the following IDF object:

```
PlantEquipmentOperation:ComponentSetpoint,
  Plant Loop 1 Setpoint Operation Scheme, !- Name
  EvaporativeFluidCooler:SingleSpeed,     !- Equipment Object Type 1
  Evaporative Fluid Cooler Single Speed 1, !- Equipment Name 1
  Node 3,                                 !- Demand Calculation Node Name 1
  Node 7,                                 !- Setpoint Node Name 1
  Autosize,                               !- Component Flow Rate 1 {m3/s}
  Cooling;                                !- Operation Type 1
```

## Possible Solution
A __very__ quick review of the code showed that the component type of single-speed evaporative coolers is defined [here](https://github.com/NREL/OpenStudio/blob/3914af3661bad89275053db21f716478260a0e5e/src/energyplus/ForwardTranslator/ForwardTranslatePlantEquipmentOperationSchemes.cpp#L497-L499) but the component type for two-speed evaporative coolesr isn't. It looks like `Dual` is used when type is not defined as `COOLING` or `HEATING`, see [here](https://github.com/NREL/OpenStudio/blob/4f76ff4f08daa3da3e03ca4c1b1206eabd5e980e/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslatePlantLoop.cpp#L1496). I'm not sure if this is the reason (not too familiar with this code base) and I'm not currently equipped to test any modifications.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform: Windows 10
 - Version of OpenStudio: 3.0.1

### Context
Use of two-speed evaporative coolers in the openstudio-standards gem.

**Comment by jmarrec** [comment]
Thanks for the report @lymereJ and yes, you correctly identified the issue: it wasn't added, so it defaults to `ComponentType::BOTH`. It's been the case for at least 5 years too.
