### ISSUE TITLE
space load objects only allow fractional schedules

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#4260]
Issue overview
--------------
EnergyPlus allows non-fractional schedules for Lights and ElectricEquipment objects (and maybe others) using total power, but OpenStudio does not. 

For example, I want to have Lights object with power = 1 W and apply a ScheduleFile of power measurements to it, but OpenStudio does not set the schedule because the ScheduleFile has a non-fractional ScheduleTypeLimits and EnergyPlus fails due to a missing schedule. The reverse, power = peak power with schedule of fractional power, runs fine. In the former case, setting the schedule in the IDF runs fine without errors or warnings.

```
test = false

require 'openstudio'
include OpenStudio::Model

m = Model.new

stl = ScheduleTypeLimits.new(m)
if test
  stl.setLowerLimitValue(0)
  stl.setUpperLimitValue(1)
end

sr = ScheduleRuleset.new(m)
sr.setScheduleTypeLimits(stl)

ld = LightsDefinition.new(m)
ld.setLightingLevel(1)

l = Lights.new(ld)
l.setSchedule(sr)

puts l
```

## Current Behavior
Set `test = false` above.

```
OS:Lights,
  {aa30d18c-5c71-4336-83cf-5bdbefab6f22}, !- Handle
  Lights 1,                               !- Name
  {58ea5d10-b57d-4316-bad4-ad1cdbd77491}, !- Lights Definition Name
  ,                                       !- Space or SpaceType Name
  ,                                       !- Schedule Name
  1,                                      !- Fraction Replaceable
  ,                                       !- Multiplier
  General;                                !- End-Use Subcategory
```

## Expected Behavior

Set `test = true` above.

```
OS:Lights,
  {02547a43-215c-4114-a5d1-531727fabb9a}, !- Handle
  Lights 1,                               !- Name
  {4de8a137-9dc8-48f6-b80a-404d0f1729cf}, !- Lights Definition Name
  ,                                       !- Space or SpaceType Name
  {b2542f69-155a-4262-ab19-587eea1b98c2}, !- Schedule Name
  1,                                      !- Fraction Replaceable
  ,                                       !- Multiplier
  General;                                !- End-Use Subcategory
```

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.1.0

**Comment by jmarrec** [comment]
@MatthewSteen it was a design decision to enforce ScheduleTypeLimits to avoid user error. I don't think we really want to go back on that, at least I don't.

You obviously have a couple of options:
* Scale your measurements
```ruby
measurements = [1.3, 3.2, 5.1, 10.0, 3.0, 4.0]
design_level = measurements.max
scaled_measurements = measurements.map{|x| x / design_level}
```

* use setPointer directly to bypass the check
```ruby
[19] model(main)> l.setPointer(4, sr.handle)
=> true
[20] model(main)> puts l
OS:Lights,
  {eafff55e-21da-456c-aadf-91e87a94621b}, !- Handle
  Lights 1,                               !- Name
  {58ef2495-25e3-4dfd-a081-5af96238f6eb}, !- Lights Definition Name
  ,                                       !- Space or SpaceType Name
  {ac7df382-1c65-4f23-abb2-63be10339d2c}, !- Schedule Name
  1,                                      !- Fraction Replaceable
  ,                                       !- Multiplier
  General;                                !- End-Use Subcategory
```

**Comment by jmarrec** [comment]
Ok, since I do not like to just say "NO, WON'T FIX" angrily, I can propose a third solution, which is to:
* Add the ability to turn off ScheduleTypeLimits checking altogether - currently I set it to be **as long as you have a ScheduleTypeLimits assigned, otherwise it will still pick and assign one** - , via a new method`ScheduleTypeRegistry::setEnforceScheduleTypeLimits(bool)`
* Swig the ScheduleTypeRegistry properly so you can actually set this value from ruby.

I implemented it quickly, see

```ruby
[1] OS-build-release(main)> include OpenStudio::Model
=> Object
[2] OS-build-release(main)> OpenStudio::Logger.instance.standardOutLogger.setLogLevel(OpenStudio::Info)
=> nil
[3] OS-build-release(main)> m = Model.new
=> #<OpenStudio::Model::Model:0x000055f040782248 @__swigtype__="_p_openstudio__model__Model">
[4] OS-build-release(main)> stl = ScheduleTypeLimits.new(m); sr = ScheduleRuleset.new(m); sr.setScheduleTypeLimits(stl)
=> true
[5] OS-build-release(main)> ld = LightsDefinition.new(m); ld.setLightingLevel(1); l = Lights.new(ld)
=> #<OpenStudio::Model::Lights:0x000055f0405a38c8 @__swigtype__="_p_openstudio__model__Lights">
[6] OS-build-release(main)> l.setSchedule(sr)
[openstudio.model.ModelObject] <0> For Object of type 'OS:Lights' and named 'Lights 1' cannot set Schedule Lighting=Schedule Ruleset 1 because it has an incompatible ScheduleTypeLimits
=> false

# As you can see, by default it enforces
[7] OS-build-release(main)> OpenStudio::Model::ScheduleTypeRegistry::instance.enforceScheduleTypeLimits
=> true

# Turn it off
[8] OS-build-release(main)> OpenStudio::Model::ScheduleTypeRegistry::instance.setEnforceScheduleTypeLimits(false)
=> true
[9] OS-build-release(main)> OpenStudio::Model::ScheduleTypeRegistry::instance.enforceScheduleTypeLimits
=> false
# Try again, this time it works
[10] OS-build-release(main)> l.setSchedule(sr)
=> true
[11] OS-build-release(main)> puts l
OS:Lights,
  {5a368c63-5356-4fef-add9-0767ae4bdcfb}, !- Handle
  Lights 1,                               !- Name
  {7d3dbef6-c11e-49a9-bae5-6e7261ae6699}, !- Lights Definition Name
  ,                                       !- Space or SpaceType Name
  {0171d3df-f177-4ed2-8a03-1723203db8d9}, !- Schedule Name
  1,                                      !- Fraction Replaceable
  ,                                       !- Multiplier
  General;                                !- End-Use Subcategory
```

Would that solution work better for you Matt?

**Comment by MatthewSteen** [comment]
@jmarrec thanks. Regarding your options...

1. Won't work for my case because we'd like to export the loads (could be post processed, but adds work).
2. `setPointer` method works for my case 🎉 
3. Probably a less hacky way than (2). Note that I'm not suggesting turning off ScheduleTypeLimits enforcement, just that objects like Lights and ElectricEquipment can have combinations of `Design Level Calculation Method` and a Schedule/ScheduleTypeLimits that align with EnergyPlus' enforcement (e.g. Design Level = W and schedule =W), which I understand is less strict/user friendly than OpenStudio.

**Comment by jmarrec** [comment]
Closing this one, setPointer needs to be used. I tried to implement something in #4260 but it has undefined behavior on windows.

See https://github.com/NREL/OpenStudio/pull/4270#issuecomment-812514366
