### ISSUE TITLE
Deleting Reheat in VAV with Reheat HVAC system gives Zone Sizing error

### ISSUE THREAD

**Issue by rwadhwa910** [NREL/OpenStudio#4263]
When I Select Packaged VAV with Reheat and When I delete the Reheat Terminal It gives me the error.

   ** Severe  ** ManageSizing: Requested System Sizing but did not request Zone Sizing.
   **   ~~~   ** System Sizing cannot be done without Zone Sizing

Now if the system cannot run without reheat It should not have the option to delete the Reheat Terminal at first place or it should give a flag that it cannot be delete. The other thing I think it will be useful if you can introduce the same system without Reheat.

OS 3.1.0
Windows10
![Capture](https://user-images.githubusercontent.com/63880759/112522665-e781e980-8d6b-11eb-8dab-7c086536e31a.PNG)

**Comment by jmarrec** [comment]
I would like to ask that in the future you please try to use the issue template that appears when you open the issue, it's there to try and make sure you provide enough information for us to reproduce the issue.

If you deleted the VAV reheat terminal and did not include ANY other terminal in place, that might explain the issue. You can put an AirTerminal:SingleDuct:VAV:NoReheat in its palce, making sure to connect at least one thermal zone as well.

The other thing is that you need to have Design Days in your model or the zone sizing object isn't translated.

In any case, this type of question that isn't a confirmed bug is probably best suited for unmethours.com. 

I'm going to close the issue, but if you can produce more info to reproduce a bug, I'll reopen promptly.
