### ISSUE TITLE
Remove long deprecated methods interiorVisibleAbsorbtance and exteriorVisibleAbsorbtance

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#4279]
Issue overview
--------------

Two of these were supposed to be deprecated in 1.4.0 (release date: July 9, 2014...). They are probably an original typo sor**b**tance v sor**p**tance. Keeping it around hurts the API since the right spelling is so close
 
https://github.com/NREL/OpenStudio/blob/eadff9598068b16479b1f5a223ee0611458d2fc6/src/model/ConstructionBase.hpp#L126-L141

Same in model/PlanarSurface.hpp

This is the commit from 7 years ago that deprecated them (in 1.13.0) https://github.com/NREL/OpenStudio/commit/bd9c9d6103b16789ee8c529ac8d2a6e0b23e3a28

An actual Warning has been issued for 6+ years, so I think it's fair to remove them: https://github.com/NREL/OpenStudio/blob/eadff9598068b16479b1f5a223ee0611458d2fc6/src/model/ConstructionBase.cpp#L304-L307

**Comment by macumber** [comment]
Well at this point you should deprecate the warning message, someone might have code that depends on that warning message!


(just kidding.... kill it dead :-) )

**Comment by jmarrec** [comment]
Haha, I think you're taking Hyrum's Law a bit too far :D
