### ISSUE TITLE
ruby error on cleanup origin on some models

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#428]
I have added a single space model to the network that triggers this error. you need to select the space to get the error (the script only works on the selection).

Y:\5500\5500 HPBldg\davidg

Running Cleanup Origins
User script Cleanup Origins completed
redraw polygon
redraw polygon
redraw polygon
redraw polygon
redraw polygon
redraw polygon
Error: #<NoMethodError: undefined method `entities' for #<Sketchup::ShadowInfo:0x137edaac>>
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/SubSurface.rb:344:in `erase_entity'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/PlanarSurface.rb:326:in `update_entity'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/SurfaceGroup.rb:132:in `update_child_entities'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/SurfaceGroup.rb:129:in `each'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/SurfaceGroup.rb:129:in `update_child_entities'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/SurfaceGroup.rb:122:in `update_entity'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/DrawingInterface.rb:154:in `draw_entity'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/DrawingInterface.rb:363:in `on_change_model_object'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/SurfaceGroup.rb:93:in `on_change_model_object'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/watchers/PluginModelObjectWatcher.rb:52:in `call_on_change_model_object'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/watchers/PluginModelObjectWatcher.rb:40:in `onChangeIdfObject'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/PluginManager.rb:214:in `call'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/PluginManager.rb:214:in `process_events'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/PluginManager.rb:207:in `each'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/PluginManager.rb:207:in `process_events'
C:/Users/dgoldwas/Documents/GitHub/OpenStudio/openstudiocore/ruby/openstudio/sketchup_plugin/lib/PluginManager.rb:259:in `start_event_processing'
Surface.face_polygon:  entity not valid

**Comment by macumber** [comment]
Classifying as a crash since I think plugin stops on this error

**Comment by macumber** [comment]
@DavidGoldwasser can we close this as won't fix?

**Comment by DavidGoldwasser** [comment]
I can't find the file. I'll close it but re-open if I see it again. May just be issue with user script code vs. core plugin.
