### ISSUE TITLE
Discrepancy in OpenStudio Licence

### ISSUE THREAD

**Issue by deathwishdave** [NREL/OpenStudio#4286]
There appears to be a discrepancy in OpenSudio licensing, can someone please clarify.

[this](https://www.openstudio.net/) suggests the licence is LGPL.

[this](https://nrel.github.io/OpenStudio-user-documentation/help/software_license/) and [this](https://github.com/NREL/OpenStudio/blob/master/LICENSE.md) suggests it is BSD3

**Comment by tijcolem** [comment]
@deathwishdave  Thanks for catching this. The license for OpenStudio SDK (this repo) BSD3. The Application (GUI) that is now maintained at https://github.com/openstudiocoalition/OpenStudioApplication is LGPL.  We'll update openstudio.net to differentiate the licensing between the App and SDK.

**Comment by jmarrec** [comment]
openstudio.net doesn't mention LGPL anymore
