### ISSUE TITLE
Can't add a StraightComponent to an AirLoopHVAC:OutdoorAirSystem attached to AirLoopHVAC:DedicatedOutdoorAirSystem

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#4290]
Issue overview
--------------
@joseph-robertson @jmarrec 
The new AirLoopHVAC:DedicatedOutdoorAirSystem requires an AirLoopHVAC:OutdoorAirSystem on which components can be attached. Per the E+ I/O ref, supported equipment should include CoilSystem:CoolingDX (which are created for, e.g CoilCoolingDX:TwoSpeed at forward translation): 
![image](https://user-images.githubusercontent.com/10799524/114942260-81840180-9e01-11eb-8ed5-666122552a8b.png)

However, it seems that DX coils can only be attached to an AirLoopHVAC:OutdoorAirSystem if the OAS is attached to an AirLoopHVAC:
```
require 'openstudio'
include OpenStudio::Model

m = Model.new
oas = AirLoopHVACOutdoorAirSystem.new(m, ControllerOutdoorAir.new(m))
doas = AirLoopHVACDedicatedOutdoorAirSystem.new(oas)
c = CoilCoolingDXTwoSpeed.new(m)
puts c.addToNode(oas.outboardOANode.get)
```
=> false

Even if you connect an AirLoopHVAC to the DOAS:
```
require 'openstudio'
include OpenStudio::Model

m = Model.new
oas = AirLoopHVACOutdoorAirSystem.new(m, ControllerOutdoorAir.new(m))
doas = AirLoopHVACDedicatedOutdoorAirSystem.new(oas)
ahu = AirLoopHVAC.new(m)
doas.addAirLoop(ahu)
c = CoilCoolingDXTwoSpeed.new(m)
puts c.addToNode(oas.outboardOANode.get)
```
=> false

It seems StraightComponent_impl::addToNode needs to be modified to support adding to an AirLoopHVAC:OutdoorAirSystem attached to an AirLoopHVAC:DedicatedOutdoorAirSystem.
https://github.com/NREL/OpenStudio/blob/develop/src/model/StraightComponent.cpp#L156

note: both ZoneHVACEquipment (e.g. ZoneHVACTerminalUnitVariableRefrigerantFlow and AirLoopHVACUnitarySystem) and WaterToAirComponent versions of `addToNode` both attach to the OAS as expected. 

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.2.0-alpha+bc2dd59a59

**Comment by joseph-robertson** [comment]
@eringold I believe the issue is actually here in CoilCoolingDXTwoSpeed's virtual method override of `addToNode`: https://github.com/NREL/OpenStudio/blob/develop/src/model/CoilCoolingDXTwoSpeed.cpp#L692-L700.

If I extend the if block to include this case (which I believe is the scenario you are trying to model?):
```
      } else if (boost::optional<AirLoopHVACOutdoorAirSystem> oas = node.airLoopHVACOutdoorAirSystem()) {
        return StraightComponent_Impl::addToNode(node);
      }
```
it seems to work. But I'd need to verify with functional tests.

Furthermore, we'd probably want to extend all StraightComponent's virtual overrides with this logic. I need to check if this is the best path forward.

cc @jmarrec @kbenne

**Comment by jmarrec** [comment]
@joseph-robertson I think you're correct as to where to place it, and correct as far as needing to change basically all StraightCOmponent. I would make a modification to the proposed edit, so avoid allowing connecting a StraightComponent to an orphaned AirLoopHVACOutdoorAirSystem

```
 } else if (boost::optional<AirLoopHVACOutdoorAirSystem> oas = node.airLoopHVACOutdoorAirSystem()) {
        if (oas.airLoopHVACDedicatedOutdoorAirSystem()) {
            return StraightComponent_Impl::addToNode(node);
      }
 }
```
