### ISSUE TITLE
OS v3.2 new SqlFile warning

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4298]
Issue overview
--------------
Using OS v3.2, I get a new warning that I didn't get in OS v3.1:

`Using EnergyPlusVersion version 9.5.0 which should have 'Year' field, but it's always zero`

It appears to be caused by https://github.com/NREL/OpenStudio/pull/4130.

I don't know exactly what the above PR is trying to fix, but our sql files end up with Time tables where the Year is indeed empty:

![image](https://user-images.githubusercontent.com/5861765/115481244-6f430280-a209-11eb-8053-c5d2e98b6b7c.png)

Note that the Year was empty in E+ 9.4 as well, so it's not a change in E+ 9.5. Happy to provide any files to reproduce the issue if desired.

@kbenne @jmarrec

**Comment by jmarrec** [comment]
@shorowit I'm curious to see what makes your Year empty in the E+ SqlFile. 

Anyways, this is a warning that can be ignored if the rest of your workflow works.

**Comment by shorowit** [comment]
Yes I realize it's just a warning and can be ignored, but it seems like the warning is incorrect/misleading in our situation.

Here's an example model that causes it:
[in.idf.txt](https://github.com/NREL/OpenStudio/files/6377637/in.idf.txt)

If I request timeseries outputs for the same model, the warning disappears:
[in.idf.txt](https://github.com/NREL/OpenStudio/files/6377640/in.idf.txt)

**Comment by jmarrec** [comment]
Ok, so yeah, the E+ SQL file doesn't have a Year field if you didn't request any timeseries output (Output Meter or Output Variable) as a level below "RunPeriod".

How about this? Would that be better @shorowit ? Or do you see something else that would?

```diff
       // Check if zero
       boost::optional<int> maxYear = execAndReturnFirstInt("SELECT MAX(Year) FROM Time");
       if (!maxYear.is_initialized() || maxYear.get() <= 0) {
-        LOG(Warn, "Using EnergyPlusVersion version " << version.str() << " which should have 'Year' field, but it's always zero");
+        auto nOtherThanRunPeriod = execAndReturnFirstInt(
+            "SELECT COUNT(ReportingFrequency) FROM ReportDataDictionary WHERE ReportingFrequency NOT LIKE '%Run Period%'");
+        if (nOtherThanRunPeriod > 0) {
+          LOG(Warn, "Using EnergyPlusVersion version " << version.str() << " which should have 'Year' field, but it's always zero");
+        } else {
+          LOG(Info, "Your SQLFile does not contain the 'Year' field since you did not request any outputs at a frequency lower than Run Period");
+        }
         m_hasYear = false;
       }
     }
```

**Comment by jmarrec** [comment]
@shorowit thoughts?

**Comment by shorowit** [comment]
I like that it will suppress the warning for this situation but can't comment on whether it's correct/appropriate.

**Comment by tijcolem** [comment]
@jmarrec Would you be able to push up a branch/pr with your proposed solution and we can have @shorowit  test?

**Comment by jmarrec** [comment]
> @jmarrec Would you be able to push up a branch/pr with your proposed solution and we can have @shorowit test?

yes, see #4324
