### ISSUE TITLE
Where did description, other, version info go in user scripts (Bugzilla #370)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#43]
On 2011-11-22 11:28:55, @DavidGoldwasser wrote:

> Working on upgrading the diagnostic script, and realized a few things were missing.
> 
> I used to provide information on author, version, date, etc, for the user script. It was a comment in the old scripts, I thought we were turning those into variables? but I don't see them.
> 
> We also lost the pop up dialog box that user gets when they first activate a script. Nice to give them a chance to cancel out if they make a mistake, or didn't understand what the script would impact.

On 2012-01-13 15:22:01, @DavidGoldwasser wrote:

> Updated out of date Milestone Targer

On 2012-01-16 15:18:33, @DavidGoldwasser wrote:

> I either want to add this in script as comment, or create constants that can be read by users if necessary. Similar to how original user scripts were. I also want pop open a dialog with description andchance to cancel whenever the user triggers one.
> 
> # OpenStudio User Script
> # Script Name: Bad File Diagnostic
> # Author: David Goldwasser
> # Organization: NREL (optional field)
> # Version of OpenStudio written for: 0.4.5 and higher
> # Date Script Created/Modified: 10/24/11
> # User Script Version Number: 0.2 (updated for 0.5.0 files vs. 0.4.0 files)
> # SketchUp Versions Support: SU 7 or 8, free and pro, mac and windows
> 
> # Description of script function and behavior:
> 
> # Runs a variety of diagnostic tests on an IDF or OSM file looking for objects
> # that prevent the file from opening or running smoothly in the SketchUp Plugin
> # The diagnostic report is printed to the ruby console. It would be easy to adapt
> # this to write to an external file. It would also be easy to setup the script
> # to run from a command line. vs. SketchUp. Other than the interface to select the
> # file to test, there is no SketchUp API used for the diagnostic tests.

**Comment by DavidGoldwasser** [comment]
Don't expect we will fix this.
