### ISSUE TITLE
GHE design flow rate not translated

### ISSUE THREAD

**Issue by lymereJ** [NREL/OpenStudio#4304]
Issue overview
--------------
OpenStudio lets users set the design flow rate of vertical ground heat exchanger systems using the `setDesignFlowRate()` method, however, the value is not passed on to the EnergyPlus model after forward translation.

## Current Behavior
The design flow rate of vertical ground heat exchanger set using the `setDesignFlowRate()` method isn't translated into the `Design Flow Rate` field of EnergyPlus' `GroundHeatExchanger:System` object.

## Expected Behavior
The design flow rate of vertical ground heat exchanger set using the `setDesignFlowRate()` method is translated into the `Design Flow Rate` field of EnergyPlus' `GroundHeatExchanger:System` object.

## Steps to Reproduce
This ...
```
model = OpenStudio::Model::Model.new()
gloop = OpenStudio::Model::PlantLoop.new(model)
ghe = OpenStudio::Model::GroundHeatExchangerVertical.new(model)
ghe_node = gloop .supplySplitter().lastOutletModelObject().get.to_Node.get
ghe.addToNode(ghe_node)
ghe.setDesignFlowRate(0.0050)
translator = OpenStudio::OSVersion::VersionTranslator.new
trans = OpenStudio::EnergyPlus::ForwardTranslator.new
idf = trans.translateModel(model)
```
... will produce:
```
GroundHeatExchanger:System,
  Ground Heat Exchanger Vertical 1,       !- Name
  Node 3,                                 !- Inlet Node Name
  Node 7,                                 !- Outlet Node Name
  0.0033,                                 !- Design Flow Rate {m3/s}
  Site:GroundTemperature:Undisturbed:KusudaAchenbach, !- Undisturbed Ground Temperature Model Type
  Ground Heat Exchanger Vertical 1 Ground Temps, !- Undisturbed Ground Temperature Model Name
  0.692626,                               !- Ground Thermal Conductivity {W/m-K}
  2347000,                                !- Ground Thermal Heat Capacity {J/m3-K}
  Ground Heat Exchanger Vertical 1 Response Factors; !- GHE:Vertical:ResponseFactors Object Name
```
`0.0033` m3/s is the default value used by OpenStudio ([here](https://github.com/NREL/OpenStudio/blob/eadff9598068b16479b1f5a223ee0611458d2fc6/src/model/GroundHeatExchangerVertical.cpp#L475)) and is not what was set in the OpenStudio model.

## Possible Solution
It looks like `setMaximumFlowRate()` is used in place of `setDesignFlowRate()` to set the design flow rate in EnergyPlus, see [here](https://github.com/NREL/OpenStudio/blob/eadff9598068b16479b1f5a223ee0611458d2fc6/src/energyplus/ForwardTranslator/ForwardTranslateGroundHeatExchangerVertical.cpp#L131-L134). `designFlowRate` seems unused. One possible solution would be to use `designFlowRate` instead of `maximumFlowRate`.

**Comment by jmarrec** [comment]
It's confusing to say the least yes.

https://github.com/NREL/OpenStudio/blob/349202d2d29a93df839ac1c5791a3216a553c2cc/src/model/GroundHeatExchangerVertical.hpp#L85-L86

https://github.com/NREL/OpenStudio/blob/349202d2d29a93df839ac1c5791a3216a553c2cc/src/model/GroundHeatExchangerVertical.hpp#L100-L101

In hindsight, perhaps explicitly marking maximumFlowRate/setMaximumFlowRate as deprecated, and forward to the more aptly-named designFlowRate/setDesignFlowRate would have been less confusing.

(This object is also way out of line with what E+ does since 8.9 which is to break it into GHX:System, GHX:Vertical, GHX:VerticalProps.)

**Comment by jmarrec** [comment]
There should also **not** be any resetDesignFlowRate/resetMaximumFlowRate as these are actually E+ required-field. the designFlowRate() one should return a double, not an optional<double>.

I'm not sure what do to with this object, do a minimal fix or take the opportunity to revamp it seriously by somewhat breaking API. @kbenne thoughts please?

**Comment by jmarrec** [comment]
Minimal fix in https://github.com/NREL/OpenStudio/pull/4305. I think this object would benefit from a major clean up though.

**Comment by lymereJ** [comment]
Thanks for the prompt follow up, @jmarrec. If you are considering a clean up, do you think that it would make sense to also wrap the `GroundHeatExchanger:Vertical:Array` and `GroundHeatExchanger:Vertical:Single` EnergyPlus objects as part of `GroundHeatExchangerVertical`? These objects seem to provide more flexibility than `GroundHeatExchanger:ResponseFactors` since they let EnergyPlus calculate the response factors.
