### ISSUE TITLE
Floor js json import enters infinite loop of import warnings and errors

### ISSUE THREAD

**Issue by antonszilasi** [NREL/OpenStudio#4312]
Issue overview
--------------

Im certain that this is related to issue: https://github.com/NREL/OpenStudio/issues/4237

https://drive.google.com/file/d/1YFgUvUOP9U2_KwzMb1AR5jtgPnLuVOO8/view?usp=sharing

I am in the process of working which curves cause this problem

Environment
OpenStudio 3.1.0

**Comment by ggartside** [comment]
@antonszilasi Hi I'm looking at this issue to see if it has been resolved and I'm having an issue getting the test file from your google drive. If you still have it can you email it to me at gerard.gartside at d-alchemy.com. I will also request permission to get it from your google drive. Thanks

**Comment by ggartside** [comment]
I have verified that this issue is fixed, importing this file no longer enters an infinite loop
