### ISSUE TITLE
Floor js json import successful with many warnings, EnergyPlus run fails

### ISSUE THREAD

**Issue by antonszilasi** [NREL/OpenStudio#4313]
Issue overview
--------------
Floor js json import successful with many warnings

## Current Behavior
Upon import the following warnings are produced by OpenStudio, it would be good to know what these mean and are they a problem?

floor js json can be found here: https://drive.google.com/file/d/1cjIj4_7R65TR2CWFNw51UIbkC-W9dDvR/view?usp=sharing

[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon
[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon
[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon
[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon
[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon
[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon
[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon
[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon
[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon
[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon
[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon
[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon
[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon
[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon
[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon
[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon
[openstudio.model.Surface] <1> Initial area of surface 'Face 44' 2519.41 does not equal post intersection area 2519.42
[openstudio.model.Surface] <1> Initial area of surface 'Surface 1' 2474.71 does not equal post intersection area 2474.72
[openstudio.model.Surface] <1> Initial area of surface 'Surface 3' 2401.63 does not equal post intersection area 2399.6
[openstudio.model.Surface] <1> Initial area of other surface 'Face 113' 167.903 does not equal post intersection area 167.919
[openstudio.model.Surface] <1> Initial area of surface 'Surface 12' 716.098 does not equal post intersection area 716.094
[openstudio.model.Surface] <1> Initial area of other surface 'Surface 15' 167.915 does not equal post intersection area 167.893
[utilities.geometry.intersect] <1> Face difference is self intersecting, result will not include this polygon, [[0.17294, 10.6031, 0], [17.526, 18.288, 0], [19.7175, 19.2268, 0], [18.3161, 22.0415, 0], [18.1935, 22.0553, 0], [38.1, 19.812, 0], [0.762, 0, 0]]
[openstudio.model.Surface] <1> Initial area of surface 'Surface 7' 367.023 does not equal post intersection area 63.1387
[utilities.geometry.intersect] <1> Face difference is self intersecting, result will not include this polygon, [[0.143256, 6.858, 0], [10.7212, 11.5425, 0], [4.26415, 11.3812, 0], [36.7193, 12.192, 0], [3.95326, 0, 0]]
[openstudio.model.Surface] <1> Initial area of surface 'Surface 11' 212.929 does not equal post intersection area 19.8893
[openstudio.model.Surface] <1> Initial area of other surface 'Face 84' 274.659 does not equal post intersection area 274.659
[openstudio.model.Surface] <1> Initial area of other surface 'Face 125' 501.714 does not equal post intersection area 501.721
[openstudio.model.Surface] <1> Initial area of surface 'Surface 22' 252.045 does not equal post intersection area 252.32
[openstudio.model.Surface] <1> Initial area of surface 'Face 96' 165.696 does not equal post intersection area 166.215
[openstudio.model.Surface] <1> Initial area of other surface 'Face 179' 165.696 does not equal post intersection area 166.215
[openstudio.model.Surface] <1> Initial area of surface 'Face 114' 167.903 does not equal post intersection area 168.765
[openstudio.model.Surface] <1> Initial area of other surface 'Face 197' 167.903 does not equal post intersection area 168.765
[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane
[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane
[openstudio.model.Surface] <1> Initial area of surface 'Face 85' 274.659 does not equal post intersection area 274.659
[openstudio.model.Surface] <1> Initial area of other surface 'Face 168' 274.659 does not equal post intersection area 274.659
[openstudio.model.Surface] <1> Initial area of surface 'Face 126' 501.714 does not equal post intersection area 501.716
[openstudio.model.Surface] <1> Initial area of other surface 'Face 209' 501.714 does not equal post intersection area 501.716
[openstudio.model.Surface] <1> Initial area of surface 'Face 180' 165.696 does not equal post intersection area 166.215
[openstudio.model.Surface] <1> Initial area of other surface 'Face 263' 165.696 does not equal post intersection area 166.215
[openstudio.model.Surface] <1> Initial area of surface 'Face 198' 167.903 does not equal post intersection area 168.765
[openstudio.model.Surface] <1> Initial area of other surface 'Face 281' 167.903 does not equal post intersection area 168.765
[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane
[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane
[openstudio.model.Surface] <1> Initial area of surface 'Face 169' 274.659 does not equal post intersection area 274.659
[openstudio.model.Surface] <1> Initial area of other surface 'Face 252' 274.659 does not equal post intersection area 274.659
[openstudio.model.Surface] <1> Initial area of surface 'Face 210' 501.714 does not equal post intersection area 501.716
[openstudio.model.Surface] <1> Initial area of other surface 'Face 293' 501.714 does not equal post intersection area 501.716
[openstudio.model.Surface] <1> Initial area of surface 'Face 264' 165.696 does not equal post intersection area 166.215
[openstudio.model.Surface] <1> Initial area of other surface 'Face 347' 165.696 does not equal post intersection area 166.215
[openstudio.model.Surface] <1> Initial area of surface 'Face 282' 167.903 does not equal post intersection area 168.765
[openstudio.model.Surface] <1> Initial area of other surface 'Face 365' 167.903 does not equal post intersection area 168.765
[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane
[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane
[openstudio.model.Surface] <1> Initial area of surface 'Face 253' 274.659 does not equal post intersection area 274.659
[openstudio.model.Surface] <1> Initial area of other surface 'Face 336' 274.659 does not equal post intersection area 274.659
[openstudio.model.Surface] <1> Initial area of surface 'Face 294' 501.714 does not equal post intersection area 501.716
[openstudio.model.Surface] <1> Initial area of other surface 'Face 377' 501.714 does not equal post intersection area 501.716
[openstudio.model.Surface] <1> Initial area of surface 'Face 348' 165.696 does not equal post intersection area 166.215
[openstudio.model.Surface] <1> Initial area of other surface 'Face 431' 165.696 does not equal post intersection area 166.215
[openstudio.model.Surface] <1> Initial area of surface 'Face 366' 167.903 does not equal post intersection area 168.765
[openstudio.model.Surface] <1> Initial area of other surface 'Face 449' 167.903 does not equal post intersection area 168.765
[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane
[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane
[openstudio.model.Surface] <1> Initial area of surface 'Face 337' 274.659 does not equal post intersection area 274.659
[openstudio.model.Surface] <1> Initial area of other surface 'Face 420' 274.659 does not equal post intersection area 274.659
[openstudio.model.Surface] <1> Initial area of surface 'Face 378' 501.714 does not equal post intersection area 501.716
[openstudio.model.Surface] <1> Initial area of other surface 'Face 461' 501.714 does not equal post intersection area 501.716
[openstudio.model.Surface] <1> Initial area of surface 'Face 432' 165.696 does not equal post intersection area 166.215
[openstudio.model.Surface] <1> Initial area of other surface 'Face 515' 165.696 does not equal post intersection area 166.215
[openstudio.model.Surface] <1> Initial area of surface 'Face 450' 167.903 does not equal post intersection area 168.765
[openstudio.model.Surface] <1> Initial area of other surface 'Face 533' 167.903 does not equal post intersection area 168.765
[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane
[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane
[openstudio.model.Surface] <1> Initial area of surface 'Face 421' 274.659 does not equal post intersection area 274.659
[openstudio.model.Surface] <1> Initial area of other surface 'Face 504' 274.659 does not equal post intersection area 274.659
[openstudio.model.Surface] <1> Initial area of surface 'Face 462' 501.714 does not equal post intersection area 501.716
[openstudio.model.Surface] <1> Initial area of other surface 'Face 545' 501.714 does not equal post intersection area 501.716
[openstudio.model.Surface] <1> Initial area of surface 'Face 516' 165.696 does not equal post intersection area 166.215
[openstudio.model.Surface] <1> Initial area of other surface 'Face 599' 165.696 does not equal post intersection area 166.215
[openstudio.model.Surface] <1> Initial area of surface 'Face 534' 167.903 does not equal post intersection area 168.765
[openstudio.model.Surface] <1> Initial area of other surface 'Face 617' 167.903 does not equal post intersection area 168.765
[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane
[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane
[openstudio.model.Surface] <1> Initial area of surface 'Face 505' 274.659 does not equal post intersection area 274.659
[openstudio.model.Surface] <1> Initial area of other surface 'Face 588' 274.659 does not equal post intersection area 274.659
[openstudio.model.Surface] <1> Initial area of surface 'Face 546' 501.714 does not equal post intersection area 501.716
[openstudio.model.Surface] <1> Initial area of other surface 'Face 629' 501.714 does not equal post intersection area 501.716
[openstudio.model.Surface] <1> Initial area of surface 'Face 600' 165.696 does not equal post intersection area 166.215
[openstudio.model.Surface] <1> Initial area of other surface 'Face 683' 165.696 does not equal post intersection area 166.215
[openstudio.model.Surface] <1> Initial area of surface 'Face 618' 167.903 does not equal post intersection area 168.765
[openstudio.model.Surface] <1> Initial area of other surface 'Face 701' 167.903 does not equal post intersection area 168.765
[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane
[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane
[openstudio.model.Surface] <1> Initial area of surface 'Face 589' 274.659 does not equal post intersection area 274.659
[openstudio.model.Surface] <1> Initial area of other surface 'Face 672' 274.659 does not equal post intersection area 274.659
[openstudio.model.Surface] <1> Initial area of surface 'Face 630' 501.714 does not equal post intersection area 501.716
[openstudio.model.Surface] <1> Initial area of other surface 'Face 713' 501.714 does not equal post intersection area 501.716
[openstudio.model.Surface] <1> Initial area of other surface 'Surface 36' 2440.75 does not equal post intersection area 2440.75
[openstudio.model.Surface] <1> Initial area of other surface 'Surface 37' 2367.66 does not equal post intersection area 2487.9
[openstudio.model.Surface] <1> Initial area of surface 'Face 702' 167.903 does not equal post intersection area 168.172
[openstudio.model.Surface] <1> Initial area of other surface 'Surface 47' 716.098 does not equal post intersection area 716.094
[utilities.geometry.intersect] <1> Face difference is self intersecting, result will not include this polygon, [[0.143256, 0, 0], [10.7212, 4.68454, 0], [4.26415, 4.52323, 0], [36.7193, 5.334, 0], [3.95326, -6.858, 0]]
[openstudio.model.Surface] <1> Initial area of other surface 'Surface 46' 212.929 does not equal post intersection area 19.8893
[openstudio.model.Surface] <1> Initial area of surface 'Face 673' 274.659 does not equal post intersection area 274.659
[openstudio.model.Surface] <1> Initial area of surface 'Face 714' 501.714 does not equal post intersection area 501.721
[openstudio.model.Surface] <1> Initial area of surface 'Surface 69' 138.265 does not equal post intersection area 138.62

## Details

Upon import the geometry looks good however:
![image](https://user-images.githubusercontent.com/8773483/117231166-e5d02a80-addb-11eb-916d-3bbb51d170f9.png)

![image](https://user-images.githubusercontent.com/8773483/117231172-e9fc4800-addb-11eb-928e-a45fb57beabc.png)

There is some overlap with floors could this be causing these issues?

![image](https://user-images.githubusercontent.com/8773483/117231265-20d25e00-addc-11eb-8737-a3daa3ab6939.png)

Unforunately while this floor js json does import into OpenStudio successfully EnergyPlus cannot run successfully it fails with the following errors due to Geometry

![image](https://user-images.githubusercontent.com/8773483/117265587-9d336400-ae11-11eb-957d-1f126fc565da.png)

### Environment

OpenStudio 3.1.0

**Comment by tijcolem** [comment]
I think we should re-test this with 3.2.0 now that has many geometry related changes in this version. @antonszilasi Would you be able to upgrade to 3.2.0 and retest?

**Comment by antonszilasi** [comment]
@tijcolem 
Confirmed that with 3.2.0 EnergyPlus now can run successfully and geometry issues seen in the floor intersections above are fixed:
![image](https://user-images.githubusercontent.com/8773483/118750831-76b3f680-b81d-11eb-939b-172a679b154c.png)

However I am still getting the following warnings when importing the floor.js json

```
{"message":"[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.simplify] <0> 2 unique vertices were not added back to the polygon\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Face 80' 2519.41 does not equal post intersection area 2519.32\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Surface 1' 2474.61 does not equal post intersection area 2474.52\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Surface 3' 2401.42 does not equal post intersection area 2401.33\r\n[openstudio.model.Surface] <1> Initial area of other surface 'Face 143' 161.294 does not equal post intersection area 161.298\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Surface 4' 2240.03 does not equal post intersection area 2239.93\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Surface 5' 2074.24 does not equal post intersection area 2075\r\n[openstudio.model.Surface] <1> Initial area of other surface 'Face 249' 167.903 does not equal post intersection area 168.748\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Surface 7' 700.713 does not equal post intersection area 700.47\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Surface 6' 1205.53 does not equal post intersection area 1205.5\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of other surface 'Face 261' 501.714 does not equal post intersection area 501.721\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Surface 8' 520.979 does not equal post intersection area 520.43\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Face 144' 161.294 does not equal post intersection area 161.298\r\n[openstudio.model.Surface] <1> Initial area of other surface 'Face 299' 161.294 does not equal post intersection area 161.298\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Face 250' 167.903 does not equal post intersection area 168.748\r\n[openstudio.model.Surface] <1> Initial area of other surface 'Face 405' 167.903 does not equal post intersection area 168.748\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Face 262' 501.714 does not equal post intersection area 501.716\r\n[openstudio.model.Surface] <1> Initial area of other surface 'Face 417' 501.714 does not equal post intersection area 501.716\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Face 300' 161.294 does not equal post intersection area 161.298\r\n[openstudio.model.Surface] <1> Initial area of other surface 'Face 455' 161.294 does not equal post intersection area 161.298\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Face 406' 167.903 does not equal post intersection area 168.748\r\n[openstudio.model.Surface] <1> Initial area of other surface 'Face 561' 167.903 does not equal post intersection area 168.748\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Face 418' 501.714 does not equal post intersection area 501.716\r\n[openstudio.model.Surface] <1> Initial area of other surface 'Face 573' 501.714 does not equal post intersection area 501.716\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Face 456' 161.294 does not equal post intersection area 161.298\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of other surface 'Face 611' 161.294 does not equal post intersection area 161.298\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Face 562' 167.903 does not equal post intersection area 168.748\r\n[openstudio.model.Surface] <1> Initial area of other surface 'Face 717' 167.903 does not equal post intersection area 168.748\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Face 574' 501.714 does not equal post intersection area 501.716\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of other surface 'Face 729' 501.714 does not equal post intersection area 501.716\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Face 612' 161.294 does not equal post intersection area 161.298\r\n[openstudio.model.Surface] <1> Initial area of other surface 'Face 767' 161.294 does not equal post intersection area 161.298\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Face 718' 167.903 does not equal post intersection area 168.748\r\n[openstudio.model.Surface] <1> Initial area of other surface 'Face 873' 167.903 does not equal post intersection area 168.748\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Face 730' 501.714 does not equal post intersection area 501.716\r\n[openstudio.model.Surface] <1> Initial area of other surface 'Face 885' 501.714 does not equal post intersection area 501.716\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Face 768' 161.294 does not equal post intersection area 161.298\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of other surface 'Face 923' 161.294 does not equal post intersection area 161.298\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Face 874' 167.903 does not equal post intersection area 168.748\r\n[openstudio.model.Surface] <1> Initial area of other surface 'Face 1029' 167.903 does not equal post intersection area 168.748\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Face 886' 501.714 does not equal post intersection area 501.716\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of other surface 'Face 1041' 501.714 does not equal post intersection area 501.716\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Face 924' 161.294 does not equal post intersection area 161.298\r\n[openstudio.model.Surface] <1> Initial area of other surface 'Face 1079' 161.294 does not equal post intersection area 161.298\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Face 1030' 167.903 does not equal post intersection area 168.748\r\n[openstudio.model.Surface] <1> Initial area of other surface 'Face 1185' 167.903 does not equal post intersection area 168.748\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Face 1042' 501.714 does not equal post intersection area 501.716\r\n[openstudio.model.Surface] <1> Initial area of other surface 'Face 1197' 501.714 does not equal post intersection area 501.716\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Face 1080' 161.294 does not equal post intersection area 161.298\r\n[openstudio.model.Surface] <1> Initial area of other surface 'Face 1235' 161.294 does not equal post intersection area 161.298\r\n","level":"info","label":"openstudio"}
{"message":"[openstudio.model.Surface] <1> Initial area of surface 'Face 1186' 167.903 does not equal post intersection area 168.748\r\n[openstudio.model.Surface] <1> Initial area of other surface 'Face 1341' 167.903 does not equal post intersection area 168.748\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane\r\n","level":"info","label":"openstudio"}
{"message":"[utilities.geometry.boostRingFromVertices] <1> All points must be on z = 0 plane\r\n","level":"info","label":"openstudio"}
```

**Comment by ggartside** [comment]
@antonszilasi Hi I'm looking at this issue to see if it has been resolved and I'm having an issue getting the test file from your google drive. If you still have it can you email it to me at gerard.gartside at d-alchemy.com. I will also request permission to get it from your google drive. Thanks

**Comment by antonszilasi** [comment]
@ggartside did you get permission to this?

**Comment by ggartside** [comment]
Yes I did thanks!
