### ISSUE TITLE
Wrap E+ FuelFactors object

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4315]
Enhancement Request
--------------
The [EnergyPlus FuelFactors object](https://bigladdersoftware.com/epx/docs/9-5/input-output-reference/input-for-output.html#fuelfactors) is not available in the OS SDK. We have a lot of interest in using this for calculating carbon metrics (similar to TDV) in the near-ish future and it would be nice to not have to resort to an EnergyPlus measure.

**Comment by jmarrec** [comment]
seems like you may need three objects, cf https://bigladdersoftware.com/epx/docs/9-5/input-output-reference/input-for-output.html#outputenvironmentalimpactfactors

*  Output:EnvironmentalImpactFactors: (with associated reporting frequency, more than one frequency can be requested)

* EnvironmentalImpactFactors: (contains additional information necessary for the calculations not included in the Fuel Factors)

* FuelFactors: (required for every fuel that is simulated and converted in this simulation input file)
