### ISSUE TITLE
Skethcup plugin error at startup: path name contains null byte

### ISSUE THREAD

**Issue by gpmendoza** [NREL/OpenStudio#4322]
I have Sketchup Pro 2019, installed OpenStudio SDK v3.1.0, OpenStudio Application V1.1.0, and downloaded Plug-in version v1.1.0. Every version according to the 
[https://github.com/openstudiocoalition/OpenStudioApplication/wiki/OpenStudio-Application-Version-Compatibility-Matrix](url)

I then started Sketchup and installed the plugin, following instruction on [https://github.com/openstudiocoalition/openstudio-sketchup-plugin/releases](url)
It did prompted me asking for the Openstudio application root path which was in c:\ 
The Openstudio toolbars appeared and everything worked just fine.
However, a windows update later... now everytime I open SKetchup there´s an error stating that path name contains null byte, but the plugin is still in the very same folder and the path that appears on the error is correct, it´s the very same path where all the sketchup plugins are.

I have unistalled everything, even manually deleting the AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins folder, restarting the computer, re-installing everything again and still the same error. The other plugins work just fine.

And something interesting happened: I created a new windows user on my laptop, and in that other user I can install the Openstudio plugin without problem, no error when opening sketchup again, and the Openstudio toolbars appear just fine. 

How can I make the Openstudio plugin work again on my normal user where I have all my data?

[error sketchup Openstudio plugin.txt](https://github.com/NREL/OpenStudio/files/6482136/error.sketchup.Openstudio.plugin.txt)
### Error
Error Loading File C:/Users/gpmen/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/OpenStudio/Startup.rb
Error: #<ArgumentError: path name contains null byte>
C:/Users/gpmen/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/OpenStudio/Startup.rb:40:in `exists?'
C:/Users/gpmen/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/OpenStudio/Startup.rb:40:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2019/Tools/extensions.rb:197:in `require'
C:/Program Files/SketchUp/SketchUp 2019/Tools/extensions.rb:197:in `load'
C:/Users/gpmen/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/openstudio.rb:47:in `register_extension'
C:/Users/gpmen/AppData/Roaming/SketchUp/SketchUp 2019/SketchUp/Plugins/openstudio.rb:47:in `<top (required)>'

### Environment
- I´m working on Windows 10, 64-bit

**Comment by macumber** [comment]
This should be posted in https://github.com/openstudiocoalition/OpenStudio-sketchup-plugin or unmethours since it is not about the OpenStudio SDK.  I made this issue, https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/73, we can continue the conversation there.
