### ISSUE TITLE
Subsurface boundary conditions display wrong

### ISSUE THREAD

**Issue by onnomobile** [NREL/OpenStudio#4328]
Issue overview
--------------
In the spaces tab, in the subsurfaces section, the "outside boundary condition object" is not correct.

## Current Behavior
The field displayed is actually the subsurface name.

## Expected Behavior
This field should display the matched boundary subsurface. 

## Steps to Reproduce
I created the geometry with Sketchup plugin.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Win 10,
 - Version of OpenStudio (if using an intermediate build, include SHA): 1.1.0 (SDK 3.1.0)

### Context
I understood it was wrong quite fast and looked at the correct value in sketchup or IDF.

**Comment by macumber** [comment]
This sounds like an issue with the OpenStudio Application and not the OpenStudio SDK (this repo).  I created a new issue, https://github.com/openstudiocoalition/OpenStudioApplication/issues/340, we can continue the conversation there

**Comment by jmarrec** [comment]
Thanks for moving it @macumber. Closing
