### ISSUE TITLE
Switch to Fan:SystemModel in HVAC objects

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4334]
Enhancement Request
--------------
Follow-up to [Add Fan:SystemModel to OpenStudio](https://github.com/NREL/OpenStudio/pull/3856). In that PR, @jmarrec included the message:

> There are a bunch of objects that should accept Fan:SystemModel but actually don't due to IDD \object-list and \references not matching. In particular, Fan:SystemModel isn't part of FanOnOff while a bunch of ZoneHVAC objects accept Type= Fan:SystemModel but Name only FanOnOff. Cf NREL/EnergyPlus#7697

The above EnergyPlus PR has been merged, so it would be nice to update the OS objects to use Fan:SystemModel instead of Fan:OnOff. At a minimum, it looks like these objects need to be updated:
- WaterHeaterHeatPump
- WaterHeaterHeatPumpWrappedCondenser
- ZoneHVACEnergyRecoveryVentilator

**Comment by jmarrec** [comment]
@shorowit The ProposedEnergy+.idd is in line with the PR (in fact I made the changes to the OpenStudio ProposedEnergy+.idd first then propagated them upstream to E+).

Could you advise on what isn't working?

```ruby
include OpenStudio::Model;
m = Model.new
supplyFan = FanSystemModel.new(m)
exhaustFan = FanSystemModel.new(m)
hx = HeatExchangerAirToAirSensibleAndLatent.new(m)
erv = ZoneHVACEnergyRecoveryVentilator.new(m, hx, supplyFan, exhaustFan)

pts = OpenStudio::Point3dVector.new;  pts << OpenStudio::Point3d.new(0, 0, 0); pts << OpenStudio::Point3d.new(0, 1, 0); pts << OpenStudio::Point3d.new(1, 1, 0); pts << OpenStudio::Point3d.new(1, 0, 0);
space = Space::fromFloorPrint(pts, 3, m).get()
z = ThermalZone.new(m)
space.setThermalZone(z)
erv.addToThermalZone(z)

ft = OpenStudio::EnergyPlus::ForwardTranslator.new
w = ft.translateModel(m)

puts w.getObjectsByType("ZoneHVAC:EquipmentList")
ZoneHVAC:EquipmentList,
  Thermal Zone 1 Equipment List,          !- Name
  SequentialLoad,                         !- Load Distribution Scheme
  ZoneHVAC:EnergyRecoveryVentilator,      !- Zone Equipment Object Type 1
  Zone HVAC Energy Recovery Ventilator 1, !- Zone Equipment Name 1
  1,                                      !- Zone Equipment Cooling Sequence 1
  1,                                      !- Zone Equipment Heating or No-Load Sequence 1
  ,                                       !- Zone Equipment Sequential Cooling Fraction Schedule Name 1
  ;                                       !- Zone Equipment Sequential Heating Fraction Schedule Name 1


puts w.getObjectsByType("ZoneHVAC:EnergyRecoveryVentilator")
ZoneHVAC:EnergyRecoveryVentilator,
  Zone HVAC Energy Recovery Ventilator 1, !- Name
  Always On Discrete,                     !- Availability Schedule Name
  Heat Exchanger Air To Air Sensible And Latent 1, !- Heat Exchanger Name
  AutoSize,                               !- Supply Air Flow Rate {m3/s}
  AutoSize,                               !- Exhaust Air Flow Rate {m3/s}
  Fan System Model 1,                     !- Supply Air Fan Name
  Fan System Model 2,                     !- Exhaust Air Fan Name
  ,                                       !- Controller Name
  0.000508,                               !- Ventilation Rate per Unit Floor Area {m3/s-m2}
  0.00236;                                !- Ventilation Rate per Occupant {m3/s-person}
```

**Comment by jmarrec** [comment]
oh, did you mean that the default Ctors should use a Fan:SystemModel instead of a FanOnOff?

Like for eg here: https://github.com/NREL/OpenStudio/blob/b2d8eb7ff45fb56b5c10e6679d78219219acc153/src/model/ZoneHVACEnergyRecoveryVentilator.cpp#L367-L376

Is that it? If so I'm a bit reluctant to make that change until E+ officially deprecates the other fan objects, cf https://github.com/NREL/EnergyPlus/issues/6903 which has been around for 3 years but hasn't moved since then.

**Comment by shorowit** [comment]
Yes, that is what I was referring to. Here's another example; would be nice if it was a FanSystemModel instead of FanOnOff object.

```
m = OpenStudio::Model::Model.new
hpwh = OpenStudio::Model::WaterHeaterHeatPumpWrappedCondenser.new(m)
puts hpwh.fan
OS:Fan:OnOff,
  {f4386369-c573-4306-a1b8-f0dbe7fbc1ac}, !- Handle
  Fan On Off 1,                           !- Name
  {f8537ce4-1114-495d-94e9-8fbcd66940ef}, !- Availability Schedule Name
  0.6,                                    !- Fan Total Efficiency
  300,                                    !- Pressure Rise {Pa}
  autosize,                               !- Maximum Flow Rate {m3/s}
  0.8,                                    !- Motor Efficiency
  1,                                      !- Motor In Airstream Fraction
  ,                                       !- Air Inlet Node Name
  ,                                       !- Air Outlet Node Name
  {da9a6652-ad06-44a2-9c48-05450298cc57}, !- Fan Power Ratio Function of Speed Ratio Curve Name
  {a4d7734f-0c41-4764-8eb4-f3162c9d50bc}, !- Fan Efficiency Ratio Function of Speed Ratio Curve Name
  ;                                       !- End-Use Subcategory
```

**Comment by joseph-robertson** [comment]
Until E+ officially deprecates the other fan objects, would it be useful to provide alternative overload ctors so other fan types can be passed in? Or should we just wait until the deprecation?

**Comment by tijcolem** [comment]
@shorowit Are you able to make use the ctor overload?  https://github.com/NREL/OpenStudio/blob/1b8f0d3549d67f5e461677439ee85c5d6f6cad0c/src/model/ZoneHVACEnergyRecoveryVentilator.hpp#L59. 

If so, I think just use that as we don't want to change the default ctor.

**Comment by shorowit** [comment]
🤦‍♂️ I totally missed that there are alternate constructors (and even `setFan` methods) that can be used to swap the FanOnOff for a  FanSystemModel. So yes that works for me. And my issue is now moot.
