### ISSUE TITLE
OpenStudio API-reported surface "netArea" (when dealing with Frame & Divider objects)

### ISSUE THREAD

**Issue by rd2** [NREL/OpenStudio#4361]
Issue overview
--------------
It seems the OpenStudio API is reporting erroneous [netArea](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-3.2.0-doc/model/html/classopenstudio_1_1model_1_1_planar_surface.html#ae757533696d34e5bc50bd396c9e1eab0) values for opaque (planar) surfaces with subsurfaces holding _Frame & Divider_ objects (which in turn affects OpenStudio API-reported WWR). For models with many windows (especially with narrow aspect ratios), OpenStudio API-reported WWR may be off by 5% to 10%.

## Current Behavior
As described in the _EnergyPlus Input Output Reference Manual_, subsurface vertices "are those of the glazed part of the window, not the frame" when dealing with [Frame & Divider](https://bigladdersoftware.com/epx/docs/9-5/input-output-reference/group-thermal-zone-description-geometry.html#windowpropertyframeanddivider) objects. "EnergyPlus automatically subtracts the area of the frame - determined from the glazing dimensions and the frame width - from the area of the wall containing the window". Although OpenStudio's forward translation to EnergyPlus remains valid (EnergyPlus correctly reports surface/subsurface net vs gross areas, valid WWR, etc.) when dealing with _Frame & Divider_ objects, the OpenStudio API opaque surface _netArea_ method reports values as if the subsurface vertices described the _rough opening_ (and not the glazed portion).

## Expected Behavior
When dealing with _Frame & Divider_ objects, OpenStudio API should report _pre-simulation_ exactly what EnergyPlus reports _post-simulation_ e.g., opaque surface _net area_, WWR, etc.

## Steps to Reproduce
The easiest is to go through the tests [here](https://github.com/rd2/tbd/blob/d758edcc051067e845a413ec3d71ab5b6b830c04/spec/tbd_tests_spec.rb#L4414), where both issue and proposed [workaround](https://github.com/rd2/tbd/blob/d758edcc051067e845a413ec3d71ab5b6b830c04/lib/framedivider.rb#L124) are tested.

## Possible Solution
See aforementioned [workaround](https://github.com/rd2/tbd/blob/d758edcc051067e845a413ec3d71ab5b6b830c04/lib/framedivider.rb#L124) (this would require some cleaning up and porting it to C++). This would in turn likely require adjusting API WWR [calculations](https://github.com/NREL/OpenStudio/blob/70a5549c439eda69d6c514a7275254f71f7e3d2b/src/model/Surface.cpp#L1446).

### Environment

Tests are initially written for OpenStudio v2.9.1 (on a Mac), although PRs to TBD systematically go through automated 3.x Docker'ered [testing](https://github.com/rd2/tbd/actions) as well. Same behaviour.

### Context
This was recently observed when trying to accommodate subsurfaces (with Frame & Divider objects) for the _Thermal Bridging & Derating_ ([TBD](https://github.com/rd2/tbd)) OpenStudio Measure. Window (door, skylight) _rough opening_ perimeters generally do represent notable thermal bridges (mainly due to a greater concentration of structural supports e.g., lintels). So we knew we had to generate _substitute_ subsurface vertices for our _rough openings_ in our [Topolys](https://github.com/automaticmagic/topolys) back engine. The workaround not only generates the right _rough opening_ vertices (and hence the right edge lengths), it also validates whether the _rough opening_ fits within the parent surface and avoids any overlaps with its siblings (i.e., other surface's subsurfaces). The function also reports the correct _rough opening_ area (m2), which is crucial in TBD's thermal _derating_ step (based on parent surface _net area_). In addition, TBD will _soon_ (a month from this posting?) offer an _enhanced_ UA method (which will factor-in _major_ thermal bridging, as well as WWR), the calculation of which would be enabled without running an EnergyPlus simulation (i.e., _Apply Measures Now_). For these reasons, TBD no longer relies (for now) on OpenStudio API-reported _netArea_ (_derating_ workaround can be found [here](https://github.com/rd2/tbd/blob/d758edcc051067e845a413ec3d71ab5b6b830c04/lib/psi.rb#L1560)).

**Comment by macumber** [comment]
This is a great bug report with a suggested implementation.  My suggestion would be to add new methods (e.g. `frameArea`) and then match the results of each method to the reporting in E+ output tables.

**Comment by ggartside** [comment]
Its a very comprehensive report!

If I can summarize and someone chime in (Dan?) to confirm that I have understood this correctly or correct me where I am wrong

1. E+ and OS are reporting different net areas for opaque surfaces containing sub surfaces that have an associated Frame And Divider object
2. If there is a Frame and Divider object then the sub surface vertices define the glazing part, an additional area for the frame has to be subtracted from the gross area
3.  The proposed workaround is to get the frame width from the Frame and Divider object and create a polygon that is offset from the original sub-surface vertices by the amount of the frame thickness
4. This offset polygon is what will be used to calculate the area to be subtracted form the gross area of the opaque surface

**Comment by rd2** [comment]
1. Correct.
2. Correct. This is handled correctly in E+ ... not OS SDK.
3. Correct.
4. Correct. We take a few extra steps (e.g. ensure the new subsurface vertices _fit_ within the opaque surface, avoid overlaps between subsurfaces of the same opaque surface ... given the revised vertices).

Thanks!

**Comment by rd2** [comment]
_roughOpeningArea_ is preferable to _totalArea_, IMO ... (_grossArea_ even better ... yet I can appreciate the concern). If it helps, @macumber 's initial suggestion of [adding methods](https://github.com/NREL/OpenStudio/issues/4361#issuecomment-864723547) to match E+ table output (e.g. _glassArea_, _frameArea_, _dividerArea_) is pretty good (no confusion as to what they mean, easy to validate vs E+ output, etc.). In the end, _netArea_ can simply equate to _glassArea_. 

<img width="567" alt="frameArea" src="https://user-images.githubusercontent.com/40636643/131213557-0fb0c288-bb5c-4d4b-a60c-f43805575f2a.png">

Good luck with the tests.

**Comment by macumber** [comment]
GrossArea and NetArea are members of the PlanarSurface base class.  They are mostly concerned about subtracting the child's (SubSurface) gross area from the parent's (Surface) gross area to get the parent's net area, https://github.com/NREL/OpenStudio/blob/develop/src/model/PlanarSurface.cpp#L258.  That indicates to me that the grossArea of a SubSurface should be the rough opening area.

Going down to the new level, it does make sense to me that the netArea of a SubSurface would be the glazed area (grossArea minus the frame and divider area).  The same should apply to glass doors or even non-glazed doors and other SubSurface types.

I would then add methods to match the E+ outputs to the SubSurface class only.  That way, if you know you are working with a SubSurface you can use the more meaningful names.

**Comment by macumber** [comment]
Finally, it seems like this would be a good point to include window reveals since those are part of the frame and divider object:

![image](https://user-images.githubusercontent.com/1327850/131223967-7c1787d9-a91f-4a2a-aeb4-84d924bbc74b.png)

I don't think E+ models any extra heat transfer through the exterior reveal, they are only used for shading and reflectance.  So I don't think we want to modify the parent surface's area to add the reveals.  But we should run an E+ calculation and try to match it's results for areas and add in methods for any extra variables that get reported.

**Comment by ggartside** [comment]
On the topic of handling the case where sub surfaces overlap or extend beyond the parent surface I have added a method to Surface,  totalAreaOfSubsurfaces, which in the spirit of the fit method reverts the subsurface rough opening vertices back to the original vertices (i.e. ignores the frame thickness) if the subsurface overlaps another sub surface or extends beyond the parent surface. But I'm not sure if this is the best idea or whether the method should use polygon booleans to determine first the common area of the sub surface and the parent surface and then adding these common areas together to come up with the sub surface area which would include at leas some of the frame areas. I guess its a question of trying to match what E+ does when calculating WWR in these cases.

On @macumber comments:

Surface gross area = the area of the polygon defined by the surface's vertices
Surface net area = Surface Gross Area - sub surface rough opening area
Sub surface net area = the area of the polygon defined by the sub surface's vertices
Sub surface gross area = the area of the sub surface vertices offset by the thickness of the frame (i.e. the rough opening)

If this is correct I can adjust the functions accordingly (currently SubSurface has roughOpening and roughOpeningArea) but

**Comment by macumber** [comment]
I'm not sure if I think "Sub surface net area" should be "the area of the polygon defined by the sub surface's vertices" or "the area of the polygon defined by the sub surface's vertices minus the area of the dividers".  I do think sub surface should have a "frameArea" and "dividerArea" method and the documentation should be clear enough that the user can figure it out either way.

**Comment by macumber** [comment]
As far as overlapping windows, I would add a methods like `PlanarSurface::grossAreaVertices`, then use that to implement a `PlanarSurface::overlaps(const PlanarSurface& other) const` method;

**Comment by rd2** [comment]
Concerning subsurface overlaps (or not fitting in with their parent), as long as users get a warning (or non-fatal error) red-flagging the situation and inviting them to correct their invalid input, then that's OK IMO. Whether the subsequent moves are to mimic TBD' `fit?` strategy of reverting to the original vertices, or what @ggartside is suggesting, etc. matters less. Good idea to closely follow E+ behaviour when faced with bad Frame & Divider input (e.g. overlaps).

I otherwise agree with @ggartside 's short list of gross/net sub/surface areas. From where I'm sitting, doesn't seem to matter whether subsurface `netArea` includes dividers or not (as I don't see any practical use for subsurface `netArea` ...). So I'm easy. As suggested by @macumber, good idea to follow E+ in this case (and I agree with adding `frameArea` and `dividerArea` methods to subsurfaces, as per E+). Thanks.
