### ISSUE TITLE
Add support of HeatPump:PlantLoop:EIR:Heating to model air-to-water heat pump

### ISSUE THREAD

**Issue by DmitryIvanov-org** [NREL/OpenStudio#4362]
https://bigladdersoftware.com/epx/docs/9-3/input-output-reference/group-plant-equipment.html#plhp_eir

**Comment by joseph-robertson** [comment]
`HeatPumpPlantLoopEIRHeating` and `HeatPumpPlantLoopEIRCooling` would be `WaterToWaterComponent`s similar to the already wrapped `HeatPumpWaterToWaterEquationFitHeating` and `HeatPumpWaterToWaterEquationFitCooling` objects?

**Comment by DmitryIvanov-org** [comment]
Hi Joe. Thanks for your comment. I'm not sure what you exactly meant by being similar objects, but if it's about using WaterToWater objects to simulate air-to-water heat pump - it is very trick at best. There is more info on this:
https://unmethours.com/question/53494/how-can-i-model-an-air-cooled-heat-pump-in-openstudio/
