### ISSUE TITLE
Availability Schedule for DaylightingControl

### ISSUE THREAD

**Issue by lymereJ** [NREL/OpenStudio#4364]
Enhancement Request
--------------
Add an availability schedule field for the `DaylightingControl` object.

## Detailed Description
The `DaylightingControl` object in OpenStudio doesn't appear to have an availability schedule field, but the EnergyPlus object does. An example for this field would be to turn off daylighting controls during sizing period/design day simulations. While this can be done using an EnergyPlus measures, it would be really useful to implement it when measures are not an option (e.g. `openstudio-standards`).

**Comment by joseph-robertson** [comment]
Should setters/getters for daylighting controls availability schedule be attached to `DaylightingControl` or to `ThermalZone`?

If they were attached to `DaylightingControl`, there would be separate primary and secondary availability schedules. What would the logic be for forward translating these into a single availability schedule on `DaylightingControls` in EnergyPlus?

If they were attached to `ThermalZone`, they'd apply to both the primary and secondary daylighting controls. What do we call the setters/getters? Something like `daylightingControlsAvailabilitySchedule`, `setDaylightingControlsAvailabilitySchedule`, etc?

**Comment by lymereJ** [comment]
Great questions! I feel like having them attached to `DaylightingControl` is the most logical approach, however, I'm not sure what strategy should be implemented in the forward translator. EnergyPlus only uses one availability schedule per `Daylighting:Controls` object, I doubt that multiple of these objects can be assigned to a same zone. So perhaps `ThermalZone` is a better choice. The setter/getter you propose seem good.
