### ISSUE TITLE
ThermalZone:addEquipment deprecated in the Ruby bindings, yet available in C++ & online SDK

### ISSUE THREAD

**Issue by rd2** [NREL/OpenStudio#4367]
Issue overview
--------------
Mismatch between what the C++ code and online SDK are describing vs what's offered by the Ruby bindings.

## Current Behavior
The _ThermalZone_ method _addEquipment_ is deprecated in the Ruby bindings, yet the online SDK suggests it can be relied on - see _Steps to Reproduce_.

## Expected Behavior
Methods described online (SDK) should reflect what's offered in the Ruby bindings.

## Steps to Reproduce
_zone.addEquipment(object)_ will generate a **NoMethodError** on a newly instantiated _ThermalZone_.

## Possible Solution
Delete _addEquipment_ method from C++ code (ThermalZone class); delete from online SDK.

### Environment
Observed for recent SDK versions (v3.2, v3.1). Not the case for older vintages like v2.9.1.

### Context
UnmetHours [discussion](https://unmethours.com/question/55697/how-to-get-all-os-objects-and-their-members/) on compiling lists of available SDK classes, methods, members, etc. The method _addEquipment_ was noted as no longer being part of the Ruby bindings, while remaining part of the online SDK and C++ code (thanks @macumber). Granted, there are inline [notes](https://github.com/NREL/OpenStudio/blob/3bfe89f6c441d1e61e50b8e94e92e7218b4555a0/src/model/ThermalZone.hpp#L371) in the C++ code to the effect that this may change in the future (i.e. deleting the method?), so the development team does seem to be transitioning towards its deletion (good). But in the meantime it remains confusing for users if the online SDK suggests that it's still OK to rely on. This may be the case as well for other methods targeted for deletion.

**Comment by jmarrec** [comment]
This is done **on purpose**. This was a major source of confusion and leading to problems, as this method will NOT do additional logic like it should.

https://github.com/NREL/OpenStudio/blob/dd40326c4deeb34e3af2641535ffa4f65149db2f/src/model/ModelHVAC.i#L15-L16

Please see #3758 and #2920 for why we did this.

**Comment by rd2** [comment]
Merci @jmarrec for linking previously-raised issues (I had searched for "addEquipment" in _open_ issues, not _closed_ ones - my bad).

**Comment by tijcolem** [comment]
I think with @jmarrec comment we can safely close this as this was done on purpose. If there are other examples that have a mismatch between the Ruby bindings vs SDK, we can reopen, but this thread was highlighting a specific method that was done intentionally.
