### ISSUE TITLE
Intersection issue found when using create bar

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#4372]
Issue overview
--------------
There is small identified error in pre/post intersection area, but that doesn't account for larger error in expected exterior perimeter reported. 

            "stdout" : "[openstudio.model.Surface] <1> Initial area of other surface 'Surface 316' 57.2551 does not equal post intersection area 57.1732\n[openstudio.model.Surface] <1> Initial area of surface 'Surface 326' 13.9355 does not equal post intersection area 13.8945\n[openstudio.model.Surface] <1> Initial area of surface 'Surface 338' 13.9355 does not equal post intersection area 13.8945\n",
            "step_errors" : 
            [
               "East/West walls don't have the expected area (actual 5,492.4418 ft^2, target 3,661.6279 ft^2)"
            ],

## Current Behavior
That error is called here
https://github.com/NREL/openstudio-extension-gem/blob/develop/lib/openstudio/extension/core/os_lib_model_generation.rb#L2543

## Expected Behavior
Expected values should match and meaasure and method shoudl run without an error

## Steps to Reproduce
I'm going to add a test on branch of extension gem with these inputs and should be able to replicate it

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### Context
Is blocking URBANopt project until I figure out work arond

**Comment by ggartside** [comment]
@DavidGoldwasser Did you ever add a test on a branch of extension gems to reproduce this issue? I'm looking for something I can run in open studio to reproduce this issue before I dig any deeper

**Comment by DavidGoldwasser** [comment]
@ggartside I think this is the branch of extension gem I was working on. I'll test it out tomorrow or Monday with the same installer as https://github.com/NREL/OpenStudio/pull/4431

**Comment by DavidGoldwasser** [comment]
@ggartside sorry for my delay, this issue in extension gem explains things in more detail. I just ran test with version of OpenStudio used from the intersection PR and I'm still seeing this behavior.
https://github.com/NREL/openstudio-extension-gem/issues/128

I run the test by doing `bundle exec rake spec` in the extension gem after first doing `bundle install`. This is on the `intersext_tests_072021` branch and not develop. I have a meeting in a few minutes but I can email you 1 or 2 OSM files that are the output of the test, which you can use to test it without having to checkout the extension gem.
