### ISSUE TITLE
Unable to use EnergyPlusForwardTranslator and EnergyPlusReverseTranslator: OpenStudioEnergyPlusPINVOKE

### ISSUE THREAD

**Issue by MingboPeng** [NREL/OpenStudio#4377]
Issue overview
--------------

I am using C# bindings on Windows, and found both EnergyPlusForwardTranslator and EnergyPlusReverseTranslator throw OpenStudioEnergyPlusPINVOKE exception.

## Current Behavior

Currently, creating Model and VersionTranslator works excepted, but EnergyPlusForwardTranslator and EnergyPlusReverseTranslator doesn't work.

## Steps to Reproduce

1. install from nuget
2. use following code to test.
```C#
            var m = new OpenStudio.Model();
            var t1 = new OpenStudio.VersionTranslator();
            var t2 = new OpenStudio.EnergyPlusForwardTranslator();
            var t3 = new OpenStudio.EnergyPlusReverseTranslator();
```

## Details
![image](https://user-images.githubusercontent.com/9031066/126073199-0d187a4a-d59a-4dff-bf2c-3f0697dbf6c5.png)
### Context

I am trying to import constructions and materials from idf to osm with EnergyPlusReverseTranslator, but found this error.

cc @jmarrec

**Comment by jmarrec** [comment]
@MingboPeng Did it work before? If so do you have an idea of when it stopped working?

**Comment by MingboPeng** [comment]
Hi @jmarrec, I haven't tested these EnergyPlusTranslators before, this is my first time using it, and found this issue.

**Comment by jmarrec** [comment]
Which version are you using currently please?

**Comment by MingboPeng** [comment]
I have tried the two newest versions from nuget: 3.2.1 and 3.2.0. I have also tested in the most updated version that was compiled from https://github.com/NREL/OpenStudio/pull/4287#issuecomment-882072242

**Comment by jmarrec** [comment]
@MingboPeng Do you correctly have all **four** DLLs into your local build/ folder? `openstudio_translators_csharp.dll` is the one that should contain the E+ translators

**Comment by MingboPeng** [comment]
Yes, it is in the build folder: 
![image](https://user-images.githubusercontent.com/9031066/127004659-fe38d380-9885-41e2-8773-9ebff5ee8846.png)

**Comment by jmarrec** [comment]
I built locally on Ubuntu using dotnet (apparently 3.1.411 was isntalled on my system), and added a test in https://github.com/NREL/OpenStudio/commit/8a007e193265661963782b0b0632ecd732c2cab0. It works... I'm now trying windows...

**Comment by arif-hanif** [comment]
@MingboPeng this is for .net framework right?

**Comment by MingboPeng** [comment]
Thanks @jmarrec, please let me know if you could recreate the issue.

@arif-hanif Yes, I tested with .Net Framework.

**Comment by jmarrec** [comment]
I created a Console App, targeting .NET Framework 4.7.2

![image](https://user-images.githubusercontent.com/5479063/127028594-3e67476d-7a8f-4f30-b609-8b7f53050a5d.png)

**Program.cs**:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using OpenStudio;
namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var m = new OpenStudio.Model();
            Console.WriteLine(m);
            OpenStudio.EnergyPlusForwardTranslator ft = new OpenStudio.EnergyPlusForwardTranslator();
            var w = ft.translateModel(m);
        }
    }
}
```

No error...

**Comment by jmarrec** [comment]
I did do something else: C:\Users\julien\source\repos\ConsoleApp1\packages\OpenStudio.3.2.1\build\x64

Copied all four DLLs here to  C:\Users\julien\source\repos\ConsoleApp1\ConsoleApp1\bin\Release

**Comment by jmarrec** [comment]
which version of .NET framework are you using @MingboPeng ?

**Comment by jmarrec** [comment]
Or if I just explicitly put x64 for the target instead of AnyCPU, then it does pull all the DLLs nicely for me and it works.

**Comment by jmarrec** [comment]
Here's a gif video of A to Z testing showing how it all works nicely with .NET 4.8 Framework and the nuget 3.2.1. @MingboPeng @arif-hanif 

What am I missing?

![4377_testing](https://user-images.githubusercontent.com/5479063/127033707-88082070-d40c-43b1-849c-9419c42cf0f5.gif)

**Comment by MingboPeng** [comment]
Thanks @jmarrec , I will try to replicate what you did here to see if I could get it work.

It's weird that I have been using the same AnyCPU all the time, and it always works with x64 by default. And it works fine with new OpenStudio.Model(), but just not the EnergyPlusTranslator. 

I will look into it again and will keep you updated. 

For nuget packages that doesn't copy all dlls to build folder issue, I have fixed in this PR #4287.

**Comment by jmarrec** [comment]
Without your PR it does copy the dlls just fine provided you do use x86 or x64 specifically. That's what the GIF shows (and that I learned today...)

**Comment by jmarrec** [comment]
@arif-hanif @MingboPeng could one of you test with the steps I provided in the GIF please? Thanks!

**Comment by MingboPeng** [comment]
Hi @jmarrec, thanks so much for looking into this. I am able to get it working with exactly what you did in GIF. Changing AnyCPU to x64 does the trick. But one thing is weird that I have no problem with AnyCPU when using objects in OpenStudio.Model. Not sure how it is working differently with EnergyPlusTranslators.

I am closing this issue now, and thanks again.

**Comment by MingboPeng** [comment]
One note I want to add here is: changing platform to x64 also doesn't copy all dlls to build folder, but it could reference them correct.

**Comment by jmarrec** [comment]
> One note I want to add here is: changing platform to x64 also doesn't copy all dlls to build folder, but it could reference them correct.

In my GIF above I deleted the bin/ directory before building then I see all 5 openstudio DLLs. Are you not seeing that?
