### ISSUE TITLE
Completing SDK support of Tubular Daylighting Devices (TDDs)

### ISSUE THREAD

**Issue by rd2** [NREL/OpenStudio#4380]
Enhancement Request
--------------
OpenStudio SDK doesn't (fully) support Tubular Daylighting Devices (TDDs), as supported by [EnergyPlus](https://bigladdersoftware.com/epx/docs/9-5/input-output-reference/group-daylighting.html#daylightingdevicetubular).

## Detailed Description
OpenStudio is able to minimally set/get related subsurface types:
```
types = OpenStudio::Model::SubSurface.validSubSurfaceTypeValues
expect(types.is_a?(Array)).to be(true)
expect(types.include?("TubularDaylightDome")).to be(true)
expect(types.include?("TubularDaylightDiffuser")).to be(true)
```

OpenStudio-launched EnergyPlus simulations will proceed without warning(s), despite having incomplete TDD setups i.e. dome > tube > diffuser. Results reflect e.g. an expected increase in heating energy (Climate Zone 7), due to the poor(er) performance of a TDD dome. Note that the [effective RSi](https://bigladdersoftware.com/epx/docs/9-5/engineering-reference/daylighting-devices.html#conductiveconvective-gains) of the (missing) tube will be of course ignored. So one could consider this as a _partial_ implementation.

A more complete SDK implementation of TDDs is requested. The mapping to EnergyPlus inputs appear to be somewhat straightforward.

Past UnmetHours [discussion](https://unmethours.com/question/2993/how-to-model-tubular-daylight-devices-in-os/).

**Comment by joseph-robertson** [comment]
Object `DaylightingDevice:Shelf` is already wrapped. The following are not wrapped yet:
* `DaylightingDevice:Tubular`
* `DaylightingDevice:LightWell`

@rd2 Are you requesting that `DaylightingDevice:Tubular` be wrapped in OpenStudio?

**Comment by rd2** [comment]
@joseph-robertson : Yes, exactly. Basically a wrapper around [this](https://bigladdersoftware.com/epx/docs/9-5/input-output-reference/group-daylighting.html#daylightingdevicetubular). Thanks.
