### ISSUE TITLE
runner.getOptionalBoolArgumentValue method is missing

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4390]
Enhancement Request
--------------
You can create optional measure arguments of type double, integer, string, path, or boolean; every one of them has an accompanying runner.getOptionalFooArgumentValue method _except for boolean_. This is weird considering there is an `OpenStudio::OptionalBool`.

I'm having to use a disgusting workaround:

```ruby
def arguments(model)
  args = OpenStudio::Measure::OSArgumentVector.new

  arg = OpenStudio::Measure::OSArgument::makeBoolArgument('heat_pump_is_ducted', false)
  arg.setDisplayName('Heat Pump: Is Ducted')
  args << arg

  return args
end

def run(model, runner, user_arguments)

  ...

  # Disgusting workaround here:
  heat_pump_is_ducted = runner.getOptionalStringArgumentValue('heat_pump_is_ducted', user_arguments)
  if heat_pump_is_ducted.is_initialized
    if heat_pump_is_ducted.get.downcase == 'true'
      heat_pump_is_ducted= OpenStudio::OptionalBool.new(true)
    elsif heat_pump_is_ducted.get.downcase == 'false'
      heat_pump_is_ducted= OpenStudio::OptionalBool.new(false)
    else
      fail 'Unexpected value'
    end
  end

end
```

It would be great if OpenStudio could formally add a `runner.getOptionalBoolArgumentValue` method to facilitate.

**Comment by jmarrec** [comment]
@shorowit can you give me one good example where an OptionalBool makes sense? I mean where you cannot default it to some value in the arguments already, in which case it no longer has to be an OptionalBool but just a Bool.

Second, in such as case, wouldn't it be better to just make it a Choice field "Yes", "No", "N/A" or something?

Basically the optional bool makes zero sense to me, it's a poor man's tri-state bool.

----

Answering anyways:

The C++ code would be this

```c++
  boost::optional<double> OSRunner::getOptionalBoolArgumentValue(const std::string& argument_name,
                                                                   const std::map<std::string, OSArgument>& user_arguments) {
    auto it = user_arguments.find(argument_name);
    if (it != user_arguments.end()) {
      if (it->second.hasValue()) {
        return it->second.valueAsBool();
      } else if (it->second.hasDefaultValue()) {
        return it->second.defaultValueAsBool();
      }
    }

    return boost::none;
  }
```

That means that you can do a less "disgusting" workaround by doing **exactly** the same in ruby

```ruby
heat_pump_is_ducted = OpenStudio::OptionalBool.new
if user_arguments.has_key?("heat_pump_is_ducted")
  arg = user_arguments["heat_pump_is_ducted"]
  if arg.hasValue()
    heat_pump_is_ducted .set(arg.valueAsBool())
  end
end
```


Test code showing it works

```ruby
tests = [
 [nil, nil],
 [true, true],
 [false, false],
]

tests.each do |val, result|

  args = OpenStudio::Measure::OSArgumentVector.new
  arg = OpenStudio::Measure::OSArgument::makeBoolArgument('heat_pump_is_ducted', false)
  if !val.nil?
    arg.setValue(val)
  end
  args << arg

  user_arguments = OpenStudio::Measure.convertOSArgumentVectorToMap(args)
  heat_pump_is_ducted = OpenStudio::OptionalBool.new
  if user_arguments.has_key?("heat_pump_is_ducted")
    arg = user_arguments["heat_pump_is_ducted"]
    if arg.hasValue()
      heat_pump_is_ducted.set(arg.valueAsBool())
    end
  end

  raise if heat_pump_is_ducted.class != OpenStudio::OptionalBool

  if result.nil?
    raise if !heat_pump_is_ducted.empty?
  else
    raise if heat_pump_is_ducted.get != result
  end
end
```

**Comment by shorowit** [comment]
We cannot set a default value for this argument because the default is not known at this point in the workflow. Based on the value (true, false, or omitted), we do three different things in our measure:
- true -> set an HPXML element w/ true value
- false -> set an HPXML element w/ false value
- omitted -> don't set the HPXML element (which results in the value being defaulted downstream by another OS measure with nuanced logic)

You're right that we could switch to a choice element, but that seems less than ideal because then we will have a measure with required boolean arguments using true/false/omitted and optional boolean arguments using yes/no/na. That is confusing and more likely to introduce bugs/errors in both using the measure and writing the measure business code.

**Comment by jmarrec** [comment]
@shorowit Gotcha, thanks for the explanation. I'll add the method
