### ISSUE TITLE
OpenStudio can't connect BIM Server

### ISSUE THREAD

**Issue by keleisi2001** [NREL/OpenStudio#4393]
I try so many times but OpenStudio still can't connect BIM Server. Maybe "address" or "post" has wrong? But my BIM Server is running smoothly.

![1](https://user-images.githubusercontent.com/55388367/128493648-a2cf074b-5e1f-48af-a1f6-d763e1601f9d.png)
![2](https://user-images.githubusercontent.com/55388367/128493645-5a38ef42-afaf-43cd-9206-792f73f516f5.png)
![3](https://user-images.githubusercontent.com/55388367/128493643-166fa94a-da5e-4183-88c8-960d2e57b573.png)
![4](https://user-images.githubusercontent.com/55388367/128493641-fbd31dbf-74a2-48e6-88d7-87f1ecab55ef.png)
![5](https://user-images.githubusercontent.com/55388367/128493638-a024b14b-f37b-47f3-a0da-3d89259d80b1.png)

**Comment by tijcolem** [comment]
This appears to be an OpenStudio Application related issue. @macumber This could be a local networking issue for this user or could be something with the BIM server itself.

**Comment by keleisi2001** [comment]
> This appears to be an OpenStudio Application related issue. @macumber This could be a local networking issue for this user or could be something with the BIM server itself.

Yeah. I still keep trying from time to time and asked the same question in the BIM Server section. It has not yet been resolved.

**Comment by macumber** [comment]
Let's move this to https://github.com/openstudiocoalition/OpenStudioApplication/issues/410
