### ISSUE TITLE
OpenStudio CLI crashes on unknown code page

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#4397]
Issue overview
--------------
User reported issue here: https://unmethours.com/question/58811/cannot-open-openstudio-software/

## Current Behavior
OpenStudio CLI crashes on unknown code page

## Expected Behavior
OpenStudio CLI should not crash

## Steps to Reproduce
Open cmd prompt on Windows
1. `chcp 720`
2. `c:\openstudio-3.2.1\bin\openstudio.exe`

**Comment by jmarrec** [comment]
https://en.wikipedia.org/wiki/Code_page_720

> Code page 720 (CCSID 720)[1] (also known as CP 720, IBM 00720, and OEM 720) is a code page used under DOS to write Arabic in Egypt, Iraq, Jordan, Saudi Arabia, and Syria.[2] The Windows (ANSI) code page for Arabic is Windows-1256.[3] 

I can reproduce locally. About to try in debug mode

**Comment by jmarrec** [comment]
I think these are typos, should be `.so` not `.o`

https://github.com/NREL/OpenStudio/blob/3dd094d4f287d3b3ef04fd20543e9299d40ab6df/src/cli/main.cpp#L341-L372

I also found why we never managed to build ruby on MSVC the first time and always had to do `nmake /k` and `nmake /k install-nodocs`.

```diff
diff --git a/win32/Makefile.sub b/win32/Makefile.sub
index 326bd7f..e04ccb3 100644
--- a/win32/Makefile.sub
+++ b/win32/Makefile.sub
@@ -991,6 +991,7 @@ s,@SOEXT@,dll,;t t
 s,@DLEXT@,so,;t t
 s,@LIBEXT@,lib,;t t
 s,@STRIP@,$(STRIP),;t t
+s,@ENCSTATIC@,$(ENCSTATIC),;t t
 s,@EXTSTATIC@,$(EXTSTATIC),;t t
 s,@setup@,Setup,;t t
 s,@MINIRUBY@,$(MINIRUBY),;t t
```

**Comment by jmarrec** [comment]
BUT, as usual, this is a freaking nightmare and I still haven't found why it isn't capable of loading the transcoder from Windows 1256 to UTF-8

**Comment by jmarrec** [comment]
I got the conan-openstudio-ruby ruby.exe to correctly load the CP720 encoding. But the CLI is still resisting me...

**Comment by jmarrec** [comment]
Ok I found the root. IMB720 / CP720 is not supported by Ruby until 3.0. It was added by this commit: https://github.com/ruby/ruby/commit/d403591b34e204a5937241025c62c877e579fbaf

I suggest using `chcp 65001` for UTF-8, or `chcp 1256` (Windows 1256) if you want to retain an arabic encoding.

**Comment by jmarrec** [comment]
I have a PR on conan-openstudio-ruby that would added IBM720/CP720 to ruby 2.7.2, but not sure whether we'll go with it (since ruby itself doesn't add it until 3.0): https://github.com/NREL/conan-openstudio-ruby/pull/34
