### ISSUE TITLE
Inspector chops off the edit fields/drop down boxes (Bugzilla #373)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#44]
On 2011-11-28 15:34:29, @macumber wrote:

> OpenStudio Inspector. The inspector chops off the edit fields/drop down boxes of the inspector.

On 2012-01-13 15:22:01, @DavidGoldwasser wrote:

> Updated out of date Milestone Targer

**Comment by DavidGoldwasser** [comment]
Issue with SketchUp dialog box.
