### ISSUE TITLE
Add Sql helper methods to retrieve U-factors, SHGC, or VT for glazing systems

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#4403]
Enhancement Request
--------------
Add Sql helper methods to retrieve U-factors, SHGC, or VT for glazing systems after https://github.com/NREL/EnergyPlus/pull/8740 is merged

**Comment by tijcolem** [comment]
@joseph-robertson  Looks like NREL/EnergyPlus#8740 has been merged so we can look into this when time permits.
