### ISSUE TITLE
ForwardTranslator::setExcludeLCCObjects doesn't exclude all LCC objects

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4404]
Issue overview
--------------
Using `ft.setExcludeLCCObjects(true)` excludes most all LCC objects, but not the `LifeCycleCost:NonrecurringCost` object. This is annoying, because it results in an EnergyPlus warning:

```
   ************* There are 1 unused objects in input.
   ************* Use Output:Diagnostics,DisplayUnusedObjects; to see them.
```

If I use the Output:Diagnostics,DisplayUnusedObjects object, I get:

```
   ** Warning ** The following lines are "Unused Objects".  These objects are in the input
   **   ~~~   **  file but are never obtained by the simulation and therefore are NOT used.
   **   ~~~   **  Only the first unused named object of an object class is shown.  Use Output:Diagnostics,DisplayAllWarnings; to see all.
   **   ~~~   **  See InputOutputReference document for more details.
   ************* Object=LifeCycleCost:NonrecurringCost=Default Cost
```

I looked briefly at the source code and it seems to be cause by [these lines](https://github.com/NREL/OpenStudio/blob/1b8f0d3549d67f5e461677439ee85c5d6f6cad0c/src/energyplus/ForwardTranslator.cpp#L4201-L4219). Perhaps this code should be wrapped in an if statement like [here](https://github.com/NREL/OpenStudio/blob/1b8f0d3549d67f5e461677439ee85c5d6f6cad0c/src/energyplus/ForwardTranslator.cpp#L423)?

The context here is that I'm trying to write tests around my software to ensure that there are no unused objects reported by EnergyPlus (which may indicate a bug), but am unable to do so because of this.

## Steps to Reproduce
1. Clone the [OpenStudio-HPXML repo](https://github.com/NREL/OpenStudio-HPXML).
2. Run a sample file using the run_simulation.rb script (which uses setExcludeLCCObjects(true)): `openstudio workflow/run_simulation.rb -x workflow/sample_files/base.xml -o test --debug`
3. Note the unused object warning in test/run/eplusout.err.

**Comment by shorowit** [comment]
I'm able to workaround this issue by using:

```
forward_translator = OpenStudio::EnergyPlus::ForwardTranslator.new
forward_translator.setExcludeLCCObjects(true)
workspace = forward_translator.translateModel(model)

# Prevent E+ unused object warning:
workspace.getObjectByTypeAndName('LifeCycleCost:NonrecurringCost'.to_IddObjectType, 'Default Cost').get.remove
```

**Comment by jmarrec** [comment]
I'll fix it, and use the opportunity to properly test for all these Ft options
