### ISSUE TITLE
E+ 9.6.0: Wrap AirflowNetwork:MultiZone:SpecifiedFlowRate

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio#4410]
Enhancement Request
--------------
Update/add:
- [ ] Convenience methods on:
  - [x] Surface and SubSurface?
  - [ ] Flow and infiltration objects?
  - [ ] ?
- [x] FT test
- [x] Convenience method for valid unit keys
- [ ] Alternative ctor for value/units?

**Comment by shorowit** [comment]
I would like to see this wrapped as we would like to take advantage of it at some point.
