### ISSUE TITLE
Very weird and worrisome floor geometry on floor js json import

### ISSUE THREAD

**Issue by antonszilasi** [NREL/OpenStudio#4426]
Issue overview
--------------
I am using the following code to import this floor js json into OpenStudio

```
         floorplan = OpenStudio::FloorplanJS::load(floor_js_json_data)
          if floorplan.empty?
            raise "Cannot load floorplan from '#{floorplan_path}'."
          end

          scene = floorplan.get.toThreeScene(true)

          rt = OpenStudio::Model::ThreeJSReverseTranslator.new

          model = rt.modelFromThreeJS(scene)

```

Upon inspection of the geometry I see this very troublesome intersection on the 2nd floor of the model, there actually appears to be a hole in the floor.

![image](https://user-images.githubusercontent.com/8773483/131448934-628c10c8-67f4-430b-80ac-56cb74fa007b.png)

I have uploaded the floor js json here: https://drive.google.com/file/d/1JStrJo8jRh-9KKHi2mYglUHlExhhLBSr/view?usp=sharing

### Environment

OpenStudio 3.2.0

**Comment by tijcolem** [comment]
I tested this with OpenStudio v3.4.1-alpha and loaded this in the OpenStudioApplication 1.4.0 and I am not seeing any problems regarding the observed hole in the floor. We can reopen if needed but I don't think this is an issue so I'm going to close. 

Floorspace Layout

![Screen Shot 2022-08-25 at 4 50 26 PM](https://user-images.githubusercontent.com/7087120/186933122-e15df77f-88a7-4aed-baef-65f11d88fa06.png)

OpenStudio Application 3D model view
![Screen Shot 2022-08-25 at 5 05 55 PM](https://user-images.githubusercontent.com/7087120/186933342-5a1e2c84-f765-4568-a54f-bbb52bf9a288.png)

**Comment by antonszilasi** [comment]
@tijcolem before you close did you check all the floors?
