### ISSUE TITLE
Add a Measure to make a construction fit four Windows

### ISSUE THREAD

**Issue by zhirgb** [NREL/OpenStudio#4429]
Enhancement Request
--------------

**Comment by zhirgb** [comment]
We can change the U, SHGC, and window-wall ratio of all four at the same time

**Comment by jmarrec** [comment]
Hello, I'm not sure I follow what you mean. I suggest you post a question with more details on https://unmethours.com asking how you can achieve what you are trying to do.

**Comment by zhirgb** [comment]
thank you ,i mean&nbsp; What if I want to change the window/wall ratio, window heat transfer coefficient, window solar heat gain coefficient, all four aspects of a construction at the same time? This seems to be impossible in OS.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NREL/OpenStudio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月1日(星期五) 下午4:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NREL/OpenStudio] Add a Measure to make a construction fit four Windows (#4429)





 
Closed #4429.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
