### ISSUE TITLE
GbXML ReverseTranslator needs validation and/or better error handling

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#4441]
Enhancement Request
--------------

See https://github.com/NREL/OpenStudio/pull/4440#discussion_r712822703

Really we need error handling in gbxml... There is currently no validation against the gbXML schema happening and there is very little checking that is done manually (like ensuring that required values/attributes are supplied, or checking that a YearSchedule references a weekScheduleIdRef you make sure it can be found).

## Detailed Description

I found this because a test I added was failing without any logging when I had a typo in a weekScheduleIdRef

```diff
  <Schedule type="Fraction" id="Simple_Schedule">
    <YearSchedule id="Simple_Schedule_YearSchedule">
      <BeginDate>2017-01-01</BeginDate>
      <EndDate>2017-12-31</EndDate>
-      <WeekScheduleId weekScheduleIdRef="SOMETHING_THAT_CANT_BE_FOUND" />
    </YearSchedule>
    [ .... ]
```

Another issue might be when you pass Schedule with zero YearSchedule children. Or if YearSchedule doesn't have a BeginDate children. etc etc.

https://gbxml.org/schema/6-01/GreenBuildingXML_Ver6.01.xsd#element_YearSchedule

## Possible Implementation

Schema validation against the gxbml XSD ([here](https://gbxml.org/schema/6-01/GreenBuildingXML_Ver6.01.xsd)would be an option. `pugixml` doesn't support that, so that would require using a different library for xml such as xeres-c (which is on conan-center-index: https://github.com/conan-io/conan-center-index/tree/master/recipes/xerces-c).

Another option is to manually enforce that required values and attributes are there, and handle errors appropriately (at least logging to inform the user).

**Comment by jmarrec** [comment]
These two are wrong per 6.01 https://github.com/NREL/OpenStudio/blob/05c754adfe8ae0982c515a96bb24f9ccfc497500/src/gbxml/MapSchedules.cpp#L85

and https://github.com/NREL/OpenStudio/blob/05c754adfe8ae0982c515a96bb24f9ccfc497500/src/gbxml/MapSchedules.cpp#L114

should be `scheduleType`. but `type` is correct for `Schedule` though (which is confusing)

https://www.gbxml.org/schema/6-01/GreenBuildingXML_Ver6.01.xsd#element_WeekSchedule

https://www.gbxml.org/schema/6-01/GreenBuildingXML_Ver6.01.xsd#element_DaySchedule

**Comment by jmarrec** [comment]
Example "manual" error handling in https://github.com/NREL/OpenStudio/commit/2dfa66b8faa1fc047b9aed7ac9d2f2875f333cf5

**Comment by shorowit** [comment]
If XSD validation is added to OS, could it be done in such a way that it’s exposed in the SDK? Maybe Schematron validation too?

I have wanted this for a long time for our HPXML work. The Oga library we’re using is great, but it doesn’t support XSD or Schemtron validation.

**Comment by kbenne** [comment]
@jmarrec my understanding is that the momentum is toward bringing in Xerces to support validation. I know that Xerces is popular and capable, and I have confidence that you did a wide search for other library options. But, some folks on the team mentioned [libxml2](https://github.com/GNOME/libxml2) and have used it through Ruby/Python bindings and really liked it. Can you think of a reason to choose Xerces over libxml2?

**Comment by shorowit** [comment]
I would _love_ a solution that supports Schematron, which [libxml2 appears to support](https://github.com/GNOME/libxml2/blob/master/schematron.c) but not xerces.

**Comment by shorowit** [comment]
For what it's worth, I did find [this document](https://docs.google.com/document/d/1HDZTGT7jXsQUcm5OwvLiI4T7GsPFVriVLZhAyDszDe0/edit#heading=h.etvgjhllf2du), which described why pugixml was chosen in the past (instead of xerces or libxml2).

**Comment by kbenne** [comment]
I love pugixml. I don't think we will likely remove it as we already went through one conversation from QXML to pugi, and doing it again would be a lot of work and unnecessary. I suggest we continue encouraging pugi for parsing / xml manipulation needs, but we obviously need one of these other libraries for validation.

**Comment by kbenne** [comment]
libxml2 is C based, but if we keep the application of it focused on validation, we can put a small C++ wrapper around it to hide the pointers.

**Comment by jmarrec** [comment]
> @jmarrec my understanding is that the momentum is toward bringing in Xerces to support validation. I know that Xerces is popular and capable, and I have confidence that you did a wide search for other library options. But, some folks on the team mentioned [libxml2](https://github.com/GNOME/libxml2) and have used it through Ruby/Python bindings and really liked it. Can you think of a reason to choose Xerces over libxml2?

Libxml2 is C. Aside from that no. I don't really care which one we choose. Both are available for conan. Xerces does feel like C-ish as well (start / stop methods, takes const char pointers etc)

Also I do think like you that we should keep pugixml in place, just do the validation with another one, instead just using one lib to do both.

**Comment by jmarrec** [comment]
@kbenne There's something that makes me uneasy about libxml2, is that it doesn't seem to be truly thread safe. It's possible to use it with multiple threads though if you're careful. It's also not like we necesarilly need thread safety here, but still.

https://gnome.pages.gitlab.gnome.org/libxml2/devhelp/libxml2-parser.html#xmlCleanupParser
https://gitlab.gnome.org/GNOME/libxml2/-/wikis/Thread-safety

Anyways, we need to settle on a lib to use. @joseph-robertson has already started implementation with xerces-C in #4578, so if you insist on a library change it should happen now rather than when it's finished and polished. Did you guys discuss it on Friday maybe?

**Comment by joseph-robertson** [comment]
[Here](https://github.com/libxmlplusplus/libxmlplusplus/blob/b49f738e8c97863f37772895e7582c81ad5b276c/tools/build_scripts/tutorial-custom-cmd.py#L78-L84) is an additional note on using libxmlplusplus c++ wrapper for schematron.

**Comment by shorowit** [comment]
Unfortunately it seems to be more complicated than I realized. lxml, which is a very popular python library for working with xml, uses libxml2 but not really for schematron support. From [here](https://lxml.de/2.3/validation.html):

> lxml also provides support for ISO-[Schematron](http://www.schematron.com/), based on the pure-XSLT [skeleton implementation](http://www.schematron.com/implementation.html) of Schematron:
> 
> There is also basic support for pre-ISO-Schematron through the libxml2 Schematron features. However, this does not currently support error reporting in the validation phase due to insufficiencies in the implementation as of libxml2 2.6.30.

So it sounds like libxml2 support for Schematron is pretty outdated and poor. No idea if it will work well for us.

**Comment by jmarrec** [comment]
@shorowit So this may be misleading. In my search of an example of using libxml2 to do schematron validation, the **only** example I could find was a Cython extension... for `lxml`. https://github.com/lxml/lxml/blob/master/src/lxml/schematron.pxi

I'm trying to make a MCVE in C right now, to see if it would work or not.

**Comment by jmarrec** [comment]
I have a shitty MCVE implementation at https://github.com/jmarrec/TestCpp-xml-schematron

libxml2 uses a too old schematron. So I do the same as what `python`'s `lxml` module does: I convert the schematron file to an XSLT stylesheet and apply that via `libxslt` (which is based on `libxml2`) to get the validation errors. Those do not include line numbers where the errors occurs though (neither does `lxml` as far as I can tell)

**Comment by jmarrec** [comment]
FYI, https://github.com/vslavik/xmlwrapp does include both libxml and libxslt, so it could be used to do this will less apparent pointers and co. The issue is making a conan recipe for it...
