### ISSUE TITLE
E+ 9.6.0: Add `autosizedOccupantDiversity` for SizingSystem

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio#4446]
Enhancement Request
--------------
Get autosized occupant diversity value from somewhere in the sql file.

**Comment by jmarrec** [comment]
I found it in the 62.1Summary report, and it's only there.

I'm slightly confused by the fact that the tabular reports for both heating and cooling, when the E+ IDD only has a single "Occupant Diversity" field. I reached out to the implementer of the E+ PR.

![image](https://user-images.githubusercontent.com/5479063/135296105-1c112987-eac9-48b4-b8db-d9019c46bb42.png)

**Comment by jmarrec** [comment]
I think both report the same value

https://github.com/NREL/EnergyPlus/blob/f420c06a69737dddcf4ba740ad855b45a03a8ef3/src/EnergyPlus/SizingManager.cc#L1594-L1595

https://github.com/NREL/EnergyPlus/blob/f420c06a69737dddcf4ba740ad855b45a03a8ef3/src/EnergyPlus/SizingManager.cc#L1679-L1680
