### ISSUE TITLE
Coil:UserDefined

### ISSUE THREAD

**Issue by TfedUD** [NREL/OpenStudio#4449]
Hello!  Would it be possible for the object Coil:UserDefined to be added into the OS SDK?
[I see that there is the fields](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-2.0.4-doc/utilities_idd/html/hierarchy.html#:~:text=openstudio%3A%3ACoil_UserDefinedFields,non-extensible%20fields), but it appears the OS object itself does not yet exist?

Thank you!

**Comment by brianlball** [comment]
https://github.com/NREL/OpenStudio/pull/4825

**Comment by joseph-robertson** [comment]
@brianlball Close this issue as completed?
