### ISSUE TITLE
ExternalFile should enforce proper extension for E+ 9.6.0

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#4451]
Enhancement Request
--------------

Reported by @shorowit  on https://github.com/NREL/OpenStudio/issues/4405#issuecomment-925325056

Since E+ 9.6.0 (due to PR https://github.com/NREL/EnergyPlus/pull/8996), ScheduleManager.cc checks the file extension.

## Detailed Description

https://github.com/NREL/EnergyPlus/blob/f420c06a69737dddcf4ba740ad855b45a03a8ef3/src/EnergyPlus/ScheduleManager.cc#L1678-L1697

https://github.com/NREL/EnergyPlus/blob/f420c06a69737dddcf4ba740ad855b45a03a8ef3/src/EnergyPlus/FileSystem.hh#L118-L119

Accepted extensions are therefore:

```
"epJSON", "json", "glhe", "cbor", "msgpack", "ubjson", "bson", "idf", "imf", "csv", "tsv", "txt", "eso", "mtr"
```

## Possible Implementation

**3 Options:**

1. Within the ExternalFile ctor, throw if a file is passed without these extensions. The only thing I dislike is that we're responsible for keeping the list of accepted extensions aligned with E+
2. Within the ExternalFile ctor, when we copy the file for internal use, strap a .csv extension onto it if none is provided
3. Do nothing and let E+ throw a fatal (and close this issue)

thoughts @shorowit @kbenne @tijcolem ?

**Comment by kbenne** [comment]
I like option 3.
