### ISSUE TITLE
OpenStudio::UnzipFile extractAllFiles is very slow

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4456]
Issue overview
--------------
The OpenStudio::UnzipFile extractAllFiles method is slower than it seems like it should be. It appears to get exponentially slower as the unzip operation progresses.

Unzip times for test below:

Test | Operation time
-- | --
Using 7zip manually on Windows | 0.5 minutes
Using OpenStudio::UnzipFile extractAllFiles on Windows | 24.5 minutes
Using OpenStudio::UnzipFile extractAllFiles on Linux (Windows Subsystem for Linux) | 6 minutes

cc @aspeake

## Current Behavior
Slow operation.

## Expected Behavior
Faster operation.

## Steps to Reproduce
1. Download this file: https://data.nrel.gov/system/files/156/BuildStock_TMY3_FIPS.zip

2. Create this unzip.rb script at the same location:
```ruby
require 'openstudio'

unzip_file = OpenStudio::UnzipFile.new('BuildStock_TMY3_FIPS.zip')
unzip_file.extractAllFiles(OpenStudio::toPath('zip_contents'))
```

3. Run `openstudio unzip.rb` and time the operation

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - OpenStudio 3.2.1

**Comment by jmarrec** [comment]
@shorowit is using the `rubyzip` gem an option?

I've done some benchmarking, and indeed OpenStudio's Unzip file is slow.

## Benchmarking methodology

I created a first zip 'TestZipSmaller' where I zipped all E+ weather_data/ files.
I created a second TestZipBigger by duplicating each weather_data file three times in root. Copied all 4 to another 'Subfolder'
Then I took everything from TestZipBigger and put that twice/thrice in subfolders for TestZipTwiceBigger / TestZipThriceBigger.

I then wrote this benchmark file to test : OpenStudio, rubyzip, and system (ubuntu 20.04).

bench_unzip.rb

```ruby
require 'openstudio'
require 'zip'
require 'fileutils'
require 'json'

def test_openstudio(test_case)
  destination = "OpenStudio-#{test_case}"
  path = "#{test_case}.zip"
  FileUtils.rm_rf(destination)
  FileUtils.mkdir_p(destination)

  t = Time.now
  uf = OpenStudio::UnzipFile.new(path)
  uf.extractAllFiles(destination
  t = Time.now - t

  puts "OpenStudio-#{test_case}: #{t}"
  return t
end

def test_rubyzip(test_case)
  destination = "Ruby-#{test_case}"
  path = "#{test_case}.zip"
  FileUtils.rm_rf(destination)
  FileUtils.mkdir_p(destination)

  t = Time.now
  Zip::File.open(path) do |zip_file|
    zip_file.each do |f|
      fpath = File.join(destination, f.name)
      zip_file.extract(f, fpath) unless File.exist?(fpath)
    end
  end
  t = Time.now - t

  puts "Ruby-#{test_case}: #{t}"
  return t
end

def test_system(test_case)

  destination = "System-#{test_case}"
  path = "#{test_case}.zip"
  FileUtils.rm_rf(destination)
  FileUtils.mkdir_p(destination)

  t = Time.now
  system("unzip #{path} -d #{destination} > /dev/null")
  t = Time.now - t

  puts "System-#{test_case}: #{t}"
  return t
end

timings = {}

tests = ['TestZipSmaller', 'TestZipBigger', 'TestZipTwiceBigger', 'TestZipThriceBigger']
tests.each do |test_case|
  timings[test_case] = {}
timings[test_case]['openstudio'] = test_openstudio(test_case)
timings[test_case]['rubyzip'] = test_rubyzip(test_case)
timings[test_case]['system'] = test_system(test_case)
end
```

**Comment by jmarrec** [comment]
Current is the current implementation except you can set the chunksize. Mod is the other where I've made changes.

Testing chunksize of 1024 to 65536.

```
------------------------------------------------------------------------
Benchmark                              Time             CPU   Iterations
------------------------------------------------------------------------
BM_Current/1024/iterations:5        9761 ms         9745 ms            5
BM_Current/2048/iterations:5        8831 ms         8827 ms            5
BM_Current/4096/iterations:5        8210 ms         8202 ms            5
BM_Current/8192/iterations:5        8074 ms         8063 ms            5
BM_Current/16384/iterations:5       7904 ms         7900 ms            5
BM_Current/32768/iterations:5       7784 ms         7770 ms            5
BM_Current/65536/iterations:5       7669 ms         7655 ms            5
BM_Mod/1024/iterations:5            5900 ms         5895 ms            5
BM_Mod/2048/iterations:5            5020 ms         5010 ms            5
BM_Mod/4096/iterations:5            4391 ms         4382 ms            5
BM_Mod/8192/iterations:5            4173 ms         4170 ms            5
BM_Mod/16384/iterations:5           4056 ms         4050 ms            5
BM_Mod/32768/iterations:5           3913 ms         3906 ms            5
BM_Mod/65536/iterations:5           3844 ms         3838 ms            5
```
