### ISSUE TITLE
`OS:Coil:Heating:DX:MultiSpeed:StageData` has no Name field but `OS:Coil:Cooling:DX:MultiSpeed:StageData` does

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#4483]
Issue overview
--------------

The OpenStudio.idd `OS:Coil:Heating:DX:MultiSpeed:StageData` has no Name field.

The `OS:Coil:Cooling:DX:MultiSpeed:StageData` does.

## Expected Behavior

Both should be similar.

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### Context

Moved from https://github.com/openstudiocoalition/OpenStudioApplication/issues/434

**Comment by joseph-robertson** [comment]
The issue here is that `CoilHeatingDXMultiSpeed`'s stages reference `ModelObjectLists` whereas `CoilCoolingDXMultiSpeed`'s stages are an extensible list.
