### ISSUE TITLE
ElectricLoadCenterDistribution FT has incomplete charge/discharge logic

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4495]
Issue overview
--------------
The ElectricLoadCenterDistribution forward translator is only writing the `designStorageControlChargePower` and `designStorageControlDischargePower` fields to the IDF when the storage operation scheme is "FacilityDemandLeveling" or "TrackChargeDischargeSchedules". But the fields can apply to other storage operation schemes. It appears to be due to a misreading of the [EnergyPlus documentation](https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-electric-load-center-generator.html#field-design-storage-control-charge-power):

> This field is the design maximum rate that electric power can be charged into storage, in Watts. **This field is used as an upper limit for most storage control operation schemes**. However for TrackChargeDischargeSchedules, this is the design value for how much power to use when charging and it is multipled by the power fraction schedule in the next field. Required field when using Storage Operation Schemes set to FacilityDemandLeveling or TrackChargeDischargeSchedules.

The developer probably just looked at the last sentence and didn't see the sentence that I bolded above.

### Environment

Some additional details about your environment for this issue (if relevant):
 - OpenStudio v3.3.0

**Comment by joseph-robertson** [comment]
I'm assuming this applies to `storageChargePowerFractionSchedule` and `storageDischargePowerFractionSchedule` as well?

**Comment by shorowit** [comment]
> I'm assuming this applies to `storageChargePowerFractionSchedule` and `storageDischargePowerFractionSchedule` as well?

I assume so too but don't know for sure. Try manually editing an IDF and see if it has an effect.
