### ISSUE TITLE
OpenStudio Toolbar does not correctly update tool bar button state. (Bugzilla #375)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#45]
On 2011-11-28 15:36:29, @macumber wrote:

> This seems to be an issue with SketchUp on the Mac only.

On 2012-01-13 15:22:01, @DavidGoldwasser wrote:

> Updated out of date Milestone Targer

On 2012-01-16 15:11:10, @DavidGoldwasser wrote:

> The only way to fix this is to wait for SketchUp to fix it or migrate the entire toolbar over to OpenStudio.

Keywords: ReleaseNotes

**Comment by DavidGoldwasser** [comment]
Mac specific SketchUp issue, we can' fix.
