### ISSUE TITLE
Bad nodes created for AirLoopHVAC:UnitarySystem with only cooling coil and supplemental heating coil

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#4509]
Issue overview
--------------
AirLoopHVAC:UnitarySystem containing just a cooling coil and supplemental heating coil will be translated with bad component node names. Specifically, the cooling coil outlet node name will not match the supplemental heating coil inlet node name. Only happens when Unitary System has no supply fan or heating coil.

## Steps to Reproduce
```
require 'openstudio'
include OpenStudio::Model

m = Model.new
c = CoilCoolingDXSingleSpeed.new(m)
hc = CoilHeatingDesuperheater.new(m)

unit = AirLoopHVACUnitarySystem.new(m)
unit.setCoolingCoil(c)
unit.setSupplementalHeatingCoil(hc)

ahu = AirLoopHVAC.new(m)
unit.addToNode(ahu.supplyOutletNode)

ft = OpenStudio::EnergyPlus::ForwardTranslator.new()
ws = ft.translateModel(m)

u = ws.getObjectsByType("AirLoopHVAC_UnitarySystem".to_IddObjectType).first
# unitary outlet node name
puts "Unitary Inlet Node: #{u.getString(5).to_s}"
puts "Unitary Outlet Node: #{u.getString(6).to_s}"
# cooling coil air outlet node name
cc = ws.getObjectsByType("Coil_Cooling_DX_SingleSpeed".to_IddObjectType).first
puts "Cooling Coil Inlet Node: #{cc.getString(7).to_s}"
puts "Cooling Coil Outlet Node: #{cc.getString(8).to_s}"
# supplemental heating coil air inlet node name
hcc = ws.getObjectsByType("Coil_Heating_Desuperheater".to_IddObjectType).first
puts "Supplemental Heating Inlet Node: #{hcc.getString(3).to_s}"
puts "Supplemental Heating Outlet Node: #{hcc.getString(4).to_s}"
```
=> 
```
Unitary Inlet Node: Node 1
Unitary Outlet Node: Node 2
Cooling Coil Inlet Node: Node 1
Cooling Coil Outlet Node: Node 2
Supplemental Heating Inlet Node: Air Loop HVAC Unitary System 1 Cooling Coil - Supplemental Coil Node
Supplemental Heating Outlet Node: Node 2
```

Cooling Coil Outlet Node should equal the Supplemental Heating Coil inlet node ("Air Loop HVAC Unitary System 1 Cooling Coil - Supplemental Coil Node").

## Possible Solution
Need an `if (_supplementalHeatingCoil)` block somewhere around here: https://github.com/NREL/OpenStudio/blob/72156a5eb35ef8f5f8274b3180136edfcb3fe575/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitarySystem.cpp#L683

Some additional details about your environment for this issue (if relevant):
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.3.0

### Context
Trying to have a Unitary System on an AirLoop (with fan outside the unitary system) that will control for humidity (Dehumidification Control Type = "CoolReheat") with a DX cooling and CoilHeatingDesuperheater coil as the required 'supplemental' reheat coil.

**Comment by joseph-robertson** [comment]
@eringold Note that in your example above, you have no supply fan OR heating coil set on the unitary system.

**Comment by eringold** [comment]
@joseph-robertson that's correct, and it seems to work fine in EnergyPlus (when the node names are correct). AFAIK EnergyPlus requires the 'supplemental' heating coil when the unitary system Dehumidification Control Type = CoolReheat, which was what I'm trying to do here.
