### ISSUE TITLE
Install OpenStudio with pre-installed energyplus package

### ISSUE THREAD

**Issue by frozznight** [NREL/OpenStudio#4517]
Issue overview
--------------

I want to build OpenStudio from source in a linux machine.
Since the linux distribution is not ubuntu, I built from source the Energyplus v.9.6 beforehand.
However during the ccmake configuration, I can not specify my preinstalled energyplus package.

Could you advice me how can I build OpenStudio with pre-installed energyplus package?

## Current Behavior

In the ccmake entry, I found the parameter:
ENERGYPLUS_IDD
I have set the above parameter to the existing idd files after Energyplus installation.
However, the cmake configurer are still trying to download and install Energyplus package based on my linux distribution.
Consequently, the cmake configuration throw some error of energyplus installation.

## Expected Behavior

Cmake configurer can reuse preinstalled energyplus package.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
     OpenSuse 42.3
 - Version of OpenStudio (if using an intermediate build, include SHA):
     v3.3 from repository tags

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio/blob/44a7660fbbb2da7353a9c26e16d6f75f22c74cbb/CMakeLists.txt#L188-L198

Checkout the EnergyPlus sha that correspond.

go to EnergyPlus build dir. `make`, then `make package`. You'll get a tar.gz out of it. copy the tar.gz to your OpenStudio build directory. Get the md5sum of the tar.gz as well.

```
cd /path/to/EnerygPlus-build-release
make -j$(nproc) && make -j$(nproc) package
ls *.tar.gz
md5sum *.tar.gz
cp *.tar.gz /path/to/OpenStudio-build-release
```

Edit OpenStudio/CMakeLists.txt so it gets your tar.gz. I'm not familiar with opensuse. But you may have to edit this: https://github.com/NREL/OpenStudio/blob/44a7660fbbb2da7353a9c26e16d6f75f22c74cbb/CMakeLists.txt#L546-L558

Maybe you don't. Anyways, LSB_RELEASE_VERSION_SHORT will be something like 15.03. LSB_RELEASE_ID_SHORT will be something like "Opensuse". Try these commands in your terminal (or look at the cmake configure output)

```bash
lsb_release -rs
lsb_release -is
```

You definitely want to change this: https://github.com/NREL/OpenStudio/blob/44a7660fbbb2da7353a9c26e16d6f75f22c74cbb/CMakeLists.txt#L576-L587

```cmake
  elseif(EXISTS "/etc/redhat-release")
    # TODO: There aren't any redhat releases anymore, see PR #3145 too
    set(ENERGYPLUS_EXPECTED_HASH DOES_NOT_EXIST_02ed618aab65bf46c96bf1faf2e1905b)
    set(ENERGYPLUS_PLATFORM "Redhat-x86_64")
  else()
    if (LSB_RELEASE_ID_SHORT MATCHES "Ubuntu")
      if(LSB_RELEASE_VERSION_SHORT MATCHES "20.04")
        set(ENERGYPLUS_EXPECTED_HASH 3a725c159b9196655156c0944173e8a3)
      else() # 18.04
        set(ENERGYPLUS_EXPECTED_HASH 4e48feacb8fd25cb51255fe5e1fe5f20)
      endif()
      set(ENERGYPLUS_PLATFORM "Linux${ENERGYPLUS_SYSTEM_VERSION}-x86_64")
    elseif(LSB_RELEASE_ID_SHORT MATCHES "OpenSuse")
      # Replace with the md5sum you calculated before
      set(ENERGYPLUS_EXPECTED_HASH 4e48feacb8fd25cb51255fe5e1fe5f20)
      # IMPORTANT: Rename the copied EnergyPlus tar.gz on disk to match this (I assume EnergyPlus may not have good/similar package name defaults here?)
      # eg: EnergyPlus-9.6.0-9208dde19d-Linux-Opensuse15.03-x86_64.tar.gz

      set(ENERGYPLUS_PLATFORM "Linux${ENERGYPLUS_SYSTEM_VERSION}-x86_64")
    else()
        message(FATAL_ERROR "Unknown LSB_RELEASE_ID_SHORT=${LSB_RELEASE_ID_SHORT}")
    endif

  endif()
```

**Comment by jmarrec** [comment]
I'm closing the issue because this isn't something we support, but please feel to keep posting here if you run into trouble.

**Comment by frozznight** [comment]
@jmarrec Thank you for your suggestions.
I will work it out from this.
