### ISSUE TITLE
Allow CoilCoolingDXVariableSpeed object to be used as cooling coil in AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass

### ISSUE THREAD

**Issue by TiejunWu** [NREL/OpenStudio#4529]
Currently there is a restriction that does not allow variable speed cooling coil to be used in the AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass object, EnergyPlus does not have such a restriction. I have tried this configuration directly in EnergyPlus and simulation ran through without problem. See the example [example attached](https://github.com/TiejunWu/EnergyPlus-IDF-Files/blob/master/ChangeoverBypassVAV_VariableSpeedCoolingCoil.idf).

**Comment by joseph-robertson** [comment]
I believe this was addressed in https://github.com/NREL/OpenStudio/pull/4346, and therefore introduced in OpenStudio v3.3.0.

Shown here: https://github.com/NREL/OpenStudio/pull/4346.

**Comment by joseph-robertson** [comment]
@TiejunWu Can you confirm that this is no longer an issue?

**Comment by DavidGoldwasser** [comment]
@TiejunWu have you had a chance to test this with OpenStudio 3.7?

**Comment by TiejunWu** [comment]
@DavidGoldwasser @joseph-robertson Sorry for the late response. I tested with OpenStudio 3,7 and confirmed that it allows variable speed coil to be specified as the cooling coil. Thanks!
