### ISSUE TITLE
Crash with OpenStudio.removeCollinear

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#4530]
Issue overview
--------------
Specific use model is getting crashing on this block of code. Still crashes when I isolate this to its own measure
https://github.com/BuildingPerformanceSimulation/openstudio-measures/blob/master/lib/measures/surface_matching_diagnostic/measure.rb#L128-L139

## Current Behavior
`Standard Output:

Standard Error:
/Users/dgoldwas/Documents/github/building_performance_simulation/openstudio-measures/lib/measures/surface_matching_diagnostic/measure.rb:131: [BUG] Segmentation fault at 0x0000000000000008
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]

-- Crash Report log information --------------------------------------------
See Crash Report log file under the one of following:
* ~/Library/Logs/DiagnosticReports
* /Library/Logs/DiagnosticReports
for more details.
Don't forget to include the above Crash Report log file in bug reports.

-- Control frame information -----------------------------------------------
c:0022 p:---- s:0203 e:000202 CFUNC :removeCollinear
c:0021 p:0016 s:0198 e:000197 BLOCK /Users/dgoldwas/Documents/github/building_performance_simulation/openstudio-measures/lib/measures/surface_matching_diagnostic/m [FINISH]
c:0020 p:---- s:0191 e:000190 CFUNC :each
c:0019 p:0183 s:0187 e:000186 METHOD /Users/dgoldwas/Documents/github/building_performance_simulation/openstudio-measures/lib/measures/surface_matching_diagnostic/m
c:0018 p:1335 s:0167 e:000166 METHOD :/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/measure.rb:517`

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Mac 3.3.0 installer

**Comment by DavidGoldwasser** [comment]
@ggartside wasn't sure if you saw `removeCollinear` crash in any other testing. I can share the model by email

**Comment by DavidGoldwasser** [comment]
Issue seems to be calling that method on very small surfaces, for example with coordinates like what is below. While this should still be fixed, I can check area before calling this method to bypass it.

`  28.3463966472, 10.668, 9.4488,          !- X,Y,Z Vertex 1 {m}
  28.3463975616, 11.43, 9.4488,           !- X,Y,Z Vertex 2 {m}
  28.3463972568, 11.43, 9.4488;           !- X,Y,Z Vertex 3 {m}`

**Comment by DavidGoldwasser** [comment]
Here is code from measure to cleanup small surfaces and then Collinear surfaces,

`# remove collinear points in a surface
model.getPlanarSurfaces.sort.each do |surface|
  puts "starting on #{surface.name}"
  if surface.grossArea < 0.01
    runner.registerWarning("Deleting very small surface named #{surface.name}. It causes removeCollinear to crash.")
    surface.remove
    next
  end

  new_vertices = OpenStudio.removeCollinear(surface.vertices)
  starting_count = surface.vertices.size
  final_count = new_vertices.size
  if final_count < starting_count
    puts "fixing #{surface.name}"
    runner.registerInfo("Removing #{starting_count - final_count} collinear vertices from #{surface.name}.")
    surface.setVertices(new_vertices)
  end
  puts "finshing on #{surface.name}"
end`

**Comment by DavidGoldwasser** [comment]
I'll put the fix into this measure as well https://github.com/BuildingPerformanceSimulation/openstudio-measures/tree/master/lib/measures/surface_matching_diagnostic

**Comment by tijcolem** [comment]
@DavidGoldwasser Are we still hitting this error with the 3.4.0?

**Comment by jmarrec** [comment]
@DavidGoldwasser is this still a thing in 3.6.1? If so, please reopen. Otherwise, let's close.
