### ISSUE TITLE
Breaking changes to consider

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio#4531]
Enhancement Request
--------------
Checklist:
- CoolingTower:*Speed
  - [x] `evaporationLossMode` (`boost::optional<std::string>` to `std::string`)
  - [x] `blowdownCalculationMode` (`boost::optional<std::string>` to `std::string`)
  - [x] `cellControl` for CoolingTower:VariableSpeed
- EvaporativeFluidCooler:SingleSpeed
  - [ ] `performanceInputMethod` (make required-field, and change `boost::optional<std::string>` to `std::string`)

**Comment by jmarrec** [comment]
* PlantLoop:
    * [ ] commonPipeSimulation (optionalString to std::string, it has an IDD default) https://github.com/NREL/OpenStudio/blob/5cbad13c7931b54e932f9cebfe4484253c868433/src/model/PlantLoop.hpp#L141. The ctor puts it to blank FYI: https://github.com/NREL/OpenStudio/blob/5cbad13c7931b54e932f9cebfe4484253c868433/src/model/PlantLoop.cpp#L1236

**Comment by eringold** [comment]
Extending the PlantLoop bullet: might want to consider a `commonPipeSimulationValues` static member function, returning ["None", "CommonPipe", "TwoWayCommonPipe"].

**Comment by tijcolem** [comment]
merged in https://github.com/NREL/OpenStudio/pull/4548
