### ISSUE TITLE
Wrap phase change material properties

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#4538]
Enhancement Request
--------------
Wrap [MaterialProperty:PhaseChange](https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-surface-construction-elements.html#materialpropertyphasechange) and [MaterialProperty:PhaseChangeHysteresis](https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-surface-construction-elements.html#materialpropertyphasechangehysteresis) objects.

## Possible Implementation
Probably very similar to [OS:MaterialProperty:MoisturePenetrationDepth:Settings](https://github.com/NREL/OpenStudio/blob/f3fba80d69e8fd6f0d9352951ab967c0bacda39a/src/model/MaterialPropertyMoisturePenetrationDepthSettings.cpp)

**Comment by joseph-robertson** [comment]
[Here](https://github.com/NREL/OpenStudio/pull/2828) is the original PR for `OS:MaterialProperty:MoisturePenetrationDepth:Settings`.
