### ISSUE TITLE
OpenStudio exported gbXML 'exposedToSun' attribute not written

### ISSUE THREAD

**Issue by jpstaub** [NREL/OpenStudio#4559]
Issue overview
--------------
On OpenStudio forward translation to gbXML the 'exposedToSun' attribute is not written to exterior surface types.

## Current Behavior
Instead of writing the 'exposedToSun' attribute for exterior surface types no attribute is written by OpenStudio forward translation to gbXML.

## Expected Behavior
The 'exposedToSun' attribute should be written for exterior surface types per the gbXML schema.

## Steps to Reproduce
1. Set a representative wall with an 'Outdoor' boundary condition.
2. Export to gbXML.
3. View gbXML with text editor and observe 'exposedToSun' attribute not set.

## Details
Please [click here](https://unmethours.com/question/71010/openstudio-exported-gbxml-exposedtosun-attribute-not-written/) for additional details posted to Unmet Hours.

### Environment
Operating system: Windows 10
Openstudio Application: v1.3.1 (SDK version 3.3.0)

### Context
Severity of not writing the 'exposedToSun' attribute for exterior surface types is unknown at this time. The issue was discovered while reviewing gbXML files for consistency using the [Spider gbXML Viewer](https://www.ladybug.tools/spider/gbxml-viewer/r14/gv-cor-core/gv-cor.html). 

The [gbXML schema](https://gbxml.org/schema_doc/6.01/GreenBuildingXML_Ver6.01.html#Link1A8) suggests the 'exposedToSun' attribute has importance in that it separates exterior surfaces that are exposed to the sun from those that are not.

Thank you for your time and consideration of this issue.

-Jake Staub

**Comment by macumber** [comment]
It looks like that attribute isn't being set in [ForwardTranslator::translateSurface](https://github.com/NREL/OpenStudio/blob/develop/src/gbxml/ForwardTranslator.cpp#L758).  I'm not sure what impact it has if it is not set, apparently it would default to true.

**Comment by jpstaub** [comment]
Since my use of gbXML is limited to [Spider Viewer](https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/v-0-17-08/app-viewer/spider-gbxml-viewer.html) and Trane TRACE700 I am not qualified to assess impact across the wider gbXML community. I have requested that [gbXML.org](http://gbxml.org/) comment on behalf of the community. 

As far as Spider Viewer is concerned, the absence of the attribute prevents filtering for 'exposedToSun' faces which increases level of difficulty of the gbXML quality assurance process. 

I have not had the opportunity to characterize severity of impact on TRACE700 analysis results.
