### ISSUE TITLE
gbxml export does not transfer thermalZone Volume

### ISSUE THREAD

**Issue by wassimj** [NREL/OpenStudio#4561]
Issue overview
--------------

Space Volume calculations in openstudio are not accurate for complex shapes (https://github.com/NREL/OpenStudio/issues/127). As a workaround one can set osThermalZone.setVolume. While this fixes the issue in the .OSM file, the gbxml forward translator does not carry over that value and uses space.volume which can have wrong value. It should use space.thermalzone.volume instead. Or offer the use a method to set the volume for a space (osSpace.setVolume does NOT exist)

## Current Behavior

For complex shapes, the volume of the space is wrong

## Expected Behavior

One or all things should happen:
1. osSpace should calculate the volume in a more accurate fashion. Address https://github.com/NREL/OpenStudio/issues/127
2. osSpace should offer a osSpace.setVolume method
3. If the above is not fixed, The gbxml Forward translator should use the saved value in the thermalZone rather than in space.volume

## Steps to Reproduce
1. Open the attached SpeckleBuilding.zip file and extract the OSM and GBXML files
2. Using a robust geometric method, compute the volumes of Space "8" and Space "9"
3. Compare the Volumes of Space "8" and Space "9" in the gbxml file to your calculations
4. Export the OSM file to gbxml and observe the volume of Space "8" and Space "9" compare to the volume set for their thermal zones.

## Possible Solution

One or allthings should happen:
1. osSpace should calculate the volume in a more accurate fashion. Address https://github.com/NREL/OpenStudio/issues/127
2. osSpace should offer a osSpace.setVolume method
3. If the above is not fixed, The gbxml Forward translator should use the saved value in the thermalZone rather than in space.volume
### Environment
[SpeckleBuilding.zip](https://github.com/NREL/OpenStudio/files/8407059/SpeckleBuilding.zip)

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA): Application: 1.3.0  SDK: 3.3.0

### Context

We are trying to output a robust and dependable gbxml from openstudio for energy analysis and a wrong volume can cause problems down the line.

**Comment by macumber** [comment]
I think that points 1 and 2 should be addressed.  The OS volume calculations should match the E+ calculations and now that E+ has a space object I think it will make sense to be able to set the space volume directly if you know it more accurately than OS/E+.

**Comment by macumber** [comment]
I could try to add a `Space::setVolume` method, #127 might be a good issue for @ggartside if he is looking for things to work on.

**Comment by macumber** [comment]
Hmm looks like the E+ space does not have a volume property so the OS space volume would not translate over to E+.  But OS space volume would translate to gbXML which is what @wassimj is looking at.

**Comment by joseph-robertson** [comment]
So our preference here would be to implement `Space::setVolume` and update `Space` IDD for a new `Volume` field? Then have `Space::volume` return the set value, otherwise the calculated value if not populated?

(If these are addressed, then there'd be no need for point 3 above.)
