### ISSUE TITLE
Not able to run any  64 bits version of OpenStudio on Dell Precision 5560

### ISSUE THREAD

**Issue by mehrdad782014** [NREL/OpenStudio#4563]
We've been trying to install OpenStudio (V1.14.0, 2.9.0, 3.3.0) on our new Dell Precision 5560 laptops, but it looks like there is something wrong with software preventing us from running OpenStudio.(all of them failed to launch)  However, I did test on version 1.14.0 32 bits, it worked fine. It think there is something wrong 64 bit executables files. Is there any way to download the 32bit executable for V2.9.0?

**Comment by macumber** [comment]
Do you think your issue is similar to https://github.com/NREL/OpenStudio/issues/3827?  If so, it may be an issue with the CPU: https://github.com/NREL/OpenStudio/issues/3827#issuecomment-1051560389

**Comment by macumber** [comment]
I didn't hear any sound on your video so I'm not 100% sure what you were pointing out but if you are looking for the graphical user interface OpenStudio Application those installers have moved to the OpenStudio Coalition.  You can find our most recent installers at https://github.com/openstudiocoalition/OpenStudioApplication/releases

The OpenStudio Application 1.3.1 release includes the OS 3.3.0 SDK (which is what you downloaded).  

See these links for more information:
http://openstudio.net/news/1536268924
https://openstudiocoalition.org/about/openstudio_coalition/

Does that answer your question?

**Comment by jmarrec** [comment]
Closing, been kept open for a year, seems enough.
