### ISSUE TITLE
openstudio for python 3.10

### ISSUE THREAD

**Issue by wassimj** [NREL/OpenStudio#4565]
Enhancement Request
--------------
Can openstudio python module be created that is compatible with python 3.10
At present, when I try to do pip install openstudio using python 3.10, I get the following error:

```
ERROR: Could not find a version that satisfies the requirement openstudio (from versions: none)
ERROR: No matching distribution found for openstudio
```

**Comment by jmarrec** [comment]
@wassimj which platform? Win10?

**Comment by wassimj** [comment]
I am using Windows10 but topologic runs on Windows, Linux, and MacOS. Blender 3.1 uses python 3.10

**Comment by jmarrec** [comment]
I need to test this, but the bindings should already work on Linux and on mac, only windows is being annoying.

**Comment by wassimj** [comment]
> @wassimj could you try `pip install -i https://test.pypi.org/simple/ openstudio==3.4.0a0` from a python 3.10 env please on Windows? I kind messed up the versionning here, but it should work for Windows and python 3.10 (and will not work for any other combinations of platform / python version)

Yup it works! many thanks!

<img width="665" alt="openstudio-py310" src="https://user-images.githubusercontent.com/6302909/162807159-fe75a60f-4811-45c4-af17-bc15172d9d13.png">

**Comment by wassimj** [comment]
And it also now works within Blender 3.10 (using TopologicSverchok) since it uses python 3.10. Thank you again.
<img width="1454" alt="openstudio-blender-3 10" src="https://user-images.githubusercontent.com/6302909/162809420-6061a4d9-74f3-45f5-a4bd-87f3502a40d3.png">

**Comment by jmarrec** [comment]
@wassimj thanks for the report and for testing.
