### ISSUE TITLE
Handling of Spaces and ThermalZones with the same name

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/OpenStudio#4572]
Issue overview
--------------
The recent EnergyPlus release added Spaces.  The recent OpenStudio now translates both spaces and thermal zones objects to their EnergyPlus equivalents.  They cannot be named the same in EnergyPlus.

## Current Behavior
Regression testing with openstudio-standards produced this error:
`[openstudio.model.Model] No space called CB_UTILITY_F4 was found in the model, cannot be added to HVAC system. `

This is failing in [this part](https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/prototypes/common/objects/Prototype.Model.hvac.rb#L573-L575) of openstudio-standards:
```
      space = model.getSpaceByName(space_name)
      if space.empty?
        OpenStudio.logFree(OpenStudio::Error, 'openstudio.model.Model', "No space called #{space_name} was found in the model, cannot be added to HVAC system.")
```
The prototype buildings link the HVAC systems to space names, which then adds it to the spaces' thermal zones.
I'm not entirely sure why the spaces aren't showing up; in my reproduction of the model translation below the thermal zone names are changed (appending ' 1'), not the space names.  I'm wondering if there is an order in which they appear in the model that is causing the conversion.

## Expected Behavior
I would expect either a warning to disallow thermal zone assignment to a space of the same name, or renaming a thermal zone to the name of a space.  Or automatically checking before conversion to EnergyPlus. I'm not sure which is best.

## Steps to Reproduce
An example translation of an older model to an OS v3.4.0 model when the space and thermal zone names are the same:
[Link to model with identical space and thermal zone names](https://github.com/NREL/openstudio-standards/blob/9fd0542d43e76335ecc3922be546a01af666334e/data/geometry/ASHRAECollege.osm).
```
require 'openstudio'
translator = OpenStudio::OSVersion::VersionTranslator.new
path = OpenStudio::Path.new('ASHRAECollege.osm')
model = translator.loadModel(path)
model = model.get
model.save('out.osm', true)
```
In this case, the thermal zone names change upon conversion with an appended ' 1'.

## Possible Solution
I'm not sure what the best solution is here for translating older models with identical space and thermal zone names.

### Environment
Some additional details about your environment for this issue (if relevant):
 - Using OS v3.4.0-rc1

### Context
Discovered through failing regression tests in openstudio-standards

**Comment by joseph-robertson** [comment]
I don't understand what connection this could have with forward translation of spaces, as it is opt-in.

This issue is referring to weird behavior happening in version translation?

**Comment by mdahlhausen** [comment]
Yeah, it could be in the version translator.  I didn't dig deep enough to figure out the exact issue, just enough to know there is one.

**Comment by joseph-robertson** [comment]
[This](https://github.com/NREL/OpenStudio/blob/develop/developer/doc/ReleaseNotes/OpenStudio_Release_Notes_3_3_0.20211105.md#new-features-major-fixes-and-api-breaking-changes) is pointed out in the OS 3.3.0 release notes (by @jmarrec):

Note: EnergyPlus due to the Space feature now enforces unicity of names within the Zone, Space, ZoneList and SpaceList objects. As a result, we are now enforcing this in the openstudio::model namespace: the same name can no longer be used for objects of type ThermalZone, Space, SpaceType.

**Comment by mdahlhausen** [comment]
I see.  So perhaps this is an OS app or translator issue to make sure the same name isn't used across objects.  I did run the translator with the OS 3.4.0-rc1 release and found it did change ThermalZone names.  I'm not sure why it failed in the openstudio-standards prototype run which references Space names instead; perhaps there is some weird ordering where it changes either the Space or ThermalZone name depending on which one appears first in the model?

I'm not sure this is an issue that needs fixing as it is an edge case.  I expect some users may run into it with the OS app or with the version translator in specific circumstances.

**Comment by jmarrec** [comment]
@mdahlhausen This is absolutely correct, the order in which the VT finds the Space or Zone influences why one will be renamed.

Behind the scenes, what the VT does is:

```
for each object in the old workspace:    # this is the order-dependent part
   Create: a an object of the same type in the new workspace (new IDD version)
   for index, each old_field in enumerate(old object's field):
      # Map each field. That includes the 'name' field.
      new_object.setString(index, old_field)   # (and sometimes special rules, like mapping to another field etc)
```

**Comment by tijcolem** [comment]
@mdahlhausen Going to close as this is the expected behavior related to the naming/ids.
