### ISSUE TITLE
OpenStudio CLI for Revit 2022/2023 fails to run

### ISSUE THREAD

**Issue by DiddyVB** [NREL/OpenStudio#4573]
Issue overview
--------------
Revit 2022 and 2023 is unable to run a Systems Analysis via OpenStudio.

## Current Behavior
The Revit systems analysis ends a few seconds after it begins. Within the output folder, there are no error or log files generated. There also is no run directory. From my perspective, this issue is exactly the same as what was reported for Revit 2020 with #3883. I have tried all of the troubleshooting steps outlined in #3883. Including updating windows, running `openstudio --verbose --debug run`, and manually updating the bin and EnergyPlus directories to both 3.0.0 and 3.3.0. In both cases, the manual upgrade allowed me to generate log files, but the analysis fails. I assume the failure is because of incompatibilities with the commands that Revit is sending to the new versions of OS and E+. 

## Expected Behavior
I would expect to be able to run an analysis within Revit like I do on other machines. I would also expect to be able to make calls to openstudio through the CLI. 

## Steps to Reproduce
Install Revit 2022.1.2 for Windows 64
Run "C:\Program Files\NREL\OpenStudio CLI For Revit 2022\bin\openstudio.exe run -h" in a Windows Command Prompt.
No response is provided on the command line after running the command. Response is blank and advances to a new line.

## Possible Solution
Update the OpenStudio CLI for Revit20## 3rd party package.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 10 21H2 (OS Build 19044.1645)
 - Version of OpenStudio (if using an intermediate build, include SHA): OpenStudio CLI for Revit 2022 - 2.8.1

### Context
I'm trying to use Revit Systems Analysis for Revit 2022 and or 2023. I currently don't get any output running the default workflow and measures.

**Comment by tijcolem** [comment]
Hi @DiddyVB  Thanks for reporting the issue.  As you already discovered, for OpenStudio versions 2.8.1, some reported Windows builds (seems like Dell Intel hardware especially) have this problem.  The known solutions are to try and update Windows to the latest and re-install, and if that doesn't work, try a more recent version of OpenStudio.  I would advise not to copy the files to the "OpenStudio CLI For Revit 2023" directory as that is tied to specific version, although you can try. I noticed in your post that you didn't copy the "libs" folder in 3.3.0. You will want to copy that too if you go this route.   Alternatively, I would suggest you try and run it via Revit and then copy the entire workflow data path that Revit creates (see screen grab below) and then run with a different version of OpenStudio that you have installed. 

Revit is storing the run directory in ~/AppData/Local/Temp/2/<id> 
<img width="1136" alt="Screen Shot 2022-04-21 at 1 07 04 PM" src="https://user-images.githubusercontent.com/7087120/164537050-7a920959-fcae-4449-9e01-a5209190acb7.png">

I copied the entire directory, opened a command prompt, and then ran the workflow with a different version of OpenStudio. 
<img width="969" alt="Screen Shot 2022-04-21 at 1 23 44 PM" src="https://user-images.githubusercontent.com/7087120/164537684-e7fca972-2622-4c15-9c2e-e937e27431aa.png">


For what it's worth, I tested Revit 2023 and OpenStudio 2.8.1 on a clean Windows 2019 Server AWS image (See below) and everything ran fine.  

<img width="553" alt="Screen Shot 2022-04-21 at 11 38 00 AM" src="https://user-images.githubusercontent.com/7087120/164526223-4a6b7b93-27fa-4f37-bc2d-6e22ef8d80c1.png">

**Comment by DiddyVB** [comment]
Thank you for the response. Your advice on re-using the files generated by Revit and running the command through the CLI works. My last question is more general in nature. Who makes updates the "OpenStudio CLI for Revit 202#"? Is it Autodesk or OS itself?

**Comment by tijcolem** [comment]
@DiddyVB  Yes, the packaging of OpenStudio is managed by Autodesk. We are hoping for an update in the next release of Revit software.  

I'm going to close this ticket as the workaround appears to work. We can reopen if necessary.

**Comment by ForInfinity** [comment]
Run with `--no-ssl` could solve this problem.
