### ISSUE TITLE
OpenStudio 3.4.0 installer cannot run E+ simulation on windows

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#4581]
Issue overview
--------------

I made a typo in https://github.com/NREL/OpenStudio/commit/6c468e2635ef82461e8e7ff883bb6c78f8d57c8b
As a result, E+ is missing vcomp140.dll and will not run.

This is just a 180 KB DLL and can be placed manually in `C:\openstudio-3.4.0\EnergyPlus`. I hosted it here for anyone who wants a quick workaround: https://drive.google.com/file/d/1RS_JyJvEDNga9q7mhbIhrHd-RqkkkhQN/view?usp=sharing

## Current Behavior

![image](https://user-images.githubusercontent.com/5479063/167118520-d7b59963-7c9a-4738-81c7-59056a98d998.png)

## Expected Behavior

Should work.

## Steps to Reproduce

Use a **clean** windows 10 machine. (If you have C++ Redist package installed, you probably won't have the issue).

Try to run a simulation

## Possible Solution

fix typo

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.4.0 official

### Context

I was doing OpenStudioApplication 1.4.0-rc1 on clean machines.

**Comment by tijcolem** [comment]
Thanks @jmarrec for the quick fix.  I posted some new installers that include this dll. https://github.com/NREL/OpenStudio/releases/tag/v3.4.0-vcomp

**Comment by tijcolem** [comment]
I updated the windows installers in https://github.com/NREL/OpenStudio/releases/tag/v3.4.0 to include the missing dll. Closing this as the fix is now merged into develop branch.
