### ISSUE TITLE
FloorspaceJS to OSM translator

### ISSUE THREAD

**Issue by tijcolem** [NREL/OpenStudio#4583]
## Enhancement Request
Related #4387, #4432

Create an additional method to convert FloorspaceJS directly to OpenStudio OSM instead of using the deprecated ThreeJS format that currently goes from FloorspaceJS -> ThreeJS -> OSM. 

## Detailed Description
The current method to translate FloorspaceJS to OSM is to first convert FloorspaceJS to ThreeJS and then convert ThreeJS to OSM. Historically, translating from FloorspaceJS to ThreeJS was done to allow a preview of the geometry using `ViewModel` and `ViewData` before converting it to OSM.   In order to "preview" using this new method, a user would first require a conversion from FloorspaceJS -> OSM and then from OSM -> glTF to view using `ViewModel` and `ViewData`  

As the ThreeJS format is deprecated and OpenStudio is adopting the web standard glTF as a replacement this is the time to update the translation from FloorspaceJS to OSM and the thinking is having a direct translation would be a cleaner approach. 

## Possible Implementation

current

```
scene = floorplan.get.toThreeScene(true)  => preview using ThreeJS viewer
new_model = rt.modelFromThreeJS(scene) => convert to osm
```

proposed 
```
new_model = rt.modelFromFloorSpaceJS()  => convert to osm
glTF = ft.modelToGLTF(model, outputPath) => convert to glTF and view in any glTF supported viewer
```

Example of the current translation process.    https://github.com/NREL/openstudio-model-articulation-gem/blob/develop/lib/measures/merge_floorspace_js_with_model/measure.rb#L103-L122

**Comment by ggartside** [comment]
[Floorspace To OSM mapping 1st Draft.xlsx](https://github.com/NREL/OpenStudio/files/8922417/Floorspace.To.OSM.mapping.1st.Draft.xlsx)
@tijcolem @DavidGoldwasser This is the first draft for the floorspace to OSM object and property mapping for your review.

**Comment by ggartside** [comment]
I have prototyped a set of classes that will deserizlize the floorspace json file in to memory and it seems to work as I hoped so the plan is to implement this in two parts:

The first part is to get the floorspace in to memory in a set of classes that has the same structure as the floorspace json file
The second part is to walk the floorspace model and create an OpenStudio model and all the entities and relationships.

I have done one push to your servers just to make sure I have my code safe somewhere else so feel free to browse around if you want to get a sense of where this is heading (obviously the code itself isn't at production level but I have tried to follow coding standards etc.)

**Comment by ggartside** [comment]
I'm happy with the state of the floorspace classes, I have all the concepts and properties covered. Attached is a class diagram, I'll see if I can figure out a way to generate a UML diagram showing the the dependencies as well as the inheritance
![Floorspace Class Diagram](https://user-images.githubusercontent.com/21084412/175305085-30c3ee02-5cde-4e28-84b4-6a987416c26e.png)
