### ISSUE TITLE
EnergyPlus directory is missing libintl.8.dylib on Mac

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#4584]
Issue overview
--------------
Installing OpenStudio v3.4.0 and EnergyPlus-22-1-0 on Mac x86 does not install the libintl.8.dylib in the EnergyPlus dir.

## Current Behavior
Running command:

`/Applications/OpenStudio-3.4.0/EnergyPlus/energyplus -w /Applications/EnergyPlus-22-1-0/WeatherData/USA_CO_Golden-NREL.724666_TMY3.epw /Applications/EnergyPlus-22-1-0/ExampleFiles/5ZoneAirCooled.idf`

results in error:

```
dyld: Library not loaded: @loader_path/libintl.8.dylib
  Referenced from: /Applications/OpenStudio-3.4.0/EnergyPlus/libpython3.8.dylib
  Reason: image not found
```

## Expected Behavior
The simulation should run

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Mac 10.15.7 x86
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.4.0

### Context
Cannot run simulation

@jmarrec FYI

**Comment by tijcolem** [comment]
Thanks for the report @macumber.  Looks like `libintl.8.dylib` exists on our CI runner that does installer and regression testing so it didn't catch this.  I updated the 3.4.0 Mac X86 release installers on the [3.4.0 release](https://github.com/NREL/OpenStudio/releases/tag/v3.4.0) (hot swapped), so if you grab the latest it will contain `libintl.8.dylib`.  Thanks again for pointing this out. 

@jmarrec We should. consider installing every .dylib/.lib/.so included with the E+ distribution vs trying to cherry pick what is required. I think we did this to save space.  We can discuss.

**Comment by macumber** [comment]
Did this affect the arm64 installers?

**Comment by tijcolem** [comment]
@jmarrec Could you check the arm64 m1 installers?

**Comment by jmarrec** [comment]
I already added libintl on arm, left a to-do for x64, but no-one had reported any issues during testing
https://github.com/NREL/OpenStudio/commit/99611275c0ba08b657bd0e5ba313bc65199e603f
