### ISSUE TITLE
Cannot instal Python bindings 3.4.0 on macos

### ISSUE THREAD

**Issue by ruggieroguida** [NREL/OpenStudio#4586]
Issue overview
--------------
Cannot instal Python bindings 3.4.0 on macos. 3.20 works fine. I have tried with `pip install openstudio==3.4.0` but I receive the following error:
```
ERROR: Could not find a version that satisfies the requirement openstudio==3.4.0 (from versions: 3.2.0)
ERROR: No matching distribution found for openstudio==3.4.0

```
I have also tested `pip install -i https://test.pypi.org/simple/ openstudio==3.4.` and I get the same error.

## Current Behavior
It seems that 3.4.0 is not available on pypi or pypi test

### Environment

Some additional details about your environment for this issue (if relevant):
- Macobok Pro M1 (arm64)
- Monterey 12.3.1

**Comment by tijcolem** [comment]
@ruggieroguida  Thanks for the report. We actually don't have macos M1 bindings available as of yet. The bindings for x86_64 on macos are available so the command  `pip install openstudio==3.4.0` would work fine on that hardware. We currently build the python bindings using GitHub runners and they haven't released M1 VMs yet (https://github.com/actions/virtual-environments/issues/2187) but it does look promising that they will. We are also working to get some m1 runners in-house.

**Comment by jmarrec** [comment]
@ruggieroguida I just built the python bindings on my M1 machine and I pushed them to testpipy. Would you mind giving it a shot please?

```
pip install -i https://test.pypi.org/simple/ openstudio==3.4.0
```

Then in Python, the following should work.

```python
import openstudio
m = openstudio.model.Model()
print(m)
```

Thanks!

**Comment by jmarrec** [comment]
Ok nice, thanks for testing.

FYI, given the experimental nature of these bindings for M1, they will stay on **testpypi** only for now, until the next release at least, so we have a few people testing them out before we make them official on **pypi.org**.

We'll document these experimental bindings soon.

**Comment by ruggieroguida** [comment]
Not sure it is bug, or expected behaviour in the new version, so commenting here. I am not familiar with the SDK yet.

With the 3.4.0 I receive an error when forward translating the example model. 

This worked in 3.2.0
```
import openstudio
m = openstudio.model.exampleModel()
ft = openstudio.energyplus.ForwardTranslator()
w = ft.translateModel(m)
```

Now I receive a series of:
`[openstudio.model.YearDescription] <1> 'UseWeatherFile' is selected in YearDescription, but there are no weather file set for the model.`

**Comment by jmarrec** [comment]
Here is the change that produce this warning now:

https://github.com/NREL/OpenStudio/pull/4347/files#diff-3aad32589b7b0c27c7c7b8e9f4c4ebc362a0736a86d51b39bef91df63856ee61R245
