### ISSUE TITLE
Switch to E+ Space FT by default

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4588]
Enhancement Request
--------------
In OpenStudio 3.3.0, experimental Support for the EnergyPlus 9.6.0 [space concept](https://github.com/NREL/EnergyPlus/blob/develop/design/FY2021/NFP-Spaces.md) was added. This feature is currently opt-in. For OpenStudio 3.5.0, it should be changed to the default behavior while allowing the user/software to opt out.

This will:
- Better align the OpenStudio and EnergyPlus models
- Reduce bugs caused by OpenStudio trying to combine space-level objects
- Allow users/software to more easily take advantage of this capability
- Generate more accurate simulation results, as heat balances will now occur at the space (technically enclosure) and not thermal zone level

**Comment by tijcolem** [comment]
@shorowit Thanks for creating the issue for this.  

@joseph-robertson @jmarrec  I say let's got ahead and bump version to 3.4.1 and set the opt-in space feature as default to prepare for next release.
