### ISSUE TITLE
E+ Space FT Issue

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4591]
Issue overview
--------------
I'm doing some testing of the new E+ Space FT on residential models. Since the models have 1 space per zone, I expect identical results between OS 3.4.0 and 3.4.1.

## Current Behavior
For a sample file, I'm getting different E+ results due to the `ZoneInfiltration:DesignFlowRate` object changing.

## Expected Behavior
The `ZoneInfiltration:DesignFlowRate` object should be identical between OS 3.4.0 and 3.4.1

## Steps to Reproduce
Using [OpenStudio-HPXML](https://github.com/NREL/OpenStudio-HPXML), run:
`openstudio workflow/run_simulation.rb -x workflow/sample_files/base.xml`
in both OS 3.4.0 and 3.4.1 and note the different E+ results.

(To run OS 3.4.1, you need to change [this line](https://github.com/NREL/OpenStudio-HPXML/blob/master/HPXMLtoOpenStudio/resources/version.rb#L5) to "3.4.1".)

This is caused by a different `ZoneInfiltration:DesignFlowRate` object:
```patch
   Always On Discrete,                     !- Schedule Name
-  AirChanges/Hour,                        !- Design Flow Rate Calculation Method
-  ,                                       !- Design Flow Rate {m3/s}
+  Flow/Zone,                              !- Design Flow Rate Calculation Method
+  0.00922493533933472,                    !- Design Flow Rate {m3/s}
   ,                                       !- Flow per Zone Floor Area {m3/s-m2}
   ,                                       !- Flow per Exterior Surface Area {m3/s-m2}
-  0.1,                                    !- Air Changes per Hour {1/hr}
+  ,                                       !- Air Changes per Hour {1/hr}
   1,                                      !- Constant Term Coefficient
```

If I manually change the IDFs so that this object is identical, then the E+ results match perfectly.

**Comment by joseph-robertson** [comment]
Looks to be due to this: https://github.com/NREL/OpenStudio/blob/develop/src/energyplus/ForwardTranslator.cpp#L378-L385

**Comment by jmarrec** [comment]
I'm a bit confused by the geometry I find in `OpenStudio-HPXML/workflow/sample_files/run` after running `openstudio workflow/run_simulation.rb -x workflow/sample_files/base.xml`

<img width="946" alt="image" src="https://user-images.githubusercontent.com/5479063/169900192-9c475daa-f690-4604-8f74-391ce00228fe.png">

**Comment by shorowit** [comment]
HPXML files don't include full 3D building geometry, so we "explode" the surfaces in order to prevent self shading and so you can better see the surfaces (relative to a pinwheel result where all of the surfaces go through the origin). If I recall correctly, this is is the same approach used by CBECC-Com (using OpenStudio/EnergyPlus) for one of their simplified geometry options. EnergyPlus certainly supports non-enclosed building geometry.

**Comment by jmarrec** [comment]
```diff
      for (auto& infil : model.getConcreteModelObjects<SpaceInfiltrationDesignFlowRate>()) {
        // TODO: technically we only need to do that if the space it's assigned to is part of a thermalzone with more than one space
        // Same reason as above: not doing it for now
-       infil.hardSize();
+       if (infil.space() && !openstudio::istringEqual("Flow/Area", infil.designFlowRateCalculationMethod()) && infil.space()->thermalZone().spaces().size() > 1) {
+         infil.hardSize();
+       }
      }
```

**Comment by jmarrec** [comment]
Side note, but https://github.com/NREL/OpenStudio/pull/4579 is also a good workaround this issue for your model. If you hardcode space.setVolume(xxx) then the conversion ACH => Flow/Space will work too

**Comment by joseph-robertson** [comment]
> I guess the technically required cases where we need to hardsize the SpaceInfiltration are:
> 
> ```diff
>       for (auto& infil : model.getConcreteModelObjects<SpaceInfiltrationDesignFlowRate>()) {
> -       // TODO: technically we only need to do that if the space it's assigned to is part of a thermalzone with more than one space
> -        // Same reason as above: not doing it for now
> +       // technically we only need to do that if the space it's assigned to is part of a thermalzone with more than one space
> -       infil.hardSize();
> +       if (infil.space() && !openstudio::istringEqual("Flow/Area", infil.designFlowRateCalculationMethod()) && infil.space()->thermalZone().spaces().size() > 1) {
> +         infil.hardSize();
> +       }
>       }
> ```
> 
> https://github.com/NREL/OpenStudio/blob/d39d697a2aa97984aeafeada0ec7563435632658/src/energyplus/ForwardTranslator.cpp#L378-L385

Note I think you meant "Flow/Space" (instead of "Flow/Area") above.

**Comment by jmarrec** [comment]
absolutely, Flow/Space
