### ISSUE TITLE
Documentation for isGroundSurface() is missing an outside boundary condition

### ISSUE THREAD

**Issue by lymereJ** [NREL/OpenStudio#4599]
Issue overview
--------------
The documentation for `openstudio::model::Surface::isGroundSurface()` does not mention the `Foundation` outside boundary condition type but the code seems to be taking it into account, see [here](https://github.com/NREL/OpenStudio/blob/d75af8b9309517294089066e6a5b3c0373d43d9e/src/model/Surface.cpp#L341-L353).

**Comment by joseph-robertson** [comment]
@tijcolem I went ahead and opened #4686. I think I had originally introduced this issue back in #2902.
