### ISSUE TITLE
setWindowToWallRatio failed silently without warnings

### ISSUE THREAD

**Issue by weilixu** [NREL/OpenStudio#4601]
Issue overview
--------------

The setWindowToWallRatio function failed when specifying a WWR of 0.98 (98%) with **0.0** sill offset and **true** for heightOffsetFromFloor.

## Current Behavior

```ruby
m = Model.new
pts = OpenStudio::Point3dVector.new;  pts << OpenStudio::Point3d.new(0, 0, 0); pts << OpenStudio::Point3d.new(0, 1, 0); pts << OpenStudio::Point3d.new(1, 1, 0); pts << OpenStudio::Point3d.new(1, 0, 0);
s = Space::fromFloorPrint(pts, 3, m).get()
surface = m.getSurfaces.select{|s| s.surfaceType.upcase == 'WALL'}.first
new_window = surface.setWindowToWallRatio(0.98, 0.0, true).get

=> RuntimeError: Optional not initialized
```

## Expected Behavior

Expect: 1. window to wall ratio successfully set to 98% or above. or
2. Failed with informative messages.

## Steps to Reproduce

1. Create medium office prototype with OpenStudio Standard. Use '90.1-2019' as template. 
2. Load model
3. Loop through surfaces: model.getSurfaces.each do |ss|
4. get original construction of the subsurface
5. remove the subsurfaces in the surface
6. create new window: ss.setWindowToWallRatio(0.98, 0.0, true).get

### Environment
OpenStudio V3.2

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 10
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.2.1

### Context

Try to implement the logic in the [ASHRAE 90.1 2019 addendum l to 2019](https://www.ashrae.org/file%20library/technical%20resources/standards%20and%20guidelines/standards%20addenda/90_1_2019_l_20201030.pdf)

**Comment by MatthewSteen** [comment]
Could use a warning that the WWR > maximum allowed.

https://github.com/NREL/OpenStudio/blob/f7b7f88e743e15a9e934e8109af8e61784e8b2cb/src/utilities/geometry/Geometry.cpp#L687-L695
