### ISSUE TITLE
Forward Translation issue with ZoneHVACTerminalUnitVariableRefrigerantFlow

### ISSUE THREAD

**Issue by Ski90Moo** [NREL/OpenStudio#4609]
Issue overview
--------------

It appears there is an issue with forward translating variable refrigerant flow terminal units.  The following error appears:

```
[BOOST_ASSERT] <2> Assertion value failed on line 501 of double __cdecl openstudio::model::detail::ZoneHVACTerminalUnitVariableRefrigerantFlow_Impl::maximumOutdoorDryBulbTemperatureforSupplementalHeaterOperation(void) const in file D:\OSN\src\model\ZoneHVACTerminalUnitVariableRefrigerantFlow.cpp.
stderr: [BOOST_ASSERT] <2> Assertion value failed on line 501 of double __cdecl openstudio::model::detail::ZoneHVACTerminalUnitVariableRefrigerantFlow_Impl::maximumOutdoorDryBulbTemperatureforSupplementalHeaterOperation(void) const in file D:\OSN\src\model\ZoneHVACTerminalUnitVariableRefrigerantFlow.cpp.
```

![2022-06-14](https://user-images.githubusercontent.com/69771412/173661957-10b32f84-994c-4c25-9af5-585deadeef3b.png)

## Steps to Reproduce

1. Create a VRF system with multiple zone terminals
2. Run the simulation
3.
4.

## Details
![2022-06-14 (2)](https://user-images.githubusercontent.com/69771412/173662158-93e2ebef-94b5-48da-a6c3-e0f5f15525c2.png)

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### Context

I am not sure how this error affects the simulation or if this is the correct forum to report this bug.

**Comment by jmarrec** [comment]
@Ski90Moo Thanks for reporting. Seems like it's a change in OS SDK (the IDD default of 21.0 was removed and the ZoneHVACTerminalUnitVariableRefrigerantFlow Ctor is the one that harcodes it) that wasn't reflected in the OS App hvac_library.osm.

Moved to: https://github.com/openstudiocoalition/OpenStudioApplication/issues/549

Basically just open `C:\openstudioapplication-1.4.0\Resources\default\hvac_library.osm`, modify lines 5524 and 5525

```diff
OS:ZoneHVAC:TerminalUnit:VariableRefrigerantFlow,
  {61b461bb-c165-4bd3-a212-fc1fb1023e9a}, !- Handle
  VRF Zone Terminal,                      !- Name
[...]
-  ,                                       !- Maximum Supply Air Temperature from Supplemental Heater {C}
-  ;                                       !- Maximum Outdoor Dry-Bulb Temperature for Supplemental Heater Operation {C}
+  Autosize,                               !- Maximum Supply Air Temperature from Supplemental Heater {C}
+  21.0;                                   !- Maximum Outdoor Dry-Bulb Temperature for Supplemental Heater Operation {C}
```
