### ISSUE TITLE
Openstudio crashes after clicking on thermal zone tab

### ISSUE THREAD

**Issue by Nischal0150** [NREL/OpenStudio#4617]
Issue overview
--------------
I am using Openstudio 3.40 to model a building with 50 thermal zones. But every time I click on the thermal zone tab on Openstudio, the application stalls for a few seconds and then crashes abruptly.

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform : Windows 10 Build 19044.1766
 - Version of OpenStudio: 3.40

**Comment by macumber** [comment]
Would you be able to post the model here (you can rename it to a .txt extension and upload it to the issue) or send it privately to osc@openstudiocoalition.org?

**Comment by macumber** [comment]
Also, I assume this report is about OpenStudio Application 1.4.0.  I suggest closing this issue and opening a new one at https://github.com/openstudiocoalition/OpenStudioApplication/issues
