### ISSUE TITLE
Remove functions in Node that have been deprecated for 9+ years

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#4618]
Issue overview
--------------

https://github.com/NREL/OpenStudio/blob/232fa2babef311ea8810a03b7abf170ca16ac433/src/model/Node.cpp#L244-L250

Do a blame, you'll see it's been there since the first public commit ever: https://github.com/NREL/OpenStudio/blame/232fa2babef311ea8810a03b7abf170ca16ac433/src/model/Node.cpp#L148

I didn't realize they were still there because they aren't marked `OS_DEPRECATED` in the public API.

## Current Behavior

They exist.

## Expected Behavior

We should delete them

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.4.1-alpha

### Context

I went into the file as part of implementing https://github.com/NREL/OpenStudio/issues/4543

**Comment by joseph-robertson** [comment]
@jmarrec What's the protocol for removing deprecated methods? Literally just delete them? Also, do we have a standard amount of time defined between marking methods as deprecated and subsequently removing them?

**Comment by joseph-robertson** [comment]
Also, I see that they _are_ marked `OS_DEPRECATED` in the public API.

**Comment by jmarrec** [comment]
yeah here they are marked deprecated, and I think 9 years or warnings is probably safe enough to delete. We should document the removal in https://github.com/NREL/OpenStudio/blob/develop/developer/doc/ReleaseNotes/OpenStudio_Release_Notes_3_4_1_TBD.md just to square everything.
