### ISSUE TITLE
Upgrade Ruby to 3.2

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#4624]
Enhancement Request
--------------
Upgrade the embedded Ruby version to 3.1.  This would align with future plans for integrating with SketchUp, https://forums.sketchup.com/t/ruby-3-is-coming-headers-and-libs-available/202102.  I think their reasoning is pretty sound on picking 3.1 vs 3.0 (which Ubuntu 22.04 went with).

**Comment by jmarrec** [comment]
That means we may be able to use the conan-center-index ruby recipe too, which starts at 3.1.0: https://github.com/conan-io/conan-center-index/blob/master/recipes/ruby/all/conanfile.py

At least use that as a basis for modernizing our own https://github.com/NREL/conan-openstudio-ruby/ which uses a CMake layer Plus some .bat scripts and is a pain to maintain.

**Comment by jmarrec** [comment]
* https://github.com/conan-io/conan-center-index/pull/11561
* https://github.com/conan-io/conan-center-index/pull/12456

**Comment by DavidGoldwasser** [comment]
We should tentatively plan to upgrade to 3.1 or 3.2. Can discuss offline if any complications of using 3.2 vs. 3.1.

**Comment by jmarrec** [comment]
for ref sketchup has a ruby 3.2 branch. https://github.com/SketchUp/ruby-c-extension-examples/tree/dev/ruby-3.2
