### ISSUE TITLE
Python Measures: Remove unsupported code and cleanup project

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#4636]
There are some historical artifacts in the OpenStudio projects related various defunct language binding efforts, such as NodeJS bindings to name one. Before embarking on Python Measures, the purpose of this issue is to root out stale code, and generally make sure that the project structure is well organized.

**Comment by kbenne** [comment]
@tijcolem @jmarrec May I remove this file https://github.com/NREL/OpenStudio/blob/develop/INSTALL.md?

**Comment by jmarrec** [comment]
definitely. It's mostly wrong / outdated, and the install ruby is already in the official docs

**Comment by kbenne** [comment]
I think maybe this file is also abandoned. https://github.com/NREL/OpenStudio/blob/develop/install.qs
As far as I can tell the individual components define their own IFW install scripts.

**Comment by jmarrec** [comment]
@kbenne that's different, though the name is a bit misleading. It's an install script that can be used to run the IFW installer via command line, headless.

```
sudo ./OpenStudio.run --verbose --platform minimal --script /path/to/install.qs
```

Read more on this E+ file I created that has a docstring explaining a bit the usage: https://github.com/NREL/EnergyPlus/blob/develop/cmake/qtifw/install_script.qs
