### ISSUE TITLE
Python Measures: Add Python workflow for `ModelMeasure`

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#4638]
This is designed to be the first step in recreating OpenStudio Workflow with Python support. For this stage focus only on a basic Model only workflow. Receive a seed model, apply any Python ModelMeasure instances, and return the modified model. Other stages of the Workflow will be added to this.

**Comment by jmarrec** [comment]
## TODO

* [ ] Cleanup / Synchronize bcl/templates python measures to match the final resources/Resources/compact_osw/measures/IncreaseRoofInsulationPython
      * https://github.com/NREL/OpenStudio/blob/4653-python-engine/src/utilities/bcl/templates/ModelMeasure/measure.py
      * https://github.com/NREL/OpenStudio/blob/4653-python-engine/src/utilities/bcl/templates/EnergyPlusMeasure/measure.py
      * https://github.com/NREL/OpenStudio/blob/4653-python-engine/src/utilities/bcl/templates/ReportingMeasure/measure.py
      * https://github.com/NREL/OpenStudio/blob/4653-python-engine/resources/Examples/compact_osw/measures/IncreaseRoofRValuePython/measure.py
