### ISSUE TITLE
Update FT for space-level infiltration/ventilation objects

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4645]
Enhancement Request
--------------
EnergyPlus 22.2 will support [space-level infiltration and ventilation](https://github.com/NREL/EnergyPlus/pull/9564). Since it did not previously support it, OpenStudio had to go through hoops to combine multiple space objects into a single zone object for EnergyPlus. Now there should be a 1:1 map and the code should be simpler. This will also help prevent bugs (like [this one](https://github.com/NREL/OpenStudio/pull/4593)).

~This is an important feature for us because we want to use output variables for individual space-level infiltration objects in the same thermal zone. That is not possible unless the EnergyPlus model maintains the individual space-level infiltration objects that we've defined in OpenStudio.~

**Comment by tijcolem** [comment]
@joseph-robertson  Let's prioritize the E+ 22.2.0 IO Freeze first and then if we have time we can slot this in.

**Comment by shorowit** [comment]
In hindsight, I realize that we don't actually need this capability after all. I was confusing this with something else. So it's probably still worth doing, but it's not a priority from our point of view.

**Comment by shorowit** [comment]
Apparently this may be a high priority for us again, but for a different reason. Mike Witte found that the E+ models we produce generate an error in E+ 22.2 because we try to (EMS) actuate a zone-level infiltration object (since that's all OS will produce), but when that zone has multiple spaces, E+ automatically converts the zone-level infiltration object into individual space-level infiltration objects. It does the same thing for equipment, lights, etc. It's possible there is a way to workaround this, but everything would be simpler, cleaner, and more consistent if OpenStudio translated objects 1:1.

**Comment by jmarrec** [comment]
We have SpaceInfiltration (so Space), but ZoneVentilationDesignFlowRate (so ThermalZone) in OS. For SpaceInfiltration, no problem. 

But for the ZV:DesignFlowRate, do you *want* to have that map to a Space in the end? It'd be pretty weird to me

**Comment by shorowit** [comment]
> We have SpaceInfiltration (so Space), but ZoneVentilationDesignFlowRate (so ThermalZone) in OS. For SpaceInfiltration, no problem.
> 
> But for the ZV:DesignFlowRate, do you _want_ to have that map to a Space in the end? It'd be pretty weird to me. Unless we allow the OS:ZoneVentilation:DesignFlowRate to also connect to a Space... but that's not as light of a change

Not sure what to say. In E+ they are both prefixed with Zone even though they can now apply to Spaces too. I see that OS:SpaceInfiltration inherits from SpaceLoad while OS:ZoneVentilation inherits from ZoneHVACComponent, so yeah, I see the conundrum. For what it's worth, NREL-Residential doesn't use the ZV objects today so we don't have an immediate need for them to be coupled to spaces. But we might in the future, and other users might want this.

I don't know how much I like the idea myself, but would it make any sense to introduce new SpaceVentilation objects?

**Comment by jmarrec** [comment]
I'm moving the ZoneVentilationDesignFlowRate into a separate issue (for later?): https://github.com/NREL/OpenStudio/issues/4682

Consider this one fixed via #4672
