### ISSUE TITLE
Wrap E+ 22.2 new supplemental heating coil type for `AirLoopHVAC:UnitarySystem` object

### ISSUE THREAD

**Issue by yzhou601** [NREL/OpenStudio#4646]
Enhancement Request
--------------
EnergyPlus has been improved to allow multi-staging backup coil by adding `Coil:Heating:Electric:Multistage` coil type enumeration to `Supplemental Heating Coil Object Type` field for `AirLoopHVAC:UnitarySystem` object, see [EnergyPlus PR being merged](https://github.com/NREL/EnergyPlus/pull/9414). This improvement will be included in the upcoming E+ release, OpenStudio needs to be updated to coordinate this change.

**Comment by yzhou601** [comment]
@joseph-robertson Is creating this issue sufficient to ensure the feature will be included in the next release?

**Comment by joseph-robertson** [comment]
This requires that `Coil:Heating:Electric:MultiStage` be wrapped, which might be pretty straightforward - we have already-wrapped `Coil:Heating:Gas:MultiStage` to follow as a guide.

**Comment by jmarrec** [comment]
Fixed via  #4666

**Comment by jmarrec** [comment]
Fixed via #4666
