### ISSUE TITLE
Wrap the E+ Table:Lookup, Table:IndependentVariableList, and Table:IndependentVariable objects.

### ISSUE THREAD

**Issue by tijcolem** [NREL/OpenStudio#4647]
Enhancement Request

Coming from @asparke2 from an email request. 

Wrap the E+ Table:Lookup, Table:IndependentVariableList, and Table:IndependentVariable objects. OS has the previous E+ incarnation of the LookupTable objects wrapped, but I believe those were replaced with these new ones. This new format is what Eric Bonnema used to represent the Carrier HP performance.

**Comment by joseph-robertson** [comment]
Looks like these three objects would replace `Table:MultiVariableLookup` (and `Table:MultiVariableLookupPoint`). Should we:
* add the new objects and deprecate the old objects, or
* add the new objects and _not_ deprecate the old objects, or
* add the new objects and remove the old objects

?

We'd need VT if we remove the old objects.

**Comment by asparke2** [comment]
It appears that the old objects no longer exist in EnergyPlus and have been replaced by the newer ones. If this is true, my vote is to deprecate the old objects, add the new ones, and have a version translator from old to new.

**Comment by jmarrec** [comment]
For context, 9.2.0 made the change from TableMultiVariableLookup to the three new objects.

At the time it was decided to keep the current model API (cf https://github.com/NREL/OpenStudio/issues/3651) and handle everything in forward translation, which is what https://github.com/NREL/OpenStudio/pull/3653 did.
