### ISSUE TITLE
Wrap E+ 22.2 `SurfaceProperty:IncidentSolarMultiplier` object

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4648]
Enhancement Request
--------------
EnergyPlus 22.2 is adding a new `SurfaceProperty:IncidentSolarMultiplier`, which was requested by NREL-Residential. We'd like to take advantage of this in OS 3.5.0 if possible. See https://github.com/NREL/EnergyPlus/pull/9404 for details.

**Comment by jmarrec** [comment]
Fixed via #4676
