### ISSUE TITLE
PathHelpers copyDirectory should use overwrite_existing

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#4659]
Issue overview
--------------
Using the copyDirectory, a user expects files to be overwritten if they exist.  But this is not the default behavior of std::filesystem::copy_file.

## Current Behavior
Copying results from Apply Measure Nnow does not update previous results

## Expected Behavior
Copying results from Apply Measure Now should update previous results

## Steps to Reproduce
Create a measure that writes some text to a file under `generated_files`.  Run that in Apply Measure Now in the OS App, save the model.  The text file is found under files in companion dir.  Re-run the measure with updated text.  The text file found under files in companion dir is not updated.

## Possible Solution
This line https://github.com/NREL/OpenStudio/blob/master/src/utilities/core/PathHelpers.cpp#L378 should pass in std::filesystem::copy_options::overwrite_existing

**Comment by macumber** [comment]
Thanks @tijcolem !

**Comment by jmarrec** [comment]
I found issues after testing the OSApp with the nightly build from last night.

Also, boost::filesystem::copy_option is deprecated, and replaced with boost::filesystem::copy_options. That new one is greatly enhanced, eg you can now do `fs::copy(src, dest, copy_options::recursive | copy_options::overwrite_existing)`, so we can make use of that.

cf https://www.boost.org/doc/libs/1_79_0/libs/filesystem/doc/reference.html#copy_option

https://www.boost.org/doc/libs/1_79_0/libs/filesystem/doc/reference.html#copy
