### ISSUE TITLE
People work efficiency default too high

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#466]
According to Gregor this should be 0, impacts comfort calcs

**Comment by jmarrec** [comment]
I'm confused by this issue.

![screen shot 2017-09-29 at 2 03 55 pm](https://user-images.githubusercontent.com/5479063/31015181-15ccaebc-a51f-11e7-824b-264c9d8ab159.png)

**Comment by DavidGoldwasser** [comment]
I think this isn't relevant anymore. There used to be interface when you make a new schedule, that you had to pick from long list of schedule uses, one of which was work efficiency. This was originally related to Predicted Mean Vote measure which expected the user to make work. efficiency schedule in GUI and then assign it to the measure.
