### ISSUE TITLE
multi speed DX coil stage mapping does not clone properly with airloop

### ISSUE THREAD

**Issue by mleachNREL** [NREL/OpenStudio#4663]
Issue overview
--------------

## Current Behavior

When I clone an airloop with multi speed DX coils using the OS API, the coils themselves are cloned properly, as well as their corresponding stages (dx multi speed stage data objects). But the stage assignments do not map over (the stage fields in the coil object are blank)

## Expected Behavior

It should work.

## Steps to Reproduce

Let me know what details you need to investigate. I don't think it makes sense to attach a model will blank fields as evidence. It wouldn't really show anything...

### Environment

Some additional details about your environment for this issue (if relevant):
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.4.0

**Comment by jmarrec** [comment]
Could you supply a minimum complete verifiable example of your code that highlight the bug? 

I've tested a simple clone of the CoilCoolingDXMultiSpeed (not via AirLoopHVAC) and it's already wrong but a different kind of wrong than yours: the stages aren't blank, they are duplicated....

```ruby
include OpenStudio::Model

m = Model.new

a = AirLoopHVAC.new(m)

cc = CoilCoolingDXMultiSpeed.new(m)
stage1 = CoilCoolingDXMultiSpeedStageData.new(m)
stage2 = CoilCoolingDXMultiSpeedStageData.new(m)
cc.setStages([stage1, stage2])
puts "cc has #{cc.numberOfStages} stages: #{cc.stages.map{|c| c.nameString}}"
=> cc has 2 stages: ["Coil Cooling DX Multi Speed Stage Data 1", "Coil Cooling DX Multi Speed Stage Data 2"]

cc2 = cc.clone(m).to_CoilCoolingDXMultiSpeed.get
```

```
[utilities.idf.Workspace] <-1> Renamed Object of type 'OS:Coil:Cooling:DX:MultiSpeed' and named 'Coil Cooling DX Multi Speed 1' to 'Coil Cooling DX Multi Speed 2' to avoid a name conflict upon WorkspaceObject addition.
[utilities.idf.Workspace] <-1> Renamed Object of type 'OS:Coil:Cooling:DX:MultiSpeed:StageData' and named 'Coil Cooling DX Multi Speed Stage Data 1' to 'Coil Cooling DX Multi Speed Stage Data 3' to avoid a name conflict upon WorkspaceObject addition.
[utilities.idf.Workspace] <-1> Renamed Object of type 'OS:Coil:Cooling:DX:MultiSpeed:StageData' and named 'Coil Cooling DX Multi Speed Stage Data 2' to 'Coil Cooling DX Multi Speed Stage Data 4' to avoid a name conflict upon WorkspaceObject addition.
```

```ruby
puts "cc2 has #{cc2.numberOfStages} stages: #{cc2.stages.map{|c| c.nameString}}"
=> cc2 has 4 stages: ["Coil Cooling DX Multi Speed Stage Data 1", "Coil Cooling DX Multi Speed Stage Data 2", "Coil Cooling DX Multi Speed Stage Data 3", "Coil Cooling DX Multi Speed Stage Data 4"]
```

**Comment by jmarrec** [comment]
@mleachNREL Could you let me know if you had a different error please? I've opened #4683 which is ready to merge, but I'd like to make sure I addressed your actual issue and not another one. Thanks!
