### ISSUE TITLE
Interior windows missing required Outside Boundary Condition Object when translated from FloorspaceJS

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#4670]
Issue overview
--------------
Originally reported at https://github.com/openstudiocoalition/OpenStudioApplication/issues/561

Might be relevant to current work of @ggartside ?

## Current Behavior
Interior windows are translated from FloorspaceJS to OSM without the Outside Boundary Condition Object field set.  This causes simulation to fail.

## Expected Behavior
Outside Boundary Condition Object field should be set on translation from FloorspaceJS to OSM for interior windows.

## Steps to Reproduce
Create a FloorspaceJS model with two adjacent spaces, add interior windows, on translation the Outside Boundary Condition Object is not set.

**Comment by tijcolem** [comment]
@ggartside  With the recent work getting the reverse translator from FloorspaceJS -> OSM (#4623), could you please let us know if these properties are being mapped to OSM?

**Comment by ggartside** [comment]
@tijcolem They should be - I'd have to check why they don't make it to the OSM model.

**Comment by tijcolem** [comment]
@ggartside Thanks for checking. To be clear my understanding is this was using the old method of converting FloorspaceJS to OSM.

**Comment by ggartside** [comment]
@tijcolem

**Comment by ggartside** [comment]
Sorry - somehow I closed the issue!

**Comment by ggartside** [comment]
@tijcolem  One more comment. I created the same test for the threejs reverse translator, same floorspace file and the Outside Boundary Condition Object has a value

Maybe we are looking at something more specific than a general 'we never set this property' issue?

**Comment by tijcolem** [comment]
@ggartside Thanks for investigating!

 @manuvarkey, please review the above comments.  Could you attach the floorspaceJS model this isn't translating the Outside Boundary Condition Object values?

**Comment by manuvarkey** [comment]
https://github.com/openstudiocoalition/OpenStudioApplication/files/9488182/sample.file.zip

From the original issue at OpenStudioApplication

**Comment by ggartside** [comment]
That isn't a floorspace json file

**Comment by manuvarkey** [comment]
The original file was created inside OpenStudioApplication. Seems like there is no option to export a floorspace json file (May be something worth implementing @macumber ?!). I have created another sample using [https://nrel.github.io/floorspace.js/](https://nrel.github.io/floorspace.js/). The gbxml file exported from original osm file is also attached.

[Sample.zip](https://github.com/NREL/OpenStudio/files/9529830/Sample.zip)

**Comment by ggartside** [comment]
![image](https://user-images.githubusercontent.com/21084412/189217296-4c0c3d99-ec1b-402e-aaee-afe0cc9d6c7e.png)

**Comment by macumber** [comment]
@manuvarkey the floorplan.json file is saved in the OSM file's companion directory.

@ggartside I am assuming that you tested this file using the new ThreeJS reverse translator that was merged in #4623, can you confirm?  If so, then this issue will be fixed when OS App updates to the next version of the OS SDK.

**Comment by ggartside** [comment]
I retested this today (12/15/22) and get the same results as before. Both the ThreeJS and Floorspace reverse translators have OtherSideBoundaryConditionObject set for both window and door subsurfaces using the sample file provided in this report

The floorspace reverse translator

`OS:SubSurface,
  {2740dd85-3225-4f0a-8181-bfac067fbbe5}, !- Handle
  Face 4,                                 !- Name
  FixedWindow,                            !- Sub Surface Type
  ,                                       !- Construction Name
  {23abff67-9a72-4b0a-bd8e-6d60e44d785d}, !- Surface Name
  {7023aca8-7d39-4408-8570-74f10d8a3067}, !- Outside Boundary Condition Object
  ,                                       !- View Factor to Ground
  ,                                       !- Frame and Divider Name
  ,                                       !- Multiplier
  ,                                       !- Number of Vertices
  3.3528, 5.7912, 2.1336,                 !- X,Y,Z Vertex 1 {m}
  3.3528, 5.7912, 0.9144,                 !- X,Y,Z Vertex 2 {m}
  3.3528, 6.4008, 0.9144,                 !- X,Y,Z Vertex 3 {m}
  3.3528, 6.4008, 2.1336;                 !- X,Y,Z Vertex 4 {m}`

and the ThreeJS reverse translator

`OS:SubSurface,
  {e7895418-6f51-4214-9762-ba81ba0eb271}, !- Handle
  Face 3,                                 !- Name
  FixedWindow,                            !- Sub Surface Type
  ,                                       !- Construction Name
  {5c5c6431-e0d2-44d1-9bcd-cd98eafc07d1}, !- Surface Name
  {1eaca4fb-1cb7-48f0-9e32-df5aeeb8f048}, !- Outside Boundary Condition Object
  ,                                       !- View Factor to Ground
  ,                                       !- Frame and Divider Name
  ,                                       !- Multiplier
  ,                                       !- Number of Vertices
  3.3528, 5.7912, 2.1336,                 !- X,Y,Z Vertex 1 {m}
  3.3528, 5.7912, 0.9144,                 !- X,Y,Z Vertex 2 {m}
  3.3528, 6.4008, 0.9144,                 !- X,Y,Z Vertex 3 {m}
  3.3528, 6.4008, 2.1336;                 !- X,Y,Z Vertex 4 {m}`

@macumber the reverse translator merged in #4623 is the Floorspace reverse translator which creates OSM models direct from a floorspace json file, it isn't a new ThreeJS reverse trans;lator FYI.
