### ISSUE TITLE
Glass U Factor sql error

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4678]
Issue overview
--------------
User on Unmet Hours hits an error when using `window.uFactor`. Reported at https://unmethours.com/question/80413/problem-in-openstudio-measure-in-34/.

Looks like a closing single quotation mark is missing from all these sql statements:
https://github.com/NREL/OpenStudio/blob/135d27832ebee5682c545a2a6f507e25e0cffa40/src/model/SubSurface.cpp#L377
https://github.com/NREL/OpenStudio/blob/135d27832ebee5682c545a2a6f507e25e0cffa40/src/model/SubSurface.cpp#L450
https://github.com/NREL/OpenStudio/blob/d75af8b9309517294089066e6a5b3c0373d43d9e/src/model/Surface.cpp#L659
https://github.com/NREL/OpenStudio/blob/d75af8b9309517294089066e6a5b3c0373d43d9e/src/model/Surface.cpp#L732

**Comment by joseph-robertson** [comment]
This looks like my fault in https://github.com/NREL/OpenStudio/pull/4550. @jmarrec is https://github.com/NREL/OpenStudio/tree/develop/src/utilities/sql/Test an appropriate place to add tests?

**Comment by shorowit** [comment]
Looks to me like https://github.com/NREL/OpenStudio/commit/e91017d1813564dc7d1a42ece8a841f9c04702cb is to blame.
