### ISSUE TITLE
Modify Model::load(path&) to use VersionTranslator by default

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#4692]
Enhancement Request
--------------

It's been like this for ever, but it's weird that Model::load just assumes this is at the right version.  It's very confusing to new users too, and they struggle with knowing how to load a model.

https://github.com/NREL/OpenStudio/blob/92da27b27de50e076ce3bdc5032e4f348e2231e8/src/model/Model.cpp#L1836-L1858

 It shouldn't be that verbose to load a model

https://github.com/NREL/OpenStudio-workflow-gem/blob/cf99e6096f33b717df79a71c245a4d7aa4ccb7a6/lib/openstudio/workflow/util/model.rb#L51-L70

## Detailed Description

At the very least we should provide an override or extra bool parameter.

## Possible Implementation

Straightforward

**Comment by kbenne** [comment]
Two thumbs up for this. So annoying to version translate first. Love this issue.

**Comment by DavidGoldwasser** [comment]
Here is how model is loaded in measure tests
https://github.com/NREL/openstudio-common-measures-gem/blob/develop/lib/measures/ChangeBuildingLocation/tests/change_building_location_test.rb#L39-43
