### ISSUE TITLE
AirLoopHVACUnitarySystem: `Supply Air Flow Rate Method During <XXX> Operation` should be set via related setters/autosize

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#4695]
Issue overview
--------------

`Supply Air Flow Rate Method During <XXX> Operation` should be automatically infered at model time.

## Current Behavior

`Supply Air Flow Rate Method During <XXX> Operation` isn't set by default. E+ shows a warning in the eplusout.err

```
   ** Warning ** AirLoopHVAC:UnitarySystem = AIR LOOP HVAC UNITARY SYSTEM 1
   **   ~~~   ** Method used to determine the cooling supply air flow rate is not specified when cooling coil is present.
   ** Warning ** AirLoopHVAC:UnitarySystem = AIR LOOP HVAC UNITARY SYSTEM 1
   **   ~~~   ** Method used to determine the heating supply air flow rate is not specified when heating coil is present.
```

## Expected Behavior

eg `setSupplyAirFlowRatePerFloorAreaDuringCoolingOperation(1.0)`should set the `Supply Air Flow Rate Method During Cooling Operation` to `FlowPerFloorArea`

autosizeSupplyAirFlowRateDuringCoolingOperation should set it to `SupplyAirFlowRate`

## Steps to Reproduce

```ruby
m = Model.new
u = AirLoopHVACUnitarySystem.new(m)
u.setSupplyAirFlowRatePerFloorAreaDuringCoolingOperation(0.1)
# => true
u.supplyAirFlowRateMethodDuringCoolingOperation.empty?
# => false
u.supplyAirFlowRateMethodDuringCoolingOperation.get
# => ""
```

## Possible Solution

Straightforward.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of OpenStudio (if using an intermediate build, include SHA): develop circa 3.5.0-alpha, 92da27b27de50e076ce3bdc5032e4f348e2231e8

### Context

Found while adding a new regression test. cf https://github.com/NREL/OpenStudio-resources/pull/176/commits/2057e0db8113160da9d21cac1c69efcfbfa3ab6c

**Comment by joseph-robertson** [comment]
Shouldn't `u.supplyAirFlowRateMethodDuringCoolingOperation.is_initialized` return false (i.e., `u.supplyAirFlowRateMethodDuringCoolingOperation.get` shouldn't return "")? Perhaps this is because there is no default specified in the idd choice field?

**Comment by joseph-robertson** [comment]
I think we just need to use `getString(xxx, false, true)` for the getters (like `fanPlacement()`). I.e., "No default, and return uninitalized if empty".
