### ISSUE TITLE
Creating a VS WSHP using UnitarySystem object generates incorrect air flow ratios for UnitarySystemPerformance:Multispeed object

### ISSUE THREAD

**Issue by Nigusse** [NREL/OpenStudio#4715]
Created a Variable Speed WSHP programmatically using *OS:AirLoopHVAC:UnitarySystem* object in Openstudio V3.4 but the *ForwardTranslateAirLoopHVACUnitarySystem* code fails to generate the *UnitarySystemPerformance:Multispeed* object 
correctly. See sample energyplus object output created for water-source VS coils:

```
UnitarySystemPerformance:Multispeed,
  SZ-SYS SPACE1-1 Thermal Zone Unitary System Performance, !- Name
  5,                                      !- Number of Speeds for Heating
  5,                                      !- Number of Speeds for Cooling
  No,                                     !- Single Mode Operation
  ,                                       !- No Load Supply Air Flow Rate Ratio
  1,                                      !- Heating Speed Supply Air Flow Ratio 1
  1,                                      !- Cooling Speed Supply Air Flow Ratio 1
  1,                                      !- Heating Speed Supply Air Flow Ratio 2
  1,                                      !- Cooling Speed Supply Air Flow Ratio 2
  ,                                       !- Heating Speed Supply Air Flow Ratio 3
  ,                                       !- Cooling Speed Supply Air Flow Ratio 3
  ,                                       !- Heating Speed Supply Air Flow Ratio 4
  ,                                       !- Cooling Speed Supply Air Flow Ratio 4
  ,                                       !- Heating Speed Supply Air Flow Ratio 5
  ;                                       !- Cooling Speed Supply Air Flow Ratio 5
```

Inspecting the ForwardTranslateAirLoopHVACUnitarySystem code I'm suspicious of this section https://github.com/NREL/OpenStudio/blob/6a935cab2ae26b4170caf107287df201f4612401/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitarySystem.cpp#L573-L610

Also, I see a typo [CoilCoolingDXMultiSpeed](https://github.com/NREL/OpenStudio/blob/develop/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitarySystem.cpp#L481). This DX cooling coil type should have been *CoilCoolingDXVariableSpeed*, I think. I ran into the same problem when I tried to created a VS air-source heat pump using *OS:AirLoopHVAC:UnitarySystem* as a parent. 

https://github.com/NREL/OpenStudio/blob/6a935cab2ae26b4170caf107287df201f4612401/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitarySystem.cpp#L480-L482
 
## Environment ##
Some additional details about your environment for this issue (if relevant):
-    Platform (Operating system, version): Windows
-    Version of OpenStudio (if using an intermediate build, include SHA): 3.4.0
-    Defect file attached

[in.osm.txt](https://github.com/NREL/OpenStudio/files/9788780/in.osm.txt)

**Comment by Nigusse** [comment]
@jmarrec @kbenne I am documenting the issues and where in the code the problems are. Addressing this issue by fixing what is broken or taking the option to NOT generate the *UnitarySystemPerformance:Multispeed* are the two options we have. I would like to see others weigh in if there is preference for one option over the other.

**Comment by joseph-robertson** [comment]
To clarify, based on your attached in.osm.txt, you are expecting each of UnitarySystemPerformanceMultispeed's "Heating/Cooling Speed Supply Air Flow Ratio X" fields to be "Autosize", correct? I believe you should only get doubles if the AirLoopHVACUnitarySystem's "Supply Air Flow Rate During Heating/Cooling Operation" fields are not "Autosize".
