### ISSUE TITLE
Groom issues related to support Python Measures on GitHub

### ISSUE THREAD

**Issue by tijcolem** [NREL/OpenStudio#4718]
@kbenne @jmarrec There was a ton of work done on for the phase 1 support of Python Measures. I'd like to capture issues related to this for the 3.5.0 release and retag issues for 3.6.0. 

TODO:
 
* #4719
* #4720
* #4721

**Comment by jmarrec** [comment]
@tijcolem I closed all of the ones that were completed and tagged them appropriately. You can retrieve the list via this query: https://github.com/NREL/OpenStudio/issues?q=is%3Aissue+label%3A%22component+-+Python+bindings%22+is%3Aclosed+label%3A%22component+-+Measures%22

**Comment by kbenne** [comment]
I'm going to close this. Reopen if needed. (or add more new issues if something has been missed.)
