### ISSUE TITLE
[Python Workflow] Complete the C++ workflow to match the OpenStudio-workflow gem

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#4721]
* use temp subdirectories for each step
* process output requests from reporting measures
* run the IDF through E+ (as a library or a system call like current)
* run the post processing for reporting measure

**Comment by kbenne** [comment]
One question I have is do we need to strictly follow the current CLI options? My vote is actually no. Let us take this opportunity to clean up any rough edges that we might see in the existing interface.
