### ISSUE TITLE
3.5.0-rc1 RC Testing

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#4722]
Enhancement Request
--------------

A place to collect feedback on the 3.5.0-RC installers. Ideally RC testing is done a **clean** virtual machine.

Get installers from https://github.com/NREL/OpenStudio/releases/tag/v3.5.0-rc1

## Detailed Description

Copy the Examples folder in a location where you can write

```
cd /home/ && mkdir temp && cp -R /usr/local/openstudio-3.5.0-rc1/Examples .
```

When you're done, please report back by posting on this issue, with the following template filled out.

```
## Checklist

### Platform and version: <!--  eg: Ubuntu 18.04, Ubuntu 20.04, macOS 10.15, macOS 11.4, Windows 10 20H2-->

* [ ] I could install the OpenStudio SDK installer
* [ ] I can run `openstudio --version`, `openstudio --help`
* [ ] I can run a normal workflow
     * [ ] `/usr/local/openstudio-3.5.0-rc1/bin/openstudio run -w /usr/local/openstudio-3.5.0-rc1/Examples/compact_osw/compact_ruby_only.osw`
* Experimental `labs` feature
    * [ ] Labs help: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs --help`
    * [ ] Labs ruby execute: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs -e "puts OpenStudio::Model::Model.new()"`
    * [ ] Labs ruby execute require embedded gem: `/usr/local/openstudio-3.5.0-rc1/bin/labs -e "require 'oga'; puts Oga::VERSION"`
    * [ ] Labs python execute: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs -c "print(openstudio.model.Model())"`
    * [ ] Labs ruby workflow `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_ruby_only.osw`
    * [ ] Labs python workflow: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_python_only_twomeasures.osw`
    * [ ] Labs Ruby And Python Workflow: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_ruby_and_python.osw`

## Problems found:

<!-- please describe -->
```

**Comment by jmarrec** [comment]
## Checklist

### Platform and version: Ubuntu 20.04 (clean docker ubuntu:focal image)

* [x] I could install the OpenStudio SDK installer
* [x] I can run `openstudio --version`, `openstudio --help`
* [x] I can run a normal workflow
     * [x] `/usr/local/openstudio-3.5.0-rc1/bin/openstudio run -w /usr/local/openstudio-3.5.0-rc1/Examples/compact_osw/compact_ruby_only.osw`
* Experimental `labs` feature
    * [x] Labs help: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs --help`
    * [x] Labs ruby execute: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs -e "puts OpenStudio::Model::Model.new()"`
    * [x] Labs python execute: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs -c "print(openstudio.model.Model())"`
    * [x] Labs ruby workflow `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_ruby_only.osw`
    * [x] Labs python workflow: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_python_only_twomeasures.osw`


## Problems found:

This segfaults:
* [ ] Labs Ruby And Python Workflow: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_ruby_and_python.osw`

**Comment by jmarrec** [comment]
## Checklist

### Platform and version: Ubuntu 18.04 (clean docker ubuntu:bionic image)

* [x] I could install the OpenStudio SDK installer
* [ ] I can run `openstudio --version`, `openstudio --help`
* [ ] I can run a normal workflow
     * [ ] `/usr/local/openstudio-3.5.0-rc1/bin/openstudio run -w /usr/local/openstudio-3.5.0-rc1/Examples/compact_osw/compact_ruby_only.osw`
* Experimental `labs` feature
    * [ ] Labs help: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs --help`
    * [ ] Labs ruby execute: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs -e "puts OpenStudio::Model::Model.new()"`
    * [ ] Labs python execute: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs -c "print(openstudio.model.Model())"`
    * [ ] Labs ruby workflow `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_ruby_only.osw`
    * [ ] Labs python workflow: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_python_only_twomeasures.osw`
     * [ ] Labs Ruby And Python Workflow: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_ruby_and_python.osw`

## Problems found:

* [ ] I can run `openstudio --version`, `openstudio --help`

```
openstudio --version
openstudio: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by openstudio)
openstudio: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/local/openstudio-3.5.0-rc1/bin/../lib/libopenstudiolib.so)

```

**Comment by jmarrec** [comment]
## Checklist

### Platform and version: Windows 10 20H2 (clean VM)

* [x] I could install the OpenStudio SDK installer
* [ ] I can run `openstudio --version`, `openstudio --help`
* [ ] I can run a normal workflow
     * [ ] `/usr/local/openstudio-3.5.0-rc1/bin/openstudio run -w /usr/local/openstudio-3.5.0-rc1/Examples/compact_osw/compact_ruby_only.osw`
* Experimental `labs` feature
    * [ ] Labs help: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs --help`
    * [ ] Labs ruby execute: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs -e "puts OpenStudio::Model::Model.new()"`
    * [ ] Labs python execute: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs -c "print(openstudio.model.Model())"`
    * [ ] Labs ruby workflow `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_ruby_only.osw`
    * [ ] Labs python workflow: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_python_only_twomeasures.osw`
    * [ ] Labs Ruby And Python Workflow: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_ruby_and_python.osw`

## Problems found:

![image](https://user-images.githubusercontent.com/5479063/197507172-c0ff3668-2d2e-4ffa-ae2e-da092fa14310.png)

**Comment by jmarrec** [comment]
## Checklist

### Platform and version: Windows 11 21H2 (clean VM)

* [x] I could install the OpenStudio SDK installer
* [x] I can run `openstudio --version`, `openstudio --help`
* [x] I can run a normal workflow
     * [x] `C:\openstudio-3.5.0-rc1\bin\openstudio.exe run -w C:\openstudio-3.5.0-rc1\Examples\compact_osw\compact_ruby_only.osw`
* Experimental `labs` feature
    * [x] Labs help: `C:\openstudio-3.5.0-rc1\bin\openstudio.exe labs --help`
    * [x] Labs ruby execute: `C:\openstudio-3.5.0-rc1\bin\openstudio.exe labs -e "puts OpenStudio::Model::Model.new()"`
    * [x] Labs python execute: `C:\openstudio-3.5.0-rc1\bin\openstudio.exe labs -c "print(openstudio.model.Model())"`
    * [x] Labs ruby workflow `C:\openstudio-3.5.0-rc1\bin\openstudio.exe labs run -w C:\openstudio-3.5.0-rc1\Examples\compact_osw\compact_ruby_only.osw`
    * [x] Labs python workflow: `C:\openstudio-3.5.0-rc1\bin\openstudio.exe labs run -w C:\openstudio-3.5.0-rc1\Examples\compact_osw\compact_python_only_twomeasures.osw`
    * [x] Labs Ruby And Python Workflow: `C:\openstudio-3.5.0-rc1\bin\openstudio.exe labs run -w C:\openstudio-3.5.0-rc1\Examples\compact_osw\compact_ruby_and_python.osw`

**Comment by jmarrec** [comment]
## Checklist

### Platform and version: 

**I needed to do `apt install libgomp1 libx11-6` to get energyplus to run**

* [x] I could install the OpenStudio SDK installer
* [x] I can run `openstudio --version`, `openstudio --help`
* [x] I can run a normal workflow
     * [x] `/usr/local/openstudio-3.5.0-rc1/bin/openstudio run -w /usr/local/openstudio-3.5.0-rc1/Examples/compact_osw/compact_ruby_only.osw`
* Experimental `labs` feature
    * [x] Labs help: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs --help`
    * [x] Labs ruby execute: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs -e "puts OpenStudio::Model::Model.new()"`
    * [x] Labs python execute: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs -c "print(openstudio.model.Model())"`
    * [x] Labs ruby workflow `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_ruby_only.osw`
    * [x] Labs python workflow: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_python_only_twomeasures.osw`


## Problems found:

This segfaults (but is a known issue, cf https://github.com/NREL/OpenStudio/issues/4719)
    * [ ] Labs Ruby And Python Workflow: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_ruby_and_python.osw`

**Comment by jmarrec** [comment]
## Checklist

```shell
cd ~/Downloads/ && mkdir temp && cd temp
cp -R /Applications/OpenStudio-3.5.0-rc1/Examples .
openstudio --version
openstudio labs --version
openstudio labs openstudio_version
openstudio labs -e "puts OpenStudio::Model::Model.new()"
openstudio labs -e "require 'oga'; puts Oga::VERSION"
openstudio labs -c "print(openstudio.model.Model())"
openstudio run -w Examples/compact_osw/compact_ruby_only.osw
openstudio labs run -w Examples/compact_osw/compact_ruby_only.osw
openstudio labs run -w Examples/compact_osw/compact_python_only_twomeasures.osw
openstudio labs run -w Examples/compact_osw/compact_ruby_and_python.osw
```

### Platform and version: macOS 12.6, M1 (arm64): CAVEAT, this is the machine on which I built the package

* [x] I could install the OpenStudio SDK installer
* [x] I can run `openstudio --version`, `openstudio --help`
* [x] I can run a normal workflow
     * [x] `/usr/local/openstudio-3.5.0-rc1/bin/openstudio run -w /usr/local/openstudio-3.5.0-rc1/Examples/compact_osw/compact_ruby_only.osw`
* Experimental `labs` feature
    * [x] Labs help: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs --help`
    * [x] Labs ruby execute: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs -e "puts OpenStudio::Model::Model.new()"`
    * [x] Labs ruby execute require embedded gem: `/usr/local/openstudio-3.5.0-rc1/bin/labs -e "require 'oga'; puts Oga::VERSION"`
    * [x] Labs python execute: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs -c "print(openstudio.model.Model())"`
    * [x] Labs ruby workflow `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_ruby_only.osw`
    * [x] Labs python workflow: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_python_only_twomeasures.osw`
    * [x] Labs Ruby And Python Workflow: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_ruby_and_python.osw`

## Problems found:

**Comment by tijcolem** [comment]
## Checklist

### Platform and version: MacOS Monterey 12.6 x86_64 Intel i7  (clean aws mac1.metal)

* [x] I could install the OpenStudio SDK installer
* [x] I can run `openstudio --version`, `openstudio --help`
* [x] I can run a normal workflow
     * [x] `/usr/local/openstudio-3.5.0-rc1/bin/openstudio run -w /home/temp/Examples/compact_osw/compact_ruby_only.osw`
* Experimental `labs` feature
    * [x] Labs help: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs --help`
    * [x] Labs ruby execute: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs -e "puts OpenStudio::Model::Model.new()"`
    * [x] Labs python execute: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs -c "print(openstudio.model.Model())"`
    * [x] Labs ruby workflow `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_ruby_only.osw`
    * [x] Labs python workflow: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_python_only_twomeasures.osw`

## Problems found:

Appears the python is linked to the system 3.8 when it should be using E+

  ```
ec2-user@ip-172-18-9-89 ~ % openstudio labs -c "print(openstudio.model.Model())"
--pyexecute Flag received 1 times.
libc++abi: terminating with uncaught exception of type std::runtime_error: Unable to load library '/Applications/OpenStudio-3.5.0-rc1/lib/libpythonengine.so', reason: 'dlopen(/Applications/OpenStudio-3.5.0-rc1/lib/libpythonengine.so, 0x0005): Library not loaded: '/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/Python'
  Referenced from: '/Applications/OpenStudio-3.5.0-rc1/lib/libpythonengine.so'
  Reason: tried: '/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/Python' (no such file), '/Library/Frameworks/Python.framework/Versions/3.8/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/3.8/Python' (no such file)'
zsh: abort      openstudio labs -c "print(openstudio.model.Model())"
```


* [ ] I can run `openstudio --version`, `openstudio --help`

```
openstudio --version
openstudio: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by openstudio)
openstudio: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/local/openstudio-3.5.0-rc1/bin/../lib/libopenstudiolib.so)
```

What I did:

```
$ apt install software-properties-common && add-apt-repository ppa:ubuntu-toolchain-r/test
$ apt update

$ apt list --upgradable
libgcc1/bionic 1:11.1.0-1ubuntu1~18.04.1 amd64 [upgradable from: 1:8.4.0-1ubuntu1~18.04]
libstdc++6/bionic 11.1.0-1ubuntu1~18.04.1 amd64 [upgradable from: 8.4.0-1ubuntu1~18.04]
```

```
# Upgrade libstdc++6
apt upgrade
```

Then it started working.

-----

I cannot run an E+ workflow, missing some libs. (this is an E+ issue)

```
/usr/local/openstudio-3.5.0-rc1/EnergyPlus/energyplus: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
```

After installing it, I get

```
/usr/local/openstudio-3.5.0-rc1/EnergyPlus/energyplus: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory
```

So the fix was:

```
apt install libgomp1 libx11-6
```

----

This segfaults (but is a known issue, cf https://github.com/NREL/OpenStudio/issues/4719)

     *  Labs Ruby And Python Workflow: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_ruby_and_python.osw`

## Fixes

Adjust CPACK_DEBIAN_PACKAGE_DEPENDS and/or ship the missing SO libs.

**Comment by arif-hanif** [comment]
## Checklist

### Platform and version: MacOS 12.6 Monterey M1 Max ARM

* [x] I could install the OpenStudio SDK installer
* [x] I can run `openstudio --version`, `openstudio --help`
* [x] I can run a normal workflow
     * [x] `/usr/local/openstudio-3.5.0-rc1/bin/openstudio run -w /usr/local/openstudio-3.5.0-rc1/Examples/compact_osw/compact_ruby_only.osw`
* Experimental `labs` feature
    * [x] Labs help: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs --help`
    * [x] Labs ruby execute: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs -e "puts OpenStudio::Model::Model.new()"`
    * [ ] Labs ruby execute require embedded gem: `/usr/local/openstudio-3.5.0-rc1/bin/labs -e "require 'oga'; puts Oga::VERSION"`
    * [ ] Labs python execute: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs -c "print(openstudio.model.Model())"`
    * [ ] Labs ruby workflow `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_ruby_only.osw`
    * [ ] Labs python workflow: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_python_only_twomeasures.osw`
    * [ ] Labs Ruby And Python Workflow: `/usr/local/openstudio-3.5.0-rc1/bin/openstudio labs run -w /home/temp/Examples/compact_osw/compact_ruby_and_python.osw`

## Problems found:

Unable to run many of the labs commands 
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/8672758/198499086-0835d395-f0bf-44b0-b46f-22d131105fa1.png">

**Comment by shorowit** [comment]
- [ ] Not sure if this is the right place for it, but `openstudio labs execute_ruby_script` doesn't treat all following positionals as arguments to the ruby script. First command is successful, second command is not:

![image](https://user-images.githubusercontent.com/5861765/198501122-13dd5dbc-90b1-4771-a1a6-22e3c7a15248.png)

**Comment by tijcolem** [comment]
@shorowit  I'm going to move your issue to a new GitHub issue as 3.5.0-rc testing is done.  @arif-hanif  The python lib issue has been resolved. Thanks for the report.
