### ISSUE TITLE
Delete Changelog?

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4728]
Issue overview
--------------
[CHANGELOG.md](https://github.com/NREL/OpenStudio/blob/develop/CHANGELOG.md) was last updated 4 years ago and it's included in the install. If it's not going to be updated, best to just delete it.

**Comment by tijcolem** [comment]
@shorowit Agreed. We keep track of all the changes in the release notes under https://github.com/NREL/OpenStudio/tree/develop/developer/doc/ReleaseNotes and no reason to duplicate everything in one massive file.

**Comment by shorowit** [comment]
Note that up-to-date release notes are also provided alongside the changelog, so the changelog really does seem superfluous.

![image](https://user-images.githubusercontent.com/5861765/202768841-05684764-919f-46d9-a997-8f0ade807dbc.png)

**Comment by tijcolem** [comment]
@shorowit  I brought the changelog up to date. It is a bit redundant with the release notes but I think it's nice to have one master list of all changes for a quick key search. Thanks for pointing this out. Going to close.
