### ISSUE TITLE
OpenStudio labs: execute_ruby_script fails to forward flag arguments + allow just "openstudio labs script.rb"

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#4729]
Issue overview
--------------

## Current Behavior

```shell
# This works fine
openstudio labs execute_ruby_script myfile.rb arg1 arg2

# This doesn't
openstudio labs execute_ruby_script myfile.rb -x arg2
=> The following argument was not expected: -x
```

## Expected Behavior

All arguments following the filename should be forward as is to the ruby script

## Steps to Reproduce

```shell
$ cat test.rb
raise "You must supply 2 arguments" if ARGV.size != 2
puts "argv0=#{ARGV[0]}, argv1=#{ARGV[1]}"

$ openstudio labs execute_ruby_script myfile.rb -x arg2
```

## Possible Solution

Figure out a way to let CLI11 that it should stop trying to parse anything after filename

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

### Context

@shorowit reported here: https://github.com/NREL/OpenStudio/issues/4722#issuecomment-1294431147

**Comment by jmarrec** [comment]
@shorowit The way to make it work currently is to add a double dash in between the file and the args

test.rb
```
ARGV.each_with_index do |argv, i|
  puts "#{i} - #{argv}"
end
```

```shell
$ os_build_rel/Products/openstudio labs execute_ruby_script test.rb -- -x arg2 -o test
0 - -x
1 - arg2
2 - -o
3 - test
```

**Comment by jmarrec** [comment]
What is clearer:

* Option 1: Arguments isn't shown in the help message, but you can pass extra args with the `--`
```
Executes a ruby file
Usage: Products/os-cli11 labs execute_ruby_script [OPTIONS] path

Positionals:
  path TEXT:FILE REQUIRED     Path to ruby file

Options:
  -h,--help                   Print this help message and exit

Any additional arguments passed after the ruby file are forwarded
```

* Option 2: arguments is shown, but we need an extra message to say that the user must remember to include a `--`

```
Executes a ruby file
Usage: Products/os-cli11 labs execute_ruby_script [OPTIONS] path [arguments...]

Positionals:
  path TEXT:FILE REQUIRED     Path to ruby file
  arguments args              Arguments to pass to the ruby file

Options:
  -h,--help                   Print this help message and exit

If passing extra arguments, please include a double-dash `--` between the ruby file and the extra args.

Example:
   execute_ruby_script test.rb -- -x arg1 -o test
```

**Comment by shorowit** [comment]
I think users are far more likely to be confused by option 2 than option 1, so **my vote is for option 1**. You could even add something to the description like:

```
Positionals:
  path TEXT:FILE REQUIRED     Path to ruby file (additional [ARGUMENTS] can follow)
```

**Comment by jmarrec** [comment]
Retitled to include @shorowit 's comment from here: https://github.com/NREL/OpenStudio/pull/4775#issuecomment-1460454681
