### ISSUE TITLE
BCL server down? 11/19/22

### ISSUE THREAD

**Issue by MisterZam** [NREL/OpenStudio#4743]
Issue overview
--------------
IDK if this is the proper medium for this type of problem. Anyways, both the openstudio and the website cannot browse for components

## Current Behavior
cannot browse for components

## Expected Behavior
can browse for components

## Reference
![Bruh](https://user-images.githubusercontent.com/51112513/202831262-bf7d57d0-3b4b-4ec6-a851-d59b9cc37c0c.png)

**Comment by kflemin** [comment]
@MisterZam, everything should be back online on the BCL side. Feel free to reopen an issue if you run into this issue again. You can also post to the BCL Manifest repo for BCL-specific issues: https://github.com/BuildingComponentLibrary/bcl-manifest/discussions.
