### ISSUE TITLE
Release Version 3.5.0 Ubuntu-20.04.tar.gz does not reference lib/libopenstudiolib.so with relative path

### ISSUE THREAD

**Issue by chriswmackey** [NREL/OpenStudio#4746]
Issue overview
--------------
I am using the `OpenStudio-3.5.0+7b14ce1588-Ubuntu-20.04.tar.gz` that is included in the [OpenStudio 3.5 release](https://github.com/NREL/OpenStudio/releases/tag/v3.5.0) because I need to install OpenStudio in a location other than the default on Ubuntu. However, when I try to run OpenStudio CLI with this installation, I get the following error:

```
/home/ladybugbot/ladybug_tools/openstudio/bin/openstudio: error while loading shared libraries: libopenstudiolib.so: cannot open shared object file: No such file or directory
```

## Current Behavior
I am positive that the `lib/libopenstudiolib.so` file exists and it is right next to the `bin/openstudio` just like it always has been.

From what I can tell, the error above happens because the reference to `libopenstudiolib.so` does not seem to be set relative to the `openstudio` executable in `bin` as it had been in previous releases. I imagine that this issue might have been introduced to handle the fact that the `lib` folder no longer has a single `.so` file in it but has two new files for `libpythonengine.so` and `librubyengine.so`.

## Expected Behavior
I had no issues with installing the past 3 stable releases of OpenStudio in a location other than the default using the Ubuntu-20.04.tar.gz. In all cases, the OpenStudio CLI executed without issues. So I expected OpenStudio 3.5 to also succeed in this case.

## Steps to Reproduce

1. Install OpenStudio on Ubuntu 20.04 in a location other than the default (eg. `/home/ladybugbot/ladybug_tools/openstudio/`).
2. Call the OpenStudio CLI executable from the command line (eg. at `/home/ladybugbot/ladybug_tools/openstudio/bin/openstudio`)
3. I am pretty sure that just checking the `--version` should show the bug but, if not, then passing any OSW to the openstudio executable should show the error.

### Context
I am not able to update our [Pollination cloud computing service](https://www.pollination.cloud/cloud) to OpenStudio 3.5 until this issue is addressed since using the default Ubuntu installation location is not an option for our service. Our customers will be forced to keep using OpenStudio 3.4 given the current situation.

We would be immensely grateful if there could be a patch release of OpenStudio 3.5 with the fixed relative path.

**Comment by tijcolem** [comment]
@chriswmackey  Thanks for the report. As you noticed, we did make some changes to the lib folder structure to include two new .so files - `libpythonengine.so`  `librubyengine.so` as well as `libopenstudiolib.so`. The `openstudio` cli binary has a relative link to `libopenstudiolib.so` and it should load provided the folder structure remains intact. I tested this on clean 20.04 AWS Ubuntu image doing the following and this all ran clean. 

- Download OpenStudio-3.5.0+7b14ce1588-Ubuntu-20.04.tar.gz
`wget https://github.com/NREL/OpenStudio/releases/download/v3.5.0/OpenStudio-3.5.0+7b14ce1588-Ubuntu-20.04.tar.gz`
- Extract to current working directory 
`tar -xvzf OpenStudio-3.5.0+7b14ce1588-Ubuntu-20.04.tar.gz`
- Check version
`./OpenStudio-3.5.0+7b14ce1588-Ubuntu-20.04/usr/local/openstudio-3.5.0/bin/openstudio --version`
`3.5.0+7b14ce1588`
- Run osw example
`./OpenStudio-3.5.0+7b14ce1588-Ubuntu-20.04/usr/local/openstudio-3.5.0/bin/openstudio run -w ./OpenStudio-3.5.0+7b14ce1588-Ubuntu-20.04/usr/local/openstudio-3.5.0/Examples/compact_osw/compact_ruby_only.osw` 

I also moved the extracted directory to a new location to mimic your installation process and this also worked fine. 

- Move extracted directory contents to new location. 
`mv OpenStudio-3.5.0+7b14ce1588-Ubuntu-20.04/usr/local/openstudio-3.5.0/  /home/ubuntu/openstudio-3.5.0` 
- Check version
`/home/ubuntu/openstudio-3.5.0/bin/openstudio --version`
`3.5.0+7b14ce1588`
- Run osw example
`/home/ubuntu/openstudio-3.5.0/bin/openstudio run -w ./openstudio-3.5.0/Examples/compact_osw/compact_ruby_only.osw`

You can view the lib linkages using ldd. `openstudio` is linked relative to `libopenstudiolib.so` even after the move. 

```
ubuntu@ip-172-18-9-103:~$ ldd openstudio-3.5.0/bin/openstudio 
	linux-vdso.so.1 (0x00007ffc855a1000)
	libopenstudiolib.so => /home/ubuntu/openstudio-3.5.0/bin/../lib/libopenstudiolib.so (0x00007f4433c72000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4433c65000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4433c42000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4433a60000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4433a45000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4433853000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4433702000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f443941a000)
```

Could you try and run the same steps as I did above and see if that works for you?

**Comment by chriswmackey** [comment]
Thank you for testing this so quickly and getting back to me, @tijcolem . I am also sorry that it seems likely that the title of the issue might be incorrect.

I'm still to figure out why this had worked without issues in previous OpenStudio releases but I have a hunch and a question for you: is it possible that this `lib/libopenstudiolib.so` was not required to run the OpenStudio executable in earlier releases and it just became a requirement in version 3.5?

[You can see the commands that I am using to setup the OpenStudio installation here on our GitHub](https://github.com/ladybug-tools/honeybee-energy/blob/761f189fc094f6a681866a04aa95e19112660ccb/build_image.sh#L11-L18) and they appear to be identical to the ones that you are using (copying the entire directory).

However, I just realized that [this part of the Dockerfile that is setting up the OpenStudio installation in our docker image](https://github.com/ladybug-tools/honeybee-energy/blob/761f189fc094f6a681866a04aa95e19112660ccb/Dockerfile#L26-L31) only copies over a fraction of these files. I realize that I am not actually copying the `lib` folder in this process and I think we did this originally to make our Docker images as slim as possible since we don't need things like the Radiance installation that ships with OpenStudio. It looks like this lib folder has now become a requirement and I need to copy it as well.

I am going to test this now but, if you know of any other directories that are now required in order to run the OpenStudio CLI, I will make sure these are copied as well and that should get us to a quick resolution of this issue.

**Comment by tijcolem** [comment]
@chriswmackey Yes, we changed a lot in 3.5.0 release regarding the shared libs largely due to the Python Measure support we are adding (currently experimental in 3.5.0). The openstudio cli is now a very lightweight binary that loads and uses those shared libs in the `lib` folder. You'll have to copy the `lib` folder for 3.5.0 it to work.  I'll keep this issue open until you confirm that things work but that should fix your problem.

**Comment by chriswmackey** [comment]
Hey @tijcolem ,

I finally got to test it all of the way through our system and you were absolutely right that it was just the `lib` folder that needed to be copied. The new structure makes a lot of sense and I'm sorry to have raised a false alarm here about not understanding it. Maybe this issue will help others who are similarly adjusting to the new structure,

In any event, I'll close the issue and thanks again for the support!
