### ISSUE TITLE
On mac clicking the "Open Results Viewer .. " button launches the app but does not bring it to the front

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#479]
I confirmed that that this does not happen on windows. Pretty minor but wanted to get bug filed. When Gregor saw this happen with doc hidden, it wasn't clear that the app was even launching.

Kyle, fell free to re-assign if you think someone else can do this. I tested this on 10.8.4 non dev machine.

**Comment by jmarrec** [comment]
Irrelevant today (no more results viewer)
