### ISSUE TITLE
XSD/Schematron error on some Windows filesystems/directories

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4791]
Issue overview
--------------
Some BEopt users are getting openstudio errors because of how their file systems or directories are set up. (Some IT departments, like DOE, are moving user's directories to the cloud or OneDrive, or using virtual machines, and it's causing headaches.) It results in errors like these:
`Error: boost::filesystem::status: Incorrect function [system:1]: "//home.redacted.edu/home/redacted/adit/My Documents/BEopt_3.0.0/TEMP1/1/run/../hpxml.xml"`
and
`Error: D:\OSN\src\utilities\xml\XMLValidator.cpp@187 : Schema 'C:/Program Files (x86)/NREL/BEopt_3.0.0/Include/OpenStudio-HPXML/HPXMLtoOpenStudio/resources/hpxml_schema/HPXML.xsd' cannot be opened`

These are from two different users. Both related to openstudio not finding a file when doing XSD or schematron validation. The ruby code that calls these openstudio methods has no trouble with the filepaths.

Here's essentially the code that we're running. Run `openstudio test.rb` from inside this:
[os_validation.zip](https://github.com/NREL/OpenStudio/files/10573276/os_validation.zip)

Obviously it will only throw an error under specific filesystem/directory conditions.

**Comment by jmarrec** [comment]
If possible I think a potential workaround for now would be to map this networked drive to a drive letter (like `Y:/`or something), for eg: https://answers.microsoft.com/en-us/windows/forum/all/mapping-one-drive-to-a-drive-letter/83bfecfb-19ee-49c5-83c9-a2f6350b179c

**Comment by jmarrec** [comment]
I created a fake network drive: https://github.com/openstudiocoalition/OpenStudioApplication/wiki/Create-a-mapped-network-drive-in-Windows-for-testing-purposes

So I have:

* in reality; stuff is stored at `C:/Users/julien/FakeNetworkSharedDrive/os_validation`
* I can access it at `//DESKTOP-AFHNVM1/Users/julien/FakeNetworkSharedDrive/os_validation`
* And also this is mapped to Y:, so `Y:/os_validation`

This works fine:

```
C:\openstudio-3.5.1\bin\openstudio.exe C:\Users\julien\FakeNetworkSharedDrive\os_validation\test.rb
C:\openstudio-3.5.1\bin\openstudio.exe Y:\os_validation\test.rb
```

This doesn't, turns out libxml2 is having trouble when the XSD is trying to include another XSD via xsi:schemaLocation

```
$ C:\openstudio-3.5.1\bin\openstudio.exe //DESKTOP-AFHNVM1/Users/julien/FakeNetworkSharedDrive/os_validation/test.rb

this_dir=//DESKTOP-AFHNVM1/Users/julien/FakeNetworkSharedDrive/os_validation
Validating against XSD...
[openstudio.XMLValidator] <-1> Treating schema as a regular XSD
I/O warning : failed to load external entity "/DESKTOP-AFHNVM1/Users/julien/FakeNetworkSharedDrive/os_validation/HPXMLBaseElements.xsd"
[openstudio.XMLValidator] <1> xsdValidate.schemaParserError: Element '{http://www.w3.org/2001/XMLSchema}include': Failed to load the document '/DESKTOP-AFHNVM1/Users/julien/FakeNetworkSharedDrive/os_validation/HPXMLBaseElements.xsd' for inclusion.

[openstudio.XMLValidator] <1> xsdValidate.schemaParserError: Element '{http://www.w3.org/2001/XMLSchema}include': Failed to load the document '/DESKTOP-AFHNVM1/Users/julien/FakeNetworkSharedDrive/os_validation/HPXMLBaseElements.xsd' for inclusion.

[openstudio.XMLValidator] <0> xsdValidate.parseFileError: XML warning 17.1879: Element '{http://hpxmlonline.com/2019/10}HPXML', attribute '{http://www.w3.org/2001/XMLSchema-instance}schemaLocation': The value must consist of tuples: the target namespace name and the document's URI.
    at /DESKTOP-AFHNVM1/Users/julien/FakeNetworkSharedDrive/os_validation/base.xml:2
[openstudio.XMLValidator] <0> xsdValidate.parseFileError: XML warning 17.1879: Element '{http://hpxmlonline.com/2019/10}HPXML', attribute '{http://www.w3.org/2001/XMLSchema-instance}schemaLocation': The value must consist of tuples: the target namespace name and the document's URI.
    at /DESKTOP-AFHNVM1/Users/julien/FakeNetworkSharedDrive/os_validation/base.xml:2
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1845: Element '{http://hpxmlonline.com/2019/10}HPXML': No matching global declaration available for the validation root.
    at /DESKTOP-AFHNVM1/Users/julien/FakeNetworkSharedDrive/os_validation/base.xml:2
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1845: Element '{http://hpxmlonline.com/2019/10}HPXML': No matching global declaration available for the validation root.
    at /DESKTOP-AFHNVM1/Users/julien/FakeNetworkSharedDrive/os_validation/base.xml:2
false
Validating against Schematron...
[openstudio.XMLValidator] <-1> Treating schema as a Schematron, converting to an XSLT StyleSheet.
[openstudio.XMLValidator] <-1> Saved transformed XSLT Stylesheet at 'C:/Users/julien/AppData/Local/Temp/xmlvalidation-1675693751-0/EPvalidator_stylesheet.xslt'.
[openstudio.XMLValidator] <-1> Transformed Schematron to an XSLT Stylesheet and saved it at C:/Users/julien/AppData/Local/Temp/xmlvalidation-1675693751-0/EPvalidator_stylesheet.xslt.
true
[openstudio.XMLValidator] <-2> Removed temporary directory with 4 files
```

**Comment by jmarrec** [comment]
If I were to edit HPXML.xsd's xsi:schemaLocation to be an absolute path  it would work, and same in XPXMLBaseElements.xsd that points to HPXMLDataTypes.xsd


```diff
-    <xs:include schemaLocation="HPXMLBaseElements.xsd"/>
+    <xs:include schemaLocation="//DESKTOP-AFHNVM1/Users/julien/FakeNetworkSharedDrive/os_validation/HPXMLBaseElements.xsd"/>

**Comment by jmarrec** [comment]
This is somewhat similar to this issue: https://stackoverflow.com/questions/5948127/xml-validation-nested-xsd-and-unc-paths

**Comment by jmarrec** [comment]
Ok I tracked down the issue down to the libxml2's xmlCanonicPath. 

https://gitlab.gnome.org/GNOME/libxml2/-/blob/15c9f4353311c7b765e9e72e63779a161c21f010/uri.c#L2425-2427

We pass it as "//<path>" so the leading '/' is removed and then it gets super confused.


```
>	openstudiolib.dll!xmlCanonicPath(const unsigned char * path) Line 2412	C
 	openstudiolib.dll!xmlNewInputFromFile(_xmlParserCtxt * ctxt, const char * filename) Line 1565	C
 	openstudiolib.dll!xmlDefaultExternalEntityLoader(const char * URL, const char * ID, _xmlParserCtxt * ctxt) Line 4028	C
 	openstudiolib.dll!xmlLoadExternalEntity(const char * URL, const char * ID, _xmlParserCtxt * ctxt) Line 4089	C
 	openstudiolib.dll!xmlCtxtReadFile(_xmlParserCtxt * ctxt, const char * filename, const char * encoding, int options) Line 15411	C
 	openstudiolib.dll!xmlSchemaAddSchemaDoc(_xmlSchemaParserCtxt * pctxt, int type, const unsigned char * schemaLocation, _xmlDoc * schemaDoc, const char * schemaBuffer, int schemaBufferLen, _xmlNode * invokingNode, const unsigned char * sourceTargetNamespace, const unsigned char * importNamespace, _xmlSchemaBucket * * bucket) Line 10639	C
 	openstudiolib.dll!xmlSchemaParse(_xmlSchemaParserCtxt * ctxt) Line 21463	C
 	openstudiolib.dll!openstudio::XMLValidator::xsdValidate() Line 331	C++
 	openstudiolib.dll!openstudio::XMLValidator::validate(const boost::filesystem::path & xmlPath) Line 298	C++

```

**Comment by shorowit** [comment]
Since there is a bug in an upstream library and I am able to workaround it on my end, there's probably nothing else needed from the OS team. Thanks for looking into this, @jmarrec.
