### ISSUE TITLE
Add Autosizing/Hardsizing Methods from OpenStudio-Standards

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#4792]
Enhancement Request
--------------
Implement autosize/hardsize-related methods from OpenStudio-Standards that have proven useful but which have not yet been implemented in C++.

## Detailed Description
The autosizing methods below fall into several categories. 
1. They are calculated using a combination of other autosizable fields, for example `Coil:Cooling:Water.autosizedDesignCoilLoad()`
2. They pull sizing values from an associated object, for example, some values of a `ThermalZone` actually come from the `Sizing:Zone` object associated with it.
3. They are utility methods that have proven useful and should be in C++.

The Ruby implementations of these methods is available in the openstudio-standards files linked below. Some of the fuel-related methods should probably be implemented on the ModelObject classes instead of on Model.

## Possible Implementation

[Siz.AirLoopHVAC.rb](https://github.com/NREL/openstudio-standards/blob/ba5168e63a87ac25d6092a61658f0741a0f8e2e8/lib/openstudio-standards/hvac_sizing/Siz.AirLoopHVAC.rb)
```
OpenStudio::Model::AirLoopHVAC

  autosizedSumMinimumHeatingAirFlowRates()

  autosizedSumAirTerminalMaxAirFlowRate()
```

[Siz.CoilCoolingWater.rb](https://github.com/NREL/openstudio-standards/blob/ba5168e63a87ac25d6092a61658f0741a0f8e2e8/lib/openstudio-standards/hvac_sizing/Siz.CoilCoolingWater.rb)
```
OpenStudio::Model::CoilCoolingWater
  
  autosizedDesignCoilLoad()
```

[Siz.ThermalZone.rb](https://github.com/NREL/openstudio-standards/blob/ba5168e63a87ac25d6092a61658f0741a0f8e2e8/lib/openstudio-standards/hvac_sizing/Siz.ThermalZone.rb)
```
OpenStudio::Model::ThermalZone

  autosizedMaximumOutdoorAirFlowRate()

  autosizedMinimumOutdoorAirFlowRate()

  autosizedCoolingDesignAirFlowRate()
  
  autosizedHeatingDesignAirFlowRate()
  
  coolingDesignLoad()
  
  designAirFlowRate()
  
  heatingDesignLoad()
  
  heating_fuels()
  
  cooling_fuels()
```

[Siz.HeatingCoolingFuels.rb](https://github.com/NREL/openstudio-standards/blob/ba5168e63a87ac25d6092a61658f0741a0f8e2e8/lib/openstudio-standards/hvac_sizing/Siz.HeatingCoolingFuels.rb) 
```
OpenStudio::Model::Model

  plant_loop_heating_fuels()
  
  plant_loop_cooling_fuels()
  
  coil_heating_fuels()
  
  coil_heat_type()
  
  airloop_primary_heat_type()
  
  zone_equipment_heat_type()
  
  coil_cooling_fuels()
  
  zone_equipment_heating_fuels()
  
  zone_equipment_cooling_fuels()
  
  zone_airloop_heating_fuels()
  
  zone_airloop_cooling_fuels()
```

Also add all the Ruby methods defined in these files that aren't already in OpenStudio C++, which will enable a lot of code and files to be removed from openstudio-results measure, as pointed out by @eringold.

https://github.com/NREL/openstudio-common-measures-gem/tree/develop/lib/measures/openstudio_results/resources

**Comment by asparke2** [comment]
@tijcolem here are the methods that are left over after comparing the Ruby to the C++. Happy to discuss implementation details if you want.

**Comment by eringold** [comment]
+100, so these files can be removed from openstudio-results: https://github.com/NREL/openstudio-common-measures-gem/tree/develop/lib/measures/openstudio_results/resources

**Comment by asparke2** [comment]
@eringold Good call, I had only been looking at openstudio-standards, but these methods in the results measure should also be moved to C++.

**Comment by jmarrec** [comment]
I always found it quite weird that we go fetch into the `TabularDataWithStrings` and not the dedicated `ComponentSizes` table.

openstudio-standards does:

```sql
SELECT Value FROM tabulardatawithstrings
  WHERE ReportName='ComponentSizingSummary'
    AND ReportForString='Entire Facility'
    AND TableName='AirLoopHVAC'
    AND ColumnName='Sum of Air Terminal Minimum Heating Flow Rates'
    AND RowName='VAV WITH REHEAT'
    AND Units='m3/s'
```

When we could do

```sql
SELECT Value FROM ComponentSizes
  WHERE CompType = "AirLoopHVAC"
    AND Description = "Sum of Air Terminal Minimum Heating Flow Rates"
    AND Units='m3/s'
    AND CompName='VAV WITH REHEAT' 
```

But that's kinda fine. The issue is more that what the OS SDK does is a lot worse though...

It goes into the InitializationSummary report, table "Component Sizing Information", which is an absolute mess in the SQL file.
It does a first sql call to get the RowNames that match the name of the component. Then it **loops** on every row until it finds the specific one it's looking for, then does a final call for the Value itself. 

What the two versions above accomplish in a single sql call could potentially take 11 sql calls in this specific example (since there are 9 rowNames returned)...

I seem to recall that in the past E+ **did** have more information in the Initialization Summary than in ComponentSizes, but I would hope that it's been resolved since (or can be)

https://github.com/NREL/OpenStudio/blob/3561eb529cc1ed778222958badd4320749efe7ef/src/model/ModelObject.cpp#L228-L377

**Comment by jmarrec** [comment]
I've tested it, only a handful of objects aren't in componentssizes. I'll make it default to the efficient query, only those will do the inefficient one. And I'll implement the missing ones. Should I have a question on implementation details, do I reach you here or on slack?

**Comment by jmarrec** [comment]
I hadn't realized at first that the vast majority of the methods are about fuelTypes and that has nothing to do with SQL. I may break this issue into 2 PRs.

**Comment by jmarrec** [comment]
I don't think these two actually work: `ThermalZone::autosizedMaximumOutdoorAirFlowRate` / `autosizedMinimumOutdoorAirFlowRate` : https://github.com/NREL/openstudio-standards/blob/ba5168e63a87ac25d6092a61658f0741a0f8e2e8/lib/openstudio-standards/hvac_sizing/Siz.ThermalZone.rb#L5-L17

**Comment by jmarrec** [comment]
@asparke2 there's a typo here in the time being FYI: https://github.com/NREL/openstudio-standards/blob/ba5168e63a87ac25d6092a61658f0741a0f8e2e8/lib/openstudio-standards/hvac_sizing/Siz.HeatingCoolingFuels.rb#L618

**Comment by jmarrec** [comment]
Breaking the issue in two: the fuel-related part is at https://github.com/NREL/OpenStudio/issues/4798
