### ISSUE TITLE
ScheduleFixedInterval ignores leap day on forward translation

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio#4793]
Issue overview
--------------
Forward translation of ScheduleFixedInterval (to ScheduleCompact) appears to ignore the calendar year.

## Current Behavior
Where is 02/29?

`OS:ScheduleFixedInterval` has 8784 values (for hourly values of, e.g., year 2012). Then the forward translated schedule looks like:

```
Schedule:Compact,
  cooling sequential fraction,            !- Name
  Fractional,                             !- Schedule Type Limits Name

  ...

  Through: 02/27,                         !- Field 229
  For: AllDays,                           !- Field 230
  Until: 24:00,                           !- Field 231
  1,                                      !- Field 232
  Through: 02/28,                         !- Field 233
  For: AllDays,                           !- Field 234
  Until: 24:00,                           !- Field 235
  1,                                      !- Field 236
  Through: 03/01,                         !- Field 237
  For: AllDays,                           !- Field 238
  Until: 24:00,                           !- Field 239
  1,                                      !- Field 240
  Through: 03/02,                         !- Field 241
  For: AllDays,                           !- Field 242
  Until: 24:00,                           !- Field 243
  1,                                      !- Field 244

  ...

  Through: 12/31,                         !- Field 1457
  For: AllDays,                           !- Field 1458
  Until: 24:00,                           !- Field 1459
  1,                                      !- Field 1460
  Through: 01/01,                         !- Field 1461
  For: AllDays,                           !- Field 1462
  Until: 24:00,                           !- Field 1463
  1;                                      !- Field 1464
```
## Steps to Reproduce

1.
2.
3.
4.

## Possible Solution
I'm fairly certain that this is happening because [this Date ctor](https://github.com/NREL/OpenStudio/blob/develop/src/utilities/time/Date.cpp#L208-L211) returns an [assumed year different than that of the YearDescription object](https://github.com/NREL/OpenStudio/blob/develop/src/utilities/time/Date.cpp#L125-L126).

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

**Comment by shorowit** [comment]
Does it really write out every day even when the value is unchanged from the previous day? Or is this just a made-up example?

**Comment by joseph-robertson** [comment]
It does. I copied this from an actual run.

**Comment by joseph-robertson** [comment]
Lots of interesting things going on with timeseries.
