### ISSUE TITLE
Do not warn about very small rotations in illuminance maps in energyplus forward translator (Bugzilla #402)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#48]
On 2011-12-02 14:28:30, @macumber wrote:

> E.g. -6.06254e-031 radians

On 2012-01-13 15:22:02, @DavidGoldwasser wrote:

> Updated out of date Milestone Targer

On 2012-01-16 14:50:24, @DavidGoldwasser wrote:

> I need to retest this. Use geo-location to introduce minor angle.

Keywords: Invalid?

**Comment by DavidGoldwasser** [comment]
Without using SketchUp geo-location shouldn't hit this anymore.
