### ISSUE TITLE
Allow Zero Capacity Specification for Cooling and Heating Coils

### ISSUE THREAD

**Issue by TiejunWu** [NREL/OpenStudio#4807]
Enhancement Request
--------------
Currently in OpenStudio SDK, if I set the nominal/design capacity of a cooling or heating coil to 0 value. OpenStudio default the capacity field to "autosize" when generating the IDF file. I wonder if you can improve the code to pass the user specified zero capacity value to EnergyPlus IDF field?

## Detailed Description
As a user interface developer relying on OpenStudio to translate information to EnergyPlus IDF, sometimes we have the situation that user specified a system with cooling / heating coil, but in our own sizing calculation determined that the coil should have zero capacity. Then when we try to run energy simulation through OpenStudio with autosizing turned off in EnergyPlus, we will get an  EnergyPlus error saying that the coil capacity is set to be autosized  but system sizing is turned off.

Currently our workaround is that when the coil is sized to zero capacity, we will set the coil to have a non-zero capacity value but set the coil to be always off with schedule.

## Possible Implementation
One suggestion for possible implementation is to add an option at the model level called "AllowZeroCapacityCoil " and default it to False. When this option is set to True, OpenStudio will translate user specified coil capacity to EnergyPlus even if the coil capacity is 0.  This will allow interface developers the flexibility to set the coil size to 0 rather than relying on a workaround.

**Comment by jmarrec** [comment]
@TiejunWu Could you give me an example of a Coil that exhibit this behavior please?

```ruby
include OpenStudio::Model
m = Model.new
c = CoilHeatingWater.new(m)
c.setRatedCapacity(0.0)
p = PlantLoop.new(m) # so it's ForwardTranslated
p.addDemandBranchForComponent(c)
ft = OpenStudio::EnergyPlus::ForwardTranslator.new
w = ft.translateModel(m)
puts w.getObjectsByType('Coil:Heating:Water')
```

```diff
Coil:Heating:Water,
  Coil Heating Water 1,                   !- Name
  Always On Discrete,                     !- Availability Schedule Name
  Autosize,                               !- U-Factor Times Area Value {W/K}
  Autosize,                               !- Maximum Water Flow Rate {m3/s}
  Node 6,                                 !- Water Inlet Node Name
  Node 7,                                 !- Water Outlet Node Name
  ,                                       !- Air Inlet Node Name
  ,                                       !- Air Outlet Node Name
  UFactorTimesAreaAndDesignWaterFlowRate, !- Performance Input Method
+ 0,                                      !- Rated Capacity {W}
  82.2,                                   !- Rated Inlet Water Temperature {C}
  16.6,                                   !- Rated Inlet Air Temperature {C}
  71.1,                                   !- Rated Outlet Water Temperature {C}
  32.2,                                   !- Rated Outlet Air Temperature {C}
  0.5;                                    !- Rated Ratio for Air and Water Convection

**Comment by jmarrec** [comment]
@TiejunWu I have a feeling this might be a case of you trying to set a value and thinking it's accepted when really it's not. Some coils have in the IDD (and that comes from E+ not us) `\minimum >0.0`. One example is `OS:Coil:Cooling:DX:VariableRefrigerantFlow`

```
Coil:Cooling:DX:VariableRefrigerantFlow,
[...]
  N1 , \field Rated Total Cooling Capacity
       \required-field
       \type real
       \units W
       \minimum> 0.0
       \autosizable
       \note Cooling capacity excluding supply air fan heat
[...]
```

**When you construct such an object, the capacity is "Autosize". If you try to set it to 0.0, it will return `False` and leave the capacity as Autosized.**

```
[1] temp(main)> m = Model.new
=> #<OpenStudio::Model::Model:0x000000013195cbf8 @__swigtype__="_p_openstudio__model__Model">
[2] temp(main)> cc = CoilCoolingDXVariableRefrigerantFlow.new(m)
=> #<OpenStudio::Model::CoilCoolingDXVariableRefrigerantFlow:0x0000000131825f78 @__swigtype__="_p_openstudio__model__CoilCoolingDXVariableRefrigerantFlow">
[3] temp(main)> puts cc
OS:Coil:Cooling:DX:VariableRefrigerantFlow,
  {18393820-ad0f-4b27-b557-cd09307efd99}, !- Handle
  Coil Cooling DX Variable Refrigerant Flow 1, !- Name
  {7400479e-c178-4fd6-8dda-b8625c815efc}, !- Availability Schedule
  autosize,                               !- Rated Total Cooling Capacity {W}
  autosize,                               !- Rated Sensible Heat Ratio
  autosize,                               !- Rated Air Flow Rate {m3/s}
  {2798154f-e95f-4512-8efc-a17bec3c675a}, !- Cooling Capacity Ratio Modifier Function of Temperature Curve
  {f45ba596-65ff-42b8-9c36-c73f6082bc7a}; !- Cooling Capacity Modifier Curve Function of Flow Fraction

=> nil
[4] temp(main)> cc.isRatedTotalCoolingCapacityAutosized
=> true
[5] temp(main)> cc.setRatedTotalCoolingCapacity(0.0)
=> false
[6] temp(main)> cc.isRatedTotalCoolingCapacityAutosized
=> true
```

If you set it to almost 0.0, then it's accepted:

```
[7] temp(main)> cc.setRatedTotalCoolingCapacity(0.0000000001)
=> true
```

In this is the case, then it works as expected.

**Comment by TiejunWu** [comment]
@jmarrec Thanks! You are right. I went back and looked at the several coils that I was attempting to set a zero capacity. 

Coil:Heating:Gas:MultiStage
Coil:Heating:DX:VariableRefrigerantFlow
Coil:Cooling:DX:SingleSpeed
Coil:Cooling:DX:VariableRefrigerantFlow

All of these coils require capacity to be >0 in EnergyPlus idd. So my current workaround is to pass a non-zero capacity and set the availability to be not available.

**Comment by shorowit** [comment]
FYI, if you do this at the beginning of your code:
`model.setStrictnessLevel('None'.to_StrictnessLevel)`

then OpenStudio won't check whether values are invalid and will just do whatever assignments you tell it. In this case, it would assign zero for those coils and you would get an E+ error when trying to run the simulation. I don't know if you want that behavior, but it's available to you.
