### ISSUE TITLE
Support Conan 2.0

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#4818]
Issue overview
--------------

Conan 2.0 has been officially released and includes a number of API breaking changes. Currently we can't build with conan 2.0

Linked issue (where most of the work will be): 

* https://github.com/NREL/conan-openstudio-ruby/issues/47

**Comment by wnykuang** [comment]
New to the project and cmake/conan eco system. I notice the cmake-conan still does not support conan 2.0 yet. Is it the reason it broke?  Correct me if I am wrong.

https://github.com/conan-io/cmake-conan <- is it the reason?

**Comment by wnykuang** [comment]
Just curious, is it possible? Since the cmake-conan hasn't supported conan 2.0 yet: 

https://github.com/conan-io/cmake-conan

I am new to the project and Cmake ecosystem, maybe I am wrong.

**Comment by tijcolem** [comment]
Hi @wnykuang!  Using 2.0 should be possible but it's broken as of now, so you should install the latest 1.X series which I believe is 1.59 https://pypi.org/project/conan/1.59.0/

**Comment by wnykuang** [comment]
> Hi @wnykuang!  Using 2.0 should be possible but it's broken as of now, so you should install the latest 1.X series which I believe is 1.59 https://pypi.org/project/conan/1.59.0/

Yeah, I built the project with 1.48since the script(I bellevue it's CMake-Conan) indicate. 
Just curious whether it's possible to support 2.0 from ourside if CMake-Conan doesn't support it yet. 

(I spent a while to try to build it 2.0 and figured out the version issue)

**Comment by jmarrec** [comment]
This is a very good point.
But this isn't a strong necessity as of now, just rely on conan 1.59, I'm just logging it in an issue for later.
Cmake conan will either catchup or we'll just generate a conanfile.txt and call conan on it to match the preferred 2.0 workflow. For now, let's just focus on releasing OS sdk 3. :)

**Comment by jmarrec** [comment]
FYI there's a develop2 branch with experimental support on https://github.com/conan-io/cmake-conan/tree/develop2

**Comment by wnykuang** [comment]
Interesting! I didn't notice it. Thanks for the heads-up, let me take a look!

**Comment by jmarrec** [comment]
> Interesting! I didn't notice it. Thanks for the heads-up, let me take a look!

That was announced just yesterday on twitter by conanio :)

**Comment by shorowit** [comment]
@jmarrec @kbenne Seems like this was addressed by #5137. Close the issue?
