### ISSUE TITLE
Wrap Coil:UserDefined

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/OpenStudio#4823]
Enhancement Request
--------------
Add the Coil:UserDefined component as an object in OpenStudio.

## Detailed Description
The Coil:UserDefined component allows a user to specify a generic coil object and provide their own calculations for its operation in EMS code. This is similar to the PlantComponent:UserDefined object, which is already wrapped as an object in OpenStudio. 

## Possible Implementation
See the implementation for PlantComponentUserDefined.

**Comment by brianlball** [comment]
https://github.com/NREL/OpenStudio/issues/4449
i'm giving this a go.  It will be a WaterToAirComponent, so 1 airloop and 1 plantloop

**Comment by brianlball** [comment]
https://github.com/NREL/OpenStudio/pull/4825
