### ISSUE TITLE
OpenStudio temp dir errors due to collisions 

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4824]
Issue overview
--------------
The ResStock team has been seeing intermittent errors like this:

`/__w/get-resstock/get-resstock/resources/hpxml-measures/HPXMLtoOpenStudio/resources/xmlvalidator.rb:23: [BUG] Segmentation fault at 0x00007fea7d60c88d [1000](https://github.com/NREL/get-resstock/actions/runs/4379849953/jobs/7666240835#step:5:1001)ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux] [1001](https://github.com/NREL/get-resstock/actions/runs/4379849953/jobs/7666240835#step:5:1002) [1002](https://github.com/NREL/get-resstock/actions/runs/4379849953/jobs/7666240835#step:5:1003)-- Control frame information ----------------------------------------------- [1003](https://github.com/NREL/get-resstock/actions/runs/4379849953/jobs/7666240835#step:5:1004)c:0023 p:---- s:0231 e:000230 CFUNC  :validate [1004](https://github.com/NREL/get-resstock/actions/runs/4379849953/jobs/7666240835#step:5:1005)c:0022 p:0033 s:0226 e:000225 METHOD /__w/get-resstock/get-resstock/resources/hpxml-measures/HPXMLtoOpenStudio/resources/xmlvalidator.rb:23`

and

`Building ID: 160. Upgrade Name: Baseline. Job ID: 1. [6642](https://github.com/NREL/resstock/actions/runs/4387659768/jobs/7683221795#step:5:6643)[openstudio.measure.OSRunner] <1> Cannot find current Workflow Step [6643](https://github.com/NREL/resstock/actions/runs/4387659768/jobs/7683221795#step:5:6644)[openstudio.measure.OSRunner] <1> Cannot find current Workflow Step [6644](https://github.com/NREL/resstock/actions/runs/4387659768/jobs/7683221795#step:5:6645)[openstudio.XMLValidator] <2> Writing to file failed for /tmp/xmlvalidation-1678478194-0/EPvalidator_stylesheet.xslt`

The second error message in particular suggests that there is some kind of collision happening related to the XSLT file created for Schematron validation.

Looking at the source code, this appears like it might be the culprit:
https://github.com/NREL/OpenStudio/blob/433e0de51a8c109c7354c1bf222f5479117c2f71/src/utilities/core/FilesystemHelpers.cpp#L174

If you are running lots of simulations in parallel, it appears that two OS CLIs can have temp dir collisions.

@nmerket  @joseph-robertson

**Comment by shorowit** [comment]
Note that we were able to successfully [work around the issue](https://github.com/NREL/OpenStudio-HPXML/pull/1316) by providing our own temporary dir to OpenStudio for XSLT generation when performing Schematron validation.

It looks like gbxml uses this `openstudio::filesystem::create_temporary_directory` method, so that might be similarly impacted?

**Comment by wnykuang** [comment]
Found a niche in reading the snippet, under the while loop:

https://github.com/NREL/OpenStudio/blob/42683d615dd470d90390175c1fdc884039dbd767/src/utilities/core/FilesystemHelpers.cpp#L171

The `attempts` hasn't been updated.
