### ISSUE TITLE
Daylight sensor placement difference between Windows and Linux

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/OpenStudio#4831]
Issue overview
--------------
This bug came up in openstudio-standards regression testing.
There is a difference in the OS models generated on a Windows machine vs. a Linux machine.

## Current Behavior

Using the Windows-generated model as the expected regression test result generates this error in the regression test in a Linux container:
************************************************************************
```
*** SecondarySchool-90.1-2016-ASHRAE 169-2013-4A, Time: 44 sec ***
For OS:Daylighting:Control called 'Aux_Gym_ZN_1_FLR_1 Daylt Sensor 2'  'Position X-Coordinate': true model = '12.0', compare model = '3.0'
For OS:Daylighting:Control called 'Aux_Gym_ZN_1_FLR_1 Daylt Sensor 2'  'Position Y-Coordinate': true model = '8.65277', compare model = '2.8889'
For OS:ThermalZone called 'Aux_Gym_ZN_1_FLR_1 ZN'  'Fraction of Zone Controlled by Primary Daylighting Control': true model = '0.999', compare model = '0.5'
For OS:ThermalZone called 'Aux_Gym_ZN_1_FLR_1 ZN'  'Fraction of Zone Controlled by Secondary Daylighting Control': true model = '0.0', compare model = '0.499'
For OS:ThermalZone called 'LIBRARY_MEDIA_CENTER_ZN_1_FLR_2 ZN'  'Fraction of Zone Controlled by Secondary Daylighting Control': true model = '0.154', compare model = '0.153'
```

## Expected Behavior
The models daylight sensor locations should be identical, regardless of the operating system.

## Steps to Reproduce
This occurs using the 'SecondarySchool' building type with ['90.1-2013', '90.1-2016', '90.1-2019'] vintages in the [test_regression.rb](https://github.com/NREL/openstudio-standards/blob/master/test/doe_prototype/test_regression.rb) script.  Run separately on a Windows machine and Linux machine using OSv3.5.1.

Presumably it has something to do with geometry calculations called by openstudio-standards in the [space_add_daylighting_controls](
https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/standards/Standards.Space.rb#L835) method.

This error just surfaced, but the underlying issue has been present for a while.
Related recent pull requests in openstudio-standards are [remove existing daylighting controls in PRM baseline models](https://github.com/NREL/openstudio-standards/pull/1303) and [breaking out lighting to handle the zone/space distinction in EMS actuators](https://github.com/NREL/openstudio-standards/pull/1447).

## Possible Solution
Unclear.  My guess is resolving the difference in the way OpenStudio handles geometry calculations in Windows vs. Linux.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows, Linux
 - OSv3.5.1 (also occurs in OSv3.2.1)

### Context
Causes failures in openstudio-standards regression tests.

**Comment by jmarrec** [comment]
@mdahlhausen this is going to be super annoying to reproduce this issue given how large the os-standards repo is. Any chance you could you reduce down the issue for me?

I tried running `openstudio test_regression.rb` locally but it failed (`uninitialized constant Minitest::Reporters::SpecReporter`)

At least point out where the log message is issued?

FYI, My money is on the test grabbing objects in the order they come, without any kind of sorting...

**Comment by mdahlhausen** [comment]
@jmarrec The test occurs for me in the SecondarySchool regression test.  Just comment out the other building types.

**Comment by jmarrec** [comment]
I tried running the tests, it fails. see above

> I tried running openstudio test_regression.rb locally but it failed (uninitialized constant Minitest::Reporters::SpecReporter)

**Comment by jmarrec** [comment]
```
"/usr/local/openstudio-3.5.1/bin/openstudio" run -w "/home/julien/Software/Others/openstudio_gems/openstudio-standards/test/doe_prototype/output/regression-SecondarySchool-90.1-2013-ASHRAE 169-2013-4A/SR1/in.osw"
.[openstudio.model.YearDescription] <1> 'UseWeatherFile' is selected in YearDescription, but there are no weather file set for the model.
[openstudio.model.YearDescription] <1> 'UseWeatherFile' is selected in YearDescription, but there are no weather file set for the model.
"/usr/local/openstudio-3.5.1/bin/openstudio" run -w "/home/julien/Software/Others/openstudio_gems/openstudio-standards/test/doe_prototype/output/regression-SecondarySchool-90.1-2019-ASHRAE 169-2013-4A/SR1/in.osw"
.[openstudio.model.YearDescription] <1> 'UseWeatherFile' is selected in YearDescription, but there are no weather file set for the model.
[openstudio.model.YearDescription] <1> 'UseWeatherFile' is selected in YearDescription, but there are no weather file set for the model.
"/usr/local/openstudio-3.5.1/bin/openstudio" run -w "/home/julien/Software/Others/openstudio_gems/openstudio-standards/test/doe_prototype/output/regression-SecondarySchool-90.1-2016-ASHRAE 169-2013-4A/SR1/in.osw"
.

Finished in 150.247539s, 0.0200 runs/s, 0.0599 assertions/s.

3 runs, 9 assertions, 0 failures, 0 errors, 0 skips
```



I honestly think the investigation should be on your side, as it does look like an ordering issue. On the OpenStudio-resources (regression tests), this is why all tests do stuff like this: https://github.com/NREL/OpenStudio-resources/blob/d4e2965946c54fff2f5aeae9130c13861b24a58e/model/simulationtests/centralheatpumpsystem.rb#L38-L42

The varying order can be demonstrated quite easily

```shell
$ cat test_order.rb
```

```ruby
include OpenStudio::Model
m = Model.new
10.times do |i|
  s = Space.new(m)
  s.setName("Space #{i}")
end
puts m.getSpaces.first.nameString()
```

```shell
(py39)julien@doe_prototype (master *%=)$ openstudio test_order.rb
Space 8
(py39)julien@doe_prototype (master *%=)$ openstudio test_order.rb
Space 8
(py39)julien@doe_prototype (master *%=)$ openstudio test_order.rb
Space 8
(py39)julien@doe_prototype (master *%=)$ openstudio test_order.rb
Space 8
(py39)julien@doe_prototype (master *%=)$ openstudio test_order.rb
Space 8
(py39)julien@doe_prototype (master *%=)$ openstudio test_order.rb
Space 9
(py39)julien@doe_prototype (master *%=)$ openstudio test_order.rb
Space 6
```

**Comment by mdahlhausen** [comment]
@jmarrec - spoke with @asparke2.  Seems like it's an issue in the way geometry is handled on Windows vs. Linux with the `OpenStudio.joinAll()` method.  Here is a short script that demonstrates it: [test_join.zip](https://github.com/NREL/OpenStudio/files/11126878/test_join.zip)

**Comment by jmarrec** [comment]
Could you provide a diff of windows v Linux for that script? (Any help in reproducing is always super welcome)

I'm looking at the joinAll code... I don't see what could cause this aside from double rounding errors, maybe here: https://github.com/NREL/OpenStudio/blob/77ffac62c5cf2824e74bfe996f6c4a71adee9823/src/utilities/geometry/Intersection.cpp#L787

**Comment by jmarrec** [comment]
I ended up launching a test on all three platforms here: https://github.com/jmarrec/OpenStudio-Tester/actions/runs/4583343033/jobs/8094130530, they all return the same exact array...?! This is 3.5.1 official

mac:
```
[41.043, 55.3207, 0]
[41.043, -3.3207, 0]
[-3.043, -3.3207, 0]
[-3.043, 55.3207, 0]
```

windows:
```
[utilities.geometry.join] <1> Union has inner loops
[41.043, 55.3207, 0]
[41.043, -3.3207, 0]
[-3.043, -3.3207, 0]
[-3.043, 55.3207, 0]
```

ubuntu 20.04:
```
[utilities.geometry.join] <1> Union has inner loops
[41.043, 55.3207, 0]
[41.043, -3.3207, 0]
[-3.043, -3.3207, 0]
[-3.043, 55.3207, 0]
```

**Comment by mdahlhausen** [comment]
I've attached some similar examples:
[join_error.zip](https://github.com/NREL/OpenStudio/files/11130574/join_error.zip)

This is what I get when I run the `test_join.rb` script:
Linux:
```
root@2bf96788bf3d:/mnt/openstudio-standards/test/os_stds_methods# ruby test_join.rb
[utilities.geometry.join] <1> Union has inner loops
root@2bf96788bf3d:/mnt/openstudio-standards/test/os_stds_methods#
```

Windows:
```
PS C:\Users\mdahlhau\Documents\GitHub\NREL\openstudio-standards\test\os_stds_methods> ruby .\test_join.rb
[utilities.geometry.join] <1> Union has inner loops
[utilities.geometry.join] <1> Union has inner loops
[utilities.geometry.join] <1> Union has inner loops
[utilities.geometry.join] <1> Union has inner loops
PS C:\Users\mdahlhau\Documents\GitHub\NREL\openstudio-standards\test\os_stds_methods> 
```

The issue I'm running into is that [this method](https://github.com/NREL/openstudio-standards/blob/master/lib/openstudio-standards/standards/Standards.Space.rb#L20) will return different results depending whether it is on Linux or Windows.

Linux:
`{"toplighted_area"=>1248.0, "primary_sidelighted_area"=>0, "secondary_sidelighted_area"=>0, "total_window_area"=>212.79909818400003, "total_skylight_area"=>53.547263999999956}`

Windows:
`{"toplighted_area"=>1248.0, "primary_sidelighted_area"=>451.97489424772493, "secondary_sidelighted_area"=>367.36384274317516, "total_window_area"=>212.79909818400003, "total_skylight_area"=>53.547263999999956}`

The issue is that the `.join` method for the `toplit_polygons` are returning different results, which causes differences in the daylit area calculation.

**Comment by mdahlhausen** [comment]
@jmarrec some addition context - my Windows tests are with OS v3.5.1, and the Linux tests are with the docker develop container. It could be the case the Windows and Linux versions of develop both return the same values; I haven't checked that yet.

**Comment by jmarrec** [comment]
And it's the line I suspected from the get go: https://github.com/NREL/OpenStudio/blob/77ffac62c5cf2824e74bfe996f6c4a71adee9823/src/utilities/geometry/Intersection.cpp#L787

`polygonAreas` are the same on windows and linux, and they all have very similar values

```
154.24646399999997
154.24646399999997
154.24646400000000
154.24646400000000
154.24646400000000
154.24646400000000
154.24646400000003
154.24646400000003
154.24646400000003
154.24646400000003
154.24646400000003
154.24646399999997
154.24646400000003
154.24646400000003
154.24646400000003
154.24646400000003
154.24646400000003
154.24646400000003
154.24646400000003
154.24646400000003
154.24646400000003
154.24646400000003
154.24646400000000
154.24646400000003
154.24646400000003
154.24646400000003
154.24646400000003
154.24646400000003
154.24646400000003
154.24646400000003
154.24646400000000
154.24646399999997
154.24646399999997
154.24646400000000
154.24646400000000
154.24646399999997
```

Before the sort, orderedComponent is just 0 to 35.

After the sort, linux and windows are drastically different. So the order in which the join operation is later done is different.

|   Linux |   Windows |
|--------:|----------:|
|      12 |        18 |
|      23 |        16 |
|      24 |         6 |
|      21 |         7 |
|      20 |         8 |
|      19 |         9 |
|      18 |        10 |
|      17 |        17 |
|      16 |        12 |
|      15 |        13 |
|      14 |        14 |
|      13 |        15 |
|      25 |        19 |
|      10 |        20 |
|       9 |        21 |
|       8 |        23 |
|       7 |        24 |
|       6 |        25 |
|      26 |        26 |
|      27 |        27 |
|      28 |        28 |
|      29 |        29 |
|      33 |         2 |
|      30 |         3 |
|      22 |         4 |
|      34 |         5 |
|       5 |        22 |
|       4 |        30 |
|       3 |        33 |
|       2 |        34 |
|       0 |         0 |
|      35 |        31 |
|      32 |        32 |
|      31 |         1 |
|      11 |        11 |
|       1 |        35

**Comment by jmarrec** [comment]
test.cpp 

```c++
#include <algorithm>
#include <numeric>  // iota
#include <vector>

#include <iostream>

int main() {
  std::vector<double> polygonAreas{
    154.24646399999997, 154.24646399999997, 154.246464,         154.246464,         154.246464,         154.246464,
    154.24646400000003, 154.24646400000003, 154.24646400000003, 154.24646400000003, 154.24646400000003, 154.24646399999997,
    154.24646400000003, 154.24646400000003, 154.24646400000003, 154.24646400000003, 154.24646400000003, 154.24646400000003,
    154.24646400000003, 154.24646400000003, 154.24646400000003, 154.24646400000003, 154.246464,         154.24646400000003,
    154.24646400000003, 154.24646400000003, 154.24646400000003, 154.24646400000003, 154.24646400000003, 154.24646400000003,
    154.246464,         154.24646399999997, 154.24646399999997, 154.246464,         154.246464,         154.24646399999997,
  };

  std::vector<unsigned int> orderedComponent;
  std::vector<unsigned int> orderedComponentStable;

  {
    orderedComponent.resize(polygonAreas.size());
    std::iota(orderedComponent.begin(), orderedComponent.end(), 0);
    std::sort(orderedComponent.begin(), orderedComponent.end(), [&polygonAreas](int ia, int ib) { return polygonAreas[ia] > polygonAreas[ib]; });
    std::cout << "[";
    for (unsigned i : orderedComponent) {
      std::cout << i << ",";
    }
    std::cout << "]\n";
  }
  {
    orderedComponentStable.resize(polygonAreas.size());
    std::iota(orderedComponentStable.begin(), orderedComponentStable.end(), 0);
    std::stable_sort(orderedComponentStable.begin(), orderedComponentStable.end(),
                     [&polygonAreas](int ia, int ib) { return polygonAreas[ia] > polygonAreas[ib]; });
    std::cout << "[";
    for (unsigned i : orderedComponentStable) {
      std::cout << i << ",";
    }
    std::cout << "]\n";
  }

  return 0;
}
```

Unix: 

```shell
$ g++ -std=c++20 test.cpp -o test && ./test
[12,23,24,21,20,19,18,17,16,15,14,13,25,10,9,8,7,6,26,27,28,29,33,30,22,34,5,4,3,2,0,35,32,31,11,1,]
[6,7,8,9,10,12,13,14,15,16,17,18,19,20,21,23,24,25,26,27,28,29,2,3,4,5,22,30,33,34,0,1,11,31,32,35,]
```

Windows:

```shell
$ cl.exe /std:c++20 /EHsc .\test.cpp && .\test.exe 
[18,16,6,7,8,9,10,17,12,13,14,15,19,20,21,23,24,25,26,27,28,29,2,3,4,5,22,30,33,34,0,31,32,1,11,35,]
[6,7,8,9,10,12,13,14,15,16,17,18,19,20,21,23,24,25,26,27,28,29,2,3,4,5,22,30,33,34,0,1,11,31,32,35,]
```
