### ISSUE TITLE
Detect incorrectly oriented surfaces in spaces (Autocalculated volumes for some spaces are incorrect otherwise)

### ISSUE THREAD

**Issue by ckirney** [NREL/OpenStudio#4837]
Issue overview
--------------
In between OS 3.2.1 and OS 3.5.1 there appears to have been a change in how volumes are calculated.  In OS 3.5.1 some spaces whose volume calculation method is either not set or is set to 'autocalculateVolume' return incorrect volumes when the '.volume' method is used.  This behavior is in OS 3.2.1 as well but to a lesser extent.

## Current Behavior
In OS 3.5.1 (and to a lesser degree OS 3.2.1) the '.volume' method returns incorrect volumes for some spaces whose volume is autocalculated.

## Expected Behavior
The value returned by the '.volume' method should be correct for all autocalculated spaces.

## Steps to Reproduce
1.  Download the attached 'test_file.txt' and then change the .txt extension to .osm.
2.  Use OpenStudio API space.volume method to return the volumes of the three spaces in the file.  Do this using both OS 3.2.1 and OS 3.5.1.
3.  Look at the geometry of the spaces and calculate their volumes manually.
4.  Compare the results.

[test_file.txt](https://github.com/NREL/OpenStudio/files/11041010/test_file.txt)

I did the above and got the following results:

|  Space Name                 |  OS 3.2.1 Vol. (m3)    |  OS 3.5.1 Vol. (m3)    |   Man. Calc. Vol. (m3)    |
|  ------------------------  |  ---------------------  |  --------------------- | ------------------------  |
|  Zone 1 Office               |   1011                        |  1011                        |  1011                            | 
|  Zone 2 Fine Storage     |  9513                         |  2953                       |  10876                          |
|  Zone 3 Bulk Storage    |  27350                        |  35278                     |  27338                          | 

## Details
See above.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):  Ubuntu 22.04 for OS 3.5.1, Ubuntu 18.04 for OS 3.2.1 (both are based on the release versions of their respective NREL/openstudio Docker images)
 - Version of OpenStudio (if using an intermediate build, include SHA):  OS 3.2.1 and OS 3.5.1

### Context
We use the volume of spaces for many things including calculating average ceiling heights and a variety of normalizations.

**Comment by joseph-robertson** [comment]
@ckirney Can you fix your results table above so it renders properly?

**Comment by ckirney** [comment]
Sorry about that.  It should be fixed now.

**Comment by jmarrec** [comment]
The difference between 3.2.1 and 3.5.1 is expected, see https://github.com/NREL/OpenStudio/pull/4592. In this PR I aimed to iImplement the exact same calculations that E+ does. (It's possible I failed though)

Are your spaces properly enclosed? Can you show your manual calculations?
Basically, provide any help you can offer so we  can reproduce easily. Thanks a lot!

**Comment by ckirney** [comment]
Sorry, markdown tried to turn my ASCII art into a table.  I have attached a picture to this comment that shows the three spaces.  The left most space is 'Zone3 Bulk Storage'.  The large space on the right side is 'Zone2 Fine Storage'.  The little space on the bottom right of 'Zone2 Fine Storage' is 'Zone 1 Office'.
![Warehouse](https://user-images.githubusercontent.com/36897585/227034457-7dc0187c-dec2-409b-9f9c-129e49b63ef2.jpg)

**Comment by jmarrec** [comment]
As a result, the Newell Area vector is different: 

```python
for surface in sorted(m.getSurfaces(), key=lambda x: x.nameString()):
    print(surface.nameString(), openstudio.getNewellVector(surface.vertices()).get())
```

red is yours, green is the correctly reordered:

```diff
 Bulk Storage Floor [0, 0, -6409.68]
-Bulk Storage Front Wall [0, 780.309, 0]
+Bulk Storage Front Wall [0, -780.309, 0]
 Bulk Storage Left Wall [-1196.47, 0, 0]
 Bulk Storage Rear Wall [0, 780.309, 0]
 Bulk Storage Right Wall [1196.47, 0, 0]
 Bulk Storage Roof [0, 0, 6409.68]
```

**Comment by ckirney** [comment]
Thanks @jmarrec!  That issue has been has been hiding in our code and models for years.  Sorry to bother you with this.
