### ISSUE TITLE
Crash on intersect and on Crash on Project Loose geometry with user model

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#484]
Issue #24 seemed similar, but for some reason this file still crashes in 1.0.4 which is after the fix. Model is on network under issue number at this location.
Y:\5500\5500 HPBldg\davidg

I tested this on Windows 7 computer with SketchUp 8. The user also experianced this crash (not sure which system).

**Comment by macumber** [comment]
@DavidGoldwasser should we close this as won't fix?
