### ISSUE TITLE
OpenStudio logging singleton issues (especially on Windows) when using interpreted bindings (ruby measures)

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4847]
Issue overview
--------------

Two issues observed comparing the behavior of OpenStudio logging between Linux and Windows:

1. Windows produces more warning messages than appear on Linux. Why?! I primarily do my testing on Linux, so I'm concerned that I might be missing things.

```patch
--- C:/Users/shorowit/Desktop/Linux.txt	Thu Mar 30 15:24:05 2023
+++ C:/Users/shorowit/Desktop/Windows.txt	Thu Mar 30 15:23:57 2023
@@ -3,2 +3,5 @@
 [openstudio.measure.OSRunner] <1> Cannot find current Workflow Step
+[openstudio.measure.OSRunner] <1> Cannot find current Workflow Step
+[openstudio.EpwFile] <0> Successive data points (1995-Jan-31 to 1994-Feb-01, ending on line 753) are greater than 1 day apart in EPW file 'C:/git/openstudio-hpxml/HPXMLtoOpenStudio/resources/../../weather/USA_CO_Denver.Intl.AP.725650_TMY3.epw'. Data will be treated as typical (TMY)
+[openstudio.WorkflowStepResult] <0> WorkflowStepResult value called with undefined stepResult, returning 'Success'
 Running simulation...
@@ -8,2 +11,6 @@
 [openstudio.measure.OSRunner] <1> Cannot find current Workflow Step
+[openstudio.WorkflowStepResult] <0> WorkflowStepResult value called with undefined stepResult, returning 'Success'
+[openstudio.measure.OSRunner] <1> Cannot find current Workflow Step
+[openstudio.measure.OSRunner] <1> Cannot find current Workflow Step
+[openstudio.WorkflowStepResult] <0> WorkflowStepResult value called with undefined stepResult, returning 'Success'
 Wrote output file: run/results_annual.csv.
```

2. When using `OpenStudio::Logger.instance.standardOutLogger.setLogLevel(OpenStudio::Fatal)` to suppress warning messages, warnings are completely suppressed on Linux but not on Windows. For some of our workflows, this means we can get dozens and dozens of lines of output on Windows, which is annoying and makes it difficult to see the output of interest.

```patch
--- C:/Users/shorowit/Desktop/Linux.txt	Thu Mar 30 15:24:02 2023
+++ C:/Users/shorowit/Desktop/Windows.txt	Thu Mar 30 15:24:00 2023
@@ -2,2 +2,5 @@
 Creating input...
+[openstudio.measure.OSRunner] <1> Cannot find current Workflow Step
+[openstudio.EpwFile] <0> Successive data points (1995-Jan-31 to 1994-Feb-01, ending on line 753) are greater than 1 day apart in EPW file 'C:/git/openstudio-hpxml/HPXMLtoOpenStudio/resources/../../weather/USA_CO_Denver.Intl.AP.725650_TMY3.epw'. Data will be treated as typical (TMY)
+[openstudio.WorkflowStepResult] <0> WorkflowStepResult value called with undefined stepResult, returning 'Success'
 Running simulation...
@@ -5,2 +8,6 @@
 Processing output...
+[openstudio.measure.OSRunner] <1> Cannot find current Workflow Step
+[openstudio.WorkflowStepResult] <0> WorkflowStepResult value called with undefined stepResult, returning 'Success'
+[openstudio.measure.OSRunner] <1> Cannot find current Workflow Step
+[openstudio.WorkflowStepResult] <0> WorkflowStepResult value called with undefined stepResult, returning 'Success'
 Wrote output file: run/results_annual.csv.

```

## Expected Behavior
OpenStudio should behave the same on Linux and Windows.

## Steps to Reproduce
1. Clone https://github.com/NREL/OpenStudio-HPXML
2. To reproduce issue 1, run `openstudio workflow/run_simulation.rb -x workflow/sample_files/base.xml -o test` on Windows and Linux.
3. To reproduce issue 2, comment out [this line](https://github.com/NREL/OpenStudio-HPXML/blob/4f39a733f647d7b7366b176bc66925845b91de20/HPXMLtoOpenStudio/resources/meta_measure.rb#L15) and run the above command again on Windows and Linux.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Windows 10 and Ubuntu 20.04 (WSL)
 - OpenStudio 3.5

**Comment by jmarrec** [comment]
Well actually I can reproduce using only the compact_ruby_only.osw we have in source.

```shell
(py39)julien@compact_osw$ $os_build_rel3/Products/openstudio run -w compact_ruby_only.osw
[11:59:34.530107 WARN] Measure couldn't find the construction named 'EXTERIOR-WALL adj exterior wall insulation' in the exterior surface hash.
(py39)julien@compact_osw$ cat run/run.log 
[11:59:34.530107 WARN] Measure couldn't find the construction named 'EXTERIOR-WALL adj exterior wall insulation' in the exterior surface hash
```

```shell
$ C:\src\OpenStudio\build-release\Products\openstudio.exe run -w compact_ruby_only.osw
[OpenStudio.Measure] <0> OSRunner is deprecated, use OpenStudio::Measure::OSRunner instead.
[openstudio.EpwFile] <0> Header start day of the week and actual start day of the week do not match in EPW file 'C:/src/OpenStudio/build-debug/resources/Examples/compact_osw/files/srrl_2013_amy.epw'. Data will be treated as typical (TMY)
[OpenStudio.Measure] <0> OSArgumentMap is deprecated, use OpenStudio::Measure::OSArgumentMap instead.
[OpenStudio.Measure] <0> OSArgumentMap is deprecated, use OpenStudio::Measure::OSArgumentMap instead.
[12:04:09.179426 WARN] Measure couldn't find the construction named 'EXTERIOR-WALL adj exterior wall insulation' in the exterior surface hash.
[openstudio.energyplus.ForwardTranslator] <0> OS_ProgramControl is not currently translated
[utilities.idf.WorkspaceObject] <0> Object of type 'Schedule:Constant' and named 'Always Off Discrete', points to an object named OnOff from field 1, but that object cannot be located.
[utilities.idf.WorkspaceObject] <0> Object of type 'Schedule:Constant' and named 'Always On Continuous', points to an object named Fractional 1 from field 1, but that object cannot be located.
[OpenStudio.Measure] <0> OSArgumentMap is deprecated, use OpenStudio::Measure::OSArgumentMap instead.
[OpenStudio.Measure] <0> OSArgumentMap is deprecated, use OpenStudio::Measure::OSArgumentMap instead.
[OpenStudio.Measure] <0> OSArgumentMap is deprecated, use OpenStudio::Measure::OSArgumentMap instead.
$  cat .\run\run.log
[12:04:09.179426 WARN] Measure couldn't find the construction named 'EXTERIOR-WALL adj exterior wall insulation' in the exterior surface hash.
```

The `labs` doesn't have the same issue (but I realize it outputs everything to run.log though), so this is likely a ruby-side issue. I'll look into it

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio/blob/33626993b6315a614eb67de7b158bf4e5fb384d9/ruby/engine/openstudio_cli.rb#L49-L56

**Comment by jmarrec** [comment]
Ok, here is a proper MCVE:

```ruby
$logger = Logger.new(STDOUT)
$logger.level = Logger::WARN

OpenStudio::Logger.instance.standardOutLogger.setLogLevel(OpenStudio::Error)

$logger.info "STDOUT Info"
$logger.warn "STDOUT Warn"
$logger.error "STDOUT Error"

OpenStudio::logFree(OpenStudio::Info, "test", "Info")
OpenStudio::logFree(OpenStudio::Warn, "test", "Warn")
OpenStudio::logFree(OpenStudio::Error, "test", "Error")
```

Unix behaves correctly:

```
$ openstudio test.rb
W, [2023-04-04T12:21:56.062121 #230289]  WARN -- : STDOUT Warn
E, [2023-04-04T12:21:56.062161 #230289] ERROR -- : STDOUT Error
[test] <1> Error
```

Windows shows the issue. Seems like both the stdout logger and the SDK logger are intertwined:

```shell
openstudio.exe .\test.rb
W, [2023-04-04T12:22:32.765676 #15076]  WARN -- : STDOUT Warn
E, [2023-04-04T12:22:32.766081 #15076] ERROR -- : STDOUT Error
[test] <0> Warn
[test] <1> Error
[test] <1> Error
```

**Comment by jmarrec** [comment]
And here we are... We broke something during the `labs` work

```
$ C:\Users\julien\Downloads\OpenStudio-3.4.0+9e989dbeea-Windows\bin\openstudio.exe .\test.rb
W, [2023-04-04T12:33:42.759688 #14548]  WARN -- : STDOUT Warn
E, [2023-04-04T12:33:42.760148 #14548] ERROR -- : STDOUT Error
[test] <1> Error
$ C:\Users\julien\Downloads\OpenStudio-3.5.0+7b14ce1588-Windows\bin\openstudio.exe .\test.rb
W, [2023-04-04T12:34:13.628220 #11696]  WARN -- : STDOUT Warn
E, [2023-04-04T12:34:13.628766 #11696] ERROR -- : STDOUT Error
[test] <0> Warn
[test] <1> Error
[test] <1> Error
```

@kbenne My money is on the use of a shared lib for ruby: https://github.com/NREL/OpenStudio/commit/50f6c0378ce1e5e4e48c525d7d1e2e80fd6adcb2 . Thoughts?

**Comment by jmarrec** [comment]
On windows, if here I modify this line: https://github.com/NREL/OpenStudio/blob/33626993b6315a614eb67de7b158bf4e5fb384d9/src/cli/main.cpp#L299

to be

```diff
+   // Disable this logger, we have a duplicate in the ruby shared lib
+   openstudio::Logger::instance().standardOutLogger().disable();
+   openstudio::Logger::instance().standardErrLogger().disable();
    result = openstudio::rubyCLI(rubyEngine);
```

Then past the initial extra messages issued when we locate the DLL via getOpenStudioModule, I get only one set of messages

```shell
$ Products\openstudio.exe execute_ruby_script .\resources\Examples\compact_osw\test.rb
[2023-04-04 13:14:08.970602] [0x00003a00] [info]    getOpenStudioModule, szPath = 'C:\src\OpenStudio\build-debug\Products\openstudiolib.dll'
[2023-04-04 13:14:08.973631] [0x00003a00] [info]    completeAndNormalize: looking for p = C:/src/OpenStudio/build-debug/Products/openstudiolib.dll
[2023-04-04 13:14:08.974637] [0x00003a00] [info]    completeAndNormalize: temp = C:/src/OpenStudio/build-debug/Products/openstudiolib.dll
[2023-04-04 13:14:08.981796] [0x00003a00] [info]    completeAndNormalize: result = C:/src/OpenStudio/build-debug/Products/openstudiolib.dll
[2023-04-04 13:14:08.982718] [0x00003a00] [info]    getOpenStudioModule, found 'C:/src/OpenStudio/build-debug/Products/openstudiolib.dll'

W, [2023-04-04T13:14:13.052013 #6864]  WARN -- : STDOUT Warn
E, [2023-04-04T13:14:13.052447 #6864] ERROR -- : STDOUT Error
[test] <1> Error
```

**Comment by shorowit** [comment]
@jmarrec You had fixed this issue, but it's no longer working for Windows w/ OS 3.7. You can easily reproduce the issue by cloning OpenStudio-HPXML and running `openstudio tasks.rb update_hpxmls`. We are using `OpenStudio::Logger.instance.standardOutLogger.setLogLevel(OpenStudio::Fatal)` to try to suppress messages.

Linux:
![image](https://github.com/NREL/OpenStudio/assets/5861765/51662530-0150-4bb0-a81e-43f6cdb70029)

Windows:
![image](https://github.com/NREL/OpenStudio/assets/5861765/39f4609f-5af9-4137-9126-f5a41800162c)

**Comment by shorowit** [comment]
I was doing some more testing and realized this broke w/ the switch to the C++ CLI. It's easy to confirm because you can use the 3.7.0 release of OpenStudio and run the above command using `classic` or not. When running with classic` the standardOutLogger's log level is correctly used (see below); when running w/o classic, it is not (see above).

![image](https://github.com/NREL/OpenStudio/assets/5861765/6aea2660-b06d-4ea6-8355-6595f28a818f)

**Comment by jmarrec** [comment]
@shorowit I guess it was misleading having closed this issue. What I did was a mere workaround for the "classic" version in https://github.com/NREL/OpenStudio/pull/4852/commits/83015445b16e5032289600c2b723d4d0ce0f415a .
We've had a failing test since for the labs version.

The issue is that the Logger is a Static Singleton. And We get one in the libopenstudiolib, but we also get one in the rubyengine and one in the pythonengine (which are `dlopen`ed). So we end up with several logger instances... I don't know how to resolve that situation yet, and I reckon we'll need @kbenne 's magic touch for this.

**Comment by kbenne** [comment]
Testing changes to logger.hpp can be very time consuming, since it typically triggers large rebuilds. I have tested iterations of a fix to this over in the Labs repo. https://github.com/NREL/OpenStudioLabs/tree/logger-singleton

**Comment by shorowit** [comment]
Let me know if you want me to test a dev build at some point, happy to kick the tires on any proposed solution.

**Comment by kbenne** [comment]
@shorowit and @joseph-robertson 

This should be in a state that we could use your testing on it.

**Comment by shorowit** [comment]
Re-tested these issues in the 3.8-rc1 and they seem to work as expected now. Thanks @kbenne and @jmarrec!
