### ISSUE TITLE
ExternalFile issues with `labs`

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio#4863]
Issue overview
--------------
I'm seeing inconsistencies in external file copying between using the `labs` command and _not_ using the `labs` command, for both ruby and python measures that specifically use `PythonPluginInstance`.

## Current Behavior
I'm trying to run a python measure using the `labs` command. In the python measure, I have a `openstudio.model.ExternalFile.getExternalFile(model, ...)` line which copies the external file to the `run` directory's `000_xxx/files` folder. Using a completely analogous ruby measure, the same line copies the external file in the same way.

In both cases, forward translation fails on `[openstudio.energyplus.ForwardTranslator] <0> Object of type 'OS:PythonPlugin:Instance' and named 'Python Plugin Instance 1'will not be translated, cannot find the referenced file ''`. From within either measure, I can confirm that `python_plugin_instance.externalFile.filePath` is not empty, however.

If I run the same ruby measure _without_ the `labs` command, the external file is copied to the `generated_files` folder which is at the same level as `run` folder. Forward translation works as expected.

## Expected Behavior
We shouldn't be seeing an external file issue using `PythonPluginInstance` and the `labs` command with python measures, and especially not with ruby measures.

## Steps to Reproduce
See #4858.

## Possible Solution
I tried to changing the working directory before calling ExternalFile. And while it can (as expected) allow you to copy the file to `files` alongside the `run` folder, it still does not forward translate correctly.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): windows
 - Version of OpenStudio (if using an intermediate build, include SHA): pretty recent 3.6.0-alpha

**Comment by jmarrec** [comment]
I made a mistake by pushing to develop (sorry about that), but this it's a one-liner fix, I am not going to revert, reopen, PR, close.
