### ISSUE TITLE
ZoneAirDistribution

### ISSUE THREAD

**Issue by Ski90Moo** [NREL/OpenStudio#4876]
Issue overview
--------------

In OS:Sizing:Zone, if the Zone Air Distribution variables are left as default, the translator will not create a DesignSpecification:ZoneAirDistribution object.

## Steps to Reproduce

1.
![2023-05-04 (1)](https://user-images.githubusercontent.com/69771412/236274901-6ffba0e3-feef-4aad-83fe-2648f0b0db08.png)

2.
![2023-05-04](https://user-images.githubusercontent.com/69771412/236274927-4c529f94-07ee-4aee-8219-6a69aacfafe6.png)

3.
4.

## Possible Solution

If you change a variable, such as !- Design Zone Air Distribution Effectiveness in Cooling Mode, it will properly create a DesignSpecification:ZoneAirDistribution object.
### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 11
 - Version of OpenStudio (if using an intermediate build, include SHA):
![2023-05-04 (2)](https://user-images.githubusercontent.com/69771412/236275035-5c0560e6-b621-4e16-b413-5c214c6841c2.png)

**Comment by jmarrec** [comment]
This is done on purpose. Is that creating problems for you? https://github.com/NREL/OpenStudio/blob/805488732f2779ae9f5c64a18fe3ba50048ed7f5/src/energyplus/ForwardTranslator/ForwardTranslateSizingZone.cpp#L219-L230

if left blank, E+ assigns 1.0 for all fields, see https://github.com/NREL/EnergyPlus/blob/8b029a464a29fb630886ddbc097c2ed5579d9f7c/src/EnergyPlus/SizingManager.cc#L3366-L3394

**Comment by jmarrec** [comment]
@Ski90Moo You reported this again today on https://github.com/openstudiocoalition/OpenStudioApplication/issues/694

So I'll ask again: is this creating a problem for you? Or you're just annoyed with the E+ warning due to the DSZAD missing?

I'm happy to reopen the ticket if need be.

**Comment by Ski90Moo** [comment]
@jmarrec Annoyed with the warning.  I know how to solve it, but other users might not.  If it is "left blank" energyplus does not create a DesignSpecification:ZoneAirDistribution object.
