### ISSUE TITLE
OS:Coil:Heating:LowTemperatureRadiant:ConstantFlow forward translate does not name fields

### ISSUE THREAD

**Issue by Ski90Moo** [NREL/OpenStudio#4877]
Issue overview
--------------

If the OpenStudio model has the OS:Coil:Heating:LowTemperatureRadiant:ConstantFlow object, it gets forward translated to EnergyPlus, but the Branch object that is created does not have !- Component Object Type 1 or !- Component Name 1.  This causes the following error:

   ** Severe  ** <root>[Branch][Rad Floor Loop Demand Branch 1][components][0] - Missing required property 'component_name'.
   ** Severe  ** <root>[Branch][Rad Floor Loop Demand Branch 1][components][0] - Missing required property 'component_object_type'.

## Steps to Reproduce

1.
![2023-05-04 (3)](https://user-images.githubusercontent.com/69771412/236289332-027b39db-5ba4-4d2d-8378-70ea8e5cea60.png)
2.
![2023-05-04 (4)](https://user-images.githubusercontent.com/69771412/236289363-f14f8ef7-1fd3-4b1a-be24-df77af4123b9.png)
3.
![2023-05-04 (6)](https://user-images.githubusercontent.com/69771412/236289445-a6d4277f-b2e3-4b3c-8d39-9ada9c1f7be3.png)
4.
![2023-05-04 (5)](https://user-images.githubusercontent.com/69771412/236289482-7c30a344-4ed6-44e6-b7f1-ce2fc72da86e.png)

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 11
 - Version of OpenStudio (if using an intermediate build, include SHA):
![2023-05-04 (2)](https://user-images.githubusercontent.com/69771412/236289538-428553bc-0a62-4c51-ae01-2d3ed985c250.png)

**Comment by joseph-robertson** [comment]
@Ski90Moo Can you post your osm file?

**Comment by joseph-robertson** [comment]
@Ski90Moo

My hunch is that surfaces in your osm (with type "Radiant Surface Type" referenced by the ZoneHVAC:LowTemperatureRadiant:ConstantFlow) do not point to Construction:InternalSource objects. The FT requires this [here](https://github.com/NREL/OpenStudio/blob/develop/src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACLowTempRadiantConstFlow.cpp#L80-L85).

See a ZoneHVACLowTempRadiantConstFlow example for setting ContructionWithInternalSource [here](https://github.com/NREL/OpenStudio-resources/blob/develop/model/simulationtests/lowtemprad_constflow.rb#L166-L188).

While this may fix your issue, this error/requirement does seem quite cryptic. On our end, we may look at making this error/requirement more transparent.

**Comment by Ski90Moo** [comment]
@joseph-robertson Of course!  My apologies, it does appear that I had not properly assigned a construction set that would apply the Construction:InternalSource object.  Thank you for your help.

Perhaps if the error also gave a note something like "An Internal Source Construction may not be assigned.  Check construction assignments".

Thank you for your help Joseph.  

-Mike
