### ISSUE TITLE
FT: 'OS:SwimmingPool:Indoor' ... does not have an Surface attached

### ISSUE THREAD

**Issue by brgix** [NREL/OpenStudio#4878]
Issue overview
--------------
In some circumstances (to hopefully narrow down), the FT logs/throws a [message](https://github.com/NREL/OpenStudio/blob/22e1db7be5d9a04815fe46ec375e8c28a815b133/src/model/SwimmingPoolIndoor.cpp#L149) about a missing (floor) surface for [SwimmingPoolIndoor](https://s3.amazonaws.com/openstudio-sdk-documentation/cpp/OpenStudio-3.5.1-doc/model/html/classopenstudio_1_1model_1_1_swimming_pool_indoor.html) objects, despite having a linked floor surface. Issue filed following this UMH [post](https://unmethours.com/question/91058/swimming-pool-in-openstudio/). 

## Current Behavior
In what look like cases where a model may be (quite) incomplete or have otherwise invalid inputs (undiagnosed elsewhere in the model, e.g. bad PlantLoop inputs), adding a **SwimmingPoolIndoor** object (via the SDK/CLI), then attempting to run a simulation ... triggers the above "_does not have an Surface attached_" message. In all test cases, a (valid?) floor surface always seems to be successfully _attached_ to the object (via the **SwimmingPoolIndoor** constructor). In the most basic tests (incomplete models, see below), it is the first/only message that's logged/thrown. There are tons of missing/invalid inputs in these very basic models (e.g. missing surface construction), but an _unattached_ surface _per se_ is not one of them.

## Expected Behavior
Error messages should inform users on what's missing/invalid from the model (e.g. missing thermal zone), or more specifically here the _attached_ floor surface (e.g. missing construction). If there is something fundamentally wrong with the target surface, it should be caught when instantiating.

## Steps to Reproduce
_(First, successful cases: adding a pool to an existing OpenStudio model, here the [SmallOffice](https://github.com/rd2/tbd_tests/blob/develop/spec/files/osms/in/smalloffice.osm) model)_

Run the following Ruby script:

```
require 'openstudio'

translator = OpenStudio::OSVersion::VersionTranslator.new

mdl = "smalloffice.osm"
file = File.join(__dir__, mdl)
path = OpenStudio::Path.new(file)
model = translator.loadModel(path)
raise "Can't find #{mdl}" if model.empty?
model = model.get

loup = "Main Service Water Loop"
loop = model.getPlantLoopByName(loup)
raise "Can't find #{loup}" if loop.empty?
loop = loop.get

flr = "Core_ZN_floor"
floor = model.getSurfaceByName(flr)
raise "Can't find #{flr}" if floor.empty?
floor = floor.get

pool = OpenStudio::Model::SwimmingPoolIndoor.new(model, floor)
pool.setName("POOL")
raise "Can't attach POOL to #{loup}" unless loop.addDemandBranchForComponent(pool)

modele = "smalloffice_pool.osm"
pth = File.join(__dir__, modele)
model.save(pth, true)
```

Run a simulation with the generated _smalloffice_pool.osm_ (either via the App or the CLI).
Results are most likely _off_, but EnergyPlus only logs 2x warnings about plant capacity.

--
Apply the following to the same initial _smalloffice.osm_ (based on this UMH [solution](https://unmethours.com/question/57703/model-indoor-swimmimg-pool-in-openstudio/?answer=57790#post-id-57790)):

`openstudio -e "include OpenStudio::Model; vt = OpenStudio::OSVersion::VersionTranslator.new; m = vt.loadModel('smalloffice.osm').get; lp = m.getPlantLoopByName('Main Service Water Loop').get; fl = m.getSurfaceByName('Core_ZN_floor').get; pl = OpenStudio::Model::SwimmingPoolIndoor.new(m, fl); pl.setName('POOL'); lp.addDemandBranchForComponent(pl); m.save('smalloffice_pool2.osm', true)"`

Run a simulation with the generated _smalloffice_pool2.osm_. Same _successful_ results.

--

_(Very elementary, _unsuccessful_ cases)._

Run the following:

`openstudio -e "include OpenStudio::Model; m = OpenStudio::Model::Model.new; sp = OpenStudio::Model::Space.new(m); v = OpenStudio::Point3dVector.new; v << OpenStudio::Point3d.new(10,10,0); v << OpenStudio::Point3d.new(10,0,0); v << OpenStudio::Point3d.new(0,0,0); v << OpenStudio::Point3d.new(0,10,0); fl = OpenStudio::Model::Surface.new(v, m); fl.setName('FLOOR'); fl.setSpace(sp); lp = OpenStudio::Model::PlantLoop.new(m); lp.setName('LOOP'); pl = OpenStudio::Model::SwimmingPoolIndoor.new(m, fl); pl.setName('POOL'); lp.addDemandBranchForComponent(pl); m.save('smalloffice_pool3.osm', true)"`

Run a simulation with the generated _smalloffice_pool3.osm_ (e.g. App, CLI) ... will halt with the following :

```
[openstudio.model.SwimmingPoolIndoor] <2> Object of type 'OS:SwimmingPool:Indoor' and named 'POOL' does not have an Surface attached.
[10:18:43.036259 ERROR] Found error in state 'translator' with message ["/Users/jenkins/git/OpenStudioFull/3.5.1-rc3/src/model/SwimmingPoolIndoor.cpp@149 : Object of type 'OS:SwimmingPool:Indoor' and named 'POOL' does not have an Surface attached.::/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/model.rb:124:in `translateModel'\n:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/model.rb:124:in `translate_to_energyplus'\n:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/jobs/run_translation.rb:72:in `perform'\n:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:291:in `step'\n:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:233:in `run'\n:/openstudio_cli.rb:1184:in `execute'\n:/openstudio_cli.rb:814:in `execute'\n:/openstudio_cli.rb:1983:in `<main>'\neval:188:in `eval'\neval:188:in `require_embedded_absolute'\neval:173:in `block in require_embedded'\neval:167:in `each'\neval:167:in `require_embedded'\neval:126:in `require'\neval:3:in `<main>'"]}
```

### Environment
 - MacOS (Intel, Ventura), App 1.5.0/SDK 3.5.1

**Comment by eringold** [comment]
try: 
```
openstudio -e "m = OpenStudio::Model::Model.new; sp = OpenStudio::Model::Space.new(m); v = OpenStudio::Point3dVector.new; v << OpenStudio::Point3d.new(10,10,0); v << OpenStudio::Point3d.new(10,0,0); v << OpenStudio::Point3d.new(0,0,0); v << OpenStudio::Point3d.new(0,10,0); fl = OpenStudio::Model::Surface.new(v, m); fl.setName('FLOOR'); fl.setSpace(sp); tz = OpenStudio::Model::ThermalZone.new(m); sp.setThermalZone(tz);lp = OpenStudio::Model::PlantLoop.new(m); lp.setName('LOOP'); pl = OpenStudio::Model::SwimmingPoolIndoor.new(m, fl); pl.setName('POOL'); lp.addDemandBranchForComponent(pl); ft = OpenStudio::EnergyPlus::ForwardTranslator.new; ws = ft.translateModel(m); puts ws"
```

**Comment by brgix** [comment]
@eringold : Thanks! Adding the thermal zone to the space did it. Learned something useful today.
