### ISSUE TITLE
Rewrite MeasureManager in C++

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#4885]
Enhancement Request
--------------

Even in the `labs` subcommand, the MeasureManager is purely Ruby, so you can't use it to compute arguments for a Python Measure. 

## Detailed Description

https://github.com/NREL/OpenStudio/blob/f4f51c3e1888721212fb6c2002f75023abfc0011/src/cli/MeasureUpdateCommand.cpp#L369-L389

## Possible Implementation

We have the buildings blocks in place to compute arguments already in the MeasureUpdateCommand::getAndUpdateMeasure. But we'd need to write an HTTP server in C++. We have cpprestsdk that we already use for RemoteBCL. boost asio is another option, so is Poco.

**Comment by jmarrec** [comment]
I scoped it out, implemented a basic http server with cpprestsdk, looks like it wouldn’t be a daunting task

**Comment by kbenne** [comment]
I agree that a small http server using what we already have, cpprestsdk, is a good path.
