### ISSUE TITLE
`SurfacePropertyExposedFoundationPerimeter` has surfaceName method instead of surface

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4890]
Issue overview
--------------
Not sure if this is a bug report or a feature request...

The only way to get the surface from a `SurfacePropertyExposedFoundationPerimeter` object is from the `surfaceName` (string) method, which isn't very helpful. Instead, it should be a `surface` method that returns a Surface object. 

`SurfacePropertyIncidentSolarMultiplier` is a similar object that does it right -- it correctly has a `subSurface` method.

**Comment by joseph-robertson** [comment]
Certainly seems like there should be a `surface` method - not sure why I originally implemented as `surfaceName`.
