### ISSUE TITLE
openstudiolib.dll not found without C++ API installation

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#4897]
Issue overview
--------------
The `openstudiolib.dll` isn't installed if the `C++ API` is unchecked during installation of 3.6.0 and 3.6.1, which means the CLI can't be used. Not sure if this is the intended behavior now but it's different than previous versions. 

## Current Behavior
See below.

## Expected Behavior
Users should be able to use the CLI without installing the C++ API as in previous versions (e.g. 3.4.0) or be told that it's now required.

## Steps to Reproduce

1. Install 3.6.0 or 3.6.1 with the following options. 

   ![image](https://github.com/NREL/OpenStudio/assets/8397034/1db877e2-dec9-486c-9ab9-e9244194be82)

2. Add `C:\openstudio-3.6.0\bin` to PATH

3. `openstudio --version`
   
   ![image](https://github.com/NREL/OpenStudio/assets/8397034/46730ee2-9fea-4a97-8051-808089bdea52)

## Possible Solution
Fix or provide information during installation that the C++ API is now *required* for the CLI to work.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform: Windows 10 
 - Version of OpenStudio: 3.6.0 and 3.6.1

**Comment by jmarrec** [comment]
@MatthewSteen thanks for the report. The CLI used to be self-contained (statically linked) and now isn't since the `labs` subcommand was added, so we need to update the install rules.
