### ISSUE TITLE
Shading geometry incorrect when using building angle (Bugzilla #403)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#49]
On 2011-12-02 14:38:39, @macumber wrote:

> https://openstudio.nrel.gov/forums/openstudio-plug-google-sketchup/bug-reports-and-feature-requests/apparent-geometry-error-open

On 2011-12-14 10:47:48, @DavidGoldwasser wrote:

> Dan, can this be related to bug number 11?
> http://cbr-drupaldev.nrel.gov/bugzilla/show_bug.cgi?id=11
> 
> Site Shading surfaces are improperly displayed when there is a a non-0 building rotation 
> 
> That was fixed a long time ago, but maybe broke again?

On 2012-01-09 13:51:08, @DavidGoldwasser wrote:

> This user seems to have same issue.

On 2012-01-09 13:51:20, @DavidGoldwasser wrote:

> Forgot thread
> https://openstudio.nrel.gov/forums/openstudio-plug-google-sketchup/help-desk/modified-idf

On 2012-01-16 14:49:28, @DavidGoldwasser wrote:

> I think this is still a valid bug, but tagged as "Invalid?" so I remember to retest it.

On 2012-01-19 10:52:48, @DavidGoldwasser wrote:

> Batch moving bugs from SketchUp to "Code" component

Keywords: Invalid?

**Comment by DavidGoldwasser** [comment]
This be good now.
