### ISSUE TITLE
Support Testing of Python Measures with standard OpenStudio install

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#4906]
Enhancement Request
--------------
example Python measures included with OpenStudio use `pytest` for the measure tests. `pytest` isn't included in the EnergyPlus Python that is used by the OpenStudio CLI when `openstudio labs my_test.py` is run.

## Detailed Description
While a clean OpenStudio installer can run OSW file with labs that runs fine, there isn't way currently to run measure tests. We want to make it easy for novice measure writes to write and use tests when developing or altering Python measures, as we have done for Ruby measures. The goal here is to provide update the example measure tests, and make any changes necessary so the example Python measure, and other Python measures that do not use external packages can be tested with out of the box OpenStudio installer.

## Possible Implementation
Preferred solution is to change to use `unittest` and fix issues that exist. When I try to `import unittest` on non-developer mac OpenStudio I get the following error. I have not tested on Windows.
```
  File "/Users/dgoldwas/Documents/github/nrel/openstudio-common-measures-gem/lib/measures/IncreaseRoofRValuePython/tests/test_measure.py", line 2, in <module>
    import unittest
  File "/Applications/OpenStudio-3.6.0/EnergyPlus/python_standard_lib/unittest/__init__.py", line 60, in <module>
    from .async_case import IsolatedAsyncioTestCase
  File "/Applications/OpenStudio-3.6.0/EnergyPlus/python_standard_lib/unittest/async_case.py", line 1, in <module>
    import asyncio
  File "/Applications/OpenStudio-3.6.0/EnergyPlus/python_standard_lib/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/Applications/OpenStudio-3.6.0/EnergyPlus/python_standard_lib/asyncio/base_events.py", line 23, in <module>
    import socket
  File "/Applications/OpenStudio-3.6.0/EnergyPlus/python_standard_lib/socket.py", line 49, in <module>
    import _socket
ModuleNotFoundError: No module named '_socket'
```

If we can't get `unittest` to work, it would be fine as an alternative to add `pytest` to OpenStudio's Python, so that the existing example Python Measure tests work as written.

**Comment by jmarrec** [comment]
I'd ideally like to actually bundle some packages into the CLI (install them in the energyplus standard_lib folder), some of which are native. I'm thinking `pytest`, `jinja2` (templating engine similar to ERB, would help @joseph-robertson with #4858 too), maybe `numpy` and `pandas`.
cf #4868 as a premise, and the folllowup branch I plan on making a PR when #4868 is merged: https://github.com/NREL/OpenStudio/commit/38eed7243dc8c01db45613af4ca37cdb4ec078b9

**Comment by kbenne** [comment]
Yeah putting them into the EnergyPlus library folder makes sense to me. The "how" we do this seems more unknown to me. The Python developers on our team seem to be using Poetry a lot. Do we start a poetry project for the things we want to bundle with OS?

**Comment by jmarrec** [comment]
Just `pip install --target=${ENERGYPLUS_DIR}/python_standard_lib --upgrade jinja2 numpy pandas pip`.

People can always use the `--python_path` CLI variable to load anything else they might need.
