### ISSUE TITLE
Systematic warnings with setShadingControlType + setSetpoint(s)

### ISSUE THREAD

**Issue by brgix** [NREL/OpenStudio#4911]
Enhancement Request (low priority)
--------------
User changes to [ShadingControl](https://s3.amazonaws.com/openstudio-sdk-documentation/cpp/OpenStudio-3.6.1-doc/model/html/classopenstudio_1_1model_1_1_shading_control.html#a853cc1d56177ec269bb4bf16cd5a1674) control **type** (e.g. from the default "_OnIfHighSolarOnWindow_") and/or to required **setpoint**(s)  trigger one or more warnings to STDOUT (for instance a systematic [resetSetpoint](https://github.com/NREL/OpenStudio/blob/872300de73e3223f0d541269def844b6250a3ed0/src/model/ShadingControl.cpp#L274), triggering this warning: https://github.com/NREL/OpenStudio/blob/872300de73e3223f0d541269def844b6250a3ed0/src/model/ShadingControl.cpp#L334

IMO, these warnings are atypical for the SDK, unnecessary, and a source of confusion.

## IRB steps to trigger STDOUT warnings:

```
require 'openstudio'
model = OpenStudio::Model::Model.new
shd = OpenStudio::Model::Shade.new(model)
ctl = OpenStudio::Model::ShadingControl.new(shd)
ctl.setSetpoint(18)
ctl.setShadingControlType("OnIfHighOutdoorAirTempAndHighSolarOnWindow")
```

or

```
require 'openstudio'
model = OpenStudio::Model::Model.new
shd = OpenStudio::Model::Shade.new(model)
ctl = OpenStudio::Model::ShadingControl.new(shd)
ctl.setSetpoint(18)
ctl.setSetpoint2(100)
ctl.setShadingControlType("OnIfHighOutdoorAirTempAndHighSolarOnWindow")
```

## Possible Implementation
The simplest would be to cease generating such warnings altogether. There are numerous OpenStudio objects that are generated without a complete set of attributes (or maybe conflicting ones), only to be discovered when attempting to run an E+ simulation. Users aren't warned in advance; more of a _consumer beware_ approach. It's great to rely on returned booleans to signal successful/failed attempts to re/set attributes, but I would prefer less verbose assistance such as the warnings discussed here.

A more nuanced solution would be to provide method overrides with additional parameters as needed (without triggering warnings), e.g.:

`ctl.setShadingControlType("OnIfHighOutdoorAirTempAndHighSolarOnWindow", 18, 100)`

... possibly even with default parameter values if missing.

## Possible BUG
Not 100% certain, but I think this is a bug:

https://github.com/NREL/OpenStudio/blob/872300de73e3223f0d541269def844b6250a3ed0/src/model/ShadingControl.cpp#L409

... should it not be:

`if (ShadingControl_Impl::isControlTypeValueNeedingSetpoint2(shadingControlType))`

**Comment by jmarrec** [comment]
You're right about the bug part.

As far as the warnings being annoying... Not sure I'm totally with you on this. 

1. Warnings are there to help you understand what's going on.

2. "There are numerous OpenStudio objects that are generated without a complete set of attributes (or maybe conflicting ones), only to be discovered when attempting to run an E+ simulation". Well in some cases that is true, but that's not generally the intent of the SDK. Sometimes we just can't, or just won't (some less used/advanced objects don't necesarilly deserve too much engineering).

3. If you're annoyed, just turn off the logging (or set the log level to Error) around the block that does it. Or set a negative lookbehind filter to exclude ShadingControl globally. This should do it: `OpenStudio::Logger.instance.standardOutLogger.setChannelRegex('.*(?<!ShadingControl)$')`

```
[1] model(main)> OpenStudio::logFree(OpenStudio::Warn, "openstudio.model.Other", "Warn")
[openstudio.model.Other] <0> Warn
=> nil
[2] model(main)> OpenStudio::logFree(OpenStudio::Warn, "openstudio.model.ShadingControl", "Warn")
[openstudio.model.ShadingControl] <0> Warn
=> nil
[3] model(main)> OpenStudio::Logger.instance.standardOutLogger.setChannelRegex('.*(?<!ShadingControl)$')
=> nil
[4] model(main)> OpenStudio::logFree(OpenStudio::Warn, "openstudio.model.Other", "Warn")
[openstudio.model.Other] <0> Warn
=> nil
[5] model(main)> OpenStudio::logFree(OpenStudio::Warn, "openstudio.model.ShadingControl", "Warn")
=> nil
```

4.  I suppose this block can be eliminated though https://github.com/NREL/OpenStudio/blob/872300de73e3223f0d541269def844b6250a3ed0/src/model/ShadingControl.cpp#L270-L277
