### ISSUE TITLE
CAN'T FIND ERROR ON OS SIMULATION

### ISSUE THREAD

**Issue by ivantaboas1** [NREL/OpenStudio#4913]
Issue overview
--------------

I have been trying for days to solve an error in the simulation I am running in openstudio and, although the run tab gives me an error, in the err file I can't find any error, severe. help.

I inserted VRF system to my 7 zones building and also an air loop in order to comply with the OA ventilation. 

I have already did the same to a project that is pretty alike to this one, but in this case i just dont know what is going on. 

I will let here below an image of the error and also the .err file, for you guys to see as there is nothing severe o fatal o error at all. Only warnings. 

Thank you.

![2023-06-09_18h53_38](https://github.com/NREL/OpenStudio/assets/136110558/50d1d84c-3de3-4f7f-a588-e1ee80136c53)

(https://github.com/NREL/OpenStudio/files/11708577/error.document.txt)

![2023-06-09_18h53_38](https://github.com/NREL/OpenStudio/assets/136110558/88737aaa-c790-42b0-b786-97b58bff97bc)

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

**Comment by jmarrec** [comment]
It's the OpenStudioResults reporting measure that's failing. We have an issue template in place for a good reason, and unfortunately you just ignored it. What version of OpenStudio are you using? Have you tried getting the Latest OpenStudioResults reporting measure?

**Comment by jmarrec** [comment]
Also, I suppose this is the same issue as https://unmethours.com/question/80413/problem-in-openstudio-measure-in-34/

**Comment by jmarrec** [comment]
SAme issue as https://github.com/NREL/OpenStudio/issues/4678 and should be fixed via https://github.com/NREL/OpenStudio/pull/4681 , so fixed in OpenStudio SDK 3.5.0.
