### ISSUE TITLE
User model simulation on 21 zone model with ideal air loads takes 2 hours to run

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#492]
Model has 21 thermal zones
Model has 91 spaces
Model has 710 base surfaces
Model has 140 sub surfaces
Model has 0 shading surfaces
Model has 0 interior partition surfaces

Above is some information from the diagnostic script. This is running in 1.0.4 with E+8. My guess is that the issue is not the number of surfaces in the model, but some specific zones with a large number of surfaces because of merged spaces. I think this user only cared about part of the building, so they lumped 50 spaces they didn't into a single zone. Not a good idea spanning multiple floors and wings. But does demonstrate an issue we can improve on. The simulation took 2 hours to run. It is running on local drive not network (I have made that mistake before).

@macumber @lgentile 
I have wanted to write a measure to address this for a long time. Hopefully after the release I can look at it, and see how much quicker this simulation is. (hopefully 5-10 minutes instead of 120. Below is a brief outline of measure technique. Some options would have bool checkboxes to enable/disable them.
1. Merge co-planer adjacent surfaces in the same zone so long as they don't make a convex surface.
2.  Combine internal mass objects within a zone using the same construction into much smaller set of objects. Can be one as long as the area isn't greater than the floor area of the space. If it gets large than make more surfaces as needed. Could offer a use option to remove these all together.
3. Offer option to create ribbon windows from discrete windows.
4. In-directly related to this I want to write a measure that takes a first stab at zoning a building, by merging adjacent space on same floor with same space type into a zone, can be options on how to address corner spaces (this will discourage the one space per zone approach).
5. We can also make thermal zone multipliers more accessible.

2-5 should be pretty easy, 1 will take a little more work. Long term, some of these could be simulation settings in C++ vs. measures. But measures seem like a nice way to handle it and offer the user a lot of control.

**Comment by macumber** [comment]
@DavidGoldwasser I think this is too big to be one issue, can you break it up?

**Comment by evanweaver** [comment]
Closed. Optimizations have since been made to model.
