### ISSUE TITLE
Wrap ZoneHVAC:RefrigerationChillerSet

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#4921]
Enhancement Request
--------------
OpenStudio already wraps [Refrigeration:AirChiller](https://s3.amazonaws.com/openstudio-sdk-documentation/cpp/OpenStudio-3.6.0-doc/model/html/classopenstudio_1_1model_1_1_refrigeration_air_chiller.html), but it is not much use without the zone equipment to reference it. ZoneHVAC:RefrigerationChillerSet is needed to model refrigerated warehouses.

https://bigladdersoftware.com/epx/docs/23-1/input-output-reference/group-zone-forced-air-units.html#zonehvacrefrigerationchillerset

https://github.com/NREL/EnergyPlus/blob/develop/testfiles/RefrigeratedWarehouse.idf

**Comment by jmarrec** [comment]
RefrigerationAirChiller is used on the RefrigerationSystem and RefrigerationSecondarySystem https://bigladdersoftware.com/epx/docs/23-1/input-output-reference/group-refrigeration.html#field-refrigerated-case-or-walkin-or-caseandwalkinlist-name and can apparently be used without this object. 

Just saying, not saying ZoneHVAC:RefrigerationChillerSet does not fit a purpose and shouldn't be wrapped. 

It seems to be a rather simple object. I really, really, really, don't like the IDD though. Seems that it should be a proper ZoneHVAC component, defining the Inlet / outlet nodes, and being part of the ZoneHVACEquipment etc, but apparently it's more of a space load...

```diff
-  A3  , \field Zone Name
        \note This must be a controlled zone and appear in a ZoneHVAC:EquipmentConnections object.
        \type object-list
        \object-list ZoneNames
  A4 ,  \field Air Inlet Node Name
        \type node
-        \note Not used - reserved for future use
        \note Name of the zone exhaust node (see Node) from which the refrigeration chiller
        \note draws its indoor air.
        \note This should be one of the zone exhaust nodes for the zone cooled by the chiller set.
  A5 ,  \field Air Outlet Node Name
        \type node
-        \note Not used - reserved for future use
        \note The name of the node where the chiller coil sends its outlet air,
        \note which must be one of the inlet air nodes for the zone which is being cooled.
```

**Comment by jmarrec** [comment]
I wish this was documented a bit better, but this is actually already handled.

https://github.com/NREL/OpenStudio/blob/79e9fe35a4d7dddd7f93f3c8c2e9b2d2e7d94dc7/src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACEquipmentList.cpp#L162-L166

**Comment by jmarrec** [comment]
Added a docstring explaining this in https://github.com/NREL/OpenStudio/commit/2af6123b91304e12060af360d0afb24083336a4c , this will show on the SDK documentation

**Comment by eringold** [comment]
thanks @jmarrec!
