### ISSUE TITLE
Port Measure Manager to C++ (make sure solution for tools that currently call Measure Manager directly instead of through the CLI

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#4929]
Enhancement Request
--------------

**Comment by DavidGoldwasser** [comment]
Note, don't remove Ruby implementation at this point.

**Comment by DavidGoldwasser** [comment]
Maybe add helper measure methods to OpenStudio from Ext gem at the same time.

**Comment by DavidGoldwasser** [comment]
@brianlball you can describe what you still need MeasureManager gem for. In future hopefully we can role that into C++ as well, or is it needed outside of OpenStudio?

**Comment by brianlball** [comment]
I think the MEasure Manager was just used in OpenStudio CLI and PAT GUI, right?

**Comment by brianlball** [comment]
the server openstudio_meta doesnt use it  https://github.com/NREL/OpenStudio-server/blob/develop/bin/openstudio_meta#L150
