### ISSUE TITLE
`evaluate` method improperly working when curve type is `TableMultiVariableLookup`

### ISSUE THREAD

**Issue by JanghyunJK** [NREL/OpenStudio#4937]
Issue overview
--------------

- unsure if this is a known issue. searched the issue tab a bit but couldn't find one.
- when `evaluate` method is used on `TableMultiVariableLookup` object then it outputs weird values. 
- compare to the above and in a similar code setup, when `evaluate` method is used on `CurveBiquadratic` object then it outputs reasonable values. 

## Current Behavior
- example below is the output of `evaluate` on `TableMultiVariableLookup` where values all result in the same negative value even though there were differences in inputs (e.g., one of the independent variable varies from 10 to 110).

![image](https://github.com/NREL/OpenStudio/assets/26775789/34fdf766-90ea-475a-9fde-1a3155159e4a)

## Expected Behavior
- example below is the output of `evaluate` on `CurveBiquadratic` where values are now different and reasonable.

![image](https://github.com/NREL/OpenStudio/assets/26775789/0cf2bbdf-ff14-48f5-a45c-d51e05ca3f8f)

## Steps to Reproduce
I'll think of a way for creating a simple example set for reproducing later...

## Possible Solution
can't think of one.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows
 - Version of OpenStudio (if using an intermediate build, include SHA): OS 3.6.1

### Context
ComStock/EUSS

**Comment by shorowit** [comment]
I don't know anything about this, but it's interesting that [the SDK documentation](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-3.6.1-doc/model/html/classopenstudio_1_1model_1_1_table_multi_variable_lookup.html#a766244b5f16155056d3486a4502e958b) says "Not supported. This is inherited from the base class."

**Comment by JanghyunJK** [comment]
(although I can't say I'm understanding everything in SDK) the `evaluate` method is used on [Curve class](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-3.6.1-doc/model/html/classopenstudio_1_1model_1_1_curve.html). And since the Curve class includes many types of curves (including lookup table) as shown below. I think making that method 'deprecate' on `TableMultiVariableLookup` class makes sense to me...

![image](https://github.com/NREL/OpenStudio/assets/26775789/1f8fef29-4c3b-4a15-bbf1-f819290212d4)

**Comment by jmarrec** [comment]
This method had the Warn message and -999 / -9999  return for a very long time. At least 2.9.0, in 2018, where I changed from 1.0 to this: https://github.com/NREL/OpenStudio/commit/21afcf837c266f76d3f5806783ded560bc9efcec#diff-81d96df590fcca02ac7bd97ca2a612f1050bb14f91f0bb53efb6423856e5ee2dR675

Also, this object itself is deprecated, replaced with TableLookup, which has the same https://github.com/NREL/OpenStudio/blob/2e7a2d82530d964395179f53075cdf012c63455b/src/model/TableLookup.cpp#L65-L68

Table objects inherit from Curve, and all other objects do have an evaluate function that works. Changing the return type to `boost::optional<double>` would penalize everyone and be an API break, so returning -9999 + a Warn message seems like a valid solution to me.

Implementing the TableLookup::evaluate would require adding interpolation facilities similar to E+, which uses a third party lib ([btwxt](https://github.com/bigladder/btwxt)). Too much complexity (and maintanability burden) for little gain.

**Comment by jmarrec** [comment]
Opened a new enhancement request to completely remove this object: https://github.com/NREL/OpenStudio/issues/4952
