### ISSUE TITLE
WaterToAirHeatPumpEquationFit curves do not support Table:Lookup

### ISSUE THREAD

**Issue by mleachNREL** [NREL/OpenStudio#4946]
Issue overview
--------------
CoilCoolingWaterToAirHeatPumpEquationFit and CoilHeatingWaterToAirHeatPumpEquationFit do not support specifying curve data using Table:Lookup.

They are supposed to accept \reference QuadvariateFunctions but the documentation shows only that Curve:QuadLinear and Curve:QuintLinear are allowed for their respective curve fields

### Context
This is needed for ComStock GSHP measure development
[coil_bug.rb.txt](https://github.com/NREL/OpenStudio/files/12443495/coil_bug.rb.txt)

**Comment by joseph-robertson** [comment]
Perhaps `bool setTotalCoolingCapacityCurve(const CurveQuadLinear& totalCoolingCapacityCurve);` needs to be relaxed to something like `bool setTotalCoolingCapacityCurve(const Curve& totalCoolingCapacityCurve);`?

Probably need to inventory all objects where curve type is too exclusive.

**Comment by joseph-robertson** [comment]
This issue is probably a lot like https://github.com/NREL/OpenStudio/issues/4611.

**Comment by jmarrec** [comment]
I agree with you @joseph-robertson 

* Change the type to the more generic Curve. **Important: This is an unavoidable API break** and should be documented properly
* Make sure the IDD references are up to date
* Look at E+ source code to make sure that they aren't more restrictions on what's accepted, if so implement them in the setter
