### ISSUE TITLE
Air-cooled Central Heat Pump System

### ISSUE THREAD

**Issue by annajmorton** [NREL/OpenStudio#4956]
Enhancement Request
--------------
Air-cooled heat recovery chillers are used to make chilled water and hot water and share heat between the two systems. With a push towards electrification, these types of systems are becoming more common. Our firm has also designed several of these systems for indoor grow facilities. There does not seem to be a simple way to model this type of system using the SDK. 

## Detailed Description
The existing `OpenStudio::Model::CentralHeatPumpSystemModuleCentralHeatPumpSystemModule` class seems like it could be used, but it is only available as a water-cooled system. It seems like this might also be a limitation with EnergyPlus? Though I do not use EnergyPlus much directly, so maybe there is an easy way to make it air-cooled in the editor. 

I looked at using the `create_central_air_source_heat_pump(model, hot_water_loop)` from the openstudio standards library with a air-cooled chiller, but this combination does not account for energy recovery between the hot and chilled water loops which is significant in some building (e.g. indoor grow facilities). the `create_central_air_source_heat_pump(model, hot_water_loop)` function uses this class - `OpenStudio::Model::PlantComponentUserDefined`

## Possible Implementation
Could this `OpenStudio::Model::CentralHeatPumpSystemModuleCentralHeatPumpSystemModule` class be modified to allow for air-cooled systems?

**Comment by jmarrec** [comment]
I/O reference guide: https://bigladdersoftware.com/epx/docs/23-1/input-output-reference/group-heating-and-cooling-coils.html#ASIHPIO
