### ISSUE TITLE
AirLoopHVACUnitarySystem: Look at changes in Fan energy use between 3.6.1 and current develop

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#4963]
Issue overview
--------------

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

**Comment by DavidGoldwasser** [comment]
More detail to come later

**Comment by mdahlhausen** [comment]
OpenStudio is now defaulting the "Supply Air Flow Rate Method During Heating Operation" and "Supply Air Flow Rate Method During Cooling Operation" fields to "supplyairflowrate", which is causing regression and performance differences in OpenStudio models.
![image](https://github.com/NREL/OpenStudio/assets/2249271/d19b06d2-5c56-46f0-aff6-77a1cb50752c)

**Comment by jmarrec** [comment]
Changed in https://github.com/NREL/OpenStudio/pull/4873

**Comment by mdahlhausen** [comment]
Was the intent of #4873 to set new defaults, and accept the resulting change in fan energy use for models made in prior versions of OpenStudio?

**Comment by jmarrec** [comment]
- Fixed via #4971
