### ISSUE TITLE
update gbXML to 7.03

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#4966]
Request from Autodesk to update gbXML version to the latest 7.03. They've switched the gbXML export in Revit to use the latest schema 7.03. They were using a custom version but have aligned theirs with main gbXML. 

The version compatibility matrix should probably be updated to list which gbXML version OpenStudio is validating against.

FYI @StephenRoth2014 and @chriswmackey.

**Comment by DavidGoldwasser** [comment]
@MatthewSteen  and @StephenRoth2014] does this upgrade add in a lot of new objects or is it a small maintenance update. I'm trying to understand if and how much work has to be done in the forward and reverse translator to support this upgrade. Our code freeze is in a few days and our release candidate is in a few weeks. Here is our 3.7.0 release checklist. https://github.com/NREL/OpenStudio/issues/4967

**Comment by DavidGoldwasser** [comment]
Work is in PR #4983

**Comment by joseph-robertson** [comment]
Does #4995 close this issue? Do we still need to update a version compatibility matrix somewhere?

**Comment by mostaphaRoudsari** [comment]
Hi @MatthewSteen and @DavidGoldwasser,

I imagine the new schema is backwards compatible. Is that correct? Otherwise, it might break several workflows that are relying on GBXML files that are generated with older versions.

**Comment by joseph-robertson** [comment]
Closed in #4995.
