### ISSUE TITLE
Add native support for measure argument methods in OsLib_HelperMethods 

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/OpenStudio#4993]
Enhancement Request
--------------
There are several methods in `OsLib_HelperMethods` in the extension gem that should be native to the `Measure` or `Measure::OSArgument` objects in OpenStudio.

## Detailed Description
These are the specific methods that **_could_** be implemented in OpenStudio:
```
- check_upstream_measure_for_arg(runner, arg_name)
- checkChoiceArgFromModelObjects(object, variableName, to_ObjectType, runner, user_arguments)
- checkDoubleAndIntegerArguments(runner, user_arguments, arg_check_hash)
- checkOptionalChoiceArgFromModelObjects(object, variableName, to_ObjectType, runner, user_arguments)
- createRunVariables(runner, model, user_arguments, arguments)
- populateChoiceArgFromModelObjects(model, modelObject_args_hash, includeBuilding)
```

## Possible Implementation
To be clear, I DO NOT think these methods should be adopted as is. Some are already partially or mostly addressed (checkDoubleAndIntegerArguments with #4551). @DavidGoldwasser - can you analyze which methods should live in OpenStudio, and which are best left to code in the measure, then comment below? @eringold may have thoughts as well.

**Comment by joseph-robertson** [comment]
Another method:
```
- getAbsoluteAzimuthForSurface(surface, model)
```
(/openstudio-extension-gem/lib/openstudio/extension/core/os_lib_geometry.rb)

**Comment by joseph-robertson** [comment]
Perhaps we could create an overloaded `runner.validateUserArguments(script_arguments, user_arguments, model)` method (note the `model` is new) that checks, for any user argument that has a handle (i.e., a UUID), whether that handle exists in `model`.

Would this cover some of the functionality of the `OsLib_HelperMethods.checkXXX` methods above?

**Comment by jmarrec** [comment]
`populateChoiceArgFromModelObjects`. How about we do it this way:

static OSArgument makeChoiceArgument(const std::string& name, const std::map<std::string, std::string>& choices_to_display_values_map, bool required = true,  bool modelDependent = false);

That way you could do something like

```ruby
choices_to_display_values_map = (
  model.getInteriorPartitionSurfaces
       .reject{|s| s.construction.empty?}
       .map(&:construction).map(&:get)
       .map{|c| [c.handle.to_s, c.nameString]}.to_h
)
choices_to_display_values_map[model.getBuilding.handle.to_s] = "*All Interior Partition Surfaces*"
object = OpenStudio::Measure::OSArgument.makeChoiceArgument('object', choices_to_display_values_map, true, true)
```

I think it's way more flexible that way.
