### ISSUE TITLE
Default new CoilCoolingWaterToAirHeatPumpEquationFit fields in forward translator

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/OpenStudio#4999]
Issue overview
--------------
OS 3.7 adds several new fields to the CoilCoolingWaterToAirHeatPumpEquationFit object:
- Part Load Fraction Correlation Curve Name
- Nominal Time for Condensate Removal to Begin {s}
- Ratio of Initial Moisture Evaporation Rate and Steady State Latent Capacity {dimensionless}
- Maximum Cycling Rate {cycles/hr}
- Latent Capacity Time Constant {s}
- Fan Delay Time {s}

The defaults are not aligned between OS object creation and the version translator.

## Current Behavior
In the forward translator, the defaults for these new fields are different than the defaults used when updating an older .osm using the version translator.
The result is a regression error:
```
For OS:Coil:Cooling:WaterToAirHeatPump:EquationFit called 'T SW Apartment ZN PSZ-AC Water-to-Air HP Clg Coil 20kBtu/hr 13.0EER'  'Latent Capacity Time Constant': true model = '60.0', compare model = '0.0'
For OS:Coil:Cooling:WaterToAirHeatPump:EquationFit called 'T SW Apartment ZN PSZ-AC Water-to-Air HP Clg Coil 20kBtu/hr 13.0EER'  'Maximum Cycling Rate': true model = '2.5', compare model = '0.0'
```

## Expected Behavior
Either the OS defaults should change, or the version translator should set the new defaults upon translation to avoid regression errors.

## Steps to Reproduce
1. Create a model with CoilCoolingWaterToAirHeatPumpEquationFit object in OS 3.6.1
2. Forward translate it with OS develop
3. Create a model with CoilCoolingWaterToAirHeatPumpEquationFit in OS develop
4. compare

### Context
impacting openstudio-standards regression tests

**Comment by jmarrec** [comment]
Now:
* I can't touch the VersionTranslator, as this would create a regression. The behavior of a 3.6.1 model should be preserved when updating to 3.7.0
* Thus, there are only two possible paths:
    * Have our SDK Ctor use a different default than E+. I'm not a huge fan of this idea, generally speaking, because it's a bit confusing, but it's maybe fine. (I'm going to prepare a PR that does this, so we have CI running on it and you can test, we can decide if we keep it or trash it)
    * You, on openstudio-standards, set these fields explicitly. @mdahlhausen is that an option? (I don't know what are the side effects of doing this)

**Comment by jmarrec** [comment]
For reference:

```
$ rg -g '*.cpp'  --max-depth 1 "setLatentCapacityTimeConstant\([\d.]+\)"
CoilCoolingDXVariableSpeed.cpp
743:    ok = setLatentCapacityTimeConstant(60.0);
795:    ok = setLatentCapacityTimeConstant(60.0);

CoilCoolingDXCurveFitOperatingMode.cpp
459:    setLatentCapacityTimeConstant(0.0);

CoilCoolingDXSingleSpeed.cpp
960:    setLatentCapacityTimeConstant(0.0);
1000:    setLatentCapacityTimeConstant(0.0);

CoilCoolingDXMultiSpeedStageData.cpp
628:    ok = setLatentCapacityTimeConstant(0.0);
675:    ok = setLatentCapacityTimeConstant(0.0);

CoilPerformanceDXCooling.cpp
590:    setLatentCapacityTimeConstant(45);
614:    setLatentCapacityTimeConstant(45);

CoilCoolingWaterToAirHeatPumpVariableSpeedEquationFit.cpp
520:    ok = setLatentCapacityTimeConstant(0.0);
558:    ok = setLatentCapacityTimeConstant(0.0);

CoilCoolingWaterToAirHeatPumpEquationFit.cpp
594:      ok = setLatentCapacityTimeConstant(0.0);
```

**Comment by mdahlhausen** [comment]
Thanks @jmarrec. I can make the openstudio-standards fix.
