### ISSUE TITLE
M1 chip mac cannot run sizing run properly

### ISSUE THREAD

**Issue by wenyikuang** [NREL/OpenStudio#5004]
Issue overview
--------------

In M1 mac, 
installed the 3.7rc1 with dmg installer, it wil raise exception from energy plus and openstudio cannot finish the run.

```
➜  test_workflow_370rc1 openstudio --version
3.7.0-rc1+211bb633b0
```
error message from the run:

```

```

## Steps to Reproduce
1. Download the test_workflow.zip.
2. Install the openstudio-3.7.0-rc1 [dmg](https://github.com/NREL/OpenStudio/releases/download/v3.7.0-rc1/OpenStudio-3.7.0-rc1+211bb633b0-Darwin-arm64.dmg) from github release.
3. `openstudio run -w ./run/workflows/bar_typical/in.osw`

## Possible Solution
- Could be unmatched version of energyplus and openstudio.
- Could be some permission issue. (Since it works on arm-linux, intel-mac, windows)

### Environment
- mac OS 12.7
- example workflow [test_workflow_370rc1.zip](https://github.com/NREL/OpenStudio/files/13192111/test_workflow_370rc1.zip)

**Comment by DavidGoldwasser** [comment]
See more details here, found in extension gem testing on mac, but issue happens with measure tests or OSW run. Seems to be specific to sizing runs, but that is just the first time the tests call EnergyPlus.
https://github.com/NREL/openstudio-extension-gem/issues/168

**Comment by jmarrec** [comment]
`brew install libomp`

**Comment by DavidGoldwasser** [comment]
I tested on non-Dev Windows machine this weekend and hit the same issue.

**Comment by jmarrec** [comment]
I just booted a clean windows 10 VM (**x86_64**, See `[1]`), and I cannot reproduce the issue on Windows. Do you have more information @DavidGoldwasser ?



Note: `[1]` you can't run a windows 11 VM on an M1 mac as it will be arm64 and the installer is built for x86_64
