### ISSUE TITLE
3.7.0-rc2 testing: C++ CLI issues

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#5016]
Issue overview
--------------

@shorowit reported these to me:

- [x] #5017
    ```
  "run_options": {
    "fast": true,
    "skip_expand_objects": true,
    "skip_energyplus_preprocess": true
  }
   ```

- [x] #5018
- [x] #5020
- [x] #5019
- [x] #5030

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.7.0-rc2

**Comment by jmarrec** [comment]
# 5. No Results.json is produced after running an OSW

https://github.com/NREL/OpenStudio/blob/c0cbe73b51f34c459d67a17d36739795bbf25fc2/src/workflow/RunReportingMeasures.cpp#L60-L67

**Comment by jmarrec** [comment]
6. I think the piggy back is happening here: https://github.com/NREL/OpenStudio-workflow-gem/blob/696306b5b24cd597edc6ab04faa1e618f99db190/lib/openstudio/workflow_runner.rb#L189-L217

**Comment by shorowit** [comment]
Looks like all of these comments have been addressed (🎉). Thanks, @jmarrec!
