### ISSUE TITLE
C++ CLI: results.json is not created

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#5019]
Issue overview
--------------

## Current Behavior

No results.json is produced after running an OSW.

## Expected Behavior

Apparently it's still needed.

## Possible Solution

https://github.com/NREL/OpenStudio/blob/c0cbe73b51f34c459d67a17d36739795bbf25fc2/src/workflow/RunReportingMeasures.cpp#L60-L67

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.7.0-rc2

### Context

- #5016

**Comment by jmarrec** [comment]
@shorowit can you please help me understand this one please?

* What is results.json used for?
* Is this something that's only created when you have a `measure_attributes.json` in the run folder like I think it is?
* Is the "analysis" stuff also still needed?

Basically I think it's this method from the workflow-gem that isn't implemented: https://github.com/NREL/OpenStudio-workflow-gem/blob/696306b5b24cd597edc6ab04faa1e618f99db190/lib/openstudio/workflow/util/post_process.rb#L31-L100

**Comment by brianlball** [comment]
Yes, all the "analysis" stuff is needed for OSAF
