### ISSUE TITLE
using labs as default in 3.7.0-rc2 broke use of `verbose`

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#5024]
New method is --trace. This is likely to create issues for many downstream OpenStudio users. Can we me either have `verbose` work or setup a synonym to --trace.

I'll leave that to @kbenne @jmarrec and @wenyikuang to decide that.

**Comment by jmarrec** [comment]
There is a distinct commit where i removed the --verbose in favor just --loglevel [LOGLEVEL] after asking for input. We can just revert that if it's, after all, needed

**Comment by jmarrec** [comment]
Reverted fada36f in 2a399fc7c20bd321bcbb66f2746b19444cc2641a
