### ISSUE TITLE
mac openstudio sketchup pulgin error

### ISSUE THREAD

**Issue by kitty9385** [NREL/OpenStudio#5026]
Hello, expert.

I am using MacBook M1.

OpenStudio-3.6.1, OpenStudioApplication-1.6.0, and SketchUp 2023.

The plug-in was downloaded below.
https://github.com/openstudiocoalition/openstudio-sketchup-plugin/releases/tag/v1.6.0-rc.1

Isn't it the right version?

I think the version is correct, but I can't enter the path.

I attach the picture below.

These are the screens that appear when you change 'Do not use' to 'Use'.

If you restart scketchup after the screen appears like the last picture, it will appear again like the first picture.

The context may be awkward using a translator.

Please help me.

<img width="991" alt="스크린샷 2023-11-11 오후 5 18 57" src="https://github.com/NREL/OpenStudio/assets/150419459/ba29093e-5535-444b-a26b-8870f6c10901">
<img width="425" alt="스크린샷 2023-11-11 오후 5 19 11" src="https://github.com/NREL/OpenStudio/assets/150419459/0f844abb-190a-41cc-8fc4-4cb9a181502a">
<img width="253" alt="스크린샷 2023-11-11 오후 5 19 18" src="https://github.com/NREL/OpenStudio/assets/150419459/37f284e5-fcbe-4981-b94d-cd5e217ef28c">

**Comment by jmarrec** [comment]
Wrong repository (I understand the confusion though). Should be filed at https://github.com/openstudiocoalition/openstudio-sketchup-plugin

Anyways, try setting it to `/Applications/OpenStudioApplication-1.6.0/` if that's where you installed it. If it doesn't work, open an issue on https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues please.
