### ISSUE TITLE
Adjust LogSink log formatter

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#5037]
Issue overview
--------------

Prompted by the fact that the run.log looks quite different between the classic (Ruby) and the C++ CLI.

Additionally, the default formatter is not great. The use of Integers for the log level is unnecessarily confusing. I think I know how to turn the LogLevel enum into a string (eg: "Debug" instead of `-1`)

https://github.com/NREL/OpenStudio/blob/3f35a4ce446e1e91a4ec0c559aeca226b2715099/src/utilities/core/LogSink.cpp#L126-L131

## Current Behavior

**C++**

```
[openstudio.measure.OSRunner] <0> runner.registerWarning called
[openstudio.workflow.OSWorkflow] <0> No results for objective function IsNonExisting.NonExisting
```

**Ruby**:

```
[13:54:18.023960 WARN] runner.registerWarning called
[13:54:18.056100 WARN] No results for objective function IsNonExisting.NonExisting
```

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

**Comment by jmarrec** [comment]
`LOG_FREE(Debug, "Channel", "MSG")`

```
# C++
[Channel] <-1> MSG
# Ruby's run.log
[11:12:13.123456 DEBUG] MSG
```

Proposed:

```
# Proposed
# Stdout
[Channel] <Debug> MSG
# run.log
[11:12:13.123456 DEBUG] [Channel] MSG
```

**Comment by kbenne** [comment]
I like the proposed format `[11:12:13.123456 DEBUG] [Channel] MSG` without a switch. Would that be ok for everyone? @shorowit @joseph-robertson
