### ISSUE TITLE
EnergyPlus ExpandObjects program will not launch

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#5050]
Specifically, the ExpandObjects program that is provided by the EnergyPlus package and bundled into OpenStudio, will not launch on Mac OS. This is because OpenStudio is not packaging the required `libgcc_s.1.1.dylib`, which is required and shipped with the EnergyPlus package.

The solution is probably to add an install command [here](https://github.com/NREL/OpenStudio/blob/55040fb543628bcbeff73532d488d6ad8ba968ee/CMakeLists.txt#L1337)

**Comment by jmarrec** [comment]
The 10.15 GHA runner does https://github.com/NREL/EnergyPlus/actions/runs/6346395022/job/17239821140#step:8:153
This wasn't the case in the 23.1.0 installer... 
* https://github.com/NREL/EnergyPlus/pull/9676
* https://github.com/NREL/EnergyPlus/pull/9682

Something changed on Github actions probably...

```
-- Found static-libquadmath at /usr/local/Cellar/gcc@11/11.4.0/lib/gcc/11/libquadmath.a by searching in CMAKE_Fortran_IMPLICIT_LINK_DIRECTORIES=/usr/local/Cellar/gcc@11/11.4.0/lib/gcc/11/gcc/x86_64-apple-darwin21/11;/usr/local/Cellar/gcc@11/11.4.0/lib/gcc/11/gcc;/usr/local/Cellar/gcc@11/11.4.0/lib/gcc/11;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib
-- FORTRAN_LIBS=-lgfortran;-lgcc_s.1.1;-lgcc;/usr/local/Cellar/gcc@11/11.4.0/lib/gcc/11/libquadmath.a
```

My M1 mac, where there is no libgcc_s.1.1.dylib in the executable.

```
-- Found static-libquadmath at /opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/current/libquadmath.a by searching in CMAKE_Fortran_IMPLICIT_LINK_DIRECTORIES=/opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/current/gcc/aarch64-apple-darwin22/13;/opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/current/gcc;/opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/current
-- FORTRAN_LIBS=-lgfortran;-lemutls_w;-lgcc;/opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/current/libquadmath.a
```
