### ISSUE TITLE
3.7 Docker Image Energy Plus command does not recognize arguments on Mac OSX

### ISSUE THREAD

**Issue by rh0dium** [NREL/OpenStudio#5057]
Updated Issue
--------------

I'm working with [nrel/openstudio:3.7.0](https://hub.docker.com/layers/nrel/openstudio/3.7.0/images/sha256-72cdd0420bc807698a6f02efedc5234b6a2a336ce4801cae7a984b9d36ef88da?context=explore) image and we are seeing an error I can't seem to figure out.

Running a basic energyplus command on docker image when the host is a Apple machine will fail

```
> docker run -it --rm -v /Volumes/Development/OpenSudio-ERI:/var/simdata/openstudio nrel/openstudio:3.7.0 bash
>> /usr/local/openstudio-3.7.0/EnergyPlus/energyplus -w ../../weather/USA_CO_Denver.Intl.AP.725650_TMY3.epw in.idf
The following argument was not expected: in.idf
Run with --help for more information.
```

Original Issue overview
--------------

Hey there,

I'm working with [nrel/openstudio:3.7.0](https://hub.docker.com/layers/nrel/openstudio/3.7.0/images/sha256-72cdd0420bc807698a6f02efedc5234b6a2a336ce4801cae7a984b9d36ef88da?context=explore) image and we are seeing an error I can't seem to figure out.

Running the following command for [OS-ERI ](https://github.com/NREL/OpenStudio-ERI) in accordance with the [documentation](https://openstudio-eri.readthedocs.io/en/latest/usage_instructions.html#running-calculations)
`openstudio workflow/energy_rating_index.rb -x workflow/sample_files/base.xml`

## Current Behavior

It errors out and looking at the stderr-energyplus.log I am simply seeing this.
```
The following argument was not expected: in.idf
Run with --help for more information.
```

Note running this locally without the container does not show this behavior.

## Expected Behavior

It should run the simulation

## Steps to Reproduce
1.  Pull down the OS-ERI Repo - `git clone https://github.com/NREL/OpenStudio-ERI.git`
2. Verify this works as expected without the image. `openstudio workflow/energy_rating_index.rb -x workflow/sample_files/base.xml `
3. Next fire off a container `docker run -it --rm -v /Volumes/Development/OpenSudio-ERI:/var/simdata/openstudio nrel/openstudio:3.7.0 bash`
4. Run the same command `openstudio workflow/energy_rating_index.rb -x workflow/sample_files/base.xml`

## Possible Solution
_It should be noted I'm running this on a Mac and there are reports but nothing on how it manifests itself_

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform Mac / Sonoma
 - Version of OpenStudio 3.7.0+d5269793f1

### Context
- Just trying to run simulations ;)
- I don't think this is related to the OS-ERI as this does work when running outside of the container.

BTW - You all rock this is awesome stuff.

**Comment by wenyikuang** [comment]
Could you try to type `openstudio --version` in the container?

**Comment by rh0dium** [comment]
You bet -> `3.7.0+d5269793f1`. This is the same as the outside.

More details - Under the hood the `energy_rating_index.rb` is running effectively (many)

/Applications/OpenStudio-3.7.0/EnergyPlus/energyplus" -w "/Volumes/Development/OpenSudio-ERI/weather/USA_CO_Denver.Intl.AP.725650_TMY3.epw" in.idf

So continuing with your thoughts -  Both inside and outside the container
/usr/local/openstudio-3.7.0/EnergyPlus/energyplus --version
> EnergyPlus, Version 23.2.0-7636e6b3e9

So this is specifically in energyplus it's not recognizing in.idf Which is so weird..

**Comment by rh0dium** [comment]
This is a Mac Issue - Could this be related to #5050 or #5022 

Running this same tests on a Linux machine works as expected
```
cd /tmp
git clone https://github.com/NREL/OpenStudio-ERI.git
> docker pull nrel/openstudio:3.7.0
> docker run -it --rm -v /tmp/OpenStudio-ERI/:/var/simdata/openstudio nrel/openstudio:3.7.0 bash
> > openstudio workflow/energy_rating_index.rb -x workflow/sample_files/base.xml
> > find . -type f -name stderr-energyplus.log | xargs -i cat {}
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
```

**Comment by jmarrec** [comment]
Running on mac M1 the amd64 image.

```
docker pull nrel/openstudio:3.7.0
docker run -it --rm --platform linux/amd64 nrel/openstudio:3.7.0 bash
```

Inside, all of this works fine.

```
curl -sLO https://raw.githubusercontent.com/NREL/EnergyPlus/develop/weather/USA_CO_Golden-NREL.724666_TMY3.epw
curl -sLO https://raw.githubusercontent.com/NREL/EnergyPlus/develop/testfiles/1ZoneUncontrolled.idf
/usr/local/openstudio-3.7.0/EnergyPlus/energyplus -w USA_CO_Golden-NREL.724666_TMY3.epw 1ZoneUncontrolled.idf

cp 1ZoneUncontrolled.idf in.idf
/usr/local/openstudio-3.7.0/EnergyPlus/energyplus -w USA_CO_Golden-NREL.724666_TMY3.epw in.idf
```

**Comment by jmarrec** [comment]
Ok, finally finished cloning OpenStudio-ERI (1 GB!): testing at https://github.com/NREL/OpenStudio-ERI/commit/15b138a30b6ddb9ebf7ddab6a72b11d9365ab883

`docker run -it --rm --platform linux/amd64 -v $(pwd)/OpenStudio-ERI:/var/simdata/openstudio nrel/openstudio:3.7.0 bash`

```
root@3949bb3f9e79:/var/simdata/openstudio#  openstudio workflow/energy_rating_index.rb -x workflow/sample_files/base.xml
HPXML: /var/simdata/openstudio/workflow/sample_files/base.xml
ERICalculation/Version: 2019ABCD
CO2IndexCalculation/Version: 2019ABCD
EnergyStarCalculation/Version: SF_National_3.2
IECCERICalculation/Version: 2021
ZERHCalculation/Version: SF_2.0
Generating 26 HPXMLs...
Running 12 Simulations...
Calculating results...
ERI: 78.47
CO2e Index: 152.49
IECC ERI: 74.51
ENERGY STAR Certification: FAIL
Zero Energy Ready Home Certification: FAIL
Completed in 163.4s.
root@3949bb3f9e79:/var/simdata/openstudio# find . -type f -name stderr-energyplus.log | xargs -i cat {}
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
EnergyPlus Completed Successfully.
```

**Comment by jmarrec** [comment]
This looks like an issue specific to your machine. Unfortunately, I can't fix what I can't reproduce.

Things you could try:

* A different mac machine if you have one handy
* A different terminal (I tested zsh in addition to my primary shell (bash - GNU bash, version 5.2.15(1)-release (aarch64-apple-darwin21.6.0))
* Not loading your .inputrc / .bash_profile in your current terminal

Happy to keep helping as much as I can though, if you have more info to chew on.

**Comment by jmarrec** [comment]
I have the same machine as yours. I think same OS version too (don't have the mac handy).

Can you try the command above with the --debug-cli added ?

**Comment by shorowit** [comment]
I don't think @rh0dium mentioned it above, but it's worth pointing out that he was successfully running OpenStudio-ERI with OpenStudio 3.6. (Right?)

**Comment by jmarrec** [comment]
E+ 23.2.0 is the first release that uses the revamped CLI based on the modern C++ lib CLI11, https://github.com/CLIUtils/CLI11,  and no longer the legacy ezOptionParser stuff (that was a plain C library). 

One thing to try out might be to just run a ubuntu:20.04 docker, install the E+ CLI there (23.2.0 first, then 23.1.0 for comparison if 23.2.0 fails) and try it out. This really looks like it has nothing to do with OpenStudio or the OpenStudio docker image.

**Comment by rh0dium** [comment]
> I have the same machine as yours, M1 Max. I think same OS version too (don't have the mac handy).
> 
> Edit: confirmed.
> 
> ```
> $ sw_vers
> ProductName:		macOS
> ProductVersion:		14.1.2
> BuildVersion:		23B92
> ```
> 
> Can you try the command above with the --debug-cli added ?
> 
> ```
>  /usr/local/openstudio-3.7.0/EnergyPlus/energyplus -w ../../weather/USA_CO_Denver.Intl.AP.725650_TMY3.epw --debug-cli in.idf
> ```
> 
> Try also omitting in.idf

So `--debug-cli` did nothing 

```
> /usr/local/openstudio-3.7.0/EnergyPlus/energyplus -w ../../weather/USA_CO_Denver.Intl.AP.725650_TMY3.epw --debug-cli in.idf
The following argument was not expected: in.idf
Run with --help for more information.
```

But when I ran without in.idf I got something

```
>  /usr/local/openstudio-3.7.0/EnergyPlus/energyplus -w ../../weather/USA_CO_Denver.Intl.AP.725650_TMY3.epw --debug-cli       

state.dataGlobal->AnnualSimulation = false,
state.dataGlobal->DDOnlySimulation = false,
state.dataStrGlobals->outDirPath = '',
state.dataStrGlobals->inputIddFilePath= '/usr/local/openstudio-3.7.0/EnergyPlus/Energy+.idd',

runEPMacro = false,
prefixOutName = eplus,

state.dataGlobal->runReadVars=false,
state.dataGlobal->outputEpJSONConversion=false,
state.dataGlobal->outputEpJSONConversionOnly=false,

suffixType=L,

state.dataGlobal->numThread=1,
state.files.inputWeatherFilePath.filePath='../../weather/USA_CO_Denver.Intl.AP.725650_TMY3.epw',
state.dataStrGlobals->inputFilePath='/usr/local/openstudio-3.7.0/EnergyPlus/energyplus',
```

**Comment by rh0dium** [comment]
@shorowit @jmarrec  - That is correct this was working fine in OpenStudio 3.6

**Comment by rh0dium** [comment]
> E+ 23.2.0 is the first release that uses the revamped CLI based on the modern C++ lib CLI11, https://github.com/CLIUtils/CLI11, and no longer the legacy ezOptionParser stuff (that was a plain C library).
> 
> One thing to try out might be to just run a ubuntu:20.04 docker, install the E+ CLI there (23.2.0 first, then 23.1.0 for comparison if 23.2.0 fails) and try it out. This really looks like it has nothing to do with OpenStudio or the OpenStudio docker image.

So should I create a new issue in the Energy Plus app - that seems more appropriate?

**Comment by rh0dium** [comment]
Added new [ticket](https://github.com/NREL/EnergyPlus/issues/10322) over on energy plus side.  I think we can close this as I was able to replicate it on strictly the energyplus:23.2.0 container.
