### ISSUE TITLE
Problem when importing measure with same name as measure already in project

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#507]
It measure A is model measure and measure B is reporting measure you will get error "failed to compute arguments: superclass mismatch".  Not sure if problem if importing measure with same name and same type.

**Comment by DavidGoldwasser** [comment]
@DavidGoldwasser re-verify post 1.9.0

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
