### ISSUE TITLE
Error messages "already initialized constant" when running OSW workflow

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#5081]
Issue overview
--------------
When running a workflow with the TBD measure (https://github.com/rd2/tbd/releases/tag/v3.4.0) there are a bunch of error messages about "warning: already initialized constant" that occur when adding output reports.  I think this might be because the runner re-loads the measure a second time so any constants are redefined.  However, this second load is not something the measure writer can really control.

## Current Behavior
The "warning: already initialized constant" messages might be confusing to users

## Expected Behavior
There should be no "warning: already initialized constant" error messages.

## Steps to Reproduce
1. Create workflow with TBD measure (https://github.com/rd2/tbd/releases/tag/v3.4.0)
2. Run workflow with `openstudio.exe --verbose run --show-stdout -w workflow.osw`
3. Notice that "warning: already initialized constant" warnings occur after "Beginning to collect output requests from Reporting measures."

## Possible Solution
Maybe it is possible to clear constants between running measures?  Might be possible to list constants/globals before and after each measure run and clear those after each run?

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 11
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.7.0

### Context
Confusing to users, potentially makes users think there are issues with the measure

**Comment by macumber** [comment]
@brgix FYI

**Comment by brgix** [comment]
Thanks @macumber. For what it's worth, I am not able to reproduce the issue with macOS (Sonoma 14.2.1). Replicated the same steps with OpenStudio v3.6.1 versus v3.7.0 : no _"warning: already initialized constant"_ **stdout** feedback with either release. I'll later try reproducing the same _v3.6.1 versus v3.7.0_ steps on a WSL2 set up.

**Comment by DavidGoldwasser** [comment]
@shorowit and @joseph-robertson I think you may use global constants across measures? Just wanted to tag you on this so any changes made for this don't negativity impact those workflows.
