### ISSUE TITLE
Openstudio Preview OSM issues related to "Face difference is self intersecting." How should I fix these errors? I do not understand the error message.

### ISSUE THREAD

**Issue by mohdezzi7** [NREL/OpenStudio#5098]
I created a FloowspaceJS plan based on actual floor plans. However, I am getting an error when I try to preview the FloorspaceJS. Will this error cause me difficulties with merging and inaccurate simulations? 

<img width="1005" alt="image" src="https://github.com/NREL/OpenStudio/assets/32164084/49d56cbd-ca5a-469c-b5b7-a385adb99970">

<img width="373" alt="image" src="https://github.com/NREL/OpenStudio/assets/32164084/2554e0a4-d1a2-4692-a050-92a65d1d9677">

**Comment by jmarrec** [comment]
Not an OpenStudio SDK issue. Maybe a floorspaceJS one, or an OpenStudioApplication one.
