### ISSUE TITLE
Removal of HVAC in osm is causing Segmentation fault in Prototype.utilities.rb

### ISSUE THREAD

**Issue by antonszilasi** [NREL/OpenStudio#5124]
Issue overview
--------------
Upon attempting to call `standard.remove_hvac(model)` (where `standard` is OpenStudio-standards ) on a particular osm with (2 ERVs and 2 PTHPs) in a single zone. 

I received a Segmentation fault in Prototype.utilities.rb of OpenStudio-standards. While this initially appeared to be a OpenStudio-standards error after further digging it appears that this is not the case hence, I am reporting it here.

![image](https://github.com/NREL/OpenStudio/assets/8773483/33b93964-b820-4e00-931c-775953d08473)

![image](https://github.com/NREL/OpenStudio/assets/8773483/6e5c5fa7-a6df-4c57-9283-f54dee8f320e)
![image](https://github.com/NREL/OpenStudio/assets/8773483/03f3f04e-7837-45fa-b0c8-a6f29410a266)

## Steps to Reproduce
I have attached the osm in question along with a small script to load it and call `standard.remove_hvac(model)` to reproduce the error in a zipped directory here.

Since this issue was originally reported on OpenStudio-standards @mdahlhausen kindly provided minimal steps to [reproduce the issue here](https://github.com/NREL/openstudio-standards/issues/1709). 

[Remove HVAC system segmentation fault.zip](https://performancesystemspsd-my.sharepoint.com/:u:/g/personal/aszilasi_psdconsulting_com/ESOIvOsujcJFnV4EQhCyFTgBhU_yHYvhyjqQ8y3_xzsmjg?e=GQnD12)

### Environment
OpenStudio 3.6.1 and 3.7, and OpenStudio standards 0.4 and 0.5

**Comment by jmarrec** [comment]
> This is not an openstudio-standards issue. This is a segmentation fault in OpenStudio because of the duplicate types of zone equipment (2 ERVs and 2 PTHPs) in a single zone in the model. It's likely related to the way removing zone HVAC is handled [here](https://github.com/NREL/OpenStudio/blob/develop/src/model/ZoneHVACEquipmentList.cpp#L318-L363). You are welcome to resubmit this issue under OpenStudio.
> 
> Minimal steps to reproduce:
> 
> ```
> require 'openstudio'
> osm_path = OpenStudio::Path.new('./PTHP with ERV.osm')
> model = OpenStudio::Model::Model.load(osm_path).get
> 
> # simplify model to the one problematic zone and space
> model.getAirLoopHVACs.each(&:remove)
> model.getThermalZones.each { |z| z.remove unless z.name.get == 'ZE1-5' }
> model.getSpaces.each { |s| s.remove unless s.name.get == 'aim1196' }
> 
> # trigger seg fault
> model.getThermalZones.each do |zone|
>   #next if zone.name.get.include?('ZE1-5')
>   zone.equipment.each do |equipment|
>     #next if equipment.name.get.include?('ERV')
>     #next if equipment.name.get.include?('PTHP')
>     puts "Attempting to remove #{equipment.name}"
>     equipment.remove
>   end
> end
> ```

**Comment by jmarrec** [comment]
Can't reproduce on 3.8.0+f953b6fcaf on mac M1.

If someone can reproduce with 3.8.0 on any other machine, I'll reopen.
