### ISSUE TITLE
RemoteBCL updateMeasures does not reliably remove old version

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#5128]
Issue overview
--------------
RemoteBCL updateMeasures is supposed to remove the old version of the measures that are updated.  

## Current Behavior
Currently, the updateMeasures gets the measure after download by uid only, meaning there is a 50/50 chance that it won't remove the old version.

## Expected Behavior
RemoteBCL updateMeasures should remove old measure by version id and uid

## Steps to Reproduce
- Download several measures using RemoteBCL
- Update measures on remote BCL
- Call RemoteBCL updateMeasures

## Possible Solution
https://github.com/NREL/OpenStudio/pull/5127/files

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows
 - Version of OpenStudio (if using an intermediate build, include SHA): v3.7.0

### Context
RemoteBCL updateMeasures is leaving old measures behind

**Comment by jmarrec** [comment]
https://www.sqlite.org/lang_select.html

4. The ORDER BY clause

If a SELECT statement that returns more than one row does not have an ORDER BY clause, the order in which the rows are returned is undefined. Or, if a SELECT statement does have an ORDER BY clause, then the list of expressions attached to the ORDER BY determine the order in which rows are returned to the user.
