### ISSUE TITLE
Release v3.8.0 Tasks

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#5136]
The purpose is this issue is to document tasks that need to be done in order to reach a 3.8.0 release. There is a separate [issue](https://github.com/NREL/OpenStudio/issues/5102) that is related to the quality control steps involved in the 3.8.0 release, but the items listed here need to be addressed before we are ready to move through the QC motions. There is also [another issue](https://github.com/NREL/OpenStudio/issues/5082) to iron out the big tasks, but this issue is more specific.

This is in the approximate order of operations. Please add known tasks here.

- [x] Confirm that Ruby 3.2.2 is the correct target. @DavidGoldwasser would you be able to help get confirmation from SketchUp that they will release against the 3.2.2 version of Ruby? It will be painful if we do a Ruby update and that ends up being the wrong version.
- [x]  @kbenne Document obscure changes to loading the embedded Ruby gems. @kbenne, specifically [this](https://github.com/NREL/OpenStudio/commit/0fbb223bb9def421962ea1607fcbc5745b88e554#r140311044) commit comment has information that would be good to put into a code comment. This is an obscure but important change that we are bound to forget.
- [x] @kbenne consolidate Ruby gem loading code, or bring [this]((https://github.com/NREL/OpenStudio/commit/0fbb223bb9def421962ea1607fcbc5745b88e554#r140311044) ) change over to the classic cli implementation.
- [ ] @kbenne, @jmarrec, and @joseph-robertson  Merge all of the branches going into the release into the [develop](https://github.com/NREL/OpenStudio/tree/develop) branch. This includes the [ruby/3.2.2]()https://github.com/NREL/OpenStudio/tree/ruby/3.2.2 branch. When we merge Ruby 3.2.2 to develop the CI will break and we will be flying blind for a period of time.
- [x] #5152
- [x] @wenyikuang Establish [openstudio-gems](https://github.com/NREL/openstudio-gems) CI for Ruby 3.2.2. Currently @jmarrec is using GitHub actions to do this on his personal fork.
- [x] @wenyikuang Fix the CI for the develop branch. This will require updating to conan2 and and Ruby 3.2.2 (assuming that ends up being the correct target)
- [x] @jmarrec Consolidate notes on building with conan2. We have https://github.com/NREL/OpenStudio/blob/ruby/3.2.2/BUILDING.md#building-with-conan-v2 and also some (probably stale) notes in the Wiki https://github.com/NREL/OpenStudio/wiki#building-openstudio.
- [x] @kbenne and @jmarrec Remove stale conan related build code that is no longer used in conan2 world. Specifically https://github.com/NREL/OpenStudio/blob/ruby/3.2.2/ConanInstall.cmake, but there could be other stuff.
- [ ] @kbenne integrate the latest openstudio-standards release from @mdahlhausen, however we plan to generate our first RC with the current version of standards, while we wait for the final openstudio-standards release.
- [x] ~~@DavidGoldwasser Review and update Ruby version requirement in assorted gemspec files.~~ (This one is superceded by the more detailed checklist in the more [recent comment](https://github.com/NREL/OpenStudio/issues/5136#issuecomment-2061074061))
     * https://github.com/NREL/OpenStudio-measure-tester-gem/blob/develop/openstudio_measure_tester.gemspec#L30
     * https://github.com/NREL/openstudio-extension-gem/blob/v0.8.0-rc1/openstudio-extension.gemspec#L29
     * https://github.com/NREL/openstudio-standards/blob/master/openstudio-standards.gemspec#L15
     * https://github.com/NREL/OpenStudio-workflow-gem/blob/develop/openstudio-workflow.gemspec#L19

**Comment by joseph-robertson** [comment]
FYI I marked with the "OpenStudio DSK v3.8.0 " milestone the, AFAIK, pull requests that should go into develop before the release.

**Comment by kbenne** [comment]
> FYI I marked with the "OpenStudio DSK v3.8.0 " milestone the, AFAIK, pull requests that should go into develop before the release.

Perfect. I'm going to add the ones that I am aware of.

**Comment by DavidGoldwasser** [comment]
@kbenne SketchUp 2024 is out now using Ruby 3.2.2. Here is release notes https://help.sketchup.com/en/release-notes/sketchup-desktop-20240

Not sure if this note about OpenSSL is standard to Ruby 3.2.2 or something they changed? `The version of OpenSSL in Ruby was updated to OpenSSL 1.1.1w`

**Comment by jmarrec** [comment]
Hum, so Ruby 3.2.2 supports OpenSSL >= 1.1.1 but also > 3.x, and the standard installers are 3.x. I'm kinda annoyed they picked 1.1.1w and not 3.x (Qt 6 for eg uses 3.x.), which is what I went with for now since it followed the ruby installers... 
https://github.com/NREL/OpenStudio/blob/2ff1c1b878739515c9b57a6511b3ef9af7a523b2/conanfile.py#L40

As can be seen, Ruby 3.2.2 was using OpenSSL 3.1.0:
https://github.com/ruby/ruby/blob/e51014f9c05aa65cbf203442d37fef7c12390015/ext/openssl/openssl.gemspec#L3

**Comment by kbenne** [comment]
> Hum, so Ruby 3.2.2 supports OpenSSL >= 1.1.1 but also > 3.x, and the standard installers are 3.x. I'm kinda annoyed they picked 1.1.1w and not 3.x (Qt 6 for eg uses 3.x.), which is what I went with for now since it followed the ruby installers...
> 
> https://github.com/NREL/OpenStudio/blob/2ff1c1b878739515c9b57a6511b3ef9af7a523b2/conanfile.py#L40
> 
> As can be seen, Ruby 3.2.2 was using OpenSSL 3.1.0: https://github.com/ruby/ruby/blob/e51014f9c05aa65cbf203442d37fef7c12390015/ext/openssl/openssl.gemspec#L3
> 
> I'd very much prefer to keep OpenSSL 3.x.
> 
> (I'm also hoping that the openstudio-sketchup-plugin will not have binary incompatibilities due to it)

Ok well I guess this is something to confirm during testing of the RC.

**Comment by jmarrec** [comment]
* https://github.com/NREL/OpenStudio-measure-tester-gem/pull/79
* extension:
       * https://github.com/NREL/openstudio-extension-gem/pull/186
       * https://github.com/NREL/openstudio-extension-gem/pull/185
* https://github.com/NREL/bcl-gem/pull/29
