### ISSUE TITLE
Update or delete CHANGELOG.md

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#5138]
Issue overview
--------------
[CHANGELOG.md](https://github.com/NREL/OpenStudio/blob/develop/CHANGELOG.md) has not been updated since v3.5. Either it should be updated or deleted.

**Comment by kbenne** [comment]
@DavidGoldwasser this should be addressed before our RC. My vote is that we remove it.

**Comment by DavidGoldwasser** [comment]
@kbenne I'm fine deleting this. I think we cover it pretty well in GitHub links for new features and minor changes in the release notes. 
https://github.com/NREL/OpenStudio/blob/develop/developer/doc/ReleaseNotes/OpenStudio_Release_Notes_3_7_0_20231117.md#new-features-major-fixes-and-api-breaking-changes
