### ISSUE TITLE
Off by one error in measure step_values when _SKIP_ is true

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#5140]
Issue overview
--------------
When adding measures to a workflow, there is a special _SKIP_ argument that can be used to skip running a measure.  Setting _SKIP_ to true results in step_values being added to the wrong measure in the out.osw file for subsequent measures in the workflow.

## Current Behavior
step_values are associated with the wrong measure in out.osw when a measure is skipped

## Expected Behavior
step_values should be associated with the correct measure in out.osw when a measure is skipped

## Steps to Reproduce
1. Unzip [MixedUpStepsSkip.zip](https://github.com/NREL/OpenStudio/files/14924550/MixedUpStepsSkip.zip)
2. openstudio.exe run -w workflow.osw
3. The step_results should be associated with the correct measure indexes but they are off by one when a measure is skipped
4. Additionally, `[openstudio.measure.OSRunner] <Error> Not prepared for step` is shown when measure is skipped

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 11
 - Version of OpenStudio (if using an intermediate build, include SHA): 3.7.0

### Context
Parsing of results in out.osw file broken for test suite

**Comment by macumber** [comment]
This does not affect the `classic` CLI.

**Comment by jmarrec** [comment]
Aren't TODOs a great way to remind you to finish something and never actually do it? https://github.com/NREL/OpenStudio/blob/b8093180dc61a47935c2fcf067e4cd8bb0fd8a28/src/workflow/ApplyMeasure.cpp#L42

**Comment by jmarrec** [comment]
Ok yeah, I need to prepareForMeasureRun before I can set the step Result and increment the step

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio/commit/c6ff09ce86a4b1d618737ce3ca21cef8c5ccc746 fixes it. I tested locally.

![Uploading image.png…]()

**Comment by macumber** [comment]
Thanks @jmarrec !
