### ISSUE TITLE
Zone group feature

### ISSUE THREAD

**Issue by archeering** [NREL/OpenStudio#5141]
Enhancement Request
--------------
 

For the building which has a long list of thermal zones, drag & drop each zone into HVAC system is a boring job, so pls add zone group feature into Openstudio for faster HVAC system setup.

## Detailed Description

Zone group is well know features in other building simulation tool, it could facilite the management of too many thermal zones in Openstudio's list. Therefore, in the HVAC systems tab, there will be one more object: Thermal zone group. Thermal zones can be mutiple selected, then copy-paste or drag-drop into thermal zone group. User can only drag-drop thermal zone group into HVAC system instead of just one thermal zone then repeat and repeat for other zones - it makes tired with a building having more than 50 thermal zones, and system HVAC network appeared too big with super small text name.

**Comment by jmarrec** [comment]
Wrong repository. You're apparnetly talking about https://github.com/openstudiocoalition/OpenStudioApplication/issues
