### ISSUE TITLE
Confirm that Classic works in 3.8.0 without updates to workflow gem for Ruby 3.2.2.

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#5144]
workflow gem hasn't been update. See if that is needed. Should we add something to CI for this if it isn't there?

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio/blob/276859dd1e3afc34f3c29ec70cc9699dc626606b/src/cli/CMakeLists.txt#L105-L109
