### ISSUE TITLE
`runner.getArgumentValues` does not honor argument data type

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#5196]
Issue overview
--------------
Very simple OSW to demonstrate the issue:
[test.zip](https://github.com/NREL/OpenStudio/files/15313179/test.zip)

Run it w/ OpenStudio 3.8 as follows:
`openstudio run -m -w test.osw`

![image](https://github.com/NREL/OpenStudio/assets/5861765/77e3389f-8a9e-47ea-bd55-78fa664ad3d3)

It will print out `{:double_value=>40}` instead of `{:double_value=>40.0}`. This caused a bug in our software because we ended up doing integer division instead of float division. Since the argument is of type Double, `runner.getArgumentValues` should be able to return the value as a double, right?

(Also, I'm seeing that `val=1` is being output when I use the `run -m` flag. Maybe some debug code in OS that wasn't removed?)

@joseph-robertson @jmarrec

**Comment by DavidGoldwasser** [comment]
I may be seeing that in one of the measures in https://github.com/NREL/openstudio-calibration-gem/pull/66

So I guess a question is putting in 3.8.0. Is this low risk and easy enough to fix today to put in release package tomorrow, or if there is a work around to bypass the issue, do we wait.

**Comment by jmarrec** [comment]
MCVE

```ruby
arg = OpenStudio::Measure::OSArgument::makeDoubleArgument("double", true)
arg.setValue(10.0)

arg.valueAsJSON
=> 10
arg.valueAsJSON.class
=> Integer
```
