### ISSUE TITLE
OpenStudio: Input File Errors And Warnings

### ISSUE THREAD

**Issue by FHLY12** [NREL/OpenStudio#5201]
OpenStudio could not import all EnergyPlus Idf objects into your model, 90 objects could not be translated

To export these objects please use 
'Plugins->OpenStudio->Export->Export Untranslated EnergyPlus Idf'
Why does this problem arise

**Comment by jmarrec** [comment]
Support for ReverseTranslation (IDF to OSM) is limited to geometry and loads and schedules and does not support HVAC objects.
