### ISSUE TITLE
OS 3.8 broke json-schema validation

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#5208]
Issue overview
--------------
OpenStudio 3.7 works (validation error returned):

```ruby
openstudio -e 'require "json-schema"; require "stringio"; schema = { "type" => "object", "required" => ["a"], "properties" => { "a" => {"type" => "integer"} } }; begin; JSON::Validator.validate!(schema, { "a" => "taco" }); rescue JSON::Schema::ValidationError => e; puts e.message; end'
The property '#/a' of type String did not match the following type: integer
```

OpenStudio 3.8 fails (ruby exception):

```ruby
openstudio -e 'require "json-schema"; require "stringio"; schema = { "type" => "object", "required" => ["a"], "properties" => { "a" => {"type" => "integer"} } }; begin; JSON::Validator.validate!(schema, { "a" => "taco" }); rescue JSON::Schema::ValidationError => e; puts e.message; end'
terminate called after throwing an instance of 'RubyException'
  what():  NameError: uninitialized constant IO::StringIO
Aborted (core dumped)
```

**Comment by shorowit** [comment]
Maybe it's as simple as updating the gem? The OS CLI has json-schema 2.7.0 which was released in 2016 (!!). The latest version is 4.3.0. I see that 2.7.0 doesn't support ruby 3.

**Comment by wenyikuang** [comment]
```
(os 3.8.0) :004 > Gem.loaded_specs['json-schema'].version
 => Gem::Version.new("2.7.0")
```


Take a really quick deep dive, this old-dated package comes from:


```
    tbd (3.4.1)
      json-schema (~> 2.7.0)
      osut (~> 0)
      topolys (~> 0)
```



https://github.com/rd2/tbd/blob/develop/tbd.gemspec#L33

Here we are

**Comment by shorowit** [comment]
`<rant>`I still don't understand why gems like these are packaged into the OS CLI. There are lots of other OS gems/measures that are generally useful, but they aren't packaged into the CLI. If someone wants to use the tbd gem, they can add it for their workflow.`</rant>`

**Comment by jmarrec** [comment]
@shorowit Tell that to openstudio-standards.
https://github.com/NREL/openstudio-standards/blob/c29f1e599799112295d3b1ef0b116a7c6632d6ba/openstudio-standards.gemspec#L52

**Comment by jmarrec** [comment]
Also, this works fine if you read the error message and just reorder the imports

```diff
-openstudio -e 'require "json-schema"; require "stringio"; ...
+openstudio -e 'require "stringio"; .require "json-schema"; ...
```

I'm not saying the StringIO thing isn't an issue. It's one I had already encountered outside of this gem I think.

**Comment by jmarrec** [comment]
The easiest might just be to do the same as here: https://github.com/NREL/OpenStudio/blob/cdee54c5fbbd53f2bbaca7bb2828cfa08fc89b4f/ruby/engine/openstudio_cli.rb#L45

eg put it here: https://github.com/NREL/OpenStudio/blob/cdee54c5fbbd53f2bbaca7bb2828cfa08fc89b4f/ruby/bindings/InitRubyBindings.cpp#L474
