### ISSUE TITLE
Measure instance data still in edit pane after instance has been deleted

### ISSUE THREAD

**Issue by elainethale** [NREL/OpenStudio#521]
1. Create a PAT project
2. Add a fixed measure
3. Click on it to look at its arguments in the edit pane
4. Delete the fixed measure

Your focus will still be on the edit pane and it will still show data from the now-deleted measure.

**Comment by macumber** [comment]
Elevating to blocked because this is likely to result in a crash

**Comment by macumber** [comment]
Cannot reproduce any more
