### ISSUE TITLE
can not install previous versions with pip install openstudio==3.7.0

### ISSUE THREAD

**Issue by AltamarMx** [NREL/OpenStudio#5219]
Issue overview

pip install openstudio==3.7.0 
fails

**Comment by wenyikuang** [comment]
```
pip install openstudio==3.7.0
Collecting openstudio==3.7.0
  Downloading openstudio-3.7.0-py3-none-manylinux1_x86_64.whl (72.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.9/72.9 MB 1.3 MB/s eta 0:00:00
Installing collected packages: openstudio
Successfully installed openstudio-3.7.0
```

Looks good from my side, do you face some network issue?

**Comment by jmarrec** [comment]
Works as expected. 3.8.0 is the first release to support python 3.12 on windows.

Please refer to https://github.com/NREL/OpenStudio/wiki/OpenStudio-SDK-Python-Binding-Version-Compatibility-Matrix
