### ISSUE TITLE
Declutter Construction Library list

### ISSUE THREAD

**Issue by nixub-a** [NREL/OpenStudio#5231]
Enhancement Request
--------------
My issue comes from Contructions>>Constructions>>Library>>Constructions. There should be subfolders for each type of construction variant. It'll reduce the scrolling.  

![Screenshot 2024-07-22 221840](https://github.com/user-attachments/assets/fab482e8-78eb-44dd-8ee0-f1762cf021e1)

**Comment by DavidGoldwasser** [comment]
This should be filed in OpenStudio Application repo. https://github.com/openstudiocoalition/OpenStudioApplication/issues

The example above seems to have duplicate similar possibly duplicate constructions. I know some NREL measures are guilty of resulting in duplicate resource objects, but that would help this be cleaner as well.

As far as subfolders for each type of construction variant. Are you just referring to opaque vs. transparent, or specific or if you mean want to look at intended surface type and categorize based on that. If you file this in other repo may want to expand on proposed behavior a little more.

**Comment by macumber** [comment]
There was a recent PR https://github.com/openstudiocoalition/OpenStudioApplication/pull/713 that added categories to the library that might be sort of in line with the feature request, the issue solved was https://github.com/openstudiocoalition/OpenStudioApplication/issues/123.  However, it would not group a bunch of duplicate objects, those should just be prevented from occurring as @DavidGoldwasser said
