### ISSUE TITLE
OpenStudio Conan site certificate expired

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#5232]
Issue overview
--------------
The OpenStudio Conan site certificate expired, builds which rely on this to provide dependencies will now fail.

## Current Behavior
The certificate is expired
![image](https://github.com/user-attachments/assets/dcb389d7-d83d-4fe4-95ea-1cc2fe265a54)

## Expected Behavior
The certificate should be renewed

## Steps to Reproduce
1. Try to perform a build which fetches conan dependencies from conan.openstudio.net

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

**Comment by macumber** [comment]
Thanks @DavidGoldwasser it all seems good now!

**Comment by wenyikuang** [comment]
Great, close.

**Comment by eringold** [comment]
@DavidGoldwasser @wenyikuang this happened again: 

![Image](https://github.com/user-attachments/assets/35a65e18-aa19-49ab-9d55-a88a4fbe5530)

**Comment by wenyikuang** [comment]
Updated the SSL cert.
