### ISSUE TITLE
Allow `.sch` extensions for schematron documents

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#5248]
Enhancement Request
--------------
Apparently schematron documents are supposed to have a `.sch` file extension. And that's what e.g. [BuildingSync uses](https://github.com/BuildingSync/use-cases/tree/main/BETTER/schematron). However, OpenStudio throws an error when validating that only `.xml` is allowed.

```
RuntimeError: /srv/jenkins/openstudio/docker-volumes/ubuntu-2204-nightly/Openstudio/src/utilities/xml/XMLValidator.cpp@188 : Schema path extension '.sch' not supported.
```

If it's a pain to support both, I don't have a problem renaming our Schematron docs to `.sch`.

**Comment by jmarrec** [comment]
For `<insert reason>`, it's checking if it's .xml or .sct, not .sch.

I'm not sure what I got that .sct from?

Should I replace .sct with .sch? I don't think .sct is a think
