### ISSUE TITLE
E+ 24.2.1: Wrap PythonPlugin:SearchPaths

### ISSUE THREAD

**Issue by bonnema** [NREL/OpenStudio#5269]
Enhancement Request
--------------

**Comment by bonnema** [comment]
Thanks @joseph-robertson. I saw that, but was wanting to add additional paths (to the system Python's site-packages directory) to use 3rd party libraries.

**Comment by jmarrec** [comment]
stating the obvious, but an E+ measure would work to add it. Either a specific one, or just the "inject idf objects"
