### ISSUE TITLE
Parse Ground Temperatures in EpwFile

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#5272]
Enhancement Request
--------------

It'd be usefult o parse the GROUND TEMPERATURES from the EpwFile, so you could use them to fill out the SiteGroundTemperature BuildingSurface/Shallow/Deep objects.

## Possible Implementation

Same-ish as E+: https://github.com/NREL/EnergyPlus/blob/94a887817b9a5fdfef43c56ab69d1c6fac37d048/src/EnergyPlus/WeatherManager.cc#L7579-L7617

**Comment by DavidGoldwasser** [comment]
If this is just added to API, but not automatically set when EPW brought in then we should at it to https://github.com/NREL/openstudio-common-measures-gem/blob/develop/lib/measures/ChangeBuildingLocation/measure.rb

Note, that measure also sets water main temperatures, but it gets that from STAT file.

**Comment by joseph-robertson** [comment]
Implementation perhaps similar to https://github.com/NREL/OpenStudio/pull/3086?
