### ISSUE TITLE
Critical issue with Bindings in 3.9.0 RC releases

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#5292]
Seems to at least impact Python, C#, and Ruby

`Kuang, Wenyi I was trying to use osw2osa repo which is similar setup to UrbanOpt, and found Ruby can'd require OpenStudio with rc1 or rc2. I think Julien found something like this with other bindings. I see this in both r1 and rc2
 
`(base) dgoldwas:0:~$ irb
irb(main):001:0> require 'openstudio'
<internal:/Users/dgoldwas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- openstudioutilitiescore (LoadError)
  from <internal:/Users/dgoldwas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
  from /Users/dgoldwas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/openstudio-0.7.6/lib/openstudio.rb:46:in `<top (required)>'
  from <internal:/Users/dgoldwas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:159:in `require'
  from <internal:/Users/dgoldwas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:159:in `rescue in require'
  from <internal:/Users/dgoldwas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:39:in `require'
  from (irb):1:in `<main>'
  from /Users/dgoldwas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
  from /Users/dgoldwas/.rbenv/versions/3.2.2/bin/irb:25:in `load'
  from /Users/dgoldwas/.rbenv/versions/3.2.2/bin/irb:25:in `<main>'
<internal:/Users/dgoldwas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- openstudio (LoadError)
Did you mean?  open-uri
  from <internal:/Users/dgoldwas/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
  from (irb):1:in `<main>'
  from /Users/dgoldwas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
  from /Users/dgoldwas/.rbenv/versions/3.2.2/bin/irb:25:in `load'
  from /Users/dgoldwas/.rbenv/versions/3.2.2/bin/irb:25:in `<main>'
irb(main):002:0>`

**Comment by wenyikuang** [comment]
Tested on `NREL/Openstudio:develop` and it works fine...

Doubt it's something os-specific;
Let me try..

**Comment by DavidGoldwasser** [comment]
Sorry user error. I'll close this, @jmarrec  if you have issue in Python or C# still can have separate issue
