### ISSUE TITLE
HVAC Schedule Flaw

### ISSUE THREAD

**Issue by nixub-a** [NREL/OpenStudio#5300]
Enhancement Request
--------------
The _Always On Schedule_ for the HVAC System needs to become more fail-safe.  

## Detailed Description
I wanted to declutter my list of schedules. After deleting all of them, the simulation could not run. The following is the error message I received: 

[openstudio.model.ControllerMechanicalVentilation] Object of type '**OS:Controller:MechanicalVentilation**' and named '**Controller Mechanical Ventilation 1**' does not have an **Availability Schedule** attached.

I could not find a solution online. I had to compare my old and new models' lines of code to notice the missing element. Long story short, one of the _Always On Schedule_ that I deleted was critical for my HVAC system to work. 

## Possible Implementation
Someone might find themselves in the same position as me. I have a couple of potential fail-safe features. 

One option is to add a new _Always On Schedule_ input box in OS:AirLoopHVAC. That way, the user can insert a new schedule in case one was deleted. 

![OS:AirLoopHVAC](https://github.com/user-attachments/assets/1019d352-cb88-4010-9310-bb31960f5bd7)

The other option is to hide the _Always On Schedule_ from the Schedule>>Other Schedule list to prevent someone from deleting it. It can only be deleted with the HVAC System.

**Comment by jmarrec** [comment]
If you delete all of your schedules, you're just shooting yourself in the foot, and there's not much we can do.

Also, this repo has nothing to do with the OSApp.

I suggest your look at the BCL measure "Remove Orphan Objects and Unused Resources", the source is at https://github.com/NREL/openstudio-common-measures-gem/tree/develop/lib/measures/remove_orphan_objects_and_unused_resources
