### ISSUE TITLE
OS App Schedule Editor lets me enter values outside of type limits

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#531]
User sent in model with On/off schedule with values not between 0 and 1. I was able to duplicate this with a fractional schedule (I used Hot Water Equipment). There was a time that this was enforced, but it doesn't seem to be now. This schedule will produce a fatal error in EnergyPlus even if it isn't used.

IDF objects below were used in schedule intended for water use equipment temperature. 

cc: @kbenne 

----
Schedule:Day:Interval,
  Schedule Day 1,                         !- Name
  OnOff,                                  !- Schedule Type Limits Name
  No,                                     !- Interpolate to Timestep
  05:00,                                  !- Time 1 {hh:mm}
  29.6876220703125,                       !- Value Until Time 1
  10:00,                                  !- Time 2 {hh:mm}
  35,                                     !- Value Until Time 2
  17:00,                                  !- Time 3 {hh:mm}
  29.6876220703125,                       !- Value Until Time 3
  21:00,                                  !- Time 4 {hh:mm}
  35,                                     !- Value Until Time 4
  24:00,                                  !- Time 5 {hh:mm}
  29.6876220703125;                       !- Value Until Time 5
  
  Schedule:Week:Daily,
  Schedule:Week:Daily {60b2f5ce-766f-43ba-8644-e23cad582e61}, !- Name
  Schedule Day 1,                         !- Sunday Schedule:Day Name
  Schedule Day 1,                         !- Monday Schedule:Day Name
  Schedule Day 1,                         !- Tuesday Schedule:Day Name
  Schedule Day 1,                         !- Wednesday Schedule:Day Name
  Schedule Day 1,                         !- Thursday Schedule:Day Name
  Schedule Day 1,                         !- Friday Schedule:Day Name
  Schedule Day 1,                         !- Saturday Schedule:Day Name
  Schedule Day 1,                         !- Holiday Schedule:Day Name
  Schedule Day 1,                         !- SummerDesignDay Schedule:Day Name
  Schedule Day 1,                         !- WinterDesignDay Schedule:Day Name
  Schedule Day 1,                         !- CustomDay1 Schedule:Day Name
  Schedule Day 1;                         !- CustomDay2 Schedule:Day Name

Schedule:Year,
  Shower,                                 !- Name
  OnOff,                                  !- Schedule Type Limits Name
  Schedule:Week:Daily {60b2f5ce-766f-43ba-8644-e23cad582e61}, !- Schedule:Week Name 1
  1,                                      !- Start Month 1
  1,                                      !- Start Day 1
  12,                                     !- End Month 1
  31;                                     !- End Day 1

---
Here is the E+ error
   ** Severe  ** ProcessScheduleInput: Schedule="SHOWER" has values outside its Schedule Type (ONOFF) range
   **   ~~~   **   Minimum should be >=0.000 and Maximum should be <=1.000

**Comment by macumber** [comment]
@DavidGoldwasser @kbenne @asparke2 @evanweaver I just confirmed this but I'm not sure what the right solution is.  The upper and lower limits in a schedule rule seem to be set as the union of the typelimits and the values in the schedule.  Why do we allow users to do this?  It seems like this was probably a fix to some earlier issue.

**Comment by macumber** [comment]
Addressed by GUI refactor
