### ISSUE TITLE
 I tried to merge  two models in open studio ,when i import the second model the first is deleted , what is the problem?

### ISSUE THREAD

**Issue by ZiadM3** [NREL/OpenStudio#5310]
I tried to merge  two models in open studio ,when i import the second model the first is deleted , what is the problem?

**Comment by macumber** [comment]
Is there significant overlap between the two models?  How did you make the two models?  If the spaces and zones are the same in between each model then the spaces/zones in the first model will be updated/replaced by the spaces/zones in the second.
