### ISSUE TITLE
OpenStudio CLI unable to `require uuid` in OpenStudio 3.9 (thereby breaking dependencies like openstudio-extension)

### ISSUE THREAD

**Issue by chriswmackey** [NREL/OpenStudio#5315]
Issue overview
--------------
I am unable to get Ladybug Tools' [`honeybee-openstudio gem`](https://github.com/ladybug-tools/honeybee-openstudio-gem) to work in OpenStudio 3.9 CLI because it requires `openstudio-extension` on [this line of code](https://github.com/ladybug-tools/honeybee-openstudio-gem/blob/master/lib/honeybee/extension.rb#L32). This results in the eventual importing of the `uuid` module, which causes OpenStudio 3.9 CLI to fail. All of this is preventing us from updating the version of OpenStudio used by the Ladybug Tools community (we are currently stuck on OpenStudio 3.7).

## Current Behavior

It seems that the openstudio-extension gem is no longer import-able in OpenStudio 3.9 CLI since I get the following traceback when I use `require 'openstudio/extension'`:

```
Traceback:
:/ruby/3.2.0/rubygems.rb:788:in `block in open_file'
eval:464:in `open'
:/ruby/3.2.0/rubygems.rb:785:in `open_file'
:/ruby/3.2.0/rubygems/specification.rb:1158:in `load'
:/ruby/3.2.0/gems/uuid-2.3.9/lib/uuid.rb:66:in `<module:Version>'
:/ruby/3.2.0/gems/uuid-2.3.9/lib/uuid.rb:65:in `<class:UUID>'
:/ruby/3.2.0/gems/uuid-2.3.9/lib/uuid.rb:62:in `<main>'
eval:236:in `eval'
eval:236:in `require_embedded_absolute'
eval:221:in `block in require_embedded'
eval:215:in `each'
eval:215:in `require_embedded'
eval:190:in `rescue in require'
eval:184:in `require'
<internal::/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
:/ruby/3.2.0/gems/bcl-0.8.0/lib/bcl.rb:21:in `<main>'
eval:236:in `eval'
eval:236:in `require_embedded_absolute'
eval:221:in `block in require_embedded'
eval:215:in `each'
eval:215:in `require_embedded'
eval:190:in `rescue in require'
eval:184:in `require'
<internal::/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
:/ruby/3.2.0/gems/openstudio-extension-0.8.2/lib/openstudio/extension/runner.rb:14:in `<main>'
eval:236:in `eval'
eval:236:in `require_embedded_absolute'
eval:221:in `block in require_embedded'
eval:215:in `each'
eval:215:in `require_embedded'
eval:190:in `rescue in require'
eval:184:in `require'
<internal::/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
:/ruby/3.2.0/gems/openstudio-extension-0.8.2/lib/openstudio/extension.rb:7:in `<main>'
eval:236:in `eval'
eval:236:in `require_embedded_absolute'
eval:221:in `block in require_embedded'
eval:215:in `each'
eval:215:in `require_embedded'
eval:190:in `rescue in require'
eval:184:in `require'
<internal::/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
C:/Program Files/ladybug_tools/resources/measures/honeybee_openstudio_gem/lib/honeybee/extension.rb:32:in `<top (required)>'
```

The issue clearly seems to originate from importing the Ruby `uuid` module. I can trace the failure [here in this module of bcl](https://github.com/NREL/bcl-gem/blob/develop/lib/bcl.rb#L21), which gets called from [here in thig module of openstudio-extension](https://github.com/NREL/openstudio-extension-gem/blob/develop/lib/openstudio/extension/runner.rb#L14)

## Steps to Reproduce
I feel like this error should be reproducible by just trying to `require 'uuid`' in any measure that is being run with OpenStudio 3.9 CLI. Simply sticking `require 'uuid`' in other parts of my measure that I'm calling with OpenStudio CLI gets the failure to happen there rather than all of the way down in the BCL dependency.

If it is not easily reproducible for whatever reason, I'm providing many details about my environment below.

## Possible Solution
I suspect that this is tied to the change of Ruby versions that happened in the last two releases of OpenStudio. Maybe OpenStudio 3.9 CLI was packaged with a version of uuid that is incompatible with Ruby 3.2?

### Environment

 - Windows 11
 - OpenStudio 3.9
 - Full System Summary:
![image](https://github.com/user-attachments/assets/4c977194-7408-4938-89d5-5d21d61f3874)

I have full admin privileges on this machine (it is my personal computer) but I still hit the same error even when running OpenStudio CLI with Admin privileges. I have no other antivirus software installed (other than Windows Defender) so I don't think that's blocking uuid from running.

### Context
I would particularly appreciate any insight that @tijcolem or @jmarrec might have as I know that they have a hand in how parts of OpenStudio are packaged. But really any thoughts about what is going on here would be immensely appreciated.

**Comment by jmarrec** [comment]
It's possible this is happening because of that annoying `File.expand_path`. Here is uuid.rb, line 62 to 73:

```
class UUID

  # Version number.
  module Version
    version = Gem::Specification.load(File.expand_path("../uuid.gemspec", File.dirname(__FILE__))).version.to_s.split(".").map { |i| i.to_i }
    MAJOR = version[0]
    MINOR = version[1]
    PATCH = version[2]
    STRING = "#{MAJOR}.#{MINOR}.#{PATCH}"
  end

  VERSION = Version::STRING
```

**Comment by jmarrec** [comment]
@chriswmackey please try this:


```
$ openstudio -e "require 'uuid'; puts UUID.new"
#<UUID:0x00007aa0e5139b00>
```

(Works on Ubuntu)

**Comment by jmarrec** [comment]
Ok, testing on windows 10 now.

**test.rb**

```ruby
require 'uuid'

puts UUID.new

puts "OK"
```


```
$ openstudio .\test.rb 

NoMethodError: undefined method `flock' for #<StringIO:0x000002862b49a198>
Backtrace:                                                                                                                      :/ruby/3.2.0/rubygems.rb:788:in `block in open_file'
        eval:464:in `open'
        :/ruby/3.2.0/rubygems.rb:785:in `open_file'
        :/ruby/3.2.0/rubygems/specification.rb:1158:in `load'
        :/ruby/3.2.0/gems/uuid-2.3.9/lib/uuid.rb:66:in `<module:Version>'
        :/ruby/3.2.0/gems/uuid-2.3.9/lib/uuid.rb:65:in `<class:UUID>'
        :/ruby/3.2.0/gems/uuid-2.3.9/lib/uuid.rb:62:in `<main>'
        eval:236:in `eval'
        eval:236:in `require_embedded_absolute'
        eval:221:in `block in require_embedded'
        eval:215:in `each'
        eval:215:in `require_embedded'
        eval:190:in `rescue in require'
        eval:184:in `require'
        <internal::/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        C:/Users/julien/test.rb:1:in `<top (required)>'
        eval:182:in `require'
        eval:182:in `require'
        <internal::/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        eval:4:in `<main>'
Failed to execute 'C:/Users/julien/test.rb'
```

**Comment by jmarrec** [comment]
I don't want to get into too much details with the shenanigans we have to do to make the embedded file system work, but I'm going to, not for you Chris, but for @kbenne and @DavidGoldwasser.

We patch Kernel.open, so that if it's an embedded file, we return a StringIO. When really it'd be a File in the regular case. Both are children of class IO

https://github.com/NREL/OpenStudio/blob/c77fbb9569be852f194eddf3425a7d699ff91513/ruby/engine/embedded_help.rb#L451-L471

OBVIOUSLY, only File has a `flock`method, as in **File lock**.

Gem::Specification::load calls Gem.open_file.

https://github.com/ruby/ruby/blob/1ae2b16d0014018c99a37e3e18531cdfa5f27f06/lib/rubygems/specification.rb#L1150-L1159

Gem.open_file (used to be called Gem.open_file_with_flock) will **ONLY ON WINDOWS** protect with flock:

https://github.com/ruby/ruby/blob/1ae2b16d0014018c99a37e3e18531cdfa5f27f06/lib/rubygems.rb#L782-L794

Let me walk through that method:

```diff
  ##
  # Open a file with given flags, and on Windows protect access with flock


  def self.open_file(path, flags, &block)
+ Note: in the regular case, this is a `File`! But we return a `StringIO` because it's an embedded file at `:/ruby/3.2.0/gems/uuid-2.3.9/uuid.gemspec`
    File.open(path, flags) do |io|
      if !java_platform? && win_platform?
        begin
+          # And here is goes KABOOM because StringIO does NOT have a `flock` method
          io.flock(File::LOCK_EX)
+.      # And NoMethodError is not in the list of exceptions caught
        rescue Errno::ENOSYS, Errno::ENOTSUP 
        end
      end
      yield io
    end
  rescue Errno::ENOLCK # NFS
    if Thread.main != Thread.current
      raise
    else
      File.open(path, flags) do |io|
        yield io
      end
    end
  end
```


Possible fixes:

* Add a general StringIO.flock (no op) in the Embedded help
* Dynamically append a flock method in the Kernel.open patch in Embedded help
* Patchup openstudio-gems so that uuid gem just harcodes its value
* (stop doing embedded)

**Comment by chriswmackey** [comment]
Thank you so much for the quick response and fix, @jmarrec . We all really appreciate it.

That's good to know that this issue seems to be Windows-specific and that you can get it to work on Ubuntu. And I can confirm that your Windows 10 test produces the same result on my machine:
![image](https://github.com/user-attachments/assets/f12bfb17-c571-4856-a439-d6fe0d8d1c8d)

I know that there's probably an internal process for deciding when there are patch releases of OpenStudio but, given that this is a blocker for a lot of Windows users, do you think the fix that you pushed could merit a patch release? Sorry that I should have tested this closer to when you released OpenStudio 3.9 last month so that I could have gotten you the bug report before you all started to get deeper into OpsnTduioo 3.10 development. I'll try to be more on top of this next time.

**Comment by kbenne** [comment]
I vote for option 1 or 2 of @jmarrec's list in the near term. I think either of those can be done quickly.

Looking at the next major releas I think option 4, abandon the embedded file system is what we need to do. The time has come. I riase the white flag. 

![9263c1cc-11df-430f-985c-0ca6823ecb38 copy](https://github.com/user-attachments/assets/6d233285-6e6e-4ffe-b8b3-40cca825ded8)

**Comment by jmarrec** [comment]
The fix is at https://github.com/NREL/OpenStudio/pull/5316, i choose not to tweak StringIO but to mimic flock only for our patches of io/kernel.open . Less chance of breaking something else.

**Comment by chriswmackey** [comment]
I just wanted to say thanks for addressing this, @jmarrec .  If there's a chance that we might be able to get a patch release of OpenStudio (eg. 3.9.1), just let me know and I'll plan our LBT dev schedule accordingly. Otherwise, I'll plan to wait for the release of OpenStudio 3.10.

Have a happy new year!
