### ISSUE TITLE
All drop zone under Water Use Equipment Definitions doesn't enforce schedule types

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#532]
This came out of same model as issue #531.  In testing this I was surprised to see that I could drop any kind of schedule on the drop zone for "Target Temperature Schedule". This was also true for other other two drop zones for the water use equipment definition.

No other loads have drop zones so I can't test there, but zones for example do enforce schedule types in the thermostat schedule drop zones. I think this is the typical behavior. FYI - there is already an open bug for this same view in OpenStudio for the units of Peak Flow Rate (Issue #177 ).

cc: @elainethale

**Comment by jmarrec** [comment]
Addressed by GUI refactor
