### ISSUE TITLE
Water Use Equipment Drop zones don't let you overwrite schedules

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#533]
Closely related to Issue #532 The drop zone doesn't let you overwrite the schedule that is there. If you have a schedule on any of the dropzones and try to drag an alternate one there you get the circle/slash icon.

you have to first delete the schedule that is there and then drag a new one. This again seems to be unique to the water use equipment def object.

cc: @elainethale

**Comment by kbenne** [comment]
@DavidGoldwasser is this still a thing?

**Comment by DavidGoldwasser** [comment]
@kbenne both this and issue #532 are both still valid

**Comment by jmarrec** [comment]
Addressed by GUI refactor
