### ISSUE TITLE
Users may inadvertently add something to dropzone when they do not intend to.

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#534]
@kbenne I found one more behavior but it wasn't unique to the water use equipment object. This happens on any drop zones. This is minor, and can be addressed at a later date.

1. Go to a view that has dropzones. In my case I made a construction set in an empty model.
2. Grab a construction and hover over a drop zone but don't let go, move the mouse out of the drop zone but still over the main body of the application (vs. the left or right gutter).
3. When you let go of themouse the construction should disappear but instead it gets assigned to the drop zone.
4. If you repeat this on the same drop zone, again hovering over it and then letting go when you are not over it, it will replace the original construction.

If you go over many drop zone it will add to whichever one you crossed over last.

**Comment by macumber** [comment]
@DavidGoldwasser @evanweaver I don't see this in pivotal, is it something we need for 1.7.0?  If invalid let's close it.  If not needed in 1.7.0 let's remove the milestone.

**Comment by evanweaver** [comment]
@macumber @DavidGoldwasser Using the Construction Sets sub-tab, this appears to be invalid.  As you move off of the dropzone, the "+" turns to a "-"; at this point, the dropzone will not receive a drop signal, which is the expected behavior.
