### ISSUE TITLE
Renamed loop doesn't get updated in pull down until you switch to "control tab" or change loops

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#535]
I noticed that if I change a loop name that the pull down list doesn't immediately update. In fact even if I move away from the HVAC and come back it still doesn't update.

It will update if I change from the the "Layout" to "Controls" view and back, or if I change to another loop in the "Layout" view either from the pulldown menu or from a linked component.

**Comment by jmarrec** [comment]
Still true today OS 2.2.1

**Comment by jmarrec** [comment]
Fixed in #535, added a gif showing fix.
