### ISSUE TITLE
Setpoint Manager Warmest doesn't have an icon in the library

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#536]
It does however have an icon when pulled into the loop. Doing a quick pass through on develop I didn't see any other missing icons or ladybugs in the library.

There is a missing icon for water use equipment under the "Loads" tab when you add a new one, but I think that is documented elsewhere in an old bug. All other load defs have an icon.

**Comment by jmarrec** [comment]
All SPMs have an icon in OS 2.2.1

![screen shot 2017-09-29 at 1 56 58 pm](https://user-images.githubusercontent.com/5479063/31015005-18c44194-a51e-11e7-891c-426cee0abf02.png)
