### ISSUE TITLE
SketchUp's Undo doesn't cooperate with OpenStudio (Bugzilla #438)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#54]
On 2011-12-19 14:34:10, @axelstudios wrote:

> Using SketchUp's undo operation on OpenStudio model elements may produce unexpected results.

On 2012-01-16 13:49:17, @DavidGoldwasser wrote:

> While this is critical I don't know that we can tackle this until we have a debug build of SketchUp.
> 
> Other things that fit into this same category are other limitations of observers (e.g. multiple copy) backing out of group while things are still going on, seemingly random crashes while opening or working on a model.

On 2012-01-16 13:59:50, @DavidGoldwasser wrote:

> While this really isn't random (just unknown cause) I tagged it with Random Keyword.

Keywords: Random, ReleaseNotes

**Comment by DavidGoldwasser** [comment]
Observer issue.
