### ISSUE TITLE
Possible file size reductions in PAT

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#541]
@nllong I created issue #540 to address responsiveness of PAT tabs after a run. I wanted to make another one to look at file size.

Looking at my DEMO project (with all of the measures in but before I made design alternatives. it is 121mb uncompressed

1a. 56mb of that is in the "scripts" folder. That can be reduced to 2.5mb if tests are removed. I had thought this was a bigger issue because all design alternatives used to carry copies, but that doesn't happen anymore. data point folders are not even made now until the job starts, and even then they don't have measures anymore.

2a. Another easy one. When I bring in a seed model that has been run it comes with the results from my run in the OS app.  That could probably go done from 53mb to 3mb (bringing just the osm and weather file)

3a. There is an 8mb "run.db" and a 2mb "project.osp-journal". I have not run yet at this point, so not sure if these are needed or can be generated at run time after the upload?

The project.osp itself is just 3mb and there is a "project.log" that is just 21kb.

---

After a run my project is 40gb. I'm sure most of that is the results, but there may be many things we can remove. Below is a list of possible things to remove.

1b. Every workflow step has a resulting OSM model. Whilethis may be useful for diagnostic purposes maybe we don't need it. I'm wonder if this comes with the results if you request detailed results (if not then maybe we don't need to keep it. (the osm file is about 1.5mb)

2b. Here is low hanging fruit. Each workflow step in each datapoint (at least for model measures) carries a copy of the weather file. We probably have 1000-2000 copies of the weather file in the project at about 1.5mb each.

3b. We also have 1000-2000 stdout file. Sometimes this is very small. Other times it can be 3mb. 
(Looking at one of the large ones this message appears about 18,000 times. This may have been unique. I only see it in the first workflow step for dataoint 1. @macumber, any thoughts on what that is and why so many times. I don't have that many surfaces or constructions. It is a16 space model )
[openstudio.model.ConstructionBase] <1> Could not resolve matched surface construction conflicts between surfaces '1', and '1', area calculation may be incorrect

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
