### ISSUE TITLE
On large job you still see "0% Failed after a job fails in the workflow

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#542]
In my case I hvae just over 200 data points. With about 36 "finished" and 1 "Failed" my summary at the top next to the run bar shows "17% Complete" and "% Failed".

If I didn't scroll down in my list of design alternatives I wouldn't know that anything failed. I don't think we need to touch this for the release, but maybe in the future we can always round up on this, or maybe just give a number of jobs vs. a % complete. 

@asparke2 and @macumber what do you think a good solution is. I'd be ok with a hybrid with %complete and then number of Failed. I think the failed ones are also includedin the %complete.

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
