### ISSUE TITLE
Running "Update My Measures" adds unexpected text to xml "&#xd;"

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#544]
It seems this is added after any line break. If you run multiple types they you will have this text multiple times after each line break.
&#xd;

In at least the "Description" field this results in extra line breaks in PAT. For some reason  these don't affect the "Modeler Description" section. In that section you need to just have a line break vs "&#xd;". Not sure why the behavior isn't the same. There is another issues (issue #335 ) related to the "Description" field in PAT, maybe could be fixed at same time. This isn't critical for the release.

**Comment by macumber** [comment]
@DavidGoldwasser is this still valid?

**Comment by DavidGoldwasser** [comment]
Doesn't seem to be an issue anymore. Maybe because I'm not editing XML directly, but editing in measure.rb, with app editing XML behind the scenes. Either way it works :)
