### ISSUE TITLE
Issues in Onlnie BCL window when viewing sections with more than 10 measures

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#546]
If you have more than 10 measures in a category then you need to go to page to view the last ones. (envelope now has 14). This works fine, but then when you choose another category it shows a number at the top right but doesn't show the measures. My guess is that it is viewing page 2 of the category that has less than 10. I'm not sure if the BCL window in OS app for components has the same issues? Clicking a second time fixes it.

steps to reproduce
1. Launch Pat and click "Add Measures From Online BCL"
2. Click Enveope, and then go to page 2
3. Next click "Electric Lighting" Notice how it shows "8" for number of measures but you don't see the measures.
4. Click "Electric Lighting" again and you will see the measures.

@asparke2 do you this should go into this release?
@evanweaver do you think this is easy and low risk?

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
