### ISSUE TITLE
Branch objects are getting unexpected blank fields when I copy from a soruce IDF into workspace in an EnergyPlus measure

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#555]
I think the measure is fine now, I think this issue in C++. @macumber Maybe there is a work around I can use for this measure that would avoid the issue for now?

I have an IDF from residential that produces 54 sever E+ errors and then fatal error. Runs fine after I clean this up.

Branch objects that looked like this in the source IDF:

Branch,
  DHW Supply Outlet Branch,               !- Name
  autosize,                               !- Maximum Flow Rate {m3/s}
  ,                                       !- Pressure Drop Curve Name
  Pipe:Adiabatic,                         !- Component Object Type 1
  DHW Supply Outlet Pipe,                 !- Component Name 1
  DHW Supply Outlet Pipe Inlet Node,      !- Component Inlet Node Name 1
  DHW Supply Outlet Node;                 !- Component Outlet Node Name 1

Look like this in the final IDF:

Branch,
  DHW Supply Outlet Branch,               !- Name
  autosize,                               !- Maximum Flow Rate {m3/s}
  ,                                       !- Pressure Drop Curve Name
  Pipe:Adiabatic,                         !- Component Object Type 1
  DHW Supply Outlet Pipe,                 !- Component Name 1
  DHW Supply Outlet Pipe Inlet Node,      !- Component Inlet Node Name 1
  DHW Supply Outlet Node,                 !- Component Outlet Node Name 1
  ,                                       !- Component Branch Control Type 1
  ,                                       !- Component Object Type 2
  ,                                       !- Component Name 2
  ,                                       !- Component Inlet Node Name 2
  ,                                       !- Component Outlet Node Name 2
  ,                                       !- Component Branch Control Type 2
  ,                                       !- Component Object Type 3
  ;                                       !- Component Name 3

-----------
Here are the resulting errors. So far I have just seen this affect "Branch" objects

   ** Severe  ** During Branch Input, Invalid Component Type input=
   **   ~~~   ** Component name=
   **   ~~~   ** Occurs on Branch=DHW SUPPLY OUTLET BRANCH
   ** Severe  ** GetBranchInput: Branch="DHW SUPPLY OUTLET BRANCH", invalid data.
   **   ~~~   ** blank required field: Component 2 Inlet Node Name
   **   ~~~   ** Occurs on Component 2 Object Type="", Component 2 Name="".
   ** Severe  ** GetBranchInput: Branch="DHW SUPPLY OUTLET BRANCH", invalid data.
   **   ~~~   ** blank required field: Component 2 Outlet Node Name
   **   ~~~   ** Occurs on Component 2 Object Type="", Component 2 Name="".
   ** Severe  ** During Branch Input, Invalid Component Type input=
   **   ~~~   ** Component name=
   **   ~~~   ** Occurs on Branch=DHW SUPPLY OUTLET BRANCH
   ** Severe  ** GetBranchInput: Branch="DHW SUPPLY OUTLET BRANCH", invalid data.
   **   ~~~   ** blank required field: Component 3 Inlet Node Name
   **   ~~~   ** Occurs on Component 3 Object Type="", Component 3 Name="".
   ** Severe  ** GetBranchInput: Branch="DHW SUPPLY OUTLET BRANCH", invalid data.
   **   ~~~   ** blank required field: Component 3 Outlet Node Name
   **   ~~~   ** Occurs on Component 3 Object Type="", Component 3 Name="".
   ** Severe  ** During Branch Input, Invalid Component Type input=
   **   ~~~   ** Component name=

**Comment by macumber** [comment]
@DavidGoldwasser is this still valid?  If not, let's close it

**Comment by DavidGoldwasser** [comment]
Stale
