### ISSUE TITLE
Schedule errors reverse translating PNNL residential IDF models into OpenStudio

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#558]
The model uses Schedule:Year, Schedule:Week:Compact, and Schedule:Day:Hourly objects. The Schedule:Year and Schedule:Day:Hourly objects seem to come int fine, but the Schedule:Week:Compact objects are not translated. This breaks all of the schedules. I'll put sample IDF file named after this issue number on the network.
Y:\5500\5500 HPBldg\davidg

**Comment by macumber** [comment]
@asparke2 do we need to do this?

**Comment by asparke2** [comment]
@macumber Nope, closed.
