### ISSUE TITLE
Related to same files as 448, construction is removed but not added to Untranslated objects (Bugzilla #451)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#57]
On 2011-12-28 19:53:10, @DavidGoldwasser wrote:

> If you watch the video I'm making (will put on YouTube tonight, but not public yet) you can see that I had to manually add this back. I think there was an unsupported material in the construction "blind" which led to its removal.

On 2012-01-13 15:22:03, @DavidGoldwasser wrote:

> Updated out of date Milestone Targer

On 2012-01-19 10:52:48, @DavidGoldwasser wrote:

> Batch moving bugs from SketchUp to "Code" component

Keywords: ReverseTranslation

**Comment by DavidGoldwasser** [comment]
I'd like to leave this open. Sidecar approach will be important if trying to create Legacy workflow using OpenStudio.

**Comment by macumber** [comment]
@DavidGoldwasser agree that we should look into this.  Probably need feature request to move some of these import methods to the OpenStudio application

**Comment by jmarrec** [comment]
is there a way to reproduce this nowadays @DavidGoldwasser or should we close?
