### ISSUE TITLE
Another sidecar bug related to EMSWindowShadeControl.idf (duplicate thermostat setpoint objects for each zone) (Bugzilla #452)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#58]
On 2011-12-29 09:17:44, @DavidGoldwasser wrote:

> Created an attachment (id=99)
> screenshot of source and unsupported file in IDF editor
> 
> The source file (bottom of picture) had 3 thermostats and 1 each heating and cooling thermostat setpoint object. The unsupported file has no thermostats and 4 each heating and cooling setpoint objects.
> 
> There seem to be two issues here.
> 1. the thermostat setpoint objects seems to be duplicating multiple times (one more than the number of zones).
> 2. The thermostat object doesn't make it into the OSM file but also doesn't make it into the sidecar file.

On 2011-12-29 09:22:54, @DavidGoldwasser wrote:

> Even for people who are not using the sidecar file, I expect these extra objects are artificially inflating the number of unsupported objects that show up in the alert box when an IDF is imported.

On 2012-01-13 15:22:03, @DavidGoldwasser wrote:

> Updated out of date Milestone Targer

On 2012-01-19 10:52:48, @DavidGoldwasser wrote:

> Batch moving bugs from SketchUp to "Code" component

Original attachments:
- sidecar_thermostats_bug.png (ID 99)

Keywords: ReverseTranslation

**Comment by DavidGoldwasser** [comment]
I'd like to leave this open. Sidecar approach will be important if trying to create Legacy workflow using OpenStudio.

**Comment by DavidGoldwasser** [comment]
This isn't valid any more. This was for exporting to IDF file objects not reverse translated into OSM. Is currently only accessible in SketchUp plugin, and I have other approaches to merging OSM and IDF file now.
