### ISSUE TITLE
Installer does not install OpenStudio.idd (Bugzilla #459)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#59]
On 2012-01-05 12:14:57, @macumber wrote:

> Should also install ProposedEnergy+.idd

On 2012-01-13 15:22:03, @DavidGoldwasser wrote:

> Updated out of date Milestone Targer

**Comment by DavidGoldwasser** [comment]
Is this related to why users still get warning about IDD in standard out? I'll leave open as minor.
