### ISSUE TITLE
Node.addSetPointManager() does not accept all types of  Setpoint Managers

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#593]
Looks like this method was not updated when the SetpointManagerWarmest and SetpointManageOutdoorAirReset were added.  See ruby crash message below:

Wrong arguments for overloaded method 'Node.addSetpointManager'.
Possible C/C++ prototypes are:
    void Node.addSetpointManager(openstudio::model::SetpointManagerSingleZoneReheat setPointManager)
    void Node.addSetpointManager(openstudio::model::SetpointManagerMixedAir setPointManager)
    void Node.addSetpointManager(openstudio::model::SetpointManagerScheduled &setPointManager)
    void Node.addSetpointManager(openstudio::model::SetpointManagerFollowOutdoorAirTemperature &setPointManager)
    void Node

**Comment by kbenne** [comment]
Maybe we need to mark deprecated, but I am favoring SetpointManager::addToNode.

**Comment by asparke2** [comment]
@kbenne agree, mark deprecated.

**Comment by mbadams5** [comment]
Is it not already marked deprecated? I thought I did that when I made the base class. Maybe I missed this one.

**Comment by asparke2** [comment]
@mbadams5 You are right, it's already [deprecated](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/Node.hpp#L69).  Closing.
