### ISSUE TITLE
Plugin and diagnostic script not catch all degenerate surfaces

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#598]
@macumber I'll look into this, but just thought I'd cc you. I'll run the "DisplayExtraWarnings" to find out more. I hit this on the calibration model I built from Scratch. There are no warnings when I open the model in the plugin, and when I run the new diagnostic script that specially looks for surfaces with less than 3 vertices it doesn't find any problems.

   *\* Severe  *\* GetSurfaceData: There are 5 degenerate surfaces; Degenerate surfaces are those with number of sides < 3.
   *\*   ~~~   *\* These surfaces should be deleted.
   *\*   ~~~   *\* For explicit details on each problem surface, use Output:Diagnostics,DisplayExtraWarnings;

**Comment by macumber** [comment]
Elizabeth Gillmor also reported that the diagnostic script does not fix errors for shading surfaces

@asparke2 FYI

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/37
