### ISSUE TITLE
Some HVAC components that exist in OpenStudio are missing from the HVAC library

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#599]
cc: @kbenne 

One such example is Fan:OnOff, but there may be others.

**Comment by macumber** [comment]
This issue is too general, @kbenne let's make sure we have captured all the objects in this issue then open new issues for any future objects

**Comment by macumber** [comment]
@kbenne @asparke2 I don't see this in pivotal.  As I said before, this is too general.  If there are any specific objects missing let's add those and close this issue.

**Comment by macumber** [comment]
@kbenne @asparke2 I don't see this in pivotal. As I said before, this is too general. If there are any specific objects missing let's add those and close this issue.

**Comment by DavidGoldwasser** [comment]
I think at least 5 specific objects are listed in the issue and comments. If all of those are in, then we can close, it but not a bad idea to proactively check that everything is in there by going through them. In one case an object showed up twice in the list.

**Comment by kbenne** [comment]
@MatthewSteen you may correct me if I'm wrong but I believe the only way to get CoilCoolingWaterToAirHP or CoilHeatingWaterToAirHP on air loop is to put it in a AirLoopHVACUnitarySystem.  Even the coil system wrapper won't do it, if I recall correctly.   I think the correct course of action on those two is to simply remove the category.

**Comment by kbenne** [comment]
Parallel fan powered boxes are now covered.

![screen shot 2015-06-17 at 8 42 34 pm](https://cloud.githubusercontent.com/assets/707488/8222464/74205836-1531-11e5-8461-b5b187da6eae.png)

**Comment by kbenne** [comment]
It appears that Air Terminal Single Duct VAV Reheat is correct in current code.  See above screenshot.
