### ISSUE TITLE
PAT, Tab 1 - Project I started yesterday now crashes if I re open and then select a measure instance

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#6]
This is the first issues I have seen like this with 1.0. Since I can't attach files I placed a zip file of the project on the network at the path below. @lgentile I will add to Pivital and put at top of backlog.

Y:\5500\5500 HPBldg\davidg\issue6.zip

**Comment by DavidGoldwasser** [comment]
@macumber I'll let you decide on this one. Broken PAT projects still do occur. Even just asked for sample project, and I gave him the one from our training repo. He wasn't able to open that tin the current version of OpenStudio. Didn't crash, just didn't open. I didn't tile a big for this, because there were already a number of corrupt project bugs, but typically not a repeatable way to corrupt a project.
https://github.com/NREL/OpenStudio-training/tree/master/Exercises/Basic%20Workflow/Models/Section%208%20-%20PAT

**Comment by macumber** [comment]
@DavidGoldwasser let's close this bug and open a new one for why the exercise file does not open
