### ISSUE TITLE
Open a saved .osm file to find that objects (windows, overhangs, etc.) are missing and/or moved. (Bugzilla #460)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#60]
On 2012-01-06 12:43:54, Daniel Studer wrote:

> It appears that this may be related to bad saves from within OpenStudio. I have gone into the text file and found objects that are either (1) incompletely written (i.e. no last line or semicolon in the E+ object), or (2) have been geographically shifted from where they were originally placed. The deletion of such objects fixes the file, but the underlying cause is very concerning. If OpenStudio is not writing the files correctly when it saves, then I should be prevented from opening the file once I reenter the program. After trying to find a file that illustrated this, it does not appear to be repeatable. Sometimes files open fine and other times they do not (for files that I suspect have bad objects within them). I have attached a file that has opened both correctly and incorrectly (ASHRAE 90.1-2004 Baseline V19.osm). Note that my workaround to this problem is to NEVER save a .osm file over itself. I ALWAYS use the âSave Asâ command which resulted in 38 separate .osm files for one projectâ¦

On 2012-01-06 12:55:12, Daniel Studer wrote:

> Created an attachment (id=106)
> ASHRAE 90.1-2004 As-Built Geometry V19.osm

On 2012-01-13 15:22:03, @DavidGoldwasser wrote:

> Updated out of date Milestone Targer

On 2012-01-16 13:26:36, @DavidGoldwasser wrote:

> I should follow up with Danny to get a file that has not been cleaned up yet to see what objects are incomplete. Then I'd like to see what to do duplicate the creation of this file. I understand that it isn't repeatable so this may be tough.

Original attachments:
* ASHRAE 90.1-2004 Baseline V19.osm (ID 106)

**Comment by macumber** [comment]
May be related to https://github.com/NREL/OpenStudio/issues/1350

**Comment by DavidGoldwasser** [comment]
Observer Issues
