### ISSUE TITLE
EnergyPlus failing on one run, then not when I re-run

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#600]
This is on a local run. It only happened on 3 out of 13 design alternatives. And only one some of the measures in a design group (never all the measures in a design group. See attached screenshot.

I re-ran the three jobs after throwing away results and this time only 2 of them failed.

The last two errors related to issue #598

![10-30-2013 3-26-21 pm](https://f.cloud.github.com/assets/4857055/1441465/ae6ef386-41ab-11e3-9c1c-581bce74750d.png)

![10-30-2013 3-26-40 pm](https://f.cloud.github.com/assets/4857055/1441466/b0c6578c-41ab-11e3-8a98-898781efc67c.png)

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
