### ISSUE TITLE
SketchUp Plugin keeps flipping vertical roof surface

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#602]
Not big issues, so just documenting it, but don't expect to fix it now. I'll just make this a wall.

![verticalroof](https://f.cloud.github.com/assets/4857055/1443760/e70f41a0-41f1-11e3-859f-42da1d025981.png)

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/36
