### ISSUE TITLE
OpenStudio does not always work within SketchUp. (geometry is not OpenStudio Entity) (Bugzilla #462)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#61]
On 2012-01-06 12:45:26, Daniel Studer wrote:

> Sometimes I will go to draw geometry inside of a zone (i.e. the zone is selected for edit) and the geometry is a SketchUp entity, not an OpenStudio entity. The only way I have found to fix this problem is to exit SketchUp entirely and reload my file (assuming it loads properly, see problem 1). This is currently occurring with ASHRAE 90.1-2004 As-Built Geometry V1.osm (attached). To create this file, I exported a .osm file to .idf and then imported that .idf and saved as a .osm file. I followed this path so that I could simplify the geometry based on the HVAC zoning pattern (i.e. I did not want geometry for all of my spaces).

On 2012-01-13 15:22:04, @DavidGoldwasser wrote:

> Updated out of date Milestone Targer

Keywords: NRELFile, Random

**Comment by DavidGoldwasser** [comment]
Observer issue, but we have added warnings to try and let the user know when this happens.
