### ISSUE TITLE
There is no way for a user to manually shut down the cloud whenever they want.

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#613]
New Issue for existing Pivotal Story
https://www.pivotaltracker.com/story/show/58627844

Description:
We have a current bug where sometimes the project gets stuck without the dialog popping up. I'm sure we will fix that but I'm also sure there will be other bugs like this. It would be nice if we let the user manually launch the "Lost Connection" dialog or just a pulldown menu item to kill the cloud anytime they want. This would avoid them (or me) from having to manually edit the sql file.

**Comment by macumber** [comment]
Workaround is to do this from EC2 console

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
