### ISSUE TITLE
On mac, opening PAT projects produces a strange RunManager error

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#621]
New Issue for existing Pivotal story

Description:
This appears on the console, when it definitely shouldn't be:
[openstudio.runmanager.RunManager] <1> Error loading runmanager database, db was imported from a previous version and has a required file conflict"

This occurs for any osp that is opened, even new ones with new baseline models.

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
