### ISSUE TITLE
Alert user if file fails to save. Ran across this in Plugin but may need to check App and PAT as well

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#626]
The behavior in the plug was what looked like a proper Save or SaveAs. In both cases the file still had the old version number and didn't have any of the updates. First indication of a problem was that the save date of the file was not updated.

In this case the cause was a read only .osm file. SaveAs still produced a file but it was also read only and didn't reflect the changes.

We should test how OS app behaves with a bad save, and maybe an issue for PAT as well, as it tries to update the OSM to the current version.

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
