### ISSUE TITLE
Rotating a space on x or y axis (vs. z) results in out of sync geometry (Bugzilla #477)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#66]
On 2012-01-12 22:02:21, @DavidGoldwasser wrote:

> Looks to rotate correctly in SketchUp plugin but when re-opened it is at unexpected location.
> 
> Draw a space, then rotate it and save osm file. Try and re-open.

On 2012-01-12 22:08:47, @DavidGoldwasser wrote:

> Created an attachment (id=121)
> screenshot of model whiel rotating space

On 2012-01-12 22:09:22, @DavidGoldwasser wrote:

> Created an attachment (id=122)
> Screenshot of rotated model after re-opening it

Original attachments:
* rotate_a.png (ID 121)
* rotate_a-reopen.png (ID 122)

Keywords: SyncWithSU

**Comment by DavidGoldwasser** [comment]
I think we have this locked down (if you try to rotate, should jump back?) But if not we won't fix

**Comment by macumber** [comment]
@DavidGoldwasser confirmed that this does not snap back and no errors are given.  Adding won't fix label
