### ISSUE TITLE
User should not be able to change space shading to building shading in inspector

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#667]

**Comment by macumber** [comment]
Still possible, now generates the "Plugin has stopped working error"

**Comment by macumber** [comment]
Possible solution is to lock down the field and add a new user script that let's people change group from one type of shading group to another.  @DavidGoldwasser do you have any ideas for the interface?  Maybe "Change Selected Shading Group Type" and the input is type to change to?  I can preserve global location.

**Comment by macumber** [comment]
Going to just change policy with no new user script, users can copy content in SketchUp if needed

**Comment by DavidGoldwasser** [comment]
I think that is fine. It should be a common need. I just assume have them copy the geometry. then make a new shading group and use paste in place. That will resolve any transformations.

**Comment by macumber** [comment]
Turns out you can't choose the shading group type when you make a new one so I ended up making the user script anyway

**Comment by DavidGoldwasser** [comment]
@macumber If you are inside of a space when you place a new one, it already makes it a space shading surface group. But I see your point, when doing it at top level, you can't choose if you want it to be site or building. Why not just adjust that tool to pop up a dialog to choose site or building? Unless just doing a script is easier.

**Comment by macumber** [comment]
The script is done, so that is easiest :-)
