### ISSUE TITLE
Running WWR user script in plugin on edge to edge walls breaks model

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#668]
I hit this trying to use WWR on reference building geometry. The entire walls disappear, and then you get errors when you re-open it.. I think this is plugin specific and wouldn't happen when WWR is used as a measure outside of SketchUp. On attached images you can see before on left and after on right.

![11-22-2013 10-51-36 am](https://f.cloud.github.com/assets/4857055/1602902/224fc55e-53a0-11e3-9669-c5474025107d.png)

**Comment by macumber** [comment]
@DavidGoldwasser is this still valid?

**Comment by macumber** [comment]
@DavidGoldwasser is this still valid?  it is listed as needed for 1.7.0

**Comment by macumber** [comment]
@DavidGoldwasser assigned to you to better document or close

**Comment by DavidGoldwasser** [comment]
@macumber yep, Steve (the scale figure) says it is still valid, Just import the medium office reference building and run the WWR user script with the default values.

![3-19-2015 3-25-56 pm](https://cloud.githubusercontent.com/assets/4857055/6741399/b91b3324-ce4c-11e4-95f6-a5e3223e3002.png)

When you re-open the model you have three sub surfaces missing their base surfaces. (FYI - I only ran WWR on the one facade, it would cause issues anywhere when original windows were as wide as the base surface.You could say it is bad practice for  base model, but it is shipping this way as reference buildling. @asparke2 are you changing the geometry for your buildings or using it as is?

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/35
