### ISSUE TITLE
Error trying to Autosize OS:WaterHeater:Mixed: Wrap WaterHeater:Sizing in OpenStudio

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#669]
When I drop in a water heater it starts as 100 gallon tank volume, and a capacity of about 2,800,000 Btu/hr.

The capacity seems large, when I tried to run after changing it to autosize I get the following error. Am I doing something wrong, or is there no way to autosize this object? 

   *\* Warning *\* Water heater named OS:WATERHEATER:MIXEDhas heater capacity set to AUTOSIZE but it is missing associated WaterHeater:Sizing object
   *\*  Fatal  *\* Errors found in water heater input. Preceding condition causes termination.

**Comment by MatthewSteen** [comment]
I'm seeing this in 1.6.0 and 1.6.3.

**Comment by jmarrec** [comment]
+1 in 1.10.2

**Comment by DavidGoldwasser** [comment]
@kbenne any thoughts on this?

**Comment by kbenne** [comment]
My thought is we need to at WaterHeaterSizing, but I honestly don't have it in my queue yet.

**Comment by ckirney** [comment]
Could you remove the autosizing option from the water heater tank volume and tank capacity in the interface until you have time to fix the problem (which I think is telling EnergyPlus which of the six autosizing options to use)?
