### ISSUE TITLE
Interpolate should be translated to idf for schedule fixed interval and schedule variable interval

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#672]

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio/blob/a007b7801e3bb05731f012f585facdd814ef31fb/src/energyplus/ForwardTranslator/ForwardTranslateScheduleFixedInterval.cpp#L144-L148

https://github.com/NREL/OpenStudio/blob/a007b7801e3bb05731f012f585facdd814ef31fb/src/energyplus/ForwardTranslator/ForwardTranslateScheduleFixedInterval.cpp#L172
