### ISSUE TITLE
C# code is not compiled into a namespace

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#679]
We have issues with class name collisions due to this.  It seems that we need to use --namepsace when using the SWIG C# generator, this article should help:

http://swig.10945.n7.nabble.com/Swig-C-multiple-modules-in-different-C-namespaces-td11616.html

**Comment by jmarrec** [comment]
I'm closing, not enough information to reproduce, and I haven't seen any problems with the c# bindings and name collision lately.
