### ISSUE TITLE
Inersect in SketchUp (is producing duplicate surface and sub-surface not contained by base)

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#681]
@macumber this is from the user file sent from Annie M. I'll attach this file the the files repo with this bug number.

Intersect looks like it works, but when you surface match, some issues appear. Then when you re-open the OSM you get these errors.

Error:  E2ABC9 2
This planar surface shares the same SketchUp face as E2ABC9.
This error cannot be automatically fixed.  The surface will not be drawn.

Error:  Sub Surface 1
This sub surface is not contained by its base surface, it cannot be drawn.

![12022013_02](https://f.cloud.github.com/assets/4857055/1658221/c0f6b1b2-5b8f-11e3-9910-b0413b9371ea.png)

Dan, I still have not had time to look at how OS based intersection is done. If you make a measure that runs intersect, I'd be happy to run this model through it to see how it works.

David

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/34
