### ISSUE TITLE
Implementation of Shading Control needs some work before we show  people how to use it

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#688]
This probably just requires changes to the user scripts in the plugin and not C++. Currently the process is a little confusing, and also doesn't allow you to swap out one fenestration construction for another, unless it has a blind or similar object.

I'll try to use it as is and give Dan feedback. It would be great if we can fix for 1.2 release, as we have had many requests for this for a while.

I'm wondering if this effort should be to make a real measure vs. a user script so that this can be used as an ECM.

**Comment by macumber** [comment]
@DavidGoldwasser @rpg777 should this be closed?

**Comment by rpg777** [comment]
I guess; the initial complaints about this at the top of the issue still apply (confusing and limited feature), but it works and I have a separate ticket to fix the workflow issue related to these controls in the Radiance scripts (which I plan to fix this week and then document).

**Comment by mdahlhausen** [comment]
@DavidGoldwasser Request to re-open this issue to add other shading control type options, especially MeetDaylightIlluminanceSetpoint.

**Comment by jmarrec** [comment]
Can you open a new issue instead @mdahlhausen please? (Reviving a 6 year-old issue that's somewhat related is probably not the best way to put this new issue on the roadmap)

I see there are new "Shading Control Type" values, but is that the only addition needed?
