### ISSUE TITLE
Invalid "tag" in built-in Replace Opentudio Model measure.rb file

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#692]
In the measure.rb file for the measure called "Replace OpenStudio Model" that gets added to your project when you click "Import from External Model" in PAT, the taxonomy tag of the measure is "WholeBuilding" which is invalid.  Change it to "Envelope.Form"

**Comment by macumber** [comment]
@asparke2 @DavidGoldwasser it seems like we do need to add a whole building term to the taxonomy?

**Comment by asparke2** [comment]
There are tags for Whole Building.Space Types and Whole Building.Whole Building Schedules already.  If we add more, the EDAPT xml and other processing code needs to be updated, so let's be considerate.
