### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [NREL/OpenStudio#696]
Some parameters (like "[${CMAKE_SOURCE_DIR}/doc/index.html.in](https://github.com/NREL/OpenStudio/blob/fa5421e2e8a5441c2b34340de4398fa5f6f49b61/openstudiocore/CMakeLists.txt#L443)" and "[${CMAKE_CXX_COMPILER}](https://github.com/NREL/OpenStudio/blob/e4e333abf307f447aab8869c30caee253907f520/CMakeLists.txt#L518)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like spaces.

I would recommend to apply [advices from a Wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes.).

**Comment by jmarrec** [comment]
Closing this 7yo issue until we hit actual actionable problems. So far it seems to be working just fine.

**Comment by elfring** [comment]
How do you think about to [recheck data processing for CMake lists](https://cmake.org/cmake/help/v3.17/manual/cmake-language.7.html#lists "Description for CMake lists")?
