### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [NREL/OpenStudio#698]
[An extra null pointer check is not needed in functions](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8 "Do I need to check for NULL before delete p?") like the following.
* [SqliteObject](https://github.com/NREL/OpenStudio/blob/cb2a233772343b75604f0a96785ab2aece64501b/openstudiocore/src/runmanager/lib/ParallelEnergyPlus/SqliteObject.cpp#L71 "destructor for SqliteObject")
* [HVACSystemsController](https://github.com/NREL/OpenStudio/blob/5a088b8d60a46a1ea25b4d47c1aac67a4e540de9/openstudiocore/src/openstudio_lib/HVACSystemsController.cpp#L150 "destructor for HVACSystemsController")
* [PlanarSurfaceWidget::clear](https://github.com/NREL/OpenStudio/blob/44082f374e5648decfc6466e082e3df4814773da/openstudiocore/src/openstudio_lib/PlanarSurfaceWidget.cpp#L74 "PlanarSurfaceWidget::clear function")

**Comment by elfring** [comment]
Do you reject this update suggestion?

**Comment by macumber** [comment]
@elfring yes because I am not sure that these checks are unnecessary for all control paths, I'm curious how your static code analyzer figured that they were

Thanks also for your help!

**Comment by elfring** [comment]
I hope that you like also small speed improvements for your software.
Null pointer checks are really [unnecessary directly before use of the delete operator](http://www.parashift.com/c++-faq/delete-handles-null.html "Do I need to check for NULL before delete p?") because the specification of the C++ programming language gives you such information that [implementations will handle it already](http://en.cppreference.com/w/cpp/language/delete "Description for the delete expression") for you. Would you like to reconsider corresponding details?

**Comment by macumber** [comment]
Interesting, I had always thought calling delete on a NULL pointer caused an error

@lefticus what is your opinion here?

**Comment by lefticus** [comment]
My opinion is that you're solving the wrong problem. Why are we doing manual memory management at all in these cases? We should be using `std::unique_ptr` instead. And also, we should be assigning / checking `nullptr` instead of `0` if we really really do need to manually manage it (but from what I looked at, that is not the case).

**Comment by elfring** [comment]
How do you think about to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks")?
