### ISSUE TITLE
A number of Simulation Settings Tab fields should be OSComboBoxes rather than OSLineEdits

### ISSUE THREAD

**Issue by elainethale** [NREL/OpenStudio#7]
A number of fields in the SimulationSettingsView  (e.g. ShadowCalculation::polygonClippingAlgorithm and ShadowCalculation::skyDiffuseModeling) are presented to the user as free-form line edits, even though they are choice fields that are expecting particular key strings. From the user's perspective, they see a free-form field and have no way (without going outside the app) to know what they are supposed to type there. In general, if the underlying IDD field is of type \choice, the app should use OSComboBox, not OSLineEdit.

**Comment by DavidGoldwasser** [comment]
Looks like there is an open pull request, so this should be closed soon.

**Comment by asparke2** [comment]
Merged pull request that fixed this
