### ISSUE TITLE
Cloud run sometimes can't find the weather file

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#702]
This is not repeatable, but happens occasionally on cloud runs. In the example screen shot attached 1 out of about 60 datapoints didn't run. The measures have nothing to do with weather file. Just changing LPD, etc. The last time I ran this same project two jobs failed instead of one.

@macumber feel free to re-assign, not sure who should get this.

![12-9-2013 10-18-31 am](https://f.cloud.github.com/assets/4857055/1707742/d34392cc-6102-11e3-8315-e4c36db990e9.png)

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
