### ISSUE TITLE
Clear Results Bug and graphic confusion

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#703]
Currently after a cloud run while the cloud is still on I can't clear results using tab 3. In this case I didn't have detailed results downloaded, just high level, and in this case the simulation failed, and I just wanted to re-run it. This is a corner use-case from issue #702.

I'm OK if we just say expected behavior is not to be able to clear results while cloud is on, but then we should use the disabled icon for the button so users know not to click it.

Seeing the screenshots below "enabled" is grey, and "disabled" is really light grey. The icon for download has a color and b/w version for the two states. Maybe this should do the same. Also, a column header (really for all columns) would be helpful to even identify what the "c" button really does".

![12-9-2013 10-26-05 am](https://f.cloud.github.com/assets/4857055/1707837/1cff9b44-6104-11e3-94a3-44f8625d1ab6.png)

![12-9-2013 10-26-50 am](https://f.cloud.github.com/assets/4857055/1707833/1812933e-6104-11e3-8c34-f507a75cfecc.png)

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
