### ISSUE TITLE
The scale tool isn't selected after adding an Illuminance map (Bugzilla #487)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#71]
On 2012-01-20 10:42:05, @DavidGoldwasser wrote:

> Without this it isn't very intuative for the user to know how to properly resize this. Just adding here so we can re-implement this when plugin re-done.

Keywords: OldGUI

**Comment by DavidGoldwasser** [comment]
Not sure if fixed, but if not, don't see us changing it now.

**Comment by macumber** [comment]
Not fixed, adding won't fix label
