### ISSUE TITLE
Calling openstudio::model::Model::load with path to 'OpenStudio.exe' returns initialized model (Bugzilla #488)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#72]
On 2012-01-25 08:18:05, @macumber wrote:

> Has a single catchall object, how is that possible?

On 2012-01-25 08:21:50, @macumber wrote:

> Also, found you can open an idf file using model load.  It creates a bunch of catchall objects, this does not seem like the old behavior.

**Comment by macumber** [comment]
This should stay open.  The bug is that calling OpenStudio::Model::Model::load with path to any random file (zip, exe, docx, etc) returns an initialized model.  To me it seems that it should return false since it did not load an IDF/OSM file

**Comment by jmarrec** [comment]
Still true OS 2.2.1
