### ISSUE TITLE
Entering an invalid date on the Utility Bills subtab crashes OpenStudio

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#739]
On the Utility Bills subtab, create a new utility bill and billing period.  Then enter a valid _start_ date of a month with 31 days (e.g. 10/31/13).  Lastly, change the month to a month with less than 31 days (e.g. 9).

**Comment by macumber** [comment]
@axelstudios I can't reproduce, can you verify this?

**Comment by axelstudios** [comment]
Closing, looks like this was fixed in a previous Qt release
