### ISSUE TITLE
Incorrect units displayed in inspector (Bugzilla #493)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#74]
On 2012-01-27 10:21:24, @macumber wrote:

> Showing 3 ft for height of building story when it should be 3 m
> 
> Need to tie signal for ip/si to sketchup

On 2012-09-10 00:53:31, @DavidGoldwasser wrote:

> 0.8.4 It does seem to correctly show based on IP or SI settings but there is no unit shown for the value.

**Comment by DavidGoldwasser** [comment]
Not doing work on inspector in plugin.
