### ISSUE TITLE
General problems with leap year simulations

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#745]

**Comment by macumber** [comment]
Relates to https://github.com/NREL/OpenStudio/issues/817

**Comment by joseph-robertson** [comment]
Here is a sql for a simulation run with a AMY 2012 weather file (includes 2/29 leap day):
[eplusout.zip](https://github.com/NREL/OpenStudio/files/2962500/eplusout.zip)

The Time table looks correct; it includes timestamps for 2/29 and has the correct year. However, `sqlfile.timeSeries(...).dateTimes` does not show data for 2/29, instead it extends one day past 12/31 (see Dan's comment above).
