### ISSUE TITLE
Crash when adding zone to air loop

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#746]
Open the associated file in the openstudio-files repo, go to the air loop, attempt to add the living space thermal zone to the loop and the app will crash
![12-20-2013 12-52-33 pm](https://f.cloud.github.com/assets/1327850/1793337/9470f5f6-69b0-11e3-92b2-83f2b774be47.jpg)

**Comment by kbenne** [comment]
Opened in 1.6.0 and assigned living zone without incident.  This model was from version 1.1 so I'm going to assume this issue has been resolved under other changes.

![screen shot 2015-02-26 at 11 14 52 am](https://cloud.githubusercontent.com/assets/707488/6397220/e03f50ac-bda8-11e4-87e5-2e418e31ab9f.png)
