### ISSUE TITLE
When two spaces in zone have mis-matched "Part of total floor area" flag we should issue a warning on export ot IDF

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#749]
Would be nice to have a warning in forward translation for this condition.

**Comment by jmarrec** [comment]
This was opened a long time ago, and the API might have been doing things differently, but nowadays I'm sure it's doing the right thing in [ThermalZone::combineSpaces](https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/model/ThermalZone.cpp#L1574): If there are mis-matched "Part of total Area" flags, then it explicitly sets the total floor area to only take the area of the ones that **are** part of the total area.

I'll add an "Info" (not a warning) there.
