### ISSUE TITLE
Ground and water temps not displayed correctly in inspector in SketchUp (Bugzilla #507)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#75]
On 2012-02-10 10:14:20, @DavidGoldwasser wrote:

> Values shown don't match what are in the OSM file. See details in bug 505. But 505 also details a forward translator issue. I'm just breaking the display into its own bug.

**Comment by DavidGoldwasser** [comment]
I don't think we display round water temps anywhere in GUI, so this must have been from deprecated ModelEditor GUI?
