### ISSUE TITLE
After failed simulation old results still show in results tab, but not functional

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#753]
I had a failed run, went to the results tab expecting it to be empty, but the results from the previous run still show up. I can see my various reports in the pull down menu, but changing the pull down menu doesn't change the reports.

Maybe the behavior should be to delete these files and clear this view at the start of a run?

**Comment by jmarrec** [comment]
tested with OS 2.2.1. Results tab is empty after failed run. Can be closed
