### ISSUE TITLE
RunManager fails to search for tools (Bugzilla #519)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#76]
On 2012-02-29 12:45:25, @axelstudios wrote:

> Created an attachment (id=145)
> Crash report
> 
> On a clean install of OS X 10.7.3, RunManager crashes as soon as you press OK in response to its prompt about not having any tools.
> 
> This same step works fine on the same machine after build tools have been installed, so there is likely a hardcoded path failure.

Original attachments:
- RM.png (ID 145)

**Comment by DavidGoldwasser** [comment]
I haven't scanned for tools in RunManager for long time. I'd have to test, but I expect it is fixed. Will show as low frequency because almost nobody uses that GUI.

**Comment by ljbrackney** [comment]
RunManager deprecated
