### ISSUE TITLE
Some measure from BCL are not showing in App

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#773]
cc: @asparke2 

I see two causes. One of them is an issue in the measure. The "Set Lighting Loads by LPD" xml is missing a version object. I can fix that and re-upload it.

The second case I see is where an outdated taxonomy is being used. It wasn't evident at first because for "Add Daylight Sensor ...." it shows the newer taxonomy on BCL vs. the old taxonomy in the actual XML "Electric Lighting.Controls". Maybe we changed this live on BCL, or maybe it is doing it on download.

So I need to look through all measures in the repo and:
1. Check for valid version object
2. Update XML taxonomy where applicable. When I do this I should also update the version to 1.2

**Comment by macumber** [comment]
@DavidGoldwasser is this fixed?  Ticket is closed in pivotal, https://www.pivotaltracker.com/story/show/63435884

Can you close if done

**Comment by macumber** [comment]
@DavidGoldwasser is this fixed it is listed as needed for 1.7.0

**Comment by DavidGoldwasser** [comment]
It will take me some time to look into it, not important for 1.7.0.

**Comment by kbenne** [comment]
Still closed in Pivotal and not closed here.  I'm going to reopen in Pivotal until it gets resolved.

**Comment by macumber** [comment]
Might need to also check for duplicate uuids

**Comment by DavidGoldwasser** [comment]
The affected bugs have been fixed. but if alter existing taxonomy we will have to update measures again.
