### ISSUE TITLE
Crash on delete air loop (on second loop I delete)

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#775]
Hmm, so it isn't about speed. This is really odd It crashes on the second air loop you delete. There There doesn't seem to be a particular loop that will make it crash unless you first delete. This is from a model made by audit tool. I'll post link to file once I uplaod it.

**Comment by macumber** [comment]
@kbenne you still working on this for 1.7.0?

**Comment by kbenne** [comment]
I am working on it, but I have changed my mind about putting it in 1.7.0.  This is too close to the wire and I haven't figured out the repercussions.  I'll merge something right after 1.7.

**Comment by macumber** [comment]
Cool, let's put it in 1.8.0

**Comment by kbenne** [comment]
This is addressed with curve as resource.

**Comment by DavidGoldwasser** [comment]
@kbenne so I assume ok to close? If not then please re-open.
