### ISSUE TITLE
Zones Tab - Minor issue but why don't we display color for thermal zone like we do elsewhere (Bugzilla #546)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#78]
On 2012-03-04 23:47:11, @DavidGoldwasser wrote:

> Look at Space Type and Story tab for color picker.

On 2012-03-05 16:10:10, @DavidGoldwasser wrote:

> <Batch change milestone from 0.7.0 to 0.7.1>

**Comment by DavidGoldwasser** [comment]
Still would be nice, but not many people asking for it. With reporting measure possibly using this it would be nice for the user to have a place to change it, in particular if they don't want the plugin to be part of their workflow.

**Comment by jmarrec** [comment]
There is a color picker in the Space Type, but not for Space nor ThermalZone. (OS 2.2.1)
