### ISSUE TITLE
As a user how do I add scripts to the library or import a script (Bugzilla #549)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#79]
On 2012-03-04 23:51:45, @DavidGoldwasser wrote:

> I can make an empty script and copy paste text into it, but doesn't seem ideal. When I load an OSM as a library it doesn't seem to change what scripts are in the library.

On 2012-03-05 09:31:20, @macumber wrote:

> Impacts work flow so made critical, but a work around might be to start a blank script and then copy in text editor

On 2012-03-05 16:10:11, @DavidGoldwasser wrote:

> <Batch change milestone from 0.7.0 to 0.7.1>

On 2012-03-15 14:41:38, @DavidGoldwasser wrote:

> The just need to know where the directory is. The new Load Library helps them find that path. Can be addressed in documentation as well

**Comment by DavidGoldwasser** [comment]
deprecated with scripts tab. Not an issue with measures.
