### ISSUE TITLE
Run Tab - On run tab not really clear when simulation is done (Bugzilla #550)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#80]
On 2012-03-04 23:53:33, @DavidGoldwasser wrote:

> Why not switch to tree sub tab or results tab when it is done.

On 2012-03-05 16:10:11, @DavidGoldwasser wrote:

> <Batch change milestone from 0.7.0 to 0.7.1>

**Comment by DavidGoldwasser** [comment]
still not great, but we have plans to bring in run section from PAT. I don't see us doing any band aids before then.
