### ISSUE TITLE
"Update All of My Measures" isn't getting epw files on any of our reporting measures

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#801]
These are nested down a bit, not sure that is the issue. At least in some cases this is preventing upload to BCL because XML is out of sync with package contents.

cc: @asparke2

**Comment by macumber** [comment]
@DavidGoldwasser can you clarify what the problem is here?  If you change the epw file and push update my measures the change is not detected?  The files have to be flat in the test and resource directories to be detected

**Comment by DavidGoldwasser** [comment]
@macumber can't remember exactly what was happening. I'll look back into this in February.

**Comment by macumber** [comment]
@DavidGoldwasser I am assigning this to you to better document or close

**Comment by DavidGoldwasser** [comment]
@macumber so the issue here was really that the XML not matching prevented BCL upload from working. I can flatten the epw out in the testing folder, I don't want to put it in resources, because it is only for use in the test. Since it isn't very easy without a text editor to edit the OSM pat to be outside of the typical directory, the reporting measure tests should have code to add in the path to the weather file dynamically.

**Comment by DavidGoldwasser** [comment]
@macumber I'll close this, but by not nesting the weather file for reporting measure tests in the typical location made by the OS app, that does mean that anyone writing a reporting measure test (which should be everyone writing a reporting measure) will need to edit their OSM file with a text editor to provide the flattened weather path. We will have to update measure writing guide to show people.

I guess there is another alternative. The measure test itself could set the weather file right after the OSM is loaded. Maybe that is a better solution.

cc: @asparke2
