### ISSUE TITLE
No way to get year in E+ output

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#817]
Need this for reconstructing timeseries, consider adding E+ preprocessor message with the year and querying for it when opening sqlfile

**Comment by macumber** [comment]
Looks like this output variable might be useful:

Zone,Average,Site Day Type Index []

http://bigladdersoftware.com/epx/docs/8-0/input-output-reference/page-008.html#site-day-type-index

**Comment by macumber** [comment]
There is also a DayType field in the Time table of the SQL output, you could find the first non-holiday and determine an assumed year from that, you would also have to scan for 2/29

**Comment by macumber** [comment]
I would also like to fix this bug as part of this, https://github.com/NREL/OpenStudio/issues/1895

If we allowed year description to have a month and day then we could find the matching year for the first non-holiday in the time table

**Comment by macumber** [comment]
@jasondegraw would you be ok taking this bug?

**Comment by jasondegraw** [comment]
@macumber Yes, I can take it.

**Comment by macumber** [comment]
May be best to wait until this is fixed in E+

**Comment by jasondegraw** [comment]
Agreed

**Comment by jmarrec** [comment]
@jasondegraw added the year field in the Sql in 8.9.0 in https://github.com/NREL/EnergyPlus/pull/6456

Looks like we can close this one, since I don't see any other action items that aren't part of another open issue.

**Comment by jasondegraw** [comment]
@jmarrec There are underlying issues with the implementation of time, dates, and timeseries that are not as far as I know addressed, reopening.

**Comment by jmarrec** [comment]
I thought that #745 and #1895 captured the problems fairly well in my opinion.

If that's not the case, could you please include specific details/action items? I myself don't know what needs fixing here, and if others are the same I'm afraid that this issue could stay open indefinitely.

**Comment by jasondegraw** [comment]
@jmarrec You do see that this issue is assigned to me, right? This is something that can be revisited once develop3 has been merged, and not until then.

**Comment by jmarrec** [comment]
Yes, I did see it was assigned to you, and also clearly tagged as an Energyplus issue to add the year in the SQL file, 5 years ago.

I'm just trying to clean up the issue backlog when I can, I **genuinely** thought this one made for an excellent candidate given the actual information on the issue (cant really read anyone's mind unfortunately).
I'd rather close really old issues with no reamining unduplicated action items - even if that means in a handful of cases  potentially trigger a reopening with the benefit of added and/or updated information - than let them pile up and mudder the issue list. I've scanned the entire backlog a few times over the past year and there are still a lot of them, some flagged for potential closing a few times already.

Seems like I was wrong in closing in this case anyways, my apologies.

**Comment by kbenne** [comment]
Hi @jasondegraw. Now that develop3 is merged can you update this thread. Do you anticipate more work before we can close this?

**Comment by jasondegraw** [comment]
@kbenne There's a lot that could be done, but I'm out of the loop.

**Comment by kbenne** [comment]
Close for now, but welcome to reopen in the future.
