### ISSUE TITLE
Can't add OS:MaterialRoofVegitation to a construction (Bugzilla #562)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#82]
On 2012-03-05 10:28:06, @DavidGoldwasser wrote:

> User identified this, I confimred it as well. Thought maybe had restrictions on outside layer, or single layer construction, but didn't ever see this in the material pulldown.
> https://openstudio.nrel.gov/forums/openstudio-plug-google-sketchup/general-discussion/green-roof-material-vegetation-constructio#comment-1061
> 
> I would assume this bug extends outside of the plugin to other apps.

**Comment by DavidGoldwasser** [comment]
duplicate of #1317
