### ISSUE TITLE
Minor graphic glitch where sub tabs are floating (Bugzilla #568)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#83]
On 2012-03-06 09:24:53, @DavidGoldwasser wrote:

> Created an attachment (id=150)
> mac screenshot of floating tabs
> 
> Doesn't seem to impact use, just cosmetic. When you first go to a tab you won't see this, but click on a sub tab and it will show up, and will stay even if you go back to the previous sub tab.

Original attachments:
* FloatingTabs.png (ID 150)

**Comment by DavidGoldwasser** [comment]
fixed
