### ISSUE TITLE
When a surface boundary condition is changed to "Outdoors" the default should be to make it sun and wind exposed

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#833]
Currently it is not. This makes setting up attics with overhangs harder to model.

**Comment by macumber** [comment]
Already done https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/Surface.cpp#L406

**Comment by DavidGoldwasser** [comment]
@macumber they are both set to false now. I think they should both be true.

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/Surface.cpp#L434

**Comment by jmarrec** [comment]
David, you're experiencing that when you do it in the Sketchup inspector, right? That is doing only workspace stuff according to @macumber 

If you use the API and do `surface.setOutsideBoundaryCondition("Outdoors")` it does change it to SunExposed and WindExposed (and if you do "Adiabatic", it does change them to NoSun and noWind)

Considering the current plans for the sketchup plugin, I think this one might need to be tagged "Won't fix"  and closed...

**Comment by DavidGoldwasser** [comment]
Looks like API and GUI now change this, so this can be closed, but I made new crash but in the process of testing this. One step forward one step back :)
https://github.com/NREL/OpenStudio/issues/2822
