### ISSUE TITLE
OSM with mis-matched interior constructions fails in an odd way

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#836]
It should either fail to make an IDF or make an IDF with mis-matched constructions (to be fixed by user later), but instead it makes an IDF with no zones and surfaces. But in OS app it still continues to go through run manager and runs a successful EnergyPlus run, but without any results.

**Comment by DavidGoldwasser** [comment]
@DavidGoldwasser reverify

**Comment by jmarrec** [comment]
@DavidGoldwasser could you verify again, or provide the file (I can't access the link above) please?

**Comment by DavidGoldwasser** [comment]
Works as expected now, When it exports to IDF with zones, which than fails as expected, because of the mismatch.

> ** Severe  ** GetSurfaceData: Construction 000 INTERIOR CEILING of interzone surface SURFACE 6 does not have the same materials in the reverse order as the construction CBECS 1980-2004 EXTROOF ATTICFLOOR CLIMATEZONE 5A of adjacent surface SURFACE 7
