### ISSUE TITLE
What is the drop zone box for in the left pane of the story and thermal zone tab (Bugzilla #579)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#85]
On 2012-03-06 22:31:27, @DavidGoldwasser wrote:

> If I load in an OSM file as a library that has stories and thermal zones they don't show up as objects to drag into these drop boxes. What are these for?
> 
> It would be really cool if you could use a library to import spaces under a story or thermal zone but I didn't think that was in our plan.
> 
> If there is nothing to drag into the drop boxes then we should hide it.

**Comment by DavidGoldwasser** [comment]
With Gridview the drop zone is gone for Thermal Zones. If story starts to use GridView I expect the same would happen.
