### ISSUE TITLE
Assert when running PAT project on the cloud

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#868]
Reported by Nick:

It appears that a new assert has popped up when running PAT points on the server.  The points still run to success so it isn't high priority.

Nick

[BOOST_ASSERT] <2> Assertion m_analysisUUID.get() == analysis->uuid() failed on line 218 of boost::optional<QUuid> openstudio::analysis::detail::DataPoint_Impl::analysisUUID() const in file /home/bldadmin/OpenStudio/openstudiocore/src/analysis/DataPoint.cpp.

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
