### ISSUE TITLE
Cloning object from library multiple times will keep making extra copies in the model

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#870]
This has been around a long time, but I'm not sure if there was an issue filed. I was hitting it today and thought I'd document it. Below is the workflow I hit this in.

I have a large model with no space types in it. I loaded the secondary school library and went to facility tab. I am dragging space types from the library to the desired spaces in the facility tree.

If I keep dragging classroom over I get multiple copies of that space type. I thought clone was supposed to recognize that they are the same, and not keep making extra copies.Maybe this has been broken as long as UUID's have been around?

In theory when I want to use a space type that I have already assigned once I can switch to "My Library" and then go back to "Library" when I need a space type I have not used, but it isn't a nice workflow. This can certainly be something we address after the release.

**Comment by kbenne** [comment]
@DavidGoldwasser @macumber @elainethale 

See my notes in the [unit test commit](https://github.com/NREL/OpenStudio/commit/4ec76a262b71c604ac8802740f71a9afe5d09dc9).  I can (probably) change the behavior of ResourceObject::clone, however this is a major change with perhaps unforeseen consequences so we shouldn't do it without some discussion.

**Comment by DavidGoldwasser** [comment]
@kbenne I'm fine flagging this as a feature. I do think it is the right thing to do. This issue isn't just the resource you clone, but some resources that it refers to. So if drag in a construction from library that uses drywall as a material, and then I drag in another that uses drywall, I only want one drywall material on the model. Back in the pre UUID days, the logic was like this (. If the name of the object and every field was the same in the target model, then the object was not cloned, if the name was the same but any other attribute was different, then the object was cloned in the target model and was given a new unique name)

@macumber I'm also wondering about UUID's of non resources like spaces. Will these not mainlining their UUID limit our options when developing workflows to merge models. We may have to resort to using names to re-build relationships vs. UUID, which maybe is fine? But it limits someones ability to rename objects while they are working on an isolated part of it.

**Comment by kbenne** [comment]
@DavidGoldwasser examine the unit tests I'm adding here.  There, I elaborate on the subtleties of how referenced ResourceObject instances are handled.  I demonstrated this though SpaceType, People, PeopleInstance, and ScheduleRuleset, but I expect the same behavior in Construction / Material.  Except what you describe is not what the unit test for SpaceType shows.  I think I will write more tests for construction and material.

**Comment by kbenne** [comment]
@DavidGoldwasser also, I'm not too concerned about the label of feature request vs bug, but I am concerned about the unforseen consequences of changing clone behavior on ResourceObjects.  I assume we can deal with those issues, I just want everyone paying attention to what I'm going to potentially do.   

To be clear we are talking about changing ResourceObject::clone behavior so that when you clone between two different models, if an identical instance already exists in the target model the clone won't do anything.  I am assuming that if you clone within the same model the current behavior will remain, and you will get a copy.

Also note that load instances (People for example) are not resource objects, so when you clone SpaceType, even if I change ResourceObject::clone behavior, you are still going to get another instance of People.

**Comment by DavidGoldwasser** [comment]
Kyle, thanks for the clarification on referenced resources, that does appear to be the behavior I want. I just want to extend it to other resources.The issue is that people stay in the "Library" vs. "My Model" to for example dragging schedules into drop zones in the space type tab. They don't really want 5 copies of that schedule in their model.

For non resources objects like cloning spaces across models it occurred to me I could create a special ruby based clone helper method that maintains the UUID of the objects across both models. This isn't something a user would hit in GUI unless it was through a measure.

**Comment by kbenne** [comment]
Retaining the UUID when cloning across models is a bad idea!  You have no way of knowing if one of them is modified, at which point they are clearly not the same object and should not have the same id.  We call them universally unique identifiers for a reason.

Changing ResourceObject::clone behavior seems like a reasonable thing to consider.  But there is an argument to be made that if you didn't want a copy from the library then don't drag it from the library.

**Comment by macumber** [comment]
The behavior that David is asking for is in insertObjects, https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/utilities/idf/Workspace.hpp#L258.  It is possible that various drop zones could be configured to use this instead of clone.  However, in that case I am not sure how to define which objects to grab from the library (since clone defines that).

**Comment by kbenne** [comment]
In my opinion insertObjects is a back door on Model akin to IdfObject::setString(0,foo).  I don't think it should be promoted in Model.

**Comment by macumber** [comment]
I'm fine with that, I'd like to look at which of these methods we can remove or label as deprecated and move to private implementation only.  CloneSubset seems like a good candidate to remove from the public API.

**Comment by macumber** [comment]
As a final note, just to be clear I don't think we should change the implementation of clone.  The issue David brought up seems best fixed when we implement the feature of BCL components with locks.

**Comment by kbenne** [comment]
If it didn't come through, I'm not eager to change clone either.  That said, David, the workflows issues you raise seem valid to me.   I just don't think I agree with the remedy.  At any rate I'm continuing to add unit tests to capture current behaviors.  See most recently the [commit](https://github.com/NREL/OpenStudio/commit/303ae3822a563d502faea0417348a93efd736043) of tests on Constructions.

**Comment by mbadams5** [comment]
I'll chime in and say i'm not excited about changing clone either. Like Kyle, I see the workflow issue, but I don't know if changing clone is necessarily the answer without extra thought.
