### ISSUE TITLE
ModelToIdf with matched surfaces in spaces without a thermal zone

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#874]
If a surface is matched to another surface which is in a space with no thermal zone then the adjacent surface is not translated.  The original surface is then in a bad state with surface boundary condition but no referenced object.

**Comment by jmarrec** [comment]
Problem exists between the keyboard and chair. E+ error will be enough to track it down. Changing it would be low-impact, medium effort, so closing it as works as expected
