### ISSUE TITLE
Run and scripts directory  get populated with odd content every time I save my model.

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#879]
I'm using 1.2.5 develop build made today. I can even reproduce this with an empty model after restarting OS app. The run directory has a sql file, eplusout.html. The scripts directory is even populated with scripts, oddly even one that only I probably have. @elainethale thinks my temp project may be corrupted and is not deleted when I quit OS.

Oddly the files directory is empty, no weather file. run directory files for the workflow step are from October 29th. The measure that showing up in scripts directory hasn't only been in existence for a few weeks.

I'm pretty sure this is a new issue, or I would have seen it more making test models for measures.

**Comment by macumber** [comment]
Sounds like this was never reproduced, I assume if this was still active others would be reporting it
