### ISSUE TITLE
 E+ translator warning: Unknown object OS:ClimateZones

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#883]
Cosmetic only

**Comment by macumber** [comment]
I fixed this

**Comment by andrewmcalpin** [comment]
How did you go about fixing this @macumber?  I have the same error with OS:ClimateZones on ModelToIDF.

**Comment by macumber** [comment]
@andrewmcalpin the fix is in this commit https://github.com/NREL/OpenStudio/commit/579c9e8eea7df9c39d2b1629bbe7fdd09c0db419

I was being lazy when I closed the ticket because I didn't think anyone was watching :-)
