### ISSUE TITLE
NMBE calculated has opposite sign

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#886]
https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/UtilityBill.cpp#L899

should be:

sumError += (*modelConsumption - convertedConsumption);

Calibration measure computes this correctly for each bill

**Comment by DavidGoldwasser** [comment]
FYI @brianlball

**Comment by jmarrec** [comment]
Permalink: https://github.com/NREL/OpenStudio/blob/7cec475621233fcd772de2c6715ef9252bcbb7a6/src/model/UtilityBill.cpp#L876

**Comment by jmarrec** [comment]
The only occurence of similar code I can find on the openstudio-calibration-gem repo appears correct: https://github.com/NREL/openstudio-calibration-gem/blob/f45c3cafccc06035403b31ece0b64d794a74f75f/lib/measures/TimeseriesObjectiveFunction/measure.rb#L617-L620

All other measures, including calibration_reports uses the SDK code. I'm closing this.
