### ISSUE TITLE
Show District Heating and Cooling End-uses in Results Summary Graphs

### ISSUE THREAD

**Issue by muh182** [NREL/OpenStudio#891]
@evanweaver OpenStudio GUI does not visualize the district heating or cooling end-uses in the graphs. Therefore, for any ideal air loop, the electricity and gas consumption graphs do not show the values. Probably, on the back-end, only electricity and natural gas tables are queried.

Here is an example of the graphs for an ideal air loop model:
![image](https://f.cloud.github.com/assets/2249257/2349112/33d51b46-a560-11e3-8a42-c34969f8926b.png)

while the natural gas table shows all values are zero:
![image](https://f.cloud.github.com/assets/2249257/2349121/55100172-a560-11e3-91f4-eaadbb0390a8.png)

the district heating table shows the heating end-use
![image](https://f.cloud.github.com/assets/2249257/2349123/65e5d12a-a560-11e3-95de-a90f5a5ca605.png)

FYI: @kbenne

**Comment by macumber** [comment]
@DavidGoldwasser is this complete?

**Comment by DavidGoldwasser** [comment]
Yep, new measure does this
