### ISSUE TITLE
WWR test measure can make surfaces that SketchUp Plugin things are not contained

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#893]
I have tried a variety of configurations, this is the first time I hit this issue. I can commit this test later.

It is very possible the surfaces are fine 

![3-6-2014 1-06-59 pm](https://f.cloud.github.com/assets/4857055/2350034/42bd94d4-a56b-11e3-9ef3-e4d6e7ae19af.png)
and that this is a plugin bug.

**Comment by macumber** [comment]
@DavidGoldwasser is this still valid?

**Comment by DavidGoldwasser** [comment]
I haven't seen any use reports of it recently.
