### ISSUE TITLE
Support thermal zone rendering color for plenums

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#894]

**Comment by jmarrec** [comment]
Tested in OS App 2.7.1, it works already:

![image](https://user-images.githubusercontent.com/5479063/53501510-9a5bbc80-3aac-11e9-89c5-7572eadd75fe.png)

![image](https://user-images.githubusercontent.com/5479063/53501538-a8114200-3aac-11e9-9d0c-bcfafb7af5cd.png)
