### ISSUE TITLE
PAT file menu - There is no cancel option if you choose "Exit".

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#9]
There is a dialog to save or not save your model, but there is also an "x" at the top right of the dialog box. I clicked that expecting it to function as a cancel but it functions as a "No" to saving your model and still exists.

It would be nice if this acts as a cancel option, or if we explicitly add a cancel button to the dialog.

**Comment by DavidGoldwasser** [comment]
Not sure if still valid.

**Comment by macumber** [comment]
Clicking X button prompts you with "Save - Yes/No" there is no cancel option
File->exit prompts you with "Save - Yes/No" there is no cancel option

Let's close this and open a feature request for a cancel option if needed
