### ISSUE TITLE
Schedule Tab - Calendars should show up on right when schedule is selected (Bugzilla #607)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#90]
On 2012-03-09 09:32:56, @DavidGoldwasser wrote:

> You shouldn't have to pick a profile to see the schedules.

On 2012-03-09 09:47:54, @DavidGoldwasser wrote:

> <these were reported by Andrew but logged by me>

On 2013-01-10 11:36:57, @DavidGoldwasser wrote:

> <batch comment: added this to Pivotal Epic, https://www.pivotaltracker.com/epic/show/458473>

**Comment by DavidGoldwasser** [comment]
@macumber, this is another one we discuss the other day. It is about not having blank display when schedule is selected. I think you were going to have it select the default profile, which would then also show the schedules at the right.

**Comment by macumber** [comment]
When I went to implement this there was a problem.  Basically the scene doesn't get drawn correctly if the widget is not visible, this is the case when you click on the schedules tab then click on the schedule sub tab.

**Comment by macumber** [comment]
Fix would be to redraw the scene when you click on the schedule sub tab.  Not terribly hard, I just didnt do it
