### ISSUE TITLE
Cloud does not appear to work on Ubuntu

### ISSUE THREAD

**Issue by elainethale** [NREL/OpenStudio#908]
My credentials work to see the Cloud Monitor on my Windows machine, but not on my Ubuntu machine. (I am fairly sure this is a platform issue and not a developer build/branch issue, but will know for certain once I have a build to test on Windows.)

**Comment by axelstudios** [comment]
Old bug... it was fixed at some point:

![image](https://cloud.githubusercontent.com/assets/411466/9593249/6f5c60e8-5009-11e5-9dbc-90970e44b4ec.png)
