### ISSUE TITLE
Schedule Tab - simplify making new rule/profile buy getting rid of "Add" button (Bugzilla #613)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#91]
On 2012-03-10 14:35:03, @DavidGoldwasser wrote:

> We used to show option to make a new profile or copy an existing one. When you first clicked to get a new profile you would pick a radio button and then click "Add". Now there is only one option, so I think when you click the green "+" to make a new rule/profile, it should just show up, vs. having to click a second button.
> 
> If we do keep the "Add" button might be nice to have it dock at the left side of the screen vs. centering in the screen. It is kind of lost in the middle of nowhere on a large screen.

On 2013-01-10 11:37:02, @DavidGoldwasser wrote:

> <batch comment: added this to Pivotal Epic, https://www.pivotaltracker.com/epic/show/458473>

**Comment by DavidGoldwasser** [comment]
@macumber is working on this now. I'll re-assign it to him, and label as feature.

**Comment by macumber** [comment]
@DavidGoldwasser was this addressed by my GUI updates for 1.7.0?

**Comment by DavidGoldwasser** [comment]
yep
