### ISSUE TITLE
Space Types Tab - Space Infiltration box is so small no text shows (also on building tab (Bugzilla #621)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#92]
On 2012-03-13 14:02:44, @DavidGoldwasser wrote:

> By, the way I see full display text on mouse over now. Great!

On 2012-03-15 15:14:38, @DavidGoldwasser wrote:

> Talking with Kyle and Dan I moved this to P3 and took out of Pivotal.

**Comment by DavidGoldwasser** [comment]
deprecated, this was pre-grid view. May still be issue on facility tab, but that will become gridview as well
