### ISSUE TITLE
Make fenestration measure handle model with no default construction

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#929]
Currently it the measure runs but simulation fails without skylight construction. Or templates don't have this default. The measure could just make a new one.

**Comment by macumber** [comment]
@DavidGoldwasser is this done?  Also if this is a measure that you maintain can you assign to yourself?

**Comment by DavidGoldwasser** [comment]
@macumber  @asparke2  I think the measure has been updated, this is now mainly as reminder to update templates with skylight constructions. Maybe some work has been done on this in the standards spreadsheet

**Comment by DavidGoldwasser** [comment]
@DavidGoldwasser move this to measure repo issue as an enhancement.

**Comment by DavidGoldwasser** [comment]
This is still valid, but should probably go in standards repo. Const. set should always give skylight construction. Also noticed glass door is missing, maybe that can use exterior window construction.

cc: @asparke2
