### ISSUE TITLE
  OpenStudio::convert doesn't seem to work in arguments section of IDF measure

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#932]
Below is an example
apRatio.setDefaultValue(OpenStudio::convert(10.0,"m","ft").get)

While these measures work in workspace vs. model, I still thought I would have access to do conversions like this? Or maybe the issue is that it is in the arguments vs. run section of the measure?

@macumber any thoughts on this. For now I'm just going to hard code the number without relying on OpenStudio::convert.

**Comment by macumber** [comment]
@DavidGoldwasser can you confirm if this is still valid?

**Comment by macumber** [comment]
@DavidGoldwasser I think this is closed, can you confirm?

**Comment by macumber** [comment]
@DavidGoldwasser I think this is closed, can you confirm?
