### ISSUE TITLE
hitting E+ error on specific heat of new default materials

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#934]
*\* Severe  *\* Out of range value Numeric Field#4 (Specific Heat), value=0.10000, range={>=100}, in MATERIAL=AEDG-K12 EXTERIORSHADE-MAT
   *\* Severe  *\* Out of range value Numeric Field#4 (Specific Heat), value=0.10000, range={>=100}, in MATERIAL=AEDG-K12 LIGHTSHELF-MAT

I hit this in fenestration measure when making new materials.

@macumber I'm going to changethe measure to hard set this in measure, but seems we should be making a valid material by default.

I didn't hit this when I first wrote the measure, but I think I didn't assign a construction until I added cost in.

**Comment by DavidGoldwasser** [comment]
@kbenne @tijcolem this is still an issue now, I was surprised to see how old it is.

**Comment by joseph-robertson** [comment]
So I can update minimum Specific Heat on the OS:Material object in the idd to be 100, and then set the default value on Standard Opaque Material to a reasonable, say 1400 (between eplus docs 800 and 2000).

But what about other properties (thickness, conductivity, density, etc) and other material types? Should we change anything there?

**Comment by DavidGoldwasser** [comment]
@joseph-robertson I am fine if you have better defaults for other fields, but other than specific heat, they are not causing E+ failure with default value.
