### ISSUE TITLE
Create From External File + facility.exteriorLights crashes ruby

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#937]
If you have a model and run the "AddExteriorLights" measure, the measure works fine.  However, if you create a PAT project, load this same model as a design alternative using the "Create From External File" feature, and have "AddExteriorLights" as an always-run measure, ruby crashes on the last line of this code inside the "AddExteriorLights" measure:
```ruby
    facility = model.getFacility
    starting_exterior_lights_power = 0
    starting_exterior_lights = facility.exteriorLights
```
This was reproduced with 1.2.4 and 1.2.5
@elainethale Perhaps something to do with how "ReplaceModel" is copying the model?

**Comment by macumber** [comment]
@asparke2 can you still reproduce this?

**Comment by asparke2** [comment]
@macumber I reproduced this with 1.8.0 by following these steps:

1. Create a PAT project, pick any baseline model
2. Add the Add Exterior Lights Measure as an always-run Measure
3. Create a model from external file.  Pick any model (doesn't need to have any Measure)
4. Run the model.
5. The Add Exterior Lights measure fails with the following stderr:

```
C:/Users/aparker/Desktop/Testing/937 Exterior Lights/937 Test 2/dataPoint2/9-UserScript/mergedjob-1/user_script.rb:163:in `exteriorLights': bad_weak_ptr (RuntimeError)

	from C:/Users/aparker/Desktop/Testing/937 Exterior Lights/937 Test 2/dataPoint2/9-UserScript/mergedjob-1/user_script.rb:163:in `run'

	from mergedjob-0/in.rb:325:in `<main>'
```

**Comment by asparke2** [comment]
Actually accidentally just reproduced again with the Measure AddCostperFloorAreaToUnusedLights.  It works fine when applied to the seed model, it just crashes with the following error on the External File model (which is the same model as the seed model in my case).

```
C:/Users/aparker/Desktop/Testing/PAT External File/PEA Example 180/dataPoint18/236-UserScript/mergedjob-1/user_script.rb:34:in `quantity': bad_weak_ptr (RuntimeError)

	from C:/Users/aparker/Desktop/Testing/PAT External File/PEA Example 180/dataPoint18/236-UserScript/mergedjob-1/user_script.rb:34:in `block in arguments'

	from C:/Users/aparker/Desktop/Testing/PAT External File/PEA Example 180/dataPoint18/236-UserScript/mergedjob-1/user_script.rb:32:in `map'

	from C:/Users/aparker/Desktop/Testing/PAT External File/PEA Example 180/dataPoint18/236-UserScript/mergedjob-1/user_script.rb:32:in `arguments'

	from mergedjob-0/in.rb:266:in `<main>'
```
which points to:
```
if value.quantity > 0 and not value.wattsperSpaceFloorArea.empty?
```
Seems like something is different after a model is loaded from external file vs. how the seed model is loaded.

**Comment by MatthewSteen** [comment]
Had this happen in a 1.8.2 project with several models created from external file, all of which failed during the first fixed measure run (add daylight sensor to space type) but ran successfully in OS.

Updated the project to 1.8.5 and all models created from external file ran successfully.
