### ISSUE TITLE
Cannot make Compressor Rated Superheat or Rated Return Gas Temp Blank

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#945]
In the inspector, you cannot make the fields Rated Superheat or Rated Return Gas Temp in a Refrigeration Compressor blank.  One or the other of these fields must be blank or EnergyPlus throws severe errors.  The only way to fix is to go into the .osm with a text editor.

@kbenne is this caused by error in idd?

**Comment by DavidGoldwasser** [comment]
@kbenne is this still valid? If so any changes needed for 1.9.0?

**Comment by evanweaver** [comment]
Fixed via adding variants to library.
