### ISSUE TITLE
OSMs for medium sized gbXMLs (~5 MB) take too long to open (Bugzilla #636)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#95]
On 2012-03-19 16:19:42, @macumber wrote nothing.

On 2012-03-21 21:47:12, @DavidGoldwasser wrote:

> <Luigi, switched these to "new" from "Unconfirmed" but left priority as is. I just wanted them to show on the open bug list. I don't think any of these should be targeted for 0.7.0. P3 or lower.>
> 
> David

**Comment by DavidGoldwasser** [comment]
I expect this has been addressed by some other plugin improvements.
