### ISSUE TITLE
New Template pull down menus too long for SketchUp Plugin

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#953]
This is partially an SketchUp bug in not being able to scroll properly, but also an issue with having templates pre-loaded with so many choices.

@asparke2 all the more reason for a wizard?

I made this major, because I really don't know if there is a good work around to grab space types you can't see.

![3-27-2014 10-31-15 pm](https://cloud.githubusercontent.com/assets/4857055/2546307/45df102a-b632-11e3-95bd-ab40cd40c33d.png)

**Comment by macumber** [comment]
@DavidGoldwasser can we close this?  You can use the up and down arrows to select any item, is that sufficient?

**Comment by macumber** [comment]
If you close this also delete https://www.pivotaltracker.com/story/show/69514932

**Comment by DavidGoldwasser** [comment]
Yep, makes sense to close it since we are using wizard resulting in shorter list.
