### ISSUE TITLE
Zones Tab - We need to give users feedback to turn on the Thermostat to add schedule, or just turn it on form them. (Bugzilla #639)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#96]
On 2012-03-20 09:15:01, @DavidGoldwasser wrote:

> I was all ready to file a bug that drop zones were broken for thermostats and then after a few minutes realized that I need to turn on the thermostat. I even know this and still forgot about it.
> 
> I think in future releases we need to either turn it on for the user when the drop a schedule there, or alert them of what they need to do.

On 2012-03-21 21:47:12, @DavidGoldwasser wrote:

> <Luigi, switched these to "new" from "Unconfirmed" but left priority as is. I just wanted them to show on the open bug list. I don't think any of these should be targeted for 0.7.0. P3 or lower.>
> 
> David

On 2012-09-07 00:01:16, @DavidGoldwasser wrote:

> *** Bug 542 has been marked as a duplicate of this bug. ***

**Comment by DavidGoldwasser** [comment]
I think grid view in 1.5.0 deprecated the on/off switch for thermostats. Now just drop zones for stepoint schedules
