### ISSUE TITLE
Schedule Tab - When too many schedules you get a horizontal scroll bar (Bugzilla #643)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#97]
On 2012-03-21 09:57:24, @DavidGoldwasser wrote:

> make the column width wider so it can handle the vertical scroll bar without having to also make a horizontal scroll bar.

On 2012-03-21 21:47:13, @DavidGoldwasser wrote:

> <Luigi, switched these to "new" from "Unconfirmed" but left priority as is. I just wanted them to show on the open bug list. I don't think any of these should be targeted for 0.7.0. P3 or lower.>
> 
> David

On 2012-09-07 00:30:20, @DavidGoldwasser wrote:

> OK, I still get this, maybe just let the user resize that pane when this happens (like most other left panes in the app.

**Comment by DavidGoldwasser** [comment]
The horizontal scroll bar is gone.
