### ISSUE TITLE
No default construction for adiabatic surfaces

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#974]
Capturing an email thread between @DavidGoldwasser, Phylroy, and @macumber
1.  Extend the construction set to have fields for adiabatic just like we do for ground, exterior, etc.
2.  Leave construction set as is but have translation treat adiabatic surfaces as interior surfaces (or exterior). Either way at least there is a default, and the user can override the default if they want to.

I think all the proposed approaches are similar in that they only come into play in the E+ translator when we need to pick a construction for adiabatic surfaces.  They differ in their ability to let the user choose what type of construction is used for adiabatic surfaces.  I am not sure if adiabatic surfaces can store heat or not, Edwin do you know?  Does the construction assigned to an adiabatic surface matter at all?  If we do want to let the user choose what construction to use for adiabatic surfaces, I feel it is not intuitive to assign adiabatic surfaces an interior wall construction.  If we want the user to be able to pick what construction is used for adiabatic surfaces then I would prefer we extend the construction set object so it is explicit.

Unsure if adiabatic surfaces can store heat, they do have visible reflectance

**Comment by YixingChen** [comment]
Is this problem solved?

**Comment by macumber** [comment]
@YixingChen no, the only solution currently is to explicitly set the construction for each adiabatic surface.

**Comment by DavidGoldwasser** [comment]
Would be good to get feedback in case we update in the future. Witch of these options sound good, or is there another one.

1. Add adiabatic to the construction set 
2. Leave construction set alone but have adiabatic surfaces take on interior construction.
3. Leave construction set alone but have adiabatic surfaces take on exterior construction.
4. Leave everything as it is but develop a user configurable measure to provide a number of options on how to map constructions to adiabatic surfaces.

There is currently at least a basic user script and measure to work with adiabatic surface, but it is limited.

**Comment by AndaMar3** [comment]
Option 1 is the most universal and versatile option in my opinion. Hopefully, it could be easily added to the 'Other Constructions' in the Construction Set window.

**Comment by jmarrec** [comment]
+1 on using option 1 above

**Comment by robianson** [comment]
Any motion on this issue?

**Comment by DavidGoldwasser** [comment]
@macumber would that be a nice project for @jmarrec :)

**Comment by jmarrec** [comment]
Where would you put the new "Adiabatic" box on the default construction set page?
How would you name it?

Perhaps in "Other Constructions", named "Adiabatic Surfaces"?

![image](https://user-images.githubusercontent.com/5479063/53484147-6b7d2080-3a83-11e9-855c-1ab3e61b4388.png)

**Comment by DavidGoldwasser** [comment]
@jmarrec "Adiabatic Surfaces' under "Other Constructions" seems like a good solution.

**Comment by jmarrec** [comment]
Done in #3439

**Comment by DavidGoldwasser** [comment]
We should make sure this gets in release notes, while it seems small it is a nice enhancement to have. We can also update measures like create bar from building type ratio to make use of this. That measures uses adiabatic for party walls, and also floor/ceiling boundaries when using zone multiplies for tall buildings.

**Comment by jmarrec** [comment]
I wonder if the library sets should set a default adiabatic construction or not

**Comment by macumber** [comment]
Probably should have a default otherwise people will still hit.  I think the templates come from os standards right?  Possibly this default would be added there?  We need to remake our templates for 2.8.0 (there has been a new version of standards released) so we can address then.

**Comment by jmarrec** [comment]
Yes they do come from openstudio standards.

I'm not sure it's a bad thing if people hit this, at least they have a place to conveniently set one instead of hard assigning a construction to each surface.

If we can figure out what we should put in there as defaults then let's do it. Otherwise let it fatal out (or catch it in FT, but currently the eplusout.err is easier to access than FT errors... there's an issue about this though that I'd like to address (will try to link to it tomorrow if I remember))
