### ISSUE TITLE
cloning building doesn't bring over thermostatSetpointDualSetpoint

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#978]
Cloning building from one model to another doesn't bring over thermostats. Directly cloning thermal zones has the same results. @kbenne is this the desired behavior? It makes it tricky for me to bring in ref buildings because I need to bring in and re-wire zones to thermostats manually, (FYI  my workflow is to translate ref IDF to model2, and then clone that building into the original model.

Water use equipment doesn't come in either, but that is how I expect that worked, but still isn't ideal.

cc: @asparke2

**Comment by macumber** [comment]
@kbenne is this fixed?  Can you close it?

**Comment by macumber** [comment]
@kbenne nevermind, I accepted the pivotal ticket I will close
