### ISSUE TITLE
Exterior lights don't make it through reverse translation

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#979]
Seems like pretty direct mapping and would make scripts for reference buildings easier. If we don't support in translation we will have to store this information somewhere else.

Service hot water is in a similar boat, although I understand more complex since it ties into HVAC. Eventually this should be in space type then we can store it with other internal loads.

@asparke2 for now my ref building examples skip these objects.

**Comment by asparke2** [comment]
Closing this because we are not adding new features to reverse translator for the foreseeable future.

**Comment by macumber** [comment]
I am going to re-open this one, we should be supporting loads including exterior lights
