### ISSUE TITLE
Clone building doesn't keep spaces connected to thermal zones

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#980]
This is related to #978 which also relates to cloning a building. In running the simulation after this measure I found that while clone building brings over spaces and thermal zones the spaces are no longer connected to the thermal zones.

@kbenne, @asparke2, and @macumber I assume this isn't the desired behavior.For now I'll rely on another hash to connect these like I did for thermostats.

David

**Comment by macumber** [comment]
@kbenne is this fixed? Can you close it?

**Comment by macumber** [comment]
@kbenne nevermind, I accepted the pivotal ticket I will close
