### ISSUE TITLE
Odd error behavior on installed vs. develop and merged vs. non merged jobs

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#982]
This the screenshots below are from PAT project I'm working on to re-create ref buildings. The first measure in all cases is the exact same measure, and it is to import the building from an IDF into an existing OSM. I use a string argument for the path.

Screenshot 1 shows what I see in my 1.3.1 developer build when I frist click run. Looks like it failed (but see screenshot 2), also notice how other jobs are being processed.
![4-14-2014 3-07-01 pm](https://cloud.githubusercontent.com/assets/4857055/2700915/c409eab6-c419-11e3-93fb-2eb9f4a4fa83.png)

If I wait 5 seconds then the error goes away and things are fine.
![4-14-2014 3-18-51 pm](https://cloud.githubusercontent.com/assets/4857055/2700961/6a6a3636-c41a-11e3-8eeb-f1a33bf44df3.png)

So next I run the same project on my 1.3.1 installed version. I get a cryptic error. @macumber it almost looks like the merge job error reporting fix didn't make it in 1.31?, but that still didn't explain why I have the error in the first place here when it is fine my by develop build.
![4-14-2014 3-11-23 pm](https://cloud.githubusercontent.com/assets/4857055/2700949/52dd601a-c41a-11e3-9f15-f642d6eeebbe.png)

Then I re-ran just one job, and I get an error about it not finding OpenStudio
![4-14-2014 3-11-57 pm](https://cloud.githubusercontent.com/assets/4857055/2700974/a34f0652-c41a-11e3-9384-c1d0e75e8ef6.png)

@axelstudios thought you may want to see this as well.

**Comment by asparke2** [comment]
Closing since we are now using Ruby 2.0.0 exclusively
