### ISSUE TITLE
SU 2014 Ruby 2.0 specific issue with surface search dialog on windows

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#984]
Launch SketchUp and then open the surface search dialog. Try to set a "Class" from the pull down menu. After you make your selection it goes back to being blank. The other pull down menus don't do this.

SketchUp 8 with current development build does not have this issue.

@macumber I'll avoid this tomorrow. I'll just search for outside boundary condition that does work.

**Comment by asparke2** [comment]
Cannot reproduce in 1.6.0 SketchUp 2015
