### ISSUE TITLE
Most reporting measures won't load into app

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#987]
In most cases I get this error
Failed to compute arguments for measure: cannot load such file --erb

But Xcel EDA Reporting and QAQC, and Export Schedules CSV can be dropped into the project.

What is strange is most of the reporting measures that are not working don't have any arguments and have the exact same text in argument def as Xcel measure that does work. @macumber any thoughts, if you have ideas I can try to fix the annual end use breakdown to demo.

  #define the arguments that the user will input
  def arguments()
    args = OpenStudio::Ruleset::OSArgumentVector.new
    
    return args
  end #end the arguments method

**Comment by macumber** [comment]
@DavidGoldwasser I think this is fixed now, can we close?
