### ISSUE TITLE
PAT crash involving directories opened in Explorer

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#989]
This happened when I was running a PAT simulation locally with the Boost 1.55 branch (I wasn't able to reproduce it with the 1.3.0 release).

Steps to reproduce:
1. Run a simulation
2. Open a datapoint directory in Explorer, then hit the "C" button to clear that datapoint (at which point the contents of the folder will be emtpied, but the datapoint directory will remain)
3. Hit the run button again with that datapoint selected

![image](https://cloud.githubusercontent.com/assets/411466/2734443/83c03a68-c654-11e3-80a9-2f77272c55d9.png)

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.
