### ISSUE TITLE
Working with scripts is very rough (Bugzilla #646)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#99]
On 2012-03-30 10:43:41, @macumber wrote:

> The workflow I tried was 1) create an osm with windows in the plug-in, 2) open it in OpenStudio application, 3) add an idf script (https://openstudio.nrel.gov/forums/openstudio-plug-google-sketchup/general-discussion/how-create-double-skin-facade#comment-11430), and run it.
> 
> There were glitches saving the script, it kept moving out of the model dir and into a temp dir.
> 
> When the script failed (as I was developing it, add junk code to reproduce) the errors were not displayed clearly and the play/stop button state changes were confusing

**Comment by DavidGoldwasser** [comment]
I think this is specific to deprecated scripts tab.
