### ISSUE TITLE
Boost 1.55 seems to use both slashes on Windows

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#990]
I've seen it in a couple places:
![image](https://cloud.githubusercontent.com/assets/411466/2734494/1c6a076c-c655-11e3-97e7-8f610e1bc029.png)

**Comment by asparke2** [comment]
@axelstudios is this actually causing any issues, or is it just annoying to look at?

**Comment by axelstudios** [comment]
There were issues initially (@macumber fixed those), so it is simply annoying to look at now.  Probably not worth doing anything about, it's entirely possible that Boost will fix this or that we'll move onto QFileSystem some day which doesn't have these issues.

**Comment by jmarrec** [comment]
We use boost 1.71 now.
